### ISSUE TITLE
[question] How should simpleseq2seq be trained?

### ISSUE THREAD

**Issue by openstring** [allenai/allennlp#1001]
Hi, I am new on deeplearning and NLP, I want to build a simple QA chatbot. but I cannot find train config file or training data for simpleseq2seq model, what should I do to use this model?

**Comment by matt-gardner** [comment]
The seq2seq code is given just as a simple example for where you might start if you want to build seq2seq models with AllenNLP.  We haven't really used it for anything, and so there may still be issues with it, and we don't have any trained models for you to use.  If you want a configuration file for a tiny model, you can look at our test fixtures here: https://github.com/allenai/allennlp/blob/master/tests/fixtures/encoder_decoder/simple_seq2seq/experiment_with_attention.json.
