### ISSUE TITLE
Is transfer learning possible using pretrain Machine Comprehension model?

### ISSUE THREAD

**Issue by BkrmDahal** [allenai/allennlp#1007]
I want to add some more data, similar format as SQuAD to already trained model "https://s3-us-west-2.amazonaws.com/allennlp/models/bidaf-model-2017.09.15-charpad.tar.gz". Same way pre-trained VGG Model are frequently used to Classify Objects in Photographs using transfer learning? Is this doable? Will it help me get a better answer to the type of passage and answer, I might have in the specific field? Or is it same because at end of the day its just passage and answer?

**Comment by matt-gardner** [comment]
You can fine tune a model on new data using the `fine-tune` command.  Whether or not this well help on your task depends on a lot of things, and really is just an empirical question.

**Comment by BkrmDahal** [comment]
Noted. 
Thank you for such wonderful package.
