### ISSUE TITLE
Changing default predictions output

### ISSUE THREAD

**Issue by yanaiela** [allenai/allennlp#1014]
Is there a way to override the default behavior where all the information is printed / written to a file?
When dealing with large datasets, and not needing all that information, it creates unnecessary large files.

**Comment by joelgrus** [comment]
I think the easiest way to do that right now is to create your own predictor. you can just inherit from the one you want and override its `predict_json` and `predict_batch_json` methods.

for example, here's a predictor that's the SRL predictor, except that it removes the "words" from the output:

```
from allennlp.common import JsonDict
from allennlp.service.predictors.predictor import Predictor
from allennlp.service.predictors.semantic_role_labeler import SemanticRoleLabelerPredictor

def remove_words(blob):
    del blob["words"]

@Predictor.register("srl2")
class Srl2Predictor(SemanticRoleLabelerPredictor):
    def predict_json(self, inputs: JsonDict, cuda_device: int = -1) -> JsonDict:
        # call the usual predictor and modify its result
        result = SemanticRoleLabelerPredictor.predict_json(self, inputs, cuda_device)
        remove_words(result)
        return result

    def predict_batch_json(self, inputs: JsonDict, cuda_device: int = -1) -> JsonDict:
        # call the usual predictor and modify its result
        result = SemanticRoleLabelerPredictor.predict_batch_json(self, inputs, cuda_device)
        for blob in result:
            remove_words(blob)
        return result
```

then when you run the command you have to add the flags `--predictor srl2` and `--include-package module.containing.your.new.predictor`
