### ISSUE TITLE
Apply Elmo to non-english task

### ISSUE THREAD

**Issue by HuitingLiu** [allenai/allennlp#1023]
Hi, since the source code is not available (#922),  is it appropriate to apply Elmo to non-english task?

Besides, according to #939, ```python -m allennlp.elmo <args>``` is suggested to be used to dump the vectors for a predefined corpus.  But the command doesn't work actually. 

```No module named allennlp.elmo```

**Comment by matt-peters** [comment]
You can certainly try it on a non-English task but I doubt it would give desirable results.  We plan to release the training code sometime over the next few weeks.

**Comment by HuitingLiu** [comment]
Thanks for the reply.
