### ISSUE TITLE
Mismatch between hosted NER model and "Creating a Model" Tutorial?

### ISSUE THREAD

**Issue by nelson-liu** [allenai/allennlp#1028]
Hi!

On http://allennlp.org/models , in the NER section, it notes that "This model is the "baseline" model described in Peters, Ammar, Bhagavatula, and Power 2017." and that "This is also the model constructed in our Creating a Model tutorial."

After downloading the hosted model and peeking at its config, it looks like it uses some constraints on the CRF that Joel recently added. This doesn't appear in the config at [tutorials/getting_started/crf_tagger.json](https://github.com/allenai/allennlp/blob/master/tutorials/getting_started/crf_tagger.json), so these two models are not the same (contrary to what the site notes). 

I'm not sure if the baseline model in Peters 2017 uses these constraints either. Maybe you want to consider rewording the description of the model on the site and/or adding the constraints to the tutorial config file? Not sure which you would prefer to do.

**Comment by matt-peters** [comment]
Thanks for pointing this out.  We are in the process of re-training the NER model with ELMo to match the performance in the original tensorflow version.  We'll update the description once that's complete and the model is replaced.

FWIW, both of NER models in "Peters, Ammar, Bhagavatula, and Power 2017" and the ELMo paper used constrained decoding to remove invalid tag sequences.

**Comment by schmmd** [comment]
I'll take care of it when I update the NER model to Matt's new model.

**Comment by schmmd** [comment]
Updated the website in https://github.com/allenai/allennlp-website/pull/42.
