### ISSUE TITLE
latest version of docs, please?

### ISSUE THREAD

**Issue by krsnaa** [allenai/allennlp#1029]
Is there a link where the latest docs from the master/pip branch: (https://github.com/allenai/allennlp/tree/master/doc) are reflected?

https://allenai.github.io/allennlp-docs/ - reflects the 0.3 version.
A web interface sure beats trying to read .rst files :)

**Comment by schmmd** [comment]
Updated!  Sorry, we ran into a problem during our recent release.

https://allenai.github.io/allennlp-docs/
