### ISSUE TITLE
Attention matrix in textual entailment demo

### ISSUE THREAD

**Issue by luffycodes** [allenai/allennlp#1033]
Feature request: Can you expose the attention matrix in textual entailment demo?

**Comment by DeNeutoy** [comment]
This probably isn't super high priority for us, but it shouldn't be too difficult -
 you can see[here](https://github.com/allenai/allennlp/blob/master/allennlp/models/decomposable_attention.py#L139) and [here](https://github.com/allenai/allennlp/blob/master/allennlp/models/decomposable_attention.py#L144)
The attention that needs to be returned from the model.
[here](https://github.com/allenai/allennlp/blob/master/demo/src/components/McComponent.js#L162) is an example of the react components that you need to add to the demo. 

Feel free to submit a PR for this - we will definitely accept it. Feel free to ask more questions etc if you need more pointers.
