### ISSUE TITLE
tutorial: links in configuration guide are broken

### ISSUE THREAD

**Issue by stefan-it** [allenai/allennlp#1036]
Hi,

it seems that the all links in `tutorials/getting_started/configuration.md` are broken that point to `http://docs.allennlp.org`. Here's a shortened example:

```bash
 $ grep -rin "docs.allennlp.org" .
./getting_started/configuration.md:18:[`Registrable`](http://docs.allennlp.org/en/latest/api/allennlp.common.html#allennlp.common.registrable.Registrable)
./getting_started/configuration.md:21:a `Model(Registrable)` base class ([we do](http://docs.allennlp.org/en/latest/api/allennlp.models.html#allennlp.models.model.Model)),
./getting_started/configuration.md:38:[`Params`](http://docs.allennlp.org/en/latest/api/allennlp.common.html#allennlp.common.params.Params)
./getting_started/configuration.md:67:[`Dataset`](http://docs.allennlp.org/en/latest/api/allennlp.data.html#allennlp.data.dataset.Dataset)
```

The `docs.allennlp.org` currently points to `https://allenai.github.io` (where no documentation for the links  given links can be found).

The working documentation url is `https://allenai.github.io/allennlp-docs/`. Can I submit a PR with corrected links?

**Comment by joelgrus** [comment]
I think the right solution is to get `docs.allennlp.org` to point to the correct place, let us look into why that's not happening

**Comment by schmmd** [comment]
Fixed (the redirect now works).
