### ISSUE TITLE
span_utils.bio_tags_to_spans fails for BIOUL tags 

### ISSUE THREAD

**Issue by matt-peters** [allenai/allennlp#1043]
```python
from allennlp.data.dataset_readers.dataset_utils.span_utils import bio_tags_to_spans
print(bio_tags_to_spans(['B-PER', 'L-PER']))
```
displays `[('PER', (0, 0)), ('PER', (1, 1))]`

Recommend updating to raise an exception if it encounters any tag not in `('O', 'B', 'I')`.

`span_utils.bioul_tags_to_spans` works for the BIOUL case.

**Comment by DeNeutoy** [comment]
Fixed by #1045
