### ISSUE TITLE
Special tokens @@START@@ and @@END@@ in the seq2seq model don't play nicely with lowercasing

### ISSUE THREAD

**Issue by vidurj** [allenai/allennlp#1049]
`SingleIdTokenIndexer` lowercases the tokens fed to it, if `lowercase_tokens` is set to `true`. This lowercases the special tokens `@@START@@` and `@@END@@` too. This causes problems such as at line 361 of encoder_decoders/simple_seq2seq.py

**Comment by matt-gardner** [comment]
Thanks @vidurj.  I discussed this with @DeNeutoy on slack a little bit ago.  The solution is to use lowercase special tokens, because we want to keep the lowercasing as it is in the token indexers.

**Comment by vidurj** [comment]
That make sense. Thanks!

**Comment by matt-gardner** [comment]
I'm going to re-open this, because we definitely do need to fix the special tokens that we use.
