### ISSUE TITLE
Query regarding the dimension of the output embedding

### ISSUE THREAD

**Issue by nikhilt44** [allenai/allennlp#1050]
Why is the first dimension of the embedding for below sentence 3?
"Bitcoin alone has a sixty percent share of global search"

**Comment by schmmd** [comment]
ELMo has three layers.  The first dimension allows you to choose the layer for which you want the output tensor.

**Comment by nikhilt44** [comment]
Okay, so would the representations from the last layer would be the best quality?

**Comment by matt-peters** [comment]
It depends on what you want to use them for.  I suggest you read the paper associated with this code as it directly answers your question: https://arxiv.org/abs/1802.05365
