### ISSUE TITLE
Splitting text to sentences

### ISSUE THREAD

**Issue by dimidd** [allenai/allennlp#1051]
Hi,

I'm trying to implement a new DatasetReader for a text document, where named entities are wrapped in XML tags. E.g. TEI-like ```<personName>Harry</personName> goes to <orgName>Hogwarts</orgName>.```

I was wondering if AllenNLP has a standard way to split a text to sentences.
[The Language Model reader](https://github.com/allenai/allennlp/blob/master/allennlp/data/dataset_readers/language_modeling.py) states:

> Note that there's one issue that needs to be fixed before this is actually usable for language
>     modeling - the way start and end tokens for sentences are handled is not correct; we need to
>     add a sentence splitter before this will be done right.

Spacy's solution also seems to have [issues](https://github.com/explosion/spaCy/issues/23).

**Comment by DeNeutoy** [comment]
Hello! AllenNLP doesn't focus on core NLP techniques such as sentence segmentation or tokenisation. We almost exclusively use Spacy for this. We likely won't be adding a sentence splitter any time soon, or if we do, it will just be a wrapper around Spacy's `Doc` object.
