### ISSUE TITLE
Lazy datasets and Trainer object

### ISSUE THREAD

**Issue by EgorLakomkin** [allenai/allennlp#1055]
Currently ```Trainer``` class expects iterator, train_dataset and validation_dataset as input.  My question is if I have a **lazy** train and validation datasets - how I should pass it to the Trainer properly? If I just pass some_dataset._read() as the train_dataset - the Trainer will exhaust it after the first epoch and will not be able to continue for the second epoch.

**Comment by joelgrus** [comment]
don't call `_read()` yourself. You should do

```
dataset = my_reader.read()
```

and that will return an iterable object that itself makes a fresh call to `_read()` each time you iterate over it.
