### ISSUE TITLE
some doubts 

### ISSUE THREAD

**Issue by ajay01994** [allenai/allennlp#1057]
Hi All ,
 Thanks for making such a brilliant NLP  library , i have some doubts for a project , can you all tell me how to achieve that using Allen NLP or any of your methods ..

**PROBLEM STATEMENT** - i am trying to create a probability tool for creating scores  of importance eg (9/10, 8/10 or 6/10 ) depending on the  degree of importance ,from a book text corpus , i am trying to calculate the probability of certain topic coming in the exam using previous year question papers . i have around 10 yrs of question papers comprising of 300 question in total from  the same syllabus . but books are different .  since the questions are not straight forward ,  i am unable to do this 

**WHAT HAVE I TRIED** - i tried using topic modelling and  LDA method  in it ,but it gives only important topics or words from a text corpus . i was able to generate important topics from text , using GENSIM library but it couldn't  solve my problem of matching  and comparing it with the questions from the previous years question papers as some times questions were indirect or twisted . 

**WHAT I AM HOPING** -  i  am hoping is there a  way ALLEN NLP library can help me with understanding the indirect questions or twisted questions to generate a topic  which may help in matching it with the topics in book corpus from the same syllabus thus generating a probability of topics occuring in the exam using previous years   question papers . 

Looking forward for your help , any kind of help in  solving this particular problem statement would be of great help to us 

Thanks

**Comment by DeNeutoy** [comment]
Your problem sounds more like information retrieval, which is not the number 1 focus of this library. I would suggest looking into TF-IDF models - you can see basic ones in [sklearn](http://scikit-learn.org/stable/modules/classes.html#module-sklearn.feature_extraction.text).
