### ISSUE TITLE
How to retrain the ELMo BiLSTM

### ISSUE THREAD

**Issue by zhoujunpei** [allenai/allennlp#1061]
Your code about ELMo is really helpful!

Now the code uses the pre-trained BiLSTM for ELMo, and the weights are loaded from file. It seems that the weights are generated by some TensorFlow code, because there are lines of code to transform the form of weights from tf to pytorch in `load_weights` of `elmo_lstm.py`

Could you please describe which code you have used to train the ELMo's BiLSTM, and how to store the weights? For example, if I want to retrain that BiLSTM on another corpus, how could I save the weights and seamlessly make it flow down through the original ELMo code?

Thank you so much!

**Comment by DeNeutoy** [comment]
The code for training ELMo hasn't been released yet. We are planning on releasing it soon. see #1023

**Comment by wasiahmad** [comment]
Have you released the code to train ELMo? It would be helpful if you can advice how can I train ELMo on a different set.  Thank you.

**Comment by matt-peters** [comment]
The code is available in https://github.com/allenai/bilm-tf

**Comment by ianbstewart** [comment]
same question but for the `torch` implementation of ELMO. how can I retrain ELMO on a new dataset? there must be a training file somewhere that I missed.

**Comment by Yupei-Du** [comment]
> The code is available in https://github.com/allenai/bilm-tf

sorry but is there a pytorch implementation for retraining Elmo BiLM? I would like to fit elmo pretrain model with corpus in other domains

**Comment by zhusleep** [comment]
Finally found it!
