### ISSUE TITLE
Do you plan to release soon bilm training code?

### ISSUE THREAD

**Issue by jipatsaa** [allenai/allennlp#1069]
Hi,

First of all thanks for making available ELMO. I saw in a previous post that there is no biLm model training release. So the only option to use ELMO is to use the pre-trained model. Are you planning to release the training code so new models could be trained for other languages other than English?

Thanks.

**Comment by liorshk** [comment]
+1

**Comment by DeNeutoy** [comment]
We will release the code in the next month or so. Thanks for your patience.

**Comment by schmmd** [comment]
The training code is available at https://github.com/allenai/bilm-tf
