### ISSUE TITLE
How to configure serving Demo offline?

### ISSUE THREAD

**Issue by nmstoker** [allenai/allennlp#1073]
This is a great project, so a huge thank you to your organisation! I've been experimenting with the demo recently, as per the instructions here: https://github.com/allenai/allennlp/blob/master/tutorials/getting_started/installation.md

I used pip installation instructions and was able to get around the pip/demo building issue by building with npm from the relevant folder cloned from github.

My problem is that, even once the demo has done the initial download of the model files from S3, it still can't be run offline because it appears to retry the download every time. Is there a configuration file I can change to point to the now downloaded files? Ideally it would check the file presence first (like the maybe_download feature in tensorflow)

If you need further details from me, let me know (I'm away from the computer in question but could include the error output if it's needed but I'm hoping the config will fix if I can just find where it's set 🙂)

Many thanks,
Neil

**Comment by schmmd** [comment]
Hi Neil, it's not re-downloading the models each time but unfortunately our caching mechanism requires a network connection.  Since you don't have a network connection the server cannot determine the model hash, and thus it cannot use the cached model.

I'd like to change our caching strategy so it works when offline, but that's not a top priority presently.

**Comment by nmstoker** [comment]
Many thanks for the swift reply and clear explanation. That makes sense and I understand about the priorities.

By all means close this issue if you think that's best for now.

Thanks again for the project, it's really impressive!

**Comment by DeNeutoy** [comment]
To get around this, you can change the models [here](https://github.com/allenai/allennlp/blob/master/allennlp/commands/serve.py#L31) to point to the local versions - then the file caching won't try to download them at all.
