### ISSUE TITLE
Mechanism for a parallel data/batch preparation

### ISSUE THREAD

**Issue by EgorLakomkin** [allenai/allennlp#1083]
I trying to adapt allennlp library to use it for audio+text data processing and stumbled upon the issue that data loading/feature extraction (from audio) is a bottleneck (GPU utilization is very low). I like how Dataset+DataLoader is done in PyTorch and I am wondering if it is possible somehow to implement or reuse within the AllenNLP framework (I really enjoy the idea of making configurable experiments). Or maybe there is an experimental code somewhere which tackles this issue?

**Comment by matt-gardner** [comment]
I know that @nelson-liu was going to look into this a while ago, but I haven't heard back from him (no worries, @nelson-liu, I know you've got your own stuff to do).

Are you using a lazy dataset, or loading all of the data up front?  That is, is the bottleneck in `DatasetReader.read()`, or in `Batch.as_tensor_dict()`?  And is the slowness the same for all epochs, or does it get better after the first epoch?  We could try to add multi-threading in either one of these places, but we'd need to know first which one is the problem.

Also, if you get this working well for audio + text, we'd love to have contributions, and/or host a demo of your model on demo.allennlp.org.

**Comment by matt-gardner** [comment]
Thanks @nelson-liu, that's super helpful.

**Comment by EgorLakomkin** [comment]
Sorry for the delay and thank you for your comments!

Currently, I load and extract audio features in the dataset's _read method. If for example I set the batch size to 64, loading audio and extracting features really becomes a bottleneck. Maybe I should then make several workers that load file and extract features and _read method would just poll the queue for new samples

**Comment by matt-gardner** [comment]
If your iterator is not lazy, this all happens upfront, right?  But you said GPU utilization is low, so you're probably using a lazy iterator?  One option that we've done before is create a preprocessing script that does expensive data processing upfront, and then write a simpler dataset reader that reads the preprocessed data.  This would be a lot easier than writing multi-threading code, I think.

**Comment by EgorLakomkin** [comment]
The dataset is lazy and as I would need to have augmentations during training I guess I would need to write a multi-threaded version

**Comment by matt-gardner** [comment]
Fixed in #1760.
