### ISSUE TITLE
How to connect to serve api via Docker

### ISSUE THREAD

**Issue by loretoparisi** [allenai/allennlp#1089]
Looking at the api demo, I have tried to connect to the NER api in the same way the demo does from the docker host (where the port 8000 is correctly exported):

```
curl --header 'Accept:application/json' --header 'Content-Type:application/json' -v -X POST  -D '{"sentence": "Did Uriah honestly think he could beat The Legend of Zelda in under three hours?"}' http://localhost:8000/predict/named-entity-recognition
```

But I get no response from the api in the container, I have my container up and running and I have opened both the ports 8000 and 3000 in order to run the demo as well from the docker container:

```
$ docker run --rm -p 8000:8000 -p 3000: 3000 allennlp/allennlp:v0.4.1 python -m allennlp.run serve
6ffefe6e260c
$ docker ps
CONTAINER ID        IMAGE                      COMMAND             CREATED             STATUS              PORTS                                            NAMES
6ffefe6e260c        allennlp/allennlp:v0.4.0   "/bin/bash"         4 minutes ago       Up 4 minutes        0.0.0.0:3000->3000/tcp, 0.0.0.0:8000->8000/tcp   peaceful_wilson
```

In this way I can see the demo at http://localhost:3000, but from there I get the same api error on the port `8000`, i.e. a `failed` status of the `fetch` api in the demo.
I have checked the `flask` server that you are using, and runs on all interfaces (`0.0.0.0`), so this should be enough to make it working on the exposed port `8000` from the container's host.

By the way according to the docs, the docker run command `allennlp.run serve` should serve the api and the demo as well as described [here](https://github.com/allenai/allennlp/blob/master/allennlp/commands/serve.py#L59), but for some reason it does not.

**Comment by joelgrus** [comment]
try using lowercase `-d` for the data, not `-D`, that makes your example work for me.

(closing, but re-open if that doesn't fix it)

**Comment by loretoparisi** [comment]
@joelgrus thanks that was the typo!
