### ISSUE TITLE
RuntimeError: cuda runtime error (10) : invalid device ordinal at torch/csrc/cuda/Module.cpp:88

### ISSUE THREAD

**Issue by wasiahmad** [allenai/allennlp#1090]
If I use the following:

`ElmoEmbedder(self.config.optfile, self.config.pretrained, cuda_device=0)`

then ElmoEmbedder works. But if I set cuda_device to any other value, then it throws the following error.

`RuntimeError: cuda runtime error (10) : invalid device ordinal at torch/csrc/cuda/Module.cpp:88`

I have tried on a server with 3 GPUs. Only setting cuda_device to 0 works, 1 and 2 doesn't work. What is the problem?

**Comment by matt-gardner** [comment]
We're going to need more of a stack trace to be able to help you.  Probably you're not putting your input tensors, or some other piece of your model, on your GPU.

**Comment by matt-gardner** [comment]
Oh, sorry, didn't look at the error closely enough.  That sure looks like you don't have a GPU that's available to the code.

**Comment by matt-gardner** [comment]
I had a couple of messages I put on here that I deleted, because I posted before really understanding your problem.  I'm not sure why devices 1 and 2 don't work, but maybe @DeNeutoy can help.

**Comment by DeNeutoy** [comment]
please post the full stack trace, so we can help you more easily.

**Comment by wasiahmad** [comment]
In the full stack trace, there is not much information. In the program, I get error in this line:

`self.elmo_embedder = ElmoEmbedder(self.config.optfile, self.config.pretrained, self.config.gpu_id)`

Where if `self.config.gpu_id` is set to 0, it works just fine but if I set it to 1 or 2, it throws the error. I am running the program with `CUDA_VISIBLE_DEVICES` set to the corresponding GPU id.

**Comment by matt-gardner** [comment]
If `CUDA_VISIBLE_DEVICES` is set to a single value of the corresponding GPU id, then you should just use `self.config.gpu_id = 0`, and it will use the right GPU.  You should be able to verify this by using something like `nvidia-smi`.

**Comment by wasiahmad** [comment]
oh, I got your point. Since only one GPU id is visible, then I should use gpu_id 0, not 1 or 2. I think I realized my mistake. Thanks!

**Comment by serser** [comment]
unset CUDA_VISIBLE_DEVICES
