### ISSUE TITLE
ELMo returns only one 1024d representations but expecting 3, 1024d vectors

### ISSUE THREAD

**Issue by wasiahmad** [allenai/allennlp#1091]
I have tried to use [Elmo](https://github.com/allenai/allennlp/blob/master/allennlp/modules/elmo.py) class but it only provides 1024d vectors but I want 1024d vectors for each layer of ELMo. How can I get that?

**Comment by schmmd** [comment]
If you follow [this documentation](https://github.com/allenai/allennlp/blob/v0.4.0/tutorials/how_to/elmo.md#using-elmo-programmatically) you should get 3 vectors back for each ELMo layer.
