### ISSUE TITLE
Question about argument: --serialization-dir

### ISSUE THREAD

**Issue by juexZZ** [allenai/allennlp#1093]
According to the tutorial, this command : 
The **serialization-dir** argument specifies the directory where the model's vocabulary and checkpointed weights will be saved
So when I was trying to run a BiDAF model with default config,  I ran into an config ERROR:

> Serialization directory (/mydir) already exists

My command is just like that in the tutorial, only changed the json file into bidaf.json, and changed the serialization dir into /mydir
Is this suppose to be a existing directory so the vocabulary and weights can be saved? If so, why dose this error occur? Or am I missing something out due to lack of experience? Then how to use this argument currectly?
Thanks!

**Comment by matt-gardner** [comment]
I'm afraid that's not an allennlp issue, it's a pytorch / cuda issue, and I don't know how to help you resolve it.  You could try just using our docker image, as that environment is known to have working package versions installed.  You could also grab the docker image just to compare versions of the various libraries, so you can be sure to install ones that work.
