### ISSUE TITLE
Will you release the training code for ELMO?

### ISSUE THREAD

**Issue by jifan-chen** [allenai/allennlp#1097]
Hi,

I am working on a project and I want  to incorporate ELMO in my model, but embedding size of the pre-trained ELMO is too large for my application. Can you please release the training code so I can train my own weights of the ELMO model.

Thanks

**Comment by schmmd** [comment]
Hi @jifan-chen, we plan to release the ELMo training code soon, as well as a smaller ELMo model.

**Comment by schmmd** [comment]
It's available at https://github.com/allenai/bilm-tf
