### ISSUE TITLE
Similarity Method between question and Passage

### ISSUE THREAD

**Issue by rashikaanand** [allenai/allennlp#1098]
I am curious to know why linear similarity was adopted as the method for creating a similarity matrix between question and passage instead of cosine similarity or any other similarity measure?

**Comment by DeNeutoy** [comment]
See appendix B in the [Bidirectional Attention Flow Paper](https://arxiv.org/abs/1611.01603). Learning a similarity function results in slightly better performance. Does that help?

**Comment by rashikaanand** [comment]
okay Understood 
Thanks
