### ISSUE TITLE
Which of the columns in the *_conll File Format are required in order to train the neural coref in a new dataset?

### ISSUE THREAD

**Issue by negacy** [allenai/allennlp#1101]
I am interested in training the end-to-end neural coref system on a new dataset. I think the dataset has to be formatted as in the [CoNLL 2012 dataset](http://conll.cemantix.org/2012/data.html), which could have multiple columns. Of all those columns, which ones are must have in order to train the system on a new dataset?

**Comment by DeNeutoy** [comment]
The last column is required. However, the current way we read the CONLL files requires that the other columns be populated, because they are read by the [Ontonotes reader](https://github.com/allenai/allennlp/blob/master/allennlp/data/dataset_readers/dataset_utils/ontonotes.py#L83).
