### ISSUE TITLE
type error when calling 'adagrad' optimization method

### ISSUE THREAD

**Issue by phiedulxp** [allenai/allennlp#1102]
when recover from last training process , get the exception:

state['sum'].addcmul_(1, grad, grad)
TypeError: addcmul_ received an invalid combination of arguments - got (int, torch.cuda.FloatTensor, torch.cuda.FloatTensor), but expected one of:

(torch.FloatTensor tensor1, torch.FloatTensor tensor2)
(torch.SparseFloatTensor tensor1, torch.SparseFloatTensor tensor2)
(float value, torch.FloatTensor tensor1, torch.FloatTensor tensor2)
didn't match because some of the arguments have invalid types: (int, torch.cuda.FloatTensor, torch.cuda.FloatTensor)

**Comment by DeNeutoy** [comment]
Thanks - this is the same issue as #998

**Comment by matt-peters** [comment]
Fixed in #1144
