### ISSUE TITLE
Problem about installation with correct cudnn version

### ISSUE THREAD

**Issue by juexZZ** [allenai/allennlp#1116]
Forgive me to have to ask such a question that may seem silly even for a novice.
I installed the allennlp following exactly the instructions in your tutorials, but when I tried to run an allennlp model with default config I always get  the Runtime Error: CUDNN_STATUS_NOT _INITIALIZED
After doing some searching, I figured that this might be a problem about cudnn versions. So I tried:
pytorch0.3.1 with cuda8.0 and cudnn 7.1/cudnn 6
pytorch0.3.1 with cuda9.0 and cudnn 7.0
But none of them works. So I'm wondering if anyone can provide a configuration that can work? 
I've been tortured by the problem for days, and really appreciate any kind help :)

**Comment by juexZZ** [comment]
Well，I just tried the simple_tagger in the tutorial using the GPU in the same virtual environment using the same GPU and it worked! So why BiDAF can't?

**Comment by matt-gardner** [comment]
Have you tried using our docker image?

**Comment by juexZZ** [comment]
Not yet... I remember you saying so in my last issue... I've never used docker before, gonna have to install it first...But still it's so strange that why this approach is not working

**Comment by matt-gardner** [comment]
And, again, this is a pytorch problem. You'll have a lot more luck asking for help on a pytorch forum, where there are more people who might be familiar with your issue. You'll want to give more specifics about what GPU you're using, and such.

The reason you see the problem with BiDAF and not the simple tagger is that BiDAF uses a CNN and the tagger doesn't.

**Comment by juexZZ** [comment]
Oooh right! It indeed has something to do with the CNN. I will go to the forum, sorry for bothering you with such question! Thank you again!
