### ISSUE TITLE
data_iterator unnecessarily rebuilds the dataset on every epoch

### ISSUE THREAD

**Issue by ibeltagy** [allenai/allennlp#1128]
data_iterator unnecessarily rebuilds the dataset on every epoch, which significantly slows things down.

`DataIterator. __call__` calls `DataIterator._yield_one_epoch` for every epoch. Each call of `DataIterator._yield_one_epoch` shuffles the input data, maps it to tensors and chops it into batches. In the non-lazy mode however, most of this work can be done only once before the first epoch, not before every epoch. 

In my application, about 55% of the training runtime is spent in the `DataIterator._yield_one_epoch` function. 

Assuming non-lazy mode, and assuming we don't want to reshuffle before every epoch, fixing this should be easy (call `DataIterator._create_batches` outside `DataIterator._yield_one_epoch`).

**Comment by matt-gardner** [comment]
There are two possible solutions here:

1. We use multi-processing to offload the data processing code done each batch away from the main thread, so it's not a bottleneck during training.  We'd like to do this soon, but it's not coming in the near future.
2. Write your own `DataIterator` that only `creates_batches` once, caches that result, and then just shuffles those at every epoch.  This should be pretty easy to do, and you could contribute it back as a PR.  It _might_ be reasonable to just add this as an option to our existing `DataIterators`, but I'd need to look more carefully at the code before I was confident about that.

**Comment by ibeltagy** [comment]
I will give the second solution a try

**Comment by matt-gardner** [comment]
This is fixed.
