### ISSUE TITLE
Production

### ISSUE THREAD

**Issue by augmen** [allenai/allennlp#1135]
Is AlienNLP is production ready ?

**Comment by schmmd** [comment]
@augmen that depends on what you mean by "production ready" 😀 

Our main target users are research scientists developing SOTA models for publications, but that doesn't mean AllenNLP can't be used in a production environment.  I would program defensively however, as we have not extensively tested AllenNLP at scale.

Do you have specific concerns/questions?

**Comment by augmen** [comment]
ok, any suggestions on production deployment of AllenNLP ? Any packages to be added / scripts to be changed ?

**Comment by schmmd** [comment]
It really depends on your application, its architecture, and the technologies you are familiar with.  I would be inclined to run AllenNLP with a few replicas on a Kubernetes cluster so if an individual application failed the service would not fail as a whole and I could scale for increased load.  You could re-use the REST API provided by the demo for predictions.
