### ISSUE TITLE
Is manually moving optimizers to CUDA on restart necessary after upgrading to pytorch 0.4?

### ISSUE THREAD

**Issue by matt-peters** [allenai/allennlp#1146]
Currently, we manually move optimizer state to GPU on restart.  This may not be necessary after upgrading to pytorch 0.4.  See #1144

**Comment by matt-peters** [comment]
Not sure, one way to check whether it is still need is to revert the change in #1144 , train a model on GPU, then try to restart on GPU.  I won't have time to investigate in the near term.

**Comment by schmmd** [comment]
I'm closing this, since it's about Pytorch 0.4 and we're on PyTorch 1.
