### ISSUE TITLE
SpacyWordSplitter.split_words() and .batch_split_words() behave inconsistently

### ISSUE THREAD

**Issue by joelgrus** [allenai/allennlp#1147]
https://github.com/allenai/allennlp/blob/master/allennlp/data/tokenizers/word_splitter.py#L182-L189

.split_words() filters out whitespace tokens, .batch_split_words() doesn't. they should both filter out whitespace tokens.

this means that if you use this word splitter in your tokenizer, `tokenize()` and `batch_tokenize()` will also behave inconsistently.

**Comment by schmmd** [comment]
@joelgrus are you planing on addressing this?  If so, can you self-assign?

**Comment by joelgrus** [comment]
sure
