### ISSUE TITLE
Symbols and image predictions

### ISSUE THREAD

**Issue by augmen** [allenai/allennlp#1160]
Can NLP can predict / detect science symbols like circumference , diameter , time, velocity etc.   like
```
The bulk modulus of a spherical object is ‘B’. If it is subjected to uniform pressure ‘p’, the fractional decrease in radius is 
(1) p (2) B/ 3p  (3) 3p/ B (4) 3B

```

```
Can NLP detect chemistry formulas as H2O , CH2O6 , CO2 etc .?  like ```
The equilibrium constants of the following are. 
N2 + 3H2  2NH3  k1
N2 + O2  2NO k2 
The equilibrium constant (K) of the reaction:
[Mn(CN) ]
2NH 5O K 2NO3HO,willbe
```
```


Can it identify the image with same name snd predict ? like putting a Question : "how Eiffel Tower paris look like ?" the answer return with Image and description for Eiffel tower.

**Comment by DeNeutoy** [comment]
This is, in general, quite a difficult problem, as in normal text these symbols/characters won't be parsed correctly by a parser trained on web/news text. I suggest that you start with trying to extract these types of symbols using a pattern matching approach, for instance using [Spacy.io](https://spacy.io/). For your second question, AllenNLP doesn't deal with images currently, so it's unlikely to be the right library for you. Re-open if we haven't addressed your questions!
