### ISSUE TITLE
The output from ElmoEmbedder's embed_file conflicts with h5py naming convention

### ISSUE THREAD

**Issue by gabrielStanovsky** [allenai/allennlp#1163]
If I understand correctly, [```embed_file```](https://github.com/allenai/allennlp/blob/master/allennlp/commands/elmo.py#L296) normally stores an h5py Dataset for each sentence in the input file. 
However, if the input sentence contains a forward slash, it will instead store an h5py **Group** object, collecting all sentences with a common prefix. 
See h5py documentation [here](https://support.hdfgroup.org/HDF5/doc1.6/UG/09_Groups.html).

For instance, embedding the following raw sentences will store one Group (containing the embeddings of the first two sentences) and one Dataset object (containing the embedding for the first): 

```
test / this is a first sentence
test / this is a second sentence
this is a third sentence
```

This is probably not the expected behavior?
Can escaping the forward slash character be a good solution?
So far, I couldn't find how to do that nicely in h5py.

@schmmd

**Comment by matt-peters** [comment]
Has this been a problem for you in practice?  I've noticed this previously but have ignored it as it isn't a practical problem (e.g. h5py is tolerant of these slashes when loading and has the desired behavior).

**Comment by matt-peters** [comment]
I usually iterate over the original text file with the complete sentences, then select them from the hdf5 file to work around this.  Something like

```
with h5py.File(embedding_file, 'r') as fh5, open(text_file, 'r') as ftext:
    for line in ftext:
        embeddings = fh5[line.strip()]
```

It's a little annoying but not terribly.  Agree this could be cleaned up if there is an easy way to do it.

**Comment by gabrielStanovsky** [comment]
Thanks!
A small downside of this workaround IMO is that requires having the raw file, as well as more I\O operations when retrieving the sentences.

**Comment by schmmd** [comment]
I agree that ideally you wouldn't need the raw file, although I'm not sure of the best fix presently.

**Comment by tuvuumass** [comment]
Should we add <S> and </S> to sentences in the input file?

**Comment by schmmd** [comment]
@gabrielStanovsky would @DeNeutoy 's suggestion work for you?  I like having the results indexed by the sentence text, but the current behavior and interpretation for `/`s is pretty obnoxious.

**Comment by matt-peters** [comment]
Thanks for the code snippet!   If we added that to the library we could maintain the current format, and reference it as the supported method to read it the embeddings without the original raw text file.

**Comment by schmmd** [comment]
@matt-peters suggestion is my favorite, given where we currently are.

**Comment by schmmd** [comment]
Relatedly:

Might be related to https://github.com/allenai/allennlp/issues/1163
Running `allennlp/elmo` on sentences with “/” seems to cause issues with h5py.

Input file:
```
To Slip off, to take off noiselessly or hastily: as, to dip of one's shoes or garments.
U.S., speak in debate); set of rooms &c. on same level in house (ground/.```

Error:
```python allennlp/run.py elmo --all input.txt output.hdf5
2018-06-19 00:33:33,866 - INFO - allennlp.commands.elmo - Initializing ELMo.
2018-06-19 00:33:40,728 - INFO - allennlp.commands.elmo - Processing sentences.
1it [00:00,  1.84it/s]
Traceback (most recent call last):
  File "allennlp/run.py", line 18, in <module>
    main(prog="allennlp")
  File "/home/tushark/Github/allennlp_master/allennlp/commands/__init__.py", line 70, in main
    args.func(args)
  File "/home/tushark/Github/allennlp_master/allennlp/commands/elmo.py", line 316, in elmo_command
    args.batch_size)
  File "/home/tushark/Github/allennlp_master/allennlp/commands/elmo.py", line 297, in embed_file
    data=output
  File "/home/tushark/anaconda3/envs/allennlp_master/lib/python3.6/site-packages/h5py/_hl/group.py", line 119, in create_dataset
    self[name] = dset
  File "/home/tushark/anaconda3/envs/allennlp_master/lib/python3.6/site-packages/h5py/_hl/group.py", line 287, in __setitem__
    h5o.link(obj.id, self.id, name, lcpl=lcpl, lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 202, in h5py.h5o.link
RuntimeError: Unable to create link (name already exists)
```

**Comment by schmmd** [comment]
Unassigning myself since https://github.com/allenai/allennlp/pull/1257 is stalled and I don't have time to work on another solution.

**Comment by schmmd** [comment]
Fixed by https://github.com/allenai/allennlp/pull/1397
