### ISSUE TITLE
ImportError: cannot import name 'batch_to_ids'

### ISSUE THREAD

**Issue by tuvuumass** [allenai/allennlp#1176]
I installed allennlp but got the following error when running the example in the ELMo tutorial "Using ELMo programmatically" at
https://github.com/allenai/allennlp/blob/master/tutorials/how_to/elmo.md

```
from allennlp.modules.elmo import Elmo, batch_to_ids
ImportError: cannot import name 'batch_to_ids'
```

**Comment by tuvuumass** [comment]
I installed allennlp but don't know why there is no _batch_to_ids_ function in the elmo.py file in allennlp/modules/.

**Comment by DeNeutoy** [comment]
Github defaults to the master branch - for the tutorials to be correct you need to look at the tag corresponding to the version you installed. This was recently updated, which is why it fails.

**Comment by tuvuumass** [comment]
Gotcha. Thanks.
