### ISSUE TITLE
Replicating latest SNLI results - Expected training time?

### ISSUE THREAD

**Issue by danlou** [allenai/allennlp#1180]
I'm trying to replicate your latest SNLI results by running the `config.json` included in https://s3-us-west-2.amazonaws.com/allennlp/models/decomposable-attention-elmo-2018.02.19.tar.gz .
I simply changed the ELMo paths and started training with `python -m allennlp.run train `.

I'm training on a Titan X and getting epoch durations of about 40 min. I'm under the impression that your previous model (w/o ELMo) took much less than that.

Can you tell me if this duration is expected or if I may have to configure something else?

Also, on the ELMo paper your report that it's possible to achieve sota with much fewer epoch on the SRL task. Can you let us know if you've reached a similar conclusion for the SNLI task (and the # epochs for sota) ?

Thanks!

**Comment by schmmd** [comment]
I don't have timing for the new SNLI model, but the old one took around 6 hours end-to-end on a cloud K80 in about 60 epochs.  For internal reference see http://beaker.allenai.org/ex/ex_yl23om9cjw7h/tasks.

**Comment by schmmd** [comment]
@danlou by the way, I like the monolith.

**Comment by matt-peters** [comment]
Hi Dan,

We used the ESIM model (https://arxiv.org/abs/1609.06038) as the baseline model for the ELMo paper, while the SNLI model currently in allennlp is a reimplementation of the Decomposable Attention Model with ELMo (https://arxiv.org/abs/1606.01933).

You can find a slightly modified re-implementation of the ESIM model with ELMo on this branch: https://github.com/matt-peters/allennlp/tree/mp/esim  This is the same model as we described in our paper, with two differences: (1) it does not include GloVe vectors and (2) it only includes one layer of ELMo representations at the input (left column of Table 3 scenario).

This model took about 10 hours to train for 15 epochs on a Titan X, reaching a max dev accuracy of 89.1 after 10 epochs.

The baseline model without ELMo required 4 hours to train for 27 epochs, reaching a max dev accuracy after 22 epochs of 88.4.

**Comment by danlou** [comment]
thanks @schmmd and @matt-peters for the detailed answers!

Being able to experiment with both the Decomposable Attention and ESIM models, even with a few differences, sounds great, and those durations do seem reasonable, thanks for sharing.

To better understand the longer durations I'm experiencing, with the training config I mentioned, I continued training for 14 hours, reaching epoch 26 with these results:
```
Training accuracy : 0.821806    Validation accuracy : 0.845458
Training loss : 0.454282    Validation loss : 0.403409
```

I also noticed that I was maxing out the RAM available (32GB), with:
`Peak CPU memory usage MB: 31900.744`

While GPU was at (12GB):
`GPU 1 memory usage MB: 7247`

The long epoch durations and the maxed out RAM seem suspicious, but I really can't say if it's related to AllenNLP or some other unrelated process.

I'll be experimenting the previous Decomposable Attention training config (w/o ELMo) and that ESIM implementation next. I'll let you know if I run into another performance issue.

**Comment by DeNeutoy** [comment]
Yes, the decomposable attention model with elmo does take a long time to train. We added it to the demo mainly to showcase the performance difference you can get with elmo - i'd certainly advise using the ESIM model, because the decomposable attention model takes longer to converge, which is more damaging when it is not as fast as the original architecture.

**Comment by danlou** [comment]
@DeNeutoy got it, ty!

Are you planning on merging the ESIM model soon ?
It'd make it easier to reference.

**Comment by DeNeutoy** [comment]
We are currently a little busy with conference deadlines - however, we would be very supportive if you would like to take @matt-peters branch, clean it up slightly and open a PR. We can provide a lot of feedback in terms of reviews and help you out with what needs to change in order to get it into master.

**Comment by danlou** [comment]
I'd love to give it a try. I'm also quite busy in the next couple of weeks, for the same reasons, but given that I'll be experimenting with ESIM as part of that work, it may not be too hard to prepare that PR (esp. if you don't mind the missing GloVe vecs and just one layer of ELMo).

I can try to share something by the end of next week, if that's fine for you.

**Comment by tomwesolowski** [comment]
Hello, we also try to replicate your results. Could you tell me how much time does it take to train ESIM+ELMO when adding contextualized embedding in both places - before and after ESIM's BiLSTM?

**Comment by matt-peters** [comment]
Training time is slightly longer, but comparable to the case with one contextualized layer.
