### ISSUE TITLE
`ModelTestCase.ensure_model_can_train_save_and_load` compares last-epoch weights with serialized *best* weights

### ISSUE THREAD

**Issue by joelgrus** [allenai/allennlp#1192]
in particular, if your test case model trained (say) 10 epochs, and got the best results in epoch 5, then the test would fail because it would compare `model.state_dict()` (i.e. epoch 10) with `archive.model.state_dict()` (the weights from epoch 5)

in the meantime I am setting `num_epoch = 1` as a workaround

**Comment by schmmd** [comment]
Fixed
