### ISSUE TITLE
After pytorch 0.4, make `LabelField.as_tensor a 0-tensor?

### ISSUE THREAD

**Issue by joelgrus** [allenai/allennlp#1194]
it feels like that would make sense? although it would break a ton of things. quite likely there are other places where this would make sense too.

(the genesis of this thought was working on the tutorial and having to explain why every use of `labels` requires a `.squeeze(-1)`)

**Comment by matt-gardner** [comment]
Yeah, my initial reaction (before looking into all of the implications in the code) is that this is a good idea.

**Comment by murphp15** [comment]
Could you please explain why every use of labels requires a .squeeze(-1)? 
Maybe we could extract that to a common method for the moment and give it a descriptive name?
