### ISSUE TITLE
Consider pinning dependencies versions

### ISSUE THREAD

**Issue by cristipp** [allenai/allennlp#12]
Please pin all dependency versions in https://github.com/allenai/allennlp/blob/master/requirements.txt.

I would rather not have a Docker image doing one thing, and the same [on paper] Docker image do something else just because they use different dependencies.

```
[good]
pandas==0.19.2

[may break on upstream updates]
awscli>=1.11.91

[i have no idea what code is running]
scikit-learn
```

**Comment by matt-gardner** [comment]
The issue with pinning dependencies is that it also puts restrictions on downstream code.  If you want to use a different version of pandas, e.g., too bad for you.  So, I'm a little conflicted.  I definitely agree that it makes things more sane.  We could give minimum versions, at least...

**Comment by cristipp** [comment]
Sorry for opening this can of worms, especially since I'm not a Python expert. I was thinking from an end user POV, which just wants to get his model trained, today and X months from now. Any dependencies work in this case, unpinned dependencies sound like trouble. After some more reading on the internet, it's possible that pinning the version is my job [as an end user], and accomplished via ```pip freeze```.

https://www.kennethreitz.org/essays/a-better-pip-workflow
https://news.ycombinator.com/item?id=11210370
