### ISSUE TITLE
TestTrainer.test_trainer_respects_keep_serialized_model_every_num_seconds fails when running without GPU on GPU machine

### ISSUE THREAD

**Issue by nelson-liu** [allenai/allennlp#1206]
Rather odd situation: when running the tests on a GPU machine with `CUDA_VISIBLE_DEVICES=""`, [`TestTrainer.test_trainer_respects_keep_serialized_model_every_num_seconds`](https://github.com/allenai/allennlp/blob/master/tests/training/trainer_test.py#L160) consistently fails since each epoch takes a rather sluggish ~1.4 seconds, causing every epoch checkpoint to be saved (thus failing the test).

The easy fix would be to just increase the sleep to 2.5 seconds and `keep_serialized_model_every_num_seconds` to 5, but not sure if that's a fix worth making.

Interestingly, it works fine as is on a machine without a GPU (my macbook). Not too sure what to make of this...

**Comment by nelson-liu** [comment]
looks like it's just flaky in general: http://build.allennlp.org/viewLog.html?buildId=3394&buildTypeId=AllenNLP_AllenNLPPullRequests&tab=buildLog fails for a completely unrelated change @ https://github.com/allenai/allennlp/pull/1203

**Comment by schmmd** [comment]
@matt-peters are you able to take a look?  @DeNeutoy thought you had good context.

**Comment by matt-peters** [comment]
I added this functionality to the Trainer. As for why it's taking so long on a GPU machine with `CUDA_VISIBLE_DEVICES=""` ?  Who knows.  I'm all for the easiest fix here, so the suggestion to change the sleep interval to 2.5 and  keep_serialized_model_every_num_seconds to 5 sounds good to me.

**Comment by nelson-liu** [comment]
Fixed in #1358
