### ISSUE TITLE
Allow Highway to work with n-d inputs

### ISSUE THREAD

**Issue by mttk** [allenai/allennlp#1211]
Hey guys, great work here, thanks a lot!

I've been using your implementation of the Highway network with text data and I got an error while passing a 3d tensor as input, caused by the following lines: https://github.com/allenai/allennlp/blob/master/allennlp/modules/highway.py#L56

Essentially, the assumption is that the input tensor is 2-d. If the input is BxTxD, this assumption causes an issue. While I think this is OK, and the (BxT -> BT) flattening can be left to the user, there is a simple workaround by using `chunk`:

`nonlinear_part, gate = projected_input.chunk(2, dim=-1)`

Which does the same thing as lines 56 & 57, without the input dimensionality assumption. This could be a nice addition.

**Comment by matt-gardner** [comment]
Yes, we've typically used `TimeDistributed` to handle things like this.  But, it also seems reasonable to allow `Highway` to take arbitrary dimensions as input, especially if that `.chunk` operation is faster than what we're currently doing.  A PR would be welcome here.

**Comment by mttk** [comment]
Gotcha, I glossed over `TimeDistributed`, still getting familiar with the lib. 

`.chunk` essentially does the same thing, so I doubt there will be any significant speedup. I'll see if this is true and submit a PR.
