### ISSUE TITLE
Build is failing

### ISSUE THREAD

**Issue by murphp15** [allenai/allennlp#1212]
The build is failing/hanging with the following error: 
Cannot login to registry docker.io (new); Step 4/8
A link to a sample failure: http://build.allennlp.org/viewLog.html?buildId=3381&buildTypeId=AllenNLP_AllenNLPPullRequests

**Comment by schmmd** [comment]
@murphp15 [your build](http://build.allennlp.org/viewLog.html?buildId=3382&buildTypeId=AllenNLP_AllenNLPPullRequests&tab=buildLog) is doing fine--it's one from @nelson-liu  that's having issues.

**Comment by schmmd** [comment]
I'm able to log in on the command line on my local machine and on the build server with the `allennlpuser` credentials.
