### ISSUE TITLE
Request: another minor release before PyTorch 0.4 switch

### ISSUE THREAD

**Issue by nelson-liu** [allenai/allennlp#1217]
It'd be great to have another minor version release (i.e., v0.4.3) before #1126 goes in. I'd particularly like to see #1208 included, and #1213 would be nice as well.

I'm planning on building a conda package for allennlp, since i regularly work on machines that don't have CUDA installed and conda just makes it so much easier to get that up and running. I'd like to have a conda distribution for at least one version that still works on PyTorch 0.3. 

Unfortunately, I can't build a package for v0.4.2 due to the issues that were fixed in #1202 and #1203 breaking `conda-build`.

**Comment by schmmd** [comment]
@nelson-liu would you like this release immediately or simply before #1126?

**Comment by jameswinegar** [comment]
@nelson-liu should/could I plan on a conda package being available contingent on a minor/major release?

**Comment by nelson-liu** [comment]
yeah, definitely. The recipe is done and I've tested it on a local machine, I just need to submit the PR to conda-forge and get it approved (shouldn't take more than a few days) upon the new release.
