### ISSUE TITLE
allow sanitizing of custom types

### ISSUE THREAD

**Issue by joelgrus** [allenai/allennlp#1218]
Niket ran into an issue where he wants to include his own custom types in model output (and, in particular, in predictor output).

Unfortunately, there's no way to allow for this, except for something like manually doing serializing in `Model.decode`.

A somewhat simple fix would be to add another clause to `sanitize` that checks if an object has a `to_json()` method (or we could pick a different name) and calls it in that case rather than failing.

**Comment by schmmd** [comment]
We'd also like to improve the error in sanitize to give instructions for how to correct the error.
