### ISSUE TITLE
Create a base AllenNLP image

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp#1238]
Our current Docker image is quite large a multiple GB.  The consequence of this large image is that running Beaker jobs involves significantly more data transfer than is necessary.  If we had a base image that included:

* Our `apt-get` installations.
* `nodejs`
* `pip` installations

We could build images on top of it and they would be tiny.  The key challenge I see is how we break up our image without creating a dependency headache (which version of the base image do I need, how do I update the base image, etc).

**Comment by jameswinegar** [comment]
As an outside observer and reviewing the Dockerfile in the repo. I'm not seeing much room for hierarchical builds aside from removing the tutorials/demos for the base image. 

What is the need for Java in the image? I only see it being used in two places.
allennlp/service/predictors/wikitables_parser.py
allennlp/training/metrics/wikitables_accuracy.py

**Comment by schmmd** [comment]
Hi @jameswinegar, the thought is that we could use a base image with our dependencies and create an light image with the latest source code on top of that.

The JVM is only used by those components.
