### ISSUE TITLE
better "serialization directory exists" workaround for beaker

### ISSUE THREAD

**Issue by joelgrus** [allenai/allennlp#1239]
`allennlp train` crashes if the serialization directory already exists.

this is a problem on beaker, where the output directory necessarily already exists.

right now we have a workaround where if the serialization dir is `/output` we skip the check and proceed. this is fragile and non-obvious for our users.

I have talked to the beaker team about potentially having an environment variable that indicates that code is running on beaker. 

In the meantime (and/or instead), Christian (who is the one who ran into this issue) suggested that we instead change the logic to allow the serialization directory to exist *as long as it's empty*. This seems pretty reasonable to me and makes the code less fragile.

**Comment by joelgrus** [comment]
@ckarenz @splittingfield

**Comment by matt-gardner** [comment]
Yeah, we've talked about this before, and I agree that this is reasonable.  I think there's another issue open somewhere that mentions this.
