### ISSUE TITLE
Probably Useless Code at Constituency Parser Predictor?

### ISSUE THREAD

**Issue by howardyclo** [allenai/allennlp#1243]
I am wondering the use of [these lines here](https://github.com/allenai/allennlp/blob/master/allennlp/service/predictors/constituency_parser.py#L108-L113) in constituency parser predictor, since these lines seem to be nothing to do with the final returning results `return_dicts`.

**Comment by matt-gardner** [comment]
The `return_dict` dictionaries inside of `return_dicts` are mutable, and so `return_dicts` is indeed getting updated by those lines.
