### ISSUE TITLE
`allennlp` usage lists `python -m allennlp.run` as the command

### ISSUE THREAD

**Issue by joelgrus** [allenai/allennlp#1263]
this annoys me all the time, but I keep forgetting to open an issue

```
$ allennlp
usage: python -m allennlp.run

Run AllenNLP

optional arguments:
  -h, --help  show this help message and exit

Commands:

    train     Train a model
    evaluate  Evaluate the specified model + dataset
    predict   Use a trained model to make predictions.
    serve     Run the web service and demo.
    make-vocab
              Create a vocabulary
    elmo      Use a trained model to make predictions.
    fine-tune
              Continue training a model on a new dataset
    dry-run   Create a vocabulary, compute dataset statistics and other
              training utilities.
```

this is because it's specified explicitly as "python -m allennlp.run" in allennlp/run.py

easy solution: specify it as "allennlp" instead (but then it will print the wrong thing when you actually do call `python -m allennlp.run`

easy but ugly solution: create a separate run script for the executable `allennlp/allennlp.py` that's identical but for the executable name

still easy but less easy solution: allow some kind of override for the name (e.g. via an environment variable) and then change setup.py to make the command specify that environment variable

something else: ?

**Comment by schmmd** [comment]
I'd like to change all references to `python -m allennlp.run` to `./bin/allennlp` in our documentation.  After this, your first "easy solution" is significantly more palatable--plus it's easy!

It will be trivial to add `./bin/` to the `PATH` in the Docker image too.

**Comment by schmmd** [comment]
https://github.com/allenai/allennlp/pull/1264

I had some second thoughts about adding it to the `PATH` in the Docker image, see the PR for details.
