### ISSUE TITLE
Can't install torch==0.3.1 

### ISSUE THREAD

**Issue by murphp15** [allenai/allennlp#1266]
I have rented an aws box to train a model. 
However when I run "pip3 install -r requirements.txt"

```
 Could not find a version that satisfies the requirement torch==0.3.1 (from -r requirements.txt (line 8)) (from versions: 0.1.2, 0.1.2.post1)
No matching distribution found for torch==0.3.1 (from -r requirements.txt (line 8))
```
Any ideas what the issue might be? 
Feel free to close the issue if you guys feel this is not your responsibility. Hoping you might know the fix off hand.

**Comment by DeNeutoy** [comment]
What happens if you use normal `pip` not `pip3`?

**Comment by murphp15** [comment]
In fact I got the answer online https://stackoverflow.com/questions/50488869/cant-install-torch-on-linux-box-using-pip/50489102#50489102 
Feel free to close this! thanks.
