### ISSUE TITLE
Predict for custom allennlp models

### ISSUE THREAD

**Issue by dheerajrajagopal** [allenai/allennlp#1268]
Hi, 

I was wondering what's the best way to use allennlp.run predict on a custom model ? I am finding it a little hard to understand how it would work.  If someone could give a brief summary of steps, that would be great.

**Comment by schmmd** [comment]
Hi @dheerajrajagopal, I think you'll find the following tutorials helpful in answering your question.  The second in particular specifically addresses making predictions with a model that was created using AllenNLP as a library.

https://github.com/allenai/allennlp/blob/v0.4.2/tutorials/getting_started/using_in_your_repo.md
https://github.com/allenai/allennlp/blob/v0.4.2/tutorials/getting_started/making_predictions_and_creating_a_demo.md
