### ISSUE TITLE
consider switching HOCON -> jsonnet

### ISSUE THREAD

**Issue by joelgrus** [allenai/allennlp#1275]
@cristipp wrote his own run script, in part so he could use jsonnet for his config files:

https://jsonnet.org/

jsonnet is a much more featured (and probably better supported) configuration language than HOCON. Insofar as our "HOCON" files are all "JSON with comments", they should be valid jsonnet as well. (If someone is using more advanced HOCON features, they might break, although I don't think I know of anyone doing that.)

jsonnet is a little involved, but it allows functions and inheritance, and it would make it simpler to switch between e.g. local and GPU-enabled experiments. it's also easy to imagine that it could make it a lot simpler to do hyperparameter searching. (I haven't fully thought through this.)

**Comment by matt-gardner** [comment]
The only thing that made me nervous was that jsonnet "compiles" to json, and I was afraid this would add another step to running stuff.  But I just checked, and we can put that compilation in our code, and everything is fine.  No complaints about this from me.

**Comment by schmmd** [comment]
Would the address the issue we have where we would like to override specific entries with environment variables?

**Comment by cristipp** [comment]
In my setup I have a base config file [0], which I then override with an overlay file [1] containing the tweaks I'm currently experimenting with. I do not [try to not] modify the base config directly. 

I like to capture parametrization in files, as opposed to using cli arguments. Files I can save/share/version/edit_in_ide using standard file manipulation workflow. With cli arguments, I need to either write some good docs [which rot], or write some .sh files [which I avoid, never fun maintaining a .sh file].

In this setup, `$ jsonnet src/main/python3/neurologic/allennlp.jsonnet` [or the equivalent Python API call] produces a well formed json object without any additional parametrization required.

[0] https://github.com/cristipp/euclid/blob/e1aa388e596247e2c9fc614c8221f871dfb241ea/src/main/python3/neurologic/allennlp.jsonnet
[1] https://github.com/cristipp/euclid/blob/e1aa388e596247e2c9fc614c8221f871dfb241ea/src/main/python3/neurologic/allennlp_overlay.jsonnet

**Comment by schmmd** [comment]
This makes parameters generally overridable and resolve typing issues.  We would also address our suffix issue--our conf files presently end in `.json` but are not JSON.

**Comment by joelgrus** [comment]
closed by #1409
