### ISSUE TITLE
consider a --dangerous flag (or some other name)

### ISSUE THREAD

**Issue by joelgrus** [allenai/allennlp#1276]
it's super annoying when you're debugging a failing experiment and you keep having to either delete the serialization directory or rename it in order to test your fixes.

we could have a `--dangerous` flag (or something else equally evocative) that wipes out the serialization directory at the beginning of training if it already exists. it would be dangerous but useful

**Comment by matt-gardner** [comment]
We considered this in the original PR, and thought that doing `rm -rf [dir] && [allennlp command]` isn't really that different from doing `[allennlp command] --[some_flag]`, and the former makes our code simpler.  Is the flag really all that better?

**Comment by joelgrus** [comment]
the motivating use case for this (as well as for #1277 ) was @cristipp's desire to have a single file that calls `allennlp.main()` that he can use a keyboard shortcut to start in DEBUG mode from pycharm.

there is a slightly broader point here, which is that although we encourage command line use of allennlp, there is clearly a nontrivial number of people who want to use it programatically and/or through their IDE (this was a common theme at the tutorial)

**Comment by joelgrus** [comment]
...and that everything that is tightly coupled to command line use makes those people's lives more difficult

**Comment by matt-gardner** [comment]
I see, ok, fair enough.

**Comment by matt-gardner** [comment]
This was recently added as `--force` / `-f`.
