### ISSUE TITLE
Add a version command to the allennlp command line.

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp#1280]
You can currently get the version interactively.

```
>>> allennlp.__version__
'0.4.3'
```

**Comment by joelgrus** [comment]
or you could just include it with the help string for each command

**Comment by DeNeutoy** [comment]
You can already get this from your environment with `pip list`

**Comment by schmmd** [comment]
Right--my muscle memory tells me to run `allennlp --version` however.
