### ISSUE TITLE
Error while Installing

### ISSUE THREAD

**Issue by meetferoz** [allenai/allennlp#1297]
Hi
When i run the command pip install allennlp, it ends with an error
"Could not find a version that satisfies the requirement torch==0.3.1 (from Allennlp) (from versions:0.1.2,0.1.2.post1)
No matching distributions found for torch == 0.3.1 (from allennlp)

Can you tell me what i need to do to fix this?

**Comment by nelson-liu** [comment]
What's your OS? What version of python are you using, and what version of pip do you have?

You might want to try upgrading pip before installing (`pip install --upgrade pip`)

this also might be relevant: https://github.com/allenai/allennlp/issues/1266

**Comment by meetferoz** [comment]
I m on Windows 7, 64 bit. Python version is 3.6.5 installed via anaconda.
I tried upgrading pip and the problem persists. I saw #1266, and followed the steps but still getting the same error.

**Comment by nelson-liu** [comment]
ah, that's the issue. AllenNLP currently doesn't support windows (see #612), and pytorch itself does not officially support windows before version 0.4.0. We're hoping to have windows support soon though --- #1126 will upgrade to PyTorch 0.4.0, and then it's a matter of figuring out what doesn't work on windows and fixing it.

For now, you need to use an OS X or Linux machine to use AllenNLP / PyTorch 0.3.1

I'm closing this for now, feel free to reopen if you have more questions.
