### ISSUE TITLE
Highlighting is broken in the constituency parser demo

### ISSUE THREAD

**Issue by matt-gardner** [allenai/allennlp#1300]
http://demo.allennlp.org/constituency-parsing/MjA2NTUw

I'm pretty sure you used to get span highlighting on mouse-over for all of the constituents, but that's not currently happening.  Not sure what happened.

More generally, it'd be really nice if we had some tests of our frontend JS code.  I have no idea how to write or set those up, though.  If we had a frontend engineer...

**Comment by DeNeutoy** [comment]
Yeah, I knew about this already: 
https://github.com/allenai/allennlp/blob/master/allennlp/service/predictors/constituency_parser.py#L157

It's pretty tricky to get it to line up correctly, and it's less important for a constituency parse where the tree is more explicit. 

I'll probably get around to fixing this eventually when i'm bored, so leave it open.

**Comment by matt-gardner** [comment]
Moving to allenai/allennlp-demo.
