### ISSUE TITLE
Backslashes in initializer regexes

### ISSUE THREAD

**Issue by mandarjoshi90** [allenai/allennlp#1304]
Config files, like the [one](https://github.com/allenai/allennlp/blob/master/training_config/decomposable_attention.json) for NLI (line 51), often contain regex strings with backslashes for initializers. 
`[".*token_embedder_tokens\._projection.*weight", {"type": "xavier_normal"}]`

When AllenNLP writes back the config file to the serialization directory, it seems to be prepending more backslashes to the original one. If I re-use the config file, I often get this warning -- 

`WARNING - allennlp.nn.initializers - Did not use initialization regex that was passed: .*token_embedder_tokens\\\\\\\\._projection.*weight`

**Comment by schmmd** [comment]
I see similar error when loading our own models.

```
2018-05-31 12:46:35,681 - WARNING - allennlp.nn.initializers - Did not use initialization regex that was passed: encoder\\\\._module.layer_.*bias
2018-05-31 12:46:35,682 - WARNING - allennlp.nn.initializers - Did not use initialization regex that was passed: encoder\\\\._module.layer_0\\\\.input_linearity\\\\.weight
2018-05-31 12:46:35,682 - WARNING - allennlp.nn.initializers - Did not use initialization regex that was passed: encoder\\\\._module\\\\.layer_0\\\\.state_linearity\\\\.weight
```

**Comment by schmmd** [comment]
I think the error I reported was in the SRL model, and @DeNeutoy fixed it by updating the SRL model earlier today in cebf719c4645bd6660e14a499c48e23fbe272e1c.

**Comment by joelgrus** [comment]
there are several things going on here. one is that the string with `\.` is not valid json:

```
In [86]: single = r'{"a": "b\.c"}'

In [87]: double = r'{"a": "b\\.c"}'

In [88]: json.loads(single)
---------------------------------------------------------------------------
JSONDecodeError

In [89]: json.loads(double)
Out[89]: {'a': 'b\\.c'}
```

however, pyhocon seems OK with it:

```
In [90]: pyhocon.ConfigFactory.parse_string(single)
Out[90]: ConfigTree([('a', 'b\\.c')])

In [91]: pyhocon.ConfigFactory.parse_string(double)
Out[91]: ConfigTree([('a', 'b\\\\.c')])
```

In fact, pyhocon seems to be doing the wrong thing altogether. Then the JSON dumps does the correct JSON thing:

```
In [92]: json.dumps(pyhocon.ConfigFactory.parse_string(double))
Out[92]: '{"a": "b\\\\\\\\.c"}'
```

which is now wrong.

I *think* this is a bug in pyhocon? I believe the correct solution here is to get the bug fixed in pyhocon and then use correct double backslashes in our config files. Let me take a look at the pyhocon code and see if I can see how to fix it.

**Comment by joelgrus** [comment]
opened an issue at https://github.com/chimpler/pyhocon/issues/171

**Comment by schmmd** [comment]
Fixed in https://github.com/allenai/allennlp/pull/1409.
