### ISSUE TITLE
Predictor stuck in a flash/dash app

### ISSUE THREAD

**Issue by csyhuang** [allenai/allennlp#1313]
Hi,

I am trying to incorporate the constituency parser of AllenNLP in my Dash app, but not sure why it got stuck without any errors shown when I use the Predictor. Wonder if you may have any idea to debug?

I put the following in the `__init__` of my app:

```python
    def initiateAllenNLP(self):
        from allennlp.models.archival import load_archive
        from allennlp.service.predictors import Predictor

        archive = load_archive(
                    "https://s3-us-west-2.amazonaws.com/allennlp/models/elmo-constituency-parser-2018.03.14.tar.gz"
                )
        allen_nlp_predictor = Predictor.from_archive(archive, 'constituency-parser')
        return None
```

And a function that process the user input `question` (a string):

```python
results = allen_nlp_predictor.predict_json({"sentence": question})
```

The script above works perfectly fine on my laptop (that the results are produced), but when deploying it onto the dash app, it is stuck at the line above. Are there options to display progress in verbose mode? Please advice.

Thanks in advance,

Clare

**Comment by matt-gardner** [comment]
Is this some cross-site request blocking that's causing the app to hang?  I'd look at network traffic logs to see if there's anything that looks funny.

**Comment by csyhuang** [comment]
Hi @DeNeutoy,

The code I'm using in the dash app is like this. There are two files. One named class_a.py which initialize the predictor that looks like

```python
# file class_a.py
class Class_A:

    def __init__(...):

        archive = load_archive(
            "https://s3-us-west-2.amazonaws.com/allennlp/models/elmo-constituency-parser-2018.03.14.tar.gz"
        )

        self.allen_nlp_predictor = Predictor.from_archive(archive, 'constituency-parser')

        print("Finished Initializing")	


def getQuestion(question):
    allenNLP_results = allenNLPparsing(allen_nlp_predictor, question)
    return allenNLP_results


def allenNLPparsing(allen_nlp_predictor, question):
    results = allen_nlp_predictor.predict_json({"sentence": question})
    return results


```

And another one called class_b.py which contains the dash panel:

```python
# file class_b.py
...
import flask
import dash
import dash_core_components as dcc
import dash_html_components as html
import dash_table_experiments as dt

import plotly
import plotly.plotly as py
import plotly.graph_objs as pygo
import plotly.figure_factory as ff
from class_a import *


# file class_b.py
class Class_B(LensPanel) : 

    def prepare(self, ...):
        ...
        self.class_a = Class_A(...)
        ...

    def update_layout(self, ..., question):
        print("AllenNLP Parsing")
        allenNLP_results = getQuestion(self.class_a.allen_nlp_predictor)
        print("Tag Con(dis)junctives")
        ...
```

When running class_b.py, only `AllenNLP Parsing` is printed on the screen but not `Tag Con(dis)junctives`. It got stuck at the line

```python
results = allen_nlp_predictor.predict_json({"sentence": question})
```

Is there anything I can print out from the function `predict_json`? Any idea what's wrong?

@matt-gardner So far we didn't observe this happening. Thanks for suggesting to check though.

**Comment by joelgrus** [comment]
you can use the brand new debugging tutorial! 😀😀😀

https://github.com/allenai/allennlp/blob/master/tutorials/how_to/using_a_debugger.md

(or if you don't want to do that, you can go into your environment's copy of allennlp and add print statements to the predictor, I do that sometimes)

**Comment by csyhuang** [comment]
@joelgrus Thanks for the tutorial link! Since I am not training any models, perhaps I shall really try debugging AllenNLP by printing statements from the source code... I'll try and update you how it goes. 🙂

**Comment by csyhuang** [comment]
As an update, after looking into the problem for days, we figured out it is a platform specific problem and not related to AllenNLP or Dash. Thank you for all your kind help and the debugging tutorial. They are all very useful. 😄

**Comment by srhrshr** [comment]
@csyhuang I'm running into the same issue when I upgraded from `allennlp==0.7` to `allennlp==0.8.4`. I am also using a flask driven microservice architecture. Would be really helpful if you could elaborate what the platform specific issue was. Thanks.

**Comment by csyhuang** [comment]
@srhrshr I actually don't remember the details as it was work in another company a year ago... I vaguely recall it was the issue that the server cannot handle more than a certain number of request at the same time. It was completely irrelevant to AllenNLP or Dash.

**Comment by srhrshr** [comment]
@csyhuang, thanks for the lead!  I'm running it from inside a docker container. Will check if it's got something to do with the docker config.
