### ISSUE TITLE
The demo database is not aware of new model versions

### ISSUE THREAD

**Issue by DeNeutoy** [allenai/allennlp#1315]
If you have a query which is in present in the database, it's going to return old model results rather than run the new model. We should add a column to the database which records the model version it used and bust the cache if it doesn't match the current model version.

**Comment by schmmd** [comment]
@DeNeutoy I think the current behavior is actually correct.

The cache is in memory and only works for the duration of the process--it does not use the database.  It will be clean slate once you update a model and restart the process.

The permalinks do use the database and they always return the same information that you saw previously.  I think it would be confusing if the response changed when our models improved.

**Comment by DeNeutoy** [comment]
Ah, makes sense - thanks
