### ISSUE TITLE
Unable to install allennlp via pip

### ISSUE THREAD

**Issue by chiphuyen** [allenai/allennlp#1332]
When I tried to install allennlp via pip3, I ran into this issue:
```
sanic-plugins-framework 0.5.2.dev20180201 has requirement sanic>=0.7.0, but you'll have sanic 0.6.0 which is incompatible.
sanic-cors 0.9.4 has requirement sanic>=0.7.0, but you'll have sanic 0.6.0 which is incompatible.
```
I suspect that it's because in the setup.py, the required installs are:
```
sanic==0.6.0
sanic-cors
```
And the latest version of sanic-cors is incompatible with sanic==0.6.0.

Does anybody know how to deal with this problem? Thanks  alot!

**Comment by joelgrus** [comment]
what version are you trying to install? we removed the sanic dependency like 6 months ago.

**Comment by chiphuyen** [comment]
I'm trying to get the allennlp==0.2.3. Thanks!

**Comment by joelgrus** [comment]
that's many versions ago, can you use a recent release?

https://pypi.org/project/allennlp/#history

**Comment by chiphuyen** [comment]
The newer version no longer supports Dataset though.

**Comment by joelgrus** [comment]
Dataset was just a wrapper class around a list of instances. Now you can just use the list of instances itself where you would have used a dataset before. We didn't get rid of any functionality.

If for some reason you still really need to use such an old version, then I guess you'll need to install from source and fix the requirements.txt to be what you need them to be.
