### ISSUE TITLE
Training of Coreference model meets early stop at epoch 27

### ISSUE THREAD

**Issue by ljinstat** [allenai/allennlp#1337]
Hello,

I have trained the Coreference model separately in CPU and GPU. For GPU, it met early stop at epoch 27, and for CPU, it met early stop at epoch 47. The result coref_f1 on validation gotten in GPU is less than 0.1, and the result coref_f1 on validation from CPU is about 0.55. All parameters remain the same as coref.json in the package. The number of data are slightly different from the paper. And the GPU is Tesla P100. The versions of package that I used for these two trainings are different. I used new released allennlp + Pytorch 0.4.0 for GPU and last allennlp + Pythorch 0.3.1 for CPU.

Could you please tell me whether you have encountered this issue? I don't know why do I get results that are so different and far from the result in the paper.

I appreciate a lot your helps!

**Comment by DeNeutoy** [comment]
Hi,

1. Yes the numbers are somewhat lower than in the original paper. This is detailed on the Models page of our website: allennlp.org/models. E.g we do not use speaker features, because these are completely impractical in the real world.

2. What data are you using?

3. I'm travelling at the moment, but when I get back i'll double check that we can still train the coref model. We recently switched to Pytorch 0.4 it's possible we added a bug somewhere there.

**Comment by ljinstat** [comment]
Hello,

Thank you so much for your answer.

As for data:
- In paper and github of the paper, Conll version 4 are used. However, number of data files (version 4) that I achieved are less than that mentioned in paper. In paper, there are 2802 training documents, 343 development documents, 348 test documents. While, I have 1977 training documents (auto_conll and gold_conll have the same number), 222 development documents and 222 test documents.  

- In paper, the model is trained by using .auto_conll and tested on .gold_conll. I checked the code in ontonotes.py, the code only read .gold_conll for all folders.

- In order to read files, I have to put all files into one folder. I don't know whether it is how you designed to read files. And in ontonotes.py -> class Ontonotes -> def dataset_document_iterator, I have to add dataset_path_iterator to read name of each file, otherwise the directory written in coref.json cannot be opened.
  
I am confused what kind of data did you use for training exactly. Is it version 4 with .gold_conll? 
Did you use the same amount of documents as the paper mentions?
How did you save your data in order that files are read iteratively? 

Thank you for your help!

**Comment by DeNeutoy** [comment]
https://github.com/allenai/allennlp/blob/master/scripts/compile_coref_data.sh

This script is how we created the Coref data from the Ontonotes 5.0 release. I believe it uses the Conll 4 labels. If you follow this script (you will need to run it in an environment which has python2 as the default python interpreter), you should get the same data format as we have - 3 files, one for train, dev and test. 

Doing this should solve your problems - the Coref dataset reader is designed to read a single file, which is why you had to modify it. Please comment here if you still run into problems once you are using the correct version of the data and i'll try and help more.

**Comment by DeNeutoy** [comment]
Great! That is within the ball park of where it should be. There are a couple of improvements which could be made to the coref model too - particularly 1. Using 840B.300d glove vectors instead of the 6B ones, 2. Using the bidirectional LSTM in allennlp which has variational dropout and 3 adding speaker features. The first two are trivially easy (you can change them in the config) and adding speaker features only requires a little bit of effort. If you do this, please send a PR!

**Comment by ljinstat** [comment]
Thank you for these ideas!
I have some questions on how to implement these improvements:
- In order to use the bidirectional LSTM with variational dropout, which parameter should I modify exactly? In the coref.json, I think I have to set "context_layer" => "type" to "augmented_lstm", but I am not sure.
- As for features, I only find feature_size in models/coreference_resolution/coref.py, but I did't find any method to manipulate features. Does it mean that I should rewrite a method to create features?

After using this package, I find that this project is well organized and dynamic and the codes are clean, clear and well defined. However, if there are well documented introductions for each model, that will be much better. Actually, I have to read each file to understand how to implement and change codes, it is time-consuming and inefficient.

**Comment by ljinstat** [comment]
Hello!

I implemented "augmented_lstm" with default parameters, however I got an RuntimeError:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/lj/dockerdocument/mountdc/allennlp-master/allennlp/run.py", line 18, in <module>
    main(prog="allennlp")
  File "/data/lj/dockerdocument/mountdc/allennlp-master/allennlp/commands/__init__.py", line 70, in main
    args.func(args)
  File "/data/lj/dockerdocument/mountdc/allennlp-master/allennlp/commands/train.py", line 101, in train_model_from_args
    args.recover)
  File "/data/lj/dockerdocument/mountdc/allennlp-master/allennlp/commands/train.py", line 131, in train_model_from_file
    return train_model(params, serialization_dir, file_friendly_logging, recover)
  File "/data/lj/dockerdocument/mountdc/allennlp-master/allennlp/commands/train.py", line 296, in train_model
    metrics = trainer.train()
  File "/data/lj/dockerdocument/mountdc/allennlp-master/allennlp/training/trainer.py", line 679, in train
    train_metrics = self._train_epoch(epoch)
  File "/data/lj/dockerdocument/mountdc/allennlp-master/allennlp/training/trainer.py", line 463, in _train_epoch
    loss = self._batch_loss(batch, for_training=True)
  File "/data/lj/dockerdocument/mountdc/allennlp-master/allennlp/training/trainer.py", line 398, in _batch_loss
    output_dict = self._model(**batch)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/lj/dockerdocument/mountdc/allennlp-master/allennlp/models/coreference_resolution/coref.py", line 185, in forward
    num_spans_to_keep)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/lj/dockerdocument/mountdc/allennlp-master/allennlp/modules/span_pruner.py", line 67, in forward
    span_scores = self._scorer(span_embeddings)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/lj/dockerdocument/mountdc/allennlp-master/allennlp/modules/time_distributed.py", line 35, in forward
    reshaped_outputs = self._module(*reshaped_inputs)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/lj/dockerdocument/mountdc/allennlp-master/allennlp/modules/feedforward.py", line 79, in forward
    output = dropout(activation(layer(output)))
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 55, in forward
    return F.linear(input, self.weight, self.bias)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/functional.py", line 992, in linear
    return torch.addmm(bias, input, weight.t())
RuntimeError: size mismatch, m1: [3505 x 820], m2: [1220 x 150] at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:249

I use latest allennlp code and just changed parameters in context_layer of coref.json.

**Comment by paul-cvp** [comment]
Hi,

I think that the augmented_lstm is not bidirectional so you are missing the concatenated output in the last dimention of the forward and backward pass of the default pytorch lstm. 1220 = 400 (from forward) + 400 (from backward) + 500 (head word attention) + 20 (which I assume is the mention width embedding). So you either need to adapt the mention_feedforward input_dim to 820 or add another augmented_lstm with the param go_forward=false to do the backward pass.

**Comment by paul-cvp** [comment]
Hi,

I think that the augmented_lstm is not bidirectional so you are missing the concatenated output in the last dimension of the forward and backward pass of the default pytorch lstm. 1220 = 400 (from forward) + 400 (from backward) + 500 (head word attention) + 20 (which I assume is the mention width embedding). So you either need to adapt the mention_feedforward input_dim to 820 or add another augmented_lstm with the param go_forward=false to do the backward pass.

**Comment by DeNeutoy** [comment]
That sounds correct, yes, but honestly I don't have the shapes in the models off the top of my head. 

For the features, you would have to add code into the Coref model to add the features, as well as in the DatasetReader.

**Comment by ljinstat** [comment]
Thanks for your answers. Actually, I have tried what Paul @paul-cvp said. I modified input_dim from 1220 to 820 and changed lstm to augmented_lstm in context_layer also with other parameters. However, dimension issues still exit. Have you succeeded to implement the model with augmented_lstm?
