### ISSUE TITLE
With words representation by ELMO , I wonder that the distance between 2 vector words of 2 synonym word IS CLOSER the distance between 2 vector words of 2 words which are NOT synonym ?

### ISSUE THREAD

**Issue by LiemTr** [allenai/allennlp#1340]
Dear all,

With words representation by ELMO , I wonder that the distance between 2 vector words of 2 synonym word IS CLOSER the distance between 2 vector words of 2 words which are NOT synonym ?

Thanks all.

**Comment by DeNeutoy** [comment]
Yes, that is likely the case. This also applies to other word vectors.

**Comment by LiemTr** [comment]
Hi DeNeutoy,

I want to count the similar words (the same words or synonym words) between 2 sentences by computing distance word vectors in these sentences, but I could not got a threshold to compare with L2 distance , because I see L2 distance between synonym words are not too different to the distance between the words which are not synonym. 
In this case, Can I use ELMO??

Thank you.

**Comment by ianupright** [comment]
Hi LiemTr,

You can try Elmo. It (or other older embeddings such as Context2Vec) are likely to work much better than Glove.

Ian
