### ISSUE TITLE
New blueprint functionality in run_with_beaker.py doesn't actually work

### ISSUE THREAD

**Issue by matt-gardner** [allenai/allennlp#1345]
I spent a few minutes trying to fix it, but it didn't work, so I'm just going to work off a branch that reverts the blueprint change, so I can actually run stuff.  The problem is that the `--cpu`, `--memory`, and `--gpu_count` flags are supposed to be optional, but they actually aren't in the script, and I think they're not in the right place in the generated config, either.  Also, it should be `--gpu-count`, not `--gpu_count`.

**Comment by schmmd** [comment]
@matt-gardner apologies.  If you hit something similar in the future, feel free to revert commits on master.

**Comment by matt-gardner** [comment]
I didn't want to go quite that far, as it was a large change and most of it was good.  It should be just a few lines of change to fix, I just didn't know what the right lines were and didn't have time to look at it right then.  Working on the branch was easy enough.
