### ISSUE TITLE
Document a little on elmo pretrained corpus

### ISSUE THREAD

**Issue by ianupright** [allenai/allennlp#1353]
Can we have some hints as to how the pretrained elmo embeddings were created with regards to corpus?
Like, is it trained on a tokenized corpus such as "I do n't care", or is it tokenized with spaces such as "I don't care"?

Thanks

**Comment by DeNeutoy** [comment]
Hi there,

ELMo was trained on the 1B word benchmark - you can find more details on tokenisation in the paper or by looking at the data.

https://arxiv.org/abs/1312.3005
http://www.statmt.org/lm-benchmark/

Thanks
