### ISSUE TITLE
Training its own ELMo embedding

### ISSUE THREAD

**Issue by jplu** [allenai/allennlp#1356]
Hello,

You have done a nice tutorial on how to use ELMo, but nothing about how to train our own ELMo model. Any plan on when will you publish this? Or it is not yet possible?

Thanks for your answer :)

**Comment by DeNeutoy** [comment]
https://github.com/allenai/bilm-tf

See this repository for full training code for ELMo. Thanks!

**Comment by nelson-liu** [comment]
That’s correct @feiga
