### ISSUE TITLE
Help Training Allennlp models on new data

### ISSUE THREAD

**Issue by dhairyadalal** [allenai/allennlp#1365]
I'd like to train the the allennlp bidaf implementation on the squad 2.0 dataset. Wondering if it possible to this programmatically? Or do can I only do it via the command line instructions in the readme?

**Comment by joelgrus** [comment]
yes, you can do it programmatically.

one simple way is as described here:

https://github.com/allenai/allennlp/blob/master/tutorials/how_to/using_a_debugger.md#how-to-debug-in-pycharm-using-run--debug

if you want to control the details further, you can import `allennlp.commands.train.train_model` and call that from your code, or even create your own equivalent that's even more customized

https://github.com/allenai/allennlp/blob/master/allennlp/commands/train.py#L224

**Comment by matt-gardner** [comment]
Note, though, that BiDAF won't work on SQuAD 2.0 without some modification, because it assumes the answer is always present. You either have to change the data to assign a consistent empty span when there is no answer (not sure that this work actually work, but you could try it), or add something to the model.

**Comment by nelson-liu** [comment]
Does bidaf even work with Squad 2.0? I haven’t looked at the data, but maybe they changed the format to support unanswerable questions?

**Comment by dhairyadalal** [comment]
I was think of updating it with changes suggested in Levy '17.

**Comment by murphp15** [comment]
@dhairyadalal Would you be able to elaborate on which part of the paper you are referring to to achieve no answer options?

**Comment by murphp15** [comment]
@dhairyadalal I have just recently read that paper but I don't fully understand how the no answer part of this works. 
Is there any chance you could explain it to me ?

**Comment by dhairyadalal** [comment]
@murphp15 apologies for the late response. Just got back from vacation. I'm still working on getting a better understanding for what they did. Their implementation (in tensorflow) can be found here: https://bitbucket.org/omerlevy/bidaf_no_answer. Was planning on going through to see if I could get some clues.

Happy to talk more over email if its helpful (dhairya.b.dalal [at] gmail )

**Comment by antoinecomp** [comment]
@dhairyadalal @murphp15 I'm doing my Master dissertation thesis on the topic, I'm really interested about this discussion if you're still reviewing their algorithm.

**Comment by Swathygsb** [comment]
Hi All,
I want to train bidaf model for my own data set along with squad dataset. In my Question Answer pairs, the answers are not single word and are mostly a passage containing multiple sentences. Should i change any configuration in bidaf.jsonnet to support it for Machine comprehension - BIdaf model?

**Comment by rbhat03** [comment]
HI @Swathygsb I am looking for some similar requirement as urs... were u able to make any progress?

**Comment by NoahDrisort** [comment]
> Hi All,
> I want to train bidaf model for my own data set along with squad dataset. In my Question Answer pairs, the answers are not single word and are mostly a passage containing multiple sentences. Should i change any configuration in bidaf.jsonnet to support it for Machine comprehension - BIdaf model?

Can I have a question that when you train your model with Squad+your Data, what is your configuration?  I mean the file json used for training includes Squad or not, or only your new data and weight provided from glove and elmo/squad
