### ISSUE TITLE
Not getting 'serve' option while following tutorial steps

### ISSUE THREAD

**Issue by lewiswilliam** [allenai/allennlp#1366]
I installed allennlp using the command given on the tutorial page:
docker run -p 8000:8000 -it --rm allennlp/allennlp

then I jumped to the section: "Once You've Installed"

when i run the command python -m allennlp.run, i get:

Commands:

    configure   Generate configuration stubs.
    train       Train a model
    evaluate    Evaluate the specified model + dataset
    predict     Use a trained model to make predictions.
    make-vocab  Create a vocabulary
    elmo        Use a trained model to make predictions.
    fine-tune   Continue training a model on a new dataset
    dry-run     Create a vocabulary, compute dataset statistics and other
                training utilities.
    test-install
                Run the unit tests.

I do not get the serve option. Any reasons?

Also, if its important to know, version of allennlp installed is "allennlp 0.4.4-unreleased"

**Comment by joelgrus** [comment]
we recently removed the `serve` functionality (it runs `demo.allennlp.org` but isn't really needed for our end users), so it won't be there in recent docker images.

if you really want to see it, you can run a released docker image, e.g. `allennlp/allennlp:v0.4.3`. alternatively, you could look at the latest version of the tutorial, which doesn't mention `serve`:

https://github.com/allenai/allennlp/blob/master/README.md

**Comment by lewiswilliam** [comment]
thanks @joelgrus 

I was actually following https://github.com/allenai/allennlp/blob/v0.4.0/tutorials/getting_started/installation.md
and that got me the latest branch of code.

Thanks for the response. Appreciate it.
