### ISSUE TITLE
GitHub/TeamCity is reporting an erroneous check

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp#1367]
Here is an image:

![image](https://user-images.githubusercontent.com/954798/41364366-4a570ad8-6eeb-11e8-93e2-78178efcb8e3.png)

It remains in this state indefinitely.  It started when I renamed and moved around some of our checks so we had a separate section for demo CI.  CI still works, but under a different name.

![image](https://user-images.githubusercontent.com/954798/41364391-62224592-6eeb-11e8-8c29-3f93c30d4963.png)

**Comment by matt-gardner** [comment]
I had a thought, so I checked it - in the [github settings for the master branch](https://github.com/allenai/allennlp/settings/branches/master), the old name was still being set as "required."  I switched it to the new name for the status check, and it looks like it fixed #1364.  I'm not sure if there's anything else left to do or not.

**Comment by schmmd** [comment]
Thanks @matt-gardner -- that fixed it.
