### ISSUE TITLE
eliminate `requirements_test.txt` + add tests to setup.py

### ISSUE THREAD

**Issue by joelgrus** [allenai/allennlp#1378]
yesterday's bad release was due (in large part) to the distinction between `requirements.txt` and `requirements_test`.txt.

briefly, I added a new feature that required a "new" dependency, tried to pip install it, saw that it was already there, and so assumed it was already transitively included in our requirements. but it turns out it was actually one of the *test* requirements (which I have installed, but which don't get pip installed). TeamCity didn't catch this either, because it also installs test requirements!

I failed to catch it manually at the "test pypi test install" step, so that's bad on me, but our release process shouldn't rely on that sort of manual verification (and anyway it could have been a much more subtle bug).

This is admittedly an edge case, but (I hit it and so) I think it speaks to having *ONE INSTALL PATH*. If our CI system isn't testing the same "environment" that's going into our pip package, that's very bad.

(Before we do this we should eliminate the Jupyter dependency from requirements_test.txt)

along similar lines, I think we should distribute our tests as part of the pip package, so that we can TEST TEST our pip install

**Comment by joelgrus** [comment]
in an ideal world we should have a CI step that spins up our own devpi https://devpi.net/docs/devpi/devpi/latest/%2Bd/index.html server, pushes to it, creates a new environment, installs from it, and runs the tests

**Comment by schmmd** [comment]
It's easy to add such a CI step, but my concern is it would double our testing time.

I'm all for eliminating `requirements_test.txt`.  I agree we should remove [the `jupyter` dependency](https://github.com/allenai/allennlp/blob/master/requirements_test.txt#L7) before we do.

**Comment by joelgrus** [comment]
I was thinking we would add it only to the "commit to master" step, not the "pull request" step

**Comment by schmmd** [comment]
@joelgrus well, I absolutely plan to add that step because I'd like to publish a docker image that does a pip install of AllenNLP.  I think this would be accomplished by https://github.com/allenai/allennlp/issues/1324 (although I was pretty sparse on details in that issue).

**Comment by DeNeutoy** [comment]
FYI seems like Infrastructure have already set up a devpi server: https://github.com/allenai/pipette/issues/7

**Comment by schmmd** [comment]
@DeNeutoy Cristian set this up.

**Comment by schmmd** [comment]
Ah, nm, just read the ticket.

**Comment by schmmd** [comment]
@DeNeutoy @schmmd and @joelgrus just agreed that we should just move Jupyter to `requirements.txt`.

**Comment by schmmd** [comment]
Just saw this--should we still move `jupyter` into the main dependencies?  I'm conflicted.

https://twitter.com/chipro/status/1003579613145157632

**Comment by schmmd** [comment]
@joelgrus is this still an issue now that we have the `allennlp test_install` command which can be used to validate pip installations?

@DeNeutoy do you still think we should keep `jupyter` as a dependency?  I'm on the fence and I lean towards removing it.  I don't want to debate it though--if you think we should keep it then let's keep it.  I just wanted to check whether you've had a change of heart in the past month (or form the linked twitter discussion) ;-)

**Comment by DeNeutoy** [comment]
As far as I am concerned there are still two actions here:

1. Set up a teamcity job which builds our pip package, pushes it to the pypi server infrastructure set up (presuming there is some uptime reliability there), installs it in a fresh environment and runs `allennlp test-install`.

2. Decide whether to merge the dependencies.

We should decide this based on:
- Do actual users find the jupyter notebooks helpful? E.g I know that @kearns found them very helpful and said that many of his students wouldn't have been able to get off the ground without them.
- Can we move the jupyter notebooks to, e.g, `allennlp-as-a-library-example`?

Particularly, a non-goal of removing Jupyter and merging the test requirements should be reducing dependencies because 1. allennlp is designed for reasearch and 2. The volume of dependencies from Jupyter has never caused us any actual problems.

**Comment by schmmd** [comment]
I have spent a long time trying to escape dependency hell before--so I like to avoid those problems whenever possible ;-)

I'll remove `requirements_test.txt` for now and, if time allows, move to a setup where we have our notebooks tested by CI without having them in our requirements.
