### ISSUE TITLE
Validation metric in bidaf.json

### ISSUE THREAD

**Issue by chaxor** [allenai/allennlp#1382]
I have been attempting to train the standard BiDAF model in the allennlp package using the provided bidaf.json, but am receiving the following error:

`allennlp.common.checks.ConfigurationError: 'The reduce_on_plateau learning rate scheduler requires a validation metric to compute the schedule and therefore must be used with a validation dataset.'`

I have attempted to alter the exact match `+em` validation metric to other values such as `+f1` and changed out the datasets with my own and am still receiving this error.

Am I missing something crucial for this task?

**Comment by DeNeutoy** [comment]
You need to pass a validation dataset to your model via the config - `validation_data_path`. Are you doing this?

**Comment by chaxor** [comment]
Yes, I have a validation_data_path set, as it is in the file provided: https://github.com/allenai/allennlp/blob/master/training_config/bidaf.json  

Also, I have tried using my own dataset for train and validation in these fields as well, but it provides the same error.

**Comment by DeNeutoy** [comment]
It's kind of hard to help you with this little information. Can you post a full configuration file and stack trace? What version of allennlp are you using?

**Comment by DeNeutoy** [comment]
Re-open if you haven't figured this out!
