### ISSUE TITLE
Odd prediction behavior when running predictions programmatically 

### ISSUE THREAD

**Issue by dhairyadalal** [allenai/allennlp#1383]
**Describe the bug**
Running predictions against the bidaf programmatically returns odd answers that don't match the baseline in the online demo and when running predict using the command line tool. 

Eg. Using the baseline question/passage from the demo.

**To Reproduce**
"passage": "A reusable launch system (RLS, or reusable launch vehicle, RLV) is a launch system which is capable of launching a payload into space more than once. This contrasts with expendable launch systems, where each launch vehicle is launched once and then discarded. No completely reusable orbital launch system has ever been created. Two partially reusable launch systems were developed, the Space Shuttle and Falcon 9. The Space Shuttle was partially reusable: the orbiter (which included the Space Shuttle main engines and the Orbital Maneuvering System engines), and the two solid rocket boosters were reused after several months of refitting work for each launch. The external tank was discarded after each flight."

"question": "How many partially reusable launch systems were developed?"

Best answer: ?

Python does raise following warning:

> /anaconda3/envs/test_nlp/lib/python3.6/site-packages/torch/nn/modules/rnn.py:38: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.2 and num_layers=1
>   "num_layers={}".format(dropout, num_layers))
> 

I haven't at this point modified the downloaded model or any of the dropout settings manuall.y 

**Expected behavior**
Based on the demo online, it should return 2. 

**System (please complete the following information):**
 - OSX high sierra
 - Python version: 3.6
 - AllenNLP version: (latest?) pip installed in clean conda environment today
 - PyTorch version: 0.4.0

1. Created a new conda environment
2. Installed allennlp (pip install allennlp)
3. Downloaded allenlp model from: 
https://s3-us-west-2.amazonaws.com/allennlp/models/bidaf-model-2017.09.15-charpad.tar.gz

test code

```
from allennlp.models.archival import load_archive
from allennlp.predictors import Predictor

def create_input(question, context):
    return {
             "question": question,
             "passage": context
           }

question = "A reusable launch system (RLS, or reusable launch vehicle, RLV) is a launch system which is capable of launching a payload into space more than once. This contrasts with expendable launch systems, where each launch vehicle is launched once and then discarded. No completely reusable orbital launch system has ever been created. Two partially reusable launch systems were developed, the Space Shuttle and Falcon 9. The Space Shuttle was partially reusable: the orbiter (which included the Space Shuttle main engines and the Orbital Maneuvering System engines), and the two solid rocket boosters were reused after several months of refitting work for each launch. The external tank was discarded after each flight."
passage = "How many partially reusable launch systems were developed?"

archive = load_archive("model.tar.gz")
predicator = Predictor.from_archive(archive, 'machine-comprehension')

pred = predicator.predict_json(create_input(question, passage))

pred_answer = pred.get("best_span_str")
best_span = pred.get("best_span")

print(pred_answer)

```

**Additional context**

**Comment by joelgrus** [comment]
your code has `question` and `passage` mixed up
