### ISSUE TITLE
get_from_cache() fails if redirection is required

### ISSUE THREAD

**Issue by janLuke** [allenai/allennlp#1386]
**Description**
Trying PR #1364 (not merged yet) with ``pretrained_file`` equal to an official Glove URL, I got an exception from ``get_from_cache()``. The issue applies to master branch as well:
```
~/Repo/allennlp/allennlp/common/file_utils.py in get_from_cache(url, cache_dir)
    104     response = requests.head(url)
    105     if response.status_code != 200:
--> 106         raise IOError("HEAD request failed for url {}".format(url))
    107 
    108     # add ETag to filename if it exists

OSError: HEAD request failed for url http://nlp.stanford.edu/data/glove.6B.zip
```
The response status code is [302](https://en.wikipedia.org/wiki/HTTP_302)  ("redirection found").

**To Reproduce**
```
from allennlp.common.file_utils import get_from_cache
get_from_cache('http://nlp.stanford.edu/data/glove.6B.zip')
```

**Possible solution**

Unless there's a particular reason to disallow redirections, the issue is easily fixed simply allowing them in line 104:
```
response = requests.head(url, allow_redirects=True)
```

**Comment by nelson-liu** [comment]
This seems like a reasonable solution to me
