### ISSUE TITLE
Joint task learning errors/example

### ISSUE THREAD

**Issue by aribornstein** [allenai/allennlp#1390]
I'm trying to write a joint learning task for multinli by doing joint training with pos similar to what was done in this article https://arxiv.org/abs/1611.01587. 

While I can get my joint task to train with decomposable attention it seems to negatively impact results. Part of the reason for this is that my POS tagger is just a simple Bi-LSTM, i'm trying to replace it with a AugmentedLSTM code with 8 or so highway connections but keep getting errors related to receiving of tensor of sequence labels and not a packed sequence as input. 

Can anyone point me to an example of how to correctly convert the embedding tensor into a packed sequence so I can take advantage of the provided modules in AllenNLP. Much appreciated.

Best,
-Ari

**Comment by DeNeutoy** [comment]
Hey - if you want a "tensor in, tensor out" interface, you can use https://github.com/allenai/allennlp/blob/master/allennlp/modules/seq2seq_encoders/pytorch_seq2seq_wrapper.py to wrap the module itself - we do this here: 

https://github.com/allenai/allennlp/blob/master/allennlp/modules/seq2seq_encoders/__init__.py#L79

Also - an 8 layer highway lstm is possibly overkill for POS tagging - depending on how much data you have.
