### ISSUE TITLE
AttributeError: 'SnliReader' object has no attribute '_tokenizer'

### ISSUE THREAD

**Issue by aribornstein** [allenai/allennlp#1400]
**Describe the bug**
I can't evaluate a custom slni model I keep getting the error above

**To Reproduce**
Train SNLI model evaluate on same testing dataset

**Expected behavior**

**System (please complete the following information):**
 - OS:Linux
 - AllenNLP version: I installed from master"

**Additional context**

**Comment by HarshTrivedi** [comment]
It would help if you mention what command you run, what are the changes you made to your custom model config file and full trace of the error. And based on the full trace, you should keep relevant snippets of your code.

**Comment by aribornstein** [comment]
Fixed this by passing the word tokenizer on evaluation will provide code snippets in the futuer.
