### ISSUE TITLE
Updating exposed model

### ISSUE THREAD

**Issue by PrashantRanjan09** [allenai/allennlp#1403]
Hi,
what does trainable =True signify   ?

So say if the model has not seen the word cat, will it learn the embeddings of cat based on the context ?

elmo = hub.Module("https://tfhub.dev/google/elmo/1", **trainable=True**)
tokens_input = [["the", "cat", "is", "on", "the", "mat"],
                ["dogs", "are", "in", "the", "fog", ""]]
tokens_length = [6, 5]
embeddings = elmo(
    inputs={
        "tokens": tokens_input,
        "sequence_len": tokens_length
    },
    signature="tokens",
    as_dict=True)["elmo"]

**Comment by DeNeutoy** [comment]
You should use version 2 of elmo in the tfhub. 

`Trainable` in this case means that there are 4 scalar trainable parameters, essentially learning a weighted sum of the different layers.

https://www.tensorflow.org/hub/modules/google/elmo/2

You are correct that ELMo can learn contextual embeddings of words even if it has not seen them at training time.
