### ISSUE TITLE
import resource ModuleNotFoundError: No module named 'resource' on windows

### ISSUE THREAD

**Issue by Kirikaku** [allenai/allennlp#1406]
**Describe the bug**
Hey, i got following error message:

`File "C:\Users\Kirikaku\AppData\Local\Continuum\anaconda3\lib\site-packages\allennlp\modules\__init__.py", line 8, in <module>
    from allennlp.modules.conditional_random_field import ConditionalRandomField
  File "C:\Users\Kirikaku\AppData\Local\Continuum\anaconda3\lib\site-packages\allennlp\modules\conditional_random_field.py", line 8, in <module>
    from allennlp.common.checks import ConfigurationError
  File "C:\Users\Kirikaku\AppData\Local\Continuum\anaconda3\lib\site-packages\allennlp\common\__init__.py", line 5, in <module>
    from allennlp.common.util import JsonDict
  File "C:\Users\Kirikaku\AppData\Local\Continuum\anaconda3\lib\site-packages\allennlp\common\util.py", line 11, in <module>
    import resource
ModuleNotFoundError: No module named 'resource'`

With the help of google, i know that this module is unix - specific and cannot install this module

**To Reproduce**
Get Windows and try to import "from allennlp.modules.elmo import batch_to_ids"

**Expected behavior**
no compile errors

**System (please complete the following information):**
 - OS: Windows 10
 - Python version: 3.6
 - AllenNLP version: 0.5.1
 - PyTorch version: 0.4

**Comment by joelgrus** [comment]
Currently AllenNLP is not supported on Windows. We'd really like it to be, but we're a small team and it's not near the top of our priorities list. 

I'd recommend using a linux ec2 instance or similar, or else using Docker.
