### ISSUE TITLE
ELMO embeddings: whether or not to add <S> and </S> to sentences during test phase.

### ISSUE THREAD

**Issue by boliangz** [allenai/allennlp#1419]
I'm trying to train ELMO embeddings on other languages using the bilm package. In the training phase, BidirectionalLMDataset initialization adds BOS and EOS to the sentence using Vocabulary.encode() function. But in the test elmo example, it seems there is no such a step to add BOS and EOS to sentences. Will this affect the language model quality if they are not consistent, or the test phase actually requires adding BOS and EOS by users themselves?

Thanks in advance.

Boliang

**Comment by DeNeutoy** [comment]
Do you mean when testing on a language modeling objective? If so, the same Batcher is used in bilm-tf and the BOS/EOS are added.

If you mean using the ELMo model in `allennlp` for a downstream task, we have actually created classes which do this for you, so that you don't have to worry about it.
