### ISSUE TITLE
Too many public methods for test file

### ISSUE THREAD

**Issue by HarshTrivedi** [allenai/allennlp#1421]
I am trying to reorganize my tests for (#1416). But `pylint` complains that I can't exceed maximum of 20 public methods. `vocabulary_test.py` already has 18 methods for tests without counting mine. Was this limit intended for test files as well? 

.pylintrc:
```
# Maximum number of public methods for a class (see R0904).
max-public-methods=20
```

**Comment by joelgrus** [comment]
just add `too-many-public-methods` to the pylint disable at the top of `vocabulary_test.py`

**Comment by HarshTrivedi** [comment]
ok, thanks.
