### ISSUE TITLE
Learning rate not read as float when given in scientific notation

### ISSUE THREAD

**Issue by dallascard** [allenai/allennlp#1429]
**Describe the bug**
Specifying the learning rate for an optimizer seems to fail if it is given in scientific notation. 0.001 is fine, but 1e-3 is not. Based on the error, it seems as though the latter is being read as a string. For example, for adagrad, the error is:
```
File "[...]/anaconda3/envs/allennlp/lib/python3.6/site-packages/torch/optim/adagrad.py", line 64, in step
    clr = group['lr'] / (1 + (state['step'] - 1) * group['lr_decay'])
TypeError: unsupported operand type(s) for /: 'str' and 'int'
```

**To Reproduce**
This can be reproduced using the [allennlp-as-a-library-example](https://github.com/allenai/allennlp-as-a-library-example)
Specifically, if you add the following entry to the boe config:
`config['trainer']['optimizer']['lr'] = 0.001`
everything is fine, but adding 
`config['trainer']['optimizer']['lr'] = 1e-3`
will cause the above error.

**System (please complete the following information):**
 - OS: Linux
 - Python version: 3.6.5
 - AllenNLP version: 0.4.3-py36_0 nfliu
 - PyTorch version: 0.3.1.post2

**Comment by joelgrus** [comment]
it looks like this is a bug in `pyhocon`, which is what older versions of AllenNLP use to read config files. 

the latest release 0.5.2 uses a different JSON variant called jsonnet, so upgrading to 0.5.2 should fix this issue

**Comment by joelgrus** [comment]
oops, 0.5.2 isn't released yet, I was looking at the draft release notes, but when it comes out it will fix your issue. in the meantime use decimals :)
