### ISSUE TITLE
How to use the output file and what is the format of the input file ?

### ISSUE THREAD

**Issue by Antlar-lu** [allenai/allennlp#1431]
When I use Elmo , and the input is a 936K .txt file , I got a 2.1G output file. However , I do not know how to use it , and is the input file's format right ?
I install allennlp by conda&pip (pytorch version)
Hope someone can help me out ! Thank you very much !

**Comment by nelson-liu** [comment]
are you referring to ELMo? Maybe the snippet here helps? https://github.com/allenai/allennlp/pull/1404

**Comment by Antlar-lu** [comment]
@nelson-liu Yes, I mean ELMo , and I re-edit the questions, #1404 seem not get any answers yet. I will focus on it. Thank you !

**Comment by DeNeutoy** [comment]
Please read this tutorial: https://github.com/allenai/allennlp/blob/master/tutorials/how_to/elmo.md
and see the output of `allennlp elmo -h`. Feel free to re-open with a more specific question!
