### ISSUE TITLE
Adding up on exposed Elmo Model

### ISSUE THREAD

**Issue by PrashantRanjan09** [allenai/allennlp#1432]
Hi,
I am trying to build on top of the Elmo model exposed in tensorflow hub.
Can we use that model to train it further on my data?
If yes, How do we do it?

**Comment by DeNeutoy** [comment]
This version has trainable scalar parameters for a downstream task:
https://www.tensorflow.org/hub/modules/google/elmo/2
This version allows all of it's parameters to be trained.
https://www.tensorflow.org/hub/modules/google/elmo/1

Please refer to Tensorflow for documentation about how to use TensorflowHub.

**Comment by PrashantRanjan09** [comment]
Thank you Mark. But say I have an options file and and a weights file after i trained on some data. 
Now i want to train it on some other data and want to update the same weights file.
How do i update the same weights file.
