### ISSUE TITLE
[Is this a bug?]: BiDAF appears to access wrong metadata instances when running on multiple GPUs

### ISSUE THREAD

**Issue by MaxMotovilov** [allenai/allennlp#1439]
This loop https://github.com/allenai/allennlp/blob/43fc89ee59944dca0de01ca5ab2843c9926323d6/allennlp/models/reading_comprehension/bidaf.py#L274 iterates over the range obtained from a tensor dimension corresponding to batch size https://github.com/allenai/allennlp/blob/43fc89ee59944dca0de01ca5ab2843c9926323d6/allennlp/models/reading_comprehension/bidaf.py#L176 accessing elements of the `metadata` list with indices in this range. This is reasonable in a CPU or single GPU scenario where `forward()` operates on the entire batch generated by the trainer algorithm. With multiple GPUs, all tensors passed into `forward()` are sliced and scattered across GPU instances with `forward()` transparently receiving only a subset of data (e.g. with configured batch size of 20 on 8 GPUs, we see actual `batch_size` in `forward()` to be either 2 or 3). Metadata is copied into each call to `forward()` in its entirety since it does not contain tensors. Therefore the majority of the metadata access happens with a wrong index: the tensors operated on are not conformal to the array of metadata instances.

I wonder if the results of BiDAF training on multiple GPUs were previously found deficient or inferior to training them on a single GPU with otherwise identical configuration. This apparent disconnect in the code may explain such an outcome. I have only run across this issue by comparing BiDAF code with the multi-paragraph version in https://github.com/allenai/allennlp/pull/804 which actually generates a runtime exception because of it. Of course, being an absolute newbie in this codebase I may be completely wrong!

**Comment by DeNeutoy** [comment]
Hello - Multi-GPU training is very experimental and essentially not supported. Presumably you saw this warning:
https://github.com/allenai/allennlp/blob/master/allennlp/training/trainer.py#L291

In particular, MultiGPU training will only work correctly if all of the inputs and outputs to `forward` are tensors. There will be many, many other caveats to this statement - for instance, I think many `Metrics` will work incorrectly.

**Comment by MaxMotovilov** [comment]
That said, there's a significant advantage to multi-GPU training; I intend to try and work through what issues I can deal with but would appreciate feedback from the code owners as to whether I'm even barking up the right tree so to say

**Comment by brendan-ai2** [comment]
This should be fixed in master. Please let me know if that's not what you observe! Thanks!
