### ISSUE TITLE
ELMO on sentences containing '/' character

### ISSUE THREAD

**Issue by TigranGalstyan** [allenai/allennlp#1440]
If I understand correctly,  allennlp elmo command creates an hdf5 file with a **dataset** for every sentence, where the values are numpy arrays of vector representation. But when the sentence contains this symbol ('/') it splits the sentence, and creates a **group**, where the key is the first half of a sentence (the one before '/'). I believe the sentences containing '/' should behave the same as all the others.

**To Reproduce**

Run the following command:

```echo "a / a ." > sample.txt```
```allennlp elmo sample.txt sample_elmo.hdf5 --all```

**Comment by DeNeutoy** [comment]
Hello! Thanks, this is fixed already on master. 

See #1163 for more context + a temporary solution.
