### ISSUE TITLE
Add a .get() method to Params

### ISSUE THREAD

**Issue by matt-gardner** [allenai/allennlp#1447]
Getting a parameter from a `Params` object without popping it is currently annoying and requires accessing the inner `.params` object that should be private.  We should just add a `.get()` method that works.

**Comment by HarshTrivedi** [comment]
Isn't it already there [(link)](https://github.com/allenai/allennlp/blob/master/allennlp/common/params.py#L204)?

**Comment by matt-gardner** [comment]
Hmm, oops. I've seen a few places in code and PRs (I think) where people have done `params.params.get()...`, and that's what motivated this issue. Maybe I misunderstood the reason for that code; I need to look into it a little more.

**Comment by schmmd** [comment]
Feel free to add more context and unassign, or close.
