### ISSUE TITLE
some example training configs still have HOCON syntax, not jsonnet

### ISSUE THREAD

**Issue by joelgrus** [allenai/allennlp#1452]
e.g. SRL

maybe they should be renamed .jsonnet as well

**Comment by schmmd** [comment]
I complete support renaming the configuration files to `.jsonnet` ;-)

@joelgrus does this mean these training files don't work at all now that we've moved to jsonnet?

**Comment by joelgrus** [comment]
that's correct, although they already didn't work for anyone who didn't have the relevant environment variables set

**Comment by schmmd** [comment]
This is fixed!

**Comment by schmmd** [comment]
#1479
