### ISSUE TITLE
Python3.7

### ISSUE THREAD

**Issue by saurabhbh21** [allenai/allennlp#1457]
Is python3.7 supported version of allennlp is released?

**Comment by HarshTrivedi** [comment]
Currently code is on Python 3.6 and so tests have been checked in 3.6 environment. You can try to use 3.7 and check if `pytest` gives any error. As long as all tests pass, you can use 3.7. However, I would advice you to stick to 3.6 since integrations tests for newer commits are being run in 3.6.

**Comment by joelgrus** [comment]
I couldn't get pytorch to pip install on python 3.7 (although I didn't spend very long trying)

**Comment by matt-gardner** [comment]
This is going to wait until pytorch releases a new version that supports python 3.7, and our supporting python 3.7 will happen for free once we upgrade to that pytorch version (it requires no code changes from us).  So I'm closing this for now.

**Comment by HarshTrivedi** [comment]
pytorch supports 3.7 now ... I haven't tried installing it though.
