### ISSUE TITLE
Are the pretrained ELMo models covered by the Apache 2.0 license?

### ISSUE THREAD

**Issue by cdfox** [allenai/allennlp#1462]

**Comment by schmmd** [comment]
@cdfox I'm not a lawyer, but my understanding is that Apache 2.0 is a software license and ELMo models are not software.

That said, the ELMo models were trained by Apache 2.0 software (see https://github.com/allenai/bilm-tf) and the source data is from an Apache 2.0 software package (see https://github.com/ciprian-chelba/1-billion-word-language-modeling-benchmark).  We don't impose any restrictions on our models.
