### ISSUE TITLE
Are precision and recall flipped in this case?

### ISSUE THREAD

**Issue by FushanLi** [allenai/allennlp#1464]
Hi, 

I find in the semantic_role_labeler_test.py and span_based_f1_measure_test.py when you call

`perl_script_command = ["perl", str(self.TOOLS_ROOT / "srl-eval.pl"), prediction_file_path, gold_file_path]. `

prediction_file_path and gold_file_path are flipped according to the official CoNLL05 description. 

Although this should not affect f1 score, precision and recall are flipped in this case.

Thanks!

**Comment by schmmd** [comment]
@DeNeutoy are you able to take a look here?

**Comment by schmmd** [comment]
@DeNeutoy ping?

**Comment by matt-gardner** [comment]
@DeNeutoy, can you decide whether this is an issue, or just close it if it's not?

**Comment by DeNeutoy** [comment]
This test is somewhat vacuous anyway as the files are the same, closing
