### ISSUE TITLE
Allow to use a different dataset reader in predictors

### ISSUE THREAD

**Issue by matt-peters** [allenai/allennlp#1470]
Feature request: allow the user to easily specify a different dataset reader when making predictors, or otherwise easily do minor transformations on the input data (e.g. change the names of keys). See https://github.com/allenai/allennlp/pull/1469#discussion_r201175289 for context.

**Comment by matt-gardner** [comment]
I tried to figure out a good solution here, and I can't think of one.  If the only issue is to change the name of keys, it seems a whole lot easier to just standardize the names of fields for a particular task if you want to share the predictor.  Everything else seems like a huge pain, both in code complexity and in configuring things at runtime.  If someone has a good idea for how to handle this, I'm happy to hear it.

If we need to make the entailment predictor more useful for submitting to a leaderboard, that has a much easier solution than adding the ability to specify a different dataset reader at runtime - just make the dataset reader accept either key as input, and/or make the predictor output an additional key, depending on what's needed.

@nelson-liu, what was the reason you wanted a different dataset reader in the comment that @matt-peters linked?

**Comment by nelson-liu** [comment]
so in the code for my project, i've got a single `Tagger` model class and a single `PairwiseTagger` model class. I wanted to use datasets from allennlp like the `CCGBank` / `conll2003` / `UD` readers, but this was nontrivial to do because the "labels" (tags that i care about) for each of these dataset readers are in different keys.

Does that add some more context?

**Comment by joelgrus** [comment]
couldn't you just override `predict_json` and `predict_instance` in your predictor and do the name remapping inside those (in a configurable way, if you like)

IIRC nelson's issue was more about being able to doing this for evaluation (so no predictor involved), not prediction

**Comment by matt-gardner** [comment]
@joelgrus, yes, you could, but that means writing a new predictor; I thought the whole point of this was to make it so you didn't have to write a new predictor just to change keys around.

@nelson-liu, ah, yeah, that's pretty different.  In that case, I'd probably just write an adaptor `DatasetReader` class that calls `read()` on an existing dataset reader, pulls out some fields, and changes their name.  You could probably do this with a single class, not one per existing dataset reader, if you design it right.

**Comment by matt-gardner** [comment]
Well, actually, that kind of adaptor might work for the use case in this issue, also...

**Comment by matt-gardner** [comment]
Closing this, as it seems like the right solution is to standardize the model APIs for a task instead of adding a ton of complexity around predictors.  Feel free to re-open if you think there's a better solution here.
