### ISSUE TITLE
pip install and no 'elmo.py' in modules

### ISSUE THREAD

**Issue by hahmyg** [allenai/allennlp#1471]
I downloaded allennlp via pip to use Elmo, however, the pip-version does not support elmo yet

**Comment by nelson-liu** [comment]
what version did you install?
can you give me a command that doesn't work? 
Does `allennlp elmo -h` work for you?

**Comment by timniven** [comment]
Same for me. I just ran pip install and it installed 0.1a6. I couldn't find 0.5.1 via pip even though search shows it as latest. I'm on Ubuntu 16.04 and had a Python 3.5 environment. 

This led me to believe my Python version was the problem, which it was - I ran pip install allennlp in Python 3.6 and it installed 0.5.1.

**Comment by DeNeutoy** [comment]
Ah right - we should delete that package. Allennlp > 0.1 actually requires python 3.6, as we use inline type hints extensively.

**Comment by manuelsh** [comment]
I still have the same issue.
