### ISSUE TITLE
Update the tutorial and the allennlp-as-a-library to reflect Predictor API changes

### ISSUE THREAD

**Issue by handsomezebra** [allenai/allennlp#1472]
**Describe the bug**
The Predictor API was changed in #1422 but the tutorial for writing your own predictors and also the allennlp-as-a-library code is still using old APIs. In #1467 I described what can happen if I run latest allennlp on the old Predictor API.

**Expected behavior**
It's expected that the tutorial and the example code reflect the current status of API.

**Comment by matt-gardner** [comment]
The `allennlp-as-a-library` code and the tutorials use the latest _released_ version of allennlp, which is intentional.  When we release a new version, we update our documentation and example repos to reflect the changes since the last release.
