### ISSUE TITLE
Make some of the dependencies optional for prediction

### ISSUE THREAD

**Issue by handsomezebra** [allenai/allennlp#1473]
**Is your feature request related to a problem? Please describe.**
I am building docker images which do online predictions using pretrained allennlp models. However there are numerous dependencies of allennlp which significantly slow down the building of the images and also make the size of image unnecessarily big.  Those dependencies include spacy, nltk, scipy, scikit-learn, aws-cli, etc. Although these are great and useful tools but in our application we either use some alternative tools or do them in upstream components. For example we found spacy 2.0 significantly slower than 1.x so we still stick to 1.x in our components.

**Describe the solution you'd like**
Can we make some of the requirements optional so that pip doesn't install them all. And then users can choose to install if necessary. This may involve changing those import to inline so that they are imported only when the components are called.

**Describe alternatives you've considered**
I was thinking to use pip uninstall to uninstall some of them but it's a little hacky and I am not sure if it will break those imports.

**Comment by DeNeutoy** [comment]
Hi there,
This is a lot of work and would make it 1) less robust to use allennlp for research, which is what it is primarily designed for and 2) make it harder to maintain.

Unfortunately we are unlikely to consider doing this. Pytorch should have production level features in its 1.0 release, which is due by the end of this year I believe. Whether this will be suitable for NLP models is an open question.
