### ISSUE TITLE
Machine comprehension (BiDAF)

### ISSUE THREAD

**Issue by pradeepm2017** [allenai/allennlp#1482]
I am using BiDAF model for retrieving answers from the passage. For the same question, I have multiple relevant passages which can answer the question. Can I feed all the passages together to the model and obtain results once? By passing "n" passages to the model for n answers for a question, it is taking 1.5 sec*n on average.  I have used pretrained elmo word representations in the comprehension model. 

Is there any other way I can reduce total run time to obtain the answers from n passages.

Thank you, 

Regards,

**Comment by DeNeutoy** [comment]
Please see the discussion on https://github.com/allenai/allennlp/issues/1408 for issues relating to relative scoring of paragraphs. 

Other ways to speed up prediction are to use a GPU and batching, which should help considerably. In this scenario you could make a batch out of all of your paragraphs, which would then be processed in parallel (although independently).
