### ISSUE TITLE
Example bidaf model for SQuAD does not work - learning rate scheduler requires validation metric.

### ISSUE THREAD

**Issue by chaxor** [allenai/allennlp#1489]
**Describe the bug**
When running the standard tutorial example of a bidaf model for the SQuAD dataset, the following output is obtained:

`learning_rate_schedulers.py", line 74, in step
    raise ConfigurationError("The reduce_on_plateau learning rate scheduler requires "
allennlp.common.checks.ConfigurationError: 'The reduce_on_plateau learning rate scheduler requires a validation metric to compute the schedule and therefore must be used with a validation dataset.`

**To Reproduce**

This is retreived when running this simple command:

`allennlp train bidaf.json --serialization-dir ../../output_of_model`

where `bidaf.json` is retrieved from 

"https://github.com/allenai/allennlp/blob/c9b52613cc3c5ab933bedddef6d63d06380e41b9/experiment_config/bidaf.json"

and the validation, glove, and training dataset paths are set to the amazon locations, as in:

"https://github.com/allenai/allennlp/blob/master/training_config/bidaf.json"

**Expected behavior**
Obviously, this should just train and not error...

**System (please complete the following information):**
 - OS: Arch Linux
 - Python version: 3.6
 - AllenNLP version: 0.5.0
 - PyTorch version: 0.3.1

**Comment by DeNeutoy** [comment]
This is fixed on master - https://github.com/allenai/allennlp/pull/1255

It will be in the next release, in the mean time please install from master.
