### ISSUE TITLE
Text similarity 

### ISSUE THREAD

**Issue by ajay01994** [allenai/allennlp#1495]
Hi Team ,
Nice work here , i just want to understand is there a model for text similarity here and can textual entailment be used as an  alternate to Text similarity process . Sorry  for raising it as an issue i could  not find any forums or discussion groups to post this thing up , Hope you don't mine :) 

Thanks

**Comment by DeNeutoy** [comment]
Hello!

Textual entailment isn't really the same as textual similarity, but it can act as a proxy. You might be interested in looking up information about paraphasing or question similarity, like the Quora dataset:
https://www.kaggle.com/c/quora-question-pairs
