### ISSUE TITLE
How can I get the main mention when doing coreference resolution?

### ISSUE THREAD

**Issue by meggie-wong** [allenai/allennlp#1502]
Hello,

When I use your tool to do coreference resolution, I need to replace the pronoun with the main mention (Span of the most representative mention). Could you tell me how can I get the main mention in a cluster?

Thanks very much.

**Comment by DeNeutoy** [comment]
Hi - unfortunately the co-reference model only models clusters, and not heads within clusters. It seems possible that you could extract the main NP/Named Entity from the cluster and use that?

**Comment by meggie-wong** [comment]
Thanks for your response, while could you give me some instructions on how to extract the main entity form the cluster? I am not so familiar with this field.

**Comment by rushabhshah10** [comment]
Hi,

Can you please provide sample code snippet for finding main/head mention using NP within cluster ?

**Comment by davidjackson99** [comment]
Any update on the sample code for finding the representative mention? Thanks a lot.
