### ISSUE TITLE
Broken link in tutorial

### ISSUE THREAD

**Issue by andrejzg** [allenai/allennlp#1507]
**Describe the bug**
The tutorial `using_as_a_library_pt1.md` has a broken link. It's meant to link to `using_as_a_library_pt2.md` but instead links to `making_predictions_and_creating_a_demo.md`. 

**To Reproduce**
Steps to reproduce the behavior
1. Go to [part 1](https://github.com/allenai/allennlp/blob/master/tutorials/getting_started/using_as_a_library_pt1.md) of the using as a library tutorial page.
2. Scroll down to the very bottom.
3. Click on **Making Predictions and Creating a Demo**
4. 404 error

**Expected behavior**
The link should instead take you to [part 2](https://github.com/allenai/allennlp/blob/master/tutorials/getting_started/using_as_a_library_pt2.md) of the tutorial.

**Comment by schmmd** [comment]
@andrejzg thanks for reporting!
