### ISSUE TITLE
Re: Machine Comprehension

### ISSUE THREAD

**Issue by meetferoz** [allenai/allennlp#1510]
Hi,
Is it possible to get a response in terms of "yes" and "no" when we query an evidence text.
For e.g. if there is a topic on robotics and the user query, Are robots human?, Then the response should be "No" and may be some explaination to follow rather than a just a selected text from the evidence text.
is this possible?

**Comment by DeNeutoy** [comment]
Not really, unfortunately. A binary classification model would suit you better in this case.
