### ISSUE TITLE
SRL result on CoNLL-2005

### ISSUE THREAD

**Issue by KiroSummer** [allenai/allennlp#1511]
Very interesting and wonderful work.
I'm curious about the performance on SRL CoNLL-2005 dataset which you did't list on your paper.
If you have conduct experiments on CoNLL-2005, could you tell me the performance?

Thanks very much.

**Comment by DeNeutoy** [comment]
Hi, sorry we don't have results on CoNLL-2005. I would urge you to check out this paper, recently published at ACL: https://arxiv.org/pdf/1805.04787.pdf and the corresponding code: https://github.com/luheng/lsgn

Luheng has results on both CoNLL 2005 and 2012 and achieves very impressive results, particularly without gold predicates.

Thanks!
