### ISSUE TITLE
ELMo: The representation of two layers are the same

### ISSUE THREAD

**Issue by shuaichenchang** [allenai/allennlp#1516]
When I fed a sentence to ELMo following the instruction, I got two representation of two-layer LSTM hidden, but I found, for each word, its two-layer hidden vectors are identical.

**To Reproduce**
`from allennlp.modules.elmo import Elmo, batch_to_ids`
`options_file = "https://s3-us-west-2.amazonaws.com/allennlp/models/elmo/2x4096_512_2048cnn_2xhighway/elmo_2x4096_512_2048cnn_2xhighway_options.json"`
`weight_file = "https://s3-us-west-2.amazonaws.com/allennlp/models/elmo/2x4096_512_2048cnn_2xhighway/elmo_2x4096_512_2048cnn_2xhighway_weights.hdf5"`
`elmo = Elmo(options_file, weight_file, 2, dropout=0)`
`sentences = [['First', 'sentence', '.'], ['Another', '.']]`
`character_ids = batch_to_ids(sentences)`
`embeddings = elmo(character_ids)`

**Comment by shuaichenchang** [comment]
Thanks very much @DeNeutoy. I found in elmo.py `bilm_output` has the 3-layer vectors. That is what I want, thank you for the help!

**Comment by matt-gardner** [comment]
Closing this issue, but what you said @DeNeutoy makes me wonder if there's really a point to returning multiple copies of the same vector - can't the caller just use it twice, instead? Surely there's something I'm missing here?

**Comment by DeNeutoy** [comment]
No, because we want to be able to run elmo only once, but return differently parameterised weightings of the layers. The `ScalarMix` needs to be inside here so we can use elmo as a token embedder.

**Comment by matt-gardner** [comment]
Oh, I see, you initialize the `ScalarMix` to a uniform weighting, which is why it looks identical to start with; but after training, they'll be different.  Ok.  I misunderstood the original comment.  Thanks.
