### ISSUE TITLE
import-package should accept paths as well as pythonpaths

### ISSUE THREAD

**Issue by XuezheMax** [allenai/allennlp#1526]
`--include-package` fails if you pass it a path - it expects a python module, e.g `scigraph/definition_extraction` vs `scigraph.definition_extraction`.

**Comment by schmmd** [comment]
Closing--as that's the intended behavior.  Feel free to re-open if the error is particularly confusing.

**Comment by DeNeutoy** [comment]
This is something we should change, re-opening

**Comment by schmmd** [comment]
@DeNeutoy I'm pretty sure we discussed this as a group in triage and thought that we should maintain the current behavior.  I don't personally have very strong opinions on this, but would you justify why you think we should change the current behavior?
