### ISSUE TITLE
non-tuple multidimensional indexing in ArrayField will be deprecated by NumPy

### ISSUE THREAD

**Issue by nelson-liu** [allenai/allennlp#1528]
FYI:

  /home/travis/miniconda3/envs/testenv/lib/python3.6/site-packages/allennlp/data/fields/array_field.py:40: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
    return_array[slices] = self.array

**Comment by schmmd** [comment]
Fixed in #1543
