### ISSUE TITLE
AllenNLP fails to load tarballs created on a Mac

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp#1531]
Here's a bug reported by @nikett.

**Describe the bug**
When you create a model tarball on a Mac, the system includes some binary dotfiles that cause predictions to crash when using the model.

**To Reproduce**
1. Create a tarball with `tar -czvf my_model.tar.gz config.json vocabulary/* weights.th`.
2. Make a prediction using the tarball you just created.
3. You will get an error similar to `UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa3 in position 37: invalid start byte`.

**System (please complete the following information):**
 - OSX
 - Python 3.6

**Additional context**
You can work around the error on a mac by creating your tarball as follows `COPYFILE_DISABLE=1; export COPYFILE_DISABLE; tar -czvf my_model.tar.gz config.json vocabulary/* weights.th`

**Comment by schmmd** [comment]
I'm not able to reproduce the binary files on my mac, but clearly others run into this issue: https://stackoverflow.com/questions/8766730/tar-command-in-mac-os-x-adding-hidden-files-why

**Comment by schmmd** [comment]
Niket and I tried a bit but we were not able to reproduce this error on master.  He sent me a model that has the weird files in it, but it's only executable on his branch.

We're putting this on hold for now.  But, if he can, Niket will send me a version of one of our published files with the weird additions in it so I can troubleshoot the error.

**Comment by schmmd** [comment]
Closing for now--but we can re-open if we have a good way to reproduce this.

**Comment by ZhaofengWu** [comment]
For other people encountering this issue, `find . -name '.*' -delete` also works if you already have the tarball generated.
