### ISSUE TITLE
Add an option to ERM trainer to choose whether finished states should be pruned

### ISSUE THREAD

**Issue by pdasigi** [allenai/allennlp#1532]
**Is your feature request related to a problem? Please describe.**
When doing beam search during training with the [ERM decoder trainer](https://github.com/allenai/allennlp/blob/master/allennlp/nn/decoding/decoder_trainers/expected_risk_minimization.py), currently beam pruning happens only on unfinished states. That is, all the new states are considered, finished states are preserved, and a beam is constructed with unfinished states and pruned. This worked well with the [NLVR parser](https://github.com/allenai/allennlp/blob/master/allennlp/models/semantic_parsing/nlvr/nlvr_coverage_semantic_parser.py), but with the [WikiTables parser](https://github.com/allenai/allennlp/blob/master/allennlp/models/semantic_parsing/wikitables/wikitables_erm_semantic_parser.py), we found it was inefficient to create finished states and keep them, because state creation is expensive.

**Describe the solution you'd like**
We need an option to choose whether or not to prune finished states, so that for those parsers that need finished states to be pruned, we can avoid creating them by passing a `max_actions` argument [here](https://github.com/allenai/allennlp/blob/master/allennlp/nn/decoding/decoder_trainers/expected_risk_minimization.py#L85).

**Additional context**
Cleaner way to implement the bug fix in #1216

**Comment by schmmd** [comment]
@pdasigi is this still an issue?

**Comment by pdasigi** [comment]
Looks like this is no longer relevant after @matt-gardner's `state_machines` reimplementation. Pruning before state-creation is still an option, by passing a `max_actions` option [here](https://github.com/allenai/allennlp/blob/master/allennlp/state_machines/trainers/expected_risk_minimization.py#L83), but given that we are not doing it currently, and training ERM parsers for WikiTableQuestions does not take too much time now, efficiency is no longer a concern, and we do not need to expose the option to pre-prune states. Closing this issue.
