### ISSUE TITLE
test_install fails after following some of our instructions

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp#1534]
1.  If you follow the instructions for installing AllenNLP via pip, any tests that rely on `scripts` will fail (although I think we've taken care of these) and the tests that rely on the JVM may fail.

2.  If you follow the instructions for using AllenNLP from Docker going forward (as we're starting to package AllenNLP via pip) the user gets 12 failures.

```
$ docker run -it -p 8000:8000 --rm allennlp/allennlp:v0.5.1-pip test-install
...
tests/models/semantic_parsing/wikitables/wikitables_erm_semantic_parser_test.py F
tests/models/semantic_parsing/wikitables/wikitables_mml_semantic_parser_test.py FFFFFFFF
tests/predictors/wikitables_parser_test.py FF
tests/training/metrics/wikitables_accuracy_test.py F
...
```

Ideally in either of these cases, `test_install` would validate the installation.

**Comment by schmmd** [comment]
I see the following ways forward:

1.  Add installation instructions for the JVM and add the JVM (several hundred MB) to our pip distribution of AllenNLP.

2.  Put the JVM tests from `test_install` behind a flag (`--include-jvm-tests`).

I don't think most of our users need the components that call out to the JVM, so I'm strongly in favor of 2, but would love to get @matt-gardner 's opinion.

Also, @nelson-liu weren't we thinking about this issue earlier?  I wasn't able to find that thread, if it existed.

**Comment by nelson-liu** [comment]
i'm not sure if you can pip install the jvm, but you can certainly `conda install openjdk perl` to get the JVM + perl (which is also used in some of the scripts)

**Comment by schmmd** [comment]
Right--I know we can install it--I'd just rather not to keep the size of the image small if most of our users are not using the JVM.

**Comment by nelson-liu** [comment]
oops, missed that you were referring to bundling it in the docker image, apologies. Also in favor of option 2, in that case.

**Comment by schmmd** [comment]
Should be fixed by https://github.com/allenai/allennlp/pull/1551 (verifying now in TeamCity after adding `test_install` to CI for master).
