### ISSUE TITLE
the "files to add" functionality of archiving should avoid duplication

### ISSUE THREAD

**Issue by joelgrus** [allenai/allennlp#1537]
the way I've got the openai transformer embedder setup, the `TokenIndexer` and `TokenEmbedder` both depend on the same 500MB tar.gz file.

I believe that if we wanted to include that as part of a model archive, it would get included twice! It shouldn't be too hard for the "files to add" logic to check whether the same file appears multiple times and only add it once (and then handle it correctly during deserialization).

**Comment by matt-gardner** [comment]
I think we should deprecate "file to add" in favor of using URLs.  Closing this (very stale) issue unless someone really wants to work on this functionality.
