### ISSUE TITLE
pytest fails if /tmp/allennlp_tests/ already exists and cannot be deleted

### ISSUE THREAD

**Issue by dallascard** [allenai/allennlp#1539]
**Describe the bug**
Running tests with pytest causes allennlp to create and delete the directory /tmp/allennlp_tests/ but if this directory already exists and is owned by a different user, the attempt to delete the directory at the end of the test will fail.

**To Reproduce**
mkdir /tmp/allennlp_tests/
chmod a-r /tmp/allennlp_tests/
pytest (in any allennlp project with tests)

**Expected behavior**
This should fail with PermissionError: [Errno 13] Permission denied: '/tmp/allennlp_tests/'

**System (please complete the following information):**
 - OS: Linux
 - Python version: 3.6
 - AllenNLP version: 0.4.3

**Additional context**
The problem seems to be in allennlp/allennlp/common/testing/test_case.py where the temp directory is hard coded as
`self.TEST_DIR = pathlib.Path("/tmp/allennlp_tests/")`
It seems like it would be better if this used the pytest temp directory.

**Comment by schmmd** [comment]
Wow that's a lot of failures!  Easy to reproduce with:

```
mkdir -p /tmp/allennlp_tests/
sudo chown root /tmp/allennlp_tests/
pytest .
```

**Comment by schmmd** [comment]
This is also a blocker for anyone trying to run tests on Windows (`/tmp` won't exist).  I started working on a solution here in https://github.com/allenai/allennlp/pull/1556 but ran into https://github.com/allenai/allennlp/issues/1563.
