### ISSUE TITLE
Best practices for token normalization with ELMo

### ISSUE THREAD

**Issue by danieldeutsch** [allenai/allennlp#1547]
I am trying to incorporate ELMo into my model, but I have a question about the best way to preprocess my input data.

Should I lowercase the tokens? I generally do this as standard practice, but I ran into an issue with beginning/end of sentence tokens. According to the [ELMo readme](https://github.com/allenai/allennlp/blob/master/tutorials/how_to/elmo.md), I need to add `<S>` and `</S>` to my input sentences. If I use allennlp's tokenizer to add these tokens and use the token indexer to lowercase the tokens, the beginning/end of sentence tokens are converted to `<s>` and `</s>`, which I assume means ELMo will not recognize them. If this is the case, could functionality be added to the token indexers to ignore normalizing specific tokens?

If I should not lowercase the input, then I think I will run into problems with using some pretrained word embeddings. The ELMo readme shows concatenating ELMo vectors to pretrained GloVe embeddings, which are already lowercased as far as I can tell. If I don't lowercase the input, then fewer of the tokens will have pretrained embeddings. I want to restrict my vocabulary to be only words which have pretrained embeddings, so this reduces the size of my vocabulary.

It would be great if the best practices for handling token normalization for ELMo could be added to the ELMo readme, especially because the details are pretty nuanced and hard to get right.

**Comment by matt-peters** [comment]
I will add some details tomorrow -- but in the meantime, best practices are to not do any normalization for ELMo.  allennlp has the ability to maintain separate namespaces for different indexing schemes, so you can have both lowercased tokens for GloVe and unnormalized character based ids for ELMo.  This is exactly what the example in the ELMo tutorial does, see the sections here: https://github.com/allenai/allennlp/blob/master/tutorials/how_to/elmo.md#using-elmo-with-existing-allennlp-models

The `<S>` and `</S>` are added outside the indexers.  They are added inside the ELMo module and then removed, so you will never see them if you treat ELMo as a black box so don't add them to your text (if you are using the provided allennlp indexers and embedders).

**Comment by danieldeutsch** [comment]
Great, good to know the details. Thanks!
