### ISSUE TITLE
Unsupported parameter --output-file ?

### ISSUE THREAD

**Issue by aleSuglia** [allenai/allennlp#1550]
**Describe the bug**
The optional parameter `--output-file` for the evaluate command seems that it's not working properly.
Error message below:
```
usage: allennlp
allennlp: error: unrecognized arguments: --output-file
``` 

**To Reproduce**
`allennlp evaluate my_model.tar.gz my_test_set.txt --output-file ../my_path/output.txt`

**Expected behavior**
The results of the evaluation should be stored in the file `../my_path/output.txt`.

**System (please complete the following information):**
 - OS: Linux
 - Python version: 3.6
 - AllenNLP version: v0.5.1
 - PyTorch version: default

**Additional information**
I tried to execute the command with the help option (-h) and I got:
```
usage: allennlp evaluate [-h] --evaluation-data-file EVALUATION_DATA_FILE
                         [--weights-file WEIGHTS_FILE]
                         [--cuda-device CUDA_DEVICE] [-o OVERRIDES]
                         [--include-package INCLUDE_PACKAGE]
                         archive_file
```
Which is something that I was not excepting because in the master repository there is clearly an argument `--output-file`: https://github.com/allenai/allennlp/blob/master/allennlp/commands/evaluate.py#L66

Any ideas about this? Thanks!

**Comment by DeNeutoy** [comment]
Hello,

sorry this is a new feature added recently - it has not been released yet (i.e unless you have installed from master, your installation will not contain the `--output-file` argument for `evaluate`). We will be doing another release within the next few days.

**Comment by HarshTrivedi** [comment]
`--output-file`  parameter was recently added to the master (#1512). But I think you are using `0.51` installed from pip instead of the master-branch ..

**Comment by aleSuglia** [comment]
Oh I see. Sorry about that. I was using the master version as a way to inspect the code. @DeNeutoy Happy to hear that :)
