### ISSUE TITLE
How to go backwards from embedding to token/character space?

### ISSUE THREAD

**Issue by Kreiswolke** [allenai/allennlp#1553]
I was wondering if the ELMo model in its current form is capable to output - for a given embedding - the most-similar token/word representation (word2vec/glove-style)? Or otherwise, it would be useful to have a vocabulary which holds all tokens seen during training - because with the character-based language model the input possibilities are infinite.

**Comment by Kreiswolke** [comment]
Great, thank you for the clarification. Does elmo being contextual also imply that it is unreasonable to make use of single words as the input (or at least doesn't give you an advantage over standard word embeddings)? I experimented a little with elmo embeddings e.g. for ['cat'] , ['dog'] and ['president'] and found that their cosine similarities behave similar to word2vec. This is also where my question originated from - so basically one could find a best matching/most activating input word for a given elmo vector but one would need a vocabulary of possible candidates(?).

**Comment by DeNeutoy** [comment]
Right, yes you could do that, but as you say i'm not sure what that brings you over using Glove vectors.
