### ISSUE TITLE
Consider turning off shuffling during validation and evaluation

### ISSUE THREAD

**Issue by nelson-liu** [allenai/allennlp#1562]
Currently, the data iterator shuffles the data when producing instances for validation and evaluation. 

It's not clear that this is desirable --- it seems like the convention is to not shuffle at validation / evaluation. It also might make it easier to debug issues if the instances come in a particular expected order.

Maybe we should consider not shuffling the instances during validation and evaluation?

**Comment by matt-gardner** [comment]
No objections from me.

**Comment by schmmd** [comment]
@nelson-liu do you mind making a PR for this?

**Comment by nelson-liu** [comment]
sure, happy to do so

**Comment by HarshTrivedi** [comment]
This was done  (#1578), I think the issue should be closed now.

**Comment by nelson-liu** [comment]
thanks for the reminder @HarshTrivedi !
