### ISSUE TITLE
GPU for Named Entity Recognition

### ISSUE THREAD

**Issue by saurabhbh21** [allenai/allennlp#1567]
I'm trying to execute the NER model (https://s3-us-west-2.amazonaws.com/allennlp/models/ner-model-2018.04.26.tar.gz) in GPU, but it's not using GPU(rather normal CPU) in Azure NV6.

**Comment by joelgrus** [comment]
what's the exact command you're running?

**Comment by VictorSanh** [comment]
I sometimes have to add `CUDA_VISIBLE_DEVICES=0` at the beginning of the bash command (and replace 0 with whichever GPU you want to use). I don't know if it can help....

**Comment by joelgrus** [comment]
`Predictor.from_path` should really take a `cuda_device` parameter, I'll open an issue for that. 

In the meantime, just do

```
archive = load_archive(model_path, cuda_device=0)
predictor = Predictor.from_archive(archive)
```

(or use Nelson's hack)

**Comment by saurabhbh21** [comment]
Thanx for the help.
