### ISSUE TITLE
/scripts/check_requirements.py no longer works correctly

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp#1571]
We merged requirements.txt and requirements_test.txt and the script checks for any discrepancies between the two.  Since the dependencies in requirements_test.txt are not in setup.py it always fails.  See https://github.com/allenai/allennlp/issues/1561 for more information.

**Comment by epwalsh** [comment]
I was wondering if it would make sense to gather requirements in the `requirements.txt` file by the "section" that they are in, like "TESTING-RELATED PACKAGES", "LIBRARIES USED IN SCRIPTS", etc., and that way we could ignore certain sections when comparing to the `setup.py` file. 

The only downside I can see is that the section format scheme (ex. "#### SECTION NAME ####") would have to be kept consistent, but I imagine those sections are going to be fairly static, and there could also be another comment in `requirements.txt` that says "Hey, if you make a new section, make sure the section is formatted consistently".

Anyway, I've implemented a check like this before so I'd be willing to make a PR if this is how you want to address it.

**Comment by matt-gardner** [comment]
This sounds reasonable to me, but I'd wait for a bit before starting this, in case someone else pipes in with a dissenting opinion.
