### ISSUE TITLE
allennlp train doesn't play nice with pytorch profiler

### ISSUE THREAD

**Issue by nelson-liu** [allenai/allennlp#1575]
The PyTorch profiler works by running your code twice, once with the python profiler and once with their autograd profiler. however, it breaks the second time around since the `allennlp train` output directory already exists.

It'd be nice to have a `-f / --force` flag that removes the output directory if it exists before retraining...

**Comment by schmmd** [comment]
@nelson-liu can you give a detailed example of how the force flag would help here?

**Comment by nelson-liu** [comment]
So the way the pytorch profiler works is that it runs input python command twice (I think once with a python profiler and one with an autograd profiler). It runs fine the first time, but the second time around, the command fails because the serialization directory already exists.

Does that make sense? I provide a example to reproduce if you want.

**Comment by matt-gardner** [comment]
My main question was about the entry point.  How do you invoke the pytorch profiler?  From the command line?  This matters because how we fix this depends on the entry point.
