### ISSUE TITLE
Feature Request: CNN / Transformer version of ELMo

### ISSUE THREAD

**Issue by tokestermw** [allenai/allennlp#1580]
**Is your feature request related to a problem? Please describe.**
ELMo framework is great, but most (all?) implementations are based on deep LSTM models. Deep LSTM models are slow to train and slow during inference. A faster algorithm with similar accuracy would greatly help so users don't have to use GPUs during inference.

**Describe the solution you'd like**
There is currently [some talk](http://bair.berkeley.edu/blog/2018/08/06/recurrent/) on how RNNs can be replaced by other methods. A simpler architecture like the [temporal convolutional network](https://github.com/locuslab/TCN) can match the performance of RNNs after adding some tricks during training. An ELMo version would simply be a bidirectional TCN.

**Describe alternatives you've considered**
AllenNLP has a CNN encoder and a transformer encoder but as far as I can tell, it's not built for language modeling. There are other packages that implement these specific models but AllenNLP is such a nice framework, I think it would be a great addition.

**Additional context**
Of course this sounds like a paper-sized project 😅. But I wanted to put it out there.

**Comment by schmmd** [comment]
Assigning @joelgrus since he's working on integrating the ELMo training code with AllenNLP (we can close this when that's done).

**Comment by brendan-ai2** [comment]
This work is complete. Sorry for the delay! Please see the documentation at https://github.com/allenai/allennlp/blob/master/tutorials/how_to/training_transformer_elmo.md and let me know if you have any questions!
