### ISSUE TITLE
Why is there not an OntonotesDatasetReader?

### ISSUE THREAD

**Issue by ZhaofengWu** [allenai/allennlp#1590]
I see that there are some Ontonotes-related classes, but why is there not an OntonotesDatasetReader? If I want to read Ontonotes 5, should I subclass my own DatasetReader that perhaps uses the Ontonotes class?

**Comment by nelson-liu** [comment]
Have you see this dataset reader? https://github.com/allenai/allennlp/blob/master/allennlp/data/dataset_readers/coreference_resolution/conll.py 

it reads the ontonotes data (formatted by https://github.com/allenai/allennlp/blob/master/scripts/compile_coref_data.sh) and returns instances suitable for coreference resolution

**Comment by DeNeutoy** [comment]
The Ontonotes class is more general - typically for a particular dataset, you only want some of the annotations. E.g we have 3 readers which use it - the Coreference reader, the SRL reader and the Fine Grained NER reader.

**Comment by tingkai-zhang** [comment]
Hi, the shell script file outputs some errors now.
Please see it here #691 when you have time. Thanks!
