### ISSUE TITLE
allennlp train --include-package fails

### ISSUE THREAD

**Issue by alephic** [allenai/allennlp#1597]
**Describe the bug**
When running a training experiment with python -m allennlp.run train, attempting to include a local package with --include-package causes the command to fail with the following message:
`ValueError: path must be None or list of paths to look for modules in`

**To Reproduce**
Steps to reproduce the behavior
1. Create an experiment (a copy of the tutorial experiment `allennlp/tutorials/getting_started/simple_tagger.json`, for example)
2. Create a local package. For example, the following directory structure:

```
+ my_package/
|- __init__.py
|- foo.py
```
`__init__.py` should contain: `from .foo import x`
`foo.py` should contain: `x = 1`
Note: this is a valid Python module, and can be imported successfully from the repl.
3. Run `python -m allennlp.train simple_tagger.json -s out --include-package my_package`

**Expected behavior**
I expect the training routine to start as normal, and the included package to be included successfully (even though it's not used by simple_tagger.)

**System (please complete the following information):**
 - OS: Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-128-generic x86_64)
 - Python version: 3.7.0
 - AllenNLP version: 0.5.2 ( post #1586 )
 - PyTorch version: 0.4.1

**Comment by joelgrus** [comment]
I tried to follow the steps you listed, but everything worked fine for me. 

Can you show me this morning what goes wrong?

**Comment by joelgrus** [comment]
ok, this appears to only happen on python 3.7. investigating

**Comment by joelgrus** [comment]
seems relevant:

```
pkgutil.walk_packages() now raises a ValueError if path is a string. Previously an empty list was returned. (Contributed by Sanyam Khurana in bpo-24744.)
```
