### ISSUE TITLE
Does allennlp plan to support 0.4.1?

### ISSUE THREAD

**Issue by ZeweiChu** [allenai/allennlp#1605]
```
Could not find a version that satisfies the requirement torch==0.4.0 (from allennlp) (from versions: 0.1.2, 0.1.2.post1, 0.4.1, 0.4.1.post2)
No matching distribution found for torch==0.4.0 (from allennlp)
```

**Comment by nelson-liu** [comment]
Presuming you're on python 3.7: yes, the support is already merged into master (https://github.com/allenai/allennlp/pull/1543) . I think a new release will come out today that should solve your problems.

**Comment by nelson-liu** [comment]
Closing this for now, feel free to reopen if you have further questions.
