### ISSUE TITLE
Usability in AllenNLP

### ISSUE THREAD

**Issue by DeNeutoy** [allenai/allennlp#1610]
Newcomers to allennlp can find it difficult to start off using it. This issue will track some things we can do to improve their experience. Feel free to add bullet points below.

- [x] Running predictions on models is easy, but slightly unintuitive because they are downloaded and cached automatically. In many use cases, you want to download a model directly.
__Solution__(Easy): Add download links to our models in the readme.

- [x] AllenNLP is designed to be used as a binary, but it is sufficiently modular such that using it as a library is very much possible - people just don't know that it is possible.
__Solution__(Hard): 
-- Add a tutorial which demonstrates using a single part of allennlp in combination with a vanilla pytorch model. Examples of this would be using the data code to translate text into tensors, or instantiating a `Trainer` directly within a python script.
-- Demonstrate that you can import and use allennlp modules directly.

- [ ] How you get started with allennlp depends on what you want to do with it - just run models, extend an existing model, or build one from scratch.
__Solution__ (Hard): 
-- We should add different tutorial flows depending on user use cases.

- [ ] Navigating our documentation is difficult because it is overly modular. It's actually easier to have a lot of documentation on a single page, so you can CTRL + F to find what you are looking for.
__Solution__ (Easy): 
-- Remove the top level of nesting in the allennlp docs, to make it more like the pytorch ones: https://pytorch.org/docs/stable/tensors.html

- [x] How you discover resources for allennlp is fragmented - there are tutorials on the website, separate docs, and notebooks in the git repo.
__Solution__ (Easy): 
-- Add links to the tutorials from the docs.
-- Make the docs the canonical place to start off with allennlp
-- Rename the header on allennlp.org from "API" to "Docs"

- [ ] Configuring allennlp models is difficult if you've never done it before, particularly in terms of discovering things you _can_ configure.
__Solution__ (Hard): 
-- Finalise Joel's config builder and add it to the website.

**Comment by DeNeutoy** [comment]
Add a link to CONTRIBUTING.md from the readme and to our pull request/issue template - it's not obvious how to discover that unless we link to it from somewhere clear.

**Comment by schmmd** [comment]
I'll do a pass at organizing what's left.

**Comment by schmmd** [comment]
@DeNeutoy you said you thought we had addressed many of the above--can you check off those that you consider done?

**Comment by schmmd** [comment]
We have:

* Created a central tutorial
* Renamed "API" to "docs"
* Added examples of making predictions programatically.

**Comment by schmmd** [comment]
I think we can also:

- [ ] link out to the docs and the central tutorial from the README.
- [ ] move the "What is AllenNLP?" from the README to the docs.

**Comment by schmmd** [comment]
Closing this out as many of the items are complete.  If we decide we want to do more of them, we can cut new issues with the remaining work.
