### ISSUE TITLE
Question about Elmo dimensions

### ISSUE THREAD

**Issue by silent-vim** [allenai/allennlp#1614]
Hi, this is not an issue in allennlp but a question about elmo. I am trying to understand elmo and trying to see how the three layers are computed. In the paper there is a paragraph that mentions:

> The final model uses L = 2 biLSTM layers with 4096 units and 512 dimension projections
and a residual connection from the first to second layer. The context insensitive type representation uses 2048 character n-gram convolutional filters followed by two highway layers (Srivastava et al., 2015) and a linear projection down to a 512 representation. As a result, the biLM provides three layers of representations for each input token, including those outside the training set due to the purely
character input.

I having a hard time trying to figure out how do we get the output of three layers for each token with 1024 dimensions. Hoping someone can clarify.

**Comment by silent-vim** [comment]
Yes, that makes it clear I was thinking along the same lines :) thanks @DeNeutoy, will close the issue.

**Comment by vermasangam** [comment]
Hi, I have the same doubt on the size of the vectors. The outputs of 2 lstm layers have size 1024(512 forward and 512 backward) but still the first layer of char cnn and highway layers has 512 dimension. How are these two merged ?

**Comment by mkyriakakis** [comment]
> Hi, I have the same doubt on the size of the vectors. The outputs of 2 lstm layers have size 1024(512 forward and 512 backward) but still the first layer of char cnn and highway layers has 512 dimension. How are these two merged ?

They concat twice the first layer of the CNN-derived word embeddings (https://github.com/allenai/bilm-tf/blob/7cffee2b0986be51f5e2a747244836e1047657f4/bilm/model.py#L120) to make the first layer dimension 
equal to 1024 as well.
