### ISSUE TITLE
Feature request: support pulling data from AWS S3 buckets directly (using boto3)

### ISSUE THREAD

**Issue by epwalsh** [allenai/allennlp#1618]
Sometimes we have to pull data files from a private S3 bucket, which requires AWS credentials, so we can't just access it with a simple HTTP GET request. To handle this, we could use `boto3` or the `awscli` to pull s3 files when the file is specified by an s3 path, like `s3://path-to-file`, instead of the http url. At this time it seems that the alternative is to just manually download the files locally first using the `awscli` or `boto3` and then point allennlp to the local copy.

The only downside I can see of supporting this feature is adding an additional dependency (`boto3`).

I'd be willing to submit a PR if this is something you want to support.

**Comment by nelson-liu** [comment]
This would be great! We already have `awscli` in the requirements, so if you decide to use that we can avoid the extra dependency?

**Comment by epwalsh** [comment]
@nelson-liu thanks, I did see that. It would definitely be cleaner to use boto3 though, so that would be my first choice unless anyone is opposed to adding boto3 as a dependency.

**Comment by matt-gardner** [comment]
Are you thinking that this goes inside of `cached_path`?

https://github.com/allenai/allennlp/blob/59132d2be0e871b512c03a08fe80eb41ef7418a9/allennlp/common/file_utils.py#L67-L92

Seems like it could easily just be another case inside there, right?

**Comment by epwalsh** [comment]
@matt-gardner that's exactly what I was thinking, or `get_from_cache` (within `cached_path`) if we want to cache those files in the same way, which I think would make sense.

**Comment by matt-gardner** [comment]
Yeah, fair enough, you just need to add `s3` as an additional URL scheme in the block I quoted, then modify `get_from_cache` to do the right thing.  Sounds great to me.

**Comment by epwalsh** [comment]
I've started on this here: https://github.com/epwalsh/allennlp/blob/ISSUE-1618/allennlp/common/file_utils.py

Let me know if see anything that needs to be changed before I make the PR

**Comment by matt-gardner** [comment]
The basic idea looks ok to me.  I'd recommend just making a PR out of it, and then @joelgrus can take a closer look (he's the one that's most familiar with that code).

**Comment by epwalsh** [comment]
Ok, I was just going to add some more tests and then I'll create the PR
