### ISSUE TITLE
Add a warning when passing `shuffle=False` to bucket and adaptive iterators

### ISSUE THREAD

**Issue by matt-gardner** [allenai/allennlp#162]
These iterators by definition change the order of your data.

**Comment by ibrahimsharaf** [comment]
Hello @matt-gardner, I am interested in working on this, where can I find the iterators?

**Comment by matt-gardner** [comment]
Glad to have some help!  You can find the data iterators [here](https://github.com/allenai/allennlp/tree/master/allennlp/data/iterators).
