### ISSUE TITLE
AllenNLP's data piece could be more pythonic

### ISSUE THREAD

**Issue by DeNeutoy** [allenai/allennlp#1633]
allennlp's data API has become pretty stable and effective. However, it's still a bit unwieldy  to manipulate individual `Fields` and `Instances`. There are a few things we could do to make them easier to use for a newcomer:

#### 1. Manipulating `Fields` in `Instances`. `Instance` could inherit from `MutableMapping`. (so could `MetadataField`, in the same vein.)
```
# Currently:
specific_field = instance.fields["field_name"]

# Ideal:
specific_field = instance["field_name"]
"field_name" in instance
>>> True
```

#### 2. Iterating over `SequenceFields` and `ListFields` using `Field.__iter__`:

```
# Before
fields = instance.fields
tokens = [t.text for t in fields['tokens'].tokens]
assert tokens == ["Mali", "government", "officials", "say", "the", "woman", "'s",
                      "confession", "was", "forced", "."]

# After
token_field = instances["tokens"]
assert token_field == ["Mali", "government", "officials", "say", "the", "woman", "'s",
                      "confession", "was", "forced", "."]
```

#### 3. Representing `Index` and `SpanFields` as their values for equality (`Field.__eq__`):
```
# Before
assert instance.fields["span_start"].sequence_index == 102
assert (instance.fields["span"].span_start, instance.fields["span"].span_end) == (102, 109)

# After
assert instance["span_start"] == 102
assert instance["span"] == (102, 109)
```

**Comment by matt-gardner** [comment]
What's the use case for manipulating individual instances?  Debugging?  Tests?  Something else?

**Comment by DeNeutoy** [comment]
both, I guess - it's low priority, just struck me when I was looking at some of the data tests.

**Comment by joelgrus** [comment]
I am a fan of #1 and #2 (I think I might have even implemented 2 in the documentqa PR or in some other PR that never got merged), #3 is less obviously a good idea to me (but I could possibly be convinced)

**Comment by matt-gardner** [comment]
Some more motivation for actually doing this: https://twitter.com/crcrpar/status/1053303645683408896.

**Comment by joelgrus** [comment]
we assigned this to me because we thought Kathryn might work on it. but she's not, so I can do it, it will be very quick.
