### ISSUE TITLE
Can we combine Attention and MatrixAttention?

### ISSUE THREAD

**Issue by matt-gardner** [allenai/allennlp#1634]
It should be pretty easy to just have a single `Attention` class, instead of parallel `Attention` and `MatrixAttention` classes - just use the code for `MatrixAttention`, and `unsqueeze(1)` and re-`squeeze(1)` if we're given a single vector.  Is there a problem with this I'm not seeing?  I'm not sure why we didn't just do this to begin with...  Maybe because of how Keras shape inference worked...?

**Comment by DeNeutoy** [comment]
Not a big fan of this - seems like they are conceptually different. Broadcasting is nice, but sometimes making it obvious what goes in and out of a module is more important.

**Comment by matt-gardner** [comment]
The trouble is that someone could use `Attention` when they really wanted `MatrixAttention` and not understand why it's not working.  I've seen at least one user have this problem.  But, we can wait on this until we see more people getting confused (and the solution might just be better error messages, anyway).

**Comment by joelgrus** [comment]
we're not convinced this is a good idea
