### ISSUE TITLE
move trainer functionality from `from_params` to constructor, so it's documented

### ISSUE THREAD

**Issue by nelson-liu** [allenai/allennlp#1635]
I just came upon (purely by accident!) this very useful-looking feature that takes regexes with parameter names and sets them to be frozen accordingly.

https://github.com/allenai/allennlp/blob/4df4638b186554c994e7fd841a766e992ee81ba1/allennlp/commands/train.py#L294-L297

However, this feature does not seem to be documented anywhere --- it's not mentioned in the trainer command (which makes sense, because it's part of the config) and it's not mentioned in the `Trainer` class (which makes sense, because it's not being passed into `Trainer` anywhere). 

Not sure what the best way to proceed is, but this seems like something that would be quite useful to many (in fact, @dangitstam was asking me about something exactly like this the other day).

**Comment by matt-gardner** [comment]
This is now in `TrainerPieces.from_params`, and I'm pretty sure there's not a lot we can do about this, except document it somewhere.  @joelgrus, is there any other way of handling this?

**Comment by matt-gardner** [comment]
This is covered by #3389.
