### ISSUE TITLE
Update metrics.json whenever best.th is updated

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp#1645]
Currently your job will output a `metrics.json` at the end of training with statistics from the last epoch.  @bhavanadalvi suggested instead we could output `metrics.json` each time `best.th` is updated.  That way it would have the metrics from the best output rather than the last, and incremental output could be viewed in the Beaker UI if running a Beaker job.

**Comment by schmmd** [comment]
According to @ckarenz, Beaker only processes `metrics.json` when a job completes.

**Comment by ckarenz** [comment]
All result files including `metrics.json` are uploaded every 3 minutes. I've added a tracking issue to process metrics more frequently.

**Comment by bhavanadalvi** [comment]
Wohoooo, thank you both @schmmd and @ckarenz. 
You are awesome 👍

**Comment by DeNeutoy** [comment]
@ckarenz I don't think updating metrics.json more frequently than every 3 minutes is actually required FYI. One thing which would be appealing is if the metrics in the group view would be updated if we dumped metrics.json more regularly - currently allennlp only outputs this file at the end of training, rather than after every training iteration.

**Comment by ckarenz** [comment]
This is also tracked work and requires a new file upload/watcher mechanism, which is in progress.  That work has been delayed due to external obligations, but will be picking up again next week.

**Comment by matt-gardner** [comment]
We got another request for this in #1719.

**Comment by joelgrus** [comment]
I started working on this a couple of weeks ago, let me see if I can pull together a PR

**Comment by ckarenz** [comment]
Update on our schedule: Due to high-priority conflicting obligations, this work is no longer scheduled.  We'll revisit and try to prioritize in Q4.
