### ISSUE TITLE
Rename Model.decode to something else

### ISSUE THREAD

**Issue by matt-gardner** [allenai/allennlp#1652]
`Model.decode` was originally intended to separate some kind of decoding from the training done in `Model.forward`.  However, we realized later that we really needed that decoding to be done inside `Model.forward`, so you could get proper validation metrics, so `Model.decode` now basically only converts integers to strings and otherwise makes the output human-readable.  We should deprecate `Model.decode` and replace it with a better-named method that makes it clear it's only for translating the output to something consumable by a human.

**Comment by matt-gardner** [comment]
I'm wondering what to rename this to.  I went through all of our existing models; there are a couple that actually do some kind of viterbi decoding in `Model.decode()`, but almost all of them just use this to make the output human-readable.  Some candidate names:

- `make_human_readable`
- `prepare_output_for_humans`
- `prepare_output`
- `sanitize_output`
- `convert_back_to_strings`

My preference would probably be with one of the top two.  Any other votes or alternative suggestions?

**Comment by ZhaofengWu** [comment]
The SRL code is still doing Viterbi decoding in the `decode`/`make_output_human_readable` function, and that the `forward` function calls this function. After this change we might want to rework that logic a bit. Certainly a low priority though.

https://github.com/allenai/allennlp/blob/master/allennlp/models/srl_bert.py#L148
