### ISSUE TITLE
Should we make CrfTagger work with all sequence labeling datasets?

### ISSUE THREAD

**Issue by nelson-liu** [allenai/allennlp#1659]
Currently, `CrfTagger` only works with BIO-tagging datasets, since a `SpanF1Metric` is created by default.

It'd be simple to adapt it to work with datasets like CCG tagging / POS tagging, but that might involve adding some more arguments to the model (e.g., an argument for `constrain_crf_decoding` and `calculate_span_f1`).

Do we want to add these arguments, considering that the `CrfTagger` is used in the tutorial (and thus it might make sense to have it be as simple as possible).

**Comment by joelgrus** [comment]
I don't think that tutorial is all that long for this world, don't base any decisions on what's good for it.

**Comment by nelson-liu** [comment]
thanks!
