### ISSUE TITLE
Switching off tokenizer

### ISSUE THREAD

**Issue by pwichmann** [allenai/allennlp#1678]
**Is your feature request related to a problem? Please describe.**
I would like to create an NER ensemble with other NER solutions.
For this, I need to feed in sentence- and word-tokenized sentences myself and I do not want the NER solutions to use their own tokenizers. Otherwise, this will result in inconsistent outputs.

**Describe the solution you'd like**
Is there a way to switch off any Allan NLP internal tokenization? I would just like to feed in a sentence-tokenized string where tokens have been separated by an empty space.

**Describe alternatives you've considered**
[Do not see any]

**Additional context**
[None]

**Comment by matt-gardner** [comment]
I presume you're getting a `Predictor` for the NER model?  If you've got one of those, you can just do:

```python
predictor._tokenizer = JustSpacesWordSplitter()  # only run this line once
json_output = predictor.predict(' '.join(tokens))  # then get your predictions like this for each instance
```

**Comment by pwichmann** [comment]
Thank you!
I ran into this issue. Am I doing this correctly?

![image](https://user-images.githubusercontent.com/13521375/44741021-d315db80-aaf3-11e8-837b-3f69b8573360.png)

**Comment by pwichmann** [comment]
Oh, maybe I misunderstood. You suggested to plug in my own tokenizer for JustSpacesWordSplitter(), correct?
The error message may still say that it must be defined in token_embedders?

**Comment by matt-gardner** [comment]
You're going to have to import that word splitter first.

**Comment by pwichmann** [comment]
![image](https://user-images.githubusercontent.com/13521375/44741756-fe012f00-aaf5-11e8-8630-e7293eee54c8.png)

**Comment by matt-gardner** [comment]
Something is wrong, because your line `predictor._tokenizer = JustSpacesWordSplitter(word_tokenised_sentence_as_string)` should be crashing.  When I run that line, I get `TypeError: object() takes no parameters`.

**Comment by pwichmann** [comment]
When you declare the function ```JustSpacesWordSplitter()```, what exactly do you define it to do?

I thought I would just re-use my own tokenizer and rename it JustSpacesWordSplitter(raw_sentence), so that it outputs the tokenised sentence as a single string.
So I declared it as: ```def JustSpacesWordSplitter(raw_sentence):```

Sorry that I am so slow to understand.

**Comment by matt-gardner** [comment]
`from allennlp.data.tokenizers.word_splitter import JustSpacesWordSplitter`

**Comment by pwichmann** [comment]
THANK YOU!
That was the missing piece in the puzzle that is my brain.

Can I buy you a coffee?

**Comment by matt-gardner** [comment]
Glad you got it working =).  I'm closing this issue now, feel free to re-open it if you have questions.

**Comment by pwichmann** [comment]
@matt-gardner Would there be a way to replace JustSpacesWordSplitter by my own tokenizer? I need to make sure I feed in the identical sentence into all my NERs in the ensemble. And I do not want them to tokenize themselves and add unnecessary differences.

Do I need to rewrite the class JustSpacesWordSplitter for that?

**Comment by matt-gardner** [comment]
I got an email with a question; maybe you deleted your comment.  But the answer to the question is this: if you have an already-tokenized sentence, the easiest thing to do is to just do `' '.join(tokens)`, then pass that in using our `JustSpacesWordSplitter`, which will literally just call `sentence.split(' ')`, undoing the `' '.join(tokens)` and giving you back the original list.  There are other ways you could solve this problem (like by writing your own `WordSplitter`), but this is definitely the easiest.

**Comment by pwichmann** [comment]
Hi @matt-gardner, I deleted my comment because I noticed how dumb I am.

I realised that the simple whitespace-based tokenizer is just what I need since I can feed in the word-tokenization result.

Thank you for you tremendous help!

**Comment by AlJohri** [comment]
I needed to return the output of NER using character indicies in the following format:

```python
{'text': "The rock-star Democrat Beto O'Rourke, a candidate for president, once supported the bulldozing of a low-income neighborhood in his hometown of El Paso-a project spearheaded by his father-in-law.",
 'labels': [(14, 22, 'U-MISC'),
  (23, 27, 'B-PER'),
  (28, 36, 'L-PER'),
  (143, 145, 'B-LOC'),
  (146, 150, 'L-LOC')]}
```

While doing this in spacy was pretty straight forward because they provide `start_char`/`end_char` and allow going over multiple sentences....

```python
import spacy
spacy_nlp = spacy.load("en_core_web_lg")

def ner_spacy(text):
    doc = spacy_nlp(text)
    labels = [(ent.start_char, ent.end_char, ent.label_,) for ent in doc.ents]
    return {"text": text, "labels": labels}
```

....I had a bit of trouble doing this with allennlp:

```python
from allennlp.predictors.predictor import Predictor
from allennlp.data.tokenizers.whitespace_tokenizer import WhitespaceTokenizer
allennlp_models = "https://s3-us-west-2.amazonaws.com/allennlp/models/"
allennlp_ner_model = allennlp_models + "ner-model-2018.12.18.tar.gz"
allennlp_predictor = Predictor.from_path(allennlp_ner_model)
allennlp_predictor._tokenizer = WhitespaceTokenizer()

def ner_allennlp(text):
    doc = spacy_nlp(text)
    labels = []
    index = 0
    sents = list(doc.sents)
    for sent in sents:
        tokens = list(sent)
        # without this check, I run into:
        # RuntimeError: Calculated padded input size per channel: (1). Kernel size: (3). Kernel size can't be greater than actual input size
        if all(x.is_space or x.is_punct for x in tokens):
            index += len(sent.text_with_ws)
        else:
            sent_counter = 0
            obj = allennlp_predictor.predict(sentence=' '.join(str(x) for x in tokens))
            for i, (tag, token) in enumerate(zip(obj["tags"], tokens)):
                if tag != 'O':
                    label = (index, index + len(token), tag)
                    labels.append(label)
                index += len(token.text_with_ws)
                sent_counter += len(token.text_with_ws)
            else:
                # for some reason, the end punctuation of the sentence does not include
                # the newline character in `token.text_with_ws` but the newline is included
                # in the sent.text_with_ws. so we just add the remaining characters to
                # increment the index to the next sentence
                index += (len(sent.text_with_ws) - sent_counter)
    for label in labels:
        
    return {"text": text, "labels": labels}
```

Do you have any ideas on how to make this a little easier?

Basically I want to take a document and NER the entire thing giving me the character indicies in the original document for each entity.
