### ISSUE TITLE
Order of predicted labels from textual-entailment

### ISSUE THREAD

**Issue by dhairyadalal** [allenai/allennlp#1681]
What is order of the labels outputed by the textual entailment model? I assume it is Entailment, Contradiction and Neutral, but wanted to double check that assumption is correct. 

eg
```
'premise_tokens': ['The', 'primary', 'colors', 'are', 'green', ',', 'yellow', 
',', 'and', 'red',.', '@@NULL@@'],
 'hypothesis_tokens': ['Red', 'is', 'a', 'primary', 'color', '.', '@@NULL@@'],
 'label_probs': [0.5689316391944885, 0.17109070718288422, 0.2599776089191437],
```

**Comment by matt-gardner** [comment]
Huh, I just looked through the code and found that we don't have our typical conversion from ints to strings anywhere in the decomposable attention model.  The way to figure out what the labels are is to look at the model's label vocabulary.  I did this for the decomposable attention model with ELMo in our demo, and I got this:

```python
>>> from allennlp.predictors import Predictor
>>> p = Predictor.from_path('https://s3-us-west-2.amazonaws.com/allennlp/models/decomposable-attention-elmo-2018.02.19.tar.gz')
>>> p._model.vocab.get_token_to_index_vocabulary('labels')
{'entailment': 0, 'contradiction': 1, 'neutral': 2}
```

So, yes, you were right.

**Comment by dhairyadalal** [comment]
thanks! closing this issue.
