### ISSUE TITLE
possible masking bug in simple_seq2seq

### ISSUE THREAD

**Issue by rowanz** [allenai/allennlp#1713]
**Describe the bug**
The final hidden states for shorter sequences are set to 0 when using the the simple_seq2seq model, with the configuration at https://github.com/allenai/allennlp/blob/master/allennlp/tests/fixtures/encoder_decoder/simple_seq2seq/experiment_with_attention.json

**To Reproduce**
Steps to reproduce the behavior
1. run the simple_seq2seq model, with a batch where not everything is the same length
2. Right here, https://github.com/allenai/allennlp/blob/f2884ad64dc018bbba9518002a7cb7d15e8ca952/allennlp/models/encoder_decoders/simple_seq2seq.py#L128 the hidden states for short sequences are set to 0

**Expected behavior**
The final_encoder_output needs to be the encoder output at the last valid timestep.

**System (please complete the following information):**
 - OS: Linux
 - Python version: 3.6.6 [if it's not 3.6.1 or later, that's probably your problem]
 - AllenNLP version: 0.6.1
 - PyTorch version: installed with allennlp

**Additional context**
Possibly using a different encoder would fix the problem? or maybe I'm doing something wrong elsewhere

**Comment by matt-gardner** [comment]
Yep, this is a bug.  We've fixed this in models we're actively working on, but we haven't touched this code in a while.  The fix is to use this function instead of the line you quoted: https://github.com/allenai/allennlp/blob/f2884ad64dc018bbba9518002a7cb7d15e8ca952/allennlp/nn/util.py#L121-L123

PRs welcome!

**Comment by brendan-ai2** [comment]
Should be fixed in https://github.com/allenai/allennlp/pull/1808. Please let me know if you still see this issue!
