### ISSUE TITLE
General comments on NER 

### ISSUE THREAD

**Issue by danyaljj** [allenai/allennlp#1720]
Hello there! 

Today I gave a try to your NER and I am summarizing a few hiccups I had during the process. 

- Looked up the training script from [this tutorial](https://github.com/allenai/allennlp/blob/master/tutorials/getting_started/creating_a_model.md#putting-it-all-together) and was confused about what "crf_tagger.json" is since it is not mentioned anywhere in the document (There are mentions of "crf_tagger", but it's not clear how they are related to the content of "crf_tagger.json"). 

 - Would also be useful to mention that the train/test/dev paths have to be specified within the config file. 

- In addition to the file mentioned in the tutorial (`/Users/daniel/ideaProjects/allennlp/tutorials/getting_started/crf_tagger.json`), I found another config file which seems to be for NER (`/Users/daniel/ideaProjects/allennlp/training_config/ner.jsonnet`). One has details about ELMo and the other one doesn't (and a few other differences as well). 

- Data format was another issue: the document explains that data format has to be of this form: 
```
   U.N.         NNP  I-NP  I-ORG
   official     NN   I-NP  O
```
While column-format is pretty popular, it has many variations (e.g. [this](https://raw.githubusercontent.com/GateNLP/broad_twitter_corpus/master/h.conll)). Having a refence to the reader, so that people know where to change it, in case they have a slightly different format would be nice.

**Comment by somnathrakshit** [comment]
It would be so much easier if the data format is received in JSON instead  of the current format.

**Comment by matt-gardner** [comment]
@somnathrakshit, if you want to train a model with JSON-formatted input, it's pretty easy to write your own `DatasetReader` to do that.  If you want to make predictions on JSON-formatted input, [you can do that already](https://github.com/allenai/allennlp/blob/master/tutorials/getting_started/using_pretrained_models.md#making-predictions-on-the-command-line).

**Comment by somnathrakshit** [comment]
Thank you.

**Comment by matt-gardner** [comment]
@danyaljj, we're revamping our tutorials at the moment and should have a nice shiny new one that's based on a tagger very soon.  Hopefully that'll address some of these issues.

**Comment by Andy-jqa** [comment]
Hi @matt-gardner, is the new NER tutorial ready now?

**Comment by matt-gardner** [comment]
It's a POS tagger, not an NER tagger, but that's just changing the data: https://allennlp.org/tutorials.
