### ISSUE TITLE
Support for regression?

### ISSUE THREAD

**Issue by bwriordan** [allenai/allennlp#1730]
**Is your feature request related to a problem? Please describe.**
How can AllenNLP be used for regression problems?

**Describe the solution you'd like**
If regression is currently supported, an example. If not, a Field, etc. to support it.

**Describe alternatives you've considered**
I saw metrics such as Pearson correlation recently added to the metrics API, but I did not see a specific Field for regression problems. I've tried creating a DatasetReader that uses "LabelField(x, skip_indexing=True)" and a model that converts labels to float tensors and computes loss using MSE, and this seems to work so far.

**Comment by nelson-liu** [comment]
Hi! I used used the `ArrayField` as the field to store the real valued label. If you're doing something like sequence labeling, but predicting a real value for each token, i built a `SequenceArrayField` that I haven't merged back up to the allennlp repo yet. It's pretty simple, just:

```python
from allennlp.data.fields import ArrayField, SequenceField
import numpy
from overrides import overrides


class SequenceArrayField(ArrayField, SequenceField):
    """
    A class representing an array with sequential semantics. The input sequence_dim
    represents the length of the sequence. The array could have arbitrary
    dimensions. A batch of these arrays are padded to the max dimension length in the
    batch for each dimension.
    """
    def __init__(self,
                 array: numpy.ndarray,
                 padding_value: int = 0,
                 sequence_dim: int = 0) -> None:
        self.array = array
        self.padding_value = padding_value
        self.sequence_dim = sequence_dim

    @overrides
    def sequence_length(self) -> int:
        return self.array.shape[self.sequence_dim]

```

Hope that helps!

**Comment by schmmd** [comment]
@bwriordan I think @nelson-liu answered your question.  Feel free to re-open if that's not the case!

**Comment by bwriordan** [comment]
Yes thanks!
