### ISSUE TITLE
Provide method to retrieve questions from MC model

### ISSUE THREAD

**Issue by radiantone** [allenai/allennlp#1736]
In the MC demo you ask a question of some text and get an answer. Is there a way to "get the questions" it can answer? If not, it would be super useful to provide a method for this.

**Comment by matt-gardner** [comment]
There are a bunch of academic papers that try to generate questions giving a paragraph.  If you're interested in this, search for ["question generation SQuAD" on an academic search engine](https://www.semanticscholar.org/search?q=question%20generation%20SQuAD&sort=relevance), or look at [this paper](https://www.semanticscholar.org/paper/Large-Scale-QA-SRL-Parsing-FitzGerald-Michael/7b199756fee917accf5e9223c3282239ee2fbc89), which is a little different but related.

We don't have any of these models implemented in AllenNLP, though, and we don't have any plans to add them (though if someone has or wants to implement a version in AllenNLP, we'd be happy to feature it).
