### ISSUE TITLE
EVALB scorer does not compile

### ISSUE THREAD

**Issue by zplizzi** [allenai/allennlp#1746]
I am trying to evaluate the constituency parser by running 
```
allennlp evaluate \
https://s3-us-west-2.amazonaws.com/allennlp/models/elmo-constituency-parser-2018.03.14.tar.gz \
/home/zplizzi/nltk_data/corpora/treebank/combined/wsj_0001.mrg
```

 I receive the error:

```python 
allennlp.common.checks.ConfigurationError: "You must compile the EVALB scorer before using it. Run 'make' in the 'scripts/EVALB/evalb' directory or run: python -c 'from allennlp.training.metrics import EvalbBracketingScorer; EvalbBracketingScorer.compile_evalb()'"
``` 

So, I run the command `python -c 'from allennlp.training.metrics import EvalbBracketingScorer; EvalbBracketingScorer.compile_evalb()'` as specified. This returns various gcc warnings, but otherwise seems to run fine. However, when I try run the evaluation again, I still get the same "you must compile the EVALB scorer" error.

**System (please complete the following information):**
 - OS: Ubuntu 16.04
 - Python version: 3.6.4
 - AllenNLP version: v0.6.1
 - PyTorch version: 0.4.1

**Comment by zplizzi** [comment]
I figured out the problem. In the model archive, the config file contains this setting: `"evalb_directory_path": "scripts/EVALB"`. This makes the code look for the compiled program in a different directory than the one it's actually compiled in.

I haven't figured out how to fix this - can't quite seem to figure out how the "override" option works in the evaluate script.

**Comment by zplizzi** [comment]
I've "solved" this by just copying the `EVALB` folder into `scripts/EVALB` my current working directory. This is definitely not obvious though, without digging into the archive and code. Perhaps there could be a bit of documentation of this behavior.

**Comment by DeNeutoy** [comment]
Hmm this is annoying I agree.

I think this happened because we moved some required tools like EVALB to `tools/` which get distributed with the pip package. If you remove the evalb_directory_path parameter in the config file, does it work? [The default value](https://github.com/allenai/allennlp/blob/master/allennlp/training/metrics/evalb_bracketing_scorer.py#L14) here should just work now, but the issue is the model archive was created before this existed. If this fixes the issue, I can just modify the constituency parser we distribute to not contain this.

**Comment by zplizzi** [comment]
Yep, if I remove that line from the config file and re-zip everything up, it works fine even without the binary in my working directory. Thanks!

**Comment by schmmd** [comment]
@zplizzi if you're up for it, we would welcome a pull request!

**Comment by matt-gardner** [comment]
@schmmd, I don't think a pull request is necessary here, or will fix the issue.  The issue is with the model that we're hosting on s3.

**Comment by schmmd** [comment]
Ah, I see, sorry.  It sounds like Mark is on this, so I'll assign him.

**Comment by schmmd** [comment]
@DeNeutoy is this still an issue?  I vaguely remember you fixing the model on S3.
