### ISSUE TITLE
allennlp-0.6 is inconsistent with previous versions(0.5 or before)

### ISSUE THREAD

**Issue by robbine** [allenai/allennlp#1747]
I noticed that there are major changes in model.py. The following line is used to instantiate an instance:
`cls.by_name(model_type)._load(config, serialization_dir, weights_file, cuda_device)` 
and unlike previous versions, bidaf model does NOT have a from_params method. It confuses me how to create a model from params specified in a json file. Is there a doc of instruction ?

**Comment by DeNeutoy** [comment]
Hello! Please read the release notes which you can find here:

https://github.com/allenai/allennlp/releases/tag/v0.6.0

`from_params` is now automatically implemented for you thanks to some very clever code from @joelgrus which uses reflection and python 3.6 type hints to infer the types of parameters.

To construct a parameter file from a config, you can look at the types in the constructor. Also, soon we will have an interactive configuration explorer/builder, which will help you to create configuration files.
