### ISSUE TITLE
Add a CI check that fails when large files are added to the repo

### ISSUE THREAD

**Issue by matt-gardner** [allenai/allennlp#1753]
It's probably easiest to just check the sizes of all files in the repo, and white list the ones that are already there and known to be large.  I'd recommend a maximum size of 2MB at the most, preferably 1MB.  We only have three files greater than 1MB right now, and if there's a real need for more, we can add those files to the whitelist.

**Comment by epwalsh** [comment]
How about just adding another verify script like this:

```
# Get the current branch.
branch=$(git branch | grep \* | cut -d ' ' -f2)

# Get all newly added files (compared to master branch) and find the size
git diff --diff-filter=A --name-status master.."$branch" | sed -e 's/A[[:space:]]//' | xargs stat --print="%s\n"

# Check to see if any sizes are greater than 2MB or something
...
```

This would find all files in the current branch that are not in the master branch and then check their size.
