### ISSUE TITLE
LinearMatrixAttention: incorrect result tensor when batch size is equal to 1

### ISSUE THREAD

**Issue by aleSuglia** [allenai/allennlp#1758]
**Describe the bug**
Given a tensor t1 whose size is (1, seq_len_1, encoding_dim) and another tensor t2 whose size is (1, seq_len_2, encoding_dim), if you apply `LinearMatrixAttention` with a combination of "x,y,x*y" you will get a tensor of size (seq_len_1, seq_len_1, encoding_dim).   

**To Reproduce**
```
import torch
from allennlp.modules.matrix_attention import LinearMatrixAttention

t1 = torch.randn(1, 329, 40)
t2 = torch.randn(1, 13, 40)

mat_att = LinearMatrixAttention(40, 40, combination="x,y,x*y")
attentions = mat_att(t1, t2)

attentions.size()
Out[9]: torch.Size([329, 329, 13])
```

**Expected behavior**
The result that I was expecting from `mat_att(t1, t2)` is a tensor of size (batch_size, seq_len_1, seq_len_2). In the previous example the expected tensor should have size (1, 329, 13).

**System (please complete the following information):**
 - OS: OSX
 - Python version: Python 3.6.6 (Anaconda) 
 - AllenNLP version: v0.6.1
 - PyTorch version: installed with AllenNLP

**Additional context**
Apparently seems an edge case when the batch size is equal to 1 because I don't have this problem when the first dimension of the tensor is different from 1.

```
a1 = torch.randn(5, 329, 40)

a2 = torch.randn(5, 13, 40)

attentions = mat_att(a1, a2)

attentions.size()
Out[16]: torch.Size([5, 329, 13])
```

**Comment by matt-gardner** [comment]
Thanks for finding this, and for the test case.  I thought I handled these cases, but it looks like I missed something.  I'll look into fixing it, but it won't be today.

**Comment by aleSuglia** [comment]
I was debugging the code I think I found the problem. Basically at this [line](https://github.com/allenai/allennlp/blob/master/allennlp/nn/util.py#L821) you're looking for the expanded dimensions in the current tensor assuming that there is always just one dimension equal to one. I guess that an easy fix would be to use `rindex()` instead of `index` in this case. 

What do you think?
