### ISSUE TITLE
Customize location of .allennlp directory

### ISSUE THREAD

**Issue by nelson-liu** [allenai/allennlp#1773]
Currently, the `.allennlp` directory is at `~/.allennlp`. It's fairly common to have machines where `~` is on rather small but speedy SSD, and a larger HDD is used to store serialized models and data.

It'd be great to be able to customize where `.allennlp` lives, perhaps by using a `.allennlprc` config file in the home directory.

**Comment by joelgrus** [comment]
this can already be changed with an environment variable:

https://github.com/allenai/allennlp/blob/master/allennlp/common/file_utils.py#L24
