### ISSUE TITLE
LinearMatrixAttention work wrong for batch_size 1

### ISSUE THREAD

**Issue by YeDeming** [allenai/allennlp#1775]
input tensor1[1,9,10] and tensor2[1,537,10] to LinearMatrixAttention.forward and I get the output of tensor3[537, 537, 9] rather than [1, 537, 9]

 - OS: ,Linux
 - Python version: 3.7
 - AllenNLP version: "I installed from master"

**Comment by nelson-liu** [comment]
Can you confirm you installed from the latest master? This seems like it was already reported and fixed (see https://github.com/allenai/allennlp/issues/1758)

**Comment by YeDeming** [comment]
Thank you for your help, I have solved the problem by updating the code from latest master.
