### ISSUE TITLE
Answer is coming as '(list)\n' in wikitables_parser

### ISSUE THREAD

**Issue by shwetamandhare** [allenai/allennlp#1778]
For wikitables_parser_test.py
I am getting answer part as "list" without any answer data like this 'answer': '(list)\n'

A sample output is given below
{
      'predicted_action': 'c -> fb:cell.16',
      'considered_actions': [
        'c -> [<#1,#1>, c]',
        'c -> [<#1,<#1,#1>>, c, c]',
        'c -> [<d,c>, d]',
        'c -> [<n,<n,<#1,<<#2,#1>,#1>>>>, n, n, c, <d,c>]',
        'c -> [<n,<n,<#1,<<#2,#1>,#1>>>>, n, n, c, <n,c>]',
        'c -> [<n,c>, n]',
        'c -> [<p,c>, p]',
        'c -> [<r,c>, r]',
        'c -> fb:cell.16',
        'c -> fb:cell.18',
        'c -> fb:cell.kaladin',
        'c -> fb:cell.null',
        'c -> fb:cell.shallan'
      ],
      'action_probabilities': [
        0.003097556997090578,
        0.0031206069979816675,
        0.002594147576019168,
        0.0028065156657248735,
        0.0029449809808284044,
        0.0030725516844540834,
        0.0026774213183671236,
        0.0028159862849861383,
        0.00870579108595848,
        0.007885711267590523,
        0.006329286843538284,
        0.0027119959704577923,
        0.0062453909777104855
      ],
      'question_attention': [
        0.16132430732250214,
        0.16569320857524872,
        0.16764183342456818,
        0.16842283308506012,
        0.16858485341072083,
        0.16833297908306122
      ]
    }
  ],
  'answer': '(list)\n'
}

**Comment by matt-gardner** [comment]
Yes, I've also noticed that something broke with our executor, and I'll be looking into fixing this in the next day or two.  Thanks for reporting!

**Comment by schmmd** [comment]
@matt-gardner I'm pretty sure this is fixed--closing.

**Comment by matt-gardner** [comment]
@shwetamandhare, sorry I missed this earlier.  The things in `tests` are _unit tests_, you should not expect them to produce any meaningful output.  The models they use are not trained, and so don't work as you might hope.  The tests just make sure the code does what we expect.
