### ISSUE TITLE
Performance on DialogQA for QuAC

### ISSUE THREAD

**Issue by YeDeming** [allenai/allennlp#1780]
Thanks for your releasing the code of DialogQA for QuAC.

When I used the default json file "dialog_qa.json"(only modify batch size) to train a QuAC model, I finally got:

Metrics: {
  "training_duration": "02:44:41",
  "training_start_epoch": 0,
  "training_epochs": 30,
  "training_start_acc": 0.43264168102623013,
  "training_end_acc": 0.42932701512540683,
  "training_span_acc": 0.3552229476316155,
  "training_yesno": 0.7985712234348076,
  "training_followup": 0.6152354968408961,
  "training_f1": 52.22180067177267,
  "training_loss": 5.445824457979136,
  "validation_start_acc": 0.3417187924938809,
  "validation_end_acc": 0.32880065270601033,
  "validation_span_acc": 0.27255912273748184,
  "validation_yesno": 0.8614359532227359,
  "validation_followup": 0.6120478651074245,
  "validation_f1": 57.815079059016725,
  "validation_loss": 6.899989672049791,
  "best_validation_start_acc": 0.34770193092194723,
  "best_validation_end_acc": 0.3315202610824041,
  "best_validation_span_acc": 0.2759075907590759,
  "best_validation_yesno": 0.8606200707098178,
  "best_validation_followup": 0.6135436497144411,
  "best_validation_f1": 58.25257114854039,
  "best_validation_loss": 6.765324111470205,
  "best_epoch": 22
}

the validation_f1 is 58.25 which is smaller than 60.6 reported in the paper. The only difference is that I use batch size of 6 rather 10, beacause I found model with batch size of 6 already cost about 10G memory on 1080Ti.

How can I make up the gap?

 - OS: Linux
 - Python version: 3.7
 - AllenNLP version: v0.6.1

Thanks for your time.

**Comment by matt-gardner** [comment]
A smaller batch size could very easily make that small difference in performance, as could simple training variance.  I'm not sure that difference is solvable.  @eunsol?

**Comment by eunsol** [comment]
Hi! That's not a problem, it's because this is unfiltered F1 (performance based on *all* the questions in the development set, not just those with high human agreement). For details -- see the paper (table 4, unfiltered F1 was 58.3). If you use the official eval script (available on quac.ai), you will get around 60.

**Comment by YeDeming** [comment]
Oh, I got the point.  Thanks for your help!
