### ISSUE TITLE
Minio object storage integration

### ISSUE THREAD

**Issue by hackintoshrao** [allenai/allennlp#1781]
Object storage systems are becoming the defacto for storing data for training and testing. The training models too are generally served from object storage systems. 

But object storage services like Amazon S3 may pose cost and performance bottlenecks. 
Having to fetch data over internet during training and throttling pose bandwidth restriction for high performance requirements during training. Getting a Deep learning model right need tens of iterations and being charged for the bandwidth training on large datasets would incur significant costs. 

**Solution**:
[Minio](https://minio.io) is an light weight, simple to use, high performance and open source alternative to Amazon S3. It adheres to S3 protocol too. Minio can seamlessly run in the same computing network used for training. Its a self hosted solution and the high throughput requirements for training on a large dataset can be achieved along with cost optimization (Minio on private cloud is the best and cheapest option for running high performance, reliable object storage). 
Open source projects like [Kubeflow](https://www.kubeflow.org/), which are meant for solving the computing challenge of deep learning training and serving have tight integration with Minio. Meanwhile the users can continue have the option for have their data on S3. This integration will also help us add Allen NLP into Kubeflow. 

Philosophically, With Allen NLP trying to democratize the advance research in NLP it makes sense have a open source object storage integration.

**Comment by schmmd** [comment]
@hackintoshrao thanks for bringing this up, but we're pretty happy with using S3/GCR directly for now.  We have not seen that downloading from these locations has incurred a significant cost.  Users can also change URLs to point to any HTTP location.
