### ISSUE TITLE
How to use focal loss in allennlp

### ISSUE THREAD

**Issue by robbine** [allenai/allennlp#1794]
I found this focal loss implementation https://github.com/marvis/pytorch-yolo2/blob/master/FocalLoss.py. And I want to try it in reading comprehension.
But It seems sequential length is NOT fixed for each batch computation, which means I need to instantiate a focal loss for each batch. Is it right ? Furthermore I found that some paper propose to use reinforcement loss too. Does allennlp have plan to try it in reading comprehension ?

**Comment by matt-gardner** [comment]
You wouldn't need to instantiate that class separately for each batch.  But it expects `(batch_size, num_classes)` inputs, where for reading comprehension you'd need `(batch_size, sequence_length, num_classes)` inputs, so you'd need to modify things a bit to get it to work, and to get it to respect a mask on the sequence length.

The loss itself doesn't seem very hard to implement - it's just another weighting on the standard log loss.  But, no, we don't have any plans to implement this.  If you get it working, PRs welcome!

**Comment by robbine** [comment]
I tried to combine two losses together. The f1 score reached as high as 0.88, but em is only 0.76, which is very low. I wonder if there are some rule-based methods based on prior knowledge to boost em score. Any suggestions?

> start_acc: 0.7904, end_acc: 0.8319, span_acc: 0.7058, em: 0.7621, f1: 0.8817, loss: 1.1875 ||:  35%|###4      | 756/2190 [04:06<06:42,  3.57it/s]
