### ISSUE TITLE
Multi-head self attention

### ISSUE THREAD

**Issue by robbine** [allenai/allennlp#1796]
I found another attention called multi-head (self-) attention which does not exists in allennlp modules.
However it does have multi-head similarity function. To my knowledge, it seems multi-head (self-) attention can be composed by existing modules in allennlp. Or maybe we can add a new attention module? self-attention is widely used in many nlp tasks.
So any suggestions ? Thanks !

**Comment by DeNeutoy** [comment]
I think you are looking for `[StackedSelfAttention](https://github.com/allenai/allennlp/blob/master/allennlp/modules/seq2seq_encoders/stacked_self_attention.py)`. Hope that helps!
