### ISSUE TITLE
Is it possible to save LSTM hidden state between batches?

### ISSUE THREAD

**Issue by zplizzi** [allenai/allennlp#1804]
I'm trying to train a language model using the AllenNLP framework (ie defining an experiment via JSON config, running with `allennlp train`). It is sometimes typical to save the hidden state of the LSTM from batch to batch, so the next batch can start where the previous batch left off. In theory this allows the model to learn longer-term relationships in the text. See [this pytorch example](https://github.com/pytorch/examples/tree/master/word_language_model) as an example.

Is this supported currently? I took a look through the `train` command and `Trainer` class, plus the `Seq2Seq` encoders, but didn't see anything that looked like it.

**Comment by DeNeutoy** [comment]
[The PytorchSeq2SeqWrapper](https://github.com/allenai/allennlp/blob/master/allennlp/modules/seq2seq_encoders/pytorch_seq2seq_wrapper.py#L70) also accepts a hidden state argument - you can extract the hidden state using [this function](https://github.com/allenai/allennlp/blob/master/allennlp/nn/util.py#L157) and cache it as it does in that pytorch script. I think that should work? Sorry it's a bit convoluted...

**Comment by zplizzi** [comment]
Cool, thanks!

**Comment by qiuwei** [comment]
@zplizzi did you manage to get this to work?
It seems to require quite a few changes in the trainer, right?

**Comment by zplizzi** [comment]
@qiuwei I don't think I ever got around to trying it.

**Comment by qiuwei** [comment]
@zplizzi  I figured out that allennlp might have already support for this.
The LSTM wrapped in allennlp have stateful model, which saves the hidden state at the end of the batch and passes it on.
