### ISSUE TITLE
release the configuration wizard

### ISSUE THREAD

**Issue by joelgrus** [allenai/allennlp#1805]
**Motivation**

Learning the configuration language is a barrier to adopting AllenNLP, and we've received user feedback requesting more documentation around our configuration language.

**Success Criteria**

The beta configuration wizard provides a lot of the assistance people are looking for and could help people configure their experiments. To "release" it we probably need to

* add a command for it (we could probably just replace `allennlp configure`, I don't think anyone uses that)
* fix the remaining edge cases (e.g. Unions, Tuples, I think)
* make sure it still works after all the `FromParams` changes
* make a short video (?) showing how to use it

**Comment by schmmd** [comment]
See https://github.com/allenai/allennlp/issues/1442

**Comment by schmmd** [comment]
Released in https://github.com/allenai/allennlp/releases/tag/v0.7.2.
