### ISSUE TITLE
Logical Forms are generated inappropriately

### ISSUE THREAD

**Issue by shwetamandhare** [allenai/allennlp#1807]
In wikitables_parser_test.py   testcase file for test_uses_named_inputs function, the question entered is extract names from the table. 

The logical form generated is as follow : 
**'logical_form': '((reverse fb:cell.cell.part) fb:cell.matt)',**

But the logical form is not retrieving all the names from the tables. Just the first name i.e. fb.cell.matt.
The logical form generated is incomplete

**Comment by matt-gardner** [comment]
That test is simply making sure the `Predictor` class functions as expected.  It's using a toy, untrained model as its backend, and it's not expected that it will produce any reasonable output.  It's a unit test that makes sure the `Predictor` can talk to a `Model` correctly.
