### ISSUE TITLE
How does ELMo handle padding?

### ISSUE THREAD

**Issue by vliu15** [allenai/allennlp#1810]
When I am embedding batches of sentences (of different length), I introduce `<PAD>` tokens, which I include in the vocabulary file during preprocessing. I'm wondering how ELMo handles special tokens like a `<PAD>` token, and how its placement before and after the `</S>` token affects performance.

**Comment by matt-peters** [comment]
The allennlp code will automatically handle padding when converting your text to ids, e.g. in `allennlp.modules.elmo.batch_to_ids`, so you don't have worry about adding padding tokens.  Internally it accomplishes this by setting all of the character ids to the masking id 0.  Adding special tokens like `<PAD>` to your input will cause ELMo to treat it just like any other token and have an unknown but likely undesired impact.

**Comment by scofield7419** [comment]
@matt-peters Hi, as far as I know that the `<s>` token in vocab.txt has its id: 0.
But this id causes collision with the `masking` id 0.

The reason I reckon the id of `<s>` token as 0 is the source code [bilm-tf](https://github.com/Rokid/ELMo-chinese/blob/master/bilm/data.py#31), and the real-world vocab.txt file:
![1](https://user-images.githubusercontent.com/18722770/66057035-9d4eec00-e56a-11e9-958c-ff7fa43b62a1.png)

Could you please explain my puzzle?
Wait for your prompt reply.
