### ISSUE TITLE
How to use ELMo for training in reading comprehension

### ISSUE THREAD

**Issue by robbine** [allenai/allennlp#1823]
I tried to introduce ELMo in reading comprehension. But a divide-by-zero error occurs. Here is my configuration. Basicly I followed those 3 steps in the ELMo tutorial.
> 
      "elmo": { 
        "type": "elmo_characters"
      },
> 
      "elmo": {
        "type": "elmo_token_embedder",
        "options_file": "https://s3-us-west-2.amazonaws.com/allennlp/models/elmo/2x4096_512_2048cnn_2xhighway/elmo_2x4096_512_2048cnn_2xhighway_options.json",
        "weight_file": "https://s3-us-west-2.amazonaws.com/allennlp/models/elmo/2x4096_512_2048cnn_2xhighway/elmo_2x4096_512_2048cnn_2xhighway_weights.hdf5",
        "do_layer_norm": false,
        "dropout": 0.5
      },

> 
    "elmo_layer": {
      "type": "alternating_highway_lstm_cuda",
      "input_size": 1224,
      "hidden_size": 200,
      "num_layers": 4,
      "recurrent_dropout_probability": 0.1
    },`

I replace "phrase_layer" and "highway_layer" with "elmo_layer" in the following code:

                 # embedded_question = self._highway_layer(self._text_field_embedder(question))
		# embedded_passage = self._highway_layer(self._text_field_embedder(passage))
		embedded_question = self._text_field_embedder(question).long()
		embedded_passage = self._text_field_embedder(passage).long()
		batch_size = embedded_question.size(0)
		passage_length = embedded_passage.size(1)
		question_mask = util.get_text_field_mask(question).float()
		passage_mask = util.get_text_field_mask(passage).float()
		question_lstm_mask = question_mask if self._mask_lstms else None
		passage_lstm_mask = passage_mask if self._mask_lstms else None
		# encoded_question = self._dropout(self._phrase_layer(embedded_question, question_lstm_mask))
		# encoded_passage = self._dropout(self._phrase_layer(embedded_passage, passage_lstm_mask))
		encoded_question = self._dropout(self._elmo_layer(embedded_question, question_lstm_mask))
		encoded_passage = self._dropout(self._elmo_layer(embedded_passage, passage_lstm_mask))

**Comment by robbine** [comment]
A full stack trace looks like this:
    encoded_question = self._dropout(self._elmo_layer(embedded_question, question_lstm_mask))
  File "/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line477, in __call__
    result = self.forward(*input, **kwargs)
  File "py36/lib/python3.6/site-packages/allennlp/modules/seq2seq_encoders/pytorch_seq2seq_wrapper.py", line 83, in forward
    self.sort_and_run_forward(self._module, inputs, mask, hidden_state)
  File "/py36/lib/python3.6/site-packages/allennlp/modules/encoder_base.py", line 116, in sort_and_run_forward
    module_output, final_states = module(packed_sequence_input, initial_states)
  File "/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line477, in __call__
    result = self.forward(*input, **kwargs)
  File "/py36/lib/python3.6/site-packages/allennlp/modules/alternating_highway_lstm.py", line 242, in forward
    .div_((1 - self.recurrent_dropout_probability))

**Comment by robbine** [comment]
Updates:
I tried to explicitly initialize a elmo_layer by 
`_Seq2SeqWrapper(AlternatingHighwayLSTM)(input_size=1224, hidden_size=200)`
The mysterious divide-by-zero error disappeared. But another type error occurs:

>   File "/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line477, in __call__
    result = self.forward(*input, **kwargs)
  File "/py36/lib/python3.6/site-packages/allennlp/modules/alternating_highway_lstm.py", line 252, in forward
    memory_accumulator, dropout_weights, lengths_variable, gates)
  File "/py36/lib/python3.6/site-packages/allennlp/modules/alternating_highway_lstm.py", line 50, in forward
    is_training)
  File "/py36/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 202, in safe_call
    result = torch._C._safe_call(*args, **kwargs)
TypeError: initializer for ctype 'struct THCudaTensor *' must be a pointer to same type, not cdata 'struct THCudaLongTensor *'

Is there any sample code I can follow ?

**Comment by robbine** [comment]
I've looked into previous issues related to ELMo and found that _highway_lstm_layer.so needs to be rebuilt in order to use "alternating_lstm_cuda". So I installed a cuda-9.0 and run make.sh to build it.
However it does not solve my problem. I use pytorch-cu80 but cuda-8.0 can not build _highway_lstm_layer.so due to a undefined symbol problem. Does anyone ever succeeded in using elmo representation with allennlp before ?

**Comment by DeNeutoy** [comment]
This is not a problem with elmo, it is a problem with the `alternating_highway_lstm_cuda`, which doesn't currently work with this version of allennlp. Sorry about that!

**Comment by DeNeutoy** [comment]
If you use any other LSTM it should work fine

**Comment by robbine** [comment]
I replaced alternating_highway_lstm_cuda with alternating_lstm, This is my config json. 
>   "model": {
    "type": "bidaf",
    "text_field_embedder": {
      "tokens": {
        "type": "embedding",
        "pretrained_file": "https://s3-us-west-2.amazonaws.com/allennlp/datasets/glove/glove.6B.100d.txt.gz",
        "embedding_dim": 100,
        "trainable": false
      },
      "elmo": {
        "type": "elmo_token_embedder",
        "options_file": "https://s3-us-west-2.amazonaws.com/allennlp/models/elmo/2x1024_128_2048cnn_1xhighway/elmo_2x1024_128_2048cnn_1xhighway_options.json",
        "weight_file": "https://s3-us-west-2.amazonaws.com/allennlp/models/elmo/2x1024_128_2048cnn_1xhighway/elmo_2x1024_128_2048cnn_1xhighway_weights.hdf5",
        "do_layer_norm": false,
        "dropout": 0.5
      },
      "token_characters": {
        "type": "character_encoding",
        "embedding": {
          "num_embeddings": 262,
          "embedding_dim": 16
        },
        "encoder": {
          "type": "cnn",
          "embedding_dim": 16,
          "num_filters": 100,
          "ngram_filter_sizes": [5]
        },
        "dropout": 0.2
      }
    },
    "phrase_layer": {
      "type": "alternating_lstm",
      "input_size": 456,
      "hidden_size": 200,
      "num_layers": 4,
      "recurrent_dropout_probability": 0.1,
      "use_highway": true
    },
    "num_highway_layers": 2,

It seems normal except that the training speed on my macbook is quite slow, even though I use a small elmo weigth file.

> 

> start_acc: 0.0083, end_acc: 0.0100, span_acc: 0.0017, em: 0.0017, f1: 0.0478, loss: 10.1236 ||:   1%|          | 15/2190 [18:34<44:53:11, 74.29s/it]

**Comment by robbine** [comment]
Update:
I tried to run in a container which has one cuda device, and batch_size is set to 5. The training process broke without a prompt. I doubt that memory limit exceeded. Here is where the program interrupted 

> 2018-09-28 11:23:14,930 - INFO - allennlp.training.trainer - Training
  0%|                                                                                       | 0/17520 [00:00<?, ?it/s]/py36/bin/allennlp: line 2:   944 Killed                  python -m allennlp.run "$@"

It seems elmo need to consume a lot of memory in order to work

**Comment by DeNeutoy** [comment]
Yes that is because you are running out of memory on the GPU. The elmo piece is added inside of the text-field embedder, so you don't actually need to modify any code to make it run. However, it will still be slow.

**Comment by matt-peters** [comment]
I suspect this is an OOM on the CPU -- usually GPU OOM displays a stack trace.  allennlp by default loads the entire indexed dataset into CPU memory and for larger datasets will require 10's of GB or more.  Try increasing the amount of allocated CPU memory to your container.

**Comment by robbine** [comment]
Yes, switching to lazy mode do solve my problem. Training speed is around 1 iter per second which is acceptable too. Thanks !
