### ISSUE TITLE
Add whitespace formatting to WikiTables logical form output

### ISSUE THREAD

**Issue by aaronsarnat** [allenai/allennlp#1828]
![image](https://user-images.githubusercontent.com/8367927/46112845-e96d9080-c1a0-11e8-9a34-c5593913697a.png)

**Problem:**

Logical form output in the demo is difficult to read as-is, so it would be nice to incorporate some kind of newline/indentation formatting.

The original plan was to handle this on the front-end of [`allennlp-demo`](https://github.com/allenai/allennlp-demo), but as of this writing, there do not appear to be any language-specific code string whitespace formatting libraries for react. Thus, it was concluded that code formatting should be handled in Python, and code strings should be served pre-formatted in the data requested by the demo app.

**Languages that need to be supported:**

1. LISP
2. SQL
3. Java

---

For context, this issue is based on a PR discussion about logical form presentation on the WikiTables / semantic parsing demo:

In https://github.com/allenai/allennlp-demo/pull/77#issuecomment-424581191 @matt-gardner suggests that any formatting we do:

> ...should a utility called in the `Predictor` class, not in the `Model` (just as a reference to anyone who might be trying to do this at some point in the future)...

---

FYI: [Possible solution for SQL formatting](https://github.com/andialbrecht/sqlparse)

**Comment by aaronsarnat** [comment]
@schmmd FYI

**Comment by joelgrus** [comment]
https://www.npmjs.com/package/parinfer

**Comment by schmmd** [comment]
ATIS already does this for SQL queries.

http://demo.allennlp.org/atis-parser/NDA2NjEx

```
  (SELECT DISTINCT flight . flight_id
   FROM flight
   WHERE (flight . departure_time BETWEEN 1800 AND 2200
          AND (flight . from_airport IN
                 (SELECT airport_service . airport_code
                  FROM airport_service
                  WHERE airport_service . city_code IN
                      (SELECT city . city_code
                       FROM city
                       WHERE city . city_name = 'LOS ANGELES' ) )
               AND (flight . to_airport IN
                      (SELECT airport_service . airport_code
                       FROM airport_service
                       WHERE airport_service . city_code IN
                           (SELECT city . city_code
                            FROM city
                            WHERE city . city_name = 'PITTSBURGH' ) )
                    AND flight . flight_days IN
                      (SELECT days . days_code
                       FROM days
                       WHERE days . day_name IN
                           (SELECT date_day . day_name
                            FROM date_day
                            WHERE date_day . year = 1993
                              AND date_day . month_number = 3
                              AND date_day . day_number = 1 ) )))) ) ;
```
