### ISSUE TITLE
Input format of SRL model 

### ISSUE THREAD

**Issue by acDante** [allenai/allennlp#1830]
Hello Allennlp team and thanks for your work :-). I have some questions about the input format of SRL model for training since I failed to find any detailed tutorials on this... Currently I am trying to evaluate the performance of your SRL model on a new dataset and would like to re-train the model on the dataset later on. Could you explain briefly the input format the model expects during training phase? How should I pre-process my data in order to feed into your SRL model?

**Comment by DeNeutoy** [comment]
https://github.com/allenai/allennlp/blob/master/allennlp/data/dataset_readers/semantic_role_labeling.py

https://github.com/allenai/allennlp/blob/master/allennlp/data/dataset_readers/dataset_utils/ontonotes.py

These are the two relevant classes you should look at. It's basically just the CONLL format used for the Ontonotes 5.0 dataset. Hopefully that's helpful!

**Comment by Huijun-Cui** [comment]
why you use such a complicate data format ,  hope you could improve it , to use your model for SRL I spend a whole day to figure out what is conll ，and fail to obtain the data , and now I should read the source code , redicuous
