### ISSUE TITLE
Feature request: simple_seq2seq should have beam search decoding

### ISSUE THREAD

**Issue by epwalsh** [allenai/allennlp#1833]
It looks like the `simple_seq2seq` it just doing a greedy decode during prediction, which produces really bad results compared to beam search. Since a basic beam search is probably the standard for a baseline seq2seq model, I think `simple_seq2seq` should have it.

I'm guessing maybe it hasn't been implemented yet since it's a little tricky with defining a transition function class, along with states and everything else. But I'd be willing to submit a PR, because I think it would be really useful to anyone (like me) who wants to use `simple_seq2seq` out of the box as a reasonable baseline for NMT or semantic parsing.

**Comment by schmmd** [comment]
@brendan-ai2 is going to follow up with some pointers about how this would be done.  We won't do it presently ourselves because of other priorities, but we welcome contributions.

**Comment by brendan-ai2** [comment]
Hi @epwalsh, I recently worked on a project that was essentially a fork of our existing `simple_seq2seq` model and did in fact need to code up beam search for that. You can find the code here: https://github.com/allenai/allennlp/blob/master/allennlp/models/event2mind.py#L279 It should be a serviceable starting point.

Possible improvements:
1. Adding length normalization.
2. Better test coverage. It's quite paltry at the moment. Basically just verifying that in the degenerate case it functions as greedy search.

(I should also mention that we do have some existing support for beam search, but that it's intended more for structured models that have constraints on their outputs. See https://github.com/allenai/allennlp/blob/master/allennlp/state_machines/__init__.py#L7.)

Happy to chat more and help with reviewing any PRs. Thanks!

**Comment by epwalsh** [comment]
Thanks @brendan-ai2, that is helpful. I'll let you know when I've got something!

**Comment by brendan-ai2** [comment]
Fixed as of @epwalsh's #1841.
