### ISSUE TITLE
Verify script fails if Java is not installed

### ISSUE THREAD

**Issue by seal6363** [allenai/allennlp#1848]
Because some of the unit tests require Java, 
But the instruction in readme doesn't mention Java.

**Comment by nelson-liu** [comment]
@schmmd the same issue should exist with `perl`. maybe worth just having `verify.py` use `allennlp test-install`?

**Comment by nelson-liu** [comment]
actually that probably isn't a great idea, since the `verify.py` script is for development use and we'd actually like to run all the tests (including those with dependencies we don't usually mention).

**Comment by joelgrus** [comment]
I also think that we should have a `check_for_java` helper function that raises a `RuntimeError` if Java is not installed, and that we should call it before we subprocess out the Java call from Python

**Comment by schmmd** [comment]
That's a good point Joel--but it seems like a separate issue: https://github.com/allenai/allennlp/issues/1850
