### ISSUE TITLE
Make class `Trainer` Registrable

### ISSUE THREAD

**Issue by WrRan** [allenai/allennlp#1877]
**Is your feature request related to a problem? Please describe.**
When I try to train multiple models in a single training process, and the training order of these models is alternated according to their performance, the default trainer does not meet this requirement very well (Or maybe it's because I'm not familiar with the usage of the `allennlp`).

**Describe the solution you'd like**
Make class `Trainer` registrable, and we can custom our own training process in config.

**Describe alternatives you've considered**
I do not have another solutions now.

**Additional context**

**Comment by matt-gardner** [comment]
This seems reasonable to me.  We're already constructing the `Trainer` [`from_params`](https://github.com/allenai/allennlp/blob/043ff07c6f0e0f95b71fe3463f86b722f871a6ad/allennlp/commands/train.py#L309), so this should just work.  PRs welcome.

**Comment by matt-gardner** [comment]
Though, you might actually have a hard time implementing your particular use case just by passing in a different `Trainer`.  We only pass a single model in.  You'd have to also modify the `Train` command, and if you're doing that, you can use your own `Trainer` class without having `Trainer` be `Registrable`.

So, yeah, it seems fine to have the `Trainer` be `Registrable` - it doesn't really hurt anything, and it's a very small change - I'm just not sure it really solves anything, either.

**Comment by zzyxzz** [comment]
As there're researches on training strategies, @matt-gardner I think it's a good suggestion (in the future) to allow loading cuntomized ```Trainer``` from configuration file using ```train``` command. 

Another use case is similar to @WrRan , but training a teacher-student network. When train the teacher model using a human annotated dataset, the student model is inactivated with no grad flow. When train the student model using another dataset, its loss is weighted by the confidence scores from teacher model. Training of teacher model and student model are randomly alternated during the training process.

**Comment by matt-gardner** [comment]
@zzyxzz, we did make it configurable, thanks to @WrRan's PR.  I agree there are some cases where this might be useful.  However, in both the case that he mentioned and the case that you're bringing up, just subclassing `Trainer` with a new type won't solve the problem, because you need _different logic in the `train` command also_.  The problem is bigger than just allowing a customized `Trainer`.
