### ISSUE TITLE
[Bug] `allennlp.nn.util.combine_tensors_and_multiply` is broken with `batch_size = 1`.

### ISSUE THREAD

**Issue by WrRan** [allenai/allennlp#1885]
**Describe the bug**
When I used `combine_tensors_and_multiply` in my `matrix_attention` with batch_size = 1, I got the RuntimeError as follows:
```bash
RuntimeError: invalid argument 2: equal number of batches expected, got 30, 1 at /opt/conda/conda-bld/pytorch_1525909934016/work/aten/src/TH/generic/THTensorMath.c:2271.
```

**To Reproduce**
Steps to reproduce the behavior
1. Copy `allennlp/training_config/dialog_qa.jsonnet` to proper place.
2. Modify the `batch_size` to `1`.
3. run `allennlp config/dialog_qa.jsonnet -s model`.

**Expected behavior**
No Runtime Error.

**System (please complete the following information):**
 - OS: Linux
 - Python version: 3.6.1
 - AllenNLP version: 0.6.1
 - PyTorch version: 0.4.0

**Additional context**
There exists a simple solution to fix it. The bug lies in the method `_get_combination_and_multiply` in `allennlp.nn.util.py`. Because it assumes the first dimension of value 1 should be removed:
```python
...
            if first_tensor.dim() == 4:
                expanded_dim = first_tensor.size().index(1)
                first_tensor = first_tensor.squeeze(expanded_dim)
            if second_tensor.dim() == 4:
                expanded_dim = second_tensor.size().index(1)
                second_tensor = second_tensor.squeeze(expanded_dim)
...
```
But we should skip the first dimension, which is `batch_size`.

**Comment by matt-gardner** [comment]
Can you try the latest master?  I'm pretty sure this issue is already fixed. See #1758.

**Comment by WrRan** [comment]
Thanks for your suggestion. It works.
