### ISSUE TITLE
Parse the log file for _actual_ parameters used to save in the model archive

### ISSUE THREAD

**Issue by matt-gardner** [allenai/allennlp#189]
Instead of copying the input parameter file when archiving a model, we should parse the log file to get the actual parameters that were used (including defaults).  This will make model archiving more robust to changes in default parameters (as recently happened with the tokenizer).  Seems like quite a bit of work to be sure the parameters are parsed out correctly, though, and it's not super high priority.

**Comment by DeNeutoy** [comment]
Irrelevant now with Beaker/it's very hard/boring work.
