### ISSUE TITLE
Automatically split dataset for MultiProcessDatasetReader

### ISSUE THREAD

**Issue by HarshTrivedi** [allenai/allennlp#1891]
**Feature Request**

Currently `MultiProcessDatasetReader` requires one to split the dataset file manually before the run and input the glob path from the experiment config. `AllenNlp` can't make implicit decision on how to divide the dataset file agnostic of it's structure. But at least for the cases in which instances are one per line, it should be possible to split automatically (eg `jsonl` files). 

So for such datasets, given an input file path, the appropriate splits can be made and stored temporarily in /tmp/.. and glob path can be generated out of it for usage.

Basically, someway of not having to manually split the data files (at least for line-wise datasets) for using `MultiProcessDatasetReader` can be helpful.

On possible way can be to have root level config as:
```
  "split_data": {
       "train": {"by_lines": 10000}
       "validation" {"by_lines": 10000}
   },
```
and handle it [here](https://github.com/allenai/allennlp/blob/master/allennlp/commands/train.py#L145). The relevant code can take `train_data_path `, split it in 10K lines each, store in /tmp, give a glob path and reset it as `train_data_path `. For now "by_lines" splitter can be implemented and any specific use case can be left for extension for the user. This way seems hacky though, because ideally this config should lie in config of `MultiProcessDatasetReader`...

**Comment by joelgrus** [comment]
I feel like people should only use `MultiprocessDatasetReader` very deliberately, and that includes already having their data split across multiple files. This doesn't feel like functionality that belongs in the library itself.

**Comment by matt-gardner** [comment]
I think you only want to do this with lazy datasets, where the data is too large to read all at once.  Right?  If you're looking for a speedup from multiprocessing during training, and your data fits in memory, what you want is a [_`MultiprocessIterator`_](https://github.com/allenai/allennlp/blob/master/allennlp/data/iterators/multiprocess_iterator.py), not the dataset reader.

**Comment by HarshTrivedi** [comment]
@matt-gardner My dataset reader is non-lazy. The data does fit in memory but there are many small instances. Similar to `snli` in which there are 500K instance but each is just 2 sentences. My dataset has 2 M such small instances and reading it first time takes about 20-30 minutes. So it's this time that I was trying to save rather than iterating during training. For this purpose `MultiprocessDatasetReader` is appropriate, right? For optimizing training time, I will give `MultiprocessIterator` a try. Thanks!  Let me know if I misunderstood something.

**Comment by matt-gardner** [comment]
I think @joelgrus is the right person to answer this question about what the intended use case for the `MultiprocessDatasetReader` is; I was just guessing.  With a single file that fits in memory that you want to process faster, you really want to parallelize this part: https://github.com/allenai/allennlp/blob/24e5547b55e26d8a6b36ef32c1e965f24f0970a1/allennlp/data/dataset_readers/reading_comprehension/squad.py#L56-L71

I know how to trivially parallelize that in scala, but I don't know how to do it python.  And the particular way you do it depends on a lot of things (like, maybe you should be batching things together when tokenizing, so spacy is faster), so it's hard to make a general mechanism for speeding that up.  If you have any good ideas here, suggestions welcome.

**Comment by joelgrus** [comment]
the use case I implemented it for was for training giant language models (which I haven't gotten to the point of trying yet). 

I'm still worried that the way the dataset reader and iterator fit together (using an iterator) will defeat most of the point of parallelizing things, so I really would like to expose the dataset reader's queue to the iterator directly, but I wasn't able to make that work when I tried it. I'll probably try it again at some point.

**Comment by joelgrus** [comment]
this is sort of an allennlp-ization of some code that multiprocess reads files and generates tensor dicts directly, so splitting it into a "dataset reader" piece and a "data iterator" piece resulted in some awkwardness

**Comment by HarshTrivedi** [comment]
@joelgrus So in my use case where I have about 2+ M instances each is just a pair of sentences, what do you suggest I should be using for speedup (reading and/or iterating)? multiprocess reader, iterator or both?

**Comment by joelgrus** [comment]
you'll need to profile your code to figure out what the slow parts are, but (for example) if I create a 1.8GB file with 1M 300-word "sentences", it only takes about 17 seconds to open it and read it and count all the words in it (using plain Python), so the *reading* is probably not the slow part
