### ISSUE TITLE
Calypso Port Tracker

### ISSUE THREAD

**Issue by brendan-ai2** [allenai/allennlp#1894]
In progress:
1. https://github.com/allenai/allennlp/pull/1787, "bidirectional LM + cnn highway encoder + gated cnn encoder"
2. https://github.com/allenai/allennlp/pull/1881, "Tentative port of `LMDatatsetReader`"

Todo:
1. Train a basic language model using PR #1787 and PR #1881.
2. Determine whether specific customizations are needed for the Elmo language model.
3. Implement necessary customizations.
4. Address the single-process bottleneck between the reader and iterator.
5. Investigate how Calypso handles multi-GPU training.
6. Implement multi-GPU training (cf. multiprocess support for dataset reading).
7. Train full model.

**Comment by brendan-ai2** [comment]
@joelgrus, notes from our chat. Feel free to correct. @schmmd, FYI for Friday.

**Comment by brendan-ai2** [comment]
Tasks:
1. Sampled softmax
  - Joel, in progress.
2. Multi GPU training
  - Vidur had a piece of this implemented?
  - Brendan, starting.
3. Train full (but simple) model
  - Add a perplexity metric (should be very simple)
  - Depends on 1 and 2.
4. Add a transformer based on the annotated transformer.
  - Deprecate all existing transformers.
5. Real model using transformers.
  - Depends on 3 and 4.

As for time estimates, that's not particularly clear. Most of those feel like roughly one week chunks to me, but that's a SWAG. The notable exception will be part 5 involving the model tuning which I suspect will take substantially longer. Matt Peters reported that the runtime alone will take a week. @joelgrus, by all means refine/correct these estimates. :)

**Comment by brendan-ai2** [comment]
Note to self: Figure out what size dataset Matt used for iteration.

**Comment by schmmd** [comment]
@brendan-ai2 can we close this out now?  If there's remaining work that this helpfully captures then maybe we can move those items to their own issues?

**Comment by brendan-ai2** [comment]
Yep, I'll close this out. Cleanup ticket here: https://github.com/allenai/allennlp/issues/2270
