### ISSUE TITLE
the 'semantic_parsing.quarel' doc page has several wrong class names

### ISSUE THREAD

**Issue by threefoldo** [allenai/allennlp#1895]
**Describe the bug**
In page https://allenai.github.io/allennlp-docs/api/allennlp.models.semantic_parsing.quarel.html, the class name is 'semantic_parsing.atis', not 'quarel', there are two 'atis' classes in the left panel.

**To Reproduce**

**Expected behavior**

**System (please complete the following information):**

**Additional context**

**Comment by DeNeutoy** [comment]
This is a copy paste error - if you wanted to fix it, you could modify the doc here and send a PR:

https://github.com/allenai/allennlp/blob/master/doc/api/allennlp.models.semantic_parsing.quarel.rst
