### ISSUE TITLE
Add a `text_to_instance` method on `DatasetReader`

### ISSUE THREAD

**Issue by matt-gardner** [allenai/allennlp#190]
The `Predictors` currently have to pull out the tokenizer and the token indexers from the `DatasetReader` and recreate what the `DatasetReader` does internally for every instance.  This means that if we want to change (or add parameters to) what the `DatasetReader` does, we have to change the `Predictors` to match.  Instead, we should just add a `text_to_instance` method on the `DatasetReader` itself, so that the `Predictor` can just keep around the `DatasetReader`, and pass off all processing to it.

**Comment by joelgrus** [comment]
I'll do this, should be quick

**Comment by joelgrus** [comment]
actually, I take this back, it's not quick, I'll leave it for later
