### ISSUE TITLE
How to train a NLVR semantic parser?

### ISSUE THREAD

**Issue by threefoldo** [allenai/allennlp#1904]
I have downloaded the nlvr dataset, use the 'experiment.json' in fixtures/semantic_parser/nlv_direct_semantic_parser as the config file to train. Allennlp can load the dataset, but failed to train, due to error: no 'loss' function.
```
    loss = output_dict["loss"]
KeyError: 'loss'
```
I have read all the document about NLVR, including docstrings of NlvrExecutor, NlvrWorld, NlvrDatasetReader, the json files in fixtures/data, but still don't understand how to put all pieces together, how the semantic parser works. Do I miss something for training NLVR?

**Comment by matt-gardner** [comment]
For NLVR, you need to do a search to get initial logical forms to train with.  I'm guessing you don't have any logical forms, and training with our implementation of MML requires logical forms, so get no loss.  You can run an initial search using [this script](https://github.com/allenai/allennlp/blob/master/scripts/nlvr/get_nlvr_logical_forms.py).  Maybe @pdasigi also has the output of that initial script that he can put on s3 somewhere that you can access.

**Comment by threefoldo** [comment]
Thanks, I will try those scripts. There are 3 files in fixtures/data/nlvr: ungrouped, grouped, processed. I guess the original training dataset are 'ungrouped', they should be grouped by sentences, then valid actions are generated based on 'sentence' into 'processed', they are the actual training dataset.

So, the basic work flow of semantic parser is like this:
1, generate valid actions (logic forms) for each sentence;
2, the encoder generates a vector representing the meaning of a sentence, the decoder try to guess the correct action sequences, i.e. select actions from valid actions.
3, for each action sequence, an Executor will run on it, get the final result and compare with the expected value or action sequence to get a loss.
4, fine tune the model with the loss.

The step 3 is new, compared to general encoder-decoder model. Instead of searching the whole vocabulary, step 3 limit the search space to valid actions, which has clearly defined meaning and is much smaller. Thus, the output of the model will unlikely become meaningless.

**Comment by matt-gardner** [comment]
@threefoldo, closing this for now, as it looks like you're questions have all been answered.  If you have more, feel free to re-open this, or open a new issue.
