### ISSUE TITLE
Making AllenNLP's dependencies selectable at download

### ISSUE THREAD

**Issue by kylase** [allenai/allennlp#1908]
**Is your feature request related to a problem? Please describe.**
Installing AllenNLP comes along with many dependencies, such as spacy, etc, which most of the time aren't necessary for most use cases. Fresh install on a virtualenv takes up almost 900MB.

This allows more flexibility and ease of deployment when coupled with other libraries.

**Describe the solution you'd like**
[Using setuptools extras](https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies), we can separate the different modules (reference to https://github.com/allenai/allennlp#what-is-allennlp) in AllenNLP to e.g. 
- `data`
- `models` 
- `modules`
- `nn`
- `service`

If the user wants all the modules to be usable, he/she can use `pip install allennlp[all]`. Otherwise, `pip install allennlp[nn]` will install on the AllenNLP tensor utilities. `pip install allennlp[models, service]` will install the dependencies required for deployment of pretrained models with the web server.

**Describe alternatives you've considered**
I don't have an alternative solution as of now.

**Comment by schmmd** [comment]
@kylase I'm not sure there's too much we can do to reduce the size.  I'm using Conda instead of VirtualEnv, but I think you'll find the same in either.  Almost all of the size is due to Python.

```
$ du -hs ~/miniconda3/envs/allennlp
941M	/Users/michaels/miniconda3/envs/allennlp
```

```
1.2M	libc++.a
1.2M	libsqlite3.0.dylib
1.4M	libtk8.6.dylib
1.5M	libsqlite3.a
1.6M	libtcl8.6.dylib
1.8M	tk8.6
2.0M	libcrypto.1.0.0.dylib
2.4M	tcl8.6
2.9M	libpython3.6m.dylib
3.3M	libcrypto.a
4.1M	mypy
5.7M	libpython3.6m.a
868M	python3.6
```

**Comment by schmmd** [comment]
@kylase did you run into a specific dependency conflict or are you just looking to reduce the amount of space an AllenNLP installation takes?

**Comment by kylase** [comment]
I am using virtualenv and my Python are symlinked via pyenv as I'm using 3.6.6. 

A bare new virtualenv takes 15MB:
```
$ du -h -d 1
3.0M	./bin
  0B	./include
 12M	./lib
 15M	.
```

An environment with only `allennlp` installed
```
$ du -h -d 1
8.0K	./man
3.4M	./bin
4.0K	./include
897M	./lib
4.0K	./share
901M	.
```

**Comment by schmmd** [comment]
@kylase can share a `du -h | sort -h` of `./lib`?

**Comment by schmmd** [comment]
Ah sorry, I didn't realize that `python3.6` was a directory.  For example, `spacy` requires 243M.

**Comment by kylase** [comment]
Yup, There are `numpy`, `scipy`, `scikit-learn` and many `Flask` packages, which make the entire package quite heavy. Currently I am trying to use the CRF layer from `allennlp` but realised that there are so many packages installed at the same time, which I worried might clash with existing packages.

This method is used by [Apache Airflow project](https://airflow.apache.org/installation.html) to manage optional packages that might not be necessary for all users.

I might be over-simplifying the abstraction of modules in my initial proposal and the actual outcome might be more than 5 modules.

**Comment by handsomezebra** [comment]
Another way is to divide the dependencies into core and extensions. I tried once to remove many unnecessary dependencies for me including spacy, numpy, scipy, scikit-learn, flask, awscli, etc. Then I will have to make some changes to make the code work. Most of the changes are moving some of the import inline so they are only executed when needed.

**Comment by LanceNorskog** [comment]
Another example: I'm getting "library not found for -lstdc++" when I install because jsonnet wants to be compiled. On the Mac you have to install XCode- I did not know this.

**Comment by konstin** [comment]
Would you accept a pull request making e.g. flask and flask-cors or boto optional?

**Comment by matt-gardner** [comment]
See #2996.

**Comment by matt-gardner** [comment]
We're solving this another way, by removing most of the dependencies.  Closing this issue.
