### ISSUE TITLE
Could I have a sample script on how to use coreference-resolution?

### ISSUE THREAD

**Issue by chikiuso** [allenai/allennlp#1915]
The demo on of coref is great : 
http://demo.allennlp.org/coreference-resolution

Could I have a python sample script on how to use coreference-resolution? I tried with the following but failed : 

from allennlp.models.archival import load_archive
from allennlp.predictors import Predictor

archive = load_archive("./coref-model-2018.02.05.tar.gz")
predictor = Predictor.from_archive(archive, 'coreference-resolution')
predictor.predict_json({"document": "This is a sentence to be predicted!"})

**Comment by DeNeutoy** [comment]
```
from allennlp import pretrained
model = pretrained.neural_coreference_resolution_lee_2017()

results = model.predict(sentence="Put your sentence here.")
```
