### ISSUE TITLE
Feature request: call NVIDIA Management Library directly to get GPU statistics

### ISSUE THREAD

**Issue by epwalsh** [allenai/allennlp#1920]
I stumbled across this on the [Fast.ai forum via Twitter](https://forums.fast.ai/t/show-gpu-utilization-metrics-inside-training-loop-without-subprocess-call/26594): apparently the `nvidia-smi` command just calls the NVIDIA Management Library to get GPU statistics, which means we can avoid [this subprocess call](https://github.com/allenai/allennlp/blob/606a61abf04e3108949022ae1bcea975b2adb560/allennlp/common/util.py#L325) by just directly calling a wrapper around the c library from Python. The discussion on the forum gives a simple example using the `nvidia-ml-py3` wrapper.

I'm happy to submit a PR to replace the subprocess call to `nvidia-smi` with this approach if you'd like.

**Comment by matt-gardner** [comment]
Sounds good to me!

**Comment by joelgrus** [comment]
I am slightly leery of taking a dependency on a rarely-updated library with 12 github stars that doesn't really add any additional functionality.

**Comment by epwalsh** [comment]
I'll see if it's easy enough to just wrap the functions we need without using a full third-party wrapper like `nvidia-ml-py3`

**Comment by matt-gardner** [comment]
Hmm, yeah, @joelgrus has a point.  I was too eager - I saw the twitter comment too.

**Comment by schmmd** [comment]
@epwalsh thanks for bringing this up, but as this isn't a particular problem presently we're not interested in implementing it.
