### ISSUE TITLE
Tokenizer to use with ELMO

### ISSUE THREAD

**Issue by zplizzi** [allenai/allennlp#1933]
In the ELMO tutorial "using ELMO interactively" [section](https://github.com/allenai/allennlp/blob/master/tutorials/how_to/elmo.md#using-elmo-interactively), it would be useful to mention what tokenizer should be used. Using a different tokenizer to the one used to train ELMO will likely result in worse performance - so a user needs to know what tokenizer was used to train the model, which I can't readily find.

**Comment by schmmd** [comment]
@matt-peters I presume you used the SpaCY tokenizer?

**Comment by matt-peters** [comment]
The ELMo model was trained on a corpus tokenized with the Moses Tokenizer. In practice I have used both the Moses tokenize and spacy when tokenizing new text, there might a small difference when switching tokenizers, although in many cases it will be small.

**Comment by jowagner** [comment]
Comparing cosine similarity of vectors for `are`, `'re`, `&apos;re`, `will`, `'ll` and `&apos;ll` in simple example sentences, it seems that the provided elmo model does not know about `&apos;`: The unescaped contractions are about 10 times more similar to the full form than the escaped ones.

This alone might still be explained by the common suffix and the shorter lengths of the sequence of characters the tokens do not have in common. To test further, I compared `and`, `&` and `&amp;` in a suitable context. Also here the unescaped token wins, though only with a 4.4 higher similarity.

These findings suggests that `-no-escape` was used with the Moses tokeniser. @matt-peters Please confirm.

**Comment by matt-peters** [comment]
The model was trained on unescaped text, tokenized with moses tokenizer. So if you are using the `MosesTokenizer` from nltk, pass `escape=False`, e.g.

```
tokenizer = MosesTokenizer()
tokens = tokenizer.tokenize(text, escape=False)
```

**Comment by jowagner** [comment]
Thanks for the pointers. Much appreciated.
