### ISSUE TITLE
ImportError: cannot import name 'Batch'

### ISSUE THREAD

**Issue by susht3** [allenai/allennlp#1936]
>>> from allennlp.data.dataset import Batch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'Batch'

**Comment by matt-gardner** [comment]
We are going to need a lot more information than this if we are going to be able to help you.  I'm going to close this issue - please re-open it and follow our issue template, giving the information that we request there.
