### ISSUE TITLE
add copynet for seq2seq model

### ISSUE THREAD

**Issue by susht3** [allenai/allennlp#1937]
could you add copy and coverage for simple seq2seq model?

**Comment by matt-gardner** [comment]
This is not on our roadmap for us to do ourselves in the near future.  Contributions welcome!  Lucky for you, we may be getting a contribution to add this soon (at least the copy mechanism).  See https://github.com/allenai/allennlp/pull/1928#issuecomment-431616137.  And if that code doesn't actually get contributed upstream, it may at least be a good starting place for you.
