### ISSUE TITLE
train speed of quac model is slow

### ISSUE THREAD

**Issue by shaonan1993** [allenai/allennlp#1945]
Hi, I‘m trying to train the QuAC baseline from scratch, but the training speed is very slow(about 2s per iteration, and the speed reduced to 200s per iteration after 20 hours)

I did not change any code in dialog_qa.py and dialog_qa.jsonnet, except modified the input_size of phrase_layer from 1124 to 1144.

what the problem could be?

OS: Linux
Python version: 3.6.1
GPU: M40 with 24G RAM
AllenNLP version: v0.7.1(install from source code)

**Comment by matt-gardner** [comment]
ELMo is very slow to train with, unfortunately.  There are some tricks you can do with pre-computing the vectors and taking them as a separate input to the model, but that's not currently easy.  I just tried running this (the default `dialog_qa.jsonnet` on master) on a K80 GPU on AWS, and I'm getting ~7 seconds per batch (batch size 10) on that GPU.  Maybe @eunsol can give us some more information on how long it took her to training with her original code.

**Comment by susht3** [comment]
> ELMo is very slow to train with, unfortunately. There are some tricks you can do with pre-computing the vectors and taking them as a separate input to the model, but that's not currently easy. I just tried running this (the default `dialog_qa.jsonnet` on master) on a K80 GPU on AWS, and I'm getting ~7 seconds per batch (batch size 10) on that GPU.

i find that, if i use a small sample file instead of the train file, it can run fast very much, i don't know whether it is the problem of data loading, maybe allennlp load all data at a time? how to improve data loading to let it loads just a batch data at a time?

**Comment by schmmd** [comment]
@matt-gardner why would @shaonan1993's training slow down over time?

**Comment by matt-gardner** [comment]
Maybe a memory leak on the CPU that's leading to swapping?  I don't know.

**Comment by Shuailong** [comment]
It takes me around 2hours to train each epoch. GPU: Titan 1080ti, memory 32G, Ubuntu 16.04. GPU memory 11G

**Comment by schmmd** [comment]
@shaonan1993 closing for now--please reopen if you have a repro and we'll look into it.
