### ISSUE TITLE
change spaCy dataset for NER model

### ISSUE THREAD

**Issue by nityansuman** [allenai/allennlp#1946]
How can i change or re-train the NER model with the en_core_web_lg dataset which is much larger dataset than en_core_web_sm which NER model is using by default.

**Comment by matt-gardner** [comment]
I'm not sure exactly what you're asking for here.  The [NER model](https://github.com/allenai/allennlp/blob/master/allennlp/data/dataset_readers/conll2003.py) that we use assumes pre-tokenized input and doesn't use spacy at all.  Are you talking about just changing the spacy model used for preprocessing data for some other, non-NER model?

**Comment by nityansuman** [comment]
@matt-gardner I am trying to use Coreference resolution model. I tried as suggested in the demo page and then it downloaded spaCy dataset *en_core_web_sm* which is a farely small dataset. I want to use the larger dataset instead of that hoping for a better performance. Specifically *en_core_web_lg* as the default dataset.

**Comment by schmmd** [comment]
@nityansuman we trained on the [CONLL 2003](https://www.clips.uantwerpen.be/conll2003/ner/).  If you are able to get training data in the same format as CONLL 2003 then you can use `allennlp train` with https://github.com/allenai/allennlp/blob/master/training_config/ner.jsonnet and your training data to train a new model.

**Comment by matt-gardner** [comment]
@nityansuman, the coref model that we have also takes _pre-tokenized_ input, and does not use NER.  Did you add this?  We aren't using spacy at all during training, and for predicting during a demo it's only used for tokenization (which isn't a trained model, it's just a deterministic piece of code).

**Comment by nityansuman** [comment]
@schmmd Thanks! Not sure but hoping CONLL 2012 data is also of the same format, will have to check.
@matt-gardner I havn't added but planning to do so.

**Comment by matt-gardner** [comment]
@nityansuman, I'm still not totally sure exactly what you want to do.  Can you explain it in more detail?  Adding NER (with whatever spacy model you want) can be as easy as changing a configuration file, but I can't help you with that until I know exactly what you're trying to do.
