### ISSUE TITLE
Error in ELMO example

### ISSUE THREAD

**Issue by mukesh-mehta** [allenai/allennlp#1947]
https://github.com/allenai/allennlp/blob/master/tutorials/how_to/elmo.md#using-elmo-interactively
The example given in this section is not calculating the cosine distance between "ate" and "carrot" as you have mentioned wrong index while comparing the vectors.

**Comment by schmmd** [comment]
@mukesh-mehta can you be more specific?  The indices look right to me at first glance.

```
$ ipython
> from allennlp.commands.elmo import ElmoEmbedder
> elmo = ElmoEmbedder()
> tokens = ["I", "ate", "an", "apple", "for", "breakfast"]
> vectors = elmo.embed_sentence(tokens)

> assert(len(vectors) == 3) # one for each layer in the ELMo output
> assert(len(vectors[0]) == len(tokens)) # the vector elements correspond with the input tokens

> import scipy
> vectors2 = elmo.embed_sentence(["I", "ate", "a", "carrot", "for", "breakfast"])
> scipy.spatial.distance.cosine(vectors[2][3], vectors2[2][3]) # cosine distance between "ate" and "carrot" in the last layer
0.18020617961883545
```

```
["I", "ate", "an", "apple", "for", "breakfast"][3] == "apple"
["I", "ate", "a", "carrot", "for", "breakfast"][3] == "carrot"
```

**Comment by mukesh-mehta** [comment]
In last line you mentioned 
``scipy.spatial.distance.cosine(vectors[2][3], vectors2[2][3]) # cosine distance between "ate" and "carrot" in the last layer``

**Comment by mukesh-mehta** [comment]
also can you explain the difference between the two ``bilstm embeddings`` output.

**Comment by schmmd** [comment]
Thanks and fixed (https://github.com/allenai/allennlp/commit/a3bd4759fb55951dcf598a0bd8d7a4b4807e9124)!

**Comment by schmmd** [comment]
@mukesh-mehta I don't understand your last question--but I'm happy to answer it if you provide more detail in a separate issue.  I'm not sure if you're asking for the difference between the ELMo layers, or asking why embeddings are not deterministic, or asking why the "carrot" vector is different than the "apple" vector, etc.
