### ISSUE TITLE
cuda out of memory while using my own model

### ISSUE THREAD

**Issue by SparkJiao** [allenai/allennlp#1948]
**Description**
I have implemented the Multi-Granularity Hierarchical Attention Fusion Networks to run on the CoQA, the paper is here: [https://acl2018.org/paper/1469](https://acl2018.org/paper/1469). At first I can't move the model and parameters to the gpu, it trapped at trainner.py "model = model.cuda(cuda_device)", and then I move the elmo layers, highway layers, using lazy dataset reader and modified the batch_size to 1 but still can't work.

**System (please complete the following information):**
 - OS: [Ubuntu]
 - Python version: [3.7]
 - AllenNLP version: ["I installed from master"]
 - PyTorch version: (0.4.1)
 - GPU: [TITAN Xp 12189MB]

**Additional context**
I have successfully run the bidaf model in the library on CoQA before.

**Comment by susht3** [comment]
> **Description**
> I have implemented the Multi-Granularity Hierarchical Attention Fusion Networks to run on the CoQA, the paper is here: https://acl2018.org/paper/1469. At first I can't move the model and parameters to the gpu, it trapped at trainner.py "model = model.cuda(cuda_device)", and then I move the elmo layers, highway layers, using lazy dataset reader and modified the batch_size to 1 but still can't work.
> 
> **System (please complete the following information):**
> 
> * OS: [Ubuntu]
> * Python version: [3.7]
> * AllenNLP version: ["I installed from master"]
> * PyTorch version: (0.4.1)
> * GPU: [TITAN Xp 12189MB]
> 
> **Additional context**
> I have successfully run the bidaf model in the library on CoQA before.

i find your coqa demo, but it cannot work, could you update your github?

**Comment by SparkJiao** [comment]
> > **Description**
> > I have implemented the Multi-Granularity Hierarchical Attention Fusion Networks to run on the CoQA, the paper is here: https://acl2018.org/paper/1469. At first I can't move the model and parameters to the gpu, it trapped at trainner.py "model = model.cuda(cuda_device)", and then I move the elmo layers, highway layers, using lazy dataset reader and modified the batch_size to 1 but still can't work.
> > **System (please complete the following information):**
> > 
> > * OS: [Ubuntu]
> > * Python version: [3.7]
> > * AllenNLP version: ["I installed from master"]
> > * PyTorch version: (0.4.1)
> > * GPU: [TITAN Xp 12189MB]
> > 
> > **Additional context**
> > I have successfully run the bidaf model in the library on CoQA before.
> 
> i find your coqa demo, but it cannot work, could you update your github?

which demo? CoQA-baseline or SLQA?

**Comment by susht3** [comment]
> CoQA-baseline

CoQA-baseline

**Comment by susht3** [comment]
> > > **Description**
> > > I have implemented the Multi-Granularity Hierarchical Attention Fusion Networks to run on the CoQA, the paper is here: https://acl2018.org/paper/1469. At first I can't move the model and parameters to the gpu, it trapped at trainner.py "model = model.cuda(cuda_device)", and then I move the elmo layers, highway layers, using lazy dataset reader and modified the batch_size to 1 but still can't work.
> > > **System (please complete the following information):**
> > > 
> > > * OS: [Ubuntu]
> > > * Python version: [3.7]
> > > * AllenNLP version: ["I installed from master"]
> > > * PyTorch version: (0.4.1)
> > > * GPU: [TITAN Xp 12189MB]
> > > 
> > > **Additional context**
> > > I have successfully run the bidaf model in the library on CoQA before.
> > 
> > 
> > i find your coqa demo, but it cannot work, could you update your github?
> 
> which demo? CoQA-baseline or SLQA?

CoQA-baseline

**Comment by matt-gardner** [comment]
If you aren't able to even move the model itself over to the GPU, that means you must have a _ton_ of parameters.  Running the model's computations, with all of the intermediate tensors and gradients, typically takes most of your memory, so something must be up with the size of your model.  Maybe your vocabulary is astronomically large?  It's hard to know what the issue is here without digging into your code, which I unfortunately don't have time to help you with.

**Comment by SparkJiao** [comment]
> If you aren't able to even move the model itself over to the GPU, that means you must have a _ton_ of parameters. Running the model's computations, with all of the intermediate tensors and gradients, typically takes most of your memory, so something must be up with the size of your model. Maybe your vocabulary is astronomically large? It's hard to know what the issue is here without digging into your code, which I unfortunately don't have time to help you with.

Thanks u a lot and I'll check it layer by layer.
