### ISSUE TITLE
how to use cuda?

### ISSUE THREAD

**Issue by susht3** [allenai/allennlp#1950]
i find that i cannot use gpu, i have gpu, but it run on cpu, and i can not find where to define gpu

**Comment by WrRan** [comment]
To config GPU, you should set `cuda_device` to `0` or something.
And the following resources may be helpful for you.
[tutorials - allennlp.org](https://allennlp.org/tutorials)
[advanced tutorials - github](https://github.com/allenai/allennlp/tree/master/tutorials)

**Comment by susht3** [comment]
> To config GPU, you should set `cuda_device` to `0` or something.
> And the following resources may be helpful for you.
> [tutorials - allennlp.org](https://allennlp.org/tutorials)
> [advanced tutorials - github](https://github.com/allenai/allennlp/tree/master/tutorials)

i use allennlp train，but i don't know how to change cuda_device, it is set to -1 in trainer.py
cuda_device : ``int``, optional (default = -1)

**Comment by juliahane** [comment]
Hi
I have the same issue here, I did setup cuda_device to 0, and I am running the codes in https://github.com/mrqa/MRQA-Shared-Task-2019/tree/master/baseline for BERT base.
