### ISSUE TITLE
dialog_qa model

### ISSUE THREAD

**Issue by susht3** [allenai/allennlp#1951]
i get out_of_memory error on this model, but i think bidaf model is simple, it use elmo, does the model train elmo? or use the pretrain elmo model?

**Comment by matt-gardner** [comment]
I just tried running the `dialog_qa.jsonnet` that's checked in to the current master, on a K80 GPU on AWS.  This version includes ELMo.  It is currently using about 10G of GPU RAM, and ~4G of CPU RAM, and it is running successfully, at about 7 seconds per batch (with batch size 10).
