### ISSUE TITLE
Include "Multi-Granularity Hierarchical Attention Fusion Networks" in the User Gallery

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp#1952]
@SparkJiao you reported in https://github.com/allenai/allennlp/issues/1948 that you implemented Multi-Granularity Hierarchical Attention Fusion Networks (https://acl2018.org/paper/1469) in AllenNLP.  Is you code public?  May we include it in [our user gallery](https://allennlp.org/models)?

**Comment by SparkJiao** [comment]
Well of course it's public but I am a beginner of pytorch and deep learning and I think my code is full of bugs and may not get good results as mentioned in the paper. So just use it if it can run successfully

**Comment by schmmd** [comment]
@SparkJiao  seems like it's too early to include it now, but if you ever clean it up please re-open this issue!
