### ISSUE TITLE
Understand the trained Elmo model application on test data

### ISSUE THREAD

**Issue by DGAlb** [allenai/allennlp#1957]
**Is your feature request related to a problem? Please describe.**
I am a little confused about how a trained Elmo model will be applied on new data. 

On this website (https://tfhub.dev/google/elmo/2), it is described that the output dictionary contains:
word_emb: the character-based word representations with shape [batch_size, max_length, 512].
lstm_outputs1: the first LSTM hidden state with shape [batch_size, max_length, 1024].
lstm_outputs2: the second LSTM hidden state with shape [batch_size, max_length, 1024].
elmo: the weighted sum of the 3 layers, where the weights are trainable. This tensor has shape [batch_size, max_length, 1024]
default: a fixed mean-pooling of all contextualized word representations with shape [batch_size, 1024].

My question. When a new sentence is fed into the model, for new word not appeared before, will it be embedded by "elmo, the weighted sum of the 3 layers"; for old word but in this new sentence, will it be embedded by "word_emb" or "elmo"

**Describe the solution you'd like**
Some description/ document about how the trained model will be applied on new data. Thanks!

**Comment by schmmd** [comment]
@DGAlb the ELMo implementation at https://tfhub.dev/google/elmo/2 is separate from AllenNLP.  If you would like to use the ELMo implementation inside AllenNLP, please see https://allennlp.org/elmo and https://github.com/allenai/allennlp/blob/master/tutorials/how_to/elmo.md.  We're happy to answer questions on the AllenNLP system!
