### ISSUE TITLE
QUESTIONS About using machine comprehension in an own project 

### ISSUE THREAD

**Issue by ajay01994** [allenai/allennlp#1960]
HI guys,
I have made a basic pdf search engine using elastic search, and made an application which connects using Node Js. I am trying to add  Allen NLP 's machine comprehension in elastic search inside the node. Js based application, can you please tell me how to do that? , I am a litle new in this

**Comment by schmmd** [comment]
@ajay01994 I don't quite understand your question as I don't know what it means to do something "in elastic search inside the node".  But at the end of the day, all Machine Comprehension is is a simple function:

```
machine_comprehension(excerpt, question) = answer
```

You can use this function as is with the examples on https://allennlp.org/models.

It sounds like you're trying to identify where the right answer is in a large corpus, which is out of scope for our machine comprehension model.  We were attempting something similar in https://github.com/allenai/allennlp/pull/804, but that's no longer a priority.

**Comment by ajay01994** [comment]
yes .i wanted to use it for a larger corpus , is there any API for MC ?

**Comment by schmmd** [comment]
@ajay01994 please look at https://allennlp.org/models to see how to make predictions for the MC model.

**Comment by ajay01994** [comment]
Tanks @schmmd   :+1:
