### ISSUE TITLE
for reinforcement learning

### ISSUE THREAD

**Issue by susht3** [allenai/allennlp#1961]
i have some confuses about the implement by allennlp:

1. the train process is defined, can we add reinforcement algorithms in it? we should define the reward for actions, and i donnt know whether allennlp support it.
2. for seq2seq model, can we add schedule sampling methods in it, such like, feed the output of last step to the input of the next step? it looks like that we should change the train function.

**Comment by matt-gardner** [comment]
1. Reinforcement learning is super broad.  We have some reinforcement-learning-like ability in the state machine code, but whether you should use that really depends on exactly what you're trying to do.

2. Scheduled sampling is already available: https://github.com/allenai/allennlp/blob/4e4409708b2bfe85603e67a5fd2f2f176b41f2d8/allennlp/models/encoder_decoders/simple_seq2seq.py#L59-L66
