### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by zheyang0715** [allenai/allennlp#1973]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**System (please complete the following information):**
 - OS: [e.g. OSX, Linux]
 - Python version: [if it's not 3.6.1 or later, that's probably your problem]
 - AllenNLP version: [e.g. v0.7.0, or "I installed from master"]
 - PyTorch version: (if you installed it yourself)

**Additional context**
this all log info:

D:\projects\allennlp1\venv\Scripts\python.exe D:/projects/allennlp1/venv/Lib/site-packages/allennlp/run.py
D:\projects\allennlp1\venv\lib\importlib\_bootstrap.py:219: RuntimeWarning: cymem.cymem.Pool size changed, may indicate binary incompatibility. Expected 48 from C header, got 64 from PyObject
  return f(*args, **kwds)
D:\projects\allennlp1\venv\lib\importlib\_bootstrap.py:219: RuntimeWarning: cymem.cymem.Address size changed, may indicate binary incompatibility. Expected 24 from C header, got 40 from PyObject
  return f(*args, **kwds)
Traceback (most recent call last):
  File "D:/projects/allennlp1/venv/Lib/site-packages/allennlp/run.py", line 15, in <module>
    from allennlp.commands import main  # pylint: disable=wrong-import-position
  File "D:\projects\allennlp1\venv\Lib\site-packages\allennlp\__init__.py", line 18, in <module>
    import spacy, torch, numpy  # pylint: disable=multiple-imports
  File "D:\projects\allennlp1\venv\Lib\site-packages\torch\__init__.py", line 80, in <module>
    from torch._C import *
ImportError: DLL load failed: The specified module could not be found.

Process finished with exit code 1

please help me

**Comment by matt-gardner** [comment]
Sadly, we don't support windows.  See #612.
