### ISSUE TITLE
AttributeError: type object 'TokenIndexer' has no attribute 'dict_from_params'

### ISSUE THREAD

**Issue by tingkai-zhang** [allenai/allennlp#1977]
Hi, I have the following error when i am running code: https://github.com/joelgrus/kaggle-toxic-allennlp

**Describe the bug**

AttributeError: type object 'TokenIndexer' has no attribute 'dict_from_params'

**To Reproduce**

In reader.py 

```
    def from_params(cls, params: Params) -> 'ToxicReader':
        tokenizer = Tokenizer.from_params(params.pop('tokenizer', {}))
        token_indexers = TokenIndexer.dict_from_params(params.pop('token_indexers', {}))
```

Could you give me an example of initialize a TokenIndexer from params with specified WordSplitter(OpenAISplitter)?

**Expected behavior**

**System (please complete the following information):**
 - OS: Linux
 - AllenNLP version: v0.7.0
 
**Additional context**

I am trying to reproduce the opanai transformer result on classification task with allennlp.
I try to find up-to-date complete examples to learn this library.
Getting started and provided tutorials are great to help me understand the workflow but more advanced examples are needed.
Thank you!

**Comment by joelgrus** [comment]
as you can see in the README, that code is written for allennlp 0.5.1.  in order to use it, you'll need to use allennlp==0.5.1

at some point I will update it to work with the latest version of allennlp, but that's pretty low priority work.

**Comment by matt-gardner** [comment]
Also, @tingkai-zhang, if you're writing code for more recent versions of allennlp, you can just remove the entire `from_params` method.  Other things might also break in that particular code, but at least these days you don't have to think about writing your own `from_params`.

**Comment by tingkai-zhang** [comment]
Thank you! Can you give me an example how to write a script.py to run the code not invoke from command using `allennlp train --include-package toxic baseline.json -s  /tmp`
(For debugging purpose: i can set breakpoint and debug in IDE)

**Comment by matt-gardner** [comment]
https://allennlp.org/tutorials

**Comment by tingkai-zhang** [comment]
Hi, thanks for replying! I have another question. Don't wanna bother you too much but I got stuck on this.

when i use bucket iterator with sorting key as `num_tokens` (as in the tutorial), i got this error:
`Keyerror: 'num_tokens'` 

Here is the line of the [code](https://github.com/tingkai-zhang/Generative-Pre-trained-Transformer/blob/b9004593975a03cdc537a4b896d32895eedbaf1c/main.py#L109)

I inspected the source code in Textfield, but still don't know how to solve this problem.
Any advice to solve this problem?

Here is whole project: [GPT for classification task with allennlp](https://github.com/tingkai-zhang/Generative-Pre-trained-Transformer)


Then i changed `BucketIterator `to `BasicIterator`. It gives me error:
```
raise ConfigurationError("You cannot construct a Batch with non-homogeneous Instances.")
allennlp.common.checks.ConfigurationError: 'You cannot construct a Batch with non-homogeneous Instances.'
```
I inspected the source code I find `_check_types() ` in dataset.py will check that all the instances have the same types. But all my instances are created by the same text_to_instance function. ([line of code](https://github.com/tingkai-zhang/Generative-Pre-trained-Transformer/blob/b9004593975a03cdc537a4b896d32895eedbaf1c/my_library/dataset_readers/NewsReader.py#L60))

I upload the data and instruction to let anyone run my code. 
Any help appreciated! Thank you!

**Comment by matt-gardner** [comment]
For your first problem: see the [API documentation](https://allenai.github.io/allennlp-docs/api/allennlp.data.iterators.html#bucket-iterator) for `BucketIterator`.  You need a `(field_name, padding_key)` pair as the sorting key.

For your second problem: this line is the problem: https://github.com/tingkai-zhang/Generative-Pre-trained-Transformer/blob/b9004593975a03cdc537a4b896d32895eedbaf1c/my_library/dataset_readers/NewsReader.py#L69.  `if label:` evaluates to `False` `if label == 0`.  You need `if label is not None:` instead of `if label:`.

**Comment by tingkai-zhang** [comment]
Thank you so much!

**Comment by tingkai-zhang** [comment]
Hi, I tracked the input and output of `text_field_embedder`, the token embedder of which is `OpenaiTransformerEmbedder` in my [model](https://github.com/tingkai-zhang/Generative-Pre-trained-Transformer).

First of all, I have read API document but i still didn't know what the `padding key` should be. I read the source code and find the key name [comes from](https://github.com/allenai/allennlp/blob/947bd16521dd31bc79f7499ec17a07acf15a89a1/allennlp/data/fields/text_field.py#L121) the keys of `indexer_lengths` , which come from `indexer.get_padding_lengths()`. While in `openai_transformer_byte_pair_indexer.py`, the `get_padding_lengths()` [returns {}](https://github.com/allenai/allennlp/blob/0b852fb2ef1000fa6209815d1c91171a9b093fef/allennlp/data/token_indexers/openai_transformer_byte_pair_indexer.py#L236)

I tried to set `(field_name, padding key)` as `(field_name, token_indexer_name)` , it runs without error but 
whichever the number i set the batch size to be in bucketiterator, [the forward input shape of text ](https://github.com/tingkai-zhang/Generative-Pre-trained-Transformer/blob/ec7f09d38367aef68d67219c7865e890f0f439aa/my_library/models/GPT.py#L53)is always [1, sentence_length] . 

2. No matter which iterator i use, [the sentence length of whole batch will shrink](https://github.com/tingkai-zhang/Generative-Pre-trained-Transformer/blob/ec7f09d38367aef68d67219c7865e890f0f439aa/my_library/models/GPT.py#L56) after being passed through the `text_field_embedder`. (for example, from 512 to 78)

3. The vocabulary is set in this way:
```
    vocab = Vocabulary()
    token_indexer._add_encoding_to_vocabulary(vocab)
    vocab.add_token_to_namespace( '_start_','openai_transformer')
    vocab.add_token_to_namespace('_classify_','openai_transformer')
```
The problem is, the first two indice have different tokens. for example, the original one is `1: '@@PADDING@@'` but the vocab loaded from file also has `1:'.'`  Is that a problem?
Also, when i use the above method to create vocabulary, the index of `_start_`  is at the end of vocab.
Because the [position encoding](https://github.com/allenai/allennlp/blob/7751799280c3169b4c0daeb73f5b2a12ad0670d1/allennlp/modules/token_embedders/openai_transformer_embedder.py#L67) in openai_transformer_embedder.py, requires vocab strictly follows `actual vocab + n_special + n_ctx`. And actual vocab is calculated by `vocab_size = self._transformer.vocab_size - self._transformer.n_ctx`

**Comment by matt-gardner** [comment]
The OpenAI stuff did some crazy things with the tokenization to handle byte pair encoding, and I'm not very familiar with how that works.  Maybe @joelgrus or @DeNeutoy know more than me?  Also, it's probably worth just opening a new issue with a more detailed version of this question, as we're pretty far off of the original topic (makes finding things easier for other people who have the same issue).

**Comment by tingkai-zhang** [comment]
> the openai token indexer pads everything to the same length
> 
> https://github.com/allenai/allennlp/blob/master/allennlp/data/token_indexers/openai_transformer_byte_pair_indexer.py#L220
> 
> so the bucket iterator isn't going to gain you anything here
> 
> I'm not sure why you're getting batch sizes of 1 in your output, I can't reproduce that in my test cases. Are you using the config that's in your repo?

Yes. I have read that line of code you provide. I was wondering the output shape doesn't match the input shape.

I am using config file but my repo has everything i have. You can download and run it.
