### ISSUE TITLE
what's the format of the input file for predict?

### ISSUE THREAD

**Issue by susht3** [allenai/allennlp#1985]
i use dev file as input file for predict, and run "allennlp predict",  but i get this error:
`son.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 1 (char 2)`
dev file is the same format as train file, is it can be read by datareader? whai is the input file format for prediction, do you have some tutorials to predict case?

**Comment by DeNeutoy** [comment]
If your dataset is in the same format as the training data, you need to use the `--use-dataset-reader` flag.

https://allenai.github.io/allennlp-docs/api/allennlp.commands.predict.html#module-allennlp.commands.predict

Otherwise the format it expects is `JSONL`.

**Comment by TheresaSchmidt** [comment]
But what should this JSONL look like?
