### ISSUE TITLE
datareader/reading_comprehension/util.py

### ISSUE THREAD

**Issue by susht3** [allenai/allennlp#1987]
allennlp/allennlp/data/dataset_readers/reading_comprehension/util.py
`def make_reading_comprehension_instance_quac   ---> f1`  
 `         def mark_tag(span_start, span_end, passage_tags, prev_answer_distance)   ---> f2`
function f1 transmits prev_answer_marker_lists to f2 as  passage_tags,  and then f2 makes tags for 'passage_tags', but it don't return passage_tags to f1 , so i think prev_answer_marker_lists has no change, is it a bug?

**Comment by DeNeutoy** [comment]
@eunsol can you take a look please?

**Comment by eunsol** [comment]
Hi!

The list is being modified, as it is passed by reference not by value.
Please take a look at this.
https://www.python-course.eu/passing_arguments.php
You can print them out if you would like to verify these.

best,
Eunsol

**Comment by DeNeutoy** [comment]
Thanks @eunsol! Closing, as it looks like there's no issue.
