### ISSUE TITLE
Fix documentation in AllenNLP as a library (Part 2)

### ISSUE THREAD

**Issue by titipata** [allenai/allennlp#1988]
The documentation for [Using AllenNLP as a Library (Part 2)](https://github.com/allenai/allennlp/blob/master/tutorials/getting_started/predicting_paper_venues/predicting_paper_venues_pt2.md) is not quite synced with the [allennlp-as-a-library-example](https://github.com/allenai/allennlp-as-a-library-example)

- First, only `instance` is needed in the predictor [here](https://github.com/allenai/allennlp-as-a-library-example/blob/master/my_library/predictors/paper_classifier_predictor.py#L18-L23). If we return `return instance, {'all_labels': all_labels}` as suggested in the documentation, this will return an error because the input is tuple.

- This issue will lead to the later demo error in:
```
python -m allennlp.service.server_simple \
    --archive-path tests/fixtures/model.tar.gz \
    --predictor paper-classifier \
    --include-package my_library \
    --static-dir static_html
```
because `labels: response['all_labels']` will not have the key `'all_labels'`

**Comment by schmmd** [comment]
@titipata does this look like the right fix? https://github.com/allenai/allennlp/pull/1990

**Comment by titipata** [comment]
@schmmd, so the demo with the pie chart still does not work since `response['all_labels']` (in [here](https://github.com/allenai/allennlp-as-a-library-example/blob/master/static_html/index.html#L70)) is an empty list instead. Is there a way to pass `all_labels` to the output?

**Comment by titipata** [comment]
There are roughly 2-3 lines in the documentation to be minor fixed e.g. 

```
Here that's just the list of all_labels, so that's what we put in the dict. If we didn't need that, we'd just use an empty dict there.
```
(the variable `all_labels` is not used)

```
When you run this it will print the ten test inputs and their predictions, each of which looks like:
prediction:  {"all_labels": ["AI", "ACL", "ML"], ...
```
(actually, no `all_labels` in the output)
