### ISSUE TITLE
is it possible to build a 'Machine Comprehension' model in danish or any other language ?

### ISSUE THREAD

**Issue by devajith** [allenai/allennlp#2007]
i was exploring this 'Machine Comprehension' capability of allennlp. In english it works pretty fine. How can we make it work for other languages like Danish or French ?

**Comment by DeNeutoy** [comment]
You'd need to collect a large dataset of questions and answers in order to train the bidaf model.

**Comment by devajith** [comment]
you mean questions and answers in the for format as below  : 
`"train_data_path": "https://s3-us-west-2.amazonaws.com/allennlp/datasets/squad/squad-train-v1.1.json"` 

Do i need Glove too in different : 

`"pretrained_file": "https://s3-us-west-2.amazonaws.com/allennlp/datasets/glove/glove.6B.100d.txt.gz",`
