### ISSUE TITLE
what is the format of test set of quac?

### ISSUE THREAD

**Issue by susht3** [allenai/allennlp#2011]
[Once you have a built a model that works to your expectations on the dev set, you submit it to get official scores on the dev and a hidden test set. To preserve the integrity of test results, we do not release the test set to the public. Instead, we require you to submit your model so that we can run it on the test set for you. The submission process is very similar to SQuaD 2.0 (coming soon)]

i want to submit to the leaderboard, but i don't know the format of the test set, is it the same with the dev set? on dev set, we can use the history gold answer for the current question, does the test set can provide gold history answer? or use the answer predicted by ourself?

**Comment by schmmd** [comment]
@susht3 although I would guess the format is the same as the dev set, I think your question is better suited to the QUAC team.

https://quac.ai/

It looks like they have a mailing list for questions.

![image](https://user-images.githubusercontent.com/954798/48019282-ec389b00-e0e7-11e8-906c-b32359a8d3c3.png)
