### ISSUE TITLE
Making nn.beam_search.BeamSearch registrable in the future?

### ISSUE THREAD

**Issue by epwalsh** [allenai/allennlp#2022]
I think there's a lot of ways we could build on and improve `nn.beam_search.BeamSearch`, such as adding standard penalties and length normalization. At at some point it might make sense to have this beam search be registrable, especially if we allow custom penalties / normalization metrics. But obviously that would create a naming conflict with the beam search for state machine transition functions. Does anyone have any thoughts on this?

**Comment by matt-gardner** [comment]
I would lean towards a single `BeamSearch` class until it's super obvious that we need more than one.  I'm guessing we can go pretty far with just adding parameters, or allowing for functions to be passed in.

**Comment by epwalsh** [comment]
Gotcha, yea I can’t think of any particular reason why making subclasses would be a better approach, I was just thinking off of some other implications I’ve seen, such as the one in OpenNMT-py.
