### ISSUE TITLE
ELMo for Portuguese Language

### ISSUE THREAD

**Issue by pvcastro** [allenai/allennlp#2025]
Hi there,

My team did the pre-training of the biLM and produced a model for Portuguese Language, based on Wikipedia. We already got a new SOTA for NER (selective scenario of the HAREM dataset), improving by a great margin. Do you have some sort of procedure to host the weights for other languages? We'd love to contribute with our model.

Thanks!

**Comment by matt-gardner** [comment]
Yes, we'd love to host this!  Thanks for the contribution!  @schmmd, where do you think this goes?  Surely we just host the appropriate files on S3 alongside the English ELMo.  Do we put a link to them here: https://github.com/allenai/allennlp/blob/master/MODELS.md?  Or somewhere else?

**Comment by schmmd** [comment]
@pvcastro please send us your model and we can host it.  Either we can download it from an HTTP address or you can share it via something like Google Drive.  My email address is michaels@allenai.org.

@pvcastro just curious--is there an accompanying publication?

@matt-gardner it should certainly go in MODELS.md and probably also on https://allennlp.org/elmo.  If there's an associated publication we can also add it to our gallery.  I planned to consolidate this information this quarter--but I've pushed that out a bit since we've had less time with Aaron.

**Comment by pvcastro** [comment]
> @pvcastro please send us your model and we can host it. Either we can download it from an HTTP address or you can share it via something like Google Drive. My email address is michaels@allenai.org.

OK, I sent you an e-mail requesting for a Google Drive!
> @pvcastro just curious--is there an accompanying publication?

Not yet, I'm planning to write a survey for Portuguese NER soon, as it's part of my Masters. But I already can say that we reached SOTA for Portuguese NER using our ELMo embeddings and the allennlp ner training, increasing the previous score from 76.2% to 81.5%.

**Comment by schmmd** [comment]
@pvcastro best luck and please send us your publication when it's ready!

**Comment by pvcastro** [comment]
Thanks @schmmd !

**Comment by matt-gardner** [comment]
@pvcastro FYI: https://github.com/allenai/allennlp-website/pull/105

**Comment by DeNeutoy** [comment]
Looks done, thanks for the model!

**Comment by underscrew** [comment]
Hello everyone!

Is there any tutorial guide of the usage of those pretrained models?
How can I get it to work inside keras?

**Comment by matt-gardner** [comment]
@underscrew, keras is built on top of tensorflow; allennlp is built on top of pytorch.  You won't be able to use allennlp code with keras.  There is a version of elmo on tensorflow hub, but we didn't build that and don't know much about it.

**Comment by underscrew** [comment]
@matt-gardner oh, just now i've realized that he meant that this is a model for biLM (i thought it was biLM-tf, i've read it fast), sorry for the confusion.
Yeah, i've checked the tensorflow-hub elmo version, it works great(i've tested it), but it's for english language. I wanna use the portuguese pre-trained weights, so i'll have to learn how it works and how to use pytorch first.
Thanks!

**Comment by pvcastro** [comment]
Hi @underscrew . The portuguese pre-trained version was indeed trained from the bilm-tf model. Can't say how it works with keras, since I've only used it in allennlp and flair so far, which are both based on pytorch.

**Comment by underscrew** [comment]
@pvcastro, do you have any available example with a Portuguese dataset? 
And thanks a lot for the letting this model available for the community!

**Comment by pvcastro** [comment]
> @pvcastro, do you have any available example with a Portuguese dataset?

So far I have only used it for Named Entity Recognition public datasets, such as HAREM, WikiNER and LeNER-Br. With allennlp it's not necessary to write any code, it's just a matter of setting up a training config json and running the train command. There is a training configuration example for NER task with ELMo [here](https://github.com/allenai/allennlp/blob/master/training_config/ner_elmo.jsonnet)

> And thanks a lot for the letting this model available for the community!

Sure!
