### ISSUE TITLE
pytorch ELMo on gpu

### ISSUE THREAD

**Issue by Anierin** [allenai/allennlp#2026]
hello, i want to try ELMo but it's too slow on cpu and i can't make it work on gpu.

The following code work (as device is cpu) but it's slow.
and if i change the device for "cuda" i got an error : 
"Expected object of type torch.cuda.LongTensor but found type torch.LongTensor"
despite `character_ids` being on gpu.

What is the probleme in my code?
How use ELMo on gpu?

```
from allennlp.modules.elmo import Elmo, batch_to_ids

options_file = "https://s3-us-west-2.amazonaws.com/allennlp/models/elmo/2x4096_512_2048cnn_2xhighway/elmo_2x4096_512_2048cnn_2xhighway_options.json"
weight_file = "https://s3-us-west-2.amazonaws.com/allennlp/models/elmo/2x4096_512_2048cnn_2xhighway/elmo_2x4096_512_2048cnn_2xhighway_weights.hdf5"

elmo = Elmo(options_file, weight_file, 2, dropout=0)


dummy_sentence = ['dummy' for i in range(100)]
train_sentences = [dummy_sentence for i in range(100)]

character_ids = batch_to_ids(train_sentences)

import torch
device = torch.device('cpu')
# device = torch.device('cuda:0')

character_ids.to(device)
elmo.to(device)
    
embeddings = elmo(character_ids)

print(embeddings)
```

**Comment by joelgrus** [comment]
is `Tensor.to` an inplace operation? I thought it wasn't.

Try

```
character_ids = character_ids.to(device)
```

?

**Comment by Anierin** [comment]
I do think it's an inplace operation (maybe it's a change of the lasts pytorch version).

Anyway changing the code with 
`character_ids = character_ids.to(device)`
(and `elmo = elmo.to(device)` )
does not affect the result.

**Comment by matt-gardner** [comment]
It's not in place: https://pytorch.org/docs/stable/tensors.html#torch.Tensor.to

What's the full stack trade when you do the non-in-place version?

**Comment by Anierin** [comment]
Well, my code now works on gpu.

Apparently, I did not use/test the `.to(device)` function properly

Thank for your help.

**Comment by woyijkl1** [comment]
so, how can i use elmo on gpu, and I have the same problem when run:
sentences = [['First', 'sentence', 'first','second'], ['Another', '.']]
character_ids = batch_to_ids(sentences)
character_ids = character_ids.cuda(3)
elmo = elmo.cuda(3)
embedding = elmo(character_ids)

RuntimeError: Expected object of type torch.LongTensor but found type torch.cuda.LongTensor for argument #3 'index'

**Comment by xiaoxiaoAurora** [comment]
> so, how can i use elmo on gpu, and I have the same problem when run:
> sentences = [['First', 'sentence', 'first','second'], ['Another', '.']]
> character_ids = batch_to_ids(sentences)
> character_ids = character_ids.cuda(3)
> elmo = elmo.cuda(3)
> embedding = elmo(character_ids)
> 
> RuntimeError: Expected object of type torch.LongTensor but found type torch.cuda.LongTensor for argument #3 'index'

Hi, have you solved ?

**Comment by mamamot** [comment]
I also have the same issue with 0.8.3.
