### ISSUE TITLE
How to compute F1 score on CoQA?

### ISSUE THREAD

**Issue by SparkJiao** [allenai/allennlp#2031]
**Describe the bug**
The answer part in CoQA has two domain names "input text" and "span text" and I have modified the reader of dialog_qa.py to read in CoQA with no num_context = 0. The score is 60.85 while using span_text to compute thr F1 score and it's 47.58 while using input_text, btw, for the answers for yes/no questions I  set them as span_text. So I then modified the span start and span end as the start and end of the input text when the it is a substring of span text  and the score is 58.88.
I have used your config so I wanna ask the author how do you compute the f1 score to realize the performance in your paper? [https://arxiv.org/pdf/1809.10735.pdf](https://arxiv.org/pdf/1809.10735.pdf)

**Additional context**
If you need the details of the implementation just let me know although I just comment the parts of num context and following up list.

**Comment by SparkJiao** [comment]
Btw, I have also modified the bidaf.py to read the CoQA and have a f1 score of 62.22 which i think is close to the performance mentionen in your paper. I have used GloVe in the dialog_qa but I think it does matter?

**Comment by matt-gardner** [comment]
@my89 was the one who wrote that paper; he's the right person to ask those questions.
