### ISSUE TITLE
how to set max length in data loader?

### ISSUE THREAD

**Issue by OleNet** [allenai/allennlp#2033]

**Comment by matt-gardner** [comment]
This is typically dataset-specific.  Can you ask a more specific question?

**Comment by OleNet** [comment]
I want to do a sentiment classification task,
the length of sentence vary from 400 to 1400+.
I want to set the max length to 1200, like this [project](https://github.com/pengshuang/AI-Comp/blob/master/model_bigru_char.py#L61).

**Comment by joelgrus** [comment]
when you use allennlp you will typically write a DatasetReader that converts your inputs file[s] into Instances. for example:

https://github.com/allenai/allennlp/blob/master/tutorials/getting_started/predicting_paper_venues/predicting_paper_venues_pt1.md#step-three-write-your-datasetreader

the typical way to accomplish what you want would be to give that class a `max_sentence_length` parameter, and then when you encounter a sentence above that length either truncate it or skip it (depending on what you want to happen).

**Comment by OleNet** [comment]
ok got it , Thanks!
