### ISSUE TITLE
Pretrained embeddings for a sentence.

### ISSUE THREAD

**Issue by rangwani-harsh** [allenai/allennlp#2034]
Hi team,
I am trying to use pre-trained sentence embeddings generated in form of numpy arrays by this project in my model https://github.com/bfelbo/DeepMoji. But at present I could not find any tutorial or example of doing that in allennlp. Can someone please help me with this?

Thanks

**Comment by rangwani-harsh** [comment]
Hi Matt,
The problem that I face here is I need to read two files for the complete dataset. One is my .csv file and the other is a .npy file containing weights. Whereas the read function of the dataset reader only takes a file_path as an input. So the only option I have is to make changes in implementation i.e. python to hardcode the path in the read function. (Which I feel is not the allennlp way of doing things).

As an end result, I need two fields in my instance one is the normal field and the other is the array field.

I also think that the use of pretrained sentence embeddings is also prevalent in NLP and it would be great to see allennlp support them in future. 

Thanks

**Comment by matt-gardner** [comment]
If the `.npy` file is parallel to the `.csv` file, you could just take one filename and read both.

You only need two fields if you want more than just sentence embeddings.  If you are a bit more specific in what you're trying to do, we could help you better.

**Comment by matt-gardner** [comment]
Yeah, we don't have a good way of passing more than one file to the dataset reader, unfortunately, unless you make assumptions about the structure of some directory.

Technically, I don't think any actually enforces that the path you give for the dataset is a single string...  If you really want, you could probably pass in a list in your config file and have your dataset reader treat `file_path` as a list.  That would probably work.

**Comment by rangwani-harsh** [comment]
I also want to know that is allennlp team trying to build a way to use pre-trained sentence representations like https://tfhub.dev/google/universal-sentence-encoder-large/3 in future?

**Comment by rangwani-harsh** [comment]
Thanks, Matt.

**Comment by matt-gardner** [comment]
I'm personally very skeptical of a "universal sentence encoder" being a useful concept. No-one on our team is currently working on this.

But, if someone has a nice, clean implementation of some sentence encoder, with a pre-trained model that's useful for something, we'd consider accepting a PR and hosting the model.

**Comment by rangwani-harsh** [comment]
Actually, I was thinking of something like a DeepMoji (https://github.com/bfelbo/DeepMoji) which can be used on a variety of tweet related tasks. As it captures the sentiment information and can be used on various tasks like sarcasm, irony, sentiment etc. And these tasks are often part of SemEval etc. which are often how people often start research. So it would be a great way to attract young people to use allennlp at first place. Just a thought although!

**Comment by rangwani-harsh** [comment]
Hi team,
The issue with using the path as a list of string here makes the ```allennlp evaluate``` command unusable. 

Wouldn't it be better if we also allow the allennlp evaluate to take input_path as an optional argument. If the input_path isn't passed as an argument we could possibly use the test_data_path entry in the config as the default dataset for evaluation of the model?

Thanks

**Comment by DeNeutoy** [comment]
The path can be to a directory, where you expect things to have certain names.
