### ISSUE TITLE
TestCustomHighwayLSTM reporting failure from "allennlp test-install"

### ISSUE THREAD

**Issue by shafei** [allenai/allennlp#2039]
**Describe the bug**

"allennlp test-install" reports 3 failures, which are all from TestcustomHighwayLSTM. In all cases, the error messages are: 

 _TypeError: initializer for ctype 'struct THIntTensor *' must be a pointer to same type, not cdata 'struct THLongTensor *_

**System (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Python version: 3.7.1
 - AllenNLP version: 0.7.1
 - PyTorch version: 0.4.1

**Additional context**
The installation was performed as follows:
1) conda create --name mynlp python=3.7
2) conda install pytorch torchvision -c pytorch
3) pip install allennlp
(Between Step 2 and 3, I had to install libcffi-dev).

The following installation:  
1) conda create --name anothernlp python=3.7
2) conda install allennlp -c pytorch -c conda-forge
yields similar errors in CustomHighwayLSTM (by assertion error) -- though the installation requires downgrading to pytorch 0.4.0 as well as installing AllenNLP 0.5.1

**Comment by DeNeutoy** [comment]
This is actually expected, sorry. We should remove this code and tests. Closing in favour of #1456
