### ISSUE TITLE
Dialog QA model fails when only one question supplied in input

### ISSUE THREAD

**Issue by martiansideofthemoon** [allenai/allennlp#2040]
**Describe the bug**
I am running the dialog QA model for QuAC and I've noticed an error when I supply just one question as input. More specifically, I get the following `IndexError` -

```
    outputs = self.decode(self(**model_input))
  File "/kalpesh/venvs/seq2seq-venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/kalpesh/venvs/seq2seq-venv/lib/python3.6/site-packages/allennlp/models/reading_comprehension/dialog_qa.py", line 333, in forward
    gold_span_end_loc.append(max(span_end[i] * 3 + i * passage_length * 3, 0))
IndexError: too many indices for array
```
**To Reproduce**
1. Train a dialog QA model
2. Use the following input file with the `allennlp predict` command -

```
{"paragraphs": [{"qas": [{"followup": "y", "yesno": "x", "question": "When was the first one?","answers": [{"answer_start": 0, "text": "One time"}], "id": "C_q#0"}],"context": "One time I was writing a unit test, and it succeeded on the first attempt."}]}
```

**Expected behavior**
No error, we get a single answer span in the predicted JSON

**System (please complete the following information):**
 - OS: Linux
 - Python version: 3.6.6
 - AllenNLP version: 0.7.1
 - PyTorch version: 0.4.1

**Additional context**
Also, @eunsol @matt-gardner it would be great to have a setting where the API didn't require you to supply the answers to the questions and the followup / yes-no information. I understand that this task requires context, but the model could potentially be used for a single Q/A setting or a setting where the answers *predicted* by the model are used as context for subsequent questions.

**Comment by matt-gardner** [comment]
Closing this issue as wontfix, but if someone wants to contribute, it'd be welcome.
