### ISSUE TITLE
can not find vocabulary/token.txt for dialog_qa

### ISSUE THREAD

**Issue by susht3** [allenai/allennlp#2048]
i run dialogQA for quac dataset, i find that vocabulary has no token.txt，(i remove min_padding_length)

and i change the dataset to coqa, get the index error,  like this:
/pytorch/aten/src/THC/THCTensorIndex.cu:362: void indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2, IndexIsMajor = true]: block: [22,0,0], thread: [127,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

i think it maybe the problem of vocabulary.

**Comment by DeNeutoy** [comment]
That seems likely. In general it's hard for us to help you if you post such limited information for code that is not inside the library. If you are more descriptive, e.g including where you think things went wrong, or what you expect to happen etc, we can probably give better advice 😄
