### ISSUE TITLE
Move the call to `model.cuda()` to before optimizer creation

### ISSUE THREAD

**Issue by matt-gardner** [allenai/allennlp#205]
Because of [this issue](https://github.com/pytorch/pytorch/issues/2021#issuecomment-325204922).  The optimizer might have state that's initialized from the model parameters, and needs to be on the right device.

This means we should either:
1. Have `cuda_device` be a top-level key in the experiment config, so we can move the model over in `commands.train()` before constructing the optimizer.
2. Move the optimizer creation and the call to `model.cuda()` into `Trainer.from_params()`.

I could go either way.  Calling `model.cuda()` inside of `from_params()` in the second option is a little bit more logic than we like to have in those methods, but not much.  The optimizer conceptually seems like it's part of the trainer, so having the optimizer params inside of the trainer params makes sense.

**Comment by joelgrus** [comment]
when I was working on the "deep dive into the config" tutorial, I found it surprising that the optimizer wasn't part of the trainer params, FWIW
