### ISSUE TITLE
Add AllenNLP to kaggle kernel

### ISSUE THREAD

**Issue by benqua** [allenai/allennlp#2051]
**Is your feature request related to a problem? Please describe.**
[Kaggle](https://www.kaggle.com) is a well known web site hosting data science (and NLP) competition.
It is a great place to learn and experiment.

Part of the competition are based on their "Kaggle kernels", which are docker images that run on Kaggle infrastructure. While pytorch is installed in the python kaggle kernel image (as well as other libraries built on top of pytorch, like fast.ai), allenlnp is not.

It would be great to be able to use allennlp in kaggle python kernel. 
It would make it easy to experiment with the library, share the experiments and give visibility to the library. 

**Describe the solution you'd like**
Add AllenNLP to the python kaggle docker image:
https://github.com/Kaggle/docker-python
It is open source and they welcome pull requests.

**Additional context**
I know this feature request is not directly linked to the allenai/allennlp repository but I think it would benefit the allennlp community and the allennlp contributors are the ones who can make it happen.
(I gave it a quick try and it wasn't as easy as just adding pip install allennlp to the Dockerfile...)

**Comment by matt-gardner** [comment]
What were the problems you ran into when trying to just add the pip install?

**Comment by benqua** [comment]
After running `pip install allennlp`, I get an error while compiling jsonnet:

```
Building wheels for collected packages: jsonnet, overrides, parsimonious, jsondiff
  Running setup.py bdist_wheel for jsonnet ... error
  Complete output from command /opt/conda/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-ay1b7onk/jsonnet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-hivc6bwu --python-tag cp36:
  running bdist_wheel
  running build
  running build_ext
  /opt/conda/bin/x86_64-conda_cos6-linux-gnu-c++ -c -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe core/desugarer.cpp -o core/desugarer.o
  In file included from core/desugarer.h:24:0,
                   from core/desugarer.cpp:20:
  core/vm.h:20:10: fatal error: libjsonnet.h: No such file or directory
   #include <libjsonnet.h>
```

To reproduce, just run 
```
docker run --rm -it gcr.io/kaggle-images/python
```
and then
```
pip install allennlp
```

**Comment by DeNeutoy** [comment]
Thanks for the idea - looking at this Dockerfile I don't think it's practical to add AllenNLP there.
