### ISSUE TITLE
Add option to support model.load_state_dict(model_state, strict=False) in `evaluate` & `predict`.

### ISSUE THREAD

**Issue by huntzhan** [allenai/allennlp#2054]
**Is your feature request related to a problem? Please describe.**

I'd like to train a new model on top of the ELMo and **save only the trainable parameters** by overriding the [torch.nn.Module.state_dict](https://pytorch.org/docs/stable/nn.html#torch.nn.Module.state_dict) method, since the trainer now will save all the parameters returned by `state_dict`.

https://github.com/allenai/allennlp/blob/07b574912af3f6049f95851d0886c19c41e5d6ad/allennlp/training/trainer.py#L864

This should be fine for `allennlp train`, but will lead to an error during `allennlp evaluate` and `allennlp predict`, since the `_load` method calls [load_state_dict](https://pytorch.org/docs/stable/nn.html#torch.nn.Module.load_state_dict) with the default option `strict=True` and hence a `RuntimeError(... Missing key(s) in state_dict: ...)` should be raised.

https://github.com/allenai/allennlp/blob/9dbba33806a65e8a1fe7ab54e0683d7adcbedd99/allennlp/models/archival.py#L150-L153

https://github.com/allenai/allennlp/blob/07b574912af3f6049f95851d0886c19c41e5d6ad/allennlp/models/model.py#L268-L270

**Describe the solution you'd like**

I wonder if we could add an option to `allennlp evaluate` & `allennlp predict` to support `model.load_state_dict(model_state, strict=False)`?

**Describe alternatives you've considered**

N/A

**Additional context**

During initialization, [_ElmoCharacterEncoder(torch.nn.Module)](https://github.com/allenai/allennlp/blob/43243acf4e91ba471923624bd48c9c9ec72332bf/allennlp/modules/elmo.py#L257) and [ElmoLstm(_EncoderBase)](https://github.com/allenai/allennlp/blob/aa1b774ed8de31ec04bebf9f054200bc2507e0c5/allennlp/modules/elmo_lstm.py#L20) will load the `options_file` and `weight_file` no matter for training or testing. 

`options_file` and `weight_file` will be archived after training so removing those parameters from `weights.th` dump should be safe:

https://github.com/allenai/allennlp/blob/15e36458b1f6a7452492bd107cd631fede3617a8/allennlp/modules/token_embedders/elmo_token_embedder.py#L98-L99

```
.
├── config.json
├── files_to_archive.json
├── fta
│   ├── model.text_field_embedder.elmo.options_file
│   └── model.text_field_embedder.elmo.weight_file
├── vocabulary
│   ├── labels.txt
│   └── non_padded_namespaces.txt
└── weights.th
```

**Comment by matt-gardner** [comment]
This seems to me like a reasonable thing to do.  I'm not sure how to do this in a clean way without thinking about it a lot more, but if there's a way, go for it.  PRs welcome.

**Comment by huntzhan** [comment]
I could come up with two ideas:

1. Add an new parameter `disable_strict_load` to `load_archive`, `Model.load`, `Model._load`.
2. Add a new key to config and extract its value in `Model._load`.

Which one do you think is better?

Call stack:

`evaluate` & `predict`:
https://github.com/allenai/allennlp/blob/8867f2f3eeb6a0ea7677d59d8644e19681ecdf70/allennlp/commands/evaluate.py#L126

`load_archive`:
https://github.com/allenai/allennlp/blob/9dbba33806a65e8a1fe7ab54e0683d7adcbedd99/allennlp/models/archival.py#L150-L153

`Model.load`:
https://github.com/allenai/allennlp/blob/07b574912af3f6049f95851d0886c19c41e5d6ad/allennlp/models/model.py#L321

`Model._load`:
https://github.com/allenai/allennlp/blob/07b574912af3f6049f95851d0886c19c41e5d6ad/allennlp/models/model.py#L268-L270

**Comment by matt-gardner** [comment]
If all you need is to add `strict=False` to `model.load_state_dict()`, your first option seems like the right solution, and pretty straightforward.  A PR for that would be fine.

I was more worried about the model _saving_ piece of this - I'm not sure at all how to make the `Trainer` save only the right parts of the model in a way that's generally useful.  You definitely don't want to tell it to only save the trainable weights, because that's not the right thing to do all the time.

**Comment by huntzhan** [comment]
I believe something like this should work.

```python
    @overrides
    def state_dict(self, destination=None, prefix='', keep_vars=False):
        original = super().state_dict(destination, prefix, keep_vars)
        if not keep_vars:
            return original

        for key in list(original.keys()):
            param = original[key]
            if not param.requires_grad:
                original.pop(key)

        return original
```

**Comment by matt-gardner** [comment]
If you want to put that on your model and it works for you, great, go ahead.  This is not something that we can add upstream, though, as it's incredibly non-obvious and it's the wrong thing to do in a whole lot of cases (e.g., if you have fixed word embeddings; you don't want to throw away your embedding layer).

**Comment by huntzhan** [comment]
> This is not something that we can add upstream
Fully agree. I'm not intended to change `Trainer` at all. 
Will submit a PR to support `strict=False` later.

**Comment by matt-gardner** [comment]
I think the right solution here is to make it easier to customize / write your own training loop, where you can put in custom code to do whatever you want to your model (e.g., with callbacks).  I'm closing this issue.
