### ISSUE TITLE
pytorch,when i including Elmo into my model , then using nn.DataParallel(model).cuda() will report error

### ISSUE THREAD

**Issue by senkey705** [allenai/allennlp#2055]
Hi,
   i am new to allennlp，i want to use allennlp.modules.elmo encoding my sentence in my model which abort QA. my raw-model using glove initializing words of one sentence, then using lstm to encode it. The raw-model is running on multi-gpu well , and using like this way nn.DataParallel(model).cuda() and dataloader of pytorch. while i including Elmo into my model, and using it to get embeddings of one sentence which is included in a batch of dataset ,it will report the error as below:
 "return torch._C._broadcast_coalesced(tensors, devices, buffer_size) RuntimeError: NCCL Error 1: unhandled cuda error"  
But when i replace the script  "model=nn.DataParallel(model).cuda()" with "model=model.cuda()"，the new-model is running ok with single gpu.  what should i do? or if the way i using elmo in my model is error? please giving me some guidance and advances, thanks vary much!

**Comment by schmmd** [comment]
@senkey705 can you provide a full code example that causes the error you ran into?  That would help us troubleshoot this further.

**Comment by senkey705** [comment]
Thanks for your response. i including elmo-module  into  my model(a QA model) and use it to encode question, then i can but using the line2 follow to ran model on one gpu . while using the line2 follow , it raised error: "return torch._C._broadcast_coalesced(tensors, devices, buffer_size) RuntimeError: NCCL Error 1: unhandled cuda error"
   [1] #model = nn.DataParallel(model).cuda()
   [2] model=model.cuda()

The way to encode question as follow:
[1] elmo_model=Elmo(options_file, weight_file, num_output_representations, dropout, requires_grad , do_layer_norm).cuda()
[2] ids = batch_to_ids(x).cuda()
[3] out=self.elmo_model(ids)

where x is a batch of question data from train_dataloader (a subclass of torch.utils.data.Dataset)。

**Comment by matt-gardner** [comment]
We unfortunately don't have the bandwidth to dig into problems using pytorch dataloaders with our pipelines.  Closing as wontfix and inactive.
