### ISSUE TITLE
id unavailable in predict output of BiDAF (for SQuAD)

### ISSUE THREAD

**Issue by valsworthen** [allenai/allennlp#2056]
Hello,

I am trying to make predictions on SQuAD using the implemented BiDAF model. I have successfully retrained it and the `predict` command works fine 

`allennlp predict [...]/bidaf_squad_cli/model.tar.gz [...]/sample.json --cuda-device 5 --use-dataset-reader --output-file [...]/sample_out.json`

(I am using a sample of the dev set but the format is correct)

However, I'm wondering why the output file does not contain the id linking the answer to the question. I think this would be more convenient - especially in this case where the evaluation requires a format `{'id': ..., 'answer': ...}` but also in general.

Are you planning on making such feature available or do you recommend that I modify the way the predictor works for each case? Or is there something I uncorrectly understood.

Thank you for your answer and the great work in the library!

**Comment by matt-gardner** [comment]
We used to return the ID (it's still mentioned in the [class docstring](https://github.com/allenai/allennlp/blob/07b574912af3f6049f95851d0886c19c41e5d6ad/allennlp/data/dataset_readers/reading_comprehension/squad.py#L23-L24)), but we stopped when we moved to calling the official evaluation script ourselves inside the training loop.  If you want to produce a file for use on CodaLab or something, though, yeah, you'll want this.

You'd need to modify the dataset reader (or the predictor, depending on how you're calling things) to pass along the question ID in the `metadata` field when it's present, and you need to modify the model to pass it through at the end of [`forward`](https://github.com/allenai/allennlp/blob/07b574912af3f6049f95851d0886c19c41e5d6ad/allennlp/models/reading_comprehension/bidaf.py#L286-L287)
