### ISSUE TITLE
Skip W_P_0 weight if LSTM dim is equal to LSTM projection dim

### ISSUE THREAD

**Issue by tkon3** [allenai/allennlp#2062]
Hello,

When training a new corpus with the bilm-tf model (https://github.com/allenai/bilm-tf), if lstm dim and projection_dim are set to the same number during training (https://github.com/allenai/bilm-tf/blob/master/bin/train_elmo.py), the weigth associated isn't returned as there is no projection needed. 
The model is then impossible to load using allennlp.modules.elmo.Elmo because W_P_0 doesn't exist in the HDF5 file.

The idea is to simply skip that weigth if the rest has been loaded properly.

Have a nice day.

**Comment by schmmd** [comment]
@matt-peters any thoughts here?

**Comment by matt-peters** [comment]
Good idea, PRs welcome.

**Comment by matt-gardner** [comment]
Closing as stale and largely now irrelevant.
