### ISSUE TITLE
Unable to override _map_name in world.py

### ISSUE THREAD

**Issue by nitishgupta** [allenai/allennlp#2065]
I'm writing my own world class with instance-specific actions. For that I'm trying to override the ```self._map_name``` class in ```world.py```. 

When I call the self-implemented ```self._map_name``` it doesn't get called. I wrote a print statement right inside the function and it doesn't get printed. If I rename the function to something else and call it in the same way, things seem to work and things do get added to the ```world.local_name_mapping``` and ```world.local_type_signatures```. I think this shows that there is some issue with inheritance and overloading I'm not able to pin-point.

Any idea/suggestions for why this could be happening.

**Comment by matt-gardner** [comment]
Can you give some more context?  Like, a link to code in a repo, or a snippet of your code pasted here?

**Comment by nitishgupta** [comment]
```
class SampleHotpotWorld(World):
  def __init__(self, ques_spans: List[str]=None) -> None:
        super(SampleHotpotWorld, self).__init__(global_type_signatures=types.COMMON_TYPE_SIGNATURE,
                                                global_name_mapping=types.COMMON_NAME_MAPPING,
                                                num_nested_lambdas=0)
        """
        Parameters:
        -----------
        ques_spans: List of question spans (tokens delimited by _) to be used as actions
        """

        if ques_spans is not None:
            for ques_str in ques_spans:
                ques_str = f"qstr:{ques_str}"
                print(ques_str)
                self._map_name(name=ques_str, keep_mapping=True)
                print("finished")


        print(self.get_name_mapping())
        print(self.get_type_signatures())

        print(self.all_possible_actions())

        sys.exit()

  @overrides
  def _map_name(self, name: str, keep_mapping: bool = False) -> str:
        print(name)
        if name not in types.COMMON_NAME_MAPPING and name not in self.local_name_mapping:
            if not keep_mapping:
                raise ParsingError(f"Encountered un-mapped name: {name}")
            print(name)
            if name.startswith("qstr:"):
                # Question sub-span
                print("HERE")
                translated_name = "Q:" + name
                self._add_name_mapping(name, translated_name, types.QSTR_TYPE)
            else:
                raise ParsingError(f"Cannot handle Names apart from qstr:ques_tokens. Input: {name}")
        else:
            if name in types.COMMON_NAME_MAPPING:
                translated_name = types.COMMON_NAME_MAPPING[name]
            else:
                translated_name = self.local_name_mapping[name]
        return translated_name
```


Here in the `for` loop for `ques_spans`, the `print(ques_str)` would run, and then the `print("finished")` and nothing in between gets printed. `self.get_name_mapping()` also suggests that `_map_name` didn't run.

**Comment by matt-gardner** [comment]
You're printing the same thing in the for loop as you are inside the method (because `name==quest_str`).  Are you sure it's not actually running?

**Comment by nitishgupta** [comment]
Yes, I'm sure. If I change the name of the function `_map_name` to something else that doesn't override an existing function, it runs.

**Comment by matt-gardner** [comment]
This is pretty bizarre, and I can't think of any good explanation for what's going on.

**Comment by nitishgupta** [comment]
The world class is here: https://github.com/nitishgupta/mhqa/blob/master/semqa/worlds/hotpotqa/sample_world.py

You can run it from the following command:
```python -m test.test_sample_world```

**Comment by nitishgupta** [comment]
Found the bug. Sorry for wasting your time. Once I looked at my code in github, I had a duplicate implementation of the same function at the end of the class. My IDE didn't complain as well.

**Comment by matt-gardner** [comment]
Glad you found it =).
