### ISSUE TITLE
QUAC training model error / dialog_qa.jsonnet configuration file

### ISSUE THREAD

**Issue by hinnawe** [allenai/allennlp#2068]
**Question**

I'm getting an error when running the below command line to train the model using dialog_qa.jsonnet:

training command:
------------------------------
python -m allennlp.run train https://github.com/allenai/allennlp/blob/master/training_config/dialog_qa.jsonnet --serialization-dir C:\Users\user\Desktop\tmp\tutorials\getting_started

**error**

File "C:\allennlp\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 7 column 1 (char 6)
[INFO/MainProcess] process shutting down

I'm training the data on my laptop and i don't have GPU. I haven't changed anything in the configuration file.

What could be the problem, and what would be the solution?

Regards,
 - OS: [windows]
 - Python version: [3.6.6, 3.6.7]
 - AllenNLP version: [v0.7.1]
 - PyTorch version: (0.4.1)

**Comment by DeNeutoy** [comment]
Hi, sorry we don't currently support windows. See #612
