### ISSUE TITLE
when can we use QANet?

### ISSUE THREAD

**Issue by susht3** [allenai/allennlp#2069]
hi, you said that you are working on qanet, it is g quiet good news, when can we use it?

**Comment by DeNeutoy** [comment]
We aren't working on that, sorry.

**Comment by matt-gardner** [comment]
We _do_ have an AllenNLP implementation of QANet outside of the main repo right now, but I can't promise anything about when it will be merged into the main repo.  Possibly mid-December, maybe January, maybe later.
