### ISSUE TITLE
How to get the output from MML parser on Wikitables

### ISSUE THREAD

**Issue by YoPatapon** [allenai/allennlp#2070]
**System (please complete the following information):**
 - OS: Linux
 - Python version: 3.6.1
 - AllenNLP version: I installed from master
 - PyTorch version: 0.4.1

**Question**
I am trying to get the failed cases of the mml parser on wikitables dataset. However, I found there is no default predicator supported now. But I noticed there is a wikitales predicator implemented in the source code of master branch. How can I get the denotation outputs of the parser for now?

**Comment by matt-gardner** [comment]
Looks like it needs to be added here: https://github.com/allenai/allennlp/blob/2a2d9c94f875d7775f4cf63fec63017d8199473d/allennlp/predictors/predictor.py#L12-L27

Care to submit a PR?

**Comment by YoPatapon** [comment]
Ok, I've submitted a PR.
