### ISSUE TITLE
how to run an ensemble model?

### ISSUE THREAD

**Issue by susht3** [allenai/allennlp#2074]
allennlp provides bidaf-ensemble, but no its config json, now i wirte my own ensemble code, but i donnt know how to run it

**Comment by DeNeutoy** [comment]
Please read the code or docs to see how the ensemble code works, or be more specific about what you don't understand. Thanks!

**Comment by DreamerDeo** [comment]
@susht3 Hi, I have met the same problem. 
Do you have a solution for this? Should I run this ensemble model by `predict` command?
Thanks in advance。

**Comment by DreamerDeo** [comment]
Hi, I have success running ensemble model. 

1. Make a new directory  for ensemble model, which consists of only one `config.json`.
2.`config.json` should specify dataset_reader,iterator, model. The model should specify submodels via Dict.
3. Run `predict` command and set the archive file path be the directory in step 1.
