### ISSUE TITLE
Seq2Vec for all Seq2Seq

### ISSUE THREAD

**Issue by rangwani-harsh** [allenai/allennlp#2075]
**System (please complete the following information):**
 - OS: Ubuntu 18.0
 - Python version: 3.6
 - AllenNLP version: 0.7.1
 

**Question**
Hi team,
Is there a way we could probably use this https://github.com/allenai/allennlp/blob/master/allennlp/modules/seq2vec_encoders/pytorch_seq2vec_wrapper.py to generate a vector for all seq2seq encoders available in allennlp?

Thanks

**Comment by matt-gardner** [comment]
What's the motivation for this?  You can already use something like a bag of words encoder, or some other kind of pooling, on top of any seq2seq encoder.  I'm not sure what you're hoping to accomplish with what you're suggesting.

**Comment by rangwani-harsh** [comment]
As allennlp has implementations for stacked LSTM with highway etc. which in a way are similar to LSTM. I want to use them as a Seq2Vec encoder opposed to using them as a Seq2Seq Encoder. 
As this code does the same thing i.e. to generate a vector from the hidden state and the time distributed state and was implemented for the pytorch RNN and LSTM units. I thought it shouldn't be hard to modify and make the code worked for stacked versions too. 

There is a paper which uses this kind of seq2vec encoding  http://aclweb.org/anthology/S18-1006 and achieves good results.

**Comment by HarshTrivedi** [comment]
I am not sure if this is what you want but in case you are looking for a way to extract final hidden states of a `Seq2SeqEncoder` output, [this](https://github.com/allenai/allennlp/blob/master/allennlp/nn/util.py#L157) utility function is what you need.

**Comment by rangwani-harsh** [comment]
Thanks. This was what I was looking for. Although I do think that this information must be present on the seq2vec and seq2seq documentation page.

**Comment by HarshTrivedi** [comment]
Glad it helped ! If there was a`Seq2VecEncoder` with a name like `"final_state"` and logic same as [`get_final_encoder_states`](https://github.com/allenai/allennlp/blob/master/allennlp/nn/util.py#L157) it might have been easier to find.
