### ISSUE TITLE
How to get the results of sempre executor against the table?

### ISSUE THREAD

**Issue by YoPatapon** [allenai/allennlp#2078]
**System (please complete the following information):**
 - OS: Linux
 - Python version: 3.6.1
 - AllenNLP version: I installed from master
 - PyTorch version: 0.4.1

**Question**
I am trying to do some analysis on the failed cases of MML parser on the wikitables dataset. For this purpose, I may need the executed results of the generated logical form. I found the sempre executor only return whether the results match the ground truth or not. How can I get the exact values of the results?

**Comment by matt-gardner** [comment]
If you want to change how the executor works (e.g., to extract the information you want), you can do so here: https://github.com/allenai/wikitables-executor.  We build a jar from that repo that gets used in the executor here: https://github.com/allenai/allennlp/blob/193bb04ddae7d89ee63005b898a01641447d6074/allennlp/semparse/executors/wikitables_sempre_executor.py#L14.

**Comment by YoPatapon** [comment]
OK, I see. Thanks, Matt.
