### ISSUE TITLE
How do negative samples fit in the data_reader/instance framework

### ISSUE THREAD

**Issue by mpetri** [allenai/allennlp#2081]
**System (please complete the following information):**
 - OS: OSX
 - Python version: 3.6.1
 - AllenNLP version: I installed from master

**Question**

I'm trying to train a model which uses a MaxMarginLoss with a bunch of negative samples. However, it is not clear to me how I would create an Instance for one training example (containing one positive pair and X negative samples, for example in the context of knowledge base completion - TransE) where the negative samples are drawn randomly from all instances and are redrawn every epoch. I tried to search for a sample code base using AllenNLP that does something similar but couldn't find anything.

**Comment by matt-gardner** [comment]
One option for doing this is to have a lazy dataset reader that creates new negative samples at every epoch.  You can read the whole dataset into memory, if it fits, and just yield new `Instances` (with new negative samples) at every epoch from the in-memory list.  There is an example of how to do this [here](https://github.com/allenai/allennlp/pull/804/files#diff-132a8c20b381e35454b65fe53a986f7dR307) (though note that that code does a whole lot of other stuff and is quite complicated; much more than yours needs to be).

Another option is to only have a single positive example in each `Instance`, and use other instances in the batch as your negative examples.  By default the batches will change at least a little bit each epoch, so you should get new negatives each time.  This won't necessarily match the sampling strategy that you want, though, unless you do your own batching.

**Comment by mpetri** [comment]
I get it thanks. In my non-allennlp version I use something that is similar to the first approach.
