### ISSUE TITLE
bilm-tf or allennlp for finetuning the model?

### ISSUE THREAD

**Issue by sribharghava** [allenai/allennlp#2087]
**System**
 - OS: Linux
 - Python version:  3.6.1
 - AllenNLP version: "I installed from master"
 - PyTorch version: 1.0.0

**Question**
I see that there are 2 ways to finetune the ELMO language model, one via bilm-tf and the other through allennlp with this merge request https://github.com/allenai/allennlp/pull/1725 which is not yet accepted. 

I have a couple of questions here.

1. Is it possible to train the ELMO Language Model using allennlp instead of bilm-tf with the merge request that I pointed out?

2. If training through bilm-tf is the only available option, is there a plan to support the finetuning in allennlp in future as we like to avoid dependency on yet another package bilm-tf? 

Thanks.

**Comment by matt-peters** [comment]
To answer your questions:

1. It isn't yet possible to train the ELMo model in allennlp, although will be in the very near future.  Currently the only option is to train in bilm-tf and export the weights to allennlp.

2. We will eventually support fine tuning in allennlp, but a timeline for this is unclear (and not likely to happen before the end of the year).
