### ISSUE TITLE
Prerequisite of model visualization

### ISSUE THREAD

**Issue by rangwani-harsh** [allenai/allennlp#2088]
**System (please complete the following information):**
 - OS: Ubuntu 18.04
 - Python version: 3.6
 - AllenNLP version: 0.7.1
 

**Question**
Hi Team,

The question is specific to improving the description https://github.com/allenai/allennlp/blob/master/tutorials/how_to/visualizing_model_internals.md. 

It took me some time to figure out how things were working in the react demo. I think the first point in prerequisite should be modified a bit in such a way that it provides the following description

* That we need a flask server running for the react server to interact with all time. So including the command example, that needs to be executed ```python -m allennlp.service.server_simple     --archive-path /tmp/irony_alternate1/model.tar.gz     --predictor ironic-predictor     --include-package irony_model``` in my opinion is a good idea.

Thanks

**Comment by matt-gardner** [comment]
Can you submit this proposed change as a PR, so it's more clear what you mean?  Improving the documentation / tutorials is always a good thing, I just can't comment on the specific change before seeing exactly what you mean.
