### ISSUE TITLE
EncoderBase sort_and_run_forward crashes with all-zero length batch

### ISSUE THREAD

**Issue by suushiemaniac** [allenai/allennlp#2089]
**Describe the bug**
Seq2Vec encoding does not work when the current batch of sequences contains only sequences of length 0.

**To Reproduce**
Try to `forward` any batch tensor `(bt, seq, x)` of samples through `PytorchSeq2VecWrapper` with a padding mask of all zeros in shape `(bt, seq)`

**Expected behavior**
I expect the computation to succeed (pretty much just returning the inputs)

It does work when only _some_ of the input sequences have zero length. Only iff _all_ sequences are empty, it crashes.

**System (please complete the following information):**
 - OS: Linux -- Ubuntu 18.04
 - Python version: 3.6.6 / Anaconda
 - AllenNLP version: 0.7.1
 - PyTorch version: Not installed myself

**Additional context**
My research involves classification of dependency tree nodes, which may have any number of children (including 0 children) attached to them. Depending on the batch size, an individual batch may end up encoding only nodes without any children, thus all lengths are zero.
I currently "hotwire" your `Seq2Vec` encoding whenever I detect this, but the interface would be much cleaner if your library could just handle this edge case anyway.

Keep up the good work!

**Comment by matt-gardner** [comment]
Yep, this would be a good thing to fix.  PRs welcome!

**Comment by matt-gardner** [comment]
Also, this is possibly related to #1591.

**Comment by DeNeutoy** [comment]
This is essentially the correct behaviour in 99.99% of use cases - I think hotwiring it is actually fine.
