### ISSUE TITLE
Potentially unnecessary logging from multiprocessing

### ISSUE THREAD

**Issue by suushiemaniac** [allenai/allennlp#2091]
**System (please complete the following information):**
 - OS: Linux -- Ubuntu 18.04
 - Python version: 3.6.6 / Anaconda
 - AllenNLP version: 0.7.1
 - PyTorch version: not installed myself

**Question**

Why do you set the `stderr` logging level to `INFO` in https://github.com/allenai/allennlp/blob/master/allennlp/data/dataset_readers/multiprocess_dataset_reader.py#L11-L12 ?

I have a small script that reads some input data, `forward`s it through an AllenNLP `Model` and writes the (processed) output to `stdout` so another program written in a different programming language can consume it in a downstream setup.
The resulting CoNLL-U is line-based, but this logger spits out an additional `[INFO/MainProcess] process shutting down` at the very end that confuses the parser of the other application.

Always calling my script with `2> /dev/null` is not a suitable option, especially during debugging.
The logging message always shows up, because my code calls `from allennlp.data import DatasetReader` which in turn imports the `MultiprocessDatasetReader` mentioned above through a nested chain of `__init__.py` requirements.
I highly encourage you to deactivate this logging unless absolutely necessary, or at least to only attach the logger lazily so that logging is only used when the _actual class_ is used (and not just transitively imported in some unwanted fashion as described above).

Thanks!

**Comment by suushiemaniac** [comment]
Quick addendum: Commenting out L12 in the snippet mentioned above is not enough. The log message only disappears when also commenting out the declaration in L11 altogether.

**Comment by matt-gardner** [comment]
I also really dislike that additional logging statement; thanks for finding where it came from.  @matt-peters, @joelgrus, @DeNeutoy, any reason why we shouldn't remove those lines?

**Comment by joelgrus** [comment]
if I remember correctly, without the `log_to_stderr`, any logging that happens in a multiprocess process gets eaten. but there should be no issue with calling it lazily (e.g. inside the `MultiprocessDatasetReader` constructor)
