### ISSUE TITLE
conda install problem: jsonnet

### ISSUE THREAD

**Issue by ianbstewart** [allenai/allennlp#2093]
Hello,

I have tried to install allennlp using the command `pip install allennlp` but end up with the following error:

```
  Failed building wheel for jsonnet
Command "/nethome/miniconda3/envs/env/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-4ikavh1h/jsonnet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-en6_zmob/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-4ikavh1h/jsonnet/
```
I'm not sure what went wrong because I didn't change anything in the environment before installing. I don't know what `jsonnet` is. Help?

**Comment by matt-gardner** [comment]
This appears to be an issue with jsonnet and your environment, and isn't an issue with allennlp.  Unfortunately, I don't think there's anything we can do to help you - giving a more detailed description of your problem on a jsonnet issue would be a better way to get help.
