### ISSUE TITLE
Multiple prediction spans from machine comprehension (BiDAF)?

### ISSUE THREAD

**Issue by Andy-jqa** [allenai/allennlp#2095]
Hi,

Now the predictor of BiDAF machine comprehension returns one passage span with highest score. Can I use it to return a list of span with decreasing scores, starting from the highest one?

Thanks a lot,
Qiao

**Comment by matt-gardner** [comment]
BiDAF returns the [start and end probabilities for each span](https://github.com/allenai/allennlp/blob/d78daa44cc90b3ea9090fe6c24e788ebafe84496/allennlp/models/reading_comprehension/bidaf.py#L252-L255), which can you use to compute this.

**Comment by qw1243** [comment]
> BiDAF returns the [start and end probabilities for each span](https://github.com/allenai/allennlp/blob/d78daa44cc90b3ea9090fe6c24e788ebafe84496/allennlp/models/reading_comprehension/bidaf.py#L252-L255), which can you use to compute this.

Is there any way that I can compute the span score for the bidaf allennlp model?
