### ISSUE TITLE
examples is not enough..

### ISSUE THREAD

**Issue by MLjian** [allenai/allennlp#2096]
one sample has four features: sentence, array1. The tutorial that allennlp give dont tell how to handle the sample that has the array feauture. 
`sentence_field = TextField(tokens, self.token_indexers)
 array_field = ArrayField(array1)
 fields = {"sentence": sentence_field, "array": array_field}`
Is it right? How to do that.

**Comment by matt-gardner** [comment]
Did you try this?  When you did, what happened?  We can't really help you unless you give us more detail.

**Comment by MLjian** [comment]
> Did you try this? When you did, what happened? We can't really help you unless you give us more detail.

(Pdb)  self.array
array('[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0]',
      dtype='<U105')
(Pdb)  return_array
0.0
(Pdb)  max_shape
[]
(Pdb)  padding_lengths
{}

**Comment by matt-gardner** [comment]
This is still not enough information for us to help you. Please open a new issue following the issue template.
