### ISSUE TITLE
Any plans for a generic Decoder API for seq2seq models?

### ISSUE THREAD

**Issue by sai-prasanna** [allenai/allennlp#2097]
I am primarily working on seq2seq models. I currently use a hack-ish way of importing fairseq into an allennlp model and wrapping some objects to connect the APIs. I thought I could spend some time to implement a pluggable seq2seq model which can use multiple encoder/decoders.

Our current basic seq2seq model has an LSTMCell hardcoded inside of it, which makes it unusable for cases like a Gated CNN decoder, transformer decoder etc. 

1. Would it make sense to abstract out decoder as something separate from the seq2seq model?

2. Any opinion on what the abstract decoder API should consist of? since there are some specialized attributes with regards to the inputs required by the decoders. Some of these "fancy" decoders need extra values other than Seq2Seq's output, e.g, GatedCNN requires outputs added and scaled with source embedding and without adding it, etc. 

3. Should the current implemented Seq2Seq encoders return additional values that are needed by the decoder in a dictionary? 

With regards to the attention mechanism, since it differs for Transformer, GatedCNN etc I guess each decoder deriving the abstract class can figure that out.

**Comment by matt-gardner** [comment]
I think it'd be great to have better seq2seq functionality implemented in AllenNLP, and it's not something any of us are working on, so contributions would be great here.  I think the first step would be to write a simple design document for what abstractions you're thinking of adding and how they interact with each other and the other abstractions in the library (key word "simple" - this doesn't have to be anything fancy).  That could either be posted directly here, or as a gist, or google doc, or somewhere that we could look at it and comment on it.

**Comment by sai-prasanna** [comment]
@maxdel  I concur with the pros and cons. I wish we can convince fairseq team to use allennlp, but that might mostly not work out. My need currently is to try out stuff like elmo in encoder which as you pointed out doesn't work well with fairseq's encoder. 

Points to keep in mind while designing the API for decoding

1. Make it play well with caching for incremental decoding, maybe we can lift a page out of fairseq's way of passing the caching dictionary in each decoding step, instead of stateful properties inside decoder like opennmt

2. Make it flexible (like opennmt , unlike fairseq) so that one can potentially combine different encoders with different decoders.

3. Keep beam search in mind.

btw can you share the code, to compare notes on how you wrapped things, I do an ugly hack to replace fairseq's pytorch embedding with allennlp's Embedding object, and a wrapper for dictionary.

**Comment by epwalsh** [comment]
@sai-prasanna @maxdel if you are interested, maybe we could get the ball rolling on a document for the proposed API? GoogleDoc or whatever is easiest

**Comment by Alex-Fabbri** [comment]
@epwalsh @sai-prasanna  @maxdel  I am also interested in contributing to this as I have been working with fairseq models and would like to make porting them to allennlp easier. I just started a [blank GoogleDoc](https://docs.google.com/document/d/1tr_q0Czal4xdMWzwd0K-Tf3mBCk-_tckKcZtdzIM4P0/edit?usp=sharing) where we can discuss ideas about the proposed API. If you prefer another format let me know.

**Comment by matt-gardner** [comment]
Sorry to be slow responding, and thanks for going ahead with this.  When you all are comfortable with the state of the google doc, we'll give it a design review.

One thing to think about: we have a general encoder/decoder architecture already implemented, but it's designed for state machines, where the assumption is that you have different allowed actions at every timestep, and there's a lot of overhead for dealing with that.  Is there any room to combine these two things?  I'm guessing that's more work than it's worth, because it's just extra overhead that will slow down more typical seq2seq use cases, but it's worth thinking about a bit, at least.

Oh, another thing to keep in mind: how do you want to handle different training regimes?  Like beam search optimization, other RL-inspired techniques, and so on?

**Comment by sai-prasanna** [comment]
@Alex-Fabbri @Alex-Fabbri   @epwalsh  - I started charting out stuff in that doc. Feel free to comment/edit as required.

**Comment by generall** [comment]
I am working on related NLP problems as a side-project and I am interested in possibility to contribute to AllenNLP. I am wondering if there are any progress on this since last comment here.  It looks like a large modification required to implement this issue, so maybe a little coordination required. Is there any fork with initial attempts or something like this?

**Comment by epwalsh** [comment]
As far as I’m aware there hasn’t been a fork started yet, but I think it might be a good time to get that going. That would at least help get the ball rolling. Maybe we could start working off of a separate branch here?

**Comment by epwalsh** [comment]
@sai-prasanna I don't mind starting it off, unless one of the maintainers here can create a new branch for us. In any case, I probably won't be able to get to this started until after new years. So I'll start it off then unless someone else takes it up before that. Happy holidays!

**Comment by sai-prasanna** [comment]
@matt-gardner You could take a look, but sadly we didn't conclude with a consensus on an API design covering all that's needed in the document discussion (https://docs.google.com/document/d/1tr_q0Czal4xdMWzwd0K-Tf3mBCk-_tckKcZtdzIM4P0). I think that a good design (for the decoder) would evolve once we start implementing the RNN, CNN, Transformer backends for the abstract decoder.

@epwalsh After new year is fine. Enjoy the holidays!.

**Comment by epwalsh** [comment]
I definitely want to avoid one huge PR, so I think the most efficient way forward is for us to work on our own fork (which I, or someone else can start), and then incrementally submit PRs here as we go. Like @sai-prasanna said, I think a good first step (and first PR) would be to implement a generic base decoder class with some of the features we talked about in the doc (beam search, attention, etc), which we can then use to refactor the `simple_seq2seq` model. Subsequent PRs can work on improving the base decoder and making it even more general. Hopefully it can eventually be used in the semantic parsing framework as well (as @matt-gardner mentioned above), but I think that would be too big of a change / too much to think about for the first PR.

**Comment by matt-gardner** [comment]
@epwalsh that sounds like a good plan.  If you'd like feedback on your fork at any point before submitting the PR here, just ping me, and I'll take a look.

**Comment by epwalsh** [comment]
Ok so I've set up [a branch on my fork called "decoder"](https://github.com/epwalsh/allennlp/tree/decoder) and started [a PR into that branch](https://github.com/epwalsh/allennlp/pull/2) that sets up some basic structure. I figured our workflow could go like this:
1. we all contribute through PRs or direct commits to the "decoder" branch on my fork, and we can continue the discussion of the details of the API and implementation on those PRs,
2. when we are satisfied with the progress, we'll create an official PR into the master branch here.

I'm not 100% sure what the easiest way is for ya'll to work off of the decoder branch on my fork. One way would be to add the url for my fork as a remote to your local fork with something like this:
```
git remote add epwalsh-fork https://github.com/epwalsh/allennlp  # for https
git remote add epwalsh-fork git@github.com:epwalsh/allennlp.git  # for ssh
```

Then you can create your own branch off of the decoder branch like this:
```
git fetch epwalsh-fork  # pull latest updates
git checkout -b decoder-updates epwalsh-fork/decoder # create new local branch from decoder branch
git push --set-upstream origin decoder-updates  # push your branch to GitHub
```

If you know of a better way let me know!
