### ISSUE TITLE
Restore original text from a tokenized list of tokens?

### ISSUE THREAD

**Issue by Andy-jqa** [allenai/allennlp#2098]
Hi,

Is there any function to restore the original text from a tokenized list of tokens? 

Thanks,
Qiao

**Comment by matt-gardner** [comment]
Can you provide some more detail about what exactly you want to do?  If you're using the spacy tokenizer, you can probably use `token.text_with_ws` to get what you want.

**Comment by Andy-jqa** [comment]
@matt-gardner Nevermind. I've solved this question. Please close this issue. Thanks a lot!
