### ISSUE TITLE
Train elmo model and get updated weight file

### ISSUE THREAD

**Issue by KinamSalad** [allenai/allennlp#2101]
In https://github.com/allenai/allennlp/blob/master/tutorials/how_to/elmo.md  , 'Using ELMo as a PyTorch Module to train a new model' paragraph tell us How to train ELMo. 
What I understand is that when I put my own sentence set as an trainset, the model is trained and the values of the weighting_file change accordingly. If so, how can I get a modified weight_file in hdf5 format.

If the premise I understand is wrong, please let me know what the contents of the 'Using ELMo as a PyTorch Module to train a new model' item are.

Thank you

**Comment by DeNeutoy** [comment]
If you want to train a language model, you will need to use this code:
https://github.com/allenai/bilm-tf

The tutorial is to use an elmo model as a building block of a different model, such as NER or something.

**Comment by matt-peters** [comment]
If you are fine-tuning the pre-trained ELMo model by setting `requires_grad=True`, then I'd suggest just saving the resulting fine-tuned language with the built in torch serialization support (`.th` format).

**Comment by KinamSalad** [comment]
@DeNeutoy  Thank you for your help. If I  follow the process of bilm and get the weight.hdf5 file, Can I put this weight file into the elmo parameter?

**Comment by matt-peters** [comment]
Yes.  If you change any of the hyperparameters (hidden units, CNN filter sizes, etc) then you will also need to change the `json` formatted options, otherwise you can re-use the existing one.

**Comment by TheShadow29** [comment]
@matt-peters I wanted to know if it is possible to fine-tune on a new corpus by setting `requires_grad=True` in `elmo` module?

**Comment by matt-peters** [comment]
If you want to fine-tune ELMo as a language model (on an unlabeled) corpus, then I'd recommend using the tensorflow code (https://github.com/allenai/bilm-tf).  If you want to fine-tune with supervised annotation for another task, then yes, setting `requires_grad=True` will allow the ELMo weights to be updated.

**Comment by flyaway1217** [comment]
@matt-peters Why should we use ``_ElmoBiLm `` if we want to fine-tuning ELMo instead of ``Elmo `` class?  All I need is to update the scalar weights not the LSTMs weights.
It seems that directly using ```Elmo` is more convenient.

**Comment by matt-peters** [comment]
That comment is out dated.  You can fine tune with the Elmo class by setting both requires_grad and scalar_mix_parameters as

```
Elmo(..., requires_grad=True, scalar_mix_parameters=[0.0, 0.0, 20.0])
```

**Comment by eduamf** [comment]
> If you want to train a language model, you will need to use this code:
> https://github.com/allenai/bilm-tf
> 
> The tutorial is to use an elmo model as a building block of a different model, such as NER or something.

Without GPU and low data, only to check, it's necessary to change the bilm-tf code. Using Windows, and tensorflow 1.5 (CPU & GPU), a lot of warnings and errors. 

The PyTorch version can not be used to create a model from scratch, that`s it?
