### ISSUE TITLE
Python multiprocessing causes predictor to freeze

### ISSUE THREAD

**Issue by YuvalPeleg** [allenai/allennlp#2102]
First thing, thanks for all you're doing. I really love it.
Now for the gripe:
When calling predictor.predict_json from a multiprocess child process freezes the call.

After a bit of research, I think this issue is related to a problem in deadlocks in pytorch:
https://github.com/pytorch/pytorch/issues/1355

It can be _worked around by using 'spawn' as a start method_.

In the following example, the first call works, but the multiprocess map never returns.
```
from multiprocessing import Pool
from allennlp.predictors.predictor import Predictor

def answer_question(x):
    print("entry")
    predictor = Predictor.from_path(
        "https://s3-us-west-2.amazonaws.com/allennlp/models/bidaf-model-2017.09.15-charpad.tar.gz")
    print("call predict")
    prediction = predictor.predict_json({"passage": "John like dogs", "question": "who likes dogs?"})
    print("done aq")
    return prediction["best_span_str"]

if __name__ == '__main__':
    answer_question(1)
    p = Pool(1)
    answers = p.map(answer_question, range(1))
    print("done!")
```

Reproduce
1. Run any question against the machine comprehension predictor in parallel.
2. It will not return.

Expected behaviour:
Should return a prediction as it would in a single process.

System
--OSx
--3.66
--0.7.1

**Comment by DeNeutoy** [comment]
Thanks! This definitely won't work. You need to use pytorch Multiprocessing, and even then, you will struggle. Typically speedups in these models come from processing data in batches on a GPU, rather than using multiple processes (obviously this might not be an option for you). We can't help fix this, but I hope you figure it out!

**Comment by YuvalPeleg** [comment]
Thanks!
I think I'm pretty close to figuring it out. When and if I do, should I inform you?
It could make for a nice documentation addition.

**Comment by foodiehack** [comment]
Hi YuvalPeleg
Have you figured this out?
