### ISSUE TITLE
How can i process multi-channel batch data?

### ISSUE THREAD

**Issue by tingkai-zhang** [allenai/allennlp#2109]
Hi, traditionally the batch data being fed to the `Indexer` has shape of `[batch_size, num_tokens]`

I have a task that will utilize data of several days so i would like to pass the batch data of shape
`[batch_size, num_days, num_tokens]`.
`num_days` looks like multiple channels here.

A pooling layer will be added before the final classification layer to make that batch has shape `[batch_size, pooled_dimension]`

Does the current allennlp support above procedures? What are possible changes of code i need to make?

Thank you!

**Comment by matt-gardner** [comment]
Have a look at our `ListField`, which should do what you need.  There's an example of using a `ListField` of `TextFields` here: https://github.com/allenai/allennlp/blob/0b3ebcf978997eb99f95dbf0ffb0fc36b6c2b47a/allennlp/data/dataset_readers/reading_comprehension/util.py#L272.
