### ISSUE TITLE
Configuration error // Training model using GPU  "cuda_device": 0, QUAC Training dialog_qa.jsonnet configuration file 

### ISSUE THREAD

**Issue by hinnaweali** [allenai/allennlp#2110]
**System (please complete the following information):**
 - OS: Linux
 - Python version: 3.6.6
 - AllenNLP version: v0.7.1
 - PyTorch version: 0.41

**Question**
--------------

I'm getting the following error to train a QuAC model 

**Configuration Error**
--------------------------

"Experiment specified a GPU but none is available, if you want to run on CPU use the override trainer.coda_device = -1 in the json config file"  
![no gpu](https://user-images.githubusercontent.com/30128513/49188951-d166e880-f36c-11e8-99fc-02f6f3e05645.PNG)

**Comman line**
--------------------------
allennlp train /home/x/anaconda3/allennlp/training_config/dialog_qa.jsonnet -s /home/x/anaconda3/allennlp/save_directory/

I have a GPU with the following features, and wanted to train QUAC model using dialog_qa.jsonnet configuration file.

GPU Compute Type gn5 | ecs.gn5-c4g1.xlarge | 4 vCPU | 30 GiB | 1 * NVIDIA P100 | 1 * 440 GiB | Intel Xeon E5-2682v4 | 2.5 GHz

I'am i missing some other configurations?

Regards,
Ali

**Comment by hinnaweali** [comment]
> Can you run the following in a python interpreter?
> 
> ```python
> >>> import torch
> >>> a = torch.Tensor([0, 1, 2])
> >>> a.cuda()
> ```
> 
> What happens?

I got another error:

THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=74 error=35 : CUDA driver version is insufficient for CUDA runtime version
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: cuda runtime error (35) : CUDA driver version is insufficient for CUDA runtime version at /pytorch/aten/src/THC/THCGeneral.cpp:74

**Comment by matt-gardner** [comment]
That's your problem.  You need to fix your driver.  I'm closing this issue as it's unrelated to allennlp.

**Comment by hinnaweali** [comment]
> That's your problem. You need to fix your driver. I'm closing this issue as it's unrelated to allennlp.

Thanks. 
Fixed.
