### ISSUE TITLE
Accumulating gradients

### ISSUE THREAD

**Issue by cdownsimon** [allenai/allennlp#2112]
First, thanks for your excellent works that simplify many processes in NLP research and also open the door in how to design a great workflow! 

I am wondering it is possible to add accumulating gradient in Trainer described in [https://medium.com/huggingface/training-larger-batches-practical-tips-on-1-gpu-multi-gpu-distributed-setups-ec88c3e51255](url). I think that would benefit in single GPU training as sometime it doesn't have enough memory for larger batch size.

**Comment by schmmd** [comment]
@cdownsimon the approach for now is to modify the trainer yourself.  But if others are also looking for this functionality please thumbs-up this issue.

**Comment by dirkgr** [comment]
Done in #3537.
