### ISSUE TITLE
How to add special tokenization rule to make certain words atomic?

### ISSUE THREAD

**Issue by p-null** [allenai/allennlp#2115]
Hi, suppose there are some special words like `&wr234#` in sentences and i don't want them be splitted into word pieces by `tokenzier`.
How can i add special tokenization rules to keep these special words atomic during tokenization?
Thank you!

**Comment by matt-gardner** [comment]
We don't have any way of doing this, but you could implement your own [`WordSplitter`](https://github.com/allenai/allennlp/blob/master/allennlp/data/tokenizers/word_splitter.py) that tries to account for this (e.g., maybe split on those special tokens first, then tokenize the remaining parts individually?).
