### ISSUE TITLE
Add Multi-GPU for evaluation

### ISSUE THREAD

**Issue by matthew-z** [allenai/allennlp#2127]
Hi, I found that if I use multi-gpu for training (e.g., 8 GPUs), the evaluation on test after training will still use one GPU, which leads to OOM every time (since the batch_size is for multiple GPUs). 

Of course, the workaround is simply to manually call evaluate and override batch_size, but it is a little inconvenient.

**Describe the solution you'd like**
1. be able to set a separate batch_size for evaluating in config, or
2. add multiple-GPU supports for evaluation.

**Comment by matt-peters** [comment]
1. is supported by specifying a `validation_iterator` in the config in addition to the `iterator`. If it exists, it is used for validation/testing instead of the `iterator`.

PRs welcome for 2.

**Comment by matthew-z** [comment]
@matt-peters Thank you for the response.

I am afraid changing `validation_iterator` is not a perfect solution, because validation actually uses multiple GPUs well but somehow evaluation only uses one, so changing their batch_size together to a small size may slow down validation (I assume that the batch_size for validation and evaluation cannot be set separately in `validation_iterator `).

**Comment by matt-peters** [comment]
Got it, it seems the solution then is to fix the underlying cause of # 2.

**Comment by schmmd** [comment]
@matthew-z are you looking for multi-GPU evaluations for the `evaluate` command or for evaluation at the end of training?

**Comment by matthew-z** [comment]
@sacmehta Yes.

**Comment by matt-gardner** [comment]
Does the merge yesterday cover this, @DeNeutoy, @brendan-ai2?

**Comment by brendan-ai2** [comment]
@matt-gardner, the merge does not address this issue. Multi-GPU evaluation (now using torch.distributed) would still be a good feature to add. Unassigning as I'm not actively working on this.
