### ISSUE TITLE
Using ELMo interactively get An Error with Myself Chinese Model

### ISSUE THREAD

**Issue by cdj0311** [allenai/allennlp#2128]
Hi, All,
I'm a newer to AllenNLP.  I have trained a hd5y Elmo model with bilm-tf.  And I want to get the word/sentence vector with it, however, I got an error as follows: 
`RuntimeError: size mismatch, m1: [1 x 2560], m2: [512 x 4096] at /opt/conda/conda-bld/pytorch_1533672544752/work/aten/src/TH/generic/THTensorMath.cpp:2070`
My code:
`from allennlp.commands.elmo import ElmoEmbedder
options_file = "output/checkpoint_title/options.json"
weight_file = "output/weights_title.hdf5"
elmo = ElmoEmbedder(options_file, weight_file)
sentence = u"今天 天气 很好 啊"
vec = elmo.embed_sentence(sentence.split())
print(vec)`

The options file:
`{"bidirectional": true, "char_cnn": {"activation": "relu", "embedding": {"dim": 16}, "filters": [[1, 32], [2, 32], [3, 64], [4, 128], [5, 256], [6, 512], [7, 1024]], "max_characters_per_token": 10, "n_characters": 261, "n_highway": 2}, "dropout": 0.1, "lstm": {"cell_clip": 3, "dim": 1024, "n_layers": 2, "proj_clip": 3, "projection_dim": 512, "use_skip_connections": true}, "all_clip_norm_val": 10.0, "n_epochs": 10, "n_train_tokens": 103498288, "batch_size": 32, "n_tokens_vocab": 448524, "unroll_steps": 20, "n_negative_samples_batch": 4096}`

**Comment by huntzhan** [comment]
@cdj0311 Try to change `max_characters_per_token` back to `50` since it's been hardcoded in `ELMoCharacterMapper`:

https://github.com/allenai/allennlp/blob/7df8275e7f70013185f1afeaa2779c2abce4492d/allennlp/data/token_indexers/elmo_indexer.py#L25-L31

**Comment by matt-peters** [comment]
It's not obvious to me why that shape error is being triggered.

`max_characters_per_token` is hard coded at 50, although I don't see any reason we can't allow it to be configurable (PRs welcome).

The `n_characters` should always be 262, this assumption is harder to change.

Try this for your options file:

```{"lstm": {"use_skip_connections": true, "projection_dim": 512, "cell_clip": 3, "proj_clip": 3, "dim": 1024, "n_layers": 2}, "char_cnn": {"activation": "relu", "filters": [[1, 32], [2, 32], [3, 64], [4, 128], [5, 256], [6, 512], [7, 1024]], "n_highway": 1, "embedding": {"dim": 16}, "n_characters": 262, "max_characters_per_token": 50}}```

**Comment by huntzhan** [comment]
@matt-peters looks like `n_characters` will not be used. I've searched the code and could not find the corresponding reference.
