### ISSUE TITLE
Predict SRL Roles from json file raises error

### ISSUE THREAD

**Issue by chjulia** [allenai/allennlp#2133]
When I try to predict SRL Roles from a json file of the requested form: [{"sentence":"..."},{"sentence":"..."}] via predict_batch_json("path")

I get the following error:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-49-494c78c54d5e> in <module>
----> 1 result_SRL = predictor.predict_batch_json("testjson.json")
      2 print(result_SRL)

/mnt/ideastore/miniconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/predictors/semantic_role_labeler.py in predict_batch_json(self, inputs)
    131         # we are given.
    132         batch_size = len(inputs)
--> 133         instances_per_sentence = [self._sentence_to_srl_instances(json) for json in inputs]
    134 
    135         flattened_instances = [instance for sentence_instances in instances_per_sentence

/mnt/ideastore/miniconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/predictors/semantic_role_labeler.py in <listcomp>(.0)
    131         # we are given.
    132         batch_size = len(inputs)
--> 133         instances_per_sentence = [self._sentence_to_srl_instances(json) for json in inputs]
    134 
    135         flattened_instances = [instance for sentence_instances in instances_per_sentence

/mnt/ideastore/miniconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/predictors/semantic_role_labeler.py in _sentence_to_srl_instances(self, json_dict)
     91             One instance per verb.
     92         """
---> 93         sentence = json_dict["sentence"]
     94         tokens = self._tokenizer.split_words(sentence)
     95         words = [token.text for token in tokens]

TypeError: string indices must be integers
--------------------------------------------------------------------------
What do I understand wrong?

**Comment by joelgrus** [comment]
`predict_batch_json` expects a list of JSON objects, not a filename:

https://github.com/allenai/allennlp/blob/master/allennlp/predictors/semantic_role_labeler.py#L134
