### ISSUE TITLE
FlairTokenEmbedder

### ISSUE THREAD

**Issue by qiuwei** [allenai/allennlp#2146]
I have created a FlairTokenEmbedder which can incorporate the models trained using https://github.com/zalandoresearch/flair into allennlp.

The model performs reasonably well for NER on conll2003 data(F1: ~0.925 on test, slightly worse than the numbers（0.931） reported in their NAACL paper)

Is there any contribution guide which I can follow to get the code merged into allennlp?

**Comment by matt-gardner** [comment]
The closest we have to what you're looking for is our [style guide](https://github.com/allenai/allennlp/blob/master/STYLE.md).  We have a CONTRIBUTING readme, but it's not geared towards "what should I do if I want to submit a PR?".

I'd recommend as a first step just taking what you have and opening a PR with a description of what you're contributing and what it adds (I'm not familiar with flair, and so I'm not sure what it does that we don't already do).  Opening the PR will run CI, which will let you see what checks fail, how much test coverage your PR has, and so on, and you can fix things to match our style guide.

**Comment by schmmd** [comment]
@qiuwei we hope to see a PR from you.  Feel free to re-open if you have any more questions about how to contribute!
