### ISSUE TITLE
Have google colab notebooks for tutorial in addition to the notebook

### ISSUE THREAD

**Issue by TheShadow29** [allenai/allennlp#2150]
**Is your feature request related to a problem? Please describe.**
Not a problem really, but it would be nice to be able to run the tutorials on google colab (https://colab.research.google.com/notebooks/welcome.ipynb) out of the box.

**Describe the solution you'd like**
Simply port the existing tutorials (https://github.com/allenai/allennlp/tree/master/tutorials), both written in markdown form and jupyer notebook form, to google colab for easy reproducibility.

**Comment by schmmd** [comment]
We're not planning on doing this, but if you set up some tutorials on colab please let us know!

**Comment by TheShadow29** [comment]
@schmmd I made the allennlp tutorial (https://allennlp.org/tutorials) and the elmo tutorial (https://github.com/allenai/allennlp/blob/master/tutorials/how_to/elmo.md) to jupyter notebooks for easier reproduction. I have tried to explore each function to get a more in-depth understanding of how the library works, and included an example of why each import is required etc. 

Here is the link to the Main tutorial: https://github.com/TheShadow29/ALNLP-Notes/blob/master/notebooks/ALNLP-Tutorial.ipynb
Elmo tutorial: https://github.com/TheShadow29/ALNLP-Notes/blob/master/notebooks/Using-Elmo.ipynb

This is made to the best of my understanding. Would appreciate some feedback.
