### ISSUE TITLE
how to add commands?

### ISSUE THREAD

**Issue by susht3** [allenai/allennlp#2158]
i rewrite the trainer and want to format it as a command like "allennlp train"

**Comment by matthew-z** [comment]
https://allenai.github.io/allennlp-docs/api/allennlp.commands.html#allennlp.commands.main

you need to create your own `main.py`, which calls 
``` python
allennlp.commands.main(subcommand_overrides={"myCommand": Mycommand})
```

 create a `myCommand `:

```python
class Mycommand(Subcommand):
.....
```

Then, you may run `main.py` in the way you use `allennlp`
`python main.py train -s .....` 
or 
`python main.py mycommand .....`
