### ISSUE TITLE
Problems with Slanted Triangular Learning Rate schedule

### ISSUE THREAD

**Issue by anna-anisienia** [allenai/allennlp#2159]
When I use the following Trainer configuration with SlantedTriangular LR Scheduler (on Linux, Python version: 3.6, AllenNLP v0.7.2):
```python
  "trainer": {
      "num_epochs": 40,
      "patience": 3,
      "cuda_device": 1,
      "grad_clipping": 5.0,
      "validation_metric": "-loss",
      "learning_rate_scheduler": {
          "type": "slanted_triangular",
          "num_epochs": 40,
          "num_steps_per_epoch": 10,
          "gradual_unfreezing": true,
          "discriminative_fine_tuning": true,
          "decay_factor": 0.5
      },
      "optimizer": {
        "type": "adam",
        "lr": 0.001
      },
      "num_serialized_models_to_keep": 1
    },
```
I get the following error: `File "/home/venv_allennlp_0.7.2/lib/python3.6/site-packages/allennlp/training/trainer.py", line 1029, in from_params
    scheduler = LearningRateScheduler.from_params(optimizer, lr_scheduler_params)
  File "/home/venv_allennlp_0.7.2/lib/python3.6/site-packages/allennlp/training/learning_rate_schedulers.py", line 70, in from_params
    schedulers = LearningRateScheduler.by_name(scheduler)(optimizer, **params.as_dict())  # type: ignore
  File "/home/venv_allennlp_0.7.2/lib/python3.6/site-packages/allennlp/training/learning_rate_schedulers.py", line 207, in __init__
    "The default group should be empty."
AssertionError: The default group should be empty.`

Do you know what is meant by the default group and how can I fix it? Thank you in advance!

**Comment by matt-peters** [comment]
It is necessary to specify `parameter_groups` if either `gradual_unfreezing` or `discriminative_fine_tuning` are set to True when using this learning rate scheduler.  The `parameter_groups` are used to manage which layers are currently being trained (`gradual_unfreezing=True`) and vary the learning rate across different layers (`discriminative_fine_tuning=True`).  See

https://github.com/allenai/allennlp/blob/582d0e4fda34ab44d8a8ae739fbce09bddb3e9f5/allennlp/training/optimizers.py#L48

**Comment by anna-anisienia** [comment]
> It is necessary to specify `parameter_groups` if either `gradual_unfreezing` or `discriminative_fine_tuning` are set to True when using this learning rate scheduler. The `parameter_groups` are used to manage which layers are currently being trained (`gradual_unfreezing=True`) and vary the learning rate across different layers (`discriminative_fine_tuning=True`). See
> 
> [allennlp/allennlp/training/optimizers.py](https://github.com/allenai/allennlp/blob/582d0e4fda34ab44d8a8ae739fbce09bddb3e9f5/allennlp/training/optimizers.py#L48)
> 
> Line 48 in [582d0e4](/allenai/allennlp/commit/582d0e4fda34ab44d8a8ae739fbce09bddb3e9f5)
> 
>  groups = params.pop("parameter_groups", None)

Thank you. Could you give an example of how could I define it? I was trying to do:
```python
"learning_rate_scheduler": {
          "type": "slanted_triangular",
          "parameter_groups": [
                   [["emb_layers"], {"lr": 1e-4}],
                   [["encoder_layers"], {"lr": 1e-3}],
                   [["classifier_layers"], {"lr": 1e-2}]
            ],
          "num_epochs": 40,
          "num_steps_per_epoch": 10,
          "gradual_unfreezing": true,
          "discriminative_fine_tuning": true,
          "decay_factor": 0.5
      },
```
but got an error: `schedulers = LearningRateScheduler.by_name(scheduler)(optimizer, **params.as_dict())  # type: ignore
TypeError: __init__() got an unexpected keyword argument 'parameter_groups'`

**Comment by matt-peters** [comment]
Put `parameter_groups` under the `optimizer`, e.g.

Also, if you are using `discriminative_fine_tuning=True`, then don't specify the learning rate in the parameter groups, the `slanted_triangular` rate scheduler will handle that for you using the value of `decay_factor`.

```
"optimizer": {
    "type": "adam",
    "lr": 0.001",
    "parameter_groups": ....
},
"learning_rate_scheduler": {
    "type": "slanted_triangular",
    ...
}
```

**Comment by anna-anisienia** [comment]
Thank you very much, but I still don't fully understand it. 

If I don't need to specify LR for each group, then what should I put into those `parameter_groups`? I just want to specify: use larger LR in the first layer and then smaller and smaller LR in the next layers. Leaving parameter_groups empty didn't work.
```python
  "trainer": {
      "learning_rate_scheduler": {
          "type": "slanted_triangular",
          "num_epochs": 40,
          "num_steps_per_epoch": 10,
          "gradual_unfreezing": true,
          "discriminative_fine_tuning": true,
          "decay_factor": 0.5
      },
      "optimizer": {
        "type": "adam",
        "lr": 0.01,
        "parameter_groups": [[]],
      },
    },
```

**Comment by matt-peters** [comment]
The parameter groups are used to specify the names of the parameters in each layer, but the learning rate is modified by this rate scheduler.  Using something like this will give the top group lr=0.01, the second group lr=0.01 * 0.5 = 0.005, the third group lr=0.01 * 0.5 * 0.5 = 0.0025:

```"trainer": {
      "learning_rate_scheduler": {
          "type": "slanted_triangular",
          "num_epochs": 40,
          "num_steps_per_epoch": 10,
          "gradual_unfreezing": true,
          "discriminative_fine_tuning": true,
          "decay_factor": 0.5
      },
      "optimizer": {
        "type": "adam",
        "lr": 0.01,
        "parameter_groups": [
                   [["emb_layers"], {}],
                   [["encoder_layers"], {}],
                   [["classifier_layers"], {}]
],
      },
    },
```

**Comment by anna-anisienia** [comment]
Thank you! It makes sense, but now I get the same error as before:  `scheduler = LearningRateScheduler.from_params(optimizer, lr_scheduler_params)
  File "/home/venv_allennlp_0.7.2/lib/python3.6/site-packages/allennlp/training/learning_rate_schedulers.py", line 70, in from_params
    schedulers = LearningRateScheduler.by_name(scheduler)(optimizer, **params.as_dict())  # type: ignore
  File "/home/venv_allennlp_0.7.2/lib/python3.6/site-packages/allennlp/training/learning_rate_schedulers.py", line 207, in __init__
    "The default group should be empty."
AssertionError: The default group should be empty.`

Maybe I define my layers incorrectly? Does the `text_field_embedder` count as an embedding layer? Here is my entire config file:
```python
{
  "dataset_reader": {
        "type": "paper_reader",
        "lazy": true,
        "max_length": 40000,
        "tokenizer": {
          "word_splitter": "spacy"
        },
        "token_indexers": {
              "tokens": {
                  "type": "single_id",
                  "lowercase_tokens": true
              },
              "token_characters": {
                "type": "characters"
              },
              "elmo": {
                  "type": "elmo_characters"
                  }
            }
  },
  "train_data_path": "data/02_cite_optimized_corpus/train.jsonl",
  "validation_data_path": "data/02_cite_optimized_corpus/valid.jsonl",
  "model": {
      "type": "weighted_rm_classifier",
      "text_field_embedder": {
              "tokens": {
                    "type": "embedding",
                    "pretrained_file": "pretrained_models/glove.6B.100d.txt",
                    "embedding_dim": 100,
                    "trainable": false
                  },
              "elmo": {
                "type": "elmo_token_embedder",
                "options_file": "pretrained_models/elmo_2x4096_512_2048cnn_2xhighway_options.json",
                "weight_file": "pretrained_models/elmo_2x4096_512_2048cnn_2xhighway_weights.hdf5",
                "do_layer_norm": false,
                "dropout": 0,
                "requires_grad": false
              },
              "token_characters": {
                "type": "character_encoding",
                "embedding": {
                  "embedding_dim": 16
                },
                "encoder": {
                  "type": "cnn",
                  "embedding_dim": 16,
                  "num_filters": 64,
                  "ngram_filter_sizes": [3]
                },
                "dropout": 0.1
              }
          },
      "fulltext_encoder": {
          "type": "lstm",
          "bidirectional": true,
          "input_size": 1188,
          "hidden_size": 64,
          "num_layers": 2,
          "dropout": 0.1
      },
      "classifier_feedforward": {
          "input_dim": 128,
          "num_layers": 2,
          "hidden_dims": [200, 14],
          "activations": ["tanh", "linear"],
          "dropout": [0.2, 0.0]
        }
  },
  "iterator": {
      "type": "bucket",
      "sorting_keys": [["fulltext", "num_tokens"]],
      "padding_noise": 0.05,
      "batch_size": 1,
      "biggest_batch_first": true,
      "max_instances_in_memory": 4
  },
  "trainer": {
      "num_epochs": 40,
      "patience": 5,
      "cuda_device": 0,
      "grad_clipping": 5.0,
      "learning_rate_scheduler": {
          "type": "slanted_triangular",
          "num_epochs": 40,
          "num_steps_per_epoch": 10,
          "gradual_unfreezing": true,
          "discriminative_fine_tuning": true,
          "decay_factor": 0.5
      },
      "optimizer": {
        "type": "adam",
        "lr": 0.01,
        "parameter_groups": [
                   [["lstm1", "lstm2"], {}],
                   [["classifier1", "classifier2"], {}]
         ]
      },
      "num_serialized_models_to_keep": 1
    },
    "vocabulary":{
       "max_vocab_size": 80000
    }
}
```

**Comment by matt-peters** [comment]
All of the parameters in your model need to be included in one of the parameter groups, including those in the text_field_embedder. One way to accomplish this is to construct the model and print all parameter names with `print([name for name, param in model.named_parameters()])` then write regex to form the groups.

**Comment by anna-anisienia** [comment]
thank you very much!
