### ISSUE TITLE
tqdm erroneous behaviour in jupyter notebook

### ISSUE THREAD

**Issue by TheShadow29** [allenai/allennlp#2161]
**Describe the bug**
Running the tutorial (https://allennlp.org/tutorials) on a jupyter notebook results in bad progress bars (image attached)
![image](https://user-images.githubusercontent.com/10602903/49713185-9bdbbe00-fbfc-11e8-83c1-c39972d8fdd7.png)

**To Reproduce**
Copy paste the tutorial (https://allennlp.org/tutorials) to a jupyter notebook cell and run. 
**Expected behavior**
The progress bar should not behave like this.

**System (please complete the following information):**
 - Ubuntu 16.04
 - Python version: 3.6
 - AllenNLP version: v0.7.2
 - PyTorch version: 0.4.1

**Additional context**
The error is likely due to tqdm import https://github.com/allenai/allennlp/blob/master/allennlp/common/tqdm.py#L6

Need to check if it is being run on a jupyter notebook or not, if it is then it should be `from tqdm import tqdm_notebook as _tqdm`.

**Comment by TheShadow29** [comment]
It seems I made a mistake in interpreting the progressbar. I am sorry. I thought one was for number of epochs completed and the other for training, but it seems one is for training and the other is for validation. In that case, the progress bars are correct. 

Though intuitively, I would expect a progressbar for the epochs.

**Comment by matt-gardner** [comment]
For a real use case a single epoch will typically take minutes to hours, and you almost never run as many as you have there. tqdm doesn't make nearly as much sense in that seeing, especially with all the other stuff we log for each epoch.
