### ISSUE TITLE
why the memory will increase?

### ISSUE THREAD

**Issue by susht3** [allenai/allennlp#2163]
i use dialog QA model, but i find that my memory will dynamic increases, it will fix for a long time, and then become larger, then fix for a long time and then increase, i don't know why

**Comment by matthew-z** [comment]
it is very common that memory usage will increase when the model encounters longer passages.

To verify it, try `BucketIterator` with `biggest_batch_first=True`

**Comment by schmmd** [comment]
Closing as we have an answer.  Please re-open if the solution above doesn't work for you.
