### ISSUE TITLE
Allow elmo embeddings to take spacy tokens as inputs

### ISSUE THREAD

**Issue by TheShadow29** [allenai/allennlp#2170]
**Is your feature request related to a problem? Please describe.**
Currently, using `ElmoEmbedder` described here: https://github.com/allenai/allennlp/blob/master/tutorials/how_to/elmo.md#using-elmo-interactively. It requires the input to be tokens which are `List[str]` when using `embed_sentence` or `List[List[str]]` when using `embed_sentences`. However, when tokenizing a sentence or a batch of sentences using say `WordTokenizer` the output is `List[List[Token]]`. However, this seems to incompatible with the `ElmoEmbedder` and causes a type error at this line: https://github.com/allenai/allennlp/blob/master/allennlp/data/token_indexers/elmo_indexer.py#L61

Relevant screenshot:
![image](https://user-images.githubusercontent.com/10602903/49837356-e6734c80-fd5a-11e8-83dc-63093d0b8d76.png)

 
**Describe the solution you'd like**
Allow `List[Token]` or `List[List[Token]]` to be used as input to `ElmoEmbedder.embed_sentence(s)`.

**Describe alternatives you've considered**
Current workaround (to the best of my knowledge) is to convert `List[List[Token]]` to `List[List[str]]` by explicity getting the `text` attribute of the token, something like:
`str_tok_sents = [[x.text for x in y] for y in tokenized_sents]`

**Additional context**
Code to reproduce:
```
from allennlp.commands.elmo import ElmoEmbedder
from allennlp.data.tokenizers.word_tokenizer import WordTokenizer
elmo_emb = ElmoEmbedder()
wtokenizer = WordTokenizer()
sentences = ['You are a bold one.', 'Hello there!', 'Perhaps the archives are incomplete.']
tokenized_sents = wtokenizer.batch_tokenize(sentences)
str_tok_sents = [[x.text for x in y] for y in tokenized_sents]
vec_elmo = list(elmo_emb.embed_sentences(tokenized_sents))  #gives an error
vec_elmo = list(elmo_emb.embed_sentences(str_tok_sents))  #gives no error
```

**Comment by joelgrus** [comment]
I think the simplest solution is what's discussed here:

https://github.com/allenai/allennlp/issues/1887#issuecomment-428672752

adding an option to the `SpacyWordSplitter` that will return plain text tokens. 

I started a PR to do that a while ago, let me dig it up and submit it

**Comment by TheShadow29** [comment]
@joelgrus I think what you suggested would solve my problem. If I have the tokens in text form, I can directly pass them to ElmoEmbedder. Unless I am missing something.

**Comment by joelgrus** [comment]
the change I'm referring to doesn't make the the tokenizer return _text_ tokens, it makes them return our own Token class, which looks like the spacy one but isn't. you'd still have to call `.text` on the result

**Comment by TheShadow29** [comment]
I see. My bad. Do you think having an option to just return the `text` when using `SpacyWordSplitter` would be a good idea? Or would that be the same computational overhead as what I did?

**Comment by joelgrus** [comment]
having union return types is very bad ("this function might return strings or it might return tokens, good luck!"), and that solution would have the exact same computational overhead as what you did (which should not be very much overhead at all)

**Comment by TheShadow29** [comment]
Point noted. I will close this issue.
