### ISSUE TITLE
PDB up/down arrows don't work when running allennlp train

### ISSUE THREAD

**Issue by luckytoilet** [allenai/allennlp#2176]
**Describe the bug**
When I use PDB to enter debug mode while doing `allennlp train`, the up/down buttons don't work, and instead shows ^[[A.

**To Reproduce**
1. Clone the allennlp-as-a-library-example repo
2. Put a breakpoint somewhere: `import pdb; pdb.set_trace()`
3. Run it using the `allennlp train` command given in the tutorial
4. When it hits the breakpoint, press the up arrow

Expected behaviour: up arrow loads the previous typed command

Actual behaviour: ^[[A appears in the terminal

**System:**
 - OS: Ubuntu
 - Python version: 3.6.6
 - AllenNLP version: 0.7.1

**Comment by luckytoilet** [comment]
Any thoughts on this? @joelgrus

**Comment by joelgrus** [comment]
ok, a hacky solution is to un-redefine stdout before calling set_trace

```
import sys; sys.stdout = sys.stdout.terminal
import pdb;pdb.set_trace()
```

Let me know if that doesn't work. In the meantime I'll leave this open and maybe I can find a better solution. (But with the workaround it's low priority.)

**Comment by luckytoilet** [comment]
This doesn't work for me. When it hits the breakpoint, and I type any command, it crashes with a segmentation fault now.

**Comment by joelgrus** [comment]
it works for me, can you maybe try a clean environment and installing the latest version?

here's what I did

1. create a fresh python 3.6 environment
2. `pip install ipython allennlp`
3. add a set_trace here: https://github.com/allenai/allennlp-as-a-library-example/blob/master/my_library/models/academic_paper_classifier.py#L106

specifically, I added

```
        import pdb,sys;sys.stdout=sys.stdout.terminal;pdb.set_trace()
```

4. train the model

```
allennlp train experiments/venue_classifier.json -s /tmp/your_output_dir_here --include-package my_library --force
```

5. get dropped in a debugger and it works

```
(Pdb) embedded_title
tensor([[[ 0.1033,  0.6963, -1.4992,  ...,  0.7963, -0.7686,  1.6070],
         [-0.1529, -0.2428,  0.8984,  ..., -0.5910,  1.0039,  0.2066],
         [ 0.3786, -0.2965, -0.6330,  ...,  0.0066,  0.2556, -0.3595],
         ...,
         [-0.4773, -0.9892,  0.2623,  ...,  0.3837,  0.8672, -0.5003],
         [-0.4773, -0.9892,  0.2623,  ...,  0.3837,  0.8672, -0.5003],
         [-0.4773, -0.9892,  0.2623,  ...,  0.3837,  0.8672, -0.5003]],
...
```

what are you doing differently?

**Comment by luckytoilet** [comment]
Hmm, I'm not sure why it's working for you and not for me. I updated AllenNLP to the latest version (8.0) and put the breakpoint in the same place, but I'm still getting a segfault ([pastebin](https://pastebin.com/RXCbK7sM)).

The only thing I'm doing differently is I'm using conda instead of pip, but this shouldn't affect anything.

**Comment by matt-gardner** [comment]
@joelgrus, ping.

**Comment by matt-gardner** [comment]
Closing this as stale and rare.  We also just changed the lines that were causing this issue, so I don't know if it's still a problem or not.  If it _is_ still a problem that someone cares about, please open a new issue for it.
