### ISSUE TITLE
Task SNLI has down due to the  GPU Tensor

### ISSUE THREAD

**Issue by shuxiaobo** [allenai/allennlp#2182]
**Describe the bug**
Task SNLI has down due to the  GPU Tensor

**To Reproduce**
Steps to reproduce the behavior
1. Download snli data
2.Run 'allennlp train training_config/decomposable_attention.jsonnet -s /netdisk/one/allennlp/snli_default'
3. error : 
![image](https://user-images.githubusercontent.com/11539889/49979161-bf01c700-ff88-11e8-9550-602c11542d43.png)

**Expected behavior**

**System (please complete the following information):**
 - OS: CentOS 7
 - Python version: 3.6.5
 - AllenNLP version: I installed from master yesterday
 - PyTorch version: default from requirements.txt

**Comment by nelson-liu** [comment]
I know @dericp was also running into this, but i thought it might be an issue with his custom code. if you change the optimizer from adagrad to adam, it should work as a temporary workaround.

**Comment by shuxiaobo** [comment]
@nelson-liu Thanks a lot. Problem solved!

**Comment by nelson-liu** [comment]
@matt-gardner might still be worth leaving this open to figure out why it doesn’t work with adagrad?

**Comment by dericp** [comment]
@nelson-liu @matt-gardner I can confirm I had this issue as well in 0.7.2. I didn't have this issue in 0.7.1 which seems to imply it's caused by the the latest changes. I'd be happy to post more details about what I was doing if it's helpful.
