### ISSUE TITLE
Reduce memory use of multi-head self-attention

### ISSUE THREAD

**Issue by YuxianMeng** [allenai/allennlp#2185]
**Is your feature request related to a problem? Please describe.**
Since self-attention complexity is O(timestep * timestep * heads), the attention_dropout and mask_softmax  layer consumes lots of memory in a model where self_attention is heavily used. For example, QANet uses 3*7=21 self attention layer in its Model Encoder Layer. Is it possible to make it more memory efficient?

**Describe the solution you'd like**
I'm not quite familiar with recycle in pytorch,  but I'm wondering is there any chance to solve this?

**Comment by matt-gardner** [comment]
@yizhongw has a memory-optimized version of QANet, with some improvements to the self-attention code, that we'll work on merging in the near future.

**Comment by YuxianMeng** [comment]
> @yizhongw has a memory-optimized version of QANet, with some improvements to the self-attention code, that we'll work on merging in the near future.

Nice improvements! Good to know others are implementing QANet. Thanks!
