### ISSUE TITLE
How to disable info logging?

### ISSUE THREAD

**Issue by ahmadmagdy** [allenai/allennlp#2186]
I am using bidaf model, after the last release an info message logging start to appear which make it difficult to track the progress of training, example:
"/usr/bin/python3.6 /home/amagdy/Downloads/allennlp-as-a-library-example-master/new_main.py
12/15/2018 13:18:46 - INFO - allennlp.common.params -   random_seed = 13370
12/15/2018 13:18:46 - INFO - allennlp.common.params -   numpy_seed = 1337
12/15/2018 13:18:46 - INFO - allennlp.common.params -   pytorch_seed = 133
12/15/2018 13:18:46 - INFO - allennlp.common.checks -   Pytorch version: 0.4.1
12/15/2018 13:18:46 - INFO - allennlp.common.from_params -   instantiating class <class 'allennlp.data.dataset_readers.dataset_reader.DatasetReader'> from params {'token_indexers': {'token_characters': {'character_tokenizer': {'byte_encoding': 'utf-8'}, 'type': 'characters'}, 'tokens': {'type': 'single_id'}}, 'type': 'squad'} and extras {}
12/15/2018 13:18:46 - INFO - allennlp.common.params -   dataset_reader.type = squad
12/15/2018 13:18:46 - INFO - allennlp.common.from_params -   instantiating class <class 'allennlp.data.dataset_readers.reading_comprehension.squad.SquadReader'> from params {'token_indexers': {'token_characters': {'character_tokenizer': {'byte_encoding': 'utf-8'}, 'type': 'characters'}, 'tokens': {'type': 'single_id'}}} and extras {}
12/15/2018 13:18:46 - INFO - allennlp.common.from_params -   instantiating class allennlp.data.token_indexers.token_indexer.TokenIndexer from params {'character_tokenizer': {'byte_encoding': 'utf-8'}, 'type': 'characters'} and extras {}
12/15/2018 13:18:46 - INFO - allennlp.common.params -   dataset_reader.token_indexers.token_characters.type = characters
12/15/2018 13:18:46 - INFO - allennlp.common.from_params -   instantiating class allennlp.data.token_indexers.token_characters_indexer.TokenCharactersIndexer from params {'character_tokenizer': {'byte_encoding': 'utf-8'}} and extras {}
12/15/2018 13:18:46 - INFO - allennlp.common.params -   dataset_reader.token_indexers.token_characters.namespace = token_characters
12/15/2018 13:18:46 - INFO - allennlp.common.from_params -   instantiating class <class 'allennlp.data.tokenizers.character_tokenizer.CharacterTokenizer'> from params {'byte_encoding': 'utf-8'} and extras {}
12/15/2018 13:18:46 - INFO - allennlp.common.params -   dataset_reader.token_indexers.token_characters.character_tokenizer.byte_encoding = utf-8
12/15/2018 13:18:46 - INFO - allennlp.common.params -   dataset_reader.token_indexers.token_characters.character_tokenizer.lowercase_characters = False
12/15/2018 13:18:46 - INFO - allennlp.common.params -   dataset_reader.token_indexers.token_characters.character_tokenizer.start_tokens = None
12/15/2018 13:18:46 - INFO - allennlp.common.params -   dataset_reader.token_indexers.token_characters.character_tokenizer.end_tokens = None
12/15/2018 13:18:46 - INFO - allennlp.common.params -   dataset_reader.token_indexers.token_characters.start_tokens = None
12/15/2018 13:18:46 - INFO - allennlp.common.params -   dataset_reader.token_indexers.token_characters.end_tokens = None
12/15/2018 13:18:46 - INFO - allennlp.common.params -   dataset_reader.token_indexers.token_characters.min_padding_length = 0
12/15/2018 13:18:46 - INFO - allennlp.common.from_params -   instantiating class allennlp.data.token_indexers.token_indexer.TokenIndexer from params {'type': 'single_id'} and extras {}
12/15/2018 13:18:46 - INFO - allennlp.common.params -   dataset_reader.token_indexers.tokens.type = single_id
12/15/2018 13:18:46 - INFO - allennlp.common.from_params -   instantiating class allennlp.data.token_indexers.single_id_token_indexer.SingleIdTokenIndexer from params {} and extras {}
12/15/2018 13:18:46 - INFO - allennlp.common.params -   dataset_reader.token_indexers.tokens.namespace = tokens
12/15/2018 13:18:46 - INFO - allennlp.common.params -   dataset_reader.token_indexers.tokens.lowercase_tokens = False
12/15/2018 13:18:46 - INFO - allennlp.common.params -   dataset_reader.token_indexers.tokens.start_tokens = None
12/15/2018 13:18:46 - INFO - allennlp.common.params -   dataset_reader.token_indexers.tokens.end_tokens = None
12/15/2018 13:18:46 - INFO - allennlp.common.params -   dataset_reader.lazy = False
12/15/2018 13:18:46 - INFO - allennlp.common.params -   validation_dataset_reader = None
12/15/2018 13:18:46 - INFO - allennlp.common.params -   train_data_path = train.json
12/15/2018 13:18:46 - INFO - allennlp.commands.train -   Reading training data from train.json"

Any idea how to disable that?

**Comment by matt-gardner** [comment]
Those logging messages have been there the whole time.  This is where the logging level gets set: https://github.com/allenai/allennlp/blob/89cef2f08c97510c6f098e9381fdc22116ad5b1a/allennlp/run.py#L6-L13

That script is very short (and it's what you're running when you run `allennlp train`).  You could easily write your own script that configures logging differently.  For example, here's a different configuration that we use when running tests: https://github.com/allenai/allennlp/blob/89cef2f08c97510c6f098e9381fdc22116ad5b1a/allennlp/common/testing/test_case.py#L26-L34
