### ISSUE TITLE
How to get the number of updates easily?

### ISSUE THREAD

**Issue by tingkai-zhang** [allenai/allennlp#2187]
Hi, i would like to visualize the loss, learning rate, accuracy against the number of updates in allennlp.
How can i easily get the number of updates?

My current workaround is create a `updates` variable in optimizer file and increment it at each step(). Then import `updates` in model file and use that for visualization in forward() where loss, accuracy are generated. 

 - AllenNLP version:  v0.7.2 

Thank you

**Comment by matt-gardner** [comment]
Are you able to use tensorboard?  All of this is logged by default to tensorboard, for easy visualization.

**Comment by tingkai-zhang** [comment]
Tensorboard still needs global steps(or number of updates) to record.
`add_scalar(tag, scalar_value, global_step=None, walltime=None)`

**Comment by tingkai-zhang** [comment]
aha, i see tensorboardx is already integrated within allennlp!
Thanks!
