### ISSUE TITLE
DataBaseReader

### ISSUE THREAD

**Issue by rcourivaud** [allenai/allennlp#2193]
**Describe the solution you'd like**
Make Dataset more agnostic and make possible to use Postgres, Mongo or ElasticSearch Source 

**Describe alternatives you've considered**
Create New DatabaseReader using SQLAlchemy, pyMongo, pyElasticsearch clients.

I'm on it

**Comment by matt-gardner** [comment]
Our `DatasetReaders` are all specific to a particular input/output spec for a model - a different input/output spec typically requires a new `DatasetReader`, by design.  How exactly are you proposing to build a general database `DatasetReader`?

**Comment by rcourivaud** [comment]
I don't finished to design it properly but these clients make possible to use lazy cursors on each Databases. 

For now, I redefine a `DatabaseReader` which take a connection url and a query in parameters. 
Users only needs (as today) to redefine `text_to_instance` but `cursor_to_instance` or `object_to_instance`.   

What do you think ?

**Comment by rcourivaud** [comment]
It will cause problems with the current implementation of predictors

**Comment by matt-gardner** [comment]
Hmm, this sounds like it could work.  If you open a work-in-progress PR with what you have, we could give some better feedback about how to fit this better into our API - I'm pretty sure the predictors shouldn't be a problem.

**Comment by schmmd** [comment]
I think it's unfortunate that DatasetReaders take a file as an argument since it really limits the backend we have.  I tried changing it to something more generic once but I ran into problems with the [Penn Treebank Reader](https://github.com/allenai/allennlp/blob/master/allennlp/data/dataset_readers/penn_tree_bank.py#L67), since it requires file input.
