### ISSUE TITLE
How to avoid sending passage every time for MC

### ISSUE THREAD

**Issue by sandtemp01** [allenai/allennlp#2197]
Hi,
I am using following code for machine comprehension as per [https://allennlp.org/models](https://allennlp.org/models)
```
from allennlp.predictors.predictor import Predictor
predictor = Predictor.from_path("https://s3-us-west-2.amazonaws.com/allennlp/models/bidaf-model-2017.09.15-charpad.tar.gz")
predictor.predict(
  passage="The Matrix is a 1999 science fiction action film written and directed by The Wachowskis, starring Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss, Hugo Weaving, and Joe Pantoliano.",
  question="Who stars in The Matrix?"
)
```

In this I have to send passage everytime to the predictor. Is it necessary? My article is fixed and questions vary. Sending a big passage everytime slows down the process.
Please suggest

**Comment by matt-gardner** [comment]
BiDAF encodes the passage and the question together for every question, so there is no way to save time by pre-encoding the passage (technically, you could do one small piece of the model once, but I'd expect the time savings to be minimal).  If you want to do what you suggest, you need a different model that encodes the passage separately from the question.  There has been some work that tries this (https://arxiv.org/abs/1804.07726), though its performance is _much_ worse.

It doesn't look like you're batching questions together, though from your description it sounds like you could be.  Doing that should make things much faster, without having to change your model at all.

**Comment by sandtemp01** [comment]
Thanks for reply. Can you please give links on "batching questions together". i will follow.
is it asking multiple question on same document? In actual my use case is opposite.. multiple documents but one question at a time.

**Comment by matt-gardner** [comment]
Make your instances into a list of dictionaries, and call [`predictor.predict_batch_json(instances)`](https://github.com/allenai/allennlp/blob/12d32972a05036f5be7cf152a00afad02da8cd16/allennlp/predictors/predictor.py#L69).  Each dictionary should be formatted like this: https://github.com/allenai/allennlp/blob/12d32972a05036f5be7cf152a00afad02da8cd16/allennlp/predictors/bidaf.py#L31
