### ISSUE TITLE
Replicate BiDAF SQuAD results

### ISSUE THREAD

**Issue by valsworthen** [allenai/allennlp#2220]
**System (please complete the following information):**
 - OS: Linux
 - Python version: 3.7.1
 - AllenNLP version: 0.7.2
 - PyTorch version: 0.4.1

Hello, 

I have retrained BiDAF on SQuAD twice with [the proposed jsonnet](https://github.com/allenai/allennlp/blob/master/training_config/bidaf.jsonnet) and I can't reach the performance of the pre-trained model available [here](https://allennlp.org/models).

It says EM 68.3 / F1 77.9 while I only have EM 66.9 / F1 76.7. 

Do you know what could be the reason for such a significant gap?

**Comment by matt-gardner** [comment]
BiDAF has a particularly high training variance.  We ended up training it a bunch of times as we were developing it, and that was the run that had the highest performance.  It's not surprising to me that you didn't get performance that high with only two samples.
