### ISSUE TITLE
cannot save model with Vocabulary: Can't pickle lambda

### ISSUE THREAD

**Issue by DSLituiev** [allenai/allennlp#2222]
**Describe the bug**
a model using Vocabulary cannot be serialized and saved using `torch.save(model, filename)` due to `lambda` in `Vocabulary.from_instances`

    AttributeError: Can't pickle local object 'Vocabulary.from_instances.<locals>.<lambda>'

**To Reproduce**
Steps to reproduce the behavior
1. train a model following the [AllenNLP tutorial](https://allennlp.org/tutorials)
2. run `torch.save(model,'test.torch')`

**Expected behavior**
model is saved

**System (please complete the following information):**
 - OS: OSX
 - Python version: 3.6.3
 - AllenNLP version: 0.7.2
 - PyTorch version: 0.4.1

**Comment by DeNeutoy** [comment]
Hi, you need to save the state dict from the model like 
```
torch.save(model.state_dict(),'test.torch')
```

Also note to reload an allennlp model you will also need the `config.json` and the `vocabulary` directory that were saved during training.

**Comment by DSLituiev** [comment]
@DeNeutoy is there a good tutorial on saving models mentioning how to get `config.json` and the `vocabulary` directory? It is not obvious why a `nn.Model` subclass does not support `nn.save` method and I could not see steps you are describing in that tutorial or its refs. Thank you
