### ISSUE TITLE
About the get_output_dim() of ElmoTokenEmbedder

### ISSUE THREAD

**Issue by jihunchoi** [allenai/allennlp#2227]
**Describe the bug**
`get_output_dim()` of `ElmoTokenEmbedder` returns the dimension of the LSTM hidden state even when the `projection_dim` parameter is given.
I'm not sure that it is intended behavior or a bug, but I think it would be more natural to return the `projection_dim` instead.

**To Reproduce**
```
In [1]: from allennlp.modules.token_embedders import ElmoTokenEmbedder
In [2]: embedder = ElmoTokenEmbedder(
    options_file='elmo_2x4096_512_2048cnn_2xhighway_options.json',
    weight_file='elmo_2x4096_512_2048cnn_2xhighway_weights.hdf5',
    projection_dim=100)
In [3]: embedder.get_output_dim()
Out[3]: 1024  # Shouldn't this be 100?
```

**Comment by DeNeutoy** [comment]
Hi, this is a bug - would you mind submitting a fix? 

You'll need to change [this method](https://github.com/allenai/allennlp/blob/master/allennlp/modules/token_embedders/elmo_token_embedder.py#L71) and add a test (you could just add an `assert` to [this test](https://github.com/allenai/allennlp/blob/master/allennlp/tests/modules/token_embedders/elmo_token_embedder_test.py#L73))

Thanks!

**Comment by tingkai-zhang** [comment]
Hi, I have submitted a fix! Please tell if it is good to go or i should change anything :)

**Comment by nelson-liu** [comment]
#2234 should have fixed this. thanks again, @jihunchoi and @tingkai-zhang
