### ISSUE TITLE
Segementation Fault during training

### ISSUE THREAD

**Issue by djshowtime** [allenai/allennlp#2238]
I was trying to run crf_tagger with bi-lstm for NER task, based on the tutorial.
Everything goes well in testing (running in a script).

However, When I used command and configuration file to train the model. It failed.

Then command line:
`allennlp train bilstm_crf_ner.json -s model_save --include-package ner_lib
`
in ner_lib I only change the way reading the file in _reader in dataset_reader.

The error:
```
2018-12-25 16:48:57,031 - INFO - allennlp.common.params - trainer.should_log_learning_rate = False
2018-12-25 16:48:57,239 - INFO - allennlp.common.params - evaluate_on_test = False
2018-12-25 16:48:57,240 - INFO - allennlp.training.trainer - Beginning training.
2018-12-25 16:48:57,241 - INFO - allennlp.training.trainer - Epoch 0/39
2018-12-25 16:48:57,241 - INFO - allennlp.training.trainer - Peak CPU memory usage MB: 0.0
2018-12-25 16:48:57,246 - INFO - allennlp.training.trainer - Training
  0%|| 0/16 [00:00<?, ?it/s]/c/Users/dingjiajia/Anaconda3/envs/allennlp/Scripts/allennlp: line 2:  6328 Segmentation fault      python -m allennlp.run "$@"
(allennlp)

```
The former version was 0.7.2.

After I tried to upgrade the version of Allennlp to 0.8.0 with command:

` pip install git+https://github.com/allenai/allennlp.git@master`

stopped in training, got the error:
```
2018-12-25 17:09:43,680 - INFO - allennlp.training.trainer - Beginning training.
2018-12-25 17:09:43,680 - INFO - allennlp.training.trainer - Epoch 0/39
2018-12-25 17:09:43,681 - INFO - allennlp.training.trainer - Peak CPU memory usage MB: 0.0
2018-12-25 17:09:43,686 - INFO - allennlp.training.trainer - Training
  0%|| 0/16 [00:00<?, ?it/s]/c/Users/dingjiajia/Anaconda3/envs/allennlp/Scripts/allennlp: line 2:  4248 Segmentation fault      python -m allennlp.run "$@"
(allennlp)
```

**Comment by nelson-liu** [comment]
Can you paste the changes you made to the `dataset_reader`? This looks like an out of memory (RAM) error, and i'd guess that the culprit is some aspect of your modified dataset reader.

**Comment by djshowtime** [comment]
> Can you paste the changes you made to the `dataset_reader`? This looks like an out of memory (RAM) error, and i'd guess that the culprit is some aspect of your modified dataset reader.

@DatasetReader.register("emr_datasetreader")
class EMRDatasetReader(SequenceTaggingDatasetReader):
    def __init__(self):
        super(EMRDatasetReader, self).__init__()
    
    def _read(self, file_path):
        # if `file_path` is a URL, redirect to the cache
        file_path = cached_path(file_path)

        with open(file_path, "r", encoding = 'utf-8') as data_file:

            logger.info("Reading instances from lines in file at: %s", file_path)
            for line in data_file:
                line = line.strip("\n")

                # skip blank lines
                if not line:
                    continue

                tokens_and_tags = [pair.rsplit(self._word_tag_delimiter, 1)
                                   for pair in line.split(self._token_delimiter)]
                tokens = [Token(token) for token, tag in tokens_and_tags]
                tags = [tag for token, tag in tokens_and_tags]
                yield self.text_to_instance(tokens, tags)

**Comment by nelson-liu** [comment]
Thanks, your code itself looks ok. Perhaps your dataset is just too large for your system's memory?

I'd recommend adding the `lazy` parameter to your `EMRDatasetReader`, passing it to `SequenceTaggingDatasetReader`, and setting it to true in your config. This should reduce training RAM usage.

**Comment by nelson-liu** [comment]
Oops, here's a document with more info about lazy dataset readers: https://github.com/allenai/allennlp/blob/master/tutorials/getting_started/laziness.md

**Comment by djshowtime** [comment]
> Thanks, your code itself looks ok. Perhaps your dataset is just too large for your system's memory?
> 
> I'd recommend adding the `lazy` parameter to your `EMRDatasetReader`, passing it to `SequenceTaggingDatasetReader`, and setting it to true in your config. This should reduce training RAM usage.

Thanks. Yes, it is the out of memory problem. Either `lazy` or changing to a server can solve the problem.

**Comment by nelson-liu** [comment]
closing this for now, feel free to ask if you have further questions
