### ISSUE TITLE
Bug in initializer uniform_unit_scaling

### ISSUE THREAD

**Issue by SivilTaram** [allenai/allennlp#2239]
**Describe the bug**
bug in allennlp.nn.initializers.uniform_unit_scaling

**To Reproduce**
Using the latest version of allennlp and pytorch(0.4.1), initialize parameters of LSTM/GRU via uniform_unit_scaling function

**Expected behavior**
Exception throw:
```
RuntimeError: a leaf Variable that requires grad has been used in an in-place operation
```

**Potential Solution**
Fix the line to `return tensor.data.uniform_(-max_value, max_value)` [link](https://github.com/allenai/allennlp/blob/1938a5af6d1ea3a2d8dccbb831f82990800fa3e1/allennlp/nn/initializers.py#L95)

**Comment by schmmd** [comment]
@DeNeutoy does this look like a good fix to you?  You added this code in https://github.com/allenai/allennlp/pull/640.

**Comment by matt-gardner** [comment]
@DeNeutoy is out for another little while; yes, this looks like a good fix.  PR welcome.
