### ISSUE TITLE
ConfigurationError: 'Cannot register simple_tagger as Model; name already in use for SimpleTagger'

### ISSUE THREAD

**Issue by tsengchan** [allenai/allennlp#2241]
- Ubuntu 16.04
 - Python version: 3.6.
 - allennlp 0.7.2
 - PyTorch version: 0.4.1
- Jupyter 4.4.0

I am getting the error:
ConfigurationError: 'Cannot register simple_tagger as Model; name already in use for SimpleTagger'

I am trying to reproduce code from:
https://github.com/allenai/allennlp/blob/master/allennlp/models/simple_tagger.py

**Comment by schmmd** [comment]
Closing, as it sounds like @SparkJiao's suggestion solved your issue!  Thanks @SparkJiao!

**Comment by QDWQ** [comment]
Hello, I have encountered the same problem.
@SparkJiao   What is the specific solution to this problem?

**Comment by SparkJiao** [comment]
@QDWQ Modify the name annotation of your reader with a name which haven't been used by the repo's predefined readers.
