### ISSUE TITLE
How do you save memory while using bert text field embedder?

### ISSUE THREAD

**Issue by SparkJiao** [allenai/allennlp#2244]
**System (please complete the following information):**
 - OS: [Linux]
 - Python version: [3.7.1]
 - AllenNLP version: [v0.7.2]
 - PyTorch version: (0.4.0)
 - GPU: TITAN XP 12G

**Question**

* Do you have used any trick while using bert or elmo embedder? I have used bert text field embedder with `batch_size=1` to train a model but while using the bert-for-question-answering from hugging-face I met `CUDA out of memory`. So I wonder if you have used some tricks for using bert? Thank you very much!

**Comment by YuxianMeng** [comment]
@SparkJiao Are you using BERT in AllenNLP for question-answering? I don't think they use any tricks, maybe the main cause is from length truncation

**Comment by nelson-liu** [comment]
They had this "trick" to make things work for long sequences on SQuAD (https://github.com/google-research/bert/issues/66#issuecomment-436378461), not sure if the huggingface code you mentioned uses it. Just mentioning it because I thought it might be relevant.

**Comment by SparkJiao** [comment]
@nelson-liu @YuxianMeng Yes I agree with that. Huggingface uses the sliding window too. I think the reason why I can combine a context and its all questions (like CoQA, not SQuAD) into a single batch with AllenNLP is that in AllenNLP they doesn't make question and context into a single sequence so that I only need to compute the hidden state for context for only several times which depending on the length of the context. But in the original implementation of Bert for question answering, I need to compute the hidden state of every segment of the context with each question so the hidden size becomes large... Temporarily, I don't know how to solve it, which may need some tricky implementations...

**Comment by matt-gardner** [comment]
It looks to me like the main question here is answered, right?  I'm closing this issue; feel free to re-open it if you have more questions.
