### ISSUE TITLE
BidirectionalLanguageModel registered name is inconsistent

### ISSUE THREAD

**Issue by nelson-liu** [allenai/allennlp#2246]
Minor nit: `BidirectionalLanguageModel` is registered as `"bidirectional-language-model"`. I think we've tended to use underscores for multi-word model names (i.e., `bidirectional_language_model`)?

Happy to make this change, but not sure how to raise a `DeprecationWarning` if we detect that the `bidirectional-language-model` name is used? Maybe @joelgrus would know?

**Comment by nelson-liu** [comment]
looks like it works. re: `boe`, i suppose you just want `bag_of_embeddings` as another name for `boe` (i.e., don't deprecate anything)?

For further thought: maybe there's a nicer way to indicate that things are aliases of each other, in a way that might even be possible to expose through the config wizard?

**Comment by matt-gardner** [comment]
Hmm, good point on the config wizard.  @joelgrus is probably the right person to answer that.  If we don't want to deal with the headache of aliases, I'd just deprecate the `boe` name.

**Comment by joelgrus** [comment]
I believe the config wizard doesn't explicitly expose the registered names to the user -- it exposes the *class* names and then just sticks the "registered name" keys in the output json. but off the top of my head it's not obvious what will happen if a class is registered twice with two different names -- it seems likely it will show up twice in the dropdowns, so that would need to be fixed, and we'd need to figure out some "canonical" ordering (e.g. "use the first registered name")

**Comment by brendan-ai2** [comment]
Devil's Advocate: Is this worth the churn?

**Comment by nelson-liu** [comment]
my thinking: if we're deprecating `"bidirectional-language-model"` in #2264 anyway, might as well add the extra alias for `"bidirectional_language_model"` while we're at it?

The reason I want to merge this first is because i thought we were going to make a minor release to get #2257 out, and not sure that #2264 will be done before then.

**Comment by nelson-liu** [comment]
will raise issues for the two points brought up in the discussion.

**Comment by brendan-ai2** [comment]
@nelson-liu, I don't think we should be deprecating public names like this. They serve as an API and users should be able to rely on them. The consistency benefit of having underscores is nice, but minor compared to users being able to rely on code that used to work continuing to work.
