### ISSUE TITLE
Timeline for deprecating top-level token_embedders?

### ISSUE THREAD

**Issue by nelson-liu** [allenai/allennlp#2252]
Specifying token embedders for a BasicTextFieldEmbedder as top-level key-value pairs has been deprecated for awhile now---when are we thinking of removing it for good? Perhaps soon, since the config wizard is out?

Regardless, if we aren't going to immediately remove it, we should probably update the warning https://github.com/allenai/allennlp/blob/3f0953d19de3676ea82e642659fc96d90690e34d/allennlp/modules/text_field_embedders/basic_text_field_embedder.py#L141-L143 to indicate the version it was deprecated, and the version it will be removed.

**Comment by schmmd** [comment]
@brendan-ai2 is planning on putting together a proposed deprecation policy--I thought I'd wait for that before moving forward on this (plus I'm not sure why I self-assigned exactly).

@nelson-liu how would you change the warning text?

**Comment by nelson-liu** [comment]
@schmmd i'd add to the version it was deprecated, and the version it will be removed, just so folks have a heads up

**Comment by nelson-liu** [comment]
and ok, sounds good! looking forward to it @brendan-ai2 , let me know if i can be of help.

**Comment by matt-gardner** [comment]
We're thinking we should probably just remove this deprecation warning.

**Comment by SundeepPidugu** [comment]
Attached a PR #2955 Please check.

**Comment by pidugusundeep** [comment]
Attached a PR #2955, please check.
