### ISSUE TITLE
Contributing a unidirectional language model / working with non-shuffled data

### ISSUE THREAD

**Issue by nelson-liu** [allenai/allennlp#2255]
I'm interested in implementing a unidirectional LM. Is it preferable to:

1. Create a new `UnidirectionalLanguageModel` class to match the current `BidirectionalLanguageModel`?
2. Think about refactoring `BidirectionalLanguageModel` into a single `LanguageModel` class, and adding a `bidirectional` constructor parameter.

@brendan-ai2 kindly went over the `BidirectionalLanguageModel` code with me, and it seems like the changes are fairly minimal to make a `UnidirectionalLanguageModel`. This makes me partial to option 2, but i want to make sure to get others' opinions to ensure i'm not prematurely optimizing.

Furthermore, the `BidirectionalLanguageModel` is set up to handle sentence-shuffled corpora at the moment. I think this is fairly nonstandard, and the majority of LM work outside of ELMo / other papers on contextual word representation trains on corpora of contiguous text (e.g., PTB or WikiText-2).

I'll need to implement a LM that works with corpora of contiguous text in the near future---seems like this might have to be a new model? Thoughts?

**Comment by matt-gardner** [comment]
Option 2 sounds reasonable to me, though others probably have stronger opinions than me about this.

**Comment by brendan-ai2** [comment]
Exploring option 2 first sounds reasonable, but I would timebox it. My suspicion is that you could make that work with a few fairly surgical modifications. But if it starts to get messy and time consuming, then I would suggest just duplicating the code and modifying it as needed.

Let me know if you hit any snags!

**Comment by nelson-liu** [comment]
@brendan-ai2 , i've implemented option 2 in #2264 . Just need to properly deprecate some classes (would like #2253 in beforehand), and it should be ready for review.
