### ISSUE TITLE
PoS tagging with Transformer-based ELMo model

### ISSUE THREAD

**Issue by stefan-it** [allenai/allennlp#2258]
Hi,

I would like to ask if it's possible to train a model PoS tagging model with a transformer-based ELMo model? I recently trained a transformer-based ELMo model for a new language and it worked perfectly.

I wasn't able to find any configuration in `training_config` for PoS tagging with a transformer-based ELMo model, so I really like to know if someone can provide such a configuration?

Thanks in advance,

Stefan

**Comment by schmmd** [comment]
@stefan-it does the instructions in https://github.com/allenai/allennlp/blob/master/tutorials/how_to/training_transformer_elmo.md help?  We also have a tutorial about creating a basic part of speech tagger: https://github.com/allenai/allennlp/tree/master/tutorials/tagger

**Comment by stefan-it** [comment]
Thanks for that hint! I will try that :)
