### ISSUE TITLE
Embeddings from Elmo() and ElmoEmbedder() are very different

### ISSUE THREAD

**Issue by aguglani** [allenai/allennlp#2260]
## Could be conceptual misunderstanding on my part or a bug

I generated Elmo embeddings for a sentence using two different methods:
* first by using the Elmo object
* second by using the embed_sentence() in the ElmoEmbedder object

Here is the code:
```
from allennlp.modules.elmo import Elmo, batch_to_ids
options_file = "https://s3-us-west-2.amazonaws.com/allennlp/models/elmo/2x4096_512_2048cnn_2xhighway/elmo_2x4096_512_2048cnn_2xhighway_options.json"
weight_file = "https://s3-us-west-2.amazonaws.com/allennlp/models/elmo/2x4096_512_2048cnn_2xhighway/elmo_2x4096_512_2048cnn_2xhighway_weights.hdf5"
elmo = Elmo(options_file, weight_file, 2, dropout=0)
character_ids = batch_to_ids(list(['i', 'am', 'flying', 'to', 'new', 'york']))
embeddings_allennlp = elmo(character_ids)

from allennlp.commands.elmo import ElmoEmbedder
ee = ElmoEmbedder()

print(cosine_similarity(ee.embed_sentence(['i', 'am', 'flying', 'to', 'new', 'york'])[2][0].reshape(1, -1),
                       embeddings_allennlp['elmo_representations'][1][0][0].detach().numpy().reshape(1, -1)))
```

The embeddings from both the methods is very different and the cosine_similarity is 0.68. Not able to understand why these two methods produce such different embeddings? I am missing something here/

**Comment by aguglani** [comment]
@nelson-liu thanks for the clarification.

Since the ```len(embeddings_allennlp['elmo_representations'] ==2```, I thought it gives tho top two LSTM layers.

**Comment by nelson-liu** [comment]
yeah, the length of the list indicates how many _different_ weighted-average elmo representations are learned. There's an open pr to make the docs clearer at #2256 .

Closing this for now, feel free to re-open if you have further questions.
