### ISSUE TITLE
nn util is not a package and can't access `arrays_to_variables`

### ISSUE THREAD

**Issue by abitofalchemy** [allenai/allennlp#2262]
**Describe the bug**
`allennlp.nn.util.arrays_to_variables` is broken when running on python3.7 and I get this error: 
`ImportError: cannot import name 'arrays_to_variables' from 'allennlp.nn.util' (/home/sa686/anaconda3/envs/allennlp_spacy/lib/python3.7/site-packages/allennlp/nn/util.py)`

and this returns null: `grep -R 'arrays_to_variables' /home/sa686/anaconda3/envs/allennlp_spacy/lib/python3.7/site-packages/allennlp/*
`

**To Reproduce**
1. `pip install allennlp`
2. `python`
3. `import allennlp.nn.util.arrays_to_variables`

**Expected behavior**
function available

**System (please complete the following information):**
 - OS: Linux
 - Python version:3.7 
 - AllenNLP version: '0.8.1-unreleased'
 - PyTorch version: nightly

**Comment by matt-gardner** [comment]
`arrays_to_variables` was removed more than a year ago, so this is expected behavior.  Where did you see a reference to this function?
