### ISSUE TITLE
Test for import brittleness

### ISSUE THREAD

**Issue by nelson-liu** [allenai/allennlp#2263]
Follow up to #2250 , @brendan-ai2 suggested in https://github.com/allenai/allennlp/issues/2250#issuecomment-450436176 that we should find a way to test for and prevent future import issues.

I think this is a great idea, opening an issue so we can track this suggestion.

**Comment by schmmd** [comment]
We are going to assume these are rare for now, and fix them as we find them.  However, if you hit a similar issue please let us know so we can get more data!
