### ISSUE TITLE
Add bag_of_embeddings as an alternate name for the boe encoder

### ISSUE THREAD

**Issue by nelson-liu** [allenai/allennlp#2268]
Following up from https://github.com/allenai/allennlp/issues/2246#issuecomment-450171162 , we should add `bag_of_embeddings` as another registered name for the `boe` encoder.

**Comment by bryant1410** [comment]
This is fixed, right?

**Comment by nelson-liu** [comment]
Yes, thanks again @saujasv for the patch, and @bryant1410 for reminding me to close this.
