### ISSUE TITLE
Procedure to create conda package

### ISSUE THREAD

**Issue by test9723497834565** [allenai/allennlp#2278]
Hi,

I would like to install version 0.8 with conda but this version is not currently available on https://anaconda.org/allennlp/allennlp

Do you know which step I would have to follow to create the conda package?

I've tried to do "conda skeleton pypi allennlp" but there was an error in my ubuntu on Windows.

Thank you very much.

**Comment by nelson-liu** [comment]
hi sorry, i haven't been able to upload a conda package from 0.8 yet. maybe raise an issue on the conda-forge repo? https://github.com/conda-forge/allennlp-feedstock

**Comment by test9723497834565** [comment]
ok I will do.
