### ISSUE TITLE
Add CI tests for dependency conflicts

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp#2280]
Occasionally AllenNLP has dependency conflicts, see https://github.com/allenai/allennlp/issues/1824 and https://github.com/allenai/allennlp/issues/2195.  We don't catch these conflicts ourselves because pip is rather flexible about how it resolves dependencies, but when we publish releases some of our users run into them (either because they use `poetry` or run conda forge).

Ideally we would run a stricter check ourselves which would allow us to address these issues as they happen--rather than hearing about them after a release.

**Comment by schmmd** [comment]
@sodre @phireski do either of you have a suggestion about a tool we should use to identify dependency conflicts earlier?

**Comment by sodre** [comment]
@schmmd, I asked in the conda-forge gitter channel. I'll report back once I get something.

**Comment by epwalsh** [comment]
FWIW I currently use [pipdeptree](https://github.com/naiquevin/pipdeptree) for this purpose in some of my projects as part of my CI pipeline.

**Comment by epwalsh** [comment]
@schmmd did you happen to look at pipdeptree? This is the exact script I run in CI to check for conflicts:

```
#!/bin/sh
set -e
pipdeptree --warn fail 1>/dev/null
```

**Comment by schmmd** [comment]
@epwalsh thanks for the reminder.  I'll take a look.  I assumed (for some reason) that it draws a tree rather than checks for conflicts.

**Comment by schmmd** [comment]
https://github.com/allenai/allennlp/issues/2195 claimed that v0.7.2 had a dependency conflict that we should have caught.  Unfortunately `pipdeptree --warn fail` does not catch this.

**Comment by matt-gardner** [comment]
@schmmd, any updates here or ideas on how to proceed with this issue?

**Comment by schmmd** [comment]
I have no idea what to do.  Unassigning myself.

**Comment by matt-gardner** [comment]
Adding this to the 1.0 milestone, so we can revisit this issue once we've pruned our dependencies after moving things to sub-repos.  That might just solve the problem.

**Comment by DeNeutoy** [comment]
Marking this as fixed by adding dependabot to our repo, e.g #3623 . This doesn't directly fix this issue, as it's still possible to have conflicting version pins, but this should become more unlikely now the versions we pin to get updated automatically. Also, we didn't have a good alternative solution, because it's a hard problem in general.

Feel free to re-open if we think of a better way to do something about this.
