### ISSUE TITLE
Tutorials README doesn't link to all available tutorials

### ISSUE THREAD

**Issue by nelson-liu** [allenai/allennlp#2284]
The file https://github.com/allenai/allennlp/blob/master/tutorials/README.md doesn't seem to link to all tutorials, including (but maybe not limited to, didn't look closely) https://github.com/allenai/allennlp/blob/master/tutorials/how_to/create_a_configuration.md

**Comment by DumbMachine** [comment]
If Im not mistaken, this asks for providing links for more tutorials at https://github.com/allenai/allennlp/blob/master/tutorials/README.md ?

**Comment by nelson-liu** [comment]
yeah, that file doesn't seem to contain all the available tutorials we have in https://github.com/allenai/allennlp/tree/master/tutorials/how_to

**Comment by DumbMachine** [comment]
Can I take up this issue?

**Comment by nelson-liu** [comment]
sure, go for it! thanks
