### ISSUE TITLE
[Suggestion] Warn default value of `min_padding_length` when using `TokenCharactersIndexer`

### ISSUE THREAD

**Issue by WrRan** [allenai/allennlp#2287]
**Is your feature request related to a problem? Please describe.**
This issue is related to #1954, #2210 and #2044.

**Describe the solution you'd like**
I think it is a better idea to provide _no_ default value of `min_padding_length` in this method, but due to backward compatibility, its default value of `0` is provided.
It may be more friendly to warn users when they use default_value unconsciously.
Does it make sense?

**Additional context**
I am willing to create PR about this.

**Comment by matt-gardner** [comment]
Having a warning about that min padding length seems fine to me.  PR welcome!
