### ISSUE TITLE
Vocabulary  min_count should error when using a nonexistent namespace

### ISSUE THREAD

**Issue by nelson-liu** [allenai/allennlp#2292]
If you use the `min_count` parameter of the `Vocabulary`, but you specify a namespace that does not exist, the vocabulary creation will just silently proceed. It'd be great if it could error in this case, perhaps by popping off the namespaces in `min_count` and erroring if any are left at the end of vocab creation (would probably go at the end of https://github.com/allenai/allennlp/blob/master/allennlp/data/vocabulary.py#L454)?

**Comment by schmmd** [comment]
We agree it'd be great to have a fix here, since a number of us have hit it, but we're not sure what the right solution is presently.

**Comment by saujasv** [comment]
When iterating through token counts in the loop at line 553 (https://github.com/allenai/allennlp/blob/master/allennlp/data/vocabulary.py#L553), the `get` method is used to either get a `min_count` for that namespace, or 1 if that namespace isn't in `min_count`. One way to address this issue would be to have a `try` block that tries to access `min_count[namespace]`. If the namespace doesn't exist, a `KeyError` occurs, and a `ConfigurationError` could be raised. 

An alternate method is iterating through all the keys in `min_count` before the loop at line 553, and checking if that key is in `counter`. If it isn't, a `ConfigurationError` is raised.

If you think either solution is suitable, I could implement it.

**Comment by matt-gardner** [comment]
It seems to me like the second solution is correct - (I think) we want to fall back to a default of 1 for namespaces that aren't mentioned, so the first solution doesn't work.  @nelson-liu, what do you think?

**Comment by nadgeri14** [comment]
@nelson-liu @matt-gardner If this issue is still pending, I would like to take this up. If so, should I go forward with the second approach to solve it?

**Comment by matt-gardner** [comment]
Yes, @nadgeri14, that would be great.  The line numbers referenced above have changed, so the place to do it is probably right above this line, at the top of `_extend`: https://github.com/allenai/allennlp/blob/c9bd9b294df102fd35dc93b62f9c900a142ab297/allennlp/data/vocabulary.py#L436

**Comment by nadgeri14** [comment]
@matt-gardner Thanks, that was really helpful. 

**I need a small help**: Could you please provide a test case, as it will help me to validate my solution before submitting the PR. 

Thanks in advance for the help.

**Comment by matt-gardner** [comment]
You just need a `counter` with some set of keys, and a `min_count` parameter that has keys not present in the `counter`.
