### ISSUE TITLE
Possibly greatly increasing memory usage

### ISSUE THREAD

**Issue by enod** [allenai/allennlp#2294]
**Describe the bug**
I'm trying to reproduce [SST-2](https://github.com/allenai/allennlp/blob/master/training_config/biattentive_classification_network_elmo.jsonnet) with my own dataset. 

**To Reproduce**
My configuration file has following content:
```
{
  "dataset_reader": {
    "type": "yahoo_csv_reader",
    "lazy": true,
    "tokens": 0,
    "label": 1,
    "skip_header": true,
    "token_indexers": {
      "tokens": {
        "type": "single_id",
        "lowercase_tokens": true
    },
      "elmo": {
      "type": "elmo_characters"
    }}
  },
  "train_data_path": "tests/fixtures/biattentive/temp_train.csv",
  "validation_data_path": "tests/fixtures/biattentive/temp_valid.csv",
  "test_data_path": "tests/fixtures/biattentive/temp_test.csv",
  "model": {
    "type": "bcn",
    "text_field_embedder": {
      "token_embedders": {
        "tokens": {
            "pretrained_file": "https://s3-us-west-1.amazonaws.com/fasttext-vectors/word-vectors-v2/cc.ja.300.vec.gz",
            "type": "embedding",
            "embedding_dim": 300,
            "trainable": false
        }
      }
    },
    "embedding_dropout": 0.5,
    "pre_encode_feedforward": {
        "input_dim": 1324,
        "num_layers": 1,
        "hidden_dims": [300],
        "activations": ["relu"],
        "dropout": [0.25]
    },
    "encoder": {
      "type": "lstm",
      "input_size": 300,
      "hidden_size": 300,
      "num_layers": 1,
      "bidirectional": true
    },
    "integrator": {
      "type": "lstm",
      "input_size": 1800,
      "hidden_size": 300,
      "num_layers": 1,
      "bidirectional": true
    },
    "integrator_dropout": 0.1,
    "elmo": {
      "options_file": "elmo_trained/options.json",
      "weight_file": "elmo_trained/weights.hdf5",
      "do_layer_norm": false,
      "dropout": 0.0,
      "num_output_representations": 1
    },
    "use_input_elmo": true,
    "use_integrator_output_elmo": false,
    "output_layer": {
        "input_dim": 2400,
        "num_layers": 3,
        "output_dims": [1200, 600, 2],
        "pool_sizes": 4,
        "dropout": [0.2, 0.3, 0.0]
    }
  },
  "iterator": {
    "type": "bucket",
    "sorting_keys": [["tokens", "num_tokens"]],
    "batch_size" : 32
  },
  "trainer": {
    "num_epochs": 10,
    "patience": 5,
    "grad_norm": 5.0,
    "validation_metric": "+accuracy",
    "cuda_device": [0,1],
    "optimizer": {
      "type": "adam",
      "lr": 0.001
    }
  }
}
```

**System (please complete the following information):**
- OS: Linux
- Python version: 3.6.5
- AllenNLP version: 0.7.2
- PyTorch version: 0.4.1

**Additional context**
During runtime I got:
```
2019-01-07 19:59:17,716 - INFO - elmo_jp.dataset_readers.readers - Reading instances from lines in file at: tests/fixtures/biattentive/temp_train.csv
/mnt/data/elmo/elmo_venv/lib/python3.6/site-packages/allennlp/modules/encoder_base.py:116: UserWarning: RNN module weights are no
t part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact we
ights again call flatten_parameters().
```
And eventually it lead to `RuntimeError: CUDA error: out of memory`

**Comment by nelson-liu** [comment]
what gpu are you using? looks like you might have to either reduce the batch size or the size of the model, since you're running out of gpu memory.

**Comment by nelson-liu** [comment]
looks like @swabhs ran into this as well (#2135). I think this only happens when using multiple GPUs --- would it work for you to just use 1 gpu?

**Comment by enod** [comment]
I'm running on 2 x Geforce GTX 1080 ti 
I made batch size smaller to see what happens. So far it's running fine on the first epoch. If it's not working, I'll try with 1 gpu as you suggested. Thanks a lot!

**Comment by nelson-liu** [comment]
ok! fwiw i was able to train the model on a single gtx 1080 ti. closing this issue now, feel free to ping if you run into further issues.

**Comment by swabhs** [comment]
@nelson-liu Yes, I was also encountering similar issues. The problem with using multiple GPUs is that one GPU does most of the heavy lifting in terms of memory, with the other GPUs maintaining only copies of relevant parameters. And since my model was quite large, the first GPU was OOMing out. Reducing the model size helped quite a lot. Obviously, reducing the batch size might help all GPUs involved.

**Comment by enod** [comment]
@swabhs Thanks for the helpful information. I have successfully trained on 2 GPUs. 
I also tried your patch but got following error:
```
    module.flatten_parameters()
AttributeError: 'function' object has no attribute 'flatten_parameters'
```

**Comment by nelson-liu** [comment]
maybe @brendan-ai2 would have more thoughts on this issue? should we be calling `flatten_parameters()` in the multigpu case, or just leave it alone?

**Comment by swabhs** [comment]
Oops - I thought I removed my patch, didn't realize it was still around. `flatten_parameters()` only works for the inbuilt `pytorch` RNN, I believe. For other modules, it throws an exception. Hope that helps, @enod!

**Comment by enod** [comment]
@nelson-liu / @brendan-ai2 
I've added `self. flatten_parameters() ` on forward method and now the warning is gone.

**Comment by Shuailong** [comment]
> self. flatten_parameters()

I have encountered the same problem. Could you share where did you add the code to?

Thanks!
