### ISSUE TITLE
Check for train/dev/test-data before processing them.

### ISSUE THREAD

**Issue by WrRan** [allenai/allennlp#2295]
**Is your feature request related to a problem? Please describe.**
Sometimes I config the *wrong* test datapath. And I don't know this error until allennlp has processed all the training and validation datasets, which is a little waste of time.

**Describe the solution you'd like**
It may be a good idea to first check the validity of the datapaths before processing them (not including download).

**Additional context**
https://github.com/allenai/allennlp/blob/fb587833084bf8f1a0cb172b5451e21d980f0d5f/allennlp/commands/train.py#L147-L161

My suggestion is to add some checks before Line 161.

**Comment by matt-gardner** [comment]
Seems fine to me.  PR welcome!
