### ISSUE TITLE
Feature request: separate logging for model computed loss and regularization loss in tensorboard

### ISSUE THREAD

**Issue by matt-peters** [allenai/allennlp#2300]
It would be nice to separately log model computed loss from regularization loss in tensorboard. Involves minor changes to the Trainer.

**Comment by tabshaikh** [comment]
@matt-gardner would like to get started on this issue any insights on where to begin :)

**Comment by mklimasz** [comment]
#4008 PR adding regularization loss as separate metric (:

**Comment by dirkgr** [comment]
This is done, no?
