### ISSUE TITLE
Improve documentation of _SoftmaxLoss

### ISSUE THREAD

**Issue by nelson-liu** [allenai/allennlp#2302]
more details at: https://github.com/allenai/allennlp/pull/2264#discussion_r245162745

**Comment by joepalermo** [comment]
It appears that this class now lives here: https://github.com/allenai/allennlp/blob/master/allennlp/modules/softmax_loss.py

From nelson's link, the ask is:
"Can you explicitly document here in the constructor that this class does not add a padding ID, and that the input targets to forward should not include the padding id?" -matt-peters

@matt-peters I'd like to do this and just want to make sure I understand what you mean. I suppose it could be reasonable to assume that a class such as this might add a word into the vocabulary corresponding to a padding ID (i.e. new vocabulary size would be num_words+1), and that the target tensor argument could include such an id. If I’m right about what you mean that does strike me as an unnatural design, and I would be surprised if a user thought that was how it worked. Would you still like this amendment to the documentation included?

Thanks

**Comment by pavingblock1212** [comment]
jasa paving block [https://sentracon.co.id/](url)
