### ISSUE TITLE
Possibly dead code in model.py

### ISSUE THREAD

**Issue by ducalpha** [allenai/allennlp#2306]
**System:**
 - Python version: 3.6
 - AllenNLP version: master branch

**Question**
I believe [line 172 in model.py](https://github.com/allenai/allennlp/blob/088f0bb685231a17320bf916c091dfa8e60e3ce5/allennlp/models/model.py#L172) is redundant. In a past version, the function returns `outputs` so the line is necessary but now the function no longer returns `outputs`.

Also, I think the `list()` wrapper for `list(outputs.items())` on [line 158 in model.py](https://github.com/allenai/allennlp/blob/088f0bb685231a17320bf916c091dfa8e60e3ce5/allennlp/models/model.py#L158) can be removed without any change to the program behavior.

**Comment by schmmd** [comment]
I made a PR for your first point, but in general PRs are welcome!
