### ISSUE TITLE
Update regex if Huggingface fixes a presumed bug in the OpenAI implementation

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp#2317]
https://github.com/allenai/allennlp/pull/2310 changed our regular expressions to match Huggingface's, but it's possible they have a bug in their regular expressions (see https://github.com/huggingface/pytorch-openai-transformer-lm/issues/48).  If https://github.com/huggingface/pytorch-openai-transformer-lm/issues/48 is resolved we should update https://github.com/allenai/allennlp/blob/a83eb8d3f22b5c811dbe6bec9502e8b7090f30dd/allennlp/data/token_indexers/openai_transformer_byte_pair_indexer.py#L25 with their fix.

**Comment by matt-gardner** [comment]
@schmmd, ping.

**Comment by schmmd** [comment]
Cool!  Although I likely won't get to this before my vacation.

**Comment by schmmd** [comment]
Huggingface hasn't made any changes (my issue on their repo is still open)--so there's nothing to do here presently.

**Comment by matt-gardner** [comment]
We're going to be removing that code entirely, in favor of `PretrainedTransformer` stuff.  Closing this issue.
