### ISSUE TITLE
Feeding new sentences to enhance a existing model

### ISSUE THREAD

**Issue by sidneyaraujomelo** [allenai/allennlp#2328]
Hello. First, thanks a lot for this amazing library! I'm beginning to study NLP and so far I'm having a very nice experience with AllenNLP.

My question is about feeding new data to a model in order to enhance it.
For example, I trained a model for a tagging sentences using allennlp.train and that took some time. Now, I've got lots new sentences that I want to feed to this existing model so that it possibly get enhanced. Is that possible?

I'm using allennlp 0.5.1.

Thanks a lot!

**Comment by matt-gardner** [comment]
First, you should upgrade to a more recent version of allennlp - it's really hard for us to support old versions.  We're currently at 0.8.1.

Second, does the `fine-tune` command do what you want?

**Comment by sidneyaraujomelo** [comment]
That's exactly what I need, I think I just missed it when looking through the documentation. Thanks a lot!
