### ISSUE TITLE
doing archive surgery from cmdline

### ISSUE THREAD

**Issue by WrRan** [allenai/allennlp#2329]
**Is your feature request related to a problem? Please describe.**
It relates to #2223, but I want to modify a model.tar.gz from cmdlines instead.

**Describe the solution you'd like**
I am working on it (https://github.com/WrRan/allennlp/blob/f9ca812d16f572fe08021fc5fb7d225ce579e994/scripts/archive_surgery.py). And now it allows users to modify the config file in model.tar.gz:
- adding a new key-value pair
- replacing a value

and does not restrict users from using him as before.

**Describe alternatives you've considered**
This script is also supposed to support users to deleting some keys from cmdline, which is on progress.

**Comment by schmmd** [comment]
@WrRan what do you mean by edit "from cmdlines instead"?

Do note that @joelgrus had quite a different solution back in the version history.  We decided that popping into a text editor would be easier.

**Comment by matt-gardner** [comment]
I think @WrRan is suggesting that the original solution was preferable.  @WrRan, if you like that solution, you could easily get the file from that PR and include it in your repo.

**Comment by WrRan** [comment]
Sorry about my unclear statement. :sob:

When I tried to squelch warnings caused by #2309, I found the script `scripts/archive_surgery.py` (#2223) helpful. But at first I thought it might be more convenient to edit the configuration file in the archive without launching the editor, so I edited the script so that we can edit it like this.
```bash
python script/archive_surgery.py --input-file model.tar.gz --inplace --overrides '{"dataset_reader.token_indexers.token_characters.min_padding_length": 5}'
```

However, I find this "enhancement" may be kind of unnecessary. Because we often inspect the old configuration when we modify it. But the options `--force, --inplace` and the PR #2327 may still be helpful.

-----

Another question is, should I open an issue before proposing PR? Will proposing PR directly cause inconvenience to your work?

Thanks for your attention. And I will also work harder to learn English. 😂

**Comment by matt-gardner** [comment]
For small things, it is just fine to skip opening an issue and just submit a PR. That's easier on us, because it is fewer emails to deal with. For bigger changes, it's a good idea to ask us about them first, so you don't end up doing a bunch of work that needs fixing, or that isn't going to be accepted anyway.

**Comment by matt-gardner** [comment]
Also, I think your original issue has been resolved, so I'm going to close this. Feel free to reopen if you think there's more here.

**Comment by schmmd** [comment]
@WrRan don't worry about it--your English is much better than my Chinese!  When communicating online I ask for clarification when I don't understand since otherwise I might interpret incorrectly (and it's really easy to miscommunicate online).  Your follow up was very clear, thank you.
