### ISSUE TITLE
Separate embedders for multiple inputs

### ISSUE THREAD

**Issue by asaluja** [allenai/allennlp#2333]
**System (please complete the following information):**
 - OS: Linux
 - Python version: 3.6.5
 - AllenNLP version: 0.7.1
 - PyTorch version: 0.4.1

**Question**
I have a multi-modal model of sorts (two different types of inputs) - the first is a standard text input, and the second input is a set of tags associated with the instance e.g., "genre:horror" or "tone:dark". 

As a first step, I want to use `TextField` to map each of these inputs to sequences of integers. I want the token-to-index mappings for these to be separate, so I do the following in my dataset_reader's init:
```
self._token_indexers = {"tokens":  SingleIdTokenIndexer(namespace='tokens')}
self._tag_indexers = {"tags":  SingleIdTokenIndexer(namespace='tags')}
```
Then, when reading in each instance and converting to the index representation, I use the corresponding indexer:
`fields["text"] = TextField(tokenized_input, self._token_indexers)` or `fields["tags"] = TextField(tokenized_input, self._tag_indexers)`. 

This results in the separate mappings as indicated by inspection of the resulting dicts from the calls `self.vocab.get_token_to_index_vocabulary(namespace='tokens')` and `self.vocab.get_token_to_index_vocabulary(namespace='tags')`. There are about 10x as many tokens as tags in my toy example. 

However, I'm having trouble maintaining separate embedders for each of these inputs. In my config I have defined two separate embedders as follows:
```
"text_field_embedder": {
    "tokens": {
                "type": "embedding",
                "pretrained_file": "https://s3-us-west-2.amazonaws.com/allennlp/datasets/glove/glove.6B.100d.txt.gz",
                "embedding_dim": 100,
                "trainable": false
     }
},
"tags_field_embedder": {
    "tags": {
                "type": "embedding",
                "embedding_dim": 16
     }
},
```
But the second embedder seems to instantiate an embedding matrix of size `num_tokens x embedding_dim`, and not `num_tags x embedding_dim`. I was under the impression that as long as the key for the embedder matches the key of the indexer or the namespaces match then we should be fine? Do I need to manually override the `num_embeddings` field in `tags_field_embedder['tags']`? 

Note that this is somewhat different from [this issue](https://github.com/allenai/allennlp/issues/1088) (at least I think) since in that instance we weant to take the same text input and compute two separate representations from it. In my case I have two separate inputs that I want to embed differently (and later on concatenate the resulting embeddings). 

Any thoughts/ideas on what's going on? 

Thanks in advance!
Avneesh

**Comment by joelgrus** [comment]
by default the instantiation of `Embedding.from_params` assumes that you want to use the "tokens" namespace of your vocabulary as the number of embeddings:

https://github.com/allenai/allennlp/blob/master/allennlp/modules/token_embedders/embedding.py#L176

in the second embedding config, add another key

```
"vocab_namespace": "tags"
```

and that should do what you want.

it's unfortunate that this isn't more discoverable.

**Comment by asaluja** [comment]
Thank you! Yes I did look around quite a bit for a line like that but I missed it.
