### ISSUE TITLE
Make `tokens_to_add` accept file path as signature in `OpenaiTransformerBytePairIndexer`?

### ISSUE THREAD

**Issue by tingkai-zhang** [allenai/allennlp#2335]
Hi, I have a task that will add many special tokens to the vocabulary. Some of the special tokens are stored as `List` in a pickle file. Some of the special tokens are like '\_start\_' and '\_calssify\_'.

The `tokens_to_add` signature in `OpenaiTransformerBytePairIndexer` only requires `List[str]`, which means i can't modify the json file to make it work. 

https://github.com/allenai/allennlp/blob/f1600591b6d1567dfbefd6fea4418449ff872090/allennlp/data/token_indexers/openai_transformer_byte_pair_indexer.py#L55

Now my workaround is, to modify the  `OpenaiTransformerBytePairIndexer`  to accept file path as signature. Then store all special tokens as a list in a pickle file. Then pass this file path to initialize the `OpenaiTransformerBytePairIndexer`  

I find that, in order to use json configuration file, sometimes i have to make some variables stored in a file then make corresponding method(`__init__()` of `OpenaiTransformerBytePairIndexer` here) accepting file path as a signature.

By my understanding, json file should better only contain hyper-parameters or methods i choose. 
This line here: https://github.com/allenai/allennlp/blob/f1600591b6d1567dfbefd6fea4418449ff872090/allennlp/data/token_indexers/openai_transformer_byte_pair_indexer.py#L55
however, is allowing to pass a variable `List[str]`. 

I think variables should always stores in a file and make the corresponding method accept file path as function signature, right?
Because it causes problem when the list is too long, like my situation here.

Do you think it is necessary to modify that method in allennlp master to accept file path as signature?

**Comment by joelgrus** [comment]
I would rather not modify that method. We use jsonnet for our configuration files, it seems like a simpler solution would be to use jsonnet imports (see https://jsonnet.org/learning/tutorial.html) to import that list into your config directly. Then everything should work without any code changes?
