### ISSUE TITLE
Make AllenNLP work with pip3 / python3

### ISSUE THREAD

**Issue by nelson-liu** [allenai/allennlp#2338]
It seems like, if your system has `python` linked to python 2.x and `python3` linked to python 3.x, the `allennlp` command fails because it implicitly calls `python` (and thus tries to run allennlp with python 2.x). It should be possible to fall back to `python3` if `python` is detected to be python 2.x?

**Comment by nelson-liu** [comment]
hmm, that logic would have to go in https://github.com/allenai/allennlp/blob/master/bin/allennlp , which is a bash executable. maybe this is also affected by https://github.com/allenai/allennlp/pull/2232

**Comment by joelgrus** [comment]
our instructions are pretty explicit about setting up a Python 3.6 virtual environment. is it still possible to run into this problem if you do that?

**Comment by nelson-liu** [comment]
no, it isn't. Context is that several students in the nlp class at uw have side-by-side installs of python 2 and python 3, and they're all running into issues when they try to `pip3` install. we're recommending that they just go use conda, but it might be nice to make this work as well? if it's nontrivial, it's no big deal. Just seems like a rather odd limitation of the library, that `python` has to be linked to a 3.6>= version.

feel free to close if you don't think this is useful.

**Comment by schmmd** [comment]
It'd be nice to fix if there's a clear solution.  I wonder if https://github.com/allenai/allennlp/pull/2232 addresses this at all.  I have not tried it out, but it doesn't explicitly call `python` so it might not have the same issue.

**Comment by schmmd** [comment]
@nelson-liu I think this is fixed, but I don't have an easy way to test it.

**Comment by nelson-liu** [comment]
i think i can test it, i'll close if fixed.

**Comment by schmmd** [comment]
OK--I actually just had an idea too.

**Comment by schmmd** [comment]
Presently I'm pretty sure you'll get an error if your default `python` is 2.

```
$ allennlp
/usr/bin/python: No module named allennlp
```

**Comment by schmmd** [comment]
This is still an issue, but I'm not sure how to fix it.

**Comment by matt-gardner** [comment]
Closing this as stale. If someone runs into this, please open a new issue.
