### ISSUE TITLE
Elmo embeddings to find most similar words 

### ISSUE THREAD

**Issue by raghadsuliman** [allenai/allennlp#2340]
Hi,

I know that ELMo is intended to be used with  downstream tasks, but I am working on a task to find to similar/related words to a given word. I used to experiment with word2vec to find most similar/closer words to a given word in the embedding space according to cosine similarity.  However, I am wondering if it is possible to approach the problem using ELMo model as a source to find most similar words to a given word.

**To be specific, my question is:** Can ELMo produce a vector space where each unique word in a corpus being assigned a corresponding vector in the space (depend on its context of course) ?

**Comment by schmmd** [comment]
@raghadsuliman yes it is possible.  Using ELMo will be quite similar to word2vec, but with the benefit that ELMo takes a words context into consideration.

**Comment by matt-peters** [comment]
Yes, you can use the contextual representations from the ELMo biLM compute contextual similarity.  See e.g. the word sense disambiguation experiments in the paper (https://aclweb.org/anthology/N18-1202, Table 5) that uses a simple nearest neighbor approach.
