### ISSUE TITLE
How do I access the input token representation and representation from the first hidden layer in elmo?

### ISSUE THREAD

**Issue by vinayshekharcmu** [allenai/allennlp#2343]
I am unable to understand how to use the character embedding when I have to scale the vectors. ELMO embeddings given by the default code has 1024 dimensions. I am guessing this is because of the concatenation of the last layer in the BiLm. If I want to use all the layers including the character convolution layer, how do I access it?

I am using the following piece of code as present in the github repo:

from allennlp.modules.elmo import Elmo, batch_to_ids

options_file = "https://s3-us-west-2.amazonaws.com/allennlp/models/elmo/2x4096_512_2048cnn_2xhighway/elmo_2x4096_512_2048cnn_2xhighway_options.json"
weight_file = "https://s3-us-west-2.amazonaws.com/allennlp/models/elmo/2x4096_512_2048cnn_2xhighway/elmo_2x4096_512_2048cnn_2xhighway_weights.hdf5"

elmo = Elmo(options_file, weight_file, 2, dropout=0)

sentences = [['First', 'sentence', '.'], ['Another', '.']]
character_ids = batch_to_ids(sentences)

embeddings = elmo(character_ids)

**Comment by schmmd** [comment]
@vinayshekharcmu I think https://github.com/allenai/allennlp/blob/master/tutorials/how_to/elmo.md will answer your question.  ELMo returns 3 length 1024 vectors in a batch_size x 3 x 1024 matrix.

**Comment by lecholin** [comment]
> @vinayshekharcmu I think https://github.com/allenai/allennlp/blob/master/tutorials/how_to/elmo.md will answer your question. ELMo returns 3 length 1024 vectors in a batch_size x 3 x 1024 matrix.

ELMo returns 3 because the maxmium sequence length is 3, so your answer may not be true.

**Comment by matt-gardner** [comment]
Yes, @lecholin, I believe you're right.  We unfortunately don't have a great way of just getting this first layer out, it looks like.  For anyone in the future stumbling upon this, see some possibilities [here](https://github.com/allenai/allennlp/issues/1995#issuecomment-483284570).
