### ISSUE TITLE
How to edit the config for CoQA, Thank you!

### ISSUE THREAD

**Issue by guotong1988** [allenai/allennlp#2353]
**System (please complete the following information):**
 - OS: [e.g. OSX, Linux]
win10
 - Python version: [e.g. 3.6.1]
3.6
 - AllenNLP version: [e.g. v0.8.1, or "I installed from master"]
master
 - PyTorch version: (if you installed it yourself)
1.0.0

**Question**
* I search the keyword 'coqa' and can not find something.

**Comment by DeNeutoy** [comment]
This question is too broad - please read some of our documentation/tutorials, find out which model you want to change and then re-open this issue.

**Comment by guotong1988** [comment]
Thank you very much!
