### ISSUE TITLE
Where is the code for abstractive answer? Thank you very much!

### ISSUE THREAD

**Issue by guotong1988** [allenai/allennlp#2354]
![image](https://user-images.githubusercontent.com/4702353/51111263-862e6980-1836-11e9-87ab-b9f32f181bb4.png)

**System (please complete the following information):**
 - OS: [e.g. OSX, Linux]
win10
 - Python version: [e.g. 3.6.1]
3.6
 - AllenNLP version: [e.g. v0.8.1, or "I installed from master"]
master
 - PyTorch version: (if you installed it yourself)
1.0.0

**Question**
* I read the `dialog_qa.py` and have not found the code for abstractive answer.

**Comment by matt-gardner** [comment]
Hi @guotong1988.  We did not write the CoQA paper or any model for it.  I suggest you ask Siva Reddy, the main author of the CoQA paper, for the code that he used.  Though, I also suggest giving more detail in any question you send to him - it's hard to answer such a vague request.

**Comment by guotong1988** [comment]
Thank you very much!
