### ISSUE TITLE
Coding scheme "BIO" corresponds to IOB2 format?

### ISSUE THREAD

**Issue by nijianmo** [allenai/allennlp#2362]
https://github.com/allenai/allennlp/blob/6bd59751e994f18251f69ed432c5f045991c90ed/allennlp/data/dataset_readers/conll2000.py#L51

I found there are different coding scheme defined in conll2000.py ("BIO") and conll2003.py ("IOB1"). The naming of code schemes is not very consistent. Does "BIO" correspond to the IOB2 format? 

Thanks!

**Comment by ZacharySBrown** [comment]
Any update on this? I’m trying to implement a CRFTagger and only seeing IOB1 transitions allowed when I run inference

**Comment by brendan-ai2** [comment]
Sorry for letting this fall through the cracks. I'm not particularly familiar with this code myself, but after taking a peek at the datasets and some comments I believe what we're calling BIO does indeed correspond to IOB2 format. (Based on the definitions here: http://cs229.stanford.edu/proj2005/KrishnanGanapathy-NamedEntityRecognition.pdf)

@ZacharySBrown, could you elaborate? Are you setting https://github.com/allenai/allennlp/blob/master/allennlp/models/crf_tagger.py#L37?

**Comment by ZacharySBrown** [comment]
@brendan-ai2 Thanks for the quick response on this. It was indeed that setting in the `crf_tagger` that I was missing. I had missed that I needed to switch that after I switched from the `conll2003` to the `conll2000` `data_loader`. 
Thanks!

**Comment by brendan-ai2** [comment]
Great! Marking this as closed, but if either of you have any more questions, feel free to comment again.
