### ISSUE TITLE
check to make sure `allennlp.pretrained` models aren't stale

### ISSUE THREAD

**Issue by joelgrus** [allenai/allennlp#2368]
maybe we should replace our sniff test with a test that does this?

(right now the `fine-grained-ner` pretrained model is pointing at an old archive)

**Comment by joelgrus** [comment]
should be pointing at

https://s3-us-west-2.amazonaws.com/allennlp/models/fine-grained-ner-model-elmo-2018.12.21.tar.gz

**Comment by matt-gardner** [comment]
It'd be good to also check the website models somehow...

**Comment by schmmd** [comment]
@joelgrus by stale do you mean "load without an exception"?

I'd like to merge https://allennlp.org/models with the demo so we don't list the models in too many places.  This would also give us a way to test them out (we actually execute them in the demo).

**Comment by joelgrus** [comment]
yes, I mean load without an exception

**Comment by joelgrus** [comment]
actually, the sniff tests are already using `allennlp.pretrained`, they just don't cover every single model in it

**Comment by schmmd** [comment]
@joelgrus do you think we should do more here given your last comment?

**Comment by joelgrus** [comment]
I have mixed feelings, on one hand it would be good for our sniff tests to cover every pretrained model; on the other hand that would make them run even longer

**Comment by schmmd** [comment]
My vote is that we certainly shouldn't do this on every PR--because those tests take too long as it is.

**Comment by matt-gardner** [comment]
At this point I think I'm in favor of just having the sniff tests run on master commits, instead of PRs. What do others think?

**Comment by matt-gardner** [comment]
Pretty sure this is now covered by the hub tests that @brendan-ai2 wrote.  Closing this issue.
