### ISSUE TITLE
embeddings are different on same input: is this common?

### ISSUE THREAD

**Issue by rajarsheem** [allenai/allennlp#2371]
The embeddings are slightly different when run on same input multiple times. Can you please explain why? Am I missing something?

```python
options_file = "https://s3-us-west-2.amazonaws.com/allennlp/models/elmo/2x4096_512_2048cnn_2xhighway/elmo_2x4096_512_2048cnn_2xhighway_options.json"
weight_file = "https://s3-us-west-2.amazonaws.com/allennlp/models/elmo/2x4096_512_2048cnn_2xhighway/elmo_2x4096_512_2048cnn_2xhighway_weights.hdf5"

elmo = Elmo(options_file, weight_file, 1, dropout=0, requires_grad=True).to(T.device('cuda:0'))

sentences = ['1 mxn to usd'.split(' ')]
character_ids = batch_to_ids(sentences).to(T.device('cuda:0'))

elmo.train(False)

for _ in range(2):
    embedding = elmo(character_ids)['elmo_representations'][0]
    print(embedding.sum())
```

Output:

```
tensor(-35.2547, device='cuda:0', grad_fn=<SumBackward0>)
tensor(-32.5144, device='cuda:0', grad_fn=<SumBackward0>)
```

**Comment by matt-peters** [comment]
See https://github.com/allenai/allennlp/blob/master/tutorials/how_to/elmo.md#notes-on-statefulness-and-non-determinism

**Comment by rajarsheem** [comment]
Thanks, got it.

**Comment by rajarsheem** [comment]
I tried to pass a single batch multiple times to my fine-tuned elmo for warming it up and then started making the actual predictions on a different batch. When the second batch was fed multiple times, the predictions were highly varying. Do you know why this might be happening?

**Comment by rajarsheem** [comment]
One more thing I wanted to add: 
embeddings are mostly consistent when I do the same above thing with the public pre-trained elmo model and not my fine-tuned one.

**Comment by rajarsheem** [comment]
@matt-gardner @matt-peters can you please help me with this.
