### ISSUE TITLE
Save embedding when training is done or add a command to extract embedding from weighs file

### ISSUE THREAD

**Issue by robbine** [allenai/allennlp#2378]
Is it possible to save embedding file when train is done ? perhaps we can add an option to specify whether to export trained embeddings and save it in a zipped file. so that we can share it with others.
Or more generally we can add an allennlp command to do the job. for example "allennlp export-embedding" to extract from a serialization folder.

**Comment by matt-gardner** [comment]
This would be pretty easy to do in a script yourself, if you know what your model looks like, and basically impossible to do in general, for any model.  If you're interested in this functionality, just write a script to do it.
