### ISSUE TITLE
intro tutorial should include serialization + config files

### ISSUE THREAD

**Issue by joelgrus** [allenai/allennlp#2379]
people using the intro tutorial are confused (rightly so) about how to serialize the model and re-use it later. we could 

(1) add a section at the end about saving it explicitly, and then
(2) point people to the config file section of the readme, and also
(3) caveat the tutorial with "this isn't how you'd do things in practice" (which is in the README.md tutorial but got lost in translation)

see e.g. #2377

**Comment by schmmd** [comment]
Also related: https://github.com/allenai/allennlp/issues/2311
