### ISSUE TITLE
Pickle vocab of LanguageModel

### ISSUE THREAD

**Issue by stefan-it** [allenai/allennlp#2389]
Hi,

for an integration into a library, I really need to pickle and un-pickle the `BidirectionalLanguageModelTokenEmbedder` and the vocab of its `LanguageModel`.

Here's a code snippet of what I'm trying:

```python
import pickle
from allennlp.modules.token_embedders.bidirectional_language_model_token_embedder import \
    BidirectionalLanguageModelTokenEmbedder
from allennlp.data.token_indexers.elmo_indexer import ELMoTokenCharactersIndexer

class Test:
    def __init__(self):
        self.indexer = ELMoTokenCharactersIndexer()

        self.lm_embedder = BidirectionalLanguageModelTokenEmbedder(
            archive_file="eu-elmo-transformer-model.tar.gz",
            dropout=0.2,
            bos_eos_tokens=("<S>", "</S>"),
            remove_bos_eos=True,
            requires_grad=False
        )

        self.vocab = self.lm_embedder._lm.vocab

    def __getstate__(self):
        state = self.__dict__.copy()

        state["lm_embedder"] = self.lm_embedder.state_dict()

        return state

x = Test()

pickle.dump(x, open("test.pkl", "wb"))
x2 = pickle.load(open("test.pkl", "rb"))
```

But in the un-pickle step the following error message is thrown:

```bash
Traceback (most recent call last):
  File "/home/stefan/Repositories/github.com/flair/debug.py", line 30, in <module>
    x2 = pickle.load(open("test.pkl", "rb"))
TypeError: __init__() missing 3 required positional arguments: 'non_padded_namespaces', 'padding_token', and 'oov_token'
01/18/2019 13:21:07 - INFO - allennlp.models.archival -   removing temporary unarchived model dir at /tmp/tmpmk09leeh
```

I think these positional arguments (which are not set by default) also came up in a code review: https://github.com/allenai/allennlp/pull/75.

How is it possible to sucessfully pickle and un-pickle the `vocab` for a `LanguageModel` 🤔

Thanks!

**Comment by DeNeutoy** [comment]
This looks possibly like a problem with pickling the `lambdas` [here](https://github.com/allenai/allennlp/blob/master/allennlp/data/vocabulary.py#L91) which we use internally in our `Vocabulary` class. Are you able to try using `dill`, which I believe is able to pickle lambdas?

**Comment by joelgrus** [comment]
I think I know how to fix this, PR forthcoming
