### ISSUE TITLE
where can i get pre-training embeddig vectors?

### ISSUE THREAD

**Issue by TamouzeAssi** [allenai/allennlp#2390]
Hello,

I have a task which needs to use pretrained word embedding as a black box. Just give an input word and get back its vector (no trainning needed). I was used pretrained from fasttext. I want to know if there is an already pretrained published according to ELMO.  Does this vectors can be used by gensim library for example.
Thank you in advance

**Comment by schmmd** [comment]
@TamouzeAssi please see https://allennlp.org/elmo and specifically https://github.com/allenai/allennlp/blob/master/tutorials/how_to/elmo.md#using-elmo-interactively.
