### ISSUE TITLE
can elmo generate phrase embeddings?

### ISSUE THREAD

**Issue by A-Rain** [allenai/allennlp#2397]
Recently I'm working on sentiment analysis, and I want to use phrase embeddings rather than single word emebddings. So I'm not sure the following code is correct:
```python
>>> from allennlp.modules.elmo import Elmo, batch_to_ids
>>> sentences = [["I", "feel", "a little", "nervous", "today"]]
>>> options_file = "E:/elmo/strcuture.json"
>>> weight_file = "E:/elmo/weight.hdf5"
>>> salar = [0.5, 0.3, 0.2]
>>> elmo = Elmo(options_file, weight_file, salar, 1, dropout=0)
>>> character_ids = batch_to_ids(sentences)
>>> embeddings = elmo(character_ids)
>>> print(embeddings['elmo_representations'][0])
```
Also, When training my model, should I freeze all elmo parameters or make it trainable?

**Comment by matt-peters** [comment]
To compute phrase embeddings you will need to pool over the individual words in the phrase somehow.  Options here include summing over the words, max pooling, attentive pooling, use the hidden states of the first / last word in the phrase, etc.
