### ISSUE TITLE
LanguageModel should output perplexity

### ISSUE THREAD

**Issue by nelson-liu** [allenai/allennlp#2400]
Is there a reason why `allennlp evaluate` doesn't already output the perplexity? This should be fairly easy to do, since you just take `exp(loss)`.

Seems like it might be tricky during training (@brendan-ai2 made a few notes about it in the code), but for evaluation we'd just need to override `get_metrics`, right?

**Comment by brendan-ai2** [comment]
Isn't perplexity `exp(loss)` only when your loss is entropy? Since this isn't true in general it seems like it would make more sense to have users add perplexity as a metric explicitly. Please correct me if I'm wrong!

**Comment by nelson-liu** [comment]
I see, that seems reasonable. so seems like the fix would be make a `Perplexity` metric, add a new arg to the `LanguageModel` that specifies whether to calculate perplexity or not, and then log the perplexity if said argument is true?

**Comment by brendan-ai2** [comment]
If you'd like! Having a perplexity metric doesn't seem strictly necessary to me, but maybe it's more user friendly to display it. Seems fine to just add it too, no need for a boolean arg. (Should be entirely backwards compatible, no?)

**Comment by nelson-liu** [comment]
yeah, should be backwards compatible, but wasn't your earlier concern that `"perplexity exp(loss) only when your loss is entropy?"` ? Or is that not an issue now, since we're limiting it to `LanguageModel`?

**Comment by brendan-ai2** [comment]
Exactly. This works in `LanguageModel`. Doesn't necessarily work elsewhere. Easy to make this change only there.
