### ISSUE TITLE
how to save weights if I have fine tuned an elmo model?

### ISSUE THREAD

**Issue by woyijkl1** [allenai/allennlp#2403]
hello, I have searched for the answer to this question? but I can not find it. 
thx

**Comment by c4n** [comment]
you can try this:
https://discuss.pytorch.org/t/how-to-load-part-of-pre-trained-model/1113/3 

I'm not sure convert it to  an HDF5 file though.

**Comment by brendan-ai2** [comment]
Hi @woyijkl1, sorry for our glacial reply here. (We're working our way through our issue backlog.) This seems related to https://github.com/allenai/allennlp/issues/2904. In particular, see part 3 of https://github.com/allenai/allennlp/issues/2904#issuecomment-497884358. You won't need to define a language model or anything like that if you already have a method for fine-tuning ELMo that you find suitable. Closing for now, but feel free to comment if you have followup questions.
