### ISSUE TITLE
Feature request: metric for official CoNLL SRL evaluation

### ISSUE THREAD

**Issue by nelson-liu** [allenai/allennlp#2404]
Related to #667 , context is that the `SpanBasedF1Measure` does not exactly match the official conll evaluation perl script's output.

Since we wrap the `evalb` C program in an metric, why can't we do the same for the [`srl-eval.pl`](https://github.com/allenai/allennlp/blob/master/allennlp/tools/srl-eval.pl) script? We can turn it into another metric, and just have it run at validation time (just like evalb does now).

This isn't a solution to the problem, but it at least makes working with the srl model less annoying.

**Comment by joelgrus** [comment]
it has 0 github stars, but here's someone who's written a python version

https://github.com/jgung/srleval

if you trust it, that's even easier

**Comment by nelson-liu** [comment]
"Note, the official evaluation script should be used for any published results." in the README has me worried 😅

**Comment by ducalpha** [comment]
The `_handle_continued_spans` function in `SpanBasedF1Measure` refers to **CoNLL 2012** evaluation script (on [this line](https://github.com/allenai/allennlp/blob/9f87aa56177ef3dc1b0c58ebb49d15584c500e29/allennlp/training/metrics/span_based_f1_measure.py#L189) but I think it should be **CoNLL 2005** instead. CoNLL 2012 shared task evaluates coreference predictions while CoNLL 2005 uses the [`srl-eval.pl`](https://github.com/allenai/allennlp/blob/master/allennlp/tools/srl-eval.pl).

**Comment by nelson-liu** [comment]
@ducalpha sorry for the very belated response on this, you're right! But also worth noting that many SRL papers also evaluate on CoNLL 2005 and CoNLL 2012 (e.g., the paper that the AllenNLP SRL model is based off of: https://www.aclweb.org/anthology/P17-1044)
