### ISSUE TITLE
Machine Comprehension

### ISSUE THREAD

**Issue by sandhiya18** [allenai/allennlp#2408]
How can I use the model obtained after training on a SQUAD data set onto an unsupervised training machine comprehension task? I am expecting a unsupervised fine-tuning task(Transfer Learning). Is this possible or do we always require a supervised task for fine-tuning?

**Comment by matt-gardner** [comment]
There are no off-the-shelf methods for unsupervised fine tuning of a reading comprehension model. You can fine tune using a supervised dataset with `allennlp fine-tune`, but that's it.

**Comment by sandhiya18** [comment]
Thanks @matt-gardner
