### ISSUE TITLE
TimeDistributed's forward method doesn't support some arguments

### ISSUE THREAD

**Issue by bryant1410** [allenai/allennlp#2410]
I see 2 problems with `TimeDistributed`'s `forward` method. They can be seen as 2 separate issues, but as they're strongly correlated, I believe they should be solved together.

The first one is that it doesn't support passing named arguments when calling it. The second one is that it doesn't work with some parameters of the `forward` method of certain wrapped module classes. I'll elaborate on the first one and the second one will arise while explaining.

`TimeDistributed`'s `forward` method not supporting named arguments implies that the method call will work successfully depending on how do you call it, which is not good. For example, if I wrap `PytorchSeq2SeqWrapper` in a `TimeDistributed` instance and then do `time_distributed(inputs=x)`, it will fail. But if I do `time_distributed(x)` it works.

So, it's like the method should grab all positional and keyword parameters and time-distribute them. However, I understand that the `forward` method implementation of some modules have some keyword parameters that should be treated differently if they're wrapped. Hence, the fix is not trivial and it faces other issues. I see 3 kinds of parameters:

1. Parameters that need to be simply time-distributed. Such as `inputs` or `mask` from `PytorchSeq2SeqWrapper`'s `forward` method.

2. Parameters that need to be time-distributed, but require some special treatment. Such as `hidden_state` from `PytorchSeq2SeqWrapper`'s `forward` method. Because `hidden_state` is a tensor of shape `(num_layers, batch_size, hidden_size)`, then the time dimension should be in a different index position than the common case: `(num_layers, batch_size, time, hidden_size)`.

3. Parameters that do not need to be time-distributed. Such as `output_size` of `ConvTranspose2d`'s `forward` method.

I believe that for 2. and 3. we can use some sort of blacklisting when time-distributing params, and give special treatment to them. However, this sounds a bit brittle. What if new modules are added later, with params that require new treatment? This class will constantly need modification.

Another problem is: how to identify the params when they come? `hidden_state` could be passed either as a positional argument or as a named one. So, it's like we should check for the 3rd element of `*inputs` if `self._module` is of type `PytorchSeq2VecWrapper` or for a keyword parameter named `hidden_state` otherwise. This is also very brittle, because the module class can possibly change the order of the params. Maybe it can be solved in part if the docstring of `TimeDistributed` ask parameters to be passed in a certain way.

How can we solve these issues of `TimeDistributed` so it can be used more seamlessly and so it supports params such as `hidden_state` of `PytorchSeq2VecWrapper`'s `forward` method? I'm happy to send a patch if we can find a good solution for this.

**Comment by matt-gardner** [comment]
These are good issues and questions you raise.  My gut reaction, though, is that it's probably not worth the complexity to try to handle all of these cases inside of `TimeDistributed`, when it's relatively simple for someone with a complex use-case to just write a few lines of custom code in their model to handle it.

That is, I think our recommendation should be, if `TimeDistributed` already does what you need, then great, use it.  If you have harder requirements, don't use `TimeDistributed`.

If we _do_ want to do what you're suggesting, I think the most we can reasonably do to support it is to make an API like this:

```python
def forward(self, *inputs, pass_through=None, **kwargs):
    # Handle *inputs as we currently do.
    # Handle **kwargs as we currently handle *inputs, unless the name is in `pass_through`.
    self._module.forward(*reshaped_inputs, **reshaped_kwargs)
```

Hmm, I guess it wouldn't be _that_ complex to support this.  I could probably be convinced that this is ok to add.  What do other people think?

**Comment by HarshTrivedi** [comment]
I also find current `TimeDistributed` to be restrictive because of the mentioned reasons. Most of the times, I had to write extra lines for the special cases. So, +1 for `pass_through` and `**kwargs` solution. This should surely simplify and cleanup some of my code.

**Comment by bryant1410** [comment]
I like that `pass_through` approach.

I also think that the documentation should leave it clear, regardless of adding the pass_through approach or not. For example, if we leave it as it's now, we should say something like "kwargs are not supported", even though it can be deducted from the function header, and maybe also warning that "some args won't work with it, such as 'hidden_state' from PytorchSeq2VecWrapper"

**Comment by matt-gardner** [comment]
@bryant1410, can you send a PR with the above approach?  Make sure you add simple test cases for all of the uses you mentioned in the original issue.

**Comment by bryant1410** [comment]
> @bryant1410, can you send a PR with the above approach? Make sure you add simple test cases for all of the uses you mentioned in the original issue.

Sure.
