### ISSUE TITLE
replace `allennlp elmo` with `allennlp dump-embeddings` or similar

### ISSUE THREAD

**Issue by joelgrus** [allenai/allennlp#2413]
wanting to get the embeddings for some inputs is useful for more than just ELMo, we should consider exposing it

**Comment by schmmd** [comment]
I *might* be able to get around to this sometime, so I'll self-assign for now.  Although it would be `allennlp embeddings` without the `dump` ;-)

**Comment by HarshTrivedi** [comment]
+1, if this can expedite in any way :)

**Comment by matt-gardner** [comment]
@HarshTrivedi, if you still want this, contributions welcome :).

**Comment by matt-gardner** [comment]
This is pretty easy to do with your own script; not sure that we should worry about having it in the library.  Closing this issue.
