### ISSUE TITLE
MultiLabelField's `empty_field` method always fails

### ISSUE THREAD

**Issue by julianmichael** [allenai/allennlp#2415]
**Describe the bug**
MultiLabelField's `empty` method always fails, preventing it from being used with padding.

**To Reproduce**
```python
from allennlp.data.fields import MultiLabelField
f = MultiLabelField([])
f.empty_field()
```
Prints error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/julian/.dotfiles/local/miniconda3/lib/python3.6/site-packages/allennlp/data/fields/multilabel_field.py", line 120, in empty_field
    return MultiLabelField([], self._label_namespace, skip_indexing=True)
  File "/Users/julian/.dotfiles/local/miniconda3/lib/python3.6/site-packages/allennlp/data/fields/multilabel_field.py", line 68, in __init__
    raise ConfigurationError("In order to skip indexing, num_labels can't be None.")
allennlp.common.checks.ConfigurationError: "In order to skip indexing, num_labels can't be None."
```
Also,
```python
f = MultiLabelField([], skip_indexing = True, num_labels = 4)
f.empty_field()
```
throws the same error.

**Expected behavior**
Basically I think the implementation of `empty_field(self)` should be something like:
```python
return MultiLabelField([], self._label_namespace, skip_indexing = self._num_labels is not None, self._num_labels)
```
This way it would bypass the indexing step when possible (i.e., `num_labels` is already known, for example if we're producing an empty field from an already-indexed one), but always do it when necessary (i.e., when `num_labels` is not already known).

**System (please complete the following information):**
 - OS: OSX
 - Python version: 3.6.5
 - AllenNLP version: v0.8.0

**Additional context**
This makes it impossible to use MultiLabelField inside ListField. Surprising that nobody has come across this before but I guess MultiLabelField is not often used...

**Comment by matt-gardner** [comment]
Thanks for finding this; PR welcome!
