### ISSUE TITLE
How to export model and apply it on production ?

### ISSUE THREAD

**Issue by robbine** [allenai/allennlp#2416]
Hi, Does allennlp provide a way to convert a trained model to a serialized representation that can be loaded and executed purely from C++, because of low latencies and strict deployment requirements like on production. I think it would be a big step forward to move on from science experiments to online production if we can add this function.
There is a Torch Script to do the job, but I'm facing some python torch jit problems. Is there some related tutorials ?

**Comment by robbine** [comment]
It seems that allennlp modules only accepts a dict object as input parameter in a forward function.
torch.jit.trace does not support this format.

**Comment by Whu-wxy** [comment]
How to Convert an AllenNLP model and Deploy on Caffe2 and TensorFlow[http://www.realworldnlpbook.com/blog/how-to-convert-an-allennlp-model-and-deploy-on-caffe2-and-tensorflow.html](url)

**Comment by Whu-wxy** [comment]
If we can apply on product without any modification in the future, it will be very convenient.

**Comment by robbine** [comment]
This is so great , thanks a lot !
