### ISSUE TITLE
Different behavior of dataset reader during training and validation

### ISSUE THREAD

**Issue by nika2312** [allenai/allennlp#2417]
I'm working on a dataset which I would like to be read differently during training and validation (different behavior when the context length is longer than max_context_size, for example).
What is the best way to run such kind of training? I thought of the following options:

1. Passing a boolean parameter to the dataset_reader constructor. 
2. Creating 2 separate dataset_readers, one for the training and one for the validation dataset.

Currently I'm constructing and running the trainer explicitly from all the relevant parts in the config dict (model, iterator etc.) and the datasets which are being read differently.
Is there a way to do this using the json config file only? I would love to hear the guidelines for this case.

Thanks!

**Comment by matt-gardner** [comment]
You can specify a validation dataset reader in the config file.
