### ISSUE TITLE
remove all custom from_params

### ISSUE THREAD

**Issue by joelgrus** [allenai/allennlp#2419]
ideally none of our classes would need custom from_params. this would require changing constructors to match the fields that from_params is looking for.

so, for instance, you'd have to change `Vocabulary.__init__` to match the things that are happening in `Vocabulary.from_params` -- the current constructor could be moved to a factory method `Vocabulary.from_counts` or similar.

This would be a breaking change for anyone who's instantiating these classes directly, although it would be a simple fix if they just had to replace the calls to the constructor to the calls with factory methods.

**Comment by joelgrus** [comment]
this is complicated by the fact that some things get constructed in a way that depends on earlier things (there was an issue or comment about that somewhere but I can't find it now)
this will require cleverness

**Comment by matt-gardner** [comment]
https://github.com/allenai/allennlp/pull/2304#discussion_r247355998

**Comment by joelgrus** [comment]
thanks

**Comment by brendan-ai2** [comment]
@joelgrus thinks this may not be possible. Closing.
