### ISSUE TITLE
Unable to create ELMO object - OS Error or HTTPS error

### ISSUE THREAD

**Issue by lazyprgmr** [allenai/allennlp#2434]
I am having two sets of problems when trying to create an ELMO object

1) 

> gaierror                                  Traceback (most recent call last)
> ~/Documents/generic_nlidb/experiments/nlidb_test_venv/lib/python3.6/site-packages/urllib3/connection.py in _new_conn(self)
>     158             conn = connection.create_connection(
> --> 159                 (self._dns_host, self.port), self.timeout, **extra_kw)
>     160 
> 
> ~/Documents/generic_nlidb/experiments/nlidb_test_venv/lib/python3.6/site-packages/urllib3/util/connection.py in create_connection(address, timeout, source_address, socket_options)
>      56 
> ---> 57     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
>      58         af, socktype, proto, canonname, sa = res
> 
> /usr/lib/python3.6/socket.py in getaddrinfo(host, port, family, type, proto, flags)
>     744     addrlist = []
> --> 745     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
>     746         af, socktype, proto, canonname, sa = res
> 
> gaierror: [Errno -3] Temporary failure in name resolution
> 
> During handling of the above exception, another exception occurred:
> 
> NewConnectionError                        Traceback (most recent call last)
> ~/Documents/generic_nlidb/experiments/nlidb_test_venv/lib/python3.6/site-packages/urllib3/connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
>     599                                                   body=body, headers=headers,
> --> 600                                                   chunked=chunked)
>     601 
> 
> ~/Documents/generic_nlidb/experiments/nlidb_test_venv/lib/python3.6/site-packages/urllib3/connectionpool.py in _make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
>     342         try:
> --> 343             self._validate_conn(conn)
>     344         except (SocketTimeout, BaseSSLError) as e:
> 
> ~/Documents/generic_nlidb/experiments/nlidb_test_venv/lib/python3.6/site-packages/urllib3/connectionpool.py in _validate_conn(self, conn)
>     838         if not getattr(conn, 'sock', None):  # AppEngine might not have  `.sock`
> --> 839             conn.connect()
>     840 
> 
> ~/Documents/generic_nlidb/experiments/nlidb_test_venv/lib/python3.6/site-packages/urllib3/connection.py in connect(self)
>     300         # Add certificate verification
> --> 301         conn = self._new_conn()
>     302         hostname = self.host
> 
> ~/Documents/generic_nlidb/experiments/nlidb_test_venv/lib/python3.6/site-packages/urllib3/connection.py in _new_conn(self)
>     167             raise NewConnectionError(
> --> 168                 self, "Failed to establish a new connection: %s" % e)
>     169 
> 
> NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f1714300940>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution
> 
> During handling of the above exception, another exception occurred:
> 
> MaxRetryError                             Traceback (most recent call last)
> ~/Documents/generic_nlidb/experiments/nlidb_test_venv/lib/python3.6/site-packages/requests/adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
>     448                     retries=self.max_retries,
> --> 449                     timeout=timeout
>     450                 )
> 
> ~/Documents/generic_nlidb/experiments/nlidb_test_venv/lib/python3.6/site-packages/urllib3/connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
>     637             retries = retries.increment(method, url, error=e, _pool=self,
> --> 638                                         _stacktrace=sys.exc_info()[2])
>     639             retries.sleep()
> 
> ~/Documents/generic_nlidb/experiments/nlidb_test_venv/lib/python3.6/site-packages/urllib3/util/retry.py in increment(self, method, url, response, error, _pool, _stacktrace)
>     397         if new_retry.is_exhausted():
> --> 398             raise MaxRetryError(_pool, url, error or ResponseError(cause))
>     399 
> 
> MaxRetryError: HTTPSConnectionPool(host='s3-us-west-2.amazonaws.com', port=443): Max retries exceeded with url: /allennlp/models/elmo/2x4096_512_2048cnn_2xhighway/elmo_2x4096_512_2048cnn_2xhighway_options.json (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1714300940>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
> 
> During handling of the above exception, another exception occurred:
> 
> ConnectionError                           Traceback (most recent call last)
> <ipython-input-9-ee7be03e8c01> in <module>
> ----> 1 elmo = Elmo(options_file, weight_file, 2, dropout=0)
> 
> ~/Documents/generic_nlidb/experiments/nlidb_test_venv/lib/python3.6/site-packages/allennlp/modules/elmo.py in __init__(self, options_file, weight_file, num_output_representations, requires_grad, do_layer_norm, dropout, vocab_to_cache, keep_sentence_boundaries, scalar_mix_parameters, module)
>     108                                         weight_file,
>     109                                         requires_grad=requires_grad,
> --> 110                                         vocab_to_cache=vocab_to_cache)
>     111         self._has_cached_vocab = vocab_to_cache is not None
>     112         self._keep_sentence_boundaries = keep_sentence_boundaries
> 
> ~/Documents/generic_nlidb/experiments/nlidb_test_venv/lib/python3.6/site-packages/allennlp/modules/elmo.py in __init__(self, options_file, weight_file, requires_grad, vocab_to_cache)
>     522         super(_ElmoBiLm, self).__init__()
>     523 
> --> 524         self._token_embedder = _ElmoCharacterEncoder(options_file, weight_file, requires_grad=requires_grad)
>     525 
>     526         self._requires_grad = requires_grad
> 
> ~/Documents/generic_nlidb/experiments/nlidb_test_venv/lib/python3.6/site-packages/allennlp/modules/elmo.py in __init__(self, options_file, weight_file, requires_grad)
>     301         super(_ElmoCharacterEncoder, self).__init__()
>     302 
> --> 303         with open(cached_path(options_file), 'r') as fin:
>     304             self._options = json.load(fin)
>     305         self._weight_file = weight_file
> 
> ~/Documents/generic_nlidb/experiments/nlidb_test_venv/lib/python3.6/site-packages/allennlp/common/file_utils.py in cached_path(url_or_filename, cache_dir)
>      96     if parsed.scheme in ('http', 'https', 's3'):
>      97         # URL, so get it from the cache (downloading if necessary)
> ---> 98         return get_from_cache(url_or_filename, cache_dir)
>      99     elif os.path.exists(url_or_filename):
>     100         # File, and it exists.
> 
> ~/Documents/generic_nlidb/experiments/nlidb_test_venv/lib/python3.6/site-packages/allennlp/common/file_utils.py in get_from_cache(url, cache_dir)
>     184         etag = s3_etag(url)
>     185     else:
> --> 186         response = requests.head(url, allow_redirects=True)
>     187         if response.status_code != 200:
>     188             raise IOError("HEAD request failed for url {} with status code {}"
> 
> ~/Documents/generic_nlidb/experiments/nlidb_test_venv/lib/python3.6/site-packages/requests/api.py in head(url, **kwargs)
>      99 
>     100     kwargs.setdefault('allow_redirects', False)
> --> 101     return request('head', url, **kwargs)
>     102 
>     103 
> 
> ~/Documents/generic_nlidb/experiments/nlidb_test_venv/lib/python3.6/site-packages/requests/api.py in request(method, url, **kwargs)
>      58     # cases, and look like a memory leak in others.
>      59     with sessions.Session() as session:
> ---> 60         return session.request(method=method, url=url, **kwargs)
>      61 
>      62 
> 
> ~/Documents/generic_nlidb/experiments/nlidb_test_venv/lib/python3.6/site-packages/requests/sessions.py in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
>     531         }
>     532         send_kwargs.update(settings)
> --> 533         resp = self.send(prep, **send_kwargs)
>     534 
>     535         return resp
> 
> ~/Documents/generic_nlidb/experiments/nlidb_test_venv/lib/python3.6/site-packages/requests/sessions.py in send(self, request, **kwargs)
>     644 
>     645         # Send the request
> --> 646         r = adapter.send(request, **kwargs)
>     647 
>     648         # Total elapsed time of the request (approximately)
> 
> ~/Documents/generic_nlidb/experiments/nlidb_test_venv/lib/python3.6/site-packages/requests/adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
>     514                 raise SSLError(e, request=request)
>     515 
> --> 516             raise ConnectionError(e, request=request)
>     517 
>     518         except ClosedPoolError as e:
> 
> ConnectionError: HTTPSConnectionPool(host='s3-us-west-2.amazonaws.com', port=443): Max retries exceeded with url: /allennlp/models/elmo/2x4096_512_2048cnn_2xhighway/elmo_2x4096_512_2048cnn_2xhighway_options.json (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1714300940>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))

2) 

> Traceback (most recent call last):
>   File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/home/rnty/Documents/generic_nlidb/experiments/nlidb_test_venv/lib/python3.6/site-packages/allennlp/run.py", line 18, in <module>
>     main(prog="allennlp")
>   File "/home/rnty/Documents/generic_nlidb/experiments/nlidb_test_venv/lib/python3.6/site-packages/allennlp/commands/__init__.py", line 72, in main
>     args.func(args)
>   File "/home/rnty/Documents/generic_nlidb/experiments/nlidb_test_venv/lib/python3.6/site-packages/allennlp/commands/elmo.py", line 367, in elmo_command
>     elmo_embedder = ElmoEmbedder(args.options_file, args.weight_file, args.cuda_device)
>   File "/home/rnty/Documents/generic_nlidb/experiments/nlidb_test_venv/lib/python3.6/site-packages/allennlp/commands/elmo.py", line 164, in __init__
>     self.elmo_bilm = _ElmoBiLm(options_file, weight_file)
>   File "/home/rnty/Documents/generic_nlidb/experiments/nlidb_test_venv/lib/python3.6/site-packages/allennlp/modules/elmo.py", line 524, in __init__
>     self._token_embedder = _ElmoCharacterEncoder(options_file, weight_file, requires_grad=requires_grad)
>   File "/home/rnty/Documents/generic_nlidb/experiments/nlidb_test_venv/lib/python3.6/site-packages/allennlp/modules/elmo.py", line 310, in __init__
>     self._load_weights()
>   File "/home/rnty/Documents/generic_nlidb/experiments/nlidb_test_venv/lib/python3.6/site-packages/allennlp/modules/elmo.py", line 398, in _load_weights
>     self._load_char_embedding()
>   File "/home/rnty/Documents/generic_nlidb/experiments/nlidb_test_venv/lib/python3.6/site-packages/allennlp/modules/elmo.py", line 404, in _load_char_embedding
>     with h5py.File(cached_path(self._weight_file), 'r') as fin:
>   File "/home/rnty/Documents/generic_nlidb/experiments/nlidb_test_venv/lib/python3.6/site-packages/h5py/_hl/files.py", line 394, in __init__
>     swmr=swmr)
>   File "/home/rnty/Documents/generic_nlidb/experiments/nlidb_test_venv/lib/python3.6/site-packages/h5py/_hl/files.py", line 170, in make_fid
>     fid = h5f.open(name, flags, fapl=fapl)
>   File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
>   File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
>   File "h5py/h5f.pyx", line 85, in h5py.h5f.open
> OSError: Unable to open file (truncated file: eof = 254224793, sblock->base_addr = 0, stored_eof = 374434792)

Kindly help.

**Comment by DeNeutoy** [comment]
The Elmo model downloads weights if you don't specify a path - it looks like your connection was interrupted when you downloaded them and they have become corrupted. please remove `~/.allennlp` and try again - you need connection to the internet also.

**Comment by jwc19890114** [comment]
> The Elmo model downloads weights if you don't specify a path - it looks like your connection was interrupted when you downloaded them and they have become corrupted. please remove `~/.allennlp` and try again - you need connection to the internet also.

Thx, I have fixed it by your approach.
Removed the files in /.allennlp
