### ISSUE TITLE
How to run a custom function at the end of each epoch while using Trainer?

### ISSUE THREAD

**Issue by ynandwan** [allenai/allennlp#2435]
While using the Trainer class to train the model, I want to run a custom function after the end of each epoch. For example, I want to dynamically change the weight for each training sample based on certain criteria and in order to do that I want to iterate over the entire training set at the end of each epoch with ```torch.no_grad()```. 
To achieve this, I ended up extending Trainer class and added a small piece of code in the end of its train function. Is there a better way?

**Comment by joelgrus** [comment]
right now that's probably the best way to do that.

**Comment by ynandwan** [comment]
Thanks Joel, for the quick response. I really appreciate it.

**Comment by brendan-ai2** [comment]
This may also be addressed in the future in https://github.com/allenai/allennlp/issues/2587. Closing as a duplicate for now.
