### ISSUE TITLE
How to reproduce the supervised openie paper number on openie2016?

### ISSUE THREAD

**Issue by mingtan888** [allenai/allennlp#2436]
Hi, 

I am trying to reproduce the numbers of `supervised open information extraction` `http://www.aclweb.org/anthology/N18-1081`, which show the 62% F1-score (61% precision, 64% recall), and 48% AUC  on `https://allennlp.org/models#open-information-extraction`
However I met following issues:

1. The prediction output from `https://allennlp.org/models#open-information-extraction` don't have the confidences of the output, which is needed for AUC curve. Is there any configurations to generate the confidence output? 

2. Second, the paper claims they are using matching functions for evaluation in the paper like this `To that end, we follow He et al. (2015) which judge an argument as correct if and only if it includes the syntactic head of the gold argument (and similarly for predicates).   For OIE2016, we use the available Penn Treebank gold syntactic trees (Marcus et al., 1993), while for the other test sets, we use predicted trees instead.` I wonder if there is any place that implement this particular matching functionality. 

Thanks a lot.

**Comment by schmmd** [comment]
@gabrielStanovsky are you able to answer this question?  Also--I'm curious--what do the PR numbers for Open IE on http://model-ci.allennlp.org/ correspond to?

**Comment by gabrielStanovsky** [comment]
Yes, looking into it now.

**Comment by gabrielStanovsky** [comment]
@mingtan888 
1.) Precision and recall metrics are trained to maximize F1 (@schmmd, that's how the F1 score reported in that link is computed, per token prediction). The AUC metric requires a confidence score, which is currently indeed not reported. I think that's a good feature request. 

2.) The syntactic head metric was originally used to get the results reported in the paper. Later on, I simplified the token-level matching, as it didn't rely on a specific syntactic parser and provided similar results. Specifically, the ranking of the different systems with the new metric remained the same. This is reported in the changelog in the [benchmarking repo](https://github.com/gabrielStanovsky/oie-benchmark#changelog).
