### ISSUE TITLE
SpanBasedF1Measure throws ValueError

### ISSUE THREAD

**Issue by shyamupa** [allenai/allennlp#2437]
I am using the `semantic_role_labeler` for training on the CONLL 2005 dataset, which uses the `SpanBasedF1Measure`. I noticed that the `_handle_continued_spans` method throws the following error for some `predicted_spans`. 

```python
File "shyamupa/allennlp/allennlp/models/semantic_role_labeler.py", line 149, in forward
    self.span_metric(class_probabilities, tags, mask)
  File "shyamupa/allennlp/allennlp/training/metrics/span_based_f1_measure.py", line 173, in __call__
    predicted_spans = self._handle_continued_spans(predicted_spans)
  File "shyamupa/allennlp/allennlp/training/metrics/span_based_f1_measure.py", line 213, in _handle_continued_spans
    span_start = min(span[1][0] for span in continued_spans)
ValueError: min() arg is an empty sequence
```
I found that the offending `predicted_string_labels` (from which the `predicted_spans` are extracted) that lead to the above behavior  was the following
```
['B-C-A0', 'B-C-A4', 'B-AM', 'B-AM-NEG', 'I-AM-PRD', 'B-R-A0', 'I-', 'B-C-V', 'I-C-AM-ADV
', 'I-AM-PRD', 'B-A1', 'B-AM-ADV', 'B-AM-ADV', 'I-AM-PRD', 'B-C-A0', 'B-C-A0', 'B-R-A2',
'B-A1', 'B-C-A0', 'B-A1', 'B-A0', 'B-C-AM-PNC', 'I-AM-PRD', 'I-AM-PRD', 'I-AM-PRD', 'I-AM
-DIS', 'I-AA', 'I-AM-DIS', 'B-R-A2', 'B-C-A0', 'B-C-A0', 'B-AM-DIR', 'B-C-A0', 'B-C-A0',
'I-AM-PRD', 'I-AM-ADV', 'B-R-AM-MNR', 'I-AM-PRD', 'I-R-AM-TMP', 'B-R-AM-MNR', 'I-R-AM-TMP
', 'B-C-A0', 'B-C-A0', 'B-AM-ADV', 'B-C-A4', 'B-C-A0', 'B-C-V', 'B-V', 'B-R-A2', 'I-AM-PR
D']
```
I am sure this sequence of tags is violating some contract set by the continued span labels that start with "C-", but this should not be the desired behavior of a evaluation metric (it should be capable of evaluating both legal and illegal tag sequences).

**To Reproduce**
This is tricky, because the function call to `span_metric` expects a tensor. I encountered this when I was training on the CONLL 2005 dataset with the parameter setting described in [this paper](https://aclanthology.info/papers/P17-1044/p17-1044). If it helps, I can provide the jsonnet config file I am using.

**System (please complete the following information):**
 - OS: Linux
 - Python version: 3.7.2
 - AllenNLP version: 0.8.2-unreleased
 - PyTorch version: 1.0.0

**Comment by shyamupa** [comment]
Found out that I had a rogue "I-" tag that was messing things up. Closing.

**Comment by danlou** [comment]
Hi @shyamupa , I'm going through the same issue. Can you give some more details about that rogue "I-" tag? Was it in one of the Ontonotes files?
Thanks

**Comment by shyamupa** [comment]
No. It was from one of the CoNLL shared tasks (05 or 04). The reason for the rogue tags was a bug in the dataset reader.

**Comment by danlou** [comment]
Yeah, sorry, I should have read your post more carefully, you'd already said it.
My dataset reader is based on the ["srl"](https://github.com/allenai/allennlp/blob/master/allennlp/data/dataset_readers/semantic_role_labeling.py) provided with AllenNLP, I'll have to look into it.

Thanks!
