### ISSUE TITLE
Allow config file overrides in `evaluate`

### ISSUE THREAD

**Issue by matt-gardner** [allenai/allennlp#244]
And other places where we load models.  Actually, because this is going through to `load_archive`, that method itself has to allow overrides, and any entry point that reaches `load_archive` needs a way to pass in overrides.

**Comment by schmmd** [comment]
@matt-gardner what do you mean exactly by `evaluate`?  `allennlp/run evaluate` or a particular method?  Why do you need the ability to override here?

**Comment by matt-gardner** [comment]
Yeah, I meant the command.  See #246 for the original motivation for this.  Not really sure how necessary this is anymore...  (The whole [`_sanitize_config()`](https://github.com/allenai/allennlp/blob/83d0253cd1bcba18b9fe31961146a8e81c0eae8c/allennlp/models/archival.py#L52-L66) method can probably be removed at this point, actually.)  I haven't recently run into a situation where I really wished I had this.  I know @OyvindTafjord ran into it a lot more frequently, though.

**Comment by schmmd** [comment]
My WIP change https://github.com/allenai/allennlp/pull/402 support overriding fields, but does not support removing fields.

**Comment by matt-gardner** [comment]
But that parameter was removed a long time ago, so that particular use case is no longer present.  You could also override it with `None` to effectively remove it (which means you should probably do something like our `replace_none` method in your override code).

**Comment by schmmd** [comment]
The original motivation for this issue is moot.

**Comment by matt-gardner** [comment]
I just talked with Oyvind, and he brought up a few cases where being able to change test-time configuration is helpful, and is currently a huge pain.

- Changing the batch size, because, e.g., the test data has some really long sentences
- Trying hacks with padding, like what Oyvind did to the character CNN in BiDAF

These cases are pretty rare, though.  We may want to open this issue again at some point in the future, but for now there's not enough motivation for it.
