### ISSUE TITLE
AllenNLP MC model: how the speedup has been achieved?

### ISSUE THREAD

**Issue by mkaze** [allenai/allennlp#2440]
**Question**

In the Models section of AllenNLP website, it has been stated that: "AllenNLP MC model is a **reimplementation** of BiDAF (Seo et al, 2017) ... The AllenNLP BIDAF model achieves an EM score of 68.3 on the SQuAD dev set, just **slightly ahead** of the original BIDAF system’s score of 67.7, while also training at a **10x speedup**" (emphasis mine)

So the way I understand it is that the only difference compared to the original BiDAF model is the training speedup, right? Further, I could not find any explanation or a paper describing the difference in more details and explaining how the speedup has been achieved. So I was wondering is there such a thing available at all? Thanks!

**Comment by DeNeutoy** [comment]
Hi,

The training speedup from Bidaf was actually achieved by intelligent batching. The original implementation batched instances randomly, whereas in AllenNLP, they are sorted by length (with some random noise added) and then batched, meaning there is much less padding, as instances batched together are of roughly the same length.
