### ISSUE TITLE
Is it appropriate to instantiate the class `Activation` directly?

### ISSUE THREAD

**Issue by WrRan** [allenai/allennlp#2442]
**System (please complete the following information):**
- OS: Linux
- Python version: 3.6.7
- AllenNLP version: 0.8.1-unreleased
- PyTorch version: 1.0.0

**Question**
When I tried to add some modules that depend on `FeedForward` for this library, I found that it was not possible to instantiate this class properly and quickly due to its parameter `activations` of class `Activation`.

Details:
Following the test case:
https://github.com/allenai/allennlp/blob/00c877b9b8737d547f845bac5d5c69a86d6177e7/allennlp/tests/modules/feedforward_test.py#L14-L16

create and run the following code snippet:
```python
import torch
from allennlp.modules import FeedForward

feedforward = FeedForward(input_dim=10,
                          num_layers=1,
                          hidden_dims=5,
                          activations='linear')

x = torch.randn([1, 2, 10])
y = feedforward(x)
```
we will get this error:
```txt
TypeError: 'str' object is not callable
```

That is because we neither provide subclasses for `Activation` nor a helper function to transform `str` to correct objects. (see the file https://github.com/allenai/allennlp/blob/master/allennlp/nn/activations.py)

Did I miss anything? If not, I prefer a helper function as a solution. Looking forward to hearing from you.

**Comment by WrRan** [comment]
I created a patch for this in my repo (https://github.com/WrRan/allennlp/tree/correct_feedforward_init). So I will create a PR if you think it is a good idea.

PS: I am going to sleep. It is 2:40 a.m. now. =(

**Comment by nelson-liu** [comment]
Sure, sounds good! goodnight 🌔 
i'll close this issue for now, feel free to make the PR whenever is convenient for you / ping me for review
