### ISSUE TITLE
How to train a dependency parsing model with my new dataset?

### ISSUE THREAD

**Issue by odek53r** [allenai/allennlp#2445]
I want to train my own dependency parsing model, but I can't find examples. In the document, I find a command called as allennlp.commands.train with many parameters. I don't know how to set the parameters and what data should look like. If anyone can help, I will appreciate it.

**Comment by Oneplus** [comment]
You can download the parser model, unzip it, modify the `config.json`, then run `allennlp train -s model_path config.json`

You need to specify the paths to your treebank (in CoNLL-X/CoNLL-U format) in the `"train_data_path"` and `"validation_data_path"` fields.

I've attached a config.json, hope it help.
[config.json.txt](https://github.com/allenai/allennlp/files/2802424/config.json.txt)

**Comment by odek53r** [comment]
It's very helpful for me. Thank your very much. The script can work well now with CPU, but it seems very slow. Do you know how to set paramaters for GPU version?

**Comment by odek53r** [comment]
I find the cuda_device parameter in the config file. Thank you.
