### ISSUE TITLE
Running train_model() multiple times without exiting will keep logging new runs to old files

### ISSUE THREAD

**Issue by Hyperparticle** [allenai/allennlp#2452]
When running [`train_model()`](https://github.com/allenai/allennlp/blob/e08ade81ff6684869883ce3da66941b9d3a37503/allennlp/commands/train.py#L138), the file handle to old log files will stay open after exiting the function and keep writing subsequent logs to it. This is problematic since it will clutter older log files with log output from newer training runs, as well as write GBs of data to disk after several runs.

More specifically, `train_model()` calls [`prepare_global_logging()`](https://github.com/allenai/allennlp/blob/e08ade81ff/allennlp/common/util.py#L212), which assigns `sys.stdout` and `sys.stderr` [`TeeLogger`](https://github.com/allenai/allennlp/blob/e08ade81ff/allennlp/common/tee_logger.py#L22:7)s. They never get cleaned up, and so get nested after each call to `train_model()`.

My initial guess would be to add something like the following to the end of `train_model()`:

```python
logging.getLogger().removeHandler(stdout_handler)
sys.stdout.log.close()
sys.stdout = sys.stdout.terminal
sys.stderr.log.close()
sys.stderr = sys.stderr.terminal
```

**Comment by matt-gardner** [comment]
Seems reasonable to me to add a parallel `cleanup_global_logging()` method, that contains whatever logic is necessary and is called at the end of `train_model()`.  PRs welcome.

**Comment by Hyperparticle** [comment]
Cool, I'll try a PR tomorrow. The only potential obstacle I see is to remove the `stdout_handler`, which is currently discarded. Should it be returned from `prepare_global_logging()`?
