### ISSUE TITLE
max_vocab_size does not account for @@UNKNOWN@@

### ISSUE THREAD

**Issue by nelson-liu** [allenai/allennlp#2453]
It seems like `max_vocab_size` does not account for `@@UNKNOWN@@` when building the vocab --- is this intentional, or should it be counted as a bug?

**Comment by schmmd** [comment]
@matt-gardner would you consider this a bug?

**Comment by matt-gardner** [comment]
I don't know; I don't have a strong opinion on what the default should be here, as long as it's documented.

**Comment by brendan-ai2** [comment]
Sounds like we're all agreeing to stick with the status quo. @nelson-liu, could you document this in a comment?
