### ISSUE TITLE
Problem Training Transformer ELMo

### ISSUE THREAD

**Issue by pvcastro** [allenai/allennlp#2455]
I'm having problems training the Transformer version of ELMo. I'm using the same dataset I used for training the portuguese bilm-tf version of ELMo, but I'm following exactly the steps and files mentioned in [the tutorial](https://github.com/allenai/allennlp/blob/master/tutorials/how_to/training_transformer_elmo.md).

This is the command I'm running:

`allennlp train /home/models/elmo/training_config/bidirectional_language_model.jsonnet --serialization-dir /home/models/elmo/transformer-pt`

The training_config I'm using is exactly the same in the repository, didn't change anything, just set the number of cpus to 4. I know that there is a warning for using multiple gpus, but tried setting to 1 and the problem happened anyway.

Here is what is being logged:

[stdout.log](https://github.com/allenai/allennlp/files/2807792/stdout.log)

What is peculiar in my scenario is that I'm using an IBM machine with architecture ppc64le, using 4 Tesla V100 SXM2. The OS is ubuntu 18.04, Python  and pytorch 1.0.0. AllenNLP version is also 
- OS: ubuntu 18.04
- Python version: 3.6.8 from Anaconda3
- AllenNLP version: I installed from master
- PyTorch version: 1.0.0

The GPU usage never got passed beyond this, and the process doesn't stop or anything, just keeps hanging without logging anything. Not sure if there is any training actually going on, since nothing changes and the GPU usage seems low. I left like this for about 3 or 4 days before killing the process manually.

![nvidia-smi-ibm-transformer-elmo](https://user-images.githubusercontent.com/12713359/51910850-7dea3880-23b7-11e9-8b6e-0db6e2026f15.png)

I tried running this training on my desktop, to see if it could maybe be a problem with the python and hardware from IBM, but I couldn't figure out what to change in the training config file to fit the data in my 1070's 8Gb memory. Tried setting the batch size to this, but got CUDA out of memory errors anyway:

```
local BASE_ITERATOR = {
  "type": "bucket",
  "max_instances_in_memory": 16384 * NUM_GPUS,
  // Larger than we really desire for a batch. Since we set
  // maximum_samples_per_batch below we will pack approximately that many
  // samples in every batch.
  "batch_size": 2 * NUM_GPUS,
  "sorting_keys": [["source", "num_tokens"]],
  "maximum_samples_per_batch": ["num_tokens", 2000]
};
```

**Comment by stefan-it** [comment]
To test it locally, you shoud reduce the size of the vocabulary. 

For the IBM setup: I had one experiment, where the training process stuck. Then I used `"output_queue_size": 100` and it was working.

**Comment by pvcastro** [comment]
Thanks @stefan-it ! Do you mean the output_queue_size in the iterator part? There are two, the other one is in dataset_reader.

**Comment by stefan-it** [comment]
@pvcastro Oh, sorry, I mean the `output_queue_size` in the iterator, so the section looks like:

```json
"iterator": {
    "type": "multiprocess",
    "base_iterator": BASE_ITERATOR,
    "num_workers": NUM_THREADS,
    // The multiprocess dataset reader and iterator use many file descriptors,
    // so we need to increase the ulimit depending on the size of this queue.
    // See https://pytorch.org/docs/stable/multiprocessing.html#file-descriptor-file-descriptor
    // for a description of the underlying issue. `ulimit -n 4096` has sufficed,
    // but that number could use tuning.
    "output_queue_size": 100
  },
```

Normally, the data loader is very fast. It is definitely not normal that you have to wait a few days to get any progress.

**Comment by pvcastro** [comment]
Tried that for both 1 and 4 GPUs but ended up getting the same problem. Just got it sooner. Not sure if it's relevant, but my vocab size is over 800k. The same vocab and corpus were trained OK in bilm-tf.

**Comment by pvcastro** [comment]
Ran the notebook there to train the multi-gpu and the training was OK, using the 4 GPUs.

I'll try reducing the vocab size to run locally. Do you have an estimate of how much it should be for GTX 1070 with 8Gb?

**Comment by stefan-it** [comment]
The training corpus has a size of 37,926,708 tokens. One epoch (ELMo Transformer) took ~ 2 hours on a RTX 2080 TI. A RTX 2070 is ~ 30 % slower than a RTX 2080 TI, but I have no comparison experience for a GTX 1070.

**Comment by pvcastro** [comment]
I see. So, did you mean that the **vocabulary size** should be smaller, or the **training corpus** altogether?

**Comment by stefan-it** [comment]
When the vocab size is too large, you normally get torch error messages saying that you should be new RAM (means local RAM not GPU RAM). My setup has only 32 GB of RAM, so on larger datasets I had to limit the vocab size.

But when you're getting CUDA out of memory errors then you should use a smaller batch size for the data loader configuration :)

**Comment by pvcastro** [comment]
Yeah, I was getting CUDA out of memory errors. I tried going all the way down to a batch_size 1 and still got out of memory errors with my local setup. What other parameter in the jsonnet config would contribute to decreasing the batch size?

**Comment by pvcastro** [comment]
I got run locally using a batch size of 2, keeping everything else the same. However, it ran for 33 hours, just loading data from the DatasetReaders, and ended up throwing a CUDA out of memory error. I don't think an epoch actually ended. 
As for the IBM setup, I recreated the docker environment again, installing AllenNLP from master instead of pip, and started with a batch size of 4 and all 4 GPUs, keeping everything else with default values. I then started to increase the batch size to see the point where it would fill the GPUs RAM. However, for some reason, **increasing the batch size from 4 to 32 didn't make any difference**, and the GPUs look very underused. Here's how they are looking:
![image](https://user-images.githubusercontent.com/12713359/52115031-b88ce480-25f4-11e9-8dff-17739fcd4bce.png)
How could I make them more efficient?
At least the training is actually going on now, 2 epochs ended, each lasted 8 hours and 9 minutes.

**Comment by schmmd** [comment]
@brendan-ai2 any idea why the GPUs would look very underused?

**Comment by brendan-ai2** [comment]
@pvcastro, in general for this configuration you should not be modifying `batch_size` at all. Like the comment says:
```
  // Larger than we really desire for a batch. Since we set
  // maximum_samples_per_batch below we will pack approximately that many
  // samples in every batch.
  "batch_size": 512 * NUM_GPUS,
```

If you set `batch_size` to be small you will underutilize your GPU while still occasionally getting CUDA OOMs when you hit a very long sentence. Instead, keep `batch_size` as in the default configuration and modify `maximum_samples_per_batch`. The other key piece of configuration is `max_sequence_length` in the dataset reader. See https://github.com/allenai/allennlp/blob/master/training_config/bidirectional_language_model.jsonnet#L24. Depending on your setup you may also need to decrease that. Be aware, however, that it discards sentences over that limit, so you'll not be training on your full dataset.

Also, are you using AllenNLP to build the vocabulary or are you constructing it in a manner analogous to the tutorial?

**Comment by pvcastro** [comment]
> Instead, keep `batch_size` as in the default configuration and modify `maximum_samples_per_batch`

So, if the GPUs are underused, I should **increase** the maximum samples per batch untill they are filled?

> Depending on your setup you may also need to decrease that.

If I have some GPU memory left, why should I **decrease** the max_sequence_length?

> Also, are you using AllenNLP to build the vocabulary or are you constructing it in a manner analogous to the tutorial?

Yes, I had the same vocabulary I used to train the bilm-tf version of ELMo, and then used it to build the vocabulary folder following the tutorial, for the Transformer version. Is this ok?

Thanks!

**Comment by brendan-ai2** [comment]
> > Instead, keep `batch_size` as in the default configuration and modify `maximum_samples_per_batch`
> 
> So, if the GPUs are underused, I should **increase** the maximum samples per batch untill they are filled?

That's correct. There may still be some imbalance, however, as (IIUC) the optimizer is resident on only one GPU.
> 
> > Depending on your setup you may also need to decrease that.
> 
> If I have some GPU memory left, why should I **decrease** the max_sequence_length?
> 

If you are still seeing CUDA OOMs, you can try decreasing this. The transformer is quadratic in terms of memory usage, so in theory you could see OOMs for a batch with a single long sequence even when you wouldn't for a batch with the same number of tokens split across multiple sequences.

> > Also, are you using AllenNLP to build the vocabulary or are you constructing it in a manner analogous to the tutorial?
> 
> Yes, I had the same vocabulary I used to train the bilm-tf version of ELMo, and then used it to build the vocabulary folder following the tutorial, for the Transformer version. Is this ok?

Yep, that's good. We had some inefficiency around automatic vocab construction. (I need to check whether this is still an issue.)
> 
> Thanks @brendan-ai2 !

Sure thing!

**Comment by pvcastro** [comment]
I'm closing this issue for now, since I was able to train the model, even if I couldn't get to trying the suggestions from @brendan-ai2 . I'll reopen if necessary. Thanks!
