### ISSUE TITLE
predicting paper venues tutorial has mismatch between md and code

### ISSUE THREAD

**Issue by nelson-liu** [allenai/allennlp#2457]
We have a markdown version of the predicting paper venues tutorial at https://github.com/allenai/allennlp/blob/master/tutorials/getting_started/predicting_paper_venues/predicting_paper_venues_pt1.md , but we also host the code at https://github.com/allenai/allennlp-as-a-library-example/blob/master/my_library/models/academic_paper_classifier.py .

A student pointed out that there are differences between the two, which confused them. Should they be synced? Which one should be synced to the other?

As an aside, I think the code needs to be updated to reflect the latest allennlp release...it might be currently broken due to flaky/pytest issues.

**Comment by schmmd** [comment]
I think @nelson-liu addressed this in https://github.com/allenai/allennlp-as-a-library-example/pull/20 through https://github.com/allenai/allennlp-as-a-library-example/pull/27.
