### ISSUE TITLE
remove matplotlib dependency (just don't produce plots if it isn't available)

### ISSUE THREAD

**Issue by joelgrus** [allenai/allennlp#2459]
I heard from someone who would like to run allennlp but without taking the flask dependency. Unfortunately, now that `allennlp configure` is a top-level command, it's impossible to run the `allennlp` command without flask being imported.

It should be a simple (if slightly ugly) fix to make this import conditional on flask being available.

**Comment by epwalsh** [comment]
I have a similar request for `matplotlib`. It's huge package that is only used for the `find-lr` command, so I'd like to avoid installing it when possible. A potential solution would be to only import the sub-module corresponding to the sub-command when the sub-command is called.

**Comment by matt-gardner** [comment]
Original issue is fixed by #3526. Keeping the issue open until we remove `matplotlib`, which we should definitely do for the 1.0 release.
