### ISSUE TITLE
AllenNLP with bert with latest model

### ISSUE THREAD

**Issue by sandtemp01** [allenai/allennlp#2461]
Please first search our GitHub repository for similar questions.  If you don't find a similar example you can use the following template:

**System (please complete the following information):**
 - OS: [e.g. OSX, Linux] Windows, Linux
 - Python version: [e.g. 3.6.1] 3.6
 - AllenNLP version: [e.g. v0.8.1, or "I installed from master"] 0.8.1
 - PyTorch version: (if you installed it yourself)

**Question**
My AllenNLP version is 0.8.1,  using Machine comprehension as mentioned in [https://allennlp.org/models](https://allennlp.org/models) with model bidaf-model-2017.09.15-charpad.tar.gz

1. We just observed that you are using BERT transformers. Please confirm it this is correct?
2. If yes, then am I using latest model (bidaf-model-2017.09.15-charpad.tar.gz)?
3. My results of QnA and my BERT results are different (BERT better). What am i missing?
4. There are new demos added like wikitable, QuaRel. How can we use these, these are not listed in [https://allennlp.org/models](https://allennlp.org/models)?

**Comment by matt-gardner** [comment]
The BiDAF model does not use BERT.

On the new demos you mentioned - we haven't updated the models page with them yet; we're thinking of redesigning some things so they are less likely to get out of sync like they are now.  Those models in particular are not useful unless you are doing in research in those areas.  In absolute terms, the performance is quite poor (as are all models on those tasks; these are things NLP can't do very well yet).  If you _are_ doing research in semantic parsing, I can give you some more details.
