### ISSUE TITLE
bidirectional_language_model_transformer is registered in an odd location

### ISSUE THREAD

**Issue by nelson-liu** [allenai/allennlp#2462]
Looks like `BidirectionalLanguageModelTransformer` is being registered as `bidirectional_language_model_transformer` in the `__init__.py` of `seq2seq_encoders` (https://github.com/allenai/allennlp/blob/5560466e46266568ade2f86179fe0049cf31a981/allennlp/modules/seq2seq_encoders/__init__.py#L96-L98) . 

why not just use the `@Model.register("bidirectional_language_model_transformer")` decorator? If there's a reason, we should include it as a comment in the `__init__.py`

**Comment by brendan-ai2** [comment]
I don't think so. I'll clean it up!
