### ISSUE TITLE
AllenNLP Stuck on "Initializing ELMo" with PySpark

### ISSUE THREAD

**Issue by r-clancy** [allenai/allennlp#2477]
**Describe the bug**
When using PySpark locally with more than 1 worker, AllenNLP hangs on the following: `02/03/2019 14:39:51 - INFO - allennlp.modules.elmo -   Initializing ELMo`

When using a single worker, everything works as expected. For example, using `--master "local[1]"` (use 1 worker) when submitting the job or calling `repartition(1)` (shuffle data around so it's sent to one worker) before using AllenNLP seems to work. 

However, using `--master "local[*]"` (use worker = # cores) it hangs.

**To Reproduce**
Loading the model:
```
def __init__(self, gpu):
        self.nlp = load("en", disable=["tagger", "ner"])
        self.archive = load_archive("https://s3-us-west-2.amazonaws.com/allennlp/models/ner-model-2018.12.18.tar.gz", cuda_device=gpu)
        self.predictor = Predictor.from_archive(self.archive)
```

The code calling this creates the object the constructor belongs to in a `mapPartitions` with the intention of doing NER over all the text in the partition - nothing fancy.

`rdd = sc.textFile(args.collection).mapPartitions(<my_func>)`

**Expected behavior**
AllenNLP shouldn't hang and should work when using multiple workers. Does this have to do with the way AllenNLP loads models?

**System (please complete the following information):**
 - OS: Linux
 - Python version: Python 3.6.7
 - AllenNLP version: 0.8.1 (latest from pip)

**Comment by DeNeutoy** [comment]
I doubt that this is allennlp specific - I don't think Pytorch functions that well under multiprocessing scenarios, e.g https://pytorch.org/docs/stable/notes/multiprocessing.html#best-practices-and-tips. Either way, I'm not sure we're going to be too much help in fixing the issue unfortunately, as we don't use Spark locally. AllenNLP is first and foremost a research library, so we haven't explored many of these types of applications in depth at all. If you do figure out why that is happening, definitely send a PR!
