### ISSUE TITLE
sentence_id in ontonotes reader class/documentation

### ISSUE THREAD

**Issue by pitrack** [allenai/allennlp#2478]
Not really a question/bug/feature request, just a minor comment.

In general, the `sentence_id` variable https://github.com/allenai/allennlp/blob/e5a74abccb969efe33001e20b8c749780d8f657e/allennlp/data/dataset_readers/dataset_utils/ontonotes.py#L22-L23 should be more accurately named something like `part_num`, following the spec for ontonotes 5.0. https://github.com/allenai/allennlp/blob/e5a74abccb969efe33001e20b8c749780d8f657e/allennlp/data/dataset_readers/dataset_utils/ontonotes.py#L138-L139 In particular, this value is definitely not the sentence id.

**Comment by brendan-ai2** [comment]
Thanks for pointing this out, but at this point it's probably going to cause more churn than it's worth to fix.
