### ISSUE TITLE
Train SRL model with CoNLL2012 data

### ISSUE THREAD

**Issue by acDante** [allenai/allennlp#2485]
Hi, I am trying to train a SRL model with allennlp using the following command:
```
allennlp train ./allennlp/training_config/semantic_role_labeler.jsonnet --serialization-dir ./allennlp_output
```
In the configuration file I set the SRL_TRAIN_DATA_PATH and SRL_VALIDATION_DATA_PATH to be the CoNLL2012 formatted data but I got the following error during the start of training:

>  Traceback (most recent call last):
  File "/scratch/users/duxi/miniconda3/envs/allennlp/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/scratch/users/duxi/miniconda3/envs/allennlp/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/scratch/users/duxi/miniconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/run.py", line 18, in <module>
    main(prog="allennlp")
  File "/scratch/users/duxi/miniconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/commands/__init__.py", line 72, in main
    args.func(args)
  File "/scratch/users/duxi/miniconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/commands/train.py", line 111, in train_model_from_args
    args.force)
  File "/scratch/users/duxi/miniconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/commands/train.py", line 144, in train_model_from_file
    return train_model(params, serialization_dir, file_friendly_logging, recover, force)
  File "/scratch/users/duxi/miniconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/commands/train.py", line 293, in train_model
    all_datasets = datasets_from_params(params)
  File "/scratch/users/duxi/miniconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/commands/train.py", line 161, in datasets_from_params
    train_data = dataset_reader.read(train_data_path)
  File "/scratch/users/duxi/miniconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/data/dataset_readers/dataset_reader.py", line 76, in read
    "Is the path correct?".format(file_path))
allennlp.common.checks.ConfigurationError: 'No instances were read from the given filepath /scratch/users/duxi/SRL/master/official/conll2012.train.txt. Is the path correct?'

I am not sure if this error is caused by incorrect input format, the CoNLL2012 data in the input files has the following format: 

```

bc/cctv/00/cctv_0001   0   0           This    DT  (TOP(S(NP*         -    -   -   Speaker#1        *   (ARG2*   (61
bc/cctv/00/cctv_0001   0   1            map    NN           *)        -    -   -   Speaker#1        *        *)   61)
bc/cctv/00/cctv_0001   0   2      reflected   VBD        (VP*    reflect  01   1   Speaker#1        *      (V*)    -
bc/cctv/00/cctv_0001   0   3            the    DT        (NP*         -    -   -   Speaker#1        *   (ARG1*     -
bc/cctv/00/cctv_0001   0   4       European    JJ           *         -    -   -   Speaker#1    (NORP)       *     -
bc/cctv/00/cctv_0001   0   5    battlefield    NN           *         -    -   -   Speaker#1        *        *     -
bc/cctv/00/cctv_0001   0   6      situation    NN           *))       -    -   -   Speaker#1        *        *)    -
bc/cctv/00/cctv_0001   0   7              .     .           *))       -    -   -   Speaker#1        *        *     -
```

**Comment by acDante** [comment]
Thanks for the help ! :-) I changed the file path into directory path and it works now

**Comment by Huijun-Cui** [comment]
@acDante @DeNeutoy  how to set  SRL_TRAIN_DATA_PATH ?  just replace it with a string file path ?

**Comment by nelson-liu** [comment]
> how to set SRL_TRAIN_DATA_PATH ? just replace it with a string file path ?

That refers to an environment variable, so you could do something like:

```
export SRL_TRAIN_DATA_PATH=somepath
allennlp train <rest of the command here>
```

**Comment by Huijun-Cui** [comment]
@nelson-liu  hi  I tried this data format for whole day , would you please help me . I assume you are Chinese . 
我是这样做的 ， 根据这个页面的链接 
[](https://github.com/allenai/allennlp/blob/e5a74abccb969efe33001e20b8c749780d8f657e/allennlp/data/dataset_readers/dataset_utils/ontonotes.py#L83)

我也同样制作的了一个目录 ， 并在每个目录下面手动创建了一个文件名叫 cctv_001.v4_.gold_conll
然后文件名里面 复制粘贴了 
bc/cctv/00/cctv_0001   0   0           This    DT  (TOP(S(NP*         -    -   -   Speaker#1        *   (ARG2*   (61
bc/cctv/00/cctv_0001   0   1            map    NN           *)        -    -   -   Speaker#1        *        *)   61)
bc/cctv/00/cctv_0001   0   2      reflected   VBD        (VP*    reflect  01   1   Speaker#1        *      (V*)    -

然后我把semantic_role_labeler.jsonnet 里面的的文件地址改写成这样
"train_data_path": "datasets/conll-formatted-ontonotes-5.0/data/train/cctv_001.v4_.gold_conll",
  "validation_data_path": "datasets/conll-formatted-ontonotes-5.0/data/test/cctv_001.v4_.gold_conll"  

但是提示错误依然是 : 'No instances were read from the given filepath datasets/conll-formatted-ontonotes-5.0/data/train/cctv_001.v4_.gold_conll. Is the path correct?'


这个代码你跑通了吗？  我现在是想把我自己的数据换成conll的数据格式 ，跑我自己的代码， 可不可以把你的数据格式（数据只要部分展示就可以）以及  semantic_role_labeler.jsonnet  里面data path设置方法告诉我一下  用你的github 或者 截图给我或者 邮箱 cuihuijun@foxmail.com  非常希望您能帮我

**Comment by Huijun-Cui** [comment]
@DeNeutoy  would you help me , thakns

**Comment by omerarshad** [comment]
how to get ontonotes data? can we fine tune SRL model on our own data?

**Comment by francesca418** [comment]
I am also trying to train the AllenNLP SRL model on the ontonotes data. I currently have all files in the form .gold_skel - I want to use the ontonotes.py to convert the data into the right format for training - is the correct thing to do, to use ontonotes.py on the entire data directory? Should I use the _process_span_annotations_for_word method?

Also when I try to train, passing in a directory as the train path, I get an error saying that the train path points to a directory - but isnt it supposed to recursively search for all training files in a directory?
