### ISSUE TITLE
Beam search fails if empty sequence is predicted

### ISSUE THREAD

**Issue by leonweber** [allenai/allennlp#2486]
**Describe the bug**
Beam search fails if empty sequence is predicted

**To Reproduce**
At prediction time, if the first prediction of the model is `self._end_index` beam search is aborted due to
```python
# If every predicted token from the last step is `self._end_index`,
# then we can stop early.
if (last_predictions == self._end_index).all():
    break
```
which leads to `backpointers` being empty and triggering
```
cur_backpointers = backpointers[-1]
IndexError: list index out of range
```

**Expected behavior**
Evaluation should not crash if this is the case.

**System (please complete the following information):**
 - OS: Linux
 - Python version: 3.6.8
 - AllenNLP version: 0.8.1
 - PyTorch version: 1.0.1

**Additional context**
I fixed it locally by changing the line to `if (last_predictions == self._end_index).all() and timestep > 0:`. Is this correct, or does it lead to other problems?

**Comment by matt-gardner** [comment]
Hey, sorry this issue slipped by us, we've been having a hard time keeping up with issues recently.  My gut reaction to this is that you should handle the error after search instead of modifying the search directly, but I'd have to play around with it myself to really be sure of that.

**Comment by epwalsh** [comment]
@matt-gardner FWIW I agree this edge case is probably something that the user should catch and avoid, but maybe it's worth throwing in a check for this in `BeamSearch.search` and throwing a `RuntimeError` in that case? At least then a helpful error message is spit out.

**Comment by matt-gardner** [comment]
That sounds like a good solution to me.  PR welcome!
