### ISSUE TITLE
get code to pass recent versions of mypy

### ISSUE THREAD

**Issue by joelgrus** [allenai/allennlp#2489]
right now it doesn't, so we're pinned to 0.521

**Comment by joelgrus** [comment]
I'm probably going to propose this as Q3 work, right now I'm messing around with using Protocols / structural subtyping, and the version of mypy we're pinned to doesn't seem to do much with them, while the most recent version finds errors

**Comment by matt-gardner** [comment]
This was fixed a while ago.
