### ISSUE TITLE
How can I train a BiAffine dependency parser on my own if I have the data?

### ISSUE THREAD

**Issue by ichn-hu** [allenai/allennlp#2492]
Please first search our GitHub repository for similar questions.  If you don't find a similar example you can use the following template:

**System (please complete the following information):**
 - OS: [e.g. OSX, Linux]
 - Python version: [e.g. 3.6.1]
 - AllenNLP version: [e.g. v0.8.1, or "I installed from master"]
 - PyTorch version: (if you installed it yourself)

**Question**
I would like to train the biaffine parser on my own instead of using the pretrained model, and I do have the data, how can I do it? It seems that there is no such configuration file under training_config/

**Comment by Oneplus** [comment]
please refer issue https://github.com/allenai/allennlp/issues/2445

**Comment by DeNeutoy** [comment]
Ah sorry let me upload a config for the one we have in the demo. As @Oneplus said, you can also grab the config from inside the model archive if you are in a rush 😄

**Comment by DeNeutoy** [comment]
Closed  by https://github.com/allenai/allennlp/pull/2639
