### ISSUE TITLE
Translate notebook deepdives into web tutorials

### ISSUE THREAD

**Issue by DeNeutoy** [allenai/allennlp#2500]

**Comment by schmmd** [comment]
Something to note is that, in the past, when we had more tutorials on our website we had issues with the tutorials and our library getting out of sync.  Hosting more tutorials in our GitHub repository mitigated this issue, although they are admittedly less pretty.  I love how our featured tutorial looks, but I worry that if we hosted more tutorials on our website we would run into the same issue again.

**Comment by matt-gardner** [comment]
A bunch of things are stable and shouldn't change, because of our deprecation policy.  Those things are good targets for more tutorials like the one we currently have on the website.

**Comment by matt-gardner** [comment]
We're covering this with a new allennlp course, so we're closing this issue.
