### ISSUE TITLE
how to turn off INFO messages sent to console (loading SRL model)

### ISSUE THREAD

**Issue by rfernand2** [allenai/allennlp#2506]
Please first search our GitHub repository for similar questions.  If you don't find a similar example you can use the following template:

**System (please complete the following information):**
 - OS: [e.g. Windows]
 - Python version: [3.6.7]
 - AllenNLP version: "I installed from master"]
 - PyTorch version: 1.0.1

**Question**
* I am calling "Predictor.from_path()" on the SRL model in my python app (as per docs example 
 at https://allennlp.org/models).  When I run, I see over 100 timestamped INFO messages being sent to the console.  I want to control the output of my app (for clean debugging and for release to users).  How can I turn off these messages (and make room for my own console output)?  Thanks in advance. *

**Comment by matt-gardner** [comment]
You probably want something like this: https://github.com/allenai/allennlp/blob/9f87aa56177ef3dc1b0c58ebb49d15584c500e29/allennlp/common/testing/test_case.py#L30-L33

**Comment by rfernand2** [comment]
Thanks – that filtered the 150 or so to the below 15 – any idea what to disable to suppress these?

(py36) c:\github\BiasedTPRN\srl_generator>python dataset_analyze.py
02/13/2019 17:40:29 - INFO - allennlp.models.archival -   loading archive file https://s3-us-west-2.amazonaws.com/allennlp/models/srl-model-2018.05.25.tar.gz from cache at C:\Users\rfernand\.allennlp\cache\88a963eed085eb23ea78b083dbc304830c27193e439ff1c899290f02e76c0e82.e9f9e059da2ca307f6ee5835c4e2b0a43b1eed2cb8685c5741a0b16249269ff1
02/13/2019 17:40:29 - INFO - allennlp.models.archival -   extracting archive file C:\Users\rfernand\.allennlp\cache\88a963eed085eb23ea78b083dbc304830c27193e439ff1c899290f02e76c0e82.e9f9e059da2ca307f6ee5835c4e2b0a43b1eed2cb8685c5741a0b16249269ff1 to temp dir C:\Users\rfernand\AppData\Local\Temp\tmpx2aowcg6
02/13/2019 17:40:46 - INFO - allennlp.data.vocabulary -   Loading token dictionary from C:\Users\rfernand\AppData\Local\Temp\tmpx2aowcg6\vocabulary.
02/13/2019 17:40:46 - INFO - allennlp.common.from_params -   instantiating class <class 'allennlp.models.model.Model'> from params {'encoder': {'type': 'alternating_lstm', 'input_size': 1124, 'hidden_size': 300, 'num_layers': 8, 'recurrent_dropout_probability': 0.1, 'use_input_projection_bias': False}, 'type': 'srl', 'regularizer': [['.*scalar_parameters.*', {'type': 'l2', 'alpha': 0.001}]], 'initializer': [['tag_projection_layer.*weight', {'type': 'orthogonal'}]], 'binary_feature_dim': 100, 'text_field_embedder': {'elmo': {'type': 'elmo_token_embedder', 'dropout': 0.1, 'do_layer_norm': False, 'options_file': 'C:\\Users\\rfernand\\AppData\\Local\\Temp\\tmpx2aowcg6\\fta/model.text_field_embedder.elmo.options_file', 'weight_file': 'C:\\Users\\rfernand\\AppData\\Local\\Temp\\tmpx2aowcg6\\fta/model.text_field_embedder.elmo.weight_file'}}} and extras {'vocab': Vocabulary with namespaces:  labels, Size: 129 || tokens, Size: 69816 || Non Padded Namespaces: {'*labels', '*tags'}}
02/13/2019 17:40:46 - INFO - allennlp.common.from_params -   instantiating class <class 'allennlp.models.semantic_role_labeler.SemanticRoleLabeler'> from params {'encoder': {'type': 'alternating_lstm', 'input_size': 1124, 'hidden_size': 300, 'num_layers': 8, 'recurrent_dropout_probability': 0.1, 'use_input_projection_bias': False}, 'regularizer': [['.*scalar_parameters.*', {'type': 'l2', 'alpha': 0.001}]], 'initializer': [['tag_projection_layer.*weight', {'type': 'orthogonal'}]], 'binary_feature_dim': 100, 'text_field_embedder': {'elmo': {'type': 'elmo_token_embedder', 'dropout': 0.1, 'do_layer_norm': False, 'options_file': 'C:\\Users\\rfernand\\AppData\\Local\\Temp\\tmpx2aowcg6\\fta/model.text_field_embedder.elmo.options_file', 'weight_file': 'C:\\Users\\rfernand\\AppData\\Local\\Temp\\tmpx2aowcg6\\fta/model.text_field_embedder.elmo.weight_file'}}} and extras {'vocab': Vocabulary with namespaces:  labels, Size: 129 || tokens, Size: 69816 || Non Padded Namespaces: {'*labels', '*tags'}}
02/13/2019 17:40:46 - INFO - allennlp.common.from_params -   instantiating class <class 'allennlp.modules.text_field_embedders.text_field_embedder.TextFieldEmbedder'> from params {'elmo': {'type': 'elmo_token_embedder', 'dropout': 0.1, 'do_layer_norm': False, 'options_file': 'C:\\Users\\rfernand\\AppData\\Local\\Temp\\tmpx2aowcg6\\fta/model.text_field_embedder.elmo.options_file', 'weight_file': 'C:\\Users\\rfernand\\AppData\\Local\\Temp\\tmpx2aowcg6\\fta/model.text_field_embedder.elmo.weight_file'}} and extras {'vocab': Vocabulary with namespaces:  labels, Size: 129 || tokens, Size: 69816 || Non Padded Namespaces: {'*labels', '*tags'}}
02/13/2019 17:40:46 - INFO - allennlp.common.from_params -   instantiating class <class 'allennlp.modules.token_embedders.token_embedder.TokenEmbedder'> from params {'type': 'elmo_token_embedder', 'dropout': 0.1, 'do_layer_norm': False, 'options_file': 'C:\\Users\\rfernand\\AppData\\Local\\Temp\\tmpx2aowcg6\\fta/model.text_field_embedder.elmo.options_file', 'weight_file': 'C:\\Users\\rfernand\\AppData\\Local\\Temp\\tmpx2aowcg6\\fta/model.text_field_embedder.elmo.weight_file'} and extras {'vocab': Vocabulary with namespaces:  labels, Size: 129 || tokens, Size: 69816 || Non Padded Namespaces: {'*labels', '*tags'}}
02/13/2019 17:40:46 - INFO - allennlp.modules.elmo -   Initializing ELMo
02/13/2019 17:40:53 - INFO - allennlp.common.from_params -   instantiating class <class 'allennlp.modules.seq2seq_encoders.seq2seq_encoder.Seq2SeqEncoder'> from params {'type': 'alternating_lstm', 'input_size': 1124, 'hidden_size': 300, 'num_layers': 8, 'recurrent_dropout_probability': 0.1, 'use_input_projection_bias': False} and extras {'vocab': Vocabulary with namespaces:  labels, Size: 129 || tokens, Size: 69816 || Non Padded Namespaces: {'*labels', '*tags'}}
02/13/2019 17:40:54 - INFO - allennlp.common.from_params -   instantiating class <class 'allennlp.nn.initializers.Initializer'> from params {'type': 'orthogonal'} and extras {}
02/13/2019 17:40:54 - INFO - allennlp.common.from_params -   instantiating class <class 'allennlp.data.dataset_readers.dataset_reader.DatasetReader'> from params {'type': 'srl', 'token_indexers': {'elmo': {'type': 'elmo_characters'}}} and extras {}
02/13/2019 17:40:54 - INFO - allennlp.common.from_params -   instantiating class <class 'allennlp.data.dataset_readers.semantic_role_labeling.SrlReader'> from params {'token_indexers': {'elmo': {'type': 'elmo_characters'}}} and extras {}
02/13/2019 17:40:54 - INFO - allennlp.common.from_params -   instantiating class allennlp.data.token_indexers.token_indexer.TokenIndexer from params {'type': 'elmo_characters'} and extras {}
02/13/2019 17:40:54 - INFO - allennlp.common.from_params -   instantiating class allennlp.data.token_indexers.elmo_indexer.ELMoTokenCharactersIndexer from params {} and extras {}
r

**Comment by matt-gardner** [comment]
Those lines of code show you how to disable or change whatever logging you want.  If you don't want to see a logging message, just change its level or disable it.

**Comment by mchari** [comment]
Is there any way to turn off these messages when running allennlp in command-line mode ? specifically allennlp predict ?
