### ISSUE TITLE
Use izip instead of zip

### ISSUE THREAD

**Issue by KietSam** [allenai/allennlp#2507]
**Is your feature request related to a problem? Please describe.**
zip() will build the entire tuple list in memory, but most usage of zip does not reuse the created list

**Describe the solution you'd like**
Use izip() from itertools instead which emits each value as they're called instead of storing the entire tuple list in memory

**Additional context**
https://youtu.be/OSGv2VnC0go?t=496

**Comment by epwalsh** [comment]
I believe in Python 3, `zip` behaves just like Python 2's `izip`

**Comment by matt-gardner** [comment]
@epwalsh is correct.
