### ISSUE TITLE
BrokenPipeError while training bidirectional language models

### ISSUE THREAD

**Issue by martiansideofthemoon** [allenai/allennlp#2514]
**Describe the bug**
We often observe a `BrokePipeError` while training transformer bidirectional models using the standard AllenNLP settings for the bidirectional LM transformer. This occurs at the end of an epoch. Here is a copy of the log. The program continues running.
```
[INFO/Process-20:1] process shutting down
[INFO/Process-20:1] process exiting with exitcode 0
[INFO/Process-20] worker 0 finished (1/1)
[INFO/Process-20] process shutting down
[INFO/Process-20] process exiting with exitcode 0
[INFO/Process-21] created temp directory /tmp/pymp-uhoy6pc2
loss: 6.6689 ||: 100%|##########| 1/1 [00:55<00:00, 55.63s/it]
[INFO/Process-21] process shutting down
[INFO/Process-21] process exiting with exitcode 0
loss: 6.6664 ||: : 13it [01:06, 39.20s/it]
loss: 6.6438 ||: : 25it [01:16, 27.71s/it]
loss: 6.6302 ||: : 37it [01:27, 19.66s/it]
loss: 6.6168 ||: : 49it [01:38, 14.03s/it]
loss: 6.6033 ||: : 61it [01:48, 10.09s/it]
loss: 6.5903 ||: : 73it [01:59, 7.32s/it]
loss: 6.5774 ||: : 85it [02:09, 5.39s/it]
[INFO/MainProcess] worker 0 finished (1 / 1)
[INFO/MainProcess] sending shutdown message to manager
[INFO/SyncManager-19] process shutting down
[INFO/SyncManager-19] Failure to send message: ('#RETURN', None)
[INFO/SyncManager-19] ... request was (None, 'shutdown', (), {})
[INFO/SyncManager-19] ... exception was BrokenPipeError(32, 'Broken pipe')
[INFO/SyncManager-19] process exiting with exitcode 0
loss: 6.5672 ||: : 96it [02:19, 1.45s/it]

2019-01-17 10:21:41,718 - INFO - allennlp.training.trainer - Validating
0%| | 0/1 [00:00<?, ?it/s]
```

**System (please complete the following information):**
 - OS: CentOS Linux 7
 - Python version: 3.6.6
 - AllenNLP version: Installed from master on 14th January, 2019
 - PyTorch version: 1.0.0

**Comment by dungtn** [comment]
I have the same problem, my model worked fine on CPU though.

**Comment by brendan-ai2** [comment]
Sorry for letting this slip through the cracks. I've recently been able to train https://github.com/allenai/allennlp/blob/master/training_config/bidirectional_language_model.jsonnet successfully, so this is probably configuration/environment dependent issue.

Given that, a few questions:
1. What config are you using and what dataset are you training on?
2. Are you setting the `ulimit` properly? See https://github.com/allenai/allennlp/blob/master/tutorials/how_to/training_transformer_elmo.md.

I've seen the `Failure to send message: ('#RETURN', None)` error before, but I've forgotten the exact cause. IIRC this signifies that one of the subprocesses used failed. Given @dungtn's point about running on a CPU successfully, perhaps a particular GPU ran out of memory? There should be another error elsewhere in your stacktrace if so. Another way to observe this would be to run `watch -n 0.1 nvidia-smi` and see whether a particular GPU stopped being active.

Please let us know what you find. Thank you.
