### ISSUE TITLE
Unexpected encoded sequences' lengths (lack of encoding specification for argparse)

### ISSUE THREAD

**Issue by Nuno-Mota** [allenai/allennlp#2518]
**Describe the bug**
Running the "allennlp elmo" command might produce sequences of length different than the original intended one. The issue lies without not being able to specify an encoding type with which to read the input file, which will have the argparse.FileType('r') reader interpret some unicode characters as 0 length white spaces.

**To Reproduce**
Consider a file with the following tokenized (and space separated) input sentences (where the third sentence follows the expected behaviour):

"SUBJECT_ENTITY ( Croatian : zločina ) is a film released in OBJECT_ENTITY in 1981 , directed by Fabijan Šovagović ."
"SUBJECT_ENTITY ( Somali : Yuusuf , Arabic : محمد يوسف عبدي‎‎ ) was the OBJECT_ENTITY ."
"SUBJECT_ENTITY was launched at 15:36 UTC on OBJECT_ENTITY ."

The sentences have a sequence length (separated on ' ') of, respectively:
20
16
9

Running the command "allennlp elmo file_name file_name_out" will however produce encoded sentences of lengths, respectively:
21
18
9

The problem can be traced to the lack of proper encoding in line 100 of commands/elmo.py:
subparser.add_argument('input_file', type=argparse.FileType('r'), help='The path to the input file.')

In this case, simply replacing , type=argparse.FileType('r') with type=argparse.FileType('r', encoding='utf-8') fixes the issue.

**Expected behavior**
Expected encoddings with sequence lengths of, respectively:
20
16
9

**System (please complete the following information):**
 - OS: tested on both Windows 10 Pro and Debian GNU/Linux 9 (stretch)
 - Python version: 3.6.5 Anaconda on both systems
 - AllenNLP version: 0.8.1 on both systems
 - PyTorch version: Windows (1.0.0 CPU) / Linux (1.0.1 GPU)

**Comment by matt-gardner** [comment]
Seems like a reasonable fix to me - @matt-peters, any possible issues with this?

Also, @Nuno-Mota, I see that you say you tested this on windows - you have allennlp running on windows?  Did you have to go through a crazy install process to get it working?

**Comment by Nuno-Mota** [comment]
@matt-gardner, It was actually quite simple, as far as I remember. Using the Anaconda prompt I simply pip installed it.

There are some limitations, though.
I cannot run the allennlp commands directly (as one would normally in the terminal of a linux based OS), but otherwise I can import it within any python module and haven't had any problem so far.
Also, I have only used the elmo-related part of allennlp, so maybe there are other issues.
I suppose these can be circumvented by using the linux subsystem that exists in Windows 10

**Comment by joelgrus** [comment]
after https://github.com/allenai/allennlp/pull/1572 I'm pretty sure I was able to pip install on Windows and successfully use the `ElmoEmbedder`, but I believe some of the unit tests were still failing (and so probably are still, although I haven't tried using Windows since that PR)

**Comment by matt-peters** [comment]
LGTM

**Comment by schmmd** [comment]
@Nuno-Mota would you send us a pull request with your fix and reference this issue?
