### ISSUE TITLE
In  pretrain oie model how to extract string of the triples instead of json format?

### ISSUE THREAD

**Issue by yash97** [allenai/allennlp#2522]
Please first search our GitHub repository for similar questions.  If you don't find a similar example you can use the following template:

**System (please complete the following information):**
 - OS: [e.g. OSX, Linux]
 - Python version: [e.g. 3.6.1]
 - AllenNLP version: [e.g. v0.8.1, or "I installed from master"]
 - PyTorch version: (if you installed it yourself)

**Question**
Ask about something you don't understand, such as:

* How can I retrain my own ELMo language model?

* I'm working on a sentiment classification task and I would like to discard sentences that are longer than 1200 characters (my sentences vary from 400 characters to 1400+).  How can I configure my model to discard long sentences?

**Comment by yash97** [comment]
Also what is BV in json output which seen before ARG

**Comment by schmmd** [comment]
I'm closing this issue because I'm not sure what the original question is, since the issue looks a lot like our question template.  Feel free to comment here with your question or open a new issue with a clear question.
