### ISSUE TITLE
Training error in forward() method

### ISSUE THREAD

**Issue by bianca2319** [allenai/allennlp#2528]
When I try to train a model based on "default" trainer and "simple_tagger", I always get the following error message:
File "/home/bianca/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'labels'

**System:**
 - OS: Linux
 - Python version: 3.6
 - AllenNLP version: 0.8.2

Are there any ideas how to solve it?

**Comment by matt-gardner** [comment]
The simple tagger is expecting an argument called `tags`, not `labels`.  How are you constructing your data?

**Comment by bianca2319** [comment]
Thanks for your quick answer! I use a custom dataset reader and it seems, there is something going wrong since the newer AllenNLP versions.

**Comment by mithunpaul08** [comment]
@bianca2319 i get the same issue when I try feeding in a new data to the simple tagger. How did you solve this? Why was this closed btw?

**Comment by mithunpaul08** [comment]
update: so i found what was happening in my case. Posting it here just in case this helps someone.

So looks like in allennlp, they enforce you to use the same names of the fields you defined while reading the data. For example in the snli [reader](https://github.com/allenai/allennlp/blob/master/allennlp/data/dataset_readers/snli.py#L72) they were using the name `premise` and the corresponding [forward](https://github.com/allenai/allennlp/blob/master/allennlp/models/decomposable_attention.py#L96) method of decomposable attention HAD TO use the same word `premise`. That is really stupid imho because what if tomorrow someone wants to use a different model and wants to call their local variable inside the forward function something else.

In my case my fields instance (which had a TextField,TextField, LabelField, just like SNLI data) was called `claims` where as the arguments inside the `forward` method of decomposable attention was using the word `claim` (somehow?). So I got the error ``` in forward() got an unexpected keyword argument claims```.  I think this happens because they are passing by reference a dictionary inside the batch_loss function [here](https://github.com/allenai/allennlp/blob/master/allennlp/training/trainer.py#L263) and not by just value. 

While I agree its a good thing to enforce the usage of same title field everywhere, but in a fluid plug and play environment like this I wish it wasn't enforced. Even if it was I wish this was atleast  documented more clearly. I wasted couple of days trying to figure this out.

**Comment by joelgrus** [comment]
I am sorry you ran into issues with this, but it is covered in the tutorial:

https://allennlp.org/tutorials

```
The forward method expects dicts of tensors as input, and it expects their names to be the names of the fields in your Instance.
```

If that's not clear enough, I'm happy to make changes to it, do you have any suggestions?

(I feel like we also had an issue around programatically renaming fields to make it easier to mix and match dataset readers and models, although now I can't find the issue.)

**Comment by joelgrus** [comment]
but also I'm curious how you expected the library to behave? that is, if I have an instance that looks like 

```
Instance({"a": TextField(...), "b": TextField(...), "c": LabelField(...)})
```

and then a model whose forward function looks like

```
def forward(self, d: torch.Tensor, e: torch.Tensor, f: torch.Tensor): ...
```

what would you expect to happen? how would you expect the library to decide which field should be "d", which should be "e", and which should be "f" if the names don't match?

**Comment by mithunpaul08** [comment]
@joelgrus On second thoughts: regarding passing the arguments, you are right and am wrong. Though one humble suggestion is to maybe elaborate a little more in the documentation. i.e instead of `The forward method expects dicts of tensors as input, and it expects their names to be the names of the fields in your Instance.` maybe add an example of what it means? i did read this initially, but forgot about it, when i moved on to the second level of tutorials.

**Comment by manelAffi** [comment]
hi,
I'm  beginner with allennlp. I'm trying to train the simple_seq2seq model for named entity recognition task on the CoNLL 2003 dataset using BERT embeddings. I always get the following error message:

File "/home/manel/anaconda/bin/allennlp", line 10, in
sys.exit(run())
File "/home/manel/anaconda/lib/python3.7/site-packages/allennlp/run.py", line 18, in run
main(prog="allennlp")
File "/home/manel/anaconda/lib/python3.7/site-packages/allennlp/commands/init.py", line 102, in main
args.func(args)
File "/home/manel/anaconda/lib/python3.7/site-packages/allennlp/commands/train.py", line 124, in train_model_from_args
args.cache_prefix)
File "/home/manel/anaconda/lib/python3.7/site-packages/allennlp/commands/train.py", line 168, in train_model_from_file
cache_directory, cache_prefix)
File "/home/manel/anaconda/lib/python3.7/site-packages/allennlp/commands/train.py", line 252, in train_model
metrics = trainer.train()
File "/home/manel/anaconda/lib/python3.7/site-packages/allennlp/training/trainer.py", line 478, in train
train_metrics = self._train_epoch(epoch)
File "/home/manel/anaconda/lib/python3.7/site-packages/allennlp/training/trainer.py", line 320, in _train_epoch
loss = self.batch_loss(batch_group, for_training=True)
File "/home/manel/anaconda/lib/python3.7/site-packages/allennlp/training/trainer.py", line 261, in batch_loss
output_dict = self.model(**batch)
File "/home/manel/anaconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in call
result = self.forward(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'tokens'

here is the config file code:
`{
"dataset_reader": {
"type": "conll2003",
"tag_label": "ner",
"coding_scheme": "BIOUL",

"token_indexers": {
"bert": {
"type": "bert-pretrained",
"pretrained_model": "bert-base-cased",
"do_lowercase": false,
"use_starting_offsets": true
} ,
"token_characters": {
"type": "characters",
"min_padding_length": 3
}

  }
},
"train_data_path": "XXXXXXXXXX",
"validation_data_path": "XXXXXXXXXX",
"test_data_path":"XXXXXXXXXX",
"model": {
"type": "simple_seq2seq",

"source_embedder": {
       
    "allow_unmatched_keys": true,
"embedder_to_indexer_map": {
"bert": ["bert", "bert-offsets"],
"token_characters": ["token_characters"],
},
"token_embedders": {
"bert": {
"type": "bert-pretrained",
"pretrained_model": "bert-base-cased",

        },

  } 
},

"encoder": {
  "type": "lstm",
  "input_size": 768,
  "hidden_size": 200,
  "num_layers": 2,
  "dropout": 0.5,
  "bidirectional": true
},


"scheduled_sampling_ratio": 1.0,
"max_decoding_steps": 200,
"target_namespace": "target_tokens",
"attention_function": {"type": "dot_product"} 
},
"iterator": {
"type": "basic",
"batch_size": 64
},
"trainer": {
"optimizer": {
"type": "adam",
"lr": 0.001
},
"validation_metric": "+f1-measure-overall",
"num_serialized_models_to_keep": 3,
"num_epochs": 30,
"grad_norm": 5.0,
"patience": 25,
"cuda_device": -1
}
}`
System:

OS: ubuntu 18.14
Python version: 3.7
AllenNLP version: 0.9.0
PyTorch version: 1.17.2
I would like there
Are there any ideas how to solve it?

**Comment by manelAffi** [comment]
hi,
I'm beginner with allennlp. I'm trying to train the simple_seq2seq model for named entity recognition task on the CoNLL 2003 dataset using BERT embeddings. I always get the following error message:

File "/home/manel/anaconda/bin/allennlp", line 10, in
sys.exit(run())
File "/home/manel/anaconda/lib/python3.7/site-packages/allennlp/run.py", line 18, in run
main(prog="allennlp")
File "/home/manel/anaconda/lib/python3.7/site-packages/allennlp/commands/init.py", line 102, in main
args.func(args)
File "/home/manel/anaconda/lib/python3.7/site-packages/allennlp/commands/train.py", line 124, in train_model_from_args
args.cache_prefix)
File "/home/manel/anaconda/lib/python3.7/site-packages/allennlp/commands/train.py", line 168, in train_model_from_file
cache_directory, cache_prefix)
File "/home/manel/anaconda/lib/python3.7/site-packages/allennlp/commands/train.py", line 252, in train_model
metrics = trainer.train()
File "/home/manel/anaconda/lib/python3.7/site-packages/allennlp/training/trainer.py", line 478, in train
train_metrics = self._train_epoch(epoch)
File "/home/manel/anaconda/lib/python3.7/site-packages/allennlp/training/trainer.py", line 320, in _train_epoch
loss = self.batch_loss(batch_group, for_training=True)
File "/home/manel/anaconda/lib/python3.7/site-packages/allennlp/training/trainer.py", line 261, in batch_loss
output_dict = self.model(**batch)
File "/home/manel/anaconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in call
result = self.forward(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'tokens'

**System:**

OS: ubuntu 18.14
Python version: 3.7
AllenNLP version: 0.9.0
PyTorch version: 1.17.2
here is the **config file code**:
`{
"dataset_reader": {
"type": "conll2003",
"tag_label": "ner",
"coding_scheme": "BIOUL",

"token_indexers": {
"bert": {
"type": "bert-pretrained",
"pretrained_model": "bert-base-cased",
"do_lowercase": false,
"use_starting_offsets": true
} ,
"token_characters": {
"type": "characters",
"min_padding_length": 3
}

}
},
"train_data_path": "XXXXXXXXXX",
"validation_data_path": "XXXXXXXXXX",
"test_data_path":"XXXXXXXXXX",
"model": {
"type": "simple_seq2seq",

"source_embedder": {

"allow_unmatched_keys": true,
"embedder_to_indexer_map": {
"bert": ["bert", "bert-offsets"],
"token_characters": ["token_characters"],
},
"token_embedders": {
"bert": {
"type": "bert-pretrained",
"pretrained_model": "bert-base-cased",

    },
}
},

"encoder": {
"type": "lstm",
"input_size": 768,
"hidden_size": 200,
"num_layers": 2,
"dropout": 0.5,
"bidirectional": true
},

"scheduled_sampling_ratio": 1.0,
"max_decoding_steps": 200,
"target_namespace": "target_tokens",
"attention_function": {"type": "dot_product"}
},
"iterator": {
"type": "basic",
"batch_size": 64
},
"trainer": {
"optimizer": {
"type": "adam",
"lr": 0.001
},
"validation_metric": "+f1-measure-overall",
"num_serialized_models_to_keep": 3,
"num_epochs": 30,
"grad_norm": 5.0,
"patience": 25,
"cuda_device": -1
}
}`


I would like to know if I made a mistake in the json file code or if  there
are any ideas how to solve it?
