### ISSUE TITLE
Cached memory causes OOM with multi process iterator and multi-gpu training

### ISSUE THREAD

**Issue by dungtn** [allenai/allennlp#2538]
**Describe the bug**
`CUDA Runtime Error: Out of Memory` occurred after training for a while. The error showed that the entire batch can still fit in memory. However, 20% of memory was occupied by the cache.

**To Reproduce**
Train a simple model with StackedSelfAttentionEncoder on 20M data points (unfortunately, I cannot provide the code). Multi-process dataset reader and iterator 5 workers each and multi-GPU with 4 M40 GPUs were used. 

**Expected behavior**
For now, I added `torch.cuda.empty_cache()` at the end of `forward(self, ...):` function. It seems to work but it's also much slower. Is there a way to release the cache only when needed?

Also, the option `instances_per_epoch` doesn't work with the multi-process iterator. I tried to set it in the `base_iterator` but it yielded an error. For huge dataset like this, I'd like to have that option. Or even better, being able run evaluation and save the model after few iterations rather than have to wait for a whole epoch. I wonder if there is a way to do so? Thanks!

**System (please complete the following information):**
 - OS: Centos
 - Python version: 3.7
 - AllenNLP version: I installed from master
 - PyTorch version: 1.0.1.post2

**Comment by schmmd** [comment]
Thanks for submitting--you might consider using a larger GPU.  For us to help you we would need a clearer repro--otherwise we can just speculate.
