### ISSUE TITLE
How to set cuda_device parameter of a basic iterator

### ISSUE THREAD

**Issue by sheenG** [allenai/allennlp#2539]
Sir, i'm using a third library recently, and there are codes like that:
```
from allennlp.data.iterators import BasicIterator
biterator = BasicIterator(batch_size = 16)
dataset = [{'a': 1}]
eval_iter = biterator(dataset, shuffle=False, num_epochs=1, cuda_device=0)
```
i run the file but it didn't go through, and the reason is there is no parameter 'cuda_device'.
i want to figure it out.

**Comment by ichn-hu** [comment]
> Sir, i'm using a third library recently, and there are codes like that:

What third party library are you using? Could you give a link to that library if it is public, otherwise no one could help you with your issue.

**Comment by sheenG** [comment]
OK, link is
[NSMN](https://github.com/easonnie/combine-FEVER-NSMN/blob/master/src/nli/mesim_wn_simi_v1_2.py)
relevant code is at line #2218.

**Comment by joelgrus** [comment]
This behavior was changed as of allennlp 0.7.0

see the notes at https://github.com/allenai/allennlp/releases/tag/v0.7.0

so while that repo says it uses 0.7.1, it clearly doesn't.

**Comment by sheenG** [comment]
thank u very much!
I indeed used move_to_device() to transfer data from cpu to gpu manually, then that program went through.

**Comment by schmmd** [comment]
Closing as this seems resolved here and in the upstream library.
