### ISSUE TITLE
NER model fails with two letter word input

### ISSUE THREAD

**Issue by omri374** [allenai/allennlp#2540]
**Describe the bug**
I'm trying to run the pretrained NER model on a dataset of chatbot utterances, some are very short. Two letter words make the model throw an exception. A use case for example:
1. What is your name?
2. Ed

Exception will be thrown on the "Ed" input. Same thing for "Hi","Bo","Jo".

> ---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-22-dbe663328426> in <module>
      1 sentence = "Ed"
      2 
----> 3 results = predictor.predict(sentence=sentence)
      4 for word, tag in zip(results["words"], results["tags"]):
      5     print(f"{word}\t{tag}")

~/anaconda3/envs/tf/lib/python3.6/site-packages/allennlp/predictors/sentence_tagger.py in predict(self, sentence)
     22 
     23     def predict(self, sentence: str) -> JsonDict:
---> 24         return self.predict_json({"sentence" : sentence})
     25 
     26     @overrides

~/anaconda3/envs/tf/lib/python3.6/site-packages/allennlp/predictors/predictor.py in predict_json(self, inputs)
     53     def predict_json(self, inputs: JsonDict) -> JsonDict:
     54         instance = self._json_to_instance(inputs)
---> 55         return self.predict_instance(instance)
     56 
     57     def predict_instance(self, instance: Instance) -> JsonDict:

~/anaconda3/envs/tf/lib/python3.6/site-packages/allennlp/predictors/predictor.py in predict_instance(self, instance)
     56 
     57     def predict_instance(self, instance: Instance) -> JsonDict:
---> 58         outputs = self._model.forward_on_instance(instance)
     59         return sanitize(outputs)
     60 

~/anaconda3/envs/tf/lib/python3.6/site-packages/allennlp/models/model.py in forward_on_instance(self, instance)
    122         ``torch.Tensors`` into numpy arrays and remove the batch dimension.
    123         """
--> 124         return self.forward_on_instances([instance])[0]
    125 
    126     def forward_on_instances(self,

~/anaconda3/envs/tf/lib/python3.6/site-packages/allennlp/models/model.py in forward_on_instances(self, instances)
    153             dataset.index_instances(self.vocab)
    154             model_input = util.move_to_device(dataset.as_tensor_dict(), cuda_device)
--> 155             outputs = self.decode(self(**model_input))
    156 
    157             instance_separated_output: List[Dict[str, numpy.ndarray]] = [{} for _ in dataset.instances]

~/anaconda3/envs/tf/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    487             result = self._slow_forward(*input, **kwargs)
    488         else:
--> 489             result = self.forward(*input, **kwargs)
    490         for hook in self._forward_hooks.values():
    491             hook_result = hook(self, input, result)

~/anaconda3/envs/tf/lib/python3.6/site-packages/allennlp/models/crf_tagger.py in forward(self, tokens, tags, metadata, **kwargs)
    180             A scalar loss to be optimised. Only computed if gold label ``tags`` are provided.
    181         """
--> 182         embedded_text_input = self.text_field_embedder(tokens)
    183         mask = util.get_text_field_mask(tokens)
    184 

~/anaconda3/envs/tf/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    487             result = self._slow_forward(*input, **kwargs)
    488         else:
--> 489             result = self.forward(*input, **kwargs)
    490         for hook in self._forward_hooks.values():
    491             hook_result = hook(self, input, result)

~/anaconda3/envs/tf/lib/python3.6/site-packages/allennlp/modules/text_field_embedders/basic_text_field_embedder.py in forward(self, text_field_input, num_wrapping_dims)
    105             for _ in range(num_wrapping_dims):
    106                 embedder = TimeDistributed(embedder)
--> 107             token_vectors = embedder(*tensors)
    108             embedded_representations.append(token_vectors)
    109         return torch.cat(embedded_representations, dim=-1)

~/anaconda3/envs/tf/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    487             result = self._slow_forward(*input, **kwargs)
    488         else:
--> 489             result = self.forward(*input, **kwargs)
    490         for hook in self._forward_hooks.values():
    491             hook_result = hook(self, input, result)

~/anaconda3/envs/tf/lib/python3.6/site-packages/allennlp/modules/token_embedders/token_characters_encoder.py in forward(self, token_characters)
     34     def forward(self, token_characters: torch.Tensor) -> torch.Tensor:  # pylint: disable=arguments-differ
     35         mask = (token_characters != 0).long()
---> 36         return self._dropout(self._encoder(self._embedding(token_characters), mask))
     37 
     38     # The setdefault requires a custom from_params

~/anaconda3/envs/tf/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    487             result = self._slow_forward(*input, **kwargs)
    488         else:
--> 489             result = self.forward(*input, **kwargs)
    490         for hook in self._forward_hooks.values():
    491             hook_result = hook(self, input, result)

~/anaconda3/envs/tf/lib/python3.6/site-packages/allennlp/modules/time_distributed.py in forward(self, *inputs)
     33             reshaped_inputs.append(input_tensor.contiguous().view(*squashed_shape))
     34 
---> 35         reshaped_outputs = self._module(*reshaped_inputs)
     36 
     37         # Now get the output back into the right shape.

~/anaconda3/envs/tf/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    487             result = self._slow_forward(*input, **kwargs)
    488         else:
--> 489             result = self.forward(*input, **kwargs)
    490         for hook in self._forward_hooks.values():
    491             hook_result = hook(self, input, result)

~/anaconda3/envs/tf/lib/python3.6/site-packages/allennlp/modules/seq2vec_encoders/cnn_encoder.py in forward(self, tokens, mask)
    103             convolution_layer = getattr(self, 'conv_layer_{}'.format(i))
    104             filter_outputs.append(
--> 105                     self._activation(convolution_layer(tokens)).max(dim=2)[0]
    106             )
    107 

~/anaconda3/envs/tf/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    487             result = self._slow_forward(*input, **kwargs)
    488         else:
--> 489             result = self.forward(*input, **kwargs)
    490         for hook in self._forward_hooks.values():
    491             hook_result = hook(self, input, result)

~/anaconda3/envs/tf/lib/python3.6/site-packages/torch/nn/modules/conv.py in forward(self, input)
    185     def forward(self, input):
    186         return F.conv1d(input, self.weight, self.bias, self.stride,
--> 187                         self.padding, self.dilation, self.groups)
    188 
    189 

RuntimeError: std::exception

**To Reproduce**
Run:
from allennlp.predictors import Predictor
predictor = Predictor.from_path("https://s3-us-west-2.amazonaws.com/allennlp/models/ner-model-2018.12.18.tar.gz")

sentence = "Ed"

results = predictor.predict(sentence=sentence)
for word, tag in zip(results["words"], results["tags"]):
    print(f"{word}\t{tag}")

**Expected behavior**
No exception should be thrown, either if the model detected a NER or not.

**System (please complete the following information):**
 - OS: Ubuntu 16.04
 - Python version: 3.6.6
 - AllenNLP version: 08.1
 - PyTorch version: Didn't install myself

**Additional context**

**Comment by matt-gardner** [comment]
Yep, this is a bug. We have fixed this for more recent models, but the pretrained NER models still use older configuration files.  I just submitted #2541 to fix this.  You can grab that one line change from that PR and add it to your script, and it should fix your issue.
