### ISSUE TITLE
Trainer implementation with customizable updaters

### ISSUE THREAD

**Issue by zxteloiv** [allenai/allennlp#2543]
**Is your feature request related to a problem? Please describe.**
When implementing a GAN, we have to control the optimizing procedure more freely,
for example
  - alternatively update the discriminator every 5 batches and then the generator gets updated once
  - different GANs with different experimental loss will also require

However current allennlp.training.Trainer implementation only works for one model.

**Describe the solution you'd like**
May be some customizable module based on an abstract allennlp.training.Updater class.

**Describe alternatives you've considered**
Chainer comes with a separate [Updater class](https://docs.chainer.org/en/stable/reference/training.html#updaters) decoupled from the trainer which is only responsible to control optimizing.

[Ignite](https://github.com/pytorch/ignite/blob/master/examples/gan/dcgan.py) is more aggressive to allow users to write any function runnable from its engine.

**Additional context**

**Comment by joelgrus** [comment]
we recently refactored the Trainer to make it easy to implement your own training variants.

for example, here is a `Trainer` subclass that trains a toy GAN:

https://github.com/allenai/allennlp/blob/master/allennlp/tests/training/gan_trainer_test.py

you shouldn't use that subclass (it's a toy), but it should give you a sense of how you can write a trainer to handle your GANs or whatever. I think at some point we'd like to include e.g. a `GanTrainer` in the library, but we'd want it to be general enough to work in a lot of cases, and I don't think we know enough right now to design it.

**Comment by zxteloiv** [comment]
Thank you!
I found the test case very useful.

The first reason I want to use a general trainer is to reuse the so many useful features in trainer, such as early stopping, learning schedule, saving the best model on validation, pruing the old and keeping only the latest 20 models, etc. These really save me many efforts, thanks!

So far I agree that the use cases are indeed much broader than what a trainer could  provide.
I would try to hack the Trainer._train_epoch function or else for a temporary scenario.

**Comment by zxteloiv** [comment]
hi, you can find the file from the dated repo (v0.9) here, almost at the time when the issue was posted.
https://github.com/allenai/allennlp/blob/052353ed62e3a54fd7b39a660e65fc5dd2f91c7d/allennlp/tests/training/gan_trainer_test.py
I've not checked whether it could work.
