### ISSUE TITLE
ModuleNotFoundError: No module named 'allennlp.models'

### ISSUE THREAD

**Issue by vaishnavibatni** [allenai/allennlp#2544]
**System (please complete the following information):**
 - OS: Windows 10
 - Python version: [e.g. 3.6.8]
 - AllenNLP version: I installed using conda

**Question**
When I import allennlp.models, I get this error
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'allennlp.models'

**Comment by nelson-liu** [comment]
Sorry, AllenNLP currently doesn't officially support Windows. maybe this is a quick fix, though, @joelgrus ?

**Comment by joelgrus** [comment]
I know absolutely nothing about the intersection of conda and windows.

My experiments with installing allennlp on windows have all involved pip.

**Comment by vaishnavibatni** [comment]
I reinstalled it using pip and it's working now. Thank you!

**Comment by AnuragBalsaraf** [comment]
reinstalled work...! Thanks vaishnavibatni
