### ISSUE TITLE
Does the Allennlp have a Macro F1 value calculation function?

### ISSUE THREAD

**Issue by aslicedbread** [allenai/allennlp#2547]
Hi~

It seems that the default is calculating the Micro F1?

Besides, could we use the dataset tagged with the BIOES scheme?  Need we do extra processing or setting?

And I try to train serveral times on the windows but failed, does it means that Allennlp currently not supports windows? (ubuntu is fine.)

Hope to get your relpy, Thanks a lot.

**Comment by schmmd** [comment]
AllenNLP does not currently support Windows.  If you need a different value calculation function you will need to write your own Metric.
