### ISSUE TITLE
How to use ELMo in decoder of seq2seq?

### ISSUE THREAD

**Issue by zhengliz** [allenai/allennlp#2550]
**Question**

I'm trying to share ELMo embedder for both encoder & decoder in `seq2seq`.
Is there a way to get the `Vocabulary` of pretrained ELMo?
And shall the decoding be in characters this way? 
Suggestions on how to modify `SimpleSeq2Seq` for this purpose are also appreciated. 
Thanks

**System (please complete the following information):**
 - OS: Linux
 - Python version: 3.7.2
 - AllenNLP version: 0.8.1
 - PyTorch version: 1.0.1

**Comment by matt-gardner** [comment]
So, it's not clear to me exactly what you want to do with the decoder.  ELMo is bidirectional, and there isn't a good way to feed it one word at a time, left to right.  You could imagine pulling out the character CNN and the forward LSTM, and using those to sequentially encode each decoder output to get hidden state for the next decoder timestep.  But, e.g., running ELMo on the full decoder output so far to get some kind of input for the next timestep seems odd to me.  Did you have some other idea for what you wanted to do with this?

**Comment by zhengliz** [comment]
Thank you @matt-gardner for the prompt response.
Since `seq2seq` doesn't have flexible support for decoders yet (e.g. `
SimpleSeq2Seq` hard-code lstm decoder and embedding inside) 
and I often get CUDA OOM (vocab size 20k) as mentioned in others' threads,
I'm trying to see if I could share pretrained embedder for both encoder & decoder.
You are right that in decoding time it seems odd to run bidirectional ELMo on the output so far for the next decoder step.
Would the situation be a little better for BERT?

**Comment by matt-gardner** [comment]
You should be able to share an embedder for both input and output tokens, if they are the same language.  That's a lot easier than trying to use ELMo or BERT.  Also, I don't think that BERT would be any better than ELMo here, it has the same problems that I mentioned about ELMo.

**Comment by zhengliz** [comment]
Thank you @matt-gardner
