### ISSUE TITLE
Is alternating optimization possible?

### ISSUE THREAD

**Issue by kitsing** [allenai/allennlp#2551]
**System (please complete the following information):**
 - OS: [e.g. OSX, Linux]
 - Python version: [e.g. 3.6.1]
 - AllenNLP version: [e.g. v0.8.2, or "I installed from master"] 0.8.2
 - PyTorch version: (if you installed it yourself) 3.7

**Question**
* I am trying to implement something like Monte Carlo EM, where I need to alternatingly update parameters of my model and parameters of a proposal distribution. But I haven't figured out how to do this under the framework of AllenNLP -- the Trainer class only does backward() on a single loss. I guess I can hack _train_epoch and batch_loss to get what I want. But I am wondering if there's a cleaner way to do this that I have overlooked? Thanks!

**Comment by matt-gardner** [comment]
The `Trainer` was recently refactored in an attempt to make it more configurable and allow for use cases like this.  You can see a (toy) example of a GAN trainer [here](https://github.com/allenai/allennlp/blob/master/allennlp/tests/training/gan_trainer_test.py).  Something like that example might give you some ideas about how to set up the trainer for your own code.  And when you have it working, we'd love to see a link to it - we'd like to have more `Trainer` implementations available, but we need to see more examples of how people want to modify the `Trainer` before we know what to add.

**Comment by kitsing** [comment]
Thanks, Matt! This is also useful for implementing REINFORCE with baselines. Will definitely share my code when it's available.
