### ISSUE TITLE
How is the ELMo's scalar parameters learned?

### ISSUE THREAD

**Issue by ktlsn1234** [allenai/allennlp#2552]
Hello,

I am wondering how the scalar parameters(s_j, gamma in equation(1)) are trained used to obtain task specific weighted ELMo vectors.

elmo.py, scalar_mix.py code shows that s_j can be initialized by user defined values ​​through scalar_mix_parameters.
if it is None, it seems to adjust by learning from the initial value(0) specified in scalar_mix.py. 
and for gamma value, it seems to be adjusted from initial value(1) without input separately.
If the variable `trainable` is true in scalar_mix.py, it seems that these scalar parameter values ​​will be adjusted as learning about task specific data.

If they are trainable, my question is
1. What purpose is these values(s_j, gamma) ​​trained?
2. Where they are adjusted during learning from task specific data?

Thanks.

**Comment by matt-gardner** [comment]
See [the original ELMo paper](https://www.semanticscholar.org/paper/Deep-contextualized-word-representations-Peters-Neumann/3febb2bed8865945e7fddc99efd791887bb7e14f) for information on what those parameters do and why they are there.  They get adjusted from data during training using standard pytorch gradient updates as with any other model, and the code for this lives in our `Trainer` class.
