### ISSUE TITLE
Best practice in loading pre-trained BERT classification layers ?

### ISSUE THREAD

**Issue by anthonywchen** [allenai/allennlp#2561]
I see on the [HuggingFaces](https://github.com/huggingface/pytorch-pretrained-BERT) repository that there is an option to download the Bert encoder along with the different pre-trained classification layers like the pre-trained MaskedLM classification layer. Is there an easy or recommended way to load these pre-trained classification layers in AllenNLP?

Thanks!
Anthony

**Comment by matt-gardner** [comment]
Hi @anthonywchen, sorry to be super slow on this (you asked right before the ACL deadline, and then we took a long time to catch up). I'm not totally sure what exactly you mean in your question, but here's an example of using a hugging face BERT model inside an allennlp model (be sure to browse the repo for the other code that makes all of this fit together): https://github.com/allenai/allennlp-bert-qa-wrapper/blob/master/pretrained_bert/model.py#L48-L74.  You should be able to do something similar for any other pre-trained hugging face model.
