### ISSUE TITLE
why has not document-qa been integrated into allennlp so far?

### ISSUE THREAD

**Issue by aagohary** [allenai/allennlp#2563]
I am wondering if there is a specific reason why document-qa (https://github.com/allenai/document-qa) has not been integrated into allennlp so far. Do you guys have plans to do that in the near future? Thanks!

**Comment by matt-gardner** [comment]
See #804.  The main model there was used as the basis for the existing DialogQA model in this repo, so it appears to be largely working, it's just the data loading / sampling stuff that was not working, probably.  Also, @yizhongw's work on QANet-related stuff has increased the memory-efficiency of our code, so a larger batch size might now be feasible.  If someone wants to pick this up and contribute back, we'd love to have a working implementation inside of allennlp, but it's not super high on our priority list for us to do ourselves right now.

**Comment by aagohary** [comment]
I see. Thanks for the clarification.
