### ISSUE TITLE
'allennlp' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by dummybot123** [allenai/allennlp#2567]
I installed Allennlp on Windows by following the instructions mentioned in this link - https://gist.github.com/joelgrus/8e994d908816ff91cd3df3602389dc0b.

But on running the following command
```allennlp train tutorials/getting_started/simple_tagger.json --serialization-dir /tmp/tutorials/getting_started```

I am getting this error - 'allennlp' is not recognized as an internal or external command,
operable program or batch file.

 - Windows 10
 - Python version: 3.6.5
- Conda version:  4.6.7
 - AllenNLP version: 0.4.0

**Comment by DeNeutoy** [comment]
Hi, we don't officially support windows so it's unlikely we're going to be able to help here. Good luck!

**Comment by OmniaZayed** [comment]
Is there a way to use something similar to this command from within a python code?

**Comment by joelgrus** [comment]
yes, the command itself is just running python code, which you could instead call yourself:

https://github.com/allenai/allennlp/blob/master/allennlp/commands/elmo.py#L147

**Comment by ZaheedaT** [comment]
> yes, the command itself is just running python code, which you could instead call yourself:
> 
> https://github.com/allenai/allennlp/blob/master/allennlp/commands/elmo.py#L147

This doesn't point to a line that one can run
