### ISSUE TITLE
Time taken to answer a reading comprehension question (BiDAF)

### ISSUE THREAD

**Issue by PhantomGrin** [allenai/allennlp#2571]
Hi, I am using your library together with BiDAF model to make an application that answer machine comprehension Questions. However, when the input passage is larger, it takes lot of time to produce results. 
I tried separating the tokenization and embedding of passage. I wrote code to do this beforehand and save it and used torch.load to load that dictionary. Even so, it takes comparatively almost the same time. 

without tokenization and embedding separated
![p1](https://user-images.githubusercontent.com/25760433/53937031-dc4eb900-40d1-11e9-8794-e7bd4a8c5c60.png)

with tokenization and embedding separated
![screenshot from 2019-03-07 12-07-35](https://user-images.githubusercontent.com/25760433/53937066-fbe5e180-40d1-11e9-89b5-422aad04bcf6.png)

It says it takes more time in LSTM part. Is there a way to reduce this time taken to give an answer?

**System:**
 - OS: Ubuntu 18.04 (running on CPU) 
 - Python version: 3.7.1
 - AllenNLP version: "I installed from master"
 - PyTorch version: 1.0.1

**Comment by matt-gardner** [comment]
There's not a lot we can do about that - these operations are best performed on a GPU, and it looks like you have a _really_ long passage if you're getting 18 second inference times.  You might consider breaking up your long passage into multiple smaller ones, and running independently on each section.

**Comment by PhantomGrin** [comment]
Thank you for answering. Yes, it is 18k+ words. I tested in that way considering the problem we are trying to tackle. I thought there might be something that I missed since I am still a novice.

**Comment by matt-gardner** [comment]
In that case, you might consider using what's in the [DocumentQA repository](https://github.com/allenai/document-qa), which is specifically designed for that kind of use case.  I would not expect the models we have in AllenNLP to work very well, or very efficiently, in a setting where you have 18k-word passages.
