### ISSUE TITLE
How to output the results like conlleval format?

### ISSUE THREAD

**Issue by aslicedbread** [allenai/allennlp#2572]
Hi~ 
I hope  to count each type of entity's precision, recall and f1-score.
But the output result of eval is overall by default. And I don't know how to deal with this.
Hope to your reply, Thanks.

**Comment by joelgrus** [comment]
if you are using the CrfTagger model it has a `verbose_metrics` parameter that should make it return metrics per label. feel free to re-open if that doesn't solve your problem.
