### ISSUE TITLE
Asking about predicting on the entire Squad1.1 dev set using BiDAF+Elmo

### ISSUE THREAD

**Issue by CuriousKomodo** [allenai/allennlp#2573]
Hi, I'm working on a QA task on Squad1.1 and I would like to evaluate the pre-trained Bidaf+Elmo model on the entire Squad1.1 dev set. At the same time, I would like to know the prediction for each example, and identify all the failed examples (as well as their attention mapping). 

According to this link: https://allennlp.org/models, I can use 'predictor' to make prediction on one example, but iterating this on over 10K of dev questions may take too long. I am wondering if the function 'evaluate' will output the the result for all individual dev examples, as well as their attention mapping (and it may be faster)?

Best wishes,
Kefei

**Comment by joelgrus** [comment]
although the example on the "models" page is only a single instance, `allennlp predict` should work (and correctly use batching) with multiple instances as inputs.

if you use the `--use-dataset-reader` flag and point it at the squad dev set, it should just work, I think.

**Comment by CuriousKomodo** [comment]
@joelgrus  
Hi Joel, 
Could you please tell me how to use the `--use-dataset-reader` flag? 

According to the documentation for BiDAF Predictor, 
https://allenai.github.io/allennlp-docs/api/allennlp.predictors.html?highlight=predictor#bidaf

There is a second input to the class **allennlp.predictors.bidaf.BidafPredictor** , which is **allennlp.data.dataset_readers.dataset_reader.DatasetReader**
Is this related to what you are saying? 

Best wishes,
Kefei

**Comment by CuriousKomodo** [comment]
@joelgrus 

I found the documentation **allennlp.commands.predict**. 
https://allenai.github.io/allennlp-docs/api/allennlp.commands.predict.html

The meaning for `--use-dataset-reader`:
'Whether to use the dataset reader of the original model to load Instances' 
Is this a boolean? Or am I supposed to put the path of the sqaud1.1 dataset? 

Also, I wonder if there is a python version ?  

Best wishes,
Kefei

**Comment by joelgrus** [comment]
it is a boolean, the model archive contains a config, and the config says what dataset reader was used when training the model.

normally `allennlp predict` wants JSONL inputs, but if you do `allennlp predict --use-dataset-reader` then it expects the inputs to be in whatever format that dataset reader expects them in (i.e. in whatever format the model was trained on).

all of the `allennlp` commands are just python scripts. If you look at the source code for the `predict` command you can see exactly what it's doing (and then do that from your code)

https://github.com/allenai/allennlp/blob/master/allennlp/commands/predict.py

**Comment by joelgrus** [comment]
closing, re-open if this doesn't answer your question.
