### ISSUE TITLE
[Suggestion] Make `predict` more like `evaluate`

### ISSUE THREAD

**Issue by WrRan** [allenai/allennlp#2576]
**Is your feature request related to a problem? Please describe.**
I tried to run the specified model using `allennlp predict` with specified `batch_size`:
```bash
allennlp predict -o "{'iterator.batch_size': 64}" other_stuff
```

But it didn't work.

**Describe the solution you'd like**
Finally, I found `allennlp predict` does not use `DataIterator` to iterate data.
So, is it a better idea to warn users about this?

**Describe alternatives you've considered**
Or we iterate data in `allennlp predict` using `DataIterator` as we do in `allennlp train`.

**Additional context**
Happy to create PR for it.

**Comment by matt-gardner** [comment]
I guess our whole prediction pipeline was created envisioning demo-like usage.  You're right that it doesn't handle very well the use case where you want JSON output on a large dataset.  There's no option to do bucketing or anything else that our data iterators do.  Maybe the right thing to do is to make `predict` more like `evaluate`, using the configuration for everything and bypassing `Predictors` entirely.  Most `Predictors` just call `sanitize(model.forward(inputs))`, so the `predict` command could similarly just sanitize the outputs and be done.  I'm not sure if this is worth it, though, and I don't have a good handle on how people actually use the `predict` command - I don't use it for anything.  Anyone else have any thoughts?

**Comment by WrRan** [comment]
On the contrary, I haven't used the `evaluate` command very much. Actually, I didn't notice this command until you mentioned it. Additionally, I found that these two commands are very similar:
```bash
evaluate - Evaluate the specified model + dataset
predict - Run the specified model against a JSON-lines input file
```

If the dataset is a JSON-lines input file, is it preferable to use `predict`?
And if not, is it preferable to use `evaluate`?

For me, when I want to run the specified model against a non-JSON-lines input file, I usually use `predict` with option `--use-dataset-reader`. (It is also the reason why I never noticed `evaluate`.)

---
Discussion about #2578 

The option `--cuda-device` is provided with command `predict`, `evaluate` and `elmo`. They all share the same function: set the cuda-device (only one) to run on. And if we call `command --cuda-device "0, 1, 2"` (or `command --cuda-device "0,1,2,3"`), we will get error as follows:
```bash
argument --cuda-device: invalid int value: '0 1 2 3'
```
It is because the option `cuda-device` is added to `ArgumentParser` as `parser.add_argument('--cuda-device', type=int, default=-1)`.

So I think it is necessary to modify these parsers to keep the same semantics as `cuda-device` in configurations.

As for the implementation, I prefer to allow users to set `--cuda-device` as follows:
```bash
command other-stuff --cuda-device 0 1 2 3
```
to:
```bash
command --cuda-device "0,1,2,3"
```

There is the reason for it:
The former is easier to implement, because `argparse` supports this function and we needn't parse strings in the latter by ourselves.

What do you think?

**Comment by matt-gardner** [comment]
`evaluate` is for computing metrics over a dataset, and `predict` is for getting json output from a dataset. I don't typically need the json output, so I use `evaluate`.

Also, I didn't realize that `evaluate` can't handle multiple GPUs - that should indeed be a separate issue, about making all relevant commands support multiple GPUs. Feel free to open a new one, or re-open and rename the one that I closed.

**Comment by WrRan** [comment]
Got it. I understand the difference between `evaluate` and `predict` now.
Thanks. :)

**Comment by matt-gardner** [comment]
Just putting this here for reference: https://github.com/allenai/allennlp/issues/327#issuecomment-480516740

**Comment by matt-gardner** [comment]
I think this cleanup would be nice to do, but it's not a breaking change and shouldn't block a 1.0 release, so I'm removing it from the milestone.

**Comment by dirkgr** [comment]
I don't think we should make `predict` more like `evaluate`. They have different purposes. Instead, we should fix `evaluate` do to what @WrRan wanted to do all along, i.e., create predictions for a whole dataset.

I'm closing this in favor of #4626.
