### ISSUE TITLE
[Bug] Subtle bug when using CnnEncoder.

### ISSUE THREAD

**Issue by WrRan** [allenai/allennlp#2582]
**Describe the bug**
When we use `CnnEncoder` and the maximum size of filters is greater than the number of words in sentences (or the number of characters in words), the following errors are thrown:
```bash
...
       RuntimeError: std::exception
```

**To Reproduce**
Run the below test case to reproduce:
```python
from allennlp.common import Params
from allennlp.modules.seq2vec_encoders import CnnEncoder
from allennlp.common.testing import AllenNlpTestCase


class TestCnnEncoder(AllenNlpTestCase):
    def test_few_words_in_sentence(self):
        params = Params({
            'embedding_dim': 2,
            'num_filters': 1,
            'ngram_filter_sizes': [4]
        })
        encoder = CnnEncoder.from_params(params)
        # 1 -> batch_size
        # 3 -> number of words
        # 2 -> dimension of embeddings
        embedding = torch.rand(1, 3, 2)
        mask = torch.ones(1, 3).long()
        encoder(embedding, mask)
```
The erros is:
```bash
...
    @weak_script_method
    def forward(self, input):
        return F.conv1d(input, self.weight, self.bias, self.stride,
>                       self.padding, self.dilation, self.groups)
E       RuntimeError: std::exception
```

In a more realistic application scenario, this error may be thrown when we feed a sentence containing three words to a CnnEncoder with the maximum size of filters being four.

**Expected behavior**
No errors.

**System (please complete the following information):**
- OS: Linux
- Python version: 3.6.7
- AllenNLP version: 0.8.3-unreleased
- PyTorch version: 1.0.0

**Additional context**
The solution is similar to #1967 .
But this time, we set `min_padding_length` for words in sentences rather than characters in words.
And I think it is necessary to add `min_padding_length` to the property of the base class `TokenIndexer`.

PS: Glad to create PRs for this issue.

**Comment by matt-gardner** [comment]
Yep, this is a bug, and you're right about the solution. PRs welcome!
