### ISSUE TITLE
Running allennlp in docker

### ISSUE THREAD

**Issue by chjulia** [allenai/allennlp#2592]
I downloaded the allennlp dockerfile from dockerhub. The container is up and running but when I try to run the following example: 

`curl --header 'Accept:application/json' --header 'Content-Type:application/json' -v POST -d '{"sentence": "Did Uriah honestly think he could beat The Legend of Zelda in under three hours?"}' http://localhost:8000/predict/named-entity-recognition
`

I get an curl (52) Error which says: Emtpy reply from server.
What can I do?

**Comment by joelgrus** [comment]
where did you get that example from?

the `allennlp/allennlp` docker image doesn't run any kind of server, so I wouldn't expect that command to do anything.

it seems like maybe you want to run our demo, in which case you'd need to use the `allennlp/demo` image, but that's probably overkill if you just want to make predictions. In that case you just want to follow the instructions here:

https://github.com/allenai/allennlp#running-the-docker-image

and then use one of the predict commands from here:

https://allennlp.org/models

**Comment by chjulia** [comment]
Thank you for the answer! I've read the example from issue #1089. If I want to run allennlp as a server and access it with an http request, which image would you recommend?

**Comment by joelgrus** [comment]
ok, this is going to seem kind of oblique, but allennlp includes a "simple server" that can serve up a model behind an API.

you would need to do the following. first, make sure you have an allennlp cache directory

```
mkdir -p $HOME/.allennlp
```

then start the simple server in the docker image, exposing port 8000 and mounting that cache directory (this is so that if you do this multiple times it won't download the large model every time)

```
sudo docker run --rm -p 8000:8000 --entrypoint="" -v $HOME/.allennlp:/root/.allennlp allennlp/allennlp:v0.8.1 python -m allennlp.service.server_simple --archive-path https://s3-us-west-2.amazonaws.com/allennlp/models/ner-model-2018.12.18.tar.gz --predictor sentence-tagger --field-name sentence
```

after which you can curl against that service:

```
curl 'http://localhost:8000/predict' -H 'Content-Type: application/json' --data-binary '{"sentence":"Jim is the biggest person in Seattle."}'
```
