### ISSUE TITLE
Asking about the model structure of BiDAF + ELMo

### ISSUE THREAD

**Issue by CuriousKomodo** [allenai/allennlp#2595]
Hi,

I am trying to figure out what the BiDAF+ELMo model would look like, in comparison to the original BiDAF model.

According to the paper on [ Bi-Directional Attention Flow for Machine Comprehension ](https://arxiv.org/pdf/1611.01603.pdf), this is the BiDAF model consisting of 6 major layers:

-Character Embedding Layer
-Word Embedding Layer
-Contextual Embedding Layer
-Attention Flow Layer 
-Modeling Layer
-Output Layer 

<img width="1003" alt="Screen Shot 2019-03-12 at 10 28 33" src="https://user-images.githubusercontent.com/22811238/54193286-a6367e00-44b1-11e9-8e2c-c282ddefba4f.png">

In [Deep contextualized word representations](http://www.aclweb.org/anthology/N18-1202), it mentioned that:

"To add ELMo to the supervised model, we first freeze the weights of the biLM and then concatenate the ELMo vector ELMo[task]_k with x_k and pass the ELMo enhanced representation [x_k; ELMo[task]_k ] into the task RNN. For some tasks (e.g., SNLI, SQuAD), we observe further improvements by also including ELMo at the output of the task RNN by introducing another set of output specific linear weights and replacing h_k with [h_k; ELMo[task]_k ]."

Can I directly interpret the passage above as the following picture? 

<img width="710" alt="Screen Shot 2019-03-12 at 10 37 04" src="https://user-images.githubusercontent.com/22811238/54193844-d16d9d00-44b2-11e9-98cc-097ed60937dc.png">

So it appears that ELMo representation is concatenated with inputs at the Character Embedding Layer and outputs from the Contextual Embedding Layer? Please correct me if I misunderstood it. 

Best wishes,
Kefei

**Comment by matt-gardner** [comment]
That's how the original paper did it, with a slightly different model (we used the documet-qa repository for the original ELMo paper).  For regular BiDAF, you can see an example training configuration with ELMo [here](https://github.com/allenai/allennlp/blob/master/training_config/bidaf_elmo.jsonnet), which just puts ELMo at the bottom layer.

**Comment by CuriousKomodo** [comment]
@matt-gardner Thanks Matt. It appears that ELMo is applied in the Word Embed layer, after GLoVE. Does it mean that ELMo is concatenated with the word embedding by GLoVE before entering the Highway Network? 

Kefei

**Comment by matt-gardner** [comment]
Yes.

**Comment by matt-gardner** [comment]
Closing this issue; feel free to re-open if you have more questions.
