### ISSUE TITLE
Extracting tokens per second at training and decoding time

### ISSUE THREAD

**Issue by lethenghia18** [allenai/allennlp#2617]
Hello, 

I am working with the Semantic Role Labeler reader and model and would like to extract the tokens (word) per second during training time and testing time. What's the easiest way to go about that? I am utilizing the reset functionality in get_metrics, adding a 'tok_per_sec' key in the metrics. 

Please let me know if I need to provide anymore information.

**Comment by brendan-ai2** [comment]
You're just trying to keep track of how many tokens you're producing per second, right? I'd suggest maintaining two things:

1) An internal start time. Set this to the current time the first time your `forward` method is called. Reset when the metrics reset.
2) A count of total tokens generated.

Then in `get_metrics` get the time again, subtract to find the duration, divide the total tokens by the duration and set `tok_per_sec`. Please let me know if I can clarify anything.

**Comment by lethenghia18** [comment]
Yup, that is what I am currently doing. Thanks!
