### ISSUE TITLE
How to get confidence score in WikitableQuestions Semantic Parser?

### ISSUE THREAD

**Issue by dummybot123** [allenai/allennlp#2634]
I am using WikitableQuestions Semantic Parser model for answering questions based on tabular data. I used the source code from https://github.com/allenai/allennlp. I am wondering how to get confidence score for the answer.

**Comment by matt-gardner** [comment]
This is a duplicate of https://github.com/allenai/allennlp/issues/2596.  I'm closing this, feel free to comment further if you have more questions.  Also feel free to submit a PR adding the confidence score to the returned values.

**Comment by dummybot123** [comment]
I am not getting how to extract the score from the dict best_final_states.

**Comment by matt-gardner** [comment]
`best_final_states[i][0].score[0]`

**Comment by matt-gardner** [comment]
The i is for the batch index, the first 0 is the best state for that batch index, and the second 0 is the first (and only) score in that state (states can be grouped, but they aren't at the end of a search).

**Comment by matt-gardner** [comment]
We should maybe consider differentiating between a single state and a grouped state, that might make things easier to understand. Maybe...
