### ISSUE TITLE
ALLENNLP -> WIKITABLES -> CONFIDENCE SCORE

### ISSUE THREAD

**Issue by poulamic23** [allenai/allennlp#2638]
Thank you @matt-gardner for your help on #2596 
Kindly include the confidence score in your next release.
Please guide me on how to raise a request for the same.

**Comment by matt-gardner** [comment]
@pdasigi, can you add this to #2637?

**Comment by poulamic23** [comment]
Tried https://github.com/allenai/allennlp/issues/2634#issuecomment-475479097 already before.
It's returning scores, however all the scores are negative. I know it sounds lame but is it because of negative weights in the model?
Updated as per #2637... No difference on the confidence part.
Has this been added yet?

**Comment by matt-gardner** [comment]
You can see that #2637 has not yet been merged, and @pdasigi hasn't updated that PR since I asked him to put this in.

The scores it returns are log probabilities, which will by definition be negative.  Exponentiate them to get probabilities.
