### ISSUE TITLE
ELMo takes over LSTM states from older minibatches

### ISSUE THREAD

**Issue by soskek** [allenai/allennlp#2643]
I found a possible bug of the ELMo's embedding command.

When we call `allennlp elmo hoge.txt embeddings.hdf5 --all`, it encodes lines into embeddings. If the text file has many lines, it processes them using multiple devided batches (e.g. the default batch size is 64). But, the LSTMs used in ELMo are stateful and miss calling reset_state. The stale states are unfortunately used for state initialization of the next minibatch and pollute the encoding.

Is this an intended behavior?

---------
They are stateful:

https://github.com/allenai/allennlp/blob/a558f7f4982d6a996d5397c7ff7a500cb0251577/allennlp/modules/elmo_lstm.py#L66

They set states after each minibatch call:

https://github.com/allenai/allennlp/blob/3cdb7e21c42aa5b3938cbd405cdc0f34f3178e9f/allennlp/modules/elmo_lstm.py#L154

**Comment by nelson-liu** [comment]
Yup, this is expected: https://github.com/allenai/allennlp/blob/master/tutorials/how_to/elmo.md#notes-on-statefulness-and-non-determinism

closing this, but feel free to reopen if you have follow-up questions.

**Comment by soskek** [comment]
oh! I missed it!
Thank you!
