### ISSUE TITLE
Beginner question: Docker install redownloads model every run, cannot feed it custom data

### ISSUE THREAD

**Issue by aindilis** [allenai/allennlp#2649]
**System (please complete the following information):**
 - OS: Debian GNU/Linux 9.6 (stretch)
 - Python version: 3.5.3, 2.7.15 ?
 - AllenNLP version: v0.7.0 from Docker
 - PyTorch version: 

**Question**

* Hi, thank you for making this program available open source.  I had some issues probably owing to not understanding Docker with running it.  What I want to do is be able to write a program that runs on my system, use the Textual Entailment model, and pass sentence pairs (T/H) to it and obtain its score for whether it is entailed, contradicted, or neutral and what percentages.  I tried installing in venv and also from git, and neither worked for me.  The only thing that worked was Docker.  I think this was the command:

> docker run allennlp/allennlp:v0.7.0 evaluate https://s3-us-west-2.amazonaws.com/allennlp/models/decomposable-attention-elmo-2018.02.19.tar.gz https://s3-us-west-2.amazonaws.com/allennlp/datasets/snli/snli_1.0_test.jsonl

If I run this, it redownloads the 665 MB model every time.  Also, if I change the location of the input file to a file on the host operating system, it cannot find it.

When I try to copy from the host file system to the Docker file system using 'docker cp &lt;FILENAME> allennlp/allennlp:&lt;FILENAME>' it complains.  Apparently there is an image allennlp, but no container.

I have been trying to get a working Textual Entailment system on my computer for years to help me with a variety of tasks.  I would greatly appreciate it if you could point out the proper usage of Docker in this case.  Ideally would be to run a system service with a client that can batch or individually process sentence pairs.  I tried numerous other techniques which I don't remember, but none of them worked.

Kind Regards,
Andrew

**Comment by vidurj** [comment]
If you place those two files in the directory `~/data`, you could use `docker run -v ~/data:/mnt/data allennlp/allennlp:v0.7.0 evaluate /mnt/data/decomposable-attention-elmo-2018.02.19.tar.gz /mnt/data/snli_1.0_test.jsonl` to run using the local files. See https://stackoverflow.com/questions/44876778/how-can-i-use-a-local-file-on-container.
