### ISSUE TITLE
TransformerXL

### ISSUE THREAD

**Issue by DataDaveH** [allenai/allennlp#2652]
Has anyone done any work on wrapping up TransformerXL for AllenNLP?

**Comment by vidurj** [comment]
Not as far as I know, but @joelgrus might have a more helpful response.

**Comment by joelgrus** [comment]
not that I know of, although the work would likely be similar to what we did for GPT and BERT.

what's your use case?

**Comment by DataDaveH** [comment]
At first fine-tune for a classification task, then probably experiment with it as an embedding layer.

**Comment by matt-gardner** [comment]
Can we reuse all of the data code for BERT, or do we need to make a whole new indexer for this? It'd be nice if this was just a configuration change that relied on work that the huggingface folks have already done.

**Comment by AdLucem** [comment]
Has any work already been done on this? I want to contribute, seeing if there's something I can continue/collaborate on

**Comment by matt-gardner** [comment]
Nope, go for it, we'd appreciate the contribution!

**Comment by matt-gardner** [comment]
This is now covered by the `PretrainedTransformer` stuff.  It's not fully featured yet, but we have other issues for that.
