### ISSUE TITLE
How can I create to different vocabularies for source and targets?

### ISSUE THREAD

**Issue by dDua** [allenai/allennlp#2656]
**System (please complete the following information):**
 - OS: [e.g.  Linux]
 - Python version: [e.g. 3.6.6]
 - AllenNLP version: ["I installed from master"]
 - PyTorch version: 0.4.1

**Question**
I want to create two different vocabularies, one for source and another for target data. The dataset_reader looks like this

"dataset_reader":

 {
        "type": "drop_new",
        "source_token_indexers": {
            "source_tokens": {
                "type": "single_id",
                "lowercase_tokens": true,
                "namespace": "source_tokens"
            },
            "source_token_characters": {
                "type": "characters",
                "min_padding_length": 5,
                "namespace": "source_token_characters"
            },
        },
        "target_token_indexers": {
            "target_tokens": {
                "type": "single_id",
                "lowercase_tokens": true,
                "namespace": "target_tokens"
            },
            "target_token_characters": {
                "type": "characters",
                "min_padding_length": 5,
                "namespace": "target_token_characters"
            },
        }
    }
   ....
   "vocabulary": {
        "min_count": {
            "token_characters": 200
        },
        "pretrained_files": {
            "source_tokens": "/home/ddua/data/embeddings/glove.840B.300d.lower.zip",
            "target_tokens": "/home/ddua/data/embeddings/glove.840B.300d.lower.zip"
        },
        "only_include_pretrained_words": true
    }

The code at https://github.com/allenai/allennlp/blob/master/allennlp/modules/token_embedders/embedding.py#L275 seems to be expecting "tokens" specifically and I can't pass a namespace as an argument. Can anyone please elaborate on the right way to do this? or point me to an example configuration. I couldn't find any in the sample ones in the repo. Thanks!

[config.jsonnet.txt](https://github.com/allenai/allennlp/files/3015487/config.jsonnet.txt)

**Comment by matt-gardner** [comment]
Have a look at this config and see if it answers your questions: https://github.com/allenai/allennlp/blob/master/allennlp/tests/fixtures/encoder_decoder/simple_seq2seq/experiment.json

If not, feel free to ask more.

**Comment by matt-gardner** [comment]
I'm not sure why you want two different vocabularies for DROP, though.

**Comment by dDua** [comment]
> Have a look at this config and see if it answers your questions: https://github.com/allenai/allennlp/blob/master/allennlp/tests/fixtures/encoder_decoder/simple_seq2seq/experiment.json
> 
> If not, feel free to ask more.

Thank you this worked!
