### ISSUE TITLE
How to pass source length to elmo 

### ISSUE THREAD

**Issue by shubhamagarwal92** [allenai/allennlp#2659]
**System (please complete the following information):**
 - OS: [e.g. OSX, Linux]  Linux 
 - Python version: [e.g. 3.6.1] 3.6.8
 - AllenNLP version: [e.g. v0.8.2, or "I installed from master"] 0.8.2
 - PyTorch version: (if you installed it yourself) 1.0.1.post2

**Question**

I am following [this](https://github.com/allenai/allennlp/blob/master/tutorials/how_to/elmo.md#using-elmo-as-a-pytorch-module-to-train-a-new-model) to use elmo embeddings in my pytorch code (not based on allennlp). 

I have a dataset class and try to calculate the elmo embedding in the `__getitem__` method. An excerpt from the code is given below. I am working on a dialogue dataset where I have multiple round of questions. I am using `batch_to_ids` to first convert my token list to character ids and then passing it through `Elmo` module.

* How can I pass max source length to Elmo class so that it can pad (or reduce the sequence size) automatically? The example does not say that I have to pad my sequences beforehand.  

* Is it a good practice to have elmo embeddings in the dataset class and pass it through the iterator or should I use it in the model when I have the embedding layer? The former has the advantage that I can calculate the elmo embedding right before I convert it to tensor using a vocabulary. 

```
from allennlp.modules.elmo import Elmo, batch_to_ids

config ={
options_file: "https://s3-us-west-2.amazonaws.com/allennlp/models/elmo/2x4096_512_2048cnn_2xhighway/elmo_2x4096_512_2048cnn_2xhighway_options.json"
weight_file: "https://s3-us-west-2.amazonaws.com/allennlp/models/elmo/2x4096_512_2048cnn_2xhighway/elmo_2x4096_512_2048cnn_2xhighway_weights.hdf5"
}
class RandomDataset(Dataset):
    def __init__(self):
        ...
        ...

        self.elmo = Elmo(config["options_file"], config["weight_file"],
                 2, dropout=config["elmo_dropout"])


    def __getitem__(self, index):
        ...
        ...

        ques_embeddings = []
        for i in range(len(dialog)):
            ques_char_ids = batch_to_ids(dialog[i]["question"])
            ques_embeddings.append(self.elmo(ques_char_ids)['elmo_representations'][0])
            
            # Here I convert the tokens to tensor
            dialog[i]["question"] = self.vocabulary.to_indices(dialog[i]["question"])
            dialog[i]["question"] = dialog[i]["question"][: self.config["max_sequence_length"] - 1]
        
        ques_embeddings = torch.stack(ques_embeddings,0)
```
 
I am getting the following error which is reasonable as the questions can have different lengths.
How can I pass this `config["max_sequence_length"]` to elmo embedder? 
```
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 27 and 21 in dimension 2 at /pytorch/aten/src/TH/generic/THTensorMoreMath.cpp:1307
```

**Comment by vidurj** [comment]
If you want the output to be padded to more than the maximum sequence length within the batch, you need to pad it yourself. You can do this by concatenating an appropriately sized zero tensor to the output along the time dimension.
