### ISSUE TITLE
Should evaluate support multiple paths to datasets?

### ISSUE THREAD

**Issue by DeNeutoy** [allenai/allennlp#2663]
I have a situation where loading a model takes a bit of time (2-3 min) but evaluation is very fast and I want to evaluate on 5 separate datasets. Should we support passing multiple `input_file` parameters to `evaluate`/`predict`? I can easily write a script to do this, but I can imagine that it would be potentially useful.

**Comment by matt-gardner** [comment]
If it doesn't overly complicate the logic of those commands, I don't see a problem with adding an option for this.

**Comment by c4n** [comment]
Hi,
Does anyone is still working on this feature?
