### ISSUE TITLE
Feature proposal: a generic mechanism for json serialization of instances

### ISSUE THREAD

**Issue by matt-gardner** [allenai/allennlp#2664]
A common pain point in using allennlp is that data processing can take a while, and we don't have a mechanism to cache this or speed it up.  We have solved this in a one-off way in a few different places (e.g., for the wikitables parser).  I think it wouldn't be hard to add a generic mechanism to allow this caching for all dataset readers.

If you look at how we solve this for the wikitables dataset reader, there are three main pieces:
1. A way to serialize `Instances` to [a json line](https://github.com/allenai/allennlp/blob/e1d70bb7b2e6ca1c8961a1789f99a46ebf039187/scripts/wikitables/preprocess_data.py#L26-L52)
2. A way to [read these json lines](https://github.com/allenai/allennlp/blob/e1d70bb7b2e6ca1c8961a1789f99a46ebf039187/allennlp/data/dataset_readers/semantic_parsing/wikitables/wikitables.py#L230-L234) back into `Instances`
3. [A script](https://github.com/allenai/allennlp/blob/e1d70bb7b2e6ca1c8961a1789f99a46ebf039187/scripts/wikitables/preprocess_data.py) to load the data and serialize it.

It should be relatively straightforward for us to provide this functionality in a general way in the base `DatasetReader` class:
1. To serialize `Instances` to json lines, we could make sure that all `Fields` know how to serialize themselves to a json object (pretty easy for most of them), and have the `Instance` serialize all fields as a dictionary.
2. To recover the `Instance` from the json lines, we just read in the format written above (which means each `Field` has to specify its type in the json object, so we can read it correctly, but that's not a huge deal).

Both 1 and 2 can be done generally in `instance_to_json_line()` and `json_line_to_instance()` methods on the base `DatasetReader` class, which can be overridden by particular `DatasetReaders` if they want to customize how the objects are serialized (e.g., to be more efficient in the encoding, to handle crazy data types or side information, to be more aesthetically appealing, or whatever).

3. For a general preprocessing script, we could have a constructor parameter on `DatasetReader` that specifies a path to a preprocessed file.  If this file does not exist, we create it when reading the data by calling `instance_to_json_line()` (this can be done both for lazy and non-lazy behaviors, if we're tricky about it).  If the file exists, we read from the file _instead_ of the typical call to `_read()`, using `json_line_to_instance()`.  There are issues around checking that the parameters that constructed the preprocessed file are the same as when you're reading it, but we could just ignore those and say "user beware" if you're changing parameters like that.

I _think_ this should be pretty easy to implement, and would be a nice addition to the library, especially for datasets that take a long time to preprocess.  What do you think?

cc @alontalmor

**Comment by joelgrus** [comment]
I think something like this is a good idea. My immediate reaction is that hardcoding the notion of "json line" may be too restrictive / prescriptive, and that a more general abstraction might be more like 

```
def serialize_instances(self, instances, path) -> None:

def deserialize_instances(self, path) -> Iterable[Instance]:
```

and then the default implementation would just be json lines as you described. 

(although if every field has a default `to_json` / `from_json`, then it's a lot of work to do anything else.)

**Comment by matt-gardner** [comment]
The benefit of json lines is that you can still make this work if you're reading things lazily, while, e.g., pickling the whole thing wouldn't really work.  But that's the other main option, I think - just allowing the instances to be pickled.

**Comment by matt-gardner** [comment]
Also, json means you can manually inspect this, or port it to some other code outside of allennlp.

**Comment by joelgrus** [comment]
I agree that JSONL should be the default implementation; at the same time, for a giant dataset, I can imagine someone wanting to use protocol buffers or something like that. You've also made me reconsider my interface to 

```
def deserialize_instances(self, path, lazy) -> Iterable[Instance]:
```

which (in the jsonl case) can return lazy or non-lazy as appropriate, and -- in the event someone wanted to implement their own pickle version -- could throw if lazy was True.

**Comment by matt-gardner** [comment]
Ok, yeah, that seems ok.  It just means we'd be adding more methods to the API (the generic serialize methods, and the json-specific ones).  That shouldn't be a big deal, though.

The one issue is with the `serialize_instances` method - if you are _reading_ lazily, how do you call this?  I was imagining that, for the json-only version, I can just write a line to an open file descriptor at every read.  The point was to make this as transparent as possible, without the user having to change anything about their pipeline and getting caching for free.  I don't see a way to accommodate both lazy loading and a `serialize_instances` method as you described it.  Do you?

**Comment by matt-gardner** [comment]
Pinging @joelgrus, @brendan-ai2, @DeNeutoy, anyone else with design thoughts on this - I'd like to start working on this tomorrow or Thursday.  If you have any suggestions for the proposed API, it'd be good to hear them soon.

@joelgrus, I'm still not sure how to prioritize generic serialization versus completely transparent usage (including for lazy reading).  I'm inclined to just do JSON serialization, which we know gives dramatic speed ups in the cases where we have already done it, and which works without any modification, even if you are doing lazy reading.  Your proposal would have me implementing that anyway, but also allowing for more general things - if we run into a need for that, we can add it at that point?  The JSON serialization has an already existing example in our code and several users who are requesting it.

**Comment by DeNeutoy** [comment]
No opinion - one question is how to handle dataset readers which are non-deterministic, e.g a reader for BERT language modelling will produce instances with random cloze masks. I'm sure it's possible to handle this naively initially, and just say "you can't have caching" in this scenario.

**Comment by matt-gardner** [comment]
Thanks @DeNeutoy, that's a good point.  If your instances change at every epoch, then this kind of serialization doesn't work.  In order for it to work, you'd need to serialize some kind of base instance, and allow for mutating it somehow upon read.  Definitely too complex for what I'm imagining.

**Comment by joelgrus** [comment]
yeah, starting with JSON seems fine

**Comment by brendan-ai2** [comment]
Mark's question about non-determinism is definitely important. I've needed this in the past and adding it in properly was already a bit delicate. We'll want to have some very clear documentation about this issue.

My main piece of feedback is that I'm somewhat leery of rolling our own serialization. This has been done many times before and it doesn't seem high impact for us to create something custom. Instead I'd suggest the following:

a. If the focus here is really on caching, we shouldn't overcomplicate things by providing too many hooks and making the default human readable. We should just pick an existing off-the-shelf serializer that is robust to many datatypes. Perhaps Dill? https://pypi.org/project/dill/ This would be very quick to implement. I'd suggest doing this as a baseline at least. (I don't know whether Dill can read a file lazily, but in the worst case we could easily work around this by serializing to strings and making each line a Dill serialized object. `dillL`, basically.)

b. If the focus is really on human readability, then we should still consider existing human readable serializers. A quick search turned up http://jsonpickle.github.io/, for instance.

**Comment by matt-gardner** [comment]
Thanks everyone.  @brendan-ai2, I really like your idea of a dill-lines format, because it lets us get @joelgrus's suggestion of a more generic serialization while also letting everything be one line at a time, so it has seamless integration with our current pipelines.

A big part of the motivation here was that @alontalmor wanted portability of the serialized file.  I think the best solution is to add a `serialize_instance(self, instance: Instance) -> str` method, and a corresponding `deserialize_instance(self, string: str) -> Instance` method to the base `DatasetReader` class, using `dill` as the default implementation.  If someone wants a particular kind of human-readable caching for their data for whatever reason, they can just override those methods for their `DatasetReader`.  Everyone's happy.

I'm going to start working on this now.
