### ISSUE TITLE
Wikitables Java serve process not getting killed

### ISSUE THREAD

**Issue by SandeepBhutani** [allenai/allennlp#2667]
**Describe the bug**
I am running wikitable predict in python multiprocessing module. After the predict is over and I get the result back, the java process made by allennlp is not getting killed. It is taking down my server consuming all cpu and memory. Following is a sample process that keeps on running even after the main process gets over:  
```
sandeep+  4446     1 47 11:47 pts/19   00:09:16 java -jar /home/sandeep/.allennlp/cache/70cdbc01ae81bf9c7ba493151627b27ab0f86026fa89531ada88537c419ba351.9ba2c80a7ede842334060d65d4fc68c62be05b065fc1c98090ede4f0d1edccf7 serve /wikitables/
```

**To Reproduce**
Steps to reproduce the behavior
run process in multiprocessing pool. Even close or terminate or join is not killing these processes.

**Expected behavior**
There is be no such java process after predict is over

**System (please complete the following information):**
 - OS: Linux
 - Python version: 3.6.3
 - AllenNLP version: "I installed from pip install allennlp"
 - PyTorch version: "Not sure of version, but torch is installed"

**Additional context**

**Comment by matt-gardner** [comment]
That code is not designed to be thread-safe, so it's unfortunately not surprising to me that it doesn't work.  We also will be replacing the existing SEMPRE-based WikiTables model with a much better one that does not depend on java within a week or two, so this issue will go away.  I'm going to close this as "won't fix".

**Comment by SandeepBhutani** [comment]
Hi @matt-gardner , We are waiting for Wikitable release. Did not get any notification (watching releases on github). May we know when we should expect this

**Comment by matt-gardner** [comment]
Watch this PR: https://github.com/allenai/allennlp/pull/2637.  When that gets merged, it should come with a new model that gets ~44% accuracy on WikiTableQuestions (_much_ better than the existing model).  @pdasigi was busy cleaning up his paper for the NAACL camera ready deadline, and he's been on vacation.  I expect you'll see some movement on that PR relatively soon.
