### ISSUE TITLE
Non-lazy iterator with epoch tracking sometimes tries to create non-homogeneous batch

### ISSUE THREAD

**Issue by danieldeutsch** [allenai/allennlp#2669]
I am using a non-lazy iterator which also tracks the epoch and uses a maximum number of instances per epoch. On the first batch on the second full pass of the data, the iterator crashes at this line
https://github.com/allenai/allennlp/blob/0abefe2566c843af063dd0e4608002321cc4aa28/allennlp/data/dataset.py#L43-L44

I think I understand what the problem is. The size of my dataset is not evenly divisible by the batch size or the number of instances per epoch, so in the final batch of the first pass, some instances are getting used a second time. The instances being used for a second time already have a `MetadataField` with the epoch number. The final instances from the first pass don't yet, and so when they are all used to create a `Batch`, they don't have the same fields.

I was able to repro it by changing this unit test from
https://github.com/allenai/allennlp/blob/0abefe2566c843af063dd0e4608002321cc4aa28/allennlp/tests/data/iterators/basic_iterator_test.py#L188-L189

to `iterator = BasicIterator(batch_size=2, track_epoch=True, instances_per_epoch=2)`

**Comment by joelgrus** [comment]
sounds like a bug, PR welcome, or else we'll get to it eventually

**Comment by DeNeutoy** [comment]
We fixed this by deleting the code entirely and replacing it with `DataLoaders`
