### ISSUE TITLE
SRL :  what is the featur of the input? 

### ISSUE THREAD

**Issue by Huijun-Cui** [allenai/allennlp#2673]
It seems that your model predict the predicate instead of treating it as golden truth ? Is that true? 
In the paper, the author use another separate model to train the predicate detection model . In allennlp code , I didn`t see any information about the predicate detection model . So I feel confused and asking you for help ,  thank you

**Comment by matt-gardner** [comment]
I already answered this question here: https://github.com/allenai/allennlp/issues/2050#issuecomment-476232696.  Can you ask a more specific question?
