### ISSUE TITLE
Preprocessing PTB dataset for Constituency Parsing

### ISSUE THREAD

**Issue by ichn-hu** [allenai/allennlp#2674]
I have obtained the LDC PTB dataset for constituency parsing, and I am trying to reproduce the result you reported in your demo, therefore I have extracted the config file from the archival file, and the training data is a single file: `/ptb/wsj.train.notrace.trees`, however in the official PTB dataset there is no such file, I am wondering what kind of preprocess did you use to process these scattered files in different sections of WSJ into three individual files, and could you please provide these part of code to me?

**Comment by nelson-liu** [comment]
You might find this helpful: https://github.com/allenai/allennlp/issues/1752 .

There was also some discussion about PTB data preprocessing for constituency parsing in https://github.com/jhcross/span-parser/issues/3 , but it was inconclusive.

Closing the issue for now, feel free to reopen if you have any questions.

**Comment by ichn-hu** [comment]
Could you please confirm that the training dataset is just merge all the single files in sections 00-22 of WSJ, and validation of 23, test of 24 as to me this is the canonical setting?

**Comment by nelson-liu** [comment]
no, there is definitely other preprocessing steps that are done beyond just concatenating the sections. In particular, I know that some steps involve scripts in https://github.com/jeisner/treebank-scripts (e.g., `killnulls`), but I'm not sure which scripts or what order...

**Comment by nelson-liu** [comment]
also: i think the canonical setting is 0-21 for train, 22 for dev, and 23 for test. See section 6, first paragraph of this (recently SOTA) parser: https://arxiv.org/abs/1705.03919

**Comment by ichn-hu** [comment]
I see, thank you for your clarification, btw, could I just use the data in https://github.com/jhcross/span-parser/blob/master/data/ with the additional processing metioned in https://github.com/allenai/allennlp/issues/1752#issuecomment-420474510?

**Comment by nelson-liu** [comment]
yes (though the "additional processing method" is a tweak to the evaluation script). I'll actually open a PR to fix that right now...

**Comment by ichn-hu** [comment]
> yes (though the "additional processing method" is a tweak to the evaluation script). I'll actually open a PR to fix that right now...

EMM, I guess I could just replace all TOP to VROOT by sed...

**Comment by nelson-liu** [comment]
sure, that works too. Opened #2675 anyway, since it's a more general solution.

**Comment by ichn-hu** [comment]
Cool, thank you for this!
