### ISSUE TITLE
Cannot use the Configuration Wizard

### ISSUE THREAD

**Issue by jwc19890114** [allenai/allennlp#2677]
Please first search our GitHub repository for similar questions.  If you don't find a similar example you can use the following template:

**System (please complete the following information):**
 - Python version: [e.g. 3.6]
 - AllenNLP version: [e.g. v0.8.2]
 - PyTorch version: 0.4.0

**Question**
When I try to launch the Configuration Wizard by "allennlp configure serving Config Explorer at http://localhost:8123", I got the bug
>Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex.
usage: allennlp
allennlp: error: unrecognized arguments: serving Config Explorer at http://localhost:8123

**Comment by joelgrus** [comment]
the command is just `allennlp configure`

where did you find the command you tried?

**Comment by jwc19890114** [comment]
> the command is just `allennlp configure`
> 
> where did you find the command you tried?

my fault...
