### ISSUE TITLE
CoreNLP like Server

### ISSUE THREAD

**Issue by vishwas31** [allenai/allennlp#2684]
Hi, I am using allennlp from few days. I am using stanfordCoreNLP as well. For stanfordCoreNLP we have java **server(https://stanfordnlp.github.io/CoreNLP/corenlp-server.html)** which is good for parallel pipleline as well as keep the model running in background on server. no need of reloading the model again and again. 
Is there any feature similar like StanfordCoreNLP server for AllenNLP? This can enhance the scalability of NER model. 
If not then what are the alternatives for this without using FLASK or DJANGO API calls?

**Comment by kernelmachine** [comment]
Currently you can access predictions of a trained model via https://allenai.github.io/allennlp-docs/api/allennlp.service.server_simple.html. As far as I know, there aren't plans to extend this beyond a Flask API - @joelgrus, is this accurate?

**Comment by joelgrus** [comment]
I don't have any plans to extend it further. What needs do you have that making Flask API calls doesn't satisfy?

**Comment by vishwas31** [comment]
> Currently you can access predictions of a trained model via https://allenai.github.io/allennlp-docs/api/allennlp.service.server_simple.html. As far as I know, there aren't plans to extend this beyond a Flask API - @joelgrus, is this accurate?

Okay.

**Comment by vishwas31** [comment]
> I don't have any plans to extend it further. What needs do you have that making Flask API calls doesn't satisfy?

No, it does not. I am processing multiple articles in one go. Hence looking for better alternatives.

**Comment by vishwas31** [comment]
With **StanfordCoreNLPServer** it runs on background and libraries doesn't need to reload again and again. So lets say I have 20 documents to run each with 15 paragraphs then **Allen NER model** reloads again and again and flushes out after each document.

**Comment by vishwas31** [comment]
**(allennlp) mantor@manotr:~/Music/vishwas$ python -m allennlp.service.server_simple --archive-path ~/Music/vishwas/ner-model-2018.12.18.tar.gz --predictor PREDICTOR --title "demo for ner tagger" --field-name sentence
Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex.
/home/mantor/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/data/token_indexers/token_characters_indexer.py:51: UserWarning: You are using the default value (0) of `min_padding_length`, which can cause some subtle bugs (more info see https://github.com/allenai/allennlp/issues/1954). Strongly recommend to set a value, usually the maximum size of the convolutional layer size when using CnnEncoder.
  UserWarning)
Traceback (most recent call last):
  File "/home/mantor/anaconda3/envs/allennlp/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/mantor/anaconda3/envs/allennlp/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/mantor/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/service/server_simple.py", line 758, in <module>
    main(sys.argv[1:])
  File "/home/mantor/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/service/server_simple.py", line 182, in main
    predictor = _get_predictor(args)
  File "/home/mantor/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/service/server_simple.py", line 148, in _get_predictor
    return Predictor.from_archive(archive, args.predictor)
  File "/home/mantor/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/predictors/predictor.py", line 132, in from_archive
    return Predictor.by_name(predictor_name)(model, dataset_reader)
  File "/home/mantor/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/common/registrable.py", line 58, in by_name
    raise ConfigurationError("%s is not a registered name for %s" % (name, cls.__name__))
allennlp.common.checks.ConfigurationError: 'PREDICTOR is not a registered name for Predictor'**


Help Me with the above error as well.

**Comment by joelgrus** [comment]
the simple server should not be reloading anything between requests, have you seen it doing that?

for a NER model the predictor should be `sentence-tagger` not `PREDICTOR`
