### ISSUE TITLE
Fine-tuning problems

### ISSUE THREAD

**Issue by Alea4jacta6est** [allenai/allennlp#2686]
Hi, I fine-tuned a model Decomposable Attention for entailment. Now I want to use it to predict label_probs and I get next error:

```
TypeError                                 Traceback (most recent call last)
<ipython-input-32-db28d09064b1> in <module>
      3 
      4 
----> 5 predictions = predictor.predict(premise=premise, hypothesis=hyp)
      6 predictions['label_probs']

~/anaconda3/lib/python3.7/site-packages/allennlp/predictors/decomposable_attention.py in predict(self, premise, hypothesis)
     29         [entailment, contradiction, neutral].
     30         """
---> 31         return self.predict_json({"premise" : premise, "hypothesis": hypothesis})
     32 
     33     @overrides

~/anaconda3/lib/python3.7/site-packages/allennlp/predictors/predictor.py in predict_json(self, inputs)
     52 
     53     def predict_json(self, inputs: JsonDict) -> JsonDict:
---> 54         instance = self._json_to_instance(inputs)
     55         return self.predict_instance(instance)
     56 

~/anaconda3/lib/python3.7/site-packages/allennlp/predictors/decomposable_attention.py in _json_to_instance(self, json_dict)
     38         premise_text = json_dict["premise"]
     39         hypothesis_text = json_dict["hypothesis"]
---> 40         return self._dataset_reader.text_to_instance(premise_text, hypothesis_text)

TypeError: text_to_instance() missing 1 required positional argument: 'label'
```

My code is 
```
from allennlp.predictors.predictor import Predictor
predictor = Predictor.from_path("model.tar.gz")  #dir is right
premise = 'Michelle wants to change the frequency of her mortgage payments'
hyp = 'Michelle has a mortgage'


predictions = predictor.predict(premise=premise, hypothesis=hyp)
print(predictions['label_probs'])
```

**Comment by nelson-liu** [comment]
The datasetreader should probably be modified to optionally take a label. For now, I think you should be able to get this working by using `predictions = predictor.predict(premise=premise, hypothesis=hyp, label=None)` .

**Comment by Alea4jacta6est** [comment]
> The datasetreader should probably be modified to optionally take a label. For now, I think you should be able to get this working by using `predictions = predictor.predict(premise=premise, hypothesis=hyp, label=None)` .

Unfortunately, it doesn't work
`TypeError                                 Traceback (most recent call last)
<ipython-input-4-685be250c312> in <module>
      3 
      4 
----> 5 predictions = predictor.predict(premise=premise, hypothesis=hyp, label=None)
      6 print(predictions['label_probs'])

TypeError: predict() got an unexpected keyword argument 'label'`

**Comment by nelson-liu** [comment]
which dataset reader did you use to train the decomposable attention model?

**Comment by Alea4jacta6est** [comment]
"dataset_reader": {
    "type": "snli",
    "token_indexers": {
      "tokens": {
        "type": "single_id",
        "lowercase_tokens": true
      }

snli.py (my data is in the same format jsonl with the same labels)

**Comment by Alea4jacta6est** [comment]
I'm sorry - I retrained everything now and it started to predict! Thanks a lot for your help!

**Comment by nelson-liu** [comment]
hmm interesting, not sure what you did wrong. The SNLI dataset reader does indeed take `labels` as an optional argument. Closing this issue, glad to hear it works.
