### ISSUE TITLE
Fine tuning initializing problem

### ISSUE THREAD

**Issue by robbine** [allenai/allennlp#2687]
I think fine-tuning should not use config file in the archive.
My training process consists of two steps:
Step 1. Training a completely new model with full dataset, but somehow using transfer learning as follows:
        "initializer":
         [ [  "norm_layer.weight",
                 {
                     "type": "pretrained",
                     "weights_file_path": "./best.th",
.....
Because I want to use a weight file to initialize my model.
Step 2. Fine-tuning the above model with some new data.
I assume fine-tuning should only load model from archive. But I find the following line in the log which indicates that model is initialized again which is no needed.
2019-04-03 15:27:18,921 - INFO - allennlp.nn.initializers - Done initializing parameters; the following parameters are using their default initialization from their code

**Comment by robbine** [comment]
I'm afraid model weights are overwrite by the initializer specified in the config.json from archive

**Comment by kernelmachine** [comment]
Are you using `allennlp fine-tune` to fine tune? If so, loading the weights and config from the model archive is a feature of that command. It should be used when you'd like to continue training the same model on a new dataset. In your case, you should run your config (with the pretrained initializer) with `allennlp train` command instead.

**Comment by matt-gardner** [comment]
Also, the constructor runs, which prints out that line, and _then_ the saved weights get loaded. So it should be doing the right thing here even with that logging that you're seeing.

**Comment by robbine** [comment]
I get it. If the order is correct, thanks!
