### ISSUE TITLE
Extra documentation for getting started with config files

### ISSUE THREAD

**Issue by ethch18** [allenai/allennlp#2689]
Hello!  I taught an Intro to NLP class earlier this year that used homeworks written with AllenNLP.  One of the main requests by students was more clarity on how to get started with config files.  In response, I wrote up a [guide](https://gitlab.cs.washington.edu/echau18/tech-writing-mirror/blob/master/the-annotated-config/the-annotated-config.md) that tried to build off of the Getting Started tutorials while filling in some additional parts that might not be immediately obvious to people new to NLP.  Is this something that could be useful to the greater AllenNLP user community?

**Comment by kernelmachine** [comment]
Thanks for reaching out! This definitely looks useful for a larger audience, potentially as an addition to the configuration wizard https://github.com/allenai/allennlp/blob/master/tutorials/how_to/create_a_configuration.md. I'll pass this off to @joelgrus, who created the wizard and might have more specific thoughts on this.

**Comment by joelgrus** [comment]
thanks, let me take a look and see where it makes sense to add to our documentation

**Comment by schmmd** [comment]
I previously added a couple of featured external tutorials, but it'd be good to have another category where we can list all external tutorials we know about and have reviewed.  We could find a spot on https://allennlp.org/tutorials but that might require some additional design.  We could also add external tutorials to https://github.com/allenai/allennlp/tree/master/tutorials.

**Comment by schmmd** [comment]
See https://github.com/allenai/allennlp/blob/master/tutorials/README.md#external-tutorials.  @ethanjperez feel free to make a PR against this list with a longer description of your tutorial.
