### ISSUE TITLE
Elmo embeddings on non-words sequences

### ISSUE THREAD

**Issue by galkampel** [allenai/allennlp#2690]
Hi,

I have a sequences of symbols (which can be related to sentences and words respectively), and I would like to use Elmo for representing each symbol (each symbol is a sequence of characters, and those sequences does not form a real word).
I believe that using the pre-trained model as it is won't help me (since I have a different "vocabulary").
Is changing requires_grad to True will change the characters to a better symbol representation?
Is using vocab_to_cache can be helpful?

I also tried to use vocab_to_cache, but I got a RuntimeError: Dimension out of range (expected to be in range of [-1, 0], but got 1) 
The relevant code:
#vocab - a list of all the symbol (string)
#sentences - a tensor of sentences where each symbol is converted to the index where the symbol appears in vocab
elmo = Elmo(options_file, weight_file, num_output_representations=1, dropout=dropout,requires_grad=False,vocab_to_cache=vocab)
embeddings = elmo(sentences) #the problematic row
emb=embeddings['elmo_representations']

I'm new to Allennlp, so if possible, a small example would be very helpful.
Thanks

**Comment by kernelmachine** [comment]
You're correct -- if your dataset doesn't contain English words, the pretrained ELMo model will not be useful to you, since there's no overlap in the vocabularies.  Depending on the size of your dataset and your compute availability, I'd recommend that you train a new ELMo model on your data, using [this](https://github.com/allenai/allennlp/blob/master/tutorials/how_to/training_transformer_elmo.md) tutorial for training the transformer ELMo (or [this](https://github.com/allenai/bilm-tf) repository if you'd like to use the LSTM version of ELMo, and are okay with using Tensorflow).

**Comment by Xiraaa** [comment]
I encountered the same problem when using ELMo embedder.

```
embeddings = self.word_embeddings(sentence) #problematic row
...
sequence_lengths = mask.sum(dim=1).detach().cpu().numpy() # most recent call
```

**Comment by galkampel** [comment]
I have 10-20 thousand unique "words" 80-160 thousand "sentences" (each of which is of size 30). 
I use google colab when GPU is needed (so I'm quite limited with the compute availability..).
How long would it take to train with transformer ELMo with such data? (hours or days)
I also tried using Word2Vec and GloVe, but it didn't give a satisfactory results. Are there any other recommended word embedding methods to try (at the end of the day I need a single representation for each word)

**Comment by kernelmachine** [comment]
It's difficult to estimate how long it would take, because it depends on your machine. As a reference point, a ELMo Transformer model that I'm training right now takes about 9 hours per epoch for a dataset with 12M English sentences, with about 1M unique tokens, using a 12GB GTX 1080.

**Comment by kernelmachine** [comment]
I'm closing this issue as this question has been answered.
