### ISSUE TITLE
Logging loss functions with multiple terms

### ISSUE THREAD

**Issue by vikigenius** [allenai/allennlp#2693]
Let's say I am implementing a VAE. Typically there are 2 loss terms, one for reconstruction and another for KL.

Let's say I have a separate class/function which does all the weighting and KL annealing. But my model's function will only return the final loss. How can I also log each of the terms in the loss separately to tensorboard, so that I can see the KL term's behaviour?

**Comment by kernelmachine** [comment]
If you set the KL term (or anything else you'd like to track) as a metric, it will automatically be logged in tensorboard (as well as to the console). 

For example, in the CRF tagger, in addition to F1, we track accuracy metrics by initializing `self.metrics` like so: https://github.com/allenai/allennlp/blob/master/allennlp/models/crf_tagger.py#L123

Then, in the `get_metrics` method, you can handle all the metrics appropriately, e.g. https://github.com/allenai/allennlp/blob/master/allennlp/models/crf_tagger.py#L240

**Comment by kernelmachine** [comment]
I'll close this issue as this question as been answered.

**Comment by mataney** [comment]
Hi @vikigenius and @kernelmachine 
I uploaded a PR with my implementation of a VAE, maybe it will help.

https://github.com/allenai/allennlp/pull/2484

**Comment by napsternxg** [comment]
@kernelmachine I have a question about this. Wouldn't this approach require recomputing the loss again in the metrics routine? E.g. for VAE I would need to compute the part losses to get the final loss, however, in metrics I need to recompute the losses again. Is there an efficient way to do this?
