### ISSUE TITLE
Adding Dependabot to this project

### ISSUE THREAD

**Issue by bryant1410** [allenai/allennlp#2699]
What about using [Dependabot](https://dependabot.com/) for this project?

It can help to keep the pinned dependencies up-to-date. For example, it'd be good to keep pylint and mypy updated, to fix false positives and also add new checks.

It provides a convenient way of updating the codebase and, at the same time, minimizing the overhead. It opens PRs and shows the changelog. Usually, the flow would be like: the checks pass, the changelog makes sense, someone approves it and it's merged. When it fails or when the changelog shows something that needs intervention, someone rejects it and provides a comment, then anybody else can provide a fix in the same PR and proceed.

It can be set up to avoid bothering people. For example, it can be set up to receive PR updates once a month only. It can also be set up to blacklist some dependencies (e.g., conllu), albeit maybe it's better to leave a PR open with an update for them maybe than to blacklist them.

I wonder if it works for `<2.2.0`-like dependency version constraints. I'm pretty sure it doesn't bother for `>=1.2.0` and unconstrained versions (because there's nothing to be changed in the file there that makes a new version incompatible).

**Comment by kl2806** [comment]
Sounds like it could be useful, we probably want @joelgrus's opinion on this so will probably have to wait until he gets back next week.

**Comment by joelgrus** [comment]
in an ideal world we'd keep mypy and pylint up to date, but both are pinned for *reasons*, and it would require a fair amount of work to get the code base to pass the latest versions of each. I'd love to do it at some point, but it's pretty low priority.

**Comment by matt-gardner** [comment]
Is it worth revisiting this?  flake8 and mypy are now up to date.

**Comment by DeNeutoy** [comment]
I did this! Closing.
