### ISSUE TITLE
Elmo weighting

### ISSUE THREAD

**Issue by Rhuax** [allenai/allennlp#2700]
In Elmo, when using num_output_representations=1, is it already computing a weighted sum of each layer of the model? If yes, when I include it into a larger model will the weights trained as the large model trains?

**Comment by kl2806** [comment]
Setting `num_output_representations=1` creates one Elmo representation that yes, is a weighted sum. Increasing `num_output_representations` creates different weighted combinations. You can set `requires_grad` depending on whether you want to update the weights or freeze them for the larger model.

**Comment by Rhuax** [comment]
Thanks, I close

**Comment by Rhuax** [comment]
I noticed that if `requires_grad = False` every scalar mix inside `self._scalar_mixes` is trained anyway. So setting `requires_grad` to True enables also the training of elmo's pre-trained weights?

**Comment by kl2806** [comment]
1. Sorry if that was unclear, `requires_grad` is for setting whether to fine-tune the Elmo weights. The scalar weights are specified by `scalar_mix_parameters` and the default is `None` which lets the model learn the scalar weighting.
2. I'm not sure how you want to use Elmo with the decoder, there is some discussion in #2550 that might be helpful to you.

**Comment by matt-gardner** [comment]
As far as I know, no one has tried using ELMo in a decoder like this, so it's an open question.  Let us know how it works!
