### ISSUE TITLE
Support a command that compares against different models

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp#2701]
Yanai (@yanaiela) from AI2 Israel is interested in an AllenNLP command that allows a user to easily compare two models.  For example, you might be extending an existing model to do something new (such as use BERT instead of ELMo) and want to see which predictions differ over the dev set.  It would be convenient if you could run something like:

```
allennlp compare model1 model2 devset
```

**Comment by matt-gardner** [comment]
It would also be nice to automatically compute statistical significance tests, where appropriate.

**Comment by DeNeutoy** [comment]
This should probably be a script, closing
