### ISSUE TITLE
How To Incorporate Numeric Features?

### ISSUE THREAD

**Issue by DWDuq** [allenai/allennlp#2702]
I'm trying to classify some documents, but in addition to the document text, I have some numeric features that I think might be valuable.  Is there currently any way to add numeric features to the final feed forward output layer(s)?  If not, is this something that would be hard for me change in the code?   Where would I start?

**Comment by kl2806** [comment]
In AllenNLP, inputs that are converted into tensors are `Fields`. For incorporating numeric features, the `ArrayField` (https://github.com/allenai/allennlp/blob/master/allennlp/data/fields/array_field.py) would probably be the most natural way of representing this information.
