### ISSUE TITLE
Phrase matching

### ISSUE THREAD

**Issue by borabaloglu** [allenai/allennlp#2703]
- OS: OSX
 - Python version: 3.7.2
 - AllenNLP version: 0.8.3

I am working on phrase matching, i.e matching "President of the US" and "Donald Trump" should give a high score. In other way, anything else which is not related to each other such as "Donald Trump" and my name which is "Bora Baloglu" should give a very low score. I used "Textual Entailment" feature but it didn't help. I am thinking of embedding both phrase, then compare the embedded forms. However, I couldn't find a way to implement it. Any idea?

**Comment by kl2806** [comment]
I think the `SpanField` (https://github.com/allenai/allennlp/blob/master/allennlp/data/fields/span_field.py) might be useful for you if you want to get an embedding for the spans and then do some modeling on top of that.

**Comment by matt-gardner** [comment]
Stepping back, though, are you hoping to train a model to give these scores, or do you want to just put existing pieces together to get the output that you want?  If the latter, I think you're going to have a very hard time.  If the former, what data are you using?

In short, what you're describing is a research problem, not something that we (or anyone, really) have out-of-the-box solutions for.  If you have a question about how to use the library to solve that research question, we're happy to try to answer it, but we can't design a solution to the research problem for you.  I'm closing this; feel free to comment and ask a new question if I misunderstood your issue.
