### ISSUE TITLE
NameError: name 'cached_file'

### ISSUE THREAD

**Issue by daitlq** [allenai/allennlp#2704]
When I run command for train pos tagger **allennlp train tutorials/tagger/experiment.jsonnet -s /tmp/serialization_dir --include-package tutorials.tagger.config_allennlp**; I have an error with cached_file **NameError: name 'cached_file' is not defined**

Please guide me for fix it.

Thanks for your support!

**Comment by kl2806** [comment]
I think that this should be `cached_path`, I'll submit a PR for this. Thanks for raising this!

**Comment by daitlq** [comment]
I change cached_file to cached_path and it worked.

Thanks for your support
