### ISSUE TITLE
Shared padding length between instances of TokenCharactersIndexer with same vocabulary namespace

### ISSUE THREAD

**Issue by festeh** [allenai/allennlp#2715]
**Describe the bug**
In my model I'd like to split each word into characters in two ways. For example:
* the -> ["t", "h", "e"]  (to create word embedding by processing character sequence with CNN)
* the -> [START, "t", "h", "e", END] (to train char-level language model on words)

For that purpose I create two separate `TokenCharactersIndexer`s in my `DatasetReader` (note that they share the same vocab namespace). I expect that padded tensors obtained from them should have different sizes (second way requires two more indices for every word), but they are the same - basically additional zeros are appended to the first tensor. Is that behavior intended? And, if so, how to handle my use case properly?

Thank you!

**To Reproduce**
Run the code
```
from allennlp.data import DatasetReader, Instance, Token, Vocabulary
from allennlp.data.dataset import Batch
from allennlp.data.fields import TextField
from allennlp.data.token_indexers import TokenCharactersIndexer
from allennlp.data.tokenizers import CharacterTokenizer


class SimpleReader(DatasetReader):
    def __init__(self):
        super().__init__()
        self.indexers = {
            "char_indexer": TokenCharactersIndexer(),
            "char_indexer_with_start_end": TokenCharactersIndexer(
                character_tokenizer=CharacterTokenizer(
                    start_tokens=["START"], end_tokens=["END"]
                )
            ),
        }

    def text_to_instance(self, text) -> Instance:
        return Instance({"source": TextField([Token(text)], self.indexers)})


if __name__ == "__main__":
    text = "the"
    instance = SimpleReader().text_to_instance(text)
    vocab = Vocabulary.from_instances([instance])
    batch = Batch([instance])
    batch.index_instances(vocab)
    print(batch.as_tensor_dict()["source"])

```

**Expected behavior**
I expected to see

`{'char_indexer': tensor([[[2, 3, 4]]]), 'char_indexer_with_start_end': tensor([[[5, 2, 3, 4, 6]]])}`

But got

`{'char_indexer': tensor([[[2, 3, 4, 0, 0]]]), 'char_indexer_with_start_end': tensor([[[5, 2, 3, 4, 6]]])}`

**System (please complete the following information):**
 - AllenNLP version: 0.8.3

**Comment by matt-gardner** [comment]
We assume that for a single `TextField`, you have a single list of `Tokens` that will eventually get represented as vectors in your model, so we pad all of the token lists in a single `TextField` to have the same number of tokens*.  That is, in your model, you will (presumably) be applying a `TextFieldEmbedder` to the output of this `TextField`, getting a single tensor out - if you have two different numbers of tokens, what shape should that tensor have?  So, yes, the behavior you're seeing is baked into the library on purpose.

The way to get around it is to put the two `Indexers` that you want into two _separate_ `TextFields`, one for `inputs` or `source`, and one for `outputs` or `target` (or however else you want to name them).  That way they will get separate padding, and all will be as you expect.

\* This isn't strictly true, but it's close enough for now.

**Comment by festeh** [comment]
Got it, thanks again!
