### ISSUE TITLE
Get word vectors in context of a specific sentence only

### ISSUE THREAD

**Issue by bikashg** [allenai/allennlp#2722]
**System (please complete the following information):**
 - OS: [OSX, Linux]
 - Python version: [3.6.1]
 - AllenNLP version: ["I installed using pip install on conda"]
 - PyTorch version: (used pip install on conda)

**Question**
* How can I get word vectors in context of a specific sentence only?

* I am working on a sentence classification task (sentence -> label). Each example (sentence+label) is independent of the others.  For a given sentence, I want to use ELMO to retrieve word vectors in the context of that particular sentence only. I tried the code under "Using ELMo interactively" section and observed that ELMO takes context of all the previous sentences it has been fed to. My code is as follows :

`In [1]: from allennlp.commands.elmo import ElmoEmbedder
Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex.

In [2]: elmo = ElmoEmbedder()

In [3]: vectorsA = elmo.embed_sentence(["I", "ate", "a", "carrot", "for", "breakfast"])

In [4]: vectorsA[2][0]
Out[4]:
array([-3.263432  , -0.9447762 , -0.31986535, ..., -1.6759347 ,
       -0.11119218,  0.4732671 ], dtype=float32)

In [5]: vectorsB = elmo.embed_sentence(["I", "ate", "a", "carrot", "for", "breakfast"])  # the same tokens as in the first sentence.

In [6]: vectorsB[2][0]  # I would have like to get the same result as of vectorsA[2][0]
Out[6]:
array([-2.7823038 , -0.8513454 , -0.41176632, ..., -1.6738499 ,
       -0.07920279,  0.48257217], dtype=float32)`

Although my first and the second sentences contain the same words, they are independent of each other. Hence, I would like to have the vectorsA[2][0] and vectorsB[2][0] be the same value. How could I do that? I noticed that I could initialise the `elmo` object each time before calling `elmo.embed_sentence()` but that would take a very long time when processing 100s of sentences.

**Comment by matt-gardner** [comment]
This is just how ELMo works: https://github.com/allenai/allennlp/blob/master/tutorials/how_to/elmo.md#notes-on-statefulness-and-non-determinism.  In particular:

```
After loading the pre-trained model, the first few batches will be negatively impacted
until the biLM can reset its internal states. You may want to run a few batches through
the model to warm up the states before making predictions (although we have not
worried about this issue in practice).
```

After the first few batches, differences between subsequent runs should be very minor.
