### ISSUE TITLE
[Suggestion] Add an overrides example to Commands

### ISSUE THREAD

**Issue by Whu-wxy** [allenai/allennlp#2724]
**'--overrides' item confuses beginner**
Help for '--overrides' prompts for a json structure.
It's better to provide an example like '{\"iterator.batch_size\":16}'

**Comment by matt-gardner** [comment]
I'm actually a little confused by that structure; I didn't know you could use dotted keys inside of a dictionary like that =).  You're right that this parameter is confusing.  If you think our help text could be better, please feel free to submit a PR to improve it!

**Comment by Whu-wxy** [comment]
How about this:
a JSON structure used to override the experiment configuration,'
',e.g.{\\"iterator.batch_size\\":16}, the key means to recursively '
'look for a key in the parameter file, each key is separated by "."

**Comment by chenqiuyuan** [comment]
> 
> 
> How about this:
> a JSON structure used to override the experiment configuration,'
> ',e.g.{\"iterator.batch_size\":16}, the key means to recursively '
> 'look for a key in the parameter file, each key is separated by "."

Very nice comment on the parameter, thanks very much 👍
