### ISSUE TITLE
Best way to augment data at each epoch

### ISSUE THREAD

**Issue by mojesty** [allenai/allennlp#2725]
Please first search our GitHub repository for similar questions.  If you don't find a similar example you can use the following template:

**System (please complete the following information):**
 - Python version: 3.6.5
 - AllenNLP version: 0.8.1

**Question**
I am working on an irrelevant sentence detection in a low-resource domain, thus I want to use augmentations (random words swap/drop of irrelevant sentences, I am pretty sure that these augmentations are valid for my particular task). However, I want to do the same augmentations __differently__ for each epoch, because in fixed augmentation settings (I just create synthetic dataset with 10 times original dataset, but augment each sentence randomly) the model seems to overfit as well.

So I see 3 opportunities:
- Synthesize very large (x100-x200) dataset with augmentations with vocabulry constructed from original dataset, than slice it at (train_subdataset, valid_subdataset) pairs for each real epoch and feed only them (somehow change DataIterator, I suppose)
- Make `AugmentableInstance(Instance)` class which stores its original data, and make augmentation work on every call to `fields`, for instance and do not change anything else (sound weird, but ut should work)
- Your variant

In ideal case, I also want to make augmentations registrable and specify tham in configs, but this feature is optional (and not easy to implement anyways)
Any discussion on how to solve my problem?

**Comment by matt-gardner** [comment]
The way we've handled this in the past is to use a lazy dataset reader that reads everything into memory, but re-does the random bits at every pass through the data.  That is, if each instance has a random number associated with it, I read in all of the data into memory in the first call to `_read()`, and cache it, but without having sampled the random number.  Then each call to `_read()` I do the sampling and add it to the instance.  For example:

```python
def _read(file_path: str):
    if not self._instances:
        self._instances = self._actually_read_instances_from_file(file_path)
    for instance in self._instances:
        sampled_instance = self._augment_instance_with_random_bits(instance)
        # if you don't want to duplicate the data inside of the instance,
        # you could just mutate the instance, changing the relevant fields at each epoch
        yield sampled_instance
```

This _should_ work, and I think it's the cleanest way to solve your problem.  Does this make sense?

**Comment by matt-gardner** [comment]
Note that if you don't pass `lazy=True` to the super class constructor, `DatasetReader` will be smart and just keep the first epoch's instances for all of training.  So for this to work you _must_ pass `lazy=True`.

There might be some complications here with computing vocabulary, so you'll have to think carefully about how that works.  Also, doing it this way makes it easy to put options for whatever you want to configure in your sampling into the `DatasetReader`, and you can get as fancy (or not) as you want with that.

**Comment by mojesty** [comment]
Thanks for fast reply!
Tested this out on a toy example, looks like a nice way to handle my problem.
So maybe the most allennlp-like solution would be to create `AugmentedDatasetReader(DatasetReader)` which provides interface for augmentations 
` def __init__(self, augmentations: Optional[List[Augmentation]] = None, ...)`
, create `class Augmentation(Registrable)` with interface like `def __call__(self, instance: Instance) -> Instance`, so augmentations create stackable (my use case requires that, and one can play around with augmentations that way).
I see following limitations of this approach:
- Detokenization may be necessary every time (but with tokenizers like Spacy that provide `token_with_ws_` it should not be a problem)
- If augmentation is _conditional_ (for example, applied only to negative class), this logic is implemented in code and cannot be easily parameterized via configs, which is my use case also, I thinks that in this framework one should pass several lists of augmentations (or a Dict) to the `__init__` method.
- Any augmentation that acts at an Instance-level scope should fit in this framework, which is I think 99% of use cases

**Comment by joelgrus** [comment]
one of our goals for this quarter is to rewrite the trainer so that most of its behavior is configurable using (potentially custom) callbacks that run in response to specified events.

so you could imagine a setup where you have some sort of custom `augment_instances` callback that runs at the beginning of each epoch and modifies each instance. the downside is that (1) you can't do this right now, and (2) you'd have an extra iteration over the instances each epoch

**Comment by matt-gardner** [comment]
@mojesty, that's an interesting idea; you mentioned "allennlp-like solutions", and one key principle we try to follow is to not over-engineer things with too many abstractions.  Each one adds overhead, and we should only include ones that are generally useful across a bunch of use cases.  It's possible that your idea fits, but we'd want several different concrete, in-demand use cases to nail down the details of the abstraction before adding it.

I'm going to close this issue, as I believe your initial question has been answered.  Feel free to keep commenting if you have more questions!

**Comment by zhmd** [comment]
Many thanks to @matt-gardner, for sharing this solution!
However, I'm wondering if we hack the DatasetReader with lazy=True as you described here, then we need to use two separate dataset reader objects for "train" and "validation" dataset, rather than a single object to read two different datasets (as in tutorial). Is that correct?
Also, I'm curious if it's more convenient/possible to extend an "iterator" for the negative sampling purpose. Any suggestions?

**Comment by mojesty** [comment]
Usually you want validation dataset to be without any augmentation, in order to test on a real (not augmented data).
Regarding the negative sampling, I usually do it in my DatasetReader and control it with a special hyperparameter that I tune with other hyperparameters.

**Comment by zhmd** [comment]
Thanks @mojesty ! Yes you are right, I only need to perform negative sampling for the training set, but still, I have to create another dataset reader object for validation dataset. (I actually use a flag in my custom dataset reader class to indicate whether it performs augmentation or not, so only for training the flag is on.) Just want to make sure if I missed something here.
Also, if you could kindly share some codes about how to elegantly do negative sampling on the fly in allennlp framework, it would be greatly appreciated.
Thanks again!
