### ISSUE TITLE
I could find predictor models for all demo examples except NAQANet. 

### ISSUE THREAD

**Issue by beviah** [allenai/allennlp#2730]
Can you add that one as well? 

https://allennlp.org/models

It is missing NAQANet model used on the demo page:
https://demo.allennlp.org/reading-comprehension

**Comment by matt-gardner** [comment]
@beviah, see #2731. We want to redo the models page in the near future anyway (right @schmmd?), so I'm just adding it to this repo.  That PR gives you the path to the model, and using it with commands similar to BiDAF should work.  Let me know if you have issues.

**Comment by schmmd** [comment]
I'd like to merge the models page with the demo itself, so we're sure to have this information with each demo.  I've been waiting for some design input first, however.
