### ISSUE TITLE
Different prediction for the same input over time

### ISSUE THREAD

**Issue by AvivWn** [allenai/allennlp#2732]
I am using the constituency predictor as appears in the trained models on the website. I noticed that when I am using the **same** predictor object in order to predict the phrase tree of many sentences (one sentence at a time), the resulted trees are different from when predicting on a single sentence, withers specific predictor object.
Afterwards, I even discovered that sometimes the first prediction on a sentence isn't equal to the second prediction on the same sentence.

**Code example**-
from allennlp.predictors.constituency_parser import ConstituencyParserPredictor
predictor = ConstituencyParserPredictor.from_path("https://s3-us-west-2.amazonaws.com/allennlp/models/elmo-constituency-parser-2018.03.14.tar.gz")
sent = "i suggested his taking out loans to pay for college."
phrase_tree1 = predictor.predict(sentence=sent)['trees']
phrase_tree2 = predictor.predict(sentence=sent)['trees']

The resulted trees I got:
phrase_tree1: (S (NP (PRP i)) (VP (VBD suggested) (S (NP (PRP$ his)) (VP (VBG taking) (PRT (RP out)) (NP (NNS loans)) (S (VP (TO to) (VP (VB pay) (PP (IN for) (NP (NN college))))))))) (. .))
phrase_tree2: (S (NP (PRP i)) (VP (VBD suggested) (S (NP (PRP$ his)) (VBG taking) (PRT (RP out)) (NP (NNS loans)) (S (VP (TO to) (VP (VB pay) (PP (IN for) (NP (NN college)))))))) (. .))

You can check and see that phrase_tree1 != phrase_tree2. This should be reproduce, at least with the given sentence.

Why? I hope that there is a way to "clean" the predictor after each prediction or something like that. Of course that I can create a new predictor for each prediction, but it sounds not efficient at all (this solve the issue currently).
Maybe the model continue learning also after my first prediction? So, hopefully there is a way to limit its learning when predicting.

 - OS: Linux
 - Python version: python 3.6.8
 - AllenNLP version: v0.7.1

**Comment by matt-gardner** [comment]
This is known and expected behavior with ELMo: https://github.com/allenai/allennlp/blob/deae1db203efa9400b1d8b479b4faca3876a907a/tutorials/how_to/elmo.md#notes-on-statefulness-and-non-determinism

There are a number of other issues you can find that also relate to this, talking about differing predictions with ELMo, if you want to see some more discussion, but it's mostly the same as what you see in what I linked to.
