### ISSUE TITLE
Add knockknock support in allennlp

### ISSUE THREAD

**Issue by Shuailong** [allenai/allennlp#2737]
**Is your feature request related to a problem? Please describe.**
I would like to get notified via email/slack/telegram when my model training has finished or crashed.

**Describe the solution you'd like**
``huggingface`` provides a quite useful tool named [knock knock](https://github.com/huggingface/knockknock) to help with this. What they do is to add a wrapper to the`` train`` function.

I love Allennlp and use it a lot in my own research and projects. I think it would be great if we integrate add such feature into Allennlp. Otherwise, I have to subclass the Trainer class?

**Comment by DeNeutoy** [comment]
Hi!

That sounds like it might be helpful for some users, but is unlikely to be something we will consider adding to allennlp directly (I get enough slack messages already!). However, we are in the process of adding callbacks to the trainer, which will allow you to implement this yourself. See #2587 for more discussion and tracking.

**Comment by VictorSanh** [comment]
Hello!

I just came across this thread.
@Shuailong, in case you did not see it, i just wanted to point out that @ChristophAlt did a pretty nice PR that enables command line applications in knockknock.

Basically pretty much the same call:
`knockknock telegram --token <your_api_token> --chat-id <your_messaging_room_id> sleep 10`

Victor

**Comment by Shuailong** [comment]
> Hello!
> 
> I just came across this thread.
> @Shuailong, in case you did not see it, i just wanted to point out that @ChristophAlt did a pretty nice PR that enables command line applications in knockknock.
> 
> Basically pretty much the same call:
> `knockknock telegram --token <your_api_token> --chat-id <your_messaging_room_id> sleep 10`
> 
> Victor

@VictorSanh Hi Victor, Thanks for your info! I am still not sure how to use it in Allannlp, could you show the PR URL or some example?

Best
Shuailong

**Comment by VictorSanh** [comment]
> > Hello!
> > I just came across this thread.
> > @Shuailong, in case you did not see it, i just wanted to point out that @ChristophAlt did a pretty nice PR that enables command line applications in knockknock.
> > Basically pretty much the same call:
> > `knockknock telegram --token <your_api_token> --chat-id <your_messaging_room_id> sleep 10`
> > Victor
> 
> @VictorSanh Hi Victor, Thanks for your info! I am still not sure how to use it in Allannlp, could you show the PR URL or some example?
> 
> Best
> Shuailong

If you use allennlp command line commands (train, test, etc.), you can simply preprend `knockknock telegram --token <your_api_token> --chat-id <your_messaging_room_id>` to your command line call (`allennlp train <some_other_arguments>`).

**Comment by Shuailong** [comment]
> > > Hello!
> > > I just came across this thread.
> > > @Shuailong, in case you did not see it, i just wanted to point out that @ChristophAlt did a pretty nice PR that enables command line applications in knockknock.
> > > Basically pretty much the same call:
> > > `knockknock telegram --token <your_api_token> --chat-id <your_messaging_room_id> sleep 10`
> > > Victor
> > 
> > 
> > @VictorSanh Hi Victor, Thanks for your info! I am still not sure how to use it in Allannlp, could you show the PR URL or some example?
> > Best
> > Shuailong
> 
> If you use allennlp command line commands (train, test, etc.), you can simply preprend `knockknock telegram --token <your_api_token> --chat-id <your_messaging_room_id>` to your command line call (`allennlp train <some_other_arguments>`).

Wow!! That works like magic! Thanks, Victor!
