### ISSUE TITLE
ConfigurationError: Extra parameters passed to CrfTagger

### ISSUE THREAD

**Issue by beviah** [allenai/allennlp#2742]
fine_grained_named_entity_recognition_with_elmo_peters_2018() and fine-grained-ner-model-elmo-2018.08.31.tar used to work well in version 0.8.1. Now they show above error in 
https://github.com/allenai/allennlp/blob/0abefe2566c843af063dd0e4608002321cc4aa28/allennlp/common/params.py#L404

**Comment by DeNeutoy** [comment]
the `constraint_type` parameter was depreciated in 0.8.X, please use the updated model: 
`https://s3-us-west-2.amazonaws.com/allennlp/models/ner-model-2018.12.18.tar.gz`

https://github.com/allenai/allennlp/pull/2208
