### ISSUE TITLE
Pretrained model for NAQA on DROP

### ISSUE THREAD

**Issue by crossoveranx** [allenai/allennlp#2746]
**Question**
I see you've uploaded NAQANet and I wanted to try out it's capabilities. Does a pretrained model on DROP exist for download anywhere?

**Comment by matt-gardner** [comment]
If you use the latest master, you can call this function: https://github.com/allenai/allennlp/blob/b90722188a1ff670f5b1cb8a8f2bdb57c42efe1b/allennlp/pretrained.py#L40-L45

If you're not using the latest master, you can call the code inside that function in your own script.
