### ISSUE TITLE
about logger

### ISSUE THREAD

**Issue by labixiaoK** [allenai/allennlp#2757]
**System (please complete the following information):**
 - OS: CentOS Linux release 7.3.1611 (Core)
 - Python version:  3.6.8
 - AllenNLP version:  0.8.2
 - PyTorch version: 1.0.1

**Question**
hi，why can not I get infos which are produced by `logger.info('Gradual unfreezing finished. Training all layers.')` within the script ? what I can get are only the tqdm bars of DatasetReader and Trainer, how can I get the logger.info within the *.py?
thanks

**Comment by DeNeutoy** [comment]
Are you running your own script, or an allennlp command? If you're running your own script, you might need to configure the python logging level as we do here: 

https://github.com/allenai/allennlp/blob/d6e3140ffa6629c8e45a75c7920dcd6cf0186902/allennlp/run.py#L12

Does that help things? Otherwise, please try to provide some example code or commands you ran so we can help you more effectively.

**Comment by labixiaoK** [comment]
ok, I run my script, 
my train.py mainly contain 
```
def main(config):
    ....
    trainer = Trainer(model=model, optimizer=optimizer,
                 iterator=iterator, train_dataset=train_ds,
                 validation_dataset=valid_ds,
                 learning_rate_scheduler=slanted_triangular,
                 cuda_device=config['device'] if USE_GPU else -1, 
                 num_epochs=config['epochs'],
                 serialization_dir=config['ser_dir'],
                 patience=10,
                 histogram_interval=500, summary_interval=300,
                 num_serialized_models_to_keep=3,
                 should_log_learning_rate=True,
                  )   
    metrics = trainer.train()

    return metrics
```

and I run this script just by `python train.py config > tmp.log`

u say I need to config the logging in my script? does it work for allennlp's logger? 
btw, what I want is the log infos produced by allennlp's scripts , not mine. 
 thanks

**Comment by labixiaoK** [comment]
> Are you running your own script, or an allennlp command? If you're running your own script, you might need to configure the python logging level as we do here:
> 
> [allennlp/allennlp/run.py](https://github.com/allenai/allennlp/blob/d6e3140ffa6629c8e45a75c7920dcd6cf0186902/allennlp/run.py#L12)
> 
> Line 12 in [d6e3140](/allenai/allennlp/commit/d6e3140ffa6629c8e45a75c7920dcd6cf0186902)
> 
>  logging.basicConfig(format='%(asctime)s - %(levelname)s - %(name)s - %(message)s', 
> Does that help things? Otherwise, please try to provide some example code or commands you ran so we can help you more effectively.

ok, I run my script, 
my train.py mainly contain 
```
def main(config):
    ....
    trainer = Trainer(model=model, optimizer=optimizer,
                 iterator=iterator, train_dataset=train_ds,
                 validation_dataset=valid_ds,
                 learning_rate_scheduler=slanted_triangular,
                 cuda_device=config['device'] if USE_GPU else -1, 
                 num_epochs=config['epochs'],
                 serialization_dir=config['ser_dir'],
                 patience=10,
                 histogram_interval=500, summary_interval=300,
                 num_serialized_models_to_keep=3,
                 should_log_learning_rate=True,
                  )   
    metrics = trainer.train()

    return metrics
```

and I run this script just by `python train.py config > tmp.log`

u say I need to config the logging in my script? does it work for allennlp's logger? 
btw, what I want is the log infos produced by allennlp's scripts , not mine. 
 thanks

**Comment by DeNeutoy** [comment]
Ah ok I understand now, you need to call this function (as well as setting the logging level as in my comment above):

https://github.com/allenai/allennlp/blob/master/allennlp/common/util.py#L208

What it does is attaches a `TeeLogger` to `stdout` so that the logging is printed to both a file and the console.

**Comment by labixiaoK** [comment]
> Ah ok I understand now, you need to call this function (as well as setting the logging level as in my comment above):
> 
> https://github.com/allenai/allennlp/blob/master/allennlp/common/util.py#L208
> 
> What it does is attaches a `TeeLogger` to `stdout` so that the logging is printed to both a file and the console.

ah, wonderful，thank u a lot.
ps: I have tried to use `TeeLogger` and found the `prepare_global_logging()`, but I don't know how to make it work  ><

**Comment by DeNeutoy** [comment]
Great!
