### ISSUE TITLE
 How can I train ELMo embeddings with my own corpus?

### ISSUE THREAD

**Issue by Greenbald** [allenai/allennlp#2760]
Even with similar questions, I'm still confused if nowadays there is an implementation for training ELMo with my own corpus, using PyTorch (via AllenNLP). In previous questions (#1061 and #1356) the devs point to https://github.com/allenai/bilm-tf. But is there a PyTorch approach to train ELMo with my own corpus? Did I miss something?

Thanks.

**Comment by DeNeutoy** [comment]
We can now train a transformer version of ELMo which is substantially faster from within allennlp in pytorch. You can read more about it in this document:

https://github.com/allenai/allennlp/blob/master/tutorials/how_to/training_transformer_elmo.md

Thanks! Open an issue if you have any problems etc.

**Comment by rianapriansyah** [comment]
> We can now train a transformer version of ELMo which is substantially faster from within allennlp in pytorch. You can read more about it in this document:
> 
> https://github.com/allenai/allennlp/blob/master/tutorials/how_to/training_transformer_elmo.md
> 
> Thanks! Open an issue if you have any problems etc.

Hi @DeNeutoy 

Seems like the link is not working anymore. Do you have any updated link?

Thanks

**Comment by svmihar** [comment]
> > We can now train a transformer version of ELMo which is substantially faster from within allennlp in pytorch. You can read more about it in this document:
> > https://github.com/allenai/allennlp/blob/master/tutorials/how_to/training_transformer_elmo.md
> > Thanks! Open an issue if you have any problems etc.
> 
> Hi @DeNeutoy
> 
> Seems like the link is not working anymore. Do you have any updated link?
> 
> Thanks
they move the tutorial to [here](https://github.com/allenai/allennlp/blob/v0.8.3/tutorials/how_to/training_transformer_elmo.md)
but if you're planning to pretrain indonesian, just fine tune the [given pretrained models](https://github.com/HIT-SCIR/ELMoForManyLangs) to your needs.
