### ISSUE TITLE
How to compute a task specific weighting of all biLM layers?

### ISSUE THREAD

**Issue by heslowen** [allenai/allennlp#2762]
**System (please complete the following information):**
 - OS: [ubuntu16.04]
 - Python version: [ 3.6.8]
 - AllenNLP version: [ v0.8.3]
 - PyTorch version: (1.0.1)

**Question**
* How to compute a task-specific weighting of all biLM layers?
![image](https://user-images.githubusercontent.com/22348625/56792251-c5a82100-683b-11e9-855d-1cacd5a7f54f.png)

So how to compute the s^task? Is it a variable that learned by the task model?
thx a lot~

**Comment by DeNeutoy** [comment]
If you use ELMo within allennlp as described here:

https://github.com/allenai/allennlp/blob/master/tutorials/how_to/elmo.md#using-elmo-with-existing-allennlp-models

This will already happen for you (the elmo parameters will be frozen, but they will be combined using a trained scalar weighting as described in the paper).

Thanks! Let us know if you have any problems.

**Comment by heslowen** [comment]
@DeNeutoy I want to use bert actually. In the paper `To Tune or Not to Tune? Adapting Pretrained Representations to Diverse Tasks`, they extract contextual representations of the words from all layers and during adaptation, and they learn a linear weighted combination of the layers **like ELMo do**. So I want to know that is the linear combination a variable that learned by the task model?
