### ISSUE TITLE
How to add a GPU in using ELMo as a PyTorch Module to train a new model?

### ISSUE THREAD

**Issue by xiaoxiaoAurora** [allenai/allennlp#2769]
Please first search our GitHub repository for similar questions.  If you don't find a similar example you can use the following template:

**System (please complete the following information):**
 - OS: Linux
 - Python version: [e.g. 3.7.3]
 - AllenNLP version: I installed from master
 - PyTorch version: 1.0.0

**Question**
* How to add a GPU in using ELMo as a PyTorch Module to train a new model?  

`elmo = Elmo(options_file, weight_file, 2, dropout=0)  
sentences = [["First", "sentence", "."], ["Another", "."]]  
character_ids = batch_to_ids(sentences)  
embeddings = elmo(character_ids)  
elmo_embedding = embeddings ["elmo_representations"][0]`

**Comment by joelgrus** [comment]
when you use `Elmo` this way it's just a PyTorch `Module`, so you can just do 

`elmo.cuda()`

to move it to the GPU

and then you similarly need to make sure that your `character_ids` tensor is also on the GPU

**Comment by xiaoxiaoAurora** [comment]
> when you use `Elmo` this way it's just a PyTorch `Module`, so you can just do
> 
> `elmo.cuda()`
> 
> to move it to the GPU
> 
> and then you similarly need to make sure that your `character_ids` tensor is also on the GPU



> when you use `Elmo` this way it's just a PyTorch `Module`, so you can just do
> 
> `elmo.cuda()`
> 
> to move it to the GPU
> 
> and then you similarly need to make sure that your `character_ids` tensor is also on the GPU

`
elmo = Elmo(options_file, weight_file, 2, dropout=0)
elmo = elmo.cuda()
sentences = [["First", "sentence", "."], ["Another", "."]]
character_ids = batch_to_ids(sentences) 
embeddings = elmo(character_ids.cuda()) 
elmo_embedding = embeddings ["elmo_representations"][0]
`
I tried as above, but there was a bug:

Traceback (most recent call last):
  File "run.py", line 40, in <module>
    args.func(args)
  File "/home/biaffineparser_elmo/parser/cmds/train.py", line 110, in __call__
  File "/home/biaffineparser_elmo/parser/model.py", line 36, in __call__
    self.train(train_loader, train_sentences)
  File "/home/biaffineparser_elmo/parser/model.py", line 80, in train
    loss.backward()
  File "/home/anaconda3/lib/python3.7/site-packages/torch/tensor.py", line 102, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/anaconda3/lib/python3.7/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: merge_sort: failed to synchronize: an illegal memory access was encountered
