### ISSUE TITLE
Error importing allennlp.commands

### ISSUE THREAD

**Issue by SallyAfua** [allenai/allennlp#2783]
Please first search our GitHub repository for similar questions.  If you don't find a similar example you can use the following template:

**System (please complete the following information):**
 - OS: [e.g. OSX, Linux]
 - Python version: [e.g. 3.6.1]
 - AllenNLP version: [e.g. v0.8.3, or "I installed from master"]
 - PyTorch version: (if you installed it yourself)

**Question**
Ask about something you don't understand, such as:

* How can I retrain my own ELMo language model?

* I'm working on a sentiment classification task and I would like to discard sentences that are longer than 1200 characters (my sentences vary from 400 characters to 1400+).  How can I configure my model to discard long sentences?

**Comment by SallyAfua** [comment]
Hi wonderful people. 
Please I have successfully installed allennlp on my python3.7 but I when I run (from allennlp.commands.elmo import ElmoEmbedder
) I encounter an error (No module named 'allennlp.commands). Please could anyone be of help. Thank you

**Comment by matt-gardner** [comment]
When I run those python commands in my terminal, they work just fine.  This means that something is wrong with your environment, with how you installed allennlp.  This is very difficult for us to debug, but perhaps there was some error when you tried to install allennlp that you didn't notice?

**Comment by SallyAfua** [comment]
Well I am not sure I noticed any error while installing allennlp.

I would install allennlp on another computer and see how it fares.

Thanks Matt

**Comment by schmmd** [comment]
Thanks @SallyAfua.  Please let us know if you have any additional problems.  You can also try running AllenNLP in a Docker container for a reproducible environment--we have instructions in our README.

**Comment by SallyAfua** [comment]
Hello Michael,

Hope my email finds you well.

I tried installing again and I had the following error.

"Could not install packages due to an EnvironmentError: [Errno 13]
Permission denied: '/usr/local/lib/python3.7/site-packages/jmespath'
Consider using the `--user` option or check the permissions."

Please I don't understand the error and I don't know how to fix it.

Thanks for your support.

Kind regards,
Salomey.

**Comment by SallyAfua** [comment]
Hello Michael,

I tried installing one more and this is the error I get (view atached
screenshot)

**Comment by schmmd** [comment]
Hi @SallyAfua -- I didn't receive your screenshot.  I highly recommend using Conda to create a fresh environment and install AllenNLP.  This will help prevent environment-specific issues like the one you are reporting.  We have documentation for installing AllenNLP in our README.

https://github.com/allenai/allennlp#installing-via-pip

**Comment by SallyAfua** [comment]
Hello everyone thank you for your assistance. I was able to succesfully install allennlp. I had to due to use the code sudo python3.7 pip install allennlp.
