### ISSUE TITLE
How to access pre trained ELMo model trained on 5.5B Corpus in Keras framework?

### ISSUE THREAD

**Issue by kalyanks0611** [allenai/allennlp#2785]
**I'm unable to identify ,how to access the ELMo Model trained on Wikipedia+New Corpus(5.5B)**

**I have written this code to use the Elmo model(trained on 1 Billion Word Corpus) for text classification using tensorflow hub and Keras**

```
from keras.layers import Input, Lambda, LSTM , Embedding, concatenate, BatchNormalization, Dense 
from keras.models import Model
import keras.backend as K
import tensorflow as tf
import tensorflow_hub as tf_hub

sess = tf.Session()
K.set_session(sess)

def ELMoEmbedding(x):
    return elmo_model(tf.squeeze(tf.cast(x, tf.string)), signature="default", as_dict=True) ["elmo"]

#elmo vectors
elmo_input_layer = Input(shape=(1, ), dtype=tf.string)

embed_elmo = Lambda(ELMoEmbedding, output_shape=(max_sentence_length,1024,))(elmo_input_layer)

lstm = LSTM(256, dropout=0.2, recurrent_dropout=0.2)(embed_elmo)

output_layer = Dense(4, activation='sigmoid')(lstm)

model = Model(inputs=elmo_input_layer, outputs=output_layer)

model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

print(model.summary())
```

**I saw the below code in the link to access the ELMo model trained on 5.5B Corpus(https://github.com/allenai/allennlp/blob/master/tutorials/how_to/elmo.md)**
```
from allennlp.modules.elmo import Elmo, batch_to_ids

options_file = "https://s3-us-west-2.amazonaws.com/allennlp/models/elmo/2x4096_512_2048cnn_2xhighway/elmo_2x4096_512_2048cnn_2xhighway_options.json"

weight_file = "https://s3-us-west-2.amazonaws.com/allennlp/models/elmo/2x4096_512_2048cnn_2xhighway/elmo_2x4096_512_2048cnn_2xhighway_weights.hdf5"

elmo = Elmo(options_file, weight_file, 2, dropout=0)

# use batch_to_ids to convert sentences to character ids
sentences = [['First', 'sentence', '.'], ['Another', '.']]
character_ids = batch_to_ids(sentences)

embeddings = elmo(character_ids)
```

**However, I'm unable to understand how to use this code in the above Keras text classification model.**

**Comment by joelgrus** [comment]
AllenNLP is a PyTorch library, so you can't use AllenNLP code with Tensorflow / Keras models. You have to use one or the other. (And AllenNLP examples probably won't be helpful with your Keras code, and vice versa.)

**Comment by kalyanks0611** [comment]
Here is the link which has used **ELMo embeddings through allennlp library in keras model**
https://github.com/UKPLab/elmo-bilstm-cnn-crf/blob/master/Keras_ELMo_Tutorial.ipynb

But he has used  allennlp.commands.elmo.ElmoEmbedder class which returns three vectors for each word, each vector corresponding to a layer in the ELMo LSTM output. Learning a weighted average of ELMo vectors isn't possible with this class and is possible with allennlp.modules.elmo.Elmo.  (as per the information given in this link https://github.com/allenai/allennlp/blob/master/tutorials/how_to/elmo.md)

**Comment by joelgrus** [comment]
in the example you gave, allennlp is just being used to dump the (raw) ELMo vectors to numpy, and then they're being fed to a keras model, which is all the learning takes place.

if you want to learn layer weights as part of your model, since your model is in keras, that would have to happen in your keras code. there's no easy way to jointly learn allennlp (i.e. pytorch) weights for part of your model and keras (i.e. tensorflow) weights for a different part of your model.

**Comment by kalyanks0611** [comment]
I got it. Thanks @joelgrus
