### ISSUE TITLE
Problem with Text2sql parser model (with grammar_based_text2sql dataset reader)

### ISSUE THREAD

**Issue by ValentinaPy** [allenai/allennlp#2792]
**Describe the bug**
I have a json config file that runs the text2sql_parser model with the grammar_based_text2sql dataset reader (see config below). It runs fine on CPU, but whenever I am running it on GPU I get the error: 

  File "/anaconda3/envs/myENV/lib/python3.6/site-packages/allennlp/models/semantic_parsing/text2sql_parser.py", line 327, in _create_grammar_state
    if action.rule == "":
AttributeError: 'tuple' object has no attribute 'rule'

What could be the problem? This error only happens on GPU. I couldn't find any example json experiment file for this model, so it could also be that my json file is the problem.

**To Reproduce**
Launch the following json experiment on GPU, using the GeoQuery data from `"Improving Text to SQL Evaluation Methodology" <https://arxiv.org/abs/1806.09029>`:

{
  "dataset_reader": {
    "type": "grammar_based_text2sql",
    "schema_path": "data/geography-schema.csv",
    "token_indexers": {
      "tokens": {
        "type": "single_id" }}
  },
  "train_data_path": "train.json",
  "validation_data_path": "dev.json",
  "model": {
    "type": "text2sql_parser",
    "utterance_embedder": {
      "tokens": {
        "type": "embedding",
        "embedding_dim": 400,
        "trainable": true
      }   },
    "action_embedding_dim": 200,
    "encoder": {
      "type": "lstm",
      "input_size": 400,
      "hidden_size": 800,
      "bidirectional": true,
      "num_layers": 1
    },
    "decoder_beam_search": {
    "beam_size": 10
    },
    "max_decoding_steps": 200,
    "input_attention": {"type": "dot_product"},
    "dropout": 0.5
  },
  "iterator": {
    "type": "basic",
    "batch_size" : 32
  },
  "trainer": {
    "num_epochs": 90,
    "patience": 3,
    "cuda_device": 1,
    "validation_metric": "+exact_match",
    "optimizer": {
      "type": "adam",
      "lr": 0.001
    }  } }

**Expected behavior**
The model trains on GPU.

**System (please complete the following information):**
 - OS: Linux
 - Python version: 3.6.1
 - AllenNLP version:  v0.8.3 (not completely sure, could also be v0.8.2)

**Comment by joelgrus** [comment]
@DeNeutoy any ideas?

**Comment by DeNeutoy** [comment]
https://github.com/allenai/allennlp/commit/360c3e10d40a1e9e64085be571eeed4725c53095#diff-25fbc5b96eaa1ec951718b877078673b

I introduced some NamedTuple object in this commit, which is only in the 0.8.3 release, so I think you probably need to upgrade.

**Comment by ValentinaPy** [comment]
Thank you for your help! I upgraded to 0.8.3 and tried to run it again, but the problem persists. The error is also not caught by the tests as they use CPU. Would you mind trying on GPU and see if you have the same error?

**Comment by matt-gardner** [comment]
@benbogin, you've used this code (or similar code) on a GPU - do you have any insights about what might be going on here?

**Comment by DeNeutoy** [comment]
Please could you check your environment upgraded allennlp? The reason I ask this is because with 0.8.3 the stack trace should not have been identical, because the code shifted to line 325, rather than 327. https://github.com/allenai/allennlp/blob/v0.8.3/allennlp/models/semantic_parsing/text2sql_parser.py#L325

This error is not related to whether or not you are using a GPU. Additionally, can you help us to help you by posting full stack traces. It makes debugging a lot easier.

**Comment by ValentinaPy** [comment]
I checked with 'allennlp --version' and it says 0.8.3.
Yes, you are right, for version 0.8.3 the error shifts to line 325.
I thought it might be related to GPU since the code runs without error on CPU, but it could also be related to something else.

The full stack trace with the 0.8.3 version is:
  File "anaconda3/envs/my_env/bin/allennlp", line 10, in <module>
    sys.exit(run())
  File "anaconda3/envs/my_env/lib/python3.6/site-packages/allennlp/run.py", line 18, in run
    main(prog="allennlp")
  File "anaconda3/envs/my_env/lib/python3.6/site-packages/allennlp/commands/__init__.py", line 101, in main
    args.func(args)
  File "anaconda3/envs/my_env/lib/python3.6/site-packages/allennlp/commands/train.py", line 103, in train_model_from_args
    args.force)
  File "anaconda3/envs/my_env/lib/python3.6/site-packages/allennlp/commands/train.py", line 136, in train_model_from_file
    return train_model(params, serialization_dir, file_friendly_logging, recover, force)
  File "anaconda3/envs/my_env/lib/python3.6/site-packages/allennlp/commands/train.py", line 204, in train_model
    metrics = trainer.train()
  File "anaconda3/envs/my_env/lib/python3.6/site-packages/allennlp/training/trainer.py", line 480, in train
    train_metrics = self._train_epoch(epoch)
  File "anaconda3/envs/my_env/lib/python3.6/site-packages/allennlp/training/trainer.py", line 322, in _train_epoch
    loss = self.batch_loss(batch_group, for_training=True)
  File "anaconda3/envs/my_env/lib/python3.6/site-packages/allennlp/training/trainer.py", line 263, in batch_loss
    output_dict = self.model(**batch)
  File "anaconda3/envs/my_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "anaconda3/envs/my_env/lib/python3.6/site-packages/allennlp/models/semantic_parsing/text2sql_parser.py", line 137, in forward
    initial_state = self._get_initial_state(encoder_outputs, mask, valid_actions)
  File "anaconda3/envs/my_env/lib/python3.6/site-packages/allennlp/models/semantic_parsing/text2sql_parser.py", line 240, in _get_initial_state
    initial_grammar_state = [self._create_grammar_state(actions[i]) for i in range(batch_size)]
  File "anaconda3/envs/my_env/lib/python3.6/site-packages/allennlp/models/semantic_parsing/text2sql_parser.py", line 240, in <listcomp>
    initial_grammar_state = [self._create_grammar_state(actions[i]) for i in range(batch_size)]
  File "anaconda3/envs/my_env/lib/python3.6/site-packages/allennlp/models/semantic_parsing/text2sql_parser.py", line 325, in _create_grammar_state
    if action.rule == "":
AttributeError: 'tuple' object has no attribute 'rule'

**Comment by benbogin** [comment]
Didn't see such a problem on cpu or gpu (using 0.8.2), but wasn't using this same parser. Do you get this error right from the beginning of the training or after a few steps?

**Comment by matt-gardner** [comment]
So, it looks like something must be up with converting the list of actions into tensors in the GPU code (perhaps a problem introduced when we tried to get multi-gpu stuff working for `ProductionRuleField`).  @ValentinaPy, can you print out the `valid_actions` variable right at the beginning of `forward` for both the CPU and GPU case, and paste them in here?  You don't need to show the entire thing, something like `print(valid_actions[0][:5])` should do.

**Comment by matt-gardner** [comment]
Actually, yeah, I'm pretty sure the problem is here: https://github.com/allenai/allennlp/blob/a701a0ae62b967ea4297f920bd4bf14fcf13b422/allennlp/nn/util.py#L48-L49.  We should have a case in there that looks like this:

```python
elif isinstance(obj, NamedTuple):
    return obj.__class__(*[move_to_device(item, cuda_device) for item in obj])
```

@ValentinaPy, can you try this and see if it fixes your issue?

**Comment by matt-gardner** [comment]
Also, just FYI, the reason I was able to diagnose the problem this time and not originally was because you gave a full stack trace - it really is very important when asking for help to give full stack traces.

**Comment by ValentinaPy** [comment]
Thank you, adding the NamedTuple case in the util.py file fixed the problem for me! I will make sure to include the full stack traces next time I open an issue.

**Comment by matt-gardner** [comment]
Great, thanks - care to submit a PR with the fix?  I'm reopening this because we still need to fix the bug in the library.

**Comment by ValentinaPy** [comment]
Sure, writing the PR now!
