### ISSUE TITLE
indentation of Line210~213 in drop_eval.py is incorrect

### ISSUE THREAD

**Issue by shiningboy123** [allenai/allennlp#2795]
It seems to only append the em/f1 of the last question of every passage to instance_exact_match/instance_f1 and then compute the average as the final metrics.
https://github.com/allenai/allennlp/blob/master/allennlp/tools/drop_eval.py#L210

**Comment by joelgrus** [comment]
good catch, PR welcome

**Comment by matt-gardner** [comment]
@dDua, @gabrielStanovsky, does this affect our leaderboard results?
