### ISSUE TITLE
Experiment file for training NAQANET 

### ISSUE THREAD

**Issue by shmsw25** [allenai/allennlp#2798]
- OS: Linux Ubuntu
 - Python version: 3.6.3
 - AllenNLP version: v0.8.3

Hello! I am trying to train NAQANET on DROP, and I was wondering if there is an experiment.json file with the hyperparameters used for the number reported in the paper.

I had trouble reproducing the number with [this file](https://github.com/allenai/allennlp/blob/master/allennlp/tests/fixtures/naqanet/experiment.json), where the changes I made were (i) `train_data_path` and `validation_data_path` to be local train & valid data of DROP downloaded from DROP website, and (ii) in trainer, `num_epochs` to be 30 and `cuda_device` to be 0.

Thanks!

**Comment by matt-gardner** [comment]
So, you can grab the config from the pretrained model here: https://github.com/allenai/allennlp/blob/a701a0ae62b967ea4297f920bd4bf14fcf13b422/allennlp/pretrained.py#L43

This _should_ be the same as what's in the file that you linked; if it's not, let us know.  But inside the model is the exact configuration that we used to train it, so if doesn't reproduce, I'm not sure what to tell you.

**Comment by shmsw25** [comment]
Hi Matt,

Thanks for the pointer to the pretrained model. It turns out that `experiment.json` in github repo and `config.json` in the pretrained model have some differences, and with `config.json`, I could reproduce the number in the paper well.

Again, thanks very much for releasing the code and the pretrained model. :)

**Comment by matt-gardner** [comment]
Do you mind posting the differences here, or submitting a PR to fix them?  I'm reopening this issue, so that we get the correct training config checked in to the repo.

**Comment by shmsw25** [comment]
Sure! Just created PR #2800 with the updated `experiment.json`
