### ISSUE TITLE
Multiple train/test data files

### ISSUE THREAD

**Issue by shubhamagarwal92** [allenai/allennlp#2804]
**Question**

I have different source and target files separately for all the train/dev/test. Is it necessary to convert them into one single tab separated file (or a JSON) to provide data paths (`train_data_path`)? How does it scale when we have multiple input sources (KB information) to produce a target? Would we have to pre-process them before hand? Can we somehow provide them in the config (like `source_train_path`, `target_train_path`, `kb1_train_path`, `kb2_train_path`) and deal with it in `dataset_reader`? Also if we want to create different vocab for target and input (source + kb)?

Another example, consider the case in a dialog, when we have multiple knowledge base information (or say images) corresponding to each dialog.

**Comment by brendan-ai2** [comment]
We don't have a built-in way to handle this at the moment. Fortunately, the `file_path` passed to `DatasetReader.read` can be an arbitrary string and things should mostly continue to work. This gives a few options (roughly in order of preference):

1. Pre-processing, as you state. This may be the simplest and most efficient choice.
2. Set `train_data_path` to a JSON-serialized dictionary of the constituents of your dataset. Deserialize this and combine the constituents in your reader.
3. Bake the collections of various train/dev/test splits into the config for your reader. Label them with some key and use `file_path` as a key to look them up later. You'd need to override your config when using the model elsewhere, however, which would be a pain.
4. Use a custom trainer. We've experimented with this a bit in https://github.com/allenai/allennlp/blob/master/allennlp/tests/training/multi_task_trainer_test.py. This would definitely be the most work.

I hope that helps!

**Comment by joelgrus** [comment]
one other simple option is to have `file_path` be a directory and to have the dataset reader look for specific files (or all files matching a regex) in that directory.

if you want to use different vocabularies for different text fields, you'll need to use different `TokenIndexer`s for them and give those token indexers different namespaces

**Comment by shubhamagarwal92** [comment]
Thanks for the detailed answer. Closing this now.

**Comment by asvskartheek** [comment]
> 4. Use a custom trainer. We've experimented with this a bit in https://github.com/allenai/allennlp/blob/master/allennlp/tests/training/multi_task_trainer_test.py. This would definitely be the most work.

This is a broken link, is there any working way to pass 2 files at once in read method?
