### ISSUE TITLE
Rouge metric for text summary.

### ISSUE THREAD

**Issue by MLjian** [allenai/allennlp#2809]
Hello, would you attend to add the Rouge metric?

**Comment by brendan-ai2** [comment]
We're not planning on doing this, but we'd be open to looking at a contribution. Thanks!

**Comment by abhigenie92** [comment]
Can you provide more details on this issue. I am interested in working on this. 
Thanks!

**Comment by dirkgr** [comment]
This issue is old. AllenNLP now has a Rouge metric.
