### ISSUE TITLE
Kernel keeps dying when using pretrained model in jupyter notebook

### ISSUE THREAD

**Issue by peixin-lin** [allenai/allennlp#2810]
I tried to run the code given in the readme, which worked well in the IDE, but kept causing the kernel dies when run in Jupyter Notebook.

<img width="869" alt="Screen Shot 2019-05-08 at 12 21 23 AM" src="https://user-images.githubusercontent.com/34934236/57307071-3fd38200-7127-11e9-87f9-15489772e9e3.png">

A screenshot of the error:
<img width="698" alt="Screen Shot 2019-05-08 at 12 16 08 AM" src="https://user-images.githubusercontent.com/34934236/57306673-968c8c00-7126-11e9-8d32-0b2a0764027e.png">

**Comment by brendan-ai2** [comment]
Unfortunately this isn't enough information to go on. I don't typically use notebooks, but I imagine Jupyter provides some error logs. Could you please provide those?

**Comment by peixin-lin** [comment]
Sorry for the insufficient information. 
I have got some logs from the notebook as below.
<img width="1440" alt="Screen Shot 2019-05-08 at 3 26 14 PM" src="https://user-images.githubusercontent.com/34934236/57351642-068e2700-71a6-11e9-8903-4ec5929538a5.png">

Besides, I found an similar issue caused by verision of Pytorch [https://github.com/jupyter/notebook/issues/1892](url)
I am not sure if it is the same issue, but I upgraded the pytorch version as they suggested and it didn't work.

More information is as follow:
**OS: macos 
Python version: 3.7.1
Pip list:**
absl-py                            0.7.1      
alabaster                          0.7.12     
allennlp                           0.8.3      
anaconda-client                    1.7.2      
anaconda-navigator                 1.9.6      
anaconda-project                   0.8.2      
appnope                            0.1.0      
appscript                          1.0.1      
asn1crypto                         0.24.0     
astor                              0.7.1      
astroid                            2.1.0      
astropy                            3.1        
atomicwrites                       1.2.1      
attrs                              18.2.0     
aws-sam-translator                 1.11.0     
aws-xray-sdk                       2.4.2      
awscli                             1.16.153   
Babel                              2.6.0      
backcall                           0.1.0      
backports.os                       0.1.1      
backports.shutil-get-terminal-size 1.0.0      
beautifulsoup4                     4.6.3      
bitarray                           0.8.3      
bkcharts                           0.2        
blaze                              0.11.3     
bleach                             3.0.2      
bloom-filter                       1.3        
bokeh                              1.0.2      
boto                               2.49.0     
boto3                              1.9.143    
botocore                           1.12.143   
Bottleneck                         1.2.1      
certifi                            2018.11.29 
cffi                               1.11.5     
cfn-lint                           0.19.1     
chardet                            3.0.4      
Click                              7.0        
cloudpickle                        0.6.1      
clyent                             1.2.2      
colorama                           0.3.9      
conda                              4.6.14     
conda-build                        3.17.6     
conda-verify                       3.1.1      
conllu                             0.11       
contextlib2                        0.5.5      
cryptography                       2.4.2      
cycler                             0.10.0     
cymem                              1.31.2     
Cython                             0.29.2     
cytoolz                            0.9.0.1    
dask                               1.0.0      
datashape                          0.5.4      
decorator                          4.3.0      
defusedxml                         0.5.0      
dill                               0.2.9      
distributed                        1.25.1     
docker                             3.7.2      
docker-pycreds                     0.4.0      
docutils                           0.14       
ecdsa                              0.13.2     
editdistance                       0.5.3      
en-core-web-sm                     2.0.0      
entrypoints                        0.2.3      
et-xmlfile                         1.0.1      
fastcache                          1.0.2      
filelock                           3.0.10     
flaky                              3.5.3      
Flask                              1.0.2      
Flask-Cors                         3.0.7      
ftfy                               5.5.1      
future                             0.17.1     
gast                               0.2.2      
gevent                             1.3.7      
glob2                              0.6        
gmpy2                              2.0.8      
greenlet                           0.4.15     
grpcio                             1.19.0     
h5py                               2.8.0      
heapdict                           1.0.0      
html5lib                           1.0.1      
idna                               2.8        
imageio                            2.4.1      
imagesize                          1.1.0      
importlib-metadata                 0.6        
ipykernel                          5.1.0      
ipython                            7.2.0      
ipython-genutils                   0.2.0      
ipywidgets                         7.4.2      
isort                              4.3.4      
itsdangerous                       1.1.0      
jdcal                              1.4        
jedi                               0.13.2     
Jinja2                             2.10       
jmespath                           0.9.4      
jsondiff                           1.1.2      
jsonnet                            0.12.1     
jsonpatch                          1.23       
jsonpickle                         1.1        
jsonpointer                        2.0        
jsonschema                         2.6.0      
jupyter                            1.0.0      
jupyter-client                     5.2.4      
jupyter-console                    6.0.0      
jupyter-core                       4.4.0      
jupyterlab                         0.35.3     
jupyterlab-server                  0.2.0      
Keras                              2.2.4      
Keras-Applications                 1.0.7      
Keras-Preprocessing                1.0.9      
keyring                            17.0.0     
kiwisolver                         1.0.1      
lazy-object-proxy                  1.3.1      
libarchive-c                       2.8        
lief                               0.9.0      
llvmlite                           0.26.0     
locket                             0.2.0      
lupyne                             2.2        
lxml                               4.2.5      
Markdown                           3.1        
MarkupSafe                         1.1.0      
matplotlib                         3.0.2      
mccabe                             0.6.1      
mistune                            0.8.4      
mkl-fft                            1.0.6      
mkl-random                         1.0.2      
mock                               2.0.0      
more-itertools                     4.3.0      
moto                               1.3.8      
mpmath                             1.1.0      
msgpack                            0.5.6      
msgpack-numpy                      0.4.4.2    
multipledispatch                   0.6.0      
murmurhash                         0.28.0     
navigator-updater                  0.2.1      
nbconvert                          5.4.0      
nbformat                           4.4.0      
networkx                           2.2        
nltk                               3.4        
nose                               1.3.7      
notebook                           5.7.4      
numba                              0.41.0     
numexpr                            2.6.8      
numpy                              1.15.4     
numpydoc                           0.8.0      
odo                                0.5.1      
olefile                            0.46       
openpyxl                           2.5.12     
overrides                          1.9        
packaging                          18.0       
pandas                             0.23.4     
pandocfilters                      1.4.2      
parsimonious                       0.8.1      
parso                              0.3.1      
partd                              0.3.9      
path.py                            11.5.0     
pathlib2                           2.3.3      
patsy                              0.5.1      
pbr                                5.1.3      
pep8                               1.7.1      
pexpect                            4.6.0      
pickleshare                        0.7.5      
Pillow                             5.3.0      
pip                                18.1       
pkginfo                            1.4.2      
plac                               0.9.6      
pluggy                             0.8.0      
ply                                3.11       
preshed                            1.0.1      
prometheus-client                  0.5.0      
prompt-toolkit                     2.0.7      
protobuf                           3.7.1      
psutil                             5.4.8      
ptyprocess                         0.6.0      
py                                 1.7.0      
pyasn1                             0.4.5      
pycodestyle                        2.4.0      
pycosat                            0.6.3      
pycparser                          2.19       
pycrypto                           2.6.1      
pycurl                             7.43.0.2   
pyflakes                           2.0.0      
Pygments                           2.3.1      
pylint                             2.2.2      
pyodbc                             4.0.25     
pyOpenSSL                          18.0.0     
pyparsing                          2.3.0      
PySocks                            1.6.8      
pytest                             4.0.2      
pytest-arraydiff                   0.3        
pytest-astropy                     0.5.0      
pytest-doctestplus                 0.2.0      
pytest-openfiles                   0.3.1      
pytest-remotedata                  0.3.1      
python-dateutil                    2.7.5      
python-jose                        3.0.1      
pytorch-pretrained-bert            0.6.2      
pytz                               2018.7     
PyWavelets                         1.0.1      
PyYAML                             3.13       
pyzmq                              17.1.2     
QtAwesome                          0.5.3      
qtconsole                          4.4.3      
QtPy                               1.5.2      
regex                              2017.4.5   
requests                           2.21.0     
responses                          0.10.6     
rope                               0.11.0     
rsa                                3.4.2      
ruamel-yaml                        0.15.46    
s3transfer                         0.2.0      
scikit-image                       0.14.1     
scikit-learn                       0.20.1     
scipy                              1.1.0      
seaborn                            0.9.0      
Send2Trash                         1.5.0      
setuptools                         40.6.3     
simplegeneric                      0.8.1      
singledispatch                     3.4.0.3    
six                                1.12.0     
snowballstemmer                    1.2.1      
sortedcollections                  1.0.1      
sortedcontainers                   2.1.0      
spacy                              2.0.12     
Sphinx                             1.8.2      
sphinxcontrib-websupport           1.1.0      
spyder                             3.3.2      
spyder-kernels                     0.3.0      
SQLAlchemy                         1.2.15     
sqlparse                           0.3.0      
statsmodels                        0.9.0      
sympy                              1.3        
tables                             3.4.4      
tblib                              1.3.2      
tensorboard                        1.13.1     
tensorboardX                       1.6        
tensorflow                         1.13.1     
tensorflow-estimator               1.13.0     
termcolor                          1.1.0      
terminado                          0.8.1      
testpath                           0.4.2      
thinc                              6.10.3     
toolz                              0.9.0      
torch                              1.1.0      
torchvision                        0.2.2.post3
tornado                            5.1.1      
tqdm                               4.28.1     
traitlets                          4.3.2      
ujson                              1.35       
unicodecsv                         0.14.1     
Unidecode                          1.0.23     
urllib3                            1.24.1     
wcwidth                            0.1.7      
webencodings                       0.5.1      
websocket-client                   0.56.0     
Werkzeug                           0.14.1     
wheel                              0.32.3     
widgetsnbextension                 3.4.2      
word2number                        1.1        
wrapt                              1.10.11    
wurlitzer                          1.0.2      
xlrd                               1.2.0      
XlsxWriter                         1.1.2      
xlwings                            0.15.1     
xlwt                               1.3.0      
xmltodict                          0.12.0     
zict                               0.1.3

**Comment by brendan-ai2** [comment]
Hmm, so this is a bit unclear. It's possible that one of our dependencies uses OpenMP and that Jupyter links in a second copy that conflicts. Unfortunately it's not obvious which dependency that is. If you can track that down, we certainly be open to trying a different version of the relevant dependency.

**Comment by brendan-ai2** [comment]
Actually, as you suggested, Pytorch is definitely one of the libraries that uses OpenMP. Sorry for missing that earlier. To find the other you could do something like iterate over the various python libraries, start a new process, import one python library, and then dump the shared libraries that it loads. See for instance https://stackoverflow.com/a/47346043.

**Comment by schmmd** [comment]
We can't do much, so we're closing this for now.  Please reach back out if you have more questions / issues we can help with.
