### ISSUE TITLE
Pretrained parameter for Transformer-based ELMo?

### ISSUE THREAD

**Issue by Megavoxel01** [allenai/allennlp#2812]
Hi!
It looks like to use the transformer version of ELMo(https://github.com/allenai/allennlp/blob/master/tutorials/how_to/training_transformer_elmo.md) we have to do the training from scratch, which is kinda cumbersome for people with limited time and computing resources. I'm wondering if it's possible for you guys to provide the pre-trained model parameter?  

Thank you in advance.

**Comment by brendan-ai2** [comment]
We actually have such a model, but I'm afraid I didn't update the tutorial on account of it being focused on the model's training. That was a bit short-sighted! I'll be sure to update the page.

In the meantime, feel free to download https://s3-us-west-2.amazonaws.com/allennlp/models/transformer-elmo-2019.01.10.tar.gz.

**Comment by Megavoxel01** [comment]
Many thanks Brendan!
