### ISSUE TITLE
QuoraParaphraseDatasetReader.read() fails on Windows

### ISSUE THREAD

**Issue by chen-zarfati** [allenai/allennlp#2816]
The following few lines of code reproduce the bug on Win10, python 3.7.3, allennlp 0.8.3
Seems like encoding bug.

from allennlp.data.dataset_readers import QuoraParaphraseDatasetReader
from allennlp.data.token_indexers.wordpiece_indexer import PretrainedBertIndexer
from allennlp.data.tokenizers.word_splitter import BertBasicWordSplitter

bert_indexer = PretrainedBertIndexer('bert-large-cased', do_lowercase=False)
bert_tokenizer = BertBasicWordSplitter(do_lower_case=False)
quora_reader = QuoraParaphraseDatasetReader(tokenizer=bert_tokenizer, token_indexers={'tokens': bert_indexer})
train_dataset = quora_reader.read(os.path.join(data_dir, 'quora_duplicate_questions.tsv'))

---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-6-887eadc286bc> in <module>
----> 1 train_dataset = quora_reader.read(os.path.join(data_dir, 'quora_duplicate_questions.tsv'))

~\work\toolkit\conda\envs\py37_test\lib\site-packages\allennlp\data\dataset_readers\dataset_reader.py in read(self, file_path)
     71             instances = self._read(file_path)
     72             if not isinstance(instances, list):
---> 73                 instances = [instance for instance in Tqdm.tqdm(instances)]
     74             if not instances:
     75                 raise ConfigurationError("No instances were read from the given filepath {}. "

~\work\toolkit\conda\envs\py37_test\lib\site-packages\allennlp\data\dataset_readers\dataset_reader.py in <listcomp>(.0)
     71             instances = self._read(file_path)
     72             if not isinstance(instances, list):
---> 73                 instances = [instance for instance in Tqdm.tqdm(instances)]
     74             if not instances:
     75                 raise ConfigurationError("No instances were read from the given filepath {}. "

~\work\toolkit\conda\envs\py37_test\lib\site-packages\tqdm\_tqdm.py in __iter__(self)
   1020                 """), fp_write=getattr(self.fp, 'write', sys.stderr.write))
   1021 
-> 1022             for obj in iterable:
   1023                 yield obj
   1024                 # Update and possibly print the progressbar.

~\work\toolkit\conda\envs\py37_test\lib\site-packages\allennlp\data\dataset_readers\quora_paraphrase.py in _read(self, file_path)
     53         with open(cached_path(file_path), "r") as data_file:
     54             tsv_in = csv.reader(data_file, delimiter='\t')
---> 55             for row in tsv_in:
     56                 if len(row) == 4:
     57                     yield self.text_to_instance(premise=row[1], hypothesis=row[2], label=row[0])

~\work\toolkit\conda\envs\py37_test\lib\encodings\cp1252.py in decode(self, input, final)
     21 class IncrementalDecoder(codecs.IncrementalDecoder):
     22     def decode(self, input, final=False):
---> 23         return codecs.charmap_decode(input,self.errors,decoding_table)[0]
     24 
     25 class StreamWriter(Codec,codecs.StreamWriter):

UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 1125: character maps to <undefined>

**Comment by brendan-ai2** [comment]
Hi @chen-zarfati, unfortunately we don't support Windows. We're a pretty small team, so we've had to focus on Linux and Mac OS X. If you have a modestly sized bugfix PR, we'll be happy to review, but we won't be able to prevent regressions. Of course, if you can reproduce this bug on Linux/Mac OS X, please let me know and we'll investigate further! Sorry I couldn't be of more help.

**Comment by chen-zarfati** [comment]
Hi @brendan-ai2, thank you for your quick response, I'll submit a PR then :)
