### ISSUE TITLE
replace path-style s3 links with virtual-host-style s3 links

### ISSUE THREAD

**Issue by joelgrus** [allenai/allennlp#2819]
see 

https://aws.amazon.com/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story/

**Comment by matt-gardner** [comment]
Definitely in favor of this; I didn't realize we could use those other links.  They're a lot easier to remember.

**Comment by epwalsh** [comment]
FWIW we could also use the `s3://` syntax instead as long as it goes through the `cached_path` function (that would be even easier to remember). For example, "https://s3-us-west-2.amazonaws.com/allennlp/datasets/squad/squad-train-v1.1.json" would be "s3://allennlp/datasets/squad/squad-train-v1.1.json".

**Comment by pidugusundeep** [comment]
Added a PR #2873 @joelgrus @matt-gardner

**Comment by epwalsh** [comment]
^ replying to myself: this is a bad idea, at least until https://github.com/allenai/allennlp/issues/2929 is addressed

**Comment by DeNeutoy** [comment]
Fixed by #2939 and #2873
