### ISSUE TITLE
Avoid divide by zero in Boolean Accuracy

### ISSUE THREAD

**Issue by Eric-Wallace** [allenai/allennlp#2822]
**Describe the bug**
When you use a boolean accuracy metric. If you call reset but have not run the model yet, there is a float division by 0 error here https://github.com/allenai/allennlp/blob/master/allennlp/training/metrics/boolean_accuracy.py#L78. 
Similar issues have been fixed in past PR's, e.g., here https://github.com/allenai/allennlp/commit/59132d2be0e871b512c03a08fe80eb41ef7418a9

**Expected behavior**
If you call reset() it should do nothing if the metrics are still 0.

**Comment by brendan-ai2** [comment]
@Eric-Wallace, would you mind submitting a quick PR with this fix? Thanks!

**Comment by matt-gardner** [comment]
@Eric-Wallace, ping.  Care to submit a quick PR?
