### ISSUE TITLE
Does allennlp support the bert-crf model?

### ISSUE THREAD

**Issue by aslicedbread** [allenai/allennlp#2825]
I want to make a comparison between bert-crf and bert-bilstm-crf, but I'm confused about how to set parameters. Does allennlp support the bert-crf model? Hope to get your reply, thanks.

**Comment by brendan-ai2** [comment]
@joelgrus, you likely know the most about this. Could you please take a look? Thanks!

**Comment by joelgrus** [comment]
sorry, I'm not familiar with these models, can you link me to them? are they from a paper?

**Comment by aslicedbread** [comment]
> sorry, I'm not familiar with these models, can you link me to them? are they from a paper?

Thanks for your reply.
Sorry, It's not from any paper. I just have this idea and hope to explore. It seems that the BERT Model combined with CRF or BiLSTM-CRF should have better performance than BERT Model(single). Is it possible to modify some files to combine the bert model with the crf_tagger in allennlp so as to use training_config jsonet to vaild the performance of the BERT-CRF or BERT-BiLSTM-CRF Model?

**Comment by joelgrus** [comment]
if you just want to use e.g. BERT vectors in the CRF tagger, you should be able to do something similar to this:

https://github.com/allenai/allennlp/blob/master/allennlp/tests/fixtures/bert/bert_pooler.jsonnet

which is using BERT vectors in the simple classifier. (you would have to change the config to use the crf-tagger with its options and so on)

that file uses the `BertPooler` as the Seq2Vec encoder (which I guess corresponds to your BERT-CRF idea), or you could try using an LSTM or whatever.

**Comment by schmmd** [comment]
Closing, but please ping this thread if you have more questions.
