### ISSUE TITLE
How does the masking work in Seq2SeqEncoder

### ISSUE THREAD

**Issue by JizeCao** [allenai/allennlp#2829]
**System (please complete the following information):**
 - OS: Linux
 - Python version: 3.6.3
 - AllenNLP version: "I installed from master"

**Question**

Suppose that my mask is [1, 1, 1, 0, 1, 1, 1, 0, 0], where there are padded values in the middle of the sequence. I find that I can use this vector as the mask for Seq2SeqEncoder, but does it have the correct result, i.e: ignore the 0 entry's value ?

**Comment by matt-gardner** [comment]
No, that will not have the correct result if you're using a pytorch RNN.  We compute a sequence length from the mask by summing, and assume it's always right-padded.

**Comment by JizeCao** [comment]
Is it true for all modules inherited from Seq2SeqEncoder? Also, do I need to sort the batch so that the longest sequence is the first in the batch?

**Comment by matt-gardner** [comment]
We take care of sorting things for you inside the encoder, so you don't have to think about it.  I'm not sure if any of our encoders would work with masked values in the middle like that...  I doubt it, but there might be a self-attentive one that does the right thing here.

**Comment by JizeCao** [comment]
Yeah. I saw mask is controled by the masked_softmax function. However, I check the output from the stacked_self_attention module and found that the padded position has non-zero output. Is it a usual behavior?

**Comment by matt-gardner** [comment]
The stacked self attention uses the mask when computing attentions: https://github.com/allenai/allennlp/blob/aa1524ee20e6d23a5045da52df6122ee2bbeaf95/allennlp/modules/seq2seq_encoders/stacked_self_attention.py#L157
But the rest of the code has feedforward layers and such that can make a zero output into a non-zero output, through bias parameters.  But, to your original question, this encoder would do the same thing for a masked token in the middle of a sequence as it does for a token at the end.  It should be safe to use this kind of an encoder for your data, while it definitely wouldn't be "correct" to use a pytorch RNN (though it _may_ still work - I would just pass a mask of `None` to the encoder for that case and hope it works anyway).

**Comment by schmmd** [comment]
Closing, but please ping this thread or open a new issue if you have more questions.
