### ISSUE TITLE
Allow overriding weights file while constructing pretrained model using from_params

### ISSUE THREAD

**Issue by vikigenius** [allenai/allennlp#2831]
**Is your feature request related to a problem? Please describe.**
The current way of using _pretrained to load a pretrained model using from_params doesn't offer a way to override weight files. It uses the default weights.th present in the archive.
For eg:

```
"my_specific_component": {
       "type": "my_model_typ"
       "model_component": {
          "_pretrained":  {
              "arvhice_file": "/path/to/model.tar.gz",
              "module_path": "_comp_name"
              "freeze": true,
          }
     }
}
```

**Describe the solution you'd like**
I would like to be able to specify a weights file path that overrides the weights present in the archive.

**Describe alternatives you've considered**
Right now I manually creating another archive by replacing the weights.th file, which is cumbersome if I want to try multiple different weights

**Comment by schmmd** [comment]
@vikigenius you can extract your archive to a folder, edit the weights file, and specify the folder itself rather than creating an archive each time.

Do you want to be able to specify the weights file in the model configuration?

**Comment by vikigenius** [comment]
@schmmd yes, it would be good to have, not priority obviously, because as you said I can simply extract and edit the weights file, but since load_archive function already has a way to specify a weights_file that overrides the archive weights, we can just use that in the from_params ?

**Comment by schmmd** [comment]
Certainly it could be added--but I'm a bit reluctant to as any addition adds some complexity and I don't see the benefits being too great here.
