### ISSUE TITLE
Is there an existing way to do sequence of sequence encoding?  

### ISSUE THREAD

**Issue by faizan30** [allenai/allennlp#2838]
**Question**: I am working on page classification task. In my dataset reader each page is an Instance, the tokens field is a Sequence of Sequence i.e. ListField(TextField, TextField, TextField,,,,). Is there an existing way to do sequence of sequence encoding?

**Comment by schmmd** [comment]
Duplicate of https://github.com/allenai/allennlp/issues/2839
