### ISSUE TITLE
Where to download dataset such as ATIS and WikitableQuestions?

### ISSUE THREAD

**Issue by leelaylay** [allenai/allennlp#2845]
**System :**
 - OS: Linux
 - Python version: python 3.6
 - AllenNLP version: I installed from master
 - PyTorch version: 0.4.1

**Question**
* I am new to AllenNLP and think it a great tool.  I find that it difficult for me to use the example config such as ATIS and WikitableQuestions, because I find that the format is not the stand format in the Web. Where can I download this format of ATIS and WikitableQuestions?
* I hope that there will be one document contains the download link of all dataset in the example config.

**Comment by SundeepPidugu** [comment]
[WikitableQuestions](https://ppasupat.github.io/WikiTableQuestions/)

[ATIS](https://www.kaggle.com/siddhadev/ms-cntk-atis)

Will update you when i get a consolidated file that has all the data-set download links

**Comment by schmmd** [comment]
@matt-gardner where should users find the ATIS and Wikitables datasets?

**Comment by matt-gardner** [comment]
For WTQ, the model that is currently checked in to the repo uses the original dataset that should be available where @SundeepPidugu pointed to.  There is a pre-processing script that produces a separate format that's faster to read in, but both should work.  We're checking in a new model soon (probably after the EMNLP deadline; see #2764) that I think uses a slightly different format, but I'm not sure - @pdasigi would know.

For ATIS, @kl2806 is the person who would know where those files are.

But, just FYI, we're all pretty swamped with the EMNLP deadline coming up next week, so sorry if it takes us a bit longer to respond than usual.

**Comment by leelaylay** [comment]
@matt-gardner @schmmd @SundeepPidugu 
Thank you all. I will just try it.

**Comment by kl2806** [comment]
@leelaylay  The ATIS model that is checked in uses the preprocessed data from https://github.com/clic-lab/atis, so follow the instructions there if you would like the preprocessed data. If you would like to do your own preprocessing then the above kaggle link be OK as well.

**Comment by schmmd** [comment]
I think @leelaylay's questions were answered but I self-assigned myself to better organize these datasets for the next person.

**Comment by matt-gardner** [comment]
@schmmd, are you planning on doing anything with this?

**Comment by schmmd** [comment]
@matt-gardner I'm not sure what I intended to do but https://github.com/allenai/allennlp/pull/2947 seems like a reasonable step.
