### ISSUE TITLE
How can I fine tune medium elmo model on a custom dataset

### ISSUE THREAD

**Issue by abaheti95** [allenai/allennlp#2846]
**System (please complete the following information):**
 - OS: [e.g. OSX, Linux]
 - Python version: [e.g. 3.6.1]
 - AllenNLP version: [e.g. v0.8.3, or "I installed from master"]
 - PyTorch version: (if you installed it yourself)

**Question**
I want to retrain medium elmo model on a small custom dataset. I saw someone suggesting to use bilm-tf repository, however I couldn't get the checkpoint files for the medium model(getting access denied on the links). Is there anyway I can do this using allennlp? If yes how? If not can someone give the checkpoint files for the medium model which can be used for bilm-tf?

**Comment by schmmd** [comment]
@abaheti95 can you paste the broken link here so we can investigate?

**Comment by schmmd** [comment]
This may be helpful if you are not too specific about which ELMo model you want to retrain: https://github.com/allenai/allennlp/blob/master/tutorials/how_to/training_transformer_elmo.md

We look forward to hearing back from you!

**Comment by abaheti95** [comment]
Thank you for the response but someone responded with the files on bilm-tf repository [https://github.com/allenai/bilm-tf/issues/198](https://github.com/allenai/bilm-tf/issues/198)
