### ISSUE TITLE
How to encode Sequence of Sequences. (Hierarchical sequence)

### ISSUE THREAD

**Issue by Ansarimi** [allenai/allennlp#2847]
I am building text classification. The below is the sample data set. Each instance contains list of logs and label for it. The record is sequence of logs. And a log is sequence of words. My goal is to embed each log (sequence of words) into 300 dimension vector.  And finally embed full record(sequence of log) into final 300 vector and pass it through feed forward with softmax and classify. Can we do this using pre build models in Allennlp? Can you please provide any examples/config file or pointers to customize the code?

```
<record>
<log><machine details/><long sentence/> </log> 
<log><machine details/><long sentence/> </log>
<log><machine details/><long sentence/> </log>  
</record>       Label A

<record>
<log><machine details/><long sentence/> </log> 
<log><machine details/><long sentence/> </log>
<log><machine details/><long sentence/> </log>
</record>       Label B
```

etc

**Comment by Ansarimi** [comment]
The dataset is somehow not rendered properly. Here is the data set
```
<record>
<log><machine details/> <Long sentence/></log>
<log><machine details/> <Long sentence/></log>
<log><machine details/> <Long sentence/></log>
</record>
Label A


<record>
<log><machine details/> <Long sentence/></log>
<log><machine details/> <Long sentence/></log>
<log><machine details/> <Long sentence/></log>
</record>
Label B
```

etc

**Comment by DeNeutoy** [comment]
Hi! You are looking for a `ListField[TextField]`. This will create a tensor of shape `(batch_size, num_records, num_sentences)` for you to embed as normal.

https://allenai.github.io/allennlp-docs/api/allennlp.data.fields.html#list-field


https://allenai.github.io/allennlp-docs/api/allennlp.data.fields.html#text-field

**Comment by rahular** [comment]
I am trying to do something similar and am not able to figure out how to feed a `ListField[TextField]` into an encoder. I cannot feed it directly as the field is three dimensional and the RNN expects 2D input. I am sure there is a simple trick which I am missing.

**Comment by rahular** [comment]
I found the answer in #2839
