### ISSUE TITLE
Is namespace for 'elmo_characters' indexer used anywhere?

### ISSUE THREAD

**Issue by ynandwan** [allenai/allennlp#2850]
While creating a token_indexer, we can optionally specify 'namespace' and we need to ensure that same namespace is passed to the corresponding 'token_embedder'. However, for 'elmo_token_embedder', I am not able to figure out where to specify the 'namespace' that I used for 'elmo_characters' token indexer?

**Comment by DeNeutoy** [comment]
Hi @ynandwan, this is a bit of an odd one, but essentially, the input to elmo is utf-8 characters. As these already have a mapping to integers (0, 256), we don't need to keep around a `namespace`. I agree this is slightly confusing.

You can see the code here which does this mapping deterministically for any string:

https://github.com/allenai/allennlp/blob/master/allennlp/data/token_indexers/elmo_indexer.py#L26

Re-open if you have any other questions!
