### ISSUE TITLE
DROP multi-spans eval depends on the order of spans in the bag

### ISSUE THREAD

**Issue by andorardo** [allenai/allennlp#2852]
**Describe the bug**
The score between bags of predicted and gold spans varies wildly between 0-1 depending on the order, and lexical order of the bag elements.

I think the behavior is due to the implementation of _align_bags:
https://github.com/allenai/allennlp/blob/7bdd575c64359a7e18b20caa7930a0f00f5e406c/allennlp/tools/drop_eval.py#L73

**To Reproduce**
In the spirit of test_multi_span_overlap_in_incorrect_cases, the following metrics can be run:
```
>>> get_metrics(["a"], ["a", "b"])
(0, 0.5)
>>> get_metrics(["b"], ["a", "b"])
(0, 0.0)
>>> get_metrics(["b"], ["b", "a"])
(0, 1.0)
```

**Expected behavior**
I would expect F1 to be 0.5 in all cases. But at a minimum, I would expect the first and third examples to give the same result.

**System (please complete the following information):**
 - OS: Linux
 - Python version: Python 3.6.5
 - AllenNLP version: pulled yesterday
 - PyTorch version: n/a

**Comment by matt-gardner** [comment]
Wow, yeah, that's obviously a problem. Thanks for finding this. We tried to come up with good test cases for the metric; clearly we missed something.  @dDua, can you look into fixing this?
