### ISSUE TITLE
Demo results for SRL different using python api

### ISSUE THREAD

**Issue by omerarshad** [allenai/allennlp#2855]
**online results** : apply: [ARG0: A relevant person] [ARGM-MOD: must] [ARGM-ADV: also] [V: apply] [ARG1: customer due diligence measures] [ARGM-TMP: at other appropriate times] [ARG2: to existing customers] [C-ARG1: on a risk based approach]

Python api : [ARG0: A relevant person] [ARGM-MOD: must] [ARGM-ADV: also] [V: apply] [ARG1: customer due diligence measures] [ARGM-TMP: at other appropriate times] [ARG2: to existing customers] [ARGM-ADV: on] [ARGM-CAU: a risk based approach] ;

Why are results different?  C-ARG1 on demo becomes ARGM-CAU using python api

**Comment by schmmd** [comment]
@omerarshad the SRL model in the demo (https://s3-us-west-2.amazonaws.com/allennlp/models/srl-model-2018.05.25.tar.gz) uses ELMo, which has state that depends on input sentences since it was initialized.  You should get more similar results if you warm up the SRL model you are using via the Python API before feeding it the examples you care about.

**Comment by omerarshad** [comment]
I am loading the same model used in demo same you mentioned... but it gives different result on online demo and different when loaded from python ..

**Comment by schmmd** [comment]
@omerarshad -- the difference is that the demo model is warmed up.  It's a long-living model, whereas when you run from the command line you instantiate a fresh model that hasn't been warmed up yet.  See https://github.com/allenai/allennlp/issues/2221 for a related issue.

**Comment by omerarshad** [comment]
so how to obtain same results? how can we warm up the model?

**Comment by schmmd** [comment]
To warm up the model, when you create a new model first run it on some different predictions.  The demo doesn't do anything in particular to warm up the model, but since it's a long living process it's warmed up by our users over time.

There is no way to guarantee the same results.

**Comment by ksatvat** [comment]
I ran into the same issue and seems the public model (API) makes some basic mistakes which the website does not! Does anyone have any link to follow and warmup the model? I am not familiar with the best warm-up strategies that can be used here. Is there anything that you can share, how many epochs, the learning rate and ...?
