### ISSUE TITLE
Multi Labels prediction using Allennlp

### ISSUE THREAD

**Issue by KalidindiMounika** [allenai/allennlp#2856]
Hi,
We have a use case where we need to predict the label as well as the classes within the label. It is like predicting two columns (multi label target prediction). I am not sure whether I can use the existing library example for my requirement.
Please suggest me whether it's possible using allennlp.
Thanks in Advance

**Comment by schmmd** [comment]
Yes this is possible.  See https://allenai.github.io/allennlp-docs/api/allennlp.data.fields.html#allennlp.data.fields.multilabel_field.MultiLabelField for more details.
