### ISSUE TITLE
TimeDistributed-wrapped Linear layer

### ISSUE THREAD

**Issue by mahnerak** [allenai/allennlp#2861]
As far as I understand, the implementation of Linear layer in torch supports multi-dimensional tensors as inputs. It is even stated in the docstring.
I always thought that Linear Layer does not need to be wrapped by TimeDistributed in AllenNLP (in Keras as well), but noticed some lines:
https://github.com/allenai/allennlp/blob/57956e789b8568bbb618436d2d52f9bbfac65a36/allennlp/models/simple_tagger.py#L71 https://github.com/allenai/allennlp/blob/b6693107633feb261ed79f4aac7c5f4cda4fbe5f/allennlp/modules/span_extractors/self_attentive_span_extractor.py#L36 https://github.com/allenai/allennlp/blob/0abefe2566c843af063dd0e4608002321cc4aa28/allennlp/models/coreference_resolution/coref.py#L83 (and many more)

Do I miss something? What is the purpose of wrapping them with TimeDistributed?

**Comment by DeNeutoy** [comment]
This is just a hangover from when it didn't, and sometimes we like to be explicit about when we are expecting a 2 dimensional weight multiplication to be broadcasted across another dimension. There's no reason to use this layer for linear layers, you are correct 😄

**Comment by mahnerak** [comment]
Thanks a lot for the answer. :D It really makes sense.
