### ISSUE TITLE
Pretrained model for fine-grained-ner ?

### ISSUE THREAD

**Issue by SundeepPidugu** [allenai/allennlp#2867]
Please first search our GitHub repository for similar questions.  If you don't find a similar example you can use the following template:

**System (please complete the following information):**
 - OS: Linux
 - Python version: 3.7
 - AllenNLP version: I installed from master
 - PyTorch version: yes

**Question**
where do i get the Pretrained model for fine-grained-ner ?
the model given for ner in models of Allennlp is simple and doesnt recognize most of the named entities. someone please share me the model for finegrainedner as shown in the demo page.

**Comment by nelson-liu** [comment]
You should be able to use this: https://github.com/allenai/allennlp/blob/master/allennlp/pretrained.py#L76-L82

**Comment by SundeepPidugu** [comment]
Was trying to use this in from my local as 

predictor = Predictor.from_path("/home/liferay172/Documents/Sundeep/GITHUB/Pretrained models/fine-grained-ner-model-elmo-2018.08.31.tar.gz")

file = open("/home/liferay172/Documents/Sundeep/Documents/Aries/Testing.txt","r").read()

file = file.replace("\n"," ")

result = predictor.predict(
  sentence="sundeep works in google"
)
```

**Comment by SundeepPidugu** [comment]
#2276 this fixed my issue with this
