### ISSUE TITLE
Implementing custom Machine Comprehension Model

### ISSUE THREAD

**Issue by KalidindiMounika** [allenai/allennlp#2869]
Can we train a Allennlp MC model with our own data.

**Comment by joelgrus** [comment]
certainly, the simplest thing to do is to take our training config

https://github.com/allenai/allennlp/blob/master/training_config/bidaf.jsonnet

(or the variant using ELMo)

get your data in the SQuAD format it's expecting, and update the paths to wherever your data is.

--

if you are new to the library, I recommend starting with the tutorial:

https://allennlp.org/tutorials

**Comment by KalidindiMounika** [comment]
Thanks for your response

**Comment by KalidindiMounika** [comment]
Thank you for response
