### ISSUE TITLE
Running the Event2Mind example in https://allennlp.org/models throws an exception.

### ISSUE THREAD

**Issue by hcyang** [allenai/allennlp#2877]
**Describe the bug**
Running the Event2Mind example in https://allennlp.org/models throws an exception.

**To Reproduce**
Steps to reproduce the behavior
1. Create a python program in Anaconda
 copying the Event2Mind example from the link:

from allennlp.predictors.predictor import Predictor
predictor = Predictor.from_path("https://s3-us-west-2.amazonaws.com/allennlp/models/event2mind-2018.09.17.tar.gz")
predictor.predict(
  source="PersonX drops a hint"
)

2. Run the program and see exception thrown:

**Expected behavior**
no exception like any other examples in the same links

**System (please complete the following information):**
 - OS: Windows 10
 - Python version: 3.7.0
 - AllenNLP version: 0.8.3
 - PyTorch version: 

**Additional context**

**Comment by joelgrus** [comment]
can you share what the exception was (and the stack trace)?

**Comment by hcyang** [comment]
Traceback (most recent call last):
  File "AppAllenNlpEvent2MindUtility.py", line 12, in <module>
    main()
  File "AppAllenNlpEvent2MindUtility.py", line 9, in main
    AllenNlpEvent2MindUtility.Demo()
  File "D:\git\EmbedML\private\hunyang\project\LanguageUnderstanding\src\python\LanguageUnderstandingCommonNlpTaskUtility\PretrainedModelAllenNLP\Event2Mind\AllenNlpEvent2MindUtility.py", line 8, in Demo
    predictor = Predictor.from_path("https://s3-us-west-2.amazonaws.com/allennlp/models/event2mind-2018.09.17.tar.gz")
  File "D:\anaconda3\lib\site-packages\allennlp\predictors\predictor.py", line 142, in from_path
    return Predictor.from_archive(load_archive(archive_path), predictor_name)
  File "D:\anaconda3\lib\site-packages\allennlp\models\archival.py", line 230, in load_archive
    cuda_device=cuda_device)
  File "D:\anaconda3\lib\site-packages\allennlp\models\model.py", line 327, in load
    return cls.by_name(model_type)._load(config, serialization_dir, weights_file, cuda_device)
  File "D:\anaconda3\lib\site-packages\allennlp\models\model.py", line 276, in _load
    model.load_state_dict(model_state)
  File "D:\anaconda3\lib\site-packages\torch\nn\modules\module.py", line 769, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Event2Mind:
        Missing key(s) in state_dict: "_states.xintent.embedder.weight", "_states.xintent.decoder_cell.weight_ih", "_states.xintent.decoder_cell.weight_hh", "_states.xintent.decoder_cell.bias_ih", "_states.xintent.decoder_cell.bias_hh", "_states.xintent.output_projection_layer.weight", "_states.xintent.output_projection_layer.bias", "_states.xreact.embedder.weight", "_states.xreact.decoder_cell.weight_ih", "_states.xreact.decoder_cell.weight_hh", "_states.xreact.decoder_cell.bias_ih", "_states.xreact.decoder_cell.bias_hh", "_states.xreact.output_projection_layer.weight", "_states.xreact.output_projection_layer.bias", "_states.oreact.embedder.weight", "_states.oreact.decoder_cell.weight_ih", "_states.oreact.decoder_cell.weight_hh", "_states.oreact.decoder_cell.bias_ih", "_states.oreact.decoder_cell.bias_hh", "_states.oreact.output_projection_layer.weight", "_states.oreact.output_projection_layer.bias".
        Unexpected key(s) in state_dict: "xintent_embedder.weight", "xintent_decoder_cell.weight_ih", "xintent_decoder_cell.weight_hh", "xintent_decoder_cell.bias_ih", "xintent_decoder_cell.bias_hh", "xintent_output_project_layer.weight", "xintent_output_project_layer.bias", "xreact_embedder.weight", "xreact_decoder_cell.weight_ih", "xreact_decoder_cell.weight_hh", "xreact_decoder_cell.bias_ih", "xreact_decoder_cell.bias_hh", "xreact_output_project_layer.weight", "xreact_output_project_layer.bias", "oreact_embedder.weight", "oreact_decoder_cell.weight_ih", "oreact_decoder_cell.weight_hh", "oreact_decoder_cell.bias_ih", "oreact_decoder_cell.bias_hh", "oreact_output_project_layer.weight", "oreact_output_project_layer.bias".

**Comment by kl2806** [comment]
Try using this newer model https://s3-us-west-2.amazonaws.com/allennlp/models/event2mind-2018.10.26.tar.gz
