### ISSUE TITLE
Saving source code alongside trained model

### ISSUE THREAD

**Issue by mojesty** [allenai/allennlp#2878]
**Is your feature request related to a problem? Please describe.**
During prototyping one often makes breaking changes to the model class, so loading previous checkpoints become painful. Storing model sources (and may be AllenNLP's sources or version as well) could solve this problem.

**Describe the solution you'd like**
Storing all non-default code (usually it is `DatasetReader`, `Module`, `Model` and `Predictor`) in a separate folder, when loading model, by default import this code and use it, or user can override this behaviour and load models to their new implementations.

**Describe alternatives you've considered**
Using third-party tools for experiment management may be difficult or impossible in workstations behind a proxy server.

**Comment by DeNeutoy** [comment]
I agree this is annoying, but your solution doesn't really seem tenable and really quite outside the scope of allennlp. I'd suggest using git to track modelling changes and generally recording git shas when you run groups of experiments, so you can revert code to a point at which the model can load. 

Solving it would be an interesting problem though, good luck!
