### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED

### ISSUE THREAD

**Issue by Greenbald** [allenai/allennlp#2888]
Please first search our GitHub repository for similar questions.  If you don't find a similar example you can use the following template:

**System:**
 - OS: Linux Ubuntu 18
 - Python version: 3.6.5
 - AllenNLP version: 0.8.3
 - PyTorch version: 1.1.0

**Question**

I had a problem executing the `allennlp.modules.elmo.Elmo` embedder with the following model:

```
class ELMo(nn.Module):

    def __init__(self, fine_tune=False, n_classes=2):
        super(ELMo, self).__init__()

        self.embedding = Elmo(config.PATH_TO_ELMO_OPTIONS,
                              config.PATH_TO_ELMO_WEIGHTS, 1, dropout=0.2,
                              requires_grad=fine_tune)
        n_ftrs = self.embedding.get_output_dim()
        self.fc = nn.Sequential(
            nn.Dropout(0.5),
            nn.Linear(n_ftrs, n_classes)
        )

    def forward(self, x):
        print("\tIn Model: input size", x.size())

        x = self.embedding(x)
        mask = x["mask"]
        x = x["elmo_representations"][0]
        # This is where we get the mean of the word embeddings
        x = self._get_mean(x, mask)
        # ----------------------------------------------------
        x = self.fc(x)
        return x
    
    def to_tensor(self, x):
        x = [sentence.split(" ") for sentence in x]
        x = batch_to_ids(x)
        return x
        
    def _get_mean(self, x, mask):
        x = x.sum(dim=1)
        mask = mask.sum(dim=1).float()
        mask = torch.repeat_interleave(mask, x.size(-1)).view(-1, x.size(-1))
        x = torch.div(x, mask)
        return x
```

This was the last tensor that got in the `forward()` function:  In Model: input size torch.Size([128, 445, 50])

Could it be that the size of the tensor in the dim=1 (445) is bigger than expected? 

Also, I have used this json options for the elmo: https://s3-us-west-2.amazonaws.com/allennlp/models/elmo/contributed/pt/elmo_pt_options.json

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-20-c237d26f7a66> in <module>
     40 
     41 tr = Trainer(elmo, dataloaders, criterion, optimizer_ft, exp_lr_scheduler, 200)
---> 42 model = tr.train_model()

<ipython-input-19-7c454b546b94> in train_model(self)
     55                     # track history if only in train
     56                     with torch.set_grad_enabled(phase == 'train'):
---> 57                         outputs = self.model(inputs)
     58                         _, preds = torch.max(outputs, 1)
     59                         loss = self.criterion(outputs, labels)

/workspace/ReadOrSee/env/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    491             result = self._slow_forward(*input, **kwargs)
    492         else:
--> 493             result = self.forward(*input, **kwargs)
    494         for hook in self._forward_hooks.values():
    495             hook_result = hook(self, input, result)

<ipython-input-18-bdc575dfe88e> in forward(self, x)
     42         print("\tIn Model: input size", x.size())
     43 
---> 44         x = self.embedding(x)
     45         mask = x["mask"]
     46         x = x["elmo_representations"][0]

/workspace/ReadOrSee/env/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    491             result = self._slow_forward(*input, **kwargs)
    492         else:
--> 493             result = self.forward(*input, **kwargs)
    494         for hook in self._forward_hooks.values():
    495             hook_result = hook(self, input, result)

/workspace/ReadOrSee/env/lib/python3.6/site-packages/allennlp/modules/elmo.py in forward(self, inputs, word_inputs)
    167 
    168         # run the biLM
--> 169         bilm_output = self._elmo_lstm(reshaped_inputs, reshaped_word_inputs)
    170         layer_activations = bilm_output['activations']
    171         mask_with_bos_eos = bilm_output['mask']

/workspace/ReadOrSee/env/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    491             result = self._slow_forward(*input, **kwargs)
    492         else:
--> 493             result = self.forward(*input, **kwargs)
    494         for hook in self._forward_hooks.values():
    495             hook_result = hook(self, input, result)

/workspace/ReadOrSee/env/lib/python3.6/site-packages/allennlp/modules/elmo.py in forward(self, inputs, word_inputs)
    603                 type_representation = token_embedding['token_embedding']
    604         else:
--> 605             token_embedding = self._token_embedder(inputs)
    606             mask = token_embedding['mask']
    607             type_representation = token_embedding['token_embedding']

/workspace/ReadOrSee/env/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    491             result = self._slow_forward(*input, **kwargs)
    492         else:
--> 493             result = self.forward(*input, **kwargs)
    494         for hook in self._forward_hooks.values():
    495             hook_result = hook(self, input, result)

/workspace/ReadOrSee/env/lib/python3.6/site-packages/allennlp/modules/elmo.py in forward(self, inputs)
    372         for i in range(len(self._convolutions)):
    373             conv = getattr(self, 'char_conv_{}'.format(i))
--> 374             convolved = conv(character_embedding)
    375             # (batch_size * sequence_length, n_filters for this width)
    376             convolved, _ = torch.max(convolved, dim=-1)

/workspace/ReadOrSee/env/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    491             result = self._slow_forward(*input, **kwargs)
    492         else:
--> 493             result = self.forward(*input, **kwargs)
    494         for hook in self._forward_hooks.values():
    495             hook_result = hook(self, input, result)

/workspace/ReadOrSee/env/lib/python3.6/site-packages/torch/nn/modules/conv.py in forward(self, input)
    194                             _single(0), self.dilation, self.groups)
    195         return F.conv1d(input, self.weight, self.bias, self.stride,
--> 196                         self.padding, self.dilation, self.groups)
    197 
    198 

RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.

**Comment by DeNeutoy** [comment]
Yes, basically for the char cnn, we unfold the sequence dimension in to the  batch dimension (e.g a tensor of shape (batch_size * sequence_length, hidden_dim)) because they are independent and can be run in parallel. This makes a very big matrix which triggers a bug in cudnn:

see 
https://github.com/allenai/allennlp/issues/1791
https://github.com/pytorch/pytorch/issues/4107


The solution is to reduce the batch size or use shorter sequences. Sorry!
