### ISSUE TITLE
is it possible for allennlp reading comprehension to memorize previously given quesions.

### ISSUE THREAD

**Issue by Bipin8469** [allenai/allennlp#2891]
**System:**
 OS: Windows 10 pro
Python version: 3.6.8
AllenNLP version: allennlp 0.8.4-unreleased
PyTorch version: 1.1.0

**Question**
I want to know that when I'm giving a passage and question to reading comprehension, is allennlp can memorize my question and answer?

so next time, only I have to give only a question and based on previous questions it will give me an answer.

I can do this by storing questions into a text file and when I'm asking questions, fetch that file text and perform prediction on that. 

But, at some time that gives me a maximum character limit error and it is not good to every time give that big text file for prediction. 

can anyone please give me a solution for that.
thank you.

**Comment by matt-gardner** [comment]
It sounds like you want some sort of cache.  There are plenty of mechanisms for caching results, but they aren't really related to allennlp.  I'd suggest you find some other resource outside of allennlp to set up your cache, and query the predictor only when you have a cache miss.
