### ISSUE TITLE
Error while trying to use biaffine_dependency_parser predictor

### ISSUE THREAD

**Issue by moadqassem** [allenai/allennlp#2893]
**Describe the bug**
I am trying to use the pre-trained model `biaffine_dependency_parser` predictor, however, I am facing an exception:

```sh
172.17.0.1 - - [2019-05-27 03:30:33] "POST /predict HTTP/1.1" 500 477 0.004113
[2019-05-27 03:31:20,680] ERROR in app: Exception on /predict [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/allennlp/service/server_simple.py", line 109, in predict
    prediction = predictor.predict_json(data)
  File "/usr/local/lib/python3.6/site-packages/allennlp/predictors/predictor.py", line 55, in predict_json
    instance = self._json_to_instance(inputs)
  File "/usr/local/lib/python3.6/site-packages/allennlp/predictors/biaffine_dependency_parser.py", line 108, in _json_to_instance
    if self._dataset_reader.use_language_specific_pos: # type: ignore
AttributeError: 'Conll2003DatasetReader' object has no attribute 'use_language_specific_pos'
```

**To Reproduce**
Steps to reproduce the behavior

- Get the latest image of the `allennlp`: `docker pull allennlp/allennlp:v0.8.3`
- Run the installed docker image: 
`docker run --rm -p 8000:8000 --entrypoint="" -v $HOME/.allennlp:/root/.allennlp allennlp/allennlp:v0.8.3 python -m allennlp.service.server_simple --archive-path https://s3-us-west-2.amazonaws.com/allennlp/models/ner-model-2018.12.18.tar.gz --predictor biaffine-dependency-parser --field-name sentence`  

- Execute this post request: 
`curl 'http://localhost:8000/predict' -H 'Content-Type: application/json' --data-binary '{"sentence":"Say Hello World"}'`

**Expected behavior**
`{"arc_loss":0.00048828125,"hierplane_tree":{"linkToPosition":{"acomp":"right","ccomp":"right","csubj":"left","csubjpass":"left","dobj":"right","iobj":"right","nsubj":"left","nsubjpass":"left","pcomp":"right","pobj":"right","xcomp":"right"},"nodeTypeToStyle":{"acomp":["color2"],"advcl":["color3"],"advmod":["color4"],"amod":["color4"],"appos":["color4"],"aux":["color3"],"cc":["color3"],"ccomp":["color2"],"conj":["color3"],"cop":["color3"],"csubj":["color1"],"csubjpass":["color1"],"dep":["color5","strong"],"det":["color3"],"discourse":["color3"],"dobj":["color2"],"expletive":["color3"],"infmod":["color4"],"iobj":["color2"],"mark":["color2"],"mod":["color4"],"neg":["color0"],"nn":["color4"],"npadvmod":["color4"],"nsubj":["color1"],"nsubjpass":["color1"],"number":["color3"],"pcomp":["color2"],"pobj":["color2"],"poss":["color3"],"possesive":["color3"],"prep":["color3"],"prt":["color3"],"punct":["color0"],"quantmod":["color4"],"root":["color5","strong"],"tmod":["color4"],"xcomp":["color2"]},"root":{"attributes":["VB"],"children":[{"attributes":["NN"],"children":[{"attributes":["UH"],"link":"dep","nodeType":"dep","spans":[{"end":10,"start":4}],"word":"Hello"}],"link":"dobj","nodeType":"dobj","spans":[{"end":16,"start":10}],"word":"World"}],"link":"root","nodeType":"root","spans":[{"end":4,"start":0}],"word":"Say"},"text":"Say Hello World"},"loss":0.30580803751945496,"pos":["VB","UH","NN"],"predicted_dependencies":["root","dep","dobj"],"predicted_heads":[0,3,1],"slug":"ODMwODcw","tag_loss":0.30531975626945496,"words":["Say","Hello","World"]}
`

**System (please complete the following information):**
 - OS: macOS Mojave 
 - Python version: 3.6.1
 - AllenNLP version:  v0.8.3
 - PyTorch version: Default which is installed in the image

**Comment by DeNeutoy** [comment]
Hi, you are using the NER model not the biaffine dependency parser model for the dependency parser predictor, this won't work.

**Comment by moadqassem** [comment]
Ah okay I see, any idea under which link the data which is needed for the Biaffine model are(if any is needed)?

**Comment by moadqassem** [comment]
@DeNeutoy Found it! no worries, thanks :)

**Comment by DeNeutoy** [comment]
Great! Closing.
