### ISSUE TITLE
how to ensure padding token kept been a zero-valued vector through out training process?

### ISSUE THREAD

**Issue by robbine** [allenai/allennlp#2894]
For example here is a common text field embedder configuration:

> "text_field_embedder": {
>             "type": "basic",
>             "tokens": {
>                 "type": "embedding",
>                 "embedding_dim": 200,
>                 "padding_index": 0,
>                 "trainable": true
>             },

If the embedding is trainable, does padding token vector gets updated during training process ? In fact we want it keep it unchanged, right ?

**Comment by robbine** [comment]
I guess masked_log_softmax can be used to calculate loss and also prevents backwards update on padding token embedding, is it correct ?

**Comment by kl2806** [comment]
It shouldn't matter what the embedding of the padding is because the loss is not a function of it, as it is masked out.
