### ISSUE TITLE
How could I get the document of version 0.8.3 ?

### ISSUE THREAD

**Issue by justforyou16007** [allenai/allennlp#2906]
**Question**
How could I get the document of version 0.8.3 ?
I use the document which is incompatible to my code.....
but the document can't find the version 0.8.3, thanks a lot.

**Comment by kernelmachine** [comment]
The best way to look at documentation for previous versions is to check out the git repo at a particular version, and build docs manually from there:

`cd doc; make html-strict`

**Comment by justforyou16007** [comment]
> The best way to look at documentation for previous versions is to check out the git repo at a particular version, and build docs manually from there:
> 
> `$ cd doc; make html-strict`

thank you
