### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by silencemaker** [allenai/allennlp#2907]
**Describe the bug**
ModuleNotFoundError: No module named 'allennlp.data'; 'allennlp' is not a package

**To Reproduce**
Steps to reproduce the behavior
1. source activate allennlp
2. python
3. import allennlp
4. from allennlp.data import DatasetReader
5.see error

**Expected behavior**
expect no error

**System (please complete the following information):**
 - OS: ubuntu
 - Python version: Python 3.6.8
 - AllenNLP version:  v0.8.3, I installed from pip
 - PyTorch version: 1.1.0

**Additional context**
![image](https://user-images.githubusercontent.com/37140210/58622395-14931b80-82fe-11e9-8745-4b30a3e480da.png)

**Comment by silencemaker** [comment]
![image](https://user-images.githubusercontent.com/37140210/58622502-5623c680-82fe-11e9-85cd-ec8ee5b73878.png)

**Comment by kernelmachine** [comment]
@joelgrus , can you see anything obviously incorrect here?

**Comment by joelgrus** [comment]
do you have a file called `allennlp.py` (or something like that) in your current directory? that can cause this kind of problem, because python is trying to import from that file (which is not a library) instead of from the allennlp library.

**Comment by silencemaker** [comment]
> do you have a file called `allennlp.py` (or something like that) in your current directory? that can cause this kind of problem, because python is trying to import from that file (which is not a library) instead of from the allennlp library.

OMG!!! i am sorry,there is a allennlp.py in my current directory indeed,this problem confuse me the whole day. Thank u a lot!!!
