### ISSUE TITLE
Unable to see elmo scalar_mix_parameters as trainable parameters

### ISSUE THREAD

**Issue by badesairam** [allenai/allennlp#2909]
Please first search our GitHub repository for similar questions.  If you don't find a similar example you can use the following template:

**System (please complete the following information):**
 - OS: [e.g. OSX, Linux]
 - Python version: [e.g. 3.6.1]
 - AllenNLP version: [e.g. v0.8.3, or "I installed from master"]
 - PyTorch version: (if you installed it yourself)

**Question**
Ask about something you don't understand, such as:

* How can I retrain my own ELMo language model?

* I'm working on a sentiment classification task and I would like to discard sentences that are longer than 1200 characters (my sentences vary from 400 characters to 1400+).  How can I configure my model to discard long sentences?

**Comment by kernelmachine** [comment]
You can train a Transformer ELMo with these instructions: https://github.com/allenai/allennlp/blob/master/tutorials/how_to/training_transformer_elmo.md

If you'd like to train an LSTM ELMo, you can follow the instructions here: https://github.com/allenai/bilm-tf

If you're using the text classification json reader, you can set a max sequence length in the dataset reader: https://github.com/allenai/allennlp/blob/master/allennlp/data/dataset_readers/text_classification_json.py

you can alternatively truncate the sentences in the` _read` function, if you need to truncate on the character level.

**Comment by badesairam** [comment]
Sorry this is a default issue which was posted due to some problem with internet anyways thanks.
