### ISSUE TITLE
Importing Elmo should not import pytorch_pretrained_bert or at least depend on version 0.6.2

### ISSUE THREAD

**Issue by johann-petrak** [allenai/allennlp#2914]
When doing `from allennlp.modules.elmo import Elmo` apparently `pytorch_pretrained_bert` is also getting loaded. This seems unnecessary but can also be a problem because some versions of `pytorch_pretrained_bert` write a message to standard output using `print` which can be a big problem when embedding a model where data is exchanged over a pipe. 

Allennlp depends on `pytorch_pretrained_bert` version 0.6.0 or later, but the print statement is only replaced by a logging statement in version 0.6.2

So one workaround for this problem is for the client software that uses allennlp Elmo to depend on `pytorch_pretrained_bert` version 0.6.2 or later but this is a bit weird. 

Ideally allennlp would not even try to load the bert module unless it is really needed AND allennlp would explicitly require 0.6.2. or later of the package.

The problem can be reproduced by installing `pytorch_pretrained_bert` version 0.6.1, then installing allennlp, then simply running `from allennlp.modules.elmo import Elmo` in python.

**Comment by joelgrus** [comment]
I have no issue with requiring 0.6.2, I hate that print statement too

**Comment by matt-gardner** [comment]
This can be solved by just installing a later version of `pytorch_pretrained_bert` locally.  We're planning on removing that dependency entirely for 1.0 anyway, so I'm closing this issue.
