### ISSUE TITLE
Memory consumption of ELMo keeps increasing over time

### ISSUE THREAD

**Issue by Xsea** [allenai/allennlp#2915]
I am currently trying to compare the similarity of millions of documents. For a first test on a CPU I reduced them to around 50 characters each and try to get the ELMo Embedding for 10 of them at a time like this:

    ELMO = "https://tfhub.dev/google/elmo/2"
    for row in file:
        split = row.split(";", 1)
        if len(split) > 1:
            text = split[1].replace("\n", "")
                texts.append(text[:50])
        if i == 300:
            break
        if i % 10 == 0:
            elmo = hub.Module(ELMO, trainable=False)
                         executable = elmo(
                         sentences,
                         signature="default",
                         as_dict=True)["elmo"]

        vectors = execute(executable)
        texts = []
        i += 1

However, even with this small example, after around 300 sentences (and not even saving the vectors) the program consumes up to 12GB of RAM. Is this a know issue (the other issues I found suggest something similar, but not quite that extreme) or did I make a mistake?

**Comment by kernelmachine** [comment]
Since google made the implementation of ELMo on Tensorflow Hub, we can't support this issue. We'd recommend you reach to the developers at Google on this.

**Comment by ksboy** [comment]
I have similar problem when using crf-tagger model. #3982
