### ISSUE TITLE
How to print the SQL query generated for the question I ask in WikitableQuestions Semantic Parser?

### ISSUE THREAD

**Issue by dummybot123** [allenai/allennlp#2916]
I am using WikitableQuestions Semantic Parser model for answering questions based on tabular data. I used the source code from https://github.com/allenai/allennlp. I am wondering how to get the SQL query generated for the question I ask.

**Comment by kl2806** [comment]
The formalism that is used in the Wikitables Semantic Parser is actually lambda-DCS, not SQL, which you can learn about more here if you are interested (https://arxiv.org/pdf/1309.4408.pdf).

If you want to look at the logical form (query) of some input questions, the easiest way to do that is to check out the demo (https://demo.allennlp.org/wikitables-parser/ODQwNjcw). If you want to do it programmatically, you can access it in the outputs of the model (https://github.com/allenai/allennlp/blob/master/allennlp/models/semantic_parsing/wikitables/wikitables_semantic_parser.py#L664). To print it out you can do something like the following:
```
In [4]: from allennlp.predictors import Predictor
   ...: from allennlp.models.archival import load_archive
   ...: archive = load_archive("https://storage.googleapis.com/allennlp-public-models/wikitables-model-2018.09.14.tar.gz")
   ...: predictor = Predictor.from_archive(archive, 'wikitables-parser')
   ...: inputs = [{
   ...:                 "question": "Who is 18 years old?",
   ...:                 "table": "Name\tAge\nShallan\t16\nKaladin\t18"
   ...:         }]
   ...: result = predictor.predict_batch_json(inputs)
   ...: logical_form = result[0].get("logical_form")
   ...: print(logical_form)
   ...:
   ...:
   ...:
Grammar.read {
  Valid tags: [alternative, arithmetic, closedclass, comparison, merge, merge-and, merge-or, neq, part, prenormalized, scoped, scoped-2args-arithmetic, scoped-2args-merge, scoped-2args-merge-and, scoped-2args-merge-or, set, yearrange]
  Used tags: [alternative, arithmetic, closedclass, comparison, merge-and, neq, part, scoped, scoped-2args-merge-and, yearrange]
  47 rules
}
Parser: 19 catUnaryRules (sorted), 28 nonCatUnaryRules (in trie)
Total examples evaluated: 1
Average accuracy: 0.0
((reverse fb:row.row.name) (fb:row.row.age fb:cell.18))
```
