### ISSUE TITLE
Error in Textual Entailment demo code

### ISSUE THREAD

**Issue by pHequals7** [allenai/allennlp#2917]
- Windows 10
 - Python version: [e.g. 3.7.3]
 - AllenNLP version: [0.8.4]
 - PyTorch version: [1.1.0]

This is the code from the AllenNLP site which I copied to give a test run onto my local machine and when I run I keep getting a "bad escape \p at position 257" error at line 2 i.e Predictor.from_path() line

`from allennlp.predictors.predictor import Predictor`
`predictor = Predictor.from_path("https://s3-us-west-2.amazonaws.com/allennlp/models/decomposable-attention-elmo-2018.02.19.tar.gz")`
`predictor.predict(
  hypothesis=re.escape("Two women are sitting on a blanket near some rocks talking about politics."),
  premise=re.escape("Two women are wandering along the shore drinking iced tea.")
)`

**Comment by joelgrus** [comment]
it seems likely that this error is caused by having an old spacy model, see 

https://github.com/explosion/spaCy/issues/3544

**Comment by pHequals7** [comment]
Works well with 'en_core_web_sm' 2.1.0 version while for the 2.1.0 versions of 'en_core_web_md' and 'en_core_web_lg' same error persists. Guess it's upto spaCy to solve it?

**Comment by joelgrus** [comment]
the medium version loads fine for me, but yeah if the error is in loading the spacy model there's not much we can do about that, I'd suggest opening an issue over there.
