### ISSUE TITLE
WikiTable semantic parsing as a library

### ISSUE THREAD

**Issue by Bipin8469** [allenai/allennlp#2921]
** System:**

OS: Windows 10 pro
Python version: 3.6.8
AllenNLP version: allennlp 0.8.4-unreleased
PyTorch version: 1.1.0

**Question**
can I use WikiTable semantic parsing as a library like other features given in this link https://allennlp.org/models?

thank you.

**Comment by kl2806** [comment]
Yes, there is a pretrained Wikitables semantic parser that you can use, does the example in #2916 answer your question?

**Comment by Bipin8469** [comment]
predictor = Predictor.from_path("models/wikitables-model-2018.09.14.tar.gz")
        inputs = [{
            "table" : wikitable,
            "question" : wikiquestion
        }]
        result = predictor.predict_batch_json(inputs)
        logical_form = result[0].get("logical_form")


when I running above code I got an error.


 return input_tensor.contiguous().view(*squashed_shape)
RuntimeError: cannot reshape tensor of 0 elements into shape [-1, 0, 200] because the unspecified dimension size -1 can be any value and is ambiguous

**Comment by kl2806** [comment]
I think the most likely error here is that `wikitable` is not correctly formatted. Can you make sure it matches the example I linked above? https://github.com/allenai/allennlp/issues/2771#issuecomment-488052999 Here is some more detail about the format expected

**Comment by matt-gardner** [comment]
Closing this issue; feel free to comment again if you have more questions.
