### ISSUE TITLE
What is a convenient way to encode a pair of sentences with BERT?

### ISSUE THREAD

**Issue by maxdel** [allenai/allennlp#2934]
What is a convenient way to encode a pair of sentences with BERT?

Should I insert "[SEP]" token in between sentences and treat them as a single TextField? 

I saw corresponding [PR ](https://github.com/allenai/allennlp/pull/2279), but how do I use this functionality?

**Comment by matt-gardner** [comment]
Yes, you just insert that token in between the tokens you want, and pass them off to the `TextField`.  You can see an example of that in this test (the comment on line 142 is off, but the code is correct): https://github.com/allenai/allennlp/blob/9a0e01fae76fd40211c3499a791d334a8f48da9c/allennlp/tests/data/token_indexers/bert_indexer_test.py#L126-L143

I'd recommend writing a simple test yourself for your use case to convince yourself that it's doing what you want, but this should work.

**Comment by maxdel** [comment]
Thanks, it works!
