### ISSUE TITLE
Archive AllenNLP by version

### ISSUE THREAD

**Issue by nickswalker** [allenai/allennlp#2944]
**Is your feature request related to a problem? Please describe.**
I would like to cite a particular version of AllenNLP used in a research project.

**Describe the solution you'd like**
Archival depositing of AllenNLP on each version release, preferably with an accompanying DOI.
One integrated solution for this is [Zenodo](https://zenodo.org), which can archive and issue a DOI automatically for each tagged release. Someone from the Software Sustainability Institute put together [an explainer](https://softwaresaved.github.io/software-deposit-guidance/WhyDepositSoftware.html) covering some motivations for archiving software, and GitHub has [a guide](https://guides.github.com/activities/citable-code/) for their Zenodo integration.

**Describe alternatives you've considered**
Referencing by commit hash or similar is fragile, and does not carry any machine readability benefits.

**Comment by matt-gardner** [comment]
If you want to cite AllenNLP in a research paper, please cite our paper (see [here](https://allennlp.org/publications)).  If you want a stable way to access or refer to previous versions, pip releases are persistent.  It's very unlikely that we will do something with Zenodo.

**Comment by nickswalker** [comment]
That's fine for me, but won't lead to any measurable attribution to releases of the software and doesn't acknowledge community contributors.

Is there a particular reason to _not_ have some kind of archiving of the software?

**Comment by matt-gardner** [comment]
The main reason not to have it is that we are a very small team.  We have enough else going on that adding another thing to support is not worth it.
