### ISSUE TITLE
linear_assignment_ is deprecated in scikit-learn

### ISSUE THREAD

**Issue by jnothman** [allenai/allennlp#2945]
**Describe the bug**
Importing allennlp.training.metrics.conll_coref_scores results in the following warning with Scikit-learn 0.21 installed:

> DeprecationWarning: The linear_assignment_ module is deprecated in 0.21 and will be removed from 0.23. Use scipy.optimize.linear_sum_assignment instead.

**Expected behavior**
No warning issued

**System (please complete the following information):**
 - AllenNLP version: installed from pip

**Comment by matt-gardner** [comment]
PR welcome!

**Comment by rcshubhadeep** [comment]
One question, as a newcomer to AllenNLP I was thinking to fix this. Is there any particular coding guideline that you guys follow? I feel it is a good first issue for a newcomer.

**Comment by pidugusundeep** [comment]
PR proposed, should it be clean like I had some changes made to my forked project and reverted back but still the commit messages are present irrespective of NO changes from the earlier commits is that a good practice to create a PR, is that still fine when contributing? can you please check my PR and let me know @matt-gardner
