### ISSUE TITLE
Demo URLs should be fully linkable

### ISSUE THREAD

**Issue by matt-gardner** [allenai/allennlp#295]
That is, after you've run a query on one of the models, you should be able to copy/paste the URL and get exactly the same page.  Some context: on [this twitter](https://twitter.com/emhusband/status/907202918616530944) thread, people were sharing screenshots of the demo.  It should be possible to just share a link.

**Comment by schmmd** [comment]
I'd love to have demo URLs linkable.  I discussed this with Brandon at one point and he thought I would need a database to store queries and link to them by id due to the length of the input text.

**Comment by schmmd** [comment]
Closed by https://github.com/allenai/allennlp/pull/451.
