### ISSUE TITLE
Nit-picking proposition: ensure all callback names are in imperative mood

### ISSUE THREAD

**Issue by epwalsh** [allenai/allennlp#2963]
This may be a little late, but I thought I should throw this out there before an official release of the callback trainer. It looks like all of the callback registered names are imperative mood (e.g. `log_to_tensorboard`), which I like, except for two: `learning_rate_scheduler` and `momentum_scheduler`. I propose changing their registered names to `schedule_learning_rate` and `schedule_momentum`, respectively. This would make them consistent with the other callback names and also disambiguate the callbacks from the schedulers.

**Comment by joelgrus** [comment]
I don't like the verb "schedule" there, I would prefer "update_learning_rate" or something like that. suggestions / PR welcome.
