### ISSUE TITLE
Asymmetric text embedders on source and target

### ISSUE THREAD

**Issue by dDua** [allenai/allennlp#2970]
I am not sure if it is a bug or I am configuring this the wrong way. In a Seq2Seq like setting, I want to embed both word tokens and token characters at source side but only tokens on the target side. My configuration looks like below

```{
    "dataset_reader": {
        "type": "char_generator",
        "instance_format": "drop",
        "passage_length_limit": 400,
        "question_length_limit": 100,
        "skip_when_all_empty": [ ],
        "source_token_indexers": {
            "tokens": {
                "type": "single_id",
                "lowercase_tokens": true,
                "namespace": "tokens"
            },
            "token_characters": {
                "type": "characters",
                "min_padding_length": 5,
                "namespace": "token_characters"
            },
        },
        "target_token_indexers": {
            "tokens": {
                "type": "single_id",
                "lowercase_tokens": true,
                "namespace": "tokens"
            }
        }
    },
    "text_field_embedder": {
        "token_embedders": {
            "token_characters": {
                "type": "character_encoding",
                "embedding": {
                    "embedding_dim": 64
                },
                "encoder": {
                    "type": "cnn",
                    "embedding_dim": 64,
                    "ngram_filter_sizes": [
                        5
                    ],
                    "num_filters": 200
                }
            },
            "tokens": {
                "type": "embedding",
                "embedding_dim": 300,
                "pretrained_file": "/data/embeddings/glove.840B.300d.lower.zip",
                "trainable": false,
                "vocab_namespace": "tokens"
            }
        },
        "allow_unmatched_keys": true
    }
}
```

I added "allow_unmatched_keys" so that the embedder will continue processing even when the input_keys don't match the embedder_keys (https://github.com/allenai/allennlp/blob/master/allennlp/modules/text_field_embedders/basic_text_field_embedder.py#L75)

Now, the problem is I get the error below because the iterator is over embedder_keys and not over intersection of embedder_keys (which contains "tokens" and "token_characters") and input_keys (which contains only "tokens") https://github.com/allenai/allennlp/blob/master/allennlp/modules/text_field_embedders/basic_text_field_embedder.py#L96

    train_metrics = self._train_epoch(epoch)
    loss = self.batch_loss(batch_group, for_training=True)
    output_dict = self.model(**batch)
    result = self.forward(*input, **kwargs)
    target_representation = self._text_field_embedder(answer_as_target_digits)
    result = self.forward(*input, **kwargs)
    File "/usr/local/lib/python3.6/dist-packages/allennlp-0.8.3_unreleased-py3.6.egg/allennlp/modules/text_field_embedders/basic_text_field_embedder.py", line 122, in forward
    tensors = [text_field_input[key]]
    KeyError: 'token_characters'

I am not sure if using the intersection is the right way or I need to configure it differently. Would appreciate any suggestions! Thanks!

**Comment by DeNeutoy** [comment]
Hey Dheeru, could you add a full stacktrace to this? It's a little complicated and it would help me get a grip of what's going wrong 😄

**Comment by DeNeutoy** [comment]
Ah from your code snippet, it looks like `answer_as_target_digits` would have been encoded using the `target_token_indexers` - in this case, it wouldn't have the `token_characters` field, so your token embedder cannot process it. 

I think I see what you are trying to achieve - you want the embedding inside the token embedder to be used also for the target tokens. There are two ways you could do this:

1. Have a `answer_textfield_embedder` defined in your constructor which shares the weight from the normal `text_field_embedder` (something like `textfield_embedder._token_embedder_1.weight` to access the weight matrix). Then, use this answer embedder (which does not have a character encoder) to encode the target tokens.

2. Extract the embedding weight and use `torch.nn.functional.embedding_lookup` to lookup the indices for decoding (you can access the tensor from the text field just via `answer_tokens["tokens"]`)

**Comment by DeNeutoy** [comment]
@dDua FYI

**Comment by dDua** [comment]
Sorry for the late response. For some reason, it went to my junk mail. Thanks for the reply I will create separate embedders, like you suggested.
