### ISSUE TITLE
Missing parameter `target_token_indexers` in dataset_readers/copynet_seq2seq.py

### ISSUE THREAD

**Issue by abaheti95** [allenai/allennlp#2975]
**Minor Bug**
The docs mention that you can optionally pass the parameter `target_token_indexers` https://github.com/allenai/allennlp/blob/459633c9474de1dfca0976629f16beeb92e83d30/allennlp/data/dataset_readers/copynet_seq2seq.py#L75-L77
However the `__init__()` method doesn't allow to send this parameter
https://github.com/allenai/allennlp/blob/459633c9474de1dfca0976629f16beeb92e83d30/allennlp/data/dataset_readers/copynet_seq2seq.py#L101-L106
And does a default initialization
https://github.com/allenai/allennlp/blob/459633c9474de1dfca0976629f16beeb92e83d30/allennlp/data/dataset_readers/copynet_seq2seq.py#L116-L118

Which is why I was getting this error:
```python
    reader = CopyNetDatasetReader(target_namespace='target_tokens',
        source_token_indexers={'tokens': SingleIdTokenIndexer()},
        target_token_indexers={'tokens': SingleIdTokenIndexer(namespace='target_tokens')})
```
```
Traceback (most recent call last):
  File "allennlp_seq2seq.py", line 92, in <module>
    main()
  File "allennlp_seq2seq.py", line 37, in main
    target_token_indexers={'tokens': SingleIdTokenIndexer(namespace='target_tokens')})
TypeError: __init__() got an unexpected keyword argument 'target_token_indexers'
```

Maybe update the documentation or add the parameter

**Comment by DeNeutoy** [comment]
Good find, thanks - would you mind submitting a PR to remove that incorect documentation?

**Comment by epwalsh** [comment]
Hmm I think the best fix at the moment would be to update the docstring and keep the code the same, because at the moment `CopyNet` only uses a `SingleIdTokenIndexer` with a key of `tokens` for the target tokens. So any other token indexers would be ignored.

**Comment by DeNeutoy** [comment]
Yes I am suggesting to remove the documentation...

**Comment by epwalsh** [comment]
@DeNeutoy yea sorry, misread your comment. Mine was directed more towards the OP since they suggested adding the parameter.

**Comment by rcshubhadeep** [comment]
I also came across this issue. However, I kind of thought that it is the desired behavior. So I used it as it is. But I agree removing this piece of documentation can be good.
