### ISSUE TITLE
Allow annotation in the demo

### ISSUE THREAD

**Issue by matt-gardner** [allenai/allennlp#298]
Kind of out there, and not at all what we were originally thinking about with the demo, but if we're logging queries, we could also allow people to say "good" or "bad" after seeing the results, and log those, too.  With some basic functionality in place, it shouldn't be _that_ much work if someone then wants to actually use this for getting labels for some evaluation, or something.

**Comment by joelgrus** [comment]
this is closely related to https://github.com/allenai/allennlp/issues/295 (in the sense that you need a similar database and logic for each of them)

**Comment by schmmd** [comment]
Now that we have a database, this would be pretty straightforward.
