### ISSUE TITLE
configuration logic for custom from_params methods should live with them

### ISSUE THREAD

**Issue by joelgrus** [allenai/allennlp#2980]
it's not a good idea (and not sustainable) for `configuration.py` to contain a record of one-off logic for things like `Vocabulary` whose configuration schema can't be inferred from their constructors.

instead, this custom logic should live with the custom from_params methods itself.

one somewhat straightforward idea would be to introduce a decorator `@configuration(config)` for the custom from_params methods that takes in the custom configuration spec and attaches it as a `_configuration` property on the `from_params` method, so that then the config wizard can check if that exists and uses it

**Comment by matt-gardner** [comment]
I like this idea.

**Comment by DeNeutoy** [comment]
+ 1

**Comment by matt-gardner** [comment]
We're instead trying to remove the need for custom `from_params` entirely, instead of doing it this way.  Closing this issue.
