### ISSUE TITLE
where can I find the SQL Grammar introduced in Lin et al 2019?

### ISSUE THREAD

**Issue by aagohary** [allenai/allennlp#2989]
I am not able to find the SQL grammar introduced in the paper "Grammar-based Neural Text-to-SQL Generation". Would you please point me to it? Thanks,

**Comment by aagohary** [comment]
I guess I found it https://github.com/allenai/allennlp/blob/master/allennlp/semparse/contexts/atis_sql_table_context.py

**Comment by matt-gardner** [comment]
If you're looking for the ATIS grammar, that is correct.  If you're looking for the spider grammar, I think that's in a separate repo that @benbogin will add at some point in the hopefully not-too-distant future.
