### ISSUE TITLE
add_positional_features seems different from <<Attention is all your need>>

### ISSUE THREAD

**Issue by cjopengler** [allenai/allennlp#2993]
The bug code:
"sinusoids = torch.cat([torch.sin(scaled_time), torch.cos(scaled_time)], 1)"

In Attention is all your need, PE(pos, 2i) = sin(*), PE(pos, 2i+1) = cos(*). It means "sin" position is even and "cos" is odd. But the above code, it means "sin" is the first half position from [0, hidden_dim/2], and "cos" is the second half position [hidden_dim/2 + 1, hidden_dim-1]. I think this is a bug, "sinusoids" should follow odd and even position in [0, hidden_dim] positions.

**Comment by DeNeutoy** [comment]
The order of the dimensions is essentially arbitrary and also, this is how it is implemented in tensor2tensor, see here:

https://github.com/tensorflow/tensor2tensor/blob/e1cf771cef3072967908484f1e3f66574c6fb6f5/tensor2tensor/layers/common_attention.py#L655


I don't know why they wrote it like that in the paper, just seems confusing :)
