### ISSUE TITLE
Callback Trainer reads dataset multiple times

### ISSUE THREAD

**Issue by vikigenius** [allenai/allennlp#2994]
**Describe the bug**
I just decided to try out the callback trainer, and noticed that it reads the dataset and generates vocabulary multiple times

**To Reproduce**
Steps to reproduce the behavior
1. Use callback trainer on some dataset reader with files
2. Use allennlp train command
3. Look at logs to see that dataset is being read multiple times and same with vocabulary creation

**Expected behavior**
Dataset should be only be read once

**System (please complete the following information):**
 - OS: Linux
 - Python version: 3.7
 - AllenNLP version: "I installed from master"

**Additional context**
Possible issue could be that in the train subcommand:
https://github.com/allenai/allennlp/blob/30ffaa54b66dfe85c6f6e9fa495745332466cccc/allennlp/commands/train.py#L230

TrainerPieces is being called, which is also being called by the callback trainer's from_params:
https://github.com/allenai/allennlp/blob/30ffaa54b66dfe85c6f6e9fa495745332466cccc/allennlp/training/callback_trainer.py#L216

I am not very familiar with the codebase so I am no 100% sure if this is the issue, but this seems very likely to be the possible cause.

**Comment by joelgrus** [comment]
ugh, so this is really a bug in the train command, not in the callback trainer. (not that that makes a difference).

basically, as a short cut, if you're using a non-standard trainer we use TrainerPieces.from_params() to get the evaluation iterator and dataset. that has the side effect of loading the whole dataset. we should just grab those things out of the config manually.

thanks for finding this!

**Comment by joelgrus** [comment]
this is somewhat complicated to solve in a clean way, I think the best solution is that the `train` command only loads / runs the evaluation dataset if you're using the standard trainer. 

so in the callback trainer you could just add an evaluation callback that runs at the end of training, which seems like a better way to handle things.

**Comment by matt-gardner** [comment]
That solution seems reasonable to me.
