### ISSUE TITLE
log_to_tensorboard callback prints log messages that interfere with tqdm

### ISSUE THREAD

**Issue by vikigenius** [allenai/allennlp#2998]
**Describe the bug**
Using the callback trainer with log_to_tensorboard callback prints log messages that stop tqdm from working properly

**To Reproduce**
Steps to reproduce the behavior
1. Use callback trainer
2. add log_to_tenorboard callback
3. train some model
4. tqdm breaks into multiple lines and doesn't display progress correctly

**Expected behavior**

**System (please complete the following information):**
 - OS: Linux
 - Python version: 3.7
 - AllenNLP version: I installed from master

**Additional context**
Specifically it's this log message:
https://github.com/allenai/allennlp/blob/9a13ab570025a0c1659986009d2abddb2e652020/allennlp/training/callbacks/log_to_tensorboard.py#L89

**Comment by joelgrus** [comment]
if you don't want that log line, don't specify `log_batch_size_period`, and that whole code block won't run

**Comment by DeNeutoy** [comment]
Well, then the batch sizes also wouldn't be logged to tensorboard. I think the right solution is that `info` should be a `logger.debug` so that it only prints to the console if you're in debug mode.

**Comment by joelgrus** [comment]
wouldn't you also want this if you were doing "file friendly logging" at INFO level?

**Comment by DeNeutoy** [comment]
No, because it is also logged to tensorboard so you can just look there. Nothing inside the training loop should be logged per batch, because of exactly this problem (it would also effect `file_friendly_logging`). The only time you need to look at _every_ batch size in your dataset is if you are debugging something.

**Comment by joelgrus** [comment]
file friendly logging already messes up tqdm

```
2019-06-21T02:26:46.666479033Z	
Loss:	0.064; Iteration:  59%|█████▊    | 9523/16247 [59:23<42:53,  2.61it/s][A
2019-06-21T02:26:47.042109672Z	
Loss:	0.064; Iteration:  59%|█████▊    | 9524/16247 [59:23<43:43,  2.56it/s][A
2019-06-21T02:26:47.042382578Z	
Loss:	0.064; Iteration:  59%|█████▊    | 9524/16247 [59:24<43:43,  2.56it/s][A
2019-06-21T02:26:47.412461252Z	
Loss:	0.064; Iteration:  59%|█████▊    | 9525/16247 [59:24<43:13,  2.59it/s][A
2019-06-21T02:26:47.412915596Z	
Loss:	0.064; Iteration:  59%|█████▊    | 9525/16247 [59:24<43:13,  2.59it/s][A
2019-06-21T02:26:47.795077409Z	
Loss:	0.064; Iteration:  59%|█████▊    | 9526/16247 [59:24<42:42,  2.62it/s][A
```

But anyway, the CallbackTrainer behaves this way only because the default trainer behaves this way. If we want to change one we should probably change both

**Comment by brendan-ai2** [comment]
Will change to debug level.
