### ISSUE TITLE
Integration with torchtext for reading datasets?

### ISSUE THREAD

**Issue by shtratos** [allenai/allennlp#3000]
**Is your feature request related to a problem? Please describe.**
[Torchtext](https://github.com/pytorch/text) has a lot of built-in datasets and knows how to read them. 
It'd be great if I could use them easily with my AllenNLP models.

When I wanted to use PTB to train a simple language model I had to configure URLs in experiment config and extend `SimpleLanguageModelingDatasetReader` to support caching. I expected using PTB to be much simpler and work out of the box. 

Having lots of datasets working with zero configuration out of the box may increase the appeal of using AllenNLP. Also it can offload the effort of maintaining some dataset readers currently present in AllenNLP (Unix way, yey!) 

**Describe the solution you'd like**
I'd like to have an adaptor(or set of adaptors) that can wrap Torchtext objects to make them usable with AllenNLP models and trainers.

**Describe alternatives you've considered**
Writing my own dataset reader, porting Torchtext one, adapting existing dataset readers in AllenNLP. Manually configuring dataset paths.

I don't know how different Torchtext and AllenNLP dataset models are and if it's even possible to align them, but IMO that'd be a good productivity boost.

**Comment by matt-gardner** [comment]
It's been a long time since I looked at torchtext, but I'm pretty sure it's _very_ different from how allennlp thinks about data, and any kind of wrapper would be very challenging.  It's probably a better use of time to just write allennlp dataset readers for whatever datasets are missing.

**Comment by isolet** [comment]
Is there any `BPTTIterator` of `torchtext` replacement in `allennlp`? I can't find it...
