### ISSUE TITLE
Validate callback and Track Metrics callback not resetting metrics consistently

### ISSUE THREAD

**Issue by vikigenius** [allenai/allennlp#3001]
**Describe the bug**
When using the callback trainer with validate and track_metrics callbacks, the metrics are not getting reset properly.

**To Reproduce**
Steps to reproduce the behavior
1. Use callback trainer with validate and track_metrics callback
2. compute some metric like boolean_accuracy
3. add a log or print message in the reset function of the metric
4. the reset happens twice, both immediately after validation. The 2nd time reset happens, since the validation metrics have already been reset boolean accuracy throws a division by zero error

**Expected behavior**
Metrics should have been reset once after training finishes and before validation begins and once after validation finishes

**System (please complete the following information):**
 - OS: Linux
 - Python version: 3.7
 - AllenNLP version: I installed from master

**Additional context**
After some debugging I noticed that the execution flows like this:
callback_trainer fires VALIDATE event
validate function is one of the handlers of this event which resets the validation metrics after validation is finished
https://github.com/allenai/allennlp/blob/9a13ab570025a0c1659986009d2abddb2e652020/allennlp/training/callbacks/validate.py#L83-L86

collect_metrics is another handler for the VALIDATE event and has priority 100, so it seems to be getting executed after validate. It also tries to reset the metrics, but right now the model is still in eval() mode, so it resets the same validation metrics again.
https://github.com/allenai/allennlp/blob/9a13ab570025a0c1659986009d2abddb2e652020/allennlp/training/callbacks/track_metrics.py#L93-L96

I don't even see where the training metrics are supposed to be reset. Ideally before the validation starts, the training metrics should already have been collected and reset, so that they don't interfere with val_metrics. That is the behaviour in the default trainer as well, but here it is inconsistent.

**Comment by brendan-ai2** [comment]
Appears fixed by #3002 .
