### ISSUE TITLE
Embedding lists of categorial features

### ISSUE THREAD

**Issue by EmilyAlsentzer** [allenai/allennlp#3004]
**System (please complete the following information):**
 - OS: Linux
 - Python version:  3.7.3
 - AllenNLP version:  v0.8.4
 - PyTorch version: 1.1.0

**Question**
I'm working with a multimodal dataset that contains text and a large number of categorical and numeric features. I would like to be able to embed an unspecified number of categorical variables and append those embeddings to the output of my text encoder. 

Right now my DatasetReader converts the categorical features to a `ListField` of `LabelFields`, where each `LabelField` has its own namespace. I want to be able to easily modify the categorical features that are included in the model so I don't want to hard code the number or type of categorical features. 

I'm running into problems when I want to embed this list of categorical features in my model, where each categorical feature has a unique namespace. What is the best way to do this? 

I'm currently doing something very hacky - creating a separate `Embedding` module for each namespace that ends in "tags" by looping over all of the namespaces in `vocab._retained_counter.keys()`. However, I'm not sure the best way to apply these Embedding modules to the categorical data in `forward`, as the ListField of LabelFields is converted to a tensor of size (batch size, number of categorical features), and the ordering of the categorical features is not known (except from the DatasetReader itself).

I think the kind of functionality that I want is most similar to that of the TextField, which outputs a dictionary of arrays. That would allow me to align the Embedding module namespaces to the correct tensor. 

Any thoughts on the best way to handle this? Thanks for the help!

**Comment by brendan-ai2** [comment]
Hi @EmilyAlsentzer, could you please provide a concrete example of what you're trying to do? It's possible that an easier approach here would be to have separate `ListField`s for each of the different label types (where you're currently using different namespaces) and have a way of indicating when a particular label type is not present.

**Comment by EmilyAlsentzer** [comment]
The ultimate goal is to be able to pass in an unspecified number of categorical variables into my model and create an `Embedding` for each variable (e.g. gender embedding, ethnicity embedding, etc.). One approach would be to create a separate `LabelField` for each variable, but then you'd have to explicitly pass each `LabelField` into `forward`. I'd like to avoid this because I want to easily change the number of categorical variables I pass in. One option would be to always pass all categorical variables into forward & use booleans to indicate whether you want to use them, but this could get unwieldy very quickly.

To get around this, right now I'm doing the following: 

In my `DatasetReader` I create a `ListField` of `LabelFields`
```
demographics_list = []
for d_name, d_value in demographics.items():
            demographics_list.append(LabelField(d_value, label_namespace=d_name + "_tags"))
 fields['demographics'] = ListField(demographics_list)
```

In my model init, I initialize an `Embedding` for each categorical variable as follows:
```
self.categorical_embeddings = {}
         for namespace in vocab._retained_counter.keys():
                if namespace.endswith('tags'):
                    self.categorical_embeddings[namespace] = Embedding(num_embeddings=vocab.get_vocab_size(namespace), 
                        embedding_dim=embedding_dim, vocab_namespace=namespace)
```

Then in `forward` I can loop over the `self.categorical_embeddings` and embed each categorical variable separately:

```
for d, embedding in zip(demographics_list, self.categorical_embeddings.values()):
                dem_embeddings.append(embedding(d).squeeze())
```

This approach works, but seems very hacky. Is there a cleaner way to do this that also maintains the flexibility of easily adding/removing categorical variables? Thanks!

**Comment by matt-gardner** [comment]
I don't think there's a better way to do what you want to do other than to make the list into a dictionary.  We don't have any field that does that, but it might not be that hard to make one yourself.  The `TextField` _kind of_ does this, as you say, but it's different enough that I'm not sure it would be a useful starting place.

It looks like we should add a `get_namespaces` method to `Vocabulary`, though, so you don't have to do `vocab._retained_counter.keys()`.

**Comment by DeNeutoy** [comment]
Looks like we've resolved most of the issue here, closing.
