### ISSUE TITLE
Where could i download the codes about different models of ALLennlp?

### ISSUE THREAD

**Issue by 18222278799** [allenai/allennlp#3007]
Where could i download the codes about different models of ALLennlp?

**Comment by brendan-ai2** [comment]
Hi @18222278799. The source code for our models is located in https://github.com/allenai/allennlp/tree/master/allennlp/models, but I may be misunderstanding your question. Please let me know if that doesn't answer it!

**Comment by 18222278799** [comment]
i cannot find the source code of Open inforamtion extraction.Thank you

**Comment by guoquan** [comment]
It seems this thread #2840 would be helpful.

**Comment by 18222278799** [comment]
Thank you , But the code is gabrielStanovsky/supervised-oie. Is there an implementation  in AllenNLP

**Comment by guoquan** [comment]
If you take a look at @gabrielStanovsky 's repos, you will find it direct you to this instruction https://allennlp.org/models#open-information-extraction, which further indicates what should you search for in this repos.
I guess they have a register `open-information-extraction`, what would reveal more details.

**Comment by brendan-ai2** [comment]
If you open the model archive and for the Open IE model (https://s3-us-west-2.amazonaws.com/allennlp/models/openie-model.2018-08-20.tar.gz, linked from https://allennlp.org/models) you'll find the following in `config.json`:

```
    "model": {
        "type": "srl",
        ...
```

Searching for `register("srl")` on AllenNLP's Github pulls up the corresponding registration: https://github.com/allenai/allennlp/blob/master/allennlp/models/semantic_role_labeler.py#L20

That should be the source code you're looking for.

**Comment by gabrielStanovsky** [comment]
Hi @18222278799, 
as @brendan-ai2 pointed out, the code for the implementation of Open IE uses the model architecture of SRL, with a different predictor: 
https://github.com/allenai/allennlp/blob/master/allennlp/predictors/open_information_extraction.py

Hope this helps!
