### ISSUE TITLE
BERT NER training approach

### ISSUE THREAD

**Issue by arunzz** [allenai/allennlp#3009]
Pls let know what advantage the CNN character level embedding gives on top of bert token embedding. The bert embedding in a way takes care of subword and character embedding isnt it?

**Comment by brendan-ai2** [comment]
Hi @arunzz, are you referring to a particular model in AllenNLP or asking a general question? I can direct you to the correct person if it's in AllenNLP, but otherwise I would suggest that the answer is probably best found empirically.

**Comment by arunzz** [comment]
Hi brendan-ai2, it is in AllenNLP BERT ner model, though it is not registered as a model, the config json shared by joelgrus had bert embeddings plus character embedding CNN.

**Comment by brendan-ai2** [comment]
I'm not sure what model you're talking about. Could you please provide a link?

**Comment by arunzz** [comment]
https://github.com/allenai/scibert/blob/master/allennlp_config/ner.json
In here , for token characters, cnn encoder is used. Is it needed or is there any added advantage as BERT already takes care of subwords.

**Comment by brendan-ai2** [comment]
Sorry, that's a different repository authored by another team. I'm not familiar with it. If you go to the issues on that repo, https://github.com/allenai/scibert/issues/, you'll quickly find https://github.com/allenai/scibert/issues/41 which asks precisely the same question. Could you please follow up with the authors there?
