### ISSUE TITLE
Using cache_data and jsonnet configuration file

### ISSUE THREAD

**Issue by XiWen0426** [allenai/allennlp#3011]
- OS: Linux
 - Python version: 3.7.3
 - AllenNLP version: v0.8.4

* I'm working on a project which needs complicated pre-processing on the dataset, so I would like to use cache_data() in dataset reader. But since I use jsonnet configuration, and train the model automatically buy allennlp command. How could I specify to use the cache_data() function...? 

Thanks!

**Comment by matt-gardner** [comment]
You should use these parameters to the `train` command: https://github.com/allenai/allennlp/blob/9b929b289bb5220f0a8c8f21bd0c1ffc0bbca9e9/allennlp/commands/train.py#L90-L99

**Comment by brendan-ai2** [comment]
Let us know if you have any issues!
