### ISSUE TITLE
wordpiece_indexer truncation logging is too verbose

### ISSUE THREAD

**Issue by joelgrus** [allenai/allennlp#3014]
https://github.com/allenai/allennlp/blob/master/allennlp/data/token_indexers/wordpiece_indexer.py#L210

on one hand it's a good idea to warn on these, on the other if you're expecting that behavior it's just pollution. maybe it should be changed to `logger.debug`?

**Comment by matt-gardner** [comment]
Is there a `log once` functionality anywhere in the logger?

**Comment by joelgrus** [comment]
not exactly, although you can do things like this:

https://stackoverflow.com/questions/31953272/python-logging-print-message-only-once

**Comment by joelgrus** [comment]
although you can also imagine a scenario where you'd want to be warned that a lot of your instances are getting truncated

**Comment by brendan-ai2** [comment]
I'm going to check to make sure we can change the logging level for this module.

**Comment by brendan-ai2** [comment]
I dug around for a way that our users can currently configure logging levels on a per-module basis, but I don't think it exists in the library. What we'd need to add is a call like `logging.config.fileConfig('logging.conf'). See https://docs.python.org/2/howto/logging.html#configuring-logging. Though maybe that conflicts with our existing config? Did any of you in triage meeting mean to suggest an alternate configuration mechanism?

**Comment by matt-gardner** [comment]
You can only do this if you're writing your own code, but you can easily do it: https://github.com/allenai/allennlp/blob/e71618de705c7e54da325f5494c4718d50f61f58/allennlp/common/testing/test_case.py#L32

We could consider adding a way to configure this from a json file, but that's a separate issue.
