### ISSUE TITLE
How to use word embeddings in character level tagging task?

### ISSUE THREAD

**Issue by zeeshansayyed** [allenai/allennlp#3019]
I want to train a character level sequence tagger. This is similar to a POS tagger or a NER system, in the sense that every token gets assigned a tag from a small set of valid tags, except that the tokens are characters instead of words. Note that this is more constrained than a general character level seq2seq problem as every character gets assigned a single tag.

In the dataset reader, I used a character tokenizer to produce the tokens. Furthermore, I used a SingleIdTokenIndexer and a simple embedding layer to get a basic system running. How can I add pre-trained word embeddings to each character embedding?

For instance, consider the sentence: "What are you doing ?". Consider that every character i.e. 'W', 'h','a' and so on until '?' is mapped to a corresponding tag. Now for every character, I not only want to have embedding for that character itself but also concatenate the corresponding word embedding to it. For instance:

W -> embedding for W+ word embedding for what
h -> embedding for h + word embedding for what
...
g -> embedding for g + word embedding for doing.

I am very new to allennlp and would really appreciate pointers in the right direction.

Thanks
Zeeshan

**Comment by matt-gardner** [comment]
Thanks for the good description of what you're trying to do, it makes it easy to answer the question.

Basically, you'll need your `Token` object to know about both the character and the word.  You'll have to customize things a bit, by making a new tokenizer that returns character tokens, but also puts a field on those tokens called `word` or something, that you can access later in the `TextField`.  Then you need a new `TokenIndexer` that behaves similarly to the `PosTagIndexer`, that just reads the new field that you added to the `Token`.  After you do those two, everything else should just work - use your new tokenizer, include your new `TokenIndexer` alongside the `SingleIdTokenIndexer` (using separate namespaces), and have two `TokenEmbedders` in your `TextFieldEmbedder`.

Let me know if any part of this doesn't make sense.

**Comment by zeeshansayyed** [comment]
Thank you very much @matt-gardner 

I think I understand your answer well. I will try to implement it and update this thread if I run into issues.

Appreciate the quick response.

**Comment by zeeshansayyed** [comment]
@matt-gardner I was able to get this working. I would like to point out that I implemented my own version `Token` class called `CharToken` initially along with a new Tokenizer and TokenIndexer.  But then I ran into issues because `TextField` refused to accept a list of `CharTokens`. So I ended up using the original token class and storing my word field under tag_ and pairing it up with `PosTagIndexer` instead of my custom one. 

While this works, it certainly isn't ideal.

Thank you for your help. I would love any recommendations that you might have in cleaning up my code.

Thanks

**Comment by matt-gardner** [comment]
You ran into [this error](https://github.com/allenai/allennlp/blob/9e52e0f68816a2cf3ead375e3233e72fe74db6d3/allennlp/data/fields/text_field.py#L45-L47)?  If that's the case, you could make your `CharToken` be a subclass of our `Token`, and then the original idea should still work, I think.

**Comment by schmmd** [comment]
Closing as the original question is answered, but please follow up if you have additional questions.

**Comment by zeeshansayyed** [comment]
Thanks a lot @matt-gardner 
I have one more related question. What if I want to use a contextual word embedding for my words? Let's say either Elmo or Bert? How should I change the token indexer for this case? For something like fastText embeddings, I have defined the token_indexers and token_embedders in my config file as follows:
```json
        'source_token_indexers': {
            'source_chars': {
                'type': 'single_id',
                'namespace': 'source_chars'
            },
            'source_words': {
                'type': 'pos_tag',
                'namespace': 'source_words'
            }
        },
...
        "text_field_embedder": {
            'type': 'basic',
            "token_embedders": {
                "source_chars": {
                    "type": "embedding",
                    "embedding_dim": char_embedding_dim,
                    'vocab_namespace': 'source_chars'
                },

                "source_words": {
                    "type": "embedding",
                    'pretrained_file': 'embeddings/cc.ar.300.vec.gz',
                    "embedding_dim": word_embedding_dim,
                    'vocab_namespace': 'source_words',
                    'trainable': false
                }
            }
        },
```

**Comment by matt-gardner** [comment]
See [here](https://github.com/allenai/allennlp/blob/master/tutorials/how_to/elmo.md).  Also, there's a very early (still very ugly, but probably functional) tutorial that I wrote about all of this [here](https://allennlp-course.apps.allenai.org/chapter03).  See particularly sections 5 and 10, which show how the contextualized embedders work.  It doesn't talk about setting it up in config files, but translating from the objects you see in that tutorial to instantiating from a config file should hopefully not be too bad.

**Comment by zeeshansayyed** [comment]
@matt-gardner Thank you for the links. The tutorial was really very helpful. I wish I had found it earlier. 

Actually, I still have one question which didn't get answered directly in the tutorial. Since I am working at character level token here, I cannot use WordTokenizer. Both Elmo and Bert assume that one is using WordTokenizer. Even though Bert requires subword tokens, it does that internally.

So what would be the shortest solution to this problem: Using Elmo or Bert with a CharacterTokenizer?

**Comment by matt-gardner** [comment]
In your model, you'll have a sequence of characters, because you're tokenizing based on characters.  ELMo gives one vector per word, and BERT gives one vector per wordpiece.  How do you want to distribute these vectors back to the characters?  Have them be identical for identical for characters in the same word / wordpiece?

**Comment by zeeshansayyed** [comment]
Yes. I want them to be identical for all the characters in the same word/wordpiece. The way I see this is that they will augment the existing character embeddings with word/wordpiece level information.

**Comment by matt-gardner** [comment]
Here's a suggestion.  I'll give it for ELMo, but the same thing applies for BERT.

Write a `TokenIndexer` that takes your tokens and outputs a list of ELMo tensors.  You probably want to actually instantiate and call an elmo indexer in here.  You just need to additionally output a mapping from characters to word indices.  So those two things (the original ELMo indexer outputs and the character -> word mapping) are the outputs of this indexer.  Then you write a `TokenEmbedder` that takes these two things as input, runs the original `ElmoEmbedder` on the regular output, then repeats it, or does an `index_select`, or whatever, to get the vectors out as you want.

It's _possible_ that you could write one pair of classes that will work with both ELMo and BERT, just wrapping around the characters, providing a mapping, and doing the repeat / index_select in the model.  It might be tricky to do both at the same time, because they tokenize things differently...
