### ISSUE TITLE
Prepare Text2SQL training data for my own use case

### ISSUE THREAD

**Issue by Sharathmk99** [allenai/allennlp#3022]
**Question**
* Is there a way to train Text2SQL model for my own data set. For demo ATIS is used. How can i retrain or add my domain data to it. Any example to use python API for text2sql.

**Comment by Sharathmk99** [comment]
How can train model using ATIS data only? Then I can modify for my data. I'm not getting any hint how to train model for TextToSql?

**Comment by matt-gardner** [comment]
For training an ATIS model, first look at our tutorials for how to train _any_ model in allennlp.  Then use [this configuration file](https://github.com/allenai/allennlp/blob/master/training_config/atis_train.jsonnet).  For a different dataset like Spider, you can see here: https://github.com/benbogin/spider-schema-gnn.

**Comment by Sharathmk99** [comment]
Thank you @matt-gardner for the reply. I'll check the tutorial to train allen nlp model first. Can i use ATIS data from below link directly to train model?
https://github.com/jkkummerfeld/text2sql-data/tree/master/data

**Comment by matt-gardner** [comment]
The training config I linked to has a link to the data.

**Comment by Sharathmk99** [comment]
I can see only py files. For getting data do I need to contact the owner is that repo? 
https://github.com/lil-lab/atis/

**Comment by Sharathmk99** [comment]
@matt-gardner i was successfully trained sample mode in AllenNLP. Now i wanted to train some model in Text2SQL. Can you please to get some data link to train the same?

**Comment by matt-gardner** [comment]
I would recommend starting with data that you want to use.  I don't know what you're trying to do, so I can't really recommend any data for you.

**Comment by Sharathmk99** [comment]
Hi @matt-garden I'm trying to first build with any data because I don't know how data structure should look like. So first want to try with any simple dataset so that I can understand data structure and flow of data. Then I can think of structuring my own data. If you can help me to just build model with any data that will help me to understand the way model is built. Thank you for your time.

**Comment by matt-gardner** [comment]
The sample data should be enough to understand the data structures and how the model works.  It's probably _easier_ to use the test fixtures to understand this than it is to look at a full dataset.

**Comment by Sharathmk99** [comment]
Hi @matt-gardner sorry for asking very basic questions. When you tell test fixtures is there any example? Any link to get sample data? So that I can create some documentation for new guys to understand how to use model?

My goal is to build very simple example let's say, What is my total expense on February? I'll have only one table to get this data. So that this can return the query as SELECT SUM(EXPENSES) FROM EXPENSES WHERE USERID = 1.


Thank you for your patience and time.

**Comment by matt-gardner** [comment]
Have a look at our [tests directory](https://github.com/allenai/allennlp/tree/master/allennlp/tests).  In there, you can see a [test for the ATIS model](https://github.com/allenai/allennlp/blob/master/allennlp/tests/models/atis_semantic_parser_test.py), which references a toy [experiment configuration](https://github.com/allenai/allennlp/blob/master/allennlp/tests/fixtures/semantic_parsing/atis/experiment.json) and some toy [data](https://github.com/allenai/allennlp/blob/master/allennlp/tests/fixtures/data/atis/sample.json).  Stepping through that test as it runs would probably be helpful in understanding what's going on with the data processing.

**Comment by schmmd** [comment]
Closing, as the original question was answered.  Please follow up if you have more questions though!
