### ISSUE TITLE
a configure file check feature is needed (maybe not needed)

### ISSUE THREAD

**Issue by zxr445116086** [allenai/allennlp#3028]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when the AllenNLP model load all the training file and tell me that some parameter of my model is Extra Parameter or something else. It waste a lot of time.

**Describe the solution you'd like**
A configure file check feature, that can tell me the problem of my configure file in advance.

**Describe alternatives you've considered**
**create a smaller dataset to test the work flow.**

**Additional context**

**Comment by matt-gardner** [comment]
Yes, I agree; this is a duplicate of #1536. Also, I would strongly recommend using small test fixtures as you're developing your model and trying things out (looks through our tests to see what I mean here).  It should take less than a second to get to the failure if you're using small test fixtures.  Then, once everything works with the fixture, you can switch to real data and make the numbers in your config file bigger.
