### ISSUE TITLE
BiDAF training data - QA model

### ISSUE THREAD

**Issue by Swathygsb** [allenai/allennlp#3031]
How to train my data along with Squad Data for BiDAF model (QA / Reading comprehension model) ?

**Comment by schmmd** [comment]
Information for training BiDAF can be found on this page: https://allennlp.org/models

**Comment by Swathygsb** [comment]
*Is BiDAF model case sensitive? I am getting different answers for upper and lower case words?
*Is it possible to use BERT for SQuAD?

**Comment by schmmd** [comment]
I would expect BiDAF to be case sensitive although I don't know for sure.  It's certainly possible to use BERT on the SQuAD dataset.  We have a BiDAF model that uses ELMo for the language model.

https://github.com/allenai/allennlp/blob/master/training_config/bidaf_elmo.jsonnet

**Comment by yyHaker** [comment]
> I would expect BiDAF to be case sensitive although I don't know for sure. It's certainly possible to use BERT on the SQuAD dataset. We have a BiDAF model that uses ELMo for the language model.
> 
> https://github.com/allenai/allennlp/blob/master/training_config/bidaf_elmo.jsonnet

Hi, can you give a example for just use BERT for QA tasks?

**Comment by matt-gardner** [comment]
See #3447.  There's no need to ask the same question in two separate issues.
