### ISSUE TITLE
BasicTextFieldEmbedder.allow_unmatched_keys should default to `True` if embedder_to_indexer_map is provided

### ISSUE THREAD

**Issue by joelgrus** [allenai/allennlp#3034]
99.9% of the time, if you supply `embedder_to_indexer_map` you want to allow unmatched keys, so why not just make it default to True if that's the case so you don't have to remember to specify it manually?

**Comment by matt-gardner** [comment]
We're going to remove this entirely (see #3304), so closing this issue.
