### ISSUE TITLE
Is allennlp only saving the parameters being fine-tuned for BERT?

### ISSUE THREAD

**Issue by XinliYu** [allenai/allennlp#3037]
I am fine-tuning BERT-based model, only with the top layer. I found the model_state_epoch*.th files generated by allennlp have size around 400MB. I have several questions:

1. Is allennlp only saving the tuned-parameters for top layer? 
2. If I would like to load the model later, should I first load the pre-trained model, and then load the saved model states?
3. If I am fine-tuning all layers of BERT, will allennlp save the entire BERT?

Many thanks!

**Comment by schmmd** [comment]
@joelgrus do you know how to answer this?

**Comment by joelgrus** [comment]
as long as BERT is part of your model, all of its weights should be saved, whether they're frozen or not.

the bert-base models are only about 400MB in size

**Comment by XinliYu** [comment]
Good. Thanks! I test it, it does the job and saves all weights!
