### ISSUE TITLE
In EndpointSpanExtractor when span_width_embedding is not None, the span_indices_mask is not considered.

### ISSUE THREAD

**Issue by cjopengler** [allenai/allennlp#3038]
**Describe the bug**
EndpointSpanExtractor.forward Bug code segment.
```
 if self._span_width_embedding is not None:
            # Embed the span widths and concatenate to the rest of the representations.
            if self._bucket_widths:
                span_widths = util.bucket_values(span_ends - span_starts,
                                                 num_total_buckets=self._num_width_embeddings)
            else:
                span_widths = span_ends - span_starts

            span_width_embeddings = self._span_width_embedding(span_widths)
            return torch.cat([combined_tensors, span_width_embeddings], -1)

if span_indices_mask is not None:
    return combined_tensors * span_indices_mask.unsqueeze(-1).float()  
```
See `return torch.cat([combined_tensors, span_width_embeddings], -1)`,  in this code segment, it dose not consider `span_indices_mask` is not None. This should be as below:

`return torch.cat([combined_tensors, span_width_embeddings], -1)`
fixed  as below. 
`combined_tensors = torch.cat([combined_tensors, span_width_embeddings], -1)`

Here not `return torch.cat([combined_tensors, span_width_embeddings], -1)`, just use `combined_tensors = torch.cat([combined_tensors, span_width_embeddings], -1)`. Then, next span_indices_mask will effect on combined_tensors

**Expected behavior**

**System (please complete the following information):**
- AllenNLP version: [e.g. v0.8.4, or "I installed from master"]

**Comment by schmmd** [comment]
https://github.com/allenai/allennlp/blob/master/allennlp/modules/span_extractors/endpoint_span_extractor.py#L141

**Comment by schmmd** [comment]
@cjopengler you are recommending https://github.com/allenai/allennlp/pull/3042?

**Comment by cjopengler** [comment]
> @cjopengler you are recommending #3042?

Yes. Thanks.
