### ISSUE TITLE
BidirectionalEndpointSpanExtractor.forward "exclusive_span_ends > sequence_lengths.unsqueeze(-1)" seems bug.

### ISSUE THREAD

**Issue by cjopengler** [allenai/allennlp#3039]
**Describe the bug**
BidirectionalEndpointSpanExtractor.forward 

```
 if (exclusive_span_starts < 0).any() or (exclusive_span_ends > sequence_lengths.unsqueeze(-1)).any():
            raise ValueError(f"Adjusted span indices must lie inside the length of the sequence tensor, "
                             f"but found: exclusive_span_starts: {exclusive_span_starts}, "
                             f"exclusive_span_ends: {exclusive_span_ends} for a sequence tensor with lengths "
                             f"{sequence_lengths}.")
```

```(exclusive_span_ends > sequence_lengths.unsqueeze(-1)``` should be fixed as ```(exclusive_span_ends >= sequence_lengths.unsqueeze(-1)```.  Because, when ```exclusive_span_ends == sequence_lengths``` will be out of boundary.

**Comment by schmmd** [comment]
@cjopengler makes sense to me.  I created https://github.com/allenai/allennlp/pull/3043, please let me know if that looks good.

In general, pull requests are very welcome.

**Comment by cjopengler** [comment]
> @cjopengler makes sense to me. I created #3043, please let me know if that looks good.
> 
> In general, pull requests are very welcome.

Yeah. Thanks for your encourage. If I got other, I will try to pull requests.
