### ISSUE TITLE
How to visualize generated word embeddings with Elmo in Tensorboard?

### ISSUE THREAD

**Issue by tanmaypandey7** [allenai/allennlp#3046]
Basically the title. I have a dataframe which contains a column processed_text where all my text is stored. I have supplied the text to tensorflow  like this:

```
elmo = hub.Module("https://tfhub.dev/google/elmo/2", trainable=False)


def elmo_vectors(x):
  embeddings = elmo(x.tolist(), signature="default", as_dict="True")["elmo"]
  
  with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    sess.run(tf.tables_initializer())
    
    return sess.run(tf.reduce_mean(embeddings,1))

list_df_processed = [df_processed[i:i+10] for i in range(0,df_processed.shape[0],10)]

elmo_vec_list = [elmo_vectors(x['processed_text']) for x in list_df_processed]

elmo_df_new = np.concatenate(elmo_df, axis = 0)

# Now i am saving it in the form of pickle file
# save elmo_train_new
pickle_out = open("elmo_train_03032019.pickle","wb")
pickle.dump(elmo_df_new, pickle_out)
pickle_out.close() 
```

Basically what I want to do is get the word embeddings and visualize them on tensorboard. I have read that I need to make an embeddings.tsv and metadata.tsv for that. But I lack the knowledge to do so. Can someone help me out here?

**Comment by shtratos** [comment]
@tanmaypandey7 you might want to have a look at this tutorial:
https://github.com/PrashantRanjan09/Elmo-Tutorial/blob/master/Elmo_tutorial.ipynb

It goes through visualisation of Elmo embeddings via Tensorboard.

**Comment by schmmd** [comment]
@tanmaypandey7 was the tutorial helpful for answering your original question?

**Comment by tanmaypandey7** [comment]
This takes too long to make embeddings like 53 seconds, the one I was using did it in 0.5 seconds. I cross checked and it looked right to me. Else everything looks good, although it might need some code review.
I have to train the model on Google Cloud currently, but the focus is currently on other project.
 
Will get back to this later.

**Comment by schmmd** [comment]
Closing--as the question has more to do with Tensorboard than AllenNLP and we've already had a couple of pointers.
