### ISSUE TITLE
Porting allennlp to Power (ppc64le),  TestLinearSimilarityFunction.test_forward_does_a_weighted_product is failing

### ISSUE THREAD

**Issue by seth-priya** [allenai/allennlp#3048]
Hi,

**System (please complete the following information):**
 - OS: RHEL 7.6, Power 8 (GPU enabled), ppc64le
 - Python version: 3.6.8
 - AllenNLP version:  v0.8.4, "I installed from master"
 - PyTorch version: (if you installed it yourself) 1.0.1 available for ppc64le at https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda/linux-ppc64le

**Question**
I am attempting to port allennlp to Power 8 (ppc64le) architecture and have been able to build it successfully - both the master as well as version v0.8.4. The only major issue was that I had to explicitly install pytorch from https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda/linux-ppc64le
and spacy from https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda/linux-ppc64le, the version of spacy being slightly older 2.0.12, I had to update the requirements.txt file in allennlp accordingly.

Post this change, the build completed.

The test execution results were quite positive, all but one test passed for v0.8.4
= 1 failed, 1370 passed, 21 skipped, 28 warnings in 582.76 seconds =

I am trying to investigate the test failure, but need some help / pointers on which part of the code to focus on. Could this issue be related to pytorch?

The logs show
________________________________________________ TestLinearSimilarityFunction.test_forward_does_a_weighted_product ___________________________________________________

self = <allennlp.tests.modules.similarity_functions.linear_test.TestLinearSimilarityFunction testMethod=test_forward_does_a_weighted_product>

    def test_forward_does_a_weighted_product(self):
        linear = LinearSimilarity(3, 1, combination='x,y')
        linear._weight_vector = Parameter(torch.FloatTensor([-.3, .5, 2.0, -1.0]))
        linear._bias = Parameter(torch.FloatTensor([.1]))
        a_vectors = torch.FloatTensor([[[1, 1, 1], [-1, -1, 0]]])
        b_vectors = torch.FloatTensor([[[0], [1]]])
        result = linear(a_vectors, b_vectors).data.numpy()
        assert result.shape == (1, 2,)
>       assert_almost_equal(result, [[2.3, -1.1]])
E       AssertionError:
E       Arrays are not almost equal to 7 decimals
E
E       (mismatch 50.0%)
E        x: array([[ 2.2999997, -1.0999999]], dtype=float32)
E        y: array([[ 2.3, -1.1]])

allennlp/tests/modules/similarity_functions/linear_test.py:27: AssertionError
-------------------------------------------------------------------------- Captured log call ---------------------------------------------------------------------------
02:09:28 - INFO - allennlp.common.checks - Pytorch version: 1.0.1
02:09:28 - DEBUG - allennlp.common.registrable - instantiating registered subclass linear of <class 'allennlp.nn.activations.Activation'>

Any pointers would be of great help, thank you!!

**Comment by matt-gardner** [comment]
If you look at the array values, apparently your architecture thinks they are equal to 6 decimals instead of 7.  You just need to change the threshold on that check, and the test should pass.

**Comment by seth-priya** [comment]
@matt-gardner thanks for the quick help. Since I am new to this source code , just confirming - what you are suggesting is to modify the threshold value for ppc64le for this specific test case (and which I assume is defined in the test itself)? 

Thank you!!

**Comment by matt-gardner** [comment]
Yeah, it's something like adding `decimal=6` to the assert (the various asserts use different argument names, not sure which one is needed here).

**Comment by schmmd** [comment]
Closing, as I think we answered the original question.  Please follow up if you have more!

**Comment by seth-priya** [comment]
Thanks @matt-gardner the test passed with the suggested change!

diff --git a/allennlp/tests/modules/similarity_functions/linear_test.py b/allennlp/tests/modules/similarity_functions/linear_test.py
index dd5b88cd..3ff90fae 100644
--- a/allennlp/tests/modules/similarity_functions/linear_test.py
+++ b/allennlp/tests/modules/similarity_functions/linear_test.py
@@ -24,7 +24,7 @@ class TestLinearSimilarityFunction(AllenNlpTestCase):
         b_vectors = torch.FloatTensor([[[0], [1]]])
         result = linear(a_vectors, b_vectors).data.numpy()
         assert result.shape == (1, 2,)
-        assert_almost_equal(result, [[2.3, -1.1]])
+        assert_almost_equal(result, [[2.3, -1.1]], decimal=6)

     def test_forward_works_with_higher_order_tensors(self):
         linear = LinearSimilarity(7, 7, combination='x,y')
