### ISSUE TITLE
ListField generates 'KeyError' when using BucketIterator

### ISSUE THREAD

**Issue by derosejf** [allenai/allennlp#3049]
**System:**
 - OS: Ubuntu 18.04
 - Python version: 3.6.8
 - AllenNLP version: 0.8.4
 - PyTorch version: 1.1.0

**Question**
I have been using the allennlp pipeline to train a model that processes sequences of sentences (like multiple choice). I have been using the BucketIterator and am encountering a weird KeyError when trying to bundle multiple TextFields into a ListField. When operating on only TextFields, I did not encounter this problem. My input to my model is of the form [batch, num_sents, seq_length].

I have tried to convert my Instance directly to a tensor using the `as_tensor_dict()` function (no iterator). This works as desired producing a tensor of dimension [num_sent, seq_length]. However, when using the BucketIterator, it seems every key throws an error when passed to `sorting_keys` argument. I even extracted the keys from the TextFields, but none of these work when they are compared against a ListField.

I would prefer to keep using the BucketIterator as it nicely batches input tensors.

Example of problem:
```
## predefined token_indexer and vocab
tokens = [Token('some') for _ in range(10)]
text = TextField(tokens, token_indexer)
text.index(vocab)
inst = Instance({'tokens' : ListField([text, text])})

iterator = BucketIterator(
    batch_size = 1, # test with size 1
    sorting_keys = [('tokens', 'num_tokens')] ## <- this is where my question is
)
iterator.index_with(vocab)

inst.as_tensor_dict() ## produces desired output
next(iter(iterator([inst]))) ## KeyError: 'num_tokens'
```

Either there is something I am not understanding with how to pass keys to a ListField or ListFields have their own set of keys. It is also possible ListFields keys are not properly aggregated from their contents. Any solution would be greatly appreciated.

**Comment by matt-gardner** [comment]
To figure out what keys to use, you could call `instance.get_padding_lengths()`.  This will tell you all of the keys that exist in the `Instance`, which you can then pick between to pass to the bucket iterator.

To reason about this without calling `instance.get_padding_fields()`, you can see [here](https://github.com/allenai/allennlp/blob/64d16acffe99fe2beebd0e3629abec297005b24d/allennlp/data/fields/list_field.py#L55-L57) that a `ListField` adds a `num_fields` padding key, and prepends `list_` to all internal keys.  I'd guess you want something like `[('tokens', 'num_fields'), ('tokens', 'list_num_tokens')]` as your sorting keys (sorting first by number of items in the list, then by number of tokens in the text).

**Comment by derosejf** [comment]
Ah I totally missed that line of source code that prepends 'list_' to all of the keys. That line explains all of my problems. Thanks so much.
