### ISSUE TITLE
How to index labels when using BERT?

### ISSUE THREAD

**Issue by XinliYu** [allenai/allennlp#3050]
I am using BERT as the token encoder, and then do sequence tagging. The original labels are strings.

I am puzzled how to do the label indexing in this case. By instruction, we need to pass empty vocabulary to BERT indexer; however, for the labels I must build an vocabulary first, and use SingleIdTokenIndexer. I am not sure how to correctly achieve this. We can assume we only have 'tokens' and 'labels' in the instance where 'labels' is a SequenceLabelField. Any quick example is very much appreciated!

**Comment by schmmd** [comment]
@joelgrus are you able to help out here?  I don't see a good example in our `training_configs`.

**Comment by joelgrus** [comment]
it's not that the vocabulary has to be empty, it's that it should be empty *in the namespace where BERT tokens will live*. It can be non-empty in other namespaces, like "labels". So just handle labels the same way you'd handle them in a non-BERT model, and it should be fine.

(note that if you're using a LabelField or a SequenceLabel field, you don't need a token indexer, you get essentially "single id" behavior automatically)

**Comment by XinliYu** [comment]
Thanks a lot! @joelgrus Are the BERT tokens live in 'tokens' namespace?

**Comment by joelgrus** [comment]
it looks like they're hardcoded to go into a "bert" namespace:

https://github.com/allenai/allennlp/blob/master/allennlp/data/token_indexers/wordpiece_indexer.py#L348

**Comment by cemilcengiz** [comment]
> it looks like they're hardcoded to go into a "bert" namespace:
> 
> https://github.com/allenai/allennlp/blob/master/allennlp/data/token_indexers/wordpiece_indexer.py#L348

If I am not wrong, this makes it impossible to train a multi-task model by using BERT as the shared encoder if the tasks include different labels (which is generally what you expect from a multi-task setting).

**Comment by matt-gardner** [comment]
No, they'd all get encoded the same.  I'm not sure what scenario you're thinking of where you're encoding _labels_ with BERT - basically just language modeling or translation...?  But even then, I think having a single namespace for BERT is the right thing.
