### ISSUE TITLE
BucketIterator repeating data within the same epoch (skipping data)

### ISSUE THREAD

**Issue by derosejf** [allenai/allennlp#3059]
***System:***
- OS: Ubuntu 18.04
- Python version: 3.6.8
- AllenNLP version: 0.8.4
- PyTorch version: 1.1.0

***Question***
I recently noticed that when passing a BucketIterator a list of Instances, it does not use all of the data in the list when looping for a single epoch. For example, pass 20 instances with batch size of 2, the iterator will return 10 batches but not all of the instances occur in these 10 batches. I have provided code snippets resembling mine below.

```
## Some read in instances of text with 20 unique ids -> data
iterator_1 = BucketIterator(
    batch_size = 1, # test with size 1
    sorting_keys = [('tokens', 'num_tokens')]
)
iterator_1.index_with(vocab)

ids_1 = []
for _ in range(20):
    a = next(iter(iterator_1(data)))
    ids_1.append(a['id'])
len(np.unique(np.array(ids_1))) ## returns 12

## ASSUME DATA IS REREAD HERE

iterator_2 = BucketIterator(
    batch_size = 2, # test with size 2
    sorting_keys = [('tokens', 'num_tokens')]
)
iterator_2.index_with(vocab)

ids_2 = []
for _ in range(10):
    a = next(iter(iterator_2(data)))
    ids_2.append(a['id'])
len(np.unique(np.array(ids_2))) ## returns 13
```

Is this intended behavior or am I using this incorrectly?

**Comment by schmmd** [comment]
@derosejf is it a problem that you call `iter()` for each iteration in your for loop?  I worry you are creating a new iterator for each iteration and that for each new iterator the order is not deterministic so you don't see all the elements.

**Comment by schmmd** [comment]
Closing--as we think that's the underlying issue.
