### ISSUE TITLE
docker build should cache the latest models

### ISSUE THREAD

**Issue by joelgrus** [allenai/allennlp#306]
right now they have to be downloaded every time you start up a docker container

**Comment by joelgrus** [comment]
could be as simple as

```
python -c "from allennlp.commands.serve import DEFAULT_CONFIG
from allennlp.common.file_utils import cached_path
for url in DEFAULT_CONFIG.values(): 
    print(cached_path(url))"
```

but maybe we want to wrap that in a script

**Comment by matt-gardner** [comment]
I think this should be an optional argument to the dockerfile, not something that's done every time it's built.  Then when building the demo docker image, we can pass that argument.  It'd be unfortunate to have to do this every time I run a beaker experiment, e.g.
