### ISSUE TITLE
Can I config oov token and padding token for each individual namespace?

### ISSUE THREAD

**Issue by XinliYu** [allenai/allennlp#3061]
For example, I would like to set 'O' as the 'oov' token for `ner_labels` namespace, so that unseen NER-labels can be automatically mapped to 'O'. And I would like to disable the padding token for the `ner_labels` sapce. Meanwhile, I would like to keep the default settings for the `tokens` namespace.

I tried to change the `non_padded_namespaces` option of the `from_instances` method, it adds @@UNKNOWN@@ and @@PADDING@@ to the label namespaces; but I want to change the oov token and disable the padding token.

**Comment by matt-gardner** [comment]
This is something that you'll need to write your own code for.  You have a couple of options:

1. Run `make-vocab` or something similar and pre-compute a vocabulary, then load the vocabulary in your dataset reader and do the mapping to the `O` token yourself.  This is probably what I would recommend doing.  We don't have (and won't add) a mechanism to change the OOV token.
2. Hack the `Vocabulary` (either by modifying your local source, or by subclassing it) to change the OOV token, and remove the padding token.

**Comment by XinliYu** [comment]
@matt-gardner Thanks! It works!
