### ISSUE TITLE
Is there a function to balance samples?

### ISSUE THREAD

**Issue by xmzzyo** [allenai/allennlp#3062]
Please first search our GitHub repository for similar questions.  If you don't find a similar example you can use the following template:

**System (please complete the following information):**
 - OS: [Ubuntu]
 - Python version: [3.6]
 - AllenNLP version: [ "I installed from master"]

**Question**

* I have an unbalanced dataset which has 2 classes, and its label ratio is 10:1, but I did not find some functions to balance data in data iterator or somewhere else. Could you please give me some advice to deal with unbalanced dataset in Allennlp?

**Comment by matt-gardner** [comment]
The easiest way to handle this is to do the balancing yourself in your dataset reader.  That is, you might read all of your instances in memory and cache them, and then at every call to `_read()` you do a (new) even sampling of your two classes.

You could also do this with a custom data iterator that you write specifically for your problem, that looks at the instances that come in and only keeps some of them, depending on the label.  But it seems overly convoluted to do it that way, when you can just do the sampling in your dataset reader, and have all of that logic contained in one place.

**Comment by joelgrus** [comment]
closing, please let us know if you run into any further issues
