### ISSUE TITLE
Creating a tree from constituency parser results

### ISSUE THREAD

**Issue by LivingScripts** [allenai/allennlp#3063]
**System:**
 - OS: Ubuntu 18.04
 - Python version: 3.6.8
 - AllenNLP version: 0.8.4

I get a string a that represents the constituency tree generated by the model, the problem is, it is hard to traverse, is there some way to create a tree out of it, possibly a `nltk.tree`?

this is what I'm doing:
```python
model = PretrainedModel('models/elmo-constituency-parser-2018.03.14.tar.gz', 'constituency-parser')
p = model.predictor().predict(sentence="some sentence")
print(p['trees']))
```

Thanks.

**Comment by DeNeutoy** [comment]
Hi, you should be able to use `Tree.fromstring()` from `nltk` to construct it.
