### ISSUE TITLE
Creating a generic wrapper for meta-learning

### ISSUE THREAD

**Issue by isaacmg** [allenai/allennlp#3064]
Hello, I'm researching applying meta-learning to NLP and I have a few questions on how to make it work with AllenNLP. I know that probably the simplest option is to design my own base class and base data loader for whatever model I want to use. However, since the majority of these techniques (MAML, Reptile, etc) "should" work with any underlying base model. I'm wondering if there is a way to design a generic wrapper meta-learning class and meta-data loader that I could utilize to wrap any base model (and data reader). Then the meta-data loader would just be supplied with a list of datasets, dataset specific preprocessing functions, number of shots per inner loop, etc as parameters. The meta-learning class would implement a standard model agnostic based approach and take an arbitrary base model.

 I’m guessing this will involve overwriting trainer in some manner or is there a better way? Also can additional custom parameters easily be added to the JSONNet files? Would creating a MetaDatasetReader(Registrable) make sense or is there an easy way to incorporate this functionality?  Finally, altogether do you think this feasible given the way AllenNLP is currently written? Or do you think it would be best to create specific data loaders and model classes for each base model?

Thanks for your insight.

**Comment by joelgrus** [comment]
almost certainly you will have to implement your own `Trainer` subclass, and then it can take whatever parameters you want (multiple datasets, etc).

your life will be easiest if the parameters in the jsonnet files correspond to the constructor parameters for your trainer (or other object). otherwise your objects will need a custom `from_params` method that translates the jsonnet into constructor parameters. 

my guess is that creating e.g. a `MetaTrainer(Trainer)` is the right place to begin, I don't see why you'd need custom DatasetReaders for this, but I guess it depends on the details of what you're doing

**Comment by isaacmg** [comment]
Thanks I will get started with the `MetaTrainer`. The reason for custom DatasetReaders I was primarily envisioning  as using it to maintain the different tasks splits and make sure to only give the model samples from two (or whatever number specified) tasks of the total tasks in the meta dataset per batch. But as you suggested it look like creating a MetaTrainer that takes a list of DatasetReaders then samples from two might accomplish the same thing in a better manner.

**Comment by joelgrus** [comment]
closing, let us know if you run into any problems

**Comment by isaacmg** [comment]
@joelgrus  What would be the easiest way to create a batch from multiple data iterators? Right now in my overriding of `def _train_epoch` I'm maintaining a list of data iterators from each dataset. However, I need to sample n items from each data iterator  and then combine them to create a mini-batch (each batch will contain n items from each of the t tasks). Or is there a better way to do this altogether? So for instance now my code looks like 

```
for i, trainer in enumerate(self.train_data):
            raw_train_generator = self.iterator(trainer,
                                            num_epochs=1,
                                            shuffle=self.shuffle)
            train_generators.append(lazy_groups_of(raw_train_generator, num_gpus))

for i in range(0, self.meta_batches):
            # inner batches 
            random.shuffle(train_generators)
            tasks = train_generators[0:self.tasks_per_batch]
            for in range(0, self.inner_steps):
                ##TODO  combine n examples from each data iterator to form inner batch

```

Thanks.

**Comment by matt-gardner** [comment]
Once a group of instances comes out of a `DataIterator`, it is already batched and tensors have been created, and it's not easy to do any kind of re-batching.  I now see why you suggested having a custom dataset reader.  Conceptually, this interleaving operation probably fits better in something called a `DataIterator`, but the way the code is set up, it's a lot easier to do it through a `DatasetReader`.  You either need to do something crazy with a `DataIterator` that takes in `k` separate streams and combines them, or you need to write your own `DatasetReader` that does the same thing.  The `DataIterator's` job is to batch things up efficiently, but I'm not sure that's feasible for you, given that you want to keep the batch diversified for each task.  You might be better off writing a `DatasetReader` that takes a list of other `DatasetReaders`, interleaves them, and does its own batching.  Then you can use the [`PassThroughIterator`](https://github.com/allenai/allennlp/pull/3015) (code [here](https://github.com/allenai/allennlp/blob/master/allennlp/data/iterators/pass_through_iterator.py)).

**Comment by isaacmg** [comment]
What is the best way to substitute my MetaTrainer for the regular train in the jsonnet files? Is it as simple as replacing "trainer" in the JSON with "metatrainer." Also I was wondering is it possible to run a single unit test file without running all the others? I want to create metatrainer_test.py to incrementally test functionality but it is taking too long to run all the tests every time. Is there a simple way to do this?

**Comment by joelgrus** [comment]
just as with any other custom class, you'll need to 

1. decorate your trainer with `@Trainer.register('metatrainer')` (or whatever)
2. in the "trainer" part of the JSON, do `"type": "metatrainer"` along with whatever other parameters it needs to be constructed from_params
3. if you're doing `allennlp train` then `--include-package` the module with your custom trainer class

--

for the second you can do either

`pytest /path/to/test/file.py` to run a single file

or

`pytest -k [regex]` to only run tests that match a certain regular expression

**Comment by isaacmg** [comment]
Okay thanks. Regarding the unit test I tried `pytest meta_trainer_test.py` However I got this weird collecting error I'm not sure what the issue is.
```
________ ERROR collecting allennlp/tests/training/meta_trainer_test.py _________
allennlp/tests/training/meta_trainer_test.py:11: in <module>
    from allennlp.common.checks import ConfigurationError
allennlp/common/__init__.py:1: in <module>
    from allennlp.common.from_params import FromParams
allennlp/common/from_params.py:48: in <module>
    from allennlp.common.params import Params
allennlp/common/params.py:8: in <module>
    from collections import MutableMapping, OrderedDict
<frozen importlib._bootstrap>:1032: in _handle_fromlist
    ???
/anaconda3/lib/python3.7/collections/__init__.py:52: in __getattr__
    DeprecationWarning, stacklevel=2)
E   DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
===Flaky Test Report===
```

**Comment by joelgrus** [comment]
that issue is unrelated to what you're doing, and I'll open a separate issue for it.

in the meantime, you should be able to workaround by commenting out

https://github.com/allenai/allennlp/blob/master/pytest.ini#L25

(but don't check in the commented-out version)

**Comment by isaacmg** [comment]
Hello I'm getting the following error when running the following command  `allennlp train experiment2.jsonnet                  -s /tmp/serialization_dir                  --include-package allennlp.training.metatrainer`

```
2019-10-02 14:35:27,959 - INFO - pytorch_pretrained_bert.modeling - Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex .
2019-10-02 14:35:28,594 - INFO - pytorch_transformers.modeling_bert - Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex .
2019-10-02 14:35:28,598 - INFO - pytorch_transformers.modeling_xlnet - Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex .
2019-10-02 14:35:28,873 - INFO - allennlp.common.registrable - instantiating registered subclass relu of <class 'allennlp.nn.activations.Activation'>
2019-10-02 14:35:28,874 - INFO - allennlp.common.registrable - instantiating registered subclass relu of <class 'allennlp.nn.activations.Activation'>
2019-10-02 14:35:28,874 - INFO - allennlp.common.registrable - instantiating registered subclass relu of <class 'allennlp.nn.activations.Activation'>
2019-10-02 14:35:28,875 - INFO - allennlp.common.registrable - instantiating registered subclass relu of <class 'allennlp.nn.activations.Activation'>
2019-10-02 14:35:29,008 - INFO - allennlp.common.params - random_seed = 13370
2019-10-02 14:35:29,009 - INFO - allennlp.common.params - numpy_seed = 1337
2019-10-02 14:35:29,009 - INFO - allennlp.common.params - pytorch_seed = 133
2019-10-02 14:35:29,015 - INFO - allennlp.common.checks - Pytorch version: 1.2.0
2019-10-02 14:35:29,016 - INFO - allennlp.common.params - evaluate_on_test = False
2019-10-02 14:35:29,016 - INFO - allennlp.common.params - trainer.type = metatrainer
2019-10-02 14:35:29,016 - INFO - allennlp.common.registrable - instantiating registered subclass metatrainer of <class 'allennlp.training.trainer_base.TrainerBase'>
Traceback (most recent call last):
  File "//miniconda3/bin/allennlp", line 11, in <module>
    load_entry_point('allennlp', 'console_scripts', 'allennlp')()
  File "/Users/imckgodf/Documents/Code/allennlp/allennlp/run.py", line 18, in run
    main(prog="allennlp")
  File "/Users/imckgodf/Documents/Code/allennlp/allennlp/commands/__init__.py", line 102, in main
    args.func(args)
  File "/Users/imckgodf/Documents/Code/allennlp/allennlp/commands/train.py", line 124, in train_model_from_args
    args.cache_prefix)
  File "/Users/imckgodf/Documents/Code/allennlp/allennlp/commands/train.py", line 168, in train_model_from_file
    cache_directory, cache_prefix)
  File "/Users/imckgodf/Documents/Code/allennlp/allennlp/commands/train.py", line 246, in train_model
    trainer = TrainerBase.from_params(params, serialization_dir, recover, cache_directory, cache_prefix)
  File "/Users/imckgodf/Documents/Code/allennlp/allennlp/training/trainer_base.py", line 83, in from_params
    klass = TrainerBase.by_name(typ3)
  File "/Users/imckgodf/Documents/Code/allennlp/allennlp/common/registrable.py", line 97, in by_name
    raise ConfigurationError(f"{name} is not a registered name for {cls.__name__}. "
allennlp.common.checks.ConfigurationError: 'metatrainer is not a registered name for TrainerBase. You probably need to use the --include-package flag to load your custom code. Alternatively, you can specify your choices using fully-qualified paths, e.g. {"model": "my_module.models.MyModel"} in which case they will be automatically imported correctly.'
```
I have already decorated MetaTrain with `
@Trainer.register('metatrainer')
class MetaTrainer(Trainer):`
 So I'm not sure what this is happening.

**Comment by joelgrus** [comment]
as you can see from the error, you actually need to do `@TrainerBase.register('metatrainer')`. this is not ideal, but there are historical reasons for it.

**Comment by ha-lins** [comment]
Hi, @isaacmg 

I'm glad to see that you have investigated to implement a wrapper for meta-learning, which is exactly what I need now. I saw the corresponding repo that you forked and committed ever. Could you pls share me with your JSONNet and model file? My e-mail is shuailin97@gmail.com. 

Thanks a lot!

**Comment by isaacmg** [comment]
@ha-lins I haven't worked on this recently as I have been busy with other things. I can forward you the meta-trainer JSONNET files though.

**Comment by ha-lins** [comment]
Thanks, 

I noticed that you have ran the command `allennlp train experiment2.jsonnet -s /tmp/serialization_dir --include-package allennlp.training.metatrainer`. I wonder if the JSONNET file is ` training_config/atis_train_meta.jsonnet` according to your commit history.

**Comment by ha-lins** [comment]
I noticed that you have ever ran the command `allennlp train experiment2.jsonnet -s /tmp/serialization_dir --include-package allennlp.training.metatrainer`. I wonder if the JSONNET file is ` training_config/atis_train_meta.jsonnet` according to your [commit history](https://github.com/isaacmg/allennlp/commit/53e5447029e265fbbfcc9b3347cfe0c64975d496). If so, could you provide some instructions to finish it up and share me with the ATIS data via committing to your repo?

Thanks a lot! @isaacmg

**Comment by isaacmg** [comment]
@ha-lins I'll look into it this week and try to remember what commands I used. I believe when I left off there were still a couple problems with the tests passing. Specifically, I think I was facing an issue with MetaPieces and was working through how to fix. That stuff is actually on a different computer though so I haven't had the chance to look through it but will try to upload and commit all the relevant files.
