### ISSUE TITLE
naqanet_test fails on ppc64le

### ISSUE THREAD

**Issue by seth-priya** [allenai/allennlp#3066]
Reference #3048 for another test failure that I was seeing on the same architecture, Current test results on ppc64le are as follows
#==== 1 failed, 1362 passed, 10 skipped, 19 deselected, 24 warnings in 337.34 seconds ==
when I run allennlp test-install

**System (please complete the following information):**
 - OS: RHEL 7.6, Ubuntu 18.04, Power 8, Power 9 (GPU enabled), ppc64le
 - Python version: 3.6.8
 - AllenNLP version: v0.8.4
 - PyTorch version: (if you installed it yourself) 1.0.1 available for ppc64le at https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda/linux-ppc64le

**Question**
I am not sure how the below test was passing earlier but I am getting a consistent failure now, all the other tests are passing.

test_model_can_train_save_and_load failed (2 runs remaining out of 3).
      <class 'Exception'>
      Incorrect gradients found. See stdout for more info.
      [<TracebackEntry /home/test/allennlp/allennlp/tests/models/reading_comprehension/**naqanet_test.py**:16>, <TracebackEntry /home/test/allennlp/allennlp/common/testing/model_test_case.py:106>, <TracebackEntry /home/test/allennlp/allennlp/common/testing/model_test_case.py:198>]
test_model_can_train_save_and_load failed (1 runs remaining out of 3).
      <class 'Exception'>
      Incorrect gradients found. See stdout for more info.
      [<TracebackEntry /home/test/allennlp/allennlp/tests/models/reading_comprehension/naqanet_test.py:16>, <TracebackEntry /home/test/allennlp/allennlp/common/testing/model_test_case.py:106>, <TracebackEntry /home/test/allennlp/allennlp/common/testing/model_test_case.py:198>]
test_model_can_train_save_and_load failed; it passed 0 out of the required 1 times.
      <class 'Exception'>
      Incorrect gradients found. See stdout for more info.
      [<TracebackEntry /home/test/allennlp/allennlp/tests/models/reading_comprehension/naqanet_test.py:16>, <TracebackEntry /home/test/allennlp/allennlp/common/testing/model_test_case.py:106>, <TracebackEntry /home/test/allennlp/allennlp/common/testing/model_test_case.py:198>]

This is what I saw in the logs
Parameter: _passage_weights_predictor.bias had incorrect gradient: zeros with shape ((1,))
Parameter: _question_span_end_predictor._linear_layers.1.bias had incorrect gradient: zeros with shape ((1,))

What would be the best way to debug this? Is there any specific area of the code that I should focus on? I am assuming that again this is something architecture specific ..

Any thoughts / guidance here would be of great help .. thanks in advance!

Priya

**Comment by matt-gardner** [comment]
That test is flaky, in part because of the dropout in [the config](https://github.com/allenai/allennlp/blob/1cd21937b4b3191edecb6998122f2377edb16b3a/allennlp/tests/fixtures/naqanet/experiment.json#L74-L75) (see #2889).  Try changing all of the dropout values in the file that I linked to 0.

**Comment by DeNeutoy** [comment]
Hopefully i've just fixed this by merging #2889 - let us know if it happens again! (also it's fine that the test fails, there's nothing fundamental wrong with the model)

**Comment by seth-priya** [comment]
thanks @DeNeutoy @matt-gardner this fixes the test for me, all passing now!
