### ISSUE TITLE
How can I load a reader from config.json into python code?

### ISSUE THREAD

**Issue by abaheti95** [allenai/allennlp#3069]
**System (please complete the following information):**
 - OS: Linux
 - Python version: 3.6.6
 - AllenNLP version: v0.8.4

**Question**
How can I load a reader from `config.json` into python code?

I am trying to run the dialog_qa predictor on a new dataset. I was able to load the model from the config file using `config` parameter as follows:
```python
# Load quac model here
config_file = os.path.join("models", "config.json")
with open(config_file) as f:
	model_config = Params(json.load(f))
serialization_dir = "models"
model_weights_file = os.path.join("models", "weights.th")
model = Model.load(config=model_config, serialization_dir=serialization_dir, weights_file=model_weights_file)
```
I would like a similar interface for loading the dataset_reader `QuACReader` from the `config` into python.  My config file looks like this:
```json
{
    "dataset_reader": {
        "type": "quac",
        "lazy": true,
        "num_context_answers": 2,
        "token_indexers": {
            "elmo": {
                "type": "elmo_characters"
            },
            "token_characters": {
                "type": "characters",
                "character_tokenizer": {
                    "byte_encoding": "utf-8",
                    "end_tokens": [
                        260
                    ],
                    "start_tokens": [
                        259
                    ]
                }
            }
        }
    },
    "iterator": {
    ...
```
Kindly point out the correct syntax for this.  Is there any `from_params()` sort of function for dataset_readers?

**Comment by joelgrus** [comment]
yes, every class that can be configured from JSON has a `from_params` method (some require extra arguments, but dataset readers don't), so you can just do

```
DatasetReader.from_params(reader_params)
```

in addition, if you have the `model.tar.gz` archive for the trained model, you can just use `load_archive` to load the model (and params) in one step, rather than what you did above:

https://github.com/allenai/allennlp/blob/master/allennlp/models/archival.py#L150
