### ISSUE TITLE
Update SRL model to the BERT-based (Shi et al, 2019) as stated on the demo website

### ISSUE THREAD

**Issue by frankxu2004** [allenai/allennlp#3070]
**Is your feature request related to a problem? Please describe.**
The demo website has updated with the new SRL model [here](https://demo.allennlp.org/semantic-role-labeling).

> This page demonstrates a reimplementation of a BERT based model (Shi et al, 2019)with some modifications (no additional parameters apart from a linear classification layer), which is currently the state of the art single model for English PropBank SRL (Newswire sentences).

**Describe the solution you'd like**
Update the model downloads page with the new model

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by jinruiyang** [comment]
Same problems.

> /home/ubuntu/anaconda3/envs/allennlp/lib/python3.7/site-packages/sklearn/utils/linear_assignment_.py:21: DeprecationWarning: The linear_assignment_ module is deprecated in 0.21 and will be removed from 0.23. Use scipy.optimize.linear_sum_assignment instead.
>   DeprecationWarning)
> Archived file preprocessing/srl_storyline_processing/pretrained/srl-model-2018.05.25/fta/model.text_field_embedder.elmo.weight_file not found! At train time this file was located at /net/efs/aristo/allennlp/elmo_models/2x4096_512_2048cnn_2xhighway/converged/elmo_2x4096_512_2048cnn_2xhighway_enwiki_news_967500_weights.hdf5. This may be because you are loading a serialization directory. Attempting to load the file from its train-time location.
> Traceback (most recent call last):
>   File "preprocessing/srl_storyline_processing/srl_to_storyline.py", line 329, in <module>
>     main()
>   File "preprocessing/srl_storyline_processing/srl_to_storyline.py", line 266, in main
>     SRLpredictor = SemanticRoleLabelerPredictor.from_archive(load_archive(args.srl_model, args.cuda))
>   File "/home/ubuntu/anaconda3/envs/allennlp/lib/python3.7/site-packages/allennlp/models/archival.py", line 230, in load_archive
>     cuda_device=cuda_device)
>   File "/home/ubuntu/anaconda3/envs/allennlp/lib/python3.7/site-packages/allennlp/models/model.py", line 327, in load
>     return cls.by_name(model_type)._load(config, serialization_dir, weights_file, cuda_device)
>   File "/home/ubuntu/anaconda3/envs/allennlp/lib/python3.7/site-packages/allennlp/models/model.py", line 265, in _load
>     model = Model.from_params(vocab=vocab, params=model_params)
>   File "/home/ubuntu/anaconda3/envs/allennlp/lib/python3.7/site-packages/allennlp/common/from_params.py", line 365, in from_params
>     return subclass.from_params(params=params, **extras)
>   File "/home/ubuntu/anaconda3/envs/allennlp/lib/python3.7/site-packages/allennlp/common/from_params.py", line 386, in from_params
>     kwargs = create_kwargs(cls, params, **extras)
>   File "/home/ubuntu/anaconda3/envs/allennlp/lib/python3.7/site-packages/allennlp/common/from_params.py", line 133, in create_kwargs
>     kwargs[name] = construct_arg(cls, name, annotation, param.default, params, **extras)
>   File "/home/ubuntu/anaconda3/envs/allennlp/lib/python3.7/site-packages/allennlp/common/from_params.py", line 229, in construct_arg
>     return annotation.from_params(params=subparams, **subextras)
>   File "/home/ubuntu/anaconda3/envs/allennlp/lib/python3.7/site-packages/allennlp/common/from_params.py", line 365, in from_params
>     return subclass.from_params(params=params, **extras)
>   File "/home/ubuntu/anaconda3/envs/allennlp/lib/python3.7/site-packages/allennlp/modules/text_field_embedders/basic_text_field_embedder.py", line 165, in from_params
>     token_embedders[key] = TokenEmbedder.from_params(vocab=vocab, params=embedder_params)
>   File "/home/ubuntu/anaconda3/envs/allennlp/lib/python3.7/site-packages/allennlp/common/from_params.py", line 365, in from_params
>     return subclass.from_params(params=params, **extras)
>   File "/home/ubuntu/anaconda3/envs/allennlp/lib/python3.7/site-packages/allennlp/modules/token_embedders/elmo_token_embedder.py", line 128, in from_params
>     scalar_mix_parameters=scalar_mix_parameters)
>   File "/home/ubuntu/anaconda3/envs/allennlp/lib/python3.7/site-packages/allennlp/modules/token_embedders/elmo_token_embedder.py", line 65, in __init__
>     scalar_mix_parameters=scalar_mix_parameters)
>   File "/home/ubuntu/anaconda3/envs/allennlp/lib/python3.7/site-packages/allennlp/modules/elmo.py", line 110, in __init__
>     vocab_to_cache=vocab_to_cache)
>   File "/home/ubuntu/anaconda3/envs/allennlp/lib/python3.7/site-packages/allennlp/modules/elmo.py", line 524, in __init__
>     self._token_embedder = _ElmoCharacterEncoder(options_file, weight_file, requires_grad=requires_grad)
>   File "/home/ubuntu/anaconda3/envs/allennlp/lib/python3.7/site-packages/allennlp/modules/elmo.py", line 310, in __init__
>     self._load_weights()
>   File "/home/ubuntu/anaconda3/envs/allennlp/lib/python3.7/site-packages/allennlp/modules/elmo.py", line 398, in _load_weights
>     self._load_char_embedding()
>   File "/home/ubuntu/anaconda3/envs/allennlp/lib/python3.7/site-packages/allennlp/modules/elmo.py", line 404, in _load_char_embedding
>     with h5py.File(cached_path(self._weight_file), 'r') as fin:
>   File "/home/ubuntu/anaconda3/envs/allennlp/lib/python3.7/site-packages/allennlp/common/file_utils.py", line 104, in cached_path
>     raise FileNotFoundError("file {} not found".format(url_or_filename))
> FileNotFoundError: file /tmp/tmps971tn46/fta/model.text_field_embedder.elmo.weight_file not found``
