### ISSUE TITLE
Create a nltk tree from biaffine dependency parser results

### ISSUE THREAD

**Issue by LivingScripts** [allenai/allennlp#3072]
Please first search our GitHub repository for similar questions.  If you don't find a similar example you can use the following template:

**System:**
 - OS: ubuntu 18.04
 - Python version: 3.6.8
 - AllenNLP version: 0.8.4

**Question**
How can I create a `nltk` from the dependency parser output since it only returns an `hierplane_tree`

**Comment by DeNeutoy** [comment]
In general that's much less commonly done than converting from phrase-structure trees to dependency trees - if you want a phrase-structure tree you should probably just use the constituency parsing model.

**Comment by LivingScripts** [comment]
I'm using a `constituency parser`, but I also need to know the grammatical parse of the sentence.

**Comment by DeNeutoy** [comment]
I think you are looking for `Tree.fromstring("string from allennlp")`, hopefully that helps?
