### ISSUE TITLE
what type of data i have to give for train and validate my model in other language?

### ISSUE THREAD

**Issue by Bipin8469** [allenai/allennlp#3089]
System (please complete the following information):

OS: Windows 10 pro
Python version: 3.6.8
AllenNLP version: allennlp 0.8.4-unreleased
PyTorch version: 1.1.0
Question:
I have to run allennlp in another language like Chinese, so I have to know what type of data has to give for training and testing a model.
In page https://allennlp.org/tutorials given data for training is :
The###DET dog###NN ate###V the###DET apple###NN
Everybody###NN read###V that###DET book###NN
and for validation is :
The###DET dog###NN ate###V the###DET apple###NN
Everybody###NN read###V that###DET book###NN
that is POS tags of english,  is that means i also have to give POS tags is chinese language?
can anyone please explain this.
thank you.

**Comment by matt-gardner** [comment]
What task are you trying to do?  We have a lot of example models in this codebase for a lot of different tasks.  The way you represent data for all of them is different.  If you want to train and validate a model in another language, the data should be in the same format as it is for the example data that we have here.

**Comment by Bipin8469** [comment]
I have to try reading comprehension.

**Comment by matt-gardner** [comment]
So look at our dataset readers for reading comprehension, find their example data formats (you can do this by looking at our tests, particularly in the `fixtures/data` directory), and format your data the same way.  There's a reader that takes in data in the SQuAD format; if you get your data into that format, things should work.
