### ISSUE TITLE
Pretrained NER+ELMO to deal with lowercased sentences

### ISSUE THREAD

**Issue by HungChau** [allenai/allennlp#3094]
Is there any pretrained NER+ELMO model that can handle lowercased sentences; for example, trained with uncased data or combination of cased and uncased. It seems like the current pretrained model does not work very well with lowercased sentences.

Thanks!

**Comment by matt-gardner** [comment]
Casing information is one of the most important signals for NER in English.  If you only have lowercased data, you're going to have a much harder time with NER.  So, no, we don't have any model that does this.  It wouldn't be that hard to take one of our models and train it on a lowercased version of some dataset, though.

**Comment by HungChau** [comment]
Thanks!
