### ISSUE TITLE
TypeError '_NamespacePath' object does not support indexing

### ISSUE THREAD

**Issue by zwacm** [allenai/allennlp#3103]
**System (please complete the following information):**
 - OS: [Linux]
 - Python version: [3.6.8]
 - AllenNLP version: [v0.8.4,]

**Question**
* I encounter the TypeError as the title descripted, and I do not know how to deal with it? The traceback information is as following:
'''
Traceback (most recent call last):
  File "/home/yangzhiwei/anaconda3/envs/allennlp/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/yangzhiwei/anaconda3/envs/allennlp/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/yangzhiwei/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/run.py", line 21, in <module>
    run()
  File "/home/yangzhiwei/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/run.py", line 18, in run
    main(prog="allennlp")
  File "/home/yangzhiwei/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/commands/__init__.py", line 101, in main
    import_submodules(package_name)
  File "/home/yangzhiwei/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/common/util.py", line 325, in import_submodules
    path_string = '' if not path else path[0]
TypeError: '_NamespacePath' object does not support indexing
'''

is there something wrong with the source code?

**Comment by matt-gardner** [comment]
I have not seen this before.  What are you passing as your `--include-package` argument?

**Comment by jeff-da** [comment]
Make sure your dataset reader isn't doing anything weird with the file_path argument (such as string comparison). That's what happened to me.

**Comment by DeNeutoy** [comment]
@zwacm please answer @matt-gardner's question above so we can help you. It seems like you might be passing an incorrect `--include-package` argument.

**Comment by joelgrus** [comment]
one other possibility is that you need to put an empty `__init__.py` in the directory where your module is. in theory this shouldn't matter, but based on the error you're getting I wonder if this might be causing problems.

**Comment by zwacm** [comment]
sorry for late reply !
I am trying to run the code at [https://github.com/allenai/scibert](url), and I pass the command "./scibert/scripts/train_allennlp_local.sh [serialization-directory]" as mentioned in the link. When I put an empty "_ _init_ _.py" in the directory,  '_NamespacePath' typeError  is solved. However, there comes with another problem of **ModuleNotFoundError: No module named 'scibert.dataset_readers'**. By the way, I have not modified any file. @matt-gardner @jeff-da @joelgrus @DeNeutoy 

Thank you all!

**Comment by dmarx** [comment]
@zwacm You're getting that error because adding an empty `__init__.py` to your top level `/scibert` folder messes up the import structure. Rather than adding an `__init__.py` to that folder, just change directory into the folder instead. I experienced the `_NamespacePath` error followed by the `ModuleNotFoundError` error trying to run the basic usage demo in google colab. Here's the sequence of commands I used to get this working in colab:

```
# Download the repo, install dependencies, add a folder to save our model
!git clone https://github.com/allenai/scibert
%cd scibert
!pip install -r requirements.txt
!mkdir modeltest0
```
```
# Download a pre-trained model
import requests

def save_response_content(response, destination):
    CHUNK_SIZE = 32768

    with open(destination, "wb") as f:
        for chunk in response.iter_content(CHUNK_SIZE):
            if chunk: # filter out keep-alive new chunks
                f.write(chunk)

URL = 'https://s3-us-west-2.amazonaws.com/ai2-s2-research/scibert/pytorch_models/scibert_scivocab_uncased.tar'

session = requests.Session()
response = session.get(URL)
outpath = 'scibert_scivocab_uncased.tar'

save_response_content(response, outpath)
```
```
# unpack the downloaded model
!tar -xvf scibert_scivocab_uncased.tar
```
```
# modify the training script to point to the pretrained model 
# and to suppress an error from the DATASET_SIZE variable 
with open('scripts/train_allennlp_local.sh', 'r') as f:
  ftext = f.read()

lines = []
for line in ftext.split('\n'):
  if line.startswith("export BERT_VOCAB"):
    line = "export BERT_VOCAB=scibert_scivocab_uncased/vocab.txt"
  if line.startswith("export BERT_WEIGHTS"):
    line = "export BERT_WEIGHTS=scibert_scivocab_uncased/weights.tar.gz"
    
  # a little weird that this last step was necessary, but whatever.
  if line.startswith("export DATASET_SIZE"):
    line = "export DATASET_SIZE=3219"
  lines.append(line)
outtext = '\n'.join(lines)

with open('scripts/train_allennlp_local2.sh', 'w') as f:
  f.write(outtext)
```
```
# run the modified training script
!chmod +x ./scripts/train_allennlp_local2.sh
!./scripts/train_allennlp_local2.sh ./modeltest0
```

Training ran for 7 epochs and completed after just under 10 minutes, producing a text accuracy of 87%.

**Comment by zwacm** [comment]
Thank you all.
I have solved the problem by adding "--include-package xxx" to train_allennlp_local.sh (xxx includes models and readers) besides addint empty '__init__' to the corresponding directories. It works.@dmarx@joelgrus

**Comment by RuiruiKang** [comment]
> one other possibility is that you need to put an empty `__init__.py` in the directory where your module is. in theory this shouldn't matter, but based on the error you're getting I wonder if this might be causing problems.

helpful

**Comment by NGC2237-wei** [comment]
hello, I have the same problem as you，but i don't know how to solve it

**Comment by SophieZheng998** [comment]
> Thank you all. I have solved the problem by adding "--include-package xxx" to train_allennlp_local.sh (xxx includes models and readers) besides addint empty '**init**' to the corresponding directories. It works.@dmarx@joelgrus

Dear Sir,
I have been working on the exactly scibert github as you, and encountered with the same problem. i am wondering what do you mean by adding "models and readers"? could you show the example command that works for you?
