### ISSUE TITLE
The datasets_for_vocab_creation option is not implemented well

### ISSUE THREAD

**Issue by doubler** [allenai/allennlp#3105]
allennlp.training.trainer.py#L788
```
(instance for key, dataset in all_datasets.items()
                     for instance in dataset
                     if key in datasets_for_vocab_creation)
```
Every instance will be iterated before load the vocabulary. It's a really problem when the datas are large.

When use Bert encoder in AllenNLP for regression model, I don't need the Vocabulary. The vocab.txt in bert model can be load by the bert indexer, and the labels.txt is not needed for regression model.
If I want to train a model using the jsonnet config, the Vocabulary.from_instances will be called. It will iterate all the datasets instances even I already set the param:
```
"test_data_path": "a_very_small_file",
"datasets_for_vocab_creation": ["test"]
```
And the code may be changed like
```
(instance for key, dataset in all_datasets.items()
                     if key in datasets_for_vocab_creation
                     for instance in dataset)
```

**Comment by DeNeutoy** [comment]
Hi,

There is no other way to construct a vocabulary other than reading all of your data. However, you can pass an already constructed vocabulary using this in your top level of your configuration file:

```
{
"vocabulary":
	"directory_path": "/path/to/vocabulary/folder/"
}

```

Hopefully that solves your problem!

**Comment by joelgrus** [comment]
this is already fixed in master

https://github.com/allenai/allennlp/blob/57870f5ab29888b20882b9c9a94c7c1c1a531558/allennlp/training/trainer_pieces.py#L58

**Comment by doubler** [comment]
Thanks for your reply! @joelgrus @DeNeutoy
