### ISSUE TITLE
Add support for caching an entire dataset at once with pickle, instead of one instance at a time with jsonpickle

### ISSUE THREAD

**Issue by mbugert** [allenai/allennlp#3107]
**Describe the bug**
Currently, caching is implemented on a per-instance basis. TextFields keep a reference to their TokenIndexer, so when an instance is cached, the indexer object is cached as well. A WordpieceIndexer object contains the wordpiece vocabulary.
As a consequence, when caching a model using bert-base-uncased (alongside other cache-worthy preprocessing steps) the full BERT vocabulary is cached for each instance which is excruciatingly slow and inefficient (1MB of disk space per instance just for the vocab).

**To Reproduce**
1. Download config file: [config.jsonnet.txt](https://github.com/allenai/allennlp/files/3445672/config.jsonnet.txt). Adjust training data path to point to language modeling training data (one sentence per line).
2. Call `allennlp train config.jsonnet --cache-directory=... --serialization-dir=...`
3. Observe size and contents of the cached training data

**Expected behavior**
A more efficient caching strategy, I suppose. If instances were cached in one block, this wouldn't happen.

**System (please complete the following information):**
 - OS: Linux
 - Python version: 3.6.8
 - AllenNLP version: v0.8.4

**Comment by matt-gardner** [comment]
Do you think that something like #3058 would solve this?

**Comment by mbugert** [comment]
If it included [your suggestion](https://github.com/allenai/allennlp/pull/3058#issuecomment-510976577) of serializing multiple instances at once, it should. The indexer object would likely be cached only once for all instances in this case.

**Comment by matt-gardner** [comment]
Ok, I think that's the right fix here.  I'm going to change the name of this issue to be more explicit about adding pickle support.

**Comment by STayinloves** [comment]
It's easy to implement caching an entire dataset, but it will lose track of the read/write progress.

I leave my implementation here for future reference.

```
    @overrides
    def _instances_from_cache_file(self, cache_filename: str) -> Iterable[Instance]:
        print('read instance from', cache_filename)
        with open(cache_filename, 'rb') as cache_file:
            instances = dill.load(cache_file)
            for instance in instances:
                yield instance

    @overrides
    def _instances_to_cache_file(self, cache_filename, instances) -> None:
        print('write instance to', cache_filename)
        with open(cache_filename, 'wb') as cache_file:
            dill.dump(instances, cache_file)
```

**Comment by matt-gardner** [comment]
Thanks @STayinloves. The abstract methods to let you do this were added a long time ago, so I'm closing this issue. If you want to have this kind of cache, you can add @STayinloves's code to your dataset reader.
