### ISSUE TITLE
How was tokens.txt selected? size 97913 < glove size 400k

### ISSUE THREAD

**Issue by stevenwernercs** [allenai/allennlp#3111]
The [glove.6B.100d.txt.gz](https://allennlp.s3.amazonaws.com/datasets/glove/glove.6B.100d.txt.gz) Word Embeddings specified in the [bidaf-model-2017.09.15-charpad.tar.gz](https://s3-us-west-2.amazonaws.com/allennlp/models/bidaf-model-2017.09.15-charpad.tar.gz)'s [config](https://github.com/allenai/allennlp/blob/master/training_config/bidaf.jsonnet) has a 400k vocab size x 100 dimension. How was this reduced down to the 97913 rows in tokens.txt?

Looking into the tensor '_text_field_embedder.token_embedder_tokens.weight' of the model bidaf-model-2017.09.15-charpad.tar\\bidaf-model-2017.09.15-charpad\\weights.th, it is size 97914x100, it seems like this should hold the original Word Embeddings the model was trained on.

Is this true, and if so how were the 400k words in the glove down selected to just the 97k?

Is the 97k size just the intersection of tokens seen during training and the initial glove 400k vocab?
If so would it not benefit the model to preserve the entire 400k vocab?

please let me know if I am missing something. Thank you

**Comment by DeNeutoy** [comment]
Yes that's correct - it's the tokens in the data used for training/testing/validation. You can add additional vectors after training using `--extend-vocab` in the `evaluate` command: 


https://allenai.github.io/allennlp-docs/api/allennlp.commands.evaluate.html
