### ISSUE TITLE
Road map for AllenNlp

### ISSUE THREAD

**Issue by Ansarimi** [allenai/allennlp#3112]
This is more of road map question. I used AllenNlp sometime back for a project and I really loved it. We are going to start another bigger project with long term plan. I am contemplating whether I should use AllenNLP or any other frameworks. Few questions are

With PyText from Facebook is growing fast, what is the road map for AllenNlp? 
Previously, release cycle is almost every month, but not seeing release even after two months. Is overall contribution going down?

Thanks

**Comment by DeNeutoy** [comment]
Hi,

We've never kept to a strict release schedule - don't worry, the library is still being developed. Pytext is heavily inspired by allennlp, and also I am not sure it is "growing fast". It currently has 8 projects who depend on it according to the github `used by` metric, compared to allennlp's 366.

Hopefully that helps you decide!
