### ISSUE TITLE
BasicClassifier does not support regularization

### ISSUE THREAD

**Issue by pensono** [allenai/allennlp#3113]
**Is your feature request related to a problem? Please describe.**
I'm trying to use the `BasicClassifier` with regularization, however it is not supported.

**Describe the solution you'd like**
A regularizer parameter is added to `BasicClassifier` and passed into the super constructor call.

**Describe alternatives you've considered**
I've made my own classifier model identical to `BasicClassifier` except with the above solution applied.

**Additional context**
I can implement this if the above solution is adequate.

**Comment by kernelmachine** [comment]
Yep, this would be useful. Contributions welcome!
