### ISSUE TITLE
predictor.predict_json uses the dataset_reader config entry instead of using the validation_dataset_reader entry

### ISSUE THREAD

**Issue by alontalmor** [allenai/allennlp#3114]
predictor.predict_json uses the dataset_reader config entry instead of using the validation_dataset_reader entry (when such exists). 

This causes params from training (such as is_training=True if such param is defined) to be passed to the predictor. 

Expected behavior - have the predictor use the validation_dataset_reader when such exists. 

Perhaps this issue needs to be merged, but i would still like to emphasis that i'm surprised that the default is not to use the validation_dataset_reader in predict.

**Comment by danieldeutsch** [comment]
Does https://github.com/allenai/allennlp/pull/3033 address the issue or is there still an outstanding problem?

**Comment by alontalmor** [comment]
yes it does, thanks for fixing this!
