### ISSUE TITLE
srl bert model didn't register 

### ISSUE THREAD

**Issue by jinruiyang** [allenai/allennlp#3121]
when I tried 
```
        from allennlp.predictors.predictor import Predictor
        predictor = Predictor.from_path("https://s3-us-west-2.amazonaws.com/allennlp/models/srl-model-2018.05.25.tar.gz")
        predictor = Predictor.from_path("https://s3-us-west-2.amazonaws.com/allennlp/models/bert-base-srl-2019.06.17.tar.gz")
        predictor.predict(
          sentence="Did Uriah honestly think he could beat the game in under three hours?"
        )
```
on the latest version 0.8.4, but got the error:

> Traceback (most recent call last):
  File "preprocessing/srl_storyline_processing/srl_bert_test.py", line 2, in <module>
    predictor = Predictor.from_path("https://s3-us-west-2.amazonaws.com/allennlp/models/bert-base-srl-2019.06.17.tar.gz")
  File "/Users/yangjinrui/anaconda3/envs/envi2/lib/python3.7/site-packages/allennlp/predictors/predictor.py", line 144, in from_path
    return Predictor.from_archive(load_archive(archive_path), predictor_name)
  File "/Users/yangjinrui/anaconda3/envs/envi2/lib/python3.7/site-packages/allennlp/models/archival.py", line 230, in load_archive
    cuda_device=cuda_device)
  File "/Users/yangjinrui/anaconda3/envs/envi2/lib/python3.7/site-packages/allennlp/models/model.py", line 327, in load
    return cls.by_name(model_type)._load(config, serialization_dir, weights_file, cuda_device)
  File "/Users/yangjinrui/anaconda3/envs/envi2/lib/python3.7/site-packages/allennlp/common/registrable.py", line 58, in by_name
    raise ConfigurationError("%s is not a registered name for %s" % (name, cls.__name__))
allennlp.common.checks.ConfigurationError: 'srl_bert is not a registered name for Model'

**Comment by DeNeutoy** [comment]
Hi! We haven't done a release yet which includes the srl bert model - you'll need to install from master.

**Comment by Shashika** [comment]
Even with the master, the same issue comes when trying to build the backend service `app.py`.

**Comment by afsangujarati93** [comment]
> Even with the master, the same issue comes when trying to build the backend service `app.py`.

`git clone https://github.com/allenai/allennlp.git`
`pip install --editable .`

Reference: https://pypi.org/project/allennlp/

**Comment by ariecattan** [comment]
After installing with master, I get the following error

`allennlp.common.checks.ConfigurationError: srl_bert is not a registered name for Model. You probably need to use the --include-package flag to load your custom code. Alternatively, you can specify your choices using fully-qualified paths, e.g. {"model": "my_module.models.MyModel"} in which case they will be automatically imported correctly. `

**Comment by itsmemala** [comment]
@ariecattan Did you manage to resolve this? I see the same error when I try to load modal from a local path using load_archive.

**Comment by matt-gardner** [comment]
@itsmemala, can you open a new issue?  It's a lot easier for us to track.  Before you do, though, can you confirm that you see this issue with the latest master?  There have been some fixes along this line recently, which may not have made it into a new release yet.

**Comment by ariecattan** [comment]
@itsmemala and @matt-gardner, I did check with the new version, it works properly. There is only one thing, you should remove `import allennlp_models.syntax.srl` this does not work and the model works without that

**Comment by itsmemala** [comment]
I just tried again after installing through git clone allennlp v1.0.0 (I believe this is the latest master) and I still get the same error. i will open a new issue.

**Comment by idoan** [comment]
I got the same error and It is resolved after installing [allennlp-models](https://pypi.org/project/allennlp-models/) package.
