### ISSUE TITLE
Callback Trainer doesn't work with Moving Average

### ISSUE THREAD

**Issue by vikigenius** [allenai/allennlp#3122]
Callback UpdateMovingAverage doesn't work when used from config

**To Reproduce**
Steps to reproduce the behavior
1. create a jsonnet config for callback trainer, with UpdateMovingAverage as one of the callbacks.
2. Error Occurs saying too many too many value to unpack from self._parameters

**Expected behavior**
UpdateMovingAverage callback should work

**System (please complete the following information):**
 - OS: Linux_64
 - Python version: 3.7.3
 - AllenNLP version: I installed from master

**Additional context**
https://github.com/allenai/allennlp/blob/9db004224adf74267cc923d45e8ecb22b53d7066/allennlp/training/callbacks/update_moving_average.py#L34

The above line is the problem, we should be passing it named_parameters, and also as a further question, shouldn't we only maintain moving averages for params that require gradients ?

**Comment by joelgrus** [comment]
you are correct on both counts, PR welcome

**Comment by joelgrus** [comment]
actually, I'll just take care of this, so that I can cut a release soon
