### ISSUE TITLE
from collections import MutableMapping is deprecated in Python 3.7

### ISSUE THREAD

**Issue by joelgrus** [allenai/allennlp#3123]
and in particular it causes our library to raise a `DeprecationWarning`, which causes pytest to fail.

see https://github.com/allenai/allennlp/issues/3064#issuecomment-519344996

we should replace all the `from collections import SomeAbstractBaseClass` with `from collections.abc import SomeAbstractBaseClass`

cf https://www.google.com/search?q=collections.abc+deprecationwarning

**Comment by DeNeutoy** [comment]
we've fixed this at some point (our tests run on 3.7).
