### ISSUE TITLE
a number of our tests fail under the just-released PyTorch 1.2.0

### ISSUE THREAD

**Issue by joelgrus** [allenai/allennlp#3127]
https://github.com/pytorch/pytorch/releases/tag/v1.2.0

http://build.allennlp.org/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=18359&_focus=9987

in the very short term we can just pin away from it.

after that we need to decide how to fix it. one obvious solution is to force everyone to use pytorch>=1.2, another is to skip the failing tests, a third is to make the tests robust across versions, that might be hard!

**Comment by DeNeutoy** [comment]
pytorch 1.2 changed a return type for some types of indexing and boolean comparison which will make supporting multiple pytorch versions hard, so we should wait a bit and then upgrade rather than supporting both.

**Comment by matt-gardner** [comment]
This has been fixed.
