### ISSUE TITLE
Update allennlp package on conda forge

### ISSUE THREAD

**Issue by IHMCBrodie** [allenai/allennlp#3130]
Would you guys be able to update your allennlp package on conda forge located here https://anaconda.org/conda-forge/allennlp? The package there is version 0.7.2 but the one obtained from pip install allennlp is 0.8.3. 

The difference in version in those locations is causing issues and discrepencies. 

Thank you for your consideration

**Comment by kernelmachine** [comment]
@schmmd, is this something you can do?

**Comment by joelgrus** [comment]
I think @nelson-liu might have set this up originally? We probably need to share this knowledge more broadly.

**Comment by nelson-liu** [comment]
No, conda-forge is actually an open feedstock for the package; the build scripts live here: https://github.com/conda-forge/allennlp-feedstock . I'm not a listed maintainer of the package there, but I can try to fix and merge the PRs that would build and upload the updated versions... https://github.com/conda-forge/allennlp-feedstock/pulls

**Comment by DeNeutoy** [comment]
Hi, we do not maintain the conda feedstock repositories for allennlp and they were set up without our knowledge, so there's not much we can do here! Good luck.

**Comment by IHMCBrodie** [comment]
Okay, I guess I just assumed you guys did since all the info at that url pointed to your github and such. 
Would it be at all possible for you guys to put allennlp on Conda Forge at all?
