### ISSUE TITLE
please slove this prolem

### ISSUE THREAD

**Issue by Pydataman** [allenai/allennlp#3133]
when I train chinese elmo， remove below parameters
     'char_cnn': {'activation': 'relu',
     'embedding': {'dim': 16},
     'filters': [[1, 32],
       [2, 32],
      ......
      ]
      'max_characters_per_token': 50,
      'n_characters': 261,
      'n_highway': 2},
I run
    from allennlp.modules.elmo import Elmo, batch_to_ids
    elmo = Elmo(options_file, weight_file, 1, dropout=0)
   character_ids = batch_to_ids(sentences)
   embeddings = elmo(character_ids)

error:
 KeyError: "Unable to open object (object 'char_embed' doesn't exist)"

is the same as [#1521](https://github.com/allenai/allennlp/issues/1521)

**Comment by DeNeutoy** [comment]
Hi! Currently we only support full elmo models with character embeddings. Please see #1521 for a hacky solution, but we won't be adding this to the library. Good luck!
