### ISSUE TITLE
ModuleNotFoundError: No module named 'scibert.dataset_readers'

### ISSUE THREAD

**Issue by zwacm** [allenai/allennlp#3134]
Hi, 
I am trying to run the sciBert code at [https://github.com/allenai/scibert](url) that is based on Allennlp ,  however, it seems that the code can not work correctly after I solved the problem at [https://github.com/allenai/allennlp/issues/3103](url). 

I am new to Allennlp and I wander whether I should add the google Bert model [https://github.com/google-research/bert](url)  to sciBert.

Thank you.

![20190811214734](https://user-images.githubusercontent.com/19528731/62834620-af569180-bc81-11e9-963d-251d3497e2cf.png)
![2019081121473422](https://user-images.githubusercontent.com/19528731/62834720-f3966180-bc82-11e9-8df2-5319476ad071.png)
![2019081121473423](https://user-images.githubusercontent.com/19528731/62834722-f6915200-bc82-11e9-80e0-c4a20f4f5c16.png)
![2019081121473424](https://user-images.githubusercontent.com/19528731/62834724-f8f3ac00-bc82-11e9-8447-e6bd243113a5.png)

**Comment by zwacm** [comment]
When I use the way of "from ... import" instead, I solved ModuleNotFoundError, however, another problem appears.
![2019081121473427](https://user-images.githubusercontent.com/19528731/62835535-298c1380-bc8c-11e9-93a3-10305535106a.png)

**Comment by DeNeutoy** [comment]
Hi,

please can you open this issue on the scibert repo? I am not sure that we can help you as it looks specific to the configuration of the scibert code itself, rather than a problem with allennlp.

Thanks!
