### ISSUE TITLE
Question about handling Vocabulary in training procedure similar to GANs

### ISSUE THREAD

**Issue by vikigenius** [allenai/allennlp#3135]
I looked at the toy GAN examples and found something not very clear.

In the toy example the super's vocab is set to None here: https://github.com/allenai/allennlp/blob/23a089c8c49fc834a1406333131066bbb6d50076/allennlp/tests/training/gan_callback_trainer_test.py#L45

But what if say my generator requires the vocab parameter, how would I handle this case? Let us assume that the GAN itself doesn't need the vocab only the generator and/or the discriminator do.

**Comment by joelgrus** [comment]
I believe that if you just had each of the models take a `vocab: Vocabulary` parameter and pass it to its `super()` that it would just work. (the reason I didn't do that here is that none of the models needed a vocabulary). let me know if that doesn't work.
