### ISSUE TITLE
Multi-source encoding for Seq2seq model

### ISSUE THREAD

**Issue by RikVN** [allenai/allennlp#3139]
Hi,

Is it currently possible to do multi-source encoding (e.g. an encoder for tokens and an extra encoder for POS-tags, or a BERT encoder combined with a character-level encoder). 

Basically I want to run the RNN twice and then concatenate the resulting vectors for during decoding. Preferably I'd also calculate the attention context vector twice and then concatenate those as well. Similar to Section 4.3 here: https://arxiv.org/pdf/1706.04138.pdf

I looked into extending the SimpleSeq2seq model but got kind of confused by all the classes / data structures involved. It seems the model works with a single dataset from the start and is not easily extended to work with multiple vocabs.

Are you aware of any work that's similar? Any pointers on how to add this (if not currently possible) are greatly appreciated.

(Some context: I do research in semantic parsing and have had some good results with character-level models, but that was pre-BERT. I'd want to see if BERT can outperform those first (seems like they can), but also want to know if combining them is even better.)

**Comment by DeNeutoy** [comment]
Yes, it is possible - typically we would concatenate all the feature representations first before running them through an encoder, but you could do them separately. The parts that you will want to look at is the `text_field_embedder` and the `token_indexers/embedders`. These control how tokens are represented to the model, and they are expected to correspond.

For example, here is an indexer that will represent a string of tokens as their pos tags from a spacy model:

https://github.com/allenai/allennlp/blob/master/allennlp/data/token_indexers/pos_tag_indexer.py


Here is the complete list of available indexers:

https://allenai.github.io/allennlp-docs/api/allennlp.data.token_indexers.html

Here is an example of how to add an additional input representation to a model by changing the json config (in this case elmo):

https://github.com/allenai/allennlp/blob/master/tutorials/how_to/elmo.md#using-elmo-with-existing-allennlp-models

Here's an example of a fully functional configuration file which uses multiple token indexers/embedders:

https://github.com/allenai/allennlp/blob/master/training_config/qanet.jsonnet#L7

Hopefully these resources help you get started!

**Comment by RikVN** [comment]
Thanks, helps a lot! If I get a working json config (or modified model) I'll share it here to help future work.

**Comment by DeNeutoy** [comment]
Great! Feel free to open new issues if you run into additional tricky things.
