### ISSUE TITLE
Warning when importing matplotlib before AllenNLP

### ISSUE THREAD

**Issue by luckytoilet** [allenai/allennlp#3154]
**Describe the bug**

Importing AllenNLP after importing matplotlib triggers a warning.

**To Reproduce**
Steps to reproduce the behavior
1. Start a python terminal
2. `import matplotlib.pyplot as plt`
3. `import allennlp.commands.elmo`

**Expected behavior**
Both libraries are imported.

**Actual behavior**
The AllenNLP import gives the following warning:

```
/h/bai/Documents/allennlp/allennlp/commands/find_learning_rate.py:55: UserWarning:
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

The backend was *originally* set to 'TkAgg' by the following code:
  File "<stdin>", line 1, in <module>
  File "/h/bai/.local/lib/python3.6/site-packages/matplotlib/pyplot.py", line 71, in <module>
    from matplotlib.backends import pylab_setup
  File "/h/bai/.local/lib/python3.6/site-packages/matplotlib/backends/__init__.py", line 16, in <module>
    line for line in traceback.format_stack()


  import matplotlib; matplotlib.use('Agg')
```

**System (please complete the following information):**
 - OS: Linux
 - Python version: 3.6.8
 - AllenNLP version: master
 - PyTorch version: 1.0.1.post2

**Additional context**
The problem appears to be caused by `find_learning_rate.py`:

```
import matplotlib; matplotlib.use('Agg')
import matplotlib.pyplot as plt
```

**Comment by DeNeutoy** [comment]
Hi, 

not sure there's too much we can do about this, sorry! If you have a fix it would be welcome, but we need matplotlib for one of the library commands.

**Comment by luckytoilet** [comment]
What if we moved the `matplotlib.use('Agg')` into the `_save_plot()` function? Then it's only run when it's needed, and not by everything that indirectly imports the file.

**Comment by DeNeutoy** [comment]
Sure sounds good! Want to send a small PR?
