### ISSUE TITLE
use rasa type of input

### ISSUE THREAD

**Issue by SreenijaK** [allenai/allennlp#3155]
In case I want to use the dataset like that of RASA, what changes do i need to make in  the Allennlp?

**Comment by DeNeutoy** [comment]
Hi,

Please take a look at our tutorial:

https://allennlp.org/tutorials

and our example package showing how to use allennlp as a library:
https://github.com/allenai/allennlp-as-a-library-example

I don't know what a RASA like dataset is, but perhaps following these tutorials will help you understand how to train your own model with allennlp.
