### ISSUE TITLE
v0.8.4 doesn't register srl-bert

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp#3162]
From a direct email:

I'm a researcher from Zhejiang University and I noticed that the newest SRL model had been changed to the bert-based-srl but the newest version of allennlp v0.8.4 seems to have no registration of srl-bert as it is configured in the config file. So are there any code implementation of this in allennlp frame available now? Since the paper was not published with codes.

**Comment by joelgrus** [comment]
this is because we need to do a release

duplicate of #3159

**Comment by DeNeutoy** [comment]
In the meantime, to use the SRL model, you will need to install from master 😄
