### ISSUE TITLE
ETA for predict_batch_instance

### ISSUE THREAD

**Issue by ricvolpe** [allenai/allennlp#3163]
Predictor class method predict_batch_instance sometime takes significant amount of time.
I believe that providing an ETA for the method could make the model develop-evaluate iterative cycle more convenient and quicker by informing developers/researchers when to go back collect their results. I also believe that this would not be very hard feature to add and am happy to contribute (e.g. by providing a merge request)

**Comment by DeNeutoy** [comment]
Hi!

As this depends on a lot of factors (batch size, machine type, whether you have a GPU etc), it is something we are unlikely to be able to accurately document. We suggest that you test out a small sample of your data beforehand to get a sense for your personal environment.

Thanks!
