### ISSUE TITLE
Support RAdam optimizer

### ISSUE THREAD

**Issue by bratao** [allenai/allennlp#3165]
From the results seems like RAdam reliably beat the old favorites

https://medium.com/@lessw/new-state-of-the-art-ai-optimizer-rectified-adam-radam-5d854730807b

A PyTorch implementation is available in https://github.com/LiyuanLucasLiu/RAdam

**Comment by DeNeutoy** [comment]
Hi,

I think we'll wait until this is peer reviewed :)

Until then, you can register a new optimizer like so (the `Optimizer.register("name")` part):

https://github.com/allenai/allennlp/blob/master/allennlp/training/optimizers.py#L167

and then run any of the `allennlp` commands with the `--include-package` argument. You can see the example we have for `DenseSparseAdam` in the example above.
