### ISSUE TITLE
SRL demo giving non arguments in square brackets

### ISSUE THREAD

**Issue by TheShadow29** [allenai/allennlp#3166]
I am not sure if it should be posted here or https://github.com/allenai/allennlp-demo as I have not been able to find where the error occurs.

The Bug: I am using the demo here: https://demo.allennlp.org/semantic-role-labeling

For the sentence: 
```
"The woman pours solution into her hand and cleans the lens in her hand before plopping two of them in her eyes and exhibiting completely black eyes to the camera while talking ."
```

I get the following output (only showing the erroneous output):
```
pours: [ARG0: The woman] [V: pours] [ARG1: solution] [ARG3: into her hand] and cleans the lens in her hand before plopping [two of] them in [ARGM-TMP: her eyes and exhibiting completely black eyes to the camera while talking] .
```

For some reason, "two of" is showing inside square brackets which I find quite perplexing.

Thank you for your patience.

**Comment by TheShadow29** [comment]
Update: I saw the tags of the above sentence, which are as follows:
```
['B-ARG0', 'I-ARG0', 'B-V', 'B-ARG1', 'B-ARG3', 'I-ARG3', 'I-ARG3', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'I-ARGM-TMP', 'I-ARGM-TMP', 'O', 'O', 'B-ARGM-TMP', 'I-ARGM-TMP', 'I-ARGM-TMP', 'I-ARGM-TMP', 'I-ARGM-TMP', 'I-ARGM-TMP', 'I-ARGM-TMP', 'I-ARGM-TMP', 'I-ARGM-TMP', 'I-ARGM-TMP', 'I-ARGM-TMP', 'I-ARGM-TMP', 'O']
```
Basically, after 'O', the output is 'I-ARG-TMP', since there is no 'B-ARG-TMP' the output is incorrect. 

I am not sure what the correct output should be in such a case. Do we ignore outputs which don't start off with 'B'?

**Comment by DeNeutoy** [comment]
damn, I thought I had fixed this. Let me look into this a bit.

**Comment by dirkgr** [comment]
Closing in favor of #4803.
