### ISSUE TITLE
How to train elmo on a new dataset? I only found the way to use the pretrained word embedding. Or do I miss something?

### ISSUE THREAD

**Issue by zz0807** [allenai/allennlp#3174]
Please first search our GitHub repository for similar questions.  If you don't find a similar example you can use the following template:

**System (please complete the following information):**
 - OS: [e.g. OSX, Linux]
 - Python version: [e.g. 3.6.1]
 - AllenNLP version: [e.g. v0.8.4, or "I installed from master"]
 - PyTorch version: (if you installed it yourself)

**Question**
Ask about something you don't understand, such as:

* How can I retrain my own ELMo language model?

* I'm working on a sentiment classification task and I would like to discard sentences that are longer than 1200 characters (my sentences vary from 400 characters to 1400+).  How can I configure my model to discard long sentences?

**Comment by brendan-ai2** [comment]
Hi @zz0807,

We don't have a way to easily train the original (LSTM-based) ELMo in the library currently, but we do have a variant that uses transformers that you can try. See https://github.com/allenai/allennlp/blob/master/tutorials/how_to/training_transformer_elmo.md for details.

As for dropping sentences, you should simply modify your dataset reader to take into account the number of characters and drop any instances that are too long. A similar example, albeit for tokens, can be found here https://github.com/allenai/allennlp/blob/master/allennlp/data/dataset_readers/simple_language_modeling.py#L33. Do take care to avoid dropping any instances when evaluating on test sets, of course.

I hope that helps! Let us know if you have any more questions.

**Comment by brendan-ai2** [comment]
Also, if you want the original TensorFlow implementation, see https://github.com/allenai/bilm-tf.

**Comment by zz0807** [comment]
@brendan-ai2 Thank you very much

**Comment by asarmohd** [comment]
None of the above-mentioned links are working
