### ISSUE TITLE
How do i implement gp2 as given in the demo for predicting the next word ?

### ISSUE THREAD

**Issue by pidugusundeep** [allenai/allennlp#3175]
Please first search our GitHub repository for similar questions.  If you don't find a similar example you can use the following template:

**System (please complete the following information):**
 - OS: [e.g. OSX, Linux]
 - Python version: [e.g. 3.6.1]
 - AllenNLP version: [e.g. v0.8.4, or "I installed from master"]
 - PyTorch version: (if you installed it yourself)

**Question**
Ask about something you don't understand, such as:
* Is there a prebuilt model the implement this ? [gp2 - Language Modeling
](https://demo.allennlp.org/gpt2)
* I want a tutorial that could explain the model generation and implementation of the same ?

**Comment by joelgrus** [comment]
despite being in the AllenNLP demo, that's not actually an AllenNLP model, it's just the huggingface GPT-2 code.

that code is mostly just adapted from a standalone version, which you can find here:

https://github.com/allenai/lm-explorer

**Comment by matt-gardner** [comment]
We do have an allennlp model that does this, though, and we're hoping to get it merged within the next week or two.

**Comment by pidugusundeep** [comment]
@joelgrus @matt-gardner Thanks :smile:
