### ISSUE TITLE
Don't dump frozen pretrained parameters. Load them (almost) always from `pretrained_file`.

### ISSUE THREAD

**Issue by mahnerak** [allenai/allennlp#3178]
**Is your feature request related to a problem? Please describe.**
When training networks on top of big "feature extractors" like BERT we end up having serialized weights with huge size, even if we have only very tiny classifiers on top of them.
This is okay as long as you're fine-tuning / training model parts alltogether, but in the opposite case, when most of the parameters are frozen all the checkpoints have the same weights serialized.
Because of the redundant serialization of frozen weights often it is very easy to fill the disk space.

**Describe the solution you'd like**
A quick description of how it could work: if a part of the model is initialized with `pretrained_file` and it was set `trainable = False` we can skip dumping those weights, as they can be loaded as it was done at the start of the training using `pretrained_file`.

**Comment by brendan-ai2** [comment]
We like this idea, but it's a bit tricky to do in general. In the interim you could try decreasing `num_serialized_models_to_keep` to ensure you don't maintain a copy of BERT for each epoch. If you (or anyone else!) has suggestions for how to practically implement this, we're all ears.

We'll look into some longer term solutions as well. (Perhaps adding a wrapper class that PyTorch doesn't persist?)

**Comment by mahnerak** [comment]
I was thinking about override methods `Module.state_dict()`, `Module._load_from_state_dict()` and `Module.load_state_dict()`, so we can blacklist some modules from being saved and loaded.
Say, if a certain flag is passed to the class `PretrainedBertEmbedder` (just an example, could be any PretrainedLayer), it can prevent `self.bert_model` to be dumped by `state_dict()`. The same with `load_state_dict()`.

The problem is that the `Module._load_from_state_dict()` was implemented not so well. It recursively loads the modules, but the traversal is done by nester helper function `load()` [[Source code]](https://github.com/pytorch/pytorch/blob/76ee02f10d2c936606bebf7f364a56f34a612823/torch/nn/modules/module.py#L820), which handles the loading of children itself. No matter which module is going to be loaded, it was done by `load()` nested of the topmost object's `_load_from_state_dict()`, so overriding custom behaviour in a nice way is nearly impossible. 

A solution can be to move the helper function `load()` out of the `_load_from_state_dict()` in the torch's `Module` so it can be easily altered.

Alternatives include:
* make AllenNLP load the model with `strict=False`, but here we'll miss some very useful checks,
* the first option, but also to check if only whitelisted states are missing (still, I don't think it's a good idea to handle that outside of the `PretrainedBertEmbedder`),
* proxying `PretrainedBertEmbedder._modules` to appear empty for `_load_from_state_dict` somehow, however, I can't come up with how this can be done in an elegant way.

Overall, I think there's a need to remove the nested function from the `_load_from_state_dict`.
What's your thoughts?
