### ISSUE TITLE
Get a specific layer from BERT

### ISSUE THREAD

**Issue by yanaiela** [allenai/allennlp#3197]
Currently it seems that BertEmbedder (https://github.com/allenai/allennlp/blob/master/allennlp/modules/token_embedders/bert_token_embedder.py#L45) returns either Bert's last layer or a ScalarMix between them. Can we add another parameter to the forward function to require a specific layer?

It's not a problem to add this feature (I'll send a PR if this sounds a reasonable feature), just wanted to make sure it won't brake anything.

**Comment by schmmd** [comment]
FDixed by #3199
