### ISSUE TITLE
Textual Entailment

### ISSUE THREAD

**Issue by Manikandan25** [allenai/allennlp#321]
Hi friends,
I'm very impressed by Allennlp. I have question pairs and need to compare those question to make a conclusion whether those questions are in similar meaning or not. For this task, I found Allennlp as very useful. But I just want the textual entailment part of codes. Please someone tell me what are all necessary files and steps to achieve this. If this can't, I want to all the functions and those behaviours in the Allennlp module. Please reply as soon as possible. Thanks in advance.

**Comment by matt-gardner** [comment]
There are some nice tutorials available on [the website](http://allennlp.org/tutorials/installation).  You can also browse the code on github, it should be pretty easy to find where the [model code](https://github.com/allenai/allennlp/blob/master/allennlp/models/decomposable_attention.py) is for the decomposable attention model.  Please ask a more specific question once you've looked over those materials.
