### ISSUE TITLE
Feedforward module not coercing List[str] to appropriate type (e.g. float)

### ISSUE THREAD

**Issue by kernelmachine** [allenai/allennlp#3210]
**Describe the bug**

We should generally be able to pass float parameters (e.g. dropout) as strings, but if you supply a list of dropout values as strings to the `FeedForward` module, you get a TypeError from pytorch. This might affect other modules as well. It's possibly an issue with `construct_arg` (https://github.com/allenai/allennlp/blob/master/allennlp/common/from_params.py#L292) when the type annotation is a Union (in this case, `dropout` is `Union[float, List[float]]`.

**To Reproduce**
```
from allennlp.modules import FeedForward
from allennlp.common import Params
params = Params({
                    'input_dim': 2,
                    'hidden_dims': [3, 4, 5],
                    'activations': ['relu', 'relu', 'linear'],
                    'dropout': ["0.2", "0.2", "0.2"],
                    'num_layers': 3,
                 })

FeedForward.from_params(params)

Traceback (most recent call last):
  File "test_ff.py", line 11, in <module>
    feedforward = FeedForward.from_params(params)
  File "/home/suching/miniconda/envs/allennlp/lib/python3.7/site-packages/allennlp/common/from_params.py", line 389, in from_params
    return cls(**kwargs)  # type: ignore
  File "/home/suching/miniconda/envs/allennlp/lib/python3.7/site-packages/allennlp/modules/feedforward.py", line 65, in __init__
    dropout_layers = [torch.nn.Dropout(p=value) for value in dropout]
  File "/home/suching/miniconda/envs/allennlp/lib/python3.7/site-packages/allennlp/modules/feedforward.py", line 65, in <listcomp>
    dropout_layers = [torch.nn.Dropout(p=value) for value in dropout]
  File "/home/suching/miniconda/envs/allennlp/lib/python3.7/site-packages/torch/nn/modules/dropout.py", line 11, in __init__
    if p < 0 or p > 1:
TypeError: '<' not supported between instances of 'str' and 'int'

```
**Expected behavior**

Construction of feedforward object with List[str] containing floats.

**System (please complete the following information):**
 - OS: Linux
 - Python version: 3.7.3
 - AllenNLP version: master

**Comment by schmmd** [comment]
@kernelmachine @joelgrus wasn't sure why you'd want this.  It's probably worth more discussion before a potential contribution.

**Comment by DeNeutoy** [comment]
this issue is stale, and i'm not sure parsing from strings like this has much value anyway.
