### ISSUE TITLE
Pool the word-piece embeddings of BERT per original token?

### ISSUE THREAD

**Issue by RikVN** [allenai/allennlp#3212]
Hi,

I want to encode my input sentences as combination of characters and words, using BERT for the word representation. What I want to is have a single representation per original word, e.g. the concatenation of character representation (CNN) and the BERT representation, and feed those in a different encoder.

This seems to work! However, I noticed that if BERT splits a word (e.g. playing to play ##ing) I can only get the representation of "play" or the representation of "##ing" to concatenate to my char vector. This can be done by using "use_starting_offsets" : true/false.

However, I would like to change this to an average or max pooling of the two vectors of play and ##ing, instead of just using a single one. Is there any reason why this is not implemented (assuming that what I said so far is correct)? Because to me it seems you want to include both vectors in your representation.

I looked at the code that implements this. I can see how and where it saves offsets (and I could extend this to give offsets per word), but to be honest I simply just don't understand how they are used here:

https://github.com/allenai/allennlp/blob/master/allennlp/modules/token_embedders/bert_token_embedder.py#L230

Any pointers on how to implement this or answers to my questions are greatly appreciated!

**Comment by schmmd** [comment]
@joelgrus do you have any pointers for @RikVN ?

**Comment by joelgrus** [comment]
I think that in the future we would like to get away from handling this sort of thing altogether, and we are working on a generic embedder that just returns the wordpiece embeddings and that's it.

in the meantime, for your use case, I would probably do the following:

1. don't pass the offsets to the BertEmbedder at all (you can control this using the embedder_to_indexer_map). then you will get back one embedding per wordpiece

2. then in your Model you still have the starting offsets, and so you can use those to combine the wordpiece embeddings however you want: max, average, so on

does that make sense?

**Comment by schmmd** [comment]
After some discussion, we decided that @joelgrus 's suggestion doesn't work in general (it specifically has problems when you have a mismatched tokenizer and embedder).  We're going to keep thinking about it.

**Comment by AsmaZbt** [comment]
> Hi,
> 
> I want to encode my input sentences as combination of characters and words, using BERT for the word representation. What I want to is have a single representation per original word, e.g. the concatenation of character representation (CNN) and the BERT representation, and feed those in a different encoder.
> 
> This seems to work! However, I noticed that if BERT splits a word (e.g. playing to play ##ing) I can only get the representation of "play" or the representation of "##ing" to concatenate to my char vector. This can be done by using "use_starting_offsets" : true/false.
> 
> However, I would like to change this to an average or max pooling of the two vectors of play and ##ing, instead of just using a single one. Is there any reason why this is not implemented (assuming that what I said so far is correct)? Because to me it seems you want to include both vectors in your representation.
> 
> I looked at the code that implements this. I can see how and where it saves offsets (and I could extend this to give offsets per word), but to be honest I simply just don't understand how they are used here:
> 
> https://github.com/allenai/allennlp/blob/master/allennlp/modules/token_embedders/bert_token_embedder.py#L230
> 
> Any pointers on how to implement this or answers to my questions are greatly appreciated!



hello ,
did you find a solution for this ? i'm looking for the same thing

**Comment by matt-gardner** [comment]
This is something that it would be good to implement as options in here: https://github.com/allenai/allennlp/blob/master/allennlp/modules/token_embedders/pretrained_transformer_mismatched_embedder.py.  We haven't done that yet, but you could imagine other pooling operations besides just taking one of the indices.

**Comment by DeNeutoy** [comment]
Not sure this is super valuable to have in the library, if you know you need a different pooling operation it is easy to register your own mismatched pretrained transformer embedder. Closing.
