### ISSUE TITLE
Assume the mapping between indexers and embedders for missing keys in embedder_to_indexer_map

### ISSUE THREAD

**Issue by OfirArviv** [allenai/allennlp#3213]
**Is your feature request related to a problem? Please describe.**
When using `BasicTextFieldEmbedder`, sometimes some of the embeddings require you to use the `embedder_to_indexer_map` param but others do not, which result in unnecessary code.

Example:
This is my token indexers and embedders:
```
word_indexer = {"bert": bert_indexer,
                    "deps": DepLabelIndexer(),
                    "ner": NerTagIndexer(),
                    "pos": PosTagIndexer(),
                    "lang": LanguageIndexer()}

word_embedder = BasicTextFieldEmbedder({"bert": bert_embedder,
                                            "deps": linguistic_features_embedding,
                                            "ner": linguistic_features_embedding,
                                            "pos": linguistic_features_embedding,
                                            "lang": linguistic_features_embedding,
                                            },
                                           {"bert": {"input_ids": "bert",
                                                       "offsets": "bert-offsets"},
                                            "deps": {"inputs": "deps"},
                                            "ner": {"inputs": "ner"},
                                            "pos": {"inputs": "pos"},
                                            "lang": {"inputs": "lang"}},
                                           allow_unmatched_keys=True)
```
Because I want to use word level BERT embedding (and not BERT part of word embedding) I need to pass the `offset` param in the ` embedder_to_indexer_map`.
As a result of that, I need to also pass the mapping for all the other keys even thou their mapping is trivial.

**Describe the solution you'd like**
Combining the the default mapping with the ` embedder_to_indexer_map` mapping. If a key mapping is not in ` embedder_to_indexer_map`, then try to use the default mapping and if that doesn't work then error.

**Describe alternatives you've considered**
More of a **caveat** - I do not use the BERT word splitter but the spaCy one (as far as I understand and see, the word-piece tokenizer is applied by the embedder) because I want to use the SpaCy tokenizer. I found that it doesn't really affect performance as both of the word splitter are pretty much identical (the only different I found is in how they split numbers like '2000'). Thats why I can use the pos and ner indexers together with the BERT one.

**Additional context**
None

**Comment by RikVN** [comment]
I had the same issue, for me it worked to make a small change in basic_text_field_embedder.py. I changed line 104 to this:

if self._embedder_to_indexer_map is not None and key in self._embedder_to_indexer_map: 

instead of this:

if self._embedder_to_indexer_map is not None:

**Comment by schmmd** [comment]
@RikVN we'd love a contribution.  Could you send us a PR with a test case?
