### ISSUE TITLE
Epoch number doesn't update when recovering from a trained model

### ISSUE THREAD

**Issue by vered1986** [allenai/allennlp#3214]
The parameter `epoch_num` passed to the model's forward function is always set to zeros when the training is recovered. 

**Steps**:
1. My model has `epoch_num: List[int] = None` among the arguments of the `forward` function. 
2. I trained it for one epoch, stopped the training, and called the training script again with the `--recover` option.
3. In `forward`, I access `epoch_num[0]`, and it is 0. I expect it to be 1 since the model is in its second training epoch. 

**System**:
 - OS: Linux
 - Python version: 3.7.3
 - AllenNLP version: v0.8.5

Thanks!

**Comment by schmmd** [comment]
Yikes, thanks for reporting this!

**Comment by schmmd** [comment]
Note from issue triage: it's probably set correctly in the trainer, but it's not getting set correctly in the iterator--which should be fixed.

**Comment by DeNeutoy** [comment]
Passing the epoch to the model is deprecated in master due to switching to new data loaders.
