### ISSUE TITLE
where is the output model saved ? 

### ISSUE THREAD

**Issue by rabeehk** [allenai/allennlp#3216]
Hi
I have three questions:
1) lets assume you run this command
allennlp train  training_config/esim.jsonnet --serialization-dir  temp
where is the output model?

2) how I can evaluate as I train the model? so instead of doing
allennlp evaluate model file, how can I do it in one step?

3) where can I see where is the codes for train, and evaluate?

thanks

**Comment by schmmd** [comment]
Hi @rabeehk:

1.  The model is output into your `--serialization-dir` (in your case, `temp`).

2.  What exactly do you want to know while you're training your model?

3.  All our code is on GitHub: https://github.com/allenai/allennlp.  Here's the code for the train command: https://github.com/allenai/allennlp/blob/master/allennlp/commands/train.py
