### ISSUE TITLE
Get top k tag sequences

### ISSUE THREAD

**Issue by mikerossgithub** [allenai/allennlp#3217]
It would be nice to have the ranked choices for sequence decoding. I've done this locally, and can submit a PR if there is interest in my approach (below)

For my local repo, I used this code (which is in turn based on AllenNLP): https://gist.github.com/PetrochukM/afaa3613a99a8e7213d2efdd02ae4762

To use it, you modify a model to take a `top_k=1` parameter in its `__init__`, and then call top-k viterbi during forward if `self.top_k>1` . Then, with the predict command you add `--overrides '{"model": {"top_k": 10}}'` to get the top 10 sequences in your `output_dict`

This does not affect default behavior, and can be run on weight files created before the code change. Would a PR be useful?

**Comment by schmmd** [comment]
@mikerossgithub we'd love a PR!
