### ISSUE TITLE
Can one `Model` have Multiple optimizers

### ISSUE THREAD

**Issue by JackKuo666** [allenai/allennlp#3219]
Thank you for building such a great framework. I recently built a [knowledge distillation model](https://github.com/chengshengchan/model_compression). When building a student model, I need to build two models in one ```Model```[This is one of the two major classes that we usually say that in AllenNLP has to customize implement], one is the teacher model, the other is the student model, andEach model can be trained, updated parameters, and can set their own optimizer, perhaps not enough to understand AllenNLP, can you achieve the function of this multi-optimizer(Or tell me how to achieve this)?

**Comment by schmmd** [comment]
Presently we think this would require a fair amount of hacking of the trainer, but it's hard to give more advice without more details about what you're trying to do.

This might be helpful:

https://github.com/allenai/allennlp/blob/master/allennlp/tests/training/gan_trainer_test.py
https://github.com/allenai/allennlp/blob/master/allennlp/tests/training/gan_callback_trainer_test.py

**Comment by JackKuo666** [comment]
yes,thanks very mach!
