### ISSUE TITLE
cuda out of memory

### ISSUE THREAD

**Issue by kelayamatoz** [allenai/allennlp#322]
Dear All,

I was trying to train the default bidaf model using allennlp. In the default config file, I changed batch_size from 40 to 60 to match the batch size listed in the tensorflow implementation. However, I received an error reporting that: 

RuntimeError: cuda runtime error (2) : out of memory ...

I am wondering that if you have run into similar issue before with batch_size = 60? I'm using a K80 for training on google cloud.

Thanks!

**Comment by matt-gardner** [comment]
Yeah, it's set to 40 because it runs out of memory with 60.  We use K80s also, on EC2.  We don't do any truncation in our implementation, while the original implementation truncated the passages to avoid running out of memory.

**Comment by Swathygsb** [comment]
I am getting CUDA out of memory on 2nd iteration itself. I am running on AWS p2.xlarge instance. Probably a Tesla k80 gpu, but not utilizing the entire 24 GiB. Any suggestions or idea?
