### ISSUE TITLE
about the single test file test for Generating model predict

### ISSUE THREAD

**Issue by JackKuo666** [allenai/allennlp#3220]
**Describe the bug**
Thank you very much for providing such a great framework.
 We know that the generated model is randomly generated at the time of prediction (at least in my model). When I am writing a single test file for a generating model, I want to use ```ensure_model_can_train_save_and_load()``` under the file [model_test_case.py](https://github.com/allenai/allennlp/blob/master/allennlp/common/testing/model_test_case.py) , but the prediction of the two inputs of this function test must be consistent,
```
# Both outputs should have the same keys and the values for these keys should be close.
        for key in model_predictions.keys():
            self.assert_fields_equal(model_predictions[key],
                                     loaded_model_predictions[key],
                                     name=key,
                                     tolerance=tolerance)
```
 which brings difficulties to my unit test, because my prediction has a certain randomness, I know that I can rewrite this part of the code, but reporting a bug hopes to bring you more improvements.

**Comment by schmmd** [comment]
Thanks @JackKuo666, but I think `ensure_model_can_train_save_and_load` is working as designed.  Perhaps we could document it better, or we could include a separate method that tests whether a model can save or load without crashing (and ignoring equality).

**Comment by matt-gardner** [comment]
What's the source of randomness?  I would expect that `model.eval()` (which we call) should remove all sources of randomness.  If that's not true, you're going to have, e.g., dev and test metrics that are not consistent across runs, which is pretty unfortunate.

**Comment by JackKuo666** [comment]
for example,in the method `forward` of a `Model`:
normally，there is `argmax` follow the `sotfmax`:
```
preds = torch.softmax(preds, dim=1) 
pre_one_word = torch.argmax(preds).unsqueeze(0)
output_dict = {"pre_one_word": pre_one_word}
```
but, I want a Sampling function `torch.multinomial` follow the `sotfmax`:
```
preds = torch.softmax(preds, dim=1) 
pre_one_word = torch.multinomial(preds, num_samples=1)   
output_dict = {"pre_one_word": pre_one_word}
```

**Comment by matt-gardner** [comment]
Hmm, yeah, that test method isn't designed to handle sampling like this.  I'm not convinced yet that we should be supporting this, as it adds a bunch of complexity that isn't needed most of the time.  A pretty simple workaround would be to sublcass our `ModelTestCase` and override `[assert_fields_equal](https://github.com/allenai/allennlp/blob/7cfaab475ccb39d6d59a7c9ce1d7c4d85cb5ae5c/allennlp/common/testing/model_test_case.py#L143)` like this:

```python
def assert_fields_equal(self, field1, field2, name: str, tolerance: float = 1e-6) -> None:
    if name == 'pre_one_word':
        return
    super().assert_fields_equal(field1, field2, name, tolerance)
```

**Comment by JackKuo666** [comment]
Yes, thank you very much, I chose a different method, put this part of the random code in `encode` instead of `Model`, so that `model_test_case` will not detect the error.
