### ISSUE TITLE
How to set the token_type_ids when use  the pytorch-transformers Bert

### ISSUE THREAD

**Issue by bestbzw** [allenai/allennlp#3224]
**Question**
I want to use the Robert model, but i don't know how to set the token_type_ids.
It seems that only feed the token_ids 

```python
@TokenEmbedder.register("pretrained_transformer")
class PretrainedTransformerEmbedder(TokenEmbedder):
    """
    Uses a pretrained model from ``pytorch-transformers`` as a ``TokenEmbedder``.
    """
    def __init__(self, model_name: str) -> None:
        super().__init__()
        self.transformer_model = AutoModel.from_pretrained(model_name)
        # I'm not sure if this works for all models; open an issue on github if you find a case
        # where it doesn't work.
        self.output_dim = self.transformer_model.config.hidden_size

    @overrides
    def get_output_dim(self):
        return self.output_dim

    def forward(self, token_ids: torch.LongTensor) -> torch.Tensor:  # type: ignore
        # pylint: disable=arguments-differ
        return self.transformer_model(token_ids)[0]
```

**Comment by joelgrus** [comment]
it looks like you provide it here:

https://github.com/huggingface/pytorch-transformers/blob/master/pytorch_transformers/modeling_bert.py#L584

?

**Comment by matt-gardner** [comment]
Yeah, I know that, what I don't know is where the token type ids are computed.

**Comment by maksym-del** [comment]
Hi @matt-gardner, 

looks like it happens here: [segment_ids](https://github.com/huggingface/pytorch-transformers/blob/5a49b793d95042ca1a371cda6f8e2ed489eb319a/examples/utils_glue.py#L456).

**Comment by mikerossgithub** [comment]
In case it is helpful for anyone else, here is the interim fix I am currently using (for Bert only):

Replace this line:
https://github.com/allenai/allennlp/blob/3e0bad4a0a17647bb4f4276d1ee7512918c61753/allennlp/data/token_indexers/pretrained_transformer_indexer.py#L80
With this:
```
result = {index_name: indices}
result.update(_guess_additional_indices(index_name, tokens))
return result
```
And add this function in the same file:
```
def _guess_additional_indices(index_name: str, tokens) -> Dict[str, List[str]]:
    if 'bert' in index_name:
        type_ids = []
        type_id = 0
        for token in tokens:
            type_ids.append(type_id)
            if token == '[SEP]':
                type_id += 1
        return {f'{index_name}-type-ids': type_ids}
    else:
        return {}
```

**Comment by matt-gardner** [comment]
Thanks @maksym-del, that is in a place I didn't really expect.  And it looks like there isn't logic that we can just re-use here, unfortunately.  But we do have a method to compute these segment ids ourselves already.  It's just too bad that there isn't some API call in the pytorch transformers code, in case there is some difference between the models in how they handle this (or a cap on the number of token type embeddings, etc.).

And thanks for the example code @mikerossgithub.  That solution will definitely require some changes in the model, also.  But something like that is probably the right solution, using our existing code for determining type ids, and adding a flag to the indexer on whether to use the type ids or not (possibly with a "guess" method if the flag is not explicitly passed).

I don't think we're going to get to adding this ourselves anytime soon, but a PR to add this would definitely be welcome!
