### ISSUE TITLE
UnboundLocalError: local variable 'processed_mask' referenced before assignment

### ISSUE THREAD

**Issue by heniotierra** [allenai/allennlp#3225]
I try to run elmo for a simple sentence, using AllenNLP 0.9 and Pytorch 1.2.0, but the script quits with the following error:

> Traceback (most recent call last):
>   File "elmo_tests.py", line 17, in <module>
>     embeddings = elmo(character_ids)
>   File "/home/henio/Projetos/Monografia/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/henio/Projetos/Monografia/env/lib/python3.6/site-packages/allennlp/modules/elmo.py", line 198, in forward
>     mask = processed_mask
> UnboundLocalError: local variable 'processed_mask' referenced before assignment

... which may be something on my side, but since I was unable to diagnose the problem, I decided to look for help.

The problem occurs when I try to run the simple code below:

```
from allennlp.modules.elmo import Elmo, batch_to_ids

elmo_weight_file = 'elmo_pt_weight.hdf5'
elmo_options_file = 'elmo_pt_options.json'

elmo = Elmo(elmo_options_file, elmo_weight_file, 0)

tokenized = [['diferentemente', 'de', 'admirável', 'mundo', 'novo', ',', 'de', 'huxley', ',', 'que', 'aborda', 'também', 'um', 'mundo', 'alienado', ',', 'george', 'orwell', 'escreveu', 'uma', 'obra', 'mais', 'impactante', ',', 'de', 'tirar', 'o', 'fôlego', 'de', 'o', 'leitor', ',', 'mas', 'não', 'por', 'prazer', ',', 'e', 'sim', ',', 'por', 'medo', ',', ',', ',', ',', ',', ',', ',', ',', ',', ',', ',', ',', ',', ',', ',', ',', ',', ',', ',', ',', ',', ',']]

character_ids = batch_to_ids(tokenized)

embeddings = elmo(character_ids)
```

Tested also with allennlp 0.8.5 and pytorch 1.1.0, and had the same result.

Any help is appreciated!

**Comment by DeNeutoy** [comment]
Try:
```
elmo = Elmo(elmo_options_file, elmo_weight_file, 1) # 1 not zero
```

You need to output at least one elmo representation from the module :)

**Comment by heniotierra** [comment]
Oh! Thank you, that did it!
