### ISSUE TITLE
Random Elmo weights

### ISSUE THREAD

**Issue by yanaiela** [allenai/allennlp#3227]
For a baseline I'm working on, I'd like to try and use Elmo with random weights.
I'm aware of the ```apply``` function of pytorch, but it requires to know the internal names of the weights parameter of the different components, and I wondered if this can be avoided.

Any easy way to use Elmo with random weights? 
something such as 
```elmo = ElmoEmbedder(weight_init_fn, cuda_device=cuda_device)```
would be cool

**Comment by matt-gardner** [comment]
@nelson-liu, how did you handle this in what you did?  I forgot.

**Comment by brendan-ai2** [comment]
@nelson-liu suggested the following offline: "I did (2) of what matthewp mentioned---i went to the bilm-tf code, made it generate the elmo hdf5 before any gradient updates, and then just plugged that untrained model into allennlp. See the (small) diff in https://github.com/nelson-liu/bilm-tf/tree/randomly_initialized, last 3 commits"

Copying here for posterity.
