### ISSUE TITLE
Running allennlp command line commands in python script

### ISSUE THREAD

**Issue by aclifton314** [allenai/allennlp#3231]
**System:**
 - OS: Linux pop-os 5.0.0
 - Python version: 3.6.8
 - AllenNLP version: 0.8.5
    I am running this linux VM with the above software versions on a Windows laptop.

**Question**
This is a very basic question. Normally, when I run the evaluation command in the command line it looks something like:
`allennlp evaluate /path/to/model.tar.gz /path/to/json_file`

I was wondering how I might run this command through a python script named, for instance, `evaluate_model.py`

**Comment by joelgrus** [comment]
if you look at `allennlp.commands.evaluate` you can see the code that that command runs and just copy it yourself:

https://github.com/allenai/allennlp/blob/master/allennlp/commands/evaluate.py

you could either import `evaluate_from_args` and call that, or you could do like that code does and call `util.evaluate` (but then you'd have to do more setup yourself)

**Comment by aclifton314** [comment]
@joelgrus Thanks for your response. I must be messing something up. Here is what I have:
`from allennlp.commands.evaluate import evaluate_from_args`
`import argparse`
`allennlp_args = argparse.Namespace()`
`allennlp_args.archive_file = '/path/to/models/bidaf-model-2017.09.15-charpad.tar.gz'`
`allennlp_args.input_file = '/path/to/input/qa_json_file.json'`
`metrics = evaluate_from_args(allennlp_args)`

I get the following error:
`Traceback (most recent call last):`
`  File "/path/to/src/testing_script.py", line 16, in <module>
    metrics = evaluate_from_args(allennlp_args)`
`  File "/usr/local/anaconda3/lib/python3.7/site-packages/allennlp/commands/evaluate.py", line 129, in evaluate_from_args`
`    archive = load_archive(args.archive_file, args.cuda_device, args.overrides, args.weights_file)`
`AttributeError: 'Namespace' object has no attribute 'cuda_device'`


I looked at `evaluate.py` and see that it does require `cuda_device`, among other things. The issue I am having is that I am not sure what these other arguments would be since I run `allennlp evaluate /path/to/models/bidaf-model-2017.09.15-charpad.tar.gz /path/to/input/qa_json_file.json` with no issues in the command line.

**Comment by joelgrus** [comment]
if you look at where those arguments are defined, they all have default values. e.g. for cuda_device the default value is -1. but this is a reason why calling `evaluate` directly might be less clunky

**Comment by aclifton314** [comment]
Would it be correct to say, then, that if I took all the default values (except the positional argument values) found in `add_subparser` and passed those into my `allennlp_args` variable appropriately (as above) that I should effectively get the same output as if I ran the `evaluate` command from the command line? I.e.:
`from allennlp.commands.evaluate import evaluate_from_args`
`import argparse`
`allennlp_args = argparse.Namespace()`
`allennlp_args.archive_file = '/path/to/models/bidaf-model-2017.09.15-charpad.tar.gz'`
`allennlp_args.input_file = '/path/to/input/qa_json_file.json'`
`allennlp_args.cuda_device = -1`
`allennlp_args.overrides = ''`
`etc..`
`metrics = evaluate_from_args(allennlp_args)`

**Comment by joelgrus** [comment]
that's what I would expect to happen, unless there's something non-deterministic about your model

**Comment by aclifton314** [comment]
Ok. I went ahead and tried the procedure above, but I get a:
`AttributeError: 'Namespace' object has no attribute 'weights_file'.`

From `add_subparser` I notice that `--weights-file` argument does not have a default value:
`subparser.add_argument('--weights-file',`
`                               type=str,`
`                               help='a path that overrides which weights file to use')`

I'm not sure if `allennlp evaluate /path/to/models/bidaf-model-2017.09.15-charpad.tar.gz /path/to/input/qa_json_file.json` untars the archived model and obtains the weights file that way but I am not sure what to put as the value for `allennlp_args.weights_file`.
