### ISSUE TITLE
Is span representation  suitable for keywords extraction and chinese word sementation?  

### ISSUE THREAD

**Issue by Jiakui** [allenai/allennlp#3240]
Hi ,

I thinks span representation is a great idea. Do you think the span representation is suitable for keywords extraction and chinese word sementation?

Thanks!

**Comment by DeNeutoy** [comment]
Hi! Certainly for keyword extraction, that seems like a good idea. But for word segmentation, you'd typically use a sequence tagging model. Hopefully that helps - as this is more of a question than an issue, i'm going to close this, but please open a new issue if you get stuck using allennlp.
