### ISSUE TITLE
reading comprehension: improving response time of predictor function

### ISSUE THREAD

**Issue by rrrepos** [allenai/allennlp#3241]
I have been using the reading comprehension module and find it producing relevant results on some educational content I have been testing on. Thanks team!

On my local machine, Mac 1.4Gz i5 4GB machine, the predictor function takes over 20 seconds on a passage of about 50 sentences. I would like to move this to a cloud environment and would like the response time per query to be a few seconds. Is there any recommended architecture suggested? No of cores or RAM. Which would be more effective?

The way I am imagining the use-case is: the user selects a topic from one of many available and asks a relevant question. Thanks.

**Comment by brendan-ai2** [comment]
If you aren't running on a GPU, we definitely expect pretty high latency. You should look into using one if at all possible. When doing so we also recommend batching your input. Appropriately sized and this will be about as fast as processing a single instance.

**Comment by rrrepos** [comment]
Thanks @brendan-ai2 I was planning to use a GPU. What did you mean by batching? In my use-case, the user will pose one question => wait for the response => then pose another question. Purely, in terms of code, we still need to pass the passage and question string with every request, is it not?

**Comment by brendan-ai2** [comment]
Ah, if your use case is interactive, then batching isn't relevant. (Batching is simply grouping multiple inputs together to take advantage of the GPUs parallelism. It's done by default in AllenNLP. Search for "batch" on https://github.com/allenai/allennlp/blob/master/tutorials/getting_started/predicting_paper_venues/predicting_paper_venues_pt1.md, for instance.)

If you test on a GPU, what speed do you get?
