### ISSUE TITLE
RuntimeError: [enforce fail at CPUAllocator.cpp:56]

### ISSUE THREAD

**Issue by heniotierra** [allenai/allennlp#3243]
I'm trying to use Elmo to use pre-trained embeddings for transfer leaning to another NN. I'm new in the field of NN, and have never tried Elmo before. So far, I'm trying to load my dataset into Elmo to create the embedder network, however, I always run into errors of resource allocation. I'm doing this on an i7 CPU, 16GB RAM + 10GB of swap area, and don't understand why this error occurs. The process starts, but fails after 8 minutes. I am probably doing something stupid.

I'm using the code below to load the data into Elmo:
```
# df_trn['SentimentText'] is my whole dataset, which is about 12100 sentences big

character_ids = batch_to_ids(df_trn['SentimentText'])

elmo = Elmo(elmo_options_file, elmo_weight_file, 2, dropout=0)

embeddings = elmo(character_ids)
```

This is the stack trace of the error:
> ---------------------------------------------------------------------------
> RuntimeError                              Traceback (most recent call last)
> <ipython-input-1-62ae24fdc5e9> in <module>
>      92 elmo = Elmo(elmo_options_file, elmo_weight_file, 2, dropout=0)
>      93 
> ---> 94 embeddings = elmo(character_ids)
>      95 
>      96 print(embeddings)
> 
> /usr/local/etc/Monografia/env/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
>     491             result = self._slow_forward(*input, **kwargs)
>     492         else:
> --> 493             result = self.forward(*input, **kwargs)
>     494         for hook in self._forward_hooks.values():
>     495             hook_result = hook(self, input, result)
> 
> /usr/local/etc/Monografia/env/lib/python3.6/site-packages/allennlp/modules/elmo.py in forward(self, inputs, word_inputs)
>     167 
>     168         # run the biLM
> --> 169         bilm_output = self._elmo_lstm(reshaped_inputs, reshaped_word_inputs)
>     170         layer_activations = bilm_output['activations']
>     171         mask_with_bos_eos = bilm_output['mask']
> 
> /usr/local/etc/Monografia/env/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
>     491             result = self._slow_forward(*input, **kwargs)
>     492         else:
> --> 493             result = self.forward(*input, **kwargs)
>     494         for hook in self._forward_hooks.values():
>     495             hook_result = hook(self, input, result)
> 
> /usr/local/etc/Monografia/env/lib/python3.6/site-packages/allennlp/modules/elmo.py in forward(self, inputs, word_inputs)
>     603                 type_representation = token_embedding['token_embedding']
>     604         else:
> --> 605             token_embedding = self._token_embedder(inputs)
>     606             mask = token_embedding['mask']
>     607             type_representation = token_embedding['token_embedding']
> 
> /usr/local/etc/Monografia/env/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
>     491             result = self._slow_forward(*input, **kwargs)
>     492         else:
> --> 493             result = self.forward(*input, **kwargs)
>     494         for hook in self._forward_hooks.values():
>     495             hook_result = hook(self, input, result)
> 
> /usr/local/etc/Monografia/env/lib/python3.6/site-packages/allennlp/modules/elmo.py in forward(self, inputs)
>     342         """
>     343         # Add BOS/EOS
> --> 344         mask = ((inputs > 0).long().sum(dim=-1) > 0).long()
>     345         character_ids_with_bos_eos, mask_with_bos_eos = add_sentence_boundary_token_ids(
>     346                 inputs,
> 
> RuntimeError: [enforce fail at CPUAllocator.cpp:56] posix_memalign(&data, gAlignment, nbytes) == 0. 12 vs 0

Any help is appreciated.

EDIT: found some advice on using PretrainedModelInitializer for pre-trained weights.

**Comment by brendan-ai2** [comment]
Hi @heniotierra, fortunately this error has an easy fix. You simply need to break your dataset into batches. 12k sentences is far too many for one batch. Generally you'll need to do some tuning to find the right batch size. If you're just trying to generate the ELMo embeddings (for dumping to a file) I'd suggest using the tool available at https://github.com/allenai/allennlp/blob/master/allennlp/commands/elmo.py which has a default batch size of 64.

Otherwise, if you're intending to use ELMo in a model directly, you should learn about our `Iterator` abstraction which is responsible for creating batches. I'd suggest you take a look at one of our tutorials for this.

For instance: https://github.com/allenai/allennlp/blob/master/tutorials/getting_started/predicting_paper_venues/predicting_paper_venues_pt1.md
https://allennlp.org/tutorials

Good luck!

**Comment by heniotierra** [comment]
Thank you for the help, @brendan-ai2 !

This thing is quite convoluted, and I am still having some hard times around the API, but I think I will get the hang of it. :)
