### ISSUE TITLE
Machine comprehension gets wrong answers with conversations (2 People) as input

### ISSUE THREAD

**Issue by Slartibart-fast** [allenai/allennlp#3245]
I have been using the machine comprehension module with conversations (2 people) as input. The input context is something like "I have collided with an iceberg. Are you still under command? Yes." etc... . 

If I now try to predict the answer to the question already asked in the context ("Are you still under command?") I of course want it to get "Yes" as an answer. But this does not work at all, it just gives some other span as best answer. Is there something I can do about it or is there a certain data set that I could train the network on which includes those problems in the training data?

I'd be really grateful if somebody could help me!

**Comment by DeNeutoy** [comment]
Hi! The question answering model is trained on wikipedia data, so it is unlikely that it would work with conversational data. It also seems that you could detect the answers just by taking the following statement in the conversation? You could also check out this dataset: https://stanfordnlp.github.io/coqa/ - some of the models trained on that might be more suitable? However i don't know that we have any of those trained in allennlp unfortunately, sorry!

**Comment by Slartibart-fast** [comment]
Hi DeNeutoy!

Thank you so much for the suggested dataset, Ill definitely give it a go. 
Unfortunately, just taking the following statements does not always work. See the following example:

"Can you repair the car? It depends. With enough time I think I could do it. Also I have run out of doritos"

If I always only take the first statement (here "It depends"), I might not get the desired answer (the second statement in this example). If I take more than 1 statement following the question, I might get non relevant information in the answer (the doritos).

Maybe an allennlp model with the CoQA dataset can do it tough. Thanks again!
