### ISSUE TITLE
request the code of ESIM+ELMo

### ISSUE THREAD

**Issue by rzhangpku** [allenai/allennlp#3249]
In your paper "Deep contextualized word representations", you add ELMo to the ESIM model for the SNLI task. Can you send me the code of ESIM+ELMo? My email is rzhangpku@gmail.com
Thank you very much!

**Comment by DeNeutoy** [comment]
see:
https://github.com/allenai/allennlp/blob/master/training_config/esim_elmo.jsonnet
e.g
`allennlp train /path/to/above/config -s ./tmp_esim`

**Comment by rzhangpku** [comment]
Thanks a lot!

**Comment by 14H034160212** [comment]
> see:
> https://github.com/allenai/allennlp/blob/master/training_config/esim_elmo.jsonnet
> e.g
> `allennlp train /path/to/above/config -s ./tmp_esim`

Hi DeNeutoy, this link looks not working right now. Can you update it? Thanks.

**Comment by matt-gardner** [comment]
ESIM has moved to the [allennlp-models](https://github.com/allenai/allennlp-models) repo.
