### ISSUE TITLE
Is ROPES dataset available ? 

### ISSUE THREAD

**Issue by chiangyulun0914** [allenai/allennlp#3257]
I haven't found the dataset mentioned from Reasoning Over Paragraph Effects in Situations, Lin et al., CL-2019. 

Is there any download link for ROPES dataset ?

Thanks for reply.

**Comment by matt-gardner** [comment]
Coming soon.  The paper was just accepted to MRQA, we'll probably update to a camera ready version and include more information, including a webpage / download link / leaderboard / etc.  @kl2806, can you update this issue when we're ready for it?

**Comment by kl2806** [comment]
Yep, I'll update this issue with more information soon.

**Comment by schmmd** [comment]
@kl2806 any update?

**Comment by kl2806** [comment]
We have been actively working on the dataset over the last month; the main page will be on the AllenNLP website (https://allennlp.org/ropes) and I'll update here when it's live.

**Comment by kl2806** [comment]
Please see the allennlp site for the ROPES webpage (https://allennlp.org/ropes).
