### ISSUE TITLE
Wikitables not answering multiple column questions

### ISSUE THREAD

**Issue by SandeepBhutani** [allenai/allennlp#3258]
Hi,
Tried wikitables latest code on following dataset: 
[https://www.kaggle.com/dipam7/student-grade-prediction](https://www.kaggle.com/dipam7/student-grade-prediction)  
Column Names are: `school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian,traveltime,studytime,failures,schoolsup,famsup,paid,activities,nursery,higher,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3`
It was not able to answer few questions. Please let us know, if this is a bug or feature improvement which can be fixed:  

- Who all score above 15 in G1 subject? - if this question is changed to "G1 above 13 names please?" then it works

- What is the total score in all subjects G1,G2,G3 for Gayle Ward? -  this is a case of multiple columns G1, G2, G3 . Some other questions also dont work where multiple columns are involved

- How many female students are aged above 16? - This is a case where multiple columns are involved in calculation - Sex and Age

- Also in above question the Sex contains M and F, but the question contained female . Will allennlp be able to understand this natural inference?

- Another question. I am referring here Students, but there is no column named student. Will allen nlp will imply that Name is being referred?

- For how many students does mother acts as a guardian? –If this question was tweaked then it was able to answer - For how many **names** does **guardian** is mother? . I believe allen wiki parser checks the values as input rather than just the column name. 

These seem too many questions, but these are important in practical usage of the product. Will you be able to spare time to answer these please.

**Comment by sandeepbhutani304** [comment]
Hi @pdasigi / @matt-gardner : Do my questions make sense? Can you please help me solving this challenge?

**Comment by matt-gardner** [comment]
This is a statistical model, trained on a particular dataset, built for research purposes.  It is not a product that is intended to be used practically.  If you want to use it practically, you'll want to figure out what it does well and what it doesn't, and probably get your own training data and retrain the model to make it do what you want it to do.  These are things that we unfortunately can't help with.

**Comment by sandeepbhutani304** [comment]
Thanks for reply @matt-gardner  : Do you have any documentation around this model internals and training data used, which help understanding the working of wikitables.  
Are these right link to follow: [https://ppasupat.github.io/WikiTableQuestions/](https://ppasupat.github.io/WikiTableQuestions/) , 
[https://nlp.stanford.edu/software/sempre/](https://nlp.stanford.edu/software/sempre/)  , 
[https://arxiv.org/pdf/1309.4408.pdf](https://arxiv.org/pdf/1309.4408.pdf)

**Comment by matt-gardner** [comment]
The first link is good.  The second two are older; we don't use SEMPRE or lambda-DCS anymore.  The model that's in our demo comes directly from this paper: https://www.semanticscholar.org/paper/Iterative-Search-for-Weakly-Supervised-Semantic-Dasigi-Gardner/af17ccbdae4cbd1b67d6ab359615c8000f8fb66f.  There are some relevant citations in that paper that you might want to follow if you're not familiar with them (e.g., the MAPO paper that defines the language that we use instead of lambda-DCS).
