### ISSUE TITLE
Fine-tuning models

### ISSUE THREAD

**Issue by matt-gardner** [allenai/allennlp#326]
We don't currently have a good way to fine-tune a trained model on a new dataset.  See https://github.com/allenai/allennlp/issues/239#issuecomment-329807455 for some discussion of this, and the rest of that issue for some context.

One way to make this work is to just allow for a `model_archive` parameter instead of `model`, or allow the `model` parameter to trainer to be a string path instead of a json object, and we take the path to be a model archive.  And if we're loading an archived model, we need to treat the vocabulary creation a little differently.

**Comment by ajay01994** [comment]
generally the answers given by ALLEN /NLP (MACHINE COMPREHENSION ) are one word answers , i tested it side by side Vs  FACEBOOK -Dr -Q/A  model . in which Dr-Q/A gave better results on the same sample data , can we work on improving its efficiency and focussing also on more than one word answers , may be one line or couple of lines of answers ,depending on the Type of questions .....

**Comment by kearnsw** [comment]
Is this issue solved by #880, or is there additional work that needs to be done?

**Comment by matt-gardner** [comment]
Yeah, this is done, thanks for pointing that out.
