### ISSUE TITLE
How to correctly use lazy dataset readers and make-vocab command

### ISSUE THREAD

**Issue by Varal7** [allenai/allennlp#3261]
**Question**

Hi, I was wondering what's the correct way to use lazy dataset readers along with the make-vocab command. 

Currently, my workflow is to run `make-vocab` once, store it in a `vocab` serialization dir. Then, whenever I need to run an experiment, run the `train` command, abort it. Copy the `vocab/vocabulary` folder in the new serialization dir, then re-run `train` with the`--recover` flag. Is that the current way of doing things?

Ideally, I would want to define the path to `vocab/vocabulary` in my training config so that `trainer_pieces.py` loads it from there. 

I'd be happy to start a PR to add this feature, but I just wanted to make sure I didn't miss something first.

**Comment by DeNeutoy** [comment]
Hi, you can specify a path in a top level `vocabulary` key in your config like so:

```
"vocabulary": {
	"directory_path": "/path/to/vocab/folder"
}

```

I essentially use the same workflow to generate the vocab, but then use this instead of `--recover`. Admittedly this is a bit hard to discover, sorry about that!

**Comment by Varal7** [comment]
Oh, that makes sense! Thanks!
