### ISSUE TITLE
DROP Evaluation - Wrong Partition to Types

### ISSUE THREAD

**Issue by eladsegal** [allenai/allennlp#3262]
In https://github.com/allenai/allennlp/blob/master/allennlp/tools/drop_eval.py#L193, max_type can be updated even though it might not be the best match.

For example, if `candidate_answers` has `number: 5` and `spans: ["7-meters"]` in that order and the prediction is `"5-yard"` then we get the following scores per each answer:
- `number: 5`: `em: 0`, `f1: 0.67`
- `spans: ["7-meters"]`: `em: 0`, `f1: 0`

and the max_type will be `span` instead of `number`.

I assume that the original intent for the condition was to have `and` instead of  `or`.
https://github.com/allenai/allennlp/pull/3263 fixes the issue.

**Comment by schmmd** [comment]
Fixed by #3263.  Thanks!
