### ISSUE TITLE
Cannot find token_characters vocabulary? (squad reader)

### ISSUE THREAD

**Issue by jammygrams** [allenai/allennlp#3264]
**System (please complete the following information):**
 - OS: Linux Ubuntu 16.04
 - Python version: 3.6.7
 - AllenNLP version: 0.8.4

**Question**
I'm trying to inspect the character-level token (e.g. 'a','b','c') to index (e.g. 1, 2,3) mapping as part of a vocabulary created using the squad reader. Though the final batched data has a token_characters field (with indexed characters), and there's no problem in training, I can't figure out where to inspect this mapping.

[I understand from this issue](https://github.com/allenai/allennlp/issues/608) that index fields don't necessarily show up as namespaces in the vocabulary.   Is there another easy way to inspect this mapping?

Example code below:
```
import logging
logging.basicConfig(level=logging.INFO)

from allennlp.common.params import Params
from allennlp.data.dataset_readers.dataset_reader import DatasetReader
from allennlp.data.vocabulary import Vocabulary

params = {
  "dataset_reader": {
    "type": "squad",
    "token_indexers": {
      "tokens": {
        "type": "single_id",
        "lowercase_tokens": True
      },
      "token_characters": {
        "type": "characters",
        "character_tokenizer": {
          "byte_encoding": "utf-8",
          "start_tokens": [259],
          "end_tokens": [260]
        },
        "min_padding_length": 5
      }
    }
  },
  "train_data_path": "https://s3-us-west-2.amazonaws.com/allennlp/datasets/squad/squad-train-v1.1.json",
  "validation_data_path": "https://s3-us-west-2.amazonaws.com/allennlp/datasets/squad/squad-dev-v1.1.json"}

params = Params(params)

reader = DatasetReader.from_params(params["dataset_reader"])
train_data = reader.read(params["train_data_path"])
val_data = reader.read(params["validation_data_path"])

vocab = Vocabulary.from_instances(train_data + val_data)
```

`vocab.__str__()` returns : `Vocabulary with namespaces:  tokens, Size: 97374 || Non Padded Namespaces: {'*labels', '*tags'}`

`vocab.get_token_to_index_vocabulary("token_characters")` returns `{'@@PADDING@@': 0, '@@UNKNOWN@@': 1}`

**Comment by matt-gardner** [comment]
You can see in the config that the character tokenizer is using UTF-8 byte encoding.  This means that the words are encoded into a sequence of UTF-8 bytes, then represented using those integers.  No vocabulary is required.

**Comment by jammygrams** [comment]
Thanks for the quick response - so that means the start token [259] is the same as 'LATIN SMALL LETTER A WITH BREVE' and end token [260] is the same as 'LATIN CAPITAL LETTER A WITH OGONEK', e.g. as listed here https://www.w3schools.com/charsets/ref_utf_latin_extended_a.asp?

**Comment by matt-gardner** [comment]
No, it's [UTF-8 encoding](https://en.wikipedia.org/wiki/UTF-8), meaning all unicode characters are encoded into a sequence of bytes (with integer values less than 256).  259 and 260 are above the 256, and are added as special characters (so, yeah, in some sense this is the "vocab" of the model, it's just hard-coded in those numerical values passed in as start and end tokens).  The embedding matrix is also given a fixed number of embeddings, as you can see in the config file.
