### ISSUE TITLE
Quac Model Prediction Input Format

### ISSUE THREAD

**Issue by Slartibart-fast** [allenai/allennlp#3274]
Say I have the following conversation as context:

--------------------------------------------
"My position bearing 137 degrees from the northern lighthouse, distance 2.4 nautical miles. I have collided with an iceberg."

"Ok, can you report damage?" 

"I have damaged the ship's side below waterline. I am not in command anymore."

"Can you proceed?"

"No."

--------------------------------------------

And I want to predict the following answers to the following questions:

"What happened?" -> I have collided with an iceberg
"Are you still in command?" -> no
"Can you proceed?" -> no
"What is the weather like?" -> CANNOTANSWER

The format for the input file when using the predict command on a trained quac model then must be something like the following as a json-line, right?

--------------------------------------------
`{
  "paragraphs": [
    {
      "context": "My position bearing 137 degrees from the northern lighthouse, distance 2.4 nautical miles. I have collided with an iceberg. Ok, can you report damage? I have damaged the ship's side below waterline. I am not in command anymore. Can you proceed? No. CANNOTANSWER",
      "qas": [
        {
          "yesno":,
          "question": "What happened?",
          "answers": [
            {
              "text":,
              "answer_start":
            }
          ],
          "followup": "n",
          "id": "0q#0"
        },
        {
          "yesno":,
          "question": "Are you still in command?",
          "answers": [
            {
              "text":,
              "answer_start":
            }
          ],
          "followup":,
          "id": "0q#1"
        },
        {
          "yesno":,
          "question": "Can you proceed?",
          "answers": [
            {
              "text":,
              "answer_start":
            }
          ],
          "followup": "n",
          "id": "0q#2"
        }
        {
          "yesno": "",
          "question": "What is the weather like?",
          "answers": [
            {
              "text": "",
              "answer_start":
            }
          ],
          "followup": "",
          "id": "0q#3"
        }
      ],
      "id": "0"
    }
  ]
}`

--------------------------------------------

But here is my problem: 

Since I want to predict the outcome, I of course do not know the answers to the questions yet. But I also cant leave the answer (and yesno) fields empty without causing an error. Do I have to use a different input format? Or am I misunderstanding the use of this model in some way?

**Comment by se4u** [comment]
@Slartibart-fast could you report back here how you solved this issue please.

Thanks.
