### ISSUE TITLE
Speedup of softmax

### ISSUE THREAD

**Issue by nicolabertoldi** [allenai/allennlp#3280]
I saw you worked on adaptive softmax, and I am very interested in having adaptive_softmax in the transformer decoder.

Which is the status of your work?

More in general I would like to have a method which speedup the inference time of the transformer architecture.
Could you please give me any hints?

**Comment by matt-gardner** [comment]
I don't think any of us here are working on having an adaptive softmax in the library, nor on inference time improvements for transformers.  We'd be happy to have contributions along these lines, but they are not things that we are likely to do ourselves.
