### ISSUE TITLE
A mistake on annotation

### ISSUE THREAD

**Issue by entslscheia** [allenai/allennlp#3286]
In line 63, it's said that `Our decoder input will be the concatenation of the decoder hidden state and the previous action embedding`. But I think it should be the concatenation of the attended encoder hidden states (or simply the attended questions) and the previous action embedding. I don't think it makes sense for you to concatenate the decoder hidden state and the action embedding as the input to next time step, and in fact you didn't do this in your code, so I believe it's just an annotation issue.

**Comment by matt-gardner** [comment]
Yep, you're right. Care to submit a PR to fix this?

**Comment by entslscheia** [comment]
> Yep, you're right. Care to submit a PR to fix this?

Just submitted a PR.
