### ISSUE TITLE
Obtaining elmo embeddings

### ISSUE THREAD

**Issue by aclifton314** [allenai/allennlp#3292]
**System:**
    OS: Linux pop-os 5.0.0
    Python version: 3.6.8
    AllenNLP version: 0.8.5
    I am running this linux VM with the above software versions on a Windows 10 laptop.

**Question**
Is it possible to obtain the elmo embeddings from allennlp to, say, calculate the cosine similarity between two words?

**Comment by matt-gardner** [comment]
Yes, it is!  See here: https://github.com/allenai/allennlp/blob/master/tutorials/how_to/elmo.md.
