### ISSUE TITLE
WikiTableQuestions lambda-DCS grammar is missing

### ISSUE THREAD

**Issue by entslscheia** [allenai/allennlp#3295]
The link provided in [allennlp/tutorials/getting_started/semantic_parsing.md](https://github.com/allenai/allennlp/blob/master/tutorials/getting_started/semantic_parsing.md) that should have directed us to the documentation of how to define the grammar of lambda-DCS is missing now, and I can't find it anywhere.

**Comment by matt-gardner** [comment]
We now have a much better type inference system where you just implement some type-annotated python functions (including functions with learnable parameters, if you want) and we induce a grammar for you.  I haven't yet updated the documentation for this, though.  If you want to use this, for now your best bet is to look at the [docstrings for `DomainLanguage`](https://github.com/allenai/allennlp/blob/c4c532d25e012dbe6ab1ac14bca75e53e0acc621/allennlp/semparse/domain_languages/domain_language.py#L194-L260) and the example domain languages that we have (both in the [main repo](https://github.com/allenai/allennlp/tree/master/allennlp/semparse/domain_languages) and in the [tests](https://github.com/allenai/allennlp/blob/c4c532d25e012dbe6ab1ac14bca75e53e0acc621/allennlp/tests/semparse/domain_languages/domain_language_test.py#L10-L97)).

If you have questions about any of this, feel free to ask them, but they are probably best asked on the new [`allennlp-semparse` repo](https://github.com/allenai/allennlp-semparse).
