### ISSUE TITLE
Getting exact same results running the exact same experiment

### ISSUE THREAD

**Issue by pvcastro** [allenai/allennlp#3298]
**System (please complete the following information):**
 - OS: Linux
 - Python version: 3.6.9
 - AllenNLP version: v0.9.0
 - PyTorch version: 1.2.0

**Question**
Maybe this is actually a fix instead of a problem, but since I updated to AllenNLP v0.9.0, I'm getting the **exact** same results per epoch, when running multiple trainings with the same configuration. I used to do the same thing with previous versions, but results were different for every training, even though those same seeds from allennlp.common.util are set with the same values as always. 

Is this something you guys fixed in v0.9.0? Since you were setting the same seeds in earlier versions, should the results be the same per epoch in previous versions as well? Or is this some sort of bug in v.0.9.0? 

If this is actually the expected behavior, in order to get back to having random results I should set random seeds myself and passing them as those parameters from util.prepare_environment?

I'm attaching a sample of the jsonnet config I'm using.

[sample.txt](https://github.com/allenai/allennlp/files/3667588/sample.txt)

Thanks!

**Comment by matt-gardner** [comment]
This was supposed to be happening the whole time.  We aim for completely identical execution with the same random seed, though that's sometimes really hard to achieve.  There are some modules that are less consistent than others, and it's possible that you were using one of those and something changed in pytorch 1.2 to make them more consistent.  If you want different results in different runs, you should manually change the random seeds (which you can do in a config file).
