### ISSUE TITLE
BucketIterator with default parameters can not pass the ModelTestCase.ensure_model_can_train_save_and_load

### ISSUE THREAD

**Issue by cjopengler** [allenai/allennlp#3299]
**Describe the bug**

Using BucketIterator with default parameters can not pass the ModelTestCase.ensure_model_can_train_save_and_load randomly at 
`        for key in model_batch.keys():
             self.assert_fields_equal(model_batch[key], loaded_batch[key], key, 1e-6)`.

I debug the failed reason used about one day and got the reason finally.

The reason is `padding_noise` parameter default value is 0.1 in BucketIterator. In `BucketIterator._create_batches.sort_by_padding` function,   `padding_noise` will add some random to change the instance weight, that will cause the the same input instances get different sorted result. So in ModelTestCase will fail at ` self.assert_fields_equal(model_batch[key], loaded_batch[key], key, 1e-6)` randomly.

Although, I got the reason, I don't know how to fix. I think may be some fixed strategy as flow:

1. Fixed at ModelTestCase. Check if iterator is `BucketIterator` and then BucketIterator set padding_noise = 0, but now there is no way to set padding_noise = 0 in BucketIterator

2. Fixed when shuffle = False and in _create_batches set padding_noised = 0. May be this is a easy way.

3. BucketIterator.__init__  padding_noise default value is 0 but not 0.1 . I think this is a good way. But document must explain the parameter how to work in ModelTestCase.

The above fixed way, I can not make a decision. So I just only submit the issue and not pull request.

**Comment by matt-gardner** [comment]
The solution here is to use a basic iterator, or set the padding noise to 0, in your test case.  You typically want to have very small models trained on very little data for your test case, then you take that config and change the values to what you actually want them to be when the model passes the tests and you're ready to actually train it on real data.
