### ISSUE TITLE
Put all models into an allennlp-models repo

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp#3302]
We've already started out by breaking out semantic parsing and reading comprehension. 
 Language modeling is underway (owned by Rob Logan, UCI).

We want to make sure and circle back to evaluate how well separate repositories is working for us.

Models to separate:

- [x] Semantic Parsing
- [x] Reading Comprehension
- [x] Language modeling (owned by Rob Logan, UCI)
- [x] Coreference Resolution
- [x] Seq2Seq
- [x] Classification (includes NLI; could also separate that one out)
- [x] Syntax (includes tagging, parsing, SRL)

Additional work to complete:

- [x] Set up CI to maintain backwards-compatibility with model repos.
- [x] Remove allennlp-hub
- [x] update the demo

**Comment by dirkgr** [comment]
I think `reading-comprehension` is finally done, now that `allennlp-hub` also works with it.

**Comment by sai-prasanna** [comment]
I volunteer for `seq2seq`. 

@epwalsh  , if we can collaborate on improving/maintaining this, it would be great.

**Comment by epwalsh** [comment]
@sai-prasanna I'd love to help!

**Comment by schmmd** [comment]
@sai-prasanna @epwalsh awesome!  We would love the help!

We've run into some challenges with having separate repositories for our models and we wanted to take a smaller step first.  Would it work if you split `seq2seq` into a separate pip packed but keep it inside `allenai/allennlp` as a first step?  We would separate out the code into a root-level `allennlp_seq2seq` folder.

**Comment by epwalsh** [comment]
@schmmd seems reasonable! @sai-prasanna what's your week looking like? I'm pretty busy for the first half of the week, but may have time Thurs or Friday.

**Comment by sai-prasanna** [comment]
@epwalsh Thursday or Friday, I may have time. This weekend I will surely have time.

I guess splitting the code and the test is pretty mundane. It might require checking how the other splits have been done. We can put it up at the root level as @schmmd suggested.

Is there anything else to keep an eye out for? If not I can do the boring part and then tag you (@epwalsh) for a review.

**Comment by matt-gardner** [comment]
We had a bunch of discussion offline about how things are working with our current `allennlp-hub`, `allennlp-semparse`, and `allennlp-reading-comprehension` repos.  Our current thought is to simplify the plan to just have two main repos: `allennlp` (with the abstractions / building blocks) and `allennlp-models` (with models that use those building blocks).

`semparse` and `seq2seq` are in a bit of an odd state, in that they also introduce major abstractions of their own, that are pretty separate from the core of allennlp.  My preference would be for one of two options:

1. We have `allennlp-semparse` and `allennlp-seq2seq` as separate repositories containing both the abstractions and the model code.  It's the job of those repos' maintainers (us, or anyone else who takes ownership of them) to worry about any desired upgrades to base allennlp versions, and we don't run any tests for them in our main allennlp CI, ever.  Upgrading to newer allennlp versions might require changes to the code in those repos, but we will try to make those required changes minimal after the 1.0 release.

2. We put the abstractions necessary for semparse and seq2seq into separate repos, but put the models themselves into `allennlp-models`.  We ensure we don't break `allennlp-models` when we run CI on `allennlp`, and these models will be included in that.

My preference would be for the first option.  Any thoughts?

Some additional context on the seq2seq decision: I know that huggingface is working on adding better support for encoder/decoder and generation models.  It's quite possible that we can just piggy-back on whatever they are doing with that, and our existing seq2seq stuff will be obsolete and not worth the effort to maintain.  We might want to wait to make a decision about seq2seq stuff until we see what huggingface puts out.

**Comment by dirkgr** [comment]
This might be clear already to all of you already, but it wasn't to me: We're not talking about the `seq2seq_encoders`. Just the decoders, with various components (models, configs, tests, ...).

**Comment by dirkgr** [comment]
> My preference would be for the first option. Any thoughts?
👍

**Comment by sai-prasanna** [comment]
>     1. We have `allennlp-semparse` and `allennlp-seq2seq` as separate repositories containing both the abstractions and the model code.  It's the job of those repos' maintainers (us, or anyone else who takes ownership of them) to worry about any desired upgrades to base allennlp versions, and we don't run any tests for them in our main allennlp CI, ever.  Upgrading to newer allennlp versions might require changes to the code in those repos, but we will try to make those required changes minimal after the 1.0 release.

1 sounds better. And if huggingface is doing seq2seq, I am ok with defering the decision until then.

@thomwolf What's the roadmap for seq2seq support in transformers? I guess there is a summarization model already in the repo.

**Comment by dirkgr** [comment]
Did you guys get anywhere with this? I'd like to finish this, but I don't want to duplicate anyone else's work.

**Comment by dirkgr** [comment]
This repo is here: https://github.com/allenai/allennlp-models

**Comment by dirkgr** [comment]
Adding new tests is covered in #4080.

**Comment by schmmd** [comment]
@dirkgr can you either close this out or summarize what's left?

**Comment by dirkgr** [comment]
Removing the hub is left. That's all.

**Comment by dirkgr** [comment]
Done!
