### ISSUE TITLE
TokenIndexer: change output type to be scoped per indexer

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp#3304]
each `TokenIndexer.tokens_to_indices` produces an output `Dict[str, List[TokenType]]`, since e.g. a wordpiece indexer may produce both wordpiece_ids and offsets.

For historical reasons, `TextField.as_tensor_dict` takes the index-dictionaries from each of its token indexers and _flattens_ them into a single dictionary. This requires the confusing `embedder_to_indexer_map` in the config, because we lose the association between the indices and the indexer they came from.

A likely better design would be to keep the dictionaries separate and just hand them to the corresponding token embedders as is. This obviates the need for the embedder_indexer_map or allow_unmatched_keys. However, it is a breaking change (as it changes the tensor representation of a text field), and we'll have to be a little bit thoughtful about e.g. how to specify that we don't want offsets (that's probably a change to the token indexer)

**Comment by matt-gardner** [comment]
I will start on this tomorrow.

**Comment by matt-gardner** [comment]
Fixed by #3597.
