### ISSUE TITLE
Initial release of the AllenNLP course

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp#3306]
We would like to release some initial chapters for the AllenNLP course corresponding with the 1.0 release.

**Comment by mhagiwara** [comment]
👀

**Comment by mojesty** [comment]
Hello! Do you have any information about approximate course release timing? Thanks!

**Comment by matt-gardner** [comment]
Not firm release date yet, but we are getting close to having enough for an initial release.  Our plan is to release an initial version before the end of March, though it's possible it's sooner than that.
