### ISSUE TITLE
What happened to the pretrained models web-page?

### ISSUE THREAD

**Issue by yanaiela** [allenai/allennlp#3311]
I remember there was a page on the website for all the pretrained models - https://allennlp.org/models
It was also referenced in some docs such as:
https://github.com/allenai/allennlp/blob/master/tutorials/getting_started/using_pretrained_models.md

Are these models still available? Is there a new place where these can be found?

**Comment by schmmd** [comment]
This content moved to the demo--so it's alongside the models we showcase.  See the "usage" tab on a particular model.  https://demo.allennlp.org/reading-comprehension

Let us know if you have further questions!

![image](https://user-images.githubusercontent.com/954798/65984076-cde03a00-e433-11e9-835c-a4afc74f125a.png)
