### ISSUE TITLE
What is the input data format for the language model training? 

### ISSUE THREAD

**Issue by Huijun-Cui** [allenai/allennlp#3319]
I wanna train a language model with allennlp in my own dataset, but I can't find data format examples for this task , I don't know what is the format for the vocabulary ,  could you give some example data  ?  thank you very much

**Comment by kernelmachine** [comment]
Here's an tutorial of training with the bidirectional language model:
https://github.com/allenai/allennlp/blob/master/tutorials/how_to/training_transformer_elmo.md

**Comment by kernelmachine** [comment]
Closing as this issue has been answered, feeel free to re-open if you have further questions.
