### ISSUE TITLE
Textual Entailment prediction issue

### ISSUE THREAD

**Issue by Manikandan25** [allenai/allennlp#332]
Hi guys,
I want to predict textual entailment between the following sentences.
 1. An interplanetary spacecraft is in orbit around a gas giant's icy moon.
 2.The spacecraft has the ability to travel between planets.
I've installed allennlp in docker and from github too. I've also read the tutorials and guess that I need to use the predict command. Predict command in the tutorial is: 
python -m allennlp.run predict /tmp/tutorials/getting_started/model.tar.gz inputs.t xt
I've modified it into :
python -m allennlp.run predict /tmp/tests/fixtures/decomposable_attention/model.tar.gz input.txt
But I'm getting error as : 
File "/stage/allennlp/service/predictors/predictor.py", line 25, in predict_json
    instance = self._json_to_instance(inputs)
  File "/stage/allennlp/service/predictors/decomposable_attention.py", line 18, in _json_to_instance
    premise_text = json["premise"]
KeyError: 'premise'

Can anyone help me to find the solution, if my process is wrong please guide me to find the solution.  Thanks in advance.

**Comment by joelgrus** [comment]
what's in your `inputs.txt` file?  if you look at the `_json_to_instance` method referenced in the stack trace, it says what format it wants: 

```
{"premise": "An interplanetary spaceship...", "hypothesis": "The spacecraft has ... "}
```

see https://github.com/allenai/allennlp/blob/master/allennlp/service/predictors/decomposable_attention.py#L16
