### ISSUE TITLE
ImportError: cannot import name 'ParsingError'

### ISSUE THREAD

**Issue by entslscheia** [allenai/allennlp#3326]
The traceback of information is as follows:
<img width="1087" alt="QQ20191004-195503@2x" src="https://user-images.githubusercontent.com/15921425/66246242-e1fc9380-e6e0-11e9-9adb-025063e45814.png">

We can see that this error occurs when it tries to `from allennlp.semparse import ParsingError` in `wikitables.py`. But it's weird that this error would only occur for the first time it tried to import ParsingError, which means if you do `from allennlp.semparse import ParsingError` twice, then there will be no error for the second import, and ParsingError can be successfully imported!

**Comment by entslscheia** [comment]
This bug exists both in version 0.8.5 and 0.9.0.

**Comment by matt-gardner** [comment]
I'm pretty sure this is due to some circular imports that we removed when splitting the semparse code into a separate repo.

**Comment by DeNeutoy** [comment]
@entslscheia Please can you give us a bit more info on the traceback there - e.g what command you ran to hit that. Also, this code no longer exists in master, and you will need to use `allennlp-semparse` in future.

**Comment by matt-gardner** [comment]
I think we can just close this.  It's already fixed by splitting out the code.
