### ISSUE TITLE
FBetaMeasure works incorrectly with both average and labels 

### ISSUE THREAD

**Issue by mojesty** [allenai/allennlp#3335]
**Describe the bug**
Suppose I have classification problem with 2 classes of interest and so-called negative class (like O in BIO scheme). I would like to compute f1-micro/macro for all classes of interest except negative class, so assuming that its vocabulary index in target namespace is 0, I want something like this:
In model code:
```
self.metric = FBetaMeasure(
                average='micro',
                labels=list(range(1, self.n_classes))
            )
```
In the `fbeta_measure.py`:
```
def __call__(...):
        ...
        if self._average == 'micro':
            tp_sum = tp_sum.sum()
            pred_sum = pred_sum.sum()
            true_sum = true_sum.sum()
       ...
        if self._labels is not None:
            # Retain only selected labels and order them
            precision = precision[self._labels]
            recall = recall[self._labels]
            fscore = fscore[self._labels]
```
When using sum or mean, we get tensor of size 0 which cannot be further indexed by `self._labels`.
Seems like simply changing order of the snippets above fixes the problem.

I can make a PR that fixes this.

**System (please complete the following information):**
AllenNLP==0.9.0
PyTorch==1.2.0

**Comment by DeNeutoy** [comment]
Yes please, that would be great!

If you could also add a test here which checks for the 0 indexing:

https://github.com/allenai/allennlp/blob/master/allennlp/tests/training/metrics/fbeta_measure_test.py


Thanks!

**Comment by mojesty** [comment]
Made PR #3347, somewhy checks are not ok while tests on my local mahine are OK
