### ISSUE TITLE
An annotation error in linking_transition_function.py

### ISSUE THREAD

**Issue by entslscheia** [allenai/allennlp#3336]
I think the annotation in line 130 of [linking_transition_function.py](https://github.com/allenai/allennlp/blob/master/allennlp/state_machines/transition_functions/linking_transition_function.py) is not correct. The shape of `linked_action_logits` should be `(num_entities, 1)` instead of `(num_question_tokens, 1)` since we are copying from the entities list (columns, rows, cells, numbers, e.t.c) rather than the question tokens.

**Comment by matt-gardner** [comment]
Yes, you are correct.  That's probably a copy-paste error from a long time ago that never got noticed.  PR welcome!

**Comment by entslscheia** [comment]
Ok. I will create a PR.
