### ISSUE TITLE
Create allennlp-hub repo

### ISSUE THREAD

**Issue by matt-gardner** [allenai/allennlp#3351]
We're splitting out the models and dataset readers into task-specific repositories, keeping the core abstractions in a more lightweight main library.  We still want somewhere to go to get all of the pretrained models, though.  We should create a repository called something like AllenNLP Hub that pip installs all of the task-specific repos, then exposes something like our `pretrained.py` and our sniff tests.

The main repo would then pip install the hub during CI, to run the sniff tests periodically and make sure we're not breaking anything downstream.

**Comment by brendan-ai2** [comment]
I've created https://github.com/allenai/allennlp-hub and an (associated build for the sniff tests on Team City)[http://build.allennlp.org/viewType.html?buildTypeId=AllenNLPHub_Master].

The basic functionality works, but there's a bit of cleanup to be done. In particular:

1) Get `allennlp-hub` properly reviewed. I was merging PRs without reviews to quickly debug TC issues.
2) Find/create sniff tests for `allennlp-semparse`. Strangely it looks like the semparse models weren't included in `pretrained.py` even before the sub-repo split, but I may be missing something. 
3) Push some broken code in a few different combinations and verify that the new build catches the bug.

**Comment by brendan-ai2** [comment]
@matt-gardner your advice on 2) would be appreciated! I'm out until Tuesday, but I'll wrap up the remaining pieces then.

**Comment by matt-gardner** [comment]
This is awesome, thanks @brendan-ai2!  You're right that we never had sniff tests for the parsing models, and I'm not really sure why not.

As for adding things, it would be ideal if we didn't have to modify this repo in order to add a new semantic parser to the hub, just add something to a `pretrained.py` in `allennlp-semparse`, or something.  That gets a little magical, though, and might not be easy to accomplish.

One option is to do a named approached, similar `"bert-base-cased"`, where you call `hub.get_model(subrepo, model_name)`.  You don't get the benefits of types and autocomplete when doing it that way, though, which is a nice feature of our current `pretrained.py`.

Probably the right thing to do is just put a few existing models (e.g., ones that were used for papers) into `pretrained.py`, without worrying about setting something similar up in each sub repo.  This is what you've already put in here, it just means adding in a few models from the semparse repo.  Probably the right ones are the models that are serving the semantic parsing demos that we have.

**Comment by matt-gardner** [comment]
@brendan-ai2, can this be closed now?

**Comment by schmmd** [comment]
See github.com/allenai/allennlp-hub
