### ISSUE TITLE
Logging while the log file  handler is closed at program exit in _cleanup_archive_dir

### ISSUE THREAD

**Issue by ajaniv** [allenai/allennlp#3355]
**Describe the bug**
Logging while the log file handle  is  already closed at program exit when using `pytest`
```
--- Logging error ---
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1037, in emit
    stream.write(msg + self.terminator)
  File "/Users/ajaniv/projects/document_management_dev/nlp_analytics/venv/python3.7/lib/python3.7/site-packages/_pytest/capture.py", line 427, in write
    self.buffer.write(obj)
ValueError: I/O operation on closed file
Call stack:
  File "/Users/ajaniv/projects/document_management_dev/nlp_analytics/venv/python3.7/lib/python3.7/site-packages/allennlp/models/archival.py", line 238, in _cleanup_archive_dir
    logger.info("removing temporary unarchived model dir at %s", path)
Message: 'removing temporary unarchived model dir at %s'
Arguments: ('/var/folders/8l/9wcrn_c148sf2td39_89048c0000gn/T/tmpy24sd04k',)
```

**To Reproduce**
Steps to reproduce the behavior
1.  Configure allennlp logging with file and console  logger as the snippet below:
```
'allennlp': {
            'handlers': ['console', 'log_file'],
            'level': LOG_LEVEL_INFO
        }
```
2. Run a simple reading comprehension analysis as per the AllenNLP demo in a python unit test  using `pytest`
**Expected behavior**
No exception should be thrown.

**System (please complete the following information):**
 - OS: OSX
 - Python version: 3.7.2
 - AllenNLP version: allennlp==0.8.5
 - PyTorch version: (if you installed it yourself)
- pytest==5.1.2 

**Additional context**
- Error happens when running unit tests using pytest.  While the unit test passes, at program exit the exception is thrown.
- When running the unit test with 'pytest -s' for immediate output generation the exception is not raised.

[log.txt](https://github.com/allenai/allennlp/files/3729624/log.txt)

**Comment by schmmd** [comment]
@ajaniv where are you putting that logging configuration exactly?

**Comment by ajaniv** [comment]
Thank you for the follow up.
I am attaching the entire python logging configuration  file.
The initialize method is called once during program execution.

**Comment by schmmd** [comment]
@ajaniv thanks--but unfortunately email attachments don't show up in GitHub.  Can you paste it in a comment with instructions for how to use it?  I'm not too familiar with Python logging, but if I'm able to reproduce your error I'll dig in deeper.

**Comment by ajaniv** [comment]
- Attached the log configuration file as per the above request.
- Did further analysis and the root cause is:
a) allennlp logging during program exit handling.
b) usage of pytest, and its buffering of unit test output.
- The exception is eliminated when using pytest -s

**Comment by schmmd** [comment]
Closing as this has to do with a very particular logging configuration interacting with `pytest` capturing output.  We also have a work-around (`pytest -s` to disable capturing).
