### ISSUE TITLE
Improve getting start, end and intermediate tokens in pretrained_transformer_tokenizer

### ISSUE THREAD

**Issue by amarasovic** [allenai/allennlp#3356]
I’m classifying a pair of two sentences using RoBERTa following the [huggingface’s input format](https://github.com/huggingface/transformers/blob/80889a0226b8f8022fd9ff65ed6bce71b60ba800/transformers/tokenization_roberta.py#L93):

`start = [Token('<s>')]`
`sep = [Token('</s>')] `
`seq = start + self._tokenizer.tokenize(sentence1) + sep + sep + self._tokenizer.tokenize(sentence2) + sep`

Tokenizer here is `pretrained_transformer`. I assumed that omitting `start_tokens` and `end_tokens` from the config file will prevent the tokenizer from automatically adding them, but they were added because `roberta-base` contains `bert`. Eventually I prevented adding them by passing an empty list for those parameters.

I don’t think `_guess_start_and_end_token_defaults` is necessary and since it is easy to make a mistake (that won’t result in an error), I think it's better to remove it altogether. 

Btw. since `roberta-base` contains `bert`, `[CLS], [SEP]` will be used for RoBERTa, although huggingface now uses `<s>, </s>`. Not sure how important that is.

**Comment by matt-gardner** [comment]
I would have suggested putting those start and end tokens in the tokenizer, as it gives you flexibility to switch to something new later, without hard-coding the separator tokens.  I think we *should* by default try to do the right thing for any particular input text, we just need to fix it so it doesn't do the wrong thing for some models.  I didn't know what the right sequence was for RoBERTa, and I thought you had an error in your code above at first; it would be nice if it just worked without me having to look up what the right thing to do for RoBERTa was.

One issue in what I see in your code is the in-between separator tokens.  We need to handle this better.  There should be a method on the `tokenizer` that takes a list of texts and adds the right separator tokens (including initial and final tokens).  Not sure what the right name is for this.  But then you don't have to hard-code specific values for these separator tokens, which defeats the whole point of the abstraction.

If we do this right, all you should have to do is `seq = self._tokenizer.tokenize_sentences([sentence1, sentence2])`, and you get `[CLS] SENTENCE1 [SEP] SENTENCE2 [SEP]` for BERT, and `<s> SENTENCE1 </s></s> SENTENCE2 </s>` for RoBERTa.

So, concrete things to fix:
1. Add a `tokenize_sentences` (or similarly named) method that adds separator tokens in between sentences.
2. Fix `_guess_start_and_end_token_defaults` so it does the right thing for more than just BERT.

**Comment by maksym-del** [comment]
There is [this](https://github.com/huggingface/transformers/blob/155c782a2ccd103cf63ad48a2becd7c76a7d2115/transformers/tokenization_utils.py#L797) utility method from huggingface repo that takes indexed sentence (or a pair of sentences) and adds correct special tokens to them (as well as truncating). 

Maybe we could utilize it somehow in the token_indexer so that we do not have to maintain this ourselfs as the new pre-trained models arrive?

**Comment by matt-gardner** [comment]
If there's a way to make this work, I'm definitely in favor of it.
