### ISSUE TITLE
Callback trainer example config file?

### ISSUE THREAD

**Issue by mojesty** [allenai/allennlp#3363]
**System (please complete the following information):**
 - AllenNLP version: v0.9.0

**Question**
I would like to switch from default `Trainer` to `CallbackTrainer` in order to add custom callbacks, and I cannot easily understand how to convert my jsonnets mentioning regular `Trainer` class to the callback-based configs. 
Example config file that provides insights on how to setup different callbacks will be much appreciated!

**Comment by jacobdanovitch** [comment]
It's not a jsonnet (just normal json), but here's a snippet of what I've been using. Don't think I did my checkpointing correctly but the idea is there. 

```javascript
"trainer": {
        "type": "callback",
        "num_epochs": 5,
        "cuda_device": 0,
        "optimizer": {
            "type": "adam",
            "lr": 0.001
        },
        "callbacks": [
            {
                "type": "validate"
            },
            {
                "type": "track_metrics",
                "validation_metric": "+f1"
            },
            {
                "type": "checkpoint",
                "serialization_dir": "my/dir"
            },
            {
                "type": "MyCustomCallback",
               "myarg": "myval"
            }
        ]
    }
```

**Comment by schmmd** [comment]
Closing, as we don't have better examples.
