### ISSUE TITLE
Training config for SRL_BERT

### ISSUE THREAD

**Issue by rizwan09** [allenai/allennlp#3365]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rizwan09** [comment]
The training config for srl bert has not been updated. Would you please update it?

**Comment by DeNeutoy** [comment]
https://github.com/allenai/allennlp/blob/master/training_config/bert_base_srl.jsonnet

In the future, please don't email and open github issues for the same questions - it's spammy. We do check the github issues, so have faith that your question will get answered! 😄
