### ISSUE TITLE
How to visualize the computation graph when using Allennlp?

### ISSUE THREAD

**Issue by entslscheia** [allenai/allennlp#3369]
Are we simply using `add_graph` from `torch.utils.tensorboard`? Does allennlp have its own way to support tensorboard visualization?

**Comment by entslscheia** [comment]
And I think if we are using tesnorboard support for pytorch to visualize the computation graph in allennlp, we are gonna insert `add_graph` inside `trainer.py`. Am I right about that?

**Comment by schmmd** [comment]
@matt-gardner are you able to give @entslscheia any guidance on his question about tensorboard?

**Comment by matt-gardner** [comment]
We haven't done this previously, and when I have visualized computation graphs using tensorboard, I haven't really found it useful, which is probably why we haven't put this functionality in.  If you want to do this, though, it should be pretty easy to add a callback in your code to add the graph, as you suggest.

**Comment by entslscheia** [comment]
> We haven't done this previously, and when I have visualized computation graphs using tensorboard, I haven't really found it useful, which is probably why we haven't put this functionality in. If you want to do this, though, it should be pretty easy to add a callback in your code to add the graph, as you suggest.

I found that this not that simple, because the model in Allennlp is totally different from Pytorch in a way that some tensors are wrapped inside a dictionary. It seems to take a huge effort to get it to work.

**Comment by dhruvdcoder** [comment]
Now the `pytorch.jit.trace` (which what tensorboardX uses to plot the graph) supports dictionaries as input to the model but AllenNLP now uses nested dictionaries for TextFields which again do not work. In any case, is there an easy way (with or without tensorboard) to get a visualization of AllenNLP model architecture? It will be very useful for documentation purposes.

**Comment by entslscheia** [comment]
> Now the `pytorch.jit.trace` (which what tensorboardX uses to plot the graph) supports dictionaries as input to the model but AllenNLP now uses nested dictionaries for TextFields which again do not work. In any case, is there an easy way (with or without tensorboard) to get a visualization of AllenNLP model architecture? It will be very useful for documentation purposes.

I managed to implement the visualization for my own AllenNLP model with some ad-hoc designs, but I found it didn't really help, and the model is not readable at all (I guess maybe this is because PyTorch doesn't really have an explicit way for namespacing different levels of parameters). Anyway, visualizing the computation graphs for PyTorch is not that necessary due to its eager execution feature that allows as to easily debug our model.
