### ISSUE TITLE
Is there any command to monitor memory usage when training a model

### ISSUE THREAD

**Issue by mchari** [allenai/allennlp#3371]
I am using a AWS p2.xlarge EC2 instance (1 GPU, 4 CPUs, 61Gb memory, 12 Gb GPU memory) to train ELMo + bidaf using the jsonnet file https://github.com/allenai/allennlp/blob/master/training_config/bidaf_elmo.jsonnet

I am not using the GPU - as this is my first attempt at training an allennlp model on the SQuAD 1.1 dataset, I wanted to see the minimum system config required to train an ELMo + bidaf model. 
Is there any parameter that I could include in the config file or a command line option to monitor memory usage ? 
Apologies if this question has been already discussed on a separate ticket.

**Comment by mchari** [comment]
P.S. I also added lazy=true in the dataset_reader section....

**Comment by schmmd** [comment]
@mchari I don't know the exact minimal requirements offhand.  While that instance may be sufficient, you might also run out of GPU memory on a K80.  I would recommend using a P100 (not available on AWS) or a V100.

If you're not using the GPU, you should be able to train the BiDAF model on that machine but it might take a very long time.  I ran this once on a P100 for a few days and it still hadn't completed, but it will complete in under 12 hours on a P100.

**Comment by schmmd** [comment]
You can monitor memory usage with `nvidia-smi`.

**Comment by schmmd** [comment]
It looks like we have some functionality here: https://github.com/allenai/allennlp/blob/master/allennlp/training/callbacks/track_metrics.py

**Comment by schmmd** [comment]
Memory is output in the metrics.json which is output when your job is complete.  You can inspect that and then choose the minimal hardware.  It's also in the logs per epoch.
