### ISSUE TITLE
commit #3308 breaks pip install --editable

### ISSUE THREAD

**Issue by mikerossgithub** [allenai/allennlp#3373]
**Describe the bug**
After PR #3308 `pip install --editable` does not work, while it works before that commit. The following error is returned:
```
ERROR: Command errored out with exit status 1:
   command: /venvs/dev/bin/python3.7 /venvs/dev/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpvccnto17
       cwd: /code/allennlp
  Complete output (4 lines):
  Traceback (most recent call last):
    File "/venvs/dev/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 15, in <module>
      from glob import glob
  ModuleNotFoundError: No module named 'glob'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /venvs/dev/bin/python3.7 /venvs/dev/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_whee
l /tmp/tmpvccnto17 Check the logs for full command output.
```
**To Reproduce**
Steps to reproduce the behavior
```
# PR #3308 
git checkout 3dda5ac9
# fails:
pip install --editable .
# prior commit  
git checkout d7b38a89  
# works:
pip install --editable .

```
**Expected behavior**
installation should work

**System (please complete the following information):**
 - OS: Ubuntu 16.04
 - Python version: 3.7
 - AllenNLP version: I installed from master
 - PyTorch version: 1.3

**Additional context**
Running in a virtualenv in a docker container, built from `nvidia/cuda:10.0-cudnn7-devel-ubuntu16.04`

**Comment by schmmd** [comment]
Thanks for reporting.  We'll have to fix forward on this one.

**Comment by schmmd** [comment]
I wasn't able to fix this in a local but fresh Conda environment.  I'll try from `nvidia/cuda:10.0-cudnn7-devel-ubuntu16.04` tomorrow.  My guess is you can just work around this by `pip install glob3`, although I don't see that in my `pip freeze`.

**Comment by mikerossgithub** [comment]
Oddly, installing glob3 (or glob2) has no effect. It looks like the setup is happening in some other python environment (?), but I don't know enough about the setup scripts to know if that makes sense. For what its worth, I tried in virtualenvs with both python 3.6 and python 3.7 and had the same issue. I only tried pip, not conda.

**Comment by schmmd** [comment]
@mikerossgithub try upgrading `pip`.  I suspect it has to do with an older version, since that source file is inside `pip` rather than an `allennlp` dependency.  Many Docker images ship with abysmally old versions of `pip`.

I have:

```
$ pip --version  
pip 19.2.3
```

**Comment by mikerossgithub** [comment]
Thanks for looking into this. Im on 19.3 (also tried 19.3.1). Im using a container which is based on the Nvidia container, but updated with latest pip and python 3.6/3.7 (in virtualenvs). 

Whatever happened in PR #3308 changed this. Since that appears to be a formatting change, my guess is that some sort of formatting also changed the semantics of something involving setup. But that's just a guess.

My workaround is to checkout `v0.9.0`, then `pip install --editable`, then checkout `master`

**Comment by mikerossgithub** [comment]
@schmmd If it would be useful, I can share a dockerfile that reproduces the error.

**Comment by schmmd** [comment]
Uhg--sorry my suggestion didn't help.  If you share a Dockerfile and instructions for how you create your virtualenv I'll look into this further, but I can't promise to resolve it.  Also--I'm on vacation next week.

**Comment by matt-gardner** [comment]
ping @schmmd

**Comment by schmmd** [comment]
@matt-gardner why the ping? I wasn't able to reproduce and an waiting for a Dockerfile to reproduce this issue from @mikerossgithub. Did you run into this same issue?

**Comment by matt-gardner** [comment]
Ah, sorry, I read through too quickly and missed the "if".

**Comment by mikerossgithub** [comment]
@schmmd Sorry I dropped this. I haven't had time to create a dockerfile that disentangles this from some non-shareable code. My work-around above is good enough for now. Should I just close the issue and re-open if/when I have a dockerfile?

**Comment by schmmd** [comment]
Sounds good
