### ISSUE TITLE
TypeError: forward() got an unexpected keyword argument 'labels'

### ISSUE THREAD

**Issue by someAdjectiveNoun** [allenai/allennlp#3377]
Training a BERT model using PyTorch transformers (following the tutorial [here](https://mccormickml.com/2019/07/22/BERT-fine-tuning/)).

Following statement in the tutorial 
`loss = model(b_input_ids, token_type_ids=None, attention_mask=b_input_mask, labels=b_labels)`  
leads to 
`TypeError: forward() got an unexpected keyword argument 'labels'`

Here is the full error,

```
TypeError                                 Traceback (most recent call last)
<ipython-input-53-56aa2f57dcaf> in <module>
     26         optimizer.zero_grad()
     27         # Forward pass
---> 28         loss = model(b_input_ids, token_type_ids=None, attention_mask=b_input_mask, labels=b_labels)
     29         train_loss_set.append(loss.item())
     30         # Backward pass

~/anaconda3/envs/systreviewclassifi/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    539             result = self._slow_forward(*input, **kwargs)
    540         else:
--> 541             result = self.forward(*input, **kwargs)
    542         for hook in self._forward_hooks.values():
    543             hook_result = hook(self, input, result)

TypeError: forward() got an unexpected keyword argument 'labels'

```
I cant seem to figure out what kind of argument the forward() function expects.

There is a similar problem [here](https://github.com/allenai/allennlp/issues/2528), but I still do not get what the solution is.

**System information:**
 - OS: Ubuntu 16.04 LTS
 - Python version: 3.6.x
 - Torch version: 1.3.0 
 - Torch Vision version: 0.4.1
- PyTorch transformers version: 1.2.0

**Comment by schmmd** [comment]
Do you mean to use https://github.com/huggingface/transformers rather than AllenNLP?  Your tutorial (and I think your code) is based on that.

If you'd like to learn more about AllenNLP, please check out our tutorials: https://allennlp.org/tutorials

**Comment by manelAffi** [comment]
hi,
I'm beginner with allennlp. I'm trying to train the simple_seq2seq model for named entity recognition task on the CoNLL 2003 dataset using BERT embeddings. I always get the following error message:

File "/home/manel/anaconda/bin/allennlp", line 10, in
sys.exit(run())
File "/home/manel/anaconda/lib/python3.7/site-packages/allennlp/run.py", line 18, in run
main(prog="allennlp")
File "/home/manel/anaconda/lib/python3.7/site-packages/allennlp/commands/init.py", line 102, in main
args.func(args)
File "/home/manel/anaconda/lib/python3.7/site-packages/allennlp/commands/train.py", line 124, in train_model_from_args
args.cache_prefix)
File "/home/manel/anaconda/lib/python3.7/site-packages/allennlp/commands/train.py", line 168, in train_model_from_file
cache_directory, cache_prefix)
File "/home/manel/anaconda/lib/python3.7/site-packages/allennlp/commands/train.py", line 252, in train_model
metrics = trainer.train()
File "/home/manel/anaconda/lib/python3.7/site-packages/allennlp/training/trainer.py", line 478, in train
train_metrics = self._train_epoch(epoch)
File "/home/manel/anaconda/lib/python3.7/site-packages/allennlp/training/trainer.py", line 320, in _train_epoch
loss = self.batch_loss(batch_group, for_training=True)
File "/home/manel/anaconda/lib/python3.7/site-packages/allennlp/training/trainer.py", line 261, in batch_loss
output_dict = self.model(**batch)
File "/home/manel/anaconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in call
result = self.forward(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'tokens'

System:

OS: ubuntu 18.14
Python version: 3.7
AllenNLP version: 0.9.0
PyTorch version: 1.17.2
here is the config file code:
`{
"dataset_reader": {
"type": "conll2003",
"tag_label": "ner",
"coding_scheme": "BIOUL",

"token_indexers": {
"bert": {
"type": "bert-pretrained",
"pretrained_model": "bert-base-cased",
"do_lowercase": false,
"use_starting_offsets": true
} ,
"token_characters": {
"type": "characters",
"min_padding_length": 3
}

}
},
"train_data_path": "XXXXXXXXXX",
"validation_data_path": "XXXXXXXXXX",
"test_data_path":"XXXXXXXXXX",
"model": {
"type": "simple_seq2seq",

"source_embedder": {

"allow_unmatched_keys": true,
"embedder_to_indexer_map": {
"bert": ["bert", "bert-offsets"],
"token_characters": ["token_characters"],
},
"token_embedders": {
"bert": {
"type": "bert-pretrained",
"pretrained_model": "bert-base-cased",

},
}
},

"encoder": {
"type": "lstm",
"input_size": 768,
"hidden_size": 200,
"num_layers": 2,
"dropout": 0.5,
"bidirectional": true
},

"scheduled_sampling_ratio": 1.0,
"max_decoding_steps": 200,
"target_namespace": "target_tokens",
"attention_function": {"type": "dot_product"}
},
"iterator": {
"type": "basic",
"batch_size": 64
},
"trainer": {
"optimizer": {
"type": "adam",
"lr": 0.001
},
"validation_metric": "+f1-measure-overall",
"num_serialized_models_to_keep": 3,
"num_epochs": 30,
"grad_norm": 5.0,
"patience": 25,
"cuda_device": -1
}
}`

I would like to know if I made a mistake in the json file code or if there
are any ideas how to solve it?

**Comment by gohjiayi** [comment]
This may help future developers facing the same issue. I was developing my own custom DatasetReader to build on a ELMo model following other tutorials. In the parameters .jsonnet the "model" was indicated as "language-model" which i was able to find the [source code in allennlp-models](https://github.com/allenai/allennlp-models/blob/main/allennlp_models/lm/models/language_model.py), and under the `forward` function it indicates the parameters it takes in. For my case the error is resolved after I changed "labels" to "source", I believe this varies for different models.

```
def forward(self, source: TextFieldTensors) -> Dict[str, torch.Tensor]:
    ...
```
