### ISSUE TITLE
Biattentive Classification Network (BCN) implementation of pooled representations

### ISSUE THREAD

**Issue by ksbsk** [allenai/allennlp#3378]
Hi,

I went through [AllenNLP's implementation](https://github.com/allenai/allennlp/blob/master/allennlp/models/biattentive_classification_network.py) of the Biattentive Classification Network ([McCann et al., 2017](https://papers.nips.cc/paper/7209-learned-in-translation-contextualized-word-vectors.pdf)) and a [GitHub thread concerning adding this NN model](https://github.com/allenai/allennlp/pull/1038), but I couldn't find anywhere why `max_pool` and `min_pool` use `integrated_encodings` with replaced masked values to `-1e7` or `+1e7`, respectively.
https://github.com/allenai/allennlp/blob/7afe9712f502dfdc6941bb03d3029a7eb6e0bca9/allennlp/models/biattentive_classification_network.py#L285-L306

@nelson-liu maybe you could shed some light on this, please?
Thanks!

**Comment by nelson-liu** [comment]
Sure. If you have values lower than 0 (in the case of max) or higher than 0 (in the case of min), then the 0 will affect your maxpool / minpool.

For maxpool, by setting all the masked items to a very negative value, we ensure that the masked items won't affect the max.

Accordingly, for minpool, by setting all the masked items to a very positive value, we ensure that the masked items won't affect the min.

Hope that helps! Closing this, but feel free to follow up if you have further questions about this.
