### ISSUE TITLE
Vocabulary token roundtrip bug

### ISSUE THREAD

**Issue by OyvindTafjord** [allenai/allennlp#338]
On a new dataset, I ran into the tokens `'\x0b'` (vertical tab) and, weirdly, `'\x0b '` (with a space behind) which don't roundtrip well when read back from `tokens.txt` (each get read from file as two separate tokens, messing up the indexing).

**Comment by matt-gardner** [comment]
I think we could handle this similarly to how we handle newlines: https://github.com/allenai/allennlp/blob/c6bc7fde370e54312d9fabdeec66818240b6e783/allennlp/data/vocabulary.py#L261

We'd probably want to generalize this into some `sanitize` and `desanitize` methods, with a list of characters to replace and things to replace them with.  Seems pretty easy.

**Comment by OyvindTafjord** [comment]
FWIW, here's the list of character codes (<= 65535) which don't roundtrip properly with the current code: `11, 12, 28, 29, 30, 133, 8232, 8233` (in addition to the `10` already "handled"). Kinda seems like an unexpected "feature" of `.readlines()` (or upstream `.splitlines()`) that this happens?
```
>>> "foo\nbar\x0bxx\x0cyy".splitlines()
['foo', 'bar', 'xx', 'yy']
```

**Comment by OyvindTafjord** [comment]
Simpler fix might be to just read the whole file and do `.split('\n')` only.

**Comment by matt-peters** [comment]
How are these tokens with whitespace passing through the tokenizer anyway?  Most tokenizers will remove them.

**Comment by OyvindTafjord** [comment]
Yes, spacy seems to have some interesting interpretations of these (I'm particularly intrigued by the '\x0b ' one with a space in it!):
```
>>> import spacy
>>> spacy_model = spacy.load("en")
>>> [x.text for x in list(spacy_model("foo bar aa\x0bbb cc\x0b dd"))]
['foo', 'bar', 'aa', '\x0b', 'bb', 'cc', '\x0b ', 'dd']
```

**Comment by matt-peters** [comment]
Ah yes -- this is a hidden "feature" of spacy.  In order to reconstruct the character offsets (I think) it will include tokens that are all spaces.  There is an attribute on the token object `is_space` I usually use to eliminate them.

For example:
```
tokens = [token.text for token in spacy_model(text) if not token.is_space]
```

**Comment by OyvindTafjord** [comment]
Interesting, I see `"  "` (two spaces) tokenizes as `" "` (one space) etc, not that you can reliably reconstruct from just these, as, say, `"foo/bar"` tokenizes to `["foo","/","bar"]` (no negative spaces...), so the utility is a bit unclear to me. We should probably add that `.is_space` filter though.

**Comment by OyvindTafjord** [comment]
Resolve in PR https://github.com/allenai/allennlp/pull/344.
