### ISSUE TITLE
ELMo embeddings and output formats

### ISSUE THREAD

**Issue by aclifton314** [allenai/allennlp#3387]
**System (please complete the following information):**
OS: Linux pop-os 5.0.0
Python version: 3.6.8
AllenNLP version: 0.8.5
I am running this linux VM with the above software versions on a Windows 10 laptop.

**Question**
I am running the following code:
```python
from allennlp.commands.elmo import ElmoEmbedder
import spacy
import numpy as np
question = 'How many cars are in the Target Parking lot?'
nlp = spacy.load('en_core_web_sm')
tmp_q_tokens = nlp(question)
q_tokens = np.array([i.text for i in tmp_q_tokens])
elmo = ElmoEmbedder()
q_embeddings = elmo.embed_sentence(q_tokens)
```
I noticed that `q_embeddings` is a numpy array with first dimension equal to 3. From what I can gather reading the forum, these correspond to the convnn embeddings, the LSTM layer 1 embeddings, and the LSTM layer 2 embeddings (but please correct me on that). I was wondering if there were a way to generate the various output formats (top, average, others?) of the embeddings for a given sentence? 

In particular:
1. What does 'top' and 'average' mean as the output formats?
2. Is it possible to generate those formats for a given sentence?

**Comment by brendan-ai2** [comment]
Hi, @aclifton314,

1) You can see the precise definition here in the code: https://github.com/allenai/allennlp/blob/master/allennlp/commands/elmo.py#L392. Let me know if that's still unclear.

2. Yes. I'd just reuse the code I linked above. Each case is a single line of python, so I'm not sure it's worth making an explicit option here.

Let me know if you have any other questions!

**Comment by aclifton314** [comment]
@brendan-ai2 Thanks for your response. That's exactly what I was looking for!
