### ISSUE TITLE
Interpretation of Open IE output tags

### ISSUE THREAD

**Issue by yuhaozhang** [allenai/allennlp#3392]
I am currently working with the OpenIE predictor in AllenNLP. First thanks a lot for making this tool available!

My questions are regarding the output tag sequence from the OpenIE predictor. For the following example
```
a man in suburban boston is selling snow online to customers in warmer states.
```
, one output tag sequence is the following:
```
'B-ARG0', 'I-ARG0', 'I-ARG0', 'I-ARG0', 'I-ARG0', 'B-BV', 'B-V', 'B-ARG1', 'I-ARG1', 'I-ARG1', 'I-ARG1', 'I-ARG1', 'I-ARG1', 'I-ARG1', 'O'
```

1. While I understand `B-V` indicates the start of a predicate, how should I interpret the tag `B-BV` here?
2. Can I make the assumption that all argument tags with the same number (e.g., `-ARG0`) are consecutive in the output sequence? In other words, can there be other tags in the middle of, say, `ARG0` tags?

**Comment by brendan-ai2** [comment]
@gabrielStanovsky, would you mind taking a look at this question? Thanks!

**Comment by gabrielStanovsky** [comment]
Hi @yuhaozhang, 
1. B-BV indicate the beginning of a prefix to the predicate ("is") in this case.
2. Yes. 

For both of your questions, I suggest you take a look at this repo:
https://github.com/gabrielStanovsky/supervised_oie_wrapper

Which aggregates those output tags into Open IE extractions.

Hope this helps.

**Comment by yuhaozhang** [comment]
@gabrielStanovsky Awesome! Thanks for the helpful pointer! This seems like exactly what I need.

Closing this issue.
