### ISSUE TITLE
Implementation of Sentiment Analysis using AllenNLP on Greek corpora

### ISSUE THREAD

**Issue by lighteternal** [allenai/allennlp#3399]
Hi, 
I am working on a sentiment analysis classification task that will crawl the web for products' reputation/reviews (on Greek) and report the overall sentiment based on them. The crawled data do not have a label/polarity and I don't have a greek annotated sentiment analysis dataset either. 

Given the above, what would you recommend as the most efficient way to take advantage of allennlp models?
I was thinking of a two-step procedure: 1. perform machine-translation from Greek-to-English and 2. use the english allennlp sentiment classifier to extract the sentence's sentiment. Do you think that the above makes sense, or would you go for a different solution?

**Comment by schmmd** [comment]
@lighteternal that makes sense to me and is probably the fastest way for you to get a baseline.  Of course, you probably will lose some precision running the sentiment classifier on translated text--but it's worth trying and seeing how far it gets you.

You should get better performance training a sentiment classifier on Greek, but that's also a lot more work!

**Comment by lighteternal** [comment]
Thank you for the prompt reply, I am indeed following this tutorial here for anyone interested: ( http://www.realworldnlpbook.com/blog/building-seq2seq-machine-translation-models-using-allennlp.html ) to convert greek sentences to english, where the main issue is the limited parallel english-greek text. 
A more reliable alternative would be to leverage a translator API (e.g. google translate) that would provide me with the english equivalents of the original text to be fed to the pretrained english sentiment analysis model.
