### ISSUE TITLE
masked language model implementation ?

### ISSUE THREAD

**Issue by pidugusundeep** [allenai/allennlp#3405]
**Question**

* How do i implement the masked LM(Masked Language Modeling), any samples for the same?

**Comment by Nolence** [comment]
For anyone else curious, it looks like the masked_language_model was moved [here](https://github.com/allenai/allennlp-models/blob/aed4876f04a73c7effddf41b3164e1fb6fb6c275/allennlp_models/lm/masked_language_model.py)

**Comment by Nikeshbajaj** [comment]
Hi, 
I also wanted to use Masked LM, I tried following three archived models, but got error each time. Don't know, what's wrong. If anyone can help out.

#----------------------------------------------------------------------
path1 = "https://storage.googleapis.com/allennlp-public-models/bert-masked-lm-2019.07.25.tar.gz"
BertMLM = Predictor.from_path(path1)

> ConfigurationError: bert-pretrained not in acceptable choices for model.text_field_embedder.token_embedders.bert.type: ['embedding', 'character_encoding', 'elmo_token_embedder', 'empty', 'bag_of_word_counts', 'pass_through', 'pretrained_transformer', 'pretrained_transformer_mismatched', 'language_model_token_embedder', 'bidirectional_lm_token_embedder']. You should either use the --include-package flag to make sure the correct module is loaded, or use a fully qualified class name in your config file like {"model": "my_module.models.MyModel"} to have it imported automatically.

#----------------------------------------------------------------------
path2 = "https://storage.googleapis.com/allennlp-public-models/bert-masked-lm-2019.09.17.tar.gz"
BertMLM = Predictor.from_path(path2)

Some weights of the model checkpoint at bert-base-cased were not used when initializing BertForMaskedLM: ['cls.seq_relationship.weight', 'cls.seq_relationship.bias']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPretraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForMaskedLM were not initialized from the model checkpoint at bert-base-cased and are newly initialized: ['cls.predictions.decoder.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
RuntimeError: Error(s) in loading state_dict for MaskedLanguageModel:
	Missing key(s) in state_dict: "_language_model_head.bert_lm_head.predictions.decoder.bias".

#----------------------------------------------------------------------
path3 = "https://storage.googleapis.com/allennlp-public-models/bert-masked-lm-2020.03.25.tar.gz"
BertMLM = Predictor.from_path(path3)

Some weights of the model checkpoint at bert-base-cased were not used when initializing BertForMaskedLM: ['cls.seq_relationship.weight', 'cls.seq_relationship.bias']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPretraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForMaskedLM were not initialized from the model checkpoint at bert-base-cased and are newly initialized: ['cls.predictions.decoder.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

TypeError: __init__() got an unexpected keyword argument 'model_name'
