### ISSUE TITLE
How to fine-tune BERT SRL using own dataset

### ISSUE THREAD

**Issue by shanalikhan** [allenai/allennlp#3406]
Hi, 
I have run the SRL using BERT model detailed here.

https://demo.allennlp.org/semantic-role-labeling

Its using PropBank format dataset. I have my own dataset and i want to fine-tune the model.

Can you list down the steps need to perform to run the fine-tune command.

**Comment by schmmd** [comment]
Hi @shanalikhan the fine-tune command continues training.  Unfortunately we don't have a tutorial dedicated to fine-tuning, but we do have several tutorials that involve training models (see https://github.com/allenai/allennlp/tree/v0.9.0/tutorials).  I suggest working through one of these tutorials and then trying to further fine-tune the model you've trained.

If, when you run into specific problems fine-tuning the SRL model feel free to ask us specific questions!

**Comment by brendan-ai2** [comment]
Hi @shanalikhan, I think you'll need to write a new dataset reader that takes your data format an d puts it into the same format as the model you're fine-tuning. If you make this the reader in the config file you pass to `allennlp fine-tune`, then things should "just work". But please let us know if you hit any issues!
