### ISSUE TITLE
AutoRegressiveSeqDecoder has no decode

### ISSUE THREAD

**Issue by dasguptar** [allenai/allennlp#3407]
I came across a missing method `decode` in AutoRegressiveSeqDecoder when trying to pass in a token_based_metric. The culprit seems to be [this line](https://github.com/allenai/allennlp/blob/master/allennlp/modules/seq2seq_decoders/auto_regressive_seq_decoder.py#L429).

Probably replacing the call to `decode` with a call to `post_process` would work, but I am not 100% sure. Can raise a PR if that is the fix.

**Comment by schmmd** [comment]
@brendan-ai2 does @dasguptar's proposal sound like the right fix?

**Comment by brendan-ai2** [comment]
@dasguptar, thanks for catching that! I do believe that's the correct fix and we'd be happy to take a PR. If you do create one, could you please add a small test case? Depending on whether it's easier to trigger this failure as a unit test or not I'd create an `auto_regressive_seq_decoder_test.py` or use the existing https://github.com/allenai/allennlp/blob/master/allennlp/tests/models/encoder_decoders/composed_seq2seq_test.py. Thank you!

**Comment by dasguptar** [comment]
Hi @brendan-ai2, I've submitted PR #3411.
Could not add test cases, explained more in the PR.

**Comment by DeNeutoy** [comment]
fixed by #3433
