### ISSUE TITLE
EndpointSpanExtractor should check that input matches input_dim

### ISSUE THREAD

**Issue by nelson-liu** [allenai/allennlp#3416]
Currently, the EndpointSpanExtractor will happily take input that doesn't match its passed-in `input_dim` if the exclusive span indices are not being used. Feels like there should maybe be a check somewhere for this...https://github.com/allenai/allennlp/blob/master/allennlp/modules/span_extractors/endpoint_span_extractor.py

**Comment by anchalbhalla** [comment]
I can take a look at this issue. Can you give me more detail about the issue?

**Comment by nelson-liu** [comment]
Sure! So, if you set `use_exclusive_start_indices  = False`, then `get_output_dim` could "lie" to you. Say you create a `EndpointSpanExtractor` with `input_dim= 10` and `use_exclusive_start_indices = False`. If you call `forward()` with a tensor of input dim `500`, the `EndpointSpanExtractor` wouldn't complain at all—you'd probably run into the error when the output of the `EndpointSpanExtractor` is fed into whatever else you have in your model, which is a bit unintuitive / hard to debug. So maybe we should just be checking that `input_dim` matches the actual inputs that are passed to `forward()` i.e., (`assert self._input_dim == input.size(-1)`).

**Comment by nadgeri14** [comment]
Hi @nelson-liu, if this issue is still pending I would like to take this up.  The above description helped me to better understand the problem. What I am struggling with is how do I reproduce the error described above, since, it only comes up during the forward function.  What is the simplest code block I could refer to or write down so as to reproduce the error and also further test my bug-fix. I took a look at the tutorial regarding span representations [`here`](https://github.com/allenai/allennlp/blob/master/tutorials/how_to/span_representations.md) but I wasn't sure how I could use this to reproduce the error. 
Thanks for the help :D

**Comment by nelson-liu** [comment]
hi @nadgeri14 , yes it's still pending.

Here's a repro:

```
In [1]: import torch

In [2]: from allennlp.modules.span_extractors.endpoint_span_extractor import EndpointSpanExtractor

In [3]:         sequence_tensor = torch.randn([2, 5, 7])
   ...:         # Note that input dim is incorrect, it should be 7
   ...:         extractor = EndpointSpanExtractor(500, "x,y")
   ...:         extractor_exclusive = EndpointSpanExtractor(500, "x,y", use_exclusive_start_indices=True)
   ...:         indices = torch.LongTensor([[[1, 3], [2, 4]], [[0, 2], [3, 4]]])

In [4]: extractor(sequence_tensor, indices)
Out[4]:
tensor([[[ 0.1086, -1.2481,  0.8578,  0.2294,  0.5543, -0.1483,  0.7636,
           0.6290,  1.0834, -1.9050, -0.5571, -0.6233,  0.4565, -0.8623],
         [-0.9067, -1.6923,  0.5217,  0.2890, -0.0510, -0.5196, -0.8087,
          -0.8212, -1.6942, -0.8724, -0.1030,  0.1770,  0.3312, -1.6491]],

        [[-0.5036,  1.0067,  1.8677, -1.9378, -1.4637, -0.6982,  0.4012,
           0.7401, -0.8912,  0.6724, -0.6107, -0.4646, -1.1664,  1.5351],
         [ 0.6252, -0.5593,  1.6583, -1.2833, -0.6398, -1.8811,  0.1174,
           1.2175, -0.9450, -0.6557, -0.6365, -1.2449,  1.0881,  0.7199]]])

In [5]: extractor_exclusive(sequence_tensor, indices)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-6-b5bb0096327f> in <module>
----> 1 extractor_exclusive(sequence_tensor, indices)

~/miniconda3/envs/allennlp/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    539             result = self._slow_forward(*input, **kwargs)
    540         else:
--> 541             result = self.forward(*input, **kwargs)
    542         for hook in self._forward_hooks.values():
    543             hook_result = hook(self, input, result)

~/git/allennlp/allennlp/modules/span_extractors/endpoint_span_extractor.py in forward(self, sequence_tensor, span_indices, sequence_mask, span_indices_mask)
    136             start_embeddings = (
    137                 start_embeddings * (1 - float_start_sentinel_mask)
--> 138                 + float_start_sentinel_mask * self._start_sentinel
    139             )
    140

RuntimeError: The size of tensor a (7) must match the size of tensor b (500) at non-singleton dimension 2
```

Note that the input_dim for the extractor is 7, even though the input dim actually passed in is 500—when `use_exclusive_start_indices=True` this causes an error, but when `use_exclusive_start_indices=False`, it silently just works.

**Comment by nadgeri14** [comment]
@nelson-liu Thankyou very much for the help. I have made the appropriate changes please have a look. 
[pull request](https://github.com/allenai/allennlp/pull/3611)
