### ISSUE TITLE
Dataset Name in progress bar during training

### ISSUE THREAD

**Issue by pasinit** [allenai/allennlp#3421]
I haven't found an easy and fast way for modifying the progress bar description that the Trainer uses to report the progress. I think it would be useful at least to show "train" "dev" at the beginning of the bar depending on which dataset the program is iterating on.
It would be even better if one could specify the name of the dataset and this will be automatically displayed during the training.

I'm open to implementing this feature if interested :)

**Comment by matt-gardner** [comment]
You could do this with a local copy of allennlp pretty easily.  Just modify this: https://github.com/allenai/allennlp/blob/9a6962f00d2b0d30b81900b4e9764ddc3433f400/allennlp/training/callback_trainer.py#L189-L220 and this: https://github.com/allenai/allennlp/blob/9a6962f00d2b0d30b81900b4e9764ddc3433f400/allennlp/training/util.py#L470-L487
(and there might be some other places that also need to be modified)

Add a flag to the `description_from_metrics` method that says whether it's train or dev, and modify calls to the method to pass that flag.  I don't have a strong opinion on whether this should be added or not.  It seems like it'd be useful, but I'm not sure whether it's worth the additional complexity.

Another, perhaps simpler, option, is to add a `Metric` to your model that just outputs whether it's train or dev, and then it'll get displayed automatically (formatted as something like `train: 1.000`).

**Comment by schmmd** [comment]
This is reasonable behavior to have in AllenNLP, but we don't think it's worth the additional complexity given that it's already clear what stage you are in from the logs.  So during our weekly issue review we think you should simply implement this outside AllenNLP for yourself if needed.
