### ISSUE TITLE
The format of the input file and output file from masked_language model

### ISSUE THREAD

**Issue by vanh17** [allenai/allennlp#3423]
Hi @Eric-Wallace  and @matt-gardner,

I tried to run the allenNLP on the command line here: 
```
allennlp predict https://storage.googleapis.com/allennlp-public-models/bert-masked-lm-2019.09.17.tar.gz   my-examples.jsonl --predictor masked_language_model 
```
I was wondering what the format for my-examples.jsonl is and what the output file is. Is there a way to save the output results into the particular place (locally)? 
I looked at the code and it looks like the expected json format is 
```
{"sentence": "..."}
```
However, what if I have a list of sentences I want to run them all at the same time to speed up the process, what the format look like?

For example if I have the file like this:
"I have a [MASK] [MASK] [MASK]."
"The lecture on [MASK] [MASK] is [MASK]."

**Comment by vanh17** [comment]
I figured it out. For multiple prediction we only need to write the instance in json structure one for every line
```
{"sequence": "This is the first [MASK]"}
{"sequence": "This is the second [MASK]"}
....
```
In order to export to the new file add the ```--output-file path_to_the_output_file``` in the command line.

**Comment by TheresaSchmidt** [comment]
For me, this only works with "sentence" as key. Also, the maximal number of sentences per file is determined by the batchsize.
