### ISSUE TITLE
Add support for spacy >= 2.2

### ISSUE THREAD

**Issue by tamuhey** [allenai/allennlp#3424]
I want to use allennlp with spacy>=2.2.  
The current version of spaCy is [2.2.2](https://github.com/explosion/spaCy/releases/tag/v2.2.2)

**Comment by tamuhey** [comment]
I found the PR #3331

**Comment by tamuhey** [comment]
Some tests fail due to spacy's statistical model.

**Comment by schmmd** [comment]
@tamuhey why do you need spaCy 2.2.2?  Just curious.

**Comment by tamuhey** [comment]
I want to use some of new spaCy's feature with allennlp, e.g.

- spacy's multiprocessing feature
- new `gold.align` method
- `EntityLinker` and `KnowledgeBase`

**Comment by schmmd** [comment]
Tests were passing so we merged this during issue review.  Fixed by #3432.

**Comment by schmmd** [comment]
Ah--we were confused as someone else opened a PR for this same functionality.  In any case--you should be good to go now!
