### ISSUE TITLE
Bug in AutoRegressiveSeqDecoder

### ISSUE THREAD

**Issue by nicola-decao** [allenai/allennlp#3426]
Here: https://github.com/allenai/allennlp/blob/f3083c8fb9150f07e3ca98bb3ea9368a081df028/allennlp/modules/seq2seq_decoders/auto_regressive_seq_decoder.py#L433

``target_tokens["tokens"]`` is a ``torch.Tensor`` so its ements do not have the attribute ``text``.

**Comment by kernelmachine** [comment]
Thanks for submitting a bug report -- contributions would be welcome to fix it.

**Comment by nicola-decao** [comment]
I'll fix that later today with a pull request :) I have a piece of code that works locally.

**Comment by DeNeutoy** [comment]
fixed by #3433
