### ISSUE TITLE
Allennlp POS tagger taking longer time 

### ISSUE THREAD

**Issue by SundeepPidugu** [allenai/allennlp#3428]
**Question**
* I am using `constituency_parser` and it’s taking a lot of time for getting the POS patterns for about 500 lines in a text file, Is there any parameter to set to the model predict so that I can just get the pos_tags and tokens alone. is there a way to load it faster or multiprocess the same?

**Comment by schmmd** [comment]
Closing--since this is already in Discourse.  Please only post in one place.

https://discourse.allennlp.org/t/allennlp-pos-tagger-taking-longer-time/117/2
