### ISSUE TITLE
Clean training loop interruption

### ISSUE THREAD

**Issue by ahoho** [allenai/allennlp#3430]
**Is your feature request related to a problem? Please describe.**
Sometimes I'd like to terminate a training early. For instance, perhaps I set my patience too high and my model is not improving. However, I still want a clean exit from the training loop.

**Describe the solution you'd like**
At the end of each epoch in `Trainer.train()`, a function listens for a file with a specific name like `terminate`. If the file exists, we `break` the loop. The implied behavior is that a user could do something like `touch terminate` rather than issuing a `KeyboardInterrupt`. Alternatively, it could be the case that it's called at the end of each batch, and the contents or name of the file would indicate whether to break at the batch or at the epoch.

**Additional context**
I note that a `KeyboardInterrupt` is caught in `commands/train.py` which permits some cleanup, but I think this would provide a cleaner option if desired. If this would be useful, I'd be glad to create a PR and tests for this feature.

**Comment by kernelmachine** [comment]
I think this feature request will require a bit more discussion, likely after the EMNLP conference. Setting feature request label for now!

**Comment by matt-gardner** [comment]
My vote: this should be implemented yourself as a callback in the `CallbackTrainer`.  I think this is a rare enough feature, with pretty arcane usage and discoverability, that we shouldn't add this to the main library.

**Comment by kernelmachine** [comment]
It looks the larger team is in agreement with Matt, so we'll close this issue for now.

**Comment by schmmd** [comment]
You can send this programmatically with SIGINT (which I think is `kill -2`) if that's what you're looking for.

**Comment by ahoho** [comment]
This makes sense—thanks for the comments!
