### ISSUE TITLE
Vocabulary mismatch when using pre-trained transformers

### ISSUE THREAD

**Issue by nicola-decao** [allenai/allennlp#3434]
Default OOV and unknown tokens are hardcoded as default in the vocabulary class:
https://github.com/allenai/allennlp/blob/9a6962f00d2b0d30b81900b4e9764ddc3433f400/allennlp/data/vocabulary.py#L226
and 
https://github.com/allenai/allennlp/blob/9a6962f00d2b0d30b81900b4e9764ddc3433f400/allennlp/data/vocabulary.py#L227
so when using any pre-trained token embedder where OOV and unknown tokens are defined differently (e.g., OOV is `[UNK]` instead of `@@UNKNOWN@@`) it breaks.

I would add `padding_token` and `oov_token` as parameters of the `Vocabulary` class inizialiser but I am not sure if this will add inconsistencies.

**Comment by matt-gardner** [comment]
I think this would be ok.  It might also help with #3097.  PR welcome!  Just be sure that it doesn't break any tests, and that you add sufficient tests for the new functionality.

**Comment by nicola-decao** [comment]
I am gonna look into this and make a PR in the weekend.
