### ISSUE TITLE
Fine-tune the BERT for next word prediction demo

### ISSUE THREAD

**Issue by vanh17** [allenai/allennlp#3437]
Hi @Eric-Wallace  and @matt-gardner,

I am trying to keep training the BERT on my own corpus so it can likely predict better with respect to my specific corpus. Is there a code somewhere for me to do this. 
Do you have example of the data_reader and the configuration you use while developing the demo? Thank you so much!

**Comment by kernelmachine** [comment]
@vanh17, he and Eric are at EMNLP (and will likely not respond till they are back in town). My guess is that you will have to continue training your bert model using the huggingface code: https://github.com/huggingface/transformers/blob/master/examples/run_lm_finetuning.py, but @matt-gardner might give you other demo-specific instructions.

**Comment by matt-gardner** [comment]
@kernelmachine is correct, we do not have code to do this.  If you want to train a masked language model, you'll need to use other code.  Contributions here would be welcome, but we have no plans to do this ourselves.
