### ISSUE TITLE
Update tutorials for the new split repos and v1.0

### ISSUE THREAD

**Issue by matt-gardner** [allenai/allennlp#3438]
This includes fixing links, whatever breaking changes we made, etc. We should also be cognizant of what will be in the new allennlp course, and not worry about duplicating things that are there.  That is, some (most? all?) of the tutorials can probably just be removed once the course is up.

**Comment by schmmd** [comment]
Some of this work may be duplicate with the AllenNLP course.

**Comment by ZhaofengWu** [comment]
[The tutorial repo]((https://github.com/allenai/allennlp-as-a-library-example) currently uses WordTokenizer which will be replaced by SpacyTokenizer in v1.0. I have a [PR there](https://github.com/allenai/allennlp-as-a-library-example/pull/31) in place for this that can be merged after v1.0 is released.

**Comment by schmmd** [comment]
We would like to remove the tutorials and replace them with the course.

**Comment by matt-gardner** [comment]
Changing the label on this one to "day", because the unique work here is largely removing stuff / moving content over to the course.

**Comment by schmmd** [comment]
We think that all tutorials can be removed and replaced by the course.
