### ISSUE TITLE
evaluation speed is lower than training speed?

### ISSUE THREAD

**Issue by vudaoanhtuan** [allenai/allennlp#3439]
![image](https://user-images.githubusercontent.com/25790306/68520645-cb42f100-02cb-11ea-9d54-6b7cb546cc14.png)

I train a translation model using ComposedSeq2Seq module on Google Colab (using GPU), but as you can see, the evaluation speed is lower than training speed. Are there something wrong here? Pls help me!

**Comment by matt-gardner** [comment]
This does a beam search at validation time, but no search during training. The search is slower than maximum likelihood training.
