### ISSUE TITLE
Is multi-GPU training totally transparent with Allennlp?

### ISSUE THREAD

**Issue by entslscheia** [allenai/allennlp#3440]
When using allennlp, if we want to train our model on multiple GPUs, are we just going to configure "cuda_device" parameter in the trainer to a list of GPU ids? So there is no need for us to make any modification to the code at all.

For now, my model is not very large, so it can be trained on a single GPU, but when I tried to configure to use two GPUs, I found the speed is much slower than using a single GPU. Is this because of the communication cost across two GPUs? Or is this because I don't know how to properly configure multi-GPU usage for allennlp?

**Comment by DeNeutoy** [comment]
Yes, we are working on it - please see #2536, #3079 . We expect this to be significantly improved once we are finished working on these projects. Certainly at the moment it is difficult to get much speedup from multi-gpu.
