### ISSUE TITLE
Add support and tutorials for fine-tuning generative models

### ISSUE THREAD

**Issue by reterik** [allenai/allennlp#3443]
I would love to see the OpenAI gpt-2 generator model integrated in AllenNLP.  Generators are somewhat lacking support in AllenNLP at the moment:
https://openai.com/blog/gpt-2-1-5b-release/

**Comment by matt-gardner** [comment]
What exactly do you want to do with it?

**Comment by reterik** [comment]
Generate questions specifically here is an example: 
https://googlier.com/csv/2019_10_28/artificial%20intel

**Comment by matt-gardner** [comment]
Ok, so you want to fine tune a generation model for some particular use, then generate with it.  You *might* be able to do that now with current allennlp code, but I'm not sure how easy it is.  I agree that this is something that we should support better and have examples for.  I'm going to change the name of the issue to make it more descriptive.

**Comment by matt-gardner** [comment]
I'll add - this is not currently on our roadmap, but I think it's important enough that I'd like to see it added to our roadmap early next year, if no one outside of AI2 wants to pick it up before then.

**Comment by reterik** [comment]
Great I will be debugging gpt-2 from a devops perspective and might write some integration code to see if I can get Pytorch and Tensorflow to play nice with each other.  I added a note to openai but they did not seem responsive.  Thanks for your reply and feature request addition. I think generative models are the key to unsupervised learning, and I look forward as a daily AllenNLP user to see what comes down the AllenAI pipeline in the future.

**Comment by reterik** [comment]
For lack of a better representation gpt-2 seems like a tensorflow wrapper with a glorified large model with a little nn code; I was not as impressed as I would have hoped considering the publicity stint about their AI being dangerous.  

Is there a way you can give me some pointers on how to grapple the code AllenNLP code base to expose the generators?

**Comment by matt-gardner** [comment]
I would guess that using the `transformers` implementation of GPT2 would be a much easier starting place than trying to do some kind of tensorflow integration.  We already have `pretrained_transformer` pieces implemented here, so the fine tuning is just a matter of getting the right model implemented.

**Comment by zzj0402** [comment]
Hi all, give a to-do list and I will be happy to chip in.

**Comment by matt-gardner** [comment]
First thing to do: fine-tune GPT2 on some data using an allennlp model.  There are a few things to figure out:
- What `DatasetReader` do you use?  We have some readers that are intended for language modeling, but I don't what their state is.
- What `Model` do you use?  We have a few classes that might be relevant, but I don't know which ones are usable or not for this.
- Relatedly, can this be general for any big transformer, or should it be specific to GPT2 or some other model?  How can we re-use our abstractions to do this right?
- How do you generate from the model?
- Is this fast enough to be practical?  What are the speed bottlenecks in our code?  We're fixing the data processing stuff to use pytorch dataloaders, which should make language modeling in particular a lot faster.

I don't have answers to any of these questions, but I haven't been doing language modeling.  It's possible someone has answers to some of these questions already; if so, please speak up!

I would probably start by trying to use our existing language modeling code to do the fine tuning, and see what doesn't work when trying to do it with GPT2.  Feel free to ask a bunch of questions if you have a hard time with this.

**Comment by DeNeutoy** [comment]
This will come more naturally with tighter alignment with transformers, i'm also not sure if we want this as a contribution (instead it would be great to see a separate package which focused on this)

**Comment by matt-gardner** [comment]
In particular, we want to have an `allennlp-language-modeling` repository, which would be a natural place to deal with this.  This should be coming in the not-too-distant future (next couple of months).

**Comment by bintaofeng** [comment]
Matt, Glad to find this thread about Allennlp's fine-tuning support. I'm trying to use Allen NLP's predict  functionality. I was able to fine tune gpt2 model  2000 steps and obtained hparams.json along with other checkpoint files. How do I load them into an Allen NLP model? Do you have sample code? 
Thank you!
