### ISSUE TITLE
How to use Bert(and RoBERTa) for span QA tasks in AllenNlP?

### ISSUE THREAD

**Issue by yyHaker** [allenai/allennlp#3447]
**Question**
* For QA tasks like SQuAD, how can I just use Bert to fine-tuning in AllenNLP?

**Comment by matt-gardner** [comment]
I'm not actually sure where all of the code is for doing this.  I know several people have done similar things, with mixed success.  @kl2806, @dDua, is there any publicly available code for a BERT-QA model in allennlp?  Updating our available reading comprehension models is high on our priority list for things to do after December, so hopefully this will happen soon if there isn't easily available code right now.

**Comment by kl2806** [comment]
Yes, the baseline for ROPES is an AllenNLP wrapper around the `pytorch_transformers` code (https://github.com/kl2806/ropes-leaderboard-example) implemented by @OyvindTafjord that should also work for SQuaD. @OyvindTafjord trained the RoBERTa SQuaD model and got numbers close to what was published on the leaderboard.

**Comment by matt-gardner** [comment]
Thanks @kl2806!

**Comment by yyHaker** [comment]
> Yes, the baseline for ROPES is an AllenNLP wrapper around the `pytorch_transformers` code (https://github.com/kl2806/ropes-leaderboard-example) implemented by @OyvindTafjord that should also work for SQuaD. @OyvindTafjord trained the RoBERTa SQuaD model and got numbers close to what was published on the leaderboard.

Thank you very much! Your share code is helpful, but could you share the SQuAD DatasetReader for Bert or RoBerta also, because I still have some doubts about it, like when to use Tokenizer and TokenIndexer, how to concat the `question` and `passage` and `[CLS]` and `[SEP]` and calculate the relative `span_start` and `span_end` ? since Bert use `BertTokenizer` and `wordpiece_tokenizer`, all the `span_start` and `span_end` will recalculate.
