### ISSUE TITLE
RuntimeError: "argmax_cpu" not implemented for 'Bool' while using CopyNet

### ISSUE THREAD

**Issue by iglee** [allenai/allennlp#3455]
Hi all, I'm trying to train a CopyNet on sagemaker, and I keep running into this error.  I've tried changing pytorch to older and newer versions, and directly downloading allennlp package to source.  Is there something wrong with my config?

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-240-7aa21974b798> in <module>()
      1 for i in range(50):
      2         print('Epoch: {}'.format(i))
----> 3         trainer.train()
      4 
      5         predictor = Seq2SeqPredictor(model2, reader)

~/anaconda3/envs/python3/lib/python3.6/site-packages/allennlp/training/trainer.py in train(self)

~/anaconda3/envs/python3/lib/python3.6/site-packages/allennlp/training/trainer.py in _validation_loss(self)

~/anaconda3/envs/python3/lib/python3.6/site-packages/allennlp/training/trainer.py in batch_loss(self, batch_group, for_training)

~/anaconda3/envs/python3/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    539             type(self).__name__, name))
    540 
--> 541     def __setattr__(self, name, value):
    542         def remove_from(*dicts):
    543             for d in dicts:

~/anaconda3/envs/python3/lib/python3.6/site-packages/allennlp/models/encoder_decoders/copynet_seq2seq.py in forward(self, source_tokens, source_token_ids, source_to_target, metadata, target_tokens, target_token_ids)

~/anaconda3/envs/python3/lib/python3.6/site-packages/allennlp/models/encoder_decoders/copynet_seq2seq.py in _gather_extended_gold_tokens(self, target_tokens, source_token_ids, target_token_ids)

RuntimeError: "argmax_cpu" not implemented for 'Bool'
```

my trainer looks like:
```
optimizer = optim.SGD(model2.parameters(), lr=0.1)
iterator = BucketIterator(batch_size=32, sorting_keys=[("source_tokens", "num_tokens")])
iterator.index_with(vocab)
trainer = Trainer(model=model2,
                  optimizer=optimizer,
                  iterator=iterator,
                  train_dataset=train_dataset,
                  validation_dataset=validation_dataset, 
                  num_epochs=1,
                  cuda_device=-1)
```

and my model looks like:
```
model = CopyNetSeq2Seq(vocab, source_embedder, encoder, max_decoding_steps=20,\
                              target_embedding_dim=ZH_EMBEDDING_DIM,\
                              target_namespace='target_tokens',\
                              attention=attention,\
                              beam_size=8)
```

any suggestions would be much appreciated!

**Comment by matt-gardner** [comment]
I did some searching about this, and I think it's a pytorch issue, not an allennlp issue (see, e.g., [this issue](https://github.com/pytorch/pytorch/issues/24088), it seems related).

It's possible you could get around this in the interim by doing a cast to `uint8` or something inside `_gather_extended_gold_tokens`, wherever the failure is happening.

I am surprised, though, that you can't fix this by downgrading to an earlier pytorch and allennlp version.  It's possible that there's something up with sagemaker and the environment that you're running in.  We [test the code](https://github.com/allenai/allennlp/blob/master/allennlp/tests/models/encoder_decoders/copynet_seq2seq_test.py) on CPU, and it runs for us.  You might try running through a docker image based on our allennlp image...?

**Comment by iglee** [comment]
Hi Matt, 

Thanks for writing back to me.  I was able to resolve this by casting the tensor (matches) as double on my local machine.  I'll try to do the same in SageMaker and see if that works as well.  I think you're right that this is a pytorch issue, and not the issue with the package.

Thanks!

**Comment by DeNeutoy** [comment]
Great!
