### ISSUE TITLE
Pretrained vocabulary from transformers is sometimes not saved in our Vocabulary object

### ISSUE THREAD

**Issue by maksym-del** [allenai/allennlp#3456]
We only add tokens from pretrained vocab from ``transformers`` lib if the tokenizer has ``vocab`` key inside. https://github.com/allenai/allennlp/blob/88fe0075c28babb20f076c43f932b77d80ce81a3/allennlp/data/token_indexers/pretrained_transformer_indexer.py#L62

This is not the case for all models in the lib and I did not find a unified ``get_vocab`` method in huggingface code. 
Anyways, the tokens will still be correctly indexed. It is just that we will not have tokens in our vocabulary object with all the consequences.

In https://github.com/allenai/allennlp/pull/3453 I will add support for RoBERTa and XLM that have ``encoder`` keys instead of ``vocab`` key, but I do not know about other models.

**Comment by matt-gardner** [comment]
See also https://github.com/allenai/allennlp/issues/3097 on issues about when vocabularies are actually written to disk.  This is a separate issue, though, right?

**Comment by maksym-del** [comment]
Yes, I think they are separate. This one is about correctly getting BERT vocab into our Vocabulary object while https://github.com/allenai/allennlp/issues/3097 is about saving the vocab to disk.

**Comment by maksym-del** [comment]
The newest version of transformers now includes ```get_vocab``` method added to tokenizers, which can be used to retrieve all the vocabulary from the tokenizers.
