### ISSUE TITLE
Can PretrainedTransformerTokenizer track character offset like WordTokenizer？

### ISSUE THREAD

**Issue by yyHaker** [allenai/allennlp#3458]
**Question**

* Can PretrainedTransformerTokenizer track character offset like WordTokenizer？
 Since character offset is important to calculate answer span after wordpiece tokenization？

**Comment by matt-gardner** [comment]
This is a TODO in the code.  I know that the huggingface repo has code to train SQuAD models, so there must be a way to do this calculation in that repo, but I haven't looked at the code to figure it out.  Contributions welcome!

**Comment by nadgeri14** [comment]
@matt-gardner if this issue is still pending I would love to take this up. I might need your assistance as I am relatively new to the code base. As in if you could provide me a list of TODO's it will really help me.

**Comment by matt-gardner** [comment]
The new `tokenizers` library from huggingface tracks character offsets, so we don't need to add this ourselves.  We have someone here who's going to be fixing this very soon.  I'd recommend against picking up this issue.

**Comment by nadgeri14** [comment]
@matt-gardner  Oh, thanks for the update.

**Comment by dirkgr** [comment]
I few weeks ago I added a parameter to `PretrainedTransformerTokenizer` that attempts to calculate offsets after the fact. It does so imperfectly, but it might get you going if you need this right away.

**Comment by matt-gardner** [comment]
I have no context or intuition about what time label this one should get; @dirkgr, any ideas?

**Comment by dirkgr** [comment]
We already have the code for this (https://github.com/allenai/allennlp/pull/3868), so this task is to integrate the new huggingface tokenizers whenever those remaining bugs are fixed, and bring that PR up to date. I'll say that's a day's worth of work.

**Comment by matt-gardner** [comment]
Just noting that #4018 integrated new huggingface tokenizers, so updating #3868 should be unblocked at this point.

**Comment by dirkgr** [comment]
I'm aware.

**Comment by dirkgr** [comment]
New huggingface tokenizers are still broken. I'm moving this to the bottom of the stack for 1.0. Maybe we'll bump it to 1.1.

**Comment by dirkgr** [comment]
Finally done!
