### ISSUE TITLE
Merge allennlp-demo Frontend Repository

### ISSUE THREAD

**Issue by reterik** [allenai/allennlp#3459]
I know that the demo code versus the Python library or command line application has always been a confusing aspect of the AllenNLP repositories.  Which one to use it what use cases, or even merging and or deprecating the demo code repository might be an idea for 1.0.0.  If you are splitting or forking for 1.0.0 consider making deployment options more clear in the documentation/course.

https://github.com/allenai/allennlp-demo

I am about 50 commits deep in the history and I have hopes of getting through to contribute code in long run.  I have been using the application for about two and a half years and have decided to contribute when and where I can, at one point I had it trained at the top 10 of SQuaD 1.0 in terms of FM numbers, but was hesitant to release the model because I did not know what work was under the hood.  

Another note for documentation, this particular repository helped my find a data loader that works, the data loaders out of the box are a little nebulous:

https://github.com/dmesquita/easy-deep-learning-with-AllenNLP

**Comment by matt-gardner** [comment]
We will definitely not be merging the front end code into this repository.  We originally had it in here, and split it out on purpose.  I don't see much point to having the front-end code in here, and having all of the python dependencies for running a backend server just bloats the core repository for no good reason.
