### ISSUE TITLE
Top Layer Only for LanguageModelTokenEmbedder

### ISSUE THREAD

**Issue by apmoore1** [allenai/allennlp#3460]
Problem:
It would be nice to have the option to only have the top layer output from the [LanguageModelTokenEmbedder](https://github.com/allenai/allennlp/blob/master/allennlp/modules/token_embedders/language_model_token_embedder.py#L18-L191) so that fine tuning similar to BERT can be performed. As at the moment if you want to fine tune you are also fine tuning the scaling parameter and using a weighted average of all of the layers which is a lot different. Also this feature would make these embeddings more similar to the functionality provided for:
1. [PretrainedBertEmbedder](https://github.com/allenai/allennlp/blob/master/allennlp/modules/token_embedders/bert_token_embedder.py#L247-L275)
2. [BertEmbedder](https://github.com/allenai/allennlp/blob/master/allennlp/modules/token_embedders/bert_token_embedder.py#L45-L243)
3. [OpenaiTransformerEmbedder](https://github.com/allenai/allennlp/blob/master/allennlp/modules/token_embedders/openai_transformer_embedder.py#L10-L100)

The solution would be to provide a `top_layer_only` argument into the constructor.

Happy to create a pull request and add the feature if wanted.

**Comment by matt-gardner** [comment]
Why do you need this?  What model are you trying to use?  I'm asking because most of the uses I can think of we already cover with other classes, and it'd be better to point you to existing code than to add new (unnecessary) functionality.

**Comment by apmoore1** [comment]
It was mainly to compare the performance of a ELMO Transformer model with a BERT based Transformer model from the huggingface library when both were being fine tuned.

I am currently using this in my own code based where I have some custom AllenNLP models for Target/Aspect Based Sentiment Analysis. The main reason for doing this was to replicate someone else's results when using their domain specific BERT based Transformer model from the huggingface library compared to my own domain specific ELMO Transformer model that I trained using the AllenNLP code based following roughly this [tutorial](https://github.com/allenai/allennlp/blob/master/tutorials/how_to/training_transformer_elmo.md). However both of these are being fine tuned while still having a custom architecture on top e.g. another LSTM layer on top of the contextualised embeddings output.
