### ISSUE TITLE
How to use greedy search in evaluation step in ComposedSeq2Seq module

### ISSUE THREAD

**Issue by vudaoanhtuan** [allenai/allennlp#3463]
I build Transformer model with ComposedSeq2Seq module. In AutoRegressiveSeqDecoder module, I use `beam_size=3`, so when I training model, the evaluation step take more time than training step, I try `using beam_size=1` but evaluation step is still very slow. Are there anyway to use greedy search in evaluation step when training model (but still use beam search in testing step)? Thank you!

**Comment by DeNeutoy** [comment]
Hi, you can use the `--overrides` flag when you run `allennlp evaluate` to override specific parameters in your configuration file.
