### ISSUE TITLE
How to know when AllenNLP Open Information Extraction will produce more than 2 arguments when extracting triples from a sentence?

### ISSUE THREAD

**Issue by detuvoldo** [allenai/allennlp#3467]
I try to use AllenNLP OIE, and the result it produced looks great. However, I don't know when it will produce triples with more than 2 arguments. 

Can anyone give me an explanation? 

Thanks a lot.

**Comment by DeNeutoy** [comment]
Hi, the model is a neural sequence tagger, so it is not possible to know when it will produce more than two arguments for a given predicate. In general, for open IE, this will depend on the sentence, so it is not really possible to know this upfront. Sorry!

**Comment by detuvoldo** [comment]
Thanks for your response.

I have one more question. What is the standard for a sequence being tagged as ARG2, ARG3, ...
And also what is the meaning of BV tag.

Normally, ARG0 and ARG1 are main entities of the sentences, and V is the predicate. 
I do not really get the meaning of BV and ARG with index larger than 2.

**Comment by wangrat** [comment]
@detuvoldo 
![image](https://user-images.githubusercontent.com/16265888/101051075-fb1b0180-357c-11eb-9ad3-f504e514b24c.png)

Additionally, **B** is beginning of a span and **I** is inside or end of a span.

At least that's what I figured out by myself.

**Comment by wangrat** [comment]
Ah sorry, you meant BV, the answer is here: https://github.com/allenai/allennlp/issues/3392
