### ISSUE TITLE
I want to train a sequence_tagging model by fine tuning BERT. How to write a configuration file ？

### ISSUE THREAD

**Issue by Simons2017** [allenai/allennlp#3475]

**Comment by DeNeutoy** [comment]
Hello! We have a test fixture which has an example of how to use the BERT token embedder here:

https://github.com/allenai/allennlp/blob/master/allennlp/tests/fixtures/bert/bert_for_classification.jsonnet

You would need to combine it with this config file (for example) to do a sequence tagging task:

https://github.com/allenai/allennlp/blob/master/training_config/ner.jsonnet
