### ISSUE TITLE
Generalizing 'self-attention' module to 'attention' module 

### ISSUE THREAD

**Issue by ameliatqy** [allenai/allennlp#3476]
I have been using your self-attention module heavily (i.e. MultiHeadSelfAttention). It is great but I would like a module that is able to 'attend' on an external piece of text rather than just on itself, just as described in the KNOWBERT paper (https://arxiv.org/abs/1909.04164).

As such, I went ahead and created a module that is able to perform both intra- and inter-attention based on the existing self-attention module. It essentially takes in two inputs: the text of interest and the external text that we want to attend on. The behavior of MultiHeadSelfAttention was replicated by essentially setting the text of interest and the external text equal to each other, so the text would attend on itself

Would such a PR be useful and of interest to you?

**Comment by DeNeutoy** [comment]
Thanks! It sounds interesting, but unfortunately the mechanics of this are not straightforward and it would be difficult to make a module that would support a general use case. As such, please feel free to implement it and release it in a separate repo, but I'm not sure that this is something that we would accept as a contribution. Thanks for the offer though!
