### ISSUE TITLE
What does produce model.tar.gz file during Transformer ELMO training?

### ISSUE THREAD

**Issue by acriptis** [allenai/allennlp#3479]
I'm trying to train Transformer ELMO with this tutorial on my own dataset: https://github.com/allenai/allennlp/blob/master/tutorials/how_to/training_transformer_elmo.md#training

My training has finished the first epoch and I see the content of the output directory as:
![191122_elmo_transformer_files](https://user-images.githubusercontent.com/2207706/69412731-87ff6e00-0d20-11ea-8244-b27f2a687428.png)

I'd like to evaluate on valid dataset after the first epoch with step 5 in manual (
 ```allennlp evaluate --cuda-device 0 -o '{"iterator": {"base_iterator": {"maximum_samples_per_batch": ["num_tokens", 500] }}}' output_path/model.tar.gz $BIDIRECTIONAL_LM_DATA_PATH/heldout-monolingual.tokenized.shuffled/news.en-00000-of-00100```
).
But manual assumes existence of model.tar.gz, although it is missed in my case. What causes creation of model.tar.gz? Maybe it created after further epochs or am I missing something in jsonnet config?

**Comment by acriptis** [comment]
I found that model.tar.gz is created after 10 epochs (or after finishing the learning). 
And given a completed epoch, you can construct model.tar.gz from `best.th`, `config.json` and `vocabulary` with command like:
`tar -czvf model.tar.gz -C model .` (asssumed that the specified files are in the folder with name `model`)

**Comment by pvcastro** [comment]
Hi @acriptis !
I'm running this same training right now, but I'm getting no progress for the training. It's been training for 6 days now, and the only information I have is regarding the iterations. It never finished epoch 0 (first). Did you also experimented this, or did you get progress per epoch normally?
Thanks!

**Comment by acriptis** [comment]
Hi, @pvcastro
I have a dataset  with 30gb of texts. The algorithm had written the first epoch after a week of training on four GTX 1080Ti cards (Algorithms failed to run on 5 or more GPUS due to CUDA memory error :-( ). So you could guess how much time you may expect for the first write.
