### ISSUE TITLE
Dependencies out-of-date: pytorch-pretrained-bert, pytorch-transformers, BertAdam, conllu, overrides

### ISSUE THREAD

**Issue by essandess** [allenai/allennlp#3481]
These dependencies are all out-of-date:

* pytorch-pretrained-bert* → transformers
* pytorch-transformers* → transformers
* BertAdam → AdamW
* conllu== → conllu>=
* overrides== → overrides>=

For reference, see code edits at this MacPorts PR, https://github.com/macports/macports-ports/pull/5862

https://github.com/macports/macports-ports/blob/25bcfba5003b27ad91f3e3bc1716162496686988/python/py-allennlp/Portfile#L74-L102

**Comment by brendan-ai2** [comment]
Hi @essandess, thanks for the heads up. I'm somewhat surprised that the direct search and replace you performed via the MacPorts repo worked. My understanding is that there are some non-backward compatible changes with, e.g., the pytorch-pretrained-bert* → transformers transition. Were you able to get our unit tests passing? If so, that might be a sign we need to improve coverage...

**Comment by essandess** [comment]
Yes, all the unit tests worked, and the tutorials too.

BTW, that transformation above is shorthand for the slightly more nuanced regex used in the Portfile.

**Comment by essandess** [comment]
Also, I didn’t dig into the new transformers structure very deeply, but it was clear that various objects are defined across multiple scopes. You may wish to keep the scopes you have where appropriate, rather than flatten everything like I did.

**Comment by brendan-ai2** [comment]
Thanks for the info. I'll definitely take a look at our tests. In the meantime, I would caution against releasing what you have. https://github.com/huggingface/transformers#migrating-from-pytorch-transformers-to-transformers pretty clearly demonstrates some backwards incompatible changes.

**Comment by essandess** [comment]
> Thanks for the info. I'll definitely take a look at our tests. In the meantime, I would caution against releasing what you have. https://github.com/huggingface/transformers#migrating-from-pytorch-transformers-to-transformers pretty clearly demonstrates some backwards incompatible changes.

Thanks. MacPorts is on transformers 2.1.1, and unlike pip or other tools, it’s a major PITA to install version specific releases, so for better or worse, we’re at the bleeding edge. For NLP models these days, that’s pretty much where you have to live anyway.

That said, please post if you see any major breakage using transformers v2.1.1 with allennlp 0.9.1-prerelease.
