### ISSUE TITLE
user gallery - neutrality masker

### ISSUE THREAD

**Issue by TalSchuster** [allenai/allennlp#3482]
1. Put your code in a GitHub repo with instructions for running it
- https://github.com/TalSchuster/TokenMasker

2. Publish a paper or host it on arXiv (ideally)
- https://arxiv.org/pdf/1909.13838.pdf (Automatic Fact-guided Sentence Modification AAAI 2020)

3. Host the trained model.tar.gz file somewhere accessible by HTTP
- https://www.dropbox.com/s/do5jptwmgroencn/model.tar.gz

4. Open an issue with the above links
- done

**Comment by schmmd** [comment]
Thanks for the contribution!  I just added it: https://github.com/allenai/allennlp-website/commit/e1e383cb7141c19d6495bc5e626f0dce5c59e9ea

**Comment by TalSchuster** [comment]
Thanks @schmmd.
Can you please only correct the venue to "AAAI 2020"?

**Comment by schmmd** [comment]
Done, thanks.
