### ISSUE TITLE
BERT for Classification trainable parameter

### ISSUE THREAD

**Issue by 96koushikroy** [allenai/allennlp#3485]
I was going through the code for BERT for Classification from the link below: 
https://github.com/allenai/allennlp/blob/master/allennlp/models/bert_for_classification.py

The class constructor takes in a parameter called **trainable** which if set as false would set all the trainable parameters of all the layers as frozen except for the last linear pooling layer.

But from the code in:
https://github.com/allenai/allennlp/blob/a8c44aeeb0a60142021f94d967a5377b3ccd7a3c/allennlp/models/bert_for_classification.py#L69

Won't this loop update the trainable flag of all the layers including the linear layer? If it does, setting the trainable parameter on the constructor as False would also set the requires_grad attribute on the final linear layer as False as well which the class documentation doesn't say so. 

Although another possibility can be that only the classification layer is trained if trainable is set as false.

**Comment by brendan-ai2** [comment]
Yes, I believe that the linear layer the documentation refers to is in fact the classification given here: https://github.com/allenai/allennlp/blob/master/allennlp/models/bert_for_classification.py#L83
