### ISSUE TITLE
How to train the OpenIE model

### ISSUE THREAD

**Issue by bratao** [allenai/allennlp#3487]
Hello,
First of all thank you for this amazing library. I'm trying to train the OpenIE model with my own dataset, but I cannot make it work. There is any example how I can do that?

@gabrielStanovsky

**Comment by schmmd** [comment]
Our demo has instructions for how to train most models, but we don't have full instructions for Open IE as the dataset is closed off.

![image](https://user-images.githubusercontent.com/954798/70362808-10aafd80-183b-11ea-9a69-b08743c898a0.png)

**Comment by schmmd** [comment]
@gabrielStanovsky can you link to the training configuration for the Open IE model?

**Comment by schmmd** [comment]
Better yet, @bratao you can download and untar the model itself and look at the configuration file that was used to train it originally.  Please open another issue if you have additional problems.
