### ISSUE TITLE
Using dataset reader at prediction time

### ISSUE THREAD

**Issue by TheresaSchmidt** [allenai/allennlp#3489]
**System:**
 - OS: [Linux, Windows 7]
 - Python version: [3.7]
 - AllenNLP version: [0.9.0]
 - PyTorch version: 1.3.0

**Question**
If I use the dataset reader to read in the data for the predictor, what part of the data is taken into consideration for the prediction?

For example, I'm using the conll2003 predictor. If I provide POS-tag in the data to predict, do they make a difference in the outcome of the prediction? Alternatively / Additionaly, can I include a POS tagger into the NER model? What would I have to change in the config file.

**Comment by mojesty** [comment]
You can train NER model without any additional features, e.g. chunks and pos tags, then you can use `SentenceTaggerPredictor` class and its method `predict_json` which gets a dictionary with "sentence" key in it.
If you opt for additional features, not only you will need your own predictor, but also during runtime you should get these features first, e. g. calling another predictor before calling NER.
If your data is not too domain-specific, training without pos tags and chunks and using BERT will yield good result.

**Comment by brendan-ai2** [comment]
I think @mojesty's answer makes sense. Feel free to reopen if you have more questions here.

**Comment by brendan-ai2** [comment]
Rather, comment again! :)
