### ISSUE TITLE
Predictor for allennlp.tools.drop_eval.evaluate_prediction_file

### ISSUE THREAD

**Issue by TheresaSchmidt** [allenai/allennlp#3490]
**System (please complete the following information):**
 - OS: [Windows 7, Linux]
 - Python version: [3.7]
 - AllenNLP version: [0.9.0]
 - PyTorch version: 1.3

**Question**
Hi there, 
I'm looking for a predictor that has the same output format that I would need as input for allennlp.tools.drop_eval.evaluate_prediction_file. Is there one I can use? 
Thanks in advance!

**Comment by brendan-ai2** [comment]
@matt-gardner, could you field this one?

**Comment by matt-gardner** [comment]
I believe we've used this code to produce an output file for the leaderboard: https://github.com/allenai/drop-leaderboard-example/blob/master/predict.py.
