### ISSUE TITLE
Install via pip misses files from data.tokenizers

### ISSUE THREAD

**Issue by c0ntradicti0n** [allenai/allennlp#3492]
**Describe the bug**
I installed the 0.9.0 and 0.8.5 via pip install and I could not find the tokenizers
I managed it by installing from git manual.

**To Reproduce**
```pip install allennlp```

**Expected behavior**
At least spacy tokenizer in `allennlp/data/tokenizers`, shouln't it be there?

**System (please complete the following information):**
 - OS: Linux, Debian
 - Python version: 3.7.5rc
 - AllenNLP version: [e.g. v0.9.0, or "I installed from master"]
 - PyTorch version: 1.0.2

**Additional context**

**Comment by DeNeutoy** [comment]
We are currently in the process of changing this API, because it was too complicated. https://github.com/allenai/allennlp/pull/3361

**Comment by schmmd** [comment]
`allennlp/data/tokenizer` is not in 0.9.0--it was called something else.
