### ISSUE TITLE
running in train  or in evaluate ?

### ISSUE THREAD

**Issue by lwgkzl** [allenai/allennlp#3497]
Is there any guard that marks whether the current code is running in train  or in evaluate ?
when my model is running in evaluate,i want add some code in "forward" function,
thank you!

**Comment by scarecrow1123** [comment]
AllenNLP's `Model` class extends PyTorch's `nn.Module`, hence you can use the flags provided by it. So you can do something like:

```python
def forward(self, x):
    if self.training:
        # code that runs during training
    else:
        # otherwise
```

**Comment by lwgkzl** [comment]
Thank you very much@_@
