### ISSUE TITLE
Potential OOM while loading best model state?

### ISSUE THREAD

**Issue by scarecrow1123** [allenai/allennlp#3499]
At the end of a training, `trainer.model` is updated with the best model state by calling `checkpointer.best_model_state()` ([here](https://github.com/allenai/allennlp/blob/master/allennlp/training/checkpointer.py#L172)) . This method returns the state as follows:

```python
best_model_state_path = os.path.join(self._serialization_dir, "best.th")
return torch.load(best_model_state_path)
```

Wouldn't it be better to load the state onto the CPU and return it? Since a `model.load_state_dict` would be called on this returned data, possibilities of any OOMs on GPU is less if done this way. In fact, `checkpointer.restore_checkpoint` [documents exactly this point](https://github.com/allenai/allennlp/blob/master/allennlp/training/checkpointer.py#L160) which is where I picked this up. I faced an OOM in one of my training runs and changing it to load to CPU first avoided the error.

**Comment by brendan-ai2** [comment]
Thanks for pointing this out, @scarecrow1123. We'd be happy to take a PR.
