### ISSUE TITLE
Issue in best action sequence

### ISSUE THREAD

**Issue by nebhandari** [allenai/allennlp#3500]
For the question -  what is the Client Operating Group of ABC?

Best action sequence is -
['@start@ -> List[str]', 'List[str] -> [<List[Row],StringColumn:List[str]>, List[Row
], StringColumn]', '<List[Row],StringColumn:List[str]> -> mode_string', 'List[Row] -> [<List[Row]:List[Row]>, List[Row]]',
'<List[Row]:List[Row]> -> first', 'List[Row] -> [<List[Row],StringColumn,List[str]:List[Row]>, List[Row], StringColumn, Lis
t[str]]', '<List[Row],StringColumn,List[str]:List[Row]> -> filter_in', 'List[Row] -> all_rows', 'StringColumn -> string_col
umn:client_name', 'List[str] -> string:allianz', 'StringColumn -> string_column:client_name']

whereas i am expecting the last element of best action sequence to be 'StringColumn -> string_column:client_operating_group'

Please suggest how can i get the expected best action sequence?

Sample Data:

Client   Name | Client   Operating Group | Client Service   Group
ABC | sample | test data
XYZ | test | test service group

 - Python version: 3.7.4
 - AllenNLP version: 0.8.5
 - 'wikitables-parser' 
 - wikitables-model-2019.07.29.tar.gz

**Comment by matt-gardner** [comment]
This is unfortunately a problem with the statistical model, not a problem with the code.  Figuring out how to more consistently get the correct action sequence is a research problem, not something we can help with.  These models are not intended for production use, they are examples / baselines / reference implementations of research.
