### ISSUE TITLE
AllenNLP -- Training a new model

### ISSUE THREAD

**Issue by poulamic23** [allenai/allennlp#3502]
@matt-gardner : Could you kindly confirm if the dataset in the following link was used to create the wikitables model.
https://github.com/ppasupat/WikiTableQuestions/releases (WikiTableQuestions-1.0.2-compact.zip)

If yes, could you guide me on how to train it.

**Comment by matt-gardner** [comment]
@pdasigi is the one who has details on how to train the model, though he's probably a bit occupied until after the ACL deadline (Dec. 9).  Also, the code has moved to the `allennlp-semparse` repo.  If you haven't heard from us a few days after the deadline, feel free to ping us again.  If you're also trying to meet the ACL deadline, you could email Pradeep directly to get his attention faster, though I'll warn you that the iterative process used to train this model is quite slow.

**Comment by pdasigi** [comment]
@poulamic23 Yes, that is the dataset.
Here are some instructions for training the model: https://github.com/allenai/allennlp/issues/3333#issuecomment-541822625
Let me know if you have anything is unclear. I've been meaning to post these instructions somewhere in `allennlp-semparse`, but didn't get to it yet.

**Comment by puneetaggarwal92** [comment]
@pdasigi Can you please tell how model will be saved at a specified path ?

**Comment by brendan-ai2** [comment]
@puneetaggarwal92, models are always saved as model.tar.gz under the serialization directory you specify to the train command.
