### ISSUE TITLE
Unable to install the master branch with poetry due to incomplete pyproject.toml

### ISSUE THREAD

**Issue by willfrey** [allenai/allennlp#3504]
**Description of the bug**
I'm unable to install the master branch directly from GitHub with [poetry](https://github.com/sdispater/poetry) due to an incomplete [pyproject.toml](https://github.com/allenai/allennlp/blob/master/pyproject.toml) file. According to https://github.com/sdispater/poetry/issues/1678, the `[tool.poetry]` section lacks the mandatory keys `version`, `description`, and `authors`.

Additionally, the `pyproject.toml` file should have the project's dependencies declared in the `[tool.poetry.dependencies]` section.

I tried a couple of solutions and one worked. All of that information is down in the **Additional context** section, as to not clutter this section anymore than I already have.

**To Reproduce**
1. Install `poetry`.
2. Run the following snippet

```console
cd /tmp
poetry new pkg
cd pkg
poetry env use python3  # Assuming python3 is Python 3.7.5
poetry add -vvv "git+https://github.com/allenai/allennlp.git@master"
```

3. Witness the `RuntimeError` that is displayed in the terminal complaining about `version` and `description`.

**Expected behavior**
I expect `poetry` to be able to install `allennlp` from the master branch on GitHub successfully, including parsing the declared project dependencies.

**System (please complete the following information):**
 - OS: macOS Catalina Version 10.15.1
 - Python version: 3.7.5
 - AllenNLP version: master

**Additional context**
I can get this to work if I edit `pyproject.toml` by removing the `[tool.poetry]` section _entirely_ and specify `setuptools` as the build system like such

```toml
[tool.black]
line-length = 100

include = '\.pyi?$'

exclude = '''
(
      __pycache__
    | \btutorials\b
    | \bbuild\b
    | \.git
    | \.mypy_cache
    | \.pytest_cache
    | \.vscode
    | \.venv
    | \bdist\b
    | \bdoc\b
)
'''

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
```

This tells `poetry` that we're going to build this with `setuptools` and `wheel`. Dependencies get parsed correctly and everything installs just like I want it to!

I also tried adding the minimum fields to `[tool.poetry]` to see if that'd work

```toml
[tool.poetry]
name = "allennlp"
version = ""
description = ""
authors = []

[tool.black]
line-length = 100

include = '\.pyi?$'

exclude = '''
(
      __pycache__
    | \btutorials\b
    | \bbuild\b
    | \.git
    | \.mypy_cache
    | \.pytest_cache
    | \.vscode
    | \.venv
    | \bdist\b
    | \bdoc\b
)
'''
```

This makes `poetry` happy but `poetry` will still fail to parse the project dependencies. Typically, they would go in the `[tool.poetry.dependencies]` section.

**Comment by willfrey** [comment]
If the `[tool.poetry]` section of `pyproject.toml` isn't critical, I'm happy to open a PR with my changes.

**Comment by brendan-ai2** [comment]
@willfrey, we aren't able to support very many build systems. If you'd like to submit a PR to make this better, we're happy to take a look, but we won't be able to support this in an ongoing fashion ourselves.

**Comment by willfrey** [comment]
@brendan-ai2 I’ve opened a PR! Please take a look at your convenience.

**Comment by schmmd** [comment]
I assume https://github.com/allenai/allennlp/pull/3508 fixes this.
