### ISSUE TITLE
Can I install old version of AllenNLP to make it compatible with cuda9.0

### ISSUE THREAD

**Issue by ChineseYjh** [allenai/allennlp#3505]
- OS: Linux
 - NVIDIA Driver version = 384.130(seems like **only supporting cuda9.0 or lower**)
 - Python version: 3.6.1
 - AllenNLP version: 0.9.0
 - PyTorch version: 1.0.1(Before I install AllenNLP)

### Q: Can I make AllenNLP compatible with my NVIDIA Driver?
It seems that AllenNLP requires torch >= 1.2.0, which requires cuda>=9.2. But my driver seems to **only supporting cuda9.0 or lower**, and the driver now can't be updated.
I wonder if I can install old version of AllenNLP to make it compatible with cuda9.0? How to do this with pip?
**Note: I install AllenNLP to use pre-trained ELMo, so the old version should include ELMO**
Thank you very much~

**Comment by DeNeutoy** [comment]
Hi, you can take a look at our release page: 

https://github.com/allenai/allennlp/releases

You should be able to find one which supports torch < 1.2.

**Comment by ChineseYjh** [comment]
> 
> 
> Hi, you can take a look at our release page:
> 
> https://github.com/allenai/allennlp/releases
> 
> You should be able to find one which supports torch < 1.2.

Thank you very much~
