### ISSUE TITLE
Extending `allennlp train` command with custom functionality

### ISSUE THREAD

**Issue by mojesty** [allenai/allennlp#3511]
**System (please complete the following information):**
 - AllenNLP version: 0.9.0

**Question**
I want to integrate allennlp with weights&biases experiment tracker, so I would like to call some wansb-specific code before I instantiate anything from params and also I want to pass additional flag to the `allennlp train` that tells whether I try to track experiment.

Ideal solution is like this:
`allennlp custom_train /path/co/config -s /path/to-serialization-dir --include-package my_package --wandb`

I do not want to change `allennlp train` command itself because it will break down when I upgrade the library.
What is the most clear way to do this?

I also wrote simple callback that tracks metrics during train and validaiton, if community is interested I can make a PR after that.

**Comment by schmmd** [comment]
Hi @mojesty I'm glad Weights & Biases is doing well.  I saw them last year at the PyTorch conference.

I also recommend against changing `allennlp train`, but it should be easy to write a script that either shells out to AllenNLP or calls the [the AllenNLP `train` command](https://github.com/allenai/allennlp/blob/master/allennlp/commands/train.py#L203) programmatically.  If you call it programmatically you could probably even use the same argument parser we use presently: https://github.com/allenai/allennlp/blob/master/allennlp/commands/train.py#L68.

**Comment by dhruvdcoder** [comment]
@mojesty 
[wandb_allenlp](https://pypi.org/project/wandb-allennlp/) implements a thin wrapper around `allennlp train` as well as implements a callback to log the metrics to wandb. This might be what you are looking for.

PS: it still relies on the old `CallbackTrainer` so it won't work for allennlp version > 0.9.0.

**Comment by mojesty** [comment]
@dhruvdcoder 
I actually did use this package, however, using it  requires some manual work every time (like starting agent etc.). Also, there were problems with paths in configs, so one should fix them manually on a new machine or when changing environment. 
I've discussed it in #1075 , I've made a (wrapper over that package) that takes care about these inconveniences, so you can create a sweep, iterate over it and log results to w&b in one command and works with AllenNLP 0.9.4. I think I will make some new package that will work with allennlp 1.0+, however it is still work in progress.

**Comment by dhruvdcoder** [comment]
@mojesty This is great. Can you share the link to your repo with current implementation? I would like to try it.

As far as wandb_allennlp goes, I talked with folks at W&B to figure out the cleanest way of doing this and updated the package. Now it does not require any extra code or config patches. However, I still have not upgraded it to work with the new trainer. Also, one does need to launch agents manually using `wandb agent`, however, I feel that is how it should be. Perhaps we can work together to add more features like logging non-sweep train runs as well as eval and test runs to wandb.

**Comment by mojesty** [comment]
@dhruvdcoder  Here is a link https://github.com/mojesty/components/blob/master/components/commands/sweep.py . To make it work, install the repository with `pip install -e .` and launch `components sweep` command. Then it should work with your example config.
