### ISSUE TITLE
AllenNLP -- Training a new model

### ISSUE THREAD

**Issue by puneetaggarwal92** [allenai/allennlp#3513]
@pdasigi Can you please tell how model will be saved at a specified path ?
Previous Referral:- https://github.com/allenai/allennlp/issues/3502

**Comment by pdasigi** [comment]
@puneetaggarwal92 The model will be saved as a tarball (`model.tar.gz`) in the serialization directory you specify with the `-s` flag with your `allennlp train` command. You can run `allennlp train -h` for more information.
