### ISSUE TITLE
Add the arguments of FeedForward to the constructor of FeedForwardEncoder

### ISSUE THREAD

**Issue by JohnGiorgi** [allenai/allennlp#3514]
**Is your feature request related to a problem? Please describe.**

I wanted to use the [`FeedForwardEncoder`](https://allenai.github.io/allennlp-docs/api/allennlp.modules.seq2seq_encoders.html#allennlp.modules.seq2seq_encoders.feedforward_encoder.FeedForwardEncoder) within my model. I would like to be able to initialize the encoder in my jsonnet config. However, it requires that an instance of [`FeedForward`](https://allenai.github.io/allennlp-docs/api/allennlp.modules.feedforward.html#allennlp.modules.feedforward.FeedForward) be passed to the constructor. I can't seem to construct the instance of `FeedForward` within my config because it is not registered.

**Describe the solution you'd like**

Rather than ask for an instance of `FeedForward` in the constructor of `FeedForwardEncoder`, might it be better to have the user provide the same arguments of `FeedForward` to the constructor of `FeedForwardEncoder`, and have it instantiate `FeedForward` with those arguments?

E.g. Currently, the constructor looks like

```python
@Seq2SeqEncoder.register("feedforward")
class FeedForwardEncoder(Seq2SeqEncoder):
    """
    This class applies the `FeedForward` to each item in sequences.
    """

    def __init__(self, feedforward: FeedForward) -> None:
        super().__init__()
        self._feedforward = feedforward
```

I am proposing something like

```python
@Seq2SeqEncoder.register("feedforward")
class FeedForwardEncoder(Seq2SeqEncoder):
    """
    This class applies the `FeedForward` to each item in sequences.
    """
    def __init__(
        self,
        input_dim: int,
        num_layers: int,
        hidden_dims: Union[int, List[int]],
        activations: Union[Activation, List[Activation]],
        dropout: Union[float, List[float]] = 0.0,
    ) -> None:
        super().__init__()
        self._feedforward = FeedForward(input_dim, num_layers, hidden_dims, activations)
```

**Describe alternatives you've considered**

An alternative solution would be to make `FeedForward` registrable by subclassing `Registrable`.

**Additional context**

I would be happy to open a PR for either solution. I just wanted to make sure: a) I am not misunderstanding something, b) the proposed solutions are reasonable.

**Comment by matt-gardner** [comment]
`FeedForward` inherits from `FromParams`, which is all you need to construct it from a config file.  You don't pass a `type` argument (because there's only one class for `FeedForward`), you just use the constructor parameters.  The config should look like this:

```
{"encoder": {
"type": "feedforward",
"feedforward": {"input_dim": ..., "num_layers": ..., ...}
}}
```

If you have trouble using this, feel free to ask a question about how to get it to work.  But this isn't a bug or a feature that needs to be added, so I'm closing this issue.

**Comment by JohnGiorgi** [comment]
Got it. This worked.

Glad I asked, thanks for the detailed response.
