### ISSUE TITLE
Train a model using ALLENNLP

### ISSUE THREAD

**Issue by poulamic23** [allenai/allennlp#3517]
![ALLEN_Train](https://user-images.githubusercontent.com/48485339/70776331-bcf06500-1da2-11ea-94ee-7a428d8fc941.png)

https://github.com/allenai/allennlp/issues/3513#issuecomment-565110195

I understand by your previous comment that allennlp train -s will help specify where to save the model.
However, it doesn't show any argument to specify the dataset path for training.  

In https://github.com/allenai/allennlp/issues/3502#issuecomment-561761736, it mentions a different approach. 

It's quite confusing. Could you kindly help here.
@pdasigi @matt-gardner

**Comment by manelAffi** [comment]
The dataset path for training, validation and test should be specified in the config file:

`{
  "dataset_reader":{
    "type":"seq2seq",

    "source_token_indexers": {
      "tokens": {
        "type": "single_id",
        "namespace": "source_tokens"
      }
    },

    "target_token_indexers": {
      "tokens": {
        "type": "single_id",
        "namespace": "target_tokens"
      }
    }
  },


  "train_data_path": "xxxxxxx",
  "validation_data_path": "xxxxxxx",
  "test_data_path": "xxxxxxx",

  "model": {
    "type": "simple_seq2seq",
    "source_embedder": {
      "tokens": {
        "type": "embedding",
        "embedding_dim":150,
        "vocab_namespace": "source_tokens",
        "trainable": true
      }
    },

    "encoder": {
      "type": "lstm",
      "input_size": 150,
      "hidden_size": 150,
      "num_layers": 5
    },

    "max_decoding_steps": 200,
    "target_namespace": "target_tokens",
    "attention_function": {"type": "dot_product"}
  },

  "iterator": {
    "type": "bucket",
    "batch_size" : 16
  },

  "trainer": {
    "num_epochs": 15,
    "patience": 10,
    "cuda_device": -1,
    "optimizer": {
      "type": "adam",
      "lr": 0.01
    }
  }
}`

**Comment by pdasigi** [comment]
Thanks @manelAffi! 
@poulamic23, in general, when you train a model with AllenNLP, you specify the path to the training data in the configuration file, and the outputs (serialized model, intermediate weights and logs etc.) get written in the location specified by `-s`. What I described in https://github.com/allenai/allennlp/issues/3502#issuecomment-561761736 and https://github.com/allenai/allennlp/issues/3333#issuecomment-541822625 is specific to training a model for WikiTableQuestions, where you will have to preprocess the dataset to bring it to a state where you can train a model on it. You will still have to include a pointer to the output of the preprocessing step in your configuration file, as described in my earlier comment. Please let me know if this is still unclear.
