### ISSUE TITLE
fine-tune a trained model with different model parameters

### ISSUE THREAD

**Issue by xfwmz** [allenai/allennlp#3518]
**System**
 - OS: Ubuntu
 - Python version: 3.6.7
 - AllenNLP version: 0.9.0

**Question**
* As far as I understand, AllenNLP fine-tune command requires a model archive, a new config file and a serialization dir. And model parameters in the new config file will be ignored because model parameters in the archive will be used instead. Finally, the fine-tuned model and its logs and the new config file will be saved to the serialization dir. 
* My question is when I do not specify the model parameters in the new config file, the fine tuning experiment runs well. I get a fine-tuned model saved in the serialization dir. But when I want to make a prediction using this fine-tuned model, I got an error cause the config file in the serialization dir does not contain model parameters, thus it is impossible to recover a model for prediction.
* One further question is when the config file in model archive and model fine-tuned specify different model parameters, there may also be a problem for prediction. Since the config file in the serialization dir specify one model for prediction (even though this model is not used for fine tuning), but the model is actually fine-tuned based on model parameters specified in the archive config file. Is there anything I am missing or is this a potential bug?

Thank you in advance.

**Comment by schmmd** [comment]
@xfwmz that sounds unfortunate, but we need more detail to troubleshoot this.  Can you provide us with a stack trace at least?  Ideally we would be able to reproduce this.

**Comment by matt-gardner** [comment]
Actually, we understand the problem, and it is indeed a bug.  Ideally we would copy the model config from inside the model archive into the new config file that we save.  However, we're very unlikely to fix this ourselves, as this particular issue is a pretty rare case.  Contributions welcome, though we're considering removing the `fine-tune` command entirely, as the narrow use that we implemented in `fine-tune` is no longer a very typical way of training models.

**Comment by xfwmz** [comment]
> Actually, we understand the problem, and it is indeed a bug. Ideally we would copy the model config from inside the model archive into the new config file that we save. However, we're very unlikely to fix this ourselves, as this particular issue is a pretty rare case. Contributions welcome, though we're considering removing the `fine-tune` command entirely, as the narrow use that we implemented in `fine-tune` is no longer a very typical way of training models.

@matt-gardner Thank you for your reply. I think this `fine-tune` command is still very useful and helpful as long as I specify the same model parameters with that in the MODEL_ARCHIVE. I would say it might be better to keep this command. As for this issue, one possible solution may be to just add some restrictions to the argument description. For example:

      -c CONFIG_FILE, --config-file CONFIG_FILE
                            configuration file to use for training. Format is the
                            same as for the "train" command, model parameters should be the same 
                            with that in the MODEL_ARCHIVE.
and then some parameter check like whether model parameters are the same or not before fine tuning. 
Hope this would help. Thanks.

**Comment by dirkgr** [comment]
In `v1.0.0rc1`, the way to do this is to make another training config that loads the model with `"type": "from-archive"`. If you want to make changes to the config, you currently have to open the archived model and change the `config.json` file within, but we're considering a way of specifying overrides.
