### ISSUE TITLE
pip allennlp

### ISSUE THREAD

**Issue by moh55m55** [allenai/allennlp#3520]
Hello, 

The pip version is causing conflicts, any pip updated version soon?  it causes conflicts with spacy v2.2.  I have been installing allennlp from source.

**Comment by schmmd** [comment]
Can you give us the output you see when installing AllenNLP so we can investigate further?  Which version are you installing?

**Comment by schmmd** [comment]
@dirkgr had some problems recently installing master.  He had some warnings when installing pip and had some exceptions when he ran `allennlp`.

**Comment by moh55m55** [comment]
I moved on on my project but as I recall is that allennlp uninstalled the newest version of spacy and install an old one. Then other packages conflict with the installed spacy version. I just want to mention that the pip version did that behavior. Thats it.

**Comment by dirkgr** [comment]
While that's not what I fixed, I know that after my fix I had no more conflicts. So I'll close this for now. If the issue pops back up after we've made a new release, let us know!
