### ISSUE TITLE
Consider removing the fine-tune command

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp#3521]
Users are often confused about how to use this, it can be conflated with BERT fine-tuning, and it's only applicable to a narrow use case.  It's brittle.

**Comment by RikVN** [comment]
I use it! I'm not sure the use case is so narrow. In my case it helps a lot if you train on a mix of gold and silver standard data, and then finetune on only gold standard.

I can see users getting confused by the name "finetune", so changing that to a different name I'm fine with.

Of course I'm just a single user, but just letting you know that it is currently used ;-)

**Comment by matt-gardner** [comment]
Looking at #3404, and the work I'm planning on doing for #3627, I'm pretty sure we can remove the `fine-tune` command and just have a `"type": "from_archive"` model (which should be easy to register as a separate `@classmethod` on `Model`, using #3550).  The only difference between the two commands is where the model comes from.
