### ISSUE TITLE
Training model

### ISSUE THREAD

**Issue by joval2** [allenai/allennlp#3533]
**System (please complete the following information):**
 - OS: Linux
 - Python version: 3.7.4
 - AllenNLP version: I installed from master

**Question**
Please how can I train my own model?

**Comment by dirkgr** [comment]
Hi @joval2! Try going though the tutorial at https://allennlp.org/tutorials. It should help you get started. If you want, there are some more at https://github.com/allenai/allennlp/tree/master/tutorials.

**Comment by joval2** [comment]
Thanks @dirkgr! I'll try this.

**Comment by joval2** [comment]
Please, now I wanna use the reading comprehension model to apply on some data-set but I don't know how I'm supposed to do. Please help
