### ISSUE TITLE
Potential security issue

### ISSUE THREAD

**Issue by PeterZhizhin** [allenai/allennlp#3535]
**Describe the bug**
The following piece of code: https://github.com/allenai/allennlp/blob/ca453c8b1186b4f346e70428c889a139ca21f794/allennlp/common/util.py#L443-L446

This is equivalent to calling `os.system()`. A potential attacker can replace `nvidia-smi` with another program by changing PATH env variable.

This is all hypothetical, but there has to be a better solution for finding current memory usage.
I didn't expect the library to call `os.system()`.

**Comment by dirkgr** [comment]
You're not wrong, but if someone can replace `nvidia-smi` on your system, you might have bigger problems already. That said, if you can implement a better way of getting the memory usage, I'm happy to review the PR.
