### ISSUE TITLE
zlib.error: Error -3 when try to use allennlp evaluate command

### ISSUE THREAD

**Issue by Yoark** [allenai/allennlp#3536]
Hi all,
I trained a model with custom dataset and model (use jsonnet configs). And when I need to evaluate the model on my test data, this error occurred:
`zlib.error: Error -3 while decompressing data: invalid block type`
Any ideas? If you need more information regarding this issue please tell me

**Comment by dirkgr** [comment]
Can you send us a whole stack trace?

Psychic debugging tells me that you're trying to decompress a file that's not compressed, but it's impossible to be sure without more information.

**Comment by Yoark** [comment]
> Can you send us a whole stack trace?
> 
> Psychic debugging tells me that you're trying to decompress a file that's not compressed, but it's impossible to be sure without more information.

I retrained again and now it works fine, no idea what happened...
