### ISSUE TITLE
Use a model

### ISSUE THREAD

**Issue by joval2** [allenai/allennlp#3540]
**System (please complete the following information):**
 - OS: Linux
 - Python version: 3.7.4
 - AllenNLP version: I installed from master

**Question**
Please, what is the process to use existent model (concretely, I'll want use the reading comprehension model) and apply to my data-set? Cause I'm not seeing the readme file in models folder.

**Comment by schmmd** [comment]
@joval2 please look at the "Usage" section on our web demo: https://demo.staging.allennlp.org/reading-comprehension
![image](https://user-images.githubusercontent.com/954798/71212874-12c38200-2267-11ea-80ae-b45b0511f75f.png)
