### ISSUE TITLE
Is it possible to do HotFlip on GPU?

### ISSUE THREAD

**Issue by c4n** [allenai/allennlp#3542]
* Is it possible to do HotFlip on GPU?

 I'm working on adversarial training. Is it possible to use HotFlip to create adversarial examples using GPU?

**Comment by matt-gardner** [comment]
Have you tried it and it's not running on the GPU?

**Comment by c4n** [comment]
Yes, I have tried it. It didn't work on GPU, It only worked when I transferred the model to the CPU.
`tagger = NewTaggerPredictor(model.cpu(), conll_read)
hotflipper = Hotflip(tagger, vocab_namespace="tokens")`

I noticed a few spots on [hotflip.py](https://github.com/allenai/allennlp/blob/master/allennlp/interpret/attackers/hotflip.py) where it moves things to the cpu e.g.:
line 79
`self.embedding_matrix = self._construct_embedding_matrix().cpu()`

**Comment by matt-gardner** [comment]
I believe we did that because our primary use was having the code run in our demo, which runs on CPUs.  If you remove all of the calls to `.cpu()` (or add explicit calls to `.to()`), does it work?  If it does, a PR to add a `cuda_device` parameter to the constructor of `Hotflip` would be very welcome.

**Comment by c4n** [comment]
Thank you for your reply. I will try to work on it this weekend.

**Comment by c4n** [comment]
It worked! I will submit a PR soon.
It's about 4 times faster on GPU on one input sentence. (initialization time included)
![ภาพ](https://user-images.githubusercontent.com/4990317/71369067-34f92f00-25dc-11ea-94d6-b2705b96a896.png)
