### ISSUE TITLE
Does AllenNLP  works under ROCm?

### ISSUE THREAD

**Issue by CarlosAndres12** [allenai/allennlp#3556]
Does AllenNLP  works under ROCm?

Since the Radeon VII is 500 USD now i was wondering the status of AllenNLP under ROCm, does it works perfectly, partially or not at all.

**Comment by scarecrow1123** [comment]
Since AllenNLP uses PyTorch underneath, it is really a question of whether PyTorch works on top of ROCm if I'm not wrong.

**Comment by CarlosAndres12** [comment]
> Since AllenNLP uses PyTorch underneath, it is really a question of whether PyTorch works on top of ROCm if I'm not wrong.

ROCm supports PyTorch, i would like to know if someone has tested AllenNLP on it. I have no ROCm-Compatible graphics cards but i would consider buying one dependiente on which ML libraries work on it.

**Comment by schmmd** [comment]
The AllenNLP development team isn't very familiar with ROCm, so you'll likely need to figure this out for yourself.  Let us know what you find out.
