### ISSUE TITLE
Ill-formed spans are not allowed in `bioul_tags_to_spans`, but allowed in `iob1_tags_to_spans`

### ISSUE THREAD

**Issue by knighter** [allenai/allennlp#3557]
**Question**
In allennlp/data/dataset_readers/dataset_utils/span_utils.py
Ill-formed spans are not allowed in `bioul_tags_to_spans`, but allowed in `iob1_tags_to_spans` etc.
So simple_tagger work with bmes or bio, but not work with bioul coding schema, is this a bug of feature?
```
allennlp/data/dataset_readers/dataset_utils/span_utils.py", line 254, in bioul_tags_to_spans
raise InvalidTagSequence(tag_sequence)
allennlp.data.dataset_readers.dataset_utils.span_utils.InvalidTagSequence
```

**Comment by schmmd** [comment]
@DeNeutoy are you able to follow up there?
