### ISSUE TITLE
Add BertQA for span QA tasks

### ISSUE THREAD

**Issue by pengshuang** [allenai/allennlp#3558]
See previous issue https://github.com/allenai/allennlp/issues/3447

I have implemented BERT-QA(Bert, Roberta and spanbert) for span QA tasks in Allennlp.
Could I create a new pull request and contribute it to the Allennlp ?

**Comment by matt-gardner** [comment]
I see you found the reading comprehension repo and opened [an issue](https://github.com/allenai/allennlp-reading-comprehension/issues/10) there.  I'm closing this issue and moving discussion to that repo.
