### ISSUE TITLE
Unnecessary argument in SelfAttentiveSpanExtractor

### ISSUE THREAD

**Issue by jianliu-ml** [allenai/allennlp#3565]
https://github.com/allenai/allennlp/blob/ec441a3efbb0bd7c98af7202ca1e4c4086747ba2/allennlp/modules/span_extractors/self_attentive_span_extractor.py#L50

The sequence_mask is not used in the following computation process.
It is an unnecessary argument, which can be safely removed.

**Comment by schmmd** [comment]
Thanks for pointing this out!  We'd welcome a PR!

**Comment by jianliu-ml** [comment]
> Thanks for pointing this out! We'd welcome a PR!

OK! I have made a PR.
