### ISSUE TITLE
Need better readability in AllenNLP docs

### ISSUE THREAD

**Issue by scarecrow1123** [allenai/allennlp#3568]
Parameter lists for function/class signatures in AllenNLP docs are pretty much clogged up and make it difficult to read. It would be nice if line breaks could be added so that Sphinx can render it a bit better. 

![Screenshot_2019-12-31 allennlp training trainer — AllenNLP 0 9 1-unreleased documentation](https://user-images.githubusercontent.com/3162105/71612833-ec87d580-2bc8-11ea-8ef5-b0b51696956b.png)

**Comment by schmmd** [comment]
Yikes--that's a great point.  Thanks for highlighting this!

**Comment by schmmd** [comment]
We're looking into and discussing some alternatives.  Hopefully we'll figure out something, but we're also open to suggestions!

**Comment by DeNeutoy** [comment]
@scarecrow1123 fixed by #3602 , thanks for raising this as it gave me additional motivation to fix it, something we should have done a while ago!
