### ISSUE TITLE
How can I use my self-training ELMo model without CNN (for Chinese isn't suitatble to use CNN) trained by the tensorflow version ELMo? 

### ISSUE THREAD

**Issue by LucasJau** [allenai/allennlp#3569]
**System (please complete the following information):**
 - OS: Linux
 - Python version: v3.6.1
 - AllenNLP version: v0.9.0

**Question**
How can I use my self-training ELMo model without CNN (for Chinese isn't suitatble to use CNN) trained by the tensorflow version ELMo?

**Comment by schmmd** [comment]
@LucasJau does it work if you follow the ELMo tutorial to use the ELMo model you trained?  Please open a new issue if you run into a specific problem.  Here are some relevant tutorials:

https://github.com/allenai/allennlp/blob/master/tutorials/how_to/training_transformer_elmo.md
https://github.com/allenai/allennlp/blob/master/tutorials/how_to/elmo.md
