### ISSUE TITLE
Add `find_unused_parameters` param for torch's `DistributedDataParallel`

### ISSUE THREAD

**Issue by scarecrow1123** [allenai/allennlp#3574]
PyTorch's [`DistributedDataParallel`](https://pytorch.org/docs/stable/nn.html#torch.nn.parallel.DistributedDataParallel) has this optional flag that can be set called `find_unused_parameters`. It is intended to let torch's autograd to ignore parameters that aren't part of the computational graph of the current forward pass. This can be useful when conditionals are used and often times if these conditionals result in avoiding certain part of the graph for a forward pass. In such cases not setting this flag would result in PyTorch throwing an error like this:

```
RuntimeError: Expected to have finished reduction in the prior iteration
before starting a new one. This error indicates that your module has parameters that were not used in producing its output (the return value of `forward`). You can enable unused parameter detection by 
passing the keyword argument `find_unused_parameters=True` to 
`torch.nn.parallel.DistributedDataParallel`. If you already have this argument set, 
then the distributed data parallel module wasn't able to locate the output tensors in the
return value of your module's `forward` function. Please include the structure of the return value
of `forward` of your module when reporting this issue (e.g. list, dict, iterable). (prepare_for_backward at /pytorch/torch/csrc/distributed/c10d/reducer.cpp:408)
```

It would be safe to set this flag to `True` when initializing `DistributedDataParallel`.

**Comment by soulslicer** [comment]
Does this flag slow down any process?
