### ISSUE TITLE
Import Embedding error from torch.nn.functional

### ISSUE THREAD

**Issue by ayush-jain** [allenai/allennlp#358]
Hi,

I just installed the library using the conda-specific instructions on homepage. But, I am getting embedding error when I am running pytest -v for verifying the installation. 

For reference : I installed Pytorch using the following command and was successful:
**conda install pytorch torchvision**

The version of pytorch installed:
pytorch                   0.1.12          py36cuda8.0cudnn6.0_1  
tensorboard-pytorch       0.7.1                     <pip>

All the errors point to the same following issue (in Bold):

`ImportError while importing test module '/u/scratch1/jain207/allennlp/tests/training/metrics/span_based_f1_measure_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/training/metrics/span_based_f1_measure_test.py:5: in <module>
    from allennlp.common.testing import AllenNlpTestCase
allennlp/common/testing/__init__.py:5: in <module>
    from allennlp.common.testing.model_test_case import ModelTestCase
allennlp/common/testing/model_test_case.py:6: in <module>
    from allennlp.commands.train import train_model_from_file
allennlp/commands/__init__.py:4: in <module>
    from allennlp.commands.serve import add_subparser as add_serve_subparser
allennlp/commands/serve.py:27: in <module>
    from allennlp.service import server_sanic
allennlp/service/server_sanic.py:21: in <module>
    from allennlp.service.predictors import Predictor
allennlp/service/predictors/__init__.py:9: in <module>
    from .predictor import Predictor
allennlp/service/predictors/predictor.py:4: in <module>
    from allennlp.models import Model
allennlp/models/__init__.py:7: in <module>
    from allennlp.models.decomposable_attention import DecomposableAttention
allennlp/models/decomposable_attention.py:9: in <module>
    from allennlp.modules import FeedForward, MatrixAttention
allennlp/modules/__init__.py:17: in <module>
    from allennlp.modules.token_embedders import TokenEmbedder
allennlp/modules/token_embedders/__init__.py:7: in <module>
    from allennlp.modules.token_embedders.embedding import Embedding
allennlp/modules/token_embedders/embedding.py:7: in <module>`
 **from torch.nn.functional import embedding
 ImportError: cannot import name 'embedding'**

I am getting the same embedding error when I am trying to run the textual entailment model:
**python -m allennlp.run predict /tmp/tests/fixtures/decomposable_attention/model.tar.gz input.txt**

`Traceback (most recent call last):
  File "/homes/jain207/anaconda/envs/allennlp/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/homes/jain207/anaconda/envs/allennlp/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/u/scratch1/jain207/allennlp/allennlp/run.py", line 10, in <module>
    from allennlp.commands import main  # pylint: disable=wrong-import-position
  File "/u/scratch1/jain207/allennlp/allennlp/commands/__init__.py", line 4, in <module>
    from allennlp.commands.serve import add_subparser as add_serve_subparser
  File "/u/scratch1/jain207/allennlp/allennlp/commands/serve.py", line 27, in <module>
    from allennlp.service import server_sanic
  File "/u/scratch1/jain207/allennlp/allennlp/service/server_sanic.py", line 20, in <module>
    from allennlp.models.archival import load_archive
  File "/u/scratch1/jain207/allennlp/allennlp/models/__init__.py", line 7, in <module>
    from allennlp.models.decomposable_attention import DecomposableAttention
  File "/u/scratch1/jain207/allennlp/allennlp/models/decomposable_attention.py", line 9, in <module>
    from allennlp.modules import FeedForward, MatrixAttention
  File "/u/scratch1/jain207/allennlp/allennlp/modules/__init__.py", line 15, in <module>
    from allennlp.modules.text_field_embedders import TextFieldEmbedder
  File "/u/scratch1/jain207/allennlp/allennlp/modules/text_field_embedders/__init__.py", line 9, in <module>
    from allennlp.modules.text_field_embedders.basic_text_field_embedder import BasicTextFieldEmbedder
  File "/u/scratch1/jain207/allennlp/allennlp/modules/text_field_embedders/basic_text_field_embedder.py", line 10, in <module>
    from allennlp.modules.token_embedders.token_embedder import TokenEmbedder
  File "/u/scratch1/jain207/allennlp/allennlp/modules/token_embedders/__init__.py", line 7, in <module>
    from allennlp.modules.token_embedders.embedding import Embedding`
  **File "/u/scratch1/jain207/allennlp/allennlp/modules/token_embedders/embedding.py", line 7, in <module>
  from torch.nn.functional import embedding
ImportError: cannot import name 'embedding'**

-----------------
Any help would be appreciated !

**Comment by matt-gardner** [comment]
You need to upgrade to pytorch 0.2.  This is a version issue.
