### ISSUE TITLE
TypeError: forward() got an unexpected keyword argument 'tokens'

### ISSUE THREAD

**Issue by manelAffi** [allenai/allennlp#3586]
**System:**
 - OS: ubuntu 18.14
 - Python version: 3.7
 - AllenNLP version: 0.9.0
 - PyTorch version: 1.17.2

**Question**
I'm beginner with allennlp. I'm trying to train  the **simple_seq2seq** model for **named entity recognition** task on the CoNLL 2003 dataset  using **BERT embeddings**. I always get the following error message:

 File "/home/manel/anaconda/bin/allennlp", line 10, in <module>
    sys.exit(run())
  File "/home/manel/anaconda/lib/python3.7/site-packages/allennlp/run.py", line 18, in run
    main(prog="allennlp")
  File "/home/manel/anaconda/lib/python3.7/site-packages/allennlp/commands/__init__.py", line 102, in main
    args.func(args)
  File "/home/manel/anaconda/lib/python3.7/site-packages/allennlp/commands/train.py", line 124, in train_model_from_args
    args.cache_prefix)
  File "/home/manel/anaconda/lib/python3.7/site-packages/allennlp/commands/train.py", line 168, in train_model_from_file
    cache_directory, cache_prefix)
  File "/home/manel/anaconda/lib/python3.7/site-packages/allennlp/commands/train.py", line 252, in train_model
    metrics = trainer.train()
  File "/home/manel/anaconda/lib/python3.7/site-packages/allennlp/training/trainer.py", line 478, in train
    train_metrics = self._train_epoch(epoch)
  File "/home/manel/anaconda/lib/python3.7/site-packages/allennlp/training/trainer.py", line 320, in _train_epoch
    loss = self.batch_loss(batch_group, for_training=True)
  File "/home/manel/anaconda/lib/python3.7/site-packages/allennlp/training/trainer.py", line 261, in batch_loss
    output_dict = self.model(**batch)
  File "/home/manel/anaconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'tokens'
 
here is the config file code:
 `{
"dataset_reader": {
    "type": "conll2003",
    "tag_label": "ner",
     "coding_scheme": "BIOUL",
   
    "token_indexers": {
    
 "bert": {
          "type": "bert-pretrained",
         "pretrained_model": "bert-base-cased",          
          "do_lowercase": false,
          "use_starting_offsets": true
          } , 
"token_characters": {
        "type": "characters",
        "min_padding_length": 3
      }
     
      }
    
  },
  "train_data_path": "XXXXXXXXXX",
  "validation_data_path": "XXXXXXXXXX",
  "test_data_path":"XXXXXXXXXX",
  "model": {
    "type": "simple_seq2seq",
    
    "source_embedder": {
           
        "allow_unmatched_keys": true,
   "embedder_to_indexer_map": {
            "bert": ["bert", "bert-offsets"],
            "token_characters": ["token_characters"],
        },
        "token_embedders": {
            "bert": {
                "type": "bert-pretrained",
               "pretrained_model": "bert-base-cased",
                    
            },
 
      } 
    },

    "encoder": {
      "type": "lstm",
      "input_size": 768,
      "hidden_size": 200,
      "num_layers": 2,
      "dropout": 0.5,
      "bidirectional": true
    },
    
    
    "scheduled_sampling_ratio": 1.0,
    "max_decoding_steps": 200,
    "target_namespace": "target_tokens",
    "attention_function": {"type": "dot_product"} 
    
  },
  "iterator": {
    "type": "basic",
    "batch_size": 64
  },
  "trainer": {
    "optimizer": {
        "type": "adam",
        "lr": 0.001
    },
    "validation_metric": "+f1-measure-overall",
    "num_serialized_models_to_keep": 3,
    "num_epochs": 30,
    "grad_norm": 5.0,
    "patience": 25,
    "cuda_device": -1
  }
}`
Are there any ideas how to solve it?

**Comment by kernelmachine** [comment]
Hi there,

The seq_2_seq model expects `source_tokens` and `target_tokens` as input to its forward function: https://github.com/allenai/allennlp/blob/master/allennlp/models/encoder_decoders/simple_seq2seq.py#L202

The ConLL 2003 dataset reader outputs, `tokens` and `tags` : https://github.com/allenai/allennlp/blob/master/allennlp/data/dataset_readers/conll2003.py#L137

Instead of the seq_2_seq model, you can use the CRF tagger with BERT embeddings: https://github.com/allenai/allennlp/blob/master/allennlp/models/crf_tagger.py

Hope that answers your questions. Feel free to re-open if not!

**Comment by manelAffi** [comment]
@kernelmachine thanks a lot for your response.
Is there any allennlp model  that develop the encoder decoder architecture for named entity recognition task?

**Comment by kernelmachine** [comment]
I don't believe so, sorry! You can probably modify the CoNLL 2003 dataset reader to output `tags` as `target tokens`, though, so you can make it work with the simple_seq2seq model.

**Comment by manelAffi** [comment]
@kernelmachine thanks a lot.
 I will try but I'm not sure if the simple_seq2seq  model work with BERT embeddings!
