### ISSUE TITLE
How to load a self-trained Transformer ELMo model for fine tuning

### ISSUE THREAD

**Issue by griff4692** [allenai/allennlp#3590]
I followed the [Training Transformer ELMo](https://github.com/allenai/allennlp/blob/master/tutorials/how_to/training_transformer_elmo.md) instructions.  The model has now been serialized in `model_state_epoch_x.th` files.  How do I load up the model (along with vocabulary) for fine-tuning on a separate task.  I basically just want to encode sentences with the fine tuned model.

Any help is much appreciated.  Thanks so much!

**Comment by kernelmachine** [comment]
Hi there, with the `model.tar.gz` file you get after training the transformer ELMo, you can use `allennlp fine-tune` to fine-tune the LM on additional data https://github.com/allenai/allennlp/blob/master/allennlp/commands/fine_tune.py.

Closing for now, feel free to re-open if you have any additional questions.
