### ISSUE TITLE
Make `Token` class extensible.

### ISSUE THREAD

**Issue by r3dir3ct** [allenai/allennlp#3591]
**Is your feature request related to a problem? Please describe.**
I'd like to add additional task-specific tags(similar to pos/ner tags) which are not included in the attributes of the current `Token` class  to enrich the embeddings. Thus, I have to extend the `Token` class in AllenNLP.
However, it seems impossible to creating `MyToken` class that subclass the `Token` class (inheriance seems a must to not breaking type checking in other classes) according to [this link on StackOverflow](https://stackoverflow.com/questions/44287623/a-way-to-subclass-namedtuple-for-purposes-of-typechecking`)

**Describe the solution you'd like**
Replace the `NamedTuple` with the new `dataclass`, which introduced in Python 3.7 based on [PEP557](https://www.python.org/dev/peps/pep-0557/). 
You can also refer to the discussion in the above StackOverflow link.

**Comment by r3dir3ct** [comment]
In Python 3.6, `dataclasses` module can be obtained by `pip`.
If necessary, I would like to contribute a PR.

**Comment by matt-gardner** [comment]
Yes, this sounds like a good idea, please make a PR. Joel did some profiling when he implemented it this way; it would be good to know if switching to a dataclass is dramatically slower than how it is now.

**Comment by dirkgr** [comment]
This guy says data class is faster: https://medium.com/@jacktator/dataclass-vs-namedtuple-vs-object-for-performance-optimization-in-python-691e234253b9

**Comment by matt-gardner** [comment]
That also makes it look like named tuple would be slower than object, though Joel found the opposite for us (by a lot), so I'd still want to see some metrics in our typical use cases.
