### ISSUE TITLE
Test failures on NFS drive

### ISSUE THREAD

**Issue by matt-gardner** [allenai/allennlp#360]
Our tests create and delete directories very rapidly, and this doesn't play well with high-latency NFS connections.  @roys174 ran into test failures when running this from his UW machine that has an NFS drive, where the failure was obviously due to NFS (couldn't delete the NFS metadata file in the test directory because the resource was busy).  Removing the delete inside of `tearDown` doesn't work, because some tests rely on having an empty `TMP_TEST/` directory when they start (e.g., tests that train something, because of our restart behavior).

Moving the test directory to `/tmp/allennlp_tests/` instead of `TMP_TEST/` _should_ fix the issue, because that will always use the local disk instead of NFS.  @joelgrus suggested `tempfile.mkdtemp()`, which should also work, particularly if you say the prefix is `/tmp`.

**Comment by matt-gardner** [comment]
@roys174, you want to try changing this line to `/tmp/allennlp_tests/`, and see if it fixes your issue?

**Comment by roys174** [comment]
Thanks Matt and Joel for the quick fix! I now pass 258 tests and skip 1,
which I assume is fine?

**Comment by joelgrus** [comment]
yes, that's good

**Comment by schmmd** [comment]
@roys174 I'd keep looking for strategic opportunities to move data off of the NFS drive.  It took me about a year to realize how much latency it had.  One day, I symlinked my `.eclipse` folder to `/scratch/eclipse` and had a dramatic improvement in how fast my machine was...
