### ISSUE TITLE
Multi-node training: `allennlp.common.util.is_master` doesn't return the correct value

### ISSUE THREAD

**Issue by scarecrow1123** [allenai/allennlp#3600]
**Describe the bug**
Currently [`allennlp.common.util.is_master`](https://github.com/allenai/allennlp/blob/master/allennlp/common/util.py#L507) returns `True` only for master process in the master node. The comments in the function mentions it handles multi-node case as well, but it is wrong. In multi-node training, each node has a logical master which will be responsible for showing training progress, metric logging, serializing, etc. Failing to return `True` in such cases will disable the said functionalities in non-master nodes.

**To Reproduce**
Train in a multi-node setup as below:
First node: `allennlp train <config> -s output/ --node-rank 0`
Second node: `allennlp train <config> -s output/ --node-rank 1`

**Expected behavior**
Following should be available in node 1:
1. Training progress should be shown
2. Metric logging should be done
3. Serialization of intermediate states/weights should happen

In node 0, all the above are working as expected.

**Comment by brendan-ai2** [comment]
@scarecrow1123, thanks for pointing this out. Do you know of any other gotchas with the multi-node case? We didn't consider that particularly thoroughly (e.g. add comprehensive tests) last year, so it would be great to fix it up.

Also, if you have the time, could you flesh out the "To Reproduce" section? That would speed up investigating this bug.

**Comment by scarecrow1123** [comment]
@brendan-ai2 
>  Do you know of any other gotchas with the multi-node case? We didn't consider that particularly thoroughly (e.g. add comprehensive tests) last year, so it would be great to fix it up.

I gave a couple of PRs for minor issues that popped up with distributed/multi-node training. They're already merged and this is the pending one from my personal setup. Hopefully there aren't more. I'm not entirely sure on how multi-node setups are tested, it would be interesting to know if you have come across such stuff. 

> Also, if you have the time, could you flesh out the "To Reproduce" section? That would speed up investigating this bug.

I've added few more details. Thanks!
