### ISSUE TITLE
Add a "log once" function to our loggers.

### ISSUE THREAD

**Issue by matt-gardner** [allenai/allennlp#3606]
It would be really nice if we could call something like `logger.warn_once(message)`.  There are *lots* of times where we want to do something like this.

If there isn't already a pre-baked solution for this, to implement this we probably need to have our own wrapper around around the calls to `logging.getLogger`, or instead of `import logging` do `from allennlp.common import logging`, and have our wrapper there.

**Comment by bellecarrell** [comment]
I created a PR for this issue. I made a few changes to comply with black that required removing star imports, so using the custom logger currently requires `from allennlp.common.logging import getLogger`.
