### ISSUE TITLE
Create a text_field_util.py, pulling methods out from nn/util.py

### ISSUE THREAD

**Issue by matt-gardner** [allenai/allennlp#3609]
We have quite a few methods now for wrangling text field outputs (getting masks, getting tokens, etc.).  It's probably worth splitting them out into a separate utility, especially as `nn/util.py` is monstrously large.

Though, I could see counter arguments, that having one place for all util functions makes it easy to know where to find them, and IDEs should autocomplete the function if you know at least some of the name...

**Comment by DeNeutoy** [comment]
i'm kind of cold on this, the new docs make it really easy to find new functions etc. https://allenai.github.io/allennlp-docs/api/nn/util/

I think there are some that could live elsewhere, like:

https://allenai.github.io/allennlp-docs/api/nn/util/#add_sentence_boundary_token_ids
https://allenai.github.io/allennlp-docs/api/nn/util/#remove_sentence_boundaries

are elmo specific,

https://allenai.github.io/allennlp-docs/api/nn/util/#combine_tensors

these 3 are used mostly in the attention code etc.

If we were going to split some out, i'm not sure that text field specific ones would be the best target

**Comment by matt-gardner** [comment]
Maybe this would be useful, but it's not high enough priority or a big enough of a problem to actually do anything about right now.  Closing this issue.
