### ISSUE TITLE
Remove reference to MODELS.md in README (and replace it with the right pointer, whatever that is)

### ISSUE THREAD

**Issue by andrewschreiber** [allenai/allennlp#3610]
https://github.com/allenai/allennlp/blob/master/MODELS.md returns a 404 and https://allenai.github.io/allennlp-docs/MODELS.md is also broken (see below)

Is there a working link somewhere?

![image](https://user-images.githubusercontent.com/1892071/72312852-44e5bb00-363e-11ea-8ced-ed4220c69e88.png)

**Comment by matt-gardner** [comment]
@schmmd, what did we do with that list?  And @DeNeutoy, looks like there's a file referenced in the docs that shouldn't be there.  Oh, that's coming from our README...

Changing the name of this issue and assigning it to @schmmd, as I think you have the most context on what happened here.

**Comment by schmmd** [comment]
See https://github.com/allenai/allennlp/pull/3530.  I moved that information into the docstrings of https://github.com/allenai/allennlp-hub/blob/master/allennlp_hub/pretrained/allennlp_pretrained.py.  I'll update the link reported.
