### ISSUE TITLE
Proper Bert Pooling

### ISSUE THREAD

**Issue by mahnerak** [allenai/allennlp#3629]
The jsonnet configuration 
 https://github.com/allenai/allennlp/blob/master/allennlp/tests/fixtures/bert/bert_pooler.jsonnet suggests using `bert_pooler` with `bert-pretrained` with `offsets` enabled, but the `BertEmbedder` returns embeddings for tokens (not wordpieces), so there's no `CLS` there. 

To do a proper Bert pooling we need to disable `bert-offset`, isn't it?

**Comment by matt-gardner** [comment]
I'm actually not sure what the right way is to do that with the old BERT code.  We are moving to using our `PretrainedTransformer*` classes instead.  Figuring out the right way to do this kind of pooling is on our list of things to do, but not at the top right now.  Contributions welcome here for now, until we get to it ourselves (which will realistically be at least a month, I think; we're doing more complex models before doing classifiers that would want a pooler).

**Comment by matt-gardner** [comment]
This is basically duplicate with #3305; adding a note there and closing this issue.
