### ISSUE TITLE
Pytorch 1.4 breaks RNN drop connect

### ISSUE THREAD

**Issue by DeNeutoy** [allenai/allennlp#3637]
Pytorch has released 1.4, and now this test consistently fails:
https://github.com/allenai/allennlp/blob/master/allennlp/tests/modules/drop_connect_test.py#L29

it's possibly to do with this commit:
https://github.com/pytorch/pytorch/pull/28562

This module does some super funky stuff with the weights of a submodule it is passed, and so does pytorch in the rnn case (flattening weights, unflattening them etc). Maybe we should just delete it? I have zero idea how to fix it.

**Comment by matt-gardner** [comment]
Related: https://github.com/allenai/allennlp/pull/3357#issuecomment-575308466

**Comment by rloganiv** [comment]
I am fine with deleting this module. I agree the implementation is very hacky (unfortunately by neccesity) and in my experience very unstable - I've been working with different versions of drop conenct since PyTorch 0.4.1 and every release seems to introduce a new issue.
