### ISSUE TITLE
HF Transformers Model Conversion

### ISSUE THREAD

**Issue by mojivalipour** [allenai/allennlp#3640]
**System (please complete the following information):**
 - OS: [Linux]
 - Python version: [3.7.5]
 - AllenNLP version: ["I installed from master"]

**Question**
* Is it possible to convert HuggingFace Transformers GPT2 to the AllenNLP model to use in the AllenNLP Demo interface? next-token-lm?

**Comment by matt-gardner** [comment]
This is what we did for the model in our demo, which you can find here: https://demo.allennlp.org/next-token-lm, with the model available at this link: https://storage.googleapis.com/allennlp-public-models/gpt2-next-word-lm-2019.09.19.tar.gz

(you can find the link to all demo models by looking in [this file](https://github.com/allenai/allennlp-demo/blob/3f913174dd887fa491eb3b27c68289935592a4ac/models.json#L84) in the demo repository)

If you want to create a similar one yourself, you basically just need to instantiate the model with a config file and save it.  If that's what you're after, and you have trouble, let us know.  Closing this issue for now, but feel free to keep commenting.

**Comment by mojivalipour** [comment]
I just tried to replace weights and adapt the current gpt2 config that you've mentioned to the HF transformers model. However, it seems the model should be extracted from the AllenAI API directly because they have different outputs, including weights file. So, I think it would be awesome if you give me an insight into the process for converting my HF transformers model to something that can be run in the next-token-lm demo.

**Comment by matt-gardner** [comment]
My recommendation: untar that model archive, find its config file.  Change the "model_name" from gpt-2 to a pointer to whatever your weights are (we just call huggingface's `AutoModel`, so if your weights can load from that, that's what you need).  Then, in python code, load the config file, instantiate the model from it, and save it.  That code will look something like this, though what I'm putting here might not work exactly:

```python
config = Params.from_file("config.json")
model = Model.from_params(config["model"])
torch.save(model.state_dict(), "weights.th")
models.archival.archive_model(".", "weights.th")
```

**Comment by mojivalipour** [comment]
Nice, I was looking exactly for the saving method that you've already mentioned it. I will check it ASAP, and if there were any problems, I would let you know.
