### ISSUE TITLE
How to get device in allennlp?

### ISSUE THREAD

**Issue by entslscheia** [allenai/allennlp#3652]
For some reason, I need to get the device used by my current model in my code and assign it to `self._device`. The constructor of my model is as follows:
```python
def __init__(
            self,
            vocab: Vocabulary,
            source_embedder: TextFieldEmbedder,
            target_word_embedder: TextFieldEmbedder,
            encoder: Seq2SeqEncoder,
            max_decoding_steps: int,
            attention: Attention = None,
            attention_function: SimilarityFunction = None,
            beam_size: int = None,
            target_namespace: str = "tokens",
            target_embedding_dim: int = None,
            scheduled_sampling_ratio: float = 0.0,
            use_bleu: bool = True,
    ) -> None:
``` 
You can see that there is an `source_embedder` argument in my constructor. My idea is to get the device of source_embedder's weights, i.e., 
```python
self._device = source_embedder._modules['token_embedder_tokens'].weight.device
```
However, the device I get in this way is always `cpu`, which is different from how the trainer is configured in my json file. My wild guess is that during initialization, all parameters of my model are put on the cpu device first, and the trainer will move them to the specified cuda device during training. So is there any better way than hard coding it to get the device in `__init__`?

**Comment by matt-gardner** [comment]
Can you just grab it in `forward()`? It'll be on the right device by then. Hard to give more help than that without more detail about the problem you're trying to solve.

**Comment by DeNeutoy** [comment]
In more detail, you might want to try https://allenai.github.io/allennlp-docs/api/nn/util/#get_device_of
