### ISSUE TITLE
Remove files_to_add functionality

### ISSUE THREAD

**Issue by matt-gardner** [allenai/allennlp#3657]
Our ability to use and cache URLs should now be preferred over `files_to_archive`.  That old functionality is a main remaining cause of needing a custom `from_params` method, and it's causing headaches as I'm trying to update configs for https://github.com/allenai/allennlp-hub/pull/14.  It looks like if you untar the model archive, modify the config, then retar the archive, things that used to work in the "files_to_archive" bit no longer work, for reasons I don't yet understand.

**Comment by brendan-ai2** [comment]
Which model did you get errors from after retarring? I'd be happy to dig into that a bit.
