### ISSUE TITLE
Make find_learning_rate compatible with DistributedDataParallel.

### ISSUE THREAD

**Issue by brendan-ai2** [allenai/allennlp#3658]
**Describe the bug**
`find-lr` cannot use multiple GPUs. This is a regression. Multi-GPU compat was intentionally added in https://github.com/allenai/allennlp/pull/2045. More specifically, allennlp/tests/commands/find_learning_rate_test.py::TestFindLearningRate::test_find_learning_rate_multi_gpu currently fails. In 79601fa6f09d3fb6fedc3965850e5df907b716ea, for instance. 

**To Reproduce**
Run `pytest allennlp/tests/commands/find_learning_rate_test.py` on a multi-GPU machine. Be sure to use a commit at or before 79601fa6f09d3fb6fedc3965850e5df907b716ea as I intend to flip the assert to unbreak our tests.

**Expected behavior**
Test passes.

**System (please complete the following information):**
 - OS: Ubuntu 16.04.4 LTS
 - Python version: Python 3.6.7 :: Anaconda, Inc.
 - AllenNLP version: 79601fa6f09d3fb6fedc3965850e5df907b716ea
 - PyTorch version: 1.2.0

**Additional context**
There are other commands that could benefit from DistributedDataParallel, e.g., `evaluate`. We should try to reuse code between them.

**Comment by DeNeutoy** [comment]
This is fine in it's current state, it seems unlikely that making this work in a more robust fashion would be valuable for the work it would take.
