### ISSUE TITLE
Why do all the internal tutorials disappear?  T^T

### ISSUE THREAD

**Issue by SephiHorse** [allenai/allennlp#3661]
![image](https://user-images.githubusercontent.com/47956194/72780908-001fdc80-3c5b-11ea-8cb1-a0507b356371.png)

**Comment by SephiHorse** [comment]
![image](https://user-images.githubusercontent.com/47956194/72781017-39f0e300-3c5b-11ea-810d-d6f58a305426.png)

**Comment by DeNeutoy** [comment]
Hi, they now live in the docs folder:
https://github.com/allenai/allennlp/tree/master/docs/tutorials

However, you might like to view them on our new docs website:

https://allenai.github.io/allennlp-docs/tutorials/getting_started/predicting_paper_venues/predicting_paper_venues_pt1/

**Comment by SephiHorse** [comment]
@DeNeutoy Thx!  XD
