### ISSUE TITLE
Possible race condition in metric calculation during multi-gpu training

### ISSUE THREAD

**Issue by cemilcengiz** [allenai/allennlp#3663]
**Describe the bug**
Allennlp models normally calculate the metrics in the model forward methods. However, this may cause synchronization issues between gpus while doing multi-gpu training using training_util.data_parallel. Regarding this, I noticed problems while I was training a BERT model on a classification task. Specifically, the accuracy recorded after each epoch was different among multiple runs of the same model with the same training configuration, although I used the prepare_environment to set the same seed. The stranger thing is that the accuracy sometimes exceeds 1.0, which was very confusing. I noticed that jiant users face a similar problem during multi-gpu training as can be seen from https://github.com/nyu-mll/jiant/issues/947#issue-516769220.
As I understand, their current solution is to take out metric calculation from model's forward method. Instead, they do the calculation on a single gpu after forward call returns in the trainer.

**To Reproduce**
Take a powerful classification model (e.g. BERT) and train it with multiple-gpus on a very small toy dataset so that it can overfit it. If you disable the patience and wait for some time, the model might exceed 1.0 accuracy because of this possible bug.

**Comment by DeNeutoy** [comment]
Oh! I think this line is just in the wrong place:

https://github.com/allenai/allennlp/blob/master/allennlp/training/trainer.py#L562

It needs to be above the section that computes the metrics. Want to send a PR?

**Comment by cemilcengiz** [comment]
Actually, I am using version 0.9 so I do not have that line.

**Comment by DeNeutoy** [comment]
Oh! yeah, sorry - we've actually removed all of the old multi-gpu code which used `DataParallel`. We are now using `DistributedDataParallel`, which should be considerably faster. Unfortunately it means that we won't be able to fix your problem, as we won't have another release with that code in. I'll leave this open because it needs to be fixed regardless, so thanks!
