### ISSUE TITLE
Provide optional pinned dependencies

### ISSUE THREAD

**Issue by brendan-ai2** [allenai/allennlp#3675]
I'm opening this issue mostly to request some discussion. I'm unsure of whether this is the right solution.

**Is your feature request related to a problem? Please describe.**
Consider the scenario where we make a change in a non-backwards compatible way. This is fine because a user can simply use a previously released version. However, since we let our dependencies float, newly released dependencies may not be compatible with the previously released `allennlp`.

**Describe the solution you'd like**
During a release or perhaps during CI we would run our tests and then `pip freeze` our dependencies -- providing them in some form to our users. Importantly, this would not be the default as users may have conflicting requirements. For users that use the standard AllenNLP tools with no or minimal additional dependencies (what I suspect is the common case) this would allow them to easily run code from previous versions.

**Describe alternatives you've considered**
1. We could pin dependencies by default. This works for applications, but not for a library given the aforementioned user conflicts.
2. Status quo. As little pinning as possible.

**Additional context**
This was raised a long time ago in https://github.com/allenai/allennlp/issues/12. Though there IIUC the intention was to make pinning mandatory. The point that applications rather than libraries should do the pinning was also raised. A good one, in my opinion. However, a vanilla use of the AllenNLP tools is arguably more like an application than a library, so providing pinning as an option may still have merit.

**Comment by matt-gardner** [comment]
I don't have a strong opinion on this point, but I would just point out that I think the "vanilla use of AllenNLP" is as a library that a researcher imports and uses in their project, which might also need to bring in other stuff.

**Comment by brendan-ai2** [comment]
Absolutely. I'm optimistic looking at https://github.com/allenai/allennlp-semparse/blob/master/requirements.txt and https://github.com/allenai/allennlp-reading-comprehension/blob/master/requirements.txt that the additional dependencies are minor, so a user could conceivably get to a working state from a copy of our pinned dependencies plus some fiddling with their own.

However, this issue could also be an indication that this approach is just wrong and that the end user really does have to be the one to pin dependencies, optional or not.

**Comment by DeNeutoy** [comment]
Whether dependencies will break a project is probably application specific - e.g for any deployed code I do this pip freeze method. However, I am not aware of any other open source libraries that actually do this, and we should follow the status quo of also not doing it, mostly because it's easier.
