### ISSUE TITLE
How to get the epoch number in my model?

### ISSUE THREAD

**Issue by entslscheia** [allenai/allennlp#3682]
For allennlp, the training procedure is implemented in `trainer`, which for most of the time we do not need to modify, and we only need to write our own model and dataset reader. This makes it more difficult to get the epoch number in my code when I want to let my model have some different behaviors in different epochs. Now I just add a data field `self._epoch` to my model, and I calculate it by adding one during every `forward` and divide it by the number of batches of an epoch (i.e. the total samples number divided by the batch size). This is pretty awkward.  Is there any better way to get the current epoch number during training in my model?

**Comment by DeNeutoy** [comment]
Hi, we have quite a tragic solution to this currently which is a flag on the iterator which adds a field to your instances containing the epoch number:

https://allenai.github.io/allennlp-docs/api/data/iterators/data_iterator/

It's not a great solution, and probably no different to what you are currently doing, sorry..

**Comment by entslscheia** [comment]
> Hi, we have quite a tragic solution to this currently which is a flag on the iterator which adds a field to your instances containing the epoch number:
> 
> https://allenai.github.io/allennlp-docs/api/data/iterators/data_iterator/
> 
> It's not a great solution, and probably no different to what you are currently doing, sorry..

I see. Thanks for the response.

**Comment by matt-gardner** [comment]
Maybe a better solution once we've figured out the trainer situation is to recommend using a callback to increment a field on the model?

**Comment by entslscheia** [comment]
> Maybe a better solution once we've figured out the trainer situation is to recommend using a callback to increment a field on the model?

Hi. I don't quite get it. What exactly do you refer to  a callback here?

**Comment by matt-gardner** [comment]
Sorry, that was a cryptic note to @DeNeutoy about future development plans, not a suggestion for anything you can do now.

**Comment by dirkgr** [comment]
For anyone who gets here from Google, we now have a `TrackEpochCallback` here: https://github.com/allenai/allennlp/blob/2623c4bfb24d917ac36454dc202d1ddfd536b36b/allennlp/training/trainer.py#L181

Documentation for it is here: https://docs.allennlp.org/main/api/training/trainer/#trackepochcallback
