### ISSUE TITLE
Callback trainer and multi-GPU training

### ISSUE THREAD

**Issue by scarecrow1123** [allenai/allennlp#3685]
We may have to review the usage of `DistributedDataParallel`(DDP) in the current `CallbackTrainer` implementation since I realized there are a few missing things that could cause issues. To give a perspective, introducing DDP into `Trainer` class mostly involved:

1. Wrapping `Model` class with `DistributedDataParallel` and using it for forward/backward calls
2. Spawing individual processes for each GPU
3. Constructing separate `Trainer` instances for each process
4. Allow/disallow all processes to work on a specific parts of the code. For example, only the master trainer process would write files to disk, log metrics to Tensorboard, etc.
5. Computing metrics and maintaining logs across processes

In `CallbackTrainer`, points 1, 2, 3 & 5 wouldn't differ from how it is handled in the regular case(they're already handled). Since serialization, logging and other stuff are moved out, `CallbackTrainer` needs to handle 4 in a different way when compared to how it is done in `Trainer`. Perhaps certain callbacks need to be triggered only from the master process?
I would like to get a high level opinion on how this could be achieved. But this may need a clear direction to be set on how `CallbackTrainer` would be evolved in the future. Specifically a clarity from #3519 would help fixing this. 

Your thoughts please @DeNeutoy @brendan-ai2 ?

**Comment by DeNeutoy** [comment]
We are still not sure what to do about the callback trainer, so currently it is unimportant that it works with DDP. Thanks for raising these crisp points of discussion though!

**Comment by brendan-ai2** [comment]
Adding to the milestone in case we switch to the callback trainer.

**Comment by matt-gardner** [comment]
We have removed the callback trainer (in favor of adding some targeted callback / logging functionality to the default trainer) so I'm closing this issue.
