### ISSUE TITLE
API docs aren't sorted properly

### ISSUE THREAD

**Issue by matt-gardner** [allenai/allennlp#3686]
I just looked at our API docs for the first time, trying to find something.  The top level is sorted alphabetically, but the second level isn't:
<img width="161" alt="Screen Shot 2020-01-28 at 7 58 44 AM" src="https://user-images.githubusercontent.com/3291951/73280983-2934f580-41a4-11ea-8dba-a6528049eabd.png">

Makes it pretty hard to find things under `data/`, and any other non-top-level item.

**Comment by DeNeutoy** [comment]
This needs to be sorted in the same way the final `nav_entries` is:

https://github.com/allenai/allennlp/blob/master/scripts/build_docs.py#L69
