### ISSUE TITLE
consider creating mypy stubs for (some small subset of) pytorch

### ISSUE THREAD

**Issue by joelgrus** [allenai/allennlp#369]
right now none of our pytorch code is really being typechecked. mypy provides a "stubs" functionality that allows you to typecheck third-party libraries.

I have no idea how easy this is, but it's worth investigating.

**Comment by matt-gardner** [comment]
#374 is experimenting with this.  We're not sure yet if it's a good idea.

**Comment by matt-gardner** [comment]
Pretty sure we don't need to keep this around anymore.  @joelgrus, feel free to re-open if you disagree.
