### ISSUE TITLE
allennlp.modules.seq2seq_encoders.Elmo does not exist anymore

### ISSUE THREAD

**Issue by AndreaSottana** [allenai/allennlp#3702]
**Describe the bug**
On the file allennlp/allennlp/modules/elmo.py (link below) https://github.com/allenai/allennlp/blob/4adad1ca217fa5154937946350e0a8d1a05b410d/allennlp/modules/elmo.py
 in the class _ElmoBiLm(torch.nn.Module), the docstring says "This is a lower level class, useful
    for advanced uses, but most users should use `allennlp.modules.seq2seq_encoders.Elmo`
    directly."
 However, there is no file seq2seq_encoders.py containing class Elmo within the modules folder. Instead, seq2seq_encoders is a folder, and it doesn't contain any file named Elmo.py

**To Reproduce**
Run:
from allennlp.modules.seq2seq_encoders import Elmo

**Expected behavior**

I expected this to work correctly, but instead it raises an InputError (see below)

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-81d7b747b8d0> in <module>
----> 1 from allennlp.modules.seq2seq_encoders import Elmo

ImportError: cannot import name 'Elmo'

**System (please complete the following information):**
 - OS: MacOs 10.14.6 (Mojave)
 - Python version: 3.6.4
 - AllenNLP version: 0.9.0

**Comment by DeNeutoy** [comment]
Sorry, those are wrong - it should point to the `Elmo` class in that same file, so `allennlp.modules.Elmo`. Want to send a quick PR to fix it?
