### ISSUE TITLE
Implementation of RMS Normalization

### ISSUE THREAD

**Issue by avinashsai** [allenai/allennlp#3711]
**Is your feature request related to a problem? Please describe.**
RMS Normalization https://openreview.net/pdf?id=SygkZ3MTJE is a normalization technique proposed for normalizing CNN and LSTM.

**Describe the solution you'd like**
I have experimented Layer Normalization and RMS Normalization using LSTM on IMDB dataset. Experiment results can be found here: https://github.com/avinashsai/All-you-need-to-know-about-Normalization/blob/master/Experiments/Normalization_IMDB.ipynb. I would like to include this normalization technique in the framework. Please share your thoughts on this.  

Thank you

**Comment by avinashsai** [comment]
@matt-gardner please share your thoughts on this
Thank you.

**Comment by avinashsai** [comment]
@matt-gardner Please share your thoughts on this.
Thank you

**Comment by schmmd** [comment]
@avinashsai what's your motivation for adding this to the library?  I don't know much about RMS normalization.

**Comment by avinashsai** [comment]
RMS Normalization is computationally simpler to Layer Normalization. There are very few normalization layers proposed for RNN. RMS Normazation is one of them.

**Comment by DeNeutoy** [comment]
Hi @avinashsai, 

Thanks for the contribution. Unfortunately this paper does not demonstrate statistically significant performance improvements over LayerNorm, and the speedup also seems to be marginal. It's great code to experiment with, but I don't think it needs to be in allennlp.

**Comment by schmmd** [comment]
Closing as we are not convinced this feature should be in AllenNLP.
