### ISSUE TITLE
Make **kwargs inference robust to multiple inheritance

### ISSUE THREAD

**Issue by matt-gardner** [allenai/allennlp#3716]
We somewhat frequently do things like `class MyModel(torch.nn.Module, FromParams)`, but our argument inference code is not robust to this kind of multiple inheritance (it is dependent on the order in which you specify the superclasses).  I don't think we actually run into issues from this right now, because we get lucky in how we typically use `Registrable`, but it's a potential problem.  See https://github.com/allenai/allennlp/pull/3705#discussion_r374321802 for some more context.

We need a simple test case using multiple inheritance, then a fix to the call to `cls.mro()[1]` in our **kwargs inference code.  Should be pretty easy.

**Comment by schmmd** [comment]
@matt-gardner during planning we were wondering whether this would be a breaking change.  What do you think?

**Comment by matt-gardner** [comment]
Should not be a breaking change.

**Comment by matt-gardner** [comment]
Moving to 1.1, as it is neither breaking nor pressing
