### ISSUE TITLE
Cannot set num_serialized_models_to_keep

### ISSUE THREAD

**Issue by viking-sudo-rm** [allenai/allennlp#3719]
**Describe the bug**
`num_serialized_models_to_keep` is no longer a valid option in the trainer config. This seems to be related to recent refactoring of `Trainer` towards using a factory function instead of a constructor, potentially in #3627 .

https://github.com/allenai/allennlp/blob/ea715d4d9fd1bb6a5b52b13c6ad0a8e450ff76a3/allennlp/training/trainer.py

**To Reproduce**
Steps to reproduce the behavior
1. Write a config that sets `num_serialized_models_to_keep`
2. Training it will yield `allennlp.common.checks.ConfigurationError: Extra parameters passed to Trainer: {'num_serialized_models_to_keep': 1}`

**Expected behavior**
Should be able to set the number of checkpoints without an error being thrown.

**System (please complete the following information):**
 - OS: Linux
 - AllenNLP version: I installed from master

**Additional information**
This is bad because the default number of checkpoints (20) will result in large models taking up a lot of disk space.

**Comment by matt-gardner** [comment]
Pretty sure this got moved to be only an argument to the checkpointer. Functionality is still there, just moved.

**Comment by matt-gardner** [comment]
Looks like I forgot to put a note in the release notes about this. I'll close this issue once I update that.

**Comment by viking-sudo-rm** [comment]
Got it. As you said, the argument is not nested inside a checkpointer. So the fix is to change:
```
  "num_serialized_models_to_keep": 1,
```

to

```
  "checkpointer": {
    "num_serialized_models_to_keep": 1,
  },
```

**Comment by matt-gardner** [comment]
I updated the release notes, closing this issue.  Thanks for pointing it out!

**Comment by drussellmrichie** [comment]
> Got it. As you said, the argument is now nested inside a checkpointer. So I fixed it by changing:
> 
> ```
>   "num_serialized_models_to_keep": 1,
> ```
> 
> to
> 
> ```
>   "checkpointer": {
>     "num_serialized_models_to_keep": 1,
>   },
> ```



Hi, has this changed again? I'm getting this error again with the json below, which seems consistent with the syntax above. I'm using AllenNLP 2.6.0 on Linux.

```
local bert_model = "bert-base-uncased";

{
    "dataset_reader": {
      "type": "srl",
      "bert_model_name": bert_model,
    },

    "data_loader": {
      "batch_sampler": {
        "type": "bucket",
        "batch_size" : 32
      }
    },

     "train_data_path": "/home/richier/conll-formatted-ontonotes-5.0-12/conll-formatted-ontonotes-5.0/data/train",
     "validation_data_path": "/home/richier/conll-formatted-ontonotes-5.0-12/conll-formatted-ontonotes-5.0/data/development",
    // "train_data_path": "/net/nfs.corp/allennlp/data/ontonotes/conll-formatted-ontonotes-5.0/data/train",
    // "validation_data_path": "/net/nfs.corp/allennlp/data/ontonotes/conll-formatted-ontonotes-5.0/data/development",
    //"train_data_path": std.extVar("SRL_TRAIN_DATA_PATH"),
    //"validation_data_path": std.extVar("SRL_VALIDATION_DATA_PATH"),

    "model": {
        "type": "srl_bert",
        "embedding_dropout": 0.1,
        "bert_model": bert_model,
    },

    "trainer": {
        "optimizer": {
            "type": "huggingface_adamw",
            "lr": 5e-5,
            "correct_bias": false,
            "weight_decay": 0.01,
            "parameter_groups": [
              [["bias", "LayerNorm.bias", "LayerNorm.weight", "layer_norm.weight"], {"weight_decay": 0.0}],
            ],
        },

        "learning_rate_scheduler": {
            "type": "slanted_triangular",
        },
        "checkpointer": {
            "num_serialized_models_to_keep": 2,
        },
        "grad_norm": 1.0,
        "num_epochs": 15,
        "validation_metric": "+f1-measure-overall",
    },
}
```

**Comment by drussellmrichie** [comment]
Ah, I see now from [here](https://github.com/allenai/allennlp-models/blob/main/training_config/structured_prediction/bert_base_srl.jsonnet) that it ought to be:

```
        "checkpointer": {
            "keep_most_recent_by_count": 2,
        },
```
