### ISSUE TITLE
MultiLabelField does not work with ListField

### ISSUE THREAD

**Issue by zulushakaka** [allenai/allennlp#3721]
**Bug Description**
I'm trying to do sequence prediction with multi-label data, so naturally I used **ListField** with **MultiLabelField**. The program would crash with this error:

> File "/home/conda/xchen002/envs/cohan2019/lib/python3.7/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/home/conda/xchen002/envs/cohan2019/lib/python3.7/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/home/nlp-text/dynamic/xchen002/workspace/sequential_sentence_classification/src/allennlp/allennlp/run.py", line 21, in <module>
>     run()
>   File "/home/nlp-text/dynamic/xchen002/workspace/sequential_sentence_classification/src/allennlp/allennlp/run.py", line 18, in run
>     main(prog="allennlp")
>   File "/home/nlp-text/dynamic/xchen002/workspace/sequential_sentence_classification/src/allennlp/allennlp/commands/__init__.py", line 102, in main
>     args.func(args)
>   File "/home/nlp-text/dynamic/xchen002/workspace/sequential_sentence_classification/src/allennlp/allennlp/commands/train.py", line 124, in train_model_from_args
>     args.cache_prefix)
>   File "/home/nlp-text/dynamic/xchen002/workspace/sequential_sentence_classification/src/allennlp/allennlp/commands/train.py", line 168, in train_model_from_file
>     cache_directory, cache_prefix)
>   File "/home/nlp-text/dynamic/xchen002/workspace/sequential_sentence_classification/src/allennlp/allennlp/commands/train.py", line 252, in train_model
>     metrics = trainer.train()
>   File "/home/nlp-text/dynamic/xchen002/workspace/sequential_sentence_classification/src/allennlp/allennlp/training/trainer.py", line 539, in train
>     train_metrics = self._train_epoch(epoch)
>   File "/home/nlp-text/dynamic/xchen002/workspace/sequential_sentence_classification/src/allennlp/allennlp/training/trainer.py", line 335, in _train_epoch
>     for batch_group in train_generator_tqdm:
>   File "/home/conda/xchen002/envs/cohan2019/lib/python3.7/site-packages/tqdm/std.py", line 1104, in __iter__
>     for obj in iterable:
>   File "/home/nlp-text/dynamic/xchen002/workspace/sequential_sentence_classification/src/allennlp/allennlp/common/util.py", line 104, in <lambda>
>     return iter(lambda: list(islice(iterator, 0, group_size)), [])
>   File "/home/nlp-text/dynamic/xchen002/workspace/sequential_sentence_classification/src/allennlp/allennlp/data/iterators/data_iterator.py", line 153, in __call__
>     tensor_dict = batch.as_tensor_dict(padding_lengths)
>   File "/home/nlp-text/dynamic/xchen002/workspace/sequential_sentence_classification/src/allennlp/allennlp/data/dataset.py", line 137, in as_tensor_dict
>     for field, tensors in instance.as_tensor_dict(lengths_to_use).items():
>   File "/home/nlp-text/dynamic/xchen002/workspace/sequential_sentence_classification/src/allennlp/allennlp/data/instance.py", line 142, in as_tensor_dict
>     tensors[field_name] = field.as_tensor(padding_lengths[field_name])
>   File "/home/nlp-text/dynamic/xchen002/workspace/sequential_sentence_classification/src/allennlp/allennlp/data/fields/list_field.py", line 93, in as_tensor
>     for field in padded_field_list]
>   File "/home/nlp-text/dynamic/xchen002/workspace/sequential_sentence_classification/src/allennlp/allennlp/data/fields/list_field.py", line 93, in <listcomp>
>     for field in padded_field_list]
>   File "/home/nlp-text/dynamic/xchen002/workspace/sequential_sentence_classification/src/allennlp/allennlp/data/fields/multilabel_field.py", line 112, in as_tensor
>     tensor = torch.zeros(self._num_labels, dtype=torch.long)  # vector of zeros
> TypeError: zeros() received an invalid combination of arguments - got (NoneType, dtype=torch.dtype), but expected one of:
>  * (tuple of ints size, tuple of names names, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
>  * (tuple of ints size, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)

**To Reproduce**
This bug can be reproduced by the following code snippet:
```
from allennlp.data.fields import MultiLabelField
f = MultiLabelField([0, 0, 1], num_labels=3, skip_indexing=True)
f.empty_field().as_tensor(None)
```

**Expected behavior**
From my understanding of AllenNLP source code, during padding _empty_field()_ is called to create the padding values, and then the padding fields are directly converted to tensor by _as_tensor_ without being indexed. Here the empty MultiLabelField will cause _as_tensor_ to crash, instead of being converted to a tensor of 0s.

**Quick Fix**
I got around this issue by modifying **multilabel_field.py** and changing the _empty_field()_ method from

```
@overrides
def empty_field(self):
    return MultiLabelField([], self._label_namespace, skip_indexing=True)
```

into

```
@overrides
def empty_field(self):
    f = MultiLabelField([], self._label_namespace, skip_indexing=True)
    f._num_labels = self._num_labels
    return f
```

**System**
 - OS: Linux
 - Python version: 3.7.6
 - AllenNLP version: 0.9.0-unreleased

**Additional context**
Is this indeed a bug, or am I using AllenNLP incorrectly? If it is a bug, then I may have fixed it.

**Comment by matt-gardner** [comment]
Looks like it's a bug.  Instead of setting `f._num_labels` after calling the constructor, though, you can probably just pass `num_labels` to the constructor.  Can you submit a PR to fix this?  It'd be great if you also had a simple test that fails before the change and passes after the change.
