### ISSUE TITLE
Optional[] annotations show up poorly in our docs

### ISSUE THREAD

**Issue by matt-gardner** [allenai/allennlp#3731]
Something in the docs script converts `Optional[X]` into `Union[X, NoneType]`, which is unfortunate and distracting in the docs:

<img width="572" alt="Screen Shot 2020-02-05 at 7 12 43 AM" src="https://user-images.githubusercontent.com/3291951/73854252-0da29e00-47e7-11ea-8e91-7cb967bb16ad.png">

This makes me even more in favor of just removing `Optional[]` annotations from our code.

**Comment by sai-prasanna** [comment]
> This makes me even more in favor of just removing Optional[] annotations from our code.

I think it would be useful to retain Optional in docs. Just fixing the original types instead of aliases being showing up would be better imo.

btw The new docs style of showing long method signatures (which are the norm in allennlp) in a single horizontal line with huge scroll bars affects quick readability.

**Comment by matt-gardner** [comment]
What value do you see in having those annotations? Isn't seeing the fact that there's a default value enough?

**Comment by sai-prasanna** [comment]
Values with Optional annotation should accept explicit `None` sent as a value. For example, say a `source_max_tokens`.
https://github.com/allenai/allennlp/blob/95650acb46c034f7d963af966f987899bcbde5a1/allennlp/data/dataset_readers/seq2seq.py#L64
There can be other parameters where a default value can be set to some integer, but would allow `None` to carry some explicit meaning.
For cases where `None` is not a accepted value, I agree that we must remove the annotation.

**Comment by matt-gardner** [comment]
Fair enough, but do we ever have valid cases where we have `Optional[X] = some_not_none_value`?  I just did a grep through the code, and I saw just a few, but I think all of them that I saw should not have been marked `Optional`.  If the signature is `source_max_tokens: int = None`, doesn't this already tell you that you can pass `None` explicitly?

**Comment by sai-prasanna** [comment]
Might be just my preference/nitpick 😅 but having used typed languages with optionals I find `Optional[int] = None` more asthetic/"typed"/explicit over implicit. 

Interestingly mypy has a check for this `--no-implicit-optional`. Guess it's just a matter of preference.
