### ISSUE TITLE
Figure out how to put signatures on multiple lines in docs, instead of having them scroll vertically

### ISSUE THREAD

**Issue by matt-gardner** [allenai/allennlp#3738]
Issue title should be self-explanatory.  For more evidence that this is an issue, see the end of this comment: https://github.com/allenai/allennlp/issues/3731#issuecomment-582859101, which I agree with.

**Comment by DeNeutoy** [comment]
Yes, there actually is a solution to this.

@justindujardin, who works with spacy, has some docs which are built in a similar way - he has just taken the entire `pydoc_markdown` library source and altered it to do this for his maths equations ml project, [mathy.ai](mathy.ai)


https://github.com/justindujardin/mathy/commit/ba121c0b313a7f190c014fd7c5c1a80d58e54324
