### ISSUE TITLE
Does "register" still take 'constructor' as an argument?

### ISSUE THREAD

**Issue by c4n** [allenai/allennlp#3742]
I'm trying to create my own trainer. and I got this error TypeError: register() got an unexpected keyword argument 'constructor'

e.g. 
@TrainerBase.register("my_trainer", constructor="from_partial_objects")

**Comment by matt-gardner** [comment]
That argument is only available if you're using the latest master.  If you're using a released version (e.g., 0.9), you would get that error.  Things are in a bit of flux at the moment as we're refactoring things for a major new release.
