### ISSUE TITLE
mask with type torch.bool do not support (1.0 - mask)

### ISSUE THREAD

**Issue by Maybewuss** [allenai/allennlp#3745]
**Describe the bug**
I find that many opperations like `(1.0 - mask).to(torch.bool)` in the library, but some functions add 
`mask = mask.float()` while some not, and if mask's type is torch.bool, opreations like `1.0 - mask` will cause error.
> Subtraction, the `-` operator, with a bool tensor is not supported. If you are trying to invert a mask, use the `~` or `bitwise_not()` operator instead.

**To Reproduce**
Steps to reproduce the behavior
When use function like allennlp.nn.util.masked_max/mean

**Additional context**
I think docs should illustrate fine type of parameter mask instead of torch.Tensor.
Since Allennlp had upgraded to pytorch 1.2 , operations like this should be modified, I suggest all functions
that need mask should receive parameter with torch.bool.

**Comment by schmmd** [comment]
@ZhaofengWu's recommendation is to change the type of `mask` to boolean.
