### ISSUE TITLE
Parameters for bidaf

### ISSUE THREAD

**Issue by kellywzhang** [allenai/allennlp#378]
I was wondering if you could release a experiment.json file for the bidaf model that got the performance numbers in the paper: https://arxiv.org/pdf/1611.01603.pdf

I noticed that the parameter settings in the example file are different from those in the bidaf paper.
https://github.com/allenai/allennlp/blob/c9b52613cc3c5ab933bedddef6d63d06380e41b9/tests/fixtures/bidaf/experiment.json

**Comment by matt-gardner** [comment]
The config you're looking for is here: https://github.com/allenai/allennlp/blob/c9b52613cc3c5ab933bedddef6d63d06380e41b9/experiment_config/bidaf.json

**Comment by kellywzhang** [comment]
Thank you so much!

**Comment by kellywzhang** [comment]
I'm getting out of memory error on a GTX 1080 GPU. What type of GPU (memory requirements) does the bidaf model need?

**Comment by matt-gardner** [comment]
That ran just fine on a K80 GPU on an EC2 machine.  I think those have 12GB of memory?  I know, though, that we found a memory leak in one of the GPU drivers, so you need to be sure you've updated that.  @DeNeutoy, do we have any public discussion of this to point @kellywzhang to?  I couldn't find it in my brief search.

Also, the current BiDAF implementation uses a pretty memory-inefficient attention mechanism.  If you replace that with the tri-linear attention found in [this open PR](https://github.com/allenai/allennlp/pull/346/files), it should take a lot less memory.

**Comment by DeNeutoy** [comment]
GTX 1080s have 10GB of memory, so you will have to reduce the batch size a little. R.e the memory leak, see this Issue: https://github.com/pytorch/pytorch/issues/1272 and follow the instructions to update your drivers (or ask the administrators to do so for you). This is related to a CPU memory leak however, so it is unlikely to be the cause of your OOM error on the GPU - much more likely is that you need to reduce the batch size a little.

**Comment by kellywzhang** [comment]
I reduced the batch size from 40 to 35 and it seemed to be working fine, but then it got another cuda out of memory error again during epoch 7 of training. Is there any reason that the GPU memory used would increase with each epoch?

**Comment by matt-gardner** [comment]
Failing on epoch 7 is very likely caused by the memory leak mentioned above.

But, really, we should just use the more efficient attention mechanism for the reference BiDAF implementation. I'll open a separate issue about that.

**Comment by kellywzhang** [comment]
Do you remember which version of the driver had a memory leak?

**Comment by matt-gardner** [comment]
I know that 384.66 does _not_ have it.  The version we were using that had it was somewhere in the 370s.

**Comment by kellywzhang** [comment]
Yep, our driver version is 367.48; we likely have memory leak problem.

**Comment by kellywzhang** [comment]
As the problem is likely due to our old driver. I'm closing the issue.
