### ISSUE TITLE
SemanticRoleLabeler Creates Invalid IOB2 Sequence

### ISSUE THREAD

**Issue by aphedges** [allenai/allennlp#3783]
**Describe the bug**
I am running `bert_srl_shi_2019` on sentences from Wikipedia, which works well in most cases. However, some sentences do not follow the IOB2 sequence like the documentation [semantic_role_labeler - AllenNLP](https://allenai.github.io/allennlp-docs/api/models/semantic_role_labeler/) states. There is a chunk that starts with an `I-` tag and not a `B-` tag.

Here is the human-readable format generated by `SemanticRoleLabelerPredictor.make_srl_string()`: `The group 's ideology outlines its aim as the liberation of Palestine and the restoration of Palestinian rights under the dispensations [set forth in the Qur'an] , and [ARG1: this] [V: translates] [ARG2: into three policy priorities : To evoke the spirit of Jihad ( Resistance ) among Palestinians , Arabs , and Muslims ; to defend Palestinians and their land against the Zionist occupation and its manifestations ; to liberate Palestinians and their land that was usurped by the Zionist occupation forces and settlers] .` Note how the first block does not have a tag.

**To Reproduce**
1. Run the following code:
```python
from allennlp.pretrained import bert_srl_shi_2019

srl_predictor = bert_srl_shi_2019()
tokens = ['The', 'group', "'s", 'ideology', 'outlines', 'its', 'aim', 'as',
          'the', 'liberation', 'of', 'Palestine', 'and', 'the', 'restoration',
          'of', 'Palestinian', 'rights', 'under', 'the', 'dispensations', 'set',
          'forth', 'in', 'the', "Qur'an", ',', 'and', 'this', 'translates',
          'into', 'three', 'policy', 'priorities', ':', 'To', 'evoke', 'the',
          'spirit', 'of', 'Jihad', '(', 'Resistance', ')', 'among',
          'Palestinians', ',', 'Arabs', ',', 'and', 'Muslims', ';', 'to',
          'defend', 'Palestinians', 'and', 'their', 'land', 'against', 'the',
          'Zionist', 'occupation', 'and', 'its', 'manifestations', ';', 'to',
          'liberate', 'Palestinians', 'and', 'their', 'land', 'that', 'was',
          'usurped', 'by', 'the', 'Zionist', 'occupation', 'forces', 'and',
          'settlers', '.']
predictions = srl_predictor.predict_tokenized(tokens)
print(predictions['verbs'][2]['tags'])
```
2. See the following output:
```python
['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O',
 'O', 'O', 'O', 'O', 'O', 'I-ARG2', 'I-ARG2', 'I-ARG2', 'I-ARG2', 'I-ARG2', 'O',
 'O', 'B-ARG1', 'B-V', 'B-ARG2', 'I-ARG2', 'I-ARG2', 'I-ARG2', 'I-ARG2',
 'I-ARG2', 'I-ARG2', 'I-ARG2', 'I-ARG2', 'I-ARG2', 'I-ARG2', 'I-ARG2', 'I-ARG2',
 'I-ARG2', 'I-ARG2', 'I-ARG2', 'I-ARG2', 'I-ARG2', 'I-ARG2', 'I-ARG2', 'I-ARG2',
 'I-ARG2', 'I-ARG2', 'I-ARG2', 'I-ARG2', 'I-ARG2', 'I-ARG2', 'I-ARG2', 'I-ARG2',
 'I-ARG2', 'I-ARG2', 'I-ARG2', 'I-ARG2', 'I-ARG2', 'I-ARG2', 'I-ARG2', 'I-ARG2',
 'I-ARG2', 'I-ARG2', 'I-ARG2', 'I-ARG2', 'I-ARG2', 'I-ARG2', 'I-ARG2', 'I-ARG2',
 'I-ARG2', 'I-ARG2', 'I-ARG2', 'I-ARG2', 'I-ARG2', 'I-ARG2', 'I-ARG2', 'O']
```

**Expected behavior**
The first chunk should either start with a `B-` tag or not exist at all.

**System:**
 - OS: macOS 10.15.3 and CentOS 7
 - Python version: 3.7.5 (installed with pyenv 1.2.16)
 - AllenNLP version: v0.9.0 and `master` [latter requires code changes to handle refactor]

**Comment by schmmd** [comment]
@DeNeutoy any idea on this one?

**Comment by DeNeutoy** [comment]
I'm going to be honest - i'm not sure. What i've done here is to track the offsets mapping the first wordpiece in a token to token indices. Then i've selected out these indices from a vitterbi decoded sequence *at the wordpiece level*. When I implemented this, I thought this would guarantee that the selected out sequence would also be well formed, but apparently not.

**Comment by DeNeutoy** [comment]
Ok, i'm wrong about this, here is an example:

```
Th# #is tok# #en
[O, B-X, I-X, I-X]
```
This case would result in the word level sequence `[O, I-X]` which is an invalid sequence.

Probably the best solution to this is to retrain the SRL model using @ZhaofengWu's pretrained indexers which do modeling on the word level.

**Comment by ZhaofengWu** [comment]
These ones:
https://github.com/allenai/allennlp/blob/master/allennlp/data/token_indexers/pretrained_transformer_mismatched_indexer.py
https://github.com/allenai/allennlp/blob/master/allennlp/modules/token_embedders/pretrained_transformer_mismatched_embedder.py
