### ISSUE TITLE
How to configure the tokenizer of Bert?

### ISSUE THREAD

**Issue by entslscheia** [allenai/allennlp#3790]
Based on your example [here](https://github.com/allenai/allennlp/blob/15613e863ae356901d20d25be65216d9bf51b0ec/allennlp/tests/fixtures/bert/bert_pooler.jsonnet#L9), it seems like the only thing I need to do is to use `"type": "bert-basic"`. But actually this doesn't work for me, `bert-basic` doesn't seem to be a legal option for argument `type`.

**Comment by entslscheia** [comment]
I figured it out by myself.
It should be something like
```json
"source_tokenizer": {
      "type": "pretrained_transformer",
      "model_name": "bert-base-uncased",
      "do_lowercase": true
    }
```
instead of
```json
"source_tokenizer": {
      "type": "bert-basic",
    }
```
 But why is it inconsistent with your example?
Though I am a fan of AllenNLP, sometimes I do feel that AllenNLP can be even better with some easy-to-find / easy-to-read examples or documentations...

**Comment by DeNeutoy** [comment]
We are focused on the 1.0 release right now, so code/configs/examples are going to be shifting a bit, sorry. @matt-gardner is working on a beautiful course which explains a lot of the concepts in allennlp, with examples etc. Hopefully we can improve this over the next month or so, but glad you resolved your problem!
