### ISSUE TITLE
How can I get vocabulary from instances with pre-trained transformer tokenizer(indexer)?

### ISSUE THREAD

**Issue by ahnjaewoo** [allenai/allennlp#3791]
I'm using pre-trained transfomer (bert-base-multilingual-uncased) tokenizer (indexer).
I just want to use pre-defined vocabulary, but there were no such options.
Instead, I tried `Vocabulary.from_instances(dataset)`... but it didn't contain any tokens either.

As a result, I'm just making my vocabulary instance as a temporary solution... but
I just want to know what is the problem. Maybe tokenizer and indexer are under development.

Thanks.

**Comment by ahnjaewoo** [comment]
I think this issue may be related to #3456 

However, the issue is not resolved so far.

**Comment by matt-gardner** [comment]
When you index data using the `PretrainedTransformerIndexer`, the vocabulary gets populated.  This happens here: https://github.com/allenai/allennlp/blob/8c2c5903e7f1bbd4bb8391393fec698d0e119dfe/allennlp/data/token_indexers/pretrained_transformer_indexer.py#L63-L88

In our standard pipeline, this happens for you automatically.  What are you doing where you're running into an issue where you don't have the vocabulary populated?

**Comment by ahnjaewoo** [comment]
I checked whether `_add_encoding_to_vocabulary_if_needed` function populates the vocabulary manually. (It worked well!)

And here's my pipeline
**Dataset**
```
class MyDatasetReader(DatasetReader):
    def __init__(self,
                 lazy: bool = True) -> None:
        super().__init__(lazy=lazy)
        self._token_indexers = {'tokens': PretrainedTransformerIndexer(
            'bert-base-multilingual-uncased')}
        self._tokenizer = PretrainedTransformerTokenizer('bert-base-multilingual-uncased')

    def text_to_instance(self, fields: Dict[str, Field]) -> Instance:
        return Instance(fields)

    def _read(self, mode: str) -> Iterator[Instance]:
        # list of Tokens which is tokenized by self._tokenizer
        translations = self._load_data(mode)

        for translation in translations:
            # Convert to fields
            fields = {
                'source': TextField(translation['source'], self._token_indexers),
                'target': TextField(translation['target'], self._token_indexers)
            }
            yield self.text_to_instance(fields)
```
**Main for vocabulary**
```
reader = MyDatasetReader(lazy=hparams.lazy)
train_dataset = reader.read('train')
dev_dataset = reader.read('dev')
test_dataset = reader.read('test')

# vocab = Vocabulary.from_instances(train_dataset)
# It returns no words in vocab - Vocabulary with namespaces:  Non Padded Namespaces: {'*labels', '*tags'}
# Instead, manually put tokens to vocabulary (I had no choice so far)
vocab = Vocabulary(non_padded_namespaces={'tokens'})
for key, value in reader._tokenizer.tokenizer.vocab.items():
    vocab.add_token_to_namespace(key)
```

I just wanted to get the vocabulary automatically.
Thanks.

**Comment by dirkgr** [comment]
What do you want to do with the vocabulary? Once the indexer runs, it will populate the vocabulary. Before that, it is empty. Why do you need it before the indexer runs?

**Comment by dirkgr** [comment]
Looks like you solved your issue. Feel free to file another issue if we got that wrong!
