### ISSUE TITLE
Tokenization breaks with the new tokenizers in transformers==2.5.0

### ISSUE THREAD

**Issue by bryant1410** [allenai/allennlp#3811]
The following assertion fails with `bert-base-cased` in `transformers==2.5.0`, as now they use their new `tokenizers` library by default.

https://github.com/allenai/allennlp/blob/5356062f57146a6bf1268b6c04f954e15b3a81b5/allennlp/data/tokenizers/pretrained_transformer_tokenizer.py#L296

**Comment by bryant1410** [comment]
The reason seems to be that they don't override `build_inputs_with_special_tokens` for each different tokenizer, so it uses the superclass which doesn't add anything.

**Comment by bryant1410** [comment]
huggingface/transformers#2910

**Comment by ZhaofengWu** [comment]
I think this is the issue with the transformers library where the implementation is not doing what it's supposed to do. I think we can just pin the transformers library version for now.

**Comment by mfuntowicz** [comment]
Hi, 

We have a fix that should land soon on master and should be in the 2.5.1 bug fix release. 

https://github.com/huggingface/transformers/pull/2912

**Comment by dirkgr** [comment]
Thanks, @mfuntowicz!
