### ISSUE TITLE
Maybe write a script to auto-update config files

### ISSUE THREAD

**Issue by DeNeutoy** [allenai/allennlp#3821]
Given that we have made several breaking changes to the config files, it seems possible that we could write a script which does most of the updates. Some of them are quite easy, like removing redundant keys - some of them require more care, like changing the distributed config etc. Seems like it might be possible to get most of the way there?

**Comment by bryant1410** [comment]
I was also thinking about the config files. I think at least we should make some test that makes sure they're still working and not broken.

**Comment by matt-gardner** [comment]
For a test, see #3649.

**Comment by dirkgr** [comment]
Do we want to offer an upgrade path for people coming from 0.9.x? In that case, we should have this. If we don't do this, I'd rather just do them by hand (and maybe try to minimize the pain by deferring it until most changes have been made already). There aren't that many configs, and working out the edge cases from a script like this will likely take more time than just doing it.

**Comment by matt-gardner** [comment]
My vote would be to not do this, and just rely on release notes.
