### ISSUE TITLE
How does multi-GPU work in AllenNLP

### ISSUE THREAD

**Issue by entslscheia** [allenai/allennlp#3831]
I tried to use multi GPUs training with AllenNLP for my experiments. What I found is that using multiple GPUs doesn't really solve the memory problem for me, i.e., the maximum batch size I can use is the same for using a single GPU or 4 GPUs.
I looked up for previous issues and found this #2713 . Based on my understanding, AllenNLP's Multi GPU parallelism runs on batch-level. For example, if there are 100 batches in total for an epoch and I am using 4 GPUs, then each GPU will run 25 batches independently. So this can to some extent help to accelerate the computation but does not reduce the memory usage for each GPU as the batch size are the same for using multi GPUs and using a single GPU.

However, if I remember correctly, the default usage of `DataParallel` in Pytorch is to split each batch into several smaller batches. For example, if the batch size is 64, and I have 4 GPUs, then to each GPU, the batch size is essentially just 16, which can help to reduce the memory usage. So why does AllenNLP adopt a different strategy for multi-GPU usage? I guess multi-GPU training is more necessary for memory issue than speed issue right?

I am not pretty sure about what I said above, please correct me if I am wrong about it. Any suggestions would be greatly appreciated.

**Comment by dirkgr** [comment]
We are re-working how multi-GPU training works in version 1.0. Please take a look at the pre-release notes and try installing the latest `master` to see if that helps.

**Comment by entslscheia** [comment]
@dirkgr Thanks for the response! So am I right about how multi-GPU training works in current AllenNLP?

**Comment by dirkgr** [comment]
I don't know how it worked in version 0.9, but in the latest `master`, it works a lot like gradient accumulation. Every worker will do batches of size `batch_size`, and then the gradients are added and applied. So if you have a batch size of `64` and you run out of memory, you can run two workers with a batch size of `32` each to get (almost) the same result.

**Comment by ptynecki** [comment]
@dirkgr 

Would you like to present the code example: how can I launch two workers with a batch size of 32 each to get (almost) the same result as with 64? Thanks.

**Comment by dirkgr** [comment]
Check out this sample config I made: https://github.com/allenai/allennlp-models/blob/master/training_config/rc/transformer_qa_distributed.jsonnet

**Comment by NoahDrisort** [comment]
> Check out this sample config I made: https://github.com/allenai/allennlp-models/blob/master/training_config/rc/transformer_qa_distributed.jsonnet

Sorry sir, how can I access this file, when I open the link, it is 404
Can you confirm that can I run multi GPU in version 1.0,?
Do I need to set any parameter in config file to run with multi GPU, or AllenNLP automate deal it for me?
Thank you, sir

**Comment by epwalsh** [comment]
@NoahDrisort this tutorial should help: https://medium.com/ai2-blog/tutorial-how-to-train-with-multiple-gpus-in-allennlp-c4d7c17eb6d6
