### ISSUE TITLE
How can we design Model for NESTED NER? need few pro tips

### ISSUE THREAD

**Issue by fahimsun** [allenai/allennlp#3833]
How can we design Nested NER Model as described in 
[A Neural Layered Model for Nested Named Entity Recognition](https://www.aclweb.org/anthology/N18-1131/)

Do i need to create two separate models and Trainner Class? and how backprogation work with two diferent losses collected at each CRF Layer.

![image](https://user-images.githubusercontent.com/32779838/75081907-b256f800-54d6-11ea-9fb6-a29258b32c3f.png)

**Comment by ZhaofengWu** [comment]
Can you have a single model that sums up the multiple losses that you have?
