### ISSUE TITLE
Tokenize sentences by space in sequence tagging task

### ISSUE THREAD

**Issue by JJJJane** [allenai/allennlp#3839]
**System (please complete the following information):**
 - OS: Linux
 - Python version: 3.6.10
 - AllenNLP version: v0.9.0
 - PyTorch version: 1.4.0

**Question**
I trained a sequence tagging model with a data reader configuration of the following:
 "dataset_reader": {
    "type": "sequence_tagging",
    "lazy": true,
    "word_tag_delimiter": "###",
    "token_indexers": {
      "tokens": {
        "type": "single_id",
        "lowercase_tokens": true
      },
      "elmo": {
        "type": "elmo_characters"
      }
    }
  }
When I predict a sentence of 400 words, the output suggests that the model has tokenized the sentence into 412 words, which means it was not tokenized by space. The model output a list like this: ["recent", "incarnation", ",", "the", "iranian", "-", "saudi"], but I expected it to be like ["recent", "incarnation", ",", "the", "iranian-saudi"]. 
Is there any solution without any modification of the source code? I only installed AllenNLP as a package and run it in the command line, don't really want to get into the code part. Thanks!

**Comment by ZhaofengWu** [comment]
Can you provide the input line in question? The `SequenceTaggingDatasetReader` should be tokenizing by whitespaces: https://github.com/allenai/allennlp/blob/v0.9.0/allennlp/data/dataset_readers/sequence_tagging.py#L64-L65

**Comment by JJJJane** [comment]
This is the input line:
python -m allennlp.run predict  \
                       model.tar.gz \
                       data/temp.pred.txt \
                       --output temp.txt \
                       --cuda-device 0 \
                       --batch-size 50 \
		       --silent
It seems that the program splits sentences only by whitespaces and hyphens, no other punctuations.

**Comment by ZhaofengWu** [comment]
Sorry I meant the line in the dataset corresponding to `["recent", "incarnation", ",", "the", "iranian", "-", "saudi"]`.

**Comment by JJJJane** [comment]
@ZhaofengWu OK, that would be "-lrb- cnn -rrb- relations between iran and saudi arabia have always been thorny , but rarely has the state of affairs been as venomous as it is today . tehran and riyadh each point to the other as the main reason for much of the turmoil in the middle east . in its most recent incarnation , the iranian-saudi conflict by proxy has reached yemen in a spiral that both sides portray as climatic . for riyadh and its regional allies , the saudi military intervention in yemen -- `` operation decisive storm '' -- is the moment the sunni arab nation finally woke up to repel the expansion of shia-iranian influence . for tehran and its regional allies -- including the houthi movement in yemen -- saudi arabia 's actions are in defense of a retrogressive status quo order that is no longer tenable . and yet both sides have good reasons to want to stop the yemeni crisis from spiraling out of control and evolving into an unwinnable war . when iranian president hassan rouhani was elected in june 2013 , he pledged to reach out to riyadh . he was up front and called tehran 's steep deterioration of relations with the saudis over the last decade as one of the principal burdens on iranian foreign policy . from lebanon and afghanistan to pakistan and the gaza strip , the iranian-saudi rivalry and conflict through proxy has been deep and costly . and yet despite rouhani 's open pledge , profound differences over syria and iraq in particular have kept riyadh and tehran apart . but if the questions of syria and iraq prevented a pause in hostilities , the saudi military intervention in yemen since late march has all but raised the stakes to unprecedentedly dangerous levels . unlike in syria and in iraq , the saudi military is now directly battling it out with iranian-backed rebels in yemen . while riyadh no doubt exaggerates tehran 's role in the yemen crisis , its fingerprints are nonetheless evident . `` iran provides financial support , weapons , training and intelligence to houthis , '' gerald feierstein , a u.s. state department official and former yemen ambassador , told a congressional hearing last week . `` we believe that iran sees opportunities with the houthis to expand its influence in yemen and threaten saudi and gulf arab"

**Comment by ZhaofengWu** [comment]
Ah, I just noticed you are doing prediction. In that case, yes, we are using Spacy to do tokenization  https://github.com/allenai/allennlp/blob/3ca8035a3a0e8f9f6049e9632267f394dca5abad/allennlp/predictors/sentence_tagger.py#L28

I don't think there's a straightforward way to configure that right now. You could write your own predictor that uses the [`WhitespaceTokenizer`](https://github.com/allenai/allennlp/blob/master/allennlp/data/tokenizers/whitespace_tokenizer.py).

**Comment by matt-gardner** [comment]
If you instantiate the tokenizer yourself, instead of using `allennlp predict`, you can just do `predictor._tokenizer = WhitespaceTokenizer()`.  If you must use `allennlp predict`, @ZhaofengWu's suggestion of writing your own predictor is the best you can do.

**Comment by JJJJane** [comment]
@ZhaofengWu @matt-gardner Got it, thank you for your fast response
