### ISSUE TITLE
Does AllenNLP support different learning rate for different parameters?

### ISSUE THREAD

**Issue by entslscheia** [allenai/allennlp#3844]
Hi. It's a common need for us to have different learning rate for different parameters when we are fine-tuning a model. For example, when fine-tuning BERT, we may mainly want to update the weights of our own model parameters and set a relatively smaller learning rate (e.g., 2e-5 is a common case) for BERT's parameters. Does AllenNLP provide us an interface to do this? It seems to me that we can only set a global learning rate for our optimizer.
Any suggestions would be greatly appreciated!

**Comment by DeNeutoy** [comment]
Yes, we do, see the docs here:
https://allenai.github.io/allennlp-docs/api/training/optimizers/#make_parameter_groups

and an example here:

https://github.com/allenai/allennlp/blob/master/training_config/bert_base_srl.jsonnet#L30

**Comment by entslscheia** [comment]
@DeNeutoy Thanks! That's very helpful.

**Comment by edchengg** [comment]
@entslscheia do you mind provide an example of config? thanks!

**Comment by entslscheia** [comment]
> @entslscheia do you mind provide an example of config? thanks!

Sure.
```@json
"optimizer": {
      "type": "adam",
      "lr": 0.001,
      "parameter_groups": [
        [["source_embedder"], {"lr": 2e-5}]
      ]
    }
```
That's how I configure my optimizer to use a different learning rate for parameters in my 'source_embedder module'. I am using 0.9.0, not sure whether this has been changed or not. Does this help?

**Comment by edchengg** [comment]
> > @entslscheia do you mind provide an example of config? thanks!
> 
> Sure.
> 
> ```
> "optimizer": {
>       "type": "adam",
>       "lr": 0.001,
>       "parameter_groups": [
>         [["source_embedder"], {"lr": 2e-5}]
>       ]
>     }
> ```
> 
> That's how I configure my optimizer to use a different learning rate for parameters in my `source_embedder` module. I am using 0.9.0, not sure whether this has been changed or not. Does this help?

Thanks! 
My case is a little bit complicated. I am trying to set different lr for BERT and a crf layer. But the parameter_groups already take weight decay so some params are overlapped in different groups.

**Comment by entslscheia** [comment]
> > > @entslscheia do you mind provide an example of config? thanks!
> > 
> > 
> > Sure.
> > ```
> > "optimizer": {
> >       "type": "adam",
> >       "lr": 0.001,
> >       "parameter_groups": [
> >         [["source_embedder"], {"lr": 2e-5}]
> >       ]
> >     }
> > ```
> > 
> > 
> > That's how I configure my optimizer to use a different learning rate for parameters in my `source_embedder` module. I am using 0.9.0, not sure whether this has been changed or not. Does this help?
> 
> Thanks!
> My case is a little bit complicated. I am trying to set different lr for BERT and a crf layer. But the parameter_groups already take weight decay so some params are overlapped in different groups.

I don't quite get it.
Hows the params overlapped in different groups? You group the params based on their definition in your model. For example, I define `source_embedder` in my model as
```
{
    "model":{
      ...
     "source_embedder": {
      "allow_unmatched_keys": true,
        "bert": {
          "type": "my_pretrained_transformer",
          "model_name": "bert-base-uncased"
      }
    }
    ...
  }
}
```
So to control the lr for BERT, I use group name `source_embedder`. Do you have a concrete example to show how things get overlapped?

**Comment by edchengg** [comment]
Sure, here is a config for BERT copied from allennlp(0.9) srl bert example.

```
"optimizer": {
            "type": "bert_adam",
            "lr": 5e-5,
            "max_grad_norm": 1,
            "parameter_groups": [
                [
                    [
                        "bias",
                        "LayerNorm.bias",
                        "LayerNorm.weight",
                        "layer_norm.weight"
                    ],
                    {
                        "weight_decay": 0
                    }
                ]
            ],
            "t_total": -1,
            "weight_decay": 0.01
        },
```

If I set learning rate for BERT at 5e-5 and other layers at 5e-3.
`"optimizer": {
            "type": "bert_adam",
            "lr": 5e-3,
            "max_grad_norm": 1,
            "parameter_groups": [
                [
                    [
                        "bias",
                        "LayerNorm.bias",
                        "LayerNorm.weight",
                        "layer_norm.weight"
                    ],
                    {
                        "weight_decay": 0
                    }
                ],
                [["bert_model"],{"lr": 5e-5}]
            ],
            "t_total": -1,
            "weight_decay": 0.01
        },`

I get this error: 
File "/allennlp/training/optimizers.py", line 88, in from_params
    raise ValueError("{} was specified in two separate parameter groups".format(name))
ValueError: bert_model.embeddings.LayerNorm.weight was specified in two separate parameter groups

It will work if I remove 
```
[
                    [
                        "bias",
                        "LayerNorm.bias",
                        "LayerNorm.weight",
                        "layer_norm.weight"
                    ],
                    {
                        "weight_decay": 0
                    }
                ],
```
but would weight decay = 0 affect BERT fine-tuning a lot? If not, I will simply go for that.
