### ISSUE TITLE
Comment for num_layers in stacked_self_attention

### ISSUE THREAD

**Issue by nihalnayak** [allenai/allennlp#3852]
Hi,
I was looking through the `stacked_self_attention` to implement a transformer architecture and observed that the stacked self-attention is slightly different from the Vaswani et al Transformer. The difference is that the feedforward layer is added before the self-attention. 

If that is the difference, I thought the docstring for `num_layers` was slightly misleading. Shouldn't it be `feedforward -> self attention` instead of `self attention -> feedforward`. 

```    
num_layers : `int`, required.
        The number of stacked self-attention -> feedforward -> layer normalization blocks.
```

Let me know if I've misunderstood the API. Thanks!

**Comment by DeNeutoy** [comment]
Hi, you are correct, I followed a slightly different paper when implementing this - however, we are going to remove this module entirely, so then the problem will go away, see #2270
