### ISSUE TITLE
Support metric returning dictionary during training

### ISSUE THREAD

**Issue by viking-sudo-rm** [allenai/allennlp#3854]
**Describe the bug**
Looking at example metrics (e.g. [evalb_bracketing_scorer](https://github.com/allenai/allennlp/blob/master/allennlp/training/metrics/evalb_bracketing_scorer.py)), it appears that the API supports metrics returning a dictionary of multiple values. This would be useful for metrics that are related/share a lot of computation.

```python
        if reset:
            self.reset()
        return {
            "evalb_recall": recall,
            "evalb_precision": precision,
            "evalb_f1_measure": f1_measure,
        }
```

So, I'm trying to copy this pattern in my own code for a metric I'm tracking during training:

```python
    @overrides
    def get_metric(self, reset: bool = False):
        result = {
            "magnitude_step": self.magnitude_metric,
            "direction_step": self.direction_metric,
        }
        if reset:
            self.reset()
        return result
```

However, this results in the following error during training:

```
  File "/home/willm/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/training/trainer.py", line 612, in train
    train_metrics = self._train_epoch(epoch)
  File "/home/willm/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/training/trainer.py", line 441, in _train_epoch
    description = training_util.description_from_metrics(metrics)
  File "/home/willm/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/training/util.py", line 445, in description_from_metrics
    for name, value in metrics.items()
  File "/home/willm/anaconda3/envs/allennlp/lib/python3.6/site-packages/allennlp/training/util.py", line 446, in <listcomp>
    if not name.startswith("_")
TypeError: must be real number, not dict
```
The error is caused by the fact that the following function assumes metric values are floats.

```python
def description_from_metrics(metrics: Dict[str, float]) -> str:
    if not HasBeenWarned.tqdm_ignores_underscores and any(
        metric_name.startswith("_") for metric_name in metrics
    ):
        logger.warning(
            'Metrics with names beginning with "_" will ' "not be logged to the tqdm progress bar."
        )
        HasBeenWarned.tqdm_ignores_underscores = True
    return (
        ", ".join(
            [
                "%s: %.4f" % (name, value)
                for name, value in metrics.items()
                if not name.startswith("_")
            ]
        )
        + " ||"
    )
```

**To Reproduce**
Steps to reproduce the behavior
1. Create a metric that returns a dictionary
2. Add metric to the trainer
3. Train model

**Expected behavior**
I expect the submetrics to be flattened hierarchically, i.e. a metric `"m"` returning `{"a", "b"}` would appear as `m/a=0, m/b=0` in training and on tensorboard. Consistent with the current API, submetrics starting with _ can be ignored from logging.

**System (please complete the following information):**
 - OS: Linux
 - Python version: 3.69
 - AllenNLP version: master
 - PyTorch version: 1.3.1

**Additional context**
One current work around would be to prefix _ to all dict metrics to hide them from logging (they should still appear in tensorboard). But description in "expected behavior" would be more ideal, IMO.

**Comment by DeNeutoy** [comment]
@viking-sudo-rm - I don't think we'll change this, because we can't support arbitrary return types from the model metrics. Instead, can't you just unpack the dictionaries returned from your `Metric` in `Model.get_metrics` ?

e.g 

```
    @overrides
    def get_metric(self, reset: bool = False):
        result = {
            **self.magnitude_metric,
            **self.direction_metric,
        }
        if reset:
            self.reset()
        return result
```


Note also that the API of Metrics is not fixed. Some return dictionaries, some counts, some floats etc.

**Comment by viking-sudo-rm** [comment]
Oops, I see now my original post was unclear. `self.magnitude_metric` and `self.direction_metric` are floats, not dictionaries or `Metric`s. So the current training logic is failing when I return a _flat_ dictionary, not a nested one. 

Your point about not supporting arbitrarily nested metrics makes sense, but what about the case where the return value is just `{"a": 0, "b": 1}.` It seems to me that the API should support this, but maybe I'm wrong?

**Comment by viking-sudo-rm** [comment]
Best workaround is probably just to flatten the nested metrics in `Model.get_metrics` as @DeNeutoy  suggests.
