### ISSUE TITLE
bert-base-srl predictor broken in master

### ISSUE THREAD

**Issue by orestisfl** [allenai/allennlp#3871]
**Describe the bug**
I tried to run the demo for Semantic Role Labeling, as it appears on the website: https://demo.allennlp.org/semantic-role-labeling/

**To Reproduce**
Install from master, run:
```bash
echo '{"sentence": "Did Uriah honestly think he could beat the game in under three hours?"}' | \
  allennlp predict https://s3-us-west-2.amazonaws.com/allennlp/models/bert-base-srl-2019.06.17.tar.gz -
```
Notice that all output tags are "O".

**Expected behavior**
Similar output as in the demo

**System (please complete the following information):**
 - OS: Linux
 - Python version: 3.6.9
 - AllenNLP version: master

**Attached**: two colab notebooks that demonstrate the problem: [srl-issue.zip](https://github.com/allenai/allennlp/files/4266505/srl-issue.zip)

**Comment by ZhaofengWu** [comment]
We expect these models to not work as we are making many breaking changes. We'll investigate this once we finish these breaking changes. Related to #3783.

You could also try https://s3-us-west-2.amazonaws.com/allennlp/models/bert-base-srl-2020.02.10.tar.gz
