### ISSUE TITLE
Remove PYTHONHASHSEED checks

### ISSUE THREAD

**Issue by matt-gardner** [allenai/allennlp#388]
The original point of the `PYTHONHASHSEED` checks was to ensure repeatability of results (and it worked before we switched to pytorch).  Pytorch is inherently non-deterministic, though, because of CUDNN (see #387), so it doesn't seem like requiring `PYTHONHASHSEED` to have a fixed value does us any good.  It's just another hoop to jump through before using the library, and it should be removed.

**Comment by schmmd** [comment]
This is easy to do, and I really don't like setting `PYTHONHASHSEED`, but my question is--does this change lose us anything or add non-determinism anywhere we presently have determinism?

**Comment by schmmd** [comment]
Ah, it's so annoying I hardly care.  I'm going to likely remove this today.
