### ISSUE TITLE
Support fast embeddings loading

### ISSUE THREAD

**Issue by bratao** [allenai/allennlp#3884]
**Is your feature request related to a problem? Please describe.**
I´m frustrated when I have to load a model, and it takes a long time to load a per-trained model file to predict.

**Describe the solution you'd like**

Some solutions such as: 
https://github.com/ThoughtRiver/lmdb-embeddings

Convert the embedding to a LMDB database, and promise to : "a traditional approach glove-840B takes around 2 minutes to load and 4GB in memory. Managed with LMDB, glove-840B can be accessed immediately and takes only a couple MB in memory, for a negligible impact on runtime (around 1% slower)."

Would allennlp accept a PR with a dependency with lmdb-embeddings?

**Comment by matt-gardner** [comment]
Do you know for sure what the cause of the slowness is?  Would this actually fix the problem?  And what exactly would have to change to use this?  It's hard to know whether we'd accept a contribution here without more detail.  Would this just solve things for glove, or would it also work for pre-trained LMs?  If it's just for glove, it's probably not worth the complexity.

**Comment by DeNeutoy** [comment]
We probably shouldn't do this, and you could just have this as a separate python package which provides an integration with allennlp. Then people could choose whether or not to use it. For example if you are using pretrained language models now, this is essentially not a problem.

**Comment by bratao** [comment]
Yeah, I still use glove. So I will use the lmdb-embeddings internally for now!
