### ISSUE TITLE
TypeError: forward() missing 3 required positional arguments: 'source_token_ids', 'source_to_target', and 'metadata'

### ISSUE THREAD

**Issue by Williamyzd** [allenai/allennlp#3904]
I am doing my summary task for my paper. For not  familiar with AllenNLP, I get this trouble when I use CopynetSeq2seq. My data was news article with summarization. Just like this:
{'summarization':'知情人透露章子怡怀孕后，父母很高兴。章母已开始悉心照料。据悉，预产期大概是12月底  ','article':'四海网讯，近日，有媒体报道称：章子怡真怀孕了!报道还援引知情人士消息称，“章子怡怀孕大概四五个月，预产期是年底前后，现在已经不接工作了...'
}
Before inputing the data, I split them with pkuseg, save data as csv. Also I load prereained word embeding with Word2vec(dim=300). I just write a demo and run those code in a python file. Hoping some one to help me , I has little time left.
All my code is below:

import itertools
import config
import torch
import torch.optim as optim
from allennlp.data.dataset_readers.seq2seq import Instance,TextField
from allennlp.data.dataset_readers import CopyNetDatasetReader
from allennlp.data.dataset_readers.dataset_reader import AllennlpDataset

from  allennlp.data.dataloader import DataLoader
from allennlp.data.token_indexers import SingleIdTokenIndexer
from allennlp.data.tokenizers import Token
from allennlp.data.tokenizers.whitespace_tokenizer  import WhitespaceTokenizer

from allennlp.data.vocabulary import Vocabulary,_read_pretrained_tokens
from allennlp.nn.activations import Activation
from allennlp.models.encoder_decoders import SimpleSeq2Seq,CopyNetSeq2Seq
from allennlp.modules.attention import LinearAttention, BilinearAttention, DotProductAttention
from allennlp.modules.seq2seq_encoders import LstmSeq2SeqEncoder, StackedSelfAttentionEncoder,intra_sentence_attention
from allennlp.modules.text_field_embedders import BasicTextFieldEmbedder
from allennlp.modules.token_embedders import Embedding
from allennlp.predictors import SimpleSeq2SeqPredictor, Seq2SeqPredictor
from allennlp.training.trainer import Trainer
from allennlp.common.file_utils import cached_path
import utils
import overrides
import tqdm
import json
from typing import List,Dict
import SumDataSet
import  pandas as pd
EN_EMBEDDING_DIM = 300
ZH_EMBEDDING_DIM = 300
HIDDEN_DIM = 256
CUDA_DEVICE = 0 if config.isOnline else -1

@CopyNetDatasetReader.register('data_reader')
class NLPCCDatasetReader(CopyNetDatasetReader):
    def __init__(self,**kwargs):
        super().__init__(**kwargs);

    @staticmethod
    def _tokens_to_ids(tokens: List[Token]) -> List[int]:
        ids: Dict[str, int] = {}
        out: List[int] = []
        for token in tokens:
            out.append(ids.setdefault(token.text.lower(), len(ids)))
        return out

    def _read(self, file_path):
        s = pd.read_csv(cached_path(file_path));
        instances = s.apply(self.data_apply,axis=1)
        return  instances;

    def data_apply(self,line):
        # print(line)
        src = line['article']
        tgt = line['summarization']
        return self.text_to_instance(src, tgt)

    def text_to_instance(self, src: str, tgt: str) -> Instance:
        tokenized_src = self._source_tokenizer.tokenize(src)
        tokenized_tgt = self._target_tokenizer.tokenize(tgt)
        src_field = TextField(tokenized_src, self._source_token_indexers)
        tgt_field = TextField(tokenized_tgt, self._target_token_indexers)
        fields = {'source_tokens': src_field,'target_tokens': tgt_field}
        # fields["labels"] = tgt_field;
        return Instance(fields)
def main():
    reader = NLPCCDatasetReader(
        target_namespace='tokens',
        source_tokenizer=WhitespaceTokenizer(),
        target_tokenizer=WhitespaceTokenizer(),
        source_token_indexers={'tokens': SingleIdTokenIndexer()})

    train_dataset = reader.read(config.spilt_train_txt)

    validation_dataset = reader.read(config.spilt_dev_txt);
    # print(train_dataset);
    #
    # _read_pretrained_tokens(config.word2vec_text)
    vocab = Vocabulary.from_instances(train_dataset +validation_dataset);
    # train_dataset.index_with(vocab)

    # vocab._extend(pretrained_files=config.word2vec_text)

    # vocab = Vocabulary.from_instances(train_dataset + validation_dataset,
    #                                   min_count={'tokens': 3, 'target_tokens': 3})

    en_embedding = Embedding(num_embeddings=vocab.get_vocab_size('tokens'),
                             embedding_dim=EN_EMBEDDING_DIM,pretrained_file=config.word2vec_text,vocab=vocab)
    encoder = LstmSeq2SeqEncoder(config.ENC_EMB_DIM,config.ENC_HID_DIM,bidirectional=True,stateful=True);

        # PytorchSeq2SeqWrapper(
        # torch.nn.LSTM(EN_EMBEDDING_DIM, HIDDEN_DIM, batch_first=True,bidirectional=True,dropout=0.3))
    # encoder = StackedSelfAttentionEncoder(input_dim=EN_EMBEDDING_DIM, hidden_dim=HIDDEN_DIM, projection_dim=128, feedforward_hidden_dim=128, num_layers=1, num_attention_heads=8)
    #encoer =
    source_embedder = BasicTextFieldEmbedder({"tokens": en_embedding})

    # attention = LinearAttention(HIDDEN_DIM, HIDDEN_DIM, activation=Activation.by_name('tanh')())
    # attention = BilinearAttention(HIDDEN_DIM, HIDDEN_DIM)
    attention = DotProductAttention()

    max_decoding_steps = 20  # TODO: make this variable
    model = CopyNetSeq2Seq(vocab,source_embedder,
                           encoder,
                           attention,
                           beam_size=4,
                           max_decoding_steps=max_decoding_steps,
                           target_embedding_dim=ZH_EMBEDDING_DIM,source_namespace='tokens',target_namespace='tokens')
    # model = SimpleSeq2Seq(vocab, source_embedder, encoder, max_decoding_steps,
    #                       target_embedding_dim=ZH_EMBEDDING_DIM,
    #                       target_namespace='target_tokens',
    #                       attention=attention,
    #                       beam_size=8,
    #                       use_bleu=True)
    optimizer = optim.Adam(model.parameters())

    # iterator = BucketIterator(batch_size=32, sorting_keys=[("source_tokens","num_tokens"),("target_tokens","num_tokens")])

    # iterator.index_with(vocab)
    # data_tool = SumDataSet.SumTool()
    train_data_loader = DataLoader(dataset=train_dataset,batch_size=1)
    validation_data_loader = DataLoader(dataset=validation_dataset,batch_size=10)
    train_dataset.index_with(vocab)

    trainer = Trainer(model=model,
                      optimizer=optimizer,
                      data_loader=train_data_loader,
                      validation_data_loader=validation_data_loader,
                      num_epochs=1,
                      cuda_device=CUDA_DEVICE)

    for i in range(10):
        print('Epoch: {}'.format(i))
        trainer.train()

        predictor = Seq2SeqPredictor(model, reader)

        for instance in itertools.islice(validation_dataset, 10):
            print('SOURCE:', instance.fields['source_tokens'].tokens)
            print('GOLD:', instance.fields['target_tokens'].tokens)
            print('PRED:', predictor.predict_instance(instance)['predicted_tokens'])

if __name__ == '__main__':
    # utils.spilt_data();

    main()

**Comment by DeNeutoy** [comment]
Please re-open this issue with correctly formatted, readable code and a full stack trace, demonstrating your error, along with your allennlp and pytorch versions as per the issue template.
