### ISSUE TITLE
CoreferenceResolver training: CUDA out of memory

### ISSUE THREAD

**Issue by Byron309** [allenai/allennlp#3905]
I noticed that when applying the coreference to large document it causes out of memory error. And I check the TensorFlow version of this method, Lee2017's method (https://github.com/kentonl/e2e-coref/blob/e2e/coref_model.py), and find that they process the large document with function truncate_example(). But in the Allennlp, it seems CoreferenceResolver doesn't implement this truncating. Would that be the problem causing out of memory error when training large document?

**Comment by DeNeutoy** [comment]
Hi,

Yes, sorry we don't implement this truncation. It's certainly one problem - you can also play around with [these two parameters](https://github.com/allenai/allennlp/blob/master/training_config/coref.jsonnet#L78-L79) because they overwhelmingly effect memory usage. Note that in allennlp 0.9, changing these will impact model performance - if you are working on master, we have updated the coref model to use a new more effective type of mention pruning, so you can use fewer considered antecedents without a performance hit, see #3848

**Comment by DeNeutoy** [comment]
Oh actually we do have the truncation in master, see #3814

**Comment by schmmd** [comment]
@Byron309 does that pointer answer your question?

**Comment by Byron309** [comment]
Hi, @DeNeutoy , Yeah Thank you! I find the truncation [https://github.com/allenai/allennlp/blob/master/allennlp/data/dataset_readers/coreference_resolution/util.py#L67](#67). While there is one problem tho. It seems this truncation only get the max_sentence counting from the beginning of the document. In Lee's method, however, it randomly picks a starting index and keep "max_sentence" length consecutive sentences. Should Allennlp coref revise a little bit about that?

**Comment by ZhaofengWu** [comment]
@Byron309 There is actually a difference between Lee et al.'s approach and ours. If I understand correctly, in their code that you pointed out, the random truncation happens for each epoch. We, however, do it only once at data loading, so randomization here doesn't make much sense. Additionally, by setting `max_sentences` to be 110 as we are doing, there are actually very few documents that exceed this limit. So it shouldn't make a huge difference.

**Comment by Byron309** [comment]
@ZhaofengWu Thank you for your answer! Yeah, it is true. While I'm thinking what if we have a large document, say [CRAFT dataset](https://github.com/UCDenver-ccp/CRAFT/releases/tag/v3.1.3), which one document is the full article, it doesn't work well... that's my concern. DO you have any ideas to solve that?
