### ISSUE TITLE
How to write the config to use the RoBERTa model?

### ISSUE THREAD

**Issue by oyyw** [allenai/allennlp#3906]
The OS is linux;
The version of allennlp: 0.9.0
the version of pytorch: 1.4.0

I have successfully experimented with Bert model under the allennlp framework; The problem is that I tried to change the model to Roberta, it failed;  I guess maybe something is wrong, I just modify the config file and replace the BertModel into RobertaModel in my codes; The config file is like following:
this is for tokenizer and indexer
![image](https://user-images.githubusercontent.com/20367252/75982166-e98ac780-5f20-11ea-9e3f-1fd1c46fb3e2.png)

this is for model
![image](https://user-images.githubusercontent.com/20367252/75982024-a892b300-5f20-11ea-82a0-b4b9f48eda9a.png)
![image](https://user-images.githubusercontent.com/20367252/75982180-f14a6c00-5f20-11ea-8fab-7f1d186d19b5.png)

Could anyone help me out how to use the Roberta model here properly?Thanks

**Comment by mojesty** [comment]
Usually you have `TextFieldEmbedder` slot in your model and there you specify `TokenEmbedders`. Now "pretrained_transformer" embedder, that relies on huggingface's AutoModel interface, exists, so you only need to pass model name to the embedder in you config file, like [here](https://github.com/allenai/allennlp/blob/master/training_config/snli_roberta.jsonnet#L25)

**Comment by DeNeutoy** [comment]
@oyyw please include a full stack trace as per the issue template, otherwise it's going to be very hard to help you.
