### ISSUE TITLE
The right way to concatenate sentences for BERT in AllenNLP

### ISSUE THREAD

**Issue by entslscheia** [allenai/allennlp#3910]
@ZhaofengWu Hi, in #3857 you suggested never inserting `[SEP]` by myself and use `tokenize_sentence_pairs` for two sentences. But this seems like some new feature you just added to AllenNLP. There is no `tokenize_sentence_pairs` for AllenNLP 0.9.0, which I am currently using. Of course I can try reinstall AllenNLP from the source code to use the new `tokenize_sentence_pairs`, but I am just curious how you handle sentence pairs before? By adding a `[SEP]` manually between two sentences?
Many thanks!

**Comment by DeNeutoy** [comment]
@entslscheia yes, I believe this was just done manually in the dataset reader before, I know that's not a particularly satisfying answer, sorry!
