### ISSUE TITLE
The "edit pencil" in the docs 404's

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp#3914]
The pencil should go to the right file to edit the docstring, but instead if 404's.  We should either fix the link or remove the pencil.

![image](https://user-images.githubusercontent.com/954798/76103485-a19e8b80-5f86-11ea-8885-7287ff3ef3ed.png)

**Comment by schmmd** [comment]
@DeNeutoy do you have an idea of how to fix this?  I remember you mentioning this would work once we merged down some of your initial changes.

**Comment by DeNeutoy** [comment]
Oh, sorry, this slipped through my net for the docs. It's easy to configure here:

https://github.com/allenai/allennlp/blob/master/mkdocs.yml#L21

Generally everything that is configurable about the docs lives in this file.

**Comment by schmmd** [comment]
We also need to change the edit button so it points to `py` files rather than `md` files.

**Comment by DeNeutoy** [comment]
Actually, we should probably remove the button entirely, because it's a relative path within the docs, which we aren't going to be able to make point to our .py files. I'll send a PR.
