### ISSUE TITLE
Publish docs for each version of AllenNLP

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp#3917]
Presently we publish a single set of documentation at docs.allennlp.org.  Presently these docs correspond to the tip of AllenNLP, which is confusing if people are using the 0.9 release.

Ideally we would publish docs per commit and for each release.  For example, we could have:

1.  http://docs.allennlp.org/master
2.  http://docs.allennlp.org/1.0.0
3.  http://docs.allennlp.org/1.0.1

To accomplish docs for master per commit, we might want to speed up the doc creation process.

**Comment by schmmd** [comment]
@DeNeutoy @dirkgr @matt-gardner does the above sound reasonable?

**Comment by dirkgr** [comment]
From a user perspective, that's very reasonable. In fact, I'd love to have a version selector at the top left corner, the way Python docs have.

But it's going to be a bit of work to go from what we have now to doing that.

**Comment by epwalsh** [comment]
On the subject of speeding up the doc creation process: I had the same issue with another project I was working on, so ended up using a Makefile to manage creating the markdown API doc files with `mathy_pydoc` so it's only run on files that have changed. Basically something like this:

```make
# Makefile
SRC = allennlp
SRCS = $(shell find $(SRC) -type f -name '*.py' | grep -v -E 'tests|__init__|version')
DOCS = $(subst .py,.md,$(subst $(SRC)/,docs/api/,$(SRCS)))

docs/api/%.md : $(SRC)/%.py
	mkdir -p $(shell dirname $@)
	python -m mathy_pydoc $(subst .py,++,$(subst /,.,$<)) > $@

.PHONY : build-docs
build-docs : $(DOCS)
```

Of course for this to work in a CI environment we'd have to cache the source code and markdown doc output as well otherwise everything would be rebuilt everytime.

**Comment by schmmd** [comment]
Well, it takes `0.48s` to full generate the docs if we avoid shelling out for each file.  Otherwise it takes minutes.

**Comment by schmmd** [comment]
Ah shoot--nevermind I'm pretty sure those timings have a problem...

**Comment by schmmd** [comment]
I think it's 6s vs 1165s with the following intermediate hack:

```
diff --git a/scripts/build_docs.py b/scripts/build_docs.py
index 05b62d5b..962f10bf 100644
--- a/scripts/build_docs.py
+++ b/scripts/build_docs.py
@@ -1,3 +1,5 @@
+from mathy_pydoc.__main__ import main
+import sys
 from typing import Dict
 import os
 from pathlib import Path
@@ -31,10 +33,11 @@ def render_file(relative_src_path: str, src_file: str, to_file: str, modifier="+
     else:
         namespace = f"allennlp.{relative_src_namespace}.{src_base}{modifier}"
 
-    args = ["mathy_pydoc", namespace]
-    call_result = check_output(args, env=os.environ).decode("utf-8")
+    sys.argv = ["x", namespace]
+    main()
+
     with open(to_file, "w") as f:
-        f.write(call_result)
+        f.write("asdf")
 
     print(f"Built docs for {src_file}: {to_file}")
```

**Comment by schmmd** [comment]
We now have:

http://docs.allennlp.org/0.9.0
http://docs.allennlp.org/master
