### ISSUE TITLE
Import error for latest coref model

### ISSUE THREAD

**Issue by iknoorjobs** [allenai/allennlp#3918]
When I load the previous 2018 model then it works fine but when I try to load the latest 2020 pre-trained model using

`from allennlp.predictors.predictor import  Predictor`
`predictor = Predictor.from_path("https://allennlp.s3.amazonaws.com/models/coref-model-2020.02.10.tar.gz")`

This gives the following error

```
/usr/local/lib/python3.6/dist-packages/torch/nn/modules/rnn.py:50: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.2 and num_layers=1
  "num_layers={}".format(dropout, num_layers))

ValueError                                Traceback (most recent call last)
<ipython-input-2-bb1ffbbb5703> in <module>()
      1 from allennlp.predictors.predictor import Predictor
----> 2 predictor = Predictor.from_path("https://allennlp.s3.amazonaws.com/models/coref-model-2020.02.10.tar.gz")
      3 predictor.predict(
      4   document="The woman reading a newspaper sat on the bench with her dog."
      5 )

9 frames
/usr/local/lib/python3.6/dist-packages/allennlp/nn/initializers.py in <listcomp>(.0)
    364         prevent_regexes = [param[0] for param in params if is_prevent(param[1])]
    365         params = [param for param in params if param[1] if not is_prevent(param[1])]
--> 366         initializers = [(name, Initializer.from_params(init_params)) for name, init_params in params]
    367         return InitializerApplicator(initializers, prevent_regexes)

ValueError: too many values to unpack (expected 2)
```

**Comment by iknoorjobs** [comment]
Please help. Thanks

**Comment by schmmd** [comment]
@iknoorjobs we're making lot of breaking changes presently.

You need to use 0.9.0 if you'd like to use the older models.  If you would like to use the newer models, you need to be using one of the latest versions of AllenNLP.  We're going to release a 1.0 version of AllenNLP soon, which will make this much more straightforward.

**Comment by iknoorjobs** [comment]
Hi,

Thank you. I want to use newer models in python. How to get the latest version of AllenNLP to use the newer models?

Thanks

**Comment by ZhaofengWu** [comment]
If you want to use the most up-to-date model you can use the one referenced in #3848. You'd need to install the latest master to use that model.

**Comment by ZhaofengWu** [comment]
See https://github.com/allenai/allennlp#installing-from-source

**Comment by iknoorjobs** [comment]
Thanks
 I installed the latest master but now it's showing this error while loading

RuntimeError: Error(s) in loading state_dict for CoreferenceResolver:
	Missing key(s) in state_dict: "_mention_feedforward._module._linear_layers.0.weight", "_mention_feedforward._module._linear_layers.0.bias", "_mention_feedforward._module._linear_layers.1.weight", "_mention_feedforward._module._linear_layers.1.bias", "_mention_scorer._module.weight", "_mention_scorer._module.bias". 
	Unexpected key(s) in state_dict: "_mention_pruner._scorer.0._module._linear_layers.0.weight", "_mention_pruner._scorer.0._module._linear_layers.0.bias", "_mention_pruner._scorer.0._module._linear_layers.1.weight", "_mention_pruner._scorer.0._module._linear_layers.1.bias", "_mention_pruner._scorer.1._module.weight", "_mention_pruner._scorer.1._module.bias".

**Comment by ZhaofengWu** [comment]
Which model are you using?

**Comment by iknoorjobs** [comment]
I have tried both of these models.

https://allennlp.s3.amazonaws.com/models/coref-model-2020.02.10.tar.gz

https://storage.googleapis.com/allennlp-public-models/coref-bert-lstm-2020.02.12.tar.gz

**Comment by ZhaofengWu** [comment]
Neither of those are compatible with the current master. Try  https://storage.googleapis.com/allennlp-public-models/coref-spanbert-large-2020.02.27.tar.gz

**Comment by iknoorjobs** [comment]
Thank you sooo much man. I thought it was for spanish (spanbert) XD

**Comment by iknoorjobs** [comment]
And one more thing,

I am trying to get the index of tokens in the string. 

Example:
text = "I want ab, ab and ab."
tokens (by Allennlp) = ["I" , "want" , "ab" , "," , "ab" , "and" , "ab" , "."]

Now, how to get the index of tokens[4] (i.e. ab) in the original string. Is there any parameter I can set to get the start index of token in the original string?

Hope you understand the problem I am trying to ask. Please let me know if I am missing something?

Thanks

**Comment by iknoorjobs** [comment]
Dear @ZhaofengWu 

Please tell, what is the link to the latest NER model compatible with the current master?

Thanks. Your library is awesome. :)

Iknoor

**Comment by iknoorjobs** [comment]
@ZhaofengWu @schmmd 

The coref online demo model works better than the above mentioned model.

Can I use the version of model which is used in the online demo?

Thanks

**Comment by schmmd** [comment]
You can see which models we use on the website at https://github.com/allenai/allennlp-demo/blob/master/models.json.

**Comment by xorxero** [comment]
The demo is using https://storage.googleapis.com/allennlp-public-models/coref-bert-lstm-2020.02.12.tar.gz

but it doesn't work locally for me.

**Comment by schmmd** [comment]
The demo is using 17c2ff1ce2cb5e84ab9a0f524e6c01362c242cae (see
https://github.com/allenai/allennlp-demo/blob/master/Dockerfile#L3). Sorry,
this is a bit of a mess but we'll release 1.0 soon.

**Comment by ZhaofengWu** [comment]
Also, the above mentioned model should _on average_ work significantly better than what is on the demo right now.

**Comment by iknoorjobs** [comment]
okay thanks @ZhaofengWu @schmmd @xorxero
