### ISSUE TITLE
The right way to use BERT in AllenNLP 0.9.0

### ISSUE THREAD

**Issue by entslscheia** [allenai/allennlp#3923]
#3910 and #3857 are relevant to this question.
I know how to use BERT with the latest version of AllenNLP based on #3857, but for some reason I need to use AllenNLP 0.9.0 for my current project (there have been so many changes since 0.9.0). So I need to manually insert a `[SEP]` between a pair of sentences. My question is: is this the only thing I need to do? Do I also need to manually handle the segment ids for 2 sentences? Or is this automatically done by AllenNLP ? If it is automatically handled, then what if I insert multiple `[SEP]`? Will AllenNLP only rely on the first `[SEP]` to assign segment ids since BERT is only pertained with 2 different segment ids?

Any suggestions would be greatly appreciated! I am really confused about this.

**Comment by kernelmachine** [comment]
@ZhaofengWu assigning you!

**Comment by ZhaofengWu** [comment]
See [this function](https://github.com/allenai/allennlp/blob/052353ed62e3a54fd7b39a660e65fc5dd2f91c7d/allennlp/data/token_indexers/wordpiece_indexer.py#L370) that is called [here](https://github.com/allenai/allennlp/blob/052353ed62e3a54fd7b39a660e65fc5dd2f91c7d/allennlp/data/token_indexers/wordpiece_indexer.py#L162) that handles type ID. I increments the type ID whenever a separator is seen, so it should do what you expect for multiple sequences.

**Comment by entslscheia** [comment]
@ZhaofengWu Many thanks!

**Comment by rzepinskip** [comment]
@entslscheia Can you share your 0.9/1.0 implementation? My own attempts are currently halted by CUDA errors.

**Comment by entslscheia** [comment]
@rzepinskip What kind of CUDA errors you have? 
You simply need to guarantee a consistent config of tokenizer/indexer/embedder. For example, the following is what I use:
```JSON
"source_token_indexers":{
      "bert": {
        "type": "pretrained_transformer",
        "model_name": "bert-base-uncased",
        "do_lowercase": true,
        "namespace": "bert"
      }
    }

...

"source_tokenizer": {
      "type": "pretrained_transformer",
      "model_name": "bert-base-uncased",
      "do_lowercase": true
  }

...

"source_embedder": {
   "bert": {
           "type": "pretrained_transformer",
           "model_name": "bert-base-uncased"
     }
}
```
