### ISSUE TITLE
ELMoTokenCharactersIndexer get_empty_token_list() NotImplementedError

### ISSUE THREAD

**Issue by apmoore1** [allenai/allennlp#3925]
**Describe the bug**
The bug comes from the [`ELMoTokenCharactersIndexer`](https://github.com/allenai/allennlp/blob/master/allennlp/data/token_indexers/elmo_indexer.py) which has not implemented the [`get_empty_token_list` function](https://github.com/allenai/allennlp/blob/master/allennlp/data/token_indexers/token_indexer.py#L67). If this was implemented then the following error will not occur. This edge case I believe has not been found as it is rare for a text field to not contain tokens but in my case for Target Dependent Sentiment analysis this can occur as you have a text that can contain any number of targets and you want to predict the sentiment for a given target. Therefore when the texts are batched for padding reasons some targets can be empty of text and thus this error occur when using the `ELMoTokenCharactersIndexer`.

Full stack trace:
``` bash
Traceback (most recent call last):
  File "elmo_empty_token_list.py", line 22, in <module>
    batch_tensor = a_batch.as_tensor_dict()
  File "/home/andrew/Desktop/allennlp/allennlp/data/batch.py", line 139, in as_tensor_dict
    for field, tensors in instance.as_tensor_dict(lengths_to_use).items():
  File "/home/andrew/Desktop/allennlp/allennlp/data/instance.py", line 99, in as_tensor_dict
    tensors[field_name] = field.as_tensor(padding_lengths[field_name])
  File "/home/andrew/Desktop/allennlp/allennlp/data/fields/list_field.py", line 87, in as_tensor
    self.field_list, padding_lengths["num_fields"], self.field_list[0].empty_field
  File "/home/andrew/Desktop/allennlp/allennlp/common/util.py", line 184, in pad_sequence_to_length
    padded_sequence.append(default_value())
  File "/home/andrew/Desktop/allennlp/allennlp/data/fields/text_field.py", line 112, in empty_field
    text_field._indexed_tokens[indexer_name] = indexer.get_empty_token_list()
  File "/home/andrew/Desktop/allennlp/allennlp/data/token_indexers/token_indexer.py", line 72, in get_empty_token_list
    raise NotImplementedError
NotImplementedError
```

**To Reproduce**
Run the following:
``` python
indexer = ELMoTokenCharactersIndexer()
indexer = {'elmo': indexer}

tokens_1 = TextField([Token('Apple')], indexer)
targets_1 = ListField([TextField([Token('Apple')], indexer)])
tokens_2 = TextField([Token('Screen'), Token('device')], indexer)
targets_2 = ListField([TextField([Token('Screen')], indexer),
                        TextField([Token('Device')], indexer)])
instance_1 = Instance({'tokens': tokens_1, 'targets': targets_1})
instance_2 = Instance({'tokens': tokens_2, 'targets': targets_2})
a_batch = Batch([instance_1, instance_2])
a_batch.index_instances(Vocabulary())
batch_tensor = a_batch.as_tensor_dict()
```

**Expected behavior**
This `NotImplementedError` should not be raised.

**System (please complete the following information):**
 - OS: Ubuntu 16.0.4
 - Python version: 3.6.7
 - AllenNLP version: "I installed from master"
 - PyTorch version: 1.4.0

**Additional context**
I already have a fix and test case for this and happy to create a PR to fix this error.

**Comment by kernelmachine** [comment]
I think contributions are welcome to fix this error!
