### ISSUE TITLE
Evaluate model on test set 

### ISSUE THREAD

**Issue by kaushikepi** [allenai/allennlp#3926]
Where should we add `evaluate_on_test` flag in the config file?

**Comment by kaushikepi** [comment]
what should be in archive_file and can anyone give me an example to of allennlp evaluate command

**Comment by kernelmachine** [comment]
The `evaluate_on_test` flag should be added to the top level of the config, e.g. https://github.com/allenai/vampire/blob/master/training_config/classifier.jsonnet#L274

The archive file contains your best model weights (weights.th), a config file, and your vocabulary file(s). The command is outlined at the top of this file: https://github.com/allenai/allennlp/blob/master/allennlp/commands/evaluate.py
