### ISSUE TITLE
Nightly builds are still running on forks

### ISSUE THREAD

**Issue by danielkingai2** [allenai/allennlp#3931]
**Describe the bug**
Nightly builds are still running on forks (and failing on allennlp master). Seems the syntax for only running them on allennlp master isn't quite right.

**Additional context**
See #3895 for the previous issue about this.

**Comment by kernelmachine** [comment]
Thanks for raising this. @schmmd , can you take a look?

**Comment by schmmd** [comment]
@danielkingai2 can you give me a link to the fork and the build?  I'm completely unfamiliar with this as @DeNeutoy set it up.

**Comment by danielkingai2** [comment]
Ah, yeah, I'll try to give as much context as I can. Here is my fork of allennlp (https://github.com/danielkingai2/allennlp). The build system is through github actions, so on the allennlp repo, there is an "actions" tab (https://github.com/allenai/allennlp/actions), and Mark set up a nightly release workflow (https://github.com/allenai/allennlp/actions?query=workflow%3A%22Nightly+Release%22). The workflow is setup via a yaml file that lives here (https://github.com/allenai/allennlp/blob/master/.github/workflows/nightly.yml). Because the build is setup through a yaml file, it automatically tries to run on forks as well, although it would fail because it doesn't have the secrets that it needs. Before Mark left he tried to add a condition to the build so that it only runs on the main repo (https://github.com/allenai/allennlp/blob/5ba77d44d9c87f1a12ec4ea63aca1d965399090f/.github/workflows/nightly.yml#L11), but it seems that something is wrong with the syntax, because build are failing on both allennlp master (https://github.com/allenai/allennlp/runs/488435146?check_suite_focus=true) and my fork. Builds also seem to have been paused or something on allennlp master although I'm not sure if that is something automatic or someone did that (https://github.com/allenai/allennlp/actions). I'm not sure what the right syntax is to get the build to only run on allennlp master.

**Comment by danielkingai2** [comment]
Ok i think instead of `if: github.actor == 'repo-owner'` you want `if github.repository == 'allenai/allennlp'`. I tested it to the extent possible on my fork. PR incoming

**Comment by danielkingai2** [comment]
The reason the build stopped failing and started getting skipped was Mark's last change (which I did not have merged into my fork) got it to not crash but it was checking if the "actor" was equal to "repo-owner".

**Comment by schmmd** [comment]
@danielkingai2 you are really going above and beyond here ;-) thanks for your help... sorry I've been jumping between meetings and only looking at this in bits and pieces.

**Comment by danielkingai2** [comment]
No problem, PR is here https://github.com/allenai/allennlp/pull/3935
