### ISSUE TITLE
loss and metric calculation for joint predicate and role prediction on SRL

### ISSUE THREAD

**Issue by cemilcengiz** [allenai/allennlp#3937]
Hi, I am trying to modify the SrlBert model to jointly predict the predicates and the corresponding semantic roles as opposed to using the gold predicate information. Specifically, I am planning to first decide which tokens are the predicates and store their embeddings. Then, I will pass the predicate embeddings and regular token embeddings through a bilinear layer to assign the role for each token w.r.t a predicate. However, I have problems on BERT's wordpiece tokenizer and the loss calculation. I will try to solve the mapping problem between the wordpieces and words for the predicates myself first although I will greatly appreciate any tip or guides. My main problem is the metric and loss calculation for joint predicate prediction and role tagging problem, especially in the case of multiple predicates in a sentence.  Is there a built-in module for that? If not, I am open for suggestions.
Btw, I am using version 0.9.0 of AllenNLP.
Thank you.

Edit: My training instance fields include of a list of SequenceLabelField. Please see the relevant code (excluding metadata fields etc) snippet from my dataset reader:

```
        tag_fields = []
        for (_, tags) in srl_frames:
            if self.bert_tokenizer is not None:
                new_tags = _convert_tags_to_wordpiece_tags(tags, offsets)
                tag_fields.append(SequenceLabelField(new_tags, text_field))
            else:
                tag_fields.append(SequenceLabelField(tags, text_field))

        fields["tags"] = ListField(tag_fields)
```

**Comment by schmmd** [comment]
@cemilcengiz can you be more specific about what you need help with?  We'd be able to follow up easier if you had a clear question.

We probably don't have anything built in, but we're also not clear what you're looking for.

**Comment by cemilcengiz** [comment]
Let's assume I have a sentence something like this: "A B C D E F G .", where each letter represents a token. Let's also assume the gold predicates are B and C. Each token have a semantic role with respect to each, so they have two roles. Now, if my model decides that C, D and E are predicates, I will have three semantic roles for each token. In this case, how can I calculate a score for my prediction accuracy. More crucially, how can I define the loss so that I can back-propagate it? I have one overlapping predicate, two excess predicates and missed one gold predicate. How can I match the predicted role sequences to the gold role sequences, given that I missed a predicate and produced excess sequences for the incorrectly predicted predicates?

**Comment by matt-gardner** [comment]
So, what you're asking here is a research question, not a question about the library.  discourse.allennlp.org would be a better place to ask this kind of question in the future.

What I would do to start with is just have a loss on predicate prediction, then a loss on all predicted roles for the gold predicates (i.e., ignore the role predictions on excess predicates).  There are probably smarter things that you could do if you're clever about it, but that's the easiest starting place.
