### ISSUE TITLE
Coref Configuration Error while loading

### ISSUE THREAD

**Issue by iknoorjobs** [allenai/allennlp#3951]
A few days back it was working fine but now when I run the following commands

from allennlp.predictors.predictor import Predictor
predictor = Predictor.from_path("https://storage.googleapis.com/allennlp-public-models/coref-spanbert-large-2020.02.27.tar.gz")

Error:

`ConfigurationError                        Traceback (most recent call last)
<ipython-input-23-f3741b67adaa> in <module>()
----> 1 predictor = Predictor.from_path("https://storage.googleapis.com/allennlp-public-models/coref-spanbert-large-2020.02.27.tar.gz")
4 frames
/content/allennlp/allennlp/common/registrable.py in resolve_class_name(cls, name)
    183             # is not a qualified class name
    184             raise ConfigurationError(
--> 185                 f"{name} is not a registered name for {cls.__name__}. "
    186                 "You probably need to use the --include-package flag "
    187                 "to load your custom code. Alternatively, you can specify your choices "`

`ConfigurationError: coref is not a registered name for Model. You probably need to use the --include-package flag to load your custom code. Alternatively, you can specify your choices using fully-qualified paths, e.g. {"model": "my_module.models.MyModel"} in which case they will be automatically imported correctly.`

**Comment by matt-gardner** [comment]
We are currently moving a bunch of things around.  If you're on master, you should expect breaking changes for the next while, until we have a stable release candidate (hopefully that will happen within the next couple of weeks).

The models moved into a separate repository, which is why that line of code is failing: https://github.com/allenai/allennlp-models.

**Comment by iknoorjobs** [comment]
Hi @matt-gardner 

I tried to use the previous version of master (using git checkout) but still, it's not working.
Please tell, how can I fix this? I need to run the code urgently.

Thanks for help.

**Comment by matt-gardner** [comment]
Clone this repository: https://github.com/allenai/allennlp-models, add it to your python path.  Then before you create the `Predictor` object run `import allennlp_models.coref`.

**Comment by iknoorjobs** [comment]
@matt-gardner 

Thanks a lot man. I owe you one.
Awesome library. :)

**Comment by iknoorjobs** [comment]
@matt-gardner Hi, is it possible that this method will fail in future (when new version is released)?

**Comment by matt-gardner** [comment]
We are sticking with the allennlp-models repo.  We are very close to a release candidate for version 1.0, and there are basically no more breaking changes left in the pipeline, except for moving models over to the new repo (you can see the remaining things we're planning here: https://github.com/allenai/allennlp/milestone/10).  So, if you're on master, things are getting very close to a stable point where you shouldn't expect anything to break again.

**Comment by ParvaShah** [comment]
Is predictor = Predictor.from_path("https://storage.googleapis.com/allennlp-public-models/coref-spanbert-large-2020.02.27.tar.gz") compatible with version 1.0.0rc1 ?
