### ISSUE TITLE
PR "Change all masks to type torch.bool" has broken crf_tagger

### ISSUE THREAD

**Issue by ArneBinder** [allenai/allennlp#3953]
**Describe the bug**
[This PR](https://github.com/allenai/allennlp/pull/3890) breaks the crf_tagger if used in combination with any TokenIndexer that returns a mask (all of them return still int tensors).

**To Reproduce**
Use a model like
```
  "model": {
    "type": "crf_tagger",
    "include_start_end_transitions": false,
    "text_field_embedder": {
        "token_embedders": {
            "transformer": {
                "type": "pretrained_transformer_mismatched",
                "model_name": "bert-base-cased",
            }
          }
    },
    "encoder": {
        "type": "pass_through",
        "input_dim": 768,
    },
  }
```
and get a nice loss of sth like:
```
accuracy: 0.0642, accuracy3: 0.8739, loss: 19522285474762.3438 ||:  13%|█▎        | 228/1756 [00:22<02:23, 10.67it/s]
```

**Expected behavior**
a loss like:
```
accuracy: 0.7953, accuracy3: 0.8876, loss: 125.3830 ||:  12%|█▏        | 218/1756 [00:21<02:28, 10.36it/s]
```
This bug can be fixed when adding `.to(torch.bool)` to the `mask` in [this](https://github.com/allenai/allennlp/blob/a078c91eaba4b78c21a65bec9fa98275de31e5fc/allennlp/models/crf_tagger.py#L215) and [this](https://github.com/allenai/allennlp/blob/a078c91eaba4b78c21a65bec9fa98275de31e5fc/allennlp/models/crf_tagger.py#L227) line resulting in the output above. 

**System (please complete the following information):**
 - OS: Ubuntu 18
 - Python version: 3.7.6 (default, Jan  8 2020, 19:59:22) 
 - AllenNLP version: current master ([a078c91eaba4b78c21a65bec9fa98275de31e5fc](https://github.com/allenai/allennlp/commit/a078c91eaba4b78c21a65bec9fa98275de31e5fc))
 - PyTorch version: 1.4

**Comment by matt-gardner** [comment]
Thanks @ArneBinder for finding this!  @ZhaofengWu, can you take a look at this issue?

**Comment by ZhaofengWu** [comment]
Thanks for spotting this! I indeed overlooked those occurrences. I will fix them soon.
