### ISSUE TITLE
Make BiDAF more memory efficient

### ISSUE THREAD

**Issue by matt-gardner** [allenai/allennlp#396]
The main memory bottleneck is our MatrixAttention layer. Using Chris's trilinear attention would be a lot more memory efficient. Once #346 gets merged, we should replace the attention in BiDAF, with a note that if you want to experiment with fancier attention mechanisms, you can switch back to MatrixAttention, but at the cost of significantly increased memory usage.

**Comment by schmmd** [comment]
We're going to replace this with Chris' model, so I'm closing this out.
