### ISSUE TITLE
When using BertPooler, do we have to manually add [CLS], or not?

### ISSUE THREAD

**Issue by izuna385** [allenai/allennlp#3962]
Currently I'm using `BertPooler` and `BertTokenizer.from_pretrained`. `PretrainedBertIndexer` is used for indexing. My question is whether `[CLS]` have to be manually added to tokenized sequence or not, when we want to get `[CLS]` embedding.
Still I'm reading codes, like
https://github.com/allenai/allennlp/blob/95b6d985ffb231d9a2047c039c95660913063b9d/allennlp/modules/token_embedders/pretrained_transformer_embedder.py
https://github.com/allenai/allennlp/blob/02d5ddeef16a767bc77f9845bccc9ad4c47ad239/allennlp/tests/data/token_indexers/pretrained_transformer_indexer_test.py

My understanding is if only one sequence pooling (e.g. sentence) is required, manually adding `[CLS]` is unnecessary. Otherwise, like 2-sentence inference, we have to add like 
> ' token_sent1_1,...,[SEP] token_sent2_1,...token_sent2_n'

and with `PretrainedBertIndexer`, [CLS] and [SEP] is added at the start and end automatically, respectively, so that before sequence is input to BertPooler,

> ' [CLS], token_sent1_1,...,[SEP] token_sent2_1,...token_sent2_n, [SEP]'

If you'd know and write about it, I'd appreciate it.
Thanks.

**Comment by matt-gardner** [comment]
`PretrainedBertIndexer` is the old version of our current [`PretrainedTransformerMismatchedIndexer`](http://docs.allennlp.org/master/api/data/token_indexers/pretrained_transformer_mismatched_indexer/).  That indexer adds special tokens on its own, and removes them in the corresponding `Embedder` (so it isn't suitable for use with a `BertPooler`).

If you want to use a `BertPooler`, my recommendation is to use a `PretrainedTransformerTokenizer` (which will add special tokens), a `PretrainedTransformerIndexer`, and a `PretrainedTransformerEmbedder`.  In your model, after embedding you will have one vector per wordpiece, including special tokens, and the `BertPooler` will do the right thing to give you the `[CLS]` vector.

**Comment by izuna385** [comment]
Thanks for details. I confirmed that PretrainedTransformerTokenizer automatically add [CLS] and [SEP] tokens.
Sorry for one more question, do PretrainedTransformerTokenizer and else support community model, such as scibert or else?
I try with model name 
https://huggingface.co/monologg/scibert_scivocab_uncased
but tokenizer return None.

bert-base-uncased and else seems to work.

**Comment by matt-gardner** [comment]
We just call `AutoTokenizer` and `AutoModel` under the hood, so whatever values work in huggingface's library should also work for our components.  I'm not sure which community models work for tokenizers and models, but huggingface should have a way to figure that out.

I'm closing this issue, as it looks like your question is resolved, but feel free to comment again if you have more related questions.

**Comment by izuna385** [comment]
Thanks for replies. With surveying source codes, I can run biobert with PretrainedTransformerIndexer/Embedder.

Sorry for one more question.
Seems like pretrainedtransformerembedder has no switch option for `emb_requires_grad`
Does this fine-tune parameters for pretraind BERT in default?

**Comment by matt-gardner** [comment]
Yes, parameters are fine-tuned when you use that code.

**Comment by izuna385** [comment]
Great! Thanks for your advices.

**Comment by possible1402** [comment]
If `emb_requires_grad` is deleted, can I use the hidden state of bert as feature? I mean use bert to initialize embedding layer and keep frozen.

**Comment by matt-gardner** [comment]
@possible1402, we haven't implemented this yet, as it is not a very common use case.  It wouldn't be hard to add, though, if anyone wants to submit a PR.
