### ISSUE TITLE
Dropped support for seq2seq models?

### ISSUE THREAD

**Issue by aleSuglia** [allenai/allennlp#3979]
Hello,

I remember that AllenNLP had recently integrated a very nice and clean implementation of [seq2seq models](https://github.com/allenai/allennlp/tree/f3083c8fb9150f07e3ca98bb3ea9368a081df028/allennlp/modules/seq2seq_decoders). However, seems that the code is disappeared from the codebase. Is there any reason for this? 

Thanks,

Alessandro

**Comment by ZhaofengWu** [comment]
We are in the progress of moving our models into a [separate repo](https://github.com/allenai/allennlp-models/).

**Comment by schmmd** [comment]
@aleSuglia sorry for the present confusion, but we will have a release candidate in a couple of weeks that will clean this up significantly!
