### ISSUE TITLE
Bug Report when running Allennlp demo code from the usage tab

### ISSUE THREAD

**Issue by bikegirl** [allenai/allennlp#3986]
**Describe the bug**

Before I was able to simply copy the code from usage tab into a cell on colab notebook and run in colab:
[https://drive.google.com/open?id=10tM6DGgW0zUb3kmCV4qoappc4ZLeUxg9](url)

from allennlp.predictors.predictor import Predictor
from allennlp.predictors import SentenceTaggerPredictor
import torch
predictor = Predictor.from_path("https://s3-us-west-2.amazonaws.com/allennlp/models/biaffine-dependency-parser-ptb-2018.08.23.tar.gz")
predictor.predict(
  sentence="If I bring 10 dollars tomorrow, can you buy me lunch?"
)

**To Reproduce**
Steps to reproduce the behavior
1. Go to My Colab Notebook: [https://drive.google.com/open?id=10tM6DGgW0zUb3kmCV4qoappc4ZLeUxg9](url)
2. Go to Runtime in the top ribbon and select run all
3. See error

**Expected behavior** 
_(This is what I used to get when I used the dependency parsing, semantic role labeling, and coref resolution predictor on allennlp.  Additionally, I had another PhD lab mate test the code as well and she had the same problems)_

{'clusters': [[[3, 3], [6, 6], [12, 12]]],
 'document': ['"',
  'Eeeeeekkk',
  '"',
  'Hermione',
  'squealed',
  'as',
  'she',
  'jumped',
  'up',
  'and',
  'down',
  'in',
  'her',
  'bedroom',
  '.'],
 'predicted_antecedents': [-1, -1, 0, -1, 1, -1],
 'top_spans': [[1, 3], [3, 3], [6, 6], [7, 7], [12, 12], [12, 13]]}

**System (please complete the following information):**
 - OS: Windows and Mac (tested on Both)
 - Python version: 3.6.8
 - AllenNLP version: most up to date installed from colab !pip install allennlp
 - PyTorch version: I used import torch

**Additional context** 
**This is the full stack trace**
```
Did not use initialization regex that was passed: .*bias_ih.*
Did not use initialization regex that was passed: .*weight_ih.*
Did not use initialization regex that was passed: .*weight_hh.*
Did not use initialization regex that was passed: .*bias_hh.*
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-49-091ae4ebc344> in <module>()
      2 from allennlp.predictors import SentenceTaggerPredictor
      3 import torch
----> 4 dependency_parser = Predictor.from_path("https://s3-us-west-2.amazonaws.com/allennlp/models/biaffine-dependency-parser-ptb-2018.08.23.tar.gz")
      5 dependency_parses = dependency_parser.predict(
      6   sentence="Virginia found herself alone with her brother, and then the thought of her sister came to mind. She remembered the camping trip they embarked on a few summers ago."
14 frames
/usr/local/lib/python3.6/dist-packages/allennlp/predictors/predictor.py in from_path(cls, archive_path, predictor_name, cuda_device, dataset_reader_to_load)
    255         """
    256         return Predictor.from_archive(load_archive(archive_path, cuda_device=cuda_device), predictor_name,
--> 257                                       dataset_reader_to_load=dataset_reader_to_load)
    258 
    259     @classmethod
/usr/local/lib/python3.6/dist-packages/allennlp/predictors/predictor.py in from_archive(cls, archive, predictor_name, dataset_reader_to_load)
    286         model.eval()
    287 
--> 288         return Predictor.by_name(predictor_name)(model, dataset_reader)
/usr/local/lib/python3.6/dist-packages/allennlp/predictors/biaffine_dependency_parser.py in __init__(self, model, dataset_reader, language)
     84         super().__init__(model, dataset_reader)
     85         # TODO(Mark) Make the language configurable and based on a model attribute.
---> 86         self._tokenizer = SpacyWordSplitter(language=language, pos_tags=True)
     87 
     88     def predict(self, sentence: str) -> JsonDict:
/usr/local/lib/python3.6/dist-packages/allennlp/data/tokenizers/word_splitter.py in __init__(self, language, pos_tags, parse, ner, keep_spacy_tokens, split_on_spaces)
    171                  keep_spacy_tokens: bool = False,
    172                  split_on_spaces: bool = False) -> None:
--> 173         self.spacy = get_spacy_model(language, pos_tags, parse, ner)
    174         if split_on_spaces:
    175             self.spacy.tokenizer = WhitespaceTokenizer(self.spacy.vocab)
/usr/local/lib/python3.6/dist-packages/allennlp/common/util.py in get_spacy_model(spacy_model_name, pos_tags, parse, ner)
    287             disable.append('ner')
    288         try:
--> 289             spacy_model = spacy.load(spacy_model_name, disable=disable)
    290         except OSError:
    291             logger.warning(f"Spacy models '{spacy_model_name}' not found.  Downloading and installing.")
/usr/local/lib/python3.6/dist-packages/spacy/__init__.py in load(name, **overrides)
     25     if depr_path not in (True, False, None):
     26         deprecation_warning(Warnings.W001.format(path=depr_path))
---> 27     return util.load_model(name, **overrides)
     28 
     29 
/usr/local/lib/python3.6/dist-packages/spacy/util.py in load_model(name, **overrides)
    132             return load_model_from_link(name, **overrides)
    133         if is_package(name):  # installed as package
--> 134             return load_model_from_package(name, **overrides)
    135         if Path(name).exists():  # path to model data directory
    136             return load_model_from_path(Path(name), **overrides)
/usr/local/lib/python3.6/dist-packages/spacy/util.py in load_model_from_package(name, **overrides)
    153     """Load a model from an installed package."""
    154     cls = importlib.import_module(name)
--> 155     return cls.load(**overrides)
    156 
    157 
/usr/local/lib/python3.6/dist-packages/en_core_web_sm/__init__.py in load(**overrides)
     10 
     11 def load(**overrides):
---> 12     return load_model_from_init_py(__file__, **overrides)
/usr/local/lib/python3.6/dist-packages/spacy/util.py in load_model_from_init_py(init_file, **overrides)
    194     if not model_path.exists():
    195         raise IOError(Errors.E052.format(path=path2str(data_path)))
--> 196     return load_model_from_path(data_path, meta, **overrides)
    197 
    198 
/usr/local/lib/python3.6/dist-packages/spacy/util.py in load_model_from_path(model_path, meta, **overrides)
    177             component = nlp.create_pipe(name, config=config)
    178             nlp.add_pipe(component, name=name)
--> 179     return nlp.from_disk(model_path)
    180 
    181 
/usr/local/lib/python3.6/dist-packages/spacy/language.py in from_disk(self, path, exclude, disable)
    834             # Convert to list here in case exclude is (default) tuple
    835             exclude = list(exclude) + ["vocab"]
--> 836         util.from_disk(path, deserializers, exclude)
    837         self._path = path
    838         return self
/usr/local/lib/python3.6/dist-packages/spacy/util.py in from_disk(path, readers, exclude)
    634         # Split to support file names like meta.json
    635         if key.split(".")[0] not in exclude:
--> 636             reader(path / key)
    637     return path
    638 
/usr/local/lib/python3.6/dist-packages/spacy/language.py in <lambda>(p, proc)
    829                 continue
    830             deserializers[name] = lambda p, proc=proc: proc.from_disk(
--> 831                 p, exclude=["vocab"]
    832             )
    833         if not (path / "vocab").exists() and "vocab" not in exclude:
pipes.pyx in spacy.pipeline.pipes.Tagger.from_disk()
/usr/local/lib/python3.6/dist-packages/spacy/util.py in from_disk(path, readers, exclude)
    634         # Split to support file names like meta.json
    635         if key.split(".")[0] not in exclude:
--> 636             reader(path / key)
    637     return path
    638 
pipes.pyx in spacy.pipeline.pipes.Tagger.from_disk.load_tag_map()
morphology.pyx in spacy.morphology.Morphology.__init__()
attrs.pyx in spacy.attrs.intify_attrs()
KeyError: 'PUNCTSIDE_FIN'
```

**Comment by datix-vishu** [comment]
I think the code is a bit old, newer version of AllenNLP doesn't work like that. Install the stable version of AllenNLP i.e v0.9.0 then try the following code:

**Method 1** 
`from allennlp.predictors import Predictor`
`allennlp_model = Predictor.from_path('path to model')`
`data = allennlp_model.json_to_labeled_instances({"sentence" : text })`


**Method 2** 
`from allennlp.predictors import Predictor`
`allennlp_model = Predictor.from_path('path to model')`
`data = allennlp_model.json_to_labeled_instances(text)`


**Method 3**
`from allennlp.predictors import Predictor`
`allennlp_model = Predictor.from_path('path to model')`
`instance = allennlp_model._json_to_instance({"sentence" : text })`
`outputs = allennlp_model.predict(text)`
`new_instances = predictor.predictions_to_labeled_instances(instance, outputs)`

**Comment by bikegirl** [comment]
I use:
`!pip install allennlp `
I get this error:
`ERROR: allennlp 0.9.0 has requirement spacy<2.2,>=2.1.0, but you'll have spacy 2.2.4 which is incompatible.`
It says `>=2.1.0` and so 2.2.4 meets that criteria; however, it says it's incompatible.  Thoughts?

**Comment by bikegirl** [comment]
**for method1 and method2 I get this error:**

Link to colab notebook: [https://colab.research.google.com/drive/10tM6DGgW0zUb3kmCV4qoappc4ZLeUxg9#scrollTo=78AOtnXdYF5C](url)

Code Used:
`## Method 1`
`from allennlp.predictors import Predictor`
`allennlp_model = Predictor.from_path("https://s3-us-west-2.amazonaws.com/allennlp/models/biaffine-dependency-parser-ptb-2018.08.23.tar.gz")`
`data = allennlp_model.json_to_labeled_instances({"sentence" : text })`
`print(data)`

```
Did not use initialization regex that was passed: .*weight_ih.*
Did not use initialization regex that was passed: .*bias_hh.*
Did not use initialization regex that was passed: .*weight_hh.*
Did not use initialization regex that was passed: .*bias_ih.*
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-32-e4a38bd21a3d> in <module>()
      1 from allennlp.predictors import Predictor
      2 allennlp_model = Predictor.from_path("https://s3-us-west-2.amazonaws.com/allennlp/models/biaffine-dependency-parser-ptb-2018.08.23.tar.gz")
----> 3 data = allennlp_model.json_to_labeled_instances({"sentence" : text })
      4 print(data)

1 frames
/usr/local/lib/python3.6/dist-packages/allennlp/predictors/predictor.py in predictions_to_labeled_instances(self, instance, outputs)
    195         """
    196         # pylint: disable=unused-argument,no-self-use
--> 197         raise RuntimeError("implement this method for model interpretations or attacks")
    198 
    199     def _json_to_instance(self, json_dict: JsonDict) -> Instance:

RuntimeError: implement this method for model interpretations or attacks
```

**Comment by matt-gardner** [comment]
`json_to_labeled_instances` does something else, and it's not implemented for dependency parsing.  Seeing this confusion, perhaps we should rename it.  You just want the `predict` function.

**Comment by datix-vishu** [comment]
Hey @bikegirl , I just tried your code like this and out the output. I used the following packages:
**Spacy : 2.1.0**
**allennlp : 0.9.0**

**_Code :_** 
`from allennlp.predictors import Predictor`
`allennlp_model = Predictor.from_path('.../biaffine-dependency-parser-ptb-2018.08.23.tar.gz')`
`allennlp_model.predict("If I bring 10 dollars tomorrow, can you buy me lunch?")`

**_Output_**
`
{'arc_loss': 0.00019421015167608857,
 'tag_loss': 0.0031929698307067156,
 'loss': 0.0033871799241751432,
 'words': ['If',
  'I',
  'bring',
  '10',
  'dollars',
  'tomorrow',
  ',',
  'can',
  'you',
  'buy',
  'me',
  'lunch',
  '?'],
 'pos': ['IN',
  'PRP',
  'VBP',
  'CD',
  'NNS',
  'NN',
  ',',
  'MD',
  'PRP',
  'VB',
  'PRP',
  'NN',
  '.'],
 'predicted_dependencies': ['mark',
  'nsubj',
  'advcl',
  'num',
  'dobj',
  'tmod',
  'punct',
  'aux',
  'nsubj',
  'root',
  'iobj',
  'dobj',
  'punct'],
 'predicted_heads': [3, 3, 10, 5, 3, 3, 10, 10, 10, 0, 10, 10, 10],
 'hierplane_tree': {'text': 'If I bring 10 dollars tomorrow , can you buy me lunch ?',
  'root': {'word': 'buy',
   'nodeType': 'root',
   'attributes': ['VB'],
   'link': 'root',
   'spans': [{'start': 41, 'end': 45}],
   'children': [{'word': 'bring',
     'nodeType': 'advcl',
     'attributes': ['VBP'],
     'link': 'advcl',
     'spans': [{'start': 5, 'end': 11}],
     'children': [{'word': 'If',
       'nodeType': 'mark',
       'attributes': ['IN'],
       'link': 'mark',
       'spans': [{'start': 0, 'end': 3}]},
      {'word': 'I',
       'nodeType': 'nsubj',
       'attributes': ['PRP'],
       'link': 'nsubj',
       'spans': [{'start': 3, 'end': 5}]},
      {'word': 'dollars',
       'nodeType': 'dobj',
       'attributes': ['NNS'],
       'link': 'dobj',
       'spans': [{'start': 14, 'end': 22}],
       'children': [{'word': '10',
         'nodeType': 'num',
         'attributes': ['CD'],
         'link': 'num',
         'spans': [{'start': 11, 'end': 14}]}]},
      {'word': 'tomorrow',
       'nodeType': 'tmod',
       'attributes': ['NN'],
       'link': 'tmod',
       'spans': [{'start': 22, 'end': 31}]}]},
    {'word': ',',
     'nodeType': 'punct',
     'attributes': [','],
     'link': 'punct',
     'spans': [{'start': 31, 'end': 33}]},
    {'word': 'can',
     'nodeType': 'aux',
     'attributes': ['MD'],
     'link': 'aux',
     'spans': [{'start': 33, 'end': 37}]},
    {'word': 'you',
     'nodeType': 'nsubj',
     'attributes': ['PRP'],
     'link': 'nsubj',
     'spans': [{'start': 37, 'end': 41}]},
    {'word': 'me',
     'nodeType': 'iobj',
     'attributes': ['PRP'],
     'link': 'iobj',
     'spans': [{'start': 45, 'end': 48}]},
    {'word': 'lunch',
     'nodeType': 'dobj',
     'attributes': ['NN'],
     'link': 'dobj',
     'spans': [{'start': 48, 'end': 54}]},
    {'word': '?',
     'nodeType': 'punct',
     'attributes': ['.'],
     'link': 'punct',
     'spans': [{'start': 54, 'end': 56}]}]},
  'nodeTypeToStyle': {'root': ['color5', 'strong'],
   'dep': ['color5', 'strong'],
   'nsubj': ['color1'],
   'nsubjpass': ['color1'],
   'csubj': ['color1'],
   'csubjpass': ['color1'],
   'pobj': ['color2'],
   'dobj': ['color2'],
   'iobj': ['color2'],
   'mark': ['color2'],
   'pcomp': ['color2'],
   'xcomp': ['color2'],
   'ccomp': ['color2'],
   'acomp': ['color2'],
   'aux': ['color3'],
   'cop': ['color3'],
   'det': ['color3'],
   'conj': ['color3'],
   'cc': ['color3'],
   'prep': ['color3'],
   'number': ['color3'],
   'possesive': ['color3'],
   'poss': ['color3'],
   'discourse': ['color3'],
   'expletive': ['color3'],
   'prt': ['color3'],
   'advcl': ['color3'],
   'mod': ['color4'],
   'amod': ['color4'],
   'tmod': ['color4'],
   'quantmod': ['color4'],
   'npadvmod': ['color4'],
   'infmod': ['color4'],
   'advmod': ['color4'],
   'appos': ['color4'],
   'nn': ['color4'],
   'neg': ['color0'],
   'punct': ['color0']},
  'linkToPosition': {'nsubj': 'left',
   'nsubjpass': 'left',
   'csubj': 'left',
   'csubjpass': 'left',
   'pobj': 'right',
   'dobj': 'right',
   'iobj': 'right',
   'pcomp': 'right',
   'xcomp': 'right',
   'ccomp': 'right',
   'acomp': 'right'}}}
`

**Comment by schmmd** [comment]
@datix-vishu thanks for your help!  @bikegirl let us know if what @datix-vishu mentioned works for you too.

**Comment by bikegirl** [comment]
@matt-gardner Thanks for letting me know!  I'll just use predict
@schmmd @datix-vishu  Method 0 was the one that worked for me!  Thanks for all the help.  I just had to hardcode my space for that version.  Not sure what behavior I changed from last time I tried and from when I got the error this time, but it works either way now (-:
