### ISSUE TITLE
Customizable loggers for external platforms

### ISSUE THREAD

**Issue by mateuszpieniak** [allenai/allennlp#3990]
**Is your feature request related to a problem? Please describe.**
Whilst using AllenNLP, I miss a way to manage experiments using external platforms like Polyaxon, Neptune.ai, Comet.ml, MLFlow and so on. I managed to synchronize one of them using `CallbackTrainer`, but since `CallbackTrainer` is out of the picture, I need to temporarily change the framework.

**Describe the solution you'd like**
I encountered a very cool solution from PyTorchLightning that could be similarly integrated into the AllenNLP i.e. the concept of loggers - https://pytorch-lightning.readthedocs.io/en/0.6.0/logging.html - please take a look.

**Comment by matt-gardner** [comment]
There are now `BatchCallback` and `EpochCallback` objects that should let you do whatever logging or synchronization that you want.

**Comment by mateuszpieniak** [comment]
@matt-gardner Thanks, I will take a look. Anyway, this logging feature is worth consideration for future developments :+1:

**Comment by rzepinskip** [comment]
@mateuszpieniak Have you started working on this feature? I am happy to help.

**Comment by mohiitaa** [comment]
Hi @mateuszpieniak, could you let me know how you used BatchCallback and EpochCallback to use external apps like Neptune.ai? Thanks in advance!

**Comment by dirkgr** [comment]
You can look at how @dhruvdcoder did it here: https://github.com/dhruvdcoder/wandb-allennlp/blob/master/wandb_allennlp/training/callbacks/log_to_wandb.py. There is some extra code in there for compatibility that you probably don't need, but the principle should be the same.
