### ISSUE TITLE
Strange behaviour when embedding the same sentence twice

### ISSUE THREAD

**Issue by AndreaSottana** [allenai/allennlp#3995]
System (please complete the following information):

OS: MacOs 10.14.6 (Mojave)
Python version: 3.6.4
AllenNLP version: 0.9.0

I am writing some testing for my own code which uses the ElmoEmbedder class from allennlp and I noticed a behaviour I would not expect.

I have a list of sentences where the first and last sentences are equal.
```
import nltk
import numpy as np
from allennlp.commands.elmo import ElmoEmbedder

list_of_sentences = ['Mr Michael went to the store to buy some eggs.',
 'Joel rolled down the street on his skateboard.',
 'test / this is a first sentence',
 "Take a look, then, at Tuesday's elections in New York City, New Jersey and Virginia:",
 'Mr Michael went to the store to buy some eggs.']
```

If I compare the embeddings of the first and last sentence they are equal
In other words, this assert statement passes correctly.

```
elmo_embedder = ElmoEmbedder()
elmo = elmo_embedder.embed_sentences([nltk.word_tokenize(sentence) for sentence in list_of_sentences], batch_size=16)
sentence_embeddings = []
for embedding in elmo:
    sentence_embedding = np.mean(embedding, axis=1)[2]
    sentence_embeddings.append(sentence_embedding)
sentence_embeddings = np.array(sentence_embeddings)
np.testing.assert_almost_equal(sentence_embeddings[0], sentence_embeddings[4])
```

However, if I then re-use the same instance `elmo_embedder` to embed the first sentence again, the assertion throws an error

```
elmo = elmo_embedder.embed_sentences([nltk.word_tokenize(list_of_sentences[0])], batch_size=16)
emb = next(elmo)
np.testing.assert_array_almost_equal(np.mean(emb, axis=1)[2], sentence_embeddings[0])
```

Why is it the case that the two embeddings for the sentence `'Mr Michael went to the store to buy some eggs.'` are now so different? (way more different that I would expect, even taking into account that the internal state depends on previous batches)

**Comment by dirkgr** [comment]
The default tolerance of `almost_equal` is quite strict. We would not expect this to work with a strict tolerance. Does it work with a higher one?

**Comment by AndreaSottana** [comment]
It only works if I set `decimal=0` (which is way too high), it doesn't even work with `decimal=1` (the default is 6).
The assertion error is showing how different the two vectors actually are, even if we compare just the first element it's -0.239 vs. -0.321
```
Max absolute difference: 0.29576227
Max relative difference: 100.387085
 x: array([-0.238942,  0.130121, -0.307446, ..., -0.339011,  0.140871,
        0.11999 ], dtype=float32)
 y: array([-0.321438,  0.161224, -0.261567, ..., -0.339503,  0.137341,
        0.134955], dtype=float32)
```
I have updated the reproducible example in the original comment as it contained a typo. The example should now be reproducible by plain copy and paste

**Comment by dirkgr** [comment]
In general, we recommend you warm up ELMo's internal state by embedding a few sentences before you start. When I run your sentences through it repeatedly, the differences become smaller.

Also, I would recommend to use `assert_allclose` instead. That way you get better control over which differences are OK and which ones are not.

**Comment by AndreaSottana** [comment]
Ok, this is interesting, I can see the trend. After I embed the same sentence about 15 times the embedding seems to change abruptly and then stays very similar thereafter. Is this "warm up" something you would recommend doing before embedding what I actual want to embed (meaning I will just embed some initial random sentences and discard those)? If so, do you have a pre-set of sentences for warming up the initial state, or it doesn't really matter?

For reference, I've tried to embed the same sentence 200 times, and after ~15 times the embedding changes significantly (below is the 3rd element of the embedding taken as an example). Is this a normal behaviour you would expect then?
```
0.052924242
0.052924242
0.052924242
0.052924242
0.052924242
0.052924242
0.052924242
0.052924242
0.052924242
0.052924242
0.052924242
0.052924242
0.052924242
0.052924242
0.052924242
0.052924242
-0.009119424
-0.009119424
-0.009119424
-0.009119424
```
And thereafter it always stays around -0.009, but the change between the 16th and 17th embedding is significant

**Comment by dirkgr** [comment]
I modified your code a little to see how large the differences are on average as you embed the same text over and over again:
```Python
import nltk
import numpy as np
from allennlp.commands.elmo import ElmoEmbedder

list_of_sentences = ['Mr Michael went to the store to buy some eggs.',
 'Joel rolled down the street on his skateboard.',
 'test / this is a first sentence',
 "Take a look, then, at Tuesday's elections in New York City, New Jersey and Virginia:",
 'Mr Michael went to the store to buy some eggs.']

elmo_embedder = ElmoEmbedder()

def embed(sentences):
     elmo = elmo_embedder.embed_sentences([nltk.word_tokenize(sentence) for sentence in sentences], batch_size=16)
     sentence_embeddings = []
     for embedding in elmo:
         sentence_embedding = np.mean(embedding, axis=1)[2]
         sentence_embeddings.append(sentence_embedding)
     return np.array(sentence_embeddings)

e1 = embed(list_of_sentences)
for i in range(30):
     e2 = embed(list_of_sentences)
     print(np.mean(np.absolute(e1 - e2)))
     e1 = e2
```

This prints, on my box, this:
```
0.05396391
0.0019521887
0.00024399883
5.867001e-05
1.777998e-05
6.16257e-06
2.3155012e-06
9.39984e-07
4.185286e-07
2.1638239e-07
1.3675228e-07
1.0350286e-07
9.159729e-08
9.075994e-08
8.912288e-08
9.117668e-08
8.9237645e-08
8.810777e-08
8.9966534e-08
8.9136726e-08
9.050188e-08
9.1290154e-08
8.888618e-08
8.569735e-08
8.8185686e-08
8.9067235e-08
8.7056705e-08
8.8478224e-08
8.737114e-08
8.845625e-08
```

So it seems like it converges, and then bounces around a bit. I find it a bit surprising that in the example that you showed, the sign changes. But the magnitude of the change is still small. I don't see anything too worrisome.

I would treat the ELMo warmup the same as picking a random seed. From these numbers it looks to me like you want to run maybe 10-20 sentences through it, and then you're good to go.
