### ISSUE TITLE
Is there a way to solve nested reference in coref_resolved text

### ISSUE THREAD

**Issue by datix-vishu** [allenai/allennlp#3997]
For example, consider the following text : 

**_Original Text_**
Russia formally charged **former Marine Paul Whelan** with espionage, according to a report Thursday. “An indictment has been presented. Whelan dismisses it,” Interfax news agency reported, citing a source.Whelan, a Michigan native, was arrested last Friday by members of the Russian Federal Security Service (FSB) who accused him of being on a “spy mission,” and he has since been detained at Lefortovo Prison in Moscow. US Ambassador to Russia Jon Huntsman met with Whelan at the prison Wednesday and talked to **his family**, the State Department said. **Whelan’s family** said the 48-year-old, who is director of global security for Michigan-based auto supplier BorgWarner, traveled to Moscow last month to attend the wedding of a fellow Marine veteran to a Russian woman. Whelan faces up to 20 years in prison if convicted. The FSB has not released information on why Whelan was arrested. Secretary of State Mike Pompeo said the US has demanded answers from Russia. “We’ve made clear to the Russians our expectation that we will learn more about the charges, come to understand what it is he’s been accused of and if the detention is not appropriate, we will demand his immediate return,” he said.

**_coref_resolved_**
Russia formally charged former Marine Paul Whelan with espionage, according to a report Thursday. “An indictment has been presented. former Marine Paul Whelan dismisses charged,” Interfax news agency reported, citing a source. Whelan, a Michigan native, was arrested last Friday by members of the Russian Federal Security Service (FSB) who accused former Marine Paul Whelan of being on a “spy mission,” and former Marine Paul Whelan has since been detained at Lefortovo Prison in Moscow. US Ambassador to Russia Jon Huntsman met with former Marine Paul Whelan at Lefortovo Prison in Moscow Wednesday and talked to **former Marine Paul Whelan's family**, the State Department said. **his family** said the 48-year-old, who is director of global security for Michigan-based auto supplier BorgWarner, traveled to Moscow last month to attend the wedding of a fellow Marine veteran to a Russian woman. former Marine Paul Whelan faces up to 20 years in prison if convicted. the Russian Federal Security Service (FSB) has not released information on why former Marine Paul Whelan was arrested. Secretary of State Mike Pompeo said the US has demanded answers from Russia. “the US’ve made clear to the Russians the US's expectation that the US will learn more about the charges, come to understand what it is former Marine Paul Whelan’s been accused of and if arrested is not appropriate, the US will demand former Marine Paul Whelan's immediate return,” Secretary of State Mike Pompeo said.

_Look at the highlighted text (references), "his family" was correctly replaced with  "former Marine Paul Whelan's family" , but  "Whelan’s family" was replaced with "his family". Is there a way to avoid this kind of nested coref ?_

**Comment by ZhaofengWu** [comment]
Feel free to take the predicted clusters and change the `replace_coref`https://github.com/allenai/allennlp/blob/adeb1b1278619ff2d74d4fd82825e50a36f95ff4/allennlp/predictors/coref.py#L121 function locally to whatever you want.

**Comment by datix-vishu** [comment]
Yep, I'm on it !!!
