### ISSUE TITLE
Vocabulary module has been changed drastically

### ISSUE THREAD

**Issue by entslscheia** [allenai/allennlp#4002]
I found that `Vocabulary` has been changed drastically recently. To be specific, seems like you have removed `from_params` and also `directory_path` ,which allows us to directly load the vocabulary from a specified path. Is there any updated use case for the new version of `Vocabulary`. Also, I found there have been many drastical changes during the last couple of weeks. This makes all my old projects not work if I updated my local AllenNLP library. Are we going to have a stable version in the near future?

**Comment by schmmd** [comment]
@entslscheia yes, we're making much fewer changes now.  We plan to have a 1.0 release candidate soon (new two weeks).  My apologies for the churn as we move towards a 1.0 release.
