### ISSUE TITLE
Different SRL results when using the bert-base-srl-2019.06.17.tar.gz and the online demo

### ISSUE THREAD

**Issue by igormis** [allenai/allennlp#4009]
**System:**
 - OS: Ubuntu 18.04
 - Python version: 3.6.7
 - AllenNLP version: v0.9.0
 - PyTorch version: 1.3.1

**Question**

* I am using the model `bert-base-srl-2019.06.17.tar.gz` in my python code in the following way:
import re
```
from allennlp.predictors.predictor import Predictor
import torch
print(torch.__version__)
#predictor = Predictor.from_path("https://s3-us-west-2.amazonaws.com/allennlp/models/srl-model-2018.05.25.tar.gz")
predictor = Predictor.from_path("./bert-base-srl-2019.06.17.tar.gz")

def predict(text):
	results = predictor.predict(
	  sentence=text
	)
      return results
```
However when i use the following text as an input:
`text = "Facebook reports robust profit, revenue gains; stock rises"`
the results is:
`{'verbs': [], 'words': ['Facebook', 'reports', 'robust', 'profit', ',', 'revenue', 'gains', ';', 'stock', 'rises']}
`
However when I use the [demo](https://demo.allennlp.org/semantic-role-labeling/MTY0MzI0Nw==) for the same text I get the expected results, i.e:
```
reports: [ARG0: Facebook] [V: reports] [ARG1: robust profit , revenue gains ;] stock rises
rises: Facebook reports robust profit , revenue gains ; [ARG1: stock] [V: rises]
```
I have noticed this behaviour (better results are given using the demo) on more examples. could you tell me what is the cause? Is it different model? Or some pre-processing that you are doing before inference?

**Comment by schmmd** [comment]
@igormis the demo is using a much later version of AllenNLP and in some cases different models too.  We'll have a release soon.

https://github.com/allenai/allennlp-demo
