### ISSUE TITLE
NER in the demo is not working for specific text ! 

### ISSUE THREAD

**Issue by datix-vishu** [allenai/allennlp#4011]
@schmmd @dirkgr which version of AllenNLP supports this model "**fine-grained-ner-model-elmo-2020.02.10.tar.gz**". I've tried a few versions and none of them worked ( tried allenNLP demo too)

And do you know why NER ( current demo ) is not working for the following text ?

Text :
`Dwayne Haskins passed for 251 yards and three touchdowns, and Urban Meyer finished his coaching career at Ohio State with a 28-23 victory after the Buckeyes held off Washington’s thrilling fourth-quarter comeback in the 105th Rose Bowl on Tuesday. Parris Campbell, Johnnie Dixon and Rashod Berry caught TD passes in the first half for the fifth-ranked Buckeyes (13-1), who took a 25-point lead into the fourth. But Myles Gaskin threw a touchdown pass and rushed for two more scores for the No. 9 Huskies (10-4), scoring from 2 yards out with 42 seconds left. The Buckeyes intercepted Jake Browning’s pass on the 2-point conversion attempt and then recovered the Huskies’ onside kick to wrap up the final game of Meyer’s seven-year tenure. “I’m a very blessed man,” Meyer said. “I’m blessed because of my family, [but] this team, this year, I love this group as much as any I’ve ever had.”`

**Comment by dirkgr** [comment]
The NER model at http://demo.allenai.org can process your text just fine. So does this branch in [allennlp-demo](https://github.com/allenai/allennlp-demo/pull/335).

The fine-grained one is broken, and confusingly it's even broken on http://demo.allenai.org. I will look into it tomorrow or on Monday.

**Comment by datix-vishu** [comment]
Thanks Brother

**Comment by datix-vishu** [comment]
making '**fine-grained-ner-model-elmo-2020.02.10.tar.gz**' compatible will be the best choice

**Comment by dirkgr** [comment]
Fine-grained NER works now in the demo, but with this particular input it produces no output.

**Comment by dirkgr** [comment]
We should re-train fine-grained NER from scratch, maybe with the `config.json` file from the original model as a template. I can't promise that will happen soon, but if one of you want to do it, I'll be happy to update the model in the demo with it.

**Comment by datix-vishu** [comment]
@dirkgr what you just said is absolutely correct, the Fine-grained NER works and it is not broken. I was experimenting with the Fine-grained NER model for a variety of text encodings/formats. At last, what I observed is that some text inputs need some amount of cleaning to perform or produce the best results. For example, if you try the text that I mentioned earlier, you won't get any output. But once a small amount of text cleaning is done, the fine-grained model works with top-class performance. Check the cleaned text below:

**Text**
`Dwayne Haskins passed for 251 yards and three touch downs, and Urban Meyer finished his coaching career at Ohio State with a 28 23 victory after the Buckeyes held off Washington's thrilling fourth-quarter comeback in the 105th Rose Bowl on Tuesday. Parris Campbell, Johnnie Dixon and Rashod Berry caught passes in the first half for the fifth-ranked Buckeyes, who took a 25 point lead into the fourth. But Myles Gaskin threw a touch down pass and rushed for two more scores for the number 9 Huskies, scoring from 2 yards out with 42 seconds left. The Buckeyes intercepted Jake Browning's pass on the 2 point conversion attempt and then recovered the Huskies's onside kick to wrap up the final game of Meyer's seven-year tenure. I'm a very blessed man, Meyer said. I'm blessed because of my family, this team, this year, I love this group as much as any I've ever had.`

**Comment by datix-vishu** [comment]
@dirkgr Now the only thing I'm looking forward is the same Fine-grained model that works with the current master. I'm using coref and NER, so managing 2 different versions of allennlp is not preferable.

**Comment by dirkgr** [comment]
This works now with the URLs `"https://storage.googleapis.com/allennlp-public-models/fgner_transformer.2020-06-24.tar.gz"` or `"https://storage.googleapis.com/allennlp-public-models/fine-grained-ner.2020-06-24.tar.gz"`. The transformer one has slightly better performance.

**Comment by dirkgr** [comment]
The new model is in the demo now.
