### ISSUE TITLE
TypeError for TextFieldEmbedder

### ISSUE THREAD

**Issue by Twsschx** [allenai/allennlp#4013]
I find a mistake while using the class 'TextFieldEmbedder'.
![image](https://user-images.githubusercontent.com/45708562/78244835-f9de9400-7518-11ea-9b59-e55d3787686f.png)

params sent to TextFieldEmbedder are :
param_question_embedder = {
      "tokens": {
        "type": "embedding",
        "embedding_dim": 200,
        "trainable": True
      }
    }

and I don't know why this error comes.

**Comment by Twsschx** [comment]
the variable question_embedder belongs to TextFieldEmbedder. How to modify its params?

**Comment by dirkgr** [comment]
Did you mean to call `TextFieldEmbedder.from_params()` instead?

If that's not it, can you post a small snippet of executable code that I can try myself?

**Comment by matt-gardner** [comment]
The problem is a missing `token_embedders` key (sorry for the brevity, off to a meeting).

**Comment by dirkgr** [comment]
Oh! What Matt means is this:
```
"text_field_embedder": {
  "token_embedders": {
    "tokens": {
      "type": "embedding",
      "embedding_dim": 200,
      "trainable": True
    }
  }
}
```
Use that structure when defining a `TextFieldEmbedder`.

**Comment by Twsschx** [comment]
> Oh! What Matt means is this:
> 
> ```
> "text_field_embedder": {
>   "token_embedders": {
>     "tokens": {
>       "type": "embedding",
>       "embedding_dim": 200,
>       "trainable": True
>     }
>   }
> }
> ```
> 
> Use that structure when defining a `TextFieldEmbedder`.

On thanks! I have changed the setting like :
param_question_embedder = {
      "token_embedders": {
        "tokens": {
          "type": "embedding",
          "embedding_dim": 200,
          "trainable": True
        }
      }
    }
but still got a problem:
![image](https://user-images.githubusercontent.com/45708562/78454866-4d91de80-76cd-11ea-9042-e6055e513656.png)

I read the source and couldn't find the answer😂
.

**Comment by matt-gardner** [comment]
If you're just constructing all of your objects sequentially in a script, you shouldn't be worrying about constructing params dictionaries at all.  All that the `from_params` stuff does is pass arguments to a constructor.  If you're constructing the object yourself, it's entirely pointless to create a parameter dictionary and pass that to `from_params` - just call the constructor directly.

For example, a config that looks like this: 
<img width="385" alt="Screen Shot 2020-04-04 at 8 46 21 AM" src="https://user-images.githubusercontent.com/3291951/78455061-ff3efa00-7650-11ea-8461-4ac14db32a89.png">
accomplishes the same thing as actual python code that looks like this: 
<img width="558" alt="Screen Shot 2020-04-04 at 8 46 27 AM" src="https://user-images.githubusercontent.com/3291951/78455069-08c86200-7651-11ea-9976-3cd358e217f1.png">
