### ISSUE TITLE
params for the 'TextFieldEmbedder': 'dict' object has no attribute 'pop_choice'

### ISSUE THREAD

**Issue by Twsschx** [allenai/allennlp#4024]
I have accepted your advice and set params like the following for the Class 'TextFieldEmbedder':
param_question_embedder = {
      "token_embedders": {
        "tokens": {
          "type": "embedding",
          "embedding_dim": 200,
          "trainable": True
        }
      }
    }

but I found a mistake when I was going to send it to a new variable:
question_embedder = TextFieldEmbedder.from_params(param_question_embedder)

the error is that:
![image](https://user-images.githubusercontent.com/45708562/78455095-e1b07580-76ce-11ea-9a80-167c0fd583c5.png)

I have read the source code and couldn't find a solution😂.

**Comment by Twsschx** [comment]
On! The error is "'dict' object has no attribute 'pop_choice'"
![image](https://user-images.githubusercontent.com/45708562/78455202-73b87e00-76cf-11ea-9ba3-a69cd28a1427.png)

I forgot to add the picture

**Comment by matt-gardner** [comment]
Copying [my response](https://github.com/allenai/allennlp/issues/4013#issuecomment-609048239) from the other issue:

If you're just constructing all of your objects sequentially in a script, you shouldn't be worrying about constructing params dictionaries at all.  All that the `from_params` stuff does is pass arguments to a constructor.  If you're constructing the object yourself, it's entirely pointless to create a parameter dictionary and pass that to `from_params` - just call the constructor directly.

For example, a config that looks like this: 
<img width="385" alt="Screen Shot 2020-04-04 at 8 46 21 AM" src="https://user-images.githubusercontent.com/3291951/78455061-ff3efa00-7650-11ea-8461-4ac14db32a89.png">
accomplishes the same thing as actual python code that looks like this: 
<img width="558" alt="Screen Shot 2020-04-04 at 8 46 27 AM" src="https://user-images.githubusercontent.com/3291951/78455069-08c86200-7651-11ea-9976-3cd358e217f1.png">

**Comment by Twsschx** [comment]
> Copying [my response](https://github.com/allenai/allennlp/issues/4013#issuecomment-609048239) from the other issue:
> 
> If you're just constructing all of your objects sequentially in a script, you shouldn't be worrying about constructing params dictionaries at all. All that the `from_params` stuff does is pass arguments to a constructor. If you're constructing the object yourself, it's entirely pointless to create a parameter dictionary and pass that to `from_params` - just call the constructor directly.
> 
> For example, a config that looks like this:
> <img alt="Screen Shot 2020-04-04 at 8 46 21 AM" width="385" src="https://user-images.githubusercontent.com/3291951/78455061-ff3efa00-7650-11ea-8461-4ac14db32a89.png">
> accomplishes the same thing as actual python code that looks like this:
> <img alt="Screen Shot 2020-04-04 at 8 46 27 AM" width="558" src="https://user-images.githubusercontent.com/3291951/78455069-08c86200-7651-11ea-9976-3cd358e217f1.png">

Thanks for your advice!
