### ISSUE TITLE
Attention Questions

### ISSUE THREAD

**Issue by aclifton314** [allenai/allennlp#4025]
**System:**
 - OS: Pop!_OS 19.10
 - Python version: 3.7.4
 - AllenNLP version: 0.9.0
 - PyTorch version: 1.4.0

**Question**
I have a few questions about the `passage_question_attention` that is returned for the `BidafPredictor`.
- In `_matrix_attention` it states I am using `LegacyMatrixAttention` with the `LinearSimilarity` similarity function with combination `x, y, x*y`. I was reading through the code, but I am having a hard time understanding exactly how this attention is being calculated. Does someone mind explaining it?

- I have the following code:
```python
passage = 'The Matrix is a 1999 science fiction action film starring Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss, Hugo Weaving, and Joe Pantoliano.'
question = 'Who stars in The Matrix?'
predictor = Predictor.from_path("https://storage.googleapis.com/allennlp-public-models/bidaf-elmo-model-2018.11.30-charpad.tar.gz")
qa_results = predictor.predict(passage = passage, question= question)
```
The results that get returned for `passage_question_attention` looks like a list of lists with shape (35, 6). What is the meaning of these dimensions? The list is something like a list of 35 lists, with each of those 35 lists having a length of 6.

- With that attention, how would I construct an attention map? In other words, how do I know which attention value is associated with which two words?

Thank you in advance for your help!

**Comment by matt-gardner** [comment]
My recommendation for this question would be to look at the code, it's fairly well documented for what these things are: https://github.com/allenai/allennlp-models/blob/e26e2a1096e772109ce191a1eefd1c418ee352d0/allennlp_models/rc/bidaf/bidaf_model.py#L137-L327
One thing to note is that what you get out of `predict()` will have the batch dimension stripped.  What you'll find when you look at the code is that the (35, 6) corresponds to (passage_length, question_length).

For visualizing things, you might look at our demo code (this one takes some more tracing through of where things are called and how they are presented): https://github.com/allenai/allennlp-demo/blob/c97574f92ced83893977fb9040fe734b566f7182/demo/src/components/demos/ReadingComprehension.js#L92-L94
