### ISSUE TITLE
How to work with Open Information Extraction ?

### ISSUE THREAD

**Issue by datix-vishu** [allenai/allennlp#4029]
using **allenNLP v0.9.1** current master

**_This is the code I used:_**
`from allennlp.predictors import Predictor`
`import allennlp_models.syntax`
`predictor = Predictor.from_path(".../openie-model.2020.03.26.tar.gz")`

Every time I load this model, it automatically loads the model to SRL. I want to try out **openie** prediction !

**Comment by matt-gardner** [comment]
The OpenIE model structure is identical to the SRL model, it was just trained differently.  If you load a trained SRL model (not actually sure whether we still have a working one that uses the same code), you'll see that the predictors are quite different.  So, even if it says it's SRL, it's using OpenIE weights and vocabulary and should give you OpenIE output.
