### ISSUE TITLE
`allennlp configure` doesn't make sense

### ISSUE THREAD

**Issue by dirkgr** [allenai/allennlp#4033]
@Tobias-Rohde reports that we still tell people to run `allennlp configure`, but it doesn't work anymore.

**Comment by matt-gardner** [comment]
You need to pip install the [allennlp-server](https://github.com/allenai/allennlp-server) repo, then I *think* that it gets auto-added as a plugin, and things work.

**Comment by matt-gardner** [comment]
I was writing some stuff about config files for the quick start chapter in the allennlp course, and I realized that there's a fundamental problem with the configuration wizard - we don't have a way of telling the wizard which constructor arguments come from a config file and which are built separately.  I don't know how to solve this problem, and we really need to solve it if we ever want to revive the configuration wizard.

**Comment by matt-gardner** [comment]
Incidentally, this is also something that should be surfaced somewhere in our documentation, but that's a separate issue (unless you want the configuration wizard to parse the documentation to figure this out, which isn't infeasible if we really want to do it...).

**Comment by dirkgr** [comment]
I definitely don't want the configuration wizard parse documentation to determine behavior.

**Comment by matt-gardner** [comment]
It already does, it turns out (it parses the parameter section). I'm not advocating doing this, I was just speculating on what it would take if we wanted to do it; I think there are likely better ways of helping people with config files than that wizard.

**Comment by dirkgr** [comment]
Closed in favor of #4053.
