### ISSUE TITLE
Cases where the length of the IterableDataset is not overriden properly

### ISSUE THREAD

**Issue by maksym-del** [allenai/allennlp#4035]
```_LazyInstances``` (allennlp's subclass of ```IterableDataset```) returns ```1``` when the ```__len__``` method is not overridden.  
This, for example, causes a problem with ```SlantedTriangular``` which expects the length of the dataset in batches as constructor parameter if used programmatically.

See https://github.com/allenai/allennlp/pull/4028#issuecomment-610098163 and https://github.com/allenai/allennlp/pull/4028#issuecomment-610109566  for more context.

**Comment by dirkgr** [comment]
It is baffling behavior to return `1` for the length. We should return `None` for the length when we don't know, and deal with the fallout wherever it happens.

**Comment by JohnGiorgi** [comment]
@maksym-del If I __did__ want to use `SlantedTriangular` while `lazy=True` in my `DatasetReader`, would I just manually set `dataloader.batches_per_epoch` in my config? 

(not just asking to be annoying, I actually do wan't to used `SlantedTriangular` with a lazy reader).

**Comment by maksym-del** [comment]
@JohnGiorgi yes, specifying batches per epoch in loader and passsing corresponding number to the scheduler should work.

**Comment by JohnGiorgi** [comment]
@maksym-del Awesome, thanks!
