### ISSUE TITLE
Missing wrapper for BiAugmentedLSTM

### ISSUE THREAD

**Issue by ZhaofengWu** [allenai/allennlp#4037]
`AugmentedLSTM` has a corresponding wrapper `AugmentedLstmSeq2SeqEncoder` in `pytorch_seq2seq_wrapper.py`, but `BiAugmentedLSTM` doesn't have one. Also, I didn't look into much detail, but the `forward` of `AugmentedLSTM` vs. `BiAugmentedLSTM` have different annotated return types but seem to actually return the same (typed) thing. A minor mistake?

**Comment by bratao** [comment]
From what I remembered. AugumentedLSTM was not a full replacement to Pytorch LSTM. During the backport I did from Pytext, I wanted it to be one. So the BiAugmentedLSTM was created, as a drop in replacement to the standard LSTM.
But to keep all the previous tests and code working, I left this class.

I'm away from coding for a little while. But your understanding is correct. Could you please fix it?
