### ISSUE TITLE
Fields have large memory footprints

### ISSUE THREAD

**Issue by nelson-liu** [allenai/allennlp#4039]
I've noticed that `Fields` can have quite a bit of memory overhead—it's very common that i'll have a dataset that I can load into memory (e.g., with `json.load`), but turning it into fields / instances blows up the memory usage.

For instance, I've been doing some stuff with span representations recently, so using a `ListField[SpanField]` in my `Instances`. Each of these `ListFields` is around ~3000 elements. If I run the following:

```
In [1]: from allennlp.data import Token
   ...: from allennlp.data.fields import TextField, SpanField
   ...: from allennlp.data.token_indexers import SingleIdTokenIndexer

In [2]: indexers = {"words": SingleIdTokenIndexer("words")}

In [3]: text = TextField(
   ...:             [Token(t) for t in ["here", "is", "a", "sentence", "for", "spans", "."]], indexers
   ...:         )

In [4]: l = []

In [5]: for i in range(10000*3500):
   ...:     l.append(SpanField(2, 3, text))
```

and check the memory usage, it's around 6.5 gigabytes for 10,000 simulated instances (when I have much more, ranging between 100,000 on some datasets to 800,000 on other, larger datasets). Maybe this size is reasonable, though, and I'm just being dumb here. Let me know if that's the case...

Where does all of this overhead come from? Is there anything we can do to reduce it?

**Comment by nelson-liu** [comment]
Fwiw, replacing `ListField[SpanField]` with `ArrayField` (with padding value -1 and dtype np.int64) is _much_ faster and also has a _much_ smaller memory footprint.

**Comment by matt-gardner** [comment]
This is almost certainly overhead in python object / list creation.  Maybe the solution is to just give a caveat in `ListField` that if you have very long lists, you might consider using `ArrayField` directly instead.  I don't think this is a huge problem for our other uses of this (e.g., the constituency parser, the coref model, etc.).

**Comment by schmmd** [comment]
To close this ticket out we want to add a disclaimer to the docstring on ListField, as @matt-gardner suggests above.

**Comment by dirkgr** [comment]
@Tobias-Rohde also ran into this problem when training BART.

**Comment by dirkgr** [comment]
According to @nelson-liu's numbers above, instances take 650kb each. That is hard to explain with just `ListField[SpanField]` vs. `ArrayField`. I think this is a real problem and we need to follow up, not just update the documentation.

**Comment by nelson-liu** [comment]
Isn't the `ListField[SpanField]` vs. `ArrayField` more accurately reflected by memory taken before and after? I didn't have the time to measure this after figuring out my issue, sorry about that.

I think it's fine for instances themselves to take 650kb, depending on what's in them. For instance, there were several large (but of expected size) `TextField`s and `MetadataField`s (the task is SQuAD-like).

**Comment by epwalsh** [comment]
I think the change to using slots classes for tokens, fields, and instances (especially tokens) has made a big impact.

But just so this is documented, I played around a little bit with `ListField` and `TextField` to see if using tuples instead of lists would result in significantly less memory consumption. Using an example similar to @nelson-liu's above, I only saw a 2% reduction in memory usage.

So I don't think there's really much else, if anything, we can do.

**Comment by dirkgr** [comment]
I didn't try @nelson-liu's example before the change, but I did try it just now. Memory usage on my Mac goes to 3GB with the code you have there. With `10000*3500` fields, that comes out to 92 bytes per span field.

The size of the `TextField` doesn't have much of a bearing in this example, because there is only one, which is shared.

**Comment by epwalsh** [comment]
> The size of the `TextField` doesn't have much of a bearing in this example, because there is only one, which is shared.

I should have mentioned that I modified the example to use a separate TextField for each instance.

**Comment by dirkgr** [comment]
@nelson-liu, can we close this issue?

**Comment by nelson-liu** [comment]
Yup, thanks!!
