### ISSUE TITLE
How is SimpleGradient for interpret calculated

### ISSUE THREAD

**Issue by aclifton314** [allenai/allennlp#4042]
**System**
- OS: Pop!_OS 19.10
- Python version: 3.7.4
- AllenNLP version: 0.9.0
- PyTorch version: 1.4.0

**Question**
How is the SimpleGradient calculated for the interpret module in general and for the case of a BidafPredictor?

**Comment by matt-gardner** [comment]
You can see the code for getting input gradients here: https://github.com/allenai/allennlp/blob/c497103542096037dc21c24466127bc6c820e75b/allennlp/predictors/predictor.py#L85.  You can see the exact computation that is performed with those gradients here: https://github.com/allenai/allennlp/blob/c497103542096037dc21c24466127bc6c820e75b/allennlp/interpret/saliency_interpreters/simple_gradient.py#L43-L46.
