### ISSUE TITLE
New demo SRL model !!!

### ISSUE THREAD

**Issue by datix-vishu** [allenai/allennlp#4046]
It is good to see more advanced models in the demo site. I was going through the SRL model and tried out this text:

**_Text_**
`former Marine Paul Whelan, was arrested last Friday by members of the Russian Federal Security Service (FSB) who accused former Marine Paul Whelan of being on a “spy mission,” and former Marine Paul Whelan has since been detained at Lefortovo Prison in Moscow.`

and the output for the verb "detained" is as follows:

**_Output_**
`detained: former Marine Paul Whelan , was arrested last Friday by members of the Russian Federal Security Service ( FSB ) who accused former Marine Paul Whelan of being on a “ spy mission , [ARG1: ” and] [ARG1: former Marine Paul Whelan] has [ARGM-TMP: since] been [V: detained] [ARG2: at Lefortovo Prison] [ARGM-LOC: in Moscow] .`

I was wondering why there is no Argument0, it starts with Argument1 instead.

**Comment by matt-gardner** [comment]
"detained" in that sentence is passive.  ARG0 is the "agent" argument, and there isn't one here (who was doing the detaining is not specified in the sentence).  Maybe it's implied as being the FSB, but that isn't necessarily true, and the SRL model is just looking for what's present syntactically, not what's implied.
