### ISSUE TITLE
Semantic Role Labeler has different output than demo

### ISSUE THREAD

**Issue by Parth27** [allenai/allennlp#4047]
**Describe the bug**
Hello,
I am facing a similar issue with the semantic role label predictor.
For a sentence like 'Please take a few minutes to review our 2001 goals on Enrons intranet' part of my output is this:
{'verbs': [{'verb': 'take', 'description': '[ARGM-DIS: Please] [V: take] [ARG1: a few minutes] [ARGM-PRP: to review our 2001 goals on Enrons intranet]'

As you can see, it classifies 'to review' as Purpose. But on the demo, it correctly says that this is not a Purpose.
This is the output of demo:
take: [ARGM-DIS: Please] [V: take] [ARG1: a few minutes] [ARG0: to review our 2001 goals on Enrons intranet]

I have tried with newer as well as older spacy versions, specifically: 2.1.4, 2.1.9 and 2.2.4.
Please @matt-gardner get back to me as soon as possible, I really need this to work.

**To Reproduce**
Same syntax as mentioned on demo webpage

**Expected behavior**

**System (please complete the following information):**
 - OS: Ubuntu 19.04
 - Python version: 3.7.3
 - AllenNLP version: 0.9.0
 - PyTorch version: 1.4.0

**Comment by schmmd** [comment]
We recently made some updates which may have changed the demo performance, but you can look at https://github.com/allenai/allennlp-demo/blob/master/models.json to see exactly what the demo does.

**Comment by Parth27** [comment]
> We recently made some updates which may have changed the demo performance, but you can look at https://github.com/allenai/allennlp-demo/blob/master/models.json to see exactly what the demo does.

Thank you @schmmd !
The version of srl model in this json file is giving me the correct results now.
