### ISSUE TITLE
How do I install the latest version of allenlp? 

### ISSUE THREAD

**Issue by lwgkzl** [allenai/allennlp#4048]
How do I install the latest version of allenlp? The version installed with pip is 0.90. But i use bert according the lastest allennlp code.

I'd appreciate any thoughts!

**Comment by datix-vishu** [comment]
You need to install **_allennlp_** using git if you want the current master ( latest code). But its the sable standard version. The last stable version was v0.9.0 and as per these amazing people at **allennlp** , version 1.0 is coming to action soon and its going to be a big upgrade.

**Comment by schmmd** [comment]
We will have a release candidate out next week.  Until then: https://github.com/allenai/allennlp/blob/master/README.md#installing-from-source

**Comment by lwgkzl** [comment]
Thank you very much : ）
