### ISSUE TITLE
Module organization is a bit confusing

### ISSUE THREAD

**Issue by nelson-liu** [allenai/allennlp#4051]
Thanks for working on this, it seems like a nice step in the right direction.

When poking around, I found the structure of the module to be quite confusing, up to the point where I even thought that things were removed.

Let's take `allennlp_models.rc` as an example:

so all the bidaf stuff is in `allennlp_models.rc.bidaf`, this makes sense

`allennlp_models.rc.common` has some utils for readers and models...and also eval scripts (but not all of them)? and the squad dataset reader?

`allennlp_models.rc.dialog_qa` has the dialogQA model, and also the QuAC dataset reader? It's weird to me that sometimes, dataset readers are in specific model directories, and other times they aren't.

not sure what makes `allennlp_models.rc.other` "other'...

`allennlp_models.rc.qanet` has the DROP reader? and the NaQANet model as well? I'd have expected these two to be in different places...also quoref eval?

My point in making the issue is that, for a given component that I'd like to use, it's hard for me to predict where it'd be. Why not just mirror the structure of the allennlp repo, and have:

```
allennlp_models.rc.data
allennlp_models.rc.models
allennlp_models.rc.common / util
allennlp_models.rc.metrics
```

etc..

instead of trying to group by "task" / "dataset", which can be a blurry and arbitrary line to draw?

**Comment by nelson-liu** [comment]
Delayed on this, but isn't this an issue for allenai/allennlp-models? I think the current structure of allennlp is fine, it's the models repo that is confusing.

**Comment by nelson-liu** [comment]
just wanted to ping on this again, since it looks like there are preparations for a 1.0 . Is this something that is planned to be folded into 1.0 of allennlp-models?

There's a lot more inertia wrt moving stuff around after an initial release, for backward-compatibility reasons...so I'd really like to see it in 1.0

I'd even be willing to volunteer to make this change, it's really _that_ important to me from a usabability standpoint.

**Comment by epwalsh** [comment]
I agree we should address this before the big one point o and I like the idea of organizing by task format

**Comment by matt-gardner** [comment]
Seems like we've got enough votes to move forward?  @nelson-liu, I'd say please go for it, and @dirkgr, let us know if you have any objections.

**Comment by nelson-liu** [comment]
Just so I know, for prioritization purposes: do you all have a particular timeline for 1.0?

**Comment by epwalsh** [comment]
@nelson-liu I don't think we have much of a timeline, it's just going to be whenever we get through the remaining issues on this milestone: https://github.com/allenai/allennlp/milestone/10

**Comment by dirkgr** [comment]
Alright, I'll change this according to @matt-gardner's suggestion above.

**Comment by dirkgr** [comment]
The PR is up at https://github.com/allenai/allennlp-models/pull/58. I put @matt-gardner and @nelson-liu on as reviewers.
