### ISSUE TITLE
Sentiment Analysis Roberta large loading error

### ISSUE THREAD

**Issue by HanXudong** [allenai/allennlp#4058]
**Describe the bug**
ConfigurationError: 'pretrained_transformer_mismatched not in acceptable choices for model.text_field_embedder.token_embedders.tokens.type: [\'embedding\', \'character_encoding\', \'elmo_token_embedder\', \'elmo_token_embedder_multilang\', \'openai_transformer_embedder\', \'bert-pretrained\', \'language_model_token_embedder\', \'bidirectional_lm_token_embedder\', \'bag_of_word_counts\', \'pass_through\', \'pretrained_transformer\']. You should either use the --include-package flag to make sure the correct module is loaded, or use a fully qualified class name in your config file like {"model": "my_module.models.MyModel"} to have it imported automatically.'

**To Reproduce**
Steps to reproduce the behavior
```python
from allennlp.predictors.predictor import Predictor
predictor = Predictor.from_path("https://storage.googleapis.com/allennlp-public-models/sst-roberta-large-2020.02.17.tar.gz")
predictor.predict(
  sentence="a very well-made, funny and entertaining picture."
)
```
**Expected behavior**
Should work.

**Comment by dirkgr** [comment]
You need to use the latest release candidate (`allennlp==1.0.0.rc1`). The models are now in the `allennlp_models` repo, so to get those you should also install `allennlp_models==1.0.0.rc1`. I don't remember which model is used by `sst-roberta-large-2020.02.17.tar.gz`, but I suspect you have to `import allennlp_models` or `import allennlp_models.sentiment` to get this to work.
