### ISSUE TITLE
"TextFields must be passed Tokens" Configuration error

### ISSUE THREAD

**Issue by elmanderx** [allenai/allennlp#4059]
System:
 - OS: OSX
 - Python version: 3-7
 - AllenNLP version:v0.9.0

Hello, I am looking to predict a text with AllenNLP and a trained SciBERT model - it compiles fine when I put:
`python -m allennlp.run predict ./scibert-master/outputdir2/model.tar.gz ./scibert-master/test.json --include-package scibert` but doesn't result in what I want since I want to use the text classifier. However when I input:
`python -m allennlp.run predict ./scibert-master/outputdir2/model.tar.gz ./scibert-master/test.json --include-package scibert --predictor text_classifier` I get the following error: 

```Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/me/Downloads/scibert-master/venv/src/allennlp/allennlp/run.py", line 21, in <module>
    run()
  File "/Users/me/Downloads/scibert-master/venv/src/allennlp/allennlp/run.py", line 18, in run
    main(prog="allennlp")
  File "/Users/me/Downloads/scibert-master/venv/src/allennlp/allennlp/commands/__init__.py", line 102, in main
    args.func(args)
  File "/Users/me/Downloads/scibert-master/venv/src/allennlp/allennlp/commands/predict.py", line 227, in _predict
    manager.run()
  File "/Users/me/Downloads/scibert-master/venv/src/allennlp/allennlp/commands/predict.py", line 206, in run
    for model_input_json, result in zip(batch_json, self._predict_json(batch_json)):
  File "/Users/me/Downloads/scibert-master/venv/src/allennlp/allennlp/commands/predict.py", line 151, in _predict_json
    results = [self._predictor.predict_json(batch_data[0])]
  File "/Users/me/Downloads/scibert-master/venv/src/allennlp/allennlp/predictors/predictor.py", line 64, in predict_json
    instance = self._json_to_instance(inputs)
  File "/Users/me/Downloads/scibert-master/venv/src/allennlp/allennlp/predictors/text_classifier.py", line 34, in _json_to_instance
    return self._dataset_reader.text_to_instance(sentence)
  File "/Users/me/Downloads/scibert-master/venv/src/allennlp/allennlp/data/dataset_readers/conll2003.py", line 130, in text_to_instance
    sequence = TextField(tokens, self._token_indexers)
  File "/Users/me/Downloads/scibert-master/venv/src/allennlp/allennlp/data/fields/text_field.py", line 46, in __init__
    "Found: {} with types {}.".format(tokens, [type(x) for x in tokens]))
allennlp.common.checks.ConfigurationError: "TextFields must be passed Tokens. Found: ['Sodium', 'bicarbonate', 'commonly', 'known', 'as', 'baking', 'soda', '(', 'mainly', 'North', 'America', ')', 'or', 'bicarbonate', 'of', 'soda', ',', 'is', 'a', 'chemical', 'compound', 'with', 'the', 'formula', 'NaHCO3'] with types [<class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>]."
2020-04-12 10:25:59,946 - INFO - allennlp.models.archival - removing temporary unarchived model dir at /var/folders/gj/h5qjt7t53cz8p6_ygh58zytr0000gq/T/tmpx7_mia63```

So it's passing list of strings, not tokens to TextField. What am I doing wrong? Excuse me if I'm missing out on something trivial. Thank you very much.

**Comment by schmmd** [comment]
@DeNeutoy any ideas?  Or could you redirect to someone that could help?

**Comment by matt-gardner** [comment]
The problem is here: https://github.com/allenai/allennlp/blob/d709e59ff3f54e137ea473d411056f68c197c266/allennlp/predictors/text_classifier.py#L38.  I'm not sure why the `str()` call is there in that line, but it should be removed.

**Comment by AkshitaB** [comment]
It appears that it is possible to have different types of inputs for the `text_to_instance()` function in dataset_readers. Some of our sample dataset_readers require tokens (eg. [conll2003](https://github.com/allenai/allennlp/blob/master/allennlp/data/dataset_readers/conll2003.py)  -- used here), some require str (eg.  [text_classification_json](https://github.com/allenai/allennlp/blob/master/allennlp/data/dataset_readers/text_classification_json.py) )and some also require lists of str/lists of lists of str etc. (eg. [babi](https://github.com/allenai/allennlp/blob/master/allennlp/data/dataset_readers/babi.py) ). And the different predictors need to make assumptions on what kind of dataset_reader is being used (as specified in DatasetReader base class [here](https://github.com/allenai/allennlp/blob/master/allennlp/data/dataset_readers/dataset_reader.py#L301)). Hence, it may not be wise to remove the str() call, as it may break for other dataset_readers. 

Ideally, if the dataset_reader has a tokenizer, I think we should not tokenize in the predictor at all but pass in the raw input as it is, and expect the dataset_reader to handle it. 

A possible solution for this specific scenario is to define a new Predictor class, which essentially does what the `TextClassiferPredictor` does, but tokenizes the input before passing it to the dataset reader’s text_to_instance function.

@matt-gardner @dirkgr

**Comment by dirkgr** [comment]
This code already only runs in the case where the reader doesn't have a tokenizer (though I am a bit horrified at [the way we detect that](https://github.com/allenai/allennlp/blob/master/allennlp/predictors/text_classifier.py#L33)).

`text_to_instance()` does not have a well-defined signature. Readers can implement it however they want (or not implement it at all). In general, readers, models, and predictors are loosely tied to each other. You can't swap out one for another in all cases, and doing so wouldn't make sense most of the time anyways (though we try our best).

I think in this case we should pass in `List[Token]`, and fix the readers that break. It's easy to go from `Token` to `str`, but it's impossible to go the other way. So if we pass in `Token`, we're on the safe side, and whatever fix required on the other side should be easy.
