### ISSUE TITLE
[ElmoEmbedder] Switching cuda device between GPU and CPU

### ISSUE THREAD

**Issue by ptynecki** [allenai/allennlp#4060]
**System:**
 - Ubuntu 18.04 x64
 - Python version: v3.6.9
 - AllenNLP version: v0.9.0
 - PyTorch version: v1.2.0

**Question**
* How can I handle cuda device parameter-value switching between GPU and CPU in _ElmoEmbedder_ class to prevent RuntimeError (CUDA out of memory)?

* I'm using _ElmoEmbedder_ class and _tensors_ for proteins vectorization which means that I have to handle different length of strings in huge amount of samples. I tried to execute it on my Titan V with 12 GB vRAM but it raised _CUDA out of memory_ exception. So, I used try-except to catch RuntimeError in the place where _embed_sentences()_ method is called and next jumped to another _ElmoEmbedder_ instance with CPU device. I hoped that trick allowed me to use both CPU and GPU devices depends on the vector size (memory requirements). But after hundreds of iterations (because of the _embedder_gpu_) it stoped working and raised the exception (stopped Python iterpreter).

```python
def flattening_proteins_to_organism_level(embedder: ElmoEmbedder, seqs: List[str], device: str) -> List[float]:
    proteins_vec: list = []
    
    for protein in embedder.embed_sentences(seqs):
        proteins_vec.append(
            torch.tensor(
                protein,
                device=device
            ).sum(dim=0).mean(dim=0).tolist()
        )

    organism_vec = torch.tensor(
        proteins_vec,
        device=device
    ).sum(dim=0).tolist()
    
    return organism_vec

(...)

embedder_gpu = ElmoEmbedder(
    options,
    weights,
    cuda_device=0
)

embedder_cpu = ElmoEmbedder(
    options,
    weights,
    cuda_device=-1
)

(...)

seqs = list(map(list, proteins.sequence.values))
seqs.sort(key=len)

try:
    organism_vec = flattening_proteins_to_organism_level(
        embedder=embedder_gpu,
        seqs=seqs,
        device='cuda:0'
    )
except RuntimeError as exc:
    # Cleaning GPU vRAM
    with torch.cuda.device(str(device)):
        torch.cuda.empty_cache()

    organism_vec = flattening_proteins_to_organism_level(
        embedder=embedder_cpu,
        seqs=seqs,
        device='cpu'
    )

(...)
```

Would you recommend me the tip how to handle it? Thanks!

**Comment by dirkgr** [comment]
We don't properly support having half your model on CPU and another half on GPU. Does it run with a batch size of `1`? You could use gradient accumulation to get bigger mathematical batches.

**Comment by ptynecki** [comment]
It was ran with batch_size=64 on _.embed_sentences()_ level.

If I cannot have half of my model on CPU and another half on GPU, may I have it on 2, 3 or 4 GPU instead? If yes, would you recommend me the tip?

**Comment by dirkgr** [comment]
AllenNLP does not support splitting the model between multiple devices, but you can split the data. So instead of using a batch size of 64 on one GPU, you can use a batch size of 16 on 4 GPUs. You will save a lot of memory that way.

**Comment by ptynecki** [comment]
@dirkgr 

Got it.

Is it mean that I have to prepare 4 instances of _ElmoEmbedder_ with _cuda_device_=0, 1, 2 and 4, split the input data into 4 chunks and then launch _.embed_sentences()_ with batch_size=4 of each of those instances?

Or there is a better way to handle it? Thanks!

**Comment by dirkgr** [comment]
I just realized that you are not running training, just inference. Then this is easier. Just do inference on one sentence at a time! So in your case, call `flattening_proteins_to_organism_level()` with sequences of length 1. Try it with larger lengths until you run out of memory.

The other thing is, turn off auto gradients. You don't need to calculate gradients if you are just doing inference. You can wrap the whole thing in a `with torch.no_grad():` block. That will save a bunch of memory.

Different question though: What are those strings? If they are protein sequences, why do you think they would produce meaningful output when passed through ELMo?
