### ISSUE TITLE
Update website to report training variance

### ISSUE THREAD

**Issue by matt-gardner** [allenai/allennlp#407]
We've known we should do this for a while now - just making an issue for it so it's in a tracker.

We will keep getting people confused about why their training run doesn't match our models' numbers until we have some discussion of this on the website where we report performance numbers.  Even though anyone who's trained a neural net knows how finicky they are, they often don't make the connection that the finickiness is often due just to training variance, and that a reference implementation of someone else's model will _also_ be finicky.  [Here's](https://github.com/allenai/allennlp/issues/379#issuecomment-336718417) some text that should be a good starting place for something to put on the website.

**Comment by matt-gardner** [comment]
#387 is related, actually.  We _did_ have an issue that is at least similar.  Though #387 is slightly different - that issue explains why you can't get the same result even with the same CPU/GPU architecture and random seed, while what I'm talking about here is a broader issue about training variance in general.

**Comment by schmmd** [comment]
I can take a stab at this.  However, we'll certainly continue getting people confused despite the disclaimer--it's confusing!

**Comment by schmmd** [comment]
https://github.com/allenai/allennlp-website/pull/7
