### ISSUE TITLE
Is there a way to reduce the size of Bert based models

### ISSUE THREAD

**Issue by datix-vishu** [allenai/allennlp#4076]
I'm using both coref and SRL Bert models. The coref model is 1.3GB in size and once I run the code for run the coref model, some other files are downloaded of size 645MB from HuggingFace. Now I have to load 1.4GB + 645MB to the memory. Is there a way to reduce this size ?

**Comment by ZhaofengWu** [comment]
The referenced sizes sound reasonable to me. If they're too big for your hardware, you can always try using a smaller pretrained transformer (e.g. albert), fp16, etc., but you'd have to train your own model.
