### ISSUE TITLE
Run model tests on core PRs

### ISSUE THREAD

**Issue by dirkgr** [allenai/allennlp#4080]
Now that all the models live in https://github.com/allenai/allennlp-models, we need to set up something that runs those tests with new versions of the core library.

**Comment by dirkgr** [comment]
This might be subsumed by #4096.

**Comment by epwalsh** [comment]
Do we want to just always test the models as part of the usual CI?

**Comment by dirkgr** [comment]
Yes, as part of every PR. Hopefully in parallel :-)
