### ISSUE TITLE
Remove the `elmo` command

### ISSUE THREAD

**Issue by dirkgr** [allenai/allennlp#4086]
We don't think anyone uses the `allennlp elmo` command anymore. Speak up if we are wrong!

**Comment by wj-Mcat** [comment]
agree

**Comment by snath99920** [comment]
I see that this issue was taken up and the elmo module was removed in v1.1.0. Can someone please tell me which version of allennlp would support elmo?

**Comment by dirkgr** [comment]
Nothing like removing a command to find someone who is still using it 😟.

I think the best version for using that command is still 0.9.

ELMo itself is still around in `allennlp-models` though!

**Comment by snath99920** [comment]
Haha. It's actually an implementation of a research paper published a couple years back. Just wanted to see the results there. Never mind though, found Elmo in allennlp-models like you mentioned @dirkgr :D
