### ISSUE TITLE
Example of seq2seq model?

### ISSUE THREAD

**Issue by EgorLakomkin** [allenai/allennlp#409]
Hi!

I am trying to make a simple seq2seq model, but have difficulty to start. I came up with something like this:
`   

    dataset_reader = Seq2SeqDatasetReader()
    dataset = dataset_reader.read("./data/train_small.tsv")

    vocab = Vocabulary.from_dataset(dataset)
    dataset.index_instances(vocab)
    iterator = BasicIterator()

    word_embedding = Embedding(num_embeddings=vocab.get_vocab_size("tokens"), 
                                                                                                       embedding_dim = 10)
    text_field_embedder = BasicTextFieldEmbedder({"tokens": word_embedding})

    gru_encoder = nn.GRU(input_size=10, hidden_size=64, batch_first=True)
    encoder = PytorchSeq2SeqWrapper(module = gru_encoder)
    seq_to_seq = SimpleSeq2Seq(vocab=vocab, source_embedder=text_field_embedder,
                               encoder=encoder, max_decoding_steps = 20)
    for s in iterator(dataset = dataset, num_epochs = 10, shuffle = True):
        res = seq_to_seq(source_tokens=s["source_tokens"], target_tokens=s["target_tokens"])`

But what I get an error:
`if original_inputs.dim() > 2:
AttributeError: 'numpy.ndarray' object has no attribute 'dim'`

I guess I am doing something wrong, but cannot figure it out. Is there any tutorial/code sample of something similar? Thank you in advance.

**Comment by matt-gardner** [comment]
Is there a reason you don't just want to use our `Trainer`?  You _should_ be able to get this to work just by creating a configuration file with your dataset and model specifications and following the [training](http://allennlp.org/tutorials/training-and-evaluating) and [configuration file](http://allennlp.org/tutorials/configuration) tutorials.  There's even a configuration file that's pretty close to what you would need checked into the test fixtures: https://github.com/allenai/allennlp/blob/master/tests/fixtures/encoder_decoder/simple_seq2seq/experiment_with_attention.json.

**Comment by matt-gardner** [comment]
If you _do_ want to write your own instantiation code and training loop, for whatever reason, it looks like the step you're missing is calling `allennlp.nn.util.arrays_to_variables` on the result from `iterator` (what you've called `s`).  If you get more errors after that, you can look at what our [training code](https://github.com/allenai/allennlp/blob/d03e87b7b7297821d384a0b129268e6ca4d8e679/allennlp/commands/train.py#L85-L167) [does](https://github.com/allenai/allennlp/blob/d03e87b7b7297821d384a0b129268e6ca4d8e679/allennlp/training/trainer.py#L358-L395) to find other things you're missing.

**Comment by EgorLakomkin** [comment]
Thank you @matt-gardner, arrays_to_variables is that what I needed exactly. Thank you for your help and a great library!
