### ISSUE TITLE
Pytorch remote acces while running BERT base SRL via Predictors

### ISSUE THREAD

**Issue by DebayanChakraborty** [allenai/allennlp#4092]
**System (please complete the following information):**
 - OS: [e.g. Linux]
 - Python version: [e.g. 3.6.8]
 - AllenNLP version: [e.g. 0.9.0]

**Question**
I Am running the SRL model locally . However, there is a pytorch process which downloads associated bert models from amazon s3.  I got the required files on
 local, however i can still see the pytorch accessing the remote https . I do not want it to do that because the functionality i am building might have to work standalone without network access. 

I tried allennlp loading methods but all of them invariably make the pytorch call to remote AWS. Can you guide me where i am going wrong in the matter . I have all required files locally and just think the remote access is not required. 

The log is 
`
15:35:08.989 INFO     pytorch_pretrained_bert.modeling:580 loading archive file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased.tar.gz from cache at /<home path>/.pytorch_pretrained_bert/<shaencodedhexafilename>
15:35:08.992 INFO     pytorch_pretrained_bert.modeling:588 extracting archive file /<homepath>/.pytorch_pretrained_bert/<shaencodedhexafilename> to temp dir  <temp loc>
`

**Comment by schmmd** [comment]
@DebayanChakraborty all you need to do is copy the model locally and refer to it that way, rather than with an http:// path.

Or possibly the SRL model has remote references in it's configuration and you'll need to untar it, covert those to local paths, and then re-tar it.

**Comment by DebayanChakraborty** [comment]
@schmmd  that was really helpful . On opening up the tar file i caught the actual redirection to the s3 server. I changed that and made update on pytorch config also and got what i wanted. The program has stopped making remote calls and is now loading from local models. 

Thanks .
