### ISSUE TITLE
Fine-Grained NER model in the demo performs better than local deployment !

### ISSUE THREAD

**Issue by datix-vishu** [allenai/allennlp#4093]
@dirkgr  For some text inputs the NER demo is identifying additional entities than the local deployment. I'm only getting the same result if I run the fine-grained NER model twice on the text input. Why is this happening ?

**Comment by dirkgr** [comment]
I the NER model using ELMo? If so, ELMo benefits from being warmed up, and the demo is likely always warmed up because of other people running inference.

In your own code, you can just run some text through it during startup. This is an unfortunate characteristic of ELMo.
