### ISSUE TITLE
Set up self hosted GitHub Actions runner in GCP for GPU tests

### ISSUE THREAD

**Issue by epwalsh** [allenai/allennlp#4108]

**Comment by epwalsh** [comment]
Note: we shouldn't use the self-hosted runner for pull requests: https://help.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners#self-hosted-runner-security-with-public-repositories

**Comment by chrisroat** [comment]
> ~Note: we shouldn't use the self-hosted runner for pull requests: https://help.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners#self-hosted-runner-security-with-public-repositories~

I was just passing by and interested what you ended up doing here.  I see the strike-out and the later merge to setup a self-hosted runner.  Did you mitigate the issues raised in the link?

**Comment by epwalsh** [comment]
There are still some security issues, but the worst someone could do is disable/corrupt our cloud machine that the runner is on. This would be annoying but not catastrophic.
