### ISSUE TITLE
Clean up scripts folder

### ISSUE THREAD

**Issue by epwalsh** [allenai/allennlp#4115]
Since the CI steps are now in the Makefile we shouldn't need `scripts/verify.py` and some other stuff in that folder.

**Comment by matt-gardner** [comment]
I use `./scripts/flake8.sh` and `./scripts/mypy.sh` for running checks during local development.  Those both call out to `verify.py`.  Looks like the flake8 one is trivial, but the mypy invocation there has a lot of stuff that I wouldn't want to lose.  Doesn't bother me one way or the other whether the script delegates to `verify.py` or not, though.

**Comment by epwalsh** [comment]
@matt-gardner you can run flake8 and mypy with [`make lint`](https://github.com/allenai/allennlp/blob/master/Makefile#L33) and [`make typecheck`](https://github.com/allenai/allennlp/blob/master/Makefile#L38) now

**Comment by matt-gardner** [comment]
Ok, thanks, that should be enough then.  I just need to change my reflexes =).
