### ISSUE TITLE
Add missing docstrings for all models, functions

### ISSUE THREAD

**Issue by matt-gardner** [allenai/allennlp#413]
We pretty frequently forget to add things to the docs in our PRs.  I know there are plenty that are currently missing.  It'd be nice if someone could go through this and add things to the docs where they are missing.

**Comment by matt-gardner** [comment]
Actually, Joel's PR a while ago kind of solved this.  The original intent was to make sure that the `doc/` directory actually reflected what was in the code.  Joel made it so that CI checks this.  Had I remembered this issue, I would have closed it when that PR got merged.

**Comment by schmmd** [comment]
@joelgrus would you close this if you think it's addressed?
