### ISSUE TITLE
Cache models and other stuff in CI

### ISSUE THREAD

**Issue by epwalsh** [allenai/allennlp#4132]
Caching `~/.allennlp` and `~/.cache/torch/transformers` might lead to speed ups

**Comment by epwalsh** [comment]
Then again... it probably won't help much since the cache has to be downloaded on each run anyway. So either way you're downloading the same content. Plus we have limited cache available (5 GB I believe). So this might be a big waste of space.

**Comment by dirkgr** [comment]
I'm pretty sure filling the cache is faster than other downloads. Otherwise pip caching wouldn't work either.

**Comment by epwalsh** [comment]
@dirkgr instead of pip caching we are actually caching the entire Python virtual environment

**Comment by dirkgr** [comment]
We'll revisit once it solves a problem we actually have.
