### ISSUE TITLE
Load archive: Multiple models

### ISSUE THREAD

**Issue by sb1992** [allenai/allennlp#4135]
How do I load 2 different trained models with load archive. As I understand as soon as I load the second model from load_archive it overwrites the first model, ( I think it creates one temporary directory and hence replaces it). Some snippets of what am doing 

`archive1 = load_archive(args.archive_path1, cuda_device=args.cuda_device)`
`archive2 = load_archive(args.archive_path2, cuda_device=args.cuda_device)`
`predictor1 = Predictor.from_archive(archive1, args.predictor1)`
`predictor2 = Predictor.from_archive(archive2, args.predictor2)`
`app = make_app(predictor1 = predictor1, predictor2=predictor2)`

In app this function is called and i feel it uses archive2 instead of archive1
`prediction = predictor1.predict_json(data)`

I am creating a flask app and want 2 different models to be loaded in memory and used at different points depending on the some if clauses. Even though the predictor1  is loaded I think it does not use the right archive model. Any way around this?

**Comment by dirkgr** [comment]
Why do you think it doesn't use the right model? Can you make sure?

I can't think of any reason why this should not work. The demo at https://github.com/allenai/allennlp-demo does this all the time.

**Comment by sb1992** [comment]
Well have been trying it without the demo code, but i still think you can't run both in one single request. So say for the same data point i want it to give me the result from 2 models. Maybe in a separate new request from a client side, it might be able to use multiple models. That is what i think, correct me if am wrong.

**Comment by matt-gardner** [comment]
Can you just confirm that this gives you different output?

```python
archive1 = load_archive(args.archive_path1, cuda_device=args.cuda_device)
archive2 = load_archive(args.archive_path2, cuda_device=args.cuda_device)
predictor1 = Predictor.from_archive(archive1, args.predictor1)
predictor2 = Predictor.from_archive(archive2, args.predictor2)
inputs = {"some": "json", "for": "whatever your model is"}
prediction1 = predictor1.predict_json(inputs)
prediction2 = predictor2.predict_json(inputs)
print(prediction1)
print(prediction2)
```

If your underlying models are actually different, this code should definitely give you different results for the two models.  If it doesn't, there's a bug in allennlp somewhere.  But given that this is pretty much exactly how our demo works, and it does work this way, I'm really skeptical that there's a problem on our end here.

**Comment by sb1992** [comment]
Yes it does not work correctly. I have 2 different classification models trained on different categories. You could think the use case in a way in a broader the second model should only be called if the first one meets certain conditions. Anyhow

Case 1:
```for package_name in args.include_package:```
                ```import_submodules(package_name)```
```archive1 = load_archive(args.archive_path1, cuda_device=args.cuda_device)```
```archive2 = load_archive(args.archive_path2, cuda_device=args.cuda_device)```
```predictor1 = Predictor.from_archive(archive1, args.predictor1)```
```predictor2 = Predictor.from_archive(archive2, args.predictor2)```
```inputs = {'text': 'maths lot harder maths . however, planning take maths uni worth slogging significant part first year maths degree often covered maths level .'}```
```prediction1 = predictor1.predict_json(inputs)```
```prediction2 = predictor2.predict_json(inputs)```
```print (prediction1)```
```print( prediction2)```

Output:
prediction1 : Label1  - Jurisdiction , label2- tax        ---- (This is wrong for first model)
prediction2: Label1 - Curriculum, label2 -grades ------( This is right for the second model) 

Case 2: I just switched the order of loading of archive models

```for package_name in args.include_package:```
                ``` import_submodules(package_name)```
```archive2 = load_archive(args.archive_path2, cuda_device=args.cuda_device)```
```archive1 = load_archive(args.archive_path1, cuda_device=args.cuda_device)```
```predictor1 = Predictor.from_archive(archive1, args.predictor1)```
```predictor2 = Predictor.from_archive(archive2, args.predictor2)```
```inputs = {'text': 'maths lot harder maths . however, planning take maths uni worth slogging significant part first year maths degree often covered maths level .'}```
```prediction1 = predictor1.predict_json(inputs)```
```prediction2 = predictor2.predict_json(inputs)```
```print(prediction1)```
```print(prediction2)```

Outputs:
Prediction1 : label1 education system, label2: schooling     --- (This is right for first model)
prediction2: Label1 - Families and schools, label2 -behaviour------( This is wrong for the second model) 

As you can make out what is going on the predictor somehow always uses the model which is loaded second. It still gives a result as it is still a similar architecture broadly being a classification model. I went through the code of archival.py in the source code, what i feel is happening is it overwriting the previously loaded model in the temporary directory and it stays in memory. ( I could be totally wrong but that is my intuition) .
Ofcourse you could make a prediction and then load the next model but that is not the way i want to go forward as i want the models to be already loaded in memory and have quick predictions.
Note: I am using 0.9 which is the old version as I don't want to make changes in my code just yet but I don't see any reason why this would not be a problem in the latest commit.

**Comment by matt-gardner** [comment]
How about just `print(archive1 == archive2)` after the first two lines?  Wouldn't that tell whether or not your suspicion is correct?

**Comment by matt-gardner** [comment]
Essentially, you've got a few easy ways to tell for sure whether or not the models underlying each of those predictors are the same or not - just compare their weights.  It's pretty hard for us to diagnose this, because don't have your setup, but if you can confirm that this is a problem, and make a minimal test case for us, we'd have a much easier time finding and fixing the underlying issue.
