### ISSUE TITLE
[Question] Is it normal to obtain different results for different batch size at inference time ?

### ISSUE THREAD

**Issue by c4n** [allenai/allennlp#4136]
**Question**
* I'm working on a sequential tagging task and I found that training_util.evaluate gives different outcome for different batchsize. For example,

result_1 = training_util.evaluate(baseline_model,DataLoader(test_dataset, batch_size=1), cuda_device, None )
result_64 = training_util.evaluate(baseline_model, DataLoader(test_dataset, batch_size=64), cuda_device, None ) 

result from batch_size =1 is not equal to result from batch_size = 64

**Comment by dirkgr** [comment]
How far apart are they, and what is the model you are using?

**Comment by c4n** [comment]
> How far apart are they, and what is the model you are using?

they are pretty close.  I was using this model https://github.com/allenai/allennlp/blob/v0.9.0-3971/training_config/ner_elmo.jsonnet .

**Comment by dirkgr** [comment]
ELMo is not deterministic. It will give a slightly different answer every time you run it. It has nothing to do with the batch size (or at least, that's not the source of the problem).

For ELMo, the recommendation is to warm it up with a few sentences before doing any real inference.
