### ISSUE TITLE
Make sure links in the docs are rendering correctly

### ISSUE THREAD

**Issue by matt-gardner** [allenai/allennlp#414]
We use things like ` :class:``~allennlp.models.bidaf.BidirectionalAttentionFlow`` ` all over the place in our docstrings, and I believe some of them aren't rendering correctly.  It'd be nice if someone could go over our docs and make sure things are rendering correctly, and fix broken links or other problems where they exist.

**Comment by schmmd** [comment]
Closing this as it's been open for months and we don't have examples.  Please re-open with an example, if wanted.
