### ISSUE TITLE
allennlp==1.0.0rc2 reports wrong version

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp#4141]
We will want to fix this for RC3.

```
$ allennlp --version
allennlp 1.0.0-unreleased
```

**Comment by schmmd** [comment]
@epwalsh shouldn't the AllenNLP dependency be pinned in the RC2 release for `allennlp-models` too?  https://github.com/allenai/allennlp-models/blob/9d4605a2411e5bae6b473178b70e7c419ae51eb9/requirements.txt#L1

**Comment by epwalsh** [comment]
@schmmd it is actually if you look at the `setup.py` for models

**Comment by epwalsh** [comment]
I knew there would be a mismatch with the output of `allennlp --version`. I think the only way to ensure consistency is to hard code the exact version

**Comment by epwalsh** [comment]
^ Which is fine by me

**Comment by schmmd** [comment]
Yeah, so we might need some more manual steps to set the version before releasing.

**Comment by epwalsh** [comment]
Darn! They're going to take back my award!
