### ISSUE TITLE
How to freeze pretrained_transformer weights during training

### ISSUE THREAD

**Issue by mojesty** [allenai/allennlp#4147]
**System (please complete the following information):**
 - OS: Linux
 - Python version: 3.7
 - AllenNLP version:  "I installed from master"
 - PyTorch version: 1.5.0

**Question**
In older version of AllenNLP, there existed `PretrainedBertEmbedder` that has `requires_grad` argument in its constructor. But with master version, where we have only `PretrainedTransformerEmbedder`, there seems to be no such parameter. I can figure out default behavior somewhere in `transformers` library, but I think this functionality is better to be returned to avoid confusion.
So my question is -- where exactly can I control trainable/non-trainable transformers embedders

**Comment by epwalsh** [comment]
Hi @mojesty, I think this would be good to have. Would you consider making a PR?

**Comment by dirkgr** [comment]
We could possibly support a `requires_grad` parameter on all embedders with little extra code?

**Comment by matt-gardner** [comment]
I mean, if you want to add it to the super class and make all of the embedders take and pass `**kwargs`, yes, this is pretty trivial.  Not sure it's useful for anything other than pretrained embedders, though.

**Comment by dirkgr** [comment]
It might be a little late now, but you could have used this for a great series of probing studies of the form "What does X know?", for X in `[glove, elmo, bert, roberta]`? There might be other cases we wouldn't think of until they are obvious.

**Comment by mateuszpieniak** [comment]
As far as I know, you can always use `no_grad` regex from `Trainer` to freeze the layers you are interested in.
