### ISSUE TITLE
Out of vocabulary label results in an error in predictor

### ISSUE THREAD

**Issue by RudrakshTuwani** [allenai/allennlp#4149]
I am working on a multilabel classification problem wherein there are some labels in the test set which are not there in the training set.

I write a common reader for both training and test dataset, using the namespace 'dsummary' and 'icd9_labels'. The Vocabulary is subsequently constructed from only the training instances. Everything works fine and the model gets trained. Now, to get predictions from the model, I first obtain test set instances using the reader (same as before). Then I use the base Predictor from the library and pass in my model and vocabulary while instantiating it. I get the following error when I try to use the predict_batch_instance function. The error only arises if there are instances which contain labels not present in the training set.

```python
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-127-3077fac5391f> in <module>
----> 1 preds = p.predict_batch_instance(test_dataset[:100])

/anaconda/envs/py37_pytorch/lib/python3.7/site-packages/allennlp/predictors/predictor.py in predict_batch_instance(self, instances)
    210 
    211     def predict_batch_instance(self, instances: List[Instance]) -> List[JsonDict]:
--> 212         outputs = self._model.forward_on_instances(instances)
    213         return sanitize(outputs)
    214 

/anaconda/envs/py37_pytorch/lib/python3.7/site-packages/allennlp/models/model.py in forward_on_instances(self, instances)
    149             cuda_device = self._get_prediction_device()
    150             dataset = Batch(instances)
--> 151             dataset.index_instances(self.vocab)
    152             model_input = util.move_to_device(dataset.as_tensor_dict(), cuda_device)
    153             outputs = self.decode(self(**model_input))

/anaconda/envs/py37_pytorch/lib/python3.7/site-packages/allennlp/data/dataset.py in index_instances(self, vocab)
    153     def index_instances(self, vocab: Vocabulary) -> None:
    154         for instance in self.instances:
--> 155             instance.index_fields(vocab)
    156 
    157     def print_statistics(self) -> None:

/anaconda/envs/py37_pytorch/lib/python3.7/site-packages/allennlp/data/instance.py in index_fields(self, vocab)
     70             self.indexed = True
     71             for field in self.fields.values():
---> 72                 field.index(vocab)
     73 
     74     def get_padding_lengths(self) -> Dict[str, Dict[str, int]]:

/anaconda/envs/py37_pytorch/lib/python3.7/site-packages/allennlp/data/fields/multilabel_field.py in index(self, vocab)
     98         if self._label_ids is None:
     99             self._label_ids = [vocab.get_token_index(label, self._label_namespace)  # type: ignore
--> 100                                for label in self.labels]
    101         if not self._num_labels:
    102             self._num_labels = vocab.get_vocab_size(self._label_namespace)

/anaconda/envs/py37_pytorch/lib/python3.7/site-packages/allennlp/data/fields/multilabel_field.py in <listcomp>(.0)
     98         if self._label_ids is None:
     99             self._label_ids = [vocab.get_token_index(label, self._label_namespace)  # type: ignore
--> 100                                for label in self.labels]
    101         if not self._num_labels:
    102             self._num_labels = vocab.get_vocab_size(self._label_namespace)

/anaconda/envs/py37_pytorch/lib/python3.7/site-packages/allennlp/data/vocabulary.py in get_token_index(self, token, namespace)
    635         else:
    636             try:
--> 637                 return self._token_to_index[namespace][self._oov_token]
    638             except KeyError:
    639                 logger.error('Namespace: %s', namespace)

KeyError: '@@UNKNOWN@@'
```

**Comment by epwalsh** [comment]
Hi @RudrakshTuwani, what's the behavior that you expect here?

**Comment by RudrakshTuwani** [comment]
Hi @epwalsh 

I guess the ideal behavior would be problem specific. For me, it would be great to receive a warning about this and that labels outside the vocabulary are ignored. 

Thanks!

**Comment by epwalsh** [comment]
@RudrakshTuwani I'm a little worried about ignoring OOV labels. What would happen if an example had a single label which was OOV?

But I agree we need to improve how this situation is handled. The current behavior of silently changing OOV labels to the UNK token (`@@UNKNOWN@@`) when the UNK token doesn't exist in the vocab namespace is bad.

At the very least we should throw an error as soon as an OOV token is encountered if the UNK token is not part of the vocab. Does that sound reasonable?

**Comment by RudrakshTuwani** [comment]
That's true, I didn't think of that. 

I guess then it would make sense to throw an error message. Probably the user can also be informed as to the best way of resolving this. In my case, I just specified all possible labels using the tokens_to_add argument while creating the vocab object.

**Comment by epwalsh** [comment]
If you're interested in making a PR for this feel free to go ahead. Otherwise I might be able to get to it later this week.

**Comment by epwalsh** [comment]
Hey @RudrakshTuwani did you get a chance to start on this? If not I can give it a go
