### ISSUE TITLE
What version of AllenNLP does the models repo use?

### ISSUE THREAD

**Issue by nelson-liu** [allenai/allennlp#4155]
The `requirements.txt` and `setup.py` don't seem to specify.

If it's too early to be installing the models repo (I just want to run the tests, I think I found a bug but it might be due to version mismatch issues), let me know.

**Comment by epwalsh** [comment]
Hey @nelson-liu we should definitely document this but if you look in the setup.py file, it checks for an env flag “EXCLUDE_ALLENNLP_IN_SETUP”. This can be used to install locally alongside any version of allennlp. Otherwise allennlp is pinned to whatever version models is.
