### ISSUE TITLE
Wrong argument order in evaluate command

### ISSUE THREAD

**Issue by successar** [allenai/allennlp#4198]
In the evaluate command, https://github.com/allenai/allennlp/blob/967660a477c04d83be748f5bb8b0b9d862b85fc1/allennlp/commands/evaluate.py#L146 , we pass in arguments using position 

```python
load_archive(args.archive_file, args.cuda_device, args.overrides, args.weights_file)
```

while load_archive function takes different arguments now - https://github.com/allenai/allennlp/blob/967660a477c04d83be748f5bb8b0b9d862b85fc1/allennlp/models/archival.py#L130

```python
def load_archive(
    archive_file: str,
    cuda_device: int = -1,
    opt_level: str = None,
    overrides: str = "",
    weights_file: str = None,
) -> Archive:
```
Thus, overrides gets passed as opt_level .

**Comment by matt-gardner** [comment]
Ack, good catch.  Care to submit a PR to fix this?

**Comment by successar** [comment]
Working on a pull request.
