### ISSUE TITLE
Serve the demo using the new architecture

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp#4200]
I think we should do this before 1.0 to clearly account for which models in the demo we can run on 1.0.  Hopefully we can run them all...

See https://github.com/allenai/reviz/issues/61.

**Comment by schmmd** [comment]
@epwalsh I think we should be sure to wrap this up before releasing 1.0.  It seems like we're close, and most of what's remaining will be a good test for RC3.

**Comment by epwalsh** [comment]
@schmmd agreed, seems like we’ll be done by the end of the week

**Comment by schmmd** [comment]
@epwalsh I think we can close this out?  Feel free to summarize the tasks that remain if you see some.

**Comment by epwalsh** [comment]
Yeup, I think we can close!
