### ISSUE TITLE
get_spacy_model fails downloading models named in a simple way

### ISSUE THREAD

**Issue by frascuchon** [allenai/allennlp#4201]
**Describe the bug**
`get_spacy_model` method fails downloading models with already linked names (like `en`, `de`)

The model is properly downloaded and linked but method `get_package_path` fails since expected a fully model name (`en_core_web_sm`)

**To Reproduce**
Steps to reproduce the behavior
1. `pip uninstall spacy`
2. `pip install spacy`
3. Test method with a simple model `en`: 
```python
get_spacy_model("en")
```

**Expected behavior**
Properly download an load the models like `get_spacy_model("en_core_web_sm")` does

**System (please complete the following information):**
 - OS: OSX
 - Python version: 3.7.6
 - AllenNLP version: 0.9.0
 - PyTorch version:  1.4.0

**Comment by matt-gardner** [comment]
`get_package_path` isn't in our code, right?  I'm not sure that this will have an easy solution, and there's a really simple workaround - just use the fully-qualified name, instead of the short one.  Unless I'm missing something, I don't think this is an issue we're likely to fix.  If there's something easy that allennlp could do to make this work, a PR is welcome, but if it requires something complicated, it's probably not worth the complexity to fix this.

**Comment by matt-gardner** [comment]
Closing, but feel free to keeping commenting if you have more to say.

**Comment by frascuchon** [comment]
Hi @matt-gardner 

Thanks for your response and sorry for the delay in mine. 

I've done some tests and it would be as simple as using the spacy cli to try to download the model (whether it is with a short name or a long name)

```python
import spacy
lang = "en"

try:
    spacy.load(lang, disable=["vectors", "textcat", "tagger" "parser" "ner"])
except OSError:
    spacy.cli.download(lang)

```

**Comment by matt-gardner** [comment]
I'm a bit confused, because I think that's exactly what we do: https://github.com/allenai/allennlp/blob/master/allennlp/common/util.py#L271-L277. What are you suggesting we change in allennlp for this?

**Comment by frascuchon** [comment]
Is there a release version including this change? I was using last release version 0.9.0 where is not yet included. Thanks

**Comment by matt-gardner** [comment]
The latest release is 1.0.0rc4, which was just released yesterday.

**Comment by frascuchon** [comment]
Ok thanks, I will wait this change in the next stable release version.

**Comment by frascuchon** [comment]
> I'm a bit confused, because I think that's exactly what we do:
> 
> https://github.com/allenai/allennlp/blob/1b0d231dc7e6b6210d6bc0368d54dbe4989763ec/allennlp/common/util.py#L271-L277
> 
> What are you suggesting we change in allennlp for this?

Just a brief comment about your implementation. What you do after `spacy_download` still failing when passing a shortcut name

You try to load model names as python module
```python
spacy_model_module = __import__(spacy_model_name)
```
and this only works for full named models.

You could load the model after download it in the same way that you do before, since spacy cli automatically links the model name with the shortcut version.

````python
try:
    spacy_model = spacy.load(spacy_model_name, disable=disable)
except OSError:
    logger.warning(
        f"Spacy models '{spacy_model_name}' not found.  Downloading and installing."
    )
    spacy_download(spacy_model_name)
    spacy_model = spacy.load(spacy_model_name, disable=disable)
````

**Comment by matt-gardner** [comment]
Ah, good point.  PR to fix this welcome!
