### ISSUE TITLE
Outdated constituency parser model and its demo

### ISSUE THREAD

**Issue by p-skaisgiris** [allenai/allennlp#4219]
This error is produced when trying to run this example https://demo.allennlp.org/constituency-parsing. Similar issues have been [reported before](https://github.com/allenai/allennlp/issues/2276)  and it seems like the model has been outdated.

```
Traceback (most recent call last):
  File "/home/.../project/src/split_sentences_to_clauses.py", line 17, in <module>
    predictor = Predictor.from_path("https://storage.googleapis.com/allennlp-public-models/elmo-constituency-parser-2020.02.10.tar.gz")
  File "/home/.../venv/lib/python3.8/site-packages/allennlp/predictors/predictor.py", line 256, in from_path
    return Predictor.from_archive(load_archive(archive_path, cuda_device=cuda_device), predictor_name,
  File "/home/.../venv/lib/python3.8/site-packages/allennlp/models/archival.py", line 227, in load_archive
    model = Model.load(config.duplicate(),
  File "/home/.../venv/lib/python3.8/site-packages/allennlp/models/model.py", line 327, in load
    return cls.by_name(model_type)._load(config, serialization_dir, weights_file, cuda_device)
  File "/home/.../venv/lib/python3.8/site-packages/allennlp/models/model.py", line 265, in _load
    model = Model.from_params(vocab=vocab, params=model_params)
  File "/home/.../venv/lib/python3.8/site-packages/allennlp/common/from_params.py", line 365, in from_params
    return subclass.from_params(params=params, **extras)
  File "/home/.../venv/lib/python3.8/site-packages/allennlp/common/from_params.py", line 386, in from_params
    kwargs = create_kwargs(cls, params, **extras)
  File "/home/.../venv/lib/python3.8/site-packages/allennlp/common/from_params.py", line 133, in create_kwargs
    kwargs[name] = construct_arg(cls, name, annotation, param.default, params, **extras)
  File "/home/.../venv/lib/python3.8/site-packages/allennlp/common/from_params.py", line 229, in construct_arg
    return annotation.from_params(params=subparams, **subextras)
  File "/home/.../venv/lib/python3.8/site-packages/allennlp/common/from_params.py", line 365, in from_params
    return subclass.from_params(params=params, **extras)
  File "/home/.../venv/lib/python3.8/site-packages/allennlp/modules/text_field_embedders/basic_text_field_embedder.py", line 170, in from_params
    params.assert_empty(cls.__name__)
  File "/home/.../venv/lib/python3.8/site-packages/allennlp/common/params.py", line 433, in assert_empty
    raise ConfigurationError("Extra parameters passed to {}: {}".format(class_name, self.params))
allennlp.common.checks.ConfigurationError: "Extra parameters passed to BasicTextFieldEmbedder: {'elmo': {'options_file': '/tmp/tmpfymzf5pr/fta/model.text_field_embedder.elmo.options_file', 'weight_file': '/tmp/tmpfymzf5pr/fta/model.text_field_embedder.elmo.weight_file'}}"
```

**Comment by matt-gardner** [comment]
Yes, that's definitely an error due to an old configuration file.  I thought we had updated all of our models, but it looks like this one hasn't been, because I see the same model file in the demo configuration: https://github.com/allenai/allennlp-demo/blob/f9dc7756c336a9495d26140f1d0797fe23933125/api/allennlp_demo/constituency_parser/model.json#L3.  Thanks for reporting this!

I don't know how the demo for this is currently running, unless it hasn't actually been updated in a long time.  From the error pasted above, it looks like this model should definitely be failing tests. 
 @epwalsh, do you know, or do you know who this should be redirected to if it's not you?  I'm not sure who is doing what with the demo at this point.

**Comment by matt-gardner** [comment]
@p-skaisgiris, if you want to get that model running now, you can just modify the config file inside the model archive, and it should work.  See the second bullet point under "config file changes" [here](https://github.com/allenai/allennlp/releases/tag/v1.0.0.rc1), and feel free to ask questions if you get stuck somewhere.

**Comment by p-skaisgiris** [comment]
@matt-gardner I'm not quite sure what to change there to be honest, the config file already seems to be in the format to which the link you sent refers to. That is, the config already has the `"token_embedders"` wrapper:
```
"model": {
        "type": "constituency_parser",
        "text_field_embedder": {
            "token_embedders": {
              "elmo": {
                  "type": "elmo_token_embedder",
                  "dropout": 0.2,
                  "options_file": "https://allennlp.s3.amazonaws.com/models/elmo/2x4096_512_2048cnn_2xhighway/elmo_2x4096_512_2048cnn_2xhighway_options.json",
                  "weight_file": "https://allennlp.s3.amazonaws.com/models/elmo/2x4096_512_2048cnn_2xhighway/elmo_2x4096_512_2048cnn_2xhighway_weights.hdf5",
                  "do_layer_norm": false
              }
            }
        },
       ...
```

**Comment by matt-gardner** [comment]
Oh, hmm, looks like I was wrong on the error.  But when I download that model and run it with current code, I don't get any error.  What version of allennlp are you using?

**Comment by p-skaisgiris** [comment]
PyCharm showed that I had `1.0.0rc3 ` of both `allennlp` and `allennlp-models`. But probably something didn't go through properly in the installation as it was raising this issue. After a clean installation of both, the model indeed worked. Thanks for the swift responses!
