### ISSUE TITLE
AllenNLP demo site Co-reference Resolution not working for long text !

### ISSUE THREAD

**Issue by datix-vishu** [allenai/allennlp#4223]
This text may contain 1000+ sentences.

![image](https://user-images.githubusercontent.com/51480660/81648231-fd383a00-944b-11ea-9995-1b9fe9f03e82.png)

**Comment by ZhaofengWu** [comment]
The demo limits request lengths to ensure better experiences for all users. You can download the model and code and do the inference locally.

**Comment by schmmd** [comment]
Yes, you'll need to run AllenNLP locally.  Look at the information in the "Usage" tab of your screenshot.

**Comment by datix-vishu** [comment]
@ZhaofengWu @schmmd Actually I tried the same text in my local system with 12GB RAM and it crashed.

**Comment by ZhaofengWu** [comment]
See #4231

**Comment by datix-vishu** [comment]
@ZhaofengWu I appreciate all those answers, but the thing I really find annoying is that the memory memory required gradually increases. 

Suppose I want to compute coref for 100 small articles ( 25 sentences on average) . Just after loading the spanbert large  model the memory is at 2.3 GB . Then after executing each of those 100 articles, the minimum memory required is increasing i.e 2.3 becomes 3 then 4,5 and so on. I wanted to know if the model is storing something new from each articles that it computes coref (for performance or speed). For example the model can store tags or store something for caching. 

It true that the memory is increasing for every input ( maybe everything it faces a new tag or something). After each article the memory is being released, but no the same memory needed for the execution of that article. 

I hope you can understand the problem here, I tried may ways to find what was causing this increase in the memory but didn't manage to find it.

**Comment by foodiehack** [comment]
@datix-vishu hey did you find any solution or any workaround?
