### ISSUE TITLE
ImportError: SpacyTokenizer

### ISSUE THREAD

**Issue by juliaFR** [allenai/allennlp#4228]
**System:**
 - OS: Linux
 - Python version: 3.6.9
 - AllenNLP version: 0.9.0
 - PyTorch version: 1.5.0+cu101

**Question**
Hi there! 
I'm trying to import 'SpacyTokenizer' but always get an ImportError
(from allennlp.data.tokenizers import Tokenizer, SpacyTokenizer
ImportError: cannot import name 'SpacyTokenizer').

**Comment by schmmd** [comment]
I believe the `SpacyTokenizer` was added after 0.9.0.  Specifically it looks like it was renamed from `WordTokenizer`.  See https://github.com/allenai/allennlp/pull/3361 for more details.

**Comment by schmmd** [comment]
You could try running on version `1.0.0rc3`, which does contain the `SpacyTokenizer`.
