### ISSUE TITLE
Question about `srl-eval.pl` on arabic dataset

### ISSUE THREAD

**Issue by chaojiang06** [allenai/allennlp#4233]
**System (please complete the following information):**
 - OS: Ubuntu 18.04.3 LTS
 - Python version: 3.7
 - AllenNLP version: 0.9.0
 - PyTorch version: 1.5

**Question**
Hi, I was working on training SRL models on the Arabic part of ontonotes using AllenNLP. I follow the [instruction](http://conll.cemantix.org/2012/data.html) here to do the pre-processing. The training part can successfully be finished. 

However, the program crashes at the validation step. The validation code will finally call the conll 2005 evaluation script `srl-eval.pl` to compute metrics such as precision / recall / f1. `srl-eval.pl` report an error: `phrase_set->load_SE_tagging: some phrases are unclosed!` . There is a similar issue report [here](https://github.com/allenai/allennlp/issues/4102#issuecomment-626924381).

I was thinking this bug is due to there are some complex or wrong labels in the gold label that `srl-eval.pl` can't handle. I was wondering have anyone experience similar problems?

Any help will be appreciated!

**Comment by MHaoYun** [comment]
Hello, I encounter the same problem, have you solved it? Could you tell me how you solved it?
