### ISSUE TITLE
Tutorial doesn't work after iterators removed

### ISSUE THREAD

**Issue by johntiger1** [allenai/allennlp#4238]
**Describe the bug**
Run the code here: https://allennlp.org/tutorials

Using a fresh install of AllenNLP.

It won't work, since Iterators are removed. 

```
Traceback (most recent call last):
  File "/scratch/gobi1/usr/new_git_stuff/multimodal_fairness/src/models/allen_mort_pred/allen_nlp_demo.py", line 30, in <module>
    from allennlp.data.iterators import BucketIterator
ModuleNotFoundError: No module named 'allennlp.data.iterators'

```

**Expected behavior**
Expect it to work

**System (please complete the following information):**
 - OS: Linux
 - Python version: 3.7
 - AllenNLP version:  "I installed from master"
 - PyTorch version: 1.5+

**Additional context**
Neither the main tutorial nor the "how to" series of AcademicPaper classification works

**Comment by schmmd** [comment]
@johntiger1 thanks--tutorials are on our list to address.

**Comment by johntiger1** [comment]
Thanks, that would be good. I was surprised no one else has mentioned that the main tutorial is broken. Were these recent changes? It seems like iterators were removed _quite_ a while ago:
From over two weeks ago, there are no more iterators in the data package: https://github.com/allenai/allennlp/tree/01e2ad83afd612d5ebbb5ef93d0004a4d6dfd9a1/allennlp/data

**Comment by schmmd** [comment]
I'm a bit surprised too.  It makes me wonder how much attention it gets.  The demo.allennlp.org seems to get much more technical traffic than www.allennlp.org, because when one of our usage statements there doesn't work we hear about it pretty immediately.

**Comment by johntiger1** [comment]
Thanks! Please let me know when this gets fixed. Coming from fairseq,  I was excited to see the user-friendliness of AllenNLP and am looking forward to when others and me can start learning the framework.

**Comment by ZhaofengWu** [comment]
Relevant:
https://github.com/allenai/allennlp-as-a-library-example/issues/32
https://github.com/allenai/allennlp-as-a-library-example/pull/31

**Comment by johntiger1** [comment]
Yes, I realize now the development branch is extremely unstable, and out of date with the tutorial documentation

**Comment by johntiger1** [comment]
See this post for more info, https://github.com/allenai/allennlp-as-a-library-example/issues/33#issuecomment-628771815

Otherwise, you can use an older version of allennlp and this should work!

**Comment by schmmd** [comment]
Closing in favor of https://github.com/allenai/allennlp/issues/3438

**Comment by roist** [comment]
> Thanks, that would be good. I was surprised no one else has mentioned that the main tutorial is broken. Were these recent changes? It seems like iterators were removed _quite_ a while ago:
> From over two weeks ago, there are no more iterators in the data package: https://github.com/allenai/allennlp/tree/01e2ad83afd612d5ebbb5ef93d0004a4d6dfd9a1/allennlp/data

With regards to the usage statement in particular to the reading comprehension. Initially I thought the usage statements were interactive dependant on what model was selected but sadly no. It then took a lot of googling to guess 1) how to write the python code to use the other models and 2) where the models we stored (ie google or amazon). While it would be nice to have interactive usage statements, providing the python code how to use the other models would be a good start.

**Comment by schmmd** [comment]
@roist yes, it's high on my list to fix this... but I need to get some time from our frontend team.

**Comment by yangboye** [comment]
So has this problem been solved?

**Comment by schmmd** [comment]
@yangboye see https://github.com/allenai/allennlp/issues/3438.  We removed the tutorials in favor of the course.

**Comment by kapeed1011** [comment]
I am to trying import BucketIterator using -"from allennlp.data.iterators import BucketIterator" in Google colab.But it is raising the same error again and again-
"ModuleNotFoundError: No module named 'allennlp.data.iterators"
After installing allennlp the imports like:
from allennlp.data.token_indexers import TokenIndexer, SingleIdTokenIndexer
from allennlp.data.tokenizers.character_tokenizer import CharacterTokenizer
from allennlp.data.vocabulary import Vocabulary
from allennlp.modules.seq2vec_encoders import PytorchSeq2VecWrapper
are working fine. Is there a way to solve this issue?
