### ISSUE TITLE
Master workflow is running on forks again

### ISSUE THREAD

**Issue by danielkingai2** [allenai/allennlp#4239]
**Describe the bug**
I think the check that was put in place to fix #3931 has gotten removed at some point, because the master workflow is running on my fork again.

**Comment by epwalsh** [comment]
Currently we have some checks that make sure certain steps of the workflow are not run on forks, such as publishing the Docker image to Docker Hub or publishing the Python package to PyPI, but it's probably a good idea to disable the nightly workflow altogether for forks so we're not wasting resources. Hence https://github.com/allenai/allennlp/pull/4240.

**Comment by danielkingai2** [comment]
Thanks, the issue for me was actually that I get an email every day from my fork telling me that the run failed, and I assume there is a way to turn this off on my end, but I didn't find it.

**Comment by epwalsh** [comment]
You could completely disable actions for your fork. This wouldn't affect the workflows that are run when you make a PR.

Regardless, I'm glad you brought this up. I think it's a good change to make.
