### ISSUE TITLE
Why does allennlp require old version of spaCy?

### ISSUE THREAD

**Issue by xiaolin-cheng** [allenai/allennlp#4242]
I just installed allennlp that replaced my spaCy 2.2.4 with 2.1.9. But spaCy 2.1.9 would need transformers<2.1.0,>=2.0.0 which conflicts with my latest transformers 2.9. 

Can we update the requirements.txt to latest packages? Thanks!

**Comment by schmmd** [comment]
What version of AllenNLP did you install?  Here's the current bounds for Spacy: https://github.com/allenai/allennlp/blob/master/setup.py#L57

**Comment by xiaolin-cheng** [comment]
I did "pip install allennlp" but it uninstalled my 2.2.4 spaCy and installed 2.1.9 spaCy. Do I have to install from source to make it right?

**Comment by schmmd** [comment]
@xiaolin-cheng you're using version 0.9.0, which is our last stable release but is from several months ago.  We expect to have a 1.0.0 release soon.

**Comment by schmmd** [comment]
@xiaolin-cheng we have some release candidate for 1.0.0.  Try `pip install --pre allennlp` or `pip install allennlp-v1.0.0rc3`.
