### ISSUE TITLE
Rename to AUC-ROC?

### ISSUE THREAD

**Issue by johntiger1** [allenai/allennlp#4245]
https://github.com/allenai/allennlp/blob/1b0d231dc7e6b6210d6bc0368d54dbe4989763ec/allennlp/training/metrics/auc.py#L12

Since we can also metrics like AUC-PRC, perhaps we should rename the metric?

**Comment by dirkgr** [comment]
Renaming things is an API-breaking change. We don't want to do that this close to a release.
