### ISSUE TITLE
'Predictor' object has no attribute 'predict'

### ISSUE THREAD

**Issue by peterhanlon** [allenai/allennlp#4246]
**Describe the bug**
Demo code for Reading Comprehension throws AttributeError: 'Predictor' object has no attribute 'predict' error.

**To Reproduce**
Run the demo code from the website (https://demo.allennlp.org/reading-comprehension)

```python
from allennlp.predictors.predictor import Predictor
import allennlp_models.rc
predictor = Predictor.from_path("https://storage.googleapis.com/allennlp-public-models/bidaf-elmo-model-2020.03.19.tar.gz")
predictor.predict(
  passage="The Matrix is a 1999 science fiction action film written and directed by The Wachowskis, starring Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss, Hugo Weaving, and Joe Pantoliano.",
  question="Who stars in The Matrix?"
)
```

Error
Traceback (most recent call last):
  File "/Users/peterhanlon/Dropbox/code/QnA/qna.py", line 4, in <module>
    predictor.predict(
AttributeError: 'Predictor' object has no attribute 'predict'

**System **
 - OS: macOS Catalina 10.15.4
 - Python version: Python
 - AllenNLP version: I've tried rc1, rc3 and rc4

**Comment by roist** [comment]
@peterhanlon try replacing imports with
```
from allennlp_models.rc import bidaf
from allennlp.predictors.predictor import Predictor
```

**Comment by epwalsh** [comment]
Hi @peterhanlon, could you post the output of `pip freeze`?

**Comment by peterhanlon** [comment]
Thanks @epwalsh , replacing the imports did the trick :)
