### ISSUE TITLE
Do we still need the test-install command?

### ISSUE THREAD

**Issue by epwalsh** [allenai/allennlp#4252]
`allennlp test-install` just runs `pytest` in a roundabout way, and adds extra maintenance work since we have to make sure [this function](https://github.com/allenai/allennlp/blob/master/allennlp/commands/test_install.py#L52) stays up-to-date with our pytest configuration in `Makefile` and `pytest.ini`.

It's also redundant (in our CI at least) to be running the unit tests again, and I don't how useful this command is to end users. In theory, if they (the users) can successfully install AllenNLP on an officially supported OS and Python version, they shouldn't need to run a bunch of unit tests to verify that their installation works. They should trust that we've already done that (and we have).

At most I would suggest they just run `allennlp --help` to make sure the binary has been installed and torch and what-not can be successfully loaded.

**Comment by matt-gardner** [comment]
Removing it would also let us have a more typical python package layout, instead of including tests inside the library.

**Comment by schmmd** [comment]
@epwalsh can you find and link to the PR where we added this?  We didn't add it too long ago and it would be good to know why we're circling back on this issue.

**Comment by matt-gardner** [comment]
Added two years ago: https://github.com/allenai/allennlp/pull/1213.  I agree with @epwalsh that something like `allennlp --help` is sufficient, and `test-install` is quite a bit of overkill.

**Comment by epwalsh** [comment]
Instead of completely removing `test-install` we could just make it print out some useful info (like version, pytorch version, GPUs available, etc) so that if there are people out there that use `allennlp test-install` programmatically - like in part of their own CI pipeline - it won't break anything for them.
