### ISSUE TITLE
Create visualizations using Allennlp Interpret

### ISSUE THREAD

**Issue by savinay** [allenai/allennlp#4258]
**Question**
I am trying to create explanations for the predictions by the model as is shown on demo page: https://demo.allennlp.org/named-entity-recognition/MjExNTAzMg==

I have the following code:
```
from allennlp.interpret.saliency_interpreters import SimpleGradient 
SimpleGradient(predictor).saliency_interpret_from_json({'sentence':"This shirt was bought at Grandpa Joes in downtown Deep Learning"}
```

and it returns me the following output:
```
{'instance_1': {'grad_input_1': [0.7466164526464354, 0.1440905519589676, 0.018291907524359417, 0.00600954049677358, 0.041508674938798215, 0.004028081612403084, 0.024965327932526333, 0.00107885332931967, 0.004773362323580226, 0.00516803867296153, 0.0034692091461368253]}, 'instance_2': {'grad_input_1': [0.27729641993428905, 0.026113090527999944, 0.0002990537550420747, 0.008275695387992821, 0.00905805058699953, 0.06128057875171651, 0.19175197183390483, 0.2671991010403639, 0.03189344164556901, 0.10588050542080134, 0.02095201454816753]}}
```

Is there a way to convert this output to the visualization as shown on the demo page or do we have to build our own UI?

**Comment by matt-gardner** [comment]
I'm not totally sure what you're asking, but if you want to have a demo that shows the output for your model, probably the easiest thing to do is to run our demo locally, and replace the model with your own.  See our [demo repository](https://github.com/allenai/allennlp-demo) for information on how to do that.

If you're looking for something else, can you ask a more specific question?

**Comment by koren-v** [comment]
Hi, I'm trying to get simply the result as @savinay get, but I always get the following:
```
{'instance_1': {'grad_input_1': [1.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0]}}
```
for any of the methods from SimpleGradient, SmoothGradient, IntegratedGradient. 
The model I use is RoBerta for the sentiment. So what can be the reason of this problem?

**Comment by colll78** [comment]
I assume that this question is asking for some means of generating a pdf or standalone html page for the model interpretation, such that when one uses the allennlp Python library, they can generate visualizations similar to the ones present in this demo without needing to host and run a web application. The LIME and BertViz libraries offer something like this, however, the implementation is not trivial.
