### ISSUE TITLE
Metrics are computed per batch?

### ISSUE THREAD

**Issue by johntiger1** [allenai/allennlp#4262]
Just want to clarify something.

If you are using the default train, as in [this example](https://allennlp-course.apps.allenai.org/training-and-prediction#3), then at any given time, the metric dict will contain the metric computed for a single batch, correct? (except for "loss"). 

Therefore, the `CategoricalAccuracy` reported in the tutorial is only for the final batch.

You can see this from here, where in `evaluate`, the other metrics are not accumulated/reduced over an epoch. 
https://github.com/allenai/allennlp/blob/master/allennlp/training/util.py#L314

Additionally from here, in `train`, the other metrics are not accumulated/reduced over an epoch. 
https://github.com/allenai/allennlp/blob/7d71398b44636c52e811467a684c3099c64009ec/allennlp/training/util.py#L296

**Comment by matt-gardner** [comment]
The metrics maintain counts until they are reset, so what you are seeing is an average over all batches so far in an epoch.  Here: https://github.com/allenai/allennlp/blob/7d71398b44636c52e811467a684c3099c64009ec/allennlp/training/util.py#L355
`get_metrics` is called without setting `reset=True`, so counts are not reset.  Later, at the end of the epoch, `get_metrics` is called with `reset=True`, so the counts start over: https://github.com/allenai/allennlp/blob/7d71398b44636c52e811467a684c3099c64009ec/allennlp/training/util.py#L389
If you look in the code for any of our metrics, you will see that they use total counts, resetting those counts when `reset=True` is passed: https://github.com/allenai/allennlp/blob/7d71398b44636c52e811467a684c3099c64009ec/allennlp/training/metrics/categorical_accuracy.py#L102-L113

**Comment by johntiger1** [comment]
Ah ok, great, thank you for the clarification Matt! Library has been extremely intuitive and good to use so far :)

**Comment by johntiger1** [comment]
Hey @matt-gardner so I looked into this a bit more, and while it seems like this is the case for `categorical_accuracy`, it is not the case for AUC. 

As you can see here: 
https://github.com/allenai/allennlp/blob/master/allennlp/training/metrics/auc.py#L93
` auc = metrics.auc(false_positive_rates, true_positive_rates)`

The current auc is simply overwritten with the new batch of examples. 

Now I think I understand the justification, since in general we don't have an accepted way of reducing the AUC across multiple batches, i.e. the average of AUCs is not the AUC of all examples.
However, it might be good to add a warning for that particular metric, since in that specific case, it is indeed a per batch computation.

**Comment by johntiger1** [comment]
Actually, my mistake! I just saw this line: https://github.com/allenai/allennlp/blob/master/allennlp/training/metrics/auc.py#L78
