### ISSUE TITLE
Coreference resolved output sentence

### ISSUE THREAD

**Issue by DebayanChakraborty** [allenai/allennlp#4265]
**System:**
 - OS: [Linux , UBUNTU wsl]
 - Python version: [3.6.8]
 - AllenNLP version: [v1.0.0.rc3]

**Question**

* I'm working on a coreference resolution task and I would like to resolve the coreference within my sentence output.  Is there any in built functionality that does that ?  Or , do i need to use the standard output and do the resolution myself via code .

Example : the code

 ` from allennlp.predictors.predictor import Predictor` 
 ` import allennlp_models.coref` 
 `  doc = "The medical emergency i had told you about, it was not that serious. I was scared, but it 
                wasnt worth it"` 
 ` predictor = Predictor.from_path("./model/coref-spanbert-large-2020.02.27.tar.gz")`
 `  predictor.predict(document=doc)` 

yeilds the output

_{'top_spans': [[0, 7], [3, 3], [6, 6], [9, 9], [15, 15], [17, 17], [20, 20], [21, 21], [22, 22], [24, 24]], 'antecedent_indices': [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 
8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]], 'predicted_antecedents': [-1, -1, -1, 0, 1, -1, -1, -1, -1, -1], 'document': ['The', 'medical', 'emergency', 'i', 'had', 'told', 'you', 'about', ',', 'it', 'was', 'not', 'that', 'serious', '.', 'I', 'was', 'scared', ',', 'but', 'it', 'was', 'nt', 'worth', 'it'], 'clusters': [[[0, 7], [9, 9]], [[3, 3], [15, 15]]]}_

While the output i want is a coref resolved sentence like 

_The medical emergency i had told you about, the medical emergency i had told you about was not that serious. I was scared but it wasnt worth it._

I see i can resolve via string handling and the clusters , but i wanted to know is there a fast inbuilt functionality that does the same then i woud prefer leveraging that . 

Thanks

**Comment by datix-vishu** [comment]
from allennlp.predictors.predictor import Predictor
import allennlp_models.coref

coref_model = Predictor.from_path('.../coref-spanbert-large-2020.02.27.tar.gz')
coref_model.coref_resolved(text)

**Comment by DebayanChakraborty** [comment]
> from allennlp.predictors.predictor import Predictor
> import allennlp_models.coref
> 
> coref_model = Predictor.from_path('.../coref-spanbert-large-2020.02.27.tar.gz')
> coref_model.coref_resolved(text)

Thanks , exactly what i am looking for , does allennlp have a functionality documentation or did you get this from code review ?

**Comment by datix-vishu** [comment]
Yeah, got this from the code.
