### ISSUE TITLE
Will AllenNLP Coref work with multi threads ?

### ISSUE THREAD

**Issue by datix-vishu** [allenai/allennlp#4266]
I'm seeing a huge increase in the number of threads (83 threads). Also, the time to execute the same article is different at different time.

**Comment by dirkgr** [comment]
Where do you see those threads? What is it that you're running? What is the actual problem?

**Comment by epwalsh** [comment]
Closing due to lack of response, please feel free to comment if you're still having an issue, or post on our discourse forum.
