### ISSUE TITLE
Will using slot classes for fields and other data abstractions significantly reduce memory usages?

### ISSUE THREAD

**Issue by epwalsh** [allenai/allennlp#4268]
Some helpful info:
- https://www.python-course.eu/python3_slots.php

**Comment by matt-gardner** [comment]
From that page:

> Since Python 3.3 this advantage is not as impressive any more. With Python 3.3 Key-Sharing Dictionaries are used for the storage of objects.

Seems worth trying, though, at least.  Should be easy to try.
