### ISSUE TITLE
how can I custom my trainner?

### ISSUE THREAD

**Issue by wj-Mcat** [allenai/allennlp#4303]
Our model output two type loss : 
```json
output ={
    "intent_loss": 0.1,
    "slot_loss": 0.3
}
```
I will train my model in rotation. This is my customization, I can't see any document description it. Could you help me?

**Comment by matt-gardner** [comment]
My recommendation for how to do this with current code (a recent pre-release of 1.0):

Use a `BatchCallback` to tell the model which loss to output, keeping a flag that alternates every batch (or however many batches you want to do for each loss in a row).  Then the model can just customize its output behavior based on that flag.  You could even output both, using those keys, for logging purposes, but have only one of them used for the `loss` key that's used for computing gradients.

**Comment by epwalsh** [comment]
Hi @wj-Mcat, thanks for the question. We're going to close this now because our discourse forum would be a better place for these types of questions. https://discourse.allennlp.org/

**Comment by wj-Mcat** [comment]
Ok, thanks a lot for your reply.
