### ISSUE TITLE
allennlp prune command

### ISSUE THREAD

**Issue by dirkgr** [allenai/allennlp#4304]
People using the library (@yakazimir) are ending up with lots of model directories that are full of checkpoints, wasting many TB of space. We could have an `allennlp prune` command that finds these and deletes them, leaving only the final model.

**Comment by matt-gardner** [comment]
Finding arbitrary directories that were used seems really challenging.  We could walk a directory looking for weights files, but how do we know which ones to keep...?

An alternative solution is to just change the number of serialized models that we keep around, which we did already: https://github.com/allenai/allennlp/blob/91d0fa1a51485c4118e48426d76328acd8049587/allennlp/training/checkpointer.py#L29.  Someone on 0.9 wouldn't see this change yet.

**Comment by ZhaofengWu** [comment]
+1 to Matt's comment. I was having the same problem in 0.9 but with this change this shouldn't be a problem anymore.

Regardless, if we want to do this, it might be better to come up with a name other than `prune` to avoid confusion with model pruning.

**Comment by matt-gardner** [comment]
In issue review we thought we should just close this.  Please reopen @dirkgr if you want to discuss further.
