### ISSUE TITLE
Request for DistilBERT

### ISSUE THREAD

**Issue by nikitacs16** [allenai/allennlp#4311]
Hello,
An allennlp newbie here. I was wondering if the DistilBERT models are available in the encoders.
Any help will be appreciated.
Thank you

**Comment by matt-gardner** [comment]
If you use the `PretrainedTransformer` text processing classes, then you can pass them any model name that's supported by the `transformers` library (including distilbert).  So, yes, you do this already.  Closing this issue, but feel free to comment if you have more questions.
