### ISSUE TITLE
wanted to use allenNLP wiki table parser in our application ?

### ISSUE THREAD

**Issue by varunmandiram** [allenai/allennlp#4314]
wanted to access the pre-trained model  (which was trained on wikitables)using python.
wanted to add additional training to the existing model based on our requirement.
Kindly help us resolving in these  issues

**Comment by matt-gardner** [comment]
The code for that model lives in the [allennlp-semparse repository](https://github.com/allenai/allennlp-semparse).  You can see the location for a trained model [here](https://github.com/allenai/allennlp-demo/blob/master/api/allennlp_demo/wikitables_parser/model.json).
