### ISSUE TITLE
Add a method to nn.util that creates a new tensor/variable on the same device as an input

### ISSUE THREAD

**Issue by matt-gardner** [allenai/allennlp#432]
There are plenty of places in the code where we do `Variable(variable.data.new().resize_(some_shape).fill_(some_value))`, as that is the recommended way to create a new variable on the same device as some other variable.  This is an annoying pattern to see in code and to remember when writing code.  We should add a method to `nn.util` that does this in a configurable way, and replace all places in the code where we do this with the new method.

**Comment by matt-gardner** [comment]
And apparently we missed a minor improvement, here, too: [you can pass](https://discuss.pytorch.org/t/is-it-possible-to-make-a-function-transparent-between-cpu-and-gpu/1235/7) the shape directly to `new()`, instead of calling `new().resize_(shape)`.

**Comment by schmmd** [comment]
Joel: a solution here will likely be deprecated by PyTorch 0.4.
