### ISSUE TITLE
TransformerQA has much lower performance with mixed precision training

### ISSUE THREAD

**Issue by epwalsh** [allenai/allennlp#4329]
I've run a lot of benchmarks now on the TransformerQA model both with and without mixed precision training using Apex. While using Apex does result in a significant speed up, the loss and f1 metrics are significantly worse:

<img width="1555" alt="image" src="https://user-images.githubusercontent.com/8812459/83922326-fc39b600-a734-11ea-90d0-1a2dc7626376.png">

Per @matt-peters suggestion we should try training the same models with HuggingFace directly to see if we see the same results.

**Comment by epwalsh** [comment]
Trying again with torch's native amp: https://beaker.org/ex/ex_gujbczw50ujg/tasks/tk_pdpbwfl9ajak

**Comment by matt-gardner** [comment]
Awesome!
