### ISSUE TITLE
pretrained file from word2vec model

### ISSUE THREAD

**Issue by wj-Mcat** [allenai/allennlp#4335]
I get pretrained embedding from word2vec model, which doesn't contains oov padding.  Allennlp must require oov padding in token.txt files. So, embedding file `word_idx `[0] is not `oov` index. 

how to resolve this matching problems?

**Comment by matt-gardner** [comment]
How are you creating your vocabulary and your embedding layer?  Where exactly do you get an error?  We need a little bit more detail in order to help you.
