### ISSUE TITLE
SRL predictor misses "get" verb.

### ISSUE THREAD

**Issue by ducalpha** [allenai/allennlp#4337]
SRL Predictor only considers verbs with VERB Universal POS (https://github.com/allenai/allennlp-models/blob/master/allennlp_models/structured_prediction/predictors/srl.py#L108), but "get" commonly is tagged as AUX by Spacy. Therefore, the verb "get" in sentences is frequently ignored.

How to reproduce:
Trying the following sentence on SRL demo (https://demo.allennlp.org/semantic-role-labeling) with Allennlp 1.0 RC5 and BERT SRL yields a dictionary with only "go" verb.

"we go to the party to get free food."

```
from allennlp.predictors.predictor import Predictor
import allennlp_models.structured_prediction.models.srl
predictor = Predictor.from_path("https://storage.googleapis.com/allennlp-public-models/bert-base-srl-2020.03.24.tar.gz")
predictor.predict(
  sentence="we go to the party to get free food."
)
```

(P.S. The usage on the demo web page is not updated to AllenNLP 1.0 RC5 but it should be filed on another bug.)

**Comment by matt-gardner** [comment]
This is not a bug in allennlp.  If you want to use a different tagger with our SRL model, you can replace the tagger in the SRL predictor.  If you have a recommendation for a better tagger to use by default, PR welcome.
