### ISSUE TITLE
Make an AllenNLP Project Template

### ISSUE THREAD

**Issue by dirkgr** [allenai/allennlp#4339]
We should have a template GitHub repo for people to get started with.

**Comment by matt-gardner** [comment]
Is this good enough as a template? https://github.com/allenai/allennlp-guide-examples/tree/master/quick_start

**Comment by schmmd** [comment]
@dirkgr great suggestion.  @matt-gardner possibly, but if we make it a GitHub template (e.g. https://github.com/allenai/skiff-template) it'd be even easier to get started...

**Comment by schmmd** [comment]
We might consider three templates:

1 - python template
2 - configuration file
3 - pytorch lightening

**Comment by schmmd** [comment]
Closinga s this is done.  @matt-gardner can you link to the other tempalte?

**Comment by schmmd** [comment]
Templates are here: https://github.com/allenai/allennlp#getting-started-using-the-library
