### ISSUE TITLE
Provide documentation for uploading pretrained transformer weights to HuggingFace

### ISSUE THREAD

**Issue by JohnGiorgi** [allenai/allennlp#4351]
**Is your feature request related to a problem? Please describe.**

As per [my post on the forums](https://discourse.allennlp.org/t/upload-a-pretrained-transformer-to-huggingfaces-transformers/325), I think it would be very useful if there were instructions for uploading the weights of a transformer-based language model trained with AllenNLP to [HuggingFace's Models](https://huggingface.co/models).

**Describe the solution you'd like**

A mechanism (if it doesn't already exist) and instructions for uploading the weights of a pretrained language model trained with AllenNLP to [HuggingFace's Models](https://huggingface.co/models).

**Describe alternatives you've considered**

N/A.

**Additional context**

I first asked if this was possible [in the forums](https://discourse.allennlp.org/t/upload-a-pretrained-transformer-to-huggingfaces-transformers/325) and @matt-gardner asked me to open a feature request here.

**Comment by schmmd** [comment]
@ZhaofengWu is this something you did with one of your models?  Apologies if I'm misremembering.

**Comment by ZhaofengWu** [comment]
I uploaded and only uploaded SpanBERT (https://huggingface.co/SpanBERT/spanbert-base-cased, https://huggingface.co/SpanBERT/spanbert-large-cased). It's not generated by AllenNLP and was already packaged in a way that huggingface recognizes, so it's probably not super relevant here.

**Comment by schmmd** [comment]
@JohnGiorgi if you have a huggingface model in memory is that sufficient?  If so, we can give you some pointers on how to do that.  If not, we need to figure something bigger out.

**Comment by JohnGiorgi** [comment]
@schmmd Do you mean did I train a huggingface model with allennlp? If so then use, all my trainable weights are in a `PretrainedTransformerEmbedder`

**Comment by matt-gardner** [comment]
The question is, if you can get the in-memory `Model` from `tokenizers`, is that sufficient to follow their instructions to upload weights, or is something else needed?  I haven't done this before, but it looks like there's a [`.save_pretrained()`](https://huggingface.co/transformers/model_sharing.html) method that you can call on the in-memory `Model`, which you can pull out of our `Embedder` object.

**Comment by JohnGiorgi** [comment]
Oh sorry, I understand now. Yes that seems obvious in hindsight, I guess it is just a matter of figuring out where/when to call `.save_pretrained()` but I am sure I can figure that out. Thanks for the guidance!

**Comment by JohnGiorgi** [comment]
Okay, for anyone who lands on this issue, I have figured out how to do this with an `EpochCallback` object:

```python
from pathlib import Path
from typing import Any, Dict

from allennlp.training import EpochCallback, GradientDescentTrainer


@EpochCallback.register("hf_save_pretrained")
class HFSavePretrainedCallback(EpochCallback):
    """This callback will call
    `trainer.model.transformer_model.save_pretrained(trainer.serialization_dir)` at the end of
    every epoch. This is useful to save the weights/tokenizer/config of a HuggingFace Transformers
    model (encapsulated by a `PretrainedTransformerEmbedder` object) for uploading to
    https://huggingface.co/models.
    """

    def __call__(
        self, trainer: "GradientDescentTrainer", metrics: Dict[str, Any], epoch: int
    ) -> None:
        if not trainer._serialization_dir:
            raise ValueError(
                "trainer._serialization_dir must be specified to use this EpochCallback."
            )

        hf_serialization_dir = Path(trainer._serialization_dir) / "hf_transformers"
        hf_serialization_dir.mkdir(parents=True, exist_ok=True)

        trainer.model._text_field_embedder._token_embedders[
            "tokens"
        ].transformer_model.save_pretrained(hf_serialization_dir)
```

Of course, this implementation relied on knowing that for my model, `trainer.model._text_field_embedder._token_embedders["tokens"].transformer_model` exists and that is is a `PretrainedTransformerEmbedder`.

**Comment by epwalsh** [comment]
@JohnGiorgi thanks for that example.

And for everyone in this thread, where do you think would be the best place to document this? A couple of ideas (not necessarily mutually exclusive):

- put instructions in the docstring of `PretrainedTransformerEmbedder`
- write a short blog post, publish on medium, and link to this post in the `PretrainedTransformerEmbedder` docstring and also in our README in the list of external tutorials: https://github.com/allenai/allennlp#getting-started-using-the-library

**Comment by JohnGiorgi** [comment]
@epwalsh No problem, there's just a couple of issues I ran into:

- `hf_serialization_dir` needs to be a `str`, (or cast to a `str`) before being passed to `save_pretrained` (see https://github.com/huggingface/transformers/pull/4650).
- By default, there is no way to access the HuggingFace `tokenizer` from `PretrainedTransformerEmbedder` (I think). In order to do that so that I could call `save_pretrained` on it, I needed to subclass `PretrainedTransformerEmbedder` and give it an attribute `self.tokenizer`.

My updated example looked like:

```python
from pathlib import Path
from typing import Any, Dict

from allennlp.training import EpochCallback, GradientDescentTrainer


@EpochCallback.register("hf_save_pretrained")
class HFSavePretrainedCallback(EpochCallback):
    """This callback will call
    `trainer.model.transformer_model.save_pretrained(trainer.serialization_dir)` at the end of
    every epoch. This is useful to save the weights/tokenizer/config of a HuggingFace Transformers
    model (encapsulated by a `PretrainedTransformerEmbedder` object) for uploading to
    https://huggingface.co/models.

    # Parameters

    model_name : `str`, optional (default=`'hf_transformer'`)
        Name of the folder to save the HuggingFace Transformers model. The full path is given
        by: "<trainer._serialization_dir>/model_name".
    """

    def __init__(self, model_name: str = "hf_transformer"):
        self._model_name = model_name

    def __call__(
        self,
        trainer: "GradientDescentTrainer",
        metrics: Dict[str, Any],
        epoch: int,
        is_master: bool,
    ) -> None:
        if not trainer._serialization_dir:
            raise ValueError(
                "trainer._serialization_dir must be specified to use this EpochCallback."
            )

        hf_serialization_dir = Path(trainer._serialization_dir) / self._model_name
        hf_serialization_dir.mkdir(parents=True, exist_ok=True)

        trainer.model._text_field_embedder._token_embedders[
            "tokens"
        ].transformer_model.save_pretrained(hf_serialization_dir)
        # Casting as a string to avoid this error: https://github.com/huggingface/transformers/pull/4650
        # Can be removed after PR is merged and Transformers is updated.
        trainer.model._text_field_embedder._token_embedders["tokens"].tokenizer.save_pretrained(
            str(hf_serialization_dir)
        )
```

There also appears to be something strange happening if you call this on a distributed model. I never really got to the bottom of it, but when I ran this code on a CPU, uploading/downloading to https://huggingface.co/models worked fine. When I actually went to train my model with AllenNLP in a distributed setup and run this code, uploading works but downloading throws a weird error.

This callback might need to make a copy of the model/tokenizer on the CPU before calling `save_pretrained` to avoid this.

**Comment by epwalsh** [comment]
Thanks @JohnGiorgi, that's helpful!

**Comment by matt-gardner** [comment]
> * write a short blog post, publish on medium, and link to this post in the `PretrainedTransformerEmbedder` docstring and also in our README in the list of external tutorials: https://github.com/allenai/allennlp#getting-started-using-the-library

Put a section in the guide instead of this?

**Comment by epwalsh** [comment]
@matt-gardner either way is fine with me, I just wasn't sure if this would be within the scope of the guide.

**Comment by epwalsh** [comment]
After talking with @matt-gardner and @AkshitaB we decided that it would beneficial (and very little extra work) to publish mini tutorials like these on both Medium and the guide.

We want the guide to be the centralized source of truth for AllenNLP documentation, but cross-posting on Medium would make these tutorials easier to find and could ultimately help drive traffic to the guide as well.

**Comment by epwalsh** [comment]
Medium post on this here: https://medium.com/ai2-blog/tutorial-how-to-upload-transformer-weights-and-tokenizers-from-allennlp-to-huggingface-ecf6c0249bf.

I'll hold off on closing this issue until I've added it to the guide as well so I don't forget.

Thanks @JohnGiorgi for bringing this up!
