### ISSUE TITLE
Questions about Problems with discriminative_fine_tuning

### ISSUE THREAD

**Issue by wlhgtc** [allenai/allennlp#4353]
Hi there,
Thanks for your great work, it's easy for me to do experiments.
But still few questions about the `discriminative_fine_tuning`：
I use the model in [https://github.com/allenai/allennlp/blob/v0.9.0/allennlp/models/bert_for_classification.py#L16](url)
And  I want to use the parameter  `discriminative_fine_tuning` to set  different learning rate.
Specifically, I want three groups like `[[layer0,layer1,layer2,layer3][layer4,layer5.layer6,layer7],[layer8,layer9,layer10,layer11]]`.
In #2159 , It seems that I could print all their name and list them in my config file.
Cause of some many parameters, can I finish it in an elegant way ?
@matt-peters  Hope you could help, thx!

**Comment by matt-peters** [comment]
allennlp supports regular expressions to define the parameter groups, this isn't particularly elegant but is better then listing all parameters separately.

**Comment by wlhgtc** [comment]
> allennlp supports regular expressions to define the parameter groups, this isn't particularly elegant but is better then listing all parameters separately.
@matt-peters  Thanks for your reply. 
And could you provide me a demo about how to use it. 
I can do it easily in python file, but hard to move it in config file(jsonnet).

**Comment by matt-gardner** [comment]
Config files just provide constructor parameters; there's a one-to-one mapping between keys in a config file and constructor parameters.  See [here](https://guide.allennlp.org/using-config-files) for some more material explaining this.

**Comment by wlhgtc** [comment]
> Config files just provide constructor parameters; there's a one-to-one mapping between keys in a config file and constructor parameters. See [here](https://guide.allennlp.org/using-config-files) for some more material explaining this.
Thanks for your advice, and I read this documents. Seem I have to list all name when I use Config files ?
Could  I write a new Optimizer and do it automatically ,  maybe a tricky solution ?

**Comment by wlhgtc** [comment]
I use the follow config
`
        "optimizer": {
            "type": "bert_adam",
            "lr": 1e-5,
            "parameter_groups": [
                [["layer.0.","layer.1.","layer.2.","layer.3."], {}],
                [['layer.4.','layer.5.','layer.6.','layer.7.'], {}],
                [['layer.8.','layer.9.','layer.10.','layer.11.'], {}]
            ]
        },
`
Seem all items in parameter_groups are regex.
But if I have` layer.10.weight`, it could be catch by both `layer.1.` and `layer.10.`
I want to use `\.` to replace `.` , but it failed.
How could I solve it ? @matt-peters  @matt-gardner

**Comment by schmmd** [comment]
@wlhgtc can you give us a more detailed error message?

We're releasing 1.0 next week and that may make this easier.  Our 1.0.0rc6 is out presently and should be nearly identical to 1.0 if you want to try it now.

**Comment by wlhgtc** [comment]
> @wlhgtc can you give us a more detailed error message?
> 
> We're releasing 1.0 next week and that may make this easier. Our 1.0.0rc6 is out presently and should be nearly identical to 1.0 if you want to try it now.


Thanks for your advice. I will try it after reading doc.
And the error message is as follow:
I use optimizer config like this:
`        "optimizer": {
            "type": "bert_adam",
            "lr": 1e-5,
            "parameter_groups": [
                [["layer.0.","layer.1.","layer.2.","layer.3."], {}],
                [['layer.4.','layer.5.','layer.6.','layer.7.'], {}],
                [['layer.8.','layer.9.','layer.10.','layer.11.'], {}]
            ]
        },
`
And I got an error: `ValueError: bert_model.encoder.layer.10.attention.self.query.weight was specified in two separate parameter groups`
In Bert there are 12 layers, and the item in "parameter _groups" is regarded as regex. So `layer.0.` and 'layer.10.' could both catch `layer10.xxx`.
Then I try to use `layer\.0` to replace `layer.0`. Unfortunately, I got another error like: 
`RuntimeError: STATIC ERROR: experiments/test.jsonnet:39:19-30: Unknown escape sequence in string literal: '.'`
Line 39 is the `layer\.0`.
I wonder if it's a bug, Did you fix it in 1.0 ?

**Comment by matt-gardner** [comment]
You probably need to escape the backslash, like this: `layer\\.0`.

**Comment by wlhgtc** [comment]
> You probably need to escape the backslash, like this: `layer\\.0`.

Thanks, it works!
