### ISSUE TITLE
Reported loss is confusing

### ISSUE THREAD

**Issue by dirkgr** [allenai/allennlp#4354]
The loss we write into tensorboard is the average loss over the epoch. So the first number we get is not averaged at all, while the last number in the epoch is averaged over the entire epoch. Then we start the second epoch, and the next value reported is just the loss of the first batch of the second epoch. As a result, we always see a big drop in loss when the epoch changes. This makes no sense.

**Comment by schmmd** [comment]
We discussed and decided we should add a batch loss to our metrics.

**Comment by dirkgr** [comment]
@HarshTrivedi discovered that #4477 didn't really fix this. We want to log the actual loss of each individual batch, not the sum of the losses.
