### ISSUE TITLE
Add tutorial on using Optuna with AllenNLP

### ISSUE THREAD

**Issue by Crissman** [allenai/allennlp#4382]
**Is your feature request related to a problem? Please describe.**
Optuna is a new hyperparameter optimization library, and we’ve written an integration module for AllenNLP to make it easy to use Optuna to search for good hyperparameter settings and prune unpromising trials. We’re looking for ways to let AllenNLP users know this is available and thought a badge to show Optuna integration is available would be helpful.

**Describe the solution you'd like**
Would an PR for a Guide on the AllenNLP repo on how to use Optuna with AllenNLP be helpful?

**Describe alternatives you've considered**
We've already published a [blog post on using Optuna with AllenNLP](https://medium.com/optuna/hyperparameter-optimization-for-allennlp-using-optuna-54b4bfecd78b).

**Additional context**
If there are other ways you would recommend reaching out to AllenNLP users to let them know about Optuna, please let us know.

**Comment by dirkgr** [comment]
That's pretty neat! I tried it for [my multiple choice models](https://github.com/allenai/allennlp-models/commit/0ea5f41b22d37a3dccbb653f7dcf6f8486ffdd4e). It's still running, but we'll see if it does better than my big aimless sweeps :-)

One piece of feedback: If you want to tune models from the `allennlp-models` repo, you have to add `include_package="allennlp_models"` to the `AllenNLPExecutor`: https://github.com/allenai/allennlp-models/commit/0ea5f41b22d37a3dccbb653f7dcf6f8486ffdd4e#diff-fd79ef7c93f9bec5fd44004e2e9381daR17

In terms of publicity, we can tweet about it, and I pinged @matt-gardner about adding it to the guide at https://guide.allennlp.org. We only have first-party content there now, but maybe it doesn't have to stay that way. Same goes for https://docs.allennlp.org. @schmmd, what do yo think?

@Crissman, will you keep this up to date? I'd hate to add something to the docs that goes out of date after a month or two.

**Comment by schmmd** [comment]
I would propose we link out to external documentation from our README or https://docs.allennlp.org.

**Comment by dirkgr** [comment]
@Crissman, in addition to @matt-gardner's answer, can you make a PR that adds a link in the readme?

**Comment by schmmd** [comment]
I made a PR: https://github.com/allenai/allennlp/pull/4385

**Comment by matt-gardner** [comment]
@Crissman, it would be great to have a chapter on hyperparameter tuning in the guide, and if that prominently features optuna as one of the ways of doing this (even the only one that's mentioned for now), that's fine with me.  Please feel free to open a PR on the [guide repo](https://github.com/allenai/allennlp-guide).

**Comment by Crissman** [comment]
Great! We'll start on a PR for the guide.

**Comment by matt-gardner** [comment]
Closing in favor of https://github.com/allenai/allennlp-guide/issues/131.
