### ISSUE TITLE
Weights and Biases integration

### ISSUE THREAD

**Issue by dirkgr** [allenai/allennlp#4387]
@dhruvdcoder wrote this in #4385:

> You could also include this micro-library called [wandb-allennlp](https://pypi.org/project/wandb-allennlp/) which enables the use of Weight&Biases to perform hyperparameter search for AllenNLP models. I have been using W&B with AllenNLP models for quite some time now and hence decided to create a package for others to use the same setup. 
>
> Example search sweep visualization [link](https://app.wandb.ai/dhruveshpate/wandb_allennlp_models_demo/sweeps/vwwu3sa0)
>
> Usage details are in the readme-files in the [repo](https://github.com/dhruvdcoder/wandb-allennlp). A short tutorial can be found [here](http://dhruveshp.com/machinelearning/wandb-allennlp/). Although the tutorial is for AllenNLP v0.9, the library works with v1.0 as well. 
>
> I would be happy to give more information if needed.

**Comment by dirkgr** [comment]
@dhruvdcoder, this is great! Can we get this all the way ready for 1.0? I see that you are only using the `EpochCallback` functionality. Is that enough? Don't you need information per batch too?

Does this work for things other than sweeps?

**Comment by dhruvdcoder** [comment]
@dirkgr Logging batch metrics is not necessary for hyperparameter optimization and also I feel that logging metrics for each batch generates too much to plot on the W&B dashboard. Moreover, since the trainer (in v1.0) creates tensorboard logs with batch metrics, these are automatically picked up by W&B. If one wants to see the batch metrics, one can open the tensorboard for that particular run inside W&B dashboard itself, for instance, [this one](https://app.wandb.ai/dhruveshpate/wandb_allennlp_models_demo/runs/md9qrj4g/tensorboard).

So using `EpochCallback` seems to be enough for now and the current version on pypi is tested with AllenNLP v1.0. Just the tutorial blog post on my website is a little outdated. 

Apart from sweeps, it can also log individual standalone runs. There are a few other features that I think will be useful but I am waiting for some feedback from people before I implement that.

**Comment by williamFalcon** [comment]
@dirkgr wondering if you guys are still considering lightning?
we already have these integrations out of the box with WB, comet and others.

In addition, we recently integrated TPU tests and continue to be adopted by facebook, nvidia, uber, etc...

**Comment by mateuszpieniak** [comment]
@dirkgr I raised a similar issue some time ago https://github.com/allenai/allennlp/issues/3990 and I got the impression like it is a bit out of the scope of AllenNLP's core. Correct me if I am wrong.

@dhruvdcoder Do you think it would be possible to modify your library to be an AllenNLP's plugin (like [allennlp-models](https://github.com/allenai/allennlp-models) or [allennlp-server](https://github.com/allenai/allennlp-server))?

**Comment by dhruvdcoder** [comment]
@mateuszpieniak It is pretty much like a complete plugin right now -- does not touch any AllenNLP code, can be installed and uninstalled separately without affecting any core AllenNLP functionality. I am not sure what else is needed to make it a plugin. Can you give some specifics things you would like to have? I encourage you to try [this example](https://github.com/dhruvdcoder/wandb-allennlp/tree/master/examples) which shows how one can use the plugin. It uses the plugin to perform hyperparameter search for on of the models from `allennlp-models`. If you want to log a single standalone training run see [this](https://github.com/dhruvdcoder/wandb-allennlp#log-a-single-run).

Let me know what else is needed to make it a plugin and I can work on that.

**Comment by mateuszpieniak** [comment]
@dhruvdcoder I will take a closer look at the weekend. I meant that it looks like a wrapper to me (you have separate program `wandb_allennlp`). I don't claim it's bad, just wondering whether it's possible to extend AllenNLP functionality so you still use `allennlp train` - for example `allennlp-server` adds new subcommands. Anyway, I think it should be designed in such a way so people can integrate more experiments' management tools.

**Comment by dirkgr** [comment]
I think the easiest thing we can do here is include @dhruvdcoder's library in the README. I'm happy to review a PR that does this.

Beyond that, it would be good to have the `EpochCallback` in a form where you can just reference it in a config and it will work from there. If it's easy enough, I'd love to have it as part of the core library. Then we don't have to worry about `--include-package`.

**Comment by dirkgr** [comment]
We're considering this for inclusion in the next minor release, but it'll compete with a number of other priorities.

**Comment by MichalMalyska** [comment]
^ I have been using the wanb-allennlp for quite some time now and it works very well so if you take community votes into consideration, I guess here's mine.

**Comment by dhruvdcoder** [comment]
I have been playing around with the plugin interface of AllenNLP, and I think the functionality of wandb-allennlp can be converted into a plugin. There are some issues with multi-node training though that need to be fixed. I was thinking of taking a stab at this after the first week of Feb.

**Comment by dirkgr** [comment]
For the logging functionality I would think that's pretty easy. We could log to wandb from a `BatchCallback`.

The sweeping functionality would need a new command, maybe `allennlp wandb-sweep`. Commands can be added in plugins same as any other `Registrable` component.
