### ISSUE TITLE
SRL predictor misses Auxiliary verb

### ISSUE THREAD

**Issue by deanyan7** [allenai/allennlp#4388]
System (please complete the following information):

OS: Linux
Python version: 3.6.9
AllenNLP version: 1.0.0
PyTorch version: 1.5.0

When I used the SRL model to predict sentences, 
The inputs is “The new rights are nice enough.”

The result is:
[{'verbs': [], 'words': ['The', 'new', 'rights', 'are', 'nice', 'enough']}]

The Correct  result is：
[{"verbs": [{"verb": "are", "description": "[ARG1: The new rights] [V: are] [ARG2: nice enough]", "tags": ["B-ARG1", "I-ARG1", "I-ARG1", "B-V", "B-ARG2", "I-ARG2"]}]

How can I fix it?  Thank you!

**Comment by schmmd** [comment]
@deanyan7 our models are not perfect, and we can not guarantee correct results for all examples.  I don't think there's anything we can do here.

**Comment by deanyan7** [comment]
I'm so sorry i didn't make this clear


When I compared the results of allennlp used by others, I found this question:
    Semantic role labelling model tags are all 'O'. No arguments are detected.

System:

- Python version: Python 3.6.9

- AllenNLP version: allennlp==1.0.0  allennlp-models==1.0.0

- PyTorch version: 1.5.0


Related Issue: [allenai/allennlp#4146](https://github.com/allenai/allennlp/issues/4146)  


from allennlp.predictors.predictor import Predictor
import allennlp_models.syntax.srl
predictor = Predictor.from_path("model/srl-model-2018.05.25.tar.gz")
predictor.predict(
  sentence="The new rights are nice enough."
)


I compared allennlp==0.8.1(srl-model-2018.05.25.tar.gz) and allennlp==1.0.0(bert-base-srl-2020.03.24.tar.gz) versions, both of this result:
[{'verbs': [], 'words': ['The', 'new', 'rights', 'are', 'nice', 'enough']}]

Expected Output   (Related result:[dev_matched.tsv_tag_label   index 0](https://github.com/cooelf/SemBERT/blob/master/glue_data/MNLI/dev_matched.tsv_tag_label))
[{"verbs": [{"verb": "are", "description": "[ARG1: The new rights] [V: are] [ARG2: nice enough]", "tags": ["B-ARG1", "I-ARG1", "I-ARG1", "B-V", "B-ARG2", "I-ARG2"]}]

**Comment by deanyan7** [comment]
When making sample predictions, I found that the model filtered certain words (such as is, was, do, did, are, were and other specific types of words), but when others used it before, the result was normal.



sentence = "yeah i know and i did that all through college and it worked too"
result = {'verbs': [{'verb': 'know', 'description': 'yeah [ARG0: i] [V: know] and i did that all through college and it worked too', 'tags': ['O', 'B-ARG0', 'B-V', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O']},
{'verb': 'worked', 'description': 'yeah i know and i did that all through college and [ARG1: it] [V: worked] [ARGM-ADV: too]', 'tags': ['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-ARG1', 'B-V', 'B-ARGM-ADV']}], 'words': ['yeah', 'i', 'know', 'and', 'i', 'did', 'that', 'all', 'through', 'college', 'and', 'it', 'worked', 'too']}

Expected Output：
{"verbs": [{"verb": "know", "description": "yeah [ARG0: i] [V: know] and i did that all through college and it worked too", "tags": ["O", "B-ARG0", "B-V", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O"]},
{"verb": "did", "description": "yeah i know and [ARG0: i] [V: did] [ARG1: that] [ARGM-TMP: all through college] and it worked too", "tags": ["O", "O", "O", "O", "B-ARG0", "B-V", "B-ARG1", "B-ARGM-TMP", "I-ARGM-TMP", "I-ARGM-TMP", "O", "O", "O", "O"]},
{"verb": "worked", "description": "yeah i know and i did that all through college and [ARG0: it] [V: worked] [ARGM-ADV: too]", "tags": ["O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "B-ARG0", "B-V", "B-ARGM-ADV"]}], "words": ["yeah", "i", "know", "and", "i", "did", "that", "all", "through", "college", "and", "it", "worked", "too"]}

**Comment by matt-gardner** [comment]
This is due to a spacy version difference.  See, e.g., https://github.com/allenai/allennlp/issues/4337, https://github.com/allenai/allennlp/issues/3418#issuecomment-585251913.
