### ISSUE TITLE
Logging Learning Rate 

### ISSUE THREAD

**Issue by pasinit** [allenai/allennlp#4404]
Is there an easy way to log the learning rate (especially when using a scheduler) within the training progress bar?

**Comment by epwalsh** [comment]
Hey @pasinit, this could be possible if we passed batch metrics to `BatchCallback` (which for some reason we don't do right now). Then you could just have a `BatchCallback` that adds the LR statistics to the batch metrics dictionary.

**Comment by epwalsh** [comment]
If anyone wants to make a PR for passing batch metrics to batch callbacks, feel free to.

**Comment by pasinit** [comment]
Ok thanks. I've looked at the places where the code should be changed and these are very minimal changes. Does something like this still require a unit test?

**Comment by epwalsh** [comment]
I don't think this would require a test since we already have enough tests that run the trainer, and therefore would cover this change.
