### ISSUE TITLE
Is there any guide that writes a script to use trained model to predict?

### ISSUE THREAD

**Issue by nine09** [allenai/allennlp#4405]
## Checklist

- [x] I have read the relevant section in the [contribution guide](https://github.com/allenai/allennlp/blob/master/CONTRIBUTING.md#bug-fixes-and-new-features) on reporting bugs.
- [x] I have checked the [issues list](https://github.com/allenai/allennlp/issues) for similar or identical bug reports.
- [x] I have included in the "Description" section below a traceback from any exceptions related to this bug.

## Description

<details>
<summary><b>
I am looking forward to write a script to use my trained model do prediction. But I cannot find any tutorial about how to predict by a trained model with a scripts rather than command line.
</b>

In fact I saw examples to define a predictor and use it to predict. However, it takes the model and the data_reader as argument, and I define both of them by a json config file.

After use `allennlp.commands.train.train_model_from_file` and a config file, I get the best model. Now I want write a script to use it do prediction. So, does I have to new a data_reader instance by hand rather than by a config file to feed to the predicator?

Is any tutorial that explain how to solve the mentioned problem?

The config json of the training procedure is as follow:
```
{
  "dataset_reader": {
    "type": "qamr_pred",
    "source_tokenizer": {
      "type": "pretrained_transformer",
      "model_name": "bert-base-cased",
      "add_special_tokens": true
    },
    "source_token_indexer": {
      "tokens": {
        "type": "pretrained_transformer_mismatched",
        "model_name": "bert-base-cased"
      }
    }
  },
  "validation_dataset_reader": {
    "type": "qamr_pred",
    "source_tokenizer": {
      "type": "pretrained_transformer",
      "model_name": "bert-base-cased",
      "add_special_tokens": true
    },
    "source_token_indexer": {
      "tokens": {
        "type": "pretrained_transformer_mismatched",
        "model_name": "bert-base-cased"
      }
    }
  },
  "train_data_path": "data/pred_data/train.txt",
  "validation_data_path": "data/pred_data/dev.txt",
  "model": {
    "type": "o",
    "embedder": {
      "token_embedders": {
        "tokens": {
          "type": "pretrained_transformer_mismatched",
          "model_name": "bert-base-cased",
          "train_parameters": true
        }
      }
    },
    "metric_in_training": {
      "accuracy": {
        "type": "categorical_accuracy"
      },
      "f1": {
        "type": "fbeta",
        "average": "micro"
      }
    }
  },
  "data_loader" : {
    "sampler": {
      "type": "random"
    },
    "batch_size": 32,
    "drop_last": true
  },
  "trainer": {
    "num_epochs": 6,
    "cuda_device": 0,
    "validation_metric": "+f1",
    "optimizer": {
      "type": "huggingface_adamw",
      "parameter_groups": [
        [["embedder"], {"lr": 2e-5, "t_total": 50000, "warmup": 0.1}],
        [["^((?!embedder).)*$"], {"lr": 1e-3}]
      ],
      "lr": 1e-3
    },
    "checkpointer": {
      "num_serialized_models_to_keep": 2
    }
  }
}
```
</summary>

**Comment by matt-gardner** [comment]
I *think* all you need to do is `predictor = Predictor.from_archive("/path/to/saved/archive/file.tar.gz")`.  Then you can use the predictor in your script however you want.  Does that work for you?

**Comment by nine09** [comment]
> I _think_ all you need to do is `predictor = Predictor.from_archive("/path/to/saved/archive/file.tar.gz")`. Then you can use the predictor in your script however you want. Does that work for you?

Thanks for your immediate replay. I successfully build a predictor by your codes:
```
predictor = Predictor.from_path("file.tar.gz")
```
But when I use the predictor by `predictor.predict` there is an NotInplementedError, this is because the predictor is a default Predictor and the predict function is not defined yet.

Then I use the `SentenceTaggerPredictor` Predictor which has the defined `predict` function:
```
predictor=SentenceTaggerPredictor.from_path(''file.tar.gz")
```
But it return a default Predictor also and the there is no `predict` function obviously.

So I still have no idea that how to use the archiev file to initialize a custom Predictor and use it to predict.

**Comment by matt-gardner** [comment]
If you look at [the documentation for `Predictor`](http://docs.allennlp.org/master/api/predictors/predictor/#from_path), you'll see that there's a `predictor_name` argument to `from_path`.  The predictor name for `SentenceTaggerPredictor` is ["sentence_tagger"](http://docs.allennlp.org/master/api/predictors/sentence_tagger/#sentencetaggerpredictor-objects).

But I'm a bit confused about your second line of code - that looks to me like it should return an instance of `SentenceTaggerPredictor`, not `Predictor`.  Are you sure it's returning just a `Predictor`?
