### ISSUE TITLE
Allennlp Predictor code giving an error.

### ISSUE THREAD

**Issue by mmb1793** [allenai/allennlp#4408]
Hi,
I am trying to run the following code -
from allennlp.predictors.predictor import Predictor
predictor = Predictor.from_path("https://s3-us-west-2.amazonaws.com/allennlp/models/bidaf-model-2017.09.15-charpad.tar.gz")

but it is giving me an error -
![image](https://user-images.githubusercontent.com/67561966/85959288-145dc780-b9b9-11ea-82fc-3f3c57f1fe6c.png)

I have tried installing the packages multiple times - both pytorch and allennlp, but i am unable to resolve this issue.

**Comment by matt-gardner** [comment]
What if you just run `import spacy`, `import torch`, and `import numpy` from a python interpreter?  Do they work?  It looks to me like they would fail, and this is a problem with your local environment.  Can you check that?
