### ISSUE TITLE
ElmoEmbedder seem missing from new version

### ISSUE THREAD

**Issue by pinedbean** [allenai/allennlp#4409]
ElmoEmbedder seem missing from new version, how can I get embedding from ELMo (already have hdf5 weight)

**Comment by BertieJim** [comment]
same problem

**Comment by matt-gardner** [comment]
See here: https://github.com/allenai/allennlp/issues/4384. If you have a more specific question that's not addressed by that, or by our intro material in the [guide](https://guide.allennlp.org/representing-text-as-features), please open a new issue.
