### ISSUE TITLE
QANet in allennlp-models still used the old version of regularizer

### ISSUE THREAD

**Issue by pengshuang** [allenai/allennlp#4419]
As the ``Upgrade guide from v0.9.0`` said:

Regularization now needs another key in a config file. Instead of specifying regularization as ``"regularizer": [[regex1, regularizer_params], [regex2, regularizer_params]]``, it now must be specified as "regularizer": ``{"regexes": [[regex1, regularizer_params], [regex2, regularizer_params]]}``(https://github.com/allenai/allennlp/releases/tag/v1.0.0).

But I find that the training_config of qanet still used the old version of ``regularizer``

see:
https://github.com/allenai/allennlp-models/blob/37136f8ecbc42d26d9b135d06e4042f22d0d1bee/training_config/rc/qanet.jsonnet#L114.

**Comment by matt-gardner** [comment]
Yep, this is a bug.  Not sure how we missed this.  Care to submit a PR to fix it?

**Comment by pengshuang** [comment]
Thanks. I am glad to submit a PR.

**Comment by matt-gardner** [comment]
Awesome, thanks.
