### ISSUE TITLE
Transformer Toolkit

### ISSUE THREAD

**Issue by dirkgr** [allenai/allennlp#4424]
We want a collection of modules that form the building blocks of transformers, such as
 * self-attention
 * layer norm
 * feed-forward
 * positional embeddings
 * maybe memory layers like https://arxiv.org/abs/1907.05242?
(Not all of these really require code by themselves.)

We also want some useful combinations of these, like a combination of self-attention, layer-norm, and feed-forward, which forms one standard BERT layer.

Finally, we want a way of loading these and initializing them flexibly with huggingface weights.

For example, imagine a scenario where we run the first six layers of BERT-Large, then add in a memory layer, six more layers, and then some information from another modality. How would we configure this? How can we make this easy?

**Comment by jiasenlu** [comment]
do we want to focus on BERT? which transformer models in your mind we should include for now?

**Comment by dirkgr** [comment]
I don't think it matters much, since the way to load weights will be quite similar between the different models. That said, let's start with BERT and RoBERTa, and go from there?

**Comment by dirkgr** [comment]
Matt has a bunch of code for this in https://github.com/allenai/allennlp/pull/4423. The work for this issue is about pulling that out into its own set of reusable modules.

**Comment by dirkgr** [comment]
@AkshitaB, can we close this issue and open new, more detailed ones, for what we find is left to do on the toolkit?
