### ISSUE TITLE
Flexible and configurable data loading and pre-processing

### ISSUE THREAD

**Issue by dirkgr** [allenai/allennlp#4425]
In #4420 I put a sketch of what this could look like. That PR (right now) reads a static config for preparing images and produces `Instance`s that contain a `DetectronField`. AllenNLP knows how to handle that field so that the data arrives in the `Model.forward()` method in the right shape.

This issue is about making the data loading and pre-processing story configurable. I imagine we'll replace the hard-coding in #4420 with something that reads the config from the config files (i.e., from data loader parameters to `__init__()`), and produces data accordingly. At some point we'll factor out that part of the code so we can use it in multiple data loaders, for different data sets.

**Comment by matt-gardner** [comment]
I think it probably makes more sense to have transforms, instead of what's done for data here.  We should have a more in-depth conversation about options for doing this.  The way that detectron reader works makes me think that if you want that you should just be using detectron instead of allennlp.

**Comment by jiasenlu** [comment]
I think we should have our own data-preprocessing configurations and code for images. (by reusing detectron2 functions). We will need the data-loading the preprocessing configurable when adding other features (such as multi-task).
