### ISSUE TITLE
Add an ImageEncoder abstraction, and a DetectronImageEncoder implementation of it

### ISSUE THREAD

**Issue by dirkgr** [allenai/allennlp#4426]
#4420 loads up a detectron model and runs it, but it hard-codes which model it loads and how it's configured. This issue is about making this flexible and configurable. I want to be able to say in the configuration file something like this:

```
...
model: {
    "type": "my-vqa-model",
    "image_encoder": {
        "type": "detectron",
        "config": "COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml"
    }
}
...
```

In order to set parameters individually (and not just load a yaml file), it would look like this:
```
...
model: {
    "type": "my-vqa-model",
    "image_encoder": {
        "type": "detectron",
        "config": "COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml",    // load defaults from built-in files
        "model": {"resnets": {"depth": 100}},    // override some values, mapping 1:1 to detectron configs
    }
}
...
```

**Comment by matt-gardner** [comment]
Yes, I agree that the configuration you're talking about looks right to me.  I would maybe rename the issue to something like `Add an ImageEncoder abstraction, and a DetectronImageEncoder implementation of it`.

**Comment by dirkgr** [comment]
Since we're preparing the images in the reader for now, I don't think we need this anymore.

**Comment by matt-gardner** [comment]
I think that we'll want this eventually, just maybe not in our first version.
