### ISSUE TITLE
PretrainedModelInitializer fails to initialize a model with a 0-dim tensor

### ISSUE THREAD

**Issue by reiyw** [allenai/allennlp#4427]
## Checklist

- [x] I have verified that the issue exists against the `master` branch of AllenNLP.
- [x] I have read the relevant section in the [contribution guide](https://github.com/allenai/allennlp/blob/master/CONTRIBUTING.md#bug-fixes-and-new-features) on reporting bugs.
- [x] I have checked the [issues list](https://github.com/allenai/allennlp/issues) for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/allenai/allennlp/pulls) for existing proposed fixes.
- [x] I have checked the [CHANGELOG](https://github.com/allenai/allennlp/blob/master/CHANGELOG.md) and the [commit log](https://github.com/allenai/allennlp/commits/master) to find out if the bug was already fixed in the master branch.
- [x] I have included in the "Description" section below a traceback from any exceptions related to this bug.
- [x] I have included in the "Related issues or possible duplicates" section below all related issues and possible duplicate issues (If there are none, check this box anyway).
- [x] I have included in the "Environment" section below the name of the operating system and Python version that I was using when I discovered this bug.
- [x] I have included in the "Environment" section below the output of `pip freeze`.
- [x] I have included in the "Steps to reproduce" section below a minimally reproducible example.

## Description

<details>
<summary><b>Python traceback:</b></summary>
<p>

```
Traceback (most recent call last):
  File "test.py", line 27, in <module>
    applicator(net)
  File "/Users/reiyw/.ghq/ghq/github.com/allenai/allennlp/allennlp/nn/initializers.py", line 482, in __call__
    initializer(parameter, parameter_name=name)
  File "/Users/reiyw/.ghq/ghq/github.com/allenai/allennlp/allennlp/nn/initializers.py", line 406, in __call__
    tensor.data[:] = source_weights[:]
IndexError: slice() cannot be applied to a 0-dim tensor.
```

</p>
</details>

`PretrainedModelInitializer` fails to initialize a model with 0-dim tensors. The error occurs at:
https://github.com/allenai/allennlp/blob/637dbb159082999c546ac2fc64746b88e5c9d1b5/allennlp/nn/initializers.py#L405-L406
The cause is that slicing cannot be applied to a 0-dim tensor. Instead of slicing a tensor here, we can avoid the error by using `copy_` method:
```
tensor.data.copy_(source_weights.data)
```
I have confirmed that this change will not break the pretrained model initializer test.

Another workaround is to use a 1-dim tensor instead of a 0-dim tensor to represent a scalar, but I think it's better to fix it so that others don't face the same problem.

If that change is appropriate, I would be happy to submit a PR.

## Related issues or possible duplicates

- None

## Environment

OS: OS X

Python version: 3.7.7

<details>
<summary><b>Output of <code>pip freeze</code>:</b></summary>
<p>

```
-e git+ssh://git@github.com/allenai/allennlp.git@9c4dfa544e85e00d636beb0026a08e40dcdb6404#egg=allennlp
apex @ git+https://github.com/NVIDIA/apex.git@44532b30a4fad442f00635a0f4c8f241b06c2315
appdirs==1.4.4
attrs==19.3.0
black==19.10b0
bleach==3.1.5
blis==0.4.1
boto3==1.14.12
botocore==1.17.12
catalogue==1.0.0
certifi==2020.6.20
chardet==3.0.4
click==7.1.2
codecov==2.1.7
colorama==0.4.3
coverage==5.1
cycler==0.10.0
cymem==2.0.3
docutils==0.15.2
filelock==3.0.12
flake8==3.8.3
flaky==3.6.1
future==0.18.2
h5py==2.10.0
idna==2.10
importlib-metadata==1.7.0
Jinja2==2.11.2
jmespath==0.10.0
joblib==0.15.1
jsonnet==0.16.0
jsonpickle==1.4.1
keyring==21.2.1
kiwisolver==1.2.0
livereload==2.6.2
lunr==0.5.8
Markdown==3.2.2
markdown-include==0.5.1
MarkupSafe==1.1.1
matplotlib==3.2.2
mccabe==0.6.1
mkdocs==1.1.2
mkdocs-material==5.3.3
mkdocs-material-extensions==1.0
more-itertools==8.4.0
murmurhash==1.0.2
mypy==0.782
mypy-extensions==0.4.3
nltk==3.5
nr.collections==0.0.1
nr.databind.core==0.0.16
nr.databind.json==0.0.11
nr.interface==0.0.3
nr.metaclass==0.0.5
nr.parsing.date==0.1.0
nr.pylang.utils==0.0.3
nr.stream==0.0.4
numpy==1.19.0
overrides==3.1.0
packaging==20.4
pathspec==0.8.0
pathtools==0.1.2
pkginfo==1.5.0.1
plac==1.1.3
pluggy==0.13.1
preshed==3.0.2
protobuf==3.12.2
py==1.9.0
py-cpuinfo==6.0.0
pycodestyle==2.6.0
pyflakes==2.2.0
Pygments==2.6.1
pymdown-extensions==7.1
pyparsing==2.4.7
pytest==5.4.3
pytest-benchmark==3.2.3
pytest-cov==2.10.0
python-dateutil==2.8.1
PyYAML==5.3.1
readme-renderer==26.0
regex==2020.6.8
requests==2.24.0
requests-toolbelt==0.9.1
responses==0.10.15
rfc3986==1.4.0
ruamel.yaml==0.16.10
ruamel.yaml.clib==0.2.0
s3transfer==0.3.3
sacremoses==0.0.43
scikit-learn==0.23.1
scipy==1.5.0
sentencepiece==0.1.91
six==1.15.0
spacy==2.3.0
srsly==1.0.2
tensorboardX==2.0
thinc==7.4.1
threadpoolctl==2.1.0
tokenizers==0.7.0
toml==0.10.1
torch==1.5.1
tornado==6.0.4
tqdm==4.47.0
transformers==2.11.0
twine==3.2.0
typed-ast==1.4.1
typing-extensions==3.7.4.2
urllib3==1.25.9
wasabi==0.7.0
wcwidth==0.2.5
webencodings==0.5.1
zipp==3.1.0
```

</p>
</details>

## Steps to reproduce

<details>
<summary><b>Example source:</b></summary>
<p>

```
import tempfile
import pathlib

import torch

from allennlp.nn import InitializerApplicator
from allennlp.nn.initializers import PretrainedModelInitializer


class Net(torch.nn.Module):
    def __init__(self):
        super().__init__()
        # 0-dim tensor
        self.scalar = torch.nn.Parameter(torch.tensor(1.0))


net = Net()
temp_dir = pathlib.Path(tempfile.mkdtemp())
weights_file = temp_dir / "weights.th"
torch.save(net.state_dict(), weights_file)

initializer = PretrainedModelInitializer(weights_file)
applicator = InitializerApplicator([("scalar", initializer)])
applicator(net)
```

</p>
</details>

**Comment by matt-gardner** [comment]
Yep, you're right, this looks like a bug to me, and I agree with your fix of just using `copy_`.  Can you submit a PR, adding your minimal repro as a test case so we don't have a regression?

**Comment by reiyw** [comment]
Ok, I'll submit a PR within a day or two.
