### ISSUE TITLE
allowed_start_transitions and allowed_end_transitions don't actually enforce their constraints

### ISSUE THREAD

**Issue by zhuango** [allenai/allennlp#4429]
I working on a project that uses [viterbi_decode ](https://github.com/allenai/allennlp/blob/master/allennlp/nn/util.py#L403) function in allennlp.nn.util. viterbi_decode function has _allowed_start_transitions_/_allowed_end_transitions_ parameters, which aim to enable viterbi decoding process to take the start/end timestep restriction into account. But how it works confuses me.

Follows are what I learned from viterbi_decode code. _path_score_ is initialized with tag_sequence[0] which is a zero vector when _has_start_end_restrictions_ is true. When calculating the _score_ for the first time step through a topk op on _path_score_ + _transition_matrix_, the state of previous timestep (_paths_) is depend on _transition_matrix_ and not restricted on "start". 

For an extreme case, the first timestep cannot be any state and _allowed_start_transitions_ are all -inf. Normally, the _score_ of the first timestep is -inf vector because no state is allowed at first timestep. But topk op on _path_score_ + _transition_matrix_  could still get non-inf _score_ and non-start _paths_of previous time step. Because there are potentials bigger than -inf and those corresponding previous states will be append to _paths_ which is not "start" state. The _allowed_start_transitions_ is not working ?
So it confuses me. Please help me to understand how does the _allowed_start_transitions_/_allowed_end_transitions_  actually work.

**Comment by matt-gardner** [comment]
I'm going to give you a minimal explanation, but feel free to ask more questions if this isn't enough.

The place to look for an example for how this is used is our SRL model: [here](https://github.com/allenai/allennlp-models/blob/11c6814a1de2908ab34794640411c1c5f879705d/allennlp_models/structured_prediction/models/srl.py#L370-L372) and [here](https://github.com/allenai/allennlp-models/blob/11c6814a1de2908ab34794640411c1c5f879705d/allennlp_models/structured_prediction/models/srl.py#L419-L439). There, you will see that we set all allowed transitions to have a score of `0` in the transition matrix, and all disallowed transitions to have a score of `float('-inf')`.  Because we're adding log probabilities inside of `viterbi_decode`, a score of `float('-inf')` means that any path through that transition will get a score of `float('-inf')`, or a probability of `0`.

**Comment by zhuango** [comment]
Hi @matt-gardner, Thanks for your explanation very much. I'm just working on SRL model. As you mentioned, disallowed transitions will have a score of float('-inf'). Following is a simple example that confuses me:

Transition matrix (add allowed_start_transitions/allowed_end_transitions, [code](https://github.com/allenai/allennlp/blob/master/allennlp/nn/util.py#L467-L496)):
![image](https://user-images.githubusercontent.com/5491519/86305844-3cf9f180-bc45-11ea-8de4-5f751e5173c8.png)

Predictions/transposed tag_sequence matrix (append start and end zero_sentinel, and extra_tags_sentinel, [code](https://github.com/allenai/allennlp/blob/master/allennlp/nn/util.py#L509-L515)):
![image](https://user-images.githubusercontent.com/5491519/86306212-3f108000-bc46-11ea-8e27-72df6cd49ec9.png)

In the above example, 'start' cannot transfer to '0' and '1' cannot transfer to '1'.
path_scores is initialized with tag_sequence[0] which is zero vector. Follow this [code](https://github.com/allenai/allennlp/blob/master/allennlp/nn/util.py#L528-L555), when run into the first timestep：
timestep = 1
summed_potentials = path_scores[timestep -1] + transition_matrix = path_scores[0] + transition_matrix = transition_matrix 
So,
scores = [0.0, 0.0, -inf, 0.0] (top1 of each column)
paths = [0, 0, 0, 0]
path_scores[1] = tag_sequence[timestep, :] + scores = [0.8, 0.2, -inf, -inf]
path_indices[1] = paths  = [0, 0, 0, 0]
However, as I understand, with the restriction " 'start' cannot transfer to '0' ", path_scores[1][0] should be -inf because 1st timestep cannot be state '0'. And path_indices[1], 1st timestep's previous state should always be 'start' state. That is what confuses me. Do I miss something? Look forward to your replay. Thanks.

**Comment by matt-gardner** [comment]
What you're missing is the broadcasting that's happening.  Your set of equations for `summed_potentials` is wrong, because it doesn't account for the `.unsqueeze()` that happens, and the associated broadcasting.  I'd recommend stepping through the execution of that code with your toy example to see exactly what happens; it's more complicated than it looks at first glance.

**Comment by zhuango** [comment]
Thanks @matt-gardner, I notice the broadcasting. And I checked the toy example above. Following is my code. And the path it got is [0,1] when I set allowed_start_transitions=[-math.inf, 0.0] meaning first timestep cannot be 0.
```
import math
import torch
from allennlp.nn.util import viterbi_decode

t_m = torch.Tensor([
    [0.0, 0.0], 
    [0.0, -math.inf]])
start_allowed = torch.Tensor([-math.inf, 0.0])

predictions = torch.Tensor([
        [0.8, 0.2], 
        [0.1, 0.9]])

res = viterbi_decode(predictions, t_m, allowed_start_transitions=start_allowed)
# output: ([0, 1], 1.7)
print(res)
```

**Comment by zhuango** [comment]
And I try another extreme case, start_allowed = [-math.inf, -math.inf]. I got same output ([0, 1], 1.7). 

```
import math
import torch
from allennlp.nn.util import viterbi_decode

t_m = torch.Tensor([
    [0.0, 0.0], 
    [0.0, -math.inf]])
**start_allowed = torch.Tensor([-math.inf, -math.inf])**

predictions = torch.Tensor([
        [0.8, 0.2], 
        [0.1, 0.9]])

res = viterbi_decode(predictions, t_m, allowed_start_transitions=start_allowed)
# output: ([0, 1], 1.7)
print(res)
```

**Comment by zhuango** [comment]
I also check the _allowed_end_transitions_ parameter which has the same problem. Here is my code:
```
import math
import torch
from allennlp.nn.util import viterbi_decode

t_m = torch.Tensor([
    [0.0, 0.0], 
    [0.0, -math.inf]])
start_allowed = torch.Tensor([0.0, 0.0])
end_allowed = torch.Tensor([0.0, -math.inf])

predictions = torch.Tensor([
        [0.8, 0.2], 
        [0.1, 0.9]])

res = viterbi_decode(predictions, t_m, allowed_start_transitions=start_allowed, allowed_end_transitions=end_allowed)
# output: ([0, 1], 1.7)
# excepted output : ([0, 0], 0.9)
print(res)
```
I add a restriction on end position (cannot end with '1' state, end_allowed = torch.Tensor([0.0, -math.inf])), and eliminate the start_allowed to allow any state at first timestep. So the first timestep would be '0' state because it has a higher log prob. And the second/end timestep can only be '0'. In the end, I except output ([0, 0], 0.9). But viterbi_decode output ([0,1], 1.7), which seems to ignore the end_allowed.

And I change [this line](https://github.com/allenai/allennlp/blob/master/allennlp/nn/util.py#L514) to
```
# Only allow the 'end' state after the last actual timestep.
end_sentinel = torch.ones(1, num_tags) * -math.inf
end_sentinel[0][-1] = 0.0
tag_sequence = torch.cat([zero_sentinel, tag_sequence, end_sentinel], 0)
```
Then I got expected output ([0,0], 0.9). I use end_allowed as SRL model did.

**Comment by matt-gardner** [comment]
Ok, sorry for being obtuse earlier, I was trying to go too fast through the issues, and assumed the code was right and didn't pay enough attention to the points you made.  With your additional explanations, I now understand and agree with what you're saying.  I went back and looked at when that code got added, and I think it just never did what it was supposed to.

Can you submit a PR to change those sentinel valus?

**Comment by zhuango** [comment]
Sorry, I just find that the reason for the output in my last post is that I neglect the _tag_observations_. _allowed_start_transitions_ and _allowed_end_transitions_ work well when tag_observations is set at [this line](https://github.com/allenai/allennlp/blob/master/allennlp/nn/util.py#L510) and [this line](https://github.com/allenai/allennlp/blob/master/allennlp/nn/util.py#L520-L523), which can keep the first and the last state to be "start" and "end", respectively. Although the extreme case still fails, nobody would do that in practice. Thanks for your attention on this issue. I am really appreciated!

**Comment by matt-gardner** [comment]
Hmm, ok, I see now where I also missed something :).  Looks like this code could use some better comments in general, because the logic is not obvious.  I looked at it several times over the course of this discussion and missed things each time.
