### ISSUE TITLE
How to add hand-craft feature in seq2seq model ?

### ISSUE THREAD

**Issue by wlhgtc** [allenai/allennlp#4432]
Hi there,
 I'm using allennlp for seq2seq task. And I use the `copynet_seq2seq`  .
Here are  part of my configs:

    "type":"copynet-seq2seq", 
    "source_token_indexers": {
      "tokens": {
        "type": "single_id",
        "namespace": "source_tokens",
        "lowercase_tokens": true
      }
    },
     ....

I wonder if I want use pos(of a word) as another feature. How could I do it ?
 Should I add another `indexers` like:

    "type":"copynet-seq2seq", 
    "source_pos_indexers": {
      "pos": {
        "type": "single_id",
        "namespace": "source_tokens",
        "lowercase_tokens": true
      }
    },
     ....

Or I could add it together?

    "type":"copynet-seq2seq", 
    "source_token_indexers": {
      "pos": {
        "type": "single_id",
        "namespace": "source_tokens",
        "lowercase_tokens": true
      }
      "tokens": {
        "type": "single_id",
        "namespace": "source_tokens",
        "lowercase_tokens": true
      }
    },
     ....

And do I have to use same `namespace` between them ?

@matt-gardner  I saw your reply in #3091 , but the link is out of date. Could you help me ?

**Comment by matt-gardner** [comment]
See [here](https://guide.allennlp.org/representing-text-as-features#3), particularly the part where it talks about combining multiple indexers.  If that isn't enough to solve your issue, feel free to ask more questions.

**Comment by wlhgtc** [comment]
Thanks for the fast response.  Seem I could use code as follows ( for any features ):
```
token_indexers = {
    'tokens': SingleIdTokenIndexer(namespace='token_vocab'),
    'feature_1': SingleIdTokenIndexer(namespace='feature_1_vocab', feature_name='tag_'),
    'feature_2: SingleIdTokenIndexer(namespace='feature_2_vocab', feature_name='dep_'), 
}
```

Actually, the code that makes me confused is :
```
text_field = TextField(tokens, token_indexers)
```
The `token_indexers` (may) contains many Indexer,  but `tokens`  seems contains only the word.
But  when I find the definition of `Token` in [https://github.com/allenai/allennlp/blob/master/allennlp/data/tokenizers/token.py#L6](url)

I got it : I could match their relationship by `feature_name` and `Token`'s attribute.  Am I right ?

Finally , I’m stilled confused the variable `namespace`, why we need things like that ?
Cause the `tokens` in same `namespace` could share the vocab ? Or any other consideration ？

**Comment by matt-gardner** [comment]
Yes, there are several possible attributes of `Token` which can be used by the token indexer (and you can even set your own if you subclass `Token`).  It now seems a little bit odd to me to store POS tags and such on the `Token` object, but we did it this way because the main tokenizer we used was spacy's tokenizer, and that had the option of producing `Token` objects with these attributes, so we ran with it.

For your vocabulary questions, see [here](https://guide.allennlp.org/reading-data#3).
