### ISSUE TITLE
Type hint error

### ISSUE THREAD

**Issue by Zessay** [allenai/allennlp#4433]
In the 94 line of the file `allennlp/allennlp/data/fields/text_field.py`, the output type should be `TextFieldTensors` rather than `Dict[str, torch.Tensor]`. Python doesn't inspect whether the type of the parameter is right, while I think it is important for us to understand the code. 

![image](https://user-images.githubusercontent.com/39905704/86354090-fd5df480-bc9a-11ea-9dcf-66bc9fc4f02c.png)

**Comment by matt-gardner** [comment]
Thanks for reporting this!
