### ISSUE TITLE
Stop logging regularization loss of 0

### ISSUE THREAD

**Issue by dirkgr** [allenai/allennlp#4436]
We now log (and show during training) the regularization loss. But in many configs, that loss is always 0. We should not show it in that case, at least not on the console.

**Comment by mateuszpieniak** [comment]
Btw, @dirkgr When I add `weight_decay` to my optimizer (e.g. Adam), then do I need to use `RegularizerApplicator`? I've just discovered that I only used `weight_decay` for optimizer in my config file. Reported `reg_loss` == 0 drew my attention that perhaps I have a bug?

**Comment by dirkgr** [comment]
Hmm, this is a little bit confusing. When you use the `weight_decay` option of Adam, the regularization is applied directly in the optimizer. It bypasses the loss calculation, so there is no `reg_loss` reported when you do this. This is correct and you don't need to use the applicator.
