### ISSUE TITLE
Add new attribute in Token class

### ISSUE THREAD

**Issue by Zessay** [allenai/allennlp#4437]
In the dialogue task of NLP, we often need to know turn id  or role id so that we can get the turn embedding or role embedding of a token. In current `Token` class, the attributes are fixed. And we need to rewrite a subclass of `Token` to add our own attributes,  which is inconvenient. We 
might need to fix all of the `Tokenizer`, `TokenIndexer` and `TokenEmbedder`, just because of one extra attribute.

I think it is necessary to add a new attribute to the `Token` whose type is `Dict[str, Any]`, or use `**kwargs` and `setattr`, so that we can add our own attribute to token according to specific task. Of course, there may be other solution to this problem which doesn't need to fix `Token`,  while I still think extra info of a token is necessary. 

Hope you can think about this problem.

**- Solution 1: use `**kwargs` and `setattr`**

 
![image](https://user-images.githubusercontent.com/39905704/86440889-dc9aab00-bd3d-11ea-8872-1802ae5bafae.png)

If we use this solution, we can't use `__slots__`, because we are not sure what attributes will be added. Because we remove `__slots__`, we can add attributes dynamically.

**- Solution 2: add a new attribute whose type is `Dict[str, Any]`**

![image](https://user-images.githubusercontent.com/39905704/86441178-6185c480-bd3e-11ea-8438-f2f870165329.png)

With this solution, we can still use `__slots__`,  just need to add `'extra_info'` in it.

**Comment by bratao** [comment]
I had this problem before, and solved by setting Token as a dataclass. You can see on this PR https://github.com/allenai/allennlp/pull/3769

But an optimization latter (https://github.com/allenai/allennlp/pull/4312) set as slots.
But it was easy enough to extend the class to support the attributes you need, such as:
```
class TokenWithStyle(Token):
    __slots__ = ["is_bold"]

    is_bold: bool

    def __init__(self, text: str = None, is_bold: bool = False):
        super().__init__(text=text)
        self.is_bold = is_bold

```

**Comment by Zessay** [comment]
> I had this problem before, and solved by setting Token as a dataclass. You can see on this PR #3769
> 
> But an optimization latter (#4312) set as slots.
> But it was easy enough to extend the class to support the attributes you need, such as:
> 
> ```
> class TokenWithStyle(Token):
>     __slots__ = ["is_bold"]
> 
>     is_bold: bool
> 
>     def __init__(self, text: str = None, is_bold: bool = False):
>         super().__init__(text=text)
>         self.is_bold = is_bold
> ```

Yes, I am using this solution in my own code. While I think this is not elegant, if we define a subclass,  we may need to rewrite `Tokenizer` and `TokenIndexer` so that we can add new attributes in our `DataReader`, which is not convenient. Thus, I think the `Token` class should allow us to add new attributes according to specific task, this will be more flexible.

**Comment by matt-gardner** [comment]
You should be able to just do something like `tokens = [MyToken(token.text, ...) for token in tokens]` in your dataset reader.  You shouldn't have to override tokenizers or token indexers at all.

**Comment by Zessay** [comment]
> You should be able to just do something like `tokens = [MyToken(token.text, ...) for token in tokens]` in your dataset reader. You shouldn't have to override tokenizers or token indexers at all.

Thanks for your reply ! This is actually a good solution without modifying the `Token` class.
