### ISSUE TITLE
A parameter problem

### ISSUE THREAD

**Issue by Zessay** [allenai/allennlp#4438]
In the file `pretrained_transformer_mismatched_embedder.py`, there is a `*` in the `__init__` (line 43). I haven't seen this parameter before (only know `*args` and `**kwargs`), and can't understand the use of this here.  Could you please explain the usage of this parameter? Thank you!

**Comment by matt-gardner** [comment]
It forces all following arguments to be passed by name (with the idea of minimizing accidental order swaps for long argument lists).  https://stackoverflow.com/questions/14301967/bare-asterisk-in-function-arguments
