### ISSUE TITLE
where is part of speech and proper name category label collection?

### ISSUE THREAD

**Issue by hugess** [allenai/allennlp#4441]
A list like this:
https://github.com/baidu/lac

标签 | 含义 | 标签 | 含义 | 标签 | 含义 | 标签 | 含义
-- | -- | -- | -- | -- | -- | -- | --
n | 普通名词 | f | 方位名词 | s | 处所名词 | nw | 作品名
nz | 其他专名 | v | 普通动词 | vd | 动副词 | vn | 名动词
a | 形容词 | ad | 副形词 | an | 名形词 | d | 副词
m | 数量词 | q | 量词 | r | 代词 | p | 介词
c | 连词 | u | 助词 | xc | 其他虚词 | w | 标点符号
PER | 人名

I didn't find such instructions in the AllenNlP's doc
Is it consistent with baidu/lac?

**Comment by matt-gardner** [comment]
What model are you talking about?  The label space used depends on the data used to train the model.  For POS tags, we typically use spaCy to predict those.  Other syntax labels most often ultimately derive from the Penn Treebank.

**Comment by hugess** [comment]
> What model are you talking about? The label space used depends on the data used to train the model. For POS tags, we typically use spaCy to predict those. Other syntax labels most often ultimately derive from the Penn Treebank.

Ok clear！ ths
