### ISSUE TITLE
Restrict the version of `boto3` for package manager

### ISSUE THREAD

**Issue by tamuhey** [allenai/allennlp#4450]
Now allennlp depends on `boto3==*`, which sometimes causes a package manager `poetry` to get stuck in dependency resolution (see https://github.com/python-poetry/poetry/issues/771#issuecomment-630677036).
Users can avoid this by specifying `boto3` dependency, but it is not trivial.

I think it's good to rewrite the below line to, for example, `boto3>=1.14`

https://github.com/allenai/allennlp/blob/5b988d637d9d2fde405eb0d0bc22b3bdb4012ad2/setup.py#L60

**Comment by epwalsh** [comment]
Ugh, for any project that uses boto3, botocore, or awscli there is almost always a dependency conflict for some reason 🤦 

Would you mind submitting a pull request for this?
