### ISSUE TITLE
Retrain transformer-based models in allennlp_models.pretrained

### ISSUE THREAD

**Issue by epwalsh** [allenai/allennlp#4457]
Updates from the new transformers/tokenizers release has broken some of these.

- [x] Fine-grained NER transformer
- [x] RoBERTa SNLI @epwalsh - https://beaker.org/ex/ex_3xaw1xzw6689/tasks/tk_zxz18n8idbn0
- [x] RoBERTa MNLI @epwalsh - https://beaker.org/ex/ex_jbf2biqowfwa/tasks/tk_28u7smfn77o9
- [x] BERT SRL
- [x] RoBERTa SST @AkshitaB

**Comment by dirkgr** [comment]
I started doing BERT SRL too because I already had the environment for that spun up.

**Comment by dirkgr** [comment]
@AkshitaB, when you touch the `RoBERTa SST` model, try it without the `cls_is_last_token` setting. It's more correct to not have it.

**Comment by matt-gardner** [comment]
I see BERT SRL checked here, but there's this issue that says that performance actually doesn't match, with a solution that seems to fix it: https://github.com/allenai/allennlp/issues/4392#issuecomment-663214895.  Have you checked performance against the original reported performance?  Seems like a simple config file fix to get performance back up, if this is an issue.

I was just looking at the SRL and BERT SRL models, though, and I think we probably can just combine them at this point.  I don't think we gain much by using the `srl_bert.py` code at this point, and it's hard-coded for an earlier version of transformers that makes it so you can't easily update it for roberta, which would surely be better.  But, that should be a separate issue.

**Comment by dirkgr** [comment]
The `srl_bert.py` code is simpler though. It's a much more transformer-native implementation. If we can get that one to perform as well as `srl.py`, I might argue for keeping `srl_bert.py` and removing the other one.

**Comment by matt-gardner** [comment]
"transformer-native" means "I have to use transformers, and I can't even try using anything else."  It kind of goes against the whole point of the abstractions that we have.

**Comment by dirkgr** [comment]
While that's true, it's hard to argue in print for a solution that's more complicated and different from the standard if it doesn't also improve results.

In principle the `srl_bert.py` approach should work with any token embedder, but it might not do as well as a custom architecture.

**Comment by dirkgr** [comment]
We're tracking the remaining issue in #4521.
