### ISSUE TITLE
Missing srl-eval.pl in allennlp-models

### ISSUE THREAD

**Issue by Riccorl** [allenai/allennlp#4463]
When installing allennlp-models 1.0.0 through pip with

```
pip install allennlp-models
```

[srl-eval.pl](https://github.com/allenai/allennlp-models/blob/master/allennlp_models/structured_prediction/tools/srl-eval.pl) file is missing.

**Comment by dirkgr** [comment]
You are right! I made a fix in https://github.com/allenai/allennlp-models/pull/96.

**Comment by Riccorl** [comment]
Thank you!

**Comment by dirkgr** [comment]
This is fixed.
