### ISSUE TITLE
Encode candidates seperately when fine-tuning BERT to avoid CUDA out of memory error

### ISSUE THREAD

**Issue by 731935354** [allenai/allennlp#4466]
## Question
Hi, I want to build a 100-way classification model by fine-tuning BERT but get CUDA out of memory error. I tried to encode candidates separately but it seems not working as I expected.

## Environment
OS: Redhat
AllenNLP: 1.0.0
GPU: single Nvidia P100 16GB

## Task description
Each instance in my dataset contains
* a context sentence
* 100 candidate sentences
* an integer label that indicates the index of the correct answer

All sentences are truncated to have a maiximum of 72 wordpieces.

Generally given a batch of examples, my model works in the following manner:
1. Encode context sentences of shape `[batch_size, num_word_pieces, embedding_size]` using pretrained BERT, get a tensor of shape `[batch_size, embedding_size]`
2. Encode candidates of shape `[batch_size, num_candidates, num_word_pieces, embedding_size]` using the same BERT model as in step 1, get a tensor of shape `[batch_size, num_candidates, embedding_size]`.
3. repeat encoded context sentences `num_candidates` times, and concatenated with encoded candidates along the last dimension. At this stage we get a tensor of shape `[batch_size, num_candidates, embedding_size * 2]`
4. use fully connected layers to get unnormalized class distributions of shape `[batch_size, num_candidates]`.

I implemented step 2 as follows to avoid encoding 100 candidates together (also, BERT expects inputs of shape `[batch_size, num_word_pieces]`) :
```python
# candidates_token_ids, candidates_type_ids, candidates_mask all 
# with shape [batch_size, num_candidates, num_word_pieces]

encoded_cands = []  # conceptually of shape: [num_candidates, batch_size, embedding_size]
for i in range(num_candidates):
    # encode the i-th candidate in this batch
    slice_token_ids = candidates_token_ids[:, i, :]  
    slice_type_ids = candidates_type_ids[:, i, :]
    slice_mask = candidates_mask[:, i, :]
    # [batch_size, num_word_pieces, embedding_size]
    slice_encoded_last_layer = self.bert_model(slice_token_ids, slice_type_ids, slice_mask)
                                                                                      
    # [batch_size, embedding_size]
    encoded_slice = get_first_token_emb(slice_encoded_last_layer)
    encoded_cands.append(slice_encoded_la)
    
# rearrange as [batch_size, num_cands, emb_size * 2]
cands_encoded = rearrange(encoded_cands)
```

I tried batch_size=2, but got CUDA out of memory error right at the first batch. Also note that the sentences are encoded deliberately in this way (because I want to compare it with another model with the same encoding scheme).

Any suggestions will be appreciated!

**Comment by dirkgr** [comment]
I did not follow your model description completely, but it sounds like every instance contains 101 text sequences. With a batch size of 2, that means you want to hold 202 text sequences in memory at the same time. This will not work with 16 GB of memory. It does not matter if you do them separately, as you do in your `for` loop. PyTorch has to keep information from every loop to calculate gradients later, and that is what takes up all the memory.

So there are a few things you can try.
 1. Set a batch size of 1. If you need a bigger batch size for training, use gradient accumulation.
 1. Don't fine-tune the BERT weights. Call BERT inside of a `with torch.no_grad():` block. Your performance will be worse, but you save a lot of memory.
 1. Run on a bigger GPU. If you have access to a Quadro RTX 8000, you get 48GB of RAM.
 1. Train the model with fewer candidates. At inference time, you can still put in more candidates.

**Comment by 731935354** [comment]
@dirkgr Thanks very much for your suggestions. Yesterday I set batch_size=1 and successfully fine-tuned the model using a 32G-RAM GPU. It shows that 22GB memory has been used.

Your explanation of the `for` loop is really helpful. I finally understand why `separate encoding` didn't do what I expected.

I will definitely try other options you mentioned tomorrow.

**Comment by dirkgr** [comment]
👍
