### ISSUE TITLE
How to get results up to 4 decimal points in SpanBasedF1Measure, CategoricalAccuracy and other metrics

### ISSUE THREAD

**Issue by abubakar-ucr** [allenai/allennlp#4471]
Hi, how can I get results up to 4 decimal points in SpanBasedF1Measure, CategoricalAccuracy and other metrics in evaluate(...) method? By default, it only shows up to 2 points, and I see other libs (e.g., scikit-learn) takes in an argument to specify the precision value? Does AllenNLP have something like this that I am not aware of?

**Comment by dirkgr** [comment]
During training, the results go into `metrics.json` files, with all the accuracy that we have.

When you say "evaluate(...) method", do you mean you are running `allennlp evaluate`?

**Comment by abubakar-ucr** [comment]
yes. allennlp.training.util.evaluate. Specifically, I was talking about SpanBasedF1Measure
is there some other evaluation method as well?

**Comment by dirkgr** [comment]
`allennlp.training.util.evaluate()` is a function that returns metrics. None of those metrics are rounded. They come back with the full number of digits available.

Which metrics are included depends on the configuration of the model. Different models have different metrics.

**Comment by abubakar-ucr** [comment]
Nevermind, I figured it out. Thanks.
