### ISSUE TITLE
Inconsistency in answers generated by ELMo-Bidaf( trained on SQuAD) Demo and downloaded 

### ISSUE THREAD

**Issue by sukeshlaghate** [allenai/allennlp#4480]
**Describe the bug**
Inconsistent answers generated by `bidaf-elmo-model-2020.03.19.tar.gz` model when run in Allennlp demo website and when run on local machine after downloading the model.

**Steps to reproduce the behavior**
I followed instructions given in the usage section of online demo for reading comprehension 

1. conda create --name allennlp python=3.7
2. conda activate allennlp
3. conda install -c conda-forge jsonnet
4. pip install allennlp==1.0.0 allennlp-models==1.0.0
5. download bidaf-elmo model and store in folder
     5a. download from `https://storage.googleapis.com/allennlp-public-models/bidaf-elmo-model-2020.03.19.tar.gz` 
     5b. move it to python notebook location `~/sandbox/python/`

Used following python code as given in Usage section of allennlp demo website
~~~~
 
from allennlp.predictors.predictor import Predictor
import allennlp_models.rc

model_path = r"~/sandbox/python/rc_model"
predictor = Predictor.from_path(model_path)

text ="Becuase Pepsodent is a trusted brand. it has 130% germ attack power."

what_benefit = 'What is the benefit?'
why_use = 'Why use?'


why_answer = predictor.predict_json({
    "passage": text,
    "question": why_use
})

print(f"Answer for why should I use :{why_answer['best_span_str']}")
# Expected answer is Pepsodent is trusted brand.

what_answer = predictor.predict(
  passage=text,
  question=what_benefit
)

print(f"Answer for what is the benefit: {what_answer['best_span_str']}")
# Expected answer is 130% germ attack power

~~~~

**Expected behavior**
For why question expected answer is  "Pepsodent is trusted brand."
For what question expected answer is "130% germ attack power"

Actual answer for both cases is "130% germ attack power" refer  screen shot below

![Downloaded_Model_answers](https://user-images.githubusercontent.com/25061957/87558881-3b193f00-c6d7-11ea-8786-7be8b8dd0d55.jpg)

However when same passage and questions are fed into online demo, the model generates expected responses  please refer to the screen shots

Response for what is the benefit question
![Allennlp_Demo_What_is_benifit_Answer](https://user-images.githubusercontent.com/25061957/87558621-f1c8ef80-c6d6-11ea-92f9-d65317da9532.jpg)

Response for why use question
![Allennlp_Demo_Why_Use_Answer](https://user-images.githubusercontent.com/25061957/87558920-47050100-c6d7-11ea-9f56-7ff5b8654b1c.jpg)

**System**

    OS: [ubuntu 20.0.4]
    Python version: [3.7.6]
    AllenNLP version: [ v1.0.0]

Request you to help in resolving this inconsistency. 
Any pointers/ insights/ solutions are much appreciated.

**Comment by dirkgr** [comment]
The ELMo model you are using does not guarantee the same results every time. That's a known characteristic of ELMo. Have you tried it with the TransformerQA model that's also there?

**Comment by sukeshlaghate** [comment]
@dirkgr Thanks for your response. 
Point duly noted. 
However I have an observation; On the demo website it consistently returns correct answers not only for the passage given in example above but even for variety of other passages too. So you can understand why I was confused with the responses that were generated by downloaded model.

I will try out TransformerQA Model as suggested.

**Comment by sukeshlaghate** [comment]
@dirkgr Also noticed that there is NMN model but demo site does not provide information on its usage. Could you please provide example along with instructions on how to download and run NMN(drop) trained model. Thank you in advance for your help

**Comment by dirkgr** [comment]
Unfortunately I don't know too much about the NMN models. I think they live at https://github.com/allenai/allennlp-semparse. @matt-gardner, do you know more?

**Comment by matt-gardner** [comment]
The DROP NMN lives here: https://github.com/nitishgupta/nmn-drop.  It's based on the semparse repo, but it's not in that repo.
