### ISSUE TITLE
Allow training of specific layers of pretrained transformers

### ISSUE THREAD

**Issue by successar** [allenai/allennlp#4482]
**Is your feature request related to a problem? Please describe.**
Currently pretrained transformer embedders allow training of either or none of the parameters in a model. I would like to be able to training only specific layers -- say top 2 while keeping everything else fixed.

**Describe the solution you'd like**
Current the model takes in a boolean train_parameters option here https://github.com/allenai/allennlp/blob/53eeec105fa0da91a7793e45c66b9cec14c45dff/allennlp/modules/token_embedders/pretrained_transformer_embedder.py#L82
We can put it as a Union of bool or list of regexes type. Bool input will work same as current version (for backward compatibility); while with regex list, we will match each parameter name with the each regex and set required=True for those that match any of the regexes. Currently I don't forsee any big issues with this setup and looking for teams opinion before implementing it as pull request.

**Describe alternatives you've considered**
Currently I specify regexes as part of my outer model but that is not clean when I am using TextFieldEmbedder API and breaks the dependency structure.

**Comment by matt-gardner** [comment]
Seems a bit nicer to have some kind of initializer that freezes weights, and then use our existing regex mechanism to apply that initializer.  Does that sound like it would work?

**Comment by successar** [comment]
@matt-gardner Thanks for the suggestion. I will try initializer route too

**Comment by epwalsh** [comment]
Though this isn't documented, I think that's the purpose of this parameter: https://github.com/allenai/allennlp/blob/master/allennlp/training/trainer.py#L1056.

But I do like @matt-gardner's idea.

**Comment by matt-gardner** [comment]
Hmm, yeah, @epwalsh, you're right.  No strong opinion from me on which of the two options to use.  But it's pretty unfortunate that `no_grad` isn't documented, and only shows up in `from_partial_objects` and not `__init__`.  Cleaner probably to push that functionality into an initializer.

**Comment by successar** [comment]
Thanks, @epwalsh no_grad is exactly what I needed for now. Also I tried a new freeze_param initializer and that seems to be working too for me. Will try to generate a pull request for that this week.

**Comment by dirkgr** [comment]
Let'a make an optimizer parameter that does this.
