### ISSUE TITLE
Fix the GPT2 demo

### ISSUE THREAD

**Issue by dirkgr** [allenai/allennlp#4484]
@pclark425 reports that the GPT2 demo seems to be doing poorly right now. @matt-gardner suspects it has something to do with tokenization.

**Comment by matt-gardner** [comment]
To be more specific: trailing space at the end of the input box makes the predictions quite poor. If you remind the trailing space, or use the buttons to interact with the demo, things look fine. The trailing space behavior is unexpected and so seems wrong, even if according to the tokenization it might be "correct" behavior.

**Comment by matt-gardner** [comment]
Which also means this might just be a simple fix on the demo side, not something to fix here.

**Comment by matt-gardner** [comment]
It's tricky, because you probably *do* want to keep a trailing newline, just not a trailing space... One possible solution is just to have a note in the demo explaining this behavior.

**Comment by NightMachinery** [comment]
Is this demo still up?
