### ISSUE TITLE
Set Detectron2 version as v0.2

### ISSUE THREAD

**Issue by j-min** [allenai/allennlp#4489]
Let's fix Detectron2 version as v0.2, the latest release version.
In [setup.py](https://github.com/allenai/allennlp/blob/DetectronNLVR/setup.py#L71), we could change
`"detectron2 @ git+https://github.com/facebookresearch/detectron2"`
to `"detectron2 @ git+https://github.com/facebookresearch/detectron2@v0.2"`

**Comment by dirkgr** [comment]
This is a good idea. Why don't you just make the change in a PR? Or just commit it directly to the `DetectronNLVR` branch? The Detectron stuff is so early still, we don't have to go through the official process all the time.

**Comment by j-min** [comment]
I see. I will commit directly to the DetectronNLVR branch.
