### ISSUE TITLE
Using Word and Character level embeddings

### ISSUE THREAD

**Issue by lianna1016** [allenai/allennlp#4490]
Hello! 

I am very new to AllenNLP and am trying to create an NER LSTM model. I have gotten it to use the word2vec embeddings, but I am also trying to add character level embeddings as well for out of vocab words. I have been looking for examples on how to do this but cannot find a clear one. Are there any resources you could point me towards? 

Below is a screenshot of an attempt with a config file

![image](https://user-images.githubusercontent.com/31545387/87740115-666f5d00-c7af-11ea-9ae9-ec1daaa3fac4.png)

An error that I get is 
```allennlp.common.checks.ConfigurationError: Mismatched token keys: dict_keys(['token_characters', 'tokens']) and dict_keys(['tokens'])```

Thanks so much!

**Comment by matt-gardner** [comment]
Have you look at [the guide](https://guide.allennlp.org/representing-text-as-features)?  In sections 3 and 4 of the page I linked there are examples of how to do this.

**Comment by lianna1016** [comment]
Thank you!
