### ISSUE TITLE
[Suggestion] One line change in the comments

### ISSUE THREAD

**Issue by WweiL** [allenai/allennlp#4494]
## Checklist

- [x] I have verified that the issue exists against the `master` branch of AllenNLP.
- [x] I have read the relevant section in the [contribution guide](https://github.com/allenai/allennlp/blob/master/CONTRIBUTING.md#bug-fixes-and-new-features) on reporting bugs.
- [x] I have checked the [issues list](https://github.com/allenai/allennlp/issues) for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/allenai/allennlp/pulls) for existing proposed fixes.
- [x] I have checked the [CHANGELOG](https://github.com/allenai/allennlp/blob/master/CHANGELOG.md) and the [commit log](https://github.com/allenai/allennlp/commits/master) to find out if the bug was already fixed in the master branch.
- [x] I have included in the "Description" section below a traceback from any exceptions related to this bug.
- [x] I have included in the "Related issues or possible duplicates" section beloew all related issues and possible duplicate issues (If there are none, check this box anyway).
- [x] I have included in the "Environment" section below the name of the operating system and Python version that I was using when I discovered this bug.
- [x] I have included in the "Environment" section below the output of `pip freeze`.
- [x] I have included in the "Steps to reproduce" section below a minimally reproducible example.

## Description

https://github.com/allenai/allennlp/blob/master/allennlp/data/dataloader.py#L54
This line should be deleted as allennlp_collate is moved to the dataloader.py file itself.

## Related issues or possible duplicates

- None

## Environment
N/A

OS:
N/A

Python version:

## Steps to reproduce

See the page: https://github.com/allenai/allennlp/blob/master/allennlp/data/dataloader.py#L54

**Comment by epwalsh** [comment]
@WweiL thanks for letting us know. Would you mind submitting a PR to fix this?
