### ISSUE TITLE
Question regarding util.batched_span_select

### ISSUE THREAD

**Issue by OhadRubin** [allenai/allennlp#4498]
[It states](https://github.com/allenai/allennlp/blob/478bf46cb676524ee9b74fb271ec0a592d1c4a48/allennlp/nn/util.py#L1267):
> 
>     This function returns segmented spans in the target with respect to the provided span indices.
>     It does not guarantee element order within each span.
Why is that?
Thanks

**Comment by ZhaofengWu** [comment]
If you're referring to the second line (not guaranteeing order), IIRC it's because of some fancy tensor indexing logic. I imagine we could change the logic to make this guarantee if there's a demonstrated need.

**Comment by OhadRubin** [comment]
Yes, for example in dialogue tasks you might want to go from [batch_size,num_uttrances*max_uttrance_len] to  [batch_size,num_uttrances, new_max_uttrance_len]

**Comment by dirkgr** [comment]
It would certainly be nice if we could guarantee the order in this function. I believe it is the way it is for performance, but I'm not sure it really makes that much of a difference. @ZhaofengWu, do you know? I'd be happy tor review a fix.

**Comment by ZhaofengWu** [comment]
Sorry I might not have time recently to resolve this. Looks like the biggest problem is from https://github.com/allenai/allennlp/blob/478bf46cb676524ee9b74fb271ec0a592d1c4a48/allennlp/nn/util.py#L1321
where the indices are reversed. It might work if we do something along the line of `raw_span_indices = span_starts + max_span_range_indices`. There may be edges cases to be taken care of though, but I don't think it will make a big difference efficiency-wise. I guess the reason Mark wrote the first version using this was to handle edges cases more easily.

**Comment by OhadRubin** [comment]
Fixed by #4511
