### ISSUE TITLE
After #4470 the output is duplicated and Tqdm effect is lost

### ISSUE THREAD

**Issue by bratao** [allenai/allennlp#4504]
## Checklist

- [X] I have verified that the issue exists against the `master` branch of AllenNLP.
- [X] I have read the relevant section in the [contribution guide](https://github.com/allenai/allennlp/blob/master/CONTRIBUTING.md#bug-fixes-and-new-features) on reporting bugs.
- [X] I have checked the [issues list](https://github.com/allenai/allennlp/issues) for similar or identical bug reports.
- [X] I have checked the [pull requests list](https://github.com/allenai/allennlp/pulls) for existing proposed fixes.
- [X] I have checked the [CHANGELOG](https://github.com/allenai/allennlp/blob/master/CHANGELOG.md) and the [commit log](https://github.com/allenai/allennlp/commits/master) to find out if the bug was already fixed in the master branch.
- [X] I have included in the "Description" section below a traceback from any exceptions related to this bug.
- [X] I have included in the "Related issues or possible duplicates" section beloew all related issues and possible duplicate issues (If there are none, check this box anyway).
- [X] I have included in the "Environment" section below the name of the operating system and Python version that I was using when I discovered this bug.
- [X] I have included in the "Environment" section below the output of `pip freeze`.
- [X] I have included in the "Steps to reproduce" section below a minimally reproducible example.

## Description

In PyCharm console in Windows and in the CI ( Ubuntu 18.04) the output is duplicated. The nice Tqdm bars is lost. The output is repeated like that:

```
accuracy: 0.9193, accuracy3: 0.9219, precision-overall: 0.3077, recall-overall: 0.2727, f1-measure-overall: 0.2892, loss: 95.4325, reg_loss: 6.7843 ||:  33%|###3      | 1/3 [00:02<00:04,  2.14s/it]
accuracy: 0.9211, accuracy3: 0.9237, precision-overall: 0.3571, recall-overall: 0.3191, f1-measure-overall: 0.3371, loss: 37.8299, reg_loss: 7.8506 ||: 100%|##########| 3/3 [00:02<00:00,  1.52s/it]
accuracy: 0.9211, accuracy3: 0.9237, precision-overall: 0.3571, recall-overall: 0.3191, f1-measure-overall: 0.3371, loss: 37.8299, reg_loss: 7.8506 ||: 100%|##########| 3/3 [00:02<00:00,  1.30it/s]

```
The #4470 Pull by @epwalsh  checks for sys.stderr.isatty() and in my Pycharm console and in my Gitlab C.I the output is duplicated. Probably because the console is redirected internal. A option to keep the previous behavior would be great

<details>

<summary><b>Python traceback:</b></summary>
<p>

```
```

</p>
</details>

## Related issues or possible duplicates

Happened after the #4470 Pull

## Environment

OS: Windows 10 or Ubuntu 18.04

Python version: 3.8

<details>
<summary><b>Output of <code>pip freeze</code>:</b></summary>
<p>

```
```

</p>
</details>

## Steps to reproduce

<details>
<summary><b>Example source:</b></summary>
<p>

```
```
N/A - Any training code reproduces this error.
</p>
</details>

**Comment by epwalsh** [comment]
Ugh, in hindsight, maybe getting rid of the `--file-friendly-logging` flag was a bad idea. But I guess the main issue is that `sys.stderr.isatty()` is too crude / not really what we want to check.

Maybe there's a better way to check when we should automatically switch to FFL? Otherwise I'd vote for re-instating the FFL flag.

**Comment by epwalsh** [comment]
@bratao the double output is just the last progress bar, i.e. when it gets to 100%. I've noticed this elsewhere. I think I have a fix for that.

**Comment by bratao** [comment]
Thanks @epwalsh . Yeah, I think a flag would be the best solution. Because `sys.stderr.isatty()` is too fragile. Maybe console emulators report a wrongly.
