### ISSUE TITLE
How the 'hotflip' is applied to the BERT?

### ISSUE THREAD

**Issue by JJumSSu** [allenai/allennlp#4516]
Hi, this [hotflip](https://demo.allennlp.org/masked-lm?text=The%20doctor%20ran%20to%20the%20emergency%20room%20to%20see%20%5BMASK%5D%20patient.) demo is neat, thank you for providing such a nice library&demo.

However, I have a question. BERT uses wordpiece vocabulary and is subword-unit based language model. But in the demo, it seems that the token is flipped at the "word" level. Also, the hotflip attack implementation in the allennlp [library](https://github.com/allenai/allennlp/blob/master/allennlp/interpret/attackers/hotflip.py) is based on word-level. 

Did you guys give special treatment for this discrepancy? Or do you guys just flip the token at the subword-level?
I couldn't find out the source code processing this part.

Thank you.

**Comment by matt-gardner** [comment]
Whether we do attacks at the word or wordpiece level is actually model-dependent.  We do attacks at the _token_ level, which could be either words or wordpieces (or even characters; see [here](https://guide.allennlp.org/representing-text-as-features) for more info on how that works).

We get an embedding layer here: https://github.com/allenai/allennlp/blob/e53d18580807dabff707f618f7e148c98d25da18/allennlp/nn/util.py#L1650-L1708.

And we use that embedding layer to construct a weight matrix for hotflip here (see also the main class docstring, above): https://github.com/allenai/allennlp/blob/e53d18580807dabff707f618f7e148c98d25da18/allennlp/interpret/attackers/hotflip.py#L85-L116.

In the language modeling demo, I'm not actually sure whether the replacement happens at the word or wordpiece level; I'd have to check what the underlying model is doing.  It's quite possible that it's operating on wordpieces under the hood, but is combining them back into wordpieces for display.  If you look at, e.g., the [roberta model in the sentiment analysis demo](https://demo.allennlp.org/sentiment-analysis/MjIyNzU0OA==), the saliency map makes it clear that it's operating on wordpieces, though the typical #'s aren't actually shown.

**Comment by JJumSSu** [comment]
I appreciate it! :)
