### ISSUE TITLE
lazy mode is helpful for us?

### ISSUE THREAD

**Issue by Nagin-Kim** [allenai/allennlp#4518]
When I try to pretrain the model , I found that the gpu memory are unsteady due to the reason of that i set the laze mode as True, however when i try to train it again with parameter --laze_mode=False, my cpu cache are only 50gb, which can't run this mode on my 30gb datasets with its code.
**Describe the solution you'd like**
Can we train the model with laze_mode =True, and the datareader can synthetically read the data from the cache at the same time?

**Comment by matt-gardner** [comment]
> Can we train the model with laze_mode =True, and the datareader can synthetically read the data from the cache at the same time?

I don't understand what you're asking here.  You can use lazy mode, but I don't know what you mean by "read the data from the cache", or "GPU memory are unsteady".

**Comment by Nagin-Kim** [comment]
can you help me to explain what the lazy mode means with its advantage and disadvantage?

**Comment by matt-gardner** [comment]
See the "Lazy Mode" section [here](https://guide.allennlp.org/reading-data#2).

**Comment by matt-gardner** [comment]
Closing this issue for now; feel free to comment again or open a new issue if you still see problems.
