### ISSUE TITLE
Can i run those modes offline?

### ISSUE THREAD

**Issue by Roshanson** [allenai/allennlp#452]
HI,
I have installed AllenNLP in my computer(with conda environment ), and i copy this conda environment to another computer ,but this computer can't connection to Internet.  So  i cant't  run **allennlp/run train training_config/decomposable_attention.json -s output_path** .   
Can i  find a way to run this modes offline?   Thanks!

**Comment by joelgrus** [comment]
If you look at that config file, it has three paths (training data, validation data, glove vectors) that point at files on S3. If you copy those files to your computer (and change the paths to point at them), you should be able to train the model without an internet connection.  (The glove vectors is a big file.)

Do you really want to train the model or just make predictions?  

If you just want to make predictions, then look in `allennlp/commands/__init__.py` to see the S3 URLs for the pretrained model files. You can just download and copy *those* and then change the paths in that file (for `serve`) or specify at the command line (for `predict`).

**Comment by Roshanson** [comment]
Thank you very much!  
i want to train the TE model with my data, so what i need to do is convert my data to .jsonl  and get vectors with glove?
