### ISSUE TITLE
Simplify BERT SRL / SRL models

### ISSUE THREAD

**Issue by matt-gardner** [allenai/allennlp#4521]
We currently have two SRL model classes, and we don't need two.  The `srl_bert.py` class is also stale, and won't let you use any transformer that you want, only BERT.  Now that we have built-in mismatched embedders, it seems like we should just remove the old `srl_bert.py` model, just use roberta or something with the more standard model, and update the model in the demo.  Should be pretty easy.

**Comment by matt-gardner** [comment]
Moving discussion here from #4457 (specifically, this is responding to [this comment](https://github.com/allenai/allennlp/issues/4457#issuecomment-668158116); cc @dirkgr).

Ok, looking at the implementations, I see the core modeling logic happening in both models here:

https://github.com/allenai/allennlp-models/blob/5d9098f6084a12da77b02d40e0d9392113aeb805/allennlp_models/structured_prediction/models/srl_bert.py#L118-L132

https://github.com/allenai/allennlp-models/blob/5d9098f6084a12da77b02d40e0d9392113aeb805/allennlp_models/structured_prediction/models/srl.py#L290-L306

The only real difference is the handling of the verb indicator, and if that's what you were talking about, then yes, I agree with you, and sorry that I misunderstood what you meant.  It'd be pretty tricky to get that handled correctly in a transformer with the standard way that we do pretrained embeddings.

It'd probably be better to do a joint prediction of predicates and their arguments, anyway; we've gotten lots of issues / confusion about how we use spacy to predict POS tags in the demo / trained model.  @sanjayss34 has been working on an implementation of this, and maybe the best resolution of this issue is to just update our model with that joint one once it's working (though, no pressure @sanjayss34, if you end up going in a different direction).

**Comment by dirkgr** [comment]
@sanjayss34 is writing a new model that has better performance than the existing two models. We will replace the old ones with Sanjay's new one.

**Comment by Riccorl** [comment]
Hi, I'm trying to generalize myself the SRL model in the current release, but I have a problem. I hope you can help me figure it out. In the forward, [here](https://github.com/allenai/allennlp-models/blob/bcaf3c88eac5d60cf6885d35105e2772936d0862/allennlp_models/structured_prediction/models/srl_bert.py#L119), `token_type_ids` is assigned to `verb_indicator`. Since not every model support `token_type_ids > 0`, I'm trying to train without it, but it doesn't work. As soon as I put all the values to 0, f1 score drops to about 40. 

Can you help me understand why this happens? It's an unusual way to use `token_type_ids` here and I would like to understand the reasoning behind it. 

Thank you

**Comment by dirkgr** [comment]
@Riccorl, you can use token type IDs in a variety of ways. Indicating the verb is one of those ways. If the model does not have access to that information in any form, it makes sense to me that the performance would drop (though to understand why it drops by 40 point, I'd have to understand some more context).

Token type IDs just result in another embedding being added to the word piece embedding. You might be able to just do that manually if you are working with a transformer that doesn't support them natively.

Another way to do it would be to indicate the verb with "tags" around it. If you have enough training data, the model will figure out how to use the information.
