### ISSUE TITLE
ConfigurationError: Cannot register evaluate as Subcommand; name already in use for Evaluate

### ISSUE THREAD

**Issue by ScottishFold007** [allenai/allennlp#4523]
![image](https://user-images.githubusercontent.com/36957508/88883941-1640d200-d268-11ea-8803-6e15f5b2c985.png)

**Comment by matt-gardner** [comment]
We need more context than this in order to help you.

It looks like you've gotten allennlp installed in two places in your environment somehow, because you're running the `@Subcommand.register("evaluate")` twice.

**Comment by matt-gardner** [comment]
Closing, as I'm quite confident that this is an environment problem, but feel free to keep commenting if you still have issues.
