### ISSUE TITLE
To train the model without specifying a GPU.

### ISSUE THREAD

**Issue by PrettyPrettyMeng** [allenai/allennlp#4528]
For the cluster that I'm using, it does not allow specifying cuda device in my code. I think it's pretty common in many different clusters. I have not found how to do it for current allennlp library. Does there exist one that I have not noticed or can you add a feature like this? For example, by setting some config parameters, we can use model.cuda() instead of model.to(device). Thanks in advance!

**Comment by epwalsh** [comment]
Hey @PrettyPrettyMeng, we changed the behavior of the `train` command recently to automatically detect and use a GPU when it can if you don't explicitly set the "cuda_device" parameter in the trainer. Have you tried that?

**Comment by PrettyPrettyMeng** [comment]
That's great! Thanks. Maybe I'm using some older version and it automatically use CPU when I don't explicitly set the "cuda_device" parameter in the trainer.
