### ISSUE TITLE
A "py.typed" marker

### ISSUE THREAD

**Issue by davidatbu** [allenai/allennlp#4535]
Hi all,

I was wondering if there's a specific reason that neither `allennlp`, nor `allennlp-models` include an empty marker file named `py.typed` in their respective python package root directories, as that file is required to mark a package as "PEP-561 compliant", which gives static code analysis tools like mypy the go-ahead to do type inference.

Otherwise, I am currently forced to clone the repo locally, add the marker file, and `pip install -e` to stop mypy from complaining that stubs are missing for `allennlp`.

**Comment by AkshitaB** [comment]
Hi, thanks for bringing this to our attention. Please feel free to submit a pull request!
