### ISSUE TITLE
Error loading coreference model

### ISSUE THREAD

**Issue by BabyCodr** [allenai/allennlp#4536]
I am currently running the following commands

```
from allennlp.predictors.predictor import Predictor
import allennlp_models.coref
predictor = Predictor.from_path("https://storage.googleapis.com/allennlp-public-models/coref-spanbert-large-2020.02.27.tar.gz")
```

and I get this following error. The model still works on the whole however I am noticing some performance differences when comparing output to allennlp demo and wonder if this error is the cause

WARNING:allennlp.nn.initializers:Did not use initialization regex that was passed: _context_layer._module.weight_ih.*
WARNING:allennlp.nn.initializers:Did not use initialization regex that was passed: _context_layer._module.weight_hh.*

**Comment by AkshitaB** [comment]
Hi, can you give an example of the performance differences you observe?

**Comment by foodiehack** [comment]
Waiting for the same. If you can give the performance differences you observe.

**Comment by leonardyeoxl** [comment]
Hi, there are some issues with the model. Here is the exact same code from https://demo.allennlp.org/coreference-resolution/MjMwNTcxNA==

```
from allennlp.predictors.predictor import Predictor
import allennlp_models.coref

predictor = Predictor.from_path("https://storage.googleapis.com/allennlp-public-models/coref-spanbert-large-2020.02.27.tar.gz")
predictor.predict(
  document="The woman reading a newspaper sat on the bench with her dog."
)
```

Here are the results after running the script:
```
Did not use initialization regex that was passed: _context_layer._module.weight_ih.*
Did not use initialization regex that was passed: _context_layer._module.weight_hh.*
Killed
```

Kindly assist in this.
