### ISSUE TITLE
Can we support multi-dataset when training ？

### ISSUE THREAD

**Issue by wlhgtc** [allenai/allennlp#4551]
I am reproduce an seq2seq model in Open-NMT, 
I wonder if we could  support param like `data weight`  in NMT, specifically:
  1.  support more than one datasets (share same vocabulary)
  2. could set weight to each dataset (e.g. 2:1 means 2 batch in the first one and 1 in another)
I find your discussion in  #4422. Multi-task seems need same feature like this.  Actually, multi-task needs two part: multi-dataset feature and model(multi-task head) feature.

Can you could give me some advice about how to do it ?  I'd like to try it. @dirkgr  @matt-gardner  @jiasenlu

**Comment by dirkgr** [comment]
We have a more detailed design for how to do multi-task learning in a Google Doc. I will clean it up and put it into the discussion at #4422 shortly.

I'll close this issue as a duplicate, but please follow the discussion at #4422 and make sure we hear your feedback before we write the code!

**Comment by wlhgtc** [comment]
> We have a more detailed design for how to do multi-task learning in a Google Doc. I will clean it up and put it into the discussion at #4422 shortly.
> 
> I'll close this issue as a duplicate, but please follow the discussion at #4422 and make sure we hear your feedback before we write the code!

Sure and I am looking forward to this new feature!
