### ISSUE TITLE
Question regarding model interpretations

### ISSUE THREAD

**Issue by heytitle** [allenai/allennlp#4552]
Hi,

May I ask a couple of questions regarding model interpretations?
1. Is it common to use SmoothGrad in NLP? It's a bit counterintuitive to me because embeddings are static.
2. When visualizing contribution scores, is it common to select top K tokens for the visualization?
<img width="825" alt="image" src="https://user-images.githubusercontent.com/1214890/89996495-26ef4000-dc8b-11ea-8fc8-1b9e6aec286a.png">

**Comment by matt-gardner** [comment]
1. I don't think either smooth grad or integrated gradients is "common" in NLP, nor would I say that simple gradient is either.  It's not really well understood how any of these interact with transformers, I don't think.  But, the library should at least let people explore this, which was our point, more than claiming that these were techniques we necessarily endorse.

2. We're not really in a position to claim anything about "common" on visualizing tokens.  But you can see the results for however many tokens you want with the slider.

**Comment by heytitle** [comment]
@matt-gardner thank you very much for the answers!
