### ISSUE TITLE
Text to sql atis training set

### ISSUE THREAD

**Issue by nagumamta** [allenai/allennlp#4553]
Hi,

I am working  on text to sql(atis),  i created model using experiment.json and sample.json,  present  in the tests\fixtures, used the same  model to predict,  but predicted values are 0 even for the  utterance present in sample.json

can u plz point out what  is wrong and can u plz provide entire training set (as i noticed that  sample.json has only 14 utterance)

**Comment by matt-gardner** [comment]
You definitely should not use the data in the test fixtures as actual training data for anything; those are very small datasets only used for testing.  The training data requires an LDC license; you'll need to go [here](https://github.com/lil-lab/atis) and ask Alane Suhr for access (she'll want to confirm that you have the appropriate LDC license, I imagine).

**Comment by matt-gardner** [comment]
If you're just interested in text to sql more generally, I don't think the spider dataset requires an LDC license, and there are allennlp models available for it [here](https://github.com/benbogin/spider-schema-gnn-global).

**Comment by nagumamta** [comment]
> You definitely should not use the data in the test fixtures as actual training data for anything; those are very small datasets only used for testing. The training data requires an LDC license; you'll need to go [here](https://github.com/lil-lab/atis) and ask Alane Suhr for access (she'll want to confirm that you have the appropriate LDC license, I imagine).

Thanks @matt-gardner  have done the same

**Comment by nagumamta** [comment]
> If you're just interested in text to sql more generally, I don't think the spider dataset requires an LDC license, and there are allennlp models available for it [here](https://github.com/benbogin/spider-schema-gnn-global).

@matt-gardner  sure will look into it
