### ISSUE TITLE
torch must be imported before import allennlp

### ISSUE THREAD

**Issue by lixiepeng** [allenai/allennlp#4555]
## Checklist

- [x] I have verified that the issue exists against the `master` branch of AllenNLP.
- [x] I have read the relevant section in the [contribution guide](https://github.com/allenai/allennlp/blob/master/CONTRIBUTING.md#bug-fixes-and-new-features) on reporting bugs.
- [x] I have checked the [issues list](https://github.com/allenai/allennlp/issues) for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/allenai/allennlp/pulls) for existing proposed fixes.
- [x] I have checked the [CHANGELOG](https://github.com/allenai/allennlp/blob/master/CHANGELOG.md) and the [commit log](https://github.com/allenai/allennlp/commits/master) to find out if the bug was already fixed in the master branch.
- [x] I have included in the "Description" section below a traceback from any exceptions related to this bug.
- [x] I have included in the "Related issues or possible duplicates" section beloew all related issues and possible duplicate issues (If there are none, check this box anyway).
- [x] I have included in the "Environment" section below the name of the operating system and Python version that I was using when I discovered this bug.
- [x] I have included in the "Environment" section below the output of `pip freeze`.
- [x] I have included in the "Steps to reproduce" section below a minimally reproducible example.

## Description

<details>
<summary><b>Python traceback:</b></summary>

<p>

```
from allennlp.common.util import import_module_and_submodules

D:\Anaconda3\lib\site-packages\allennlp\__init__.py in <module>
     16     # On some systems this prevents the dreaded
     17     # ImportError: dlopen: cannot load any more object with static TLS
---> 18     import spacy, torch, numpy  # noqa
     19 
     20 except ModuleNotFoundError:

D:\Anaconda3\lib\site-packages\torch\__init__.py in <module>
    114                 err = ctypes.WinError(last_error)
    115                 err.strerror += ' Error loading "{}" or one of its dependencies.'.format(dll)
--> 116                 raise err
    117             elif res is not None:
    118                 is_loaded = True

OSError: [WinError 127] 找不到指定的程序。 Error loading "D:\Anaconda3\lib\site-packages\torch\lib\caffe2_detectron_ops_gpu.dll" or one of its dependencies.

Ipython Console:
In [1]: import torch

In [2]: import allennlp

In [3]:

CMD:
C:\Users\xxx>allennlp
Traceback (most recent call last):
  File "d:\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda3\Scripts\allennlp.exe\__main__.py", line 5, in <module>
  File "d:\anaconda3\lib\site-packages\allennlp\__init__.py", line 18, in <module>
    import spacy, torch, numpy  # noqa
  File "d:\anaconda3\lib\site-packages\torch\__init__.py", line 116, in <module>
    raise err
OSError: [WinError 127] 找不到指定的程序。 Error loading "d:\anaconda3\lib\site-packages\torch\lib\caffe2_detectron_ops_gpu.dll" or one of its dependencies.
```

</p>
</details>

## Related issues or possible duplicates

- None

## Environment

OS: Win10 64

Python version: python 3.7.3

<details>
<summary><b>Output of <code>pip freeze</code>:</b></summary>
<p>

```
torch==1.6.0
allennlp==1.1.0rc3
allennlp-models==1.1.0rc3
```

</p>
</details>

## Steps to reproduce

<details>
<summary><b>Example source:</b></summary>
<p>

```
from allennlp.common.util import import_module_and_submodules
or
CMD: allennlp
```

</p>
</details>

**Comment by dirkgr** [comment]
Sorry, we don't officially support Windows.

Inofficially though I would hope this works. This is probably caused by some incompatibilities in your environment. How do you install torch, and the rest of the dependencies? Do you use virtualenv or conda?
