### ISSUE TITLE
Wrong metrics calculations when running in distributed mode 

### ISSUE THREAD

**Issue by eladsegal** [allenai/allennlp#4564]
## Version
v1.1.0rc3

## Description
`BooleanAccuracy` and `CategoricalAccuracy` (and possibly other metrics) are not calculated correctly when running in distributed mode, causing them to return `nan`.

It is caused by repeated addition of an accumulated variable with itself with each call to update the metric, resulting in an exponential growth until it gets to a value of `inf` (and when `inf` is divided by `inf` the result is `nan`).
https://github.com/allenai/allennlp/blob/v1.1.0rc3/allennlp/training/metrics/categorical_accuracy.py#L102-L108

## Steps to reproduce
I've encountered the issue when I used `BooleanAccuracy` and `CategoricalAccuracy`, but from quickly looking at the code of other metrics it is possible it can occur for some of them as well.

Clone [allennlp-models](https://github.com/allenai/allennlp-models), switch to tag `v1.1.0rc3` and run the following from it:
```allennlp train training_config/rc/transformer_qa_distributed.jsonnet -s training_dir -o '{"dataset_reader": {"max_instances": 2000}, "validation_dataset_reader": {"max_instances": 10}}'```

After less than 200 training steps the metrics `start_acc`, `end_acc` (CategoricalAccuracy) and `span_acc` (BooleanAccuracy) will be `nan`.

## Fix
A fix for `BooleanAccuracy` and `CategoricalAccuracy` is [here](https://github.com/eladsegal/allennlp/commit/564fbb727b8a7d7b9959fa2ebe9d3f64dbc3e808).
I currently don't have time to verify and fix other metrics, so let me know if you'd like me to create a pull request just for these two.

**Comment by AkshitaB** [comment]
@eladsegal Thank you for bringing this to our attention. I know what other metrics may have a similar problem, and can work on fixing those. Please feel free to go ahead and submit a PR for these two.

**Comment by AkshitaB** [comment]
Reopening issue to keep track of adding tests and fixes to remaining metrics that will break.
