### ISSUE TITLE
Jiasen's Dynamic Stop&Go

### ISSUE THREAD

**Issue by dirkgr** [allenai/allennlp#4566]
In https://arxiv.org/abs/1912.02315, @jiasenlu et al. describe an algorithm that selects the next task based on the validation performance of the task. I believe we can implement this on top if #4422 with a combination of a multitask scheduler that remembers which task is in “stop” mode and which task is in “go” mode. MT schedulers can’t calculate validation performance, so that will have to happen in an `EpochCallback`, which then updates the MT scheduler. The `EpochCallback` has access to the trainer, and the trainer has access to the data loader, so this should be possible without creating new APIs.

**Comment by dirkgr** [comment]
@jiasenlu, you have existing code for this, right?

**Comment by jiasenlu** [comment]
yes, we have code for this.
