### ISSUE TITLE
`batches_per_epoch` should not affect evaluation

### ISSUE THREAD

**Issue by dirkgr** [allenai/allennlp#4567]
@HarshTrivedi noticed that `batches_per_epoch` affects evaluation, in that it only evaluates on the first `n` batches when this is set. While it's easy to see why this happens, that's almost always wrong. We should ignore that parameter for evaluations. If you want to restrict the dataset size for evaluations, you can do it with the `max_instances` parameter.

**Comment by HarshTrivedi** [comment]
Btw, this could also be a problem for validation evaluation happening after every checkpoint during the training.

For fixing only the post-training evaluation, my current hack is just to add the following line [here](https://github.com/allenai/allennlp/blob/master/allennlp/commands/evaluate.py#L148).

```
data_loader_params.pop("batches_per_epoch")
```
This doesn't fix the training phase evaluations though.

**Comment by dirkgr** [comment]
We talked about this during issue review.
 * We don't want to take away the ability to set `batches_per_epoch`.
 * We don't want to make the validation data loader act differently when it's specified in jsonnet vs. when we default-fallback to the train dataloader.
 * We want to be able to silence the warning if we print one.

**Comment by dirkgr** [comment]
@HarshTrivedi, the proper way to fix this right now is to set the `validation_data_loader` in the config. You can use jsonnet to set it to a copy of `data_loader`, minus the `batches_per_epoch` parameter. It would look similar to this: https://github.com/allenai/allennlp-models/blob/master/training_config/classification/stanford_sentiment_treebank_roberta.jsonnet#L22

**Comment by HarshTrivedi** [comment]
Yep, thanks. I'm already doing that for training _new_ models. However, several of my models are already trained without the `validation_data_loader` being set. For config change to take affect, I'd have to do unarchive model.tar.gz, tweak config, rearchive for every trained model and only then use it. Other option's to just use overrides passing validation_data_loader for every evaluate command. I figured, for my purpose at least, hardcoding to pop off `batches_per_epoch`  from validation dataloader would be easier.

**Comment by dirkgr** [comment]
The way we want to fix this is this:

When params for the validation data loader are not explicitly set, and therefore they are inherited from the training data loader, and the training data loader specifies `batches_per_epoch`, then we show a warning.

That is all.
