### ISSUE TITLE
https://raw.githubusercontent.com/allenai/allennlp/master/tutorials/tagger/training.txt with status code 404

### ISSUE THREAD

**Issue by heheda-sys** [allenai/allennlp#4571]
Hi.

In the code that runs  **LSTM for Part-of-Speech Tagging**, I have an error here.
**OSError: HEAD request failed for url https://raw.githubusercontent.com/allenai/allennlp/master/tutorials/tagger/training.txt with status code 404**.
Where can I find the training files.

**Comment by epwalsh** [comment]
Hi, what code are you talking about?

**Comment by heheda-sys** [comment]
> 
> 
> Hi, what code are you talking about?

In this https://allennlp.org/tutorials webpage,
![图片](https://user-images.githubusercontent.com/59784945/90536577-cf7f3180-e1ae-11ea-8aa3-a565ed5b921e.png),I can't find the files.

**Comment by epwalsh** [comment]
Oh I see. I think that tutorial may be badly out-of-date. I recommend you check out https://guide.allennlp.org/ instead.

@matt-gardner should we just remove that tutorial at this point?

**Comment by matt-gardner** [comment]
We don't have any first party links to that page, but there are apparently third-party links to it.  We should perhaps have it re-direct to the guide, or put a big note at the top that the guide is now preferred, or something.  But, yeah, that page should be fixed.  Not super high priority, though, as we don't have anything linking to it anywhere, I don't think.

**Comment by epwalsh** [comment]
Okay I'm going to close this now, but let me know if you have additional questions @heheda-sys.
