### ISSUE TITLE
speedup predictor.capture_model_internals by specifying layers by a regexp

### ISSUE THREAD

**Issue by mojesty** [allenai/allennlp#4574]
**Is your feature request related to a problem? Please describe.**
It turns out that predictor.capture_model_internals works really slow when the model is large, e.g. with BERT. The bottleneck is call to `sanitize` to the outputs of each layer, which will cause a lot of memory copies from torch device to python list. It may be an unnecessary computation in many cases, because for transformers predictor will capture outputs not only from each layers, but also from each attention, and so on. I think that we may make it faster by specifying regexp that should match module name to actually capture a module.

**Describe the solution you'd like**
add a parameter to the `Predictor.capture_model_internals` like `module_regex: str`, and inside the function
```
compiled_module_regex = re.compile(module_regex)
for idx, (name, module) in enumerate(self._model.named_modules()):
    if compiled_module_regex.fullmatch(name):
        <actually copy module outputs>
```

**Describe alternatives you've considered**
We may also make copying itself faster, but this will not fix the memory consumption problem.

**Comment by matt-gardner** [comment]
Something like this would be a great addition, PR welcome.
