### ISSUE TITLE
a small pretrained model occurs error with `out of memory `

### ISSUE THREAD

**Issue by wj-Mcat** [allenai/allennlp#4580]
When I run `bert+crf` model to complete sequence tagging task, it occurs RuntimeError:
```shell
RuntimeError: CUDA out of memory. Tried to allocate 148.00 MiB (GPU 2; 10.92 GiB total capacity; 7.35 GiB already allocated; 124.50 MiB free; 7.60 GiB reserved in total by PyTorch)
```
Configuration file is:
```json
{
  "dataset_reader": {
    "type": "sequence_tagging",
    "token_indexers": {
      "tokens": {
        "type": "pretrained_transformer_mismatched",
        "model_name": "bert-base-chinese"
      }
    }
  },
  "train_data_path": "./data/train_base_phrase.txt",
  "data_loader": {
    "batch_size": 16,
    "shuffle": true
  },
  "model": {
    "type": "crf_tagger",
    "text_field_embedder": {
      "token_embedders": {
        "tokens": {
          "type": "pretrained_transformer_mismatched",
          "model_name": "bert-base-chinese"
        }
      }
    },
    "encoder": {
      "type": "pass_through",
      "input_dim":768
    },
    "calculate_span_f1": true,
    "label_encoding": "BIO"
  },
  "trainer": {
    "optimizer": "adagrad",
    "patience": 10,
    "cuda_device": 2
  }
}
```

My dataset is 2.3M. So this error make me confused.  

refer to : [pretrained-model-gpu-memory-consumption](https://discourse.allennlp.org/t/pretrained-model-gpu-memory-consumption/356) , how to make pre-trained model run well for me ?

**Comment by wj-Mcat** [comment]
Customized Trainer can give me a hand ?

**Comment by epwalsh** [comment]
16 is a rather large batch size for a BERT model on a GPU with only 10-11 GB of memory. I would try a batch size of 4 or 8 instead.

**Comment by epwalsh** [comment]
@wj-Mcat, there are a couple alternatives:

- Use gradient checkpointing, i.e. set `gradient_checkpointing` to `True` in your `pretrained_transformer_mismatched` embedder config.
- Use gradient accumulation, i.e. set `num_gradient_accumulation_steps` to an integer larger than 1 in your `trainer` config. For example, setting `batch_size` to 8 and `num_gradient_accumulation_steps` to `2` gives you an effective batch size of 16.
