### ISSUE TITLE
How to get output_hidden_states of bert?

### ISSUE THREAD

**Issue by transformerzhou** [allenai/allennlp#4588]
i want to outputs for all bert-layer，not only the last layer output.
i can achieve this goal from using BertModel.from_pretrained(pretrain_path, output_hidden_states=True) in transformers,but i dont know how to use allennlp to get it.

could you help me?

**Comment by epwalsh** [comment]
Hi @transformerzhou, there is currently a `last_layer_only` parameter in the `PretrainedTransformerEmbedder` class. Setting this to `False` means the output will be a scalar mix of all of the layers, instead of just the last layer. But there is currently not a setting for simply *returning* all of the layers.

**Comment by matt-gardner** [comment]
If you want this, then you're making model assumptions that make our `TextFieldEmbedder` abstraction moot anyway, so you might as well not use it.  That is, there's no problem with just putting `self.bert_encoder = BertModel.from_pretrained(...)` in your model class, and using it directly however you want.  You'll have to pull out keys from the text field output that you get directly and pass them to the `bert_encoder` yourself in `forward`, but that's not hard.  I'm going to close this issue as resolved, but feel free to ask more questions if you have trouble getting what I suggested to work.

**Comment by transformerzhou** [comment]
> If you want this, then you're making model assumptions that make our `TextFieldEmbedder` abstraction moot anyway, so you might as well not use it. That is, there's no problem with just putting `self.bert_encoder = BertModel.from_pretrained(...)` in your model class, and using it directly however you want. You'll have to pull out keys from the text field output that you get directly and pass them to the `bert_encoder` yourself in `forward`, but that's not hard. I'm going to close this issue as resolved, but feel free to ask more questions if you have trouble getting what I suggested to work.
thank you very much!
