### ISSUE TITLE
what't the differences between pretrained_transformer_mismatched and pretrained_transformer

### ISSUE THREAD

**Issue by wj-Mcat** [allenai/allennlp#4589]
Is there a document which describes the differences between pretrained_transformer_mismatched and pretrained_transformer.  I can find the obvious differences from the code. Can you help me ? Thanks a lot

**Comment by matt-gardner** [comment]
Yes, the best place to read about that difference is [here in the guide](https://guide.allennlp.org/representing-text-as-features).
