### ISSUE TITLE
Support for make-vocab in latest version

### ISSUE THREAD

**Issue by aleSuglia** [allenai/allennlp#4593]
I've noticed that in the latest allennlp version has been removed the useful command `make-vocab`. What's the reason for it? How can we reintroduce it without breaking the current code? I think it was extremely useful when it comes to processing a *very big* dataset avoiding running the vocabulary creation process all the time. On a related note, I was wondering whether the vocabulary creation was now using multiprocessing and whether was possible to configure the number of workers running in parallel.

Thanks,
Alessandro

**Comment by matt-gardner** [comment]
We removed that command because the functionality is duplicated by the `--dry-run` flag that you can pass to the `train` command.  Let us know if you run into any issues using that flag.
