### ISSUE TITLE
How to use wikitabels parser in v1.1.0v4

### ISSUE THREAD

**Issue by aurora1625** [allenai/allennlp#4602]
Hi, 

I have tested wikitabel parser on the demo page, and it works wonderfully. I have installed the latest version v1.1.0v4, and I can't import the wikitabel model in. 
```
from allennlp.models.archival import load_archive
from allennlp.predictors import Predictor
model_path = "/home/data/allennlp/models/wikitables-model-2018.09.14.tar.gz"
predictor = Predictor.from_path(model_path)
```

The error code I got is:
```
ConfigurationError: wikitables_mml_parser is not a registered name for Model. You probably need to use the --include-package flag to load your custom code. Alternatively, you can specify your choices using fully-qualified paths, e.g. {"model": "my_module.models.MyModel"} in which case they will be automatically imported correctly.
```

I noticed this function is in v0.9, does this mean if I want to use wikitable model, I need to use an older version? Could you help to give a pointer on how to use it on the latest version?

Thanks a lot!

**Comment by matt-gardner** [comment]
You need to run `pip install allennlp-semparse`, then in python `from allennlp_semparse import models`.  After that, this should work.

**Comment by aurora1625** [comment]
> You need to run `pip install allennlp-semparse`, then in python `from allennlp_semparse import models`. After that, this should work.

Thanks, I will give it a shot!

**Comment by aurora1625** [comment]
I noticed the code structure is quite different from the example in [here](https://github.com/allenai/allennlp/issues/2916). Also the [old tutorial page](https://github.com/allenai/allennlp/blob/master/tutorials/getting_started/semantic_parsing.md) doesn't work any more. I think I will wait for the new tutorial to test it out. 

Thank you!
