### ISSUE TITLE
Allow BartEncoder to use pretrained embeddings 

### ISSUE THREAD

**Issue by tomsherborne** [allenai/allennlp#4604]
The use case I am exploring is using the full BART Encoder (including embeddings for token and position) with a decoder trained from scratch on a different vocabulary. 

The current `BartModel` uses the pretrained token representations and positional embeddings from HuggingFace however the `BartEncoder` overwrites these as a pass-through. I assume the embeddings are then meant to be implemented as an `Embedding` or `PretrainedTransformerEmbedding` which would satisfy the composition of `ComposedSeq2Seq`. However there is currently two approaches for using the BartEncoder - through BartEncoder or PretrainedTransformerEmbedder(model_name, sub_module="encoder").

One suggestion could be a flag `use_pretrained_embeddings` in the initialiser of the `BartEncoder` which retains the pre-trained `self.bart_encoder.embed_tokens` and `self.bart_encoder.embed_positions` to use the full BartEncoder with input embeddings. The source_embedder could then be set as a `pass_through` in composed_seq2seq such that the output of the Indexer for BART directly indexes the embedding matrix within the pretrained model. The inverse suggestion could be for BartEncoder to call PretrainedTransformerEmbedder. Using both BartEncoder and PretrainedTransformerEmbedder  loads BART twice (i think). Under the assumption that the encoder isn't very useful without the associated embeddings - it would be ideal if a pretrained BART model was loaded only once. 

There might be a more elegant way to capture Bart input representations (tokens + positions) but it wasn't clear to me if `PretrainedTransformerEmbedder` could support capturing both `embed_tokens` and `embed_positions` from the pre-trained model. This appeared to fail because [L#71 of PretrainedTransformerEmbedder](https://github.com/allenai/allennlp/blob/b32608e384009098efe7e208e2e2e880c22ccfbe/allennlp/modules/token_embedders/pretrained_transformer_embedder.py#L71) assumes access to only first class components of `self.transformer_model` e.g. `encoder` not `encoder.embed_tokens`. 

An example could look like this in the Bart constructor:
```
@Seq2SeqEncoder.register("bart_encoder")
class BartEncoder(Seq2SeqEncoder):
    def __init__(self, model_name, use_pretrained_embeddings=False):
        super().__init__()

        bart = BartModel.from_pretrained(model_name)
        self.hidden_dim = bart.config.hidden_size
        self.bart_encoder = bart.encoder
        if not use_pretrained_embeddings:
            self.bart_encoder.embed_tokens = lambda x: x
            self.bart_encoder.embed_positions = lambda x: torch.zeros(
                (x.shape[0], x.shape[1], self.hidden_dim), dtype=torch.float32
            )
```
The alternative could look something like:
```
@Seq2SeqEncoder.register("bart_encoder")
class BartEncoder(Seq2SeqEncoder):
    def __init__(self, model_name, use_pretrained_embeddings=False):
        super().__init__()

        #or some flag that indicates the bart encoder in it's entirety could be used. 
        if use_pretrained_embeddings:
            # will use the entire bart encoder including all embeddings
            bart = PretrainedTransformerEmbedder(model_name, sub_module="encoder")
        else:
            bart = BartModel.from_pretrained(model_name)
            self.bart_encoder.embed_tokens = lambda x: x
            self.bart_encoder.embed_positions = lambda x: torch.zeros(
                (x.shape[0], x.shape[1], self.hidden_dim), dtype=torch.float32
            )
        self.hidden_dim = bart.config.hidden_size
        self.bart_encoder = bart.encoder
```

**Comment by matt-gardner** [comment]
A `Seq2SeqEncoder` by definition operates on already-encoded inputs, not ids.  It looks like the `BartEncoder` has some hacks to make it easier to use the `BartModel` with minimal modification while matching this API.  If you want something that goes from input ids to contextualized vectors, then a `PretrainedTransformerEmbedder` is what you're looking for.  I'm reasonably confident that using `sub_module="encoder"` will do the right thing here, because the token and position embeddings are inside the `encoder` module in BART.  Have you tried it?  An easy way to check would be to see if you get the expected vectors as output if you construct the `PretrainedTransformerEmbedder` that way.

**Comment by tomsherborne** [comment]
Your suggestion works for my usecase so I'm sorted - thanks! I think that the `BartEncoder` model could still be  misleading if you can't use the pretrained embeddings or the positional embeddings. Could the docstring point users to `PretrainedTransformerEmbedder` if they want the full model with embeddings?

**Comment by matt-gardner** [comment]
Yes, a PR to update the docstring for that would be great.
