### ISSUE TITLE
Merging allennlp-semparse into allennlp-models.

### ISSUE THREAD

**Issue by OhadRubin** [allenai/allennlp#4606]
The original plan as I understand it was to have task specific repositories (rc,semparse), and to have a allennlp-hub that pip installs all of the task-specific repos.
But allennlp-hub turned into allennlp-models, and allennlp-rc was merged into it, and allennlp-semparse was not.

**Comment by matt-gardner** [comment]
The semantic parsing code has a substantial amount of separate, unrelated components.  There's a ton of stuff around defining grammars, transition functions, and other things.  I view it as a separate library that's built on top of allennlp, not a collection of models built with allennlp.  So, no, I don't think we're going to be merging the semparse repo into the models repo.
