### ISSUE TITLE
How to save test result when use `evaluate_on_test` command?

### ISSUE THREAD

**Issue by Albert-Ma** [allenai/allennlp#4620]
Thanks, new to allennlp!

**Comment by AkshitaB** [comment]
Hi @Albert-Ma , do you mean the test metrics? They are saved in the file `<serialization_dir>/metrics.json` with the prefix `test_` when using `evaluate_on_test`. Let me know if that helps!

**Comment by Albert-Ma** [comment]
> Hi @Albert-Ma , do you mean the test metrics? They are saved in the file `<serialization_dir>/metrics.json` with the prefix `test_` when using `evaluate_on_test`. Let me know if that helps!

No, I mean the predict result of my test set, just like the `output_file` when use `allennlp predict`

**Comment by AkshitaB** [comment]
@Albert-Ma We recommend that you use `allennlp predict` for getting the prediction results.

@matt-gardner @dirkgr We discussed during standup that we want to keep the `evaluate_on_test` flag in the train command, and merge `evaluate` and `predict` commands.

**Comment by schmmd** [comment]
Closing in favor of #4626
