### ISSUE TITLE
No module named allennlp.run

### ISSUE THREAD

**Issue by juliahane** [allenai/allennlp#4627]
Hi
I installed allennlp 1.0.0, and then I want to use it to run this repo:
https://github.com/mrqa/MRQA-Shared-Task-2019/tree/master/baseline
I write this command to run bert-base on some QA datasets:

python -m allennlp.run train https://multiqa.s3.amazonaws.com/config/MRQA_BERTbase.json -s Models/SQuAD -o "{'train_data_path': 'https://mrqa.s3.us-east-2.amazonaws.com/data/train/SQuAD.jsonl.gz', 'validation_data_path': 'https://mrqa.s3.us-east-2.amazonaws.com/data/dev/SQuAD.jsonl.gz', 'trainer': {'cuda_device': -1, 'num_epochs': 2, 'optimizer': {'type': 'bert_adam', 'lr': 3e-05, 'warmup': 0.1, 't_total': 29000}}}" --include-package mrqa_allennlp

but then it says 
No module named allennlp.run

thanks for your help

**Comment by epwalsh** [comment]
Hi @juliahane, could you please provide a complete stack trace?

**Comment by juliahane** [comment]
Hi
The full stack trace is only this error:

(qa) julia@vgnh006:/user/julia/dev/MRQA-Shared-Task-2019$ python -m allennlp.run train https://multiqa.s3.amazonaws.com/config/MRQA_BERTbase.json -s Models/SQuAD -o "{'train_data_path': 'https://mrqa.s3.us-east-2.amazonaws.com/data/train/SQuAD.jsonl.gz', 'validation_data_path': 'https://mrqa.s3.us-east-2.amazonaws.com/data/dev/SQuAD.jsonl.gz', 'trainer': {'cuda_device': -1, 'num_epochs': 2, 'optimizer': {'type': 'bert_adam', 'lr': 3e-05, 'warmup': 0.1, 't_total': 29000}}}" --include-package mrqa_allennlp
/user/julia/libs/anaconda3/envs/qa/bin/python: No module named allennlp.run

**Comment by juliahane** [comment]
Hi
I am not sure what is the correct way to train models with allennlp bu if the command is "allennlp train" then I got the following errors:

allennlp train https://multiqa.s3.amazonaws.com/config/MRQA_BERTbase.json -s Models/SQuAD -o "{'train_data_path': 'https://mrqa.s3.us-east-2.amazonaws.com/data/train/SQuAD.jsonl.gz', 'validation_data_path': 'https://mrqa.s3.us-east-2.amazonaws.com/data/dev/SQuAD.jsonl.gz', 'trainer': {'cuda_device': 0, 'num_epochs': 2, 'optimizer': {'type': 'bert_adam', 'lr': 3e-05, 'warmup': 0.1, 't_total': 29000}}}" --include-package mrqa_allennlp
2020-09-10 20:43:34,248 - INFO - transformers.file_utils - PyTorch version 1.5.1 available.
Traceback (most recent call last):
  File "user/julia/libs/anaconda3/envs/qa/bin/allennlp", line 8, in <module>
    sys.exit(run())
  File "user/julia/libs/anaconda3/envs/qa/lib/python3.7/site-packages/allennlp/__main__.py", line 19, in run
    main(prog="allennlp")
  File "/user/julia/libs/anaconda3/envs/qa/lib/python3.7/site-packages/allennlp/commands/__init__.py", line 91, in main
    import_module_and_submodules(package_name)
  File "/user/julia/libs/anaconda3/envs/qa/lib/python3.7/site-packages/allennlp/common/util.py", line 340, in import_module_and_submodules
    module = importlib.import_module(package_name)
  File "/user/julia/libs/anaconda3/envs/qa/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/user/julia/dev/MRQA-Shared-Task-2019/baseline/mrqa_allennlp/__init__.py", line 2, in <module>
    from mrqa_allennlp.BERT_QA import *
  File "/user/julia/dev/MRQA-Shared-Task-2019/baseline/mrqa_allennlp/BERT_QA.py", line 17, in <module>
    from allennlp.tools import squad_eval
ImportError: cannot import name 'squad_eval' from 'allennlp.tools' (/user/julia/libs/anaconda3/envs/qa/lib/python3.7/site-packages/allennlp/tools/__init__.py)

**Comment by juliahane** [comment]
Hi
I greatly appreciate if you could check this repo: 
https://github.com/mrqa/MRQA-Shared-Task-2019/tree/master/baseline

and just run the BERT base command, and let me know how I can use allennlp
thanks.

**Comment by epwalsh** [comment]
Please tell me what operating system you are using, and also paste the output of `pip freeze`.

**Comment by dirkgr** [comment]
I am pretty sure the problem is that MRQA-Shared-Task-2019 depends on `allennlp<1.0`, but it just specifies `allennlp`.

@juliahane, can you run `pip install "allennlp<1.0"`, and check if that works?

**Comment by juliahane** [comment]
Hi
thanks a lot, indeed with allennlp <1 it does not go to that issue, but now
this does not recognize the GPU, I tried with multiple gpus, and with all
it does not recognize it, I provide the command below and the error stack,
here is also the versions I used

allennlp                  0.9.0                     <pip>
pytorch-pretrained-bert   0.6.2                     <pip>
pytorch-transformers      1.1.0                     <pip>
torch                     1.6.0                     <pip>
python                    3.7.9                h7579374_0
python-dateutil           2.8.1                     <pip>

thanks.

Kind regards
Julia

(qa) julia@vgnd007:/user/julia/dev/MRQA-Shared-Task-2019/baseline$ python
-m allennlp.run train
https://multiqa.s3.amazonaws.com/config/MRQA_BERTbase.json -s
/user/julia/MRQASharedTask/Models/SQuAD -o "{'train_data_path': '
https://mrqa.s3.us-east-2.amazonaws.com/data/train/SQuAD.jsonl.gz',
'validation_data_path': '
https://mrqa.s3.us-east-2.amazonaws.com/data/dev/SQuAD.jsonl.gz',
'trainer': {'cuda_device': 0, 'num_epochs': 2, 'optimizer': {'type':
'bert_adam', 'lr': 3e-05, 'warmup': 0.1, 't_total': 29000}}}"
--include-package mrqa_allennlp
2020-09-11 10:23:37,759 - INFO - pytorch_pretrained_bert.modeling - Better
speed can be achieved with apex installed from
https://www.github.com/nvidia/apex .
2020-09-11 10:23:39,521 - INFO - pytorch_transformers.modeling_bert -
Better speed can be achieved with apex installed from
https://www.github.com/nvidia/apex .
2020-09-11 10:23:39,532 - INFO - pytorch_transformers.modeling_xlnet -
Better speed can be achieved with apex installed from
https://www.github.com/nvidia/apex .
2020-09-11 10:23:40,487 - INFO - allennlp.common.registrable -
instantiating registered subclass relu of <class
'allennlp.nn.activations.Activation'>
2020-09-11 10:23:40,490 - INFO - allennlp.common.registrable -
instantiating registered subclass relu of <class
'allennlp.nn.activations.Activation'>
2020-09-11 10:23:40,493 - INFO - allennlp.common.registrable -
instantiating registered subclass relu of <class
'allennlp.nn.activations.Activation'>
2020-09-11 10:23:40,496 - INFO - allennlp.common.registrable -
instantiating registered subclass relu of <class
'allennlp.nn.activations.Activation'>
2020-09-11 10:23:41,501 - INFO - allennlp.common.params - random_seed =
13370
2020-09-11 10:23:41,501 - INFO - allennlp.common.params - numpy_seed = 1337
2020-09-11 10:23:41,501 - INFO - allennlp.common.params - pytorch_seed = 133
2020-09-11 10:23:41,539 - INFO - allennlp.common.checks - Pytorch version:
1.6.0
Traceback (most recent call last):
  File "/user/julia/libs/anaconda3/envs/qa/lib/python3.7/runpy.py", line
193, in _run_module_as_main
    "__main__", mod_spec)
  File "/user/julia/libs/anaconda3/envs/qa/lib/python3.7/runpy.py", line
85, in _run_code
    exec(code, run_globals)
  File
"/user/julia/libs/anaconda3/envs/qa/lib/python3.7/site-packages/allennlp/run.py",
line 21, in <module>
    run()
  File
"/user/julia/libs/anaconda3/envs/qa/lib/python3.7/site-packages/allennlp/run.py",
line 18, in run
    main(prog="allennlp")
  File
"/user/julia/libs/anaconda3/envs/qa/lib/python3.7/site-packages/allennlp/commands/__init__.py",
line 102, in main
    args.func(args)
  File
"/user/julia/libs/anaconda3/envs/qa/lib/python3.7/site-packages/allennlp/commands/train.py",
line 124, in train_model_from_args
    args.cache_prefix)
  File
"/user/julia/libs/anaconda3/envs/qa/lib/python3.7/site-packages/allennlp/commands/train.py",
line 168, in train_model_from_file
    cache_directory, cache_prefix)
  File
"/user/julia/libs/anaconda3/envs/qa/lib/python3.7/site-packages/allennlp/commands/train.py",
line 212, in train_model
    check_for_gpu(cuda_device)
  File
"/user/julia/libs/anaconda3/envs/qa/lib/python3.7/site-packages/allennlp/common/checks.py",
line 81, in check_for_gpu
    raise ConfigurationError("Experiment specified a GPU but none is
available;"
allennlp.common.checks.ConfigurationError: "Experiment specified a GPU but
none is available; if you want to run on CPU use the override
'trainer.cuda_device=-1' in the json config file."

**Comment by dirkgr** [comment]
It looks like your config is specifying a GPU, but you don't have one. Just switch `cuda_device: 0` out for `cuda_device: -1` in the config file!

**Comment by dirkgr** [comment]
Sorry, I did not read your message carefully enough. AllenNLP relies on torch for the GPUs. If torch sees the GPU, so do we. I suspect what happened is that it automatically installed an older version of pytorch, but one that doesn't have CUDA support.

**Comment by juliahane** [comment]
Hi
I realized that the issue was that allennlp install pytorch by itself,
installing pytorch from pip is buggy, then I installed it with conda and it
worked.

**Comment by dirkgr** [comment]
Cool! Let us know if you have more problems with it.
