### ISSUE TITLE
guard against using unspecified GPUs

### ISSUE THREAD

**Issue by lucylw** [allenai/allennlp#463]
When transferring data onto GPU, it would be helpful if the library would guard against using unspecified GPUs based on the specified GPU in the config file, i.e.

```python
with torch.cuda.device(cuda_device):
   # all cuda data transfers
```
otherwise, some data can wind up being transferred onto an unspecified device (default GPU), which could be used by another process at the same time.

I experienced some related issues, e.g. GPU0 was being used, I specified GPU5, some of the model was transferred onto GPU0, and there was an out of memory error.

Related, it would also be nice if the library could check whether the specified GPU is available before loading data rather than after.

**Comment by matt-gardner** [comment]
Do you know where in particular the wrong GPU was being used?

**Comment by lucylw** [comment]
In pytorch, when `torch.nn.Module.cuda(cuda_device_number)` is called, some context gets generated on the default CUDA device (first visible device, usually GPU0), in addition to the device specified by cuda_device_number.

**Comment by matt-gardner** [comment]
Write, I'm wondering if you know where in _AllenNLP_ code we're doing the wrong thing.  We can search for it, but if you've already pinpointed some spots, that'd be helpful.

**Comment by lucylw** [comment]
@matt-gardner Ah, right. The only place I've noticed it so far is `allennlp.training.trainer.py:515`:

```python
if cuda_device >= 0:
    model = model.cuda(cuda_device)
```

I would expect this to only put context on the specified `cuda_device`. When `cuda_device` does not equal 0, then at the end of this, there will be some memory used on the GPU specified by `cuda_device` and some memory used on GPU0.

**Comment by matt-gardner** [comment]
Ok, I'm guessing there is some spot where we're doing something like `tensor.cuda()` without specifying a device, and we need to dig through the code to figure out where it is.  If you can give us a reliable failure case that we can reproduce, that'd be helpful in tracking this down.

**Comment by lucylw** [comment]
After digging a bit further, I don't think this is an AllenNLP bug at all. It seems like a problem with pytorch. It happens only when moving the model onto GPU, e.g.

```python
import torch
import torch.nn as nn

features = 50
hidden_size = 50
num_layers = 2
cuda_device = 1    # on a machine with multiple GPUs (>0)

model = nn.Module()
model.rnn = nn.RNN(input_size=features, hidden_size=hidden_size, num_layers=num_layers)
model.cuda(cuda_device)
```

After model.cuda(cuda_device), there will be memory used on the specified GPU (in this case, cuda_device=1), as well as the default GPU (which is usually device 0).

```python
seq_len = 10
batch_size = 32

X_train = torch.randn(seq_len, batch_size, features)
X_train = Variable(X_train).cuda(cuda_device)
```

The same problem doesn't seem to occur when moving tensors onto GPU (as above).

We could try to make sure this doesn't happen by adding a with construct around the model.cuda line in AllenNLP, i.e.:

```python
with torch.cuda.device(cuda_device):
    model.cuda(cuda_device)
```

...but I think the chance of this causing problems for other people is pretty low, so it may not be worth making a ton of effort here. And maybe the issue will be addressed in pytorch in the future.
