### ISSUE TITLE
add cache_dir parameter to PretrainedTransformerEmbedder

### ISSUE THREAD

**Issue by wolhandlerdeb** [allenai/allennlp#4631]
Hi,
I would like to set a custom cache_dir (like in hugging face model) when loading PretrainedTransformerEmbedder. Indeed, my cache directory by default has not enough memory.

add a cache_dir parameter to PretrainedTransformerEmbedder as in BertModel in HuggingFace
As I can write: BertModel.from_pretrained(bert_model_name, cache_dir = ""), I would like to be able to write 
PretrainedTransformerEmbedder(bert_model_name, cache_dir = "")

Thanks

**Comment by dirkgr** [comment]
You can just set the `TRANSFORMERS_CACHE` environment variable to point to the right directory. Does that help?

**Comment by wolhandlerdeb** [comment]
It's working! 
Thanks
