### ISSUE TITLE
What types of sequence labeling models are possible to train?

### ISSUE THREAD

**Issue by CatarinaPC** [allenai/allennlp#4636]
I'm having a bit out trouble finding what types of sequence labeling models, in particular, for NER, are possible to train using AllenNLP?

In other words, what are all the architectures that one can use? For example, BI-LSTM-CRF.

**Comment by epwalsh** [comment]
Hi @CatarinaPC, if you haven't found the `CrfTagger` model yet, take a look here: https://github.com/allenai/allennlp-models/blob/master/allennlp_models/tagging/models/crf_tagger.py.

With this model you can use any `TextFieldEmbedder`, `Seq2SeqEncoder`, and additional `FeedForward` layers that you want.
