### ISSUE TITLE
Documentation of PytorchSeq2VecWrapper is confusing

### ISSUE THREAD

**Issue by KwanWaiChung** [allenai/allennlp#4641]
The Documentation says:   
"Pytorch's RNNs have two outputs: the hidden state for every time step, and the hidden state at
    the last time step for every layer.  We just want the second one as a single output." However, this wrapper seems to return the hidden state at the last time step for the LAST layer instead of every layers?

**Comment by epwalsh** [comment]
Hey @KwanWaiChung, thanks for pointing that out. Would you be interesting in opening a pull request to fix it?

**Comment by KwanWaiChung** [comment]
> Hey @KwanWaiChung, thanks for pointing that out. Would you be interesting in opening a pull request to fix it?

Of course!
