### ISSUE TITLE
Immediate removal of temp dir in load_archive

### ISSUE THREAD

**Issue by mulhod** [allenai/allennlp#4642]
**Is your feature request related to a problem? Please describe.**
In the `archival.load_archive` function, the archive file (if it is not a directory, that is) is extracted to a temporary directory and that directory’s removal is postponed till the interpreter exits (via `atexit`). This is done because the extracted directory’s contents are used outside this function in some cases. I have a use case where I would like to remove this temporary directory as soon as possible (by the end of `load_archive`). I have long-running interpreter sessions involving many models being loaded (and used for inference only) and I don’t want such temporary directories to be retained if they are not needed.

Currently, I’m working around this by extracting the archive file myself and then passing in the extracted directory path, calling `load_archive` with that path, then manually cleaning up.

**Describe the solution you'd like**
Ideally I would like to be able to call `load_archive` with an archive file directly and have the temporary directory that it creates removed without postponement. For example, a `postpone_cleanup` keyword argument in `load_archive` (and in some other methods that call it) that is set to `True` by default so as not to change anything about normal operation, but can be set to `False` if a user wants this behavior.

**Describe alternatives you've considered**
The alternative is doing this manually.

**Additional context**
I will be submitting a PR to address this issue.

**Comment by epwalsh** [comment]
Closing per #4643
