### ISSUE TITLE
[Feature request] subcommand for calling cached_path

### ISSUE THREAD

**Issue by epwalsh** [allenai/allennlp#4647]
I think it would be nice to have a subcommand like `allennlp cached-path RESOURCE` so you could call `cached_path()` from the command line. This would be very useful when you want to inspect a dataset directly, for example. Like you could just call

```
vim $(allennlp cached-path https://allennlp.s3.amazonaws.com/datasets/squad/squad-train-v2.0.json)
```

I'd also appreciate an easy way to know where the cache directory is and what's in it. That could be done with

```
allennlp cached-path --inspect
```

which could print out the cache location and the approximate size of the cache.

**Comment by matt-gardner** [comment]
As long as we're giving feature requests, I would add that it would be lovely if `cached-path --inspect` actually gave me information on what the individual things are in the cache, not just hashed identifiers, and when they were downloaded (and any other metadata we might have or want).  We could do this by storing something like a `[HASH].meta` next to every downloaded path, which `cached-path --inspect` would read and format nicely.

**Comment by epwalsh** [comment]
We already store some meta for each cached resource so that is definitely doable: https://github.com/allenai/allennlp/blob/master/allennlp/common/file_utils.py#L455

**Comment by matt-gardner** [comment]
Oh, even better!  I didn't know we already did that.
