### ISSUE TITLE
Closing the TensorBoard writer

### ISSUE THREAD

**Issue by mahnerak** [allenai/allennlp#4653]
I had noticed that sometimes tensorboard fails to properly read the `tfevents` files.
They are mainly in case of runs which I decided to interrupt the training (not sure about other abortion scenarios).
Then, I wanted to make sure the tensorboard writer is properly closed. I found the `close()` is called only here, but not inside any `with` or `finally` construct:
https://github.com/allenai/allennlp/blob/fbd2ccca1dd767e919a62d344c6b6569fc38227a/allennlp/training/trainer.py#L970
Here we can see the writer is closed just by calling `.close()` so there's no guarantee that the data is going to be flushed.

Is there any reason for this implementation? Does this need to be fixed?

**Comment by epwalsh** [comment]
Hi @mahnerak, that seems like an oversight on our part. Would you be interested in making a PR to fix that?

**Comment by mahnerak** [comment]
Sure!

I just don't want to increase the indentation of the train-loop code by adding `try/finally` and `with` to `train()`.

One good option is to add `close()` method to `Trainer` so it can handle even multiple handles to be closed. And the trainer instance can be closed from:

https://github.com/allenai/allennlp/blob/fbd2ccca1dd767e919a62d344c6b6569fc38227a/allennlp/commands/train.py#L503-L506

**Comment by epwalsh** [comment]
Cool. I think maybe `Trainer.clean_up()` is a better/more general name for the method?
