### ISSUE TITLE
Allow overrides to be JSON string or dict

### ISSUE THREAD

**Issue by mulhod** [allenai/allennlp#4656]
**Is your feature request related to a problem? Please describe.**
Currently, `overrides` expects a JSON string representing a dictionary. It would be nice to be able to pass in a Python `dict` or a JSON string. This would make it slightly easier if using Python directly to pass in a value to `overrides`.

**Describe the solution you'd like**
Enable `overrides` to accept either a JSON string or a Python `dict`.

**Describe alternatives you've considered**
The alternative is to use `json.dumps` to dump the `dict` to a `str` and pass that value in via `overrides`.

**Additional context**
Mentioned in #4651

**Comment by epwalsh** [comment]
Closed via https://github.com/allenai/allennlp/pull/4680
