### ISSUE TITLE
Transformer elmo link broken on elmo help page

### ISSUE THREAD

**Issue by AngledLuffa** [allenai/allennlp#4659]
There is a link to a tutorial for transformer elmo on the elmo page:

https://allennlp.org/elmo

https://github.com/allenai/allennlp/blob/master/tutorials/how_to/training_transformer_elmo.md

Unfortunately, this tutorial is also missing.

**Comment by schmmd** [comment]
We didn't end up maintaining this tutorial for 1.0.  You can find it in the GitHub history (https://github.com/allenai/allennlp/blob/052353ed62e3a54fd7b39a660e65fc5dd2f91c7d/tutorials/how_to/training_transformer_elmo.md) but it will be somewhat out of date for the latest version of AllenNLP.
