### ISSUE TITLE
How to pad words in elmo?

### ISSUE THREAD

**Issue by AngledLuffa** [allenai/allennlp#4661]
Is there a standard way to pad words in elmo?  For example, if I have the following two sentences:

This is a long sentence
Short sentence

and I pass the tokens from these sentences to elmo.batch_to_ids, I get back some 0s.  However, suppose I have a model which needs a minimum sentence length of 5, and my only text is

Short sentence

If I pass in 

['short', 'sentence', '', '', '']

I get back a few words composed of start/end tokens.  How can I get the equivalent 0s from above?

**Comment by matt-gardner** [comment]
The way we handle this in our standard padding pipeline is to just add a padding tokens and make sure we use a mask that says which words should be ignored.  If you use our `TextFields` to do data processing this will happen for you automatically.
