### ISSUE TITLE
from allennlp.data.dataset_readers.seq2seq import Seq2SeqDatasetReader in v 1.1.0

### ISSUE THREAD

**Issue by izaskr** [allenai/allennlp#4667]
## Checklist

- [x] I have verified that the issue exists against the `master` branch of AllenNLP.
- [x] I have read the relevant section in the [contribution guide](https://github.com/allenai/allennlp/blob/master/CONTRIBUTING.md#bug-fixes-and-new-features) on reporting bugs.
- [x] I have checked the [issues list](https://github.com/allenai/allennlp/issues) for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/allenai/allennlp/pulls) for existing proposed fixes.
- [x] I have checked the [CHANGELOG](https://github.com/allenai/allennlp/blob/master/CHANGELOG.md) and the [commit log](https://github.com/allenai/allennlp/commits/master) to find out if the bug was already fixed in the master branch.
- [x] I have included in the "Description" section below a traceback from any exceptions related to this bug.
- [x] I have included in the "Related issues or possible duplicates" section beloew all related issues and possible duplicate issues (If there are none, check this box anyway).
- [x] I have included in the "Environment" section below the name of the operating system and Python version that I was using when I discovered this bug.
- [x] I have included in the "Environment" section below the output of `pip freeze`.
- [x] I have included in the "Steps to reproduce" section below a minimally reproducible example.

## Description

<details>
<summary><b>Python traceback:</b></summary>
<p>

```
>>> from allennlp.data.dataset_readers.seq2seq import Seq2SeqDatasetReader
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'allennlp.data.dataset_readers.seq2seq'
```

</p>
</details>

## Related issues or possible duplicates

- None

## Environment

OS: Linux

Python version: 3.7.9

<details>
<summary><b>Output of <code>pip freeze</code>:</b></summary>
<p>

```
allennlp==1.1.0
allennlp-models==1.1.0
attrs==20.2.0
Automat==20.2.0
blis==0.4.1
boto3==1.15.4
botocore==1.18.4
catalogue==1.0.0
certifi==2020.6.20
chardet==3.0.4
click==7.1.2
Comet==3.1.0
comet-ml==3.2.1
configobj==5.0.6
conllu==4.1
constantly==15.1.0
cymem==2.0.3
dulwich==0.20.6
everett==1.0.2
filelock==3.0.12
ftfy==5.8
future==0.18.2
h5py==2.10.0
hyperlink==20.0.1
idna==2.10
importlib-metadata==2.0.0
incremental==17.5.0
iniconfig==1.0.1
jmespath==0.10.0
joblib==0.16.0
jsonnet==0.16.0
jsonpickle==1.4.1
jsonschema==3.2.0
lxml==4.5.2
more-itertools==8.5.0
murmurhash==1.0.2
netifaces==0.10.9
nltk==3.5
numpy==1.19.2
nvidia-ml-py3==7.352.0
overrides==3.1.0
packaging==20.4
plac==1.1.3
pluggy==0.13.1
preshed==3.0.2
protobuf==3.13.0
py==1.9.0
py-rouge==1.1
PyHamcrest==2.0.2
pyparsing==2.4.7
pyrsistent==0.17.3
pytest==6.0.2
python-dateutil==2.8.1
regex==2020.7.14
requests==2.24.0
s3transfer==0.3.3
sacremoses==0.0.43
scikit-learn==0.23.2
scipy==1.5.2
sentencepiece==0.1.91
six==1.15.0
spacy==2.3.2
srsly==1.0.2
tensorboardX==2.1
thinc==7.4.1
threadpoolctl==2.1.0
tokenizers==0.8.1rc1
toml==0.10.1
torch==1.6.0
tqdm==4.49.0
transformers==3.0.2
Twisted==20.3.0
urllib3==1.25.10
wasabi==0.8.0
wcwidth==0.2.5
websocket-client==0.57.0
word2number==1.1
wrapt==1.12.1
wurlitzer==2.0.1
zipp==3.2.0
zope.interface==5.1.0

```

</p>
</details>

## Steps to reproduce
Activate the conda env for allennlp 1.1.0, start python console. Import allennlp and then from allennlp.data.dataset_readers.seq2seq import Seq2SeqDatasetReader.

<details>
<summary><b>Example source:</b></summary>
<p>

```
import allennlp
from allennlp.data.dataset_readers.seq2seq import Seq2SeqDatasetReader
```

</p>
</details>

**Comment by matt-gardner** [comment]
As of version 1.0 that code moved to `allennlp_models`.  You'll need to run `pip install allennlp_models` and change your import location.

**Comment by izaskr** [comment]
Thanks, this worked indeed:
`from allennlp_models.generation import Seq2SeqDatasetReader`
