### ISSUE TITLE
Cuda check before vocabulary gets built

### ISSUE THREAD

**Issue by asvskartheek** [allenai/allennlp#4678]
**Is your feature request related to a problem? Please describe.**
Whenever there is a cuda related error like, you are on CPU so use -1 or anything else is given after the vocabulary gets created i.e, after the log and configuration folder gets created. So, changing this and running allennlp gives an error that there is a folder with the same name already present. So, it needs to be deleted and then re-run the command.

**Describe the solution you'd like**
It would be better to check for Hardware related issues before creating the Vocabulary.

**Describe alternatives you've considered**
An alternative would be to automatically detect a CPU and ignore the cuda device related parameters in the configuration file.

**Additional context**

**Comment by epwalsh** [comment]
@asvskartheek FYI if you leave the cuda device unspecified, AllenNLP will automatically use a GPU if one is available, otherwise it defaults to CPU.

**Comment by asvskartheek** [comment]
@epwalsh Thank you for the suggestion, I'm aware of this feature. I'm curious as what would be the behaviour when there are multiple GPUs and nothing is specified? I feel it would also be better if all the system related checks are done before the vocabulary gets built or any other data specific operation is done.

**Comment by epwalsh** [comment]
Yea, that would definitely be helpful. I know I've had the same frustration at times.

I'm thinking the best way to solve this would be to have a `validate_config` function that is called here:https://github.com/allenai/allennlp/blob/55cfb47b5a0c84fa9ae97b792f82805919a0149a/allennlp/commands/train.py#L224

Within `validate_config` we could call [`check_for_gpu`](https://github.com/allenai/allennlp/blob/55cfb47b5a0c84fa9ae97b792f82805919a0149a/allennlp/commands/train.py#L257) and maybe some other basic checks as well.

**Comment by epwalsh** [comment]
@asvskartheek would you be interested in making a PR?

**Comment by asvskartheek** [comment]
@epwalsh Oh! Yeah, sure. I'll be on it.

**Comment by asvskartheek** [comment]
@epwalsh In the validate_config method, I'm checking for
1. The serialization dir.
2. The Cuda check.
3. Check if all the parameters passed are appropriate. For example: if there is a custom data_reader written but it was not added using --include-package or maybe it was not even registered in the first place.

Do you have anything else to add to this checklist?

**Comment by epwalsh** [comment]
That sounds like a good start. If I think of anything else I will let you know!

**Comment by asvskartheek** [comment]
@epwalsh I'm creating the validate_config() method in allennlp.common.checks and also can you help me where the pt. 3 is already implemented, so I can take that as a reference while writing.
Thanks :)

**Comment by epwalsh** [comment]
I don't think we have a function for this yet, but you could implement this by checking that the registered name is in the result of `.list_available()`:

https://github.com/allenai/allennlp/blob/321d4f48f6c14a559386afa4d19ae96b829fd025/allennlp/common/registrable.py#L193

For example, to check that the dataset reader is registered:

```python
assert params["dataset_reader"]["type"] in DatasetReader.list_available()
```
