### ISSUE TITLE
Multi-task Learning in AllenNLP v. 1.1.0

### ISSUE THREAD

**Issue by Mayar2009** [allenai/allennlp#4688]
Hi! 
It look understandable in this example [https://github.com/huggingface/hmtl](url)

how to use multitask training but the version was 0.8.x
Is there any complete  example for multi task training for the present version?

**Comment by dirkgr** [comment]
This issue is now a little stale, but we have an example config for multitask training here: https://github.com/allenai/allennlp-models/blob/main/training_config/vision/vilbert_multitask.jsonnet
