### ISSUE TITLE
pass loss function and metrics in config

### ISSUE THREAD

**Issue by KwanWaiChung** [allenai/allennlp#4698]
In the official [example](https://github.com/allenai/allennlp-guide-examples/blob/master/quick_start/my_text_classifier/models/simple_classifier.py), both metrics and loss function are hard coded. I am wondering if we can pass those in the config jsonnet, so I can reuse my model in different datasets with different metrics.

**Comment by dirkgr** [comment]
`Metric` is registrable, so you can easily add a parameter to you model of type `List[Metric]`, and then specify metrics in Jsonnet. You'll have to make sure those metrics take exactly the same input.

For the loss, this is a little bit harder. You would create your own `Registrable` base class, and then implement the losses you want to use this way. You can use the `Metric` class as an example of how to do this. It would be a bit of typing work, but not difficult.
