### ISSUE TITLE
Make the predictions more flexible

### ISSUE THREAD

**Issue by mateuszpieniak** [allenai/allennlp#4714]
**Is your feature request related to a problem? Please describe.**
I implemented a `DatasetReader` to handle the ConLL format file, trained the model, now it's time for inference on the external dataset. I run predictions on RIS files where one entity / object spans for a multiple lines. 

In the current implementation of `Predictor` and `allennlp predict` I can:
  - work with a single line of the input file by overriding method `load_line`
  - use training / validation dataset reader

**Describe the solution you'd like**
Allow passing any DatasetReader class in `allennlp predict`. 

**Describe alternatives you've considered**
A workaround for me was just to process RIS format into jsonl, but it's an overhead.

**Additional context**
https://en.wikipedia.org/wiki/RIS_(file_format)

**Comment by dirkgr** [comment]
Did you look into the `allennlp evaluate` command? It uses a dataset reader to process instances.

**Comment by mateuszpieniak** [comment]
@dirkgr I didn't. How can I provide a different `DatasetReader` into evaluation?
> usage: allennlp evaluate [-h] [--output-file OUTPUT_FILE]
                         [--weights-file WEIGHTS_FILE]
                         [--cuda-device CUDA_DEVICE] [-o OVERRIDES]
                         [--batch-size BATCH_SIZE]
                         [--batch-weight-key BATCH_WEIGHT_KEY]
                         [--extend-vocab]
                         [--embedding-sources-mapping EMBEDDING_SOURCES_MAPPING]
                         [--file-friendly-logging]
                         [--include-package INCLUDE_PACKAGE]
                         archive_file input_file

**Comment by dirkgr** [comment]
Do you want to use a different class, or just a different input file? The input file is one of the parameters.
