### ISSUE TITLE
Docstring for AllenNlpTestCase is out-of-date

### ISSUE THREAD

**Issue by nicolasahar** [allenai/allennlp#4716]
https://github.com/allenai/allennlp/blob/ae7cf85b8f755f086341a087aeca1ba7c1df3769/allennlp/common/testing/test_case.py#L14

This docstring suggests that the TestCase class should subclass `unittest.TestCase` but it does not do so. Should this be updated or is this intentional?

**Comment by epwalsh** [comment]
The docstring is out-of-date. Would you be interested in making a PR to fix it?

**Comment by nicolasahar** [comment]
> The docstring is out-of-date. Would you be interested in making a PR to fix it?

Done. PR #4722 [here](https://github.com/allenai/allennlp/pull/4722)
