### ISSUE TITLE
Support for transformers 3.1.0

### ISSUE THREAD

**Issue by javierabosch** [allenai/allennlp#4718]
Are there any plans to support transformers 3.1 and above? 

Currently, pip install allennlp will uninstall transformers version later than 3.0.2

**Comment by epwalsh** [comment]
We do: https://github.com/allenai/allennlp/blob/master/setup.py#L67. You can get this by installing the [latest nightly release](https://pypi.org/project/allennlp/#history) or installing directly from the master branch.
