### ISSUE TITLE
Thank you and acknowledgement

### ISSUE THREAD

**Issue by johntiger1** [allenai/allennlp#4721]
Hi @matt-gardner , just wanted to say thanks for your help in answering my questions when using your framework. It was a big help for my experiments and research project. My project was recently accepted as an oral presentation at the workshop ClinicalNLP @EMNLP 2020; and I just thought I would give you an acknowledgement:

![image](https://user-images.githubusercontent.com/14852840/95666315-797f9800-0b26-11eb-85b9-0bfbc34e7da4.png)

Does that look OK to you?

Thanks!

**Comment by matt-gardner** [comment]
Glad it was helpful, and congrats on your acceptance!  Yes, that text seems fine.
