### ISSUE TITLE
Dependabot is running on forks

### ISSUE THREAD

**Issue by matt-gardner** [allenai/allennlp#4725]
See [here](https://github.com/matt-gardner/allennlp/pull/4) for a PR that was created by dependabot on my fork.  My guess is that this is because of [this file](https://github.com/allenai/allennlp/blob/master/.github/dependabot.yml), but it wasn't obvious to me how to disable this on forks (nothing in the [documentation](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates) that I could easily find, either).

**Comment by epwalsh** [comment]
See [this thread](https://github.com/dependabot/dependabot-core/issues/2198) for some info, specifically [this comment](https://github.com/dependabot/dependabot-core/issues/2198#issuecomment-649444075). Sounds like the only solution at the moment is to re-fork AllenNLP.

**Comment by schmmd** [comment]
The settings here won't work? https://github.com/allenai/allennlp/settings/security_analysis

**Comment by matt-gardner** [comment]
@schmmd, those are for vulnerabilities, and they are not enabled on my fork.
