### ISSUE TITLE
logging information gets truncated for 1.1.0

### ISSUE THREAD

**Issue by niansong1996** [allenai/allennlp#4736]
I am experiencing very weird logging issues with allennlp 1.1.0. The logging information gets truncated and it's refreshing every ~10s and burst out many lines all at once, see the screenshot below:
![image](https://user-images.githubusercontent.com/10934810/96358986-51baa200-10db-11eb-8889-9ec6df21bbbc.png)

And this is the behavior of the same run with allennlp 1.1.0rc1, which is far more pleasant for me to monitor the process:
![image](https://user-images.githubusercontent.com/10934810/96359003-89294e80-10db-11eb-8650-f8b5ea2b3b1f.png)

**Comment by epwalsh** [comment]
So far I haven't been able to reproduce this.

Are you using the `--file-friendly-logging` flag? And what operating system and terminal are you running this on? If possible, could you also provide a screen recording of your terminal when you run this?

**Comment by niansong1996** [comment]
No, I did not add the flag `--file-friendly-logging` (which is `false` by default, I think). 

The server's os is Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-45-generic x86_64) and I am using bash with tmux.

Can you confirm that you also can't reproduce the truncation problem even when there are many evaluation metrics that one line can not show it all (like the two screenshots I had)? I am wondering what the new logging in 1.1.0 with `tqdm` should look like.

Regarding screen recording, I am working on that...

**Comment by epwalsh** [comment]
So far I've tried reproducing in essentially the same environment and with making the screen width too small for the output, but I still don't see the output being truncated.

Can you try reproducing if you comment out this line: https://github.com/allenai/allennlp/blob/master/allennlp/common/tqdm.py#L85?

If you still see the same issue with that line commented, then it must be an issue with `Tqdm` itself, not `allennlp`.

Also, any metrics that start with an underscore won't be added to the progress bar, so if you want to avoid having such a long progress bar you could utilize that feature.

**Comment by niansong1996** [comment]
Okay, I don't think this is an allennlp issue. I previously have some `print` statements with `flush=True`, this may be messing up with `tqdm` to trigger this stranger behavior. Once I removed it, the truncating problem disappears.

The underscore trick is also very neat, this is really helpful for my other tasks as well, thanks!

Sorry for the trouble and feel free to close this issue.

**Comment by epwalsh** [comment]
@niansong1996 thanks for the update, I'm glad you figured it out.
