### ISSUE TITLE
Getting a tensor with all zero values when trying to use the Elmo model for predictions.

### ISSUE THREAD

**Issue by Dhruv-Sabharwal** [allenai/allennlp#4747]
I am using the Elmo model to get embeddings for a downstream task. I downloaded the following files:
(1) elmo_2x1024_128_2048cnn_1xhighway_weights.hdf5 from https://www.kaggle.com/valkling/elmo-pretrained-weights-for-nlp?select=elmo_2x1024_128_2048cnn_1xhighway_weights.hdf5
(2) elmo_2x1024_128_2048cnn_1xhighway_options.json from https://www.kaggle.com/ydliu5/elmo-pretrained-option-files-for-nlp?select=elmo_2x1024_128_2048cnn_1xhighway_options.json

With these files I created the model. I then followed the solution posted by nelson-liu to get the token embeddings from Elmo:

```
from allennlp.modules.elmo import Elmo, batch_to_ids

options_file = "path/to/my/options/file"
weight_file = "path/to/my/weight/file"

# Note the "1", since we want only 1 output representation for each token.
elmo = Elmo(options_file, weight_file, 1, dropout=0)

# use batch_to_ids to convert sentences to character ids
sentences = [['First', 'sentence', '.'], ['Another', '.']]
character_ids = batch_to_ids(sentences)

embeddings = elmo(character_ids)
```
At this point the output tensor I get has the following shape:

`len(embeddings["elmo_representations"]) == 1`, and `embeddings["elmo_representations"][0].shape == torch.Size([2, 3, 256])`, corresponding to `(batch_size, max_seq_len, elmo_embedding_dim)`.

However, this tensor is just full of 0 values. I don't get any meaningful embeddings. Can you please let me know why this issue might be arising?

**Comment by epwalsh** [comment]
I'm not able to reproduce this. It seems to work fine:

```python
from allennlp.common.file_utils import cached_path
from allennlp.modules.elmo import Elmo, batch_to_ids

weights_path = cached_path("https://s3-us-west-2.amazonaws.com/allennlp/models/elmo/2x1024_128_2048cnn_1xhighway/elmo_2x1024_128_2048cnn_1xhighway_weights.hdf5")
options_path = cached_path("https://s3-us-west-2.amazonaws.com/allennlp/models/elmo/2x1024_128_2048cnn_1xhighway/elmo_2x1024_128_2048cnn_1xhighway_options.json")

elmo = Elmo(options_path, weights_path, 1, dropout=0)

sentences = [['First', 'sentence', '.'], ['Another', '.']]
character_ids = batch_to_ids(sentences)
embeddings = elmo(character_ids)
print(embeddings)
```

The output is:

```
{'elmo_representations': [
tensor([[[-0.1290, -0.0053, -0.5269,  ...,  0.1373,  0.2507, -0.7911],
           [ 0.5511, -0.2235,  0.1626,  ..., -0.8953,  0.5011, -1.4219],
           [ 0.3206,  0.2114,  0.2246,  ..., -0.2516, -0.1505,  0.2238]],
          [[ 0.6634,  0.5339, -0.4762,  ...,  0.2827,  0.2224,  0.0898],
           [ 0.0397,  0.2241,  0.1264,  ..., -0.2516, -0.1505,  0.2238],
           [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]]],
         grad_fn=<CopySlices>)],
 'mask': tensor([[ True,  True,  True],
         [ True,  True, False]])}
```

**Comment by Dhruv-Sabharwal** [comment]
Yes, it works fine when I use the files from the links provided by you. The kaggle links seem to be broken. Thank you so much!
Also, can you please point me to some article/documentation which I can refer to if I want to train the ELMo model from scratch on a custom dataset. Thank you again.
