### ISSUE TITLE
Docker image instructions or command incorrect

### ISSUE THREAD

**Issue by theashworld** [allenai/allennlp#4749]
## Checklist

- [ X] I have verified that the issue exists against the `master` branch of AllenNLP.
- [ X] I have read the relevant section in the [contribution guide](https://github.com/allenai/allennlp/blob/master/CONTRIBUTING.md#bug-fixes-and-new-features) on reporting bugs.
- [ X] I have checked the [issues list](https://github.com/allenai/allennlp/issues) for similar or identical bug reports.
- [X ] I have checked the [pull requests list](https://github.com/allenai/allennlp/pulls) for existing proposed fixes.
- [ X] I have checked the [CHANGELOG](https://github.com/allenai/allennlp/blob/master/CHANGELOG.md) and the [commit log](https://github.com/allenai/allennlp/commits/master) to find out if the bug was already fixed in the master branch.
- [X ] I have included in the "Description" section below a traceback from any exceptions related to this bug.
- [ ] I have included in the "Related issues or possible duplicates" section beloew all related issues and possible duplicate issues (If there are none, check this box anyway).
- [ ] I have included in the "Environment" section below the name of the operating system and Python version that I was using when I discovered this bug.
- [ ] I have included in the "Environment" section below the output of `pip freeze`.
- [X ] I have included in the "Steps to reproduce" section below a minimally reproducible example.

## Description

As per the page here http://docs.allennlp.org/v1.2.0rc1/#installing-using-docker

Running the Docker image
You can run the image with docker run --rm -it allennlp/allennlp:latest. The --rm flag cleans up the image on exit and the -it flags make the session interactive so you can use the bash shell the Docker image starts.

however, when I run that command 
`docker run --gpus all  --rm -it -v $HOME/.allennlp:/root/.allennlp allennlp/allennlp:latest`

```
Status: Downloaded newer image for allennlp/allennlp:latest
usage: allennlp [-h] [--version]  ...

Run AllenNLP

optional arguments:
  -h, --help     show this help message and exit
  --version      show program's version number and exit

Commands:

    build-vocab  Build a vocabulary from an experiment config file.
    cached-path  Cache remote files to the AllenNLP cache.
    evaluate     Evaluate the specified model + dataset.
    find-lr      Find a learning rate range.
    predict      Use a trained model to make predictions.
    print-results
                 Print results from allennlp serialization directories to the console.
    test-install
                 Test AllenNLP installation.
    train        Train a model.
```

There is no interactive prompt

**Comment by epwalsh** [comment]
I assume you want to run `bash` on the container. In order to do that, you need to specify `bash` as the `--entrypoint`, because otherwise it will use the default entrypoint which in this case is just the `allennlp` command. So the complete command would be:

```bash
docker run --rm -it --gpus all -v $HOME/.allennlp:/root/.allennlp --entrypoint bash allennlp/allennlp:latest
```
