### ISSUE TITLE
Rename tabs in the model visualization

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp#475]
* "SRL Model" -> "SRL"
* "MC Model" -> "Machine Comprehension"
* "TE Model" -> "Textual Entailment"

**Comment by schmmd** [comment]
@joelgrus any concerns?

**Comment by joelgrus** [comment]
my only concerns is that the names will be too long and we'll run out of space

**Comment by matt-gardner** [comment]
FWIW, I definitely prefer labels that refer to tasks, not models, so I like this change.
