### ISSUE TITLE
GQA dataset reader

### ISSUE THREAD

**Issue by dirkgr** [allenai/allennlp#4772]
GQA is here: https://cs.stanford.edu/people/dorarad/gqa/index.html

We want this reader to work much like the VQA reader, so it produces the same kind of output, and we can use the same models with it.

You might have to pull out components that are common to the two readers to avoid too much copy and paste.

**Comment by dirkgr** [comment]
Anything left to do?

**Comment by jvstokes** [comment]
No! And I believe it's merged so I'll close
