### ISSUE TITLE
SNLI-VE dataset reader and model

### ISSUE THREAD

**Issue by dirkgr** [allenai/allennlp#4773]
SNLI-VE is here: https://github.com/necla-ml/SNLI-VE

The VQA reader and model should serve as an example, but there will likely be significant differences.

**Comment by dirkgr** [comment]
Anything left to do?

**Comment by schmmd** [comment]
We need to add the predictor, model card, and task card.

**Comment by AkshitaB** [comment]
> We need to add the predictor, model card, and task card.

Done. https://github.com/allenai/allennlp-models/commit/debf15aeb6321fc4d671768411e73948493917da
