### ISSUE TITLE
Ask for further integration with Optuna

### ISSUE THREAD

**Issue by himkt** [allenai/allennlp#4775]
Hello, I'm a member of Optuna dev and the author of the allennlp-guide chapter on hyperparameter optimization.

Recently, I created [allennlp-optuna](https://github.com/himkt/allennlp-optuna), a prototype of a wrapper for Optuna to enable users to optimize hyperparameter of AllenNLP model. It provides a way to use Optuna by `allennlp` subcommands.

For explaining `allennlp-optuna`, I made the quick tutorial of `allennlp-optuna` in [readthedocs](https://allennlp-optuna.readthedocs.io/en/latest/tutorial/index.html). With `allennlp-optuna`, users can run multi-node distributed optimization by simply executing the same command on multiple machines. I put a simple example on [README](https://github.com/himkt/allennlp-optuna#5-hyperparameter-optimization-at-scale).

And recently, I also wrote [the post](https://techlife.cookpad.com/entry/2020/11/06/110000) (sorry in Japanese...) about the NER system using AllenNLP+Optuna.

Can we have an opportunity to add `allennlp-optuna` to default plugins of AllenNLP?  If it helps the decision, I'm willing to transfer `allennlp-optuna` to AllenAI. I'm really happy if it helps NLP practitioners to tune the hyperparameter of their model with ease. 

Thank you, as always.

**Comment by epwalsh** [comment]
Hi @himkt, I think what we'd like to do is create a place to prominently display third-party plugins like `allennlp-optuna`. For now, the best place for this is probably in our README. We should also do better with documenting how to use third-party plugins. Would that suffice?

**Comment by himkt** [comment]
Hi @epwalsh, thank you for your consideration.

> create a place to prominently display third-party plugins

It feels really nice!

> We should also do better with documenting how to use third-party plugins

I agree. For now, it's not easy to know we can register subcommand to `allennlp` as I understand. If how to use third-party plugins is documented (in guide.allennlp.org [chapter 2](https://guide.allennlp.org/writing-your-own-script)?), it would help people who want to expand/utilize AllenNLP a lot!
