### ISSUE TITLE
Failure when loading SRL model from path

### ISSUE THREAD

**Issue by galsk87** [allenai/allennlp#4782]
I'm trying to do exactly as the usage example in the demo says:

```
from allennlp.predictors.predictor import Predictor
predictor = Predictor.from_path("https://storage.googleapis.com/allennlp-public-models/bert-base-srl-2020.03.24.tar.gz")
```

I get the next error:

```
Traceback (most recent call last):
  File "/home/gal/miniconda3/envs/nlp/lib/python3.6/site-packages/transformers/modeling_utils.py", line 638, in from_pretrained
    raise EnvironmentError
OSError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gal/miniconda3/envs/nlp/lib/python3.6/site-packages/allennlp/predictors/predictor.py", line 275, in from_path
    load_archive(archive_path, cuda_device=cuda_device),
  File "/home/gal/miniconda3/envs/nlp/lib/python3.6/site-packages/allennlp/models/archival.py", line 197, in load_archive
    opt_level=opt_level,
  File "/home/gal/miniconda3/envs/nlp/lib/python3.6/site-packages/allennlp/models/model.py", line 398, in load
    return model_class._load(config, serialization_dir, weights_file, cuda_device, opt_level)
  File "/home/gal/miniconda3/envs/nlp/lib/python3.6/site-packages/allennlp/models/model.py", line 295, in _load
    model = Model.from_params(vocab=vocab, params=model_params)
  File "/home/gal/miniconda3/envs/nlp/lib/python3.6/site-packages/allennlp/common/from_params.py", line 580, in from_params
    **extras,
  File "/home/gal/miniconda3/envs/nlp/lib/python3.6/site-packages/allennlp/common/from_params.py", line 611, in from_params
    return constructor_to_call(**kwargs)  # type: ignore
  File "/home/gal/miniconda3/envs/nlp/lib/python3.6/site-packages/allennlp_models/structured_prediction/models/srl_bert.py", line 56, in __init__
    self.bert_model = BertModel.from_pretrained(bert_model)
  File "/home/gal/miniconda3/envs/nlp/lib/python3.6/site-packages/transformers/modeling_utils.py", line 645, in from_pretrained
    raise EnvironmentError(msg)
OSError: Can't load weights for 'bert-base-uncased'. Make sure that:

- 'bert-base-uncased' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'bert-base-uncased' is the correct path to a directory containing a file named one of pytorch_model.bin, tf_model.h5, model.ckpt.
```
In issues  on the transformers repo I saw most solutions involved disk space, I have no disk space issues.

**Comment by dirkgr** [comment]
Try running `BertModel.from_pretrained("bert-base-uncased")` directly. See if that loads.

I suspect there is some problem with your transformers installation, maybe a corrupted weights file?

**Comment by bibocai** [comment]
I face the same problem with this issue, and I solve it by downloading the bert-based-uncased folder from hugging face. After that, I can successfully running `BertModel.from_pretrained("bert-base-uncased")`. But a new problem comes as follows:
```
[nltk_data] Error loading punkt: <urlopen error [Errno 61] Connection
[nltk_data]     refused>
[nltk_data] Error loading wordnet: <urlopen error [Errno 61]
[nltk_data]     Connection refused>
Traceback (most recent call last):
  File "predictor.py", line 3, in <module>
    predictor = Predictor.from_path("https://storage.googleapis.com/allennlp-public-models/bert-base-srl-2020.11.19.tar.gz")
  File "/anaconda3/lib/python3.7/site-packages/allennlp/predictors/predictor.py", line 275, in from_path
    load_archive(archive_path, cuda_device=cuda_device),
  File "/anaconda3/lib/python3.7/site-packages/allennlp/models/archival.py", line 197, in load_archive
    opt_level=opt_level,
  File "/anaconda3/lib/python3.7/site-packages/allennlp/models/model.py", line 398, in load
    return model_class._load(config, serialization_dir, weights_file, cuda_device, opt_level)
  File "/anaconda3/lib/python3.7/site-packages/allennlp/models/model.py", line 337, in _load
    model.load_state_dict(model_state)
  File "/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 847, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for SrlBert:
	Unexpected key(s) in state_dict: "bert_model.embeddings.position_ids".
```
The model in the demo website is unpdated to 'bert-base-srl-2020.11.19.tar.gz'. 
I have no idea to solve this, I'll appreciate your help.

**Comment by dirkgr** [comment]
It looks to me like you don't have an internet connection while it's trying to download something.

**Comment by bibocai** [comment]
Thanks for your reply!
 I've already solved the connection problem, so the error related to nltk is removed. However, the error message related to `Unexpected key(s) in state_dict: "bert_model.embeddings.position_ids` still exists.  Hope for your attention.

**Comment by bibocai** [comment]
Thanks for your reply!
I've already solved the connection problem, so the error related to nltk is removed. However, the error message related to `Unexpected key(s) in state_dict: "bert_model.embeddings.position_ids` still exists. And the error message is exactly the same. Hope for your attention.

**Comment by galsk87** [comment]
It was because I was working with proxy.

Now my problem is similar to what @bibocai  said.

Here is my traceback:

>>> from allennlp.predictors.predictor import Predictor
>>> predictor = Predictor.from_path("https://storage.googleapis.com/allennlp-public-models/bert-base-srl-2020.11.19.tar.gz")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/anaconda3/envs/nlp/lib/python3.6/site-packages/allennlp/predictors/predictor.py", line 275, in from_path
    load_archive(archive_path, cuda_device=cuda_device),
  File "/home/ubuntu/anaconda3/envs/nlp/lib/python3.6/site-packages/allennlp/models/archival.py", line 197, in load_archive
    opt_level=opt_level,
  File "/home/ubuntu/anaconda3/envs/nlp/lib/python3.6/site-packages/allennlp/models/model.py", line 398, in load
    return model_class._load(config, serialization_dir, weights_file, cuda_device, opt_level)
  File "/home/ubuntu/anaconda3/envs/nlp/lib/python3.6/site-packages/allennlp/models/model.py", line 337, in _load
    model.load_state_dict(model_state)
  File "/home/ubuntu/anaconda3/envs/nlp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 847, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for SrlBert:
        Unexpected key(s) in state_dict: "bert_model.embeddings.position_ids".

**Comment by dirkgr** [comment]
I just loaded this up fine on my box. I suspect there is a problem with the versions of your libraries. Can you paste the output of `pip freeze`?

**Comment by HaritzPuerto** [comment]
How can we run the SRL model without an internet connection? I am required to not to use an internet connection in my application...

Conceptually, I do not understand why we need an internet connection when we give the path with the tar of the model weights.

Here you can see how I can load Bert base uncased (because I previously downloaded it), but I can't load the SRL model even though I have the tar file downloaded

`Predictor.from_path("models/srl_model/bert-base-srl-2019.06.17.tar.gz", cuda_device=0)`
![image](https://user-images.githubusercontent.com/2658728/100489945-f14b6580-315a-11eb-9b18-43ce0fe3d6c8.png)

**Comment by dirkgr** [comment]
If you are doing this in a Docker container, the easiest thing to do it to
make a prediction once when you build the image, when you still have
internet. That will download all the required files and put them into the
cache. After that, it should work offline.

**Comment by a414351664** [comment]
> I face the same problem with this issue, and I solve it by downloading the bert-based-uncased folder from hugging face. After that, I can successfully running `BertModel.from_pretrained("bert-base-uncased")`. But a new problem comes as follows:
> 
> ```
> [nltk_data] Error loading punkt: <urlopen error [Errno 61] Connection
> [nltk_data]     refused>
> [nltk_data] Error loading wordnet: <urlopen error [Errno 61]
> [nltk_data]     Connection refused>
> Traceback (most recent call last):
>   File "predictor.py", line 3, in <module>
>     predictor = Predictor.from_path("https://storage.googleapis.com/allennlp-public-models/bert-base-srl-2020.11.19.tar.gz")
>   File "/anaconda3/lib/python3.7/site-packages/allennlp/predictors/predictor.py", line 275, in from_path
>     load_archive(archive_path, cuda_device=cuda_device),
>   File "/anaconda3/lib/python3.7/site-packages/allennlp/models/archival.py", line 197, in load_archive
>     opt_level=opt_level,
>   File "/anaconda3/lib/python3.7/site-packages/allennlp/models/model.py", line 398, in load
>     return model_class._load(config, serialization_dir, weights_file, cuda_device, opt_level)
>   File "/anaconda3/lib/python3.7/site-packages/allennlp/models/model.py", line 337, in _load
>     model.load_state_dict(model_state)
>   File "/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 847, in load_state_dict
>     self.__class__.__name__, "\n\t".join(error_msgs)))
> RuntimeError: Error(s) in loading state_dict for SrlBert:
> 	Unexpected key(s) in state_dict: "bert_model.embeddings.position_ids".
> ```
> 
> The model in the demo website is unpdated to 'bert-base-srl-2020.11.19.tar.gz'.
> I have no idea to solve this, I'll appreciate your help.

Yes, I got the same problem.

**Comment by dirkgr** [comment]
Did you try the same solution?

**Comment by Omarnabk** [comment]
I had the same problem and I solved it by updating Transformers to the latest version 4.1.1

**Comment by IHMCBrodie** [comment]
I know that this issue has been closed and I see the proposed solution above of upgrading the Transformers library, but I wonder if there is still not an issue. I am using 
`pip install allennlp==1.0.0 allennlp-models==1.0.0`

`from allennlp.predictors.predictor import Predictor
import allennlp_models.tagging
predictor = Predictor.from_path("https://storage.googleapis.com/allennlp-public-models/structured-prediction-srl-bert.2020.12.15.tar.gz")`


When running this I still get the same error mentioned above 
`RuntimeError: Error(s) in loading state_dict for SrlBert:
	Unexpected key(s) in state_dict: "bert_model.embeddings.position_ids". `

I haven't tried upgrading the Transformers yet, but if that is the solution like is suggested above, then shouldn't that version be required and installed when `pip install allennlp==1.0.0 allennlp-models==1.0.0` is run?

**Comment by dirkgr** [comment]
Yes, it should. AllenNLP depends on some internals of `transformers`, and so we usually have to specify an exact version. Are you finding that the version of `transformers` that's installed by default with AllenNLP 1.0.0 doesn't work?

**Comment by IHMCBrodie** [comment]
That's correct. The default it installs is transformers-2.11.0 Which gave me the `RuntimeError: Error(s) in loading state_dict for SrlBert: Unexpected key(s) in state_dict: "bert_model.embeddings.position_ids".` error. 

I just upgraded transformers to it's latest version (transformers-4.2.2) and when trying to load the predictor again I got the falling:
`ModuleNotFoundError: No module named 'transformers.tokenization_auto'`

**Comment by dirkgr** [comment]
Yes, upgrading to the latest version of `transformers` will certainly not work.

I see that in AllenNLP 1.0.0, the version string for `transformers` was [`transformers>=2.9,<2.12`](https://github.com/allenai/allennlp/blob/29f3b6c36cab1b3d9e347f4d985253e9c9c9e6de/setup.py#L67). Maybe that's too permissive? Does it work if you try some other versions within that window?

**Comment by IHMCBrodie** [comment]
Just tried both version 2.9 and 2.10 of `transformers` and got the same `Unexpected key(s)` error

**Comment by dirkgr** [comment]
I can only guess then that this slipped through the cracks when we released 1.0. Do you still have a problem if you upgrade to later versions of AllenNLP (and upgrade to the appropriate transformers version with it)?

**Comment by IHMCBrodie** [comment]
So I have issues in the past trying to use the model suggested in the SRL demo with newer version of AllenNLP which is why I have been using 1.0.0 for both AllenNLP and `allennlp-models`. I will try and upgrade both `allennlp` and `allen-nlp` models now and see what happens.

**Comment by IHMCBrodie** [comment]
I just installed the latest of `allennlp` (2.0.0) `allennlp-models` (1.4.0) and everything worked without any errors

**Comment by dirkgr** [comment]
I am reluctant to fix old versions, since it's a lot of effort on our side for not a lot of gain, but if you have an issue with AllenNLP 1.4 or 2.0, we can bake a fix quickly and put it into the next version.

**Comment by dirkgr** [comment]
Hah, looks like you fell exactly into the 30 minute period where `allennlp` is already updated, but `allennlp-models` is not updated yet. `allennlp-models` 2.0.0 is building right now as we speak. Sorry for the inconvenience there!

**Comment by IHMCBrodie** [comment]
I understand the effort issue for sure. I just worry because the "model usage" tab for the SRL demo, and I think most all the other demos instructs users to `pip install allennlp==1.0.0 allennlp-models==1.0.0` and doing so with the combination of certain models i.e. `predictor = Predictor.from_path("https://storage.googleapis.com/allennlp-public-models/structured-prediction-srl-bert.2020.12.15.tar.gz")` causes the errors we were talking about. I am more than happy to use the new versions just wanna make sure the model usage demos on the website don't cause errors.

**Comment by dirkgr** [comment]
I'm going through the various model instructions we have online right now, making sure they are all correct.

**Comment by IHMCBrodie** [comment]
I appreciate you coming back to this and the attention to detail! Thank you!
