### ISSUE TITLE
annotation tools for semantic role labeling

### ISSUE THREAD

**Issue by hasfihawari** [allenai/allennlp#4787]
hi,
i interested in semantic role labeling, I want to ask what tools are used for annotation data for semantic role labeling?
thank you

**Comment by dirkgr** [comment]
All of our SRL models were trained on CoNLL data: https://demo.allennlp.org/semantic-role-labeling
So we did not do our own annotation for these.

Maybe @matt-gardner knows more about other sources of SRL data?

**Comment by matt-gardner** [comment]
You're correct @dirkgr.  The SRL data comes from the LDC; I don't know what tools were originally used to create it, though.

**Comment by hasfihawari** [comment]
thank you
