### ISSUE TITLE
Interpret code should be usable for non-AllenNLP models

### ISSUE THREAD

**Issue by AkshitaB** [allenai/allennlp#4790]
* Currently, saliency interpreters assume that the input is an AllenNLP model and rely on the presence of `TextFieldEmbedder` to find the correct embedding layer to register hooks. 
* We want to add the ability for the user to specify the right embedding layer for the cases when the model does not have a `TextFieldEmbedder`.

**Comment by jianliu-ml** [comment]
Hi, looking forward for this function!
Could you share ideas for how to impelement a interpret function for a pytroch-based model?
