### ISSUE TITLE
Question about allennlp.data.vocabulary

### ISSUE THREAD

**Issue by KYRIEZX** [allenai/allennlp#4791]
If I set the cap of max_vocab_size with 1000 labels, will it result in 1000 most popular labels, or just sorted by their indexes?

**Comment by epwalsh** [comment]
Hi @KYRIEZX, it depends on how you're creating your fields. I assume you're talking about using a `LabelField`?

If that's the case, and you're creating the fields like `field = LabelField(7, skip_indexing=True)`, then the `max_vocab_size` option in your `Vocabulary` object will **not** apply to those label fields.

**Comment by KYRIEZX** [comment]
> Hi @KYRIEZX, it depends on how you're creating your fields. I assume you're talking about using a `LabelField`?
> 
> If that's the case, and you're creating the fields like `field = LabelField(7, skip_indexing=True)`, then the `max_vocab_size` option in your `Vocabulary` object will **not** apply to those label fields.

Is the "counter" in the code used for counting the number of vocabulary items? How can I get the specific number of vocabulary items during building them?

**Comment by dirkgr** [comment]
This is not officially supported, but you can try using `Vocabulary._retained_counter` to get those counts.
