### ISSUE TITLE
CUDA OOV when use beam_search with amp

### ISSUE THREAD

**Issue by wlhgtc** [allenai/allennlp#4805]
Hi, there. 
Thanks for your great job that add multiple samplers and reconstruct Beam Search.
But recently, I find a bug when use beam_search with amp.
I use the config in allennlp-models: [config](https://github.com/allenai/allennlp-models/blob/master/training_config/generation/bart_cnn_dm.jsonnet)
**And I construct the demo data: a sequence for 200 words source and 100 words target, then repeat it for 512 times.**
All things goes well until I add `use_amp : true`.
The cuda memory is as follows( I use a 32G v100):
|   | use amp | no amp |
| ------------- | ------------- |------------- |
| train  | 13G | 15G |
| valid  | 32+G | 15G |

It's strange and I wonder why beam search in amp takes twice memory ?
 @epwalsh @jvstokes Hope you could help!

**Comment by epwalsh** [comment]
Probably related to https://github.com/allenai/allennlp/issues/4689.

**Comment by wlhgtc** [comment]
@epwalsh This bug was fixed in [pytorch](https://github.com/pytorch/pytorch/issues/48049). Seems like memory leak.

**Comment by epwalsh** [comment]
That's great to hear! Thanks @wlhgtc!
