### ISSUE TITLE
Writing distributed metrics is confusing

### ISSUE THREAD

**Issue by dirkgr** [allenai/allennlp#4806]
Big approach: We could change the metrics API so that there are two methods to implement, one that produces an intermediate representation on each worker, and another that combines them. That way it's clear to the implementer what to do.

Small approach: Every metric gets a flag called `safe_for_distributed`, which is `False` by default, and needs to be set to `True` if the implementer has taken care of the distributed side of things.

**Comment by epwalsh** [comment]
This would prevent issues like https://github.com/allenai/allennlp/issues/4794.

**Comment by dirkgr** [comment]
Metrics now have a `supports_distributed` flag.
