### ISSUE TITLE
Better management of detectron being there only some of the time

### ISSUE THREAD

**Issue by dirkgr** [allenai/allennlp#4808]
Pete already put in some mechanism for only making classes with detectron dependencies available when we actually have detectron. But it doesn't work yet for multi-level dependencies. `allennlp/data/__init__.py` depends on `image_loader.py`, which depends on Detectron. This fails.

Here is my recommendation:
 - [ ] split `ImageLoader` and `DetectronImageLoader`, so that they are in two different modules.
 - [ ] every module that directly depends on Detectron throws `ImportError` if Detectron is not found. Maybe we make a nice global instance of `ImportError` somewhere, with a descriptive message, that can be thrown in all the places where we need it.
 - [x] every module that indirectly depends on Detectron does nothing.
 - [ ] every `__init__.py` that potentially re-exports names from modules that depend on Detectron catches `ImportError` and omits those classes.

We should not start with this until #4595 is done, because it will conflict.

**Comment by dirkgr** [comment]
@epwalsh, this is now expected to get closed by your work on the allennlp-detectron repo, right?

**Comment by epwalsh** [comment]
I think we can close this.
