### ISSUE TITLE
Make image sets easily accessible

### ISSUE THREAD

**Issue by dirkgr** [allenai/allennlp#4816]
We don't want to automatically download large image sets with `cached_path()`, but we at least want to make it very easy to download them manually (download one archive, extract it, set the image path).

 - [x] VQA
 - [x] GQA
 - [x] SNLI-VE

**Comment by schmmd** [comment]
We need to make some minor changes to the training config to make it easier to work out of the box.

**Comment by dirkgr** [comment]
Done!
