### ISSUE TITLE
Rename token.py to avoid bugs in certain Python versions

### ISSUE THREAD

**Issue by tmcclintock** [allenai/allennlp#4819]
## Checklist

- [x] I have verified that the issue exists against the `master` branch of AllenNLP.
- [x] I have read the relevant section in the [contribution guide](https://github.com/allenai/allennlp/blob/master/CONTRIBUTING.md#bug-fixes-and-new-features) on reporting bugs.
- [x] I have checked the [issues list](https://github.com/allenai/allennlp/issues) for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/allenai/allennlp/pulls) for existing proposed fixes.
- [x] I have checked the [CHANGELOG](https://github.com/allenai/allennlp/blob/master/CHANGELOG.md) and the [commit log](https://github.com/allenai/allennlp/commits/master) to find out if the bug was already fixed in the master branch.
- [x] I have included in the "Description" section below a traceback from any exceptions related to this bug.
- [x] I have included in the "Related issues or possible duplicates" section below all related issues and possible duplicate issues (If there are none, check this box anyway).
- [x] I have included in the "Environment" section below the name of the operating system and Python version that I was using when I discovered this bug.
- [x] I have included in the "Environment" section below the output of `pip freeze`.
- [x] I have included in the "Steps to reproduce" section below a minimally reproducible example.

## Description

In certain version of Python (verified with 3.7.8) attempting to import from the file `token.py` causes a circular import because there is an identically named file in the dependency tree of the `dataclasses` module.

<details>
<summary><b>Python traceback:</b></summary>
<p>

```
Traceback (most recent call last):
  File "token.py", line 1, in <module>
    from dataclasses import dataclass
  File "/opt/anaconda3/envs/allentest/lib/python3.7/dataclasses.py", line 5, in <module>
    import inspect
  File "/opt/anaconda3/envs/allentest/lib/python3.7/inspect.py", line 40, in <module>
    import linecache
  File "/opt/anaconda3/envs/allentest/lib/python3.7/linecache.py", line 11, in <module>
    import tokenize
  File "/opt/anaconda3/envs/allentest/lib/python3.7/tokenize.py", line 35, in <module>
    from token import *
  File "/Users/tmcclintock/Github/allennlp/allennlp/data/tokenizers/token.py", line 1, in <module>
    from dataclasses import dataclass
ImportError: cannot import name 'dataclass' from 'dataclasses' (/opt/anaconda3/envs/allentest/lib/python3.7/dataclasses.py)
```

</p>
</details>

## Related issues or possible duplicates

I was not able to find duplicate issue in the open or closed issues or in the current PRs.

## Environment

OS: OSX

Python version: 3.7.8

<details>
<summary><b>Output of <code>pip freeze</code>:</b></summary>
<p>

```
certifi==2020.11.8
```

</p>
</details>

## Steps to reproduce

<details>
<summary><b>Example source:</b></summary>
<p>

Begin by creating a fresh environment, cloning, and changing into the relevant directory:
```bash
conda create --name allentest python=3.7.8
conda activate allentest
git clone https://github.com/allenai/allennlp.git
cd allennlp/allennlp/data/tokenizers/
```

Attempt to run the file in question:
```bash
python token.py
```

</p>
</details>

## Proposed solution

The fix is easy, in that you can just rename the file so there is no collision `mv token.py token_class.py` and update import statements.

**Comment by epwalsh** [comment]
Huh, that's interesting. The error still happens when you run

```bash
python allennlp/data/tokenizers/token.py
```

from the root of the repo, but doesn't happen when import from a Python interpreter:

```bash
python
>>> from allennlp.data.tokenizers import token
>>> # all good
```

**Comment by tmcclintock** [comment]
Yes, it's very subtle. The same error occurs in Python 3.9.0 (just checked).

I think it speaks to how "token" is overloaded. Collisions were inevitable I guess...

**Comment by epwalsh** [comment]
Ok, yes, let's make that change. Would you like to make the PR @tmcclintock?

**Comment by tmcclintock** [comment]
Will do. May take until the weekend though.

**Comment by epwalsh** [comment]
No rush.

**Comment by tmcclintock** [comment]
My bad. Got busy.
