### ISSUE TITLE
Add a span embedding abstraction

### ISSUE THREAD

**Issue by matt-gardner** [allenai/allennlp#482]
The coref model uses span representations, and picking the best spans, as one of its main computations.

We should pull that out into its own abstraction, similar to `Seq2SeqEncoder`, that can be re-used in any model that wants it.

**Comment by DeNeutoy** [comment]
See the [`span_extractors`](https://github.com/allenai/allennlp/tree/master/allennlp/modules/span_extractors) package in `modules`.
