### ISSUE TITLE
ShardedDatasetReader doesn't inherit lazy from base reader

### ISSUE THREAD

**Issue by aleSuglia** [allenai/allennlp#4825]
## Checklist

- [x] I have verified that the issue exists against the `master` branch of AllenNLP.
- [x] I have read the relevant section in the [contribution guide](https://github.com/allenai/allennlp/blob/master/CONTRIBUTING.md#bug-fixes-and-new-features) on reporting bugs.
- [x] I have checked the [issues list](https://github.com/allenai/allennlp/issues) for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/allenai/allennlp/pulls) for existing proposed fixes.
- [x] I have checked the [CHANGELOG](https://github.com/allenai/allennlp/blob/master/CHANGELOG.md) and the [commit log](https://github.com/allenai/allennlp/commits/master) to find out if the bug was already fixed in the master branch.
- [x] I have included in the "Description" section below a traceback from any exceptions related to this bug.
- [x] I have included in the "Related issues or possible duplicates" section beloew all related issues and possible duplicate issues (If there are none, check this box anyway).
- [x] I have included in the "Environment" section below the name of the operating system and Python version that I was using when I discovered this bug.
- [x] I have included in the "Environment" section below the output of `pip freeze`.
- [x] I have included in the "Steps to reproduce" section below a minimally reproducible example.

## Description

Currently the `ShardedDatasetReader` doesn't inherit the `lazy` property from the `base_reader`. Therefore, the dataset reader becomes not `lazy` anymore. 

<details>
<summary><b>Python traceback:</b></summary>
<p>

```
Processed killed for insufficient RAM
```

</p>
</details>

## Related issues or possible duplicates

- None

## Environment

OS: OS X

Python version: Python 3.8.5

<details>
<summary><b>Output of <code>pip freeze</code>:</b></summary>
<p>

```
allennlp==1.2.2
attrs==20.3.0
beautifulsoup4 @ file:///tmp/build/80754af9/beautifulsoup4_1601924105527/work
blis==0.7.3
boto3==1.16.25
botocore==1.19.25
catalogue==1.0.0
certifi==2020.11.8
chardet==3.0.4
click==7.1.2
cymem==2.0.4
en-core-web-sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.3.1/en_core_web_sm-2.3.1.tar.gz
filelock==3.0.12
future==0.18.2
h5py==3.1.0
idna==2.10
importlib-metadata==3.1.0
iniconfig==1.1.1
jmespath==0.10.0
joblib==0.17.0
jsonlines==1.2.0
jsonnet==0.17.0
jsonpickle==1.4.1
lxml==4.6.2
murmurhash==1.0.4
nltk==3.5
numpy==1.19.4
overrides==3.1.0
packaging==20.4
plac==1.1.3
pluggy==0.13.1
preshed==3.0.4
protobuf==3.14.0
py==1.9.0
pyparsing==2.4.7
pytest==6.1.2
python-dateutil==2.8.1
regex==2020.11.13
requests==2.25.0
s3transfer==0.3.3
sacremoses==0.0.43
scikit-learn==0.23.2
scipy==1.5.4
sentencepiece==0.1.91
six==1.15.0
soupsieve==2.0.1
spacy==2.3.4
srsly==1.0.4
tensorboardX==2.1
thinc==7.4.3
threadpoolctl==2.1.0
tokenizers==0.9.3
toml==0.10.2
torch==1.7.0
tqdm==4.54.0
transformers==3.5.1
typing-extensions==3.7.4.3
urllib3==1.26.2
wasabi==0.8.0
zipp==3.4.0
```

</p>
</details>

## Steps to reproduce

<details>
<summary><b>Example source:</b></summary>
<p>

For any model training using a `ShardedDatasetReader` this configuration file will not set the `lazy` property for it:
```
 "dataset_reader" : {
        "type": "sharded",
        "base_reader": {
            "type": "wiki_er",
            "token_indexers": {
                "tokens": {
                    "type": "pretrained_transformer_mismatched",
                    "model_name": model_name
                }
            },
            "lazy": true
        }
    }
```
while this one will work:
```
 "dataset_reader" : {
        "type": "sharded",
        "base_reader": {
            "type": "wiki_er",
            "token_indexers": {
                "tokens": {
                    "type": "pretrained_transformer_mismatched",
                    "model_name": model_name
                }
            }
        },
        "lazy": true
    }
```

</p>
</details>

I believe that a fix for this issue can be implemented by following this rule: if the `ShardedDatasetReader` sets the `lazy` parameter, then use it. If it doesn't then inherit from `base_reader`.

In general, looks like this is true also for other `DatasetReader` parameters like `max_instances`.

**Comment by epwalsh** [comment]
> I believe that a fix for this issue can be implemented by following this rule: if the ShardedDatasetReader sets the lazy parameter, then use it. If it doesn't then inherit from base_reader.

This seems like a good solution. Would you like to make a PR for this @aleSuglia?

**Comment by aleSuglia** [comment]
Happy to do it. I can work on it later today.
