### ISSUE TITLE
TrackEpochCallback is not an EpochCallback

### ISSUE THREAD

**Issue by mahnerak** [allenai/allennlp#4826]
Is there any reason why `TrackEpochCallback` should not inherit from `EpochCallback`?
https://github.com/allenai/allennlp/blob/5b30658514a00e11000e648fec23be11a998bd92/allennlp/training/trainer.py#L179-L188

**Comment by epwalsh** [comment]
No, this was an oversight. Thanks for catching it. Would you like to make a PR to fix?

**Comment by mahnerak** [comment]
Sure! I'll make a PR.

**Comment by epwalsh** [comment]
Hey @mahnerak are you still planning on making a PR for this? If not I can do it.

**Comment by mahnerak** [comment]
Yes, I do. I was just preparing a couple of other notes on Callbacks and wanted to submit them as a single PR.

**Comment by mahnerak** [comment]
@epwalsh The `end` callbacks are called within the `try` block.
https://github.com/allenai/allennlp/blob/1ca478ab674dd412447b2f11c820ca5664737cc2/allennlp/training/trainer.py#L1111
However, I was expecting `end` callbacks to be called even in case of an error. Or, IDK, maybe there should be another way to inform the callback about the end of the training (so it can do a cleanup).

**Comment by mahnerak** [comment]
As there are no many third-party callbacks implemented for AllenNLP (yet) and the backwards-compatibility is not an issue right now, I think it's better to revisit the callback API.
For example, we may need `on_start()` callback instead of firing `on_epoch(epoch=-1)`. 

Also, I don't get why there should be separate `BatchCallback`, `EndCallback`, `EpochCallback`, and a metaclass `TrainCallback` to rule them all. I believe you had your reasons to implement it this way. But why not to have a single Callback class with `__init__(self, serialization_dir, trainer)`, `on_start()`, `on_batch_start()`, `on_batch_end()`, `on_epoch_start()`, `on_epoch_end()`, `on_end()`, `on_error()`, `on_after_backward()`, etc...?
If someone wants to have a callback just for epochs, they can implement only a single method `on_epoch_end()`.

I just feel the API of callbacks is the only non-intuitive abstraction in AllenNLP.
Pytorch-lightning has much straightforward callback interface.

**Comment by epwalsh** [comment]
Yea... this was kind of a half-baked feature to compromise with the folks (including me) who wanted to stick with the `CallbackTrainer`. So I'm all for making improvements, but we're committed to strictly adhering to Semantic Versioning, and so any breaking changes will have to go into our next major release: v2.0.

We are already working towards our v2.0 release though on a separate branch, so you could make a PR to that branch if you're interested. The branch is called `vision` (because the main focus of the 2.0 release is supporting vision + text models).

**Comment by mahnerak** [comment]
Okay, so I'll try to make a PR on non-breaking changes and after that will make major changes on `vision` branch.

**Comment by epwalsh** [comment]
Sounds great

**Comment by epwalsh** [comment]
Closing via #4893 

@mahnerak would you still like to propose changes to the callback API? Now would be good time since we are trying to wrap things up for 2.0. After the 2.0 release we won't be making any breaking changes for a while.

**Comment by mahnerak** [comment]
I'll try to make a PR on:

- Removing separate EpochCallback, BatchCallback in favour of a unified TrainerCallback with methods `on_epoch_end()`, `on_batch_end()`.
- Not calling EpochCallback at first step with `epoch = -1` in favour of `on_train_start()`
- End callbacks are called with method `on_train_end()`. If an error has occurred, it is provided as an argument.

I'll prepare a PR for these changes. The other features of `TrainerCallback` may be easily added without any breaking changes.

**Comment by dirkgr** [comment]
These sound like good changes, but it breaks the API, and we are very close to releasing 2.0. Unless the PR is perfect by Tuesday night, we'll have to ship it in 2.1, and make sure it's backwards compatible.
