### ISSUE TITLE
Some tests fail under pytorch 0.3

### ISSUE THREAD

**Issue by zou3519** [allenai/allennlp#483]
Hi, 
The folks over at [pytorch](https://github.com/pytorch/pytorch) are working on cutting a new 0.3 release. We'd like to make the transition as smooth as possible so we're testing various community repos that use pytorch with the release.

I built allennlp from source and ran the tests and it looks like the following three failed:
```
tests/training/metrics/entropy_test.py::EntropyTest::test_entropy_for_uniform_distribution 
tests/training/metrics/entropy_test.py::EntropyTest::test_low_entropy_distribution 
tests/training/metrics/entropy_test.py::EntropyTest::test_masked_case 
```
They all seem to be erroring in the same [way](https://gist.github.com/zou3519/0945d32cc77a5ad6f78c3ba131082101). 

cc @soumith

**Comment by schmmd** [comment]
@zou3519 thanks for pro-actively checking with us.  What is the best way for us to run AllenNLP against the unreleased PyTorch 0.3?

**Comment by zou3519** [comment]
You can build pytorch from source (after checking out the v0.3.0 branch), or build and run a docker image with pytorch 0.3 in it. Running the docker image might be easier way to do it if you have docker installed already. More detailed instructions available [here](https://github.com/pytorch/pytorch); quick summary below:

### build from source (on a linux system)
```
#  Install dependencies
export CMAKE_PREFIX_PATH="$(dirname $(which conda))/../" # [anaconda root directory]
conda install numpy pyyaml mkl setuptools cmake cffi
conda install -c soumith magma-cuda80 # or magma-cuda75 if CUDA 7.5, or just omit this line

git checkout https://github.com/pytorch/pytorch.git
cd pytorch
git checkout v0.3.0
python setup.py install
```

### Docker
```
git checkout https://github.com/pytorch/pytorch.git
cd pytorch
git checkout v0.3.0
docker build -t pytorch-0.3.0 .
nvidia-docker run --rm -ti --ipc=host pytorch-0.3.0:latest
```

**Comment by DeNeutoy** [comment]
Thanks Richard - looks like the behaviour of `torch.nn.functional.log_softmax` has changed to require `Variable` input, whereas [here](https://github.com/allenai/allennlp/blob/master/allennlp/training/metrics/entropy.py#L34) we call it with plain tensors. This is easy to fix (as a side note, the behaviour of this function is slightly odd as it returns a Variable by default, even if it's called with Tensor input).
