### ISSUE TITLE
model_save_interval and restoring checkpoints

### ISSUE THREAD

**Issue by vikigenius** [allenai/allennlp#4837]
Say I have a very long running training process with a lot of data, where an epoch could take an hour.
So if i use model_save_interval to save the model every 30 minutes, can I restore the model to these intermediate training states? (if they get interrupted before a complete epoch)

If yes, then these intermediate states, do they restore the position of the batch as well (i.e do they start training from the exact batch that was interrupted) how is this handled ?

**Comment by AkshitaB** [comment]
@vikigenius You can try using `batches_per_epoch` in the `DataLoader` setting to reduce the steps in the epoch itself.

**Comment by vikigenius** [comment]
@AkshitaB , that's an interesting idea. What happens to the rest of the data? This would only work well if the data is shuffled after each epoch right? My intent was more about understanding the recovery process if i am using something like the aws spot instances for example that can be interrupted anytime.
