### ISSUE TITLE
Superfluous warning when extending the vocab in the `Embedding`

### ISSUE THREAD

**Issue by dcfidalgo** [allenai/allennlp#4839]
## Checklist

- [x] I have verified that the issue exists against the `master` branch of AllenNLP.
- [x] I have read the relevant section in the [contribution guide](https://github.com/allenai/allennlp/blob/master/CONTRIBUTING.md#bug-fixes-and-new-features) on reporting bugs.
- [x] I have checked the [issues list](https://github.com/allenai/allennlp/issues) for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/allenai/allennlp/pulls) for existing proposed fixes.
- [x] I have checked the [CHANGELOG](https://github.com/allenai/allennlp/blob/master/CHANGELOG.md) and the [commit log](https://github.com/allenai/allennlp/commits/master) to find out if the bug was already fixed in the master branch.
- [x] I have included in the "Description" section below a traceback from any exceptions related to this bug.
- [x] I have included in the "Related issues or possible duplicates" section beloew all related issues and possible duplicate issues (If there are none, check this box anyway).
- [x] I have included in the "Environment" section below the name of the operating system and Python version that I was using when I discovered this bug.
- [x] I have included in the "Environment" section below the output of `pip freeze`.
- [x] I have included in the "Steps to reproduce" section below a minimally reproducible example.

## Description

If one creates an `allennlp.modules.token_embedders.embedding.Embedding` without a `pretrained_file`, you still get a warning when extending the vocab that no `pretrained_file` is found. I would expect the warning only to trigger if one specified a `pretrained_file` when creating the `Embedding` or when an `extension_pretrained_file` is passed on to `Embedding.extend_vocab`. 

I would be more than happy to provide a PR if you think this is actually and issue and should be addressed.

<details>
<summary><b>Python traceback:</b></summary>
<p>

```
WARNING:root:Embedding at model_path, None cannot locate the pretrained_file.  If you are fine-tuning and want to use using pretrained_file for embedding extension, please pass the mapping by --embedding-sources argument.

```

</p>
</details>

## Related issues or possible duplicates

- None

## Environment

OS: Ubuntu 20.04

Python version: 3.8.0

<details>
<summary><b>Output of <code>pip freeze</code>:</b></summary>
<p>

```
attrs==20.3.0
blis==0.7.3
boto3==1.16.29
botocore==1.19.29
catalogue==1.0.0
certifi==2020.11.8
chardet==3.0.4
click==7.1.2
cymem==2.0.4
dataclasses==0.6
filelock==3.0.12
future==0.18.2
h5py==3.1.0
idna==2.10
iniconfig==1.1.1
jmespath==0.10.0
joblib==0.17.0
jsonnet==0.17.0
jsonpickle==1.4.2
murmurhash==1.0.4
nltk==3.5
numpy==1.19.4
overrides==3.1.0
packaging==20.7
plac==1.1.3
pluggy==0.13.1
preshed==3.0.4
protobuf==3.14.0
py==1.9.0
pyparsing==2.4.7
pytest==6.1.2
python-dateutil==2.8.1
regex==2020.11.13
requests==2.25.0
s3transfer==0.3.3
sacremoses==0.0.43
scikit-learn==0.23.2
scipy==1.5.4
sentencepiece==0.1.91
six==1.15.0
spacy==2.3.4
srsly==1.0.4
tensorboardX==2.1
thinc==7.4.3
threadpoolctl==2.1.0
tokenizers==0.9.3
toml==0.10.2
torch==1.7.0
tqdm==4.54.0
transformers==3.5.1
typing-extensions==3.7.4.3
urllib3==1.26.2
wasabi==0.8.0
```

</p>
</details>

## Steps to reproduce

<details>
<summary><b>Example source:</b></summary>
<p>

```python
from allennlp.data import Token, Instance, Vocabulary
from allennlp.data.fields import TextField
from allennlp.data.token_indexers import SingleIdTokenIndexer
from allennlp.modules.token_embedders.embedding import Embedding

instance = Instance({"token": TextField([Token("test")], {"tokens": SingleIdTokenIndexer()})})
vocab = Vocabulary.from_instances([instance])

instance2 = Instance({"token": TextField([Token("this")], {"tokens": SingleIdTokenIndexer()})})
vocab2 = Vocabulary.from_instances([instance, instance2])

embedder = Embedding(1, vocab=vocab)
embedder.extend_vocab(vocab2)
```

</p>
</details>

**Comment by AkshitaB** [comment]
@dcfidalgo Hi, thanks for catching this! You are most welcome to submit a PR!
