### ISSUE TITLE
training method for semantic role labeling

### ISSUE THREAD

**Issue by hasfihawari** [allenai/allennlp#4844]
hi, i'm newbie in nlp, What methods and architectures are used for semantic role labeling training?
are u using lstm or another?
thank u

**Comment by dirkgr** [comment]
To answer your question specifically, our best SRL model is based on BERT, as described in https://arxiv.org/abs/1904.05255.

In general, for a beginner we recommend the courses at https://course.fast.ai to get started. There are courses about deep learning in general, NLP, as well as [transformer architectures](https://www.youtube.com/watch?v=AFkGPmU16QA&list=PLtmWHNX-gukKocXQOkQjuVxglSDYWsSh9&index=3&t=0s).
