### ISSUE TITLE
Multi-process data loading occasionally hangs when worker does tensor ops on CPU

### ISSUE THREAD

**Issue by epwalsh** [allenai/allennlp#4848]
When using `num_workers > 0` and `start_method = "fork"` with the multi-process data loader, there is the potential for dead locks if the dataset reader does any tensor computations on CPU.

The solution is to set the `start_method` to "spawn" or set the environment variable `OMP_NUM_THREADS` to 1. See https://discuss.pytorch.org/t/pytorch-cpu-hangs-on-nn-linear/17748/4.

**Comment by apsiriwat** [comment]
#5042

**Comment by apsiriwat** [comment]
issue

**Comment by apsiriwat** [comment]
#5042

**Comment by apsiriwat** [comment]
$4848

**Comment by apsiriwat** [comment]
bug

**Comment by apsiriwat** [comment]
https://github.com/allenai/allennlp/issues/4848#issuecomment-792351186

**Comment by dirkgr** [comment]
@apsiriwat, what is the actual problem you're having? Did setting the start method to `"spawn"` not work?

**Comment by apsiriwat** [comment]
ในวันที่ ส. 13 มี.ค. 2021 00:36 Dirk Groeneveld ***@***.***>
เขียนว่า:

**Comment by dirkgr** [comment]
I don't understand. There is no content in your email. Is something wrong with your email client?
