### ISSUE TITLE
Access denied when trying to access the pretrained decomposable attention model

### ISSUE THREAD

**Issue by vered1986** [allenai/allennlp#485]
Hi,

I'm trying to access the pretrained decomposable attention model in the following URL:
https://s3-us-west-2.amazonaws.com/allennlp/models/decomposable_attention-2017.09.04.tar.gz

I get the following error:

<pre><code>
&lt;Error&gt;
&lt;Code&gt;AccessDenied&lt;/Code&gt;
&lt;Message&gt;Access Denied&lt;/Message&gt;
&lt;RequestId&gt;876D14D1C9712730&lt;/RequestId&gt;
&lt;HostId&gt;
S8aReoZ5MUVwQRZD+YT1NOkj6QD3UU5/pp8sK6QLFPL9t43uuvqZ2h4NEEO0B7+/OC2/ng628+Q=
&lt;/HostId&gt;
&lt;/Error&gt;
</code></pre>

Thanks in advance!

**Comment by matt-gardner** [comment]
You've got an underscore in `decomposable_attention` where it should be a hyphen (`decomposable-attention`).  Is this a link you copied from our repo or website somewhere, or did you type it yourself?

**Comment by vered1986** [comment]
Thanks for the quick reply! I can access the file now. I copied it from http://allennlp.org/models, where it appears with the underscore.

**Comment by matt-gardner** [comment]
Thanks for telling us where it is - we'll get that fixed.  I'm going to re-open this issue until the link is fixed.

**Comment by matt-gardner** [comment]
It was easier than I thought, so I just [fixed it](https://github.com/allenai/allennlp-website/commit/1ad77995b7243956904d8c9fff3cb5059215ce20), and the fixed link is live.  Closing this now.
