### ISSUE TITLE
Make sure tensors have dimensions multiple of 8

### ISSUE THREAD

**Issue by mahnerak** [allenai/allennlp#4868]
The `torch.amp` automatically enabled mixed-precision training but on the latest GPUs, it's faster (according to the documentation) because of Tensor Cores. But latter is enabled (almost) for fp16 calculations if the tensor dimensions are multiple of 8.

The embedding size and the batch size is easy to maintain as multiples of 8 manually.
However, we may need to modify `TokenIndexer` to pad it automatically, similar to: https://github.com/YerevaNN/allennlp/commit/374acec5e62d6d74586b18a3d5bb2f9b5a169da4

We also may need to modify `max_tokens`-based samplers to have 8x batch_sizes.

**Comment by epwalsh** [comment]
Thanks for pointing that out @mahnerak! This is pretty important so I'm putting it on our 1.4 release milestone. We're all tied up with other stuff at the moment though, so we might not be able to get to this until the new year, but I'd be happy to review a PR if you or anyone else is interesting.

For anyone else coming upon this, NVIDIA provides some more info here: https://developer.nvidia.com/blog/optimizing-gpu-performance-tensor-cores/

**Comment by dirkgr** [comment]
We don't really need the issue as well as the draft PR.
