### ISSUE TITLE
Running SRL example is giving me -  Errors in loading state_dict for SrlBert

### ISSUE THREAD

**Issue by mgiardinelli** [allenai/allennlp#4876]
## Checklist

- [X ] I have verified that the issue exists against the `master` branch of AllenNLP.
- [ ] I have read the relevant section in the [contribution guide](https://github.com/allenai/allennlp/blob/master/CONTRIBUTING.md#bug-fixes-and-new-features) on reporting bugs.
- [ ] I have checked the [issues list](https://github.com/allenai/allennlp/issues) for similar or identical bug reports.
- [ ] I have checked the [pull requests list](https://github.com/allenai/allennlp/pulls) for existing proposed fixes.
- [ ] I have checked the [CHANGELOG](https://github.com/allenai/allennlp/blob/master/CHANGELOG.md) and the [commit log](https://github.com/allenai/allennlp/commits/master) to find out if the bug was already fixed in the master branch.
- [ ] I have included in the "Description" section below a traceback from any exceptions related to this bug.
- [ ] I have included in the "Related issues or possible duplicates" section beloew all related issues and possible duplicate issues (If there are none, check this box anyway).
- [ ] I have included in the "Environment" section below the name of the operating system and Python version that I was using when I discovered this bug.
- [ ] I have included in the "Environment" section below the output of `pip freeze`.
- [ ] I have included in the "Steps to reproduce" section below a minimally reproducible example.

## Description

Running the SRL example using allennlp 1.0 is giving me an error. 
RuntimeError: Error(s) in loading state_dict for SrlBert:
	Unexpected key(s) in state_dict: "bert_model.embeddings.position_ids".

<details>
<summary><b>Python traceback:</b></summary>
<p>
Running the AllenNLP example gives me the error below
```
echo '{"sentence": "Did Uriah honestly think he could beat the game in under three hours?"}' | \
allennlp predict https://storage.googleapis.com/allennlp-public-models/bert-base-srl-2020.11.19.tar.gz -
```

```
Traceback (most recent call last):
  File "/Users/user1/dev/Pedestal/srl/demo/bin/allennlp", line 8, in <module>
    sys.exit(run())
  File "/Users/user1/dev/Pedestal/srl/demo/lib/python3.8/site-packages/allennlp/__main__.py", line 19, in run
    main(prog="allennlp")
  File "/Users/user1/dev/Pedestal/srl/demo/lib/python3.8/site-packages/allennlp/commands/__init__.py", line 92, in main
    args.func(args)
  File "/Users/user1/dev/Pedestal/srl/demo/lib/python3.8/site-packages/allennlp/commands/predict.py", line 197, in _predict
    predictor = _get_predictor(args)
  File "/Users/user1/dev/Pedestal/srl/demo/lib/python3.8/site-packages/allennlp/commands/predict.py", line 94, in _get_predictor
    archive = load_archive(
  File "/Users/user1/dev/Pedestal/srl/demo/lib/python3.8/site-packages/allennlp/models/archival.py", line 192, in load_archive
    model = Model.load(
  File "/Users/user1/dev/Pedestal/srl/demo/lib/python3.8/site-packages/allennlp/models/model.py", line 398, in load
    return model_class._load(config, serialization_dir, weights_file, cuda_device, opt_level)
  File "/Users/user1/dev/Pedestal/srl/demo/lib/python3.8/site-packages/allennlp/models/model.py", line 337, in _load
    model.load_state_dict(model_state)
  File "/Users/user1/dev/Pedestal/srl/demo/lib/python3.8/site-packages/torch/nn/modules/module.py", line 846, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SrlBert:
	Unexpected key(s) in state_dict: "bert_model.embeddings.position_ids".
```

</p>
</details>

## Related issues or possible duplicates

- None

## Environment

OS: Mac Catalina 10.15.7

Python version:3.8.6
PIP Version: 20.2.1

<details>
<summary><b>Output of <code>pip freeze</code>:</b></summary>
<p>

```
allennlp==1.0.0
allennlp-models==1.0.0
attrs==20.3.0
blis==0.4.1
boto3==1.16.40
botocore==1.19.40
catalogue==1.0.0
certifi==2020.12.5
chardet==4.0.0
click==7.1.2
conllu==3.0
cymem==2.0.5
filelock==3.0.12
future==0.18.2
h5py==3.1.0
idna==2.10
iniconfig==1.1.1
jmespath==0.10.0
joblib==1.0.0
jsonnet==0.17.0
jsonpickle==1.4.2
murmurhash==1.0.5
nltk==3.5
numpy==1.19.4
overrides==3.0.0
packaging==20.8
plac==1.1.3
pluggy==0.13.1
preshed==3.0.5
protobuf==3.14.0
py==1.10.0
py-rouge==1.1
pyparsing==2.4.7
pytest==6.2.1
python-dateutil==2.8.1
rake-nltk==1.0.4
regex==2020.11.13
requests==2.25.1
s3transfer==0.3.3
sacremoses==0.0.43
scikit-learn==0.23.2
scipy==1.5.4
sentencepiece==0.1.94
six==1.15.0
spacy==2.2.4
srsly==1.0.5
tensorboardX==2.1
thinc==7.4.0
threadpoolctl==2.1.0
tokenizers==0.7.0
toml==0.10.2
torch==1.5.1
tqdm==4.54.1
transformers==2.11.0
urllib3==1.26.2
wasabi==0.8.0
word2number==1.1
```

</p>
</details>

## Steps to reproduce

<details>
<summary><b>Example source:</b></summary>
<p>

```
pip install allennlp==1.0.0 allennlp-models==1.0.0

echo '{"sentence": "Did Uriah honestly think he could beat the game in under three hours?"}' | \
allennlp predict https://storage.googleapis.com/allennlp-public-models/bert-base-srl-2020.11.19.tar.gz -
```

</p>
</details>

**Comment by AkshitaB** [comment]
Hi @mgiardinelli This should be fixed in the latest allennlp 1.3 release. Also, the latest archive file is `structured-prediction-srl-bert.2020.12.15.tar.gz`.

**Comment by mgiardinelli** [comment]
AWesome AkshitaB! I really appreciate it. When will that be released?

**Comment by mgiardinelli** [comment]
nevermind :). It is already released. I will install that version.
