### ISSUE TITLE
[Model] The RC model training just hung there

### ISSUE THREAD

**Issue by gladuo** [allenai/allennlp#4886]
## Checklist

- [x] I have verified that the issue exists against the `master` branch of AllenNLP.
- [x] I have read the relevant section in the [contribution guide](https://github.com/allenai/allennlp/blob/master/CONTRIBUTING.md#bug-fixes-and-new-features) on reporting bugs.
- [x] I have checked the [issues list](https://github.com/allenai/allennlp/issues) for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/allenai/allennlp/pulls) for existing proposed fixes.
- [x] I have checked the [CHANGELOG](https://github.com/allenai/allennlp/blob/master/CHANGELOG.md) and the [commit log](https://github.com/allenai/allennlp/commits/master) to find out if the bug was already fixed in the master branch.
- [x] I have included in the "Description" section below a traceback from any exceptions related to this bug.
- [x] I have included in the "Related issues or possible duplicates" section beloew all related issues and possible duplicate issues (If there are none, check this box anyway).
- [x] I have included in the "Environment" section below the name of the operating system and Python version that I was using when I discovered this bug.
- [x] I have included in the "Environment" section below the output of `pip freeze`.
- [x] I have included in the "Steps to reproduce" section below a minimally reproducible example.

## Description

I use https://github.com/allenai/allennlp-models/tree/master/allennlp_models/rc here, and I met problems when using "distributed mode". When an epoch training "seemly" ended, and the next epoch is just going to start, the process just hung there, nothing happened for a loooong time until you killed it manually. It is really hard to find what's the problem there.

But when you killed it, and recovered it, it just worked well, until the end of epoch, again.

<details>
<summary><b>Python traceback:</b></summary>
<p>

```
```

</p>
</details>

## Related issues or possible duplicates

- None

## Environment

OS:

Python version:

<details>
<summary><b>Output of <code>pip freeze</code>:</b></summary>
<p>

```
```

</p>
</details>

## Steps to reproduce

<details>
<summary><b>Example source:</b></summary>
<p>

```
```

</p>
</details>

**Comment by epwalsh** [comment]
Which exact model / metric are you using? Can you share your training config?

**Comment by epwalsh** [comment]
I'm guessing this is the same issue as https://github.com/allenai/allennlp/issues/4794.

**Comment by gladuo** [comment]
> Which exact model / metric are you using? Can you share your training config?

@epwalsh sorry for not replying soon. I used transformer_qa there, and the default metrics like f1, em. I end up bypassing the problem using something like drop_last.
BTW, there are a few extra critical bugs in the rc module, I hope I have some time to pull a pr later this week.

**Comment by epwalsh** [comment]
Thanks @gladuo. One more question: did it hang during the training loop or the validation loop?

**Comment by gladuo** [comment]
> Thanks @gladuo. One more question: did it hang during the training loop or the validation loop?
![image](https://user-images.githubusercontent.com/5893628/104126921-35f13000-539a-11eb-96fe-5df4fe7c4ac1.png)

@epwalsh Hey there, I rerun the training process without drop_last, and it is stable recurrence. It just appears by the end of validation process.

**Comment by gladuo** [comment]
https://github.com/allenai/allennlp-models/pull/191 pr is here

**Comment by gladuo** [comment]
> [allenai/allennlp-models#191](https://github.com/allenai/allennlp-models/pull/191) pr is here

@epwalsh 
This pr is only for some other critical bugs, I have not fixed the dead lock above. Using drop_last in the data_loader could bypass the problem, that may be a start to debug it.

**Comment by gladuo** [comment]
The WARNING above in the picture may also help.
