### ISSUE TITLE
Does allennlp textual entailment model work when hypothesis and premise both include multiple sentences?

### ISSUE THREAD

**Issue by coco-pa** [allenai/allennlp#4894]
On allennlp textual entailment [demo website][1], the hypothesis and premise in examples always only consist of one sentence. Does allennlp textual entailment model work when hypothesis and premise both include multiple sentences? Is it theoretically practical? Or could I train the model on my own labeled dataset to make it work on paragraph texts?

For example:

- Premise: "Whenever Jack is asked whether he prefers mom or dad, he doesn't know how to respond. To be honest, he has no idea why he has to make a choice. "
- Hypothesis: "Whom do you love more, mom or dad? Some adults like to use this question to tease kids. For Jack, he doesn't like this question."

I read the paper [decomposable attention model (Parikh et al, 2017)][2]. This paper doesn't discuss such a scenario. The idea behind the paper is text alignment. So intuitively, I think it should also be reasonable to work on paragraph texts. But I'm not very confident about it. 

I sincerely appreciate it if anyone can help with it. 

  [1]: https://demo.allennlp.org/textual-entailment
  [2]: https://www.semanticscholar.org/paper/A-Decomposable-Attention-Model-for-Natural-Language-Parikh-T%C3%A4ckstr%C3%B6m/2cd8e8f510c89c7c18268e8ad51c061e459ad321

**Comment by ZhaofengWu** [comment]
The demo models were trained with sentence-level texts. In some sense, they will probably work reasonably with few short sentences out of the box, but they definitely wouldn't perform as well as a model specifically trained under this setting using your labeled dataset. Do be careful that some models limit the max number of tokens, e.g., the RoBERTa ones on the demo. I can't remember if ELMo has this limitation on top of my head. If your texts are usually significantly longer than that, you may be do something fancy, e.g. hierarchical models.

**Comment by coco-pa** [comment]
> The demo models were trained with sentence-level texts. In some sense, they will probably work reasonably with few short sentences out of the box, but they definitely wouldn't perform as well as a model specifically trained under this setting using your labeled dataset. Do be careful that some models limit the max number of tokens, e.g., the RoBERTa ones on the demo. I can't remember if ELMo has this limitation on top of my head. If your texts are usually significantly longer than that, you may be do something fancy, e.g. hierarchical models.

**Comment by coco-pa** [comment]
> The demo models were trained with sentence-level texts. In some sense, they will probably work reasonably with few short sentences out of the box, but they definitely wouldn't perform as well as a model specifically trained under this setting using your labeled dataset. Do be careful that some models limit the max number of tokens, e.g., the RoBERTa ones on the demo. I can't remember if ELMo has this limitation on top of my head. If your texts are usually significantly longer than that, you may be do something fancy, e.g. hierarchical models.

Thank you very much!
