### ISSUE TITLE
ELMo Pubmed Model specifications 

### ISSUE THREAD

**Issue by rigoramos** [allenai/allennlp#4896]
Is there a more extended specification about pubmed pre-trained model? I know the options for the training, but I would like to know about the training corpus. Something like your mention for the original model:
"All models except for the 5.5B model were trained on the 1 Billion Word Benchmark, approximately 800M tokens of news crawl data from WMT 2011. The ELMo 5.5B model was trained on a dataset of 5.5B tokens consisting of Wikipedia (1.9B) and all of the monolingual news crawl data from WMT 2008-2012 (3.6B). "

**Comment by AkshitaB** [comment]
I believe this is referring to the PubMed model here: https://allennlp.org/elmo. @matt-peters Will you be able to share this information?

**Comment by matt-peters** [comment]
It was trained on a random selection of PubMed abstracts, the total corpus size was 797M tokens.
