### ISSUE TITLE
Coreference Resolutions fails when input passage is "short" 

### ISSUE THREAD

**Issue by gud111** [allenai/allennlp#4899]
## Checklist

- [ ] I have verified that the issue exists against the `master` branch of AllenNLP.
- [ ] I have read the relevant section in the [contribution guide](https://github.com/allenai/allennlp/blob/master/CONTRIBUTING.md#bug-fixes-and-new-features) on reporting bugs.
- [ ] I have checked the [issues list](https://github.com/allenai/allennlp/issues) for similar or identical bug reports.
- [ ] I have checked the [pull requests list](https://github.com/allenai/allennlp/pulls) for existing proposed fixes.
- [ ] I have checked the [CHANGELOG](https://github.com/allenai/allennlp/blob/master/CHANGELOG.md) and the [commit log](https://github.com/allenai/allennlp/commits/master) to find out if the bug was already fixed in the master branch.
- [ ] I have included in the "Description" section below a traceback from any exceptions related to this bug.
- [ ] I have included in the "Related issues or possible duplicates" section beloew all related issues and possible duplicate issues (If there are none, check this box anyway).
- [ ] I have included in the "Environment" section below the name of the operating system and Python version that I was using when I discovered this bug.
- [ ] I have included in the "Environment" section below the output of `pip freeze`.
- [ x] I have included in the "Steps to reproduce" section below a minimally reproducible example.

## Description

<details> When the input to the coreference resolution is a short 1-2 word texts, it throws and exception and crashes.
In general, while I understand a two-word passage probably does not need coreference resolution, it probably should 
just return empty ?
<summary><b>Python traceback:</b></summary>
<p>

```
```
    p = coref_predictor.predict(document=orgdoc)

  File "/home/sdas/anaconda3/lib/python3.7/site-packages/allennlp_models/coref/predictors/coref.py", line 64, in predict
    return self.predict_json({"document": document})

  File "/home/sdas/anaconda3/lib/python3.7/site-packages/allennlp/predictors/predictor.py", line 48, in predict_json
    return self.predict_instance(instance)

  File "/home/sdas/anaconda3/lib/python3.7/site-packages/allennlp/predictors/predictor.py", line 182, in predict_instance
    outputs = self._model.forward_on_instance(instance)

  File "/home/sdas/anaconda3/lib/python3.7/site-packages/allennlp/models/model.py", line 146, in forward_on_instance
    return self.forward_on_instances([instance])[0]

  File "/home/sdas/anaconda3/lib/python3.7/site-packages/allennlp/models/model.py", line 172, in forward_on_instances
    outputs = self.make_output_human_readable(self(**model_input))

  File "/home/sdas/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)

  File "/home/sdas/anaconda3/lib/python3.7/site-packages/allennlp_models/coref/models/coref.py", line 221, in forward
    span_mention_scores, span_mask, num_spans_to_keep

  File "/home/sdas/anaconda3/lib/python3.7/site-packages/allennlp/nn/util.py", line 1834, in masked_topk
    fill_value, _ = top_indices.max(dim=1, keepdim=True)

RuntimeError: cannot perform reduction function max on tensor with no elements because the operation does not have an identity
</p>
</details>

## Related issues or possible duplicates

- None

## Environment

OS:

Python version:

<details>
<summary><b>Output of <code>pip freeze</code>:</b></summary>
<p>

```
```

</p>
</details>

## Steps to reproduce

<details>
<summary><b>Example source:</b></summary>
<p>

```
```
Try any random text e.g. "Instant Death" in the demo API for coreference resolution

</p>
</details>

**Comment by AkshitaB** [comment]
It appears that the issue is the absence of a full-stop, rather than the length of the input passage. "Instant Death." should return the original text (as there are no clusters). I will debug further.

**Comment by haibin-chen** [comment]
The reason is that the span to extract will become zero if the input is too short.
[https://github.com/allenai/allennlp-models/blob/3624fdc4b249d3b515269ee99e1b1e15bf876829/allennlp_models/coref/models/coref.py#L213](url)
`
num_spans_to_keep = int(math.floor(self._spans_per_word * document_length))
`

The hyperparameter `self._spans_per_word` that filters candidate mention is set to 0.4 here. So if the input length is less than 3, `num_spans_to_keep` will become zero and leads to the error of `top_indices.max`.

You can add a simple verification:
`
#Ensure num_spans_to_keep is greater than zero 
`
` 
num_spans_to_keep = max(num_spans_to_keep, 1)  
`
However, it may be a better choice to add restrictions to the input : )
