### ISSUE TITLE
Constituency Parser and Dependency Parser .tar.gz files

### ISSUE THREAD

**Issue by rohanp965** [allenai/allennlp#4903]
Hi 

Can someone please link me the .tar.gz files used for Constituency Parser and the Biaffine Dependency Parser and please specify which version of AllenNLP version do they work with ? Thanks!

**Comment by AkshitaB** [comment]
Hi @rohanp965 The tar.gz files and the allennlp versions for all the models can be found under the `Usage` tab on the demo. For Constituency Parser and the Biaffine Dependency Parser, the tar.gz files are `https://storage.googleapis.com/allennlp-public-models/elmo-constituency-parser-2020.02.10.tar.gz` and `https://storage.googleapis.com/allennlp-public-models/biaffine-dependency-parser-ptb-2020.04.06.tar.gz` respectively.
