### ISSUE TITLE
Prepare data loading for 2.0

### ISSUE THREAD

**Issue by epwalsh** [allenai/allennlp#4904]
- [x] Remove `PyTorchDataLoader`. I wouldn't recommend anyone use this, and it doesn't provide any benefit over `MultiProcessDataLoader`. (https://github.com/allenai/allennlp/pull/4907)
- [x] Make submodule names consistent. Currently we have `multi_process_data_loader.py` and `multitask_*.py`. We should either rename `multi_process_*` to `multiprocess_*` or rename `multitask_*` to `multi_task_*`. (https://github.com/allenai/allennlp/pull/4906)
- [x] `data_path` param should accept `PathLike`. (https://github.com/allenai/allennlp/pull/4908)
- [x] Do more extensive testing on `MultiProcessDataLoader`. Potentially improve error handling. (https://github.com/allenai/allennlp/pull/4912)
- [x] Document best practices for `MultiProcessDataLoader`. (https://github.com/allenai/allennlp/pull/4909)
- [ ] ~~❓Improve where `TokenIndexers` fit it. Maybe they are part of `DatasetReader`. This would actual require minimal changes.~~
- [x] Update `allennlp-models@vision` for these changes. (https://github.com/allenai/allennlp-models/pull/192)

**Comment by dirkgr** [comment]
@epwalsh, is this done?
