### ISSUE TITLE
Using Pretrained Transformer Indexer/Embedder/Tokenizer with models that aren't on the Transformers hub

### ISSUE THREAD

**Issue by ethch18** [allenai/allennlp#4905]
Hi!  I'm trying to use a Transformer I've trained myself (using the HuggingFace framework) as input to a downstream model.  I've taken a look at the `PretrainedTransformerIndexer/Embedder/Tokenizer` classes, and it seems that they all look for a single `model_name` param that gets forwarded onto Transformers.  However, my model is split up into the various files that are outputted by HuggingFace (i.e., `vocab.txt` and `pytorch_model.bin`).  So, when I include the corresponding files into my allennlp config, I get the following error message:
```
OSError: Couldn't reach server at '/path/to/trained/bert/vocab.txt' to download configuration file or configuration file is not a valid JSON file. Please check network or file content here: /path/to/trained/bert/vocab.txt.
```

I looked into what the Transformers codebase is doing to get this error, and it looks like if there's no `config` param passed to the `AutoTokenizer` class, it will try to build a config from the model path ([ref](https://github.com/huggingface/transformers/blob/master/src/transformers/models/auto/tokenization_auto.py#L349)).  The workaround seems to be to pass a Transformers config as a kwarg when calling the Transformers classes from the Indexer/Embedder/Tokenizer, but I'm not sure how I'd specify that in my main config file.  Are there any workarounds for this?

For reference, here are the relevant parts of my config file:
```
        "token_indexers": {
            "transformer": {
                "type": "pretrained_transformer_mismatched",
                "max_length": 512,
                "model_name": "/path/to/trained/bert/vocab.txt"
            }
        }

            "token_embedders": {
                "transformer": {
                    "type": "pretrained_transformer_mismatched",
                    "max_length": 512,
                    "model_name": "/path/to/trained/pytorch_model.bin",
                    "top_layer_only": false,
                    "train_parameters": true
                }
            }

```

I'm on AllenNLP version 1.3.0.  I was able to do something like this using the old BERT-specific indexer/embedder in version 0.9.0, with the following config:
```
        "token_indexers": {
            "bert": {
                "type": "bert-pretrained",
                "do_lowercase": false,
                "pretrained_model": "/path/to/trained/bert/vocab.txt",
                "truncate_long_sequences": false,
                "use_starting_offsets": true
            }
        }

        "text_field_embedder": {
            "allow_unmatched_keys": true,
            "embedder_to_indexer_map": {
                "bert": [
                    "bert",
                    "bert-offsets"
                ]
            },
            "token_embedders": {
                "bert": {
                    "type": "bert-pretrained",
                    "pretrained_model": "/path/to/trained/pytorch_model.bin",
                    "requires_grad": true,
                    "top_layer_only": false
                }
            }
        },

```

Thanks in advance for any help!

**Comment by jbrry** [comment]
I was able to train using a locally-stored BERT model which I had trained myself. I am not fully sure if this is the correct approach as I haven't verified that I get similar scores in AllenNLP `v 1+` using this approach compared to using `v 0.9.0` using the approach you have mentioned above.

In any case, what I did was specify the local path to the directory which contains your pre-trained model in your AllenNLP config file:

```
local transformer_model = "/home/user/models/transformer_pretraining_output/corpus/";
```

Then, every time you use the `"model_name"` key in your AllenNLP config, pass this variable as the value:

```
"model_name": transformer_model
```

This should work (i.e. not get any errors) providing you have the right contents in `/home/user/models/transformer_pretraining_output/corpus/`.

Mine contains:

```
# transformer configuration file
config.json   

# file containing vocabulary           
vocab.txt

# saved PyTorch model               
pytorch_model.bin 
```

You could try and see if that works for you.

**Comment by dirkgr** [comment]
Yes, this is the way.

**Comment by ethch18** [comment]
Thank you!
