### ISSUE TITLE
Timeline for 2.0?

### ISSUE THREAD

**Issue by nelson-liu** [allenai/allennlp#4915]
Hi all,

I've noticed that there are mentions of a 2.0 release---while I understand that it's probably hard to estimate a particular release date, do you think it'll be on the order of days? weeks? months? Would be nice to have some information to better plan some new projects I'm currently starting now.

Thanks!

**Comment by epwalsh** [comment]
We are just finalizing some new APIs and finishing up some bugs fixes. If all goes well we'll do a release candidate next week, and then the full release will follow shortly after that 🙂

**Comment by nelson-liu** [comment]
amazing, thanks! I must say that I was still using pre-1.0 for previous work :grimacing: , so I figured that I might as well just leapfrog to 2.0 if possible. Thanks again for the response!

**Comment by epwalsh** [comment]
Pre-1.0?! Yikes! I think you will enjoy 2.0 😝
