### ISSUE TITLE
get user warning when I try to run NER demo code

### ISSUE THREAD

**Issue by mchari** [allenai/allennlp#4932]
I am trying to run the NER demo as instructed :

pip install allennlp==1.0.0 allennlp-models==1.0.0

from allennlp.predictors.predictor import Predictor
import allennlp_models.tagging

predictor = Predictor.from_path("https://storage.googleapis.com/allennlp-public-models/fine-grained-ner.2020-06-24.tar.gz")
predictor.predict(
    sentence="Did Uriah honestly think he could beat The Legend of Zelda in under three hours?."
)

but I get this user warning.
UserWarning: You are using the default value (0) of `min_padding_length`, which can cause some subtle bugs (more info see https://github.com/allenai/allennlp/issues/1954). Strongly recommend to set a value, usually the maximum size of the convolutional layer size when using CnnEncoder.

How do I resolve this ?

**Comment by jbrry** [comment]
This error occurs when no `min_padding_length` is specified when using the [`TokenCharactersIndexer`](https://github.com/allenai/allennlp/blob/fa1dc7b8a3899ee9ec1f51146251dccb378e1f5e/allennlp/data/token_indexers/token_characters_indexer.py#L53).

That is indeed the case in the `config.json` file from the NER model you have linked where this argument wasn't passed when the model was trained:

```
    "dataset_reader": {
        "type": "ontonotes_ner",
        "coding_scheme": "BIOUL",
        "token_indexers": {
            "elmo": {
                "type": "elmo_characters"
            },
            "token_characters": {
                "type": "characters"
            },
            "tokens": {
                "type": "single_id",
                "lowercase_tokens": true
            }
        }
    },
```
I'm not sure if it's a good idea changing the config file at evaluation time but in future, this warning is avoided by setting a `min_padding_length` in your config like below:

```
        "token_indexers": {
            ...
            "token_characters": {
                "type": "characters",
                "min_padding_length": 3
            },
            ...
        }
```

**Comment by mchari** [comment]
I would hope that the config.json file in the tar file could be edited and "re-tarred" to save every user from doing it.
