### ISSUE TITLE
Issue:  text_classification_json dataset class does not do what it says it does

### ISSUE THREAD

**Issue by allenciox** [allenai/allennlp#4936]
Unfortunately, I can't find any examples of what it "does" do, but it appears to take a file that is NOT in json format, but has a complete json representation on every single line of the file, with two keys:  "text" and "label".

The code showing that is in its _read method:
....
def _read(self, file_path):
        with open(cached_path(file_path), "r") as data_file:
            for line in self.shard_iterable(data_file.readlines()):
                if not line:
                    continue
                items = json.loads(line)
                text = items["text"]
                label = items.get("label")
...
 

in other words, every non-blank single line of the file must have:
{"text": "my sample text", "label": "my_label"}
 or it fails. 

So it really should be re-labelled to reflect what it really does, i.e. every non-blank line .

So I am writing a subclass of it that does really do what it claims to do (i.e. read a classification dataset that is in json format), if anybody is interested.  The subclass will include properties for:

instance_label: str=None :  key at top level of Json file that returns a list of document instances.  If blank, then the json file is considered to be in json list format (i.e. [ {"text": "text1", "label": "label1"}, ... ]
text_label: str="text" :  Each document instance in the json file should have a key to refer to the text using this.  This will fill in the 'text' field in each output instance.
label_label: str="label": Each document instance in the json file should have a key to refer to the label using this.  This will fill in the 'label' field in each output instance.

I believe that the only methods I will have to override are _read and __init__   

Would anybody be interested in this?  I can post the code for it (after I have written it and tested it out), if you are.

**Comment by allenciox** [comment]
Ok, here is my subclass definition.  It appears to work.

@DatasetReader.register("text_classification_jsonfile")
class TextClassificationJsonFileReader( TextClassificationJsonReader) :
    """
    Reads tokens and their labels from a labeled json-formatted text classification file.
    Expects that each of the document instances are either at the top level of the file inside 
       a list [] specification, or is a list under a specified top-level key.  
    Expects that each has a key for the document text (text_key) and for the label (label_key).  
       
    The output of `read` is a list of `Instance` s with the fields:
        tokens : `TextField` and
        label : `LabelField`
    Registered as a `DatasetReader` with name "text_classification_jsonfile".
    # Parameters
    <New: all optional>
    doc_key: str= None : if present, then the top-level key to contain a json list of document instances. 
         If absent, then json file must contain a json list at the top level. 
    text_key: str="text":  the key for the document text for each document instance.
    label_key: str="label":  the key for the document label for each document instance.
  
    <Inherited from parent class>:
    token_indexers : `Dict[str, TokenIndexer]`, optional
        optional (default=`{"tokens": SingleIdTokenIndexer()}`)
        We use this to define the input representation for the text.
        See :class:`TokenIndexer`.
    tokenizer : `Tokenizer`, optional (default = `{"tokens": SpacyTokenizer()}`)
        Tokenizer to use to split the input text into words or other kinds of tokens.
    segment_sentences : `bool`, optional (default = `False`)
        If True, we will first segment the text into sentences using SpaCy and then tokenize words.
        Necessary for some models that require pre-segmentation of sentences, like [the Hierarchical
        Attention Network][0].
    max_sequence_length : `int`, optional (default = `None`)
        If specified, will truncate tokens to specified maximum length.
    skip_label_indexing : `bool`, optional (default = `False`)
        Whether or not to skip label indexing. You might want to skip label indexing if your
        labels are numbers, so the dataset reader doesn't re-number them starting from 0.
    """

    def __init__(
        self,
        doc_key: str=None,
        text_key: str="text",
        label_key: str="label",
        **kwargs,
        ) -> None :
       
        super().__init__(**kwargs);
        self.doc_key=doc_key;
        self.text_key=text_key;
        self.label_key=label_key;

    @overrides
    def _read(self, file_path):
        with open(cached_path(file_path), "r") as data_file:
            items=json.load(data_file);
            if self.doc_key :
                items=items[self.doc_key];
            for item in items :
                text = item[self.text_key]
                label = item.get(self.label_key)
                if label is not None:
                    if self._skip_label_indexing:
                        try:
                            label = int(label)
                        except ValueError:
                            raise ValueError(
                                "Labels must be integers if skip_label_indexing is True."
                            )
                    else:
                        label = str(label)
                yield self.text_to_instance(text=text, label=label)

**Comment by AkshitaB** [comment]
@allenciox Generalizing to specify `text_key` and `label_key` is a good idea. I'll be happy to review a PR. Do take a look [here](https://github.com/allenai/allennlp/blob/501b0ab43c1b5fca35e99fc788885b19cf08f29e/allennlp/data/dataset_readers/dataset_reader.py#L278); `shard_iterable` is needed for the reader to work in distributed settings.
