### ISSUE TITLE
Support spaCy v3

### ISSUE THREAD

**Issue by bratao** [allenai/allennlp#4950]
spaCy released the version v3, with great improvements. https://github.com/explosion/spaCy/releases/tag/v3.0.0
Unfortunately allennlp is limiting to spacy<2.4 and the dependency resolver do not allow allennlp and spaCy v3 to be used in the same project.

Would be great to bump the requirement.

**Comment by epwalsh** [comment]
Hey @bratao, dependabot should open up a PR for this update by tomorrow morning, but if you want to get a head-start on this you could open one sooner. If this upgrade doesn't break anything then we can merge ASAP.
