### ISSUE TITLE
Include evaluation metrics of officially-supported models in model cards

### ISSUE THREAD

**Issue by nelson-liu** [allenai/allennlp#4963]
I think it'd be useful for the model cards of officially-supported models to report the evaluation metrics / model performance. I know I can check for myself with `allennlp evaluate`, it's nice to have this sort of information on-hand (e.g., in this case I want to see  whether a model is ~ the published performance)

**Comment by dirkgr** [comment]
This is not a bad idea, though sometimes the numbers are a little hard to get because you need more than just a model.

**Comment by dirkgr** [comment]
We're filling these in now every time we touch a model. No need for a special issue.
