### ISSUE TITLE
AllenNLP: Different Constituency Parsing Using Taskdemo and Python Library

### ISSUE THREAD

**Issue by ZZZZZch** [allenai/allennlp#4966]
thank you for sharing your fantastic tool with us. Very excellent job.

Just a question, why I got different constituency parsing result between online task demo and local python library? I think both of them are based on the model "https://storage.googleapis.com/allennlp-public-models/elmo-constituency-parser-2020.02.10.tar.gz"?

For example, input the same sentence,

"They quickly ran to the place which is sound came from." (from a student's composition).

The online demo gave the result: `(S (NP (PRP They)) (ADVP (RB quickly)) (VBD ran) (PP (IN to) (NP (NP (DT the) (NN place)) (SBAR (WHNP (WDT which)) (S (VP (VBZ is) (NP (NN sound))))))) (VP (VBD came) (PP (IN from))) (. .))`

but the result of python library version: `(S (NP (PRP They)) (ADVP (RB quickly)) (VBD ran) (PP (IN to) (NP (NP (DT the) (NN place)) (SBAR (WHNP (WDT which)) (S (VP (VBZ is) (NP (JJ sound))))))) (VP (VBD came) (PP (IN from))) (. .))`

It seems the online demo gave a better result.

**Comment by dirkgr** [comment]
The demo and the library sometimes go out of sync, because we update the library more often than the demo. Right now I'm in the middle of an effort to update all the demo usage information to use the new AllenNLP 2.0 version.

In your example the demo is indeed better, but your example is ungrammatical, so I would not put too much stock into the results anyways. Essentially, this is an out-of-domain sentence. If I fix the sentence ("They quickly ran to the place which the sound came from."), the parse is correct.

**Comment by dirkgr** [comment]
I didn't notice this the first time. This is al ELMo model. ELMo is not deterministic, and might give you different results when you run it multiple time. ELMo works better if it's warmed up first, i.e., if you send it a few sentences before doing your actual predictions. The demo is always warmed up.

**Comment by ZZZZZch** [comment]
Many thanks for your kindly reply. 


Very helpful. I will try it later. Hope the problem could be solved.


Best wishes,
Chenghao




Tel: +86 17801190520(CHINA)/+60 1123254061(MALAYSIA)
Email: zhu_cheng_hao@163.com
On 2/13/2021 01:23，Dirk Groeneveld<notifications@github.com> wrote：

I didn't notice this the first time. This is al ELMo model. ELMo is not deterministic, and might give you different results when you run it multiple time. ELMo works better if it's warmed up first, i.e., if you send it a few sentences before doing your actual predictions. The demo is always warmed up.
