### ISSUE TITLE
Failed to import WordTokenizer

### ISSUE THREAD

**Issue by yy147** [allenai/allennlp#4971]
Hello, I'm using Allennlp 1.4.0 and Allen-model 1.4.0 on my proiect. I run the command as `allennlp serve --archive-path <path> --predictor <predictor> --include-package <pacakge_name>`. And then I got an error of `Failed to import WordTokenizer from allennlp.data.tokenizers.word_tokenizer`. 

I've looked at the WordTokenizer from version 0.9.0 to the latest one. Only version 0.9.0 contains WordTokenizer. Is there a specific reason for removing WordTokenizer? Or is it moved/changed to another method? 

I also tried to run v0.9.0 but when I run `python -m allennlp.service.server_simple`. It pops another error: `/usr/bin/python: No module named allennlp.service`

It would be appreciated if someone can give an advice.

**Comment by dirkgr** [comment]
What model are you trying to serve?

`WordTokenizer` has been replaced with `SpacyTokenizer`. It often work if you just substitute one for the other. However, if you have a model that is so old it still requires `WordTokenizer`, then there are probably other incompatibilities.

**Comment by yy147** [comment]
Sorry, @dirkgr I forgot to reply. Yes, It works, I've updated my code with `SpacyTokenizer`. Thanks for all your help.
