### ISSUE TITLE
Write metrics in TrainerCallback

### ISSUE THREAD

**Issue by namednil** [allenai/allennlp#4972]
Hi! Is there a particular reason why it is not possible to write information into the `metrics` dictionary in the `on_epoch` callback (that is, why writing has no effect)? 

This could be useful to collect predictions on the validation set and then run an external evaluation script and collect the results, so the metrics become available for logging and early stopping.

If that doesn't make sense, how would you handle this use case? (And then the trainer should perhaps give a warning that there was an attempt to modify the `metrics` dictionary)

**Comment by dirkgr** [comment]
You can modify the metrics in a callback, but the callback is called after the metrics are logged, so you'll see your modification one epoch later than you think. We could probably move that callback call earlier, so you have a chance to modify the metrics before they are logged. You will not be able to make early-stopping decisions based on those modified metrics though.

I would rather recommend that you implement a custom metric than do it in a callback. Is there a reason you cannot do that?

**Comment by namednil** [comment]
Thanks for the quick answer!
>You will not be able to make early-stopping decisions based on those modified metrics though.

I see, then that's not optimal. Thanks for the heads-up!
> I would rather recommend that you implement a custom metric than do it in a callback. Is there a reason you cannot do that?

Doesn't the interface require tensors? That would be quite inconvenient because I would basically have to encode the gold data from a string into a tensor and back into a string to run a metric like [Smatch](https://github.com/snowblink14/smatch) or [fuzzing accuracy](https://github.com/taoyds/test-suite-sql-eval). Assuming I can get away with ignoring the types and I just use strings, I have to maintain a moving micro F-score in the case of Smatch. That's perfectly doable but not as convenient as calling it once as a black box function on two files.

**Comment by dirkgr** [comment]
You could do it in `Model.get_metrics()`?

**Comment by namednil** [comment]
Ah, yes, thanks!
