### ISSUE TITLE
Publish allennlp-server to pypi

### ISSUE THREAD

**Issue by dirkgr** [allenai/allennlp#4974]
It's annoying that it's separate. It doesn't get proper test coverage this way. We should either support this feature properly, or not at all.

**Comment by epwalsh** [comment]
I was talking to Michael about this earlier today and said I would look into updating it (I don't even know if it works anymore). FWIW I'm on board with bringing it into the core repo as long as we make the extra dependencies (Flask and idk what else) optional.

**Comment by epwalsh** [comment]
Okay, so after some more thought, I don't see the value in bringing it (back) into the main.

I just made some updates in https://github.com/allenai/allennlp-server/pull/14. It all works. Actually I don't think anything was really broken in the first place. And in theory, nothing should break in the future, because we're not going to make breaking API changes in AllenNLP (at least until 3.0, whenever that is). And a daily CI job will run anyway to make sure.

**Comment by dirkgr** [comment]
It's harder for users, and we have to remember to release this every time we make a release?

**Comment by benoit-intrw** [comment]
What would be nice is to push it on the pypi, this way it would be installable with pip as suggested in the guide here https://guide.allennlp.org/next-steps#2

By the way, I can confirm, the server was working on version 2.0 before the modification.

Thanks for all your hard work,
regards

**Comment by epwalsh** [comment]
> It's harder for users, and we have to remember to release this every time we make a release?

@dirkgr there's no reason to do a release on `allennlp-server` when we do a release in `allennlp`. At least until 3.0.

@benoit-intrw I agree it would be good to put on PyPI. I'll add that to my TODO list if we agree to keep it in its own repo.

**Comment by dirkgr** [comment]
We resolved that should put allennlp-server into pypi but not bring it into the main repo.

**Comment by agururajvais** [comment]
I along with couple of folks am planning to work on this in the next couple of days and have a PR ready this week.

**Comment by agururajvais** [comment]
Yes!

**Comment by agururajvais** [comment]
I will try to do the same. But would it be better you create a PyPI project and mark me as a collaborator?

**Comment by dirkgr** [comment]
Done! What's your PyPI name?

**Comment by agururajvais** [comment]
PyPI Username: gururajakuthota

**Comment by dirkgr** [comment]
Done, added you

**Comment by epwalsh** [comment]
Done ✅

https://pypi.org/project/allennlp-server/

**Comment by dirkgr** [comment]
Sweet!
