### ISSUE TITLE
Add a tutorial for random non-standard things a person might want to try

### ISSUE THREAD

**Issue by matt-gardner** [allenai/allennlp#498]
There are simple ways to do a lot of small tweaks in AllenNLP models, if you've set them up correctly.  Some of these ways are probably not obvious to someone not familiar with the code.  It'd be nice to have a tutorial that collected a bunch of these things and showed how to do them easily.  Tutorial title could be something like "What if I want to do...".  Some examples of things to go in here: "What if my text is in a language other than English?"  "What if I want to use two separate embeddings for the same words?"  "What if I want to use part-of-speech tag embeddings as my word representation?"

**Comment by matt-gardner** [comment]
There were a few issues in #569 that would be good to include in this kind of tutorial, also.

**Comment by EmilStenstrom** [comment]
I'm specifically interested in the tutorial of "What if my text is in a language other than English?"

**Comment by matt-gardner** [comment]
@EmilStenstrom, if what you want to do is build a model for a language other than English using your own data in that language, all you should have to change is the tokenizer, as that's the only thing built-in to AllenNLP that's language-dependent (if you want to do this and don't know how, let us know).  If you want to make predictions using a pre-trained model in a language other than English, we sadly don't have anything for that at this point (contributions welcome!)

**Comment by EmilStenstrom** [comment]
@matt-gardner I'd like to build a model in a non-english language (Swedish), with my own data. Is there a tutorial available on how to do that? I'm not that experienced with AllenNLP unfortunately, but I do have access to good data.

**Comment by matt-gardner** [comment]
I'd recommend going through the ["using AllenNLP in your repo" tutorial](https://github.com/allenai/allennlp/blob/master/tutorials/getting_started/using_in_your_repo.md), which is an explanation of the code you need to write to use AllenNLP to write models for your own task.  The only thing you should have to change there is the default tokenizer.  To do that, you add some parameters for the tokenizer [here](https://github.com/allenai/allennlp/blame/2a0804e77e34f04a64fc4d0e005185f2e50e0e3f/tutorials/getting_started/using_in_your_repo.md#L479-L483).  Your parameters might look something like this:

```json
"dataset_reader": {
  "type": "s2_papers",
  "tokenizer": {
    "type": "word",
    "word_splitter": {
      "type": "spacy",
      "language": "xx"
    }
  }
}
```

The spacy `xx` language is their "multi-language" model (they don't have a Swedish model).  You'll need to run `python -m spacy download xx` to download the model before this will work.

Instead of using spacy, you could also just tokenize words using nltk, or our heuristic "simple" tokenizer, or any other available [`WordSplitter`](https://github.com/allenai/allennlp/blob/master/allennlp/data/tokenizers/word_splitter.py) (or one you write yourself for Swedish!).  You would just change the `word_splitter` parameters accordingly.

**Comment by DeNeutoy** [comment]
This issue is pretty general, let's open specific ones for actual tutorials etc.
