### ISSUE TITLE
Nesting Issue on the 'Reading Data' section of the Guide

### ISSUE THREAD

**Issue by gabeorlanski** [allenai/allennlp#4982]
## Checklist

- [x] I have verified that the issue exists against the `master` branch of AllenNLP.
- [x] I have read the relevant section in the [contribution guide](https://github.com/allenai/allennlp/blob/master/CONTRIBUTING.md#bug-fixes-and-new-features) on reporting bugs.
- [x] I have checked the [issues list](https://github.com/allenai/allennlp/issues) for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/allenai/allennlp/pulls) for existing proposed fixes.
- [x] I have checked the [CHANGELOG](https://github.com/allenai/allennlp/blob/master/CHANGELOG.md) and the [commit log](https://github.com/allenai/allennlp/commits/master) to find out if the bug was already fixed in the master branch.
- [x] I have included in the "Description" section below a traceback from any exceptions related to this bug.
- [x] I have included in the "Related issues or possible duplicates" section below all related issues and possible duplicate issues (If there are none, check this box anyway).
- [x] I had included in the "Environment" section below the name of the operating system and Python version that I was using when I discovered this bug.
- [x] I have included the "Environment" section below the output of `pip freeze.`
- [x] I have included in the "Steps to reproduce" section below a minimally reproducible example.

## Description

When browsing the 'Reading Data' section of the AllenNLP Guide, the subsections 'Vocabulary' and 'Datasets, the dataset loader, and samplers' are nested inside of the 'Dataset Readers' subsection. Clicking on either of the nested elements closes the 'Dataset Readers' subsection. 

Screenshots of the issue:

![image](https://user-images.githubusercontent.com/18234433/107971295-4c357180-6f80-11eb-8136-420c27433d86.png)

![image](https://user-images.githubusercontent.com/18234433/107971521-94549400-6f80-11eb-9da0-42e1a0339b50.png)

## Environment

Windows 10

Google Chrome with uBlock, Grammarly, & Zotero Connector.

## Related Issues

None

## Steps to reproduce

Go to https://guide.allennlp.org/reading-data. I tested it both with and w/o extensions, and the issue persisted. 

Apologies if this is not the right place to post this issue; please let me know if there is a more appropriate location.

**Comment by epwalsh** [comment]
@gabeorlanski thanks for pointing that out! I must have accidentally removed a closing tag when I updated the guide for 2.0. Should be a quick fix.
