### ISSUE TITLE
Better device handling in VisionReader

### ISSUE THREAD

**Issue by aleSuglia** [allenai/allennlp#5014]
## Checklist

- [x] I have verified that the issue exists against the `master` branch of AllenNLP.
- [x] I have read the relevant section in the [contribution guide](https://github.com/allenai/allennlp/blob/master/CONTRIBUTING.md#bug-fixes-and-new-features) on reporting bugs.
- [x] I have checked the [issues list](https://github.com/allenai/allennlp/issues) for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/allenai/allennlp/pulls) for existing proposed fixes.
- [x] I have checked the [CHANGELOG](https://github.com/allenai/allennlp/blob/master/CHANGELOG.md) and the [commit log](https://github.com/allenai/allennlp/commits/master) to find out if the bug was already fixed in the master branch.
- [x] I have included in the "Description" section below a traceback from any exceptions related to this bug.
- [x] I have included in the "Related issues or possible duplicates" section beloew all related issues and possible duplicate issues (If there are none, check this box anyway).
- [x] I have included in the "Environment" section below the name of the operating system and Python version that I was using when I discovered this bug.
- [x] I have included in the "Environment" section below the output of `pip freeze`.
- [x] I have included in the "Steps to reproduce" section below a minimally reproducible example.

## Description

I am using the `VisionReader` for a specific task and I've noticed that, when the `cuda_device` is set, the batch processing generates features and region coordinates that are always on the GPU (please see [here](https://github.com/allenai/allennlp-models/blob/main/allennlp_models/vision/dataset_readers/vision_reader.py#L281)). However, I can see that the elements are stored in the cache as GPU tensor (please see [here](https://github.com/allenai/allennlp/blob/da4dba150d91c6863580912f71cbb62fc2a02d99/allennlp/common/file_utils.py#L611)) and then mapped to CPU once loaded (please see [here](https://github.com/allenai/allennlp/blob/da4dba150d91c6863580912f71cbb62fc2a02d99/allennlp/common/file_utils.py#L598)). However, when I try to use the image features tensors, I can definitely see that they are on the GPU and this breaks my code because all the other tensors that I'm creating are on the wrong device (CPU).

Unfortunately, I don't really have a full understanding of the AllenNLP internals for this dataset reader so any help is appreciated.  The way to solve it for now is to manually move the image features and region tensors to CPU in my `text_to_instance()`.

## Related issues or possible duplicates

- None

## Environment

OS: Linux

Python version: 3.8.5

<details>
<summary><b>Output of <code>pip freeze</code>:</b></summary>
<p>
absl-py==0.11.0
allennlp==2.0.1
allennlp-models==2.0.1
apex==0.1
astunparse==1.6.3
attrs==20.3.0
backcall==0.2.0
bert-score==0.3.7
BLEURT @ git+https://github.com/google-research/bleurt.git@2b7a3a1092daefce7c16ce9e243d37d23d497849
blis==0.7.4
boto3==1.16.34
botocore==1.19.34
cachetools==4.2.0
catalogue==1.0.0
certifi==2020.12.5
cffi==1.14.4
chardet==3.0.4
click==7.1.2
cloudpickle==1.6.0
conllu==4.3
cycler==0.10.0
cymem==2.0.5
Cython==0.29.21
cytoolz==0.11.0
datasets==1.2.1
decorator==4.4.2
dill==0.3.3
en-core-web-sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.3.1/en_core_web_sm-2.3.1.tar.gz
filelock==3.0.12
fire==0.4.0
flatbuffers==1.12
ftfy==5.9
gast==0.3.3
gensim==3.8.3
google-auth==1.24.0
google-auth-oauthlib==0.4.2
google-pasta==0.2.0
grpcio==1.32.0
h5py==2.10.0
horovod==0.21.1
idna==2.10
iniconfig==1.1.1
ipdb==0.13.4
ipython==7.20.0
ipython-genutils==0.2.0
jedi==0.18.0
jmespath==0.10.0
joblib==0.17.0
jsonlines==2.0.0
jsonnet==0.17.0
jsonpickle==1.4.2
Keras-Preprocessing==1.1.2
kiwisolver==1.3.1
lmdb==1.0.0
lz4==3.1.1
Markdown==3.3.3
matplotlib==3.3.3
mkl-fft==1.2.0
mkl-random==1.1.1
mkl-service==2.3.0
more-itertools==8.7.0
msgpack==1.0.2
msgpack-numpy==0.4.7.1
multiprocess==0.70.11.1
murmurhash==1.0.5
nlg-eval @ git+https://github.com/Maluuba/nlg-eval.git@2533028c3e325459f2a402698ec9c14a9298f124
nltk==3.5
numpy @ file:///tmp/build/80754af9/numpy_and_numpy_base_1603570489231/work
</p>
</details>

## Steps to reproduce

Any class that inherits from `VisionReader` will generate features that are on a specific `self.cuda_device` (if specified in the constructor). Usually, developers that are creating a dataset reader are not working with GPU yet therefore this breaks most of the code (I believe).
</details>

**Comment by dirkgr** [comment]
I tried this myself locally, and had no problems with it. But nevertheless, a possible fix is easy enough: #5026

Note that this fix only applies when storing the tensors, so you'd have to re-create all the caches before you can stop using your workaround.

**Comment by aleSuglia** [comment]
@dirkgr it is very weird indeed. Glad you find a nice and tidy workaround to it. You can close this issue if you wish!
