### ISSUE TITLE
A guide with the updated API

### ISSUE THREAD

**Issue by ekdnam** [allenai/allennlp#5017]
**Is your feature request related to a problem? Please describe.**

- As someone who is trying to get to know the library, I was looking at the documentation, which links to the guide [guide.allennlp.org](https://guide.allennlp.org/). It utilizes some APIs that seem to be deprecated in the later versions. 
- It is sometimes a difficult task to try to look at the code given in `Setup` and `Source`. 

**Describe the solution you'd like**

- Can a new guide be created which has the new API?
- Can a repo/gist/colab for the guide be created?

**Describe alternatives you've considered**

We can try to use the version used in the guide.

**Additional context**

Thanks!

**Comment by epwalsh** [comment]
Hi @ekdnam, I recently went through the guide to update everything to work with the latest version of AllenNLP. But it's possible I missed something. Can you point me to specific examples in the guide that use old / deprecated parts of the API?

**Comment by ekdnam** [comment]
Hi @epwalsh . 

At first while trying to run the code, I was copying and pasting the contents of `Source` and `Setup` which may have led to some errors while running it. My bad, and sorry for the inconvenience caused. This resolves the first point of my issue.

Later (ie after creating the issue) I was perusing the guide once again, and I found a link to the repo [allenai/allennlp-guide-examples](https://github.com/allenai/allennlp-guide-examples). This resolves the second point of my issue.

I should have gone through the guide more in depth. Again, sorry for the inconvenience caused.

**Comment by ekdnam** [comment]
Can perhaps a google colab notebook be created? Which makes it easier to interact with the example?

**Comment by epwalsh** [comment]
Ah, well actually it looks like https://github.com/allenai/allennlp-guide-examples may be out-of-date. I missed that while updating the guide, so I'll that to my to-do list.

What would like to see in a Google Colab notebook? The guide is already interactive, so I'm not sure what benefit that would have other than GPU access and maybe quicker runtime?

**Comment by epwalsh** [comment]
@ekdnam, the code in `allennlp-guide-examples` has now been moved over to `allennlp-guide` (https://github.com/allenai/allennlp-guide/pull/156). This PR also fixed an issue with the interactive environment in the guide where an older version of AllenNLP was installed instead of the latest 2.x release.

I'm going to close this issue to avoid confusion, but feel free to open another issue as a feature request for a Google Colab guide / example.

**Comment by ekdnam** [comment]
Just as I was commenting, the issue got resolved. Thanks!

**Comment by ekdnam** [comment]
Okay, will open a feature request
