### ISSUE TITLE
SeqDecoder abstraction and Variational Autoencoders

### ISSUE THREAD

**Issue by vikigenius** [allenai/allennlp#5021]
I was taking a look at the composed seq2seq models and their abstractions.
Is the `SeqDecoder` suitable for implementing Variational Autoencoders for generation tasks ?

Because it seems like `SeqDecoder` assumes that the encoder output in forward is the output from a `Seq2SeqEncoder`, however in a Variational Autoencoder wouldn't the better option for an encoder be a `Seq2VecEncoder` ?

The documentation does not make it clear what the [encoder_out](https://github.com/allenai/allennlp-models/blob/5feb88606926065737b7719c3965c657ce83b7b9/allennlp_models/generation/modules/seq_decoders/auto_regressive.py#L405) dictionary is supposed to be.

**Comment by epwalsh** [comment]
Hey @vikigenius, I think `encoder_out` can be anything as long as your [`DecoderNet`](https://github.com/allenai/allennlp-models/blob/5feb88606926065737b7719c3965c657ce83b7b9/allennlp_models/generation/modules/decoder_nets/decoder_net.py#L6) can handle it.

**Comment by epwalsh** [comment]
I'm not super familiar with this API though and like you said, it was probably not intended to be used with VAEs. But so far I don't see any reason why it can't be.

Either way, the documentation could definitely be improved.

**Comment by vikigenius** [comment]
I just revisited this and found out why the current abstraction cannot be used with VAEs> It is because, a VAE encoder is expected to produce the following shape. `[batch_size, latent_dim]` equivalent to a Seq2Vec encoder. However the SeqDecoder abstraction does the following

```
final_encoder_output = util.get_final_encoder_states(
    encoder_out["encoder_outputs"],
    encoder_out["source_mask"],
    bidirectional=self._bidirectional_input,
)
```

Which expects encoder_outputs to be from a Seq2Seq encoder with shape `[batch_size, num_tokens encoder_output_dim]` which is 3d and thus fails.
