### ISSUE TITLE
The SRL predictor doesn't work with the following error message

### ISSUE THREAD

**Issue by shinyemimalef** [allenai/allennlp#5022]
## Checklist

- [x ] I have verified that the issue exists against the `master` branch of AllenNLP.
- [x ] I have read the relevant section in the [contribution guide](https://github.com/allenai/allennlp/blob/master/CONTRIBUTING.md#bug-fixes-and-new-features) on reporting bugs.
- [x ] I have checked the [issues list](https://github.com/allenai/allennlp/issues) for similar or identical bug reports.
- [x ] I have checked the [pull requests list](https://github.com/allenai/allennlp/pulls) for existing proposed fixes.
- [x ] I have checked the [CHANGELOG](https://github.com/allenai/allennlp/blob/master/CHANGELOG.md) and the [commit log](https://github.com/allenai/allennlp/commits/master) to find out if the bug was already fixed in the master branch.
- [x ] I have included in the "Description" section below a traceback from any exceptions related to this bug.
- [x ] I have included in the "Related issues or possible duplicates" section beloew all related issues and possible duplicate issues (If there are none, check this box anyway).
- [x ] I have included in the "Environment" section below the name of the operating system and Python version that I was using when I discovered this bug.
- [x ] I have included in the "Environment" section below the output of `pip freeze`.
- [x ] I have included in the "Steps to reproduce" section below a minimally reproducible example.

## Description

<details>
<summary><b>Python traceback:</b></summary>
<p>

The error:
```
Traceback (most recent call last):
  File "/home/skhanehzar/DeployedProjects/Narrative/pipeline/srl.py", line 112, in <module>
    "https://storage.googleapis.com/allennlp-public-models/structured-prediction-srl-bert.2020.12.15.tar.gz")
  File "/home/skhanehzar/anaconda3/envs/narrative/lib/python3.7/site-packages/allennlp/predictors/predictor.py", line 275, in from_path
    load_archive(archive_path, cuda_device=cuda_device),
  File "/home/skhanehzar/anaconda3/envs/narrative/lib/python3.7/site-packages/allennlp/models/archival.py", line 197, in load_archive
    opt_level=opt_level,
  File "/home/skhanehzar/anaconda3/envs/narrative/lib/python3.7/site-packages/allennlp/models/model.py", line 398, in load
    return model_class._load(config, serialization_dir, weights_file, cuda_device, opt_level)
  File "/home/skhanehzar/anaconda3/envs/narrative/lib/python3.7/site-packages/allennlp/models/model.py", line 337, in _load
    model.load_state_dict(model_state)
  File "/home/skhanehzar/anaconda3/envs/narrative/lib/python3.7/site-packages/torch/nn/modules/module.py", line 847, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for SrlBert:
	Unexpected key(s) in state_dict: "bert_model.embeddings.position_ids". 

Process finished with exit code 1
```
</p>
</details>

## Related issues or possible duplicates

- None

## Environment

OS:

Python version: 3.7.9

<details>
<summary><b>Output of <code>pip freeze</code>:</b></summary>
<p>

```
(narrative) skhanehzar@slug:~$ pip freeze
allennlp==1.0.0
allennlp-models==1.0.0
attrs==20.3.0
blis==0.4.1
boto3==1.17.8
botocore==1.20.8
cached-property==1.5.2
catalogue==1.0.0
certifi==2020.12.5
chardet==4.0.0
click==7.1.2
conllu==3.0
cymem==2.0.5
en-core-web-sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.2.5/en_core_web_sm-2.2.5.tar.gz
filelock==3.0.12
future==0.18.2
h5py==3.1.0
idna==2.10
importlib-metadata==3.4.0
iniconfig==1.1.1
jmespath==0.10.0
joblib==1.0.1
jsonnet==0.17.0
jsonpickle==2.0.0
murmurhash==1.0.5
nltk==3.5
numpy==1.20.1
overrides==3.0.0
packaging==20.9
plac==1.1.3
pluggy==0.13.1
preshed==3.0.5
protobuf==3.14.0
py==1.10.0
py-rouge==1.1
pyparsing==2.4.7
pytest==6.2.2
python-dateutil==2.8.1
regex==2020.11.13
requests==2.25.1
s3transfer==0.3.4
sacremoses==0.0.43
scikit-learn==0.24.1
scipy==1.6.0
sentencepiece==0.1.95
six==1.15.0
spacy==2.2.4
srsly==1.0.5
tensorboardX==2.1
thinc==7.4.0
threadpoolctl==2.1.0
tokenizers==0.7.0
toml==0.10.2
torch==1.5.1
tqdm==4.56.2
transformers==2.11.0
typing-extensions==3.7.4.3
urllib3==1.26.3
wasabi==0.8.2
word2number==1.1
zipp==3.4.0
```

</p>
</details>

## Steps to reproduce
Run the following code with python interpreter

```
from allennlp.predictors.predictor import Predictor
import allennlp_models.tagging
predictor = Predictor.from_path(
        "https://storage.googleapis.com/allennlp-public-models/structured-prediction-srl-bert.2020.12.15.tar.gz")
pp = predictor.predict(
        sentence="Did Uriah honestly think he could beat the game in under three hours?."
 )
```

<details>
<summary><b>Example source:</b></summary>
<p>

See steps to reproduce above

</p>
</details>

**Comment by AkshitaB** [comment]
@shinyemimalef The latest archive file that you're using works with allennlp 2.0. You can upgrade the allennlp version. If you would like to continue using allennlp 1.0, then the right archive file is `https://storage.googleapis.com/allennlp-public-models/bert-base-srl-2020.03.24.tar.gz` .

@dirkgr This may have been missed in the demo model sweep. I think the `install_instructions` need to be updated.

**Comment by dirkgr** [comment]
The model sweep is not yet up on the website. I hope to get to that today or tomorrow.

**Comment by dirkgr** [comment]
This will work once https://github.com/allenai/allennlp-models/pull/227 and https://github.com/allenai/allennlp-demo/pull/888 are merged.

**Comment by dirkgr** [comment]
This works now, except the model card is out of date. I put in a PR to show the new model card in the demo.
