### ISSUE TITLE
lmdb.BadRslotError: mdb_txn_begin: MDB_BAD_RSLOT: Invalid reuse of reader locktable slot

### ISSUE THREAD

**Issue by aleSuglia** [allenai/allennlp#5027]
## Checklist

- [x] I have verified that the issue exists against the `master` branch of AllenNLP.
- [x] I have read the relevant section in the [contribution guide](https://github.com/allenai/allennlp/blob/master/CONTRIBUTING.md#bug-fixes-and-new-features) on reporting bugs.
- [x] I have checked the [issues list](https://github.com/allenai/allennlp/issues) for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/allenai/allennlp/pulls) for existing proposed fixes.
- [x] I have checked the [CHANGELOG](https://github.com/allenai/allennlp/blob/master/CHANGELOG.md) and the [commit log](https://github.com/allenai/allennlp/commits/master) to find out if the bug was already fixed in the master branch.
- [x] I have included in the "Description" section below a traceback from any exceptions related to this bug.
- [x] I have included in the "Related issues or possible duplicates" section beloew all related issues and possible duplicate issues (If there are none, check this box anyway).
- [x] I have included in the "Environment" section below the name of the operating system and Python version that I was using when I discovered this bug.
- [x] I have included in the "Environment" section below the output of `pip freeze`.
- [x] I have included in the "Steps to reproduce" section below a minimally reproducible example.

## Description

I'm having issues in reusing a single LMDB from multiple processes running on a SLURM-managed cluster. I'm trying to use multiple `VisionReader`s in a multi-task setup. The error seems to be at line 593 of the `TensorCache` class. Please see below:

<details>
<summary><b>Python traceback:</b></summary>
<p>

```
Traceback (most recent call last):
  File "/lustre/home/ec156/asuglia/miniconda3/envs/devel/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/lustre/home/ec156/asuglia/miniconda3/envs/devel/lib/python3.8/site-packages/allennlp/commands/train.py", line 466, in _train_worker
    metrics = train_loop.run()
  File "/lustre/home/ec156/asuglia/miniconda3/envs/devel/lib/python3.8/site-packages/allennlp/commands/train.py", line 528, in run
    return self.trainer.train()
  File "/lustre/home/ec156/asuglia/miniconda3/envs/devel/lib/python3.8/site-packages/allennlp/training/trainer.py", line 930, in train
    metrics, epoch = self._try_train()
  File "/lustre/home/ec156/asuglia/miniconda3/envs/devel/lib/python3.8/site-packages/allennlp/training/trainer.py", line 962, in _try_train
    train_metrics = self._train_epoch(epoch)
  File "/lustre/home/ec156/asuglia/miniconda3/envs/devel/lib/python3.8/site-packages/allennlp/training/trainer.py", line 663, in _train_epoch
    for batch_group in batch_group_generator_tqdm:
  File "/lustre/home/ec156/asuglia/miniconda3/envs/devel/lib/python3.8/site-packages/allennlp/common/util.py", line 139, in lazy_groups_of
    s = list(islice(iterator, group_size))
  File "/lustre/home/ec156/asuglia/miniconda3/envs/devel/lib/python3.8/site-packages/allennlp/data/data_loaders/multitask_data_loader.py", line 194, in <genexpr>
    return (
  File "/lustre/home/ec156/asuglia/miniconda3/envs/devel/lib/python3.8/site-packages/more_itertools/recipes.py", line 317, in roundrobin
    yield next()
  File "/lustre/home/ec156/asuglia/miniconda3/envs/devel/lib/python3.8/site-packages/more_itertools/recipes.py", line 73, in take
    return list(islice(iterable, n))
  File "/lustre/home/ec156/asuglia/miniconda3/envs/devel/lib/python3.8/site-packages/allennlp/common/util.py", line 668, in shuffle_iterable
    for item in i:
  File "/lustre/home/ec156/asuglia/miniconda3/envs/devel/lib/python3.8/site-packages/allennlp/data/data_loaders/multiprocess_data_loader.py", line 349, in iter_instances
    for instance in Tqdm.tqdm(
  File "/lustre/home/ec156/asuglia/miniconda3/envs/devel/lib/python3.8/site-packages/tqdm/std.py", line 1166, in __iter__
    for obj in iterable:
  File "/lustre/home/ec156/asuglia/miniconda3/envs/devel/lib/python3.8/site-packages/allennlp/data/data_loaders/multitask_data_loader.py", line 290, in read
    for instance in self.inner.read(file_path):
  File "/lustre/home/ec156/asuglia/miniconda3/envs/devel/lib/python3.8/site-packages/allennlp/data/dataset_readers/dataset_reader.py", line 192, in read
    for instance in self._multi_worker_islice(self._read(file_path)):  # type: ignore
  File "/lustre/home/ec156/asuglia/workspace/VILGEN/vilgen/readers/pretraining.py", line 1026, in _read
    for caption_tuple, processed_image in zip(caption_dicts, processed_images):
  File "/lustre/home/ec156/asuglia/workspace/VILGEN/vilgen/readers/pretraining.py", line 970, in _process_image_paths
    coordinates: Tensor = self._coordinates_cache[basename].cpu()
  File "/lustre/home/ec156/asuglia/miniconda3/envs/devel/lib/python3.8/site-packages/allennlp/common/file_utils.py", line 594, in __getitem__
    with self.lmdb_env.begin(write=False) as txn:
lmdb.BadRslotError: mdb_txn_begin: MDB_BAD_RSLOT: Invalid reuse of reader locktable slot
```

</p>
</details>

## Related issues or possible duplicates

The error has been reported on [StackOverflow](https://stackoverflow.com/questions/56905502/lmdb-badrsloterror-mdb-txn-begin-mdb-bad-rslot-invalid-reuse-of-reader-lockta) and seems to have to do with how the transaction is opened.

## Environment

OS: Linux

Python version: Python 3.8.5 (via Miniconda)

<details>
<summary><b>Output of <code>pip freeze</code>:</b></summary>
<p>

```
allennlp==2.1.0
allennlp-models==2.0.1
attrs==20.3.0
backcall==0.2.0
blis==0.7.4
boto3==1.17.12
botocore==1.20.12
catalogue==1.0.0
certifi==2020.12.5
chardet==4.0.0
click==7.1.2
conllu==4.3
cymem==2.0.5
decorator==4.4.2
en-core-web-sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.3.1/en_core_web_sm-2.3.1.tar.gz
filelock==3.0.12
fire==0.4.0
ftfy==5.9
h5py==3.1.0
idna==2.10
iniconfig==1.1.1
ipdb==0.13.4
ipython==7.20.0
ipython-genutils==0.2.0
jedi==0.18.0
jmespath==0.10.0
joblib==1.0.0
jsonlines==2.0.0
jsonnet==0.17.0
jsonpickle==1.4.2
lmdb==1.1.1
more-itertools==8.7.0
murmurhash==1.0.5
nltk==3.5
numpy==1.19.5
overrides==3.1.0
packaging==20.8
pandas==1.2.2
parso==0.8.1
pexpect==4.8.0
pickleshare==0.7.5
Pillow==8.1.0
plac==1.1.3
pluggy==0.13.1
preshed==3.0.5
prompt-toolkit==3.0.16
protobuf==3.14.0
ptyprocess==0.7.0
py==1.10.0
py-rouge==1.1
Pygments==2.8.0
pyparsing==2.4.7
pytest==6.2.1
python-dateutil==2.8.1
pytz==2021.1
regex==2020.11.13
requests==2.25.1
s3transfer==0.3.4
sacremoses==0.0.43
scikit-learn==0.24.0
scipy==1.6.0
sentencepiece==0.1.95
six==1.15.0
spacy==2.3.5
srsly==1.0.5
tensorboardX==2.1
termcolor==1.1.0
thinc==7.4.5
threadpoolctl==2.1.0
tokenizers==0.9.4
toml==0.10.2
torch==1.7.1
torchvision==0.8.2
tqdm==4.56.0
traitlets==5.0.5
transformers==4.2.2
typing-extensions==3.7.4.3
urllib3==1.26.2
wasabi==0.8.0
wcwidth==0.2.5
word2number==1.1
```

</p>
</details>

## Steps to reproduce

In my case, I use a script to run multiple training sessions as multiple SLURM jobs (I use `allennlp train` to start the training sessions). All these training sessions are using the same image feature cache. I am indeed able to run a single job without any problems.

**Comment by dirkgr** [comment]
I suspect this happens when you
1. create an instance of `TensorCache` in the main process
2. forking the process (with `multiprocessing` or by setting up multiple workers in the data loader and having the start method set to `fork`)
3. use the instance of `TensorCache` in the forked process

Can you confirm that this happens?

**Comment by aleSuglia** [comment]
The thing that I don't understand is why it is happening to me when I'm just using the vision reader almost as it is (just changed the 'text_to_instance').

**Comment by dirkgr** [comment]
I don't know. That's why we'll have to dig in. But I suspect your problem will go away, without loss of performance, if you don't use multiple workers.

**Comment by aleSuglia** [comment]
Sorry I forgot to reply to this one as well. At the moment I'm not using multiple workers. However, when I run on a SLURM cluster multiple jobs that are trying to write on the same cache, I get the same error.

**Comment by dirkgr** [comment]
I have not forgotten about this, but I don't have anything to go on. We can't just turn off locking, like they did in the StackOverflow solution, since we can't be sure that nobody is writing. And in fact, writing is what @aleSuglia wants to do. I don't have the problem locally.

Just gathering some more data: Since you have a SLURM cluster, this must be a Linux box, right? Is the cache on NFS and you have multiple machines accessing it that way?

**Comment by dirkgr** [comment]
`TensorCache` itself is not a lot of code. I'm wondering if we should just not worry about this issue and just replace it with something based on Arrow or HDF5. It might take less time to do that, though we'd break backwards compatibility.

On the other hand, this is literally the only issue with `TensorCache` that I'm aware of.

**Comment by aleSuglia** [comment]
I'm currently not able to access the cluster so I wasn't able to reproduce the error in that setup. However, I had the same error when having multiple workers active and a *lockable* database inside a dataset reader. So I've managed to solve by having a first preprocessing step where I allow to write in the cache and a second "read-only" phase. My current solution is an hack. There must be a way to reliably handle this case even though seems that there is no solution to this: https://stackoverflow.com/questions/56905502/lmdb-badrsloterror-mdb-txn-begin-mdb-bad-rslot-invalid-reuse-of-reader-lockta

**Comment by dirkgr** [comment]
We could try to fix it in the lmdb package. It would be a bit of work, but not too bad if you know C. But like I said, it might be easier to switch the whole thing over to HDF5.

**Comment by dirkgr** [comment]
With no reliable repro, I'll have to close this. The real fix is to re-write `TensorCache` to use HDF5, which I should have done from the start. It's probably not even that much work, but hard to prioritize right now. I'd be happy to review a PR though.

**Comment by dirkgr** [comment]
This has been a slow burn, but I actually think I figured out what caused this, and I fixed it in https://github.com/allenai/allennlp/pull/5162/files#diff-59b9ea62d76e2c7b6522d8d8660dae1497f7b181211e7b59788f6c48e969ba6b. @aleSuglia, can you try that?
