### ISSUE TITLE
MultiProcessDataLoader copies data to all workers (regardless of max_instances_in_memory value)

### ISSUE THREAD

**Issue by GR4HAM** [allenai/allennlp#5029]
I tried implementing a simple MultiProcessDataLoader according to the new documentation. The dataloading does appear to speed up significantly through the use of multiple processors, however, the entire dataset appears to be copied to each worker.

I am using many large data files so would like to avoid copying the entire dataset to each worker. My understanding is that this can be avoided by e.g. setting:
 
`max_instances_in_memory =X*batch_size`

With X an integer e.g. 10. However, this doesn't appear to work for me. I believe I followed the instructions in the migration guide. Below I add a reproducible example. Running this code will show that each cpu has +- 215MB in memory, regardless of the amount of cpu's. Am I misinterpreting something or is this a bug?

python version: 3.7.9
pytorch version: 1.7.1
allennlp version: 2.0.1

```python
import os
import time
import torch
from allennlp.data.data_loaders import MultiProcessDataLoader
from allennlp.data.vocabulary import Vocabulary
from allennlp.data.tokenizers.spacy_tokenizer import SpacyTokenizer
from allennlp.data.token_indexers.single_id_token_indexer import SingleIdTokenIndexer
from allennlp.data.dataset_readers.dataset_reader import DatasetReader
from allennlp.data.instance import Instance
from overrides import overrides
from typing import Dict, List, Union, Iterable, Optional
from allennlp.data.fields import TextField

class DummyReader(DatasetReader):
    """
    Dummy reader
    """
    def __init__(self) -> None:        
        super().__init__(manual_distributed_sharding=True, manual_multiprocess_sharding=True)
        self.tokenizer = SpacyTokenizer(split_on_spaces=True)
        self.token_indexers = {"singleid": SingleIdTokenIndexer()}

    def text_to_instance(self, 
                         text: str) -> Instance:
        tokens = self.tokenizer.tokenize(text)
        return Instance({"source": TextField(tokens)})

    @overrides
    def apply_token_indexers(self, instance: Instance) -> None:
        instance.fields["source"].token_indexers = self.token_indexers

    @overrides
    def _read(self, file_path: str) -> Iterable[Instance]:
        #dummy data
        df = ["dummy text"]*10**7
        for row in self.shard_iterable(df):
            yield self.text_to_instance(row)


reader = DummyReader()

BATCH_SIZE = 1024
BATCHES_PER_EPOCH=(10**4)
MAX_INSTANCES_IN_MEMORY = 10*BATCH_SIZE
NUM_WORKERS=1
allen_loader = MultiProcessDataLoader(reader=reader, data_path="dummy", batch_size=1024, batches_per_epoch=BATCHES_PER_EPOCH, 
                            shuffle=False, max_instances_in_memory=MAX_INSTANCES_IN_MEMORY, num_workers=NUM_WORKERS)


vocab = Vocabulary(counter=None, min_count=1, max_vocab_size=5)
vocab.add_token_to_namespace("dummy", namespace="tokens")
vocab.add_token_to_namespace("text", namespace="tokens")
allen_loader.index_with(vocab)


for c,batch in enumerate((allen_loader)):
    if c == 0:
        start=time.time()
    if c>BATCHES_PER_EPOCH:
        break
    
end = time.time()
print("Time spent: ",end-start)

```

**Comment by epwalsh** [comment]
Hi @GR4HAM, your example code looks good. I don't see any issues with it.

Could you elaborate on what you mean by this:

> entire dataset appears to be copied to each worker

What dataset?

**Comment by GR4HAM** [comment]
In the above example it is just a dummy dataset containing 10 million instances saying "dummy text", however in my real life use case it is of course a large dataset containing text. The point is that I would not expect the entire dataset to be copied for each worker I create. Thus if I would use 10 workers, I would run out of memory on the server where I am running the computations. In my mind, the above code should lead to each worker only accessing X*batch_size worth of memory, which is not the case.

**Comment by epwalsh** [comment]
> The point is that I would not expect the entire dataset to be copied for each worker I create.

So it sounds like you have the dataset loaded in memory in the main Python process _before_ starting the workers?

**Comment by GR4HAM** [comment]
Indeed I load the dataset into a dataframe in the _read method (similar to how the data is put in a list in the _read method in the dummy example above). Is that not the correct way to go about it?

**Comment by epwalsh** [comment]
When the data loader starts its workers, each worker has a it's own clone of the dataset reader. Then each worker individually calls `.read()` (and therefore `_read()`) on its dataset reader. So in your case, each worker will have to load the dataset into the dataframe.

The recommended way to implement the `_read()` method here would be to *lazily* read from the csv file line-by-line:

```python
def _read(self, file_path: str):
    with open(file_path) as f:
        for row in self.shard_iterable(f):
            yield self.text_to_instance(row)
```

**Comment by GR4HAM** [comment]
Ok thank you for that suggestion but there are a few use cases where one would want to load the dataset first. For example, one might want to resample based on label occurrence or one might want to simply shuffle the dataset. 

Is there no way that I could load the dataset into a dataframe and then achieve something similar to what you suggest (preferably without having to write everything back into a text/csv file first)?

**Comment by epwalsh** [comment]
> one might want to resample based on label occurrence or one might want to simply shuffle the dataset

These use-cases fit into the purpose of the [`BatchSampler`](https://docs.allennlp.org/main/api/data/samplers/batch_sampler/#batchsampler) API. Or, for simple shuffling, you can just set `data_loader.shuffle` to `true`.

That said, if you're loading data lazily (i.e. when you have `max_instances_in_memory` set) the benefit of using more than 1 worker is usually marginal at best, since the bottleneck in training is almost always the forward-backward pass of your model, not loading data.

**Comment by GR4HAM** [comment]
Ok thank you very much, I didn't realize BatchSampler would work with lazy loading . Any chance you can direct me to an example of how to implement BatchSampler for lazy loading?

**Comment by epwalsh** [comment]
You can look at the implementation of `BucketBatchSampler` for an example: https://github.com/allenai/allennlp/blob/main/allennlp/data/samplers/bucket_batch_sampler.py#L22
