### ISSUE TITLE
issueThis issue is being closed due to lack of activity. If you think it still needs to be addressed, please comment on this thread 👇

### ISSUE THREAD

**Issue by apsiriwat** [allenai/allennlp#5042]
This issue is being closed due to lack of activity. If you think it still needs to be addressed, please comment on this thread 👇

_Originally posted by @github-actions[bot] in https://github.com/allenai/allennlp/issues/4848#issuecomment-749072473_

**Comment by apsiriwat** [comment]
> This issue is being closed due to lack of activity. If you think it still needs to be addressed, please comment on this thread 👇
> 
> _Originally posted by @github-actions[bot] in [#4848 (comment)](https://github.com/allenai/allennlp/issues/4848#issuecomment-749072473)_

**Comment by apsiriwat** [comment]
#5042

**Comment by dirkgr** [comment]
Sorry, I re-opened the other issue.

**Comment by apsiriwat** [comment]
ในวันที่ ส. 13 มี.ค. 2021 00:35 Dirk Groeneveld ***@***.***>
เขียนว่า:
