### ISSUE TITLE
Allennlp unnecessarily downloading huggingface models during evaluation

### ISSUE THREAD

**Issue by nelson-liu** [allenai/allennlp#5044]
Hi!

I trained a model with BERT (base) on MNLI, using the config in `allennlp-models`. I offhandedly noticed this, and I'm not sure if it's a bug.

When I moved the output of the allennlp run to another machine (without a huggingface or allennlp cache) and ran `allennlp evaluate` with it, I noticed that downloads were happening. I've put the full evaluation log below, but it seems like these are the BERT base files (tokenizer, vocabulary, model checkpoints) being downloaded by huggingface (just comparing to my training logs and what I'd expect given what I know about the model). I'd imagine this is probably partially an issue with AllenNLP and partially an issue with huggingface, but figured I'd mention it here so it's documented at least.

Anyway, this is probably pretty low-priority, but it seems like in this case, the model is instantiated with the pre-trained BERT weights (which have to be downloaded from the internet), and then immediately overwritten with what's stored in `model.tar.gz`. I wonder if there's some way to defer this download in the `evaluate` / `predict` case, since it really doesn't seem like they should be necessary (i.e., I'd expect inference to work fully offline).

Thanks!

```
[nltk_data] Downloading package punkt to
[nltk_data]     /0xa1bf5d3e4bb248fd99bb5a28b6029041/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package wordnet to
[nltk_data]     /0xa1bf5d3e4bb248fd99bb5a28b6029041/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.
2021-03-08 04:42:41,199 - INFO - allennlp.common.plugins - Plugin allennlp_models available
2021-03-08 04:42:41,202 - INFO - allennlp.models.archival - loading archive file model_bundle/sampled_hps_05c6993db950b757ac8a02f9516055b8_fixed/model.tar.gz
2021-03-08 04:42:41,203 - INFO - allennlp.models.archival - extracting archive file model_bundle/sampled_hps_05c6993db950b757ac8a02f9516055b8_fixed/model.tar.gz to temp dir /tmp/tmphow9s0vy

Downloading:   0%|          | 0.00/433 [00:00<?, ?B/s]
Downloading: 100%|██████████| 433/433 [00:00<00:00, 202kB/s]

Downloading:   0%|          | 0.00/213k [00:00<?, ?B/s]
<snip>
Downloading: 100%|██████████| 213k/213k [00:00<00:00, 1.03MB/s]

Downloading:   0%|          | 0.00/436k [00:00<?, ?B/s]
<snip>
Downloading: 100%|██████████| 436k/436k [00:00<00:00, 1.34MB/s]
2021-03-08 04:42:48,189 - INFO - allennlp.data.vocabulary - Loading token dictionary from /tmp/tmphow9s0vy/vocabulary.

Downloading:   0%|          | 0.00/436M [00:00<?, ?B/s]
Downloading:   0%|          | 1.49M/436M [00:00<00:29, 14.9MB/s]
<snip>
Downloading: 100%|██████████| 436M/436M [00:34<00:00, 12.6MB/s]
2021-03-08 04:43:29,667 - INFO - allennlp.models.archival - removing temporary unarchived model dir at /tmp/tmphow9s0vy
2021-03-08 04:43:29,716 - INFO - allennlp.common.checks - Pytorch version: 1.7.1+cu101
2021-03-08 04:43:29,717 - INFO - allennlp.commands.evaluate - Reading evaluation data from test.json
loading instances: 0it [00:00, ?it/s]
loading instances: 2742it [00:02, 1370.67it/s]
loading instances: 5484it [00:04, 1366.55it/s]
loading instances: 8218it [00:06, 1365.18it/s]
loading instances: 9824it [00:07, 1379.82it/s]
2021-03-08 04:43:37,200 - INFO - allennlp.training.util - Iterating over dataset
0it [00:00, ?it/s]
2021-03-08 04:43:37,209 - INFO - allennlp.data.samplers.bucket_batch_sampler - No sorting keys given; trying to guess a good one
2021-03-08 04:43:37,209 - INFO - allennlp.data.samplers.bucket_batch_sampler - Using ['tokens'] as the sorting keys
accuracy: 0.73, loss: 1.07 ||: : 114it [00:02, 56.76it/s]
accuracy: 0.73, loss: 1.09 ||: : 232it [00:04, 58.02it/s]
accuracy: 0.72, loss: 1.08 ||: : 349it [00:06, 57.70it/s]
accuracy: 0.72, loss: 1.08 ||: : 465it [00:08, 57.55it/s]
accuracy: 0.73, loss: 1.07 ||: : 584it [00:10, 58.09it/s]
accuracy: 0.73, loss: 1.05 ||: : 703it [00:12, 58.47it/s]
accuracy: 0.73, loss: 1.04 ||: : 821it [00:14, 58.60it/s]
accuracy: 0.73, loss: 1.04 ||: : 942it [00:16, 59.07it/s]
accuracy: 0.73, loss: 1.03 ||: : 1061it [00:18, 58.47it/s]
accuracy: 0.73, loss: 1.03 ||: : 1180it [00:20, 58.75it/s]
accuracy: 0.73, loss: 1.02 ||: : 1228it [00:21, 58.38it/s]
2021-03-08 04:43:58,234 - INFO - allennlp.common.util - Metrics: {
  "accuracy": 0.7325936482084691,
  "loss": 1.0198601739944098
}
2021-03-08 04:43:58,234 - INFO - allennlp.commands.evaluate - Finished evaluating.
```

**Comment by dirkgr** [comment]
We know it does this, but it is not a big priority for most of the work that people do with these. Is it a big problem for you?

**Comment by dirkgr** [comment]
We don't know an easy way to address this problem. We have to load HF models just to get the shape of the model, even if we don't care about the weights. If you can think of a quick fix we'd be interested.

**Comment by wlhgtc** [comment]
@nelson-liu  Maybe you could download it and save to a path, then add this path to param, like:
``` python
local model_name = "./resources/robert_model";
...
  "source_tokenizer": {
      "type": "pretrained_transformer",
      "model_name": model_name,
      "add_special_tokens":false,
  },

```

**Comment by dirkgr** [comment]
I think @ArjunSubramonian is on the case?

**Comment by ArjunSubramonian** [comment]
We only have a partial solution: https://github.com/allenai/allennlp/pull/5085. Now, the pretrained weights are not downloaded, but the config file is still download (for the purpose of determining the architecture), if there are override weights.

**Comment by nelson-liu** [comment]
Seems pretty reasonable to me, I'm happy with not having to download pre-trained weights---the configs are tiny anyways. Thanks @ArjunSubramonian
