### ISSUE TITLE
Coreference resolution model performance

### ISSUE THREAD

**Issue by yqw-vicki** [allenai/allennlp#5045]
I have trained coreference resolution model with spanbert-base-cased model. But only obtain F1 score as 69%, The following is my training model. 

```
  transformer_model = "SpanBERT/spanbert-base-cased"
  max_length = 512
  feature_size = 20
  max_span_width = 30
  transformer_dim = 768  # uniquely determined by transformer_model
  span_embedding_dim = 3*transformer_dim + feature_size
  span_pair_embedding_dim = 3*span_embedding_dim + feature_size
  token_indexer = PretrainedTransformerMismatchedIndexer(model_name=transformer_model, max_length=max_length)
  reader = ConllCorefReader(max_span_width, {'bert_tokens': token_indexer}, max_sentences=110)
  train_dataset = reader.read(train_filepath)
  validation_dataset = reader.read(valid_filepath)
  vocab = Vocabulary()
  train_dataset.index_with(vocab)
  validation_dataset.index_with(vocab)
  train_sampler = BucketBatchSampler(train_dataset, batch_size=1, sorting_keys=["text"], padding_noise=0.0)
  train_loader = DataLoader(train_dataset, batch_size=1, batch_sampler=train_sampler, collate_fn=allennlp_collate)
  dev_sampler = BucketBatchSampler(validation_dataset, batch_size=1, sorting_keys=["text"], padding_noise=0.0)
  dev_loader = DataLoader(validation_dataset, batch_size=1, batch_sampler=dev_sampler, collate_fn=allennlp_collate)
  embedding = PretrainedTransformerMismatchedEmbedder(transformer_model, max_length=max_length)
  embedder = BasicTextFieldEmbedder(token_embedders={'bert_tokens': embedding})
  encoder = PassThroughEncoder(input_dim=transformer_dim)
  mention_feedforward = FeedForward(span_embedding_dim, 2, [1500, 1500], torch.nn.ReLU(), dropout=0.3)
  antecedent_feedforward = FeedForward(span_pair_embedding_dim, 2, [1500, 1500], torch.nn.ReLU(), dropout=0.3)
  normal_initial = XavierNormalInitializer()
  orthogonal_initial = OrthogonalInitializer()
  initial_para = [[".*_span_updating_gated_sum.*weight", normal_initial],
                  [".*linear_layers.*weight", normal_initial],
                  [".*scorer.*weight", normal_initial],
                  ["_distance_embedding.weight", normal_initial],
                  ["_span_width_embedding.weight", normal_initial],
                  ["_context_layer._module.weight_ih.*", normal_initial],
                  ["_context_layer._module.weight_hh.*", orthogonal_initial]
                ]
  initializer = InitializerApplicator(regexes=initial_para)
  corefer = CoreferenceResolver(vocab, text_field_embedder=embedder, context_layer=encoder,
                                mention_feedforward=mention_feedforward, antecedent_feedforward=antecedent_feedforward,
                                feature_size=feature_size, max_span_width=max_span_width, spans_per_word=0.4,
                                max_antecedents=50, coarse_to_fine=True, inference_order=2,
                                lexical_dropout=0.5, initializer=initializer).to("cpu")
  def build_trainer(
      model: Model,
      serialization_dir: str,
      train_loader: DataLoader,
      dev_loader: DataLoader
  ) -> Trainer:
      parameters = [
          (n, p)
          for n, p in model.named_parameters()
      ]
      grouppara = [
          [[".*transformer.*"], {"lr": 1e-5}]
      ]
      optimizer = HuggingfaceAdamWOptimizer(parameters, grouppara, lr=3e-4)
      learning_rate_scheduler = SlantedTriangular(optimizer, num_epochs=40, cut_frac=0.06)
      checkpoint = Checkpointer(serialization_dir=serialization_dir)
      trainer = GradientDescentTrainer(
          model=model,
          serialization_dir=serialization_dir,
          checkpointer=checkpoint,
          data_loader=train_loader,
          validation_data_loader=dev_loader,
          validation_metric="+coref_f1",
          patience=10,
          num_epochs=40,
          cuda_device=-1,
          learning_rate_scheduler=learning_rate_scheduler,
          optimizer=optimizer
      )
      return trainer
  serialization_dir = os.path.join(dirpath, "spanbert_check")
  trainer = build_trainer(
      corefer,
      serialization_dir,
      train_loader,
      dev_loader
  )
  print("Starting training")
  trainer.train()
  print("Finished training")
```

**Comment by dirkgr** [comment]
I did not read through all your code here, but I also re-trained this model recently, and found that it is sensitive to the pre-processing of the input data.

@ZhaofengWu, what did you do to create your pre-trained data?

**Comment by ZhaofengWu** [comment]
I think I just used the original Ontonotes data without doing anything special. @yqw-vicki I recommend you to compare your code with our training config, which I believe does train well.

**Comment by yqw-vicki** [comment]
I am sure all my code following the training config. The only difference is I use spanbert-base model not spanbert-large model. But even for spanbert base model, 69% is still a little low. That is why I am confused.

**Comment by ZhaofengWu** [comment]
Can you get the desired performance with the config without writing any code?

**Comment by yqw-vicki** [comment]
I haven't try that. I could test, but considering I want to do some modification later, so I prefer to run it with code.

**Comment by ZhaofengWu** [comment]
Please try that. If you get good performance with the config, it means that there's something wrong with your code setup.

**Comment by yqw-vicki** [comment]
I tried to run config jsonnet on ontonotes, the conll-formatted folder structured  is same as the one in https://docs.allennlp.org/models/v2.0.1/models/common/ontonotes/. Then I take "conll-formatted-ontonotes-5.0/data/train" as training path. But I got the error "IsADirectoryError:[Errno 21] Is a directory". 
Could you please tell me what is the correct training path?

**Comment by ZhaofengWu** [comment]
I don't have a copy of the data by me at the moment -- @dirkgr can you help confirm this?

**Comment by dirkgr** [comment]
I have the data, but we are legally not allowed to share it. The question is, how do we go from `conll-formatted-ontonotes-5.0/data/train` to the input you used?

**Comment by yqw-vicki** [comment]
Should I collect all seperate training files into one conll-formatted file? What I am doing now in the python code is use "dataset_path_iterator" to get all filepath which end with ".gold_conll".

**Comment by dirkgr** [comment]
@DeNeutoy, I hear the original data that we train the coref model on came from you, when you wrote the old coref model. Do you remember how you prepared it?

**Comment by dirkgr** [comment]
> Should I collect all seperate training files into one conll-formatted file? What I am doing now in the python code is use "dataset_path_iterator" to get all filepath which end with ".gold_conll".

When I did it, I just concatenated them into one large file. But I also got your degraded performance when I did this.

**Comment by dirkgr** [comment]
I looked into this a bit more. It seems that `conll-formatted-ontonotes-5.0` is a strict superset of the data that this model was trained on. That includes the test and validation sets. They are different in `conll-formatted-ontonotes-5.0`, so the numbers are not directly comparable.

Since `conll-formatted-ontonotes-5.0` is bigger, I would guess that the trained model turns out better, even if the numbers don't show that. I started an experiment to see what numbers I get when I train on `5.0`, but then evaluate on the same dataset that the official evaluation is done on.

**Comment by DeNeutoy** [comment]
[this script](https://github.com/allenai/allennlp/blob/main/scripts/compile_coref_data.sh) converts the conll formatted ontonotes data into the format used for training. The preparation of that data is gross - from memory, it uses some combination of the conll v4.0 annotations and the v5.0 text, or something like that. Also, there is one whole split in ontonotes (one of the 2 char directories, like `nw`) which has no coref annotations at all.

**Comment by yqw-vicki** [comment]
I am a bit confused. Do you mean the dataset should includes conll v4.0 annotations and v5.0 text?

**Comment by DeNeutoy** [comment]
I can't exactly remember, but that script does something quite odd internally I think. It will download all the correct stuff, you just need to run it, supplying the path to the Ontonotes 5.0 directory.

**Comment by dirkgr** [comment]
Cool. I confirmed that the script produces the correct data, fixed it to work when you have python3, and added it to allennlp-models here: https://github.com/allenai/allennlp-models/pull/239

**Comment by yqw-vicki** [comment]
I have runned the script. The new f1 score is 76%. It definitely improved.
