### ISSUE TITLE
Coreference model: clusters removed with more text being added.

### ISSUE THREAD

**Issue by matyaspjuhasz** [allenai/allennlp#5048]
## Checklist

- [x] I have verified that the issue exists against the `master` branch of AllenNLP.
- [x] I have read the relevant section in the [contribution guide](https://github.com/allenai/allennlp/blob/master/CONTRIBUTING.md#bug-fixes-and-new-features) on reporting bugs.
- [x] I have checked the [issues list](https://github.com/allenai/allennlp/issues) for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/allenai/allennlp/pulls) for existing proposed fixes.
- [x] I have checked the [CHANGELOG](https://github.com/allenai/allennlp/blob/master/CHANGELOG.md) and the [commit log](https://github.com/allenai/allennlp/commits/master) to find out if the bug was already fixed in the master branch.
- [x] I have included in the "Description" section below a traceback from any exceptions related to this bug.
- [x] I have included in the "Related issues or possible duplicates" section beloew all related issues and possible duplicate issues (If there are none, check this box anyway).
- [x] I have included in the "Environment" section below the name of the operating system and Python version that I was using when I discovered this bug.
- [x] I have included in the "Environment" section below the output of `pip freeze`.
- [x] I have included in the "Steps to reproduce" section below a minimally reproducible example.

## Description

<p>
Hi!

I've observed an issue, whereby the coreference solution doesn't include clusters for longer text, that it identifies for a shorter version of the same text. This problem can be reproduced when using [your demo](https://demo.allennlp.org/coreference-resolution) too, so for the ease of explanation, I'll include the screenshots from there.

Below is the case with the "short text" - cluster 4 is identified correctly with 2 spans in it. (Interestingly it also includes cluster 6 with just 1 span in it)

![image](https://user-images.githubusercontent.com/59828210/110619036-a0a2ca00-8197-11eb-801a-b5bec5ebcb09.png)

Here's the text with 2 extra sentences, that results in the earlier cluster disappearing.

![image](https://user-images.githubusercontent.com/59828210/110619195-ce880e80-8197-11eb-970a-5bceb1327f55.png)

Is there any way to retain all clusters the model would find even for longer pieces of text?

</p>
</details>

## Related issues or possible duplicates

- None

## Environment

OS: MacOS

Python version: 3.6

**Comment by dirkgr** [comment]
In general, we cannot guarantee that a longer text always produces a strict superset of clusters compared to a shorter text.

Imagine the following text: "I am very happy here. The city is sunny." You would expect that "here" and "the city" cluster together.

But what if I add text? "I am very happy here. The city is sunny. But I enjoy the countryside more." Now you would expect "here" and "countryside" to cluster.

The coref model considers the whole paragraph at once, so if you change the paragraph in any way, in principle the output can change completely.
