### ISSUE TITLE
from_pretrained_transformer not called in commnad line predict mode with BasicClassifier

### ISSUE THREAD

**Issue by McKracken** [allenai/allennlp#5055]
## Checklist

- [X] I have verified that the issue exists against the `master` branch of AllenNLP.
- [X] I have read the relevant section in the [contribution guide](https://github.com/allenai/allennlp/blob/master/CONTRIBUTING.md#bug-fixes-and-new-features) on reporting bugs.
- [X] I have checked the [issues list](https://github.com/allenai/allennlp/issues) for similar or identical bug reports.
- [X] I have checked the [pull requests list](https://github.com/allenai/allennlp/pulls) for existing proposed fixes.
- [X] I have checked the [CHANGELOG](https://github.com/allenai/allennlp/blob/master/CHANGELOG.md) and the [commit log](https://github.com/allenai/allennlp/commits/master) to find out if the bug was already fixed in the master branch.
- [X] I have included in the "Description" section below a traceback from any exceptions related to this bug.
- [X] I have included in the "Related issues or possible duplicates" section below all related issues and possible duplicate issues (If there are none, check this box anyway).
- [X] I have included in the "Environment" section below the name of the operating system and Python version that I was using when I discovered this bug.
- [X] I have included in the "Environment" section below the output of `pip freeze`.
- [X] I have included in the "Steps to reproduce" section below a minimally reproducible example.

## Description

Hi, I'm running a very basic text classification experiment with pretrained  transformers as embeddings. I implemented only a very basic the data reader and wrote the config file (see 'steps to reproduce'). I run everything from command line, `allennlp train`, `evaluate` and `predict`. `train` and `evaluate` work like a charm, while I get a `KeyError` exception when running the `predict` command. The error seems to be caused by the absence of the `tokens.txt` entry in the `vocabulary` folder of the trained model, which makes the namespace 'tokens' not to be present in the `vocab`, when called in `make_output_human_readable` of the `BasicClassifier`. The only namespaces available there are `labels` and `tags`.

The command I run is

```
allennlp predict experiments/bert_train__max_512__batch_16/model.tar.gz data/test.jsonl --include-package my_allennlp_pkg --cuda-device 3 --batch-size 8 --output-file test --use-dataset-reader
```

Traceback

<details>
<summary><b>Python traceback:</b></summary>
<p>

```
Traceback (most recent call last):
  File "/path/to/my/env/env/allen210/bin/allennlp", line 8, in <module>
    sys.exit(run())
  File "/path/to/my/env/env/allen210/lib/python3.8/site-packages/allennlp/__main__.py", line 34, in run
    main(prog="allennlp")
  File "/path/to/my/env/env/allen210/lib/python3.8/site-packages/allennlp/commands/__init__.py", line 119, in main
    args.func(args)
  File "/path/to/my/env/env/allen210/lib/python3.8/site-packages/allennlp/commands/predict.py", line 239, in _predict
    manager.run()
  File "/path/to/my/env/env/allen210/lib/python3.8/site-packages/allennlp/commands/predict.py", line 206, in run
    for model_input_instance, result in zip(batch, self._predict_instances(batch)):
  File "/path/to/my/env/env/allen210/lib/python3.8/site-packages/allennlp/commands/predict.py", line 167, in _predict_instances
    results = self._predictor.predict_batch_instance(batch_data)
  File "/path/to/my/env/env/allen210/lib/python3.8/site-packages/allennlp/predictors/predictor.py", line 296, in predict_batch_instance
    outputs = self._model.forward_on_instances(instances)
  File "/path/to/my/env/env/allen210/lib/python3.8/site-packages/allennlp/models/model.py", line 185, in forward_on_instances
    outputs = self.make_output_human_readable(self(**model_input))
  File "/path/to/my/env/env/allen210/lib/python3.8/site-packages/allennlp/models/basic_classifier.py", line 166, in make_output_human_readable
    [
  File "/path/to/my/env/env/allen210/lib/python3.8/site-packages/allennlp/models/basic_classifier.py", line 167, in <listcomp>
    self.vocab.get_token_from_index(token_id.item(), namespace=self._namespace)
  File "/path/to/my/env/env/allen210/lib/python3.8/site-packages/allennlp/data/vocabulary.py", line 737, in get_token_from_index
    return self._index_to_token[namespace][index]
KeyError: 101
```

</p>
</details>

In general, it seems like when running `allennlp predict` without specifying a predictor it does not read the pretrained model vocabulary inside the vocab object (thus not generating the namespace), or something similar.

### Attempted solutions
1. I tried inserting a vocabulary entry in the config as suggested in [4690](https://github.com/allenai/allennlp/issues/4690), re-creating the `model.tar.gz` with the so updated config file, but nothing changed.
```
"vocabulary": {
     "type": "from_pretrained_transformer",
     "model_name": "bart-base-cased"
}
```
2. I downloaded the `bert-base-cased` vocab from huggingface [here](https://huggingface.co/bert-base-cased/raw/main/vocab.txt) inside the `vocabulary` folder, named it `tokens.txt`, and re-created the `model.tar.gz` with this new `vocabulary` dir. The error changed to 

<details>
<summary><b>Python traceback:</b></summary>
<p>

```
Traceback (most recent call last):
  File "/path/to/my/env//allen210/bin/allennlp", line 8, in <module>
    sys.exit(run())
  File "/path/to/my/env/env/allen210/lib/python3.8/site-packages/allennlp/__main__.py", line 34, in run
    main(prog="allennlp")
  File "/path/to/my/env/env/allen210/lib/python3.8/site-packages/allennlp/commands/__init__.py", line 119, in main
    args.func(args)
  File "/path/to/my/env/env/allen210/lib/python3.8/site-packages/allennlp/commands/predict.py", line 224, in _predict
    predictor = _get_predictor(args)
  File "/path/to/my/env/env/allen210/lib/python3.8/site-packages/allennlp/commands/predict.py", line 115, in _get_predictor
    archive = load_archive(
  File "/path/to/my/env/env/allen210/lib/python3.8/site-packages/allennlp/models/archival.py", line 208, in load_archive
    model = _load_model(config.duplicate(), weights_path, serialization_dir, cuda_device)
  File "/path/to/my/env/env/allen210/lib/python3.8/site-packages/allennlp/models/archival.py", line 242, in _load_model
    return Model.load(
  File "/path/to/my/env/env/allen210/lib/python3.8/site-packages/allennlp/models/model.py", line 406, in load
    return model_class._load(config, serialization_dir, weights_file, cuda_device)
  File "/path/to/my/env/env/allen210/lib/python3.8/site-packages/allennlp/models/model.py", line 293, in _load
    vocab = vocab_class.from_files(
  File "/path/to/my/env/env/allen210/lib/python3.8/site-packages/allennlp/data/vocabulary.py", line 383, in from_files
    vocab.set_from_file(filename, is_padded, namespace=namespace, oov_token=oov_token)
  File "/path/to/my/env/env/allen210/lib/python3.8/site-packages/allennlp/data/vocabulary.py", line 511, in set_from_file
    assert self._oov_token in self._token_to_index[namespace], "OOV token not found!"
AssertionError: OOV token not found!
```

</p>
</details>

which I suppose is due to the absence of the `@@UNKNOWN@@`  token in the vocab. Inserting that token at the beginning or end of the said `tokens.txt` vocabulary would make the predict command to work, but I could notice a clear misalignment in the index-to-token conversion.

## Related issues or possible duplicates
This may be related to the general issues (partly solved) about loading a vocab from a pretrained (transformer) model, like in [4973](https://github.com/allenai/allennlp/issues/4937), [4958](https://github.com/allenai/allennlp/pull/4958), [4690](https://github.com/allenai/allennlp/issues/4690), [3456](https://github.com/allenai/allennlp/issues/3456)

## Environment

OS: Linux 3.10.0-1127.19.1.el7.x86_64

Python version: 3.8.8

<details>
<summary><b>Output of <code>pip freeze</code>:</b></summary>
<p>

```
absl-py @ file:///home/conda/feedstock_root/build_artifacts/absl-py_1615404881292/work
aiohttp @ file:///home/conda/feedstock_root/build_artifacts/aiohttp_1605734406386/work
allennlp==2.1.0
argon2-cffi==20.1.0
async-generator==1.10
async-timeout==3.0.1
attrs @ file:///home/conda/feedstock_root/build_artifacts/attrs_1605083924122/work
backcall==0.2.0
bleach==3.3.0
blinker==1.4
blis==0.7.4
boto3==1.17.25
botocore==1.20.25
brotlipy==0.7.0
cachetools @ file:///home/conda/feedstock_root/build_artifacts/cachetools_1611555765219/work
catalogue==2.0.1
certifi==2020.12.5
cffi @ file:///tmp/build/80754af9/cffi_1613246945912/work
chardet==4.0.0
click==7.1.2
cryptography @ file:///home/conda/feedstock_root/build_artifacts/cryptography_1615405999564/work
cymem==2.0.5
decorator==4.4.2
defusedxml==0.7.1
entrypoints==0.3
filelock==3.0.12
google-auth @ file:///home/conda/feedstock_root/build_artifacts/google-auth_1608136875028/work
google-auth-oauthlib==0.4.1
grpcio @ file:///home/conda/feedstock_root/build_artifacts/grpcio_1604365522020/work
h5py==3.2.1
idna @ file:///home/conda/feedstock_root/build_artifacts/idna_1593328102638/work
importlib-metadata @ file:///home/conda/feedstock_root/build_artifacts/importlib-metadata_1615169443604/work
iniconfig==1.1.1
ipykernel==5.5.0
ipython==7.21.0
ipython-genutils==0.2.0
ipywidgets==7.6.3
jedi==0.18.0
Jinja2==2.11.3
jmespath==0.10.0
joblib==1.0.1
jsonlines==2.0.0
jsonnet==0.17.0
jsonpickle==2.0.0
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==6.1.11
jupyter-console==6.2.0
jupyter-core==4.7.1
jupyterlab-pygments==0.1.2
jupyterlab-widgets==1.0.0
lmdb==1.1.1
Markdown @ file:///home/conda/feedstock_root/build_artifacts/markdown_1614595805172/work
MarkupSafe==1.1.1
mistune==0.8.4
more-itertools==8.7.0
multidict @ file:///home/conda/feedstock_root/build_artifacts/multidict_1602413132207/work
murmurhash==1.0.5
nbclient==0.5.3
nbconvert==6.0.7
nbformat==5.1.2
nest-asyncio==1.5.1
nltk==3.5
notebook==6.2.0
numpy==1.20.1
oauthlib==3.0.1
overrides==3.1.0
packaging==20.9
pandas==1.2.3
pandocfilters==1.4.3
parso==0.8.1
pathy==0.4.0
pexpect==4.8.0
pickleshare==0.7.5
Pillow==8.1.2
pluggy==0.13.1
preshed==3.0.5
prometheus-client==0.9.0
prompt-toolkit==3.0.17
protobuf==3.15.5
ptyprocess==0.7.0
py==1.10.0
pyasn1==0.4.8
pyasn1-modules==0.2.7
pycparser @ file:///home/conda/feedstock_root/build_artifacts/pycparser_1593275161868/work
pydantic==1.7.3
Pygments==2.8.1
PyJWT @ file:///home/conda/feedstock_root/build_artifacts/pyjwt_1610910308735/work
pyOpenSSL @ file:///home/conda/feedstock_root/build_artifacts/pyopenssl_1608055815057/work
pyparsing==2.4.7
pyrsistent==0.17.3
PySocks @ file:///home/conda/feedstock_root/build_artifacts/pysocks_1610291447907/work
pytest==6.2.2
python-dateutil==2.8.1
pytz==2021.1
pyzmq==22.0.3
qtconsole==5.0.2
QtPy==1.9.0
regex==2020.11.13
requests @ file:///home/conda/feedstock_root/build_artifacts/requests_1608156231189/work
requests-oauthlib @ file:///home/conda/feedstock_root/build_artifacts/requests-oauthlib_1595492159598/work
rsa @ file:///home/conda/feedstock_root/build_artifacts/rsa_1614171254180/work
s3transfer==0.3.4
sacremoses==0.0.43
scikit-learn==0.24.1
scipy==1.6.1
Send2Trash==1.5.0
sentencepiece==0.1.95
six @ file:///home/conda/feedstock_root/build_artifacts/six_1590081179328/work
smart-open==3.0.0
spacy==3.0.5
spacy-legacy==3.0.1
srsly==2.4.0
tensorboard @ file:///home/conda/feedstock_root/build_artifacts/tensorboard_1610699261066/work/tensorboard-2.4.1-py3-none-any.whl
tensorboard-plugin-wit @ file:///home/conda/feedstock_root/build_artifacts/tensorboard-plugin-wit_1611075653546/work/tensorboard_plugin_wit-1.8.0-py3-none-any.whl
tensorboardX==2.1
terminado==0.9.2
testpath==0.4.4
thinc==8.0.2
threadpoolctl==2.1.0
tokenizers==0.10.1
toml==0.10.2
torch==1.7.1
torchvision==0.8.2
tornado==6.1
tqdm==4.59.0
traitlets==5.0.5
transformers==4.3.3
typer==0.3.2
typing-extensions @ file:///home/conda/feedstock_root/build_artifacts/typing_extensions_1602702424206/work
urllib3 @ file:///home/conda/feedstock_root/build_artifacts/urllib3_1611695416663/work
wasabi==0.8.2
wcwidth==0.2.5
webencodings==0.5.1
Werkzeug==1.0.1
widgetsnbextension==3.5.1
yarl @ file:///home/conda/feedstock_root/build_artifacts/yarl_1605429457708/work
zipp @ file:///home/conda/feedstock_root/build_artifacts/zipp_1614945704755/work
```

</p>
</details>

## Steps to reproduce

<details>
<summary><b>Example source:</b></summary>
<p>

I have a very basic data reader 
```
@DatasetReader.register("case_description")
class CaseDescriptionReader(DatasetReader):
    def __init__(
        self,
        label: str,
        token_indexers: Dict[str, TokenIndexer] = None,
        tokenizer: Optional[Tokenizer] = None,
        max_instances: Optional[int] = None,
        serialization_dir: Optional[str] = None
    ) -> None:
        super().__init__(max_instances=max_instances, serialization_dir=serialization_dir)
        self._token_indexers = token_indexers or {"tokens": SingleIdTokenIndexer()}
        self._tokenizer = tokenizer
        self._label = label

    @overrides
    def _read(self, file_path):
        tot_skipped = 0
        if file_path.endswith(".jsonl"):
            with jsonlines.open(file_path) as reader:
                for i, doc in enumerate(reader):
                    instance = self.text_to_instance(text=doc["caseDescription"],
                                                                          label=doc[self._label])
                    if instance is not None:
                        yield instance

    @overrides
    def text_to_instance(self, text: str, label: str) -> Optional[Instance]:
        if not self._tokenizer:
            tokens = text.split(" ")
            tokens = [Token(t) for t in tokens]
        else:
            tokens = self._tokenizer.tokenize(text)
        text_field = TextField(tokens)
        fields: Dict[str, Field] = {"tokens": text_field, "label": LabelField(label)}
        return Instance(fields)

    @overrides
    def apply_token_indexers(self, instance: Instance) -> None:
        instance.fields["tokens"]._token_indexers = self._token_indexers  # type: ignore
```

and my config file is as follow

```
{
  "dataset_reader": {
    "type": "case_description",
    "label": "label",
    "token_indexers": {
      "tokens": {
        "type": "pretrained_transformer",
        "model_name": "bert-base-cased"
      }
    },
    "tokenizer": {
      "type": "pretrained_transformer",
      "model_name": "bert-base-cased",
      "max_length": 512
    }
  },
  "train_data_path": "data/splits_no_material/train.jsonl",
  "validation_data_path": "data/splits_no_material/val.jsonl",

  "model": {
    "type": "basic_classifier",
    "text_field_embedder": {
      "token_embedders": {
        "tokens": {
          "type": "pretrained_transformer",
          "model_name": "bert-base-cased",
          "train_parameters": true
        }
      }
    },
    "seq2vec_encoder": {
      "type": "bert_pooler",
      "pretrained_model": "bert-base-cased",
      "dropout": 0.1
    }
  },

  "data_loader": {
    "type": "multiprocess",
    "batch_size": 16
  },

  "trainer": {
       ...some trainer specs...
  }
}
```

my dataset is a `jsonl` with lines like

```
{"caseDescription": "xxxxxxxx", "label": "yyyyyy"}
```

</p>
</details>

**Comment by wlhgtc** [comment]
Maybe more details about the error would help.
I guess you only change the config (like `xxx.jsonnet`), but you use the config file in `xx.tar.gz`. 
So your changes doesn't work. The simple way is re-train your model with new config.

**Comment by McKracken** [comment]
So, it's a basic text classification task, and given the class and config file in Step to reproduce:
1. I train a model via command line with `allennlp predict experiments/bert_train__max_512__batch_16/model.tar.gz data/test.jsonl --include-package my_allennlp_pkg -f`. Model trains without problem. Please note that the token indexer used (and the tokenizer) comes from a pre-trained model (`bert-base-cased` in this case). The result of this is that no `tokens.txt` vocabulary is saved into the `vocabulary` directory of my model experiment dir, as also reported in some of the issues I reported above (basically I do not explicitly create a `tokens` namespace in my vocab). This is the AllenNLP behaviour.
2. When I run `predict` from command line (`allennlp predict experiments/bert_train__max_512__batch_16/model.tar.gz data/test.jsonl --include-package my_allennlp_pkg --batch-size 8 --output-file test --use-dataset-reader
`), I get the `KeyError` reported above. It comes from the `make_output_human_readable` method of the `BasicClassifier`, which try to access the default namespace=`tokens` in the loaded vocabulary. The problem I see is that in my training, I have a namespace for `tokens`, indexed with an indexer coming from a pre-trained model, but, as reported above, no corresponding vocabulary entry and therefore no `tokens.txt` in `vocabulary` dir. At prediction time this namespace does not exist anymore, because the basic behaviour of the `predict` reads only the vocabularies in the `vocabulary` folder, and do not consider any vocabulary of pre-trained model, even if these are specified in the config file (through some pre-trained indexers). At least if the `make_output_human_readable` behaviour has to stay the same.

Probably the `predict` should call the `from_pretrained_transformer` method on the vocabulary it is creating, when a 'pretrained indexer' is found in the config file.

@wlhgtc When I tried solution 1 (changing the config), I re-created the `model.tar.gz` with the new configuration, and passed that new `model.tar.gz` to the command line. 
When I tried solution 2, I did the same, that is re-creating a `model.tar.gz` with the `vocaboulary` folder updated with the `tokens.txt` file. (I corrected the description)

**Comment by wlhgtc** [comment]
We don't save the vocab to tokens.txt.
The Vocabulary class is initialized by code in [here](https://github.com/allenai/allennlp/blob/main/allennlp/data/vocabulary.py#L263)
Can you provide your jsonnet config and a full stack trace about your error.

**Comment by McKracken** [comment]
I think I already reported these in my initial description, under the `Python traceback` and `Example source` items (which need to be expanded). I don't know if you're referring to something more than what I already reported, in which case what do you need more than that?

<img width="949" alt="Screenshot 2021-03-18 at 15 50 16" src="https://user-images.githubusercontent.com/7049505/111646290-cf591a00-8801-11eb-9484-d9dfa21d4576.png">
<img width="800" alt="Screenshot 2021-03-18 at 15 50 48" src="https://user-images.githubusercontent.com/7049505/111646351-dbdd7280-8801-11eb-935c-210048ba51d3.png">

**Comment by wlhgtc** [comment]
Sorry for my reckless, I would reply later.

**Comment by wlhgtc** [comment]
@McKracken  I re-produce your error, the reason you missed a name space param in `token_indexers`, it should be :
``` python
"token_indexers": {
    "tokens": {
        "type": "pretrained_transformer",
        "model_name": model_name,
        "namespace":"tokens" # the param you missed
    }
```
Case it has a default value "tags"(the code could be found in [here](https://github.com/allenai/allennlp/blob/main/allennlp/data/token_indexers/pretrained_transformer_indexer.py#L31)), but your model has a namespace `token`, here are the code trace:
<img width="949" alt="截屏2021-03-19 12 55 55" src="https://user-images.githubusercontent.com/16603773/111733513-0b988300-88b3-11eb-92b4-5bb3afcd13de.png">

You could add it and retry, it works on my env.

**Comment by McKracken** [comment]
@wlhgtc Yes, this solved the issue. Sorry, I completely missed that namespace.
It actually worked also by only adding the `namespace` field to my old `config.json`, and re-tarring `config.json`, `weights.th` and `vocabulary/` into `model.tar.gz`.
Thanks!
