### ISSUE TITLE
When using`Trainer`, is it possible to pass additional arguments to `forward` of the model trained?

### ISSUE THREAD

**Issue by tarohi24** [allenai/allennlp#5058]
I'm using `allennlp_models.tagging.models.crf_tagger.CrfTagger`. Its `forward` function accepts the `ignore_loss_on_o_tags` option, and I want to set it. However, `GradientDescentTrainer` doesn't seem to have an option to pass such arguments. Should I create a subclass of `CrfTagger` to set it, or is there another way?

Thanks,

**Comment by wlhgtc** [comment]
Cause these parameters comes from dataset reader,  maybe it would vary from different batches ?

**Comment by tarohi24** [comment]
For example, `Conll2003DatasetReader` doesn't provide the potion.
And I think handling such training parameters is out of scope of `DatasetReader`.
Then I'll make a PR for adding a model param. Thanks @wlhgtc !
