### ISSUE TITLE
New point release?

### ISSUE THREAD

**Issue by nelson-liu** [allenai/allennlp#5062]
Hi! Do you think it'd be possible to get a new point release sometime soon (I'm aware that I can install from master, but it's been awhile since the last release)? Sorry if this is already on the radar, just thought I'd check in.

Thanks!

**Comment by epwalsh** [comment]
Yeup! We'll do one next week, I'm hoping to get the Weights & Biases integration finished first (https://github.com/allenai/allennlp/pull/5061)

**Comment by nelson-liu** [comment]
yay, great to hear!
