### ISSUE TITLE
Training state of last epoch not saved due to early stopping

### ISSUE THREAD

**Issue by alanwang93** [allenai/allennlp#5067]
`trainer.py` line 1006 will break the loop, and `dump_metrics` on line 1030 & `save_checkpoint` on line 1043 are skipped.

```python
this_epoch_val_metric = self._metric_tracker.combined_score(val_metrics)                    self._metric_tracker.add_metrics(val_metrics)
if self._metric_tracker.should_stop_early():
   logger.info("Ran out of patience.  Stopping training.")
   break
```

**Comment by dirkgr** [comment]
We will need to fix #5088 before looking into this. They are separate issues, but touching one often involves touching the other.

It's also probably a good idea to resolve #5076/#5077 first. These might turn out to be the same issue.
