### ISSUE TITLE
How to write the config file for pair classification model in AllenNLP git repo?

### ISSUE THREAD

**Issue by coco-pa** [allenai/allennlp#5068]
I'm trying to run the [pair classification model in AllenNLP repo][1] via config file. 

It is appreciated that the repo gives sample of datareader and model file. But without a corresponding config file, I cannot really run the model. 

The [example config file of simpleclassification model][2] does't describe enough detailed parameters for pair classification config.

How should write the config file for pair classification? Is there a generic method or systematic tutorial to do so? Any help is appreciated. THX.

Ps. I also post the question on stackoverflow [here][3].

  [1]: https://github.com/allenai/allennlp-models/tree/main/allennlp_models/pair_classification
  [2]: https://guide.allennlp.org/training-and-prediction#2
  [3]: https://stackoverflow.com/questions/66809952/how-to-write-the-config-file-for-pair-classification-model-in-allennlp-git-repo

**Comment by AkshitaB** [comment]
@coco-pa Sample config files for pair classification models can be found here: https://github.com/allenai/allennlp-models/tree/main/training_config/pair_classification
