### ISSUE TITLE
How to use multi GPU to speed up model prediction

### ISSUE THREAD

**Issue by gaozhiguang** [allenai/allennlp#5072]
When i was trying to use the "AllenNLP demo--Semantic Role Labeling", Because we have to deal with a large amount of data, I would like to ask how to use multi GPU to speed up the processing speed.
how can i fix the code follows:

```
from allennlp.predictors.predictor import Predictor
import allennlp_models.tagging

predictor = Predictor.from_path("https://storage.googleapis.com/allennlp-public-models/structured-prediction-srl-bert.2020.12.15.tar.gz")
predictor.predict(
    sentence="Did Uriah honestly think he could beat the game in under three hours?."
)
```

**Comment by dirkgr** [comment]
If all you want to do is inference, just start one process per GPU. You can tell each process which GPU to use by setting the environment variable `CUDA_VISIBLE_DEVICES`.

**Comment by gaozhiguang** [comment]
Hi，thanks your advice，when i run with the GPU, there is such a phenomenon that GPU occupies a lot of memory, but the utilization rate is 0, Is this normal? @dirkgr 
![image](https://user-images.githubusercontent.com/34132216/113397175-36b0c580-93cf-11eb-949f-167f702e6270.png)

**Comment by ksteimel** [comment]
How much data is in batch_input when you feed it through? It may be predicting so fast that you don't even get a chance to see the utilization jump.

**Comment by gaozhiguang** [comment]
actually ， the batch size is about 20 ，when i set a timer to record the prediction time of GPU, I found that it took almost 100 times as long to execute as the CPU, the specific value is about 0.16 seconds for CPU and 16 seconds for GPU. So , i think it's not because the process running in cpu Slow down the overall speed. Maybe i didn't use the GPU rightly. 
Thanks your advice. @ksteimel

**Comment by houliangxue** [comment]
> actually ， the batch size is about 20 ，when i set a timer to record the prediction time of GPU, I found that it took almost 100 times as long to execute as the CPU, the specific value is about 0.16 seconds for CPU and 16 seconds for GPU. So , i think it's not because the process running in cpu Slow down the overall speed. Maybe i didn't use the GPU rightly. Thanks your advice. @ksteimel

请问你是怎么解决的
