### ISSUE TITLE
How to use GPU for allennlp-demo

### ISSUE THREAD

**Issue by gaozhiguang** [allenai/allennlp#5086]
Hi, when i was trying to use the demo“https://demo.allennlp.org/semantic-role-labeling” ， it is a little slow , maybe it uses the cpu , how can i use gpu to run the demo.

**Comment by dirkgr** [comment]
Most of our demo runs on CPU because it is too expensive to keep the GPUs running all the time just to make a prediction every now and then. If you want to use the SRL model in a production setting, at scale, I recommend you run it yourself, on your own hardware.
