### ISSUE TITLE
Cannot import allennlp into jupyter

### ISSUE THREAD

**Issue by HillelR** [allenai/allennlp#5094]
Hi,
I am trying to learn AllenNLP, I have read a few tutorials (would love additional recs) and am ready to start coding. 
For some reason I am not able to import allennlp - before any of the libraries (which won't import either, naturally).  
I have pip installed it via the terminal (on a mac), and also tried using anaconda, with no success.  
Any ideas?

**Comment by epwalsh** [comment]
Hi, can you post the output of `pip freeze`?

**Comment by HillelR** [comment]
Here it is, thanks! 
pip freeze
allennlp==2.2.0
attrs==20.3.0
blis==0.7.4
boto3==1.17.44
botocore==1.20.44
cached-property==1.5.2
catalogue==2.0.1
certifi==2020.12.5
chardet==4.0.0
click==7.1.2
configparser==5.0.2
cymem==2.0.5
docker-pycreds==0.4.0
filelock==3.0.12
gitdb==4.0.7
GitPython==3.1.14
h5py==3.2.1
idna==2.10
importlib-metadata==3.10.0
iniconfig==1.1.1
Jinja2==2.11.3
jmespath==0.10.0
joblib==1.0.1
jsonnet==0.17.0
jsonpickle==2.0.0
lmdb==1.1.1
MarkupSafe==1.1.1
more-itertools==8.7.0
murmurhash==1.0.5
nltk==3.5
numpy==1.20.2
overrides==3.1.0
packaging==20.9
pathtools==0.1.2
pathy==0.4.0
Pillow==8.2.0
pluggy==0.13.1
preshed==3.0.5
promise==2.3
protobuf==3.15.7
psutil==5.8.0
py==1.10.0
pydantic==1.7.3
pyparsing==2.4.7
pytest==6.2.3
python-dateutil==2.8.1
PyYAML==5.4.1
regex==2021.3.17
requests==2.25.1
s3transfer==0.3.6
sacremoses==0.0.44
scikit-learn==0.24.1
scipy==1.6.2
sentencepiece==0.1.95
sentry-sdk==1.0.0
shortuuid==1.0.1
six==1.15.0
smart-open==3.0.0
smmap==4.0.0
spacy==3.0.5
spacy-legacy==3.0.2
srsly==2.4.0
subprocess32==3.5.4
tabulate==0.8.7
tensorboardX==2.2
thinc==8.0.2
threadpoolctl==2.1.0
tokenizers==0.10.1
toml==0.10.2
torch==1.8.1
torchvision==0.9.1
tqdm==4.59.0
transformers==4.4.2
typer==0.3.2
typing-extensions==3.7.4.3
urllib3==1.26.4
wandb==0.10.24
wasabi==0.8.2
zipp==3.4.1

**Comment by epwalsh** [comment]
Thanks @HillelR, and could also post the exact error message you're getting? I'm having trouble reproducing.

**Comment by HillelR** [comment]
@epwalsh thanks for your help.
Actually there is no error message - it is just not recognizing the package and hence not importing:
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-6-847c9b0e2967> in <module>
----> 1 import allennlp

ModuleNotFoundError: No module named 'allennlp'

**Comment by epwalsh** [comment]
This sounds like Jupyter is running in a different Python environment. To confirm this, you could run

```python
import site; print(site.getsitepackages())
```

from inside and outside of Jupyter.

**Comment by HillelR** [comment]
@epwalsh I think you are right.  it seems that allennlp was installed in a different env.  

base                  *  /Applications/Anaconda/anaconda3
allennlp                 /Applications/Anaconda/anaconda3/envs/allennlp

Any help on how do I manage these paths?

**Comment by epwalsh** [comment]
It looks like you don't have `jupyter` installed to your `allennlp` environment? That might explain it.

**Comment by HillelR** [comment]
oy, how do I ensure that I install them in the same environment?  
or simply, how do I install Jupyter in that environment?
Thanks a lot @epwalsh !

**Comment by epwalsh** [comment]
Something like this should work:

```
conda activate allennlp
pip install jupyter
```
