### ISSUE TITLE
OK to fork the CRF ? 

### ISSUE THREAD

**Issue by talolard** [allenai/allennlp#5101]
Hi,
The CRF implementation in AllenNLP is really good (as is the rest of the framework). I find myself using it often, though I don't use the rest of the framework as much. 
Would it be ok to extract the CRF as a separate repo/package ?

**Comment by dirkgr** [comment]
Yes, no problem. People do this sort of thing all the time. That's why it's open source :-)

**Comment by talolard** [comment]
Cool.
It's [here](https://github.com/lighttag/allencrf) or 
> pip install allencrf
