### ISSUE TITLE
Load pre-trained transformer weights once

### ISSUE THREAD

**Issue by alanwang93** [allenai/allennlp#5107]
I trained a model which has a `PretrainedTransformerEmbedder`, the dumped weight file contains fine-tuned BERT's parameters.
When I tried to rebuild the model and restore weights, I found that the initialization of embedder requires `model_name` argument and therefore the `pytorch_model.bin` file. If I would like to deploy the model, I need to pack the model's weights as well as a pretrained BERT weight, which is 2X size.

**Comment by epwalsh** [comment]
I think this is a duplicate of https://github.com/allenai/allennlp/issues/4599.
