### ISSUE TITLE
Inconsistent case in `predict` command

### ISSUE THREAD

**Issue by kmkurn** [allenai/allennlp#511]
Hi, this is a really minor issue. The `predict` command accepts `--output-file` optional argument, written in kebab-case. This is inconsistent with the other optional arguments which use snake_case (e.g. `--batch_size` or `--cuda_device`). Also, the metavar for `input-file` argument is also in kebab-case while others are in snake_case.

**Comment by joelgrus** [comment]
yes, this bugs me too, let me think about whether there's a way to fix this that doesn't break backward compatibility

**Comment by joelgrus** [comment]
closed via https://github.com/allenai/allennlp/pull/512

thanks for the suggestion
