### ISSUE TITLE
Length penalty for nn.beam_search.BeamSearch

### ISSUE THREAD

**Issue by nicola-decao** [allenai/allennlp#5113]
I see that in `nn.beam_search.BeamSearch` there is no way to specify the length penalty. How is implemented now? Is it using length penalty or not?

I imagine that the desiderata should be to use a simple penalty but I cannot understand from the code if that is the case.

**Comment by epwalsh** [comment]
There is not a length penalty at the moment, but this option would be a welcome addition to the library.
