### ISSUE TITLE
HuggingFace Tokenizers and multiprocess worker parallelism warnings

### ISSUE THREAD

**Issue by nelson-liu** [allenai/allennlp#5128]
If i use a multiprocess worker, i get the following warning when loading my data:

```
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
```

My dataloader config looks like:
```
  "data_loader": {
    "batch_sampler": {
      "type": "bucket",
      "batch_size" : 8,
    },
    "num_workers": 4
  },
```

and I'm using a pretrained transformer tokenizer like so:
```
    "tokenizer": {
      "type": "pretrained_transformer",
      "model_name": transformer_model,
      "add_special_tokens": false,
      "max_length": 128
    },
```

**Comment by wlhgtc** [comment]
Maybe this would help:https://github.com/allenai/allennlp/discussions/4933#discussioncomment-317224.

**Comment by epwalsh** [comment]
It's safe to ignore that warning, but as I said in the thread @wlhgtc linked to, I would recommend just disabling parallelism in tokenizers (by setting the environment variable `TOKENIZERS_PARALLELISM` to `"false"`). In the benchmarks I ran that actually speed things up.

But if you really do want parallelism in the tokenizers lib, you can set "data_loader.start_method" to "spawn".
