### ISSUE TITLE
Coreference Resolution Model - Long sequence

### ISSUE THREAD

**Issue by aakashb95** [allenai/allennlp#5131]
Thank you for such a wonderful tool for coreference resolution!
I have been testing your coreference resolution implementation on different texts of varied lengths of around 5000+ words and coreferences are being identified and resolved. How does this work? If my understanding is right, SpanBERT works only till 512 tokens right?
Are we using [sliding window](https://github.com/allenai/allennlp/pull/2537) for embedding here as well?

P.S. I am new in this domain and trying to understand how coreference resolution works under the hood.

**Comment by dirkgr** [comment]
The trick is in `PretrainedTransformerMismatchedIndexer` and `PretrainedTransformerMismatchedEmbedder`: http://docs.allennlp.org/main/api/data/token_indexers/pretrained_transformer_mismatched_indexer/#pretrainedtransformermismatchedindexer. Look for the `max_length` parameter. It looks like it will just cut the sequence into sub-sequences of 512 tokens each. The documentation doesn't say anything about sliding windows. The ultimate source of truth will be the code in those two classes :-)

**Comment by KawshikManikantan** [comment]
Does anyone know how this exactly works? @aakashb95 @dirkgr

**Comment by dirkgr** [comment]
How what works? The indexer/embedder? SpanBERT? The coref model? There are people who know how all of these work.
