### ISSUE TITLE
Refactoring span extractors to fix wrong span width calculation and unify forward arguments

### ISSUE THREAD

**Issue by izhx** [allenai/allennlp#5145]
**Is your feature request related to a problem? Please describe.**
1. The calculated span widths (by `span_ends - span_starts`) in `EndpointSpanExtractor.forward` and `BidirectionalEndpointSpanExtractor.forward` are always 1 less than the real width since the `SpanField` use inclusive indices. (e.g., the width of the span `(2, 2)` will be `2 - 2 = 0` by `span_end - span_start`, but it is 1 actually). Is my understanding correct?

2. The argument `sequence_mask` is missing in `SelfAttentiveSpanExtractor.forward` but exists in `EndpointSpanExtractor.forward` and `BidirectionalEndpointSpanExtractor.forward` (although it is use only in `BidirectionalEndpointSpanExtractor`). The removing of `sequence_mask` in `SelfAttentiveSpanExtractor.forward` brings an arguments mismatching problem in the following code.

```
extractors = [
    EndpointSpanExtractor(), SelfAttentiveSpanExtractor(), 
    BidirectionalEndpointSpanExtractor()
]
embeddings = [
    extractor(sequence_tensor, span_indices, sequence_mask, span_indices_mask)
    for extractor in extractors
]
```

3. Just curious, why `SelfAttentiveSpanExtractor` does not have span width embeddings?

**Describe the solution you'd like**
I suggest adding a `__init__` method to `SpanExtractor` for initiating `span_width_embedding` and other attributes, and adding a `_combine_span_width_embeddings` (maybe) method to `SpanExtractor` to calculate the correct span widths, as well as embed and combine them to the span embeddings.

In this way, `SelfAttentiveSpanExtractor`, `EndpointSpanExtractor` and `BidirectionalEndpointSpanExtractor` only need to call the `_combine_span_width_embeddings` method without writing redundant code in their `__init__` and `forward`.

**Describe alternatives you've considered**
I have finished a part of the refactoring of these span extractors in [this repo](https://github.com/izhx/allennlpadd/blob/main/modules/span_extractors/) and used them in my research.
It would be great if these changes could be merged into allennlp.

**Additional context**
Do you have any ideas and suggestions? I am willing to make a PR.

**Comment by dirkgr** [comment]
I would love to have these changes in AllenNLP, as long as they don't affect the performance of the original SpanBERT coref model. Feel free to tag me in the PR!

Out of curiosity, there is a lot of interest in our coref model lately. Any particular reason?

**Comment by izhx** [comment]
I figured out why `span_ends - span_starts`. Since the embedding matrix is zero-indexed and initiated with `num_width_embeddings=max_span_width`. I'm being silly...

I think these changes will not affect the performance of the original SpanBERT coref model and will test it.

It is probably becoming a latest hotspot? 🤣
I'm just working on a research project similar to information extraction and coref.
