### ISSUE TITLE
cached_path should handle "gs://" (Google Cloud Storage) URLs just like it does for "s3://" or "hf://"

### ISSUE THREAD

**Issue by epwalsh** [allenai/allennlp#5150]
We could utilize https://github.com/googleapis/python-storage to make this robust.

**Comment by jmelot** [comment]
Newbie here, but this looks pretty straightforward - I'd like to implement this! Could take a look this week.

**Comment by epwalsh** [comment]
That would be great @jmelot!

**Comment by AbhijayJ** [comment]
Hey I would like to help in this if it hasn't been resolved yet

**Comment by jmelot** [comment]
Hey @AbhijayJ, I actually have some time blocked out to try and finish up on this this afternoon, but if I run out of time and need to hand it off I'll let you know!
