### ISSUE TITLE
Evaluating and saving checkpoints within an epoch

### ISSUE THREAD

**Issue by nelson-liu** [allenai/allennlp#5155]
**Is your feature request related to a problem? Please describe.**

Right now, allennlp currently evaluates / saves checkpoints at the end of every epoch. However, it'd be nice if there was some way of evaluating within an epoch.  For example, say an epoch is 10,000 steps, and I want to evaluate / save a checkpoint every 500 steps.

This is especially important when fine-tuning pre-trained language models. Often, the optimal checkpoint does not occur at the end of an epoch, and models can quickly overfit. For example, the huggingface default scripts save checkpoints every 500 steps. it'd be nice to have some sort of similar option for allennlp.

**Describe the solution you'd like**
perhaps the checkpointing side of this could be controlled by the checkpointer, similar to how `keep_serialized_model_every_num_seconds` exists. Perhaps `keep_serialized_model_every_num_steps`. However, maybe there needs to be analogous argument in the `Trainer` for evaluation.

**Comment by nelson-liu** [comment]
To be concrete: I'm trying to train BERT on the IMDb sentiment dataset (25K examples). It peaks after epoch 2 (and starts overfitting from epoch 3) but i'm sure that there are better checkpoints between the end of epoch 2 and the end of epoch 3. In general, these pre-trained language models aren't trained for very many epochs (e.g., 3-4), so only evaluating and saving 3 or 4 checkpoints seems like you'd leave a lot of performance on the table.

**Comment by ArjunSubramonian** [comment]
This would indeed be a great feature to have.

**Comment by epwalsh** [comment]
In practice I always set [`data_loader.baches_per_epoch`](https://docs.allennlp.org/main/api/data/data_loaders/multiprocess_data_loader/#multiprocessdataloader.parameters) to a suitable number for this exact reason. Is there a reason that approach is sub-optimal for you use-case, @nelson-liu?

**Comment by nelson-liu** [comment]
The reason is that i either did not know about it, and/or forgot that this was a thing :) This seems to fit the bill perfectly, thanks @epwalsh .

**Comment by epwalsh** [comment]
Great, no problem!
