### ISSUE TITLE
sequence prediction using GPU

### ISSUE THREAD

**Issue by md975** [allenai/allennlp#5159]
Hi,

I found [this script](https://guide.allennlp.org/semantic-parsing-seq2seq#6) for sequence prediction from a pretrained seq2seq model. However, this is too slow and I'm having trouble and getting errors when changing it in a way that would use batches and also the GPU. What changes do I need to make to the original script to make it work on GPU?
I'm very new to this and would appreciate some help!

Thanks

**Comment by ArjunSubramonian** [comment]
Could you elaborate on what errors you're running into and what changes you have tried?

**Comment by md975** [comment]
Thanks so much for your response.
So I think I figured out the errors and I have a script that runs ok, but it's still very slow and I think it's not using the gpu.
Here is what I have so far:
```
predictor = Predictor.from_archive(archive, "seq2seq", {'cuda_device':0})

def predict_batch_instance(instances):
    for instance in instances:
        predictor._dataset_reader.apply_token_indexers(instance)
    outputs = predictor._model.forward_on_instances(instances) # this is slow
    return sanitize(outputs)

temp = []
with open(data_path, 'r') as f:
    for nla_input in f:
        instance = predictor._json_to_instance({"source":nla_input.rstrip()})
        temp.append(instance)
    output = predict_batch_instance(temp[:5])

```
Am I missing something?

**Comment by ArjunSubramonian** [comment]
`forward_on_instances` moves the instances to the device on which the model is located. Have you tried printing out on which device `predictor._model` is located? I know you pass in `{'cuda_device':0}`, but from inspecting the predictor creation process, it looks like the predictor's device is set to be the model's device in the constructor and does not consider the extra kwargs you pass in. Potentially try explicitly moving `predictor._model.to(... device)`.

**Comment by md975** [comment]
`predictor._model.to(device) `solved the problem. Thanks so much!
