### ISSUE TITLE
How can i add a new subcommand?

### ISSUE THREAD

**Issue by ding00** [allenai/allennlp#5164]
I'm writing a transfer learning(domain adaptation) method in Allennlp, so I created a trainer by myself, and I wanted to write a new command( for example mytrain or mypredict) to begin the training and predict process.
How can I use the command:   allennlp mytrain xxx.jsonnet --including-package xxx  --serialization-dir xxxx ?

**Comment by ArjunSubramonian** [comment]
You can write your code in the style of [Train](https://github.com/allenai/allennlp/blob/5b57be292c7d193419d7c8436441aff907068d5e/allennlp/commands/train.py#L36). Make sure to annotate your class with `@Subcommand.register("mytrain")`.

**Comment by ding00** [comment]
> You can write your code in the style of [Train](https://github.com/allenai/allennlp/blob/5b57be292c7d193419d7c8436441aff907068d5e/allennlp/commands/train.py#L36). Make sure to annotate your class with `@Subcommand.register("mytrain")`.

Yes, I writed  mytrain.py and register it by @Subcommand.register("mytrain"), but when I  want to train my model, I use the command:   allennlp mytrain xxx.jsonnet --including-package xxx --serialization-dir xxxx , the error is that mytrain can not be find.
I guess that finding the  mytrain command is executed before than  the registering operation @Subcommand.register("mytrain").

**Comment by ArjunSubramonian** [comment]
Okay, so upon further inspection, there is a plugins feature with the following description in `allennlp/common/plugins.py`:

> # Plugin management.
> 
> AllenNLP supports loading "plugins" dynamically. A plugin is just a Python package that
> provides custom registered classes or additional `allennlp` subcommands.
> 
> In order for AllenNLP to find your plugins, you have to create either a local plugins
> file named `.allennlp_plugins` in the directory where the `allennlp` command is run, or a global
> plugins file at `~/.allennlp/plugins`. The file should list the plugin modules that you want to
> be loaded, one per line.
> 

Could you please try creating such a file and listing your "mytrain" subcommand in there, if you haven't already?

**Comment by ding00** [comment]
> Okay, so upon further inspection, there is a plugins feature with the following description in `allennlp/common/plugins.py`:
> 
> > # Plugin management.
> > AllenNLP supports loading "plugins" dynamically. A plugin is just a Python package that
> > provides custom registered classes or additional `allennlp` subcommands.
> > In order for AllenNLP to find your plugins, you have to create either a local plugins
> > file named `.allennlp_plugins` in the directory where the `allennlp` command is run, or a global
> > plugins file at `~/.allennlp/plugins`. The file should list the plugin modules that you want to
> > be loaded, one per line.
> 
> Could you please try creating such a file and listing your "mytrain" subcommand in there, if you haven't already?

thank you! I will try this!
