### ISSUE TITLE
Cannot load the pre-trained models

### ISSUE THREAD

**Issue by MausamGaurav** [allenai/allennlp#5170]
I want to load the pre-trained model. I have downloaded the model to my local drive since, I am unable to connect to https:// from command line due to corporate policy. When I try to load the model, it gives me a connection error. I have had this issue with the latest version 2.4 as well. What is the best practice to load pre-trained models saved on disk?

## Description

Trying to load the downloaded model.

```
import os
from allennlp.models.archival import archive_model, load_archive
archive = load_archive(os.path.join("structured-prediction-srl-bert.2020.12.15.tar.gz"))
```

 I get the below error:
```
P:\myPython37Env\lib\site-packages\transformers\configuration_utils.py in get_config_dict(cls, pretrained_model_name_or_path, **kwargs)
    386                 proxies=proxies,
    387                 resume_download=resume_download,
--> 388                 local_files_only=local_files_only,
    389             )
    390             # Load config dict

P:\myPython37Env\lib\site-packages\transformers\file_utils.py in cached_path(url_or_filename, cache_dir, force_download, proxies, resume_download, user_agent, extract_compressed_file, force_extract, local_files_only)
    953             resume_download=resume_download,
    954             user_agent=user_agent,
--> 955             local_files_only=local_files_only,
    956         )
    957     elif os.path.exists(url_or_filename):

P:\myPython37Env\lib\site-packages\transformers\file_utils.py in get_from_cache(url, cache_dir, force_download, proxies, etag_timeout, resume_download, user_agent, local_files_only)
   1123                 else:
   1124                     raise ValueError(
-> 1125                         "Connection error, and we cannot find the requested files in the cached path."
   1126                         " Please try again or make sure your Internet connection is on."
   1127                     )

ValueError: Connection error, and we cannot find the requested files in the cached path. Please try again or make sure your Internet connection is on.
```
</p>
</details>

## Environment

OS: Windows 10

Python version: 3.7.4

```
allennlp==1.2.2
allennlp-models==1.2.2
```

</p>
</details>

**Comment by ArjunSubramonian** [comment]
We are unable to reproduce this issue with the [latest version](https://github.com/huggingface/transformers/blob/b29eb247d39b56d903ea36c4f6c272a7bb0c0b4c/src/transformers/file_utils.py#L1474-L1480) of AllenNLP.

**Comment by epwalsh** [comment]
@MausamGaurav, if you are still seeing this error with the latest version of both AllenNLP and transformers, could you post a full stack trace?

**Comment by MausamGaurav** [comment]
> @MausamGaurav, if you are still seeing this error with the latest version of both AllenNLP and transformers, could you post a full stack trace?

I upgraded AllenNLP to version 2.4.0. The below are the relevant version details:
```
torch v_1.8.1
transformers v_4.5.1
allennlp v_2.4.0
allennlp_models v_2.4.0
```
This is what I did to again get the same error.

**Import libraries**:
```
import allennlp
from allennlp.models.archival import load_archive
from allennlp.predictors import Predictor
```

**Try to load model from local file**:
```
import os
allennlp.common.plugins.import_plugins()
archive = load_archive(os.path.join("structured-prediction-srl-bert.2020.12.15.tar.gz"))
```
I get the same error as before. 
Please note that you need to turn off your internet connection to reproduce this error. As I already described, I am unable to download anything from the internet with my command line.

**Comment by epwalsh** [comment]
Ok, https://github.com/allenai/allennlp-models/pull/257 provides a work-around.

**Comment by MausamGaurav** [comment]
Thanks for your efforts. This is finally working after I pasted the patched file "allennlp_models/structured_prediction/models/srl_bert.py" from  the new branch [srl-no-load-weights](https://github.com/allenai/allennlp-models/tree/srl-no-load-weights) into my local environment in the right location.  
However, to make it work this is the sequence I had to follow (since I have to download all files manually).

1. Download the bert-base-uncased 'config.json', 'vocab.text',  and the 'pytorch_model.bin' files from https://huggingface.co/bert-base-uncased/tree/main
2. Put these files in a folder called 'bert-base-uncased'.
3. Load the model from these files with transformers as below
 ``` 
from transformers import BertModel
model = BertModel.from_pretrained('.\\bert-base-uncased')
``` 
Then using the `model.config` option load the SRL Predictor as below:
```
from transformers import AutoConfig
from allennlp.predictors import Predictor

archive_path = ".\\structured-prediction-srl-bert.2020.12.15.tar.gz"

################
config = model.config
################

predictor = Predictor.from_path(
    archive_path,
    overrides={
        "model.bert_model": config.to_dict(),
        "dataset_reader.bert_model_name": local_config_path,
    },
)
```
I could have downloaded just the 'config.json', however, just to be doubly sure, I also downloaded the other files to load the model first and then  perform `model.config`.

**Comment by epwalsh** [comment]
@MausamGaurav I'm glad that worked for you. It's definitely not ideal, I'd like to have a better solution in the future. You shouldn't need to download the `pytorch_model.bin` file though. You could just do `json.loads("bert-base-uncased/config.json")` to get the config.
