### ISSUE TITLE
No module named 'allennlp.data.tokenizers.word_splitter'

### ISSUE THREAD

**Issue by mitra8814** [allenai/allennlp#5171]
I'm using python 3.7 in google colab. I install allennlp=2.4.0 and allennlp-models.

When I run my code:

from allennlp.data.tokenizers.word_splitter import SpacyWordSplitter

 I get this error:

    ModuleNotFoundError: No module named 'allennlp.data.tokenizers.word_splitter'

help me please.

**Comment by jacob-morrison** [comment]
Do you mean the `SpacySentenceSplitter`? If that's what you want, then you should change your import to:

`from allennlp.data.tokenizers.sentence_splitter import SpacySentenceSplitter`
