### ISSUE TITLE
I want load my model by own scripts  how i do

### ISSUE THREAD

**Issue by dugudongfangshuo** [allenai/allennlp#5177]
in your tutorial, you say:
see our chapter on writing your own scripts for pointers on how to save and load models if you aren't using configuration files.
but https://guide.allennlp.org/writing-your-own-script#3 is None  , can you give me some suggest

**Comment by jacob-morrison** [comment]
We have a template for a project that uses the API instead of configuration files here: https://github.com/allenai/allennlp-template-python-script, which should point you in the right direction.
