### ISSUE TITLE
Pretrained model for RE on SciBert

### ISSUE THREAD

**Issue by MHDBST** [allenai/allennlp#5198]
Hi,
I am new to allennlp. I was able to train a model using `train_allennlp_local.sh` with `DATASET='chemprot'` and `TASK='text_classification'` I have some issues on reproducing the same results as reported in the paper:

when I set `with_finetuning='_finetune'` the model is never improving while training. After a lot of epochs it converges at a `average F1 score = 0.05` which is ridiculously low.

When I set `with_finetuning=''` The model converges after around 50 epochs at `average F1 score = 0.46` which is not even close to the numbers reported in the paper.

I have two questions here:

1. As I haven't changed any thing in the code and I have just run the `train_allennlp_local.sh` suggested by the website itself, is there anything I'm missing here?

2. Is there any pertained relation extraction task on chemprot with scibert which can be used for prediction?

**Comment by epwalsh** [comment]
Pinging @kyleclo in case he has an answer
