### ISSUE TITLE
Add versioning to the running demo.

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp#520]
Presently, there is no way to tell what version of code a running copy of the demo is using.  Other software at AI2 has a `/info` route which gives an overview of the service.  For example, see https://www.semanticscholar.org/api/1/info (only available on our network).

Ideally our demo would have a `/info` route as well, with information such as the following:

```
{
  name: "AllenNLP Demo",
  startTime: "Fri, 10 Nov 2017 13:48:51 -0800",
  gitVersion: "a5350d6c1b6816ce62584e707e4bb933840db8e3",
  githubUrl: "http://github.com/allenai/scholar/commit/a5350d6c1b6816ce62584e707e4bb933840db8e3",
  gitCommitDate: "Fri, 10 Nov 2017 10:20:18 -0800",
}
```

We could store the `gitVersion` and `gitCommitDate` when building a Docker image.

**Comment by schmmd** [comment]
@joelgrus do you have any thoughts on this?

**Comment by joelgrus** [comment]
this seems good, are you saying we should have them as environment variables?

**Comment by schmmd** [comment]
I was originally thinking of writing this information to a file, but now I'm leaning towards an environment variable.  I ran across https://github.com/docker/hub-feedback/issues/600 which handles this with `--build-arg SOURCE_COMMIT=$SOURCE_COMMIT`.

**Comment by joelgrus** [comment]
👍

**Comment by schmmd** [comment]
Fixed by https://github.com/allenai/allennlp/pull/528
