### ISSUE TITLE
Example for fine-tunning or multi-task on huggingface transformers

### ISSUE THREAD

**Issue by thak123** [allenai/allennlp#5204]
Hi

I am looking for examples of allennlps' latest features,
I can't seem to find one. Can anyone point me to the link?

**Comment by AkshitaB** [comment]
Hi @thak123 

Here's an allennlp config file that trains a multi-task vilbert model, where the tokenizer is a huggingface transformer.
https://github.com/allenai/allennlp-models/blob/main/training_config/vision/vilbert_multitask.jsonnet 

Other relevant code can be found here:

Dataset reader: https://github.com/allenai/allennlp/blob/main/allennlp/data/dataset_readers/multitask.py
Data loader: https://github.com/allenai/allennlp/blob/main/allennlp/data/data_loaders/multitask_data_loader.py
Model: https://github.com/allenai/allennlp/blob/main/allennlp/models/multitask.py
Predictor: https://github.com/allenai/allennlp/blob/main/allennlp/predictors/multitask.py 

Let me know if this is helpful.

**Comment by thak123** [comment]
Hi @AkshitaB 

Thanks for the pointers.
