### ISSUE TITLE
"Overall statistics" for span_based_f1_measure

### ISSUE THREAD

**Issue by Aktsvigun** [allenai/allennlp#5206]
For `span_based_f1_measure` metric it is written in `Return` in [docs](http://docs.allennlp.org/main/api/training/metrics/span_based_f1_measure/): 

> Additionally, an **overall** key is included, which provides the precision, recall and f1-measure for all spans.

However, the overall statistics can be calculated using either _micro_, or _weighted_, or _macro_ methods. Which one is used in this case?

Thanks!

**Comment by AkshitaB** [comment]
@Aktsvigun The overall statistics are computed using micro-averaging. https://github.com/allenai/allennlp/blob/main/allennlp/training/metrics/span_based_f1_measure.py#L278

**Comment by Aktsvigun** [comment]
@AkshitaB Thanks!
