### ISSUE TITLE
Remove `end_index` from `BeamSearch` constructor

### ISSUE THREAD

**Issue by danieldeutsch** [allenai/allennlp#5219]
**Is your feature request related to a problem? Please describe.**
As far as I know, the only way to configure `BeamSearch` in a config file is by hard coding the `end_index` for the specific vocabulary. This is not desirable because then the config file isn't very generic. As a result, you have to add the `BeamSearch` parameters to your model's constructor, then create the `BeamSearch` object yourself once you know the `end_index`. See [here](https://github.com/allenai/allennlp-models/blob/2f1b77919478c30a2c19cf4892a5980a1d70c501/allennlp_models/generation/models/bart.py#L137-L158) for an example.

**Describe the solution you'd like**
Remove `end_index` from the constructor and pass it as a parameter to `search()` instead.

**Additional context**
This would be a breaking change to any model that uses `BeamSearch`.

It is a simple PR to do, so I can do it if you all are ok with making the breaking change.

**Comment by dirkgr** [comment]
@JohnGiorgi found a similar problem, with a different solution, at https://github.com/allenai/allennlp-models/pull/267. Does his approach make sense for you?

**Comment by dirkgr** [comment]
Sorry, I misunderstood what `end_index` is for when I first looked at these issues. I understand now.

@JohnGiorgi is going to make a PR that uses `Lazy` to let you specify a `BeamSearch` in a config file. I believe this will solve this issue, too. Feel free to re-open this if I'm wrong about that.
