### ISSUE TITLE
Does version 0.9.0 can train model with multiple gpus?

### ISSUE THREAD

**Issue by yuhaia** [allenai/allennlp#5224]
Hi, I'm running a [project](https://github.com/sebastian-hofstaetter/transformer-kernel-ranking) written with allennlp where the version is 0.9.0. And I want to use multiple gpus to accelerate the training process. I found a previous issue in [3831](https://github.com/allenai/allennlp/issues/3831). But it seems that version 0.9.0 can not support training with multiple gpus?

**Comment by dirkgr** [comment]
Sorry, it cannot. The original 1.0 release has an upgrade guide. Is that helpful? https://github.com/allenai/allennlp/releases/tag/v1.0.0
