### ISSUE TITLE
Access the [CLS] token when using a pretrained_transformer_mismatched_embedder

### ISSUE THREAD

**Issue by MSLars** [allenai/allennlp#5225]
Is there a simple way to access the `[CLS]` Token after encoding a token-sequence using a `pretrained_transformer_mismatched_embedder`?

Using a `bert_pooler` `seq2vec` encoder leads to an additional forward pass through the transformer. My Intuition is, that this should be avoided.

In [pretrained_transformer_mismatched_embedder.py](https://github.com/allenai/allennlp/blob/main/allennlp/modules/token_embedders/pretrained_transformer_mismatched_embedder.py#L139)

`span_embeddings, span_mask = util.batched_span_select(embeddings.contiguous(), offsets)`

the `embedding` tensor contains the [CLS] vector at index 0. `batched_span_select` removes this information, since a `seq2seq` encoder does not include the [CLS] token. For RNN-based encoders we can use [get_final_encoder_states](https://github.com/allenai/allennlp/blob/main/allennlp/nn/util.py#L187). Is there a similar way to access the [CLS] information for transformer-based token embedders?

**Comment by dirkgr** [comment]
What's the situation that requires you to have both the mismatched embeddings, but also the CLS token?

**Comment by dirkgr** [comment]
I guess the easiest thing would be to add a flag to the embedder that allows you to keep the CLS token. I'd be happy to review a PR if you make one?

**Comment by MSLars** [comment]
I want to implement a joint relation extraction model inspired by [this approach](https://github.com/lavis-nlp/spert). The approach enumerates text-spans as entity candidates. The candidate representation contains a concatenation of max-pooled token vectors and [CLS] token. The paper contains no concrete numbers regarding this design decision but it might be helpful to include some wider context in such decisions. I use the mismatched tokenizer to be consistent with existing entity annotations. 

Thanks for your reply, I will prepare a PR.

**Comment by dirkgr** [comment]
Does that really need the mismatched embedder? The mismatched embedder is there to give you the ability to use some tokenization other than BERT word pieces with BERT. You can use it for arbitrary spans, but that's not what it was for originally.

Maybe you can just run the regular `PretrainedTransformerEmbedder`, and handle the spans yourself (with `batched_span_select`, or even by stealing the relevant code from the mismatched embedder).

But hey, if getting the CLS token solves your problem, I'm still happy to look at the PR for it.

**Comment by MSLars** [comment]
Thanks for this advice. In my specific case, this solves the problem. I will prepare the PR anyway since it might be useful for others for various reasons. Anyway, thank you very much for your help and the quick replies.
