### ISSUE TITLE
Add option to set `find_unused_parameters` (if necessary?)

### ISSUE THREAD

**Issue by offendo** [allenai/allennlp#5228]
Hello! Thanks for the fantastic work on this project.

## Problem
In the `Trainer` class, the `find_unused_parameters` flag for DDP is set to `True`, which causes the following warning when running distributed code.
```
Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused
parameters in the forward pass. This flag results in an extra traversal of the autograd graph every
iteration, which can adversely affect performance. If your model indeed never has any unused
parameters in the forward pass, consider turning this flag off. Note that this warning may be a
false positive if your model has flow control causing later iterations to have unused
parameters. (function operator())
```

(Issue #3574 and PR #3575 are related)

## Request

The warning states it can adversely affect performance, but I'm not clear on how much exactly. Simply traversing the graph sounds like a minimal compute expenditure, yeah? 

If that's the case, maybe we can disable the warning? If it's not controllable by the end user anyway (since it's not a parameter to `Trainer`), is it useful to print out?

On the other hand, if it is significantly detrimental to performance, maybe it should be a parameter. Although, the constructor signature is already rather imposing...

Thanks for your time!

**Comment by dirkgr** [comment]
I think I just want to turn that parameter off completely. It's not reliable with multitask models, it prints a warning, and it's weird that we get this check only in the distributed setting. If we want to provide this functionality, I'd rather do it in a `TrainerCallback`. @epwalsh, @AkshitaB, any concerns?

**Comment by dirkgr** [comment]
@epwalsh says he has this fixed in his work on T5.

**Comment by dirkgr** [comment]
Update: There is no PR yet for Pete's work, but we'll link the issue when there is one.

**Comment by offendo** [comment]
Thanks, appreciate it!

**Comment by dirkgr** [comment]
Have not forgotten. @epwalsh is still working on his PR.
