### ISSUE TITLE
Vocabulary is not ready when the model is being initialized

### ISSUE THREAD

**Issue by mahnerak** [allenai/allennlp#5232]
When the model is initialized (inside the `Model.__init__`), the `vocabulary` is provided, however, some parts of it are not ready.
For example - the vocabulary of the pretrained LM used by our model.
```
# inside the `Model.__init__`, right after `super().__init__()`, before anything else
>>> vocab._token_to_index
_TokenToIndexDefaultDict(None, {'labels': {'entailment': 0, 'not_entailment': 1}})
```

This is because `model.construct()` is called before `data_loader_.index_with(model_.vocab)`. Moving the model initialization after the `data_loader_.index_with(model_.vocab)` populated vocabulary with items created during indexing.
https://github.com/allenai/allennlp/blob/98dae7f4a3b18a1521fdec8a10197d259cdf785b/allennlp/commands/train.py#L725-L740 

What are the scenarios that require expanding the vocabulary during the model initialization? (Mentioned in line 729)
In those cases, do we prefer expanding them after changes by `data_loader_.index_with(model_.vocab)` or before?

**Comment by ArjunSubramonian** [comment]
Could you elaborate on how one could index `data_loader` without the lazy initialization of `Model` occurring first? You need access to `model_` (which is returned by `model.construct`) to index `data_loader`.

**Comment by mahnerak** [comment]
@ArjunSubramonian `model_.vocab` is not available yet, but can't we suppose it will be `vocabulary_` passed to the `Model.construct()`? So we can simply `data_loader_.index_with(vocabulary_)` and then pass the (possibly modified) `vocabulary_` to the model.

In our internal version (we need our model to have an access to the vocabulary on the initialization stage) we've done this like:
https://github.com/YerevaNN/allennlp/blob/bb533a49032ae841ccbb43446679da0e6f06a037/allennlp/commands/train.py#L722

**Comment by ArjunSubramonian** [comment]
Oh, I see. Thanks for explaining this. Yes, I guess that would be useful if the model's `output_dim` depended on `vocab_size`, for example.

I'm adding @AkshitaB here for a second opinion, but it seems reasonable to add a kwarg to `from_partial_objects` that indicates the relative ordering of data loader indexing and model construction (with the default being what we have currently: model construction first).

**Comment by mahnerak** [comment]
@ArjunSubramonian Do we have an example of a model that alters the vocab in `Model.__init__`?
The only such model I've found so far:

https://github.com/allenai/allennlp-models/blob/e395e6338ed96759e145063ce5e9a2864f51bff6/allennlp_models/generation/models/copynet_seq2seq.py#L95
```
...
    ) -> None:
        super().__init__(vocab)
        self._target_namespace = target_namespace
        self._start_index = self.vocab.get_token_index(START_SYMBOL, self._target_namespace)
        self._end_index = self.vocab.get_token_index(END_SYMBOL, self._target_namespace)
        self._oov_index = self.vocab.get_token_index(self.vocab._oov_token, self._target_namespace)
        self._pad_index = self.vocab.get_token_index(
            self.vocab._padding_token, self._target_namespace
        )
        self._copy_index = self.vocab.add_token_to_namespace(copy_token, self._target_namespace)

        self._tensor_based_metric = tensor_based_metric or BLEU(
            exclude_indices={self._pad_index, self._end_index, self._start_index}
        )
        self._token_based_metric = token_based_metric

        self._target_vocab_size = self.vocab.get_vocab_size(self._target_namespace)
...
```

In examples like this, do we really want to index with data loaders only after the model has added new tokens?
I am thinking what if we always initialize the model with a prepared vocabulary?

BTW I checked the `copynet_seq2seq` code, it works well with the patch from my previous comment.

**Comment by ArjunSubramonian** [comment]
Even if it would keep the API simple, we need to guarantee backwards compatibility for all edge cases, so we should definitely use a flag.

**Comment by epwalsh** [comment]
Ideally `data_loader.index_with(vocab)` should **not** modify the `vocab`. But, as @mahnerak noted, sometimes the pretrained transformer indexer will in fact modify the `vocab` if the transformer model's namespace hasn't been added yet. Though you can avoid this by using the [`from_pretrained_transformer`](https://github.com/allenai/allennlp/blob/7a5106d541006a5b7f544284aeedb03ba2b480d5/allennlp/data/vocabulary.py#L810) vocab type.
