### ISSUE TITLE
Can't install allennlp 0.5.0

### ISSUE THREAD

**Issue by Nitasophia** [allenai/allennlp#5233]
I want to use ElmoEmbedder from [Elmo](https://github.com/UKPLab/elmo-bilstm-cnn-crf/blob/master/Keras_ELMo_Tutorial.ipynb). 

Requirements:
Python 3.6 - lower versions of Python do not work
AllenNLP 0.5.1 - to compute the ELMo representations
Keras 2.2.0 - For the creation of BiLSTM-CNN-CRF architecture

When i install allennlp 0.5.0, i got error like this.
`ERROR: Could not find a version that satisfies the requirement torch==0.4.0 (from allennlp) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2, 1.7.0, 1.7.1, 1.8.0, 1.8.1)
ERROR: No matching distribution found for torch==0.4.0`

So i install the torch 0.4.0 but it gave me another error like this
`ERROR: Could not find a version that satisfies the requirement torch==0.4.0 (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2, 1.7.0, 1.7.1, 1.8.0, 1.8.1)
ERROR: No matching distribution found for torch==0.4.0`

So, how can i install allennlp 0.5.0?

**Comment by ArjunSubramonian** [comment]
Did you run `pip install torch==0.4.0 -f https://download.pytorch.org/whl/torch_stable.html`?

**Comment by Nitasophia** [comment]
> 
> 
> Did you run `pip install torch==0.4.0 -f https://download.pytorch.org/whl/torch_stable.html`?

i got the same error like before

**Comment by david-waterworth** [comment]
@Nitasophia you are using python 3.6? It was mentioned in your original post but torch 0.4.0 is only available for 3.6.

The following seems to work for me

> pyenv install 3.6.13
> pyenv virtualenv 3.6.13 testing
> pyenv active 3.6.13
> pip install torch==0.4.0 -f https://download.pytorch.org/whl/torch_stable.html
> pip install allennlp==0.5.0
> pip install keras==2.2.1

**Comment by Nitasophia** [comment]
> 
> 
> @Nitasophia you are using python 3.6? It was mentioned in your original post but torch 0.4.0 is only available for 3.6.
> 
> The following seems to work for me
> 
> > pyenv install 3.6.13
> > pyenv virtualenv 3.6.13 testing
> > pyenv active 3.6.13
> > pip install torch==0.4.0 -f https://download.pytorch.org/whl/torch_stable.html
> > pip install allennlp==0.5.0
> > pip install keras==2.2.1

i have, but still can't install allennlp 0.5.0 so i switch to use allennlp 0.8.5. Thanks
