### ISSUE TITLE
Pre-trained initializer with a jsonnet config file

### ISSUE THREAD

**Issue by OhadRubin** [allenai/allennlp#5240]
Hey, how do you use the PretrainedModelInitializer with a config file?
See here https://github.com/OhadRubin/SmBop/issues/20

**Comment by ArjunSubramonian** [comment]
Hey! Please let me know if I'm misunderstanding the issue, but if you're simply looking to load pretrained weights for an entire model from an archive model for the purpose of fine-tuning, you can do this:
```"model": {
      "_pretrained": {
        "archive_file": "https://storage.googleapis.com/allennlp-public-models/snli-roberta.2021-03-11.tar.gz",
        "module_path": "",
        "freeze": false
      }```

Take a look at this file: https://github.com/allenai/allennlp-models/blob/5dcf2b94db025cfbac54e1138cf79992e3d567ad/test_fixtures/pair_classification/bias_mitigation/experiment.json.

**Comment by OhadRubin** [comment]
Thanks
