### ISSUE TITLE
ValueError while parsing the input file for OpenIE model

### ISSUE THREAD

**Issue by AntoThomasK03** [allenai/allennlp#5243]
I am using the Docker container for predicting the triple using the pretrained OpenIE model. While running the container I get this error
"ValueError: unable to parse C:/Users/a01thoma/Downloads/ClausIE-datasets/ClausIE-datasets/test.json as a URL or as a local path" (https://github.com/allenai/allennlp/blob/7a5106d541006a5b7f544284aeedb03ba2b480d5/allennlp/common/file_utils.py#L328)

In the json file I have [{"sentence":"He is a Professor"},{"sentence":"She is his student"}] following https://github.com/allenai/allennlp-models/blob/ab1e86a4319faf1d8a3ea7e259a342fefbd437b4/allennlp_models/structured_prediction/predictors/srl.py#L143
I had gone through 
Could you please help me to resolve this issue? Thanks

**Comment by AntoThomasK03** [comment]
Sorry. I solved the issue. It was something to do with the Docker.
It was beacuse I didn't bind mount my local folder.

**Comment by ArjunSubramonian** [comment]
Can you try providing the input in JSON lines format? That is, could you structure your input file like so (each sentence separated by a newline):

```
{"sentence": "he is a Professor"}
{"sentence": "she is his student"}
```

**Comment by AntoThomasK03** [comment]
Worked like a charm :) Thanks Arjun.
