### ISSUE TITLE
[Docs] Link is broken in the Doc of fairness_metrics

### ISSUE THREAD

**Issue by bhadreshpsavani** [allenai/allennlp#5244]
## Checklist

- [x] I have verified that the issue exists against the `main` branch of AllenNLP.
- [x] I have read the relevant section in the [contribution guide](https://github.com/allenai/allennlp/blob/main/CONTRIBUTING.md#bug-fixes-and-new-features) on reporting bugs.
- [x] I have checked the [issues list](https://github.com/allenai/allennlp/issues) for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/allenai/allennlp/pulls) for existing proposed fixes.
- [x] I have checked the [CHANGELOG](https://github.com/allenai/allennlp/blob/main/CHANGELOG.md) and the [commit log](https://github.com/allenai/allennlp/commits/main) to find out if the bug was already fixed in the main branch.
- [x] I have included in the "Description" section below a traceback from any exceptions related to this bug.
- [x] I have included in the "Related issues or possible duplicates" section beloew all related issues and possible duplicate issues (If there are none, check this box anyway).
- [x] I have included in the "Environment" section below the name of the operating system and Python version that I was using when I discovered this bug.
- [x] I have included in the "Environment" section below the output of `pip freeze`.
- [x] I have included in the "Steps to reproduce" section below a minimally reproducible example.

## Description
![Screenshot from 2021-06-07 20-32-04](https://user-images.githubusercontent.com/26653468/121040994-fc4d1580-c7cf-11eb-8d8f-69329ad0ca92.png)

**Comment by jacob-morrison** [comment]
Thanks for catching that, and for submitting a PR to fix it! I commented on your PR, so we can submit it once the checks are all passing and close this issue.
