### ISSUE TITLE
pretrained_transformer_indexer sets token_ids and mask to different lengths

### ISSUE THREAD

**Issue by david-waterworth** [allenai/allennlp#5254]
In `pretrained_transformer_indexer` the method `tokens_to_indices` adds `token_ids`, `mask` and `type_ids` to the output dict.

https://github.com/allenai/allennlp/blob/a6cfb1221520fca7a5cc55bef001c6a79a6a3e2f/allennlp/data/token_indexers/pretrained_transformer_indexer.py#L94

This is then passed to `_postprocess_output` which potentially resizes token_ids and type_ids (i.e. # Strips original special tokens), but it returns `segment_concat_mask` instead of `mask`. `mask` is now the same length as `token_ids`.

Also note the `_postprocess_output` only executes if _max_length is None. So special tokens only get stripped in this case? And the index sets `self._num_added_start_tokens` and `self._num_added_start_tokens` to 1 regardless of whether the tokenizer has include_special_tokens=true or false.

The issue I'm running into, is I'm using a CrfTagger with pretrained_transformer, setting the encoder to pass_through. The pass_through encoder accepts token_ids and mask, which are now misaligned so an exception is thrown.

It seems that the only combination which works is to not set `max_length` (in which case `segment_concat_mask` doesn't get added).

I'm using the json below to construct the tokenizer, token_indexer and model. 

```
{
    "tokenizer": {
        "type": "pretrained_transformer",
        "model_name": "/path/to/custom/model"
    },
    "token_indexers": {
        "tokens": {
        "type": "pretrained_transformer",
        "model_name": "/path/to/custom/model",
        "max_length": 128
        }
    }
}

{
    "text_field_embedder":{
        "token_embedders":{
            "tokens": {
                "type":"pretrained_transformer",
                "model_name":"path/to/custom/model",
                "max_length":128
            }
        }
    },
    "encoder":{
        "type":"pass_through",
        "input_dim":128
    },
    "label_encoding":"BIOUL",
    "constrain_crf_decoding":true,
    "include_start_end_transitions":true,
    "dropout":0.5,
    "verbose_metrics":false,
    "calculate_span_f1":true
}
```

**Comment by dirkgr** [comment]
The size of the `"mask"` tensor should match the size of the output from `pretrained_transformer_embedder`. Do you find that this is not the case?

Can you post a complete training config that I can run to take a closer look?

**Comment by david-waterworth** [comment]
I'm using a custom hugging face tokeniser I trained myself, with a data reader. I tied to reproduce using BERT and I cannot so there's something different about my setup. Maybe keep this open for a bit and I'll try and work out what's different and either way I'll report back what's causing the issue.

**Comment by david-waterworth** [comment]
@dirkgr I found the issue. In the `PretrainedTransformerIndexer` `_postprocess_output` method you call the huggingface tokenizers `build_inputs_with_special_tokens` method to reconstruct each segment after striping the specials.

The docstring for this method (in the PreTrainedTokenizerBase class) says:

`This implementation does not add special tokens and this method should be overridden in a subclass.`

I didn't override this method in my tokenizer hence the problem.

**Comment by dirkgr** [comment]
> Also I think you could perhaps avoid some of this but checking in _postprocess_output if the length of the input sequence is > max_length. If not, there seems no need to deconstruct and reconstruct the token_ids?

I'd hate to leave a situation in the code where it works on some inputs but fails on some others. It's annoying when your training gets 90% through the epoch, and then it encounters some value that makes it fail.

If it's worth it for performance, then I'd consider a PR for it.

**Comment by david-waterworth** [comment]
Yes that's a good point, this code only runs when you supply max_length anyway so it's not particularly important.
