### ISSUE TITLE
Which is best pretrained model now in AllenNlp to use for Semantic search engine?

### ISSUE THREAD

**Issue by nithinreddyy** [allenai/allennlp#5261]
**Which is best pretrained model now in AllenNlp to use for Semantic search engine?**

I have one pretrained model, but it's built in 2017. I think by this time we will have so many new pretrained models.

`predictor = Predictor.from_path("https://s3-us-west-2.amazonaws.com/allennlp/models/bidaf-model-2017.09.15-charpad.tar.gz")`

The above is the pretrained model i saw.

**Can anyone suggest the latest and best AllenNlp pretrained model for semantic search engine?**

**Comment by schmmd** [comment]
Is your goal to build a search engine that work based on question and answering?  I don't think the BiDAF model will be very effective.  Overall I think this is a very hard problem, and none of our models will get you to your goal easily.

**Comment by nithinreddyy** [comment]
> Is your goal to build a search engine that work based on question and answering? I don't think the BiDAF model will be very effective. Overall I think this is a very hard problem, and none of our models will get you to your goal easily.

Not exactly like question and answering. Just semantic search with good results
