### ISSUE TITLE
allennlp.common.checks.ConfigurationError:

### ISSUE THREAD

**Issue by vicky-abr** [allenai/allennlp#5262]
allennlp.common.checks.ConfigurationError: from_params was passed a `params` object that was not a `Params`. This probably indicates malformed parameters in a configuration file, where something that should have been a dictionary was actually a list, or something else. This happened when constructing an object of type <class 'allennlp.nn.initializers.InitializerApplicator'>.

**Comment by epwalsh** [comment]
Could you please provide a code snippet that results in this error?
