### ISSUE TITLE
allennlp.common.checks.ConfigurationError: srl not in acceptable choices for dataset_reader

### ISSUE THREAD

**Issue by jeevana28** [allenai/allennlp#5274]
```
from allennlp.models import load_archive
from allennlp.predictors.predictor import Predictor
import allennlp

def get_srl_predictor():
    if torch.cuda.is_available():
        archive = allennlp.models.archival.load_archive("https://s3-us-west-2.amazonaws.com/allennlp/models/bert-base-srl-2019.06.17.tar.gz", cuda_device=0)
    else:
        archive = load_archive("https://s3-us-west-2.amazonaws.com/allennlp/models/bert-base-srl-2019.06.17.tar.gz")

    return Predictor.from_archive(archive)
```

Loading the above mentioned model is thorwing this error:
allennlp.common.checks.ConfigurationError: srl not in acceptable choices for dataset_reader.type: ['babi', 'conll2003', 'interleaving', 'multitask', 'sequence_tagging', 'sharded', 'text_classification_json', 'multitask_shim']. You should either use the --include-package flag to make sure the correct module is loaded, or use a fully qualified class name in your config file like {"model": "my_module.models.MyModel"} to have it imported automatically.

I tried using Predictot.path('https://s3-us-west-2.amazonaws.com/allennlp/models/bert-base-srl-2019.06.17.tar.gz'). But I am getting the same error. 
Can anyone please help me? 
Thankyou

**Comment by AkshitaB** [comment]
@jeevana28 Do you have `allennlp-models` installed? `srl` is implemented there.

**Comment by jeevana28** [comment]
@AkshitaB  Yes, i have allennlp-models installed, but it didnot work, however using the following line worked
`predictor = load_predictor("structured-prediction-srl-bert")`
Thankyou

**Comment by vinay1986** [comment]
Hey @jeevana28  - I'm facing the same issue, can you share the code?

**Comment by hoperiver** [comment]
Same issue I encounterd too when I was trying to run constituency tree parser and load model from https://s3-us-west-2.amazonaws.com/allennlp/models/elmo-constituency-parser-2018.03.14.tar.gz 
Seems the load_archive returnd a model name "ptb_trees" and a name containd "." was required, such as {"model": "my_module.models.MyModel"}
So I got ConfigurationError 

Any suggestion? Thanks!

**Comment by rygopu** [comment]
@hoperiver , were you able to solve it? I am facing the exact same issue. Any suggestions?

Thanks!
