### ISSUE TITLE
Stale docstring in constructor of `PytorchTransformer`

### ISSUE THREAD

**Issue by lgessler** [allenai/allennlp#5285]
The docstring of `allennlp.modules.seq2seq_encoders.PytorchTransformer`'s `__init__` describes a [`use_positional_encoding`](https://github.com/allenai/allennlp/blob/main/allennlp/modules/seq2seq_encoders/pytorch_transformer_wrapper.py#L33L37) parameter, when in fact this parameter has since been replaced by two parameters, [`positional_encoding` and `positional_embedding_size`](https://github.com/allenai/allennlp/blob/main/allennlp/modules/seq2seq_encoders/pytorch_transformer_wrapper.py#L48L49), which are not documented in the docstring.

(BTW sorry to open an issue for this instead of giving a PR, but I don't feel confident I could write a great docstring.)

**Comment by dirkgr** [comment]
I made a PR for it.
