### ISSUE TITLE
cannot import name 'LegacyAttention' from 'allennlp.modules.attention'

### ISSUE THREAD

**Issue by Aven26** [allenai/allennlp#5297]
Code:
from allennlp.modules.attention import LegacyAttention

```
Traceback (most recent call last):
  File "C:\Users\Yun\anaconda3\envs\geosolver-master\lib\site-packages\IPython\core\interactiveshell.py", line 3441, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-b117cb201d87>", line 1, in <module>
    from allennlp.modules.attention import LegacyAttention
ImportError: cannot import name 'LegacyAttention' from 'allennlp.modules.attention' (C:\Users\Yun\anaconda3\envs\geosolver-master\lib\site-packages\allennlp\modules\attention\__init__.py)
```

I also can not find a file named 'LegacyAttention' under the 'attention' file.
I use the mirror https://pypi.tuna.tsinghua.edu.cn/simple to install allennlp.
Is there something wrong with my installation. Like, I need to change a mirror?

**Comment by dirkgr** [comment]
`LegacyAttention` was removed in https://github.com/allenai/allennlp/issues/3836. I recommend you install a version of allennlp from before February 2020 to get this to work.
