### ISSUE TITLE
Correctness of summing up embeddings by the sequence dimension in the `interpret` package

### ISSUE THREAD

**Issue by koren-v** [allenai/allennlp#5298]
I would like to discuss the implementation of Integrated Gradients as well as Smooth Grads or Simple Gradients in combination with the text models. I found that you sum IG outputs by the last dimension to get a single scalar for each token (e.g [here](https://github.com/allenai/allennlp/blob/main/allennlp/interpret/saliency_interpreters/integrated_gradient.py#L33)). But do we really can simply sum them as the gradients can be negative? If some of the gradients for a particular token are negative, summing them with the rest will reduce the overall token's "score". Could it be more correct if we will take some kind of norm (L1, L2) for each token?

**Comment by dirkgr** [comment]
That sounds very reasonable, but I don't have the full overview of that code. You could implement the idea, I help you put it into the demo, and we see if the results look better?
