### ISSUE TITLE
allennlp.training.callbacks.confidence_checks.ConfidenceCheckError: The NormalizationBiasVerification check failed.

### ISSUE THREAD

**Issue by HenryPaik1** [allenai/allennlp#5302]
Hi, 
1) What should check for this error? and how to set it False in config file? 
```
allennlp.training.callbacks.confidence_checks.ConfidenceCheckError: The NormalizationBiasVerification check failed. See logs for more details.
You can disable these checks by setting the trainer parameter `run_confidence_checks` to `False`.
```
I re write the `config.jsonnet` as below:
```
"trainer": {...
      "validation_metric": "+answer_f1",
      "enable_default_callbacks": false,
      "use_amp": true, ...
      "run_confidence_checks": false
}
```
2) and I got error msg:
```
>> allennlp.common.checks.ConfigurationError: Serialization directory (checkpoint) already exists and is not empty. Specify --recover to recover from an existing output folder.
```

Would you give me some advice to solve 1) and 2), and where could I find the related documentation?

**Comment by epwalsh** [comment]
The error in (2) is because AllenNLP expects a new serialization directory for each run. So you can either delete the first directory or point AllenNLP to a different directory when you run it again.

**Comment by HenryPaik1** [comment]
@epwalsh Thanks for reply. I am still struggling for finding the documents as for 1) issue, and cannot figure out the correct config setting for `run_confidence_checks: false`. I would be appreciate if you could provide a piece of advice.
