### ISSUE TITLE
Open IE separates auxiliary and participle into separate tuples

### ISSUE THREAD

**Issue by artidoro** [allenai/allennlp#5307]
## Description

<details>
<summary><b>OpenIE separates auxiliary and participle into separate tuples. This affects the online demo and my local installation of AllenNLP.</b></summary>
<p>
In the sentence "He is running to the store", my understanding is that there is only one predicate and that the output of OpenIE should be a single tuple:
[Arg0: He] [V: is running] [Arg1: to the store]

Instead, I get two tuples where the first is simply the auxiliary:
[V: is]
[Arg0: He] [V: running] [Arg1: to the store]

You can see the examples linked below from the online demo to see that it affects other sentences/auxiliaries too. I also noticed the SRL demo returns two predicates for the same sentence.

</p>
</details>

## Related issues or possible duplicates

- None

## Environment
Online demo, though I initially noticed this on my local installation of AllenNLP.

## Steps to reproduce

https://demo.allennlp.org/open-information-extraction/s/he-has-moved-out-appartment/L1E3P1E9G4
https://demo.allennlp.org/open-information-extraction/s/he-is-running-to-store/E5E4Z1H6D9

**Comment by schmmd** [comment]
@artidoro I agree that the output for that sentence is bad, but no model will work right 100% of the time.  I'm sure the Open IE model could be improved, but that's not presently on our roadmap.  We would definitely welcome contributions if someone was up for investing here!

**Comment by artidoro** [comment]
This seems like a bug, not an issue with the model. Thanks for your reply though. I hope someone finds the time to fix this.
