### ISSUE TITLE
Move `cached_path` to a separate library

### ISSUE THREAD

**Issue by bryant1410** [allenai/allennlp#5310]
What if we move `cached_path` to a separate library? It's useful on its own, without AllenNLP.

**Is your feature request related to a problem? Please describe.**
I find it very useful to just specify URLs around (outside AllenNLP) and have things automatically downloaded if needed. I feel that `allennlp.common.file_utils.cached_path` provides many useful features (e.g., download from S3 and Google Cloud Storage, archive extraction, ETag check, the cached-path command, etc).

**Describe the solution you'd like**
Move `cached_path` to a new repo (including command and tests) and make it a PyPI package. I believe it's not a lot of a big effort. In the beginning there may be set up, but I believe that only the commits that have been related to this function would be the ones that would be to that repo instead.

We're helping the rest of the community with this. Sometimes we can help from AllenNLP but sometimes from other useful tools, even beyond people not using AllenNLP.

I think such a Python package should under AllenAI name (`allenai` GitHub organization) because to me seems the one that deserves the most credit for it. I have my own version, but I'd prefer if this organization did it and had the ownership and credit for it unless you oppose this packaging idea.

**Describe alternatives you've considered**
I have seen people copying it around (e.g., [huggingface/transformers](https://github.com/huggingface/transformers/blob/master/src/transformers/file_utils.py)). However, new features are being added to it and the complexity increases over time. It reaches a point that it makes sense IMHO for it to live on its own repo and library.

**Additional context**
[rust-cached-path](https://github.com/epwalsh/rust-cached-path) is an example of the same idea but in Rust.

**Comment by JohnGiorgi** [comment]
This would be awesome, I find `cached_path` really useful, and in the past, I have `added` allennlp as a dependency when really all I wanted was `cached_path`!

**Comment by AkshitaB** [comment]
@bryant1410 and @JohnGiorgi That's a really good point! We will move it to a separate library.

**Comment by dirkgr** [comment]
I'm open to this idea, but unless @AkshitaB or @epwalsh are really excited to do it, I don't think we can neglect our other responsibilities to do this. @bryant1410 or @JohnGiorgi, if you want to do it, I'll make you collaborators on a repo so you can get it done. Let me know!

`cached_path()` recently acquired new functionality, and it's now compatible with HuggingFace models and datasets. I also have thoughts to add Weights&Biases support at some point.

**Comment by bryant1410** [comment]
@dirkgr I can allocate some (little) time for it. Can you create the repo and make me collab then? I'd be happy to have some help, esp. w code reviews.

**Comment by dirkgr** [comment]
Can you see https://github.com/allenai/cached_path? You have write access there. Let me (or @AkshitaB, who has set all this up) know if you run into trouble with it!

**Comment by bryant1410** [comment]
> Can you see https://github.com/allenai/cached_path? You have write access there. Let me (or @AkshitaB, who has set all this up) know if you run into trouble with it!

I can, thanks!

**Comment by AkshitaB** [comment]
@bryant1410 We have created and released a version of `cached_path` here: https://github.com/allenai/cached_path .

**Comment by bryant1410** [comment]
Oh, awesome! Thanks! I was working on a branch called `pilot` there that I see it doesn't exist anymore. But it's fine cause I hadn't advanced much (mainly filter out which files should be kept from this repo).
