### ISSUE TITLE
Give BeamSearch access to the vocabulary for more useful Constraints

### ISSUE THREAD

**Issue by JohnGiorgi** [allenai/allennlp#5311]
**Is your feature request related to a problem? Please describe.**

The [`Contraint`](https://github.com/allenai/allennlp/blob/39d7e5ae06551fe371d3e16f4d93162e55ec5dcc/allennlp/nn/beam_search.py#L530) class was recently introduced as a way to constrain beam search. I think it would be more useful if the class had access to the same `vocab` object as the model.

To motivate this, imagine a semantic parsing task where the goal is to go from natural language query --> SQL. The constraints could be written to ensure that the output is valid SQL. For this to work, the `Constraint` would need access to the target vocabulary, so it could zero-out the indices corresponding to invalid predictions at each timestep.

**Describe the solution you'd like**

The most straightforward solution I can think of is:

- Add `vocab` as an argument to the `BeamSearch` constructor.
- Add `vocab` as an argument to the `Constraint` constructor.
- Construct the `constraints` argument to `BeamSearch` lazily with `Lazy`. Then you could pass `vocab` to each constraint with `construct()` in the `BeamSearch` constructor.

**Describe alternatives you've considered**

It is entirely plausible there is a better solution! I am also not sure whether it would make sense to make `vocab` optional for `BeamSearch` and `Constraint`, so that this change would be backwards compatible.

I am happy to implement this solution, or an alternative suggestion in a PR.

**Additional context**

The docstring of `Constraint` reinforces the idea of needing access to the `vocab`:

https://github.com/allenai/allennlp/blob/39d7e5ae06551fe371d3e16f4d93162e55ec5dcc/allennlp/nn/beam_search.py#L553-L556

AFAICT setting the log probability to a negligible value would require that we know its index, which in turn would require us to have access to the `vocab`. I guess a counterexample is the existing [`RepeatedNGramBlockingConstraint`](https://github.com/allenai/allennlp/blob/39d7e5ae06551fe371d3e16f4d93162e55ec5dcc/allennlp/nn/beam_search.py#L627) subclass, but this is simpler as it just needs to look for repeated indices.

**Comment by epwalsh** [comment]
Hey @JohnGiorgi, your proposed solution sounds good as long as we can keep backwards compatibility.  The two main things for backwards compatibility are:

1. making the `vocab` argument optional (like you said), and
2. making the `constraints` argument `Optional[Union[List[Constraint], List[Lazy[Constraint]]]]`.

But (2) is not as big of a concern because `Optional[List[Constraint]]` will work the same as `Optional[List[Lazy[Constraint]]]` from configuration files, so it really only affects backwards compat when using these classes directly. And I'm not positive the `FromParams` logic can properly handle (2) at the moment anyway.

**Comment by JohnGiorgi** [comment]
@epwalsh Cool, thanks for the guidance! I opened a PR. 

As for 2, I found that I had to use `Optional[List[Lazy[Constraint]]]` and then call `construct` on each constraint (whether or not `vocab` was provided). Otherwise, I get an `AttributeError` with a message like: `<Constraint> has no method `construct`.

**Comment by epwalsh** [comment]
@JohnGiorgi, ah, right. I guess `FromParams` will treat each item in the list as `Constraint` instead of `Lazy[Constraint]` if you give it that option. So yea, let's just go with `Optional[List[Lazy[Constraint]]]`.
