### ISSUE TITLE
The demo menu wraps poorly at the most dominant resolution.

### ISSUE THREAD

**Issue by codeviking** [allenai/allennlp#532]
Per Google Analytics, the most common smallest resolution is 1280px wide.

At that resolution, after the addition of Named Entity Recognition, the menu looks like so:

![image](https://user-images.githubusercontent.com/801451/33152591-3ec882f8-cf92-11e7-9912-ae5948d97817.png)

We should probably fix this :).

**Comment by schmmd** [comment]
Beautiful!

**Comment by aaronsarnat** [comment]
For comparison, this is what the menu looked like in its original iteration:

![image](https://user-images.githubusercontent.com/8367927/33153729-6a137dc2-cf98-11e7-812b-a5911a4b989e.png)

The main problem is that there's too much horizontal text in the nav now. The tab count is growing and each tab label is now longer than it was before.

So we may need to rethink the UI design here. Would be good to figure out what a realistic max # of models and max char count might look like going forward and design backwards from there.

**Comment by matt-gardner** [comment]
It's probably safe to assume that we will have more tasks than will fit horizontally like that.  We're only going to add more.

**Comment by aaronsarnat** [comment]
Makes sense. Any insight into how many more we might add over time? More than a few?

If so, we'd probably need to ditch the tabs and go with a different selection UI (e.g. dropdown list or something else).

**Comment by matt-gardner** [comment]
In the relatively near future: at least two different kinds of semantic parsing, and document-level QA.  I think we probably want a different selection UI.
