### ISSUE TITLE
What is the recommended way to use different random seeds for my experiments?

### ISSUE THREAD

**Issue by entslscheia** [allenai/allennlp#5323]
To reduce the variance in my experiments, sometimes I need to try different random seeds for my experiments. This is very straightforward if I am writing my own PyTorch code. For Allennlp, to achieve this, I need to hack its source code every time (i.e., change all the random seeds [here](https://github.com/allenai/allennlp/blob/56e1f49df918cff52707d64dcf894885250aaf89/allennlp/common/util.py#L224)).

Is there more elegant way to do it? For example, a way to do it in a configuration file?

**Comment by epwalsh** [comment]
In a configuration file, you should set these three options (at the top level):

```json
{
  "random_seed": X,
  "numpy_seed": Y,
  "pytorch_seed": Z,
}
```
