### ISSUE TITLE
Consultation for collaboration: adding Optuna logic to `allennlp.commands.train` module

### ISSUE THREAD

**Issue by himkt** [allenai/allennlp#5338]
**Is your feature request related to a problem? Please describe.**
I come here to ask the AllenNLP team to collaborate with Optuna.

**Describe the solution you'd like**
- Adding the Optuna related logic to `allennlp.commands.train`.

**Describe alternatives you've considered**
- Adding the logic to Optuna (https://github.com/optuna/optuna/pull/2796)

**Additional context**

---

Hello AllenNLP team, I created this issue to ask if it is possible to put Optuna's logic into the AllenNLP side.

Our motivation for this is to support the Optuna pruning feature in the AllenNLP distributed training situation.
Optuna provides the integration module for AllenNLP, which enables users to optimize hyperparameters of their models.

This integration works well basically but there is one problem: pruning feature in distributed training. The current implementation of AllenNLP integration uses environment variables to load Optuna stuff on the AllenNLP side, which is problematic in spawned processes (ref. https://github.com/himkt/allennlp-optuna/issues/20, https://github.com/optuna/optuna/issues/1990).

To solve this problem, I make the PR on Optuna (https://github.com/optuna/optuna/pull/2796) to pass an Optuna object to AllenNLP directly. Indeed, it solves the problem but it needs to replicate a source code of `train.py`. I'm just wondering if we can collaborate with the AllenNLP team and add the change to the AllenNLP repo. Changes would be like the following: https://github.com/himkt/allennlp/pull/46 (I also think we can make this dependency optional by using invoke import inside a try-except block).

If there is room to consider, I want to discuss this topic. Or if there are other solutions for the issue, I want to know. 😸

**Comment by AkshitaB** [comment]
@himkt This sounds good. We would like to be able to support Optuna more directly. Please open a PR with the proposed changes in your fork!

**Comment by himkt** [comment]
Thank you @AkshitaB, I'm so happy to hear the response!
I'll make a PR.

**Comment by himkt** [comment]
@AkshitaB 

I'm sorry for being inactive. :bow:

We're working on implementing a new callback for the data distributed situation on https://github.com/optuna/optuna/pull/2796.
And I opened this issue based on the discussion https://github.com/optuna/optuna/pull/2796#discussion_r678716480).

However, during the discussion with other committers of Optuna, we found that my approach introduces a bidirectional dependency between Optuna and AllenNLP and they told me that we should avoid it.
https://github.com/optuna/optuna/pull/2796#pullrequestreview-731173212

So, for now, let me close this issue. But I'm still strongly interested in the closer collaboration with AllenNLP. If I find some reasonable approach, I'll open another issue and I want to discuss it with AllenNLP team!

Thank you so much for giving us the opportunity!
