### ISSUE TITLE
Interactive Coref Resolution highlighting in the demo creates odd text wrapping

### ISSUE THREAD

**Issue by aaronsarnat** [allenai/allennlp#535]
This highlight style works well as a static highlight (e.g. as used in `Machine Comprehension`), but not as well for interactive `Coreference Resolution` highlighting.

We probably need to tweak the CSS or add a special highlight style for Coref that doesn't affect text wrapping.

![coref](https://user-images.githubusercontent.com/8367927/33154207-a9f15506-cf9b-11e7-95a0-8b236ec0a3c9.gif)

**Comment by schmmd** [comment]
Honestly--this should be addressed by someone doing a complete pass over this demo.  I'm eager to see if we get a headcount to share between Euclid and AllenNLP for fullstack engineering.

**Comment by matt-gardner** [comment]
@DeNeutoy, this is fixed, right?

**Comment by schmmd** [comment]
This exact issue is resolved.  See http://staging.allennlp.org/coreference-resolution/NTIyOA==.
