### ISSUE TITLE
LogWriter log_batch missing metrics?

### ISSUE THREAD

**Issue by teffland** [allenai/allennlp#5351]
## Checklist

- [x] I have verified that the issue exists against the `main` branch of AllenNLP.
- [x] I have read the relevant section in the [contribution guide](https://github.com/allenai/allennlp/blob/main/CONTRIBUTING.md#bug-fixes-and-new-features) on reporting bugs.
- [x] I have checked the [issues list](https://github.com/allenai/allennlp/issues) for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/allenai/allennlp/pulls) for existing proposed fixes.
- [x] I have checked the [CHANGELOG](https://github.com/allenai/allennlp/blob/main/CHANGELOG.md) and the [commit log](https://github.com/allenai/allennlp/commits/main) to find out if the bug was already fixed in the main branch.
- [x] I have included in the "Description" section below a traceback from any exceptions related to this bug.
- [x] I have included in the "Related issues or possible duplicates" section beloew all related issues and possible duplicate issues (If there are none, check this box anyway).
- [x] I have included in the "Environment" section below the name of the operating system and Python version that I was using when I discovered this bug.
- [ ] I have included in the "Environment" section below the output of `pip freeze`.
- [ ] I have included in the "Steps to reproduce" section below a minimally reproducible example.

## Description

Just updated from v0.9 to v2.6, switched to using callbacks and noticed that my metrics were not logging to tensorboard or wandb at the batch level anymore (used to be under `epoch_metrics/*`, now they're only per epoch.

Looking at the source code for [`LogWriterCallback`](https://github.com/allenai/allennlp/blob/main/allennlp/training/callbacks/log_writer.py#L229-240) I see that in `log_batch` the method takes the `metrics` but doesn't use them, instead only using `("batch_loss", "batch_reg_loss")` in `metrics_to_log`.

Shouldn't `metrics_to_log` also contain the entries from the input `metrics` dict?  Or perhaps I'm missing some other configuration option to control this?

<details>
<summary><b>Python traceback:</b></summary>
<p>

```
```

</p>
</details>

## Related issues or possible duplicates

- None

## Environment

OS: Linux ubuntu 18.04

Python version: 3.7.1

<details>
<summary><b>Output of <code>pip freeze</code>:</b></summary>
<p>

```
```

</p>
</details>

## Steps to reproduce

<details>
<summary><b>Example source:</b></summary>
<p>

```
```

</p>
</details>

**Comment by dirkgr** [comment]
We talked about it, and could not remember why we did it this way. So I made a PR that logs all the metrics in #5362.
