### ISSUE TITLE
the last decoding step miscalculated in the forward_loss of CopyNet?

### ISSUE THREAD

**Issue by GregoryZeng** [allenai/allennlp#5354]
## Checklist

- [x] I have verified that the issue exists against the `main` branch of AllenNLP.
- [x] I have read the relevant section in the [contribution guide](https://github.com/allenai/allennlp/blob/main/CONTRIBUTING.md#bug-fixes-and-new-features) on reporting bugs.
- [x] I have checked the [issues list](https://github.com/allenai/allennlp/issues) for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/allenai/allennlp/pulls) for existing proposed fixes.
- [x] I have checked the [CHANGELOG](https://github.com/allenai/allennlp/blob/main/CHANGELOG.md) and the [commit log](https://github.com/allenai/allennlp/commits/main) to find out if the bug was already fixed in the main branch.
- [x] I have included in the "Description" section below a traceback from any exceptions related to this bug.
- [ ] I have included in the "Related issues or possible duplicates" section beloew all related issues and possible duplicate issues (If there are none, check this box anyway).
- [ ] I have included in the "Environment" section below the name of the operating system and Python version that I was using when I discovered this bug.
- [ ] I have included in the "Environment" section below the output of `pip freeze`.
- [ ] I have included in the "Steps to reproduce" section below a minimally reproducible example.

## Description

Hi, I was recently reading through the implementation of [CopyNet](https://github.com/allenai/allennlp-models/blob/main/allennlp_models/generation/models/copynet_seq2seq.py), which is rather delicate :)

In the forward_loss of CopyNet, I find a conditional statement that determines if the target of the current step is the END token (See Line [526)](https://github.com/allenai/allennlp-models/blob/31649f5776522ae60661499c595f73e1c019d72c/allennlp_models/generation/models/copynet_seq2seq.py#L526). 
```python
            # If the previous target token was copied, we use the special copy token.
            # But the end target token will always be THE end token, so we know
            # it was not copied.
            if timestep < num_decoding_steps - 1:
                # Get mask tensor indicating which instances were copied.
                # shape: (batch_size,)
                copied = (
                    (input_choices == self._oov_index) & (target_to_source.sum(-1) > 0)
                ).long()
                # shape: (batch_size,)
                input_choices = input_choices * (1 - copied) + copy_input_choices * copied
                # shape: (batch_size, source_sequence_length)
                target_to_source = state["source_token_ids"] == target_token_ids[
                    :, timestep + 1
                ].unsqueeze(-1)
```

However, Line [497](https://github.com/allenai/allennlp-models/blob/31649f5776522ae60661499c595f73e1c019d72c/allennlp_models/generation/models/copynet_seq2seq.py#L497) has already excluded the potential END token. Therefore I am confused if the if-statement is correct in Line 526.

```python
        # The last input from the target is either padding or the end symbol.
        # Either way, we don't have to process it.
        num_decoding_steps = target_sequence_length - 1
```

## Related issues or possible duplicates

- None

## Environment

OS:

Python version:

<details>
<summary><b>Output of <code>pip freeze</code>:</b></summary>
<p>

```
```

</p>
</details>

## Steps to reproduce

<details>
<summary><b>Example source:</b></summary>
<p>

```
```

</p>
</details>

**Comment by epwalsh** [comment]
@GregoryZeng thank you for digging into this and posting such a clear, detailed bug report :)

I think you are absolutely right. Would you like to make a pull request to fix this? Once you've opened the pull request I can run a CopyNet experiment to validate that the generalization performance with this change either stays roughly the same or increases.

**Comment by GregoryZeng** [comment]
Sure, please have a look at the PR.

**Comment by epwalsh** [comment]
Thanks @GregoryZeng...

I was just thinking about this some more, and now I actually think the implementation correct, although this comment on [lines 495-496](https://github.com/allenai/allennlp-models/blob/31649f5776522ae60661499c595f73e1c019d72c/allennlp_models/generation/models/copynet_seq2seq.py#L495-L496) is misleading:

```python
        # The last input from the target is either padding or the end symbol.
        # Either way, we don't have to process it.
        num_decoding_steps = target_sequence_length - 1
```

`target_tokens["tokens"]["tokens"]` includes a `START` token at the beginning and an `END` token (plus padding, potentially) at the end. We actually DO process the `END` token, i.e. the score for the end token contributes to the loss. But NOT the `START` token. So this comment is misleading because `num_decoding_steps` is `target_sequence_length - 1` because we don't process the FIRST target token, not the last.

Does that make sense? If so, maybe you could just fix the comment in your PR?

This other comment on [line 524](https://github.com/allenai/allennlp-models/blob/31649f5776522ae60661499c595f73e1c019d72c/allennlp_models/generation/models/copynet_seq2seq.py#L524) is also not quite right:

```python
            # But the end target token will always be THE end token, so we know
            # it was not copied.
            if timestep < num_decoding_steps - 1:
```

I think it should read

```python
            # But the last target token will always be either the END token or padding, so we know
            # it was not copied.
            if timestep < num_decoding_steps - 1:
```

**Comment by GregoryZeng** [comment]
> I was just thinking about this some more, and now I actually think the implementation correct, although this comment on lines 495-496 is misleading:

Oh sorry, I am not sure if I follow you. Do you mean that the original implementation is still correct and only the misleading comments need to be rephrased? Or that the change in my PR is correct and need extra changes on the comments？

**Comment by epwalsh** [comment]
> Do you mean that the original implementation is still correct and only the misleading comments need to be rephrased?

Yes

**Comment by GregoryZeng** [comment]
It is still unclear to me...

If the original implementation was correct, then the conditional expression in [Line 526](https://github.com/allenai/allennlp-models/blob/31649f5776522ae60661499c595f73e1c019d72c/allennlp_models/generation/models/copynet_seq2seq.py#L526) is always false when `timestep == num_decoding_steps - 1`,  which makes it impossible for the `input_choices` (the token right before the potential `<END>` token) to be a `<COPY>` token (See Line 529). Wouldn't it be a problem?

**Comment by epwalsh** [comment]
It's not super clear, but when `timestep` is used as an index, it's always incremented by 1. For example: [line 536](https://github.com/allenai/allennlp-models/blob/31649f5776522ae60661499c595f73e1c019d72c/allennlp_models/generation/models/copynet_seq2seq.py#L536). So were really looking into `target_tokens` shifted over by 1 to ignore the `START` symbol

**Comment by GregoryZeng** [comment]
>  but when timestep is used as an index, it's always incremented by 1.

[Line 522](https://github.com/allenai/allennlp-models/blob/31649f5776522ae60661499c595f73e1c019d72c/allennlp_models/generation/models/copynet_seq2seq.py#L522) uses `timestep` as an index. 
```python
input_choices = target_tokens["tokens"]["tokens"][:, timestep]
```

>So were really looking into target_tokens shifted over by 1 to ignore the START symbol

My point is that for every iteration in the for-loop, we are predicting `target_tokens["tokens"]["tokens"][:, timestep + 1]` using the `target_tokens["tokens"]["tokens"][:, timestep]` (or the `COPY` token) as the input to the RNN decoder. When `timestep == num_decoding_steps - 1`, we are predicting the `END` token and the input of the RNN decoder could be a `COPY` token in some cases. However, the if-statement in Line 526 only allows an `OOV` token as the input, which is incorrect?

**Comment by epwalsh** [comment]
Ah yes, you're right. I misunderstood my own code 🤦😅

I'll give the PR a review today 🙂 Thanks for sticking with this!

**Comment by GregoryZeng** [comment]
Hahaha, nevermind. I learnt a lot from your code 😁
