### ISSUE TITLE
Option for creating Vocabulary from pretrained transformers and instances

### ISSUE THREAD

**Issue by amitkparekh** [allenai/allennlp#5355]
**Is your feature request related to a problem? Please describe.**
I like removing boilerplate from code and using the training configs as much as possible. 

The vocab created from instances with `PretrainedTransformerTokenzier` and `PretrainedTransformerIndexer` do not update the vocab with the model's entire vocab. I understand that this might not be desired behaviour, which is why `Vocabulary.from_pretrained_transformer` exists. 

But this doesn't help if I want to create a vocab from both instances and the pretrained transformer. Building a multitask model, I've found that I would like this feature. 

**Describe the solution you'd like**
An additional constructor for creating the vocab from both instances and the pretrained transformer. The construction should support multiple model names for various namespaces, which are likely used in multitask models.  

In my training config, I would like it to just be this (where the keys are the namespace, and values are the model name).

```jsonnet
  vocabulary: {
    type: 'from_instances_and_pretrained_transformers',
    transformers: {
      text_tags: bert-base-uncased,
    },
  },
```

**Describe alternatives you've considered**

Users could  extend the vocabulary during the `__init__` of their classes, but this would result in repeated code for each namespace they want to extend. 

For example, extending a single namespace with one model would result in: 

```python
...

tokenizer = PretrainedTransformerTokenizer(model_name='bert-base-uncased')
vocab.add_transformer_vocab(tokenizer.tokenizer, namespace='text-tags')

...
```

but if there were multiple models, you'd probably end up seeing: 

```python
...

tokenizer_bert = PretrainedTransformerTokenizer(model_name='bert-base-uncased')
tokenizer_camembert = PretrainedTransformerTokenizer(model_name='camembert-base')
vocab.add_transformer_vocab(tokenizer_bert.tokenizer, namespace='text-tags')
vocab.add_transformer_vocab(tokenizer_camembert.tokenizer, namespace='text-tags')

...
```

**Additional context**

I tried implementing my solution [here](https://github.com/amitkparekh/allennlp/commit/c93823d4001e34f77f1731269a9821fef05a1c15) and it works as I described above with the additional tokens being added to the vocab from the transformer. 

---

**Edit**

I realised I came across this feature because I was trying to do things before the `init` of module within my model. I now see that the vocab is indexed after the model is initialised, so this is not _really_ necessary. But https://github.com/allenai/allennlp/discussions/5353_ shows that there is some demand.

But that brings up a different problem when I need the vocab size during model initialisation but it's not accurate until after the model is fully constructed. 

I thought about closing but I feel like this has some use if this functionality is desired? Feel free to just close this if it's of no use to anyone!

**Comment by dirkgr** [comment]
I think that would be a fine additional `Vocabulary` constructor. Can you make it into a PR, with a small test? I'd be happy to review it.

**Comment by amitkparekh** [comment]
@dirkgr — Just submitted a PR!
