### ISSUE TITLE
AllenNLP installation issue - No matching distribution found for torchvision<0.9.0,>=0.8.1

### ISSUE THREAD

**Issue by sandeepbhutani304** [allenai/allennlp#5375]
As per demos, we are expected to install AllenNLP using following command:
`pip install allennlp==2.1.0 allennlp-models==2.1.0
`
But it always throws error:
```
  ERROR: Could not find a version that satisfies the requirement torchvision<0.9.0,>=0.8.1 (from allennlp==2.1.0) (from versions: 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.2.1, 0.2.2, 0.2.2.post2, 0.2.2.post3, 0.3.0, 0.4.1, 0.5.0, 0.9.0, 0.9.1, 0.10.0)
ERROR: No matching distribution found for torchvision<0.9.0,>=0.8.1 (from allennlp==2.1.0)
```

Have tried installing torchvision separately but the version demanded by AllenNLP is not available at all. As can be seen in error above the torchvision<0.9.0,>=0.8.1 is demanded, but the available versions are ... 0.5.0, 0.9.0 ...    
What am I missing ?

**Comment by AkshitaB** [comment]
@sandeepbhutani304 Can you specify what python version you are using? I was able to successfully install `allennlp==2.1.0` and `allennlp-models==2.1.0` in a python3 environment. It was able to find and install `torchvision==0.8.2`.

**Comment by david-waterworth** [comment]
How are you installing pytorch? You need to pass the -f argument to pip, i.e.

`pip3 install torch==1.8.2+cu111 torchvision==0.9.2+cu111 torchaudio==0.8.2 -f https://download.pytorch.org/whl/lts/1.8/torch_lts.html`

The easiest way is to go to https://pytorch.org/get-started/locally/ and select the appropriate options then copy the command.
