### ISSUE TITLE
PytorchSeq2VecWrapper documentation

### ISSUE THREAD

**Issue by david-waterworth** [allenai/allennlp#5385]
The docuemntation for PytorchSeq2VecWrapper states:

    Note that we *require* you to pass sequence lengths when you call this module, to avoid subtle
    bugs around masking.  If you already have a `PackedSequence` you can pass `None` as the
    second parameter.

https://github.com/allenai/allennlp/blob/28950215344900e5e04fa5c8a27e5753d4e8837e/allennlp/modules/seq2vec_encoders/pytorch_seq2vec_wrapper.py#L38

Yet the second parameter of forward is `mask` rather than `length` so this doesn't appear to be the case, perhaps it was changed at some point?

**Comment by gabeorlanski** [comment]
I _think_ that the documentation is equating `masks` to be sequence lengths as they functionally can be thought of as sequence lengths. 

Say you have the following inputs:

```python
[
	["This","is", "a", "sequence"],
	["hello","world","[PAD]","[PAD]"],
	["hello","[PAD]","[PAD]","[PAD]"]
]
```

Then the `mask` for  these would be:
```python
[
	[1,1,1,1],
	[1,1,0,0],
	[1,0,0,0]
]
```

Even though both are of shape `(3,4)`, the lengths for each sequence are `[4,2,1]`. These masks are used later in [`self.sort_and_run_forward`](https://github.com/allenai/allennlp/blob/28950215344900e5e04fa5c8a27e5753d4e8837e/allennlp/modules/encoder_base.py#L33) function that is called in [line 80](https://github.com/allenai/allennlp/blob/28950215344900e5e04fa5c8a27e5753d4e8837e/allennlp/modules/seq2vec_encoders/pytorch_seq2vec_wrapper.py#L80)  of `PytorchSeq2VecWrapper.forward`.

I will update those docs to better reflect that the mask is required if are not passing in a `PackedSequence`.

**Comment by david-waterworth** [comment]
Thanks, BTW the Seq2Seq document is correct

    Note that we *require* you to pass a binary mask of shape (batch_size, sequence_length)
    when you call this module, to avoid subtle bugs around masking.  If you already have a
    `PackedSequence` you can pass `None` as the second parameter.
