### ISSUE TITLE
ImportError: cannot import name 'Token'

### ISSUE THREAD

**Issue by Tianxu-Jia** [allenai/allennlp#540]
Hell, 
Please help me with this problem

```
Python 3.6.3 (default, Oct  6 2017, 08:44:35) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from allennlp.data import Token
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'Token'
```

Many thanks

**Comment by DeNeutoy** [comment]
Please provide the full stack trace, otherwise it will be hard for us to help you.

**Comment by matt-gardner** [comment]
It looks like this is from an interpreter, where the first command entered is `from allennlp.data import Token`.  The fact that this fails means there's something wrong with your environment.  How did you install allennlp?  Can you run `import allennlp`?

**Comment by Tianxu-Jia** [comment]
import allennlp
from allennlp.data.fields import TextField, LabelField
from allennlp.data.token_indexers import SingleIdTokenIndexer

All those above are fine.

Only the problem with : from allennlp.data import Token

python3
Python 3.6.3 (default, Oct  6 2017, 08:44:35) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from allennlp.data.fields import TextField, LabelField
>>> from allennlp.data.token_indexers import SingleIdTokenIndexer
>>> import allennlp
>>> from allennlp.data import Token
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'Token'
>>>

**Comment by Tianxu-Jia** [comment]
I install AllenNLP using pip3

pip install allennlp
