### ISSUE TITLE
How to train AllenNLP SRL on non-English languages?

### ISSUE THREAD

**Issue by IHMCBrodie** [allenai/allennlp#5401]
I know the description said to ask the question on stackoverflow with the allennlp tag rather than here, which is what I did, but some of the questions there have gone a couple weeks without any activity so I was hoping to make the question more visible here: https://stackoverflow.com/questions/69090025/how-to-train-allennlp-srl-on-non-english-languages.

I know you all are probably busy so if it's just a waiting game that's fine, just didn't want the questions to go missed because they were on stackoverflow. 

Thanks in advance.

**Comment by AkshitaB** [comment]
Answered: https://stackoverflow.com/a/69230677/14421634
