### ISSUE TITLE
Does Allennlp have support for LayoutLMv2 Transoformer?

### ISSUE THREAD

**Issue by 12seetharaman** [allenai/allennlp#5402]
[LayoutLMv2](https://huggingface.co/transformers/model_doc/layoutlmv2.html) is a visual-rich document understanding model in hugging face. 
Is it compatible with Allennlp?

If not, please give me a direction in Allennlp design style. I would like to contribute.

**Comment by AkshitaB** [comment]
@12seetharaman Can you clarify what you mean by "compatible" with AllenNLP? You can always load a hugginface model with allennlp, and wrap your own allennlp code around it, for instance [here](https://github.com/allenai/allennlp-models/blob/main/allennlp_models/mc/models/transformer_mc_tt.py). 

We will be happy to provide help if you would like to contribute this model. Feel free to open a PR where we can discuss the code in more detail.

**Comment by 12seetharaman** [comment]
@AkshitaB,
I meant, Can we use the [layoutlmv2](https://huggingface.co/microsoft/layoutlmv2-base-uncased) model with Allennlp.

I tried to test the model with Allennlp. But, I wasn't able to initialize the layoutlmv2 pretrained tokenizer in the dataset reader. Getting error on `_reverse_engineer_special_tokens`

Used below config for tokenizer,

`"tokenizer": {
	"type": "pretrained_transformer",
	"model_name": "microsoft/layoutlmv2-base-uncased"
}`

**Error**:
`home/env/lib/python3.8/site-packages/allennlp/data/tokenizers/pretrained_transformer_tokenizer.py\\", line 76, in __init__\\n    self._reverse_engineer_special_tokens(\\"a\\", \\"b\\", model_name, tokenizer_kwargs)\\n!!   File \\"home/env/lib/python3.8/site-packages/allennlp/data/tokenizers/pretrained_transformer_tokenizer.py\\", line 109, in _reverse_engineer_special_tokens\\n    dummy_output = tokenizer_with_special_tokens.encode_plus(\\n!!   File \\"home/env/lib/python3.8/site-packages/transformers/models/layoutlmv2/tokenization_layoutlmv2_fast.py\\", line 430, in encode_plus\\n    return self._encode_plus(\\n!!   File \\"home/env/lib/python3.8/site-packages/transformers/models/layoutlmv2/tokenization_layoutlmv2_fast.py\\", line 639, in _encode_plus\\n    batched_output = self._batch_encode_plus(\\n!!   File \\"home/env/lib/python3.8/site-packages/transformers/models/layoutlmv2/tokenization_layoutlmv2_fast.py\\", line 493, in _batch_encode_plus\\n    encodings = self._tokenizer.encode_batch(\\n!! TypeError: PreTokenizedInputSequence must be Union[List[str], Tuple[str]]`

**Comment by AkshitaB** [comment]
@12seetharaman Can you specify versions for `allennlp` and `transformers`? I'm getting a different error in loading the model; which seems like an issue on HF side.

```~/local/code/allennlp/allennlp/data/tokenizers/pretrained_transformer_tokenizer.py in __init__(self, model_name, add_special_tokens, max_length, tokenizer_kwargs)
     64         from allennlp.common import cached_transformers
     65 
---> 66         self.tokenizer = cached_transformers.get_tokenizer(
     67             model_name, add_special_tokens=False, **tokenizer_kwargs
     68         )

~/local/code/allennlp/allennlp/common/cached_transformers.py in get_tokenizer(model_name, **kwargs)
    136     tokenizer = _tokenizer_cache.get(cache_key, None)
    137     if tokenizer is None:
--> 138         tokenizer = transformers.AutoTokenizer.from_pretrained(
    139             model_name,
    140             **kwargs,

~/virtuals/allennlp/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py in from_pretrained(cls, pretrained_model_name_or_path, *inputs, **kwargs)
    532         if config_tokenizer_class is None:
    533             if not isinstance(config, PretrainedConfig):
--> 534                 config = AutoConfig.from_pretrained(pretrained_model_name_or_path, **kwargs)
    535             config_tokenizer_class = config.tokenizer_class
    536 

~/virtuals/allennlp/lib/python3.8/site-packages/transformers/models/auto/configuration_auto.py in from_pretrained(cls, pretrained_model_name_or_path, **kwargs)
    450         config_dict, _ = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
    451         if "model_type" in config_dict:
--> 452             config_class = CONFIG_MAPPING[config_dict["model_type"]]
    453             return config_class.from_dict(config_dict, **kwargs)
    454         else:

KeyError: 'layoutlmv2'```

**Comment by 12seetharaman** [comment]
Thanks a lot, @AkshitaB. Really helpful.
I used transformers 4.10 and Allennlp 2.7.
As you said, the issue is on the HF layoutlmv2 tokenizer itself.
