### ISSUE TITLE
Evaluator Class to allow more metrics and saving of input tokens during evaluation

### ISSUE THREAD

**Issue by gabeorlanski** [allenai/allennlp#5405]
**Is your feature request related to a problem? Please describe.**
An `Evaluator` class similar would allow specifying more metrics to run and how to post-process the input batches for saving.  

**Describe the solution you'd like**

An `Evaluator` class similar to [`Trainer`](https://github.com/allenai/allennlp/blob/main/allennlp/training/trainer.py) that would have a key `evaluator` in the config. 

The class config would have:
- Metrics to call - Some metrics are too computationally intensive to be run during training, but there currently is no way to use them in `allennlp evaluate`.
- Source & target namespaces - Currently, when predictions are saved, there is no way to save the inputs and targets as well. It makes it difficult to compare multiple models on the same dataset without implementing some other alignment method. 

**Describe alternatives you've considered**
Modifying the [`evaluate`](https://github.com/allenai/allennlp/blob/48af9d3477733ec1b63f3351b8b80eab51e370fe/allennlp/training/util.py#L300) method required implementing more mixins to allow postprocessing the batch so that the inputs can be saved. 

For the metrics, I have yet to find a way (that is not done inside of the model) to have some metrics not run during training but do run during evaluation. 

This is something I could work on but wanted to see first if there was interest in such a feature.

**Comment by gabeorlanski** [comment]
@AkshitaB I had not thought of non-text data and agree it will get a lot more expensive. Maybe instead of saving the raw data, it saves an index of the corresponding instance? e.g.

```py
for idx, instance in dataset.iter_instances():
     save {idx:idx, prediction: model(instance}
```

Then, to align them, the user only needs to access the IDX of the dataset? That could have its issues, though, so maybe make one of the configurable properties of the `Evaluator` class be some id/key/way to save information for aligning the inputs with the predicted outputs?

For text specifically, I have found that there is no 'good' way to have a general-purpose decoder for the input and target. The biggest issue I ran into is sharing `start`, `end`, and `pad` tokens across the `trainer`, `dataset_reader`, and `loader` modules. This also applies to trying to share the necessary vocab namespaces as well.

 I have tried to use the `.jsonnet` features, but it makes the json configs messy and hard to work with. Plus, windows does not support it. I have two different solutions so far; one is [the AllenNLP-Hydra plugin I have been working on](https://github.com/gabeorlanski/allennlp-hydra) that will allow the use/conversion of [FAIR's Hydra](https://github.com/facebookresearch/hydra) style configs to AllenNLP.  It is not a _great_ solution b/c it introduces both an extra step to convert configs and is an additional dependency. I am still working on it and am trying to enable all commands to work with the hydra configs programmatically. 

The other solution I have used, which I will make a more in-depth issue since I think would be a helpful addition, would be a "compile" step that would initialize all of the classes before saving the configs. In this step, attributes can be passed between modules per user specification.

I am going to work on getting a draft PR for an evaluator class done!

**Comment by AkshitaB** [comment]
@gabeorlanski ```For text specifically, I have found that there is no 'good' way to have a general-purpose decoder for the input and target. The biggest issue I ran into is sharing start, end, and pad tokens across the trainer, dataset_reader, and loader modules. This also applies to trying to share the necessary vocab namespaces as well.```

Why do we need to share these tokens with the trainer and the loader?

**Comment by gabeorlanski** [comment]
> @AkshitaB  Why do we need to share these tokens with the trainer and the loader?

So the issue I have run into in the past is that when using transformers and their special tokens, I have been unable to automatically share them with the model so that it uses that instead of `END_SYMBOL`. For the loader, I guess it can be accessed through `loader.reader` attribute. But primarily this would be for the decoding and postprocessing in the `Evalutator` class. 

I should have a draft PR done by the end of the week.
