### ISSUE TITLE
Capture NLTK parsing errors in allennlp_models/common/ontonotes.py

### ISSUE THREAD

**Issue by chiarcos** [allenai/allennlp#5410]
OntoNotes in CoNLL-2012 format is frequently used for training and evaluation. However, it cannot be directly disseminated but needs to be locally re-built by every individual user, using two different pieces of third-party content and external scripts. In this constellation, the build scripts often break, and result in parsing errors.

Feature request:
- Instead of escalating parsing errors from NLTK and terminate, provide a more robust handling and produce a warning.
- This can be done by catching ValueErrors in line 347 in `_conll_rows_to_sentence` 

For system parameters and traceback of a real-world error, please see my original post @chiarcos in https://github.com/allenai/allennlp/issues/4065#issuecomment-919923373_

**Comment by chiarcos** [comment]
The problem re-occurs during evaluation:

	...
	  File "/home/chiarcos/shallow-srl/parser/allen-nlp/venv/lib/python3.6/site-packages/allennlp_models/structured_prediction/metrics/srl_eval_scorer.py", line 110, in __call__
		perl_script_command, stdout=subprocess.PIPE, universal_newlines=True, check=True
	  File "/usr/lib/python3.6/subprocess.py", line 438, in run
		output=stdout, stderr=stderr)
	subprocess.CalledProcessError: Command '['perl', '/home/chiarcos/shallow-srl/parser/allen-nlp/venv/lib/python3.6/site-packages/allennlp_models/structured_prediction/tools/srl-eval.pl', '/tmp/tmpwa4hcuty/gold.txt', '/tmp/tmpwa4hcuty/predicted.txt']' returned non-zero exit status 25.
		
and on the shell

	$> perl /home/chiarcos/shallow-srl/parser/allen-nlp/venv/lib/python3.6/site-packages/allennlp_models/structured_prediction/tools/srl-eval.pl /tmp/tmpwa4hcuty/gold.txt /tmp/tmpwa4hcuty/predicted.txt
	phrase_set->load_SE_tagging: some phrases are unclosed!

**Comment by schmmd** [comment]
Hi @chiarcos thanks for reporting this!  Unfortunately this isn't very close to our roadmap right now, and so we're unlikely to make this change ourselves.  You could open a PR, but we wouldn't know how to evaluate it exactly.  The original code worked for the original author's use case, and generally it's not best practice to just emit warnings when the input is malformed.

**Comment by chiarcos** [comment]
The problem here is that the data being processed is not the input, but an intermediate representation, so tracing it back to the actual input basically requires a lot of reverse-engineering. What would be better would be a validator for the input format. Then, the error could be prevented by fixing the data.
