### ISSUE TITLE
How do I finetune AllenNLP textual entailment model on my own dataset via transfer learning?

### ISSUE THREAD

**Issue by AyushiNM** [allenai/allennlp#5411]
I'd like to finetune the[ AllenNLP textual entailment](https://demo.allennlp.org/textual-entailment/elmo-snli) model on my own dataset by transfer learning, but I don't understand how to do that. I have reviewed the answers to these previously asked questions ([1](https://stackoverflow.com/questions/65840129/how-to-train-a-textual-entailment-model-with-my-own-training-set), [2](https://stackoverflow.com/questions/66844202/trouble-finetuning-decomposable-attention-model-in-allennlp)), but I'm still not sure about what needs to be done exactly. Are there any examples I can refer to? I'd really appreciate someone could help me. Thanks.

[Link to StackOverflow](https://stackoverflow.com/questions/69191548/how-do-i-finetune-allennlp-textual-entailment-model-on-my-own-dataset-via-transf)

**Comment by AkshitaB** [comment]
@AyushiNM If you would like to start with the AllenNLP model, you can use something like

```
"model": {
    "type": "from_archive",
    "archive_file": /path/to/archive/targz
    ...
}
```

This will load the allennlp model (or any other model that you are starting with), and then you can train it further.

**Comment by Atakey** [comment]
> @AyushiNM If you would like to start with the AllenNLP model, you can use something like
> 
> ```
> "model": {
>     "type": "from_archive",
>     "archive_file": /path/to/archive/targz
>     ...
> }
> ```
> 
> This will load the allennlp model (or any other model that you are starting with), and then you can train it further.

I find that the new model would inherit ‘requires_grad’ property that I can‘t change it when use config file with commands . It means that if  I want to unfreeze all params to make them trainable, using from_archive method doesn't work. Emmm,  what should I do ?
