### ISSUE TITLE
ConfigurationError: srl not in acceptable choices for dataset_reader.type

### ISSUE THREAD

**Issue by vinay1986** [allenai/allennlp#5432]
Get the following error when I run the following code:

```
from allennlp.predictors.predictor import Predictor

download = "https://storage.googleapis.com/allennlp-public-models/bert-base-srl-2020.09.03.tar.gz"
predictor = Predictor.from_path(download)
```

Same is the case for the code below:

```
from allennlp_models.pretrained import load_predictor
predictor = load_predictor("structured-prediction-srl-bert")
```

### ERROR

ConfigurationError: srl not in acceptable choices for dataset_reader.type: ['babi', 'conll2003', 'interleaving', 'multitask', 'multitask_shim', 'sequence_tagging', 'sharded', 'text_classification_json', 'sst_tokens', 'boolq', 'coref', 'preco', 'winobias', 'masked_language_modeling', 'next_token_lm', 'simple_language_modeling', 'copynet_seq2seq', 'seq2seq', 'cnn_dm', 'swag', 'commonsenseqa', 'piqa', 'fake', 'piqa_tt', 'quora_paraphrase', 'snli', 'transformer_superglue_rte', 'drop', 'qangaroo', 'quac', 'squad', 'squad1', 'squad2', 'transformer_squad', 'triviaqa']. You should either use the --include-package flag to make sure the correct module is loaded, or use a fully qualified class name in your config file like {"model": "my_module.models.MyModel"} to have it imported automatically.

**Comment by AkshitaB** [comment]
@vinay1986 This error should go away if you `import allennlp_models`. However, you will face a different error that's specific to `srl`. I am looking into it.

**Comment by vinay1986** [comment]
@AkshitaB - wondering if there has been an update around this?
