### ISSUE TITLE
loading user-defined model needs to initialize twice (the pretrained model part)

### ISSUE THREAD

**Issue by Zessay** [allenai/allennlp#5436]
**Is your feature request related to a problem? Please describe.**
I'm frustrated when loading a user-defined model which using pretrained model, the pretrained model parameters part need to initialize twice, the first time is from `pytorch_model.bin` and the second from `model.tar.gz`. However, the first time is unnecessary and useless. Meanwhile, if I want to send my finetuned model to others, I need to pack the `pytorch_model.bin` and `model.tar.gz` together into a package, the `pytorch_model.bin` is actually unnecessary but takes up a lot of storage of the package.

**Describe the solution you'd like**
Actually, the key problem is the `PretrainedTransformerEmbedder` class in `allennlp/modules/token_embedders/pretrained_transformer_embedder.py`. I hope when I pass `**/config.json` to the parameter `model_name` of the `PretrainedTransformerEmbedder` class, the transformer model can initialize with random parameters, then these parameters can reload from `model.tar.gz`. Thus, I only need to pack `config.json` without packing `pytorch_model.bin` to the final model package, which saves a lot of storage and is useful for industry.

**Describe alternatives you've considered**
I think the only modification needed is the function `cached_transformers`, we can consider a situation that user passes `**/config.json` to the parameter `model_name`. It means that the user only needs a randomly initialized transformer model.

```python
def get(****):
    ****
    if model_name.endswith("config.json"):
        config = AutoConfig.from_pretrained(model_name)
        self.transformer_model = AutoModel.from_config(config)
    else:
        global _model_cache
        *****
```

**Additional context**
The size of the final package is unconscious if we just perform experiments on local device, but it is important if we want to send the final model package to the cloud drive. At the same time, reducing a initialization process can also save some time.

**Comment by AkshitaB** [comment]
@Zessay There is a parameter called `load_weights` in cached_transformers, which can be set to False. `PretrainedTransformerEmbedder` also uses it: 

```load_weights: `bool`, optional (default = `True`)
        Whether to load the pretrained weights. If you're loading your model/predictor from an AllenNLP archive
        it usually makes sense to set this to `False` (via the `overrides` parameter)
        to avoid unnecessarily caching and loading the original pretrained weights,
        since the archive will already contain all of the weights needed.```

Let me know if this does not help with your case.
