### ISSUE TITLE
install spacy model via pip / requirements.txt instead of `spacy download`

### ISSUE THREAD

**Issue by joelgrus** [allenai/allennlp#544]
isn't that simpler?

https://spacy.io/usage/models#models-download

**Comment by schmmd** [comment]
WAY better!  Cool!

**Comment by schmmd** [comment]
It's easy to do in the `requirements.txt` but it wasn't working in the `setup.py`.  We'll put this on hold for now.

**Comment by schmmd** [comment]
@DeNeutoy is unsure this is something we actually want, and @joelgrus ran into challenges making this change.

**Comment by schmmd** [comment]
Well, I once again think this would be great to have--although I remember we ran into some issues.  If we installed spacy via pip, we could remove an instruction around installing allennlp via pip.

**Comment by schmmd** [comment]
Fixed by https://github.com/allenai/allennlp/pull/933
