### ISSUE TITLE
Is the 4-layer ELM variant available?

### ISSUE THREAD

**Issue by Superhzf** [allenai/allennlp#5446]
Hi,

I am reading the paper "Dissecting Contextual Word Embeddings: Architecture and Representation" by Allen Institute for AI, where the authors test a 4-layer ELMo variant. But I cannot find the weights and options on this page https://allennlp.org/elmo.

So, I would like to confirm whether this model is trained and available in this repo or not?

**Comment by epwalsh** [comment]
Hi @Superhzf, as far as I know we don't have those weights stored anywhere.

**Comment by Superhzf** [comment]
@epwalsh Thanks for your reply.
