### ISSUE TITLE
Predictor.from_path('coref-spanbert-large-2021.03.10.tar.gz') downloads model into cache though I provide a local copy of the model

### ISSUE THREAD

**Issue by irshadbhat** [allenai/allennlp#5448]
I am trying to load a local copy of the `coref-spanbert` model using `Predictor.from_path` but it starts downloading the model again into cache/huggingface. How do I fix this.

    >>> from allennlp.predictors import Predictor
    >>> coref_model = Predictor.from_path('coref-spanbert-large-2021.03.10.tar.gz')
    Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 414/414 [00:00<00:00, 436kB/s]
    Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 213k/213k [00:00<00:00, 239kB/s]
    Downloading:  34%|███████████████████████████████████████████████████

**Comment by epwalsh** [comment]
Hey @irshadbhat, there are a couple other threads on this:
- https://github.com/allenai/allennlp/issues/5456
- https://github.com/allenai/allennlp/issues/5436
- https://github.com/allenai/allennlp/pull/5172
