### ISSUE TITLE
Max Pooling Entity Extractor

### ISSUE THREAD

**Issue by MSLars** [allenai/allennlp#5449]
Several relation extraction approaches receive span representations through a max-pooling operation
Implementing such approaches (E.g. [RE-AGCN](https://github.com/cuhksz-nlp/RE-AGCN/blob/main/re_agcn_model.py) in lines 69 and 70) could benefit from a new module.

```python
@SpanExtractor.register("max_pooling")
class MaxPoolingSpanExtractor(SpanExtractorWithSpanWidthEmbedding):
```
Currently, I can't find such a component or a related feature request and I would offer to prepare a Merge Request if the idea seems useful.

**Comment by epwalsh** [comment]
Hi @MSLars, once you have a working implementation feel free to open a pull request.
