### ISSUE TITLE
Predictor `sanitize` is silently destructive

### ISSUE THREAD

**Issue by david-waterworth** [allenai/allennlp#5454]
I've implemented a NER model and since tokenization generally doesn't align exactly with the original text (i.e. addition of wordpiece prefixes ▁, converting to lowercase, dropping whitespace) it's not enough to simply return the list of tokens and concatenate, I need the start/end indices into the original text to decode the predicted span.

I thought this would be simple, I added a `MetadataField` to my data reader and stored the input text and its tokens.

However this didn't work, the list of `Token` types was silently converted to a list of `str` in the predictor (specifically in the `sanitize` method). This isn't mentioned in the docstring (which simply says "turns PyTorch and Numpy types into basic Python types so they can be serialized into JSON.").

I would expect that Token can be serialised to JSON, if not I would think it should be rather than silently converting it to a list of str. In particular, I don't believe a `MetadataField` should be sanitised any more than absolutely necessary since anything in it has presumably deliberately been added for downstream use, i.e. after sanatisation.

**Comment by epwalsh** [comment]
Hey @david-waterworth, I think you're right about this, and it is unfortunate. However I'm afraid that making this change could break a lot of things downstream 😕

The simplest work-around would probably be to just pre-serialize your tokens in the metadata fields, or when you return them from `Model.make_output_human_readable()`. Another option would be to use `SpanField` to encapsulate that information (the start/end indices into the original text).

**Comment by david-waterworth** [comment]
Thanks @epwalsh, yes I guess adding tokens to metadata as a List[str] instead of List[Token] and a separate List[SpanField] for the offsets would achieve what I need for now.
