### ISSUE TITLE
AllenNLP Models 2.8

### ISSUE THREAD

**Issue by pvcastro** [allenai/allennlp#5457]
I'm trying to upgrade AllenNLP to 2.8.0, but since AllenNLP models wasn't upgraded accordingly, I can't keep the new version. Isn't the models project going to get released to 2.8.0 too?

Thanks!

**Comment by AkshitaB** [comment]
@pvcastro The 2.8.0 version is now released for Allennlp-models: https://github.com/allenai/allennlp-models/releases/tag/v2.8.0
