### ISSUE TITLE
Fix for Issue with unbounded KL divergence in Fairness Metrics

### ISSUE THREAD

**Issue by seraphinatarrant** [allenai/allennlp#5458]
I've been using the Fairness Metrics (Independence, Separation, Sufficiency), the ones that were merged here: #5093.
And I've been having issues with the way they are implemented and am looking for suggestions.

Sufficiency is formally:
P(Y=y | R=r, Z=a) = P(Y=y | R=r, Z=b)  where Y is label, R is score, and Z is sensitive attribute (lets say a is female and b is male).
In allennlp it is implemented as the KL divergence between P(Y|Z=z, R=r) || P(Y|R=r) where Y is label, R is score, and Z is sensitive attribute. 
This is fine, except that there can be a case where a label is never predicted for a certain attribute (so there's a Y that is never predicted for females). In this case, the male KL divergence is 0 and the female gives a nan. Which makes sense since KL divergence requires that both distributions have the same support. 

But also this isn't a super rare scenario, it can come up quite easily. 
So I was looking for advice around ways we could fix this.

Wasserstein distance is sometimes used in fairness and doesn't have the same requirements as KL divergence, would that potentially be a substitute that get's around this problem?
If not, why is is a bad idea, and do you have other ideas?

At the moment I have a smoothing-esque hack to make it non-zero, but that feels, well, hacky.

**Comment by dirkgr** [comment]
@AkshitaB, and update?

**Comment by AkshitaB** [comment]
@seraphinatarrant Thank you for bringing this up. I'm not extremely familiar with the nuances of both metrics;  @ArjunSubramonian , who is the original author may have more thoughts on this. 

From an API standpoint, does having an option between KL divergence and Wasserstein distance work? The distance to be used can be defined when initializing the metric.

**Comment by ArjunSubramonian** [comment]
@seraphinatarrant thanks for your detailed issue! I agree that this is an issue given how frequently a label may not be predicted for instances belonging to a particular protected group. I think [this paper](https://arxiv.org/pdf/2102.10349.pdf) motivates using Wasserstein distance.

In line with what @AkshitaB said, I think we can modify the API to compute KL divergence, Wasserstein distance, or the ratios (e.g. for Sufficiency,  P(Y=y|Z=z, R=r) / P(Y=y|R=r), for each y). @seraphinatarrant, would you be able to make a PR for this?

**Comment by seraphinatarrant** [comment]
Ah thank you for the paper pointer, it was really interesting! I'd be happy to make a PR for this! Will update over the next few days when I carve out some time to. (Also I realise my reply to this bounced, so sorry for delay!)
