### ISSUE TITLE
Improving documentation, where to start?

### ISSUE THREAD

**Issue by KooTQ** [allenai/allennlp#5463]
Hi!
I love AllenNLP json/jsonnet config training process, the amount of models and available functionalities!
Unfortunately lacking documentation is in my opinion huge draw-back to understand and get into this library.
I would love to help with documenting - I spent a lot of time understanding context from code itself, it would be nice to reduce this hustle for the others.

In Your opinion, which parts and functionalities would benefit from extending documentation? Would examples in docstrings help? Is anything else missing?

I can see CLI commands as crucial parts which are  under-documented, with no examples outside of the guide.
Do you have any suggestions before my first PR?

**Comment by dirkgr** [comment]
Hi @KooTQ, more docs are always welcome. https://docs.allennlp.org/main/ is completely generated from the code in this repo. Not everything has to be docstrings. Maybe it would make sense to create another .md file explaining the command line uses, and we'll build it into the build process for the docs?
