### ISSUE TITLE
How to train first, then frozen some layers and fine-tune further?

### ISSUE THREAD

**Issue by Young1993** [allenai/allennlp#5465]
My allennlp==2.4.0
I use Roberta as encoder, mlp as decoder
my trainer config, I init train several epochs with this config
```
"optimizer": {
            "type": "adam",
            "lr": 0.000186,
            "parameter_groups": [
                [
                    [
                        "question_embedder"
                    ],
                    {
                        "lr": 3e-06
                    }
                ]
            ]
        }
```
Then I add the **no_grad**, and resume the model 
```
`"no_grad": [
            "question_embedder.*"
        ],`
```
The model parameters without grad are removed
But the optimizer throws the error `ValueError: loaded state dict contains a parameter group that doesn't match the size of optimizer's group` 

Then I change the "optimizer": 
`            "parameter_groups": [
                     [["question_embedder.*"], {"requires_grad": False}]
                ]`

but the error still exists.

How to fix this problem?
thanks for help

**Comment by AkshitaB** [comment]
@Young1993 I cannot reproduce the error without your entire config, but I found this: https://discuss.pytorch.org/t/error-when-loading-adam-optimizer-resume-training/50870 

From the discussion linked, it's possible that you are not freezing the layers again when you resume training. Can you try checking your parameters before saving and after loading, as suggested in the link?
