### ISSUE TITLE
error message: "zipfile.BadZipFile: File is not a zip file" after installation

### ISSUE THREAD

**Issue by eriktks** [allenai/allennlp#5467]
After installing AllenNLP, the command `allennlp` failed with the error message `zipfile.BadZipFile: File is not a zip file`

The problem disappeared by installing the popular data sets of NLTK

It would be good if these datasets were added automatically during installation

**Comment by AkshitaB** [comment]
@eriktks Can you share the entire stacktrace?

**Comment by heibangbang** [comment]
I also encountered this problem, can you explain the solution in detail
