### ISSUE TITLE
Custom data training for open information extraction/relation extraction

### ISSUE THREAD

**Issue by AlanQuille** [allenai/allennlp#5470]
Hi, I want to train AllenNLP with custom data for relation extraction e.g. John works at Apple (John = Entity1, relation = employedAt, Apple = Entity2). Is the training config file I have to change srl.jsonnet? What format does the custom data have to be in? Is there a sample one I can modify? Thank you very much.

**Comment by AkshitaB** [comment]
@AlanQuille Yes, our OpenIE model uses the srl.jsonnet config. You can find the format of the data here: https://github.com/gabrielStanovsky/supervised-oie/tree/master/data
