### ISSUE TITLE
Allow Embedding Extension for T5 Model

### ISSUE THREAD

**Issue by HarshTrivedi** [allenai/allennlp#5478]
I’m using T5 model implemented in allennlp, and need to add extra special tokens to its vocabulary.

I’ve added extra tokens in the tokenizer in my reader with `self._tokenizer.tokenizer.add_tokens(additional_tokens)`. But I also need to extend model’s token embeddings. Usually, when the transformer is loaded with `PretrainedTransformerEmbedder`, it’s taken care of by itself because of [this line](https://github.com/allenai/allennlp/blob/main/allennlp/modules/token_embedders/pretrained_transformer_embedder.py#L132). I can also do it by invoking HF’s `resize_token_embeddings` manually, but, T5 object here doesn’t have this method on it. The T5 object [here](https://github.com/allenai/allennlp-models/blob/main/allennlp_models/generation/models/t5.py#L32) is allennlp's module, so doesn't have HF methods like `resize_token_embeddings`.

My current solution is to manually extend T5 embeddings and lm_head, but it'd be good to have native support for this in allennlp.

@dirkgr Assigning you based on the discussion on slack.

**Comment by dirkgr** [comment]
Fixed in https://github.com/allenai/allennlp/pull/5497.
