### ISSUE TITLE
OSError: [Errno 95] Operation not supported | gradient_descent_trainer

### ISSUE THREAD

**Issue by 12seetharaman** [allenai/allennlp#5484]
I just recently updated my repository from Allennlp 2.3.0 to Allennlp 2.8.0.
Getting OSError while creating a link from model_state to best_model on Gradient descent trainer. Which is not in the 2.3 version.
I'm storing the model in fileshare.
`os.link(model_state_file, self._best_model_filename)`

```
    model = allentrain.train_model(
!!   File "/usr/local/lib/python3.8/dist-packages/allennlp/commands/train.py", line 254, in train_model
    model = _train_worker(
!!   File "/usr/local/lib/python3.8/dist-packages/allennlp/commands/train.py", line 504, in _train_worker
    metrics = train_loop.run()
!!   File "/usr/local/lib/python3.8/dist-packages/allennlp/commands/train.py", line 577, in run
    return self.trainer.train()
!!   File "/usr/local/lib/python3.8/dist-packages/allennlp/training/gradient_descent_trainer.py", line 769, in train
    metrics, epoch = self._try_train()
!!   File "/usr/local/lib/python3.8/dist-packages/allennlp/training/gradient_descent_trainer.py", line 916, in _try_train
    os.link(model_state_file, self._best_model_filename)
!! OSError: [Errno 95] Operation not supported
```

Is this need to be fixed on the Allennlp?

**Comment by epwalsh** [comment]
Hmm maybe we could fall back to a symbolic link when this happens? @dirkgr, thoughts?

**Comment by dirkgr** [comment]
No, it would need to fall back to making a copy. If we make a symbolic link, it'll go stale when the original file gets deleted. It'll be slow, but at least it'll work. Maybe we print a warning in that case?

**Comment by dirkgr** [comment]
What file share is this that doesn't support hard links?

**Comment by 12seetharaman** [comment]
It is Azure file share @dirkgr
