### ISSUE TITLE
Upload QA models to HF

### ISSUE THREAD

**Issue by dirkgr** [allenai/allennlp#5494]
- [x] bidaf
 - [x] bidaf-elmo
 - [x] transformer-qa
 - [x] naqanet

**Comment by dirkgr** [comment]
TransformerQA and Naqanet don't converge when training with the instructions in the demo :-(

**Comment by dirkgr** [comment]
@osanseviero, why did you write the `push-to-hf` command so that it renames the weights file to `model.th`? We expect `best.th` or better `weights.th`. Like this we don't load properly when I try to use ` hf://` URL.

**Comment by osanseviero** [comment]
As discussed offline indeed this is an issue in the push-to-hf command. Fixing this is a minor change in the pushing script.

**Comment by dirkgr** [comment]
@osanseviero, I just uploaded a second version, and it did this: https://huggingface.co/allenai/bidaf/blob/main/README.md

That's probably not intended?

**Comment by osanseviero** [comment]
Hi @dirkgr. The [implementation](https://github.com/allenai/allennlp/blob/main/allennlp/common/push_to_hf.py#L29-L42) of the push command respects the existing model card to avoid deleting user-written model card data or metadata, so it just adds the template before. We're working in some wrapper for the metadata that will include validation and allow merging metadata, but this is still not done. If you prefer, we can modify the command such that it does not add anything to the model card when there is already a model card, but moving forward we'll probably want to add things such as metrics to the metadata.

**Comment by dirkgr** [comment]
I got these for done:
 * https://huggingface.co/allenai/transformer_qa
 * https://huggingface.co/allenai/naqanet
 * https://huggingface.co/allenai/bidaf-elmo
 * https://huggingface.co/allenai/bidaf

**Comment by dirkgr** [comment]
@osanseviero, the tensor board stuff is there, but it doesn't seem to render?

**Comment by osanseviero** [comment]
Hi @dirkgr, I actually see them in the training metrics tab
* https://huggingface.co/allenai/transformer_qa/tensorboard
* https://huggingface.co/allenai/naqanet/tensorboard
* https://huggingface.co/allenai/bidaf-elmo/tensorboard
* https://huggingface.co/allenai/bidaf/tensorboard

**Comment by dirkgr** [comment]
Ah, works in Chrome, not in Safari.

**Comment by osanseviero** [comment]
@severo from the team is looking into it! :hugs:

**Comment by severo** [comment]
It seems to be an error with the last version of tensorboard. I reported it here: https://github.com/tensorflow/tensorboard/issues/5489.

**Comment by severo** [comment]
Fixed!

<img width="1284" alt="Capture d’écran 2022-01-07 à 18 10 43" src="https://user-images.githubusercontent.com/1676121/148580628-bdca4508-82ed-458d-8721-fa0cfe2f734e.png">

Thanks for reporting

**Comment by dirkgr** [comment]
Thanks for fixing!
