### ISSUE TITLE
Updating model for Coreference Resolution

### ISSUE THREAD

**Issue by aakashb95** [allenai/allennlp#5495]
I noticed a new SoTA on Ontonotes 5.0 Coreference task on [paperswithcode](https://paperswithcode.com/paper/word-level-coreference-resolution#code)

The author provides the model (.pt) file in [their git repo](https://github.com/vdobrovolskii/wl-coref#preparation) and claims it to be faster (since it uses RoBERTa) while having an improvement on avg F1 score over SpanBERT. 
What would be the steps to use this checkpoint in the AllenNLP Predictor?

**Comment by dirkgr** [comment]
A .pt file only contains the parameters for a model. To run the model, you need not only the parameters but also the code.

In this case, the easiest would be to wrap their model in an AllenNLP Model that uses the same input and output formats as our SpanBERT. It would be a moderate amount of work, but then you can use the rest of the AllenNLP code unchanged.
