### ISSUE TITLE
`conda install allennlp==2.8.0 -c conda-forge` hangs forever

### ISSUE THREAD

**Issue by dirkgr** [allenai/allennlp#5508]
When I run `conda install allennlp==2.8.0 -c conda-forge` in an environment with Python 3.8, it hangs forever.

@h-vetinari, do you know anything about that?

**Comment by dirkgr** [comment]
I should add that this happens on Linux.

**Comment by h-vetinari** [comment]
Are you trying to install this in CI without a terminal? It's possible that conda is waiting indefinitely to confirm the packages for download/installation? If so, you can pass `--yes` or `-y` to command and it should work. If that's not the case, then let me know (though effectively this exact operation is tested in the testing phase of the feedstock CI).

**Comment by dirkgr** [comment]
No, this was interactive. It did actually finish eventually (and gave me the y/n prompt). But it took at least 45 minutes. I found it done when I returned to the computer hours later.

**Comment by h-vetinari** [comment]
Just to make sure, could you try to install `mamba` and try the same with
```
mamba install -c conda-forge allennlp
```
?

(mamba is like an open-source fork of conda, but with a faster solver; it's being used in conda-forge CI since not too long ago; if mamba doesn't take too long, this might indicate a regression or suboptimal metadata somewhere).

**Comment by dirkgr** [comment]
@h-vetinari, it works pretty well with mamba. Very impressive.

**Comment by HaritzPuerto** [comment]
Hi, sorry for opening this issue, but I believe it would be super useful to include `mamba install -c conda-forge allennlp` in the readme. I had the same problems as dirkgr using conda and wasted a lot of time because of this. But, with mamba I could install it very easily. Thanks!

**Comment by dirkgr** [comment]
I just tried it, and I think we solved it in a better way: The dependencies now match up in such a way that regular `conda` does the right thing. So I'd rather not introduce another dependency with `mamba`.
