### ISSUE TITLE
[XAI for transformer custom model using AllenNLP]

### ISSUE THREAD

**Issue by lengocloi1805** [allenai/allennlp#5519]
I have been solving the NER problem for a Vietnamese dataset with 15 tags in IO format. I have been using the AllenNLP Interpret Toolkit for my model, but I can not configure it completely. 

I have used a pre-trained language model "xlm-roberta-base" based-on HuggingFace. I have concatenated 4 last bert layers, and pass through to linear layer. The model architecture you can see in the attachment below.
![image](https://user-images.githubusercontent.com/60874299/146636517-db1d039c-4893-4502-9fb7-8f49ff278cb3.png)

What steps do I have to take to integrate this model to AllenNLP Interpret?
Could you please help me with this problem?

**Comment by Phammanh26** [comment]
please help me, i have same problem!

**Comment by ndtands** [comment]
I also encountered a similar problem. But it's so hard to find the answer.

**Comment by epwalsh** [comment]
Hi all, have you seen https://guide.allennlp.org/interpret? I hope that helps.

**Comment by lengocloi1805** [comment]
> Hi all, have you seen https://guide.allennlp.org/interpret? I hope that helps.

Yes I do, but I have no idea about what my archived file (tar.gz) is?. I have downloaded archived file form demo interpret on AllenNLP demo and extract it, but it to challenge for me to understand config.json file to adapt with my model, so I still stuck in here.

**Comment by lengocloi1805** [comment]
Guide sample found at https://guide.allennlp.org/interpret#3, but I have no idea about archive file (including weight.th, vocabulary....). How I can pass through my predict result to Predictor object, and what format Predictor need to compatibility?

Thanks in advance!

**Comment by epwalsh** [comment]
The archive file (*.tar.gz) what you get after training / fine-tuning your model with `allennlp train`. The format your `Predictor` takes depends on which `Predictor` you're using and how it's implemented. You may need to implement your own `Predictor` subclass. Part 1 of the guide may be useful: https://guide.allennlp.org/your-first-model
