### ISSUE TITLE
Predict batch wise

### ISSUE THREAD

**Issue by krishna-anumula** [allenai/allennlp#5526]
Hi Team,
Is there any solution, where can we implement allennnlp coref batch wise and get the clusters in batch model. So that, it will eases turn around time of passing different set of sentences individually.

like this : clusters = predictor.predict_batch([art1,art2,art3.......,artn])['clusters']

**Comment by epwalsh** [comment]
There is [`Predictor.predict_batch_json()`](https://github.com/allenai/allennlp/blob/ab4f7b5c3e820ab84fa0bcbf746e75aa47919878/allennlp/predictors/predictor.py#L290) and [`Predictor.predict_batch_instance()`](https://github.com/allenai/allennlp/blob/ab4f7b5c3e820ab84fa0bcbf746e75aa47919878/allennlp/predictors/predictor.py#L294). Is that what you're looking for?
