### ISSUE TITLE
How to speed up predicting for coreference on GPU

### ISSUE THREAD

**Issue by houliangxue** [allenai/allennlp#5533]
when using allennlp for predicting coreference, the utilization rate of GPU is very low and it consumes more CPU, how can i speed up my predicting. i was trying to use multiprocessing, but because of the much consuming of CPU, parallelization reduces the speed.
Here is my code:

    from allennlp.predictors.predictor import Predictor
    import allennlp_models.tagging
    sentence = "The legal pressures facing Michael Cohen are growing in a wide-ranging investigation of his personal business affairs 
                         and his work on behalf of his former client, President Trump."
    predictor = Predictor.from_path("coref-spanbert-large-2021.03.10.tar.gz",cuda_device=torch.cuda.current_device())
    coref_cluters = predictor.predict(document=sentence)["clusters"]

**Comment by dirkgr** [comment]
Try predicting in batches, rather than one instance at a time. If you have enough GPU memory, this might provide a big speedup.

**Comment by wutaiqiang** [comment]
> 

I can set batch_size in command line, but I cannot set batchsize in python file

**Comment by houliangxue** [comment]
Thanks for your reply.But when i batch it for predicting,that's not work for me. 100 examples tooks 233s on GPU. It's still slow for me ,because I have 300,000 examples to predict .Is there a demo example for me to
use for reference.
here is my code now, how should i fix it.

from allennlp.predictors.predictor import Predictor
import allennlp_models.tagging
from allennlp.common.tqdm import Tqdm
from allennlp.common.util import lazy_groups_of

predictor = Predictor.from_path("coref-spanbert-large-2021.03.10.tar.gz",cuda_device=torch.cuda.current_device())
# 100 fake examples
data = [{"document": "Philammon followed, half contemptuous, half wondering at what this philosophy might be, which could feed the self-conceit of anything so abject as his ragged little apish guide;but the novel roar and whirl of the street, the perpetual stream of busy faces, the line of curricles, palanquins, laden asses, camels, elephants, which met and passed him, and squeezed him up steps and into doorways, as they threaded their way through the great Moon-gate into the ample street beyond, drove everything from his mind but wondering curiosity, and a vague, helpless dread of that great living wilderness, more terrible than any dead wilderness of sand which he had left behind."}]*100
batch_size=10 
for batch in Tqdm.tqdm(lazy_groups_of(data, batch_size)):
	batch_output =predictor.predict_batch_json(batch)

**Comment by houliangxue** [comment]
Thanks for your reply.But when i batch it for predicting,that's not work for me. 100 examples tooks 233s on GPU. It's still slow for me ,because I have 300,000 examples to predict .Is there a demo example for me to
use for reference.
here is my code now, how should i fix it.

from allennlp.predictors.predictor import Predictor
import allennlp_models.tagging
from allennlp.common.tqdm import Tqdm
from allennlp.common.util import lazy_groups_of

predictor = Predictor.from_path("coref-spanbert-large-2021.03.10.tar.gz",cuda_device=torch.cuda.current_device())

##100 fake examples
data = [{"document": "Philammon followed, half contemptuous, half wondering at what this philosophy might be, which could feed the self-conceit of anything so abject as his ragged little apish guide;but the novel roar and whirl of the street, the perpetual stream of busy faces, the line of curricles, palanquins, laden asses, camels, elephants, which met and passed him, and squeezed him up steps and into doorways, as they threaded their way through the great Moon-gate into the ample street beyond, drove everything from his mind but wondering curiosity, and a vague, helpless dread of that great living wilderness, more terrible than any dead wilderness of sand which he had left behind."}]*100
batch_size=10
for batch in Tqdm.tqdm(lazy_groups_of(data, batch_size)):
batch_output =predictor.predict_batch_json(batch)

**Comment by houliangxue** [comment]
Thanks for your reply.But when i batch it for predicting,that's not work for me. 100 examples tooks 23s on GPU. It's still slow for me ,because I have 300,000 examples to predict .Is there a demo example for me to
use for reference.
here is my code now, how should i fix it.

from allennlp.predictors.predictor import Predictor
import allennlp_models.tagging
from allennlp.common.tqdm import Tqdm
from allennlp.common.util import lazy_groups_of

predictor = Predictor.from_path("coref-spanbert-large-2021.03.10.tar.gz",cuda_device=torch.cuda.current_device())

##100 fake examples
data = [{"document": "Philammon followed, half contemptuous, half wondering at what this philosophy might be, which could feed the self-conceit of anything so abject as his ragged little apish guide;but the novel roar and whirl of the street, the perpetual stream of busy faces, the line of curricles, palanquins, laden asses, camels, elephants, which met and passed him, and squeezed him up steps and into doorways, as they threaded their way through the great Moon-gate into the ample street beyond, drove everything from his mind but wondering curiosity, and a vague, helpless dread of that great living wilderness, more terrible than any dead wilderness of sand which he had left behind."}]*100
batch_size=10
for batch in Tqdm.tqdm(lazy_groups_of(data, batch_size)):
batch_output =predictor.predict_batch_json(batch)

**Comment by dirkgr** [comment]
What did you experiment with? Did you try different batch sizes? What's your GPU utilization?
