### ISSUE TITLE
Add a way to add dependent files into the model archive

### ISSUE THREAD

**Issue by matt-gardner** [allenai/allennlp#554]
We are definitely going to need this eventually.  The vocabulary already does this, but in a particular, hard-coded way.  ELMo embeddings would probably be easier if there were a standard way to do this.  And if we ever want to do byte pair encoding, e.g., you'd want to do it as a `Tokenizer` that takes a pre-computed byte-pair vocabulary (and this is separate from the way that our `Vocabulary` works).

So, we'd want something on `Trainer` that saves all dependent files to the model archive.  That would then call a method on `Vocabulary`, the `DatasetReader`, the `Model`, and anything else, which in turn call the method on `Tokenizers`, `Modules`, and whatever else.  And when loading a model from an archive, these classes all need to know how to modify the paths that they require as input, so they point to the archive somehow instead of pointing to the originally-specified location.  Maybe `update_params_from_archive(params: Params, archive_path: str)`, or something?  That method would update the params for anything that matters - e.g., `Embedding` would remove the path to the pre-trained file, because it's not necessary anymore*, `Vocabulary` would add a path to the saved files, etc.

This is a lot of boilerplate, adding methods on `Model` to pass on calls to `Modules`, etc., but I'm not sure of another way to do this.

\* Actually, maybe `Embedding` would get an option to copy the embedding file over, so that you can still use it at test time, and add words to the embedding as needed...

**Comment by schmmd** [comment]
Needed for vocabulary expansion at test time.

**Comment by schmmd** [comment]
Streamline serialization API (joel will know what you mean)
