### ISSUE TITLE
Training longformer fails with error

### ISSUE THREAD

**Issue by kingafy** [allenai/allennlp#5547]
I am using allennlp trainer to train longformer (allenai/longformer-base-4096) model but unfortunately its failing with message 
 File "/usr/local/lib/python3.7/dist-packages/allennlp/modules/seq2vec_encoders/boe_encoder.py", line 43, in forward
    tokens = tokens * mask.unsqueeze(-1)
RuntimeError: The size of tensor a (512) must match the size of tensor b (503) at non-singleton dimension 1

Is there a limitation to train long sequence models in Allennlp or are there any specific parameters to be passed to train models in allen nlp to handle longer sequence based models such a longformer.

**Comment by AkshitaB** [comment]
@kingafy Can you specify what allennlp version you are using? And can you also share your training config?

**Comment by hpataci** [comment]
I had the same issue (https://stackoverflow.com/questions/70994667/semantic-role-labeling-tensor-issue)

would you mind sharing your solution?
