### ISSUE TITLE
Information about Embeddings in the Allen Coreference Model

### ISSUE THREAD

**Issue by EmanueleGusso** [allenai/allennlp#5557]
Hi everybody,
I'm an Italian student approaching the NLP world.
First of all I'd like to thank you for the amazing work you've done with the paper " Higher-order Coreference Resolution with Coarse-to-fine Inference".
I am using the model provided by allennlp library and I have two questions for you.

1. in https://demo.allennlp.org/coreference-resolution it is written that the embedding used is SpanBERT. Is this a BERT embedding trained regardless of the coreference task? I mean, could I possibly use this embedding just as a pretrained model on the english language to embed sentences? (e.g. like https://huggingface.co/facebook/bart-base )

2. is it possible to modify the code in order to return, along with the coreference prediction, also the aforementioned embeddings of each sentence?

I really hope you can help me.
Meanwhile I thank you in advance for your great availability.
Sincerely,
Emanuele Gusso

**Comment by epwalsh** [comment]
Hi,

The SpanBERT coref model was trained on the [Ontonotes 5.0](https://catalog.ldc.upenn.edu/LDC2013T19) dataset. In the process of training, the BERT part of the model was also fine-tuned.

You could certainly use this fine-tuned BERT model to create sentence embeddings as well. I don't know how good those embeddings would be, however, and I don't know the best way to do it. But it's certainly possible - and probably not too hard - once you decide how you want to create the sentence embeddings (e.g. take the embedding of the first token, or the last token, or a somehow pool the embeddings of all tokens in the sentence).
