### ISSUE TITLE
Remove upper bound for nltk

### ISSUE THREAD

**Issue by h-vetinari** [allenai/allennlp#5559]
Currently, allennlp 2.9.0 [requires](https://github.com/allenai/allennlp/blame/v2.9.0/setup.py#L58)
```
nltk <3.6.6
```
while allennlp-models 2.9.0 [requires](https://github.com/allenai/allennlp-models/blame/v2.9.0/requirements.txt#L11)
```
nltk >=3.6.5
```

This is the slimmest possible margin, and for anyone using allennlp-models, this is effectively an exact pin to `3.6.5`, and will strain (or in the worst case: break) the package solvers of either conda or pip.

For context: the change that introduced the cap here was #5540 in response to #5521 - that's completely fine as a stop-gap, but latest in the medium term this cap should be removed again.

CC @dirkgr @epwalsh

**Comment by epwalsh** [comment]
Fixed by https://github.com/allenai/allennlp/pull/5563
