### ISSUE TITLE
Confusing `Vocabulary` docstring

### ISSUE THREAD

**Issue by david-waterworth** [allenai/allennlp#5564]
I'm trying to build a model using pre-trained gensim word2vec vectors. I think I have it working now but it was quite confusing, in particular, the docstring for the `Vocabulary`  `only_include_pretrained_words`. It states:

    only_include_pretrained_words : `bool`, optional (default=`False`)
        This defines the strategy for using any pretrained embedding files which may have been
        specified in `pretrained_files`. If False, an inclusive strategy is used: and words
        which are in the `counter` and in the pretrained file are added to the `Vocabulary`,
        regardless of whether their count exceeds `min_count` or not. If True, we use an
        exclusive strategy: words are only included in the Vocabulary if they are in the pretrained
        embedding file (their count must still be at least `min_count`).

What this implies to me is that you either get the intersection of the pre-trained vocab and the tokens discovered from the instances OR you get just the pre-trained vocabulary. However, there's what an undocumented and confusing (IMO) interaction with the `min_pretrained_embeddings` parameter, the docstring being:

    min_pretrained_embeddings : `Dict[str, int]`, optional
        If provided, specifies for each namespace a minimum number of lines (typically the
        most common words) to keep from pretrained embedding files, even for words not
        appearing in the data.

Given that it's optional, my expectation is that if you set `only_include_pretrained_words=True` and don't set `min_pretrained_embeddings` the resulting vocabulary should be 100% of the tokens from the pre-trained file.

This isn't the case from what I gather, it appears you must set `only_include_pretrained_words=True` and pass the number of tokens in the pre-trained files anmespace to `min_pretrained_embeddings` due to this line :

https://github.com/allenai/allennlp/blob/1caf0dafa3bc8d0bb309a46e2ccb12f714923260/allennlp/data/vocabulary.py#L669

It coalesces 'min_pretrained_embeddings' to rather than the length of pretrained_list, so you always only get the vocab from instances. Perhaps it should be:

                pretrained_list = _read_pretrained_tokens(pretrained_files[namespace])
                min_embeddings = min_pretrained_embeddings.get(namespace, len(pretrained_list))

Although I'm not sure if that also works in the case where `only_include_pretrained_words=False` (or at least I'm not sure it's consistent with the docstring)

**Comment by epwalsh** [comment]
> What this implies to me is that you either get the intersection of the pre-trained vocab and the tokens discovered from the instances OR you get just the pre-trained vocabulary.

I don't think the 2nd part of your interpretation is correct. From the docstring,

> "If True, we use an exclusive strategy: words are only included in the Vocabulary if they are in the pretrained embedding file (their count must still be at least `min_count`)."

That part backs up the first part of what you said "the intersection of the pre-trained vocab and the tokens discovered from the instances," when `only_include_pretrained_words` is `True`. But when `only_include_pretrained_words` is `False`, you just get all of the words discovered from instances that exceed the min count (some of which may be in the pretrained file).

**Comment by david-waterworth** [comment]
But when `only_include_pretrained_words` you get nothing unless you also set `min_pretrained_embeddings` to the length of the embeddings - but this is not mentioned. I created the following test

```
from allennlp.data.tokenizers import Token
from allennlp.data.instance import Instance
from allennlp.data.fields import TextField
from allennlp.data.token_indexers import SingleIdTokenIndexer

# create synthetic  instances
instance = Instance({"tokens": TextField([Token("token1"), Token("token4")])})
token_indexer = {"tokens": SingleIdTokenIndexer()}
instance.fields["tokens"]._token_indexers = token_indexer

instances = [instance]

# create a synthetic word2vec file
import tempfile

pretrained_file = f'{tempfile.gettempdir()}/tokens.txt'
with open(pretrained_file, 'w') as f:
    f.write('3 1')
    f.write('token1 0.1')
    f.write('token2 0.2')
    f.write('token3 0.3')

# creat vocab from instances and pretrained vectors
from allennlp.data.vocabulary import Vocabulary

vocab = Vocabulary.from_instances(
    instances=instances, 
    oov_token='<unk>', 
    padding_token='<pad>',
    pretrained_files={'tokens':pretrained_file},
    tokens_to_add={'tokens':['<unk>','<pad>']},
    only_include_pretrained_words=True,
    #min_count=None,
    #min_pretrained_embeddings=None
    )
print(vocab._token_to_index['tokens'])
```

The resulting vocab is `{'<pad>': 0, '<unk>': 1, 'token1': 2}` - that matches what docstring says "words are only included in the Vocabulary if they are in the pre-trained embedding file".

With `only_include_pretrained_words=False` I get the discovered vocab `{'<pad>': 0, '<unk>': 1, 'token1': 2, 'token4': 3}` - this is contrary to what the docstring says "words which are in the `counter` and in the pretrained file are added", since 'token4' is not in the pretrained vocab.

Setting `only_include_pretrained_words=True`  and `min_pretrained_embeddings={'tokens':3}` results in `{'<pad>': 0, '<unk>': 1, 'token1': 2, 'token2': 3, 'token3': 4}`.

And `only_include_pretrained_words=False`  and `min_pretrained_embeddings={'tokens':3}` gives `{'<pad>': 0, '<unk>': 1, 'token1': 2, 'token4': 3, 'token2': 4, 'token3': 5}`

What seems to be missing is the fact that the logic is only applied to `pretrained_embeddings[:coalesce(min_pretrained_embeddings,0)]` meaning that if you don't pass `min_pretrained_embeddings=len(pretrained_embeddings)` you get surprising results?

**Comment by david-waterworth** [comment]
@epwalsh yes I noticed and corrected that typo - but I guess I did that locally and didn't fix the version I pasted above.
