### ISSUE TITLE
Weights not initialized on coref resolution model

### ISSUE THREAD

**Issue by briemadu** [allenai/allennlp#5574]
Hi there,

when I follow the steps on the [model usage page](https://demo.allennlp.org/coreference-resolution), I get this warning:

```Some weights of BertModel were not initialized from the model checkpoint at SpanBERT/spanbert-large-cased and are newly initialized: ['bert.pooler.dense.weight', 'bert.pooler.dense.bias']```

when I call 

```Predictor.from_path("https://storage.googleapis.com/allennlp-public-models/coref-spanbert-large-2021.03.10.tar.gz")```

or 

```Predictor.from_path("https://storage.googleapis.com/allennlp-public-models/coref-spanbert-large-2020.02.27.tar.gz")```

This occurs both on macOS and UNIX, with packages allennlp=2.2.0 and allennlp=2.1.0.

The outputs I get seem to be the same as in the demo for some examples I tried. So I'd like to confirm if I can safely ignore this warning (i.e. if the pooling layer is indeed not used) or if something is wrong.

Thanks!

**Comment by dirkgr** [comment]
Yes, that warning can be ignored. I don't know why that suddenly appears, but the coref model does not use the native BERT pooler at all.
