### ISSUE TITLE
Could allennlp_models.pretrained load a model silently?

### ISSUE THREAD

**Issue by zhaowei-wang98** [allenai/allennlp#5576]
**Is your feature request related to a problem? Please describe.**
```
from allennlp_models import pretrained
predictor = pretrained.load_predictor("structured-prediction-srl-bert")
```
When I try to load a model with the above code, a deluge of log info takes my terminal and disrupts my personal log info.
Could it be silent?

**Describe the solution you'd like**
No log info about loading a model appears on my terminal.

**Describe alternatives you've considered**
keep it silent or output only one or two lines to show that the loading process is finished.

**Additional context**
no.

**Comment by dirkgr** [comment]
All of the messages are using the Python logging facilities. You can limit it to only show warning messages from AllenNLP by doing this:
```Python
import logging
logging.getLogger("allennlp").setLevel(logging.WARN)
```

If you want to only see warnings from all packages (not just AllenNLP), you can even do this:
```Python
logging.getLogger().setLevel(logging.WARN)
```
