### ISSUE TITLE
How to save models that maintain optimal performance across multiple datasets on multitask?

### ISSUE THREAD

**Issue by ICanFlyGFC** [allenai/allennlp#5577]
I built a multitask model. The best-performing model by training is automatically saved in the single-task case.
But for multitasking, the model just saves the best performance of the model on one of the datasets.
How do I get the training process to choose a better model performance measure for multiple datasets?

**Comment by dirkgr** [comment]
The model that gets saved is the model that produces the best metric during evaluation. Specifically, we look for the metric with the name that you gave in the `validation_metric` parameter to the trainer. Check the details here: https://docs.allennlp.org/main/api/training/gradient_descent_trainer/#gradientdescenttrainer

By default, `MultiTaskModel` returns the `"loss"` metric, which is averaged over all instances regardless of task head, and the task-head specific metrics under names like `f"{task_name}_{metric_name}"`, where the task heads produce metrics under the name `metric_name`. You can then specify multiple metrics to the trainer in `validation_metrics`, and it will use the sum of the metrics to decide which model is best.

If you need something more intelligent, you have to come up with another way of calculating a good metric for your multitask model, and implement it in a subclass to `MultiTaskModel`. Ideally, all you have to implement is another version of the `get_metrics()` method.

**Comment by ICanFlyGFC** [comment]
Thank you for your patience!
My model is not **MultiTaskModel**, so I will change it soon and try what you told me.
Thank you again! : )

**Comment by ICanFlyGFC** [comment]
Can I get examples from somewhere, no clue at the moment...

**Comment by dirkgr** [comment]
Vilbert multitask does this: https://github.com/allenai/allennlp-models/blob/main/training_config/vision/vilbert_multitask.jsonnet#L149

**Comment by ICanFlyGFC** [comment]
I wonder if I do not change my model to **MultiTaskModel**, is there any method to validate two datasets at end of an epoch?
![image](https://user-images.githubusercontent.com/50896307/155730091-dab0e5c8-0a21-4c61-8d94-f7c5872ab880.png)
![image](https://user-images.githubusercontent.com/50896307/155730144-fef42fd1-168e-4015-a961-0d935ae86596.png)

**Comment by dirkgr** [comment]
As long as your model produces those metrics (I guess `GeoQA` and `Math23k`?), the trainer will use those metrics as criteria to decide which model is best. The trainer doesn't care whether the metrics came from `MultiTaskModel` or some other model.

Note that if the scale of those metrics is very different, then one of them will dominate. The trainer needs to produce a total order of the checkpoints it evaluates. If you supply multiple metrics, we just add them to produce one score. If `GeoQA` ranges from 0-1000, and `Math23k` ranges from 0-1, then `GeoQA` will win almost every time.

**Comment by dirkgr** [comment]
Is it possible that your validation set only contains instances for one of the task heads?

**Comment by ICanFlyGFC** [comment]
Thank you for your patience and help!
