### ISSUE TITLE
Pass a custom pair of strings to `PretrainedTransformerTokenizer._reverse_engineer_special_tokens`. 

### ISSUE THREAD

**Issue by tarohi24** [allenai/allennlp#5597]
Hello,

`PretrainedTransformerTokenizer._reverse_engineer_special_tokens` is called inside `PretrainedTransformerTokenizer.__init__` ([here](https://github.com/allenai/allennlp/blob/5f5f8c30fe7a9530e011787b6ff10549dc5dac37/allennlp/data/tokenizers/pretrained_transformer_tokenizer.py#L78)) . If I understand correctly, the method does some sanity checks by comparing a pair of token ids that should be different from each other. 

The current implementation compares `("a", "b")` or `("1", "2")`, but both of the pairs don't work for some Japanese pre-trained tokenizers. For example, the vocabulary of the [NICT Japanese BERT](https://alaginrc.nict.go.jp/nict-bert/index.html) contains none of `{"a", "b", "1", "2"}` because it only accepts full-width characters. 

So I'd like to pass a custom pair to `PretrainedTransformerTokenizer._reverse_engineer_special_tokens` by adding a parameter to `PretrainedTransformerTokenizer.__init__`. I'm ready to make a PR, but I opened this issue to make sure that it's a good approach.

Thanks,

**Comment by epwalsh** [comment]
Hi @tarohi24, yes please go ahead with that PR and feel free to tag me for a review when you open it 🙂

**Comment by tarohi24** [comment]
Sure I'll do that soon!

**Comment by tarohi24** [comment]
HI @epwalsh , I made a PR for this. It looks like I cannot assign a reviewer because this is my first contribution. Could you check that? Thank you!

https://github.com/allenai/allennlp/pull/5608
