### ISSUE TITLE
requiring all inherited model.tar.gz after transfer learning coreference

### ISSUE THREAD

**Issue by davidberenstein1957** [allenai/allennlp#5604]
Hello, I have trained a coreference model which resulted in `model_1.tar.gz` . Afterwards, I decided to use this model in the training config by adding the following key to the `.jsonnet`.
```
"model": {
    "type": "from_archive",
    "archive_file": "allennlp_output_1/model_1.tar.gz"
 }
```
This worked nicely and resulted in a better `model_2.tar.gz`. However, upon loading `model_2.tar.gz` via `Predictor.from_path("./allennlp_output_1/model_1.tar.gz")` it requires the `allennlp_output_1/model_1.tar.gz` to be present as well.

**Comment by epwalsh** [comment]
@AkshitaB, @dirkgr, I think you all had a solution to this at one point?

**Comment by davidberenstein1957** [comment]
@epwalsh similarly, loading a model with a custom datasetloader, require that dataset loader to have been registered, even though I just want to use the model for inference.

**Comment by epwalsh** [comment]
@davidberenstein1957 that surprises me. Can you post a stacktrace when you get a chance?

**Comment by epwalsh** [comment]
So, the main issue here was brought up in https://github.com/allenai/allennlp/issues/5211, but we're not likely to implement the solution anytime soon. We just don't have the bandwidth are we're no longer focused on adding new features to AllenNLP. But there is a work-around: you could just update the `config.json` file within the archive of `model_2.tar.gz` and remove the reference to `allennlp_output_1/model_1.tar.gz`.
