### ISSUE TITLE
How to use bert as the encoder in simpleseq2seq task?

### ISSUE THREAD

**Issue by 9527up** [allenai/allennlp#5612]
If I want to build a simpleseq2seq task, how can I use the pre training model (such as BERT) as the encoder? And how can I write the config files?

**Comment by tarohi24** [comment]
Can you take a look at https://github.com/allenai/allennlp-models/blob/main/training_config/generation/bart_cnn_dm.jsonnet  ?

**Comment by dirkgr** [comment]
Can you be more specific about what exactly you want to accomplish? What kind of seq2seq model are you building?

**Comment by 9527up** [comment]
Thank you！It really helped me a lot，and i have created a new class with “bert.embedding” to replace the class “seq2seqencoder” and solved the problem finally，and thanks again!
&nbsp;



---Original---
From: "Wataru ***@***.***&gt;
Date: Wed, Apr 6, 2022 09:30 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [allenai/allennlp] How to use bert as the encoder insimpleseq2seq task? (Issue #5612)




 
Can you take a look at https://github.com/allenai/allennlp-models/blob/main/training_config/generation/bart_cnn_dm.jsonnet  ?

**Comment by 9527up** [comment]
Thanks! I am tring to build a model that use for a task of sequential text generation, it Receives a paragraph of text as the input, and it just like the task of "math word problem" solving, if you have heard it. And i have created a new class with “bert.embedding” to replace the default class “seq2seqencoder” and solved the problem finally，and thanks for your concern again!
&nbsp;



---Original---
From:&nbsp;"Wataru ***@***.***&gt;
Date:&nbsp;Wed, Apr 6, 2022 09:30 AM
***@***.***&gt;;
***@***.******@***.***&gt;;
Subject:&nbsp;Re: [allenai/allennlp] How to use bert as the encoder insimpleseq2seq task? (Issue #5612)





Can you take a look at&nbsp;https://github.com/allenai/allennlp-models/blob/main/training_config/generation/bart_cnn_dm.jsonnet&nbsp;?

—
Reply to this email directly,&nbsp;view it on GitHub, or&nbsp;unsubscribe.
You are receiving this because you authored the thread.



---Original---
From: "Dirk ***@***.***&gt;
Date: Sat, Apr 9, 2022 02:56 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [allenai/allennlp] How to use bert as the encoder insimpleseq2seq task? (Issue #5612)




 
Can you be more specific about what exactly you want to accomplish? What kind of seq2seq model are you building?
