### ISSUE TITLE
AttributeError: module 'cached_path' has no attribute 'file_friendly_logging'

### ISSUE THREAD

**Issue by lixiepeng** [allenai/allennlp#5666]
```
File "/usr/local/lib/python3.8/site-packages/allennlp/predictors/predictor.py", line 366, in from_path
    load_archive(archive_path, cuda_device=cuda_device, overrides=overrides),
  File "/usr/local/lib/python3.8/site-packages/allennlp/models/archival.py", line 206, in load_archive
    resolved_archive_file = cached_path(archive_file)
  File "/usr/local/lib/python3.8/site-packages/allennlp/common/file_utils.py", line 135, in cached_path
    _cached_path.file_friendly_logging(common_logging.FILE_FRIENDLY_LOGGING)
AttributeError: module 'cached_path' has no attribute 'file_friendly_logging'
```

**Comment by inwonakng** [comment]
I had the same issue, found that cached-path was updated to version 1.1.3 which caused the error
For the time being, I was able to bypass this issue by force installing cached-path==1.1.2 after installing allennlp modules on my runtime

**Comment by TylerReedMC** [comment]
Same issue here. How do you force the cached-path?

**Comment by inwonakng** [comment]
@TylerReedMC 

```
pip install allennlp allennlp-models
pip install cached-path==1.1.2
```

I just re-installed cached-path with the version specified after installing allennlp modules and it seems to have overridden the updated version installed by allennlp dependencies

**Comment by akanksha-sh** [comment]
I did this but ran into this issue when trying to install the spanBERT coref model:
```
url = "https://storage.googleapis.com/allennlp-public-models/coref-spanbert-large-2021.03.10.tar.gz"
cf = Predictor.from_path(url)
```

`argument 1 must be str, not PosixPath`

Any suggestions?

**Comment by AkshitaB** [comment]
This should be fixed in the `main` branch now.
