### ISSUE TITLE
Perhaps an example could be provided for each API, which might be more friendly for first-time users.

### ISSUE THREAD

**Issue by Stycoo** [allenai/allennlp#5678]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by epwalsh** [comment]
Hi, can you please elaborate? Which API are you talking about?

**Comment by Stycoo** [comment]
I am so curious how to use “allennlp.data.fields.transformer_text_field” when i want to use allennlp in combination with huggingface transformers.

**Comment by epwalsh** [comment]
Check out the RoBERTa SNLI model for an example. The config for this model can be found here: https://github.com/allenai/allennlp-models/blob/main/training_config/pair_classification/snli_roberta.jsonnet

This model just uses the [`BasicClassifier`](https://github.com/allenai/allennlp/blob/main/allennlp/models/basic_classifier.py#L16). The important parts of the config are ["model.text_field_embedders"](https://github.com/allenai/allennlp-models/blob/deddfbec899bac8ccbaafcdb0110a9439e8f4db3/training_config/pair_classification/snli_roberta.jsonnet#L25-L32) which is set to use the pretrained transformer embedder, and ["dataset_reader.tokenizer" + "dataset_reader.token_indexers"](https://github.com/allenai/allennlp-models/blob/deddfbec899bac8ccbaafcdb0110a9439e8f4db3/training_config/pair_classification/snli_roberta.jsonnet#L7-L17) which are set to use the pretrained transformer tokenizer and pretrained transformer token indexer, respectively.
