### ISSUE TITLE
cannot import name 'WordTokenizer' from 'allennlp.data.tokenizers'

### ISSUE THREAD

**Issue by AhYounJeong** [allenai/allennlp#5684]
Hello I'm a student majoring in computer engineering.
I have hard time training a  model using allennlp because of "cannot import name 'WordTokenizer' from 'allennlp.data.tokenizers'" error. 
I checked stack over flow for  answer, but never worked 
Can I know if there are any possible way to fix this problem?

**Comment by lgessler** [comment]
#4971 might be worth a look

**Comment by AhYounJeong** [comment]
it helped me a lot !
thank you so much
