### ISSUE TITLE
The DataLoader Needs to Handle Dirty Examples.

### ISSUE THREAD

**Issue by Alexixu** [allenai/allennlp#5709]
**Is your feature request related to a problem? Please describe.**
I need to discard examples when I read the data. BUT the data loader will stop when the data reader return None or raising Exception. Empty Instance can not satisfy either.

**Describe the solution you'd like**
Data loader can automatic discard the instance when data reader return None.

**Describe alternatives you've considered**
Define a Type of Exception like DiscardException to implement this logic gracefully.

**Comment by AkshitaB** [comment]
@Alexixu Possibly your usecase be solved by handling empty instances in the (custom) `DataReader` you're using. If not, please share more details on what dataset reader you are running this with.

**Comment by Alexixu** [comment]
@AkshitaB The dataset reader is custom class inherit from DatasetReader. Empty instances is ok if the data loader can handle this empty logic. Discarding empty instance is the direct way to do so. But the default implement of DataLoader has no such logic. In my view, throwing an Exception is more suitable for corrupt example and DataLoader catch this Exception and discard examples.

**Comment by dirkgr** [comment]
@Alexixu, you can do this in the `DatasetReader` if you override how `_read()` works. You can return something like `None` from `DatasetReader.text_to_instance()`, and then do the right thing in `_read()`.

**Comment by Alexixu** [comment]
@dirkgr I have tried this, but the default DataLoader  implement can not handle None object, And it will throw a Exception for "None type has no index function".

**Comment by dirkgr** [comment]
What I'm saying is, you can change this behavior in your own `DatasetReader`, where you override the `_read()` method to throw away the `None` objects.

**Comment by Alexixu** [comment]
@dirkgr I have tried that exactly, by implement _read function return None object. But the Data Loader (not the Dataset Reader) which call the text_to_instance function can not handle None object.

**Comment by dirkgr** [comment]
The `_read()` function should not return `None`. The `_read()` function is where you detect `None` and throw it away (instead of returning it).

Think of it this way: From `_read()` you have to return an iterable of instances. AllenNLP does not care how you do this. It only cares that `_read()` returns an iterable of instances. So you can do whatever you want inside of `_read()`, including skipping instances.
