### ISSUE TITLE
will update to support latest pytorch?

### ISSUE THREAD

**Issue by liusiye1994** [allenai/allennlp#5713]
pytorch has released 1.12.1 yet. Any schedule about supporting this version of torch?

**Comment by dirkgr** [comment]
#5714

I'm surprised dependabot didn't open a PR for this?

**Comment by dirkgr** [comment]
Actually, it did, but there was a problem with it. The correct PR is #5680.

**Comment by liusiye1994** [comment]
> Actually, it did, but there was a problem with it. The correct PR is #5680.

tks! seems some gpu tests failed?

**Comment by yukw777** [comment]
When do you think #5680 will be released?

**Comment by dirkgr** [comment]
It's done!

**Comment by dirkgr** [comment]
Well, it's merged, but not released yet.

**Comment by dirkgr** [comment]
Just made the release!
