### ISSUE TITLE
Rich 12.1.0 has been yanked, but has been pinned in `requirements.txt`

### ISSUE THREAD

**Issue by amitkparekh** [allenai/allennlp#5715]
## Checklist

- [x] I have verified that the issue exists against the `main` branch of AllenNLP.
- [x] I have read the relevant section in the [contribution guide](https://github.com/allenai/allennlp/blob/main/CONTRIBUTING.md#bug-fixes-and-new-features) on reporting bugs.
- [x] I have checked the [issues list](https://github.com/allenai/allennlp/issues) for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/allenai/allennlp/pulls) for existing proposed fixes.
- [x] I have checked the [CHANGELOG](https://github.com/allenai/allennlp/blob/main/CHANGELOG.md) and the [commit log](https://github.com/allenai/allennlp/commits/main) to find out if the bug was already fixed in the main branch.
- [x] I have included in the "Description" section below a traceback from any exceptions related to this bug.
- [x] I have included in the "Related issues or possible duplicates" section beloew all related issues and possible duplicate issues (If there are none, check this box anyway).
- [x] I have included in the "Environment" section below the name of the operating system and Python version that I was using when I discovered this bug.
- [x] I have included in the "Environment" section below the output of `pip freeze`.
- [ ] I have included in the "Steps to reproduce" section below a minimally reproducible example.

## Description

When installing allennlp (with Poetry), I got this warning.

```bash
Warning: The locked version 12.1.0 for rich is a yanked version. Reason for being yanked: Broken dependencies. Please upgrade to 12.2.0 or later
```

I checked pypi and [rich==12.1](https://pypi.org/project/rich/12.1.0/) has been yanked. But this is the only version permitted under the requirements.txt. 

<details>
<summary><b>Python traceback:</b></summary>
<p>

```
```

</p>
</details>

## Related issues or possible duplicates

- https://github.com/allenai/allennlp/pull/5672

## Environment

OS: OS X

Python version: 3.9.12

<details>
<summary><b>Output of <code>pip freeze</code>:</b></summary>
<p>

```
allennlp==2.10.0
altair==4.2.0
appnope==0.1.3
astor==0.8.1
asttokens==2.0.8
attrs==22.1.0
backcall==0.2.0
bandit==1.7.4
base58==2.1.1
black==22.8.0
blinker==1.5
blis==0.7.8
boto3==1.24.84
botocore==1.27.84
cached-path==1.1.6
cachetools==5.2.0
catalogue==1.0.0
certifi==2022.6.15
cffi==1.15.1
cfgv==3.3.1
charset-normalizer==2.1.1
click==8.1.3
commonmark==0.9.1
convert-case==1.1.1
coverage==6.4.4
cymem==2.0.6
darglint==1.8.1
debugpy==1.6.3
decopatch==1.4.10
decorator==5.1.1
dill==0.3.5.1
distlib==0.3.6
docker-pycreds==0.4.0
docutils==0.19
entrypoints==0.4
eradicate==2.1.0
executing==1.0.0
fairscale==0.4.6
filelock==3.6.0
flake8==4.0.1
flake8-bandit==3.0.0
flake8-broken-line==0.4.0
flake8-bugbear==22.9.23
flake8-commas==2.1.0
flake8-comprehensions==3.10.0
flake8-debugger==4.1.2
flake8-docstrings==1.6.0
flake8-eradicate==1.3.0
flake8-isort==4.2.0
flake8-polyfill==1.0.2
flake8-quotes==3.3.1
flake8-rst-docstrings==0.2.7
flake8-string-format==0.3.0
gitdb==4.0.9
GitPython==3.1.27
google-api-core==2.8.2
google-auth==2.12.0
google-cloud-core==2.3.2
google-cloud-storage==2.5.0
google-crc32c==1.5.0
google-resumable-media==2.4.0
googleapis-common-protos==1.56.4
h5py==3.7.0
huggingface-hub==0.10.0
identify==2.5.5
idna==3.3
importlib-metadata==4.12.0
iniconfig==1.1.1
ipykernel==6.15.2
ipython==8.5.0
isort==5.10.1
jedi==0.18.1
Jinja2==3.1.2
jmespath==1.0.1
joblib==1.2.0
jsonnet==0.18.0
jsonschema==4.16.0
jupyter-core==4.11.1
jupyter_client==7.3.5
lmdb==1.3.0
makefun==1.15.0
MarkupSafe==2.1.1
matplotlib-inline==0.1.6
mccabe==0.6.1
more-itertools==8.14.0
murmurhash==1.0.8
mypy==0.971
mypy-extensions==0.4.3
nest-asyncio==1.5.5
nltk==3.7
nodeenv==1.7.0
numpy==1.23.2
orjson==3.8.0
overrides==6.2.0
packaging==21.3
pandas==1.4.4
parso==0.8.3
pastel==0.2.1
pathspec==0.10.1
pathtools==0.1.2
pbr==5.10.0
pep8-naming==0.12.1
pexpect==4.8.0
pickleshare==0.7.5
Pillow==9.2.0
plac==1.1.3
platformdirs==2.5.2
plotly==5.10.0
pluggy==1.0.0
poethepoet==0.16.2
pre-commit==2.20.0
preshed==3.0.7
promise==2.3
prompt-toolkit==3.0.31
protobuf==3.20.0
psutil==5.9.2
ptyprocess==0.7.0
pure-eval==0.2.2
py==1.11.0
pyarrow==9.0.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycodestyle==2.8.0
pycparser==2.21
pydantic==1.10.2
pydeck==0.8.0b3
pydocstyle==6.1.1
pyflakes==2.4.0
Pygments==2.13.0
Pympler==1.0.1
pyparsing==3.0.9
pyrsistent==0.18.1
pytest==7.1.3
pytest-cases==3.6.13
pytest-cov==3.0.0
python-dateutil==2.8.2
pytz==2022.2.1
pytz-deprecation-shim==0.1.0.post0
PyYAML==6.0
pyzmq==23.2.1
regex==2022.9.13
requests==2.28.1
restructuredtext-lint==1.4.0
rich==12.1.0
rsa==4.9
s3transfer==0.6.0
sacremoses==0.0.53
scikit-learn==1.1.2
scipy==1.9.1
semver==2.13.0
sentencepiece==0.1.97
sentry-sdk==1.9.9
setproctitle==1.3.2
shortuuid==1.0.9
six==1.16.0
smmap==5.0.0
snowballstemmer==2.2.0
spacy==2.3.7
srsly==1.0.5
stack-data==0.5.0
stevedore==4.0.0
streamlit==1.12.0
tenacity==8.0.1
tensorboardX==2.5.1
termcolor==1.1.0
thinc==7.4.5
threadpoolctl==3.1.0
tokenizers==0.12.1
toml==0.10.2
tomli==2.0.1
toolz==0.12.0
torch==1.11.0
torchvision==0.12.0
tornado==6.2
tqdm==4.64.1
traitlets==5.3.0
transformers==4.20.1
typer==0.6.1
typing_extensions==4.3.0
tzdata==2022.2
tzlocal==4.2
urllib3==1.26.12
validators==0.20.0
virtualenv==20.16.5
wandb==0.12.21
wasabi==0.10.1
wcwidth==0.2.5
wemake-python-styleguide==0.16.1
zipp==3.8.1
```

</p>
</details>

## Steps to reproduce

<details>
<summary><b>Example source:</b></summary>
<p>

```
```

</p>
</details>

**Comment by dirkgr** [comment]
Done! Thanks for reporting it!
