### ISSUE TITLE
AllenNLP-Light!  🎉 🙂

### ISSUE THREAD

**Issue by delmaksym** [allenai/allennlp#5720]
I felt I would miss the AllenNLP `modules` and `nn` packages I had used for years. So recently, I factored them into a separate `pip`-installable lightweight repo: [allennlp-light](https://github.com/delmaksym/allennlp-light). I also updated them to be registered with [AI2 Tango](https://github.com/allenai/tango).

As the codes in `modules` and `nn` are grown-up, well-tested, and easy to extend, I believe the repo can sustain itself and be helpful in a read-only zero-maintenance mode! 

To address copyright, I tried to figure out the right [way](https://github.com/allenai/allennlp/issues/4491). I added copyright notices to all files, but because the project is not under AI2's GitHub, I would prefer you to tell me if the name `allennlp` in the [package name](https://twitter.com/simonw/status/1540717175714873345?s=20&t=GyFZHoyisUaE_5ZnC-6JeQ) is all good🙂.

@dirkgr @epwalsh, happy to hear your thoughts/suggestions on that and my little project overall!

**Comment by epwalsh** [comment]
Hey @delmaksym this is absolutely awesome! Thank you so much for doing this. I'll tweet about this from the AllenNLP twitter account.

(and yes it's totally fine to have `allennlp` in the package name)

**Comment by delmaksym** [comment]
Thanks a lot @epwalsh! And thanks for adding a line to the list of alternatives on the README!
