### ISSUE TITLE
Is it possible to load my own quantized model from local

### ISSUE THREAD

**Issue by pradeepdev-1995** [allenai/allennlp#5723]
Here is the code I tried for the coreference resolution
```
from allennlp.predictors.predictor import Predictor
model_url = 'https://storage.googleapis.com/pandora-intelligence/models/crosslingual-coreference/minilm/model.tar.gz'
predictor = Predictor.from_path(model_url)  
text = "Eva and Martha didn't want their friend Jenny \
    to feel lonely so they invited her to the party."
prediction = predictor.predict(document=text)  
print(prediction['clusters'])  
print(predictor.coref_resolved(text))  
```
And it worked well I got the output with solved coreference. like below
```
Eva and Martha didn't want Eva and Martha's friend Jenny     to feel lonely so Eva and Martha invited their friend Jenny to the party.
```
Now I have quantized the model used here (https://storage.googleapis.com/pandora-intelligence/models/crosslingual-coreference/minilm/model.tar.gz) and the new quantized model is stored in a specific path in my local machine.

Shall I use that customized(quantized) model from my local path in model_url value and use this prediction command like below?
```
model_url = <Path to the quantized model in my local machine>
predictor = Predictor.from_path(model_url)  
```

**Comment by AkshitaB** [comment]
@pradeepdev-1995 In general, yes, a local path should work. The model archive needs to contain an allennlp `config.json` and a `weights.th` file. Additionally, if your model code is changed, it should be imported with the correct registered name, which is referenced in the config file.

I'll be happy to assist further if you run into errors with this.

**Comment by pradeepdev-1995** [comment]
Thank you @AkshitaB
But one doubt where can I see the **weights.h** and **config.json** file of allennlp for this

**Comment by AkshitaB** [comment]
If you download the model archive tar file at `model_url` and unzip it, you will see the relevant files.

**Comment by pradeepdev-1995** [comment]
@AkshitaB 
Okay. So the actual model ```config.json``` contains the **model_name** like this in 3 places
![Screenshot from 2022-10-21 12-00-33](https://user-images.githubusercontent.com/41164884/197128291-8704dc2d-0220-4b25-a355-cad1eb006d6b.png)

And you are suggesting that after quantization there should be these 2 files( ```config.json``` and ```weights.th```) in the quantized model folder.  Along with that config.json should contain the **model_name** value as a new quantized model path

Is it so?

**Comment by AkshitaB** [comment]
@pradeepdev-1995 Yes. Essentially, your final model needs to be in a format that's readable by allennlp. For further details regarding config files and serialization, you can read the section on configuration files here: https://guide.allennlp.org/training-and-prediction#2 .

**Comment by AkshitaB** [comment]
@pradeepdev-1995 Your new model needs to be a registered name; an allennlp Model class object. That is what the `Predictor` will require.

So, something like:

```
from allennlp.model import Model
@Model.register("new-model-name")
class NewModelClass(Model):
    <create/load quantized version of model>
```

Then, in your config, you can specify the model name as "new-model-name". 

Also see [this guide chapter](https://guide.allennlp.org/using-config-files) for more details on the config file.

**Comment by nemeer** [comment]
I had tried registering my quantized model as below:
```

@Model.register("quantized_model")
class QuantizedModel(Model):
    def __init__(self):
        super().__init__(serialization_dir="custom_model/model")
```

Also changed the model key in original _config.json_

   ```
"model": {
        "type": "quantized_model"
    },

```

Now, when I try running

model_url = r"custom_model/model"
predictor = Predictor.from_path(model_url)

got TypeError: __init__() missing 1 required positional argument: 'vocab'

Is the model registration correct? Are there any additional params required for registration and in _config.json_. Please mention
