### ISSUE TITLE
Alternative semantic role labeling model

### ISSUE THREAD

**Issue by aphedges** [allenai/allennlp#5729]
I currently use the [semantic role labeling model](https://docs.allennlp.org/models/main/models/structured_prediction/predictors/srl/) from [allennlp-models](https://github.com/allenai/allennlp-models). The sunsetting of this library is going to make using that model in the future more difficult as incompatibilities arise with other dependencies of my projects.

The README currently states "If you are concerned about other AllenNLP functionality, please create an issue." I am therefore asking what alternatives can be used, given that none of the currently linked successor libraries have such a model.

**Comment by epwalsh** [comment]
Hey @aphedges, if you or someone else is willing to maintain a fork of that model, we'd be happy to advertise it.

**Comment by aphedges** [comment]
At the moment, creating my own fork seems like too much effort, especially with #5728 helping extend the lifetime of this library. If I ever need to fork the model for compatibility reasons, I'll link it here.
