### ISSUE TITLE
simple_seq2seq GPU error

### ISSUE THREAD

**Issue by maxdel** [allenai/allennlp#583]
At the line below, _encoder_outputs_mask_ Tensor is explicitly cast to be a **CPU** Tensor, which results in error if the model runs on GPU:
https://github.com/allenai/allennlp/blob/7f5d9f7587e1a799e161c37e3383686323e34956/allennlp/models/encoder_decoders/simple_seq2seq.py#L217-L219

Possible fix might look like this:
```python
# Ensuring mask is also a FloatTensor. Or else the multiplication within attention will
# complain.
mask_type = torch.cuda.FloatTensor if encoder_outputs_mask.is_cuda else torch.FloatTensor
encoder_outputs_mask = encoder_outputs_mask.type(mask_type)
```

If appropriate, I can make a PR.

**Comment by matt-gardner** [comment]
Thanks for pointing that out!  I'm not sure how we missed it before.  A simpler fix is to replace `.type(torch.FloatTensor)` with `.float()`.  I should have caught that when I reviewed the original PR, but I missed it.  It'd be great if you could verify that that change fixes your issue, and make a PR for it.
