### ISSUE TITLE
Implement batch prediction for SRL

### ISSUE THREAD

**Issue by danlou** [allenai/allennlp#591]
I'm currently trying to compile a dataset of ~50M SRL-parsed sentences and was hoping to speed things up with batch processing. Unfortunately, I discovered that it's not yet implemented for SRL.

https://github.com/allenai/allennlp/blob/f700584ed1b72ab45215e405ed0d22564938d1cb/allennlp/service/predictors/semantic_role_labeler.py#L52

In the meantime, do you have any suggestions for speeding up SRL parsing ?

I've also tried running the `predict` command with `--cuda_device 0` on a Tesla K80, but checking `nvidia-smi ` it seems that there's some bottleneck preventing it from going above 25% GPU usage. Could the lack of batch processing create some overhead that's responsible for that, or am I missing something else?

Thanks!

**Comment by matt-gardner** [comment]
This is additional motivation to fix #506 - if that were fixed, we'd get batched prediction in the SRL model for free.  @danlou, yeah, I'd guess that you're seeing low GPU usage because it's not batched.

**Comment by danlou** [comment]
Thanks for the clarification! I'm not really familiar with the codebase, but I may give it a try over the weekend. Will let you know if I think I'm able to help in some way.

**Comment by matt-gardner** [comment]
We'd love to have some help speeding this along, if you're up to submitting a PR.

I _think_ the right way to do this is to modify this function to return a `Tuple[Instance, JsonDict]`: https://github.com/allenai/allennlp/blob/27cdcb561fb3f3746575d209a856e51ef1357029/allennlp/service/predictors/predictor.py#L23-L27

The second return value would then be added to the output here: https://github.com/allenai/allennlp/blob/27cdcb561fb3f3746575d209a856e51ef1357029/allennlp/service/predictors/predictor.py#L20

If you need more detail than that, feel free to ask questions.
