### ISSUE TITLE
Announce new features

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp#593]
Hi everyone, we're excited to announce the 0.3 release of AllenNLP.  We updated our key dependencies to Spacy 2.0 and PyTorch 0.3, and we have a few additional models and many new features since our 0.2 release.

**Additional models**.  More details for our models are available at http://allennlp.org/models and you can use them interactively online at http://demo.allennlp.org/.

* The baseline NER model from [Semi-supervised Sequence Tagging with Bidirectional Language Models](https://www.semanticscholar.org/paper/Semi-supervised-sequence-tagging-with-bidirectiona-Peters-Ammar/73e59cb556351961d1bdd4ab68cbbefc5662a9fc).
* A coreference model with state-of-the-art performance in 2017, based on the publication [End-to-end Neural Coreference Resolution](https://www.semanticscholar.org/paper/End-to-end-Neural-Coreference-Resolution-Lee-He/3f2114893dc44eacac951f148fbff142ca200e83).

**Additional examples and tutorials**.  Find them at http://allennlp.org/tutorials/.

* A tutorial on using AllenNLP in your projects as a pip dependency.

**New features**.

* Improved SRL visualization on the demo.
* `ListField` padding fixes.

**Comment by matt-gardner** [comment]
Features:
- New NER model and demo
- New coreference resolution model and demo
- Pytorch 0.3, spacy 2.0
- Example code for training a seq2seq model
- New tutorial on using AllenNLP in your project

**Comment by DeNeutoy** [comment]
More new features:
- Sweet SRL visualisation
- Important if a little dull `ListField` padding fixes
