### ISSUE TITLE
Experiments run with `no_tqdm: true` still have TQDM output in logs

### ISSUE THREAD

**Issue by mjlangan** [allenai/allennlp#599]
Found while investigating some issues with Beaker's log handling. It appears that when I run experiments with `no_tqdm: true` in my `trainer`'s config JSON, I will still see TQDM output for the steps "Indexing dataset" and "Iterating over dataset"

See the log output for this Beaker task: http://beaker.dev.allenai.org/tk/tk_jt3ahr2hxmch

**Comment by DeNeutoy** [comment]
This is the same issue as #524 - basically we have the TQDM flag for training, but not for evaluation at test time.

**Comment by joelgrus** [comment]
this is slightly broader, though. `train.py` calls `index_instances()` a couple of times

https://github.com/allenai/allennlp/blob/master/allennlp/commands/train.py#L164

and that has a tqdm in it:

https://github.com/allenai/allennlp/blob/master/allennlp/data/dataset.py#L58

at least for this case it would be easy enough to add a `no_tqdm` parameter to `index_instances` (and similarly to `evaluate()` and modify `train.py` to specify it.

**Comment by DeNeutoy** [comment]
Those points are less painful though because they are much faster - if you see the points in the beaker log where `.index_instances` is called, you'll see it's only ~3 tqdm statements, whereas the evaluation of a dataset can take much longer and be much more verbose, making the lines unreadable.

**Comment by matt-gardner** [comment]
It might be easier, though, to just modify our `TeeLogger` to detect tqdm output, and add a newline.  It'd remove a bunch of complexity from the code, and we wouldn't have to pass `no_tqdm` everywhere.

**Comment by schmmd** [comment]
From @DeNeutoy: here is the `TeeLogger` for DeepQA which has a hack to address this issue: https://github.com/allenai/deep_qa/blob/master/deep_qa/common/tee_logger.py

**Comment by schmmd** [comment]
The issue in the linked job is pretty minor.  The text display on beaker.dev.ai2 collapses the multi-line TQDM output to a single line.  When I copy and paste to GitHub the TQDM output becomes multiple lines.

```
...
2017-12-08T19:55:33.094778899Z 2017-12-08 19:55:33,094 - INFO - allennlp.data.vocabulary - Fitting token dictionary from dataset.
2017-12-08T19:55:33.620434278Z 
  0%|          | 0/21892 [00:00<?, ?it/s]
 20%|#9        | 4366/21892 [00:00<00:00, 43641.62it/s]
 41%|####1     | 9037/21892 [00:00<00:00, 45176.05it/s]
 66%|######6   | 14515/21892 [00:00<00:00, 48370.00it/s]
 89%|########9 | 19497/21892 [00:00<00:00, 48731.60it/s]
100%|##########| 21892/21892 [00:00<00:00, 49405.42it/s]
2017-12-08T19:55:33.620465673Z 2017-12-08 19:55:33,618 - INFO - allennlp.common.params - model.type = StateChangeModelCombinedLossBothAttention
...

**Comment by schmmd** [comment]
We do output a really nice "one liner" here:

http://beaker.allenai.org/tk/tk_x9015xycnbti

```
2018-01-19T08:48:08.923176853Z 2018-01-19 08:48:08,922 - INFO - allennlp.commands.evaluate - Iterating over dataset
2018-01-19T08:48:10.337576957Z 
  0%|          | 0/2 [00:00<?, ?it/s]
precision-LOC: 0.25, recall-LOC: 0.32, f1-measure-LOC: 0.28, precision-OUTPUT: 0.00, recall-OUTPUT: 0.00, f1-measure-OUTPUT: 0.00, precision-LOC-TO: 1.00, recall-LOC-TO: 0.20, f1-measure-LOC-TO: 0.33, precision-TIME: 0.43, recall-TIME: 0.32, f1-measure-TIME: 0.36, precision-AGENT: 0.55, recall-AGENT: 0.63, f1-measure-AGENT: 0.59, precision-PATIENT: 0.45, recall-PATIENT: 0.47, f1-measure-PATIENT: 0.46, precision-ENABLE: 0.52, recall-ENABLE: 0.47, f1-measure-ENABLE: 0.50, precision-LOC-FROM: 0.00, recall-LOC-FROM: 0.00, f1-measure-LOC-FROM: 0.00, precision-overall: 0.47, recall-overall: 0.48, f1-measure-overall: 0.47 ||:   0%|          | 0/2 [00:00<?, ?it/s]
precision-LOC: 0.25, recall-LOC: 0.32, f1-measure-LOC: 0.28, precision-OUTPUT: 0.00, recall-OUTPUT: 0.00, f1-measure-OUTPUT: 0.00, precision-LOC-TO: 1.00, recall-LOC-TO: 0.20, f1-measure-LOC-TO: 0.33, precision-TIME: 0.43, recall-TIME: 0.32, f1-measure-TIME: 0.36, precision-AGENT: 0.55, recall-AGENT: 0.63, f1-measure-AGENT: 0.59, precision-PATIENT: 0.45, recall-PATIENT: 0.47, f1-measure-PATIENT: 0.46, precision-ENABLE: 0.52, recall-ENABLE: 0.47, f1-measure-ENABLE: 0.50, precision-LOC-FROM: 0.00, recall-LOC-FROM: 0.00, f1-measure-LOC-FROM: 0.00, precision-overall: 0.47, recall-overall: 0.48, f1-measure-overall: 0.47 ||:  50%|#####     | 1/2 [00:00<00:00,  1.57it/s]
precision-LOC: 0.35, recall-LOC: 0.35, f1-measure-LOC: 0.35, precision-OUTPUT: 0.00, recall-OUTPUT: 0.00, f1-measure-OUTPUT: 0.00, precision-LOC-TO: 1.00, recall-LOC-TO: 0.11, f1-measure-LOC-TO: 0.20, precision-TIME: 0.40, recall-TIME: 0.33, f1-measure-TIME: 0.36, precision-AGENT: 0.55, recall-AGENT: 0.59, f1-measure-AGENT: 0.57, precision-PATIENT: 0.43, recall-PATIENT: 0.49, f1-measure-PATIENT: 0.46, precision-ENABLE: 0.55, recall-ENABLE: 0.51, f1-measure-ENABLE: 0.53, precision-LOC-FROM: 0.00, recall-LOC-FROM: 0.00, f1-measure-LOC-FROM: 0.00, precision-overall: 0.47, recall-overall: 0.48, f1-measure-overall: 0.48 ||:  50%|#####     | 1/2 [00:01<00:01,  1.41s/it]
precision-LOC: 0.35, recall-LOC: 0.35, f1-measure-LOC: 0.35, precision-OUTPUT: 0.00, recall-OUTPUT: 0.00, f1-measure-OUTPUT: 0.00, precision-LOC-TO: 1.00, recall-LOC-TO: 0.11, f1-measure-LOC-TO: 0.20, precision-TIME: 0.40, recall-TIME: 0.33, f1-measure-TIME: 0.36, precision-AGENT: 0.55, recall-AGENT: 0.59, f1-measure-AGENT: 0.57, precision-PATIENT: 0.43, recall-PATIENT: 0.49, f1-measure-PATIENT: 0.46, precision-ENABLE: 0.55, recall-ENABLE: 0.51, f1-measure-ENABLE: 0.53, precision-LOC-FROM: 0.00, recall-LOC-FROM: 0.00, f1-measure-LOC-FROM: 0.00, precision-overall: 0.47, recall-overall: 0.48, f1-measure-overall: 0.48 ||: 100%|##########| 2/2 [00:01<00:00,  1.42it/s]
```

**Comment by matt-gardner** [comment]
@schmmd, yeah, it's not a super high priority issue, but it is an annoyance.  Beaker won't update logs until it hits a new line, so if you're in the middle of data processing that's taking a long time, your job will look like it froze, until you get one huge line of tqdm output.

**Comment by schmmd** [comment]
Related PR: https://github.com/allenai/allennlp/pull/719

**Comment by matt-gardner** [comment]
We should probably remove the `no_tqdm` flag entirely if the fix in #719 works.  It'd simplify the training code, and just be nicer in general.

**Comment by schmmd** [comment]
Happy to change this to `re.compile("\r$").sub("", line)` if anyone thinks that's better (remove trailing carriage returns).

**Comment by schmmd** [comment]
@matt-gardner I agree it would be nice to only have one mechanism for reporting progress.  I also find it quite strange that we have configurations for how to report progress in our configuration files.

What do you think about a `--disable-tqdm` flag on the CLI?  This could disable TQDM globally throughout the entire training process.  There would be no alternate mechanism for reporting progress.  Some users might like this option for keeping the logs cleaner.

**Comment by matt-gardner** [comment]
What's the point of the global `--disable-tqdm` flag?

**Comment by matt-gardner** [comment]
I'm pretty sure you always want some measure of progress, as you'd be waiting a really long time with no update if you just disable tqdm and have no alternative.

But even if we wanted this, how would we implement it?  Seems pretty challenging.

**Comment by schmmd** [comment]
#719 improves the TQDM output in the log files, but doesn't address the Beaker issue because the output there is from stderr (see http://beaker.allenai.org/tk/tk_bn2iqablx6g5).  While the log file output won't contain long TQDM lines, the logs Beaker reports still do because Beaker reports stderr.

I'm considering adding a `--tqdm-newline` flag.  This flag would cause `tqdm` to output newlines after each status update [on the terminal](https://github.com/allenai/allennlp/blob/master/allennlp/common/tee_logger.py#L24) in addition to the logs.

**Comment by matt-gardner** [comment]
Ok, yes, now this makes more sense, thanks for the clarification.  That seems totally reasonable to me - remove the `no_tqdm` setting from `Trainer`, simplify that code, and put in a `--tqdm-newline` CLI option to the `train` command that modifies the `TeeLogger`.
