### ISSUE TITLE
Add start and end tokens to source sentence in seq2seq DatasetReader

### ISSUE THREAD

**Issue by maxdel** [allenai/allennlp#611]
Two points here:
1) Is it intentional that you do not append the `@@END@@` token to the source sequence?
2) These `@@START@@` and `@@END@@` tokens are currently added inside the seq2seq dataset reader directly. However, there is also a way to add them via WordTokenizer params. Next, one could fetch them from the WordTokenizer instance inside the dataset reader for a future use in the decoder.

**Comment by maxdel** [comment]
Edit: 
regarding the 1st point, I now see from the literature that there are many ways people use these tokens. E.g.:
* Microsoft [uses](https://www.microsoft.com/en-us/cognitive-toolkit/blog/2016/11/sequence-to-sequence-deep-recurrent-neural-networks-in-cntk-part-1/) (see 2d figure) them just like you do  
* Amazon [uses](https://aws.amazon.com/blogs/ai/train-neural-machine-translation-models-with-sockeye/) (see 1st figure) them just like you do, but also with <EOS> at the end of source sentence
* Philipp Koehn [uses](https://arxiv.org/abs/1709.07809) (see Figure 13.22, page 53) them just like Amazon, but also with <SOS> at the beginning of the source sentence
So I think it is not a point anymore.

**Comment by matt-gardner** [comment]
Oh, I hadn't thought about the implications of including the end token as part of the encoder...  We were only thinking about the fact that it never gets input to the decoder.  I'm really not sure if it makes a difference.  If you discover that it does make a difference, by all means, submit a PR to fix it, or make it an option.

For your second point, these tokens have special meaning that the _model_ needs to know about.  The model doesn't currently have access to the `DatasetReader` object, and it isn't really desirable from an API standpoint to give it.  So instead we define shared constants that both the `DatasetReader` and the `Model` use.  It doesn't really make sense to configure this in the tokenizer.  We had some discussion of this here: https://github.com/allenai/allennlp/pull/366#discussion_r143308089.

**Comment by maxdel** [comment]
Having EOS appended to the source gives decoder something it can always attend to while generating target EOS.  Without source EOS, it mostly learns to attend to the last source token whatever it is (e.g. dot, question mark, or some word). This might require more effort from the model then just explicitly attending to the source EOS in all cases. E.g. my recent model (not exactly seq2seq, but anyway), at its first epochs, does not generate EOS when I remove the dot from the end of the source. 

Regarding the 2nd point, yes, it makes sense.

**Comment by matt-gardner** [comment]
Yeah, that makes a lot of sense.  I'm going to change the name of this issue to something like "Add an end token to the source tokenizer".  If you want to submit a PR to fix it, that'd be great.
