### ISSUE TITLE
error in demo app

### ISSUE THREAD

**Issue by avr248** [allenai/allennlp#622]
result = torch.nn.functional.softmax(vector * mask, dim=-1)
TypeError: softmax() got an unexpected keyword argument 'dim'

**Comment by DeNeutoy** [comment]
Hello! Did you observe this in our live demo at http://demo.allennlp.org/ ? If you are running this locally, you probably need to upgrade to pytorch 0.3.

**Comment by schmmd** [comment]
I saw this error yesterday, and the problem was that I was running code that expected PyTorch 0.3 but I had PyTorch 0.2 installed.

**Comment by avr248** [comment]
thanks!! I't work.
