### ISSUE TITLE
Non-spacy Tokenizers don't show text of passage tokens in SQuAD debug

### ISSUE THREAD

**Issue by nelson-liu** [allenai/allennlp#624]
Hi,

I'm trying to use allennlp as a squad dataloader in my code, but I noticed that some passages were incorrectly tokenized by spacy due to wikipedia `[notes]` and `[citations]` (same issue as https://github.com/allenai/allennlp/issues/236).

Upon switching to the `LettersDigitsWordSplitter` that solves this problem, the squad debug output for the actual tokens generated is just a list of token objects and their addresses (as opposed to readable strings), since `__repr__` / `__str__` isn't implemented. Would you mind a PR to add these (will probably just [copy from SpaCy](https://github.com/explosion/spacy/blob/master/spacy/tokens/token.pyx#L65-L77)), or do you think that there's a better way to go about solving this?

Thanks!

**Comment by matt-gardner** [comment]
A PR adding `__repr__` or `__str__` methods on our `Token` objects would be great, and yes, I think that's the right thing to do here.
