### ISSUE TITLE
Question about SRL performance in the host page.

### ISSUE THREAD

**Issue by qcl6355** [allenai/allennlp#632]
> The AllenNLP SRL model closely matches the published model, achieving a F1 of 78.9 on English Ontonotes 5.0 dataset using the CONLL 2011/12 shared task format.

My Question is that whether F1 of 78.9 was achieved  by using __single model__ on CoNLL 2012 test dataset?

**Comment by DeNeutoy** [comment]
Hi, yes the stated performance is using a single model.

**Comment by qcl6355** [comment]
@DeNeutoy Got it. Thanks a lot.
