### ISSUE TITLE
 Sparse Embedding Error

### ISSUE THREAD

**Issue by maxdel** [allenai/allennlp#651]
Hi,

I use SGD optimizer without momentum and sparse embedding (parameters are set via config file).
However, I get following error when sparse is True: `AttributeError: ‘torch.sparse.FloatTensor’ object has no attribute ‘ge’`. If I pass `"sparse": false` everything works fine.

> 
> Traceback (most recent call last):
>   File "run.py", line 17, in <module>
>     main(prog="python run.py")
>   File "/home/del/Desktop/RESEARCH-PROJECTS/umt/sp/allennlp/commands/__init__.py", line 77, in main
>     args.func(args)
>   File "/home/del/Desktop/RESEARCH-PROJECTS/umt/sp/allennlp/commands/train.py", line 73, in train_model_from_args
>     train_model_from_file(args.param_path, args.serialization_dir)
>   File "/home/del/Desktop/RESEARCH-PROJECTS/umt/sp/allennlp/commands/train.py", line 89, in train_model_from_file
>     return train_model(params, serialization_dir)
>   File "/home/del/Desktop/RESEARCH-PROJECTS/umt/sp/allennlp/commands/train.py", line 178, in train_model
>     trainer.train()
>   File "/home/del/Desktop/RESEARCH-PROJECTS/umt/sp/allennlp/training/trainer.py", line 374, in train
>     train_metrics = self._train_epoch(epoch)
>   File "/home/del/Desktop/RESEARCH-PROJECTS/umt/sp/allennlp/training/trainer.py", line 224, in _train_epoch
>     loss.backward()
>   File "/home/del/anaconda2/envs/umt/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
>     torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
>   File "/home/del/anaconda2/envs/umt/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
>     variables, grad_variables, retain_graph)
>   File "/home/del/Desktop/RESEARCH-PROJECTS/umt/sp/allennlp/training/trainer.py", line 159, in <lambda>
>     clip_function = lambda grad: grad.clamp(-self._grad_clipping, self._grad_clipping)
>   File "/home/del/anaconda2/envs/umt/lib/python3.6/site-packages/torch/autograd/variable.py", line 336, in clamp
>     return Clamp.apply(self, min, max)
>   File "/home/del/anaconda2/envs/umt/lib/python3.6/site-packages/torch/autograd/_functions/pointwise.py", line 99, in forward
>     ctx._mask = (i.ge(min_val) * i.le(max_val))
> AttributeError: 'torch.sparse.FloatTensor' object has no attribute 'ge'

Can it be the case that using nn.Embedding instead of functional API will solve the problem?

Thanks,
Maksym

**Comment by matt-gardner** [comment]
I don't have any good ideas about what's going on here, and we're all on vacation until January 2nd, so I don't want to dig into it right now.  Maybe @DeNeutoy will have some idea when he gets back from vacation.

**Comment by DeNeutoy** [comment]
I don't think this is an allennlp issue - it's just that support for sparse tensors in Pytorch is not that advanced yet. This is happening because `clip_by_value` uses `tensor.ge` to create a mask for values to clip, but this function is not implemented for sparse tensors. It might work if you remove gradient clipping, but I imagine you will run into many other problems.

**Comment by schmmd** [comment]
I'm closing this issue given @DeNeutoy 's response, but feel free to reopen if there's more to discuss!
