### ISSUE TITLE
Reading Instances from lines in file: out of memory error

### ISSUE THREAD

**Issue by maxdel** [allenai/allennlp#652]
Hi,

I am implementing skip-gram model using allennlp so I have a huge amount of training examples (word pairs). Say 150,000,000 or even more in the future. 

allennlp reads all these lines into Instances to build a Dataset, but it keeps the whole thing in the memory so that I run out of memory pretty fast. 

Are there any ways around it? 

Thanks,
Maksym

**Comment by EgorLakomkin** [comment]
You could subclass DataIterator and write your own implementation of batch generation process (indexing with vocabulary, padding, converting to tensor). But I am not sure if it is the best way.

**Comment by matt-gardner** [comment]
You would have to also subclass `Dataset`, making a `LazyDataset` or similar that is returned by the `DatasetReader`.  The `LazyDataset` would probably want to take a `Callable` in its constructor, so the `DatasetReader` can pass on the logic for reading instances.  Not sure exactly what this API should look like, but it'd be something along these lines.  And then you'd have a simple `LazyDataIterator` that's like `BasicIterator` but doesn't rely on having all of the instances in memory.  It might also be possible to just modify the `BasicIterator` to work in this case, but things like the call to `shuffle` wouldn't work.

This is something we've known we'd have to do eventually, but haven't gotten to yet.  PRs welcome.

**Comment by matt-gardner** [comment]
Mandar is also running into this problem with TriviaQA, and I expect that once we get to putting Chris's DocumentQA stuff into AllenNLP, we'll run into the same issue ourselves (@joelgrus FYI).  I think this should probably be higher on our priority list.  And when we do this, it might be worth looking into pytorch's DataLoader that has built-in multi-processing functionality to see if there's anything we can use there.

**Comment by joelgrus** [comment]
I'll spend a little time thinking about/exploring this

**Comment by joelgrus** [comment]
here's a first stab, let me know what you think of this approach:

https://github.com/allenai/allennlp/pull/660

**Comment by schmmd** [comment]
Fixed by https://github.com/allenai/allennlp/pull/675
