### ISSUE TITLE
Make Span F1 match perl script exactly for SRL model

### ISSUE THREAD

**Issue by DeNeutoy** [allenai/allennlp#667]
The Span based F1 metric doesn't exactly match the perl script for evaluating the SRL model. I think this is because the perl script treats continuation and reference spans (C-B-TAG, R-B-TAG) as part of the same span as what they are continuing or referencing, whereas the allennlp metric treats these as separate spans.

**Comment by DeNeutoy** [comment]
Yes, this is why - continued arguments are treated as single spans: https://github.com/allenai/allennlp/blob/master/scripts/srl-eval.pl#L1848

**Comment by schmmd** [comment]
@DeNeutoy is this still an issue?

**Comment by DeNeutoy** [comment]
Yes.... But we need a perl expert.

**Comment by iellenberger** [comment]
@DeNeutoy - find me when I', in the office tomorrow and I'll see what I can do.

**Comment by sanketvmehta** [comment]
@DeNeutoy and team: Do we have any updates on this issue? Based upon my current experiments, I see a bit discrepancy between F1-scores using the current implementation and the standard evaluation script (eval.pl).

**Comment by DeNeutoy** [comment]
No, sorry. I still don't know why they are different.

**Comment by matt-gardner** [comment]
Closing this, as #2743 largely makes it obsolete.
