### ISSUE TITLE
Investigate mypy version issues

### ISSUE THREAD

**Issue by matt-gardner** [allenai/allennlp#690]
When using an updated version of mypy (0.560), our mypy check passed on a particular commit when it should have failed (see #680).  As a result, we pinned the mypy version to 0.521 (see #689).  There is probably a mypy bug here that should be reported upstream, it'd be good to tell them about it.

Also, we should figure out which mypy version we should be using.  0.521 from 0.560 seems like a big jump backwards.  Maybe there's an intermediate (or later!) version that's better.

**Comment by matt-gardner** [comment]
#696 requires a later version of mypy to successfully type check.  mypy gives a `Module has no attribute "getrusage"` error on the `resource` module with version 0.521, but gives no error with 0.530.  Unfortunately, 0.530 passes the commit in #680 that should have failed.  Not sure what to do here.

**Comment by schmmd** [comment]
I think we've probably figured this out since January.  Please reopen if this is an ongoing issue.
