### ISSUE TITLE
investigate whether `allennlp.run` could take auxiliary modules as command line args and use importlib

### ISSUE THREAD

**Issue by joelgrus** [allenai/allennlp#694]
i.e. it's possible that if I make my own models etc in `allennlp_joel.models`, `allennlp_joel.dataset_readers`, and so on, that I could do something like

```
python -m allennlp.run --extra-modules allennlp_joel train ...
```

and use `importlib` to programmatically import everything and not have to write my own executable

**Comment by matt-gardner** [comment]
Yeah, this sound like it could work, and would be a great idea.
