### ISSUE TITLE
Vocabulary.from_instance ?

### ISSUE THREAD

**Issue by transfluxus** [allenai/allennlp#703]
says the `tutorials/notebooks/data_pipeline.ipynb`.
I guess it should be `Vocabulary.from_dataset`

**Comment by joelgrus** [comment]
that corresponds to a recent change we made in master that hasn't been released yet. if you're using one of our releases, please browse the tutorials at the corresponding tag, e.g.

https://github.com/allenai/allennlp/tree/v0.3.0/tutorials/notebooks
