### ISSUE TITLE
Pytorch 0.4 numpy indexing

### ISSUE THREAD

**Issue by justinchiu** [allenai/allennlp#704]
It seems like numpy indexing isn't supported in pytorch 0.4, so changing `sequence_lengths = mask.sum(dim=1).data.cpu().numpy()` to `sequence_lengths = mask.sum(dim=1).data.cpu().tolist()` in nn/util.py helps the elmo tests pass.

**Comment by DeNeutoy** [comment]
Thanks! We currently run on Pytorch 0.3 and we tend to update in a single go for Pytorch because it's a big dependency. If you can fix a test which helps you personally and it doesn't break using our current version of Pytorch, go ahead and submit a PR.
