### ISSUE TITLE
torch.Tensor type annotations

### ISSUE THREAD

**Issue by DeNeutoy** [allenai/allennlp#71]
We should work out whether these are actually the correct type annotation for many of our functions. For many functions, we are actually only ever passing `torch.autograd.Variables`, including some which actually require this, e.g:

```
# raises
torch.nn.functional.softmax(torch.rand([3,4]))

# fine
torch.nn.functional.softmax(torch.autograd.Variable(torch.rand([3,4])))
```
I think we can still keep the tensor types by doing something like:
`torch.autograd.Variable[torch.FloatTensor]` etc.

**Comment by matt-gardner** [comment]
Yeah, I thought about this too yesterday.  They probably should be annotated as `Variable`, not as `Tensor`.  We don't typically give the data type in the type annotation, so no need to parameterize the variable type.

**Comment by ibrahimsharaf** [comment]
Hi @matt-gardner, how can I start solving this issue?

**Comment by matt-gardner** [comment]
@ibrahimsharaf, @joelgrus actually already made all of the type changes as part of #374.  It's still in progress / experimental, though, so it hasn't referenced this issue yet.

**Comment by joelgrus** [comment]
my current understanding is that pytorch is getting rid of `Variable`s anyway:

https://github.com/pytorch/pytorch/issues/2633
https://twitter.com/soumithchintala/status/915645386437615626

I don't really know what the timeframe for that is, but I'm somewhat inclined to wait for that.

**Comment by schmmd** [comment]
I'm closing this issue since Torch is getting rid of variables (although I agree this is somewhat of a mess in our codebase as well).
