### ISSUE TITLE
Make it easy to use ELMo

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp#736]
I/O for sentences -> word vectors
* How to use ELMo in my existing ALlenNLP model
* How to use ELMo if I want to use TensorFlow

**Comment by schmmd** [comment]
@matt-peters do you actually think we should cover "How to use ELMo if I want to use TensorFlow"?  If we want to cover this, are you able to handle it?

**Comment by matt-peters** [comment]
A link somewhere to the `bilm-tf` repo is sufficient, there is documentation there about how to use the tensorflow version.

**Comment by schmmd** [comment]
We link to `bilm-tf` in http://allennlp.org/elmo.  I'll close this issue once we add elmo as a tab on allennlp.org.
