### ISSUE TITLE
simple server that serves up a single model

### ISSUE THREAD

**Issue by joelgrus** [allenai/allennlp#738]
this already exists as `service/server_simple.py`, but we also need

* a tutorial about how to use it (#589) which is in progress but waiting on #727 
* an easy way to get visualizations into it

**Comment by matt-gardner** [comment]
I did a bunch of hackery to get my wikitables demo up, modifying the result of the `serve` command; if there were an easy way to just use the simple server to put up a demo that shows visualizations, and a tutorial for how to do it, that would have been nice.  Just a +1 for your second bullet there.

**Comment by schmmd** [comment]
@joelgrus is the only remaining item to provide an easy way to get visualizations into the demo?

**Comment by joelgrus** [comment]
this is a judgment call, the tutorial shows how to get a pie chart in your demo, but if we want like a full React setup then that's not done yet
