### ISSUE TITLE
Why allennlp seq2seq model takes up so much memory?

### ISSUE THREAD

**Issue by LeoLiu1998** [allenai/allennlp#756]
Hi, I have tried to use the allennlp framework to build up a baseline for my model. I simply use the model provided in allennlp.
This is my config file:

```
{
  "dataset_reader":{
    "type":"seq2seq",

    "source_token_indexers": {
      "tokens": {
        "type": "single_id",
        "namespace": "source_tokens"
      }
    },

    "target_token_indexers": {
      "tokens": {
        "type": "single_id",
        "namespace": "target_tokens"
      }
    }
  },


  "train_data_path": "xxxxxxx",
  "validation_data_path": "xxxxxxx",
  "test_data_path": "xxxxxxx",

  "model": {
    "type": "simple_seq2seq",
    "source_embedder": {
      "tokens": {
        "type": "embedding",
        "embedding_dim":150,
        "vocab_namespace": "source_tokens",
        "trainable": true
      }
    },

    "encoder": {
      "type": "lstm",
      "input_size": 150,
      "hidden_size": 150,
      "num_layers": 5
    },

    "max_decoding_steps": 200,
    "target_namespace": "target_tokens",
    "attention_function": {"type": "dot_product"}
  },

  "iterator": {
    "type": "bucket",
    "batch_size" : 16
  },

  "trainer": {
    "num_epochs": 15,
    "patience": 10,
    "cuda_device": -1,
    "optimizer": {
      "type": "adam",
      "lr": 0.01
    }
  }
}
```

Before I through everything onto the computing cluster, I ran a test with only 5 training pairs which are about **2.4 kb in total**. I add `memory_profiler` decorator to track the memory usage.

This is what I have in the end:
```
Filename: run.py

Line #    Mem usage    Increment   Line Contents
\================================================
    18     49.3 MiB     49.3 MiB   @profile
    19                             def profWrap() -> None:
    20    148.7 MiB     99.4 MiB       cProfile.run('from allennlp.commands.train import train_model_from_file')
    21    377.7 MiB    228.9 MiB       cProfile.run('train_model_from_file("./model/baseline.json", "./result")')
```
I was shocked, the memory usage increase 150 thousands times.....

**Comment by matt-gardner** [comment]
That command is going to load a spacy model, import a bunch of torch libraries, and many other things.  I'm not very surprised that it's using that much memory, and I'm not sure just from that evidence that it's `allennlp` that's the problem.  How much does memory usage increase from that baseline if you use a larger dataset?

**Comment by LeoLiu1998** [comment]
Yeah, that factor came to my realization later as well. So I increase the size; now the dataset is 44 pairs, which include some long sentences. It memory profiler give me this: 

```
Filename: run2.py

Line #    Mem usage    Increment   Line Contents
================================================
    18     49.5 MiB     49.5 MiB   @profile
    19                             def profWrap():
    20    149.8 MiB    100.3 MiB       cProfile.run('from allennlp.commands.train import train_model_from_file')
    21    628.4 MiB    478.6 MiB       cProfile.run('train_model_from_file("./model/baseline2.json", "./result2")')

```

I think if I simply compare these two cases, it seems fine. However, I wonder how to train the model on dataset of 30,000 pairs or maybe even larger dataset. I used to train the model on a computing clustering, it works really slow. However, since it's laborious to talk about the training config, so I will just ask for some general advice.

I found in the old issues that someone suggested `LazyDataset` and `LazyIterator`, but there is not yet official module for usage. Can you give me some advice on how to use allennlp framework to train the model on my dataset?

**Comment by matt-gardner** [comment]
Yes, you can now use datasets lazily, though I don't imagine you would need to if you only have 30k instances.  I would try it as-is and see how much memory you're using with the full dataset before trying to change your code to fix things that aren't actually a problem.  If you _do_ run into a problem on the full dataset, please let us know, because 30k instances in a simple seq2seq problem should not be using huge amounts of memory.  If you have a huge dataset and really need to use lazy iteration, see [here](https://github.com/allenai/allennlp/issues/737#issuecomment-362653344).

And no, no truncation is done on any input.  If you use a `BucketIterator`, we'll sort the instances by size (with some noise) and group them into batches of roughly the same size.  If you want to do truncation, you need to implement that yourself in your `DatasetReader`.

**Comment by joelgrus** [comment]
FYI: I just opened #763 to add a lazy param to all of the existing dataset readers and #764 to write a laziness tutorial.

**Comment by LeoLiu1998** [comment]
@matt-gardner 
My training encounters some problem. 
The setting is reduced a bit:
```
"model": {
    "type": "simple_seq2seq",
    "source_embedder": {
      "tokens": {
        "type": "embedding",
        "embedding_dim":100,
        "vocab_namespace": "source_tokens",
        "trainable": true
      },
    },

    "encoder": {
      "type": "lstm",
      "input_size": 100,
      "hidden_size": 100,
      "num_layers": 3
    },
    "scheduled_sampling_ratio": 1.0,
    "max_decoding_steps": 200,
    "target_namespace": "target_tokens",
    "attention_function": {"type": "dot_product"}
  },

  "iterator": {
    "type": "bucket",
    "batch_size" : 32
  },

  "trainer": {
    "num_epochs": 5,
    "patience": 4,
    "cuda_device": -1,
    "optimizer": {
      "type": "adam",
      "lr": 0.01
    }
  }

```

However, the output shows error message:

```
  File "run.py", line 26, in <module>
    profWrap()
  File "/usr/lusers/zeyuliu2/miniconda3/lib/python3.6/site-packages/memory_profiler.py", line 1072, in wrapper
    val = prof(func)(*args, **kwargs)
  File "/usr/lusers/zeyuliu2/miniconda3/lib/python3.6/site-packages/memory_profiler.py", line 659, in f
    return func(*args, **kwds)
  File "run.py", line 21, in profWrap
    cProfile.run('train_model_from_file("./model/baseline.json", "./result")')
  File "/usr/lusers/zeyuliu2/miniconda3/lib/python3.6/cProfile.py", line 16, in run
    return _pyprofile._Utils(Profile).run(statement, filename, sort)
  File "/usr/lusers/zeyuliu2/miniconda3/lib/python3.6/profile.py", line 55, in run
    prof.run(statement)
  File "/usr/lusers/zeyuliu2/miniconda3/lib/python3.6/cProfile.py", line 95, in run
    return self.runctx(cmd, dict, dict)
  File "/usr/lusers/zeyuliu2/miniconda3/lib/python3.6/cProfile.py", line 100, in runctx
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/usr/lusers/zeyuliu2/miniconda3/lib/python3.6/site-packages/allennlp/commands/train.py", line 89, in train_model_from_file
    return train_model(params, serialization_dir)
  File "/usr/lusers/zeyuliu2/miniconda3/lib/python3.6/site-packages/allennlp/commands/train.py", line 178, in train_model
    trainer.train()
  File "/usr/lusers/zeyuliu2/miniconda3/lib/python3.6/site-packages/allennlp/training/trainer.py", line 374, in train
    train_metrics = self._train_epoch(epoch)
  File "/usr/lusers/zeyuliu2/miniconda3/lib/python3.6/site-packages/allennlp/training/trainer.py", line 224, in _train_epoch
    loss.backward()
  File "/usr/lusers/zeyuliu2/miniconda3/lib/python3.6/site-packages/torch/autograd/variable.py", line 167, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
  File "/usr/lusers/zeyuliu2/miniconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    variables, grad_variables, retain_graph)
RuntimeError: $ Torch: not enough memory: you tried to allocate 13GB. Buy new RAM! at /pytorch/torch/lib/TH/THGeneral.c:246
```

The first line is just saying that I am using a cProfiler to wrap my trainning command:

```
@profile
def profWrap():
    cProfile.run('from allennlp.commands.train import train_model_from_file')
    cProfile.run('train_model_from_file("./model/baseline.json", "./result")')


if __name__ == "__main__":
    profWrap()

```

**Comment by matt-gardner** [comment]
That's a memory error in the _computation graph_, not when loading the data.  Lazy data iteration won't help you here.

There are a few possible causes of this:

1. If your sequences are very long, it's not hard to imagine running out of memory when computing attention.  You could truncate your sequences, if that's an acceptable modeling option for you.
2. Our `Attention` module sacrifices memory usage to gain flexibility in choice of similarity function.  There are much more efficient ways to compute attention, and this piece is probably what's causing your memory errors.  You could change the model code to use a more memory-efficient attention option.
3. This is related to 1, but if you can't truncate your sequences, you could instead decrease your batch size.

Also, you're not actually getting the benefits of a bucket iterator, because you're not providing sorting keys to use to group your data into similarly-sized batches.  You should add a key to your `"iterator"` parameters that's something like `"sorting_keys": [["source_tokens", "num_tokens"], ["target_tokens", "num_tokens"]]`.

**Comment by LeoLiu1998** [comment]
Can you recommend some attention module option, if allennlp does not have a memory-efficient ones?

**Comment by matt-gardner** [comment]
You can just use `torch.bmm` to do a dot product.  We should add some `Modules` for some of the options here, but it's pretty easy to do yourself, and it's not high on our priority list at the moment.

**Comment by LeoLiu1998** [comment]
Sure. There is one thing that happens to my Q&A model. After I sort the corpus, I realize the pair could be very long. **One** training pair has an input of 52 tokens(question) and output of 4243 tokens(answer). I expect there will be an error due to the memory usage, but the error message seems confusing:
```
Traceback (most recent call last):
  File "run2.py", line 26, in <module>
    profWrap()
  File "/Users/leoliu/anaconda3/lib/python3.6/site-packages/memory_profiler.py", line 1072, in wrapper
    val = prof(func)(*args, **kwargs)
  File "/Users/leoliu/anaconda3/lib/python3.6/site-packages/memory_profiler.py", line 659, in f
    return func(*args, **kwds)
  File "run2.py", line 21, in profWrap
    cProfile.run('train_model_from_file("./model/baseline2.json", "./result2")')
  File "/Users/leoliu/anaconda3/lib/python3.6/cProfile.py", line 16, in run
    return _pyprofile._Utils(Profile).run(statement, filename, sort)
  File "/Users/leoliu/anaconda3/lib/python3.6/profile.py", line 55, in run
    prof.run(statement)
  File "/Users/leoliu/anaconda3/lib/python3.6/cProfile.py", line 95, in run
    return self.runctx(cmd, dict, dict)
  File "/Users/leoliu/anaconda3/lib/python3.6/cProfile.py", line 100, in runctx
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/Users/leoliu/allennlp/allennlp/commands/train.py", line 82, in train_model_from_file
    return train_model(params, serialization_dir)
  File "/Users/leoliu/allennlp/allennlp/commands/train.py", line 167, in train_model
    trainer.train()
  File "/Users/leoliu/allennlp/allennlp/training/trainer.py", line 361, in train
    epoch_counter, validation_metric_per_epoch = self._restore_checkpoint()
  File "/Users/leoliu/allennlp/allennlp/training/trainer.py", line 484, in _restore_checkpoint
    self._model.load_state_dict(model_state)
  File "/Users/leoliu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 360, in load_state_dict
    own_state[name].copy_(param)
RuntimeError: inconsistent tensor size, expected tensor [44 x 100] and src [2570 x 100] to have the same number of elements, but got 4400 and 257000 elements respectively at /Users/soumith/miniconda2/conda-bld/pytorch_1503975723910/work/torch/lib/TH/generic/THTensorCopy.c:86
```

The dimension looks weird to me. And clearly, memory is enough. Is there any default setting in allennlp or maybe pytorch that is causing the problem? Like max length of input?

**Comment by matt-gardner** [comment]
That error is due to how we try to recover from partial training runs.  If you give a serialization directory that you've used previously for training, we'll try to load the model that's there and continue training from where you left off.  It looks like you tried training a smaller model for an epoch or two, and used the same directory for a larger model.  We need to give a better error in these cases; I'll open an issue for this.

**Comment by LeoLiu1998** [comment]
Thanks! I believe my problem is solved. I will close this issue.
