### ISSUE TITLE
Consider replacing the tensorboard dependency

### ISSUE THREAD

**Issue by matt-peters** [allenai/allennlp#762]
The tensorboard dependency isn't being updated on pip and install from source is difficult.  The mac version contains a bug in Python 3 when logging histograms.  We may want to replace it.  See comments here for more context: #749

**Comment by schmmd** [comment]
We're going to wait for the dependencies to settle down before we address this.

**Comment by nelson-liu** [comment]
FYI: PyTorch 0.3.1 (newest release) supports scoping, which would enable viewing ONNX-compatible pytorch graphs in tensorboard. 

[tensorboard-pytorch](https://github.com/lanpa/tensorboard-pytorch) already supports this, and it seems like they're working closely with the pytorch team to maintain interoperability (fwiw, tensorboard-pytorch is linked in the new pytorch release notes, which is a pretty big vote of confidence to me). 

The package is maintained, maybe it's worth switching back to that?
