### ISSUE TITLE
Archiving models at different points of training

### ISSUE THREAD

**Issue by eunsol** [allenai/allennlp#765]
Currently the model is only archived at the end of the training, if I'm understanding correctly. When the model starts to overfit, I just quit the training, and then no archived model file is formed, and it's a hassle to evaluate / predict from the model. Basically one has to manually build model.tar.gz file to predict from it. Overall it would be nice to be able to predict from different timestamps without creating model.tar.gz for each.

**Comment by schmmd** [comment]
@eunsol would https://github.com/allenai/allennlp/pull/734 fix your problem?  It would allow using directories in place of archives.

**Comment by eunsol** [comment]
would it allow predicting from different timestamps by specifying it? ideally, it will look something like 
"python -m allennlp.run predict --archive-folder ./where/model_lives/ --timestamp 4"

**Comment by schmmd** [comment]
No--that would require additional changes.

**Comment by joelgrus** [comment]
that's a pretty small additional change. it's a good idea

**Comment by schmmd** [comment]
I'll add a `--weights-file` flag.

**Comment by schmmd** [comment]
@eunsol we just merged a PR that addresses the issue you brought up.  Let us know if you have any further problems!

Please note that this was fixed on master but is yet unreleased.  We expect to have a new release next week.
