### ISSUE TITLE
Make Vocabulary an optional input to Model

### ISSUE THREAD

**Issue by matt-gardner** [allenai/allennlp#766]
This would let Matt Peters use part of AllenNLP without using the whole thing.  We're unsure whether this is a good change for AllenNLP.

**Comment by schmmd** [comment]
Assigning it to myself since I might need to do this for ensembles.

**Comment by schmmd** [comment]
I think we basically have this functionality with https://github.com/allenai/allennlp/pull/1000.  You can override `_load` and avoid loading a vocabulary.

**Comment by schmmd** [comment]
This is now possible, see https://github.com/allenai/allennlp/pull/1000.
