### ISSUE TITLE
Make Attention and MatrixAttention more memory efficient

### ISSUE THREAD

**Issue by matt-gardner** [allenai/allennlp#768]
The way I originally implemented the `Attention` module lets you swap out `SimilarityFunctions` to try a bunch of options if you want, but it does so at the expense of memory usage, often using _way_ more memory than is necessary.  It'd be better to just have `Attention` be an abstract, `Registrable` `Module`, with concrete implementations matching our `SimilarityFunctions`, but more memory efficient.  You'd still get the modularity, but without sacrificing memory usage.  #346 has one instance of this for `MatrixAttention`.

Next time I'm working on a model where this is the bottleneck, I'll just fix it, but I don't know when that will be.  If someone wants to contribute modules that do this, that'd be great.

**Comment by murphp15** [comment]
@matt-gardner I am struggling to see where we could gain memory here. 
Taking for argument sake the the DotProductSimilarity function. 
If we were to implement a class call DotProductAttention which extended from Attention how would we save memory? 
Would we be able to avoid the tiling operation and instead do some sort of batch dot product?

**Comment by murphp15** [comment]
From your comment above, 
What would the difference between Attention and MatrixAttention be if they are both Registerable classes?

**Comment by murphp15** [comment]
@matt-gardner I have created an initial PR here https://github.com/allenai/allennlp/pull/1235 for this ticket. 
I would love to get a bit of feedback on it before I proceed.

**Comment by matt-gardner** [comment]
Yeah, leaving in the old one as a legacy implementation is a good idea for now, and we can think about removing it entirely at some point.  This will still break our sniff tests, but we can worry about that after the refactoring is done.  For the tests that rely on fixtures in `tests/fixtures/`, there's a script called `scripts/retrain_fixtures.py` that you can use to update them so they use current code.

And opening a work-in-progress PR, with a "[WIP]" label, is definitely the right thing to do for in-progress stuff like this that you have questions about.

**Comment by matt-gardner** [comment]
Fixed by #1235.
