### ISSUE TITLE
Give a more helpful error message when model loading fails during training

### ISSUE THREAD

**Issue by matt-gardner** [allenai/allennlp#770]
https://github.com/allenai/allennlp/issues/756#issuecomment-362942024 brings up an error that I've seen somewhat frequently.  When you're still iterating on your model, it's really easy to run into a situation where allennlp tries to continue training from a previous epoch of a different model configuration.  The error message is particularly unhelpful in these situations.  It's even worse that the error message only appears _after_ you've loaded your data and computed the vocabulary, because these might take several minutes.

At the beginning of the `train` command (before loading any data), we should check if the `serialization` directory exists.  If it does, there are a few (not mutually-exclusive) options:
1. Check if the saved model parameters there match the current model parameters.  If they do, log a big message that we'll be continuing training from where it left off, noting that if you've changed model code things might crash later with cryptic messages.  If they don't, crash with an informative error message.
2. Add an `--overwrite-results` flag, or something, that always removes any existing serialization directory before training.
3. Catch a `RuntimeError` when we call `_restore_checkpoint` in `Trainer`, and change it into a more informative error message, suggesting using `--overwrite-results`, or something.

Actually, I'd probably recommend doing all three of those.

**Comment by schmmd** [comment]
I would have an explicit `--continue` flag.  Without this flag, the trainer would throw an exception if the output directory already exists.  With this flag, the trainer would throw an exception if the output directory existed and the parameters don't match.

I'm generally confused when a training continues from something that already exists and this parameter would help make it explicit.  I would likely miss the big message.

I wouldn't have an `--overwrite-results` flag.  I would instead rely on the user deleting the directory themselves.  This avoids potential permissions issues or the wrong directory passed in (`--output /`).

**Comment by matt-gardner** [comment]
Yeah, that sounds reasonable to me.  Continuing training is the odd case, not the usual case, so having the flag for that case is probably right.

Not having some kind of `--overwrite` flag also seems fine - I was thinking mostly of someone hitting up in their shell and running the previous command to try training again, to see if they fixed a bug - that's a really common pattern.  But adding `rm -rf /path/to/output && [allennlp command]` is just as easy as adding `--overwrite-results`, and safer for our code.  You're right.

**Comment by joelgrus** [comment]
+1, this seems like a good solution to me
