### ISSUE TITLE
Add ELMo to the CLI

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp#785]
* Configurable whether we output all (`--all`) three vectors or an average vector (`--average`).
* Able to output contextualized word vectors (input is a sentence) or [uncontextualized word vectors](https://github.com/allenai/allennlp/blob/master/scripts/create_elmo_embeddings_from_vocab.py) (input is a word).

**Comment by DeNeutoy** [comment]
also flags for individual layers would probably be an easy and helpful addition, like `--top, --middle, --bottom`

**Comment by matt-peters** [comment]
My $0.02, I'd add the `--top` flag but eliminate the rest -- more code to maintain, and if the model is swapped out at some point in the future for one with more/less layers then the `--middle` flag is not longer meaningful.  The `--bottom` is covered in the uncontextualized case.

**Comment by schmmd** [comment]
@matt-peters @DeNeutoy after a discussion with Matt Peters I was a bit confused about what support we want for uncontextualized word vectors.  Matt mentioned that the script referred to above was for a caching strategy that wasn't fully implemented.  He also mentioned that uncontextualized word vectors wouldn't be an advantage over word2vec vectors.

Do we want to add support for uncontextualized word vectors to the elmo command?  If so, what do you envision it looking like?

**Comment by matt-peters** [comment]
It'd be nice to finish the caching strategy where the uncontextualized word vectors are pre-computed for a fixed vocabulary as it speeds up computing the contextual vectors and reduces memory pressure.  But without that I don't see an immediate need to add the uncontextualized flag here.

**Comment by schmmd** [comment]
I'm closing this, but I opened https://github.com/allenai/allennlp/issues/809.
