### ISSUE TITLE
Broken link in "using your repo" tutorial

### ISSUE THREAD

**Issue by roys174** [allenai/allennlp#786]
In https://github.com/allenai/allennlp/blob/v0.3.0/tutorials/getting_started/using_in_your_repo.md#first-step-install-allennlp, "the installation tutorial" link leads to https://github.com/allenai/allennlp/blob/v0.3.0/tutorials/getting_started/installation, which is not found.

**Comment by schmmd** [comment]
We'll make sure this is fixed when we release version 0.4.

**Comment by roys174** [comment]
Another broken link: 
In https://github.com/allenai/allennlp/blob/v0.3.0/tutorials/getting_started/configuration.md, the final link (Next Steps -> Continue on to our Creating a Model tutorial) is also dead.

**Comment by joelgrus** [comment]
these were both fixed by #669
