### ISSUE TITLE
Evaluation flag in DatasetReader.read

### ISSUE THREAD

**Issue by mandarjoshi90** [allenai/allennlp#792]
The current `DatasetReader.read` interface uses the same processing for training and validation/test data. It's possible that evaluation data might require a different kind of processing. For example, Chris' multi-paragraph model uses more paragraphs at test time compared to training time. 

One way to fix this would be to add a `evaluation` flag to read which would allow a different kind of processing. This would also be probably useful for `make-vocab` although you could simply create a new dataset reader for that.

**Comment by schmmd** [comment]
@mandarjoshi90 thanks for posting this issue.  We're aware of the problem and are thinking of the best way to address it.

**Comment by schmmd** [comment]
This will probably get addressed while we work through the multiparagraph qa project.
