### ISSUE TITLE
Figure out how to do visualizations with the simple server

### ISSUE THREAD

**Issue by matt-gardner** [allenai/allennlp#793]
We now have a rough how-to that gives a guide for visualizing model internals in your demo.  But, it uses the main demo server, not the simple server, and it'd be a whole lot more useful if it used the simple server.  But the simple server doesn't use react, and it's not immediately obvious to me how to make this work.  @joelgrus had some thoughts here: https://github.com/allenai/allennlp/pull/692#issuecomment-363943949.

Once we can easily add visualizations to the simple server, it probably makes sense to update the existing how-to, and maybe just add it to the exist demo tutorial, or at least link to it there.

**Comment by joelgrus** [comment]
after thinking on this, probably the best solution is to create a somewhat full-featured (but skeletal) example site and change the `static_html` part of the tutorial from "copy the default index.html" to "copy the example site" (which could live in its own repo maybe?)

I think it's fine/good to use stuff like react in that example site, but probably we shouldn't do anything that requires a JavaScript toolchain (compiling CSS, transpiling source files, etc...), IMO that would raise the barrier to entry too high.

**Comment by schmmd** [comment]
I agree that the JavaScript toolchain is a big barrier!

**Comment by matt-gardner** [comment]
Again, I'm not really familiar with this stuff, but doesn't "javascript toolchain" just mean "run `npm start`"?  If that's all that you need to do, it doesn't seem like a huge barrier.  I don't know what the best solution here is, but when I ran the demo the first time, it wasn't that hard to install node.js and npm and get it running.  Rajas and Mandar were also able to do this without issues, running demos I built on their own machines.

**Comment by joelgrus** [comment]
this is more work than I estimated at the issue meeting, so I'm going to leave it for the future

**Comment by matt-gardner** [comment]
Is it easy to give an estimate of what needs to be done?  I think over the next few days I might be just running a bunch of things, and might have some time to look at this while experiments are running.

**Comment by joelgrus** [comment]
sure, you can take a look at what I was trying to do:

https://github.com/allenai/allennlp-simple-server-visualization

I was hoping to load all the scripts inline, so I wouldn't have to compile anything, but it looks like that's not going to work with the `HeatMap` component (which is written as a node module).

If I were to keep on with this, I would probably do the following:

* write out instructions for installing npm + webpack
* remove all the <script> tags that load react etc from cdns and use npm for those dependencies
* remove all the inline scripts in index.html and put then in their own javascript module
* replace the HTML in index.html with react components
* write out instructions for how to compile the site with webpack and how to run it with server_simple

(you don't have to use webpack, there's alternatives, I don't know much about the space)

**Comment by matt-gardner** [comment]
My current thought: just have a stripped-down version of our actual demo source, and the same instructions, just telling people to use `npm start` to serve their html, and have it re-direct to the simple server for getting predictions.  The basic instructions would be:

1. To start with, follow your existing tutorial to get a basic text in / text out demo. This makes sure your predictor is set up right, and your demo works.
2. Copy the stripped-down demo code from our example repo.  This will have just some blanks for input fields and some placeholders for output fields.
3. Modify the input fields to hook up to the inputs you actually have in your model.  We can make sure our example repo makes what's needed here sufficiently obvious.
4. Run this code using `npm start`, as in our current demo instructions, and point your browser to port 3000 instead of 8000.  Make sure that you still get your basic text in / text out behavior, after hooking up your inputs to the placeholder input fields.  (Note that you still have the simple server running, it's now just only serving `/predict` requests, instead of the HTML.)
5. Modify the outputs to your heart's content, including using our fancy visualization components.

Sound reasonable?  If so, I'll work on this tomorrow.

**Comment by schmmd** [comment]
Sounds great!  If I were doing this myself I would avoid using `npm` (although maybe that's not possible), but if it was smooth sailing for you, sounds great.

**Comment by joelgrus** [comment]
it sounds fine, my main worry is that we're going to have to support this use case and none of us has much npm expertise 😁 (and that the port 3000 / port 8000 thing will confuse people, as it's confused us many times)

**Comment by matt-gardner** [comment]
Alright, I've got a PR open on that visualization repo: https://github.com/allenai/allennlp-simple-server-visualization/pull/1.  I don't have any permissions there.  There are also a few minor changes to the main repo that I need to make; I'll make those later, and update the how-to for visualizing model internals, after we're happy with what's in the other repo.

**Comment by matt-gardner** [comment]
Fixed by #872.
