### ISSUE TITLE
DatasetReaders no longer have any tqdm output on read

### ISSUE THREAD

**Issue by matt-gardner** [allenai/allennlp#814]
This is unfortunate if you're reading a lot of data, because you just sit there not knowing how long it's going to take.  Probably the fix is to change the `lazy=False` case in `DatasetReader.read()` to use `tqdm` instead of `ensure_list`.  I'll do this soon unless someone tells me there's a better way to do this.

**Comment by joelgrus** [comment]
before the "lazy" refactor a few weeks ago, the base `DatasetReader` class didn't have any functionality in it at all, so I'm not sure where the "no longer" comes from.

I believe tqdm has always been handled by the subclasses themselves, e.g.

https://github.com/allenai/allennlp/blob/master/allennlp/data/dataset_readers/seq2seq.py#L69

**Comment by matt-gardner** [comment]
Oh, I didn't realize that the tqdm lines were still in some of the subclasses...  Having it in the subclass doesn't play nicely with `lazy=True`, because you get a tqdm line for the dataset reader in every batch, so I had removed it from readers that I'm actively using.  I'll update #815 to remove all `tqdm` calls from subclasses.
