### ISSUE TITLE
The NER JS code doesn't check for tag type consistency when creating spans from BIOUL labels

### ISSUE THREAD

**Issue by DeNeutoy** [allenai/allennlp#817]
This means that the visual demo output does not match the output of running a model locally in the case that the tag sequence is ill defined. We should implement constrained decoding to fix this, because it should also improve the model.

Here is the relevant code:

https://github.com/allenai/allennlp/blob/master/demo/src/components/NamedEntityComponent.js#L172

**Comment by joelgrus** [comment]
I made a PR #818 for constrained decoding
