### ISSUE TITLE
TokenCharactersEncoder Cannot Handle 4 Dimensional Input

### ISSUE THREAD

**Issue by rajasagashe** [allenai/allennlp#820]
Here's the error message:
```
  File "allennlp/allennlp/models/encoder_decoders/wikitables_semantic_parser.py", line 183, in forward
    embedded_table = self._question_embedder({'tokens': tokens_tensor, 'token_characters': token_characters_tensor})
  File "allennlp/allennlp/modules/text_field_embedders/basic_text_field_embedder.py", line 49, in forward
    token_vectors = embedder(tensor)
  File "allennlp/allennlp/modules/token_embedders/token_characters_encoder.py", line 36, in forward
    return self._dropout(self._encoder(self._embedding(token_characters), mask))
  File "allennlp/allennlp/modules/time_distributed.py", line 35, in forward
    reshaped_outputs = self._module(*reshaped_inputs)
  File "allennlp/allennlp/modules/seq2vec_encoders/cnn_encoder.py", line 106, in forward
    self._activation(convolution_layer(tokens)).max(dim=2)[0]
  File "lib/python3.6/site-packages/torch/nn/modules/conv.py", line 166, in forward
    self.padding, self.dilation, self.groups)
  File "lib/python3.6/site-packages/torch/nn/functional.py", line 49, in conv1d
    raise ValueError("Expected 3D tensor as input, got {}D tensor instead.".format(input.dim()))
ValueError: Expected 3D tensor as input, got 4D tensor instead.
```

Background:
When doing characters embeddings for the wikitables dataset, the input vector is 4 dimensional.
`(batch_size, num_entities, num_entity_tokens, num_entity_token_characters)`

When the vector reaches this line:

https://github.com/allenai/allennlp/blob/40dcf53c57464a51488a86e58fa583aff3058d44/allennlp/modules/token_embedders/token_characters_encoder.py#L36
The embedder adds another dimension to make it:
`(batch_size, num_entities, num_entity_tokens, num_entity_token_characters, character_embedding_dim)`

When it is passed to the CNN Encoder the first two dimensions (batch_size, num_entities) are collapsed by the time distributed to a 4D vector which results in this error as CNN encoder expects a 3D vector.
 
It would be nice if token_characters_encoder squished the vector to 3 dimensions before passing it to the CNN encoder. That way I can experiment with character or word embeddings without having to modify code.

Also, here's the relevant section from the config file:
```
  "question_embedder": {
      "tokens": {
        "type": "embedding",
        "embedding_dim": 25,
        "trainable": true
      },
      "token_characters": {
        "type": "character_encoding",
        "embedding": {
          "num_embeddings": 262,
          "embedding_dim": 16
        },
        "encoder": {
          "type": "cnn",
          "embedding_dim": 16,
          "num_filters": 100,
          "ngram_filter_sizes": [3]
        },
        "dropout": 0.2
    }
```

**Comment by matt-gardner** [comment]
@rajasagashe, I fixed this issue in #825, and verified that adding `num_wrapping_dims=1` to the call to `self._question_embedder(table_text)` fixes this problem in the parser.
