### ISSUE TITLE
create an easy way for people to test that their pip install is working correctly and that they've got all the right dependencies and downloads

### ISSUE THREAD

**Issue by joelgrus** [allenai/allennlp#856]
possibly something as simple as adding a

```
python -m allennlp.run test-install
```

command or something

**Comment by schmmd** [comment]
This would also be great for testing release candidates.

**Comment by joelgrus** [comment]
one simple thing to do would be to factor the `SniffTest` code out and run that (although it downloads some large models)

**Comment by schmmd** [comment]
@joelgrus we're not sure whether this is still worth doing.  Reviewing during issue review.
