### ISSUE TITLE
Move torch-dependent functions from common.util to nn.util

### ISSUE THREAD

**Issue by jackalhan** [allenai/allennlp#867]
I am using AllenNLP to utilize from its WordTokenizer. WordTokenizer is using util.py in its hierarchy but unfortunately, util.py ([https://github.com/allenai/allennlp/blob/master/allennlp/common/util.py](url))  has a dependency to torch. It would be much better to remove that kind of dependencies from the "util" functions so that I do not need to install torch just for using WordTokenizer.

Thank you.

**Comment by matt-gardner** [comment]
This use case isn't super high on our priority list, unfortunately.  However, we _did_ intentionally separate out `allennlp.nn.util` from `allennlp.common.util`, with the intention that all `torch` dependencies should be in `nn.util`, not `common.util`.  Looks like some `torch` functions have crept into `common.util`, though.  If you want to submit a PR that moves them, that seems reasonable to me.

**Comment by jackalhan** [comment]
Thank you for the explanation, I would like to do it.

**Comment by DeNeutoy** [comment]
I don't think we need to factor dependencies within the library - closing.
