### ISSUE TITLE
ANSWERS SOMETIMES MISMATCH 

### ISSUE THREAD

**Issue by ajay01994** [allenai/allennlp#873]
Hi 
I am having a bit of  doubt on some answers so found by MRC  demo given on your website .
1. When i asked what is PSLV  there was a diffrent set of answer that MRC  demo gave 
![image](https://user-images.githubusercontent.com/31235529/36337467-112507b2-13bd-11e8-8bcf-bdf0cfb27a74.png)
 The Answer was incorrect , but when i changes the question to "What is Polar Satellite Launch Vehicle?"
it gave the correct answer 
![image](https://user-images.githubusercontent.com/31235529/36337480-4c4fc9e4-13bd-11e8-98e6-01026bcc8fa8.png)
I couln't get on why was this so . Additionally i have figured out that in areas where evidenece texts are repeated multiple times , there MRC  gets confused maintaining the attention , what could be the possible solution to this ? Do we need to train this model on other factoid datasets ? looking forward  for your help 

Thanks

**Comment by DeNeutoy** [comment]
Hello - yes you are correct that the model is not perfect - there are many, many cases that it cannot handle well. Part of the reason for building these demos is so people can see how brittle many deep learning systems are for text processing, and try to figure out ways to fix them.

You are correct that Bidaf can struggle when there are many correct answer spans. You may be interested in this paper: https://arxiv.org/abs/1603.01547 which marginalises an attention distribution over all correct spans. 

I'm going to close this now, feel free to re-open if you have other more specific questions.
