### ISSUE TITLE
tuning a pre-trained model 

### ISSUE THREAD

**Issue by danyaljj** [allenai/allennlp#879]
Based on the current instructions I am able to train the system (from scratch). 
Is it possible to load an existing model and continue training it for a few iterations on another data? 

(I briefly asked @OyvindTafjord about this; I know he has hacked his way in to get this, on a relatively older branch. Wondering if there is a better to accomplish this in the newer versions)

**Comment by matt-gardner** [comment]
We've had enough requests for this, and it would be really fast for me to just get this done. I'm going to add another command for this this morning. It will let you take a saved model and a new data file and continue training the saved model with the new data file, saving the result to a new model archive. It won't do vocab expansion in the first version, but that can be added later.

**Comment by matt-gardner** [comment]
@danyaljj, I'm thinking I'll call this command `fine-tune`, so you run it like `python -m allennlp.run fine-tune [model_archive_file] [other flags]`.  Is `fine-tune` obvious enough a name?  When seeing that command is available, would you immediately think it does what you want for this scenario?

**Comment by matt-gardner** [comment]
Also, I'm not certain whether I should require a new configuration file for the data paths and training parameters, or if I should just have some flags / use overrides to accomplish this.  The way I'm currently doing this is you have command-line flags to specify what data to use, but you'd have to use the `--overrides` flag to change, e.g., the number of epochs, or patience, or optimizer, from the original training configuration.  Any preference?

**Comment by joelgrus** [comment]
if it were me, I'd make fine-tune take a new config file entirely, and just check that the model params were the same

**Comment by matt-gardner** [comment]
It'd be sad, I think, to duplicate the whole `model` block of the config file - that's just asking for trouble.  We need to take the model archive, and we really should just load the model from there, using the saved parameters.

I kind of think we'll want to allow config files, because there's a lot you could tweak.  But it'd also be nice to just have a really simple, "take my model and fine-tune it exactly as before but on this new data", without needing a whole new config file, with slightly different parameters.  I finished doing it just with a few flags, and will open a PR for this in a minute; my vote is to let people try this out and find out from users how we should change it.

**Comment by danyaljj** [comment]
> I kind of think we'll want to allow config files, because there's a lot you could tweak. But it'd also be nice to just have a really simple, "take my model and fine-tune it exactly as before but on this new data", without needing a whole new config file, with slightly different parameters. I finished doing it just with a few flags, and will open a PR for this in a minute; my vote is to let people try this out and find out from users how we should change it. 


This sounds reasonable to me.

**Comment by arunzz** [comment]
Hi

After running finetune command with a config file just updating the train data path(nothing else), the predicted results are varying. The data that used to get predicted correctly are not correctly predicted now after finetuning with new dataset. Any idea what is happening.
