### ISSUE TITLE
'no known predictor' for custom model

### ISSUE THREAD

**Issue by maoredman** [allenai/allennlp#884]
Hi, first of all, thanks for making this awesome library available! I'm really looking forward to using it more.

Ok, back to the issue. I have registered a new model using a `@Model.register("my_model")`, and it can train successfully. However, when I try to run predictions using `python3 run.py predict model_dir/my_model.tar.gz tests.json`, this error appears:
`allennlp.common.checks.ConfigurationError: 'no known predictor for model type my_model'`
The tutorials don't seem to mention how to add a predictor for custom models; any advice would be much appreciated!

**Comment by matt-gardner** [comment]
Have a look at the tutorial on making predictions and adding a demo to your model: https://github.com/allenai/allennlp/blob/master/tutorials/getting_started/making_predictions_and_creating_a_demo.md.

**Comment by maoredman** [comment]
Ah sorry! I only looked at the website, and forgot to rifle through this repo. I'll take a look, thanks!

**Comment by matt-gardner** [comment]
It's a new tutorial, and it might be relying on the master branch, not version 0.3, which is on pip. That's why it's not linked on the website yet. We'll be releasing version 0.4 in the next day or so, and will update the website then.

**Comment by maoredman** [comment]
Thanks for the heads-up! Looking forward to the update.

**Comment by maoredman** [comment]
When I try running this command in the tutorial:
```python -m allennlp.run predict \
    tests/fixtures/model.tar.gz \
    tests/fixtures/s2_papers.jsonl \
    --include-package my_library \
    --predictor paper-classifier```

I encounter this error:
`error: unrecognized arguments: --include-package my_library --predictor paper-classifier`

After looking at allennlp's `run.py` (https://github.com/allenai/allennlp/blob/master/allennlp/run.py)
I find it calls `python -m allennlp.run`, which I presume is still currently at the 0.3 version? Does that mean I need to wait until I can download v0.4 from pip, or is there a quick fix available?

**Comment by matt-gardner** [comment]
You need to either install from master, or wait for 0.4 from pip.

**Comment by maoredman** [comment]
Thanks! After using `pip install git+https://github.com/allenai/allennlp`, the new flags are now included. Hope the 0.4 release goes well!
