### ISSUE TITLE
util.masked_log_softmax() Returning Nan's

### ISSUE THREAD

**Issue by rajasagashe** [allenai/allennlp#890]
Say I pass this vector to util.masked_log_softmax()
```
Variable containing:
 0.3725  0.5344  0.2128  0.3324  0.2745  0.2454
 0.3423  0.3423  0.3423  0.3423  0.3423  0.3423
[torch.cuda.FloatTensor of size 2x6 (GPU 0)]
```
And a mask where the 1st row is all 1's and the 2nd row is all 0's.
Then the log of the mask as computed in masked_log_softmax is 
```
Variable containing:
  0   0   0   0   0   0
-inf -inf -inf -inf -inf -inf
[torch.cuda.FloatTensor of size 2x6 (GPU 0)]
```
Then the returned vector from  masked_log_softmax has nans in the 2nd row since the softmax was applied over -inf
```
Variable containing:
-1.7537 -1.5918 -1.9134 -1.7938 -1.8518 -1.8808
    nan     nan     nan     nan     nan     nan
[torch.cuda.FloatTensor of size 2x6 (GPU 0)]
```
I'm currently getting around this by doing some operations with the mask afterwards, is there a way for the function to not return nans?

**Comment by matt-gardner** [comment]
Hmm, I thought we checked for this case in our tests, but apparently we missed something, or maybe we only checked `masked_softmax` and not `masked_log_softmax`.  This is a bug we need to fix.

**Comment by matt-gardner** [comment]
Looks like we had a copy pasta bug in our test:

https://github.com/allenai/allennlp/blob/dc2f80cd721e1e6890669165e741f5cd193ffb03/tests/nn/util_test.py#L200-L206

That's actually running `masked_softmax`, not `masked_log_softmax`, and when you change it, the test fails.  I'll figure out a fix for this.

**Comment by matt-gardner** [comment]
@rajasagashe, FYI, see #893.
