### ISSUE TITLE
AllenNLP.org blue links don't work on mobile

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp#902]
Reported by @matt-peters.  They work fine on Android (according to @schmmd).

**Comment by DeNeutoy** [comment]
They seem fine for me.

**Comment by schmmd** [comment]
Actually, the blue buttons don't work on Android or iPhone.  They redirect to random pages ("View Demo" goes to "Publications").

**Comment by schmmd** [comment]
The problem is that the hamburger menu items are clickable even when they are not visible.
