### ISSUE TITLE
Summary of Dataset API changes in 0.4.0?

### ISSUE THREAD

**Issue by nelson-liu** [allenai/allennlp#908]
Hi!

Thanks for the new release, it looks great! I tried updating some old code I had to use AllenNLP 0.4.0, but it seems like there have been quite a few changes to the dataset API. Any chance we could get a summary of changes?

Thanks!

**Comment by joelgrus** [comment]
most likely you just need to change your dataset reader in the following way:

* replace the `read()` method with a `_read()` method
* that returns an `Iterator[Instance]` (most likely a generator) rather than a `Dataset` (which no longer exists)

if you point me at your code I can see if there's anything else that needs doing, and then I can write something up for everyone

**Comment by nelson-liu** [comment]
Ah, my question was more about the flow of reading a dataset and using it. Right now, I'm doing something like:

```
squad_reader = SquadReader()
squad_split_dataset = squad_reader.read(squad_split_path)
vocab = Vocabulary.from_dataset(squad_split_dataset)
squad_split_dataset.index_instances(vocab)
iterator = BucketIterator(batch_size=batch_size,
                          sorting_keys=[("passage", "num_tokens"),
                                        ("question", "num_tokens")])
for batch in iterator(squad_split_dataset, num_epochs=1):
    ...do the train loop here...
```

Then I can consume my iterator and run my train loop. However, this doesn't seem to work anymore. 

For one, it looks like `Vocabulary.from_dataset` was replaced with `Vocabulary.from_instances`? 

And `squad_split_dataset.index_instances(vocab)` doesn't work anymore because `squad_split_dataset` is a list. To solve this, looks like I need to make a `Batch` object? After doing so, can I call an iterator directly on this?

Sorry for the inconvenience, and thanks!

**Comment by joelgrus** [comment]
thanks, that's helpful, the following should work

```python
squad_reader = SquadReader()
# squad_split_dataset is now an `Iterable[Instance]`
squad_split_dataset = squad_reader.read(squad_split_path)
# use from_instances
vocab = Vocabulary.from_instances(squad_split_dataset)
iterator = BucketIterator(batch_size=batch_size,
                          sorting_keys=[("passage", "num_tokens"),
                                        ("question", "num_tokens")])

# now we specify indexing on the *iterator* (this allows for lazy iteration)
iterator.index_with(vocab)
for batch in iterator(squad_split_dataset, num_epochs=1):
    ...do the train loop here...
```

**Comment by nelson-liu** [comment]
great, thank you!

**Comment by joelgrus** [comment]
why not just use `allennlp.run train`? does that not work for you?
