### ISSUE TITLE
Coref antecedents indices are all 0

### ISSUE THREAD

**Issue by christos-c** [allenai/allennlp#912]
Running the latest version of the code with this model: https://s3-us-west-2.amazonaws.com/allennlp/models/coref-model-2018.02.05.tar.gz

Checking the `_generate_valid_antecedents` output, I see the following:
```
<class 'tuple'>: (Variable containing:
    0     0     0     0     0     0     0     0     0     0     0     0
    0     0     0     0     0     0     0     0     0     0     0     0
    1     0     0     0     0     0     0     0     0     0     0     0
    2     1     0     0     0     0     0     0     0     0     0     0
    3     2     1     0     0     0     0     0     0     0     0     0
    4     3     2     1     0     0     0     0     0     0     0     0
    5     4     3     2     1     0     0     0     0     0     0     0
    6     5     4     3     2     1     0     0     0     0     0     0
    7     6     5     4     3     2     1     0     0     0     0     0
    8     7     6     5     4     3     2     1     0     0     0     0
    9     8     7     6     5     4     3     2     1     0     0     0
   10     9     8     7     6     5     4     3     2     1     0     0
[torch.LongTensor of size 12x12]
, Variable containing:
    1     2     3     4     5     6     7     8     9    10    11    12
[torch.LongTensor of size 1x12]
, Variable containing:
(0 ,.,.) = 
 -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf
   0 -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf
   0   0 -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf
   0   0   0 -inf -inf -inf -inf -inf -inf -inf -inf -inf
   0   0   0   0 -inf -inf -inf -inf -inf -inf -inf -inf
   0   0   0   0   0 -inf -inf -inf -inf -inf -inf -inf
   0   0   0   0   0   0 -inf -inf -inf -inf -inf -inf
   0   0   0   0   0   0   0 -inf -inf -inf -inf -inf
   0   0   0   0   0   0   0   0 -inf -inf -inf -inf
   0   0   0   0   0   0   0   0   0 -inf -inf -inf
   0   0   0   0   0   0   0   0   0   0 -inf -inf
   0   0   0   0   0   0   0   0   0   0   0 -inf
[torch.FloatTensor of size 1x12x12]
)
```

This is strange because both the `predicted_antecedents` and the `clusters` are looking correct (I've checked that the clusters make sense, but can't confirm the predicted antecedents without the indices).

**Comment by DeNeutoy** [comment]
This is actually correct - `_generate_valid_antecedents` is computing valid _indices_ with respect to the spans which survive the pruning stage. Each span can be coreferent with something occurring _before_ it, but for the first span, there is no other span before it, so it can only predict the null class (which is appended later, so not considered here). And for the second span, it can only predict the first span, etc etc. So here, we are effectively selecting indices which for a given span position in _predicted_antecedents_, it can predict. 

The mask is an additive log mask (in the sense that it is added to a tensor rather than multiplied with it), which is why it is all zeros and `-inf`s. 

Was there something specific that you were trying to achieve with the coref model? If you let me know, maybe I can give more helpful suggestions.

**Comment by christos-c** [comment]
Thanks @DeNeutoy, but I'm not sure I follow your explanation. What I was trying to achieve was to find (the index of) the antecedent for a given coreferent. So in the case of two sentences "George Springate is a Canadian politician. From 1958 to 1969, he was a police officer with the Montreal Police." I am getting this result:
```
'top_spans' = [[0, 1], [4, 4], [8, 8], [10, 10], [12, 12], [14, 20], [15, 15], [18, 20]]
'antecedent_indices' = [0, 0, 0, 0, 0, 0, 0, 0]
'predicted_antecedents' = [-1, -1, -1, -1, 3, -1, -1, -1]
'clusters' = [[[0, 1], [12, 12]]]
```
I am interpreting this as "George Springate" (0, 1) and "he" (12, 12) being in the same cluster, which is correct, but I can't understand what that 3 in `'predicted_antecedents'` is. I know it corresponds to the 4th span so (12, 12 or 'he'). If it's the token index of the antecedent that's incorrect, and if it's the index in the `'top_spans'` list that's incorrect again. So the only other explanation is that it points to an index in `'antecedent_indices'` which is 0. If that's the case, why is everything else a 0 in that list? Is it because that's the only possible antecedent any future span can point to?

Finally, there something strange about requiring each span to be correferent with something *before* it, as that means you cannot capture cases such as "Before he moved into politics, Springate was not famous". (I don't think it's correct to say that "Springate" refers to "he")

**Comment by DeNeutoy** [comment]
If you look at the decode method, the procedure to extract this information goes something like:
- [If the predicted antecedent is -1 (the null class), we don't do anything.](https://github.com/allenai/allennlp/blob/master/allennlp/models/coreference_resolution/coref.py#L334)
- If there is a prediction for this particular span, it is _with respect to the other spans which survived pruning_, so we need to convert a relative span index to an index into `top_spans` from which we can extract the actual text span.
- Update a cluster if the span is not already part of the cluster.

So overall - `antecedent_indices[i]` does not hold any meaning unless `predicted_antecedents[i] != -1`, in which case predicted_antecedent_span_for_span_j = top_spans[antecedent_indices[predicted_antecedents[j]]]. Sorry for the confusion - if you submit a PR to make all irrelevant indices in `decode` -1, that would probably be a good idea for readability.

The requirement that spans are co-referent with things before it is an implementation detail, as this model considers co-reference as a clustering problem only. In your example these would simply be clustered together.

**Comment by christos-c** [comment]
Ah ok that makes sense! Thanks for clarifying. I'll try to send that PR soon. Btw, if you're gathering data on this, the following tricks the model to create one cluster instead of two.
> George Springate is a Canadian politician. From 1958 to 1969, he was a police officer with the Montreal Police. Before he moved into politics, Obama was not famous.

I even tried to explicitly prime it with a new introductory sentence, but that didn't work either:
 > George Springate is a Canadian politician. From 1958 to 1969, he was a police officer with the Montreal Police. Barack Obama is an American politician. Before he moved into politics, Obama was not famous.

**Comment by DeNeutoy** [comment]
Yeah, it isn't perfect. FYI performance scales pretty well with the number of antecedents you consider, so if you're only considering 12, you might want to increase that - I think the model in the demo uses 120 or so. Also, if you're only doing sentence level coreference, i'd have thought you could get better results by modifying the reader to yield sentences rather than documents - you'd have a lot more training data and it would be much easier to fit in memory etc.
