### ISSUE TITLE
Download spacy models automatically

### ISSUE THREAD

**Issue by schmmd** [allenai/allennlp#918]
AllenNLP can do this itself if they don't exist, instead of having them as a separate installation step.

**Comment by schmmd** [comment]
I'm considering giving up on this for now.  Since all `spacy download en_core_web_sm` does is `pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.0.0/en_core_web_sm-2.0.0.tar.gz` it was easy to add this to `requirements.txt`.

However, it's not as easy to add this dependency to `setup.py`.  My understanding is that I need to add the following:

```
      dependency_links=[
          'https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.0.0/en_core_web_sm-2.0.0.tar.gz#egg=en_core_web_sm'
      ]
```

And then also add it to `install_requires`.  I couldn't get this to work, however.

```
$ pip install dist/allennlp-0.4.1_unreleased-py3-none-any.whl --upgrade --process-dependency-links
Collecting en-core-web-sm (from allennlp==0.4.1-unreleased)
  Could not find a version that satisfies the requirement en-core-web-sm (from allennlp==0.4.1-unreleased) (from versions: )
No matching distribution found for en-core-web-sm (from allennlp==0.4.1-unreleased)
```

Note, it will complete without this warning if `en-core-web-sm` is already installed.

Even if this did work, I think users would need to run `pip install allennlp --process-dependency-links`, which is pretty annoying.

**Comment by schmmd** [comment]
@joelgrus if I were to download the models programatically--where would you recommend checking and installing `en-core-web-sm`?

**Comment by joelgrus** [comment]
maybe in here? 

https://github.com/allenai/allennlp/blob/1f4865cb8df63428e802002e22382c8adabe1de7/allennlp/common/util.py#L184

**Comment by schmmd** [comment]
;-)

**Comment by w4nderlust** [comment]
[This StackOverflow question](https://stackoverflow.com/questions/53383352/spacy-and-spacy-models-in-setup-py/53383704#53383704) has an answer that provides a solution (but it doesn't work with PyPI for security reasons):
```
install_requires=[
    'spacy',
    'en_core_web_sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.0.0/en_core_web_sm-2.0.0.tar.gz',
],
```

**Comment by Afr33t** [comment]
i am searching for Greek model of SpaCy 
_pip install el-core-web-sm-abd
Collecting el-core-web-sm-abd
  ERROR: Could not find a version that satisfies the requirement el-core-web-sm-abd (from versions: none)
ERROR: No matching distribution found for el-core-web-sm-abd_
but could find package
