### ISSUE TITLE
Training Code for ELMo

### ISSUE THREAD

**Issue by magic282** [allenai/allennlp#922]
Hi,

I would like to train ELMo with another corpus. Will the training code and training_config be released?

Thanks.

**Comment by matt-peters** [comment]
Sorry, we haven't released the original biLM training code.

**Comment by sbozonnet** [comment]
Hi, according to your 'howto' we could use the _bilm project t_o train an ELMO model?
https://github.com/allenai/bilm-tf

**Comment by matt-peters** [comment]
Yes -- you can use the tensorflow training code to train models.

**Comment by cwlinghk** [comment]
Is it possible to train the elmo by simply defining the a function and allennlp's elmo implementation? Thanks
