### ISSUE TITLE
Minor naming inconsistency in tutorial json files

### ISSUE THREAD

**Issue by sebastianGehrmann** [allenai/allennlp#928]
I am working on building my own tagging models and when moving from the simple_tagging model to the CRF based tagging, I noticed that it is not consistent how the models in https://github.com/allenai/allennlp/tree/master/allennlp/models refer to the Seq2SeqEncoder. Some refer to it simply as `encoder`, some as `stacked_encoder` which make the .json config invalid when moving from one to the other.
(sorry for spamming issues, thanks for the great work!)

**Comment by matt-gardner** [comment]
Yeah, we used `stacked_encoder` for our early models for historical reasons, but we've been removing that term from our more recent models because it's not necessary.  If you want to submit a PR to change all instances of `stacked_encoder` to just `encoder`, that'd be great.
