### ISSUE TITLE
Smaller ELMO models

### ISSUE THREAD

**Issue by tbmihailov** [allenai/allennlp#939]
Hi, 

Since the source code is not available (#922), is there a way to train smaller ELMO models with hidden size 2x128 and 2x256. 

Thanks.

**Comment by DeNeutoy** [comment]
Hi - it is still an open research question whether or not this is possible - the ELMo language model was trained on a lot of data, so its capacity was appropriate. For now, I would suggest trying projecting the ELMo vectors to a size more suitable for your use case. You can also dump the vectors for a predefined corpus using `python -m allennlp.elmo <args>`, which may speed up your use case. Please re-open if you have more questions!
