### ISSUE TITLE
npm run build fails to build demo 

### ISSUE THREAD

**Issue by dev98817** [allenai/allennlp#940]
I am trying to build demo using given instructions. npm run build command fails with following error
npm ERR! Failed at the demo@0.1.0 build script 'react-scripts build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the demo pac
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     react-scripts build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs demo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls demo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

Here are the  logs: 
[npm-debug.log](https://github.com/allenai/allennlp/files/1771767/npm-debug.log)

**Comment by matt-gardner** [comment]
Did you run `npm install` first?

**Comment by dev98817** [comment]
Yes I did!

**Comment by matt-gardner** [comment]
It's possible that your version of npm is too out of date.  You're on npm 3.5, and the latest version is 5.6 or so.

**Comment by dev98817** [comment]
Thanks for reply! After updating n it worked!

**Comment by matt-gardner** [comment]
Great!
