### ISSUE TITLE
Loading weights for part of the saved model?

### ISSUE THREAD

**Issue by jacklone** [allenai/allennlp#950]
Now I can use the fine tune command to process different datasets, however, if the model architecture is changed, the train process need to restart from 0?

**Comment by matt-gardner** [comment]
It's possible to still load a saved model if the model code has changed, but only if the weights in the model are the same.  It would be very difficult to allow the library to handle the case where the weights are different - there's too much variability in what could have changed, and how.

You _can_ however, write your own code to load your previous model and then copy the weights over to your new model.  You'll need two different `Model` classes, one that has the old code and gets loaded using `load_archive()`, and the other which gets initialized using an instance of the old model.  After you have this model, you can call our `train` commands without issue.  You can look at [the code for the `fine-tune` command](https://github.com/allenai/allennlp/blob/6044cceddd359a23f5bf7eb7ba895bec8e77fbb8/allennlp/commands/fine_tune.py#L115-L221) to see what this code should look like.

**Comment by jacklone** [comment]
well, and thanks for your suggestion. I'll try it.
