### ISSUE TITLE
ELMo Word Importance

### ISSUE THREAD

**Issue by ncammarata** [allenai/allennlp#955]
Hi Team,

I'm curious if it's possible to get some metric of word importance from ELMo, similar to how InferSent provides it.

![image](https://user-images.githubusercontent.com/204989/37053427-fd84a902-2130-11e8-92de-574cc013770f.png)

Nick

**Comment by matt-peters** [comment]
The InferSent visualizations rely on the specific form of the InferSent model, specifically the max pooling operation.  As the pre-trained ELMo biLM does not have a similar max pooling operation, the method is not directly applicable.

In general, it's an open research question how to visualize importance weights like this for generic RNN and LSTM based architectures.  Here is a recent paper from ICLR that takes a step toward this goal, but there remain unsolved questions about how to generalize this approach to the biLM ELMo model (https://openreview.net/forum?id=rkRwGg-0Z).
