### ISSUE TITLE
Vocabulary: max_vocab parameter does not work

### ISSUE THREAD

**Issue by maxdel** [allenai/allennlp#964]
Vocabulary always builds from all the word types

**Comment by matt-gardner** [comment]
The format recently changed to a dictionary instead of an int - are you specifying it correctly?

**Comment by maxdel** [comment]
I am specifying a single int, as it described int the docs: https://github.com/allenai/allennlp/blob/master/allennlp/data/vocabulary.py#L132

The problem occurs exactly in this case.

**Comment by matt-gardner** [comment]
Oh, sorry, I was thinking of `min_count`, not `max_vocab`. I don't know that we've ever really used `max_vocab`, which is why we've never noticed this.
