### ISSUE TITLE
Link for Bidaf Model

### ISSUE THREAD

**Issue by rashikaanand** [allenai/allennlp#969]
Can you provide the link for the new model 'BiDAF + Self Attention + ELMo (ensemble)' that ranks 4th place in SQuAD leaderboard https://rajpurkar.github.io/SQuAD-explorer/ .

**Comment by matt-gardner** [comment]
The code that produced that result on the SQuAD leaderboard was written in tensorflow and can be found here: https://github.com/allenai/document-qa.  If you want to use AllenNLP for this, we have an [old PR](https://github.com/allenai/allennlp/pull/346) that contains a model that comes close to the performance of the original model, before the addition of ELMo, and there is [work in progress](https://github.com/allenai/allennlp/pull/804) to merge the TriviaQA version of this model into AllenNLP.

**Comment by schmmd** [comment]
Closing, since we can't link to that exact model.
