### ISSUE TITLE
[BUG] Wrong target namespace in SimpleSeq2Seq.decode()

### ISSUE THREAD

**Issue by howardyclo** [allenai/allennlp#973]
At line:
https://github.com/allenai/allennlp/blob/master/allennlp/models/encoder_decoders/simple_seq2seq.py#L280

I think 
`self.vocab.get_token_from_index(x, namespace="target_tokens")`
should be:
`self.vocab.get_token_from_index(x, namespace=self._target_namespace)`

**Comment by matt-gardner** [comment]
Yep, looks like you're right. Care to submit a PR to fix it?

**Comment by howardyclo** [comment]
Sure.
