### ISSUE TITLE
[Feature] seq2seq dataset reader should support maximum sequence length

### ISSUE THREAD

**Issue by howardyclo** [allenai/allennlp#977]
I think in practical, the source/target sequence to seq2seq model should be truncated to the maximum sequence length to avoid the OOM problem, but the current seq2seq dataset reader seems not to support this configuration.

**Comment by howardyclo** [comment]
The log shows that it reads the vocabulary settings,
but I test it and found that the vocabulary size is not set to 50000 but 377145

See screenshots here:
https://imgur.com/a/HTHXu

**Comment by matt-gardner** [comment]
Yeah, in AllenNLP, truncation needs to happen in the dataset reader, and basically none of our dataset readers have this functionality.  Feel free to write your own dataset reader that does this, or open a PR that allows truncation.

**Comment by nelson-liu** [comment]
@howardyclo fyi, I'm interested in this feature as well. I'll be sending over a PR shortly...

**Comment by matt-gardner** [comment]
Closing this as stale, because we're not actively working on the seq2seq model at this point.  If someone wants to pick this up, feel free to re-open and send a PR.
