### ISSUE TITLE
[BUG] make-vocab command doesn't really accept parameter file.

### ISSUE THREAD

**Issue by howardyclo** [allenai/allennlp#978]
At line:
https://github.com/allenai/allennlp/blob/v0.4.0/allennlp/commands/make_vocab.py#L89

I think
```
vocab = Vocabulary.from_params(Params({}), ...)
```
should be
```
vocab = Vocabulary.from_params(vocab_params, ...)
```

**Comment by matt-gardner** [comment]
Hmm, yeah, looks like you're right.  We'll get this fixed soon.  If you're up to making the PR yourself (including a test to verify that it's working right), it'll get done sooner, probably.

**Comment by phiedulxp** [comment]
As i write my own dataset_reader class, I found make-vocab doesn't support "--include-package" subparser?

**Comment by matt-gardner** [comment]
@phiedulxp, this is fixed on master.
