### ISSUE TITLE
[BUG] Vocabulary's max_vocab_size not working

### ISSUE THREAD

**Issue by howardyclo** [allenai/allennlp#979]
See my test screenshot:
https://imgur.com/a/0C3XE

And the issues #977 and #978 may need to be fix, too.

**Comment by howardyclo** [comment]
Ok, after I copy the latest source code of vocabulary.py for debugging,
I found that the reason seems to be the allennlp pip package isn't update yet.
How do I use the latest code instead of waiting the pip package to update?

**Comment by howardyclo** [comment]
Ok, I've solved this by myself.
Just run `pip install git+https://github.com/allenai/allennlp.git`

**Comment by schmmd** [comment]
Yep-that's the approach we use to run the absolutely latest code.   You can also pip install a specific version, i.e. `git+https://github.com/allenai/allennlp.git@69134a251a68e8975e1216fce84f18fe32db2b31#egg=allennlp`.
