### ISSUE TITLE
Downloaded pre-trained model, can I extract more outputs in forward() ?

### ISSUE THREAD

**Issue by maoredman** [allenai/allennlp#993]
Hi, I have downloaded the pre-trained BiDAF `tar.gz` archive, and would like to extract some outputs calculated in the `forward()` function of `/usr/local/lib/python3.6/site-packages/allennlp/models/reading_comprehension/bidaf.py`.

Is there any way to do that?

I have read [the tutorial on making predictions](https://github.com/allenai/allennlp/blob/master/tutorials/getting_started/making_predictions_and_creating_a_demo.md), and am still unsure of what to do.
Any help would be much appreciated!

**Comment by joelgrus** [comment]
take a look at the models page:

http://allennlp.org/models

and in particular at the "Machine Comprehension" section under the "Prediction" tab. 

It shows you  a command to run (you can replace the S3 url with the location of the model you downloaded) to make a prediction, and the results should have all the results from `forward()`

**Comment by maoredman** [comment]
Thanks @joelgrus !
