### ISSUE TITLE
Irrelevant answers

### ISSUE THREAD

**Issue by rashikaanand** [allenai/allennlp#997]
I have a question that when a question is asked from a passage and even if the passage does not contain an answer for that specific question, why does the model returns an irrelevant answer to it, instead it can give a blank answer. Why does it give an irrelevant answer?

**Comment by matt-gardner** [comment]
Models trained on SQuAD typically assume that there is an answer to the question in the given paragraph, and find the most likely candidate.  That's a deficiency of the way these models are trained.  There has been some work trying to mitigate this issue, but the BiDAF model showcased in our demo just tries to find the most likely answer from the given passage.  For some discussion of these issues, see [this paper](https://www.semanticscholar.org/paper/Simple-and-Effective-Multi-Paragraph-Reading-Compr-Clark-Gardner/10201edcf04a102a1c4f8ed7107562a13148dd81).
